### ISSUE TITLE
Memory Leak when create DeviceArray in python loop(without JIT)?

### ISSUE THREAD

**Issue by YouJiacheng** [google/jax#10007]
(maybe) related issues:
#9714 
#9970 
```python
import gc
import os
import psutil

import jax

print(jax.__version__)
print(jax.default_backend())
for _ in range(5):
    A = jax.numpy.ones(1000 ** 2)
    gc.collect()
    bs = jax.lib.xla_bridge.get_backend().live_buffers()
    
    if jax.default_backend() == 'cpu':
        print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    print('-----', len(bs))
    for b in bs:
        print(b.size)
```
On GPU:
```python
0.3.4
gpu
----- 1
1000000
----- 2
1000000
1000000
----- 3
1000000
1000000
1000000
----- 4
1000000
1000000
1000000
1000000
----- 5
1000000
1000000
1000000
1000000
1000000
```
On CPU:
```python
0.3.4
2022-03-23 14:09:26.021477: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
cpu
229.5
----- 1
1000000
233.34765625
----- 2
1000000
1000000
237.15234375
----- 3
1000000
1000000
1000000
241.0078125
----- 4
1000000
1000000
1000000
1000000
244.5546875
----- 5
1000000
1000000
1000000
1000000
1000000
```
If I use `A = jax.numpy.ones(1000 ** 3)`, it will run into OOM in 4 iterations on a 16G V100.

**Comment by YouJiacheng** [comment]
If I explicitly delete reference, there will be no memory leak
```python
import os
import psutil

import jax

print(jax.__version__)
print(jax.default_backend())
for _ in range(5):
    A = jax.numpy.ones(1000 ** 2)
    del A
    bs = jax.lib.xla_bridge.get_backend().live_buffers()
    
    if jax.default_backend() == 'cpu':
        print(psutil.Process(os.getpid()).memory_info().rss / 1024 ** 2)
    print('-----', len(bs))
    for b in bs:
        print(b.size)
```
However, IIUC python assignment semantic, rebind an already bound name to another value should decrease reference count for the object previously bound to the name.

**Comment by wookayin** [comment]
@YouJiacheng Could you maybe leave this issue opened? Because I think this is still a present bug of JAX. I'm curious what references those DeviceArray instances. I as well will try troubleshoothing this in my next free cycle.

**Comment by jakevdp** [comment]
Sorry, I missed this the first time around. I think your assessment in the edited comment is correct: `bs` holds references to the live buffers, meaning that when the name is re-bound they do not have their reference count reduced to zero.

Note also that in Python `del X` does not guarantee that the memory associated wtih `X` will be deleted; if there are no other references to `X`, the refcount will go to zero, but it won't actually be deleted until the garbage collector runs. You can force garbage collection by running `import gc; gc.collect()`

**Comment by YouJiacheng** [comment]
IIUC, in Python we need `gc` only when there are cyclic references, i.e. the reference count never reduced to zero. Reference counting in Python is just like `shared_ptr` in c++.
