### ISSUE TITLE
DOC: jax.scipy.sparse.linalg.cg / bicgstab / gmres parameter x0 type should be (array or tree of arrays)

### ISSUE THREAD

**Issue by YouJiacheng** [google/jax#10006]
parameter `b` and  return `x` have type (array or tree of arrays), and the implementations support tree as well.
However, the description of parameter `x0` is:
> x0 (array) – Starting guess for the solution. Must have the same structure as b.

BTW, `bicgstab` in fact allows array type `A` since it uses `_isolve`. But document says:
> A (function) – Function that calculates the matrix-vector product Ax when called like A(x). A can represent any general (nonsymmetric) linear operator, and must return array(s) with the same structure and shape as its argument.

**Comment by jakevdp** [comment]
Thanks for bringing this up - it should be addressed in https://github.com/google/jax/pull/10010
