### ISSUE TITLE
`host_callback.call(..., call_with_device=True)` specifies the wrong device

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#10082]
I *think* the issue is `host_callback.call`, but I suppose it might be something else I haven't clocked.

On a machine with 4x GPUs, this script:
```python
import jax
import jax.numpy as jnp
import jax.experimental.host_callback as hcb

def _print_device(_, device):
    print(device)

@jax.jit
def print_device(x):
    hcb.call(_print_device, x, call_with_device=True)

cpu = jax.devices("cpu")[0]
gpu = jax.devices("gpu")[0]
a = jax.device_put(jnp.array(1), cpu)
b = jax.device_put(jnp.array(1), gpu)
print_device(a)
print_device(b)
```
prints:
```
gpu:0
gpu:0
```

Expected behaviour:
```
TFRT_CPU_0
gpu:0
```

This seems to happen with or without the `jax.jit`.

**Comment by gnecula** [comment]
Thanks for the bug report, I will look into this. It does cross my mind that perhaps the bug is elsewhere, i.e., the function runs  on GPU even though the data is on the CPU.

One thing I would do is to make the print_device return `x` and then inspect the returned value to see on what device it lives. Try `data._device` or `data.device_buffer`.

**Comment by patrick-kidger** [comment]
Looks like that bit's fine:

```python
import jax
import jax.numpy as jnp
import jax.experimental.host_callback as hcb

def _print_device(_, device):
    print(device)

@jax.jit
def print_device(x):
    hcb.call(_print_device, x, call_with_device=True)
    return x

cpu = jax.devices("cpu")[0]
gpu = jax.devices("gpu")[0]
a = jax.device_put(jnp.array(1), cpu)
b = jax.device_put(jnp.array(1), gpu)
c = print_device(a).block_until_ready()
d = print_device(b).block_until_ready()
print(c.device())
print(d.device())
```

```
gpu:0
gpu:0
TFRT_CPU_0
gpu:0
```

**Comment by gnecula** [comment]
I just tried it on an internal Google test machine, with both GPU and TPU and I get the expected results.

One idea is for you to read the end of the [Debugging section](https://jax.readthedocs.io/en/latest/jax.experimental.host_callback.html#low-level-details-and-debugging) and try to run the code with the tracing turned on, and see if you can tell of the computation is running on GPU or not and what it is doing.

**Comment by patrick-kidger** [comment]
I'm afraid I don't really need this functionality myself -- I was just flagging up that it existed -- so I'm probably unlikely to get around to digging into the details of this.

**Comment by patrick-kidger** [comment]
Closing as `host_callback` is deprecated.
