### ISSUE TITLE
eval_shape(pjit(f)) doesn't match pjit(f).shape with GlobalDeviceArray in multi-host settings

### ISSUE THREAD

**Issue by georgevdd** [google/jax#10084]
## Steps to reproduce:

```python
import functools

from absl import app
import jax
from jax.experimental import maps
from jax.experimental.pjit import PartitionSpec
from jax.experimental.pjit import pjit
import numpy as np


jax.config.update('jax_parallel_functions_output_gda', True)


@functools.partial(
    pjit,
    in_axis_resources=(),
    out_axis_resources=PartitionSpec('x'),
)
def f():
  return jax.numpy.zeros([32, 10])


def main(argv):
  del argv  # Unused
  with maps.Mesh(np.asarray(jax.devices()), axis_names=['x']):
    print(f().shape)
    print(jax.eval_shape(f))

if __name__ == '__main__':
  app.run(main)
```

## Expected output:
```
(32, 10)
ShapeDtypeStruct(shape=(32, 10), dtype=float32)
```

## Observed output:
```
(32, 10)
ShapeDtypeStruct(shape=(16, 10), dtype=float32)
```

More generally, it would be nice if `eval_shape()` could recognise `GlobalDeviceArray` and produce a subtype of `ShapeDtypeStruct` conveying not just global shape but also the shard index and replica information derived from the corresponding `PartitionSpec`. Otherwise it is currently very hard to work out what shape a `GlobalDeviceArray` is going to have and what shape its shards will have.

**Comment by yashk2810** [comment]
Thanks for the bug! I am looking into it.

> it is currently very hard to work out what shape a GlobalDeviceArray is going to have and what shape its shards will have.
For this to unblock you, you can use https://github.com/google/jax/blob/main/jax/experimental/global_device_array.py#L86-L89. That is also a no-flop calculation.

**Comment by georgevdd** [comment]
Thank you for the suggestion about `get_shard_indices_replica_ids()`. But that still requires duplicating the logic that works out which `PartitionSpec` applies to each leaf of the tree, and then applying it to give the mesh axes.
