### ISSUE TITLE
unsigned int behaviour retains negative indices fix

### ISSUE THREAD

**Issue by oliverdutton** [google/jax#10142]
I was trying to avoid the extra cost of the `add` and `select_n` thats present in promise_in_bounds, clip and fill so I went to `u32`. Looking at the jaxpr it does the compare still and then converts to `i32`. This seems wrong.

This relates to https://github.com/google/jax/issues/10063, I would also be okay with the approach 'unsigned should not exist' and add a mode for 'promise_in_bounds_positive'.

```python
import jax
import jax.numpy as jnp
indices = jnp.array([0,3,4]).astype('uint32')
x = jnp.arange(5)
print(jax.make_jaxpr(x.__getitem__)(indices))

# Output:
{ lambda a:i32[5]; b:u32[3]. let
    c:bool[3] = lt b 0
    d:u32[3] = add b 5
    e:u32[3] = select_n c b d
    f:i32[3] = convert_element_type[new_dtype=int32 weak_type=False] e
    g:i32[3,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(3, 1)] f
    h:i32[3] = gather[
      dimension_numbers=GatherDimensionNumbers(offset_dims=(), collapsed_slice_dims=(0,), start_index_map=(0,))
      fill_value=None
      indices_are_sorted=False
      mode=GatherScatterMode.PROMISE_IN_BOUNDS
      slice_sizes=(1,)
      unique_indices=False
    ] a g
  in (h,) }
```

**Comment by oliverdutton** [comment]
There’s two things:
1 - Negative index catching
2 - Conversion to i32 for gather 

Even when (1) is removed you still will pay a performance penalty for (2). Given JAX already has special int rules for out of bounds indexing the encoding of even more rules as an extra dtype u32 means you now have to deal with both dtype and bounds mode cases. Adding an extra mode solves both things and keeps the whole conversation related to just gather mode not dtype too.

**Comment by jakevdp** [comment]
We could probably avoid conversion to signed int as well, though there are some corner cases that need to be handled.

I don't think this needs an extra mode to account for this.

**Comment by oliverdutton** [comment]
Original issue closed. The idea of an unsigned int accepting gather would be a separate issue which I don’t intend to file.

Thank you.
