### ISSUE TITLE
Element type C128 is not supported on TPU

### ISSUE THREAD

**Issue by Danc2050** [google/jax#10158]
FFT appears to always throw an error and print out the stack trace when computed on an array of `float64` dtype. This code was run on a V3 TPU VM, supported by the TRC program:
```
import jax
import jax.numpy as jnp
jax.config.update("jax_enable_x64", True)
x = jax.numpy.array([1, 2, 3, 4], dtype=jax.numpy.float64)
y = jnp.fft.fft(x)
```
and produces this error report: [ElementTypeC128NotSupported.txt](https://github.com/google/jax/files/8403476/ElementTypeC128NotSupported.txt).

**Comment by hawkinsp** [comment]
This is working as intended, I think. TPUs don't have float64 hardware, so at best a complex128 FFT would be emulated using float32 double-double math. I suspect that will not go well for something as complicated as an FFT — you would do much better to perform such calculations on CPU or GPU.
