### ISSUE TITLE
Odd error with int32 nd.array shapes and random generators.

### ISSUE THREAD

**Issue by SiegeLordEx** [google/jax#1016]
```python
key = jax.random.PRNGKey(0)
print(jax.random.normal(key, shape=[2]))
print(jax.random.normal(key, shape=np.array([2], np.int32)))
```
```
jax/random.py in _random_bits(key, bit_width, shape)
    206   if max_count >= onp.iinfo(onp.uint32).max:
    207     # TODO(mattjj): just split the key here
--> 208     raise TypeError("requesting more random bits than a single call provides.")
    209 
    210   counts = lax.tie_in(key, lax.iota(onp.uint32, max_count))

TypeError: requesting more random bits than a single call provides.
```

Now I think this is completely my mistake, as presumably shape must always be a Python tuple (it's documented as such). Digging into it a tiny bit, I believe it happens because `onp.iinfo(onp.uint32).max` gets coerced to `np.int32` and overflows to a negative number. If I remove the check, everything seems to go fine, but perhaps it's an accident that it works with `nd.array` shapes.

**Comment by dynamicwebpaige** [comment]
Unable to reproduce; got the following as output:

```python
[-0.78476596  0.85644484]
[-0.78476596  0.85644484]
```

Please feel free to reopen, if I'm mistaken! 🙂
