### ISSUE TITLE
Expose optimization path of L-BFGS optimizer

### ISSUE THREAD

**Issue by miclegr** [google/jax#10243]
Algorithms such as Pathfinder ([paper](https://arxiv.org/abs/2108.03782), blackjax-devs/blackjax#157) need as input all the optimization path, and not only the result, of a L-BFGS optimization run. 
Differently from R (and consistently with scipy) jax's `jax._src.scipy.optimize._lbfgs._minimize_lbfgs`  does not expose the path, but just the result. A generalization of such fuction that expose the optimization path would look like [this](https://github.com/miclegr/blackjax/blob/pathfinder/blackjax/vi/pathfinder.py#L217-L394) and would allow to implement Pathfinder without rewriting a jax internal function and keeping it in sync with jax main branch over time.

Happy to submit a proper pull request if such feature would be considered for merging.

**Comment by froystig** [comment]
We are looking to deprecate `jax.scipy.minimize` and recommend [JAXopt](https://github.com/google/jaxopt/) instead, so I'd bring @mblondel into this thread (and perhaps eventually we should move the discussion to the jaxopt repository).

**Comment by mblondel** [comment]
JAXopt allows you to do this by repeatedly calling `solver.update` in your own for loop instead of calling `solver.run`.

**Comment by miclegr** [comment]
Thanks! That solves the problem, appreciated 👍
