### ISSUE TITLE
`jax.numpy.mean` does not work with native Python array

### ISSUE THREAD

**Issue by ToruOwO** [google/jax#1029]
`jax.numpy.mean` does not work with native Python array, which is different from what the documentation states. Also, other APIs like `jax.numpy.sum` do indeed work with native Python array.

Code to reproduce error:
```
import jax.numpy as jnp

a = [1, 2, 3]
jnp.mean(a)
```

Error message:

> <ipython-input-18-5e8b1f13b2f1> in <module>()
>       1 a = [[1, 2, 3]]
> ----> 2 jnp.mean(a)
> 
> google3/third_party/py/jax/numpy/lax_numpy.py in mean(a, axis, dtype, out, keepdims)
>    1008     normalizer = onp.prod(onp.take(shape(a), axis))
>    1009   if dtype is None:
> -> 1010     if (onp.issubdtype(_dtype(a), onp.bool_) or
>    1011         onp.issubdtype(_dtype(a), onp.integer)):
>    1012       dtype = xla_bridge.canonicalize_dtype(onp.float64)
> 
> TypeError: data type not understood

The root cause of this is lax.dtype, which uses numpy.result_type (https://docs.scipy.org/doc/numpy/reference/generated/numpy.result_type.html), and numpy.result_type only takes in "list of arrays and dtypes" as argument.

**Comment by clemisch** [comment]
I think it's always better to explicitely cast lists, tuples etc. to arrays via `np.array`. In your case this would be 

```python
import jax.numpy as jnp

a = [1, 2, 3]
jnp.mean(jnp.array(a))
```

**Comment by mattjj** [comment]
If I understand correctly, I think this is working as intended. Along the lines of what @clemisch suggests, in [the "What's supported" section of the README](https://github.com/google/jax#whats-supported) it says

> NumPy also does a lot of work to cast any array-like function arguments to arrays, as in np.sum([x, y]), while jax.numpy typically requires explicit casting of array arguments, like np.sum(np.array([x, y]))

there are also brief mentions under the TLDR "Don't use" heading. Maybe we should add it to the [Current gotchas](https://github.com/google/jax#current-gotchas) section too. (In general, the README needs to be split up into multiple files so it's easier to find stuff...)

If some other part of the docs contradict that, we should fix it! If you've spotted some, can you point them out?

We might be able to do a bit more automatic promotion to arrays in some parts of jax.numpy, but that kind of polymorphism seems like a big source of complexity in other systems (some TFP folks have explained that to us) and could even lead to performance surprises. At the same time it seems like most user code isn't burdened very much by requiring explicit ndarray creation from things like Python lists, so long as JAX's policy is as clear as possible in the documentation.

WDYT? How annoying is it to promote to an array manually? (Doc improvement PRs are especially welcome!)

**Comment by ToruOwO** [comment]
I see, thanks (and sorry for the late response)! With the documentation above this makes sense. It's inconsistent with the API doc though, which I think is pulled directly from numpy API's doc (and therefore the inconsistency).

https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.mean.html?highlight=mean

**Comment by hawkinsp** [comment]
To add another vote for implicit promotion here: a colleague came to me with exactly the same issue on Friday (passing a Python list to `np.mean` didn't work).
