### ISSUE TITLE
DeviceArray from/to GPU memory pointer

### ISSUE THREAD

**Issue by clemisch** [google/jax#1031]
Is it possible to 

1. construct a DeviceArray from a pointer to GPU memory (obatined from another tool within the same Python process)?
2. obtain the pointer from an existing DeviceArray and pass it to another tool within the same Python process?

--- 

The "tool" in my case is the [Reconstruction Toolkit](https://www.openrtk.org/) for CT reconstruction. It contains projectors working on GPU with CUDA and exposes the pointers to the GPU memory.

**Comment by christopherhesse** [comment]
You should check out my issue which involves GPU pointers: https://github.com/google/jax/issues/1009

**Comment by clemisch** [comment]
Implemented in recent [XLA/TF commit](https://github.com/tensorflow/tensorflow/commit/f7154b226b1c01cf805cf0949801f4b6b6388f93): `.unsafe_buffer_pointer()`

Related [JAX issue](https://github.com/google/jax/issues/1009#issuecomment-513769748).
