### ISSUE TITLE
Cannot change `jax_platform_name` on the fly

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#10320]
I am using `jax.config.update('jax_platform_name', 'cpu')` to change the device placement.

```python
import jax
import jax.numpy as np
a = np.zeros((128, 128))
print(a.device())  # TPU
jax.config.update('jax_platform_name', 'cpu')
a = np.zeros((128, 128))
print(a.device())  # TPU, expected CPU
```

Related: #8879

**Comment by hawkinsp** [comment]
`jax_platform_name` isn't intended to be set at run time. I suspect what you actually want to control is the default device placement, for which @skye was adding a context-manager-like API.

(I don't believe it landed yet, though.)

**Comment by mattjj** [comment]
@skye did https://github.com/google/jax/pull/9118 fix this?

**Comment by skye** [comment]
Yes, you should be able to use `jax.default_device` to do this more safely. It doesn't support a platform name (yet?), so you have to use: `with jax.default_device(jax.devices("cpu")[0])`

**Comment by mattjj** [comment]
Let's consider this solved! [Docs on `jax.default_device` here](https://jax.readthedocs.io/en/latest/_autosummary/jax.default_device.html).

**Comment by theovincent** [comment]
@skye Hi, I am very interested by the feature you developped. I am still struggling to use it. Would you mind explaining how it works please?

Here is the behavior I don't understand:
```Python
import jax

print(jax.numpy.ones(3).device())
jax.default_device(jax.devices("cpu")[0])
print(jax.numpy.ones(3).device()) 
```
Output
```Bash
gpu:0
gpu:0
```
I would expect:
```Bash
gpu:0
TFRT_CPU_0
```

I am using jax==0.3.22 and jaxlib==0.3.22+cuda11.cudnn82.
Using __device_put__ the behavior is the one that I expect:
```Python
import jax

a = jax.numpy.ones(3)
print(a.device())
a = jax.device_put(a, jax.devices("cpu")[0])
print(a.device())
```
Output
```Bash
gpu:0
TFRT_CPU_0
```

**Comment by theovincent** [comment]
@ayaka14732 Amazing, thanks :)
