### ISSUE TITLE
AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice'

### ISSUE THREAD

**Issue by kinalmehta** [google/jax#10331]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

Code:
```python
import jax
import jaxlib
import jaxlib.xla_extension as xe

jax.random.PRNGKey(0)
print(jax.devices())
print(xe.CpuDevice)
```

- [x] If applicable, include full error messages/tracebacks.

Output:
```sh
[GpuDevice(id=0, process_index=0)]
Traceback (most recent call last):
  File "~/jax/1_installation_test.py", line 8, in <module>
    print(xe.CpuDevice)
AttributeError: module 'jaxlib.xla_extension' has no attribute 'CpuDevice'
```

Environment details:
- Fedora 35 with cuda 11.6, cudnn 8.4
- jax 0.3.7
- jaxlib 0.3.7+cuda11.cudnn82
- python 3.9

**Comment by ozencgungor** [comment]
I just ran into the exact same error.



Environment details:

    cuda 11.2, cudnn 8.1
    jax 0.3.7
    jaxlib 0.3.7+cuda11.cudnn82
    python 3.8.6

Just updated from jax/jaxlib 0.3.6 to 0.3.7, took care to install the right cuda and cudnn version. I'm guessing it has something to do with v0.3.7.

Hoping it gets solved quickly.

**Comment by YouJiacheng** [comment]
CpuDevice class has been removed, I can't find out which commit removed it, but https://github.com/google/jax/pull/10326 said it was removed.

**Comment by tomhennigan** [comment]
We removed this in tensorflow/tensorflow@ea8611b. I hope to remove `{G,T}puDevice` too, but we need to find a generic way to allow devices to have custom attributes (such as `GpuDevice.device_vendor`).

The only user I could find was Chex and at least internally no one was actually using the symbol so we removed it from there too (deepmind/chex@7552dfc). I suspect if you are seeing this error that it is coming from `import chex` (which imports JAX and makes an alias to this symbol).

As noted in deepmind/chex#156 we need to make a new Chex release to incorporate these changes, this won't happen until tomorrow at the earliest (it is a bank holiday in the UK where the majority of Chex authors are) so for now either stick to jax/jaxlib v0.3.6 or install chex from head (`pip install git+git://github.com/deepmind/chex.git`).

**Comment by kinalmehta** [comment]
Yes, This error was caused by chex. I reverted to jax 0.3.2 and everything seemed to work. Will wait for the next chex update.

Thanks for the support. Closing this issue as all the questions seems to be answered.

Thanks a lot again everyone. :D

**Comment by mblondel** [comment]
I ran into the same issue and solved it by `pip install chex --upgrade`.

**Comment by gmacgmac** [comment]
I found other info on Github and solved with following
-- GENERAL SYSTEM --
> NOT LEAN VERSIONS <
```
CUDA Toolkit: Ran it with 11.8
cuDNN: Ran it with 8.9.23.28
TensortRT: Ran it with version for 11.8
```
>> Then >>
Upgrade "jax & jaxlib" with Nvidia, do following...
`pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
