### ISSUE TITLE
Jax cannot use A100 GPU despite CUDA 11 version being installed

### ISSUE THREAD

**Issue by fonnesbeck** [google/jax#10349]
I'm using an A100 GPU on Google Cloud and attempting to run some Jax code on it, however I get a runtime error when the code is run:

```
[RuntimeError: Backend 'gpu' failed to initialize: NOT_FOUND: Could not find 
registered platform with name: "cuda". Available platform names are: 
Host Interpreter]()
```

whereas, PyTorch sees the GPU:

```python
>>> torch.cuda.get_device_name(0)
'NVIDIA A100-SXM4-40GB'
```

Based on some previous issues in the tracker, I installed the CUDA 11 version of Jax via `pip install jax[cuda11]`, which resulted in v0.3.7 being installed. Given that this version of Jax should be CUDA11-compatible, I'm at a loss as to why it is not using the GPU. Any advice appreciated.

**Comment by hawkinsp** [comment]
Can you show *exactly* what command line you used?

Try uninstalling and reinstalling following the installation instructions (https://github.com/google/jax#pip-installation-gpu-cuda):

```
pip uninstall -y jax jaxlib
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html  # Note: wheels only available on linux.
```

My guess is that you haven't successfully installed a GPU-using `jaxlib`.

**Comment by fonnesbeck** [comment]
Yes, that was the issue, thanks. I did not remove the old jaxlib.
