### ISSUE TITLE
Make JAX thread-safe

### ISSUE THREAD

**Issue by zhongwen** [google/jax#1037]
Currently JAX is not thread-safe, as you can see in the following example:

```
import jax
from jax.experimental import stax
import threading
import jax.random as random

def create_net():
  init_fn, apply_fn = stax.Dense(10)
  key = random.PRNGKey(0)
  _, params = init_fn(key, input_shape=(-1, 5))
  return params, apply_fn

def f1():
  p1, apply_fn1 = create_net()
  x = random.normal(key, shape=(1, 5))
  return apply_fn1

def f2():
  p2, apply_fn2 = create_net()
  x = random.normal(key, shape=(1, 5))
  return apply_fn2

threads = []
t = threading.Thread(target=f1)
t.start()
threads.append(t)

t = threading.Thread(target=f2)
t.start()
threads.append(t)

for t in threads:
  t.join()

```

It has been increasing demand on requesting JAX to be thread-safe, could the developers consider it?

**Comment by hawkinsp** [comment]
PR #1055 makes it safe (I think!) to call JAX code concurrently from different Python threads. You must not use concurrency inside a traced function (e.g., inside a JIT-ted function) however.

**Comment by hawkinsp** [comment]
PR #1055 fixed the concurrency issues we know about, but I don't have a lot of confidence that we found everything until it sees wider use.
