### ISSUE TITLE
XLA convolution bug: error only with relu after conv

### ISSUE THREAD

**Issue by joschu** [google/jax#1049]
If you add a relu after a certain conv (with `feature_group_count > 0`), you get a message like `RuntimeError: Internal: Unable to launch convolution with type forward with activation and algorithm (0, 140693450041357)`. But without that relu, no error.
`bug=1 python bug.py`: error
`python bug.py`: no error

This is on a linux machine. Here's my nvidia-smi output
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  On   | 00000000:04:00.0 Off |                  N/A |
|ERR!   27C    P8    26W / 250W |      0MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
...
```

[bug.py.txt](https://github.com/google/jax/files/3415251/bug.py.txt)

**Comment by joschu** [comment]
As a workaround, I found that replacing the relu by `relu(Y + 1e-20)` prevents XLA from performing the problematic optimization

**Comment by hawkinsp** [comment]
Thanks for the bug report. I passed it on to the XLA GPU folks.

**Comment by hawkinsp** [comment]
This is now fixed (but requires either rebuilding jaxlib from source or waiting for us to make another release.) Hope that helps!

**Comment by joschu** [comment]
Great, thanks!!

**Comment by hawkinsp** [comment]
We made a new `jaxlib` release (0.1.23) which includes the fix for this issue. Please try it out!
