### ISSUE TITLE
Implement `jax.print`

### ISSUE THREAD

**Issue by jlebar** [google/jax#1050]
It would be cool if you could print from a JIT'ed context.  This would be useful for people who are using contexts where they can't escape JIT for some reason.  For instance, it could be used by folks using the JAX-to-HLO functionality we have.

I'd propose semantically `jax.print` works like Python `string.format`.

  ```
x = <host object>
y = <device array>
jax.print("{} = {}", x, y)
```

This would stringify `x` eagerly (i.e. when the Python interpreter evaluates the `print` call, and would stringify `y` lazily, i.e. when the XLA computation actually runs.

Because I want this to work with the JAX-to-HLO functionality, I'd propose implementing this as a custom-call.  That will work on CPU/GPU.

cc @hawkinsp @mattjj wdyt?

**Comment by gnecula** [comment]
I believe that id_print from #3006 meets this requirement.
