### ISSUE TITLE
Add `jax.jit(donate_argnames=...)`

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#10539]
`static_argnames` is much less error prone than `static_argnums`, and easily works with keyword arguments.
It would be useful to have the same syntax for `donate_***`.

**Comment by JeppeKlitgaard** [comment]
I might be interested in implementing this following #10603 and #10476

**Comment by JeppeKlitgaard** [comment]
Having had a look at this, I think an ideal solution which supports both positional-only and keyword-only arguments (as well as anything in between) would require changes to `xla.xla_call`, which would be beyond what I could do.

A simpler solution that would work in cases except keyword-only could be done quite easily with `inspect`.
