### ISSUE TITLE
Unexpected behaviour in `jnp.unravel_index`

### ISSUE THREAD

**Issue by gerdm** [google/jax#10540]
I'm getting erroneous values for `jnp.unravel_index`. For an index of `0`, some  shapes give different results than the expected `(0,0)`. Some examples:

```python
import jax.numpy as jnp

side = 10
jnp.unravel_index(0, (side, side))
# (DeviceArray(0, dtype=int32), DeviceArray(0, dtype=int32))

side = 201_995
jnp.unravel_index(0, (side, side))
# (DeviceArray(0, dtype=int32), DeviceArray(0, dtype=int32))

side = 201_996
jnp.unravel_index(0, (side, side))
# (DeviceArray(-1, dtype=int32), DeviceArray(130531, dtype=int32))

side = 205_000
jnp.unravel_index(0, (side, side))
# (DeviceArray(-1, dtype=int32), DeviceArray(82039, dtype=int32))

side = 500_000
jnp.unravel_index(0, (side, side))
# (DeviceArray(0, dtype=int32), DeviceArray(0, dtype=int32))
```

I'm using Jax version `0.3.6`.

**Comment by jakevdp** [comment]
Agreed with that synopsis, but I wonder if we could make the implementation safer with respect to potential integer overflow? After all, neither the inputs nor the expected outputs in this case are out of range.

**Comment by jakevdp** [comment]
Another potential improvement: in the common case of a static `shape` argument, we should be able to warn or error at trace time if there is not enough range to represent the output.
