### ISSUE TITLE
Implement numpy.partition and numpy.argpartition

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#10541]
Implement [numpy.partition](https://numpy.org/doc/stable/reference/generated/numpy.partition.html) and [numpy.argpartition](https://numpy.org/doc/stable/reference/generated/numpy.argpartition.html) (currently [in the docs](https://jax.readthedocs.io/en/latest/jax.numpy.html#jaxlib.xla_extension.DeviceArray.argpartition) but unimplemented). Among other things, this allows for efficient computation of [order statistics](https://en.wikipedia.org/wiki/Order_statistics) (see [selection algorithms](https://en.wikipedia.org/wiki/Selection_algorithm)) without having to sort the entire array:

```python
import numpy as np
from timeit import default_timer

def order1(a, k, axis=-1):
    return np.partition(a, k, axis).take(k, axis)

def order2(a, k, axis=-1):
    return np.sort(a, axis).take(k, axis)

def test_order(shape, axis):
   a = np.random.rand(*shape)
   k = np.random.randint(shape[axis])

   start = default_timer()
   ans1 = order1(a, k, axis)
   print('partition-based: {:g} seconds'.format(default_timer() - start))

   start = default_timer()
   ans2 = order2(a, k, axis)
   print('sort-based:      {:g} seconds'.format(default_timer() - start))

   assert np.array_equal(ans1, ans2)

for shape in [(10**7,), (10**4, 10**3), (10**3, 10**2, 10**2)]:
    for axis in range(len(shape)):
        print()
        test_order(shape, axis)
```

```
partition-based: 0.12672 seconds
sort-based:      0.878069 seconds

partition-based: 0.300224 seconds
sort-based:      0.679816 seconds

partition-based: 0.0932873 seconds
sort-based:      0.38649 seconds

partition-based: 0.16949 seconds
sort-based:      0.445229 seconds

partition-based: 0.134436 seconds
sort-based:      0.273936 seconds

partition-based: 0.130433 seconds
sort-based:      0.260393 seconds
```

**Comment by jakevdp** [comment]
Thanks for the request - this enhancement is already tracked in #70 and #2079. Unfortunately it's not easy to add, becuause XLA doesn't have an partial sorting primitive.

I'm going to close this issue as a duplicate.
