### ISSUE TITLE
Extremely slow when I jit compile a function on GPU.

### ISSUE THREAD

**Issue by xinyuxiao113** [google/jax#10596]
When I use jit for a function with fft operation on GPU  as follows (Note that I use a global variable pulse here). It takes more than 10s to jit compile on GPU while 0.1s on CPU. I can not figure out the reason. Can you explain what happend ?

```python
import time
import jax
import numpy as np
import jax.numpy as jnp

pulse = jax.device_put(np.random.rand(8000))

def f():
    sigTx = jnp.fft.fft(pulse)
    return sigTx

t0 = time.time()
a = jax.jit(f, backend='gpu')()
t1 = time.time()
print('time cost on gpu:',t1-t0)


t0 = time.time()
a = jax.jit(f, backend='cpu')()
t1 = time.time()
print('time cost on cpu:',t1-t0)
```

![截屏2022-05-06 上午10 06 15](https://user-images.githubusercontent.com/55077744/167055137-aaff804f-05a6-45f1-997c-9f2a82d07912.png)

Surprisingly,  when I pass the global variable pulse as an argument into the function, the compile time is reduce to a normal level
```python
import time
import jax
import numpy as np
import jax.numpy as jnp

pulse = jax.device_put(np.random.rand(10000))

def f(pulse):
    return jnp.fft.fft(pulse)

t0 = time.time()
a = jax.jit(f, backend='gpu')(pulse)
t1 = time.time()
print('time cost on gpu:',t1-t0)


t0 = time.time()
a = jax.jit(f, backend='cpu')(pulse)
t1 = time.time()
print('time cost on cpu:',t1-t0)
```
![截屏2022-05-06 上午10 08 59](https://user-images.githubusercontent.com/55077744/167055138-ed452d66-94ec-4b2d-b09f-66a6dfa121d3.png)

**Comment by xinyuxiao113** [comment]
Here is my environments.
cuda-11.4.2-gcc-11.2.0-rxy4qhm   
cudnn-8.2.4.15-11.4-gcc-11.2.0-a6q32ad   
gcc/11.2.0  
jax                                0.2.17  
jaxlib                             0.1.68

**Comment by YouJiacheng** [comment]
This is related to constant-folding IMO.
```
2022-05-06 12:57:16.669751: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:61] Constant folding an instruction is taking > 1s:

  %fft.0 = c64[8000]{0} fft(c64[8000]{0} %constant), fft_type=FFT, fft_length={8000}, metadata={op_name="jit(f)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(8000,)]" source_file="/home/jiacheng/xxx/xxx.py" source_line=9}

This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
```

**Comment by xinyuxiao113** [comment]
> This is related to constant-folding IMO.
> 
> ```
> 2022-05-06 12:57:16.669751: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:61] Constant folding an instruction is taking > 1s:
> 
>   %fft.0 = c64[8000]{0} fft(c64[8000]{0} %constant), fft_type=FFT, fft_length={8000}, metadata={op_name="jit(f)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(8000,)]" source_file="/home/jiacheng/xxx/xxx.py" source_line=9}
> 
> This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.
> 
> If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
> ```

Thank you for your reply, by the way, do you have any good ideas to avoid the long time constant folding ?   Or is there any  programing principles to keep my code away this trap.

**Comment by YouJiacheng** [comment]
I think we can make sure all large constants are passed as argument to jitted function, or created inside jitted function. It is okay to have large constants created inside jitted function and captured by closure as well.
```python
@jax.jit
def f(x):
  large_constant = jnp.zeros((10000, 10000))
  def g(y):
     return fft(large_constant) + y
  return g(x)
```

**Comment by YouJiacheng** [comment]
`np.random.rand(8000)` is compiling-time constant as well.
You might try:
```python
large_constant = jax.random.uniform(jax.random.PRNGKey(0), (10000, 10000))
```
BUT... it fails again
```python
import jax
import jax.numpy as jnp
import time




@jax.jit
def f():
    large_constant = jax.random.uniform(jax.random.PRNGKey(0), (8000,))
    return jnp.fft.fft(large_constant)


t0 = time.time()
f()
t1 = time.time()
print('time cost on gpu:', t1 - t0)
```
Hmmmm.

**Comment by YouJiacheng** [comment]
`np` array will be treated as compile-time constant. So constant-folding again.
`large_constant = jax.random.uniform(jax.random.PRNGKey(0), (8000,))` is not compile-time constant by default, unless
```python
import jax
import jax.numpy as jnp
import time


@jax.jit
def f():
    with jax.ensure_compile_time_eval():
        x = jax.random.uniform(jax.random.PRNGKey(0), (8000,))
    return jnp.fft.fft(x)

jnp.array(0) # backend initialization

t0 = time.time()
jax.block_until_ready(f())
t1 = time.time()
print('time cost on gpu:', t1 - t0)

# 2022-05-06 14:39:05.686491: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:61] Constant folding an instruction is taking > 1s:

#   %fft.0 = c64[8000]{0} fft(c64[8000]{0} %constant), fft_type=FFT, fft_length={8000}, metadata={op_name="jit(f)/jit(main)/jit(fft)/fft[fft_type=FftType.FFT fft_lengths=(8000,)]" source_file="/home/jiacheng/xxx/xxx.py" source_line=8}

# This isn't necessarily a bug; constant-folding is inherently a trade-off between compilation time and speed at runtime.  XLA has some guards that attempt to keep constant folding from taking too long, but fundamentally you'll always be able to come up with an input program that takes a long time.

# If you'd like to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
# time cost on gpu: 3.282024383544922
```

**Comment by xinyuxiao113** [comment]
Okay, I get your point.  I am confusing about the reason why constant folding takes such long time when I use fft on np.random.rand numbers. When I take other operations such as inverse of matrix instead of fft,  this problem disappear.

![截屏2022-05-06 下午10 44 23](https://user-images.githubusercontent.com/55077744/167156330-1e467c28-e4c0-4a12-874d-1c12cab85575.png)

**Comment by hawkinsp** [comment]
Fundamentally: if you capture a constant value in a `jit`, you are telling JAX "the compiler may see this value, must bake it into the program, and may perform optimizations using its value".

If you do not want that behavior, the fix is what you discovered: pass the value as a parameter instead! That is exactly the distinction between parameters and captured values.

(I suspect the reason you don't get constant-folding for operations other than FFT is that the HLO that JAX generates for `inv` contains `custom-call` operators that XLA will not constant fold. But XLA knows how to constant-fold FFTs.)

**Comment by YouJiacheng** [comment]
@xinyuxiao113 Not all op has constant folding rule, IIUC.

**Comment by xinyuxiao113** [comment]
Thank you again. I think I have understand this problem.

**Comment by xinyuxiao113** [comment]
> @xinyuxiao113 Not all op has constant folding rule, IIUC.

Thank you again. I think I have understand this problem.
