### ISSUE TITLE
`jit` input validation can lead to silently dynamic variables

### ISSUE THREAD

**Issue by JeppeKlitgaard** [google/jax#10601]
`jax.jit` (and presumable other similar transformations) currently does not validate `static_argnames` and `static_argnums`, which leads to silent failures in some cases. These can be particularly frustrating to debug and the additional input validation can be done with relatively little overhead.

A particularly headache inducing example of this could be when used in combination with positional-only (or keyword-only) arguments.

# Examples:
```python
def f(dyn, stat):
	print(dyn)
	print(stat)
    ...

def g(dyn, stat, /):
	print(dyn)
	print(stat)
    ...

jf = jit(f, static_argnames=("stat",)
jf(1, 2)
> Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
> 2

jg = jit(g, static_argnames=("stat",)
jg(1, 2)
> Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
> Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
# This is somewhat expected, but should at least raise an error

jit(f, static_argnames=("some_arg_that_does_not_exist",)
# No error!

jit(f, static_argnums=(9,)
# No error!
```

# Solution
Input validation on `jit` and similar functions may be made stricter. This may require using `inspect` where possible.

I would be happy to try undertaking this.

**Comment by hawkinsp** [comment]
It seems reasonable to me that if we can determine an accurate signature for the wrapped function that we error if the named arguments certainly do not exist. (You may not know, e.g., if the implementation uses `**kwargs`.)

**Comment by JeppeKlitgaard** [comment]
Would this not also apply to `argnums`?

I am working on argnum validation right now, and I think it already spotted an error in JAX source: https://github.com/google/jax/blob/ab7a60b3abdc1e4aec210d79926824b85082d2d7/jax/_src/lax/qdwh.py#L68

```python
@functools.partial(jax.jit, static_argnums=(1, 2, 3))
def _qdwh(x, is_symmetric, max_iterations):
```

I assume (and believe to recall) `static_argnums` is zero-indexed, so making `argnum=3` will never make sense.

Could you confirm this, @hawkinsp?

**Comment by JeppeKlitgaard** [comment]
My current approach to validation is to count the number of `POSITIONAL_ONLY` and `POSITIONAL_OR_KEYWORD` arguments and use that count. If we have a `VAR_POSITIONAL` (`*args`), then any number of argnums is allowed as expected.

**Comment by JeppeKlitgaard** [comment]
Similarly there seems to be a bug here:
https://github.com/google/jax/blob/562e27d72d6cac7c9e3fb07801d246f935712d0f/jax/_src/scipy/linalg.py#L149-L150

(`overwrite_b` and `overwrite_a` mismatch?)

**Comment by hawkinsp** [comment]
For the `qdwh` code, it should be `(1, 2)`.

I agree the `lu_solve` is a mismatch.

**Comment by JeppeKlitgaard** [comment]
Those two cases nicely motivate stricter input validation, I think!

I will make a PR with the additional validation.
