### ISSUE TITLE
`jupytext --sync docs/jax-101/*` fails because of an rst file

### ISSUE THREAD

**Issue by ngam** [google/jax#10632]
`jupytext --sync docs/jax-101/*` ([as here](https://jax.readthedocs.io/en/latest/developer.html#update-notebooks)) fails because of an rst file 

```
$ jupytext --sync docs/jax-101/*
...
jupytext.paired_paths.InconsistentPath: 'docs/jax-101/index.rst' is not a notebook.
```

The fix is to run `jupytext --sync docs/jax-101/*.md` and then `jupytext --sync docs/jax-101/*.ipynb` (not sure why more wildcards didn't work, e.g. `jupytext --sync docs/jax-101/*.{ipynb,md}` or maybe I was doing something wrong locally)

_Originally posted by @ngam in https://github.com/google/jax/issues/10626#issuecomment-1121309268_

**Comment by jakevdp** [comment]
Thanks! Should be addressed in #10636
