### ISSUE TITLE
`jnp.array` is much slower than `np.array` when called on a nested list

### ISSUE THREAD

**Issue by onnoeberhard** [google/jax#10662]
Consider the following example (I am using JAX version 0.3.10):
```python
>>> import jax.numpy as jnp
>>> import numpy as np
>>> x = [list(range(1000)) for i in range(1000)]    # A simple nested list
>>> %timeit np.array(x)
79.4 ms ± 6.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each
>>> %timeit jnp.array(x)
3.22 s ± 174 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

NumPy is orders of magnitude faster than JAX here. A similar problem for non-nested lists (#2919) was addressed in PR #3350.

**Comment by jakevdp** [comment]
This was the result of a performance-vs-correctness tradeoff that we made in the implementation of `jnp.array`; we chose correctness at the expense of performance. If you are converting a large list of scalar values to a JAX array and performance is more important to you than correctness, I'd suggest `jnp.array(np.array(values))`

**Comment by jakevdp** [comment]
I'll note also that even the previous "fast path" that you reference in that PR would slow down by orders of magnitude once jit-compiled, and in many cases would return different results between jit and non-jit execution, which both are behaviors we try to avoid.

**Comment by onnoeberhard** [comment]
Interesting, thanks for the reply! I assume the additional overhead of converting the NumPy array to JAX is negligible if they are on the same device?

It might be a good idea to mention this difference in the documentation (maybe [here](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#non-array-inputs-numpy-vs-jax)). I only noticed this in my project due to profiling and did not expect a performance difference between `jnp.array` and `np.array`. After switching to `jnp.array(np.array(..))`, my whole program ran about 6x faster.

If you want I could try to write up a paragraph on this and file a PR.

**Comment by jakevdp** [comment]
Regarding the overhead of converting numpy to jax – yes, it should be negligible on the same device. And if you're using an accelerated backend, there's not really any way around it: your list of integers (or whatever) lives on CPU. You can either serialize each of those integers individually and push each one to the device and then run a `concat` operation on them, or you can wrap them in a numpy array and push the array to the device all at once. Either route is going to incur overhead – there's no free lunch when your data source is a different device than your target.

**Comment by onnoeberhard** [comment]
I see, that makes sense.

I just noticed another interesting performance difference between JAX and numpy which may or may not be related to the above:
```python
```

**Comment by jakevdp** [comment]
This discrepancy is different - it's because the jax operation is not JIT compiled (if you JIT compile it, it is about 100x faster)

If you're interested in microbenchmark comparisons between JAX and NumPy, I'd start with https://jax.readthedocs.io/en/latest/faq.html#is-jax-faster-than-numpy

**Comment by onnoeberhard** [comment]
@jakevdp Thanks for the explanation. I am now trying to write about why lists are not automatically converted to numpy arrays first. I don't completely understand what you mean by "correctness" above. Can you give an example where `jnp.array(list)` returns a different (and "more correct") result than `jnp.array(np.array(list))`?

**Comment by jakevdp** [comment]
Sure, one important reason we can't just call `np.array` when the argument is a list is that JAX transforms inject tracers in place of values, so `np.array` will result in an error:
```python
from jax import jit

@jit
def f(x):
  return jnp.array([x, 0, 0])
print(f(x))
# [0. 0. 0.]

@jit
def g(x):
  return np.array([x, 0, 0])
g(x)
# ---------------------------------------------------------------------------
# TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(float16[])>with<DynamicJaxprTrace(level=0/1)>
# While tracing the function g at <ipython-input-13-53206b980741>:9 for jit, this concrete value was not available in Python because it depends on the value of the argument 'x'.
# See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError
```

Another more subtle example is when you have a list with a mix of dtypes where type promotion behavior differs between numpy and jax:
```python
import jax.numpy as jnp
import numpy as np

x = jnp.float16(0)

print(np.array([x, 0, 0]).dtype)
# float64

print(jnp.array([x, 0, 0]).dtype)
# float16
```
JAX treats unspecified python scalars as "weakly-typed", in that they conform to the types of other "strongly-typed" values they interact with. Numpy treats Python scalars as 64-bit, and tends to promote things to 64-bit indiscriminately. This is problematic when working on accelerators like GPU or TPU, where it is often preferable to work in lower-precision for performance reasons, but users still want the convenience of writing things like `0` and `1` without explicit dtype declaration.

**Comment by onnoeberhard** [comment]
Thanks a lot for the examples. Sorry for the delay (I had a paper deadline); I have now included the main points of this discussion into the "sharp bits" page and opened a pull request.
