### ISSUE TITLE
`--config=cuda` overrides explicit options, instead of augmenting them

### ISSUE THREAD

**Issue by ngam** [google/jax#10696]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
import jax.numpy as jnp
print(jnp.arange(10))
# [0 1 2 3 4 5 6 7 8 9]
```

- [x] If applicable, include full error messages/tracebacks.

---

I am trying to build cuda-enabled jaxlib on conda-forge. I am running into a problem where the `--config=cuda` flag replaces the custom toolchain. I understand this is outside the scope here, but getting cuda-enabled jax on conda-forge seems to be a very valuable contribution, and I hope you can help us achieve that. We do build cuda-enabled tensorflow, and we follow our method almost exactly. The option `--config=cuda` works fine in our tensorflow builds.

```
WARNING: option '--config=cuda' (source command line options) was expanded and now overrides the explicit option --crosstool_top=//bazel_toolchain:toolchain with --crosstool_top=@local_config_cuda//crosstool:toolchain
```

Once the above happens, the local_config_cuda parameters essentially cannot see any of the system libraries and everything  breaks. I haven't looked too deeply into this yet, so bringing it here first in case you have a quick answer/shortcut.

Corresponding PR in conda-forge: https://github.com/conda-forge/jaxlib-feedstock/pull/97

Tagging @hawkinsp who's been involved in issues related to the builds before. Thanks!

**Comment by ngam** [comment]
I believe I have managed to patch it successfully, but I will keep this open for now. I will update the conda-forge PR with details.

**Comment by mattjj** [comment]
@yashk2810 could you take a look?

**Comment by yashk2810** [comment]
What command did you use to build jaxlib?

**Comment by ngam** [comment]
something like:
``` 
python build/build.py  --bazel_options=--crosstool_top=//custom_toolchain:toolchain --bazel_options=--cpu --enable_cuda 
```


More verbosely,

```
  ${PYTHON} build/build.py --target_cpu_features default --enable_mkl_dnn ${CUSTOM_BAZEL_OPTIONS} --bazel_options=--cpu --bazel_options=${TARGET_CPU} --bazel_options="--local_cpu_resources=${CPU_COUNT}" ${CUDA_ARGS:-}

```

with the various expansions:

```shell

CUSTOM_BAZEL_OPTIONS="--bazel_options=--crosstool_top=//custom_toolchain:toolchain"

CUSTOM_BAZEL_OPTIONS="${CUSTOM_BAZEL_OPTIONS} --bazel_options=--logging=6 --bazel_options=--verbose_failures --bazel_options=--toolchain_resolution_debug --bazel_options=--define=PREFIX=${PREFIX} --bazel_options=--define=PROTOBUF_INCLUDE_PATH=${PREFIX}/include"

export TF_CUDA_COMPUTE_CAPABILITIES=sm_35,sm_50,sm_60,sm_62,sm_70,sm_72,sm_75,sm_80,sm_86,compute_86

CUDA_ARGS="--enable_cuda \
               --enable_nccl \
               --cuda_path=$CUDA_HOME \
               --cudnn_path=$PREFIX   \
               --cuda_compute_capabilities=$TF_CUDA_COMPUTE_CAPABILITIES \
               --cuda_version=$TF_CUDA_VERSION \
               --cudnn_version=$TF_CUDNN_VERSION"
```

see recipe/build.sh in the above PR: https://github.com/conda-forge/jaxlib-feedstock/blob/009b2fe3f774570476da47fac0479d05c9ded67a/recipe/build.sh

**Comment by ngam** [comment]
Here how I see it:
- `--enable_cuda` triggers `--config=cuda` in build.py
- `--config=cuda` is passed as command-line arg to bazel
- in bazelrc, `--config=cuda` sets a toolchain for the nvcc compilation
- that in turn results in this: `WARNING: option '--config=cuda' (source command line options) was expanded and now overrides the explicit option --crosstool_top=//bazel_toolchain:toolchain with --crosstool_top=@local_config_cuda//crosstool:toolchain`
- this override results in our custom_toolchain getting ignored completely (thus missing system libs, etc.)

**Comment by ngam** [comment]
The breaking point imo is that `--crosstool_top=@local_config_cuda//crosstool:toolchain` should be augmented (since it is only for the nvcc compilation anyway) and not completely override what the user wants. I have no idea if this is something that's set here or elsewhere, but it is worth looking into, especially vis-a-vis tensorflow build.

**Comment by hawkinsp** [comment]
The arguments to `bazel` are ordering sensitive. I'm wonder if the fix would be to reorder the arguments here:
https://github.com/google/jax/blob/7d4d15e260e24c54f9fbc1685a45d910edb61e43/build/build.py#L493

so that the user-provide `--bazel_options` override `--config=cuda` (i.e., come later), rather than the other way around?

**Comment by ngam** [comment]
> so that the user-provided --bazel_options override --config=cuda (i.e., come later), rather than the other way around?

I attempted a version of this and it didn't work, but there is a good chance I did it badly/wrongly...

**Comment by yashk2810** [comment]
Another thing you can try is to add things at the end to `.jax_configure.bazelrc` (Make sure you are adding your custom things at the end of the file -- not the python file but the .jax_configure.bazelrc file.)
