### ISSUE TITLE
Clipping of a NaN matrix

### ISSUE THREAD

**Issue by wyjw** [google/jax#1072]
In the following code, 
```
import jax.numpy as np
a = np.full((3,3,), np.nan)
np.clip(a, -1, 1)
```

The matrix of only NaNs is now clipped to a matrix of all -1s, which is different than what is done in numpy, which keeps it still a matrix of NaNs. Is this intended?

Thanks!

**Comment by hawkinsp** [comment]
Thanks for the report! This only reproduces on GPU, not CPU. I filed an issue for the XLA team.

**Comment by hawkinsp** [comment]
This is now fixed (but requires either rebuilding jaxlib from source or waiting for us to make another release.) Hope that helps!

**Comment by hawkinsp** [comment]
We made a new `jaxlib` release (0.1.23) which includes the fix for this issue. Please try it out!
