### ISSUE TITLE
xmap doesn't preserve static argnums

### ISSUE THREAD

**Issue by nestordemeure** [google/jax#10741]
`xmap` appears to turn static arguments into traced shapearrays. This can cause problems when one needs an argument to be static for a test.

The following code demonstrate the issue, first using `vmap` (no problem) then replacing it with `xmap` which fails (`Abstract tracer value encountered where concrete value is expected`) when testing the value of `cond` at the very beginning of the `func` function:

```python
import jax
import jax.numpy as jnp
from jax.experimental.maps import xmap

# dummy function
def func(cond, data):
   if cond: return data
   else: return data

# vectorisation
func_vmap = jax.vmap(func, in_axes=[None, 0], out_axes=0)
func_xmap = xmap(func, in_axes=[[...], ['axis']], out_axes=['axis'])

# jit compiling
func_vmap_jit = jax.jit(func_vmap, static_argnames=['cond'])
func_xmap_jit = jax.jit(func_xmap, static_argnames=['cond'])

# running
cond = True
data = jnp.ones(100)
out_vmap = func_vmap_jit(cond, data)
out_xmap = func_xmap_jit(cond, data)
```

This happens with the very last version of Jax (0.3.13).

**Comment by JeppeKlitgaard** [comment]
I believe the changes I am working on related to #10614 would fix this.

**Comment by froystig** [comment]
Assigned @apaszke for xmap and @JeppeKlitgaard based on the previous comment (https://github.com/google/jax/issues/10741#issuecomment-1129341709).

**Comment by apaszke** [comment]
xmap was removed from JAX, so this is obsolete
