### ISSUE TITLE
feature request: restart optimization

### ISSUE THREAD

**Issue by cpgoodri** [google/jax#1078]
In the experimental optimizers, I need to save the current opt_state to file and then separately use that file to load the opt_state and continue the optimization. Pickle-ing doesn't work for reasons I think I understand. The next solution I tried was to use the opt_init function to create a state and then adjust the values by hand:
```
opt_state2=opt_init(initial_params)
opt_state2.packed_state=(a1,a2)
```
Here, I'm using the RMSProp minimizer where the state can be defined from two arrays, a1 and a2. However, this throws "AttributeError: can't set attribute". 

The solution that works is to copy the rmsprop function (https://github.com/google/jax/blob/b9a984f43871dc2d6e79c5f4a627a6e0a790b2c3/jax/experimental/optimizers.py#L266) but have it explicitly set the avg_sq_grad rather than setting it to zero:
```
@optimizers.optimizer
def rmsprop_restart(step_size, gamma, eps ,avg_sq_grad):
  #step_size = make_schedule(step_size)
  def init(x0):
    #avg_sq_grad = np.zeros_like(x0)
    return x0, avg_sq_grad
  def update(i, g, state):
    x, avg_sq_grad = state
    avg_sq_grad = avg_sq_grad * gamma + g**2 * (1. - gamma)
    x = x - step_size(i) * g / (np.sqrt(avg_sq_grad) + eps)
    return x, avg_sq_grad
  def get_params(state):
    x, _ = state
    return x
  return init, update, get_params
opt_init_restart = rmsprop_restart(step_size=2e-2, gamma=0.9, eps=1e-8,avg_sq_grad=v2)[0]
opt_state2 = opt_init_restart(v1)
```
However, this is very hacky and I imagine may not be stable to future updates. 

Is there a more stable/streamlined way of doing this? If not, is this a feature that would be widely used by the community?

**Comment by liuxx479** [comment]
Just wonder if there is any progress for saving current model for restart?

**Comment by hawkinsp** [comment]
I'm going to close this issue since we don't plan to develop `jax.experimental.optimizers` (now `jax.example_libraries.optimizers') any further. `optax` is a better replacement in every way. If this issue still makes sense, I'd try it against `optax` instead!
