### ISSUE TITLE
Type error in reverse-mode AD of `lax.dot_general` with `preferred_element_type`

### ISSUE THREAD

**Issue by romanngg** [google/jax#10818]
Colab:
https://colab.research.google.com/gist/romanngg/64bae6efa7d4d364c68cd341f1be8c85/reverse_mode_dot_general_fail.ipynb

```python

import jax, jax.numpy as np

x = np.ones((), np.float16)

def f(x):
  return jax.lax.dot_general(x, x, (((), ()), ((), ())), preferred_element_type=np.float32)

jax.jacrev(f)(x)
```
causes
```
TypeError: lax.dot_general requires arguments to have the same dtypes, got float32, float16.
```
whereas forward pass and forward-mode AD work.

**Comment by alexeib** [comment]
+1, any updates? 

```x = jnp.einsum(
        "blhd,bmd->bhlm",
        q,
        k,
        preferred_element_type=jnp.float32
    )````

where q and k are bf16 crashes on backward pass with the 
```TypeError: lax.dot_general requires arguments to have the same dtypes, got float32, bfloat16.```

**Comment by alexeib** [comment]
you can work around this if you do q.astype(jnp.float32), k.astype(jnp.float32) before the einsum

**Comment by mattjj** [comment]
Thanks for the ping!

This should be easy to fix once we figure out the logic to implement. But I'm unsure of the logic we want. Maybe you can tell me!

Say we transpose (essentially, reverse-mode differentiate) a dot of the form
```
z:f32[3,5] = dot_general [preferred_element_type=f32] x:bf16[3,4] y:bf16[4,5]
```
with respect to its second argument, where the contraction is happening over the axes of the same size. That means we need to take a `z_bar:f32[3,5]` and an `x:bf16[3,4]` and ultimately produce a `y_bar:bf16[4,5]`.

At one point, probably in the ancient past, I think HLO didn't accept `dot_general` applications with different element types. Let's say that constraint is not present. Here are two different things we could transpose the above to:

```
# Option 1: change the preferred_element_type, so accumulation (and output) is now in bf16
y_bar:bf16[4,5] = dot_general [preferred_element_type=bf16] x:bf16[3,4] z_bar:f32[3,5]

# Option 2: keep the preferred_element_type (so accum is in f32), do a cast afterward
y_bar_temp:f32[4,5] = dot_general [preferred_element_type=f32] x:bf16[3,4] z_bar:f32[3,5]
y_bar:bf16[4,5] = convert_element_type[new_dtype=bf16] y_bar_temp:f32[4,5]
```

Is it clear to you which one of those is better? Is it ambiguous?

**Comment by jekbradbury** [comment]
I think `preferred_element_type` doesn't always mean that accumulation happens in that precision (e.g. accumulation of bf16 matmuls on TPU is always in f32)

**Comment by mattjj** [comment]
But I asked an LLM and that's what it told me!

Just kidding, I was going off of our docs [here](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.conv_with_general_padding.html):
> preferred_element_type (Optional[Any]) – Optional. Either None, which means the default accumulation type for the input types, or a datatype, indicating to accumulate results to and return a result with that datatype.

Maybe our docs are wrong.

**Comment by noam-character** [comment]
It should be just as fast to cast the inputs to f32, right?   Wouldn't XLA do some magic optimization to avoid materializing the f32 input in HBM?

**Comment by mattjj** [comment]
That seems likely. But I'm not familiar enough (with what XLA does, on every backend) to know the best JAX-level policy (or if it even matters given XLA magic).

Let me ask the wizard Blake...

**Comment by mattjj** [comment]
Blake and his fellow wizard @hawkinsp advised! TL;DR we will try Option #2 above.

**Comment by mattjj** [comment]
I'll make a fix for this today, unless it's more urgent and you need it ASAP.

**Comment by mattjj** [comment]
Well that was a can of worms. Sorry for the delay! #16046 should fix.
