### ISSUE TITLE
JAX cholesky failed, while numpy succeeded

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#10825]
When I use `jax.linalg.cholesky` on a particular (large) covariance matrix of shape (37k,37k) jax is returning `nan`'s while numpy is successfully returning a decomposition. I expected that jax mimics numpy in it's linear algebra operations. Note, we have set jax to 64-bit.

## how to reproduce it

Get covariance matrix ~ 11GB from @Joshuaalbert (ssh or google drive are acceptable). It's very expense to compute so this is the only reasonable method of providing the data for the MVCE.

```python
import numpy as np
from jax import numpy as jnp
from jax.config import config
config.update("jax_enable_x64", True)

cov = np.load("./big-cov.npy")

jitter = 1e-6
L_np = np.linalg.cholesky(cov + jitter * np.eye(cov.shape[0]))
assert not np.any(np.isnan(L_np)) # actually not necessary because numpy would complain instead of returning nan's

L_jax = jnp.linalg.cholesky(jnp.asarray(cov) + jitter * jnp.eye(cov.shape[0]))
assert not jnp.any(jnp.isnan(L_jax)) 
```

**Comment by hawkinsp** [comment]
What hardware platform is this?

Is it possible this is a cousin of https://github.com/google/jax/issues/10420 ?

On CPU, the kernel we call is `dpotrf` from LAPACK. You can call it directly via `scipy.linalg.lapack`. Does it succeed or fail?

**Comment by patrick-kidger** [comment]
I'm just some passing observer, but your numpy example adds `1e-6` on the diagonal whilst the JAX example adds `1e6`, so they're not doing the same thing.

**Comment by Joshuaalbert** [comment]
@hawkinsp This is on CPU.

```python
cov = np.load('./dtec_covariance.npy')
L = jnp.linalg.cholesky(cov) # fails with Nans
L = lapack.dpotrf(cov) # succeeds
```


Thanks @patrick-kidger that was a minor typo when transcribing. The problem is still unchanged.

**Comment by jakevdp** [comment]
What if you call `jnp.linalg.cholexky` with `symmetrize_input=False`?

**Comment by Joshuaalbert** [comment]
`jnp.linalg.cholesky(cov,symmetrize_input=False)` gives me a `cholesky() got an unexpected keyword argument 'symmetrize_input'`.

**Comment by jakevdp** [comment]
You need to use `lax.linalg.cholesky` to control `symmetrize_input`

**Comment by jakevdp** [comment]
Looking at the `np.linalg.cholesky` and `jnp.linalg.cholesky` implementations, it seems the main difference is that numpy assumes your input is hermitian and proceeds, while jax.numpy symmetrizes your input before proceeding (via `lax.linalg.cholesky`). So if there are differences in outputs, I'd look into whether your input is actually hermitian, and whether JAX's symmetrization step is causing problems.

**Comment by Joshuaalbert** [comment]
`L = lax_cholesky(cov,symmetrize_input=False)` gives nans too.

**Comment by jakevdp** [comment]
Well, those are my best guesses. Without a way to reproduce the issue myself, I don't have any other ideas. Best of luck!

**Comment by Joshuaalbert** [comment]
Well, one second there. It seems to me this information can already be used to rule out some things.

Numpy's cholesky succeeds. Therefore the matrix is pos-def AND numerically stable. 

Therefore, perhaps it makes sense to consider #10420. To that end, I can see if slicing to less than (32767,32767) solves it. One sec.

**Comment by Joshuaalbert** [comment]
Regarding understand if it's related to #10420, the same thing happens on a smaller slice of the matrix.

```python
cov = np.load('./dtec_covariance.npy')
cov = cov + 1e-6*np.eye(cov.shape[0])
L = np.linalg.cholesky(cov[:15000,:15000]) # works
L = lapack.dpotrf(cov[:15000,:15000]) # works
L = jnp.linalg.cholesky(cov[:15000,:15000]) # fails
L = lax_cholesky(cov[:15000,:15000],symmetrize_input=False) # fails
```

**Comment by hawkinsp** [comment]
I think at this point the best thing you could do is share the matrix with us so we can reproduce the problem.

**Comment by Joshuaalbert** [comment]
Ok, this was a false alarm. It was due to 64-bit mode not being turned on properly. In my testing setup I import jax earlier and run a jax primative (which set the 32bit), and then later when this test is run try to set 64bit (which doesn't work). So the tests were an unfair comparison between numpy in 64bit and jax in 32bit. Sorry about the time consumed on this one.

**Comment by hawkinsp** [comment]
Happy it worked out!

**Comment by hawkinsp** [comment]
Happy it worked out!
