### ISSUE TITLE
GPU not found in ipython

### ISSUE THREAD

**Issue by Xin-yang-Liu** [google/jax#10860]
Jax cannot find GPU device in ipython.

To reproduce, run the following code in ipython:
```
from jax import random
key=random.PRNGKey(0)
```
Jax output:
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
arg: 0	 type of arg <class 'jaxlib.xla_extension.DeviceArray'>
arg: 4294967295	 type of arg <class 'numpy.uint32'>
```
I tried PyTorch in the same ipython environment and it can find the GPU device.

environment: 
- OS: Ubuntu 20.04.4 LTS, Linux kernel 5.14
- CUDA: 11.6
- cuDNN: 8.4,
- GPU: NVIDIA GeForce RTX 3070
- jax: 0.3.13, installed via pip
- jaxlib: 0.3.10+cuda11.cudnn82
- python: 3.10.4

**Comment by Xin-yang-Liu** [comment]
I tested this problem in several ways and it turns out very weird. 

In the same terminal
1. I tested it in the REPL python environment and get the same results.
2. I saved the command as a .py file and run it. GPU is not found either. 

When I opened another terminal and run the same thing in ipython, REPL python and python script. In all cases, jax used GPU. So I guess in the first terminal there must be some configurations that cause the same issue. However, even if I follow the same commands I input in the first terminal, the issue cannot be reproduced. 

In the first terminal, I set the ```TF_CPP_MIN_LOG_LEVEL=0``` and get the following outputs:
```
2022-05-27 16:22:52.184138: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:174] XLA service 0x561440d94db0 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2022-05-27 16:22:52.184165: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:182]   StreamExecutor device (0): Interpreter, <undefined>
2022-05-27 16:22:52.194915: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/tfrt_cpu_pjrt_client.cc:176] TfrtCpuClient created.
2022-05-27 16:22:52.195878: I external/org_tensorflow/tensorflow/stream_executor/tpu/tpu_platform_interface.cc:74] No TPU platform found.
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

Since opening a new terminal can bypass this issue, I close this issue. I appreciate it if you can fix this weird issue.

**Comment by dbl001** [comment]
On Google CoLab Pro, 'jax' recognizes the GPU but not the TPU.

**Comment by hawkinsp** [comment]
My guess is that you had one or more environment variables set in the session where the GPU was not found that caused GPU initialization to fail. Ones that may be relevant include `PATH`, `LD_LIBRARY_PATH` and `CUDA_VISIBLE_DEVICES`.

**Comment by hawkinsp** [comment]
TPUs not being found is another issue.

See: https://github.com/google/jax/tree/main/cloud_tpu_colabs for documentation about that. Note in particular you need
```
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
```
at the top of the colab; see the examples. But also note the JAX/Colab/TPU stack is in flux, see the notes on that documentation page about the newer Cloud TPU VMs.

**Comment by dbl001** [comment]
That worked! Thank You!  
btw - Do you happen to know whether JAX will eventually support Apple Metal?

**Comment by hawkinsp** [comment]
See https://github.com/google/jax/issues/8074 for Metal support.
