### ISSUE TITLE
random.ball - Sample uniformly from Lp ball

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#10876]
Add a function that samples uniformly from the [Lp](https://en.wikipedia.org/wiki/Lp_space) [ball](https://en.wikipedia.org/wiki/Ball_(mathematics)). This is used in zeroth-order optimization, among other things. Example implementation (uses the `gnormal` function proposed in #10875):
```python3
from jax import random, numpy as jnp
from matplotlib import pyplot as plt
from gnormal import gnormal

def ball(key, d, p=2, shape=(), dtype=None):
  """Sample uniformly from the unit Lp ball.

  Reference: https://arxiv.org/abs/math/0503650.

  Args:
    key: a PRNG key used as the random key.
    d: a nonnegative int representing the dimensionality of the ball.
    p: a float representing the p parameter of the Lp norm.
    shape: a sequence of nonnegative ints representing the batch dimensions.
    dtype: a float dtype representing the result dtype.

  Returns:
    A random array of shape (*shape, d) and specified dtype.
  """
  keys = random.split(key)
  g = gnormal(keys[0], p, (*shape, d), dtype)
  e = random.exponential(keys[1], shape, dtype)
  return g / (((jnp.abs(g) ** p).sum(-1) + e) ** (1 / p))[..., None]

def test_ball():
  key = random.PRNGKey(0)
  for n in range(1, 4):
    for p in [.5, 1., 1.5, 2., 2.5]:
      for shape in [(), (5,), (10, 5)]:
        for dtype in ['float16', 'float32']:
          rvs = ball(key, n, p, shape, dtype)
          assert rvs.shape == (*shape, n)
          assert rvs.dtype == dtype
          assert ((jnp.abs(rvs) ** p).sum(-1) ** (1 / p) <= 1).all()

def show_plot():
  key = random.PRNGKey(0)
  plt.style.use({
    'savefig.dpi': 300,
    'figure.constrained_layout.use': True,
  })
  for p in [.5, 1., 1.5, 2., 2.5]:
    fig, ax = plt.subplots(figsize=plt.figaspect(1))
    rvs = ball(key, 2, p, shape=[10**5])
    ax.scatter(*rvs.T, lw=0, s=.5)
    ax.set(aspect='equal', title='p = {:g}'.format(p))
  plt.show()

if __name__ == '__main__':
  test_ball()
  show_plot()
```
<img src="https://user-images.githubusercontent.com/8883917/170843069-eec6ca9b-25d9-433c-8917-21b192e375cb.png" width="250"><img src="https://user-images.githubusercontent.com/8883917/170843073-21e195b6-c2ab-4f76-b855-588f27b8c977.png" width="250"><img src="https://user-images.githubusercontent.com/8883917/170843075-142dc4ab-a92c-46e2-9d6f-98433f46aab6.png" width="250"><img src="https://user-images.githubusercontent.com/8883917/170843081-1e6c7efc-9bb8-4925-a2e5-d9568f932be5.png" width="250"><img src="https://user-images.githubusercontent.com/8883917/170843083-bb18badd-5b4f-42ba-b427-40bd2094a3ca.png" width="250">

**Comment by jakevdp** [comment]
Thanks - I think we would be happy to accept a contribution of this function to `jax.random`. Are you interested in putting together a pull request?
