### ISSUE TITLE
GPU Memory Leak when I use numpy under a jitted fucntion.

### ISSUE THREAD

**Issue by xinyuxiao113** [google/jax#10878]
```python
import jax
import jax.random as rd
import numpy as np
import jax.numpy as jnp
import jax.profiler
from functools import partial

key = rd.PRNGKey(233)



@partial(jax.jit,static_argnums=(1,))
def f(key, n):
    print('function is jitting !')
    z = np.random.rand(3200000)
    x = jax.random.normal(key, (3,))
    return z + x[n]


for j in range(3):
    y = f(key, j)
    jax.profiler.save_device_memory_profile(f"memory{j}.prof")
```
I use pprof tool to visualize the GPU memory. 
https://jax.readthedocs.io/en/latest/device_memory_profiling.html#debugging-memory-leaks
```
pprof -http=:9409 -no_browser --diff_base memory0.prof memory1.prof
```
![mem](https://user-images.githubusercontent.com/55077744/170880313-68b4df61-9633-4dae-b3d5-2879f99065dd.png)

We can see that the executable memory is increasing as for loop go on. So we can deduce that the jitted code on GPU is not free in time when I re-jit this function !! 

In order to avoid this problem. I can 
1.  use jax.random instead of numpy.random in f.
2. do not use argnum to avoid re-jitting f.

**Comment by xinyuxiao113** [comment]
Is there any method to free jit compile memory in GPU ?

**Comment by xinyuxiao113** [comment]
#10838
There is a way to solve this problem.

**Comment by xinyuxiao113** [comment]
In addition.   Use  f._clear_cache() is useless.

**Comment by hawkinsp** [comment]
The issue is that the internal method you are calling to clear the cache does not actually clear all the necessary caches. https://github.com/google/jax/pull/11064 adds a new method `.clear_cache()` on `jit`-ted functions that should solve your problem.

**Comment by hawkinsp** [comment]
Please try out the new `.clear_cache()` method and let me know if that fixes your problem!

**Comment by xinyuxiao113** [comment]
@hawkinsp clear_cache() doesn't work here. It seems like a feature about jax.  jax.jit will save all constants inside the jitted function whenever we re-jit the function.  It is useful when we need to use the function lot of times. But it is also a possible trap  leading an out of memory problem because we restore many versions of the same function.
