### ISSUE TITLE
[x64] scatter implementation silently generates 64-bit computations

### ISSUE THREAD

**Issue by jakevdp** [google/jax#10892]
In cases where `scatter` operations are called on mismatched types, it can silently lead to 64-bit operations that are then cast back to the input types.

For example, this code:
```python
import jax.numpy as jnp
from jax.config import config
config.update('jax_enable_x64', True)
x = jnp.arange(5000, dtype='int32')
def f(x):
  return x.at[0].add(1.0)
```
will return an array of type int32, but within the implementation converts the array to float64 before converting it back:
```python
print(jax.make_jaxpr(f)(x))
# { lambda ; a:i32[5000]. let
#     b:bool[] = lt 0 0
#     c:i64[] = add 0 5000
#     d:i64[] = select_n b 0 c
#     e:i32[] = convert_element_type[new_dtype=int32 weak_type=False] d
#     f:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] e
#     g:f64[5000] = convert_element_type[new_dtype=float64 weak_type=True] a
#     h:f64[5000] = scatter-add[
#       dimension_numbers=ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))
#       indices_are_sorted=True
#       mode=GatherScatterMode.FILL_OR_DROP
#       unique_indices=True
#       update_consts=()
#       update_jaxpr={ lambda ; i:f64[] j:f64[]. let k:f64[] = add i j in (k,) }
#     ] g f 1.0
#     l:i32[5000] = convert_element_type[new_dtype=int32 weak_type=False] h
#   in (l,) }
```
The reason for this is the conversion here: https://github.com/google/jax/blob/fd61aca5a10c06c90f553460edf0efc1e8268845/jax/_src/ops/scatter.py#L93

followed by the cast here: https://github.com/google/jax/blob/fd61aca5a10c06c90f553460edf0efc1e8268845/jax/_src/ops/scatter.py#L114

The fix for this is probably relatively straightforward (rather than calling `promote_dtypes`, just cast `y` to the type of `x`) but it would probably change the behavior of `scatter` in some corner cases.

**Comment by hawkinsp** [comment]
Shouldn't this case be an error?

**Comment by jakevdp** [comment]
I think that's probably a good idea... but in order to allow people to do things like `x.at[ind].add(1)` we need to attempt to promote `y` to the dtype of `x`. Perhaps we can error if `x.dtype != result_type(x, y)`? What do you think?

**Comment by hawkinsp** [comment]
Yes. I think under no circumstances should we promote `x`, only `y`.
