### ISSUE TITLE
Cannot compute convolution

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [google/jax#10989]
I followed https://jax.readthedocs.io/en/latest/notebooks/convolutions.html and tried the first example of 1-dimensional convolution, copy-and-pasting the code onto a python file. But when I ran it, it failed and produced this error message:

`To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.`

I did that and got another error message.

`jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: CUDNN_STATUS_ALLOC_FAILED`

I tried jax.scipy.signal.convolve() but it's the same.

I'm running this on linux and python 3.10.4

**Comment by patrick-kidger** [comment]
Is this the error complaining about not being able to select a convolutional algorithm?

If so that's a nightmare bug that I've had to wrestle with before. Non-deterministically either of the following sometimes seems to help:

```python
import tensorflow as tf  # Yes, tensorflow. Even though we're using JAX.
tf.config.experimental.set_visible_devices([], 'GPU')
```

```python
import os
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = ".8"
```

in each case added to the very start of your Python script.

**Comment by k355l3r-5yndr0m3** [comment]
It worked. Thanks
