### ISSUE TITLE
How Jax lower jaxpr control flow into XLA?

### ISSUE THREAD

**Issue by adamantboy** [google/jax#10991]
### Discussed in https://github.com/google/jax/discussions/10990

<div type='discussions-op-text'>

<sup>Originally posted by **adamantboy** June  6, 2022</sup>
how jaxpr_subcomp deal with control flow primitives, when these eqns are lowered into XLA HLO? For example, cond, while, scan.</div>

**Comment by hawkinsp** [comment]
It looks like this was answered fully by the discussion.
