### ISSUE TITLE
Bitwise XOR missing as a `lax.reduce` operation

### ISSUE THREAD

**Issue by jewillco** [google/jax#11005]
The `lax.reduce` function includes bitwise AND and OR as possible reduction operations, but does not include XOR. Likewise, there is no specialized XOR-reduction function in JAX.

**Comment by jewillco** [comment]
No -- I don't know how to add that. Are there bitwise AND and OR reductions
already? Or are there only those reductions for logical operations?

-- Jeremiah Willcock

**Comment by jewillco** [comment]
I was looking at _get_monoid_reducer in
https://jax.readthedocs.io/en/latest/_modules/jax/_src/lax/lax.html#reduce;
is that relevant to what reduction ops are available?

-- Jeremiah Willcock

**Comment by jakevdp** [comment]
Yes, that's relevant here. And you'll see the list of currently available reducers here: https://github.com/google/jax/blob/879a94a05405a84d677d0ab049cfefe0169dc22b/jax/_src/lax/lax.py#L970-L990

**Comment by jakevdp** [comment]
Note that even without the specialization, you can currently compute an xor reduction manually:
```python
from jax import lax
import jax.numpy as jnp
result = lax.reduce(jnp.arange(6, dtype='uint8'), jnp.uint8(0), lax.bitwise_xor, (0,))
print(result)
# 1
```
