### ISSUE TITLE
jaxlib 0.1.61 without CUDA support not available in storage.googleapis.com

### ISSUE THREAD

**Issue by sergiuiacob1** [google/jax#11087]
A while ago some of us were depending on jaxlib 0.1.59, but that got removed from https://pypi.org/project/jaxlib/#history so the workaround was to upgrade jaxlib to 0.1.61.

Since upgrading is not always desirable/possible (i.e. dependencies, backwards compatibility etc), we switched to installing jaxlib 0.1.61 from https://storage.googleapis.com/jax-releases/jax_releases.html instead of https://pypi.org/project/jaxlib/#history in case 0.1.61 gets removed from pypi as well.

However, we're getting lots of warnings when loading jax:
```
2022-02-09 03:52:23.782602: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /backend/erts-11.2.2.6/lib:
```

Is there a way to add 0.1.61 for (linux x86_64, linux arm, macos x86_64, macos arm) to https://storage.googleapis.com/ as well?

**Comment by sergiuiacob1** [comment]
> What `pip` command did you run to install `jaxlib`?
> 
> If you look in the index, there are `nocuda` wheels there, e.g., https://storage.googleapis.com/jax-releases/nocuda/jaxlib-0.1.61-cp39-none-manylinux2010_x86_64.whl and in general we are archiving releases in that GCS bucket going forward.
> 
> I should note we have never released Linux ARM wheels, and while we now release Mac ARM I don't think we did that far back.

I'm using `pip install -f https://storage.googleapis.com/jax-releases/jax_releases.html jaxlib==0.1.61`

**Comment by sergiuiacob1** [comment]
I see. Correct me if I'm wrong, but in this case the only issue with the above solution is that the command would only work with linux systems, right?
My constraint is that I have the same `requirements.txt` file for multiple platforms (linux intel, linux arm, macos intel, macos arm).

Also, do you have any idea if and when 0.1.61 would be removed from PyPI? Is that still a concern?

**Comment by hawkinsp** [comment]
@yashk2810 Could we, as part of our release process, generate a separate `nocuda` package index that contains only the `nocuda` wheels?

**Comment by yashk2810** [comment]
Done.

Cuda index file: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

All others: https://storage.googleapis.com/jax-releases/jax_releases.html
