### ISSUE TITLE
Add depthwise convolutions to stax

### ISSUE THREAD

**Issue by untom** [google/jax#1114]
Hi there!

It would be great if depthwise convolutions could be added to stax. They're already in lax since #635, but it would be great if they'd be added in stax as well.

Best

Thomas

**Comment by xysun** [comment]
If no one has picked this up I'll have a go.

**Comment by anhangaba** [comment]
It would also be nice add support for [Mixed Convolution](https://arxiv.org/abs/1907.09595) in the depthwise layer, if supported by lax.

**Comment by TH3CHARLie** [comment]
@mattjj Is anyone currently working on this? If not, I'd like to take it as my first PR attempt in jax

**Comment by joaogui1** [comment]
@TH3CHARLie I believe #1496 is related

**Comment by hawkinsp** [comment]
We're not planning to keep evolving the current iteration of stax, in favor of libraries such as Flax and Haiku. I believe both already support depthwise convolution!

**Comment by conorturner** [comment]
Hi @hawkinsp, could you provide a link to the Flax implementation?
