### ISSUE TITLE
Improve error message when passing incorrect input_signatures to convert_and_save_model

### ISSUE THREAD

**Issue by jojennin** [google/jax#11181]
When using the [`convert_and_save_model`](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/examples/saved_model_lib.py#L33) function within the `experimental/jax2tf/examples` directory, I recently ran into an issue where I provided an `input_signatures` argument that was inconsistent with the expected input argument of my prediction function and the resulting error message was quite confusing.

To fully reproduce the error message I encountered, I have created the following gist:

https://gist.github.com/jojennin/19283842893c186e2629f1b14814594b

To summarize the gist, within the[ MNIST example provided in the examples subdirectory of jax2tf](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/examples/saved_model_main.py), I replaced the original input numpy array arguments to the prediction function with a dictionary of numpy arrays and did not change the `input_signatures` argument that is required for `convert_and_save_model`. After a long Traceback, this resulted in the following error message (shown in the logfile within the gist):

```
 File "./workspace/train_mnist_dict.py", line 67, in predict
    inputs = ddict['inputs']
 File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 601, in __getitem__
    def __getitem__(self, idx): return self.aval._getitem(self, idx)
 File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 3543, in _rewriting_take
    treedef, static_idx, dynamic_idx = _split_index_for_jit(idx, arr.shape)
 File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 3618, in _split_index_for_jit
    idx = _eliminate_deprecated_list_indexing(idx)
 File "/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py", line 3893, in _eliminate_deprecated_list_indexing
    raise TypeError(msg)
TypeError: Using a non-tuple sequence for multidimensional indexing is not allowed; use `arr[tuple(seq)]` instead of `arr[seq]`. See    https://github.com/google/jax/issues/4564 for more information.
```
Initially, this error message led me to believe that there was a problem with the prediction function itself and not the `input_signatures` and I spent quite a bit of time investigating the incorrect issue.  Would it be possible to improve the resulting error message that comes from passing the incorrect `input_signatures` argument to `convert_and_save_model`?

**Comment by zhangqiaorjc** [comment]
`convert_and_save_model ` is an example helper from `jax/experimental/jax2tf/examples/saved_model_lib.py`

@gnecula is it possible to assert that the pytree structures matches between input_signatures and actual inputs somewhere so the error message is more precise?

**Comment by gnecula** [comment]
@jojennin Thank you so much for the repro gist. I appreciate it. I was able to reproduce and I see the error. It is confusing, but I am not sure there is anything to be done in the tooling to prevent it. I wish Python had type checking.

Consider the following generic way to use jax2tf: 

```
def jax_f(jax_x): 
   ...

jax2tf.convert(jax_f)(tf_x)
```

The TF value `tf_x` must be of the same "type" as the expected parameter `jax_x` (in your case it should be a dictionary, but in your code you pass a TensorSpec). If is not there is no way for jax2tf or JAX or TF to discover it until you the function `jax_f` uses `jax_x` in a way that triggers a runtime value. 

I am closing the issue for now, feel free to reopen if you have ideas for fixing this that I missed.

**Comment by jojennin** [comment]
That makes sense. Thank you very much for your response and explanation @gnecula.
