### ISSUE TITLE
Allow symbolic zeros in custom derivatives

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#11208]
Feature request: to optionally not materialise symbolic zeros for (co)tangents to `custom_{jvp,vjp}`. Instead, pass the symbolic zero as-is and allow the user code to special-case their behaviour on which arguments have symbolic zeros.

When using `custom_{vjp,jvp}` in library code, it's common to accept a PyTree of arbitrary user-specified arguments, with respect to which derivatives are computed (my main use case is through a nonlinear solve via the implicit function theorem). Typically only some of those user-specified arguments are actually being differentiated, so the derivatives computed for the others are just a (potentially large) waste of computation.

This would also allow a solution to `jax.closure_convert` having to inefficiently hoist out all floating-point arrays: the custom derivative code will be able to determine which of these actually need a derivative and can ignore the others.

I'm imagining something like `custom_jvp(..., symbolic_zeros=True)`.

**Comment by froystig** [comment]
see also #5913

**Comment by patrick-kidger** [comment]
Addendum to this: the ability to return symbolic zeros from `custom_{jvp,vjp}`, for auxiliary information.

**Comment by typedfemale** [comment]
I would just like to voice my support for this, since it commonly comes up when trying to write novel optimizers 😇

**Comment by patrick-kidger** [comment]
Closing as this now exists! `jax.custom_jvp.defjvp(..., symbolic_zeros=True)`, and likewise for `custom_vjp`.

**Comment by NeilGirdhar** [comment]
Still needs documentation, right?  I guess when `symbolic_zeros` is true, tangents and cotangents have type `custom_derivatives.SymbolicZero` when they are both static and constant?

**Comment by froystig** [comment]
We had populated the `custom_jvp` and `custom_vjp` docstrings but the documentation wasn't rendering! That ought to be fixed by #16639.

Between that, #14570, and #15221, I believe that we can indeed close this.

**Comment by NeilGirdhar** [comment]
@froystig Awesome, looks like a very elegant design. What is the type of the "object with two attributes instead: ``value`` and ``perturbed``", also called "two-field record objects"?

**Comment by froystig** [comment]
Thanks for pointing that out. It's a `jax.custom_derivatives.CustomVJPPrimal`. #16693 should make that clearer.
