### ISSUE TITLE
Gradient of jax.nn.softplus raises error "KeyError: dtype([('float0', 'V')])"

### ISSUE THREAD

**Issue by chriscarmona** [google/jax#11253]
Computing the gradient of the softplus function raises an error (which indeed is not quite informative, and struggled to isolate it from my original code)

```python
import jax
from jax import numpy as jnp
jax.grad(jax.nn.softplus)(1.)
# KeyError: dtype([('float0', 'V')])
```
The problem seems to be solved by simply changing the definition of softplus

```python
# Doesn't work either
jax.grad(jax.jit(lambda x: jnp.logaddexp(x, 0)))(1.)
# Works
jax.grad(jax.jit(lambda x: jnp.logaddexp(x, 0.)))(1.)
```
I'd also appreciate if you could comment on what exactly goes wrong, I think is related to the internal function `_promote_args_inexact`

Thank you!

Best,
Chris

**Comment by hawkinsp** [comment]
I think this might be related to the recent NumPy 1.23 release. Try downgrading for the moment? We're working on a jax release.

**Comment by jakevdp** [comment]
This is the bug: https://github.com/google/jax/issues/11221

It's been fixed on main, but for now you can downgrade to numpy 1.22.4 or older to fix the issue.

**Comment by chriscarmona** [comment]
Thank you, downgrading numpy works for my code for now.
