### ISSUE TITLE
Pip install doesn't work

### ISSUE THREAD

**Issue by Navatso** [google/jax#11260]
pip install gives dependency error: 

ERROR: Cannot install lightweight-mmm==0.1.1, lightweight-mmm==0.1.2 and lightweight-mmm==0.1.3 because these package versions have conflicting dependencies.

The conflict is caused by:
    lightweight-mmm 0.1.3 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.2 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.1 depends on jaxlib>=0.3.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

I have tried pip installing the package into multiple new conda environments with different python versions from 3.6 to 3.9, none worked.

**Comment by jakevdp** [comment]
Thanks for the report! Could you tell us what `pip` command you ran when you encountered this error?

**Comment by Navatso** [comment]
I tried both methods:
The error that I posted here is with this one
pip install --upgrade pip
pip install lightweight_mmm
But I tried this one with no success:
pip install --upgrade git+https://github.com/google/lightweight_mmm.git

**Comment by Navatso** [comment]
This is the full error:

Collecting lightweight-mmm
  Using cached lightweight_mmm-0.1.3-py3-none-any.whl (53 kB)
Collecting frozendict
  Using cached frozendict-2.3.2-cp39-cp39-win_amd64.whl (35 kB)
Collecting tensorflow==2.7.2
  Using cached tensorflow-2.7.2-cp39-cp39-win_amd64.whl (436.7 MB)
Collecting numpy>=1.12
  Using cached numpy-1.23.0-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting seaborn==0.11.1
  Using cached seaborn-0.11.1-py3-none-any.whl (285 kB)
Collecting jax>=0.3.0
  Using cached jax-0.3.13.tar.gz (951 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting scipy
  Using cached scipy-1.8.1-cp39-cp39-win_amd64.whl (36.9 MB)
Collecting sklearn
  Using cached sklearn-0.0-py2.py3-none-any.whl
Collecting arviz==0.11.2
  Using cached arviz-0.11.2-py3-none-any.whl (1.6 MB)
Collecting numpyro>=0.8.0
  Using cached numpyro-0.9.2-py3-none-any.whl (283 kB)
Collecting absl-py
  Using cached absl_py-1.1.0-py3-none-any.whl (123 kB)
Collecting lightweight-mmm
  Using cached lightweight_mmm-0.1.2-py3-none-any.whl (48 kB)
Collecting tensorflow==2.5.3
  Using cached tensorflow-2.5.3-cp39-cp39-win_amd64.whl (428.3 MB)
Collecting seaborn
  Using cached seaborn-0.11.2-py3-none-any.whl (292 kB)
Collecting arviz
  Using cached arviz-0.12.1-py3-none-any.whl (1.6 MB)
Collecting lightweight-mmm
  Using cached lightweight_mmm-0.1.1-py3-none-any.whl (41 kB)
  Using cached lightweight_mmm-0.1.0-py3-none-any.whl (40 kB)

The conflict is caused by:
    lightweight-mmm 0.1.3 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.2 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.1 depends on jaxlib>=0.3.0
    lightweight-mmm 0.1.0 depends on tensorflow==2.4.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict


ERROR: Cannot install lightweight-mmm==0.1.0, lightweight-mmm==0.1.1, lightweight-mmm==0.1.2 and lightweight-mmm==0.1.3 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by jakevdp** [comment]
I’ve never heard of lightweight-mmm, but some googling leads to this page: https://github.com/google/lightweight_mmm you might have more luck asking a question there.

if I had to guess, though, I think your Python version is too old for the requirements listed by the package (recent versions of Jax require Python 3.7 or newer). Best of luck!
