### ISSUE TITLE
Would it be possible to upload Jax 0.3.14 to PyPi?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#11265]
Was uploading Jax 0.3.14 to PyPi overlooked?

**Comment by NeilGirdhar** [comment]
@sharadmv

**Comment by sharadmv** [comment]
Sorry we've been blocked on failing jaxlib builds for a bit now. I think it's fixed so I should be able to make a release tomorrow.

**Comment by NeilGirdhar** [comment]
@sharadmv Oh great!  Sorry for the bother.  I got excited about the release that you posted, and wasn't sure if someone just forgot to upload it.

**Comment by hawkinsp** [comment]
We've never actually *released* either version. We've tried a couple of times but never gotten something that passes all our presubmits.

The main thing blocking the `jaxlib` release is actually the vendored version of NCCL, which probably won't block your release. However, I think we need to come up with a release process that means you don't release `conda-forge` wheels until our wheels are ready.

We currently tag the release in Github when attempting to make a release, but do not actually ship the wheels until all of our presubmit testing passes. If the presubmits fail, we may update the tag. I'm guessing you took the most recent version of the tag?

**Comment by hawkinsp** [comment]
I'd hold off even longer. There are new test failures :-(

**Comment by sharadmv** [comment]
> Editing tags can be dangerous.

Heads up: I'll be needing to do this again to rollback some jaxlib changes that were breaking the build. I'll be trying to build wheels soon after that though.

**Comment by hawkinsp** [comment]
BTW, in case you're curious: our release process just runs the tests you see in our Github project. But it runs them for more of the matrix of OSes/Python versions/GPUs etc we support. It sometimes turns up problems that may not show up in our presubmit CI which only runs a handful of combinations (e.g., Mac builds).

**Comment by sharadmv** [comment]
JAX and Jaxlib 0.3.14 have been released on PyPI!

**Comment by sharadmv** [comment]
Yes it should be.
