### ISSUE TITLE
Very slow compile?  If you want to file a bug

### ISSUE THREAD

**Issue by gouchangjiang** [google/jax#11271]
Hi Dear developers of XLA,

I encountered an issue with a slow compilation of XLA as described in the title. Following is the whole warning:
'''
2022-06-27 14:06:50.915791: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55] 
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module jit_train_step.503
********************************
'''

The compilation can take 3 mins as shown in the output log:
'''
time    LOOP    COMPevl COMPtrn TRN+EVL 1stEVAL
(s)     1.0     6.1     225.7   9.3     0.6
'''

To produce this issue, just copy the [munet notebook](https://colab.research.google.com/github/google-research/google-research/blob/master/muNet/muNet.ipynb), and run it on an Nvidia A100 GPU. The issue will appear in around 10 mins. I am running it on 8 GPUs, hope running on one can also reproduce the issue. More details of muNet can be found [here](https://github.com/google-research/google-research/tree/master/muNet). The Jax and Jaxlib I am using are 0.3.4 and 0.3.2+cuda11.cudnn82 respectively.

Also, I followed the suggestion, run the notebook with the environment variable XLA_FLAGS, files are attached [here](https://drive.google.com/file/d/1I-FaGwCizI2cG4Bbz2IKdgFlzTyBxTAB/view?usp=sharing).

Another releated issue solved is [issue1769](https://github.com/google/jax/issues/1769).

Thank you in advance.

**Comment by gouchangjiang** [comment]
This issue raises only when running on 8 GPUs. On one GPU, it's as fast as running on TPUv2.

**Comment by gouchangjiang** [comment]
This issue also occurs with the latest version of JAX(0.3.13) and JAXLib(0.3.10).

**Comment by hawkinsp** [comment]
FWIW, the current version of `jax` and `jaxlib` is 0.3.14.

**Comment by gouchangjiang** [comment]
My bad, I should not say I am using the latest. 0.3.14 can not be installed from PIP since PIP does not have it now. Also, it seems that the munet script does not support parallel compilation even it calls function thread() in function train_loop. The compilation time does even increase a little when twice more cores given (from 8 cores to 16) cores. See the plot below. If you need any infos, just name it.
<img width="339" alt="企业微信截图_16566443108437" src="https://user-images.githubusercontent.com/7204483/176815039-1eeae0dd-3091-4495-bae6-7561407d2f27.png">

**Comment by xettrisomeman** [comment]
seems like there is no fix. 
![image](https://github.com/google/jax/assets/44607279/4d3851eb-9833-4d5e-abe8-72dc900a84e0)

**Comment by ecolss** [comment]
broken stuff..

**Comment by hawkinsp** [comment]
@ecolss Please file a new issue if you have an example of this problem. "Slow compile" could mean completely different things for different models.

**Comment by hawkinsp** [comment]
@xettrisomeman if you want us to look into this, please file a new issue with instructions on how to reproduce it.

**Comment by ecolss** [comment]
> @ecolss Please file a new issue if you have an example of this problem. "Slow compile" could mean completely different things for different models.

nvm, I've switched my code to pytorch

**Comment by pschuh** [comment]
For future people on this thread, I think the original bug in this thread (the munet example) compiles different programs for different devices (rather than using a single pmap or pjit for parallel devices). This has the following problems with scaling: parts of the XLA compiler are already parallelized, so additional parallelism won't help and jax tracing is single threaded, so it will scale poorly (or even worse as work bounces between competing python threads). Try to group computations into a single pjit or pmap which includes all devices and use XLA's inbuilt parallelism rather than trying to use python's parallelism.

**Comment by pschuh** [comment]
Closing to encourage people to post a unique bug with their slow compiles instead of adding to this bug.
