### ISSUE TITLE
Include examples in the documentation

### ISSUE THREAD

**Issue by atgctg** [google/jax#11283]
Whenever I encounter a new numpy function, I like to see how it is used in practice.

The numpy documentation conveniently includes examples in its API docs. For example, [numpy.reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html):
<img width="739" alt="numpy.reshape example" src="https://user-images.githubusercontent.com/105969161/176190217-2599c679-9ffb-4266-9903-2bd8aed9a24e.png">

I wish the JAX documentation also included examples.

If you think this is a good idea, I'd be willing to work on it!

**Comment by jakevdp** [comment]
Thanks for the suggestion!

There's some context and history here: the docstrings of `jax.numpy` functions are for the most part automatically generated from the numpy docstrings. Originally, this included examples, but users reported confusion given the fact that jax functions are at times more restrictive than their numpy counterparts (e.g. not acceptings lists in place of arrays). For this reason, in https://github.com/google/jax/pull/5945 we updated the doc generator to remove all examples from the auto-generated docstrings.

**Comment by atgctg** [comment]
Oh, I see — that's pretty neat! Guess I'm just gonna fall back to the numpy docs then for examples. Thanks for your quick answer:)
