### ISSUE TITLE
slow compiling compared to a few weeks ago

### ISSUE THREAD

**Issue by cpgoodri** [google/jax#1130]
I don't have a repo for this, but I have noticed a very significant (roughly 30x) slowdown in compilation when I run some jax code now compared to a few weeks ago (exact same code, no modifications at all). I'll share the code if needed, but it includes a number of vmap and scan calls. 

Have there been any updates recently that could possibly lead to such a slowdown?

Thanks!

**Comment by hawkinsp** [comment]
That's unfortunate!

There are frequent changes to JAX, any one of which might have caused your use case to regress. Without a reproduction we can run or bisecting the problem to a particular git revision it's going to be very hard to say what happened. Can you provide a self-contained, ideally small reproduction?

Thanks!

**Comment by cpgoodri** [comment]
I figured that was the case. I'll work on a *small* reproduction if the tests I'm working on don't lead anywhere.

**Comment by mattjj** [comment]
I think we spotted the issue in #1131 and fixed it in #1143. If you're able to pull the master branch, can you check? I'll also update pypi soon so you can check with that.

**Comment by mattjj** [comment]
Updated `jax` on pypi to version 0.1.41!

**Comment by cpgoodri** [comment]
Yes, I've been following #1131 religiously, thank you all for following up so fast! And yes, it completely solved the issue, my compile time for a particular calculation just went from 12 minutes to 20 seconds. 

Thanks again!

**Comment by hawkinsp** [comment]
Great! Sounds like everything is fixed!
