### ISSUE TITLE
Faster versions of isin, in1d, unique for integer arrays

### ISSUE THREAD

**Issue by MilesCranmer** [google/jax#11325]
Recently, faster versions of isin, in1d, and unique were added or proposed to numpy for 1D integer arrays, using lookup tables:

- https://github.com/numpy/numpy/pull/12065/
- https://github.com/numpy/numpy/pull/21843/

I am wondering about the feasibility of porting these to JAX. Currently, the JAX version of `in1d` is as follows:

https://github.com/google/jax/blob/7e09e63faaa54320e3ddf318a08d38b0bb54afe5/jax/_src/numpy/setops.py#L55-L58

This is $O(n^2)$ in both memory usage and compute for arrays of size $n$.

This proposed method, similar to a counting sort, is only $O(n+k)$ in compute and $O(k)$ in memory usage, for $k$ the range of input data. It's similarly reliant on vectorized array operations, rather than sorts, so it should be even faster in XLA than the current method.

Now, since JAX recompiles a function when the types change (?), so the control flow should not be an issue if this new method is only used for integer arrays. However, the array allocation will be equal to the range of input data (similar to a [counting sort](https://en.wikipedia.org/wiki/Counting_sort)). 

Therefore I am wondering if it is feasible to add this to JAX. The following implementations are possible:
- Add a `kind` parameter to `isin`, `in1d`, and `unique`, where `kind="table"` triggers this new faster method regardless of required allocation. Turn this method *off* by default.
- Using `lax.cond`, check the range of the input data, and only if the range is not too big, switch to this new method by default.

The other possibility which I strongly recommend against is to use this new method by default if the input arrays are integers. The reason I recommend against this is because the memory allocation may be massive even for small input arrays. (e.g., `unique([1, 1_000_000])` would allocate a one million-length array).

What do you think? I am happy to submit a PR if this is desirable.

CC'ing @jakevdp who looks to have worked on the set operations.

Cheers,
Miles

**Comment by MilesCranmer** [comment]
For jit compatibility, one could have a parameter to `isin` specifying the maxsize of the lookup table (e.g., 10,000), then do dynamic slicing of that.

If desired, I think the same thing could be done for `unique`, with the extra unused portions being set to `nan` or something.

**Comment by YouJiacheng** [comment]
FWIW, `lax.cond` only works without `vmap`, its batching rule is `lax.select`, which is not lazy.
I think user can implement such optimization by themselves.

**Comment by MilesCranmer** [comment]
Hi Jake,

Great questions. The cool thing about this method is it is not technically hash-based. The closest analogy to this comparison would be counting sorts vs radix sorts. A radix sort (https://en.wikipedia.org/wiki/Radix_sort) uses a hash table, whereas a counting sort (https://en.wikipedia.org/wiki/Counting_sort) pre-allocates an array of length equal to the range of integer data. A radix sort has scaling O(n*k), for k the key size, and a counting sort has scaling O(n+k), for k the range of your data. However, a counting sort might have a better constant in front of the scaling, for fixed k, since it avoids having to create the hash table, and gets to use super efficient array operations. This method is analogous to a counting sort, but a radix sort-like method is described on that blog (and would be useful for generic types).

(copied parts of my answer on the numpy mailing lists to a similar question: https://mail.python.org/archives/list/numpy-discussion@python.org/thread/3SJTDDF7D4VLZIUPQKHJMSYU2RVY3MHH/)

Here is basically how the method works, for `jnp.unique`:

1. `calloc` a "lookup table" with each element corresponding to an integer: `x = jnp.zeros(MAX_RANGE)`
2. Fill that table with 1 where a number exists in the array: `x[ar - ar_min] = 1`
3. Return the indices of elements with 1: return `jnp.nonzero(x) + ar_min`

So, the only "hash" here is `hash(integer) = integer`.

How fast are non-contiguous indexing operations in XLA, like segment_sum? If they are quick, then I think this method will be optimized in XLA. As long as the user chooses `kind="table"`, and pre-specifies a max range, then it should be optimized in XLA.

Thanks!
Miles

**Comment by jakevdp** [comment]
Looking at this again: for JAX, I think this is much less useful than for numpy due to the static array size criterion. We could not set `kind="table"` by default, because this would make these functions incompatible with JAX transforms like jit, vmap, and others unless the user provides additional static information about the size of the required table. This means it would be a breaking change.

On the other hand, we could use the default of `kind="sort"`, which would be backward compatible but would probably be ignored by the vast majority of users of these functions.

That said, I'm still in support of adding this argument, because numpy is adding it and we strive for feature parity with numpy.

**Comment by jakevdp** [comment]
@MilesCranmer are you interested in preparing a PR for this?

**Comment by MilesCranmer** [comment]
Sure, I can get around to this.

**Comment by jakevdp** [comment]
Closing since there's not been much action. Feel free to re-open this if you're interested in working on it!

**Comment by MilesCranmer** [comment]
Hey, sorry for never getting around to it @jakevdp... I sadly find I'm just too busy these days maintaining things 😪
