### ISSUE TITLE
Unable to get jax.profiler to work on TPU in the latest version of JAX

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#11362]
Although I just encountered this error when using JAX 0.3.14, I have encountered the error for many times with various versions of JAX.

The cause of the error is obvious. `jax.profiler` depends on Tensorflow, while Tensorflow is not automatically installed when installing JAX in a new virtual environment. Therefore, `jax.profiler` will not work, and it shows this error:

```
2022-07-04 21:27:10.631029: E external/org_tensorflow/tensorflow/python/profiler/internal/python_hooks.cc:369] Can't import tensorflow.python.profiler.trace
```

It is not possible to resolve this issue by installing Tensorflow from pip directly, because the default Tensorflow version is not compiled with TPU support.

The only way to solve the issue seems to be compiling Tensorflow from source, but compiling Tensorflow from source results in another error.

---

This is the method I used to compile Tensorflow from source.

JAX version 0.3.14

Locate https://github.com/google/jax/blob/jaxlib-v0.3.14/WORKSPACE#L13. The line suggests that JAX 0.3.14 is compatible with Tensorflow commit `d250676d7776cfbca38e8690b75e1376afecf58d`.

Then, I compiled Tensorflow by this script:

```sh
#!/bin/bash
set -e
set -v
sudo rm -rf ~/.cache/bazel  # clear bazel cache (see tensorflow#55563)
export TENSORFLOW_SHA=d250676d7776cfbca38e8690b75e1376afecf58d
wget -nc https://github.com/tensorflow/tensorflow/archive/$TENSORFLOW_SHA.tar.gz
tar zxf $TENSORFLOW_SHA.tar.gz
rm -f $TENSORFLOW_SHA.tar.gz
mv tensorflow-$TENSORFLOW_SHA tensorflow
cd tensorflow
export BAZEL_VERSION=`cat .bazelversion`
sudo mkdir -p /usr/local/lib/bazel/bin
sudo wget -nc -P /usr/local/lib/bazel/bin https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION/bazel-$BAZEL_VERSION-linux-x86_64
sudo chmod +x /usr/local/lib/bazel/bin/bazel-$BAZEL_VERSION-linux-x86_64
rm -rf ~/.venv310
python3.10 -m venv ~/.venv310
. ~/.venv310/bin/activate
pip install -U pip
pip install -U wheel
pip install -U packaging
pip install -U keras_preprocessing --no-deps
pip install "jax[tpu]==0.3.14" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
yes '' | python configure.py  # use the default settings
bazel build --config=tpu //tensorflow/tools/pip_package:build_pip_package
./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
ls /tmp/tensorflow_pkg/tensorflow-*.whl
```

However. I got this error:

```
2022-07-04 21:11:18.248361: F ./tensorflow/core/tpu/tpu_library_init_fns.inc:34] TpuEmbeddingEngineState_Create not available in this library.
```

I know that this error occurs when the libtpu version is not compatible with the Tensorflow version. Previously I always fixed it by recompiling Tensorflow from source. However, this time the error occurred when I was compiling Tensorflow from source, so I do not know what to do.

@skye

**Comment by sharadmv** [comment]
What are you trying to do with the profiler? You may not need TensorFlow installed to accomplish what you want to do and the `Can't import tensorflow.python.profiler.trace` error may be misleading. (Note that I was able to get rid of the error by just running `pip install tensorflow`).

I tried using `jax.profiler.trace` in a fresh Cloud TPU VM w/o TensorFlow installed and it worked fine. If you're using `tensorboard` or `python -m jax.collect_profile`, you'll need TF installed.

**Comment by ayaka14732** [comment]
> If you're using `tensorboard` or `python -m jax.collect_profile`, you'll need TF installed.

Yes, I am using `tensorboard`.

> Note that I was able to get rid of the error by just running `pip install tensorflow`

I've just tried and this is true, but I still want to install the appropriate TPU version of Tensorflow.

**Comment by sharadmv** [comment]
If you just want to get the profiler to work, you only need the TensorFlow from `pip` along with `tbp-nightly`. I was able to capture a trace using the instructions here: https://jax.readthedocs.io/en/latest/profiling.html#installation. Do you need TPU-compatible TensorFlow for something else?

**Comment by ayaka14732** [comment]
I compiled a CPU version of Tensorflow and it works. For my other Tensorflow projects I will create a different virtual environment.

**Comment by sharadmv** [comment]
@skye do we expect TF TPU and JAX TPU to play nicely here?

**Comment by skye** [comment]
Not really. The only supported way to use TF in a Cloud TPU VM is to create a VM with a TF image (https://cloud.google.com/tpu/docs/run-calculation-tensorflow#create_a_vm_or_node_with_gcloud), although you can build from source if you know what you're doing like @ayaka14732 apparently does :slightly_smiling_face: , and even with this we don't support running TPU-enabled TF and JAX in the same process. So using regular CPU-only pip-installed TF is the best way to go for profiling, like Sharad does above.
