### ISSUE TITLE
Development of `jax.scipy.sparse.linalg`

### ISSUE THREAD

**Issue by tianjuxue** [google/jax#11376]
For scientific computing purposes, JAX has been a great tool for me to build numerical solvers for PDE/ODE. This is to say, it is often desired to solve sparse linear systems. Currently JAX has `bicgstab`, `cg` and `gmres`, but the implementation seems not finished. For example, the following code throws **NotImplementedError: scatter transpose is only implemented whereunique_indices=True**

 ```
import jax.numpy as np

def A(x):
    y = 2*x
    ind = np.array([1, 2])
    y = y.at[ind].set(x[ind])
    return y

b = np.ones(10)
# Yet, jax.scipy.sparse.linalg.cg will NOT throw an exception
sol, info = jax.scipy.sparse.linalg.bicgstab(A, b)
```

The problem is at the line of `y = y.at[ind].set(x[ind])`, and this line can be thought as setting Dirichlet boundary conditions.

Perhaps a more general question is, will JAX continuously support and improve sparse linear solvers in the future?

Thank you,
Tianju

**Comment by YouJiacheng** [comment]
This is not the problem of solver, but the "limitation" of reverse-mode autodiff, linear transpose of scatter without `unique_indices` cannot be well defined.
I believe your problem can be solved by replace `y = y.at[ind].set(x[ind])` with `y = y.at[ind].set(x[ind],unique_indices=True)` as the raised error suggested.

**Comment by tianjuxue** [comment]
Thank you for the solution and the pointer. Closing the issue now.
