### ISSUE TITLE
GCD should protect against divide by zero

### ISSUE THREAD

**Issue by awf** [google/jax#11378]
In GCD, this line can unconditionally cause some divide-by-zeros in `rem(x1,x2)`
 https://github.com/google/jax/blob/b2d70058c7e93135842030193d9ceeed3e9c008f/jax/_src/numpy/lax_numpy.py#L4060

The corresponding tensorflow implementation protects against this.  Is there a reason why JAX doesn't need to?

https://github.com/tensorflow/tensorflow/blob/0ed3a6bf355bb8199ac9f85b11231558376df00d/tensorflow/python/ops/numpy_ops/np_math_ops.py#L495

Happy to PR to fix if this isn't by design.

**Comment by hawkinsp** [comment]
The reason is simple enough: the JAX `mod`/`div` operators don't issue errors on division by zero. So there's no need to defend against it.

**Comment by awf** [comment]
Thanks - I didn't find docs on this, but I assume it's inherited from https://www.tensorflow.org/xla/operation_semantics#element-wise_binary_arithmetic_operations, which says 'produces an implementation defined value', i.e. does not throw?

I might PR a doc fix of this form (for all ops) -- LMK if that would not be useful
```python
def div(x: Array, y: Array) -> Array:
  r"""Elementwise division: :math:`x \over y`.

  Wraps XLA's `Div
  <https://www.tensorflow.org/xla/operation_semantics#element-wise_binary_arithmetic_operations>`_ operator.
  """
  return div_p.bind(x, y)
```

**Comment by hawkinsp** [comment]
I think in general I would want to avoid linking to the XLA docs for this kind of doc string. Better to keep things self-contained. If you wanted to send a PR adding language like "returns an implementation-defined value on ..." then that'd work well.

**Comment by awf** [comment]
I copied that 'Wraps XLA'S...' pattern from `DynamicSlice` and others.

I guess the natural aspiration now is to lift all of those docs into JAX, to make JAX's semantics independent of XLA? Again, I would be happy to do that.

**Comment by hawkinsp** [comment]
Yes. I think so. However, I feel more strongly that `div` has self-contained documentation than something large and complicated like `gather`.
