### ISSUE TITLE
improve error message for jnp.diagonal

### ISSUE THREAD

**Issue by ilemhadri** [google/jax#11396]
```python
import jax.numpy as jnp
import numpy as np
M = jnp.ones(5)
```

Then, `np.diagonal(M)` returns a clear error message `ValueError: diag requires an array of at least two dimensions` whereas `jnp.diagonal(M)` returns a still-informative-but-less-clear `ValueError: axis 1 is out of bounds for array of dimension 1`.

Could we possibly change this behavior?

**Comment by jakevdp** [comment]
Thanks for the report - we should be able to improve that message.
