### ISSUE TITLE
i need jaxlib source

### ISSUE THREAD

**Issue by JiepingLLL** [google/jax#11450]
Hello! I want to complete some neural network projects through jax locally, but since the jaxlib on the Internet is precompiled, I can't find the source code of jaxlib, which makes my platform environment unusable. I use python3.6 version, So I want the source code of jaxlib to support my platform to complete the compilation and installation, I will be very grateful if you can provide it!

**Comment by hawkinsp** [comment]
Also note that we no longer support Python 3.6 (per our deprecation policy), so you'd have to build an older version.

**Comment by JiepingLLL** [comment]
thank you for your reply! Do I start with the link you posted above if I build it myself? By the way, I saw that there is a jaxlib release on the right side of the code module on the home page, which contains many versions, and the display is the source code. Can I use it?

**Comment by jakevdp** [comment]
If you want to build jaxlib, I'd suggest starting with the link above to the README section about building jaxlib. You could probably do that using the release tarballs linked from the github page, but those are automatically created by github when a release is tagged, and I don't have experience with using them in a build. You might be better off checking out the appropriate release tag in the github repository.
