### ISSUE TITLE
jax gpu support with nvidia 5.15?

### ISSUE THREAD

**Issue by cottrell** [google/jax#11477]
I recently upgraded and was hitting this error:

    kernel version 515.48.7 does not match DSO version 510.73.5 -- cannot find working devices in this configuration

Downgrading to:

        sudo apt install nvidia-driver-510

and reinstalling:     sudo apt install nvidia-cuda-toolkit

brought it back to working state again.

Am posting this here to ask if anyone has 515 working and hopefully this helps anyone else landing in this same spot (as you will now land here with Ubuntu 22.04 accepting all defaults I think).

**Comment by hawkinsp** [comment]
I think this isn't a JAX issue. (e.g., does any CUDA program work, or even things like `nvidia-smi`?): I'd guess you have a version mismatch between your kernel and installed libraries. Perhaps rebooting may help?
