### ISSUE TITLE
Add window reversal option to JAX convolutions

### ISSUE THREAD

**Issue by jewillco** [google/jax#11483]
XLA supports a `window_reversal` parameter to convolutions (such as the `xla::ConvGeneralDilated` builder function), and parts of JAX (such as the MLIR generator) set it. However, the user-level convolution APIs in JAX do not provide the option to reverse convolution windows. It would sometimes be convenient to write JAX code that performs reversal implicitly in the convolution rather than modifying the kernel itself.

**Comment by mattjj** [comment]
Thanks for the request! We (@jwellico, @blakehechtman, and I) discussed more off-thread and found that:
1. using the `window_reversal` option is semantically equivalent to (i.e. computes the same values as) applying a `jax.lax.rev(rhs, [i for i, b in enumerate(window_reversal) if b])` to the `rhs` input of the convolution, and
2. XLA:TPU and [XLA:GPU will](https://github.com/tensorflow/tensorflow/blob/ea243b9ea469547acf0fa68b054b4959a8075b21/tensorflow/compiler/xla/service/gpu/gpu_conv_rewriter.cc#L310) fuse a `Rev` HLO on the `rhs` input into the generated convolution, so there's no  efficiency win to be had to build the `window_reversal` option into the `conv_general_dilated` JAX primitive compared to just applying the `jax.lax.rev` function separately.

So the recommendation here is just to apply a ` jax.lax.rev`, like `jax.lax.rev(rhs, [i for i, b in enumerate(window_reversal) if b])` or similar, if you want to express something like this!
