### ISSUE TITLE
jax.numpy.reciprocal/remainder docstring

### ISSUE THREAD

**Issue by ilemhadri** [google/jax#11492]
In https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.reciprocal.html#jax.numpy.reciprocal, the link to the numpy implementation actually self-references the jax version.

Instead, it should point to https://numpy.org/doc/stable/reference/generated/numpy.reciprocal.html

The same applies for remainder: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.remainder.html#jax.numpy.remainder

**Comment by jakevdp** [comment]
Thanks for the report – this seems to be an issue widely within the package. At some point I fixed this, but it's back to self-references... I'm not sure what changed.

**Comment by jakevdp** [comment]
Looks like the problem is that `np.reciprocal`, like all ufuncs, does not report its `__module__`:
```
>>> np.reciprocal.__module__
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-119f1fb53b4a> in <module>
----> 1 np.reciprocal.__module__

AttributeError: 'numpy.ufunc' object has no attribute '__module__'
```
and this is the mechanism that JAX's doc generation function uses to generate this link.

**Comment by jakevdp** [comment]
Fundamentally, the problem is that given a `numpy.ufunc` object, there appears to be no way to know what its import path is, or even which package defined it!
