### ISSUE TITLE
tree_util deprecation warnings should set warning class and stacklevel

### ISSUE THREAD

**Issue by shoyer** [google/jax#11505]
If I try using deprecated functions like `jax.tree_map` using the development version of JAX, I see messages like:
```
>>> jax.tree_map(lambda x: x, [1, 2, 3])
/usr/local/lib/python3.7/dist-packages/jax/_src/tree_util.py:529: UserWarning: jax.tree_map is deprecated, and will be removed in a future release. Use jax.tree_util.tree_map instead.
  warnings.warn(f"jax.{f.__name__} is deprecated, and will be removed in a future release. "
[1, 2, 3]
```

This is OK, but a better warning would set `category` (so it can be filtered appropriately) and `stacklevel` (so it's clear to users where it's coming from).

Either `DeprecationWarning` or `FutureWarning` would be appropriate for the category, depending on how "noisy" you want the warnings to be. I would probably lean towards `FutureWarning` for JAX, since JAX is typically used by developers rather than end users.

**Comment by jakevdp** [comment]
Thanks - that was an oversight on my part. Fixed in #11507
