### ISSUE TITLE
Inaccurate `jax.scipy.special.zeta(s, a)` for negative `s`

### ISSUE THREAD

**Issue by Gattocrucco** [google/jax#11521]
For positive integer values of s, the Hurwitz zeta function zeta(1-s,a) is even/odd relative to a=1/2 in the interval 0 < a < 1 (https://dlmf.nist.gov/25.11#E9). The JAX implementation does not respect this. Apart from that, the values also seem wrong.

```python
import jax
from jax import numpy as jnp
jax.scipy.special.zeta(1-jnp.arange(1, 20)[:, None], jnp.array([0, 0.5, 1]))
```

Output:

```python
DeviceArray([[ 5.00000000e-01,  0.00000000e+00, -5.00000000e-01], # s = 1
             [-8.33333333e-02,  4.16666667e-02, -8.33333333e-02],
             [ 7.10542736e-14,  0.00000000e+00, -8.52651283e-14], # <- odd s is bad from here
             [ 8.33333333e-03, -7.29166667e-03,  8.33333333e-03],
             [-1.09139364e-11,  7.27595761e-12, -2.18278728e-11],
             [-3.96825379e-03,  3.84424604e-03, -3.96825373e-03],
             [ 1.86264515e-09,  0.00000000e+00,  3.72529030e-09],
             [ 4.16666269e-03, -4.13411856e-03,  4.16666269e-03],
             [ 4.76837158e-07,  0.00000000e+00, -4.76837158e-07],
             [-7.58361816e-03,  7.55310059e-03, -7.57598877e-03], # <- even s is bad from here
             [-6.10351562e-05,  0.00000000e+00,  1.22070312e-04],
             [ 2.24609375e-02, -2.34375000e-02,  1.75781250e-02],
             [-1.56250000e-02,  3.12500000e-02,  6.25000000e-02],
             [ 2.50000000e-01, -5.00000000e-01,  0.00000000e+00],
             [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
             [ 6.40000000e+01,  0.00000000e+00,  0.00000000e+00],
             [ 2.04800000e+03,  0.00000000e+00,  0.00000000e+00],
             [ 1.63840000e+04, -3.27680000e+04, -6.55360000e+04],
             [ 0.00000000e+00,  0.00000000e+00, -1.04857600e+06]],            dtype=float64)
```

**Comment by YouJiacheng** [comment]
JAX use algorithm proposed in https://arxiv.org/pdf/1309.2877.pdf
which requires the real part of `s` is large(positive) enough.

**Comment by jakevdp** [comment]
This code was added in #3385. @fehiepsi as the original author, do you have any ideas of how to approach this?

**Comment by Gattocrucco** [comment]
I would implement it in the following way:

1) For s > -10, use https://dlmf.nist.gov/25.11.E3 to have |1-a| <= 1/2, and then sum the series https://dlmf.nist.gov/25.11.E10.

2) For larger negative s, write the Hurwitz zeta in terms of the periodic zeta https://dlmf.nist.gov/25.13.E3 and compute the periodic zeta by summing the series https://dlmf.nist.gov/25.13.E1.

I needed the periodic zeta in the first place, so I have not completed this, my partial implementation of the Hurwitz zeta is [here](https://github.com/Gattocrucco/lsqfitgp/blob/66011f0f341db40052965fc56bbab51a03a954dc/lsqfitgp/_patch_jax.py#L605-L617).

**Comment by fehiepsi** [comment]
The formula that we use in the current implementation seems to assume z > 1. For negative `s`, I guess we can follow your approach.

**Comment by Gattocrucco** [comment]
Closing because jax 0.4.16+ has new implementation that outright forbids $s<1$.
