### ISSUE TITLE
Colab flakiness.

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#1156]
This will probably be a pretty difficult issue to track down, but I thought I'd at least start raising it. I've been experiencing some flakiness in colab (both internal and external). It seems to be deterministic in the sense that code that fails will fail repeatedly, but it is difficult to make a repro since it seems pretty sensitive to order of commands being executed. The issue also seems to have appeared somewhat recently.

The error I've most commonly been seeing is something like,
```
/usr/local/lib/python3.6/dist-packages/jax/api.py in f_jitted(*args, **kwargs)
    138     flat_fun, out_tree = flatten_fun_leafout(f, in_tree)
    139     out = xla.xla_call(flat_fun, *args_flat, device_values=device_values,
--> 140                        device_assignment=device_assignment)
    141     return out if treedef_is_leaf(out_tree()) else tree_unflatten(out_tree(), out)
    142 

/usr/local/lib/python3.6/dist-packages/jax/core.py in call_bind(primitive, f, *args, **params)
    661   if top_trace is None:
    662     with new_sublevel():
--> 663       ans = primitive.impl(f, *args, **params)
    664   else:
    665     tracers = map(top_trace.full_raise, args)

/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py in _xla_call_impl(fun, *args, **params)
    690                                *map(abstractify, args))
    691   try:
--> 692     return compiled_fun(*args)
    693   except FloatingPointError:
    694     print("Invalid value encountered in the output of a jit function. "

/usr/local/lib/python3.6/dist-packages/jax/interpreters/xla.py in _execute_compiled(compiled, pval, handle_result, *args)
    718   device_num, = compiled.DeviceOrdinals()
    719   input_bufs = [device_put(x, device_num) for x in args]
--> 720   out_buf = compiled.Execute(input_bufs)
    721   check_nans("jit-compiled computation", out_buf)
    722   return pe.merge_pvals(handle_result(out_buf), pval)

RuntimeError: Internal: Unable to launch kernel
```

Here's an extremely large repro that, when run using a GPU on OSS colab, will produce the above result. Let me know if I can help out with debugging this at all!

https://colab.sandbox.google.com/drive/1rc8yhxLq2MF1Bdyl55dmsMEOCEOh2pXz#scrollTo=U3oEzzLpK5Mw

**Comment by dynamicwebpaige** [comment]
Tagging in @craigcitro from the Colab team.

**Comment by craigcitro** [comment]
Interestingly, this one fails differently for me:

![image](https://user-images.githubusercontent.com/468559/66703742-7a3edd80-ecca-11e9-9a8e-fcee9f4c0205.png)

A few thoughts:

* if you can repro, I'd try hitting ctrl-shift-p -> runtime logs and see if there's anything useful getting logged when it fails.

* similarly, if you can repro internally, I'll have way more ability to help dig. ;)

* I think it'd be worth trying to pare down this repro; in particular, I'd start by pinning the versions you're installing via pip, and see if that makes the repro more reliable (or makes it disappear), as well as trying to strip out unrelated code.

**Comment by sschoenholz** [comment]
Nope, everything has been working great lately! Thanks for reminding me that I had raised this issue.
