### ISSUE TITLE
jax.lax.cond evaluates None as True

### ISSUE THREAD

**Issue by jemisjoky** [google/jax#11574]
When using `jax.lax.cond`, passing `None` as the first argument causes the `true_fun` argument to get called. This is contrary to the behavior one would expect for Python if statements.

For example, running the following
```python
import jax

true_fun = lambda x: True
false_fun = lambda x: False

for pred in [True, False, None]:
	print(pred, jax.lax.cond(pred, true_fun, false_fun, None))
```

gives the following output:
```
True True
False False
None True
```

I am using the newest PyPI versions of `jax` and `jaxlib` (0.3.14).

**Comment by jakevdp** [comment]
I suppose a better behavior here would be to raise an error when `None` is passed in a place where a JAX array is expected.

**Comment by jemisjoky** [comment]
That would work. The only thing to keep an eye on is the documentation of `jax.lax.cond`, which currently says:

```
cond() has equivalent semantics to this Python implementation:

  def cond(pred, true_fun, false_fun, *operands):
    if pred:
      return true_fun(*operands)
    else:
      return false_fun(*operands)
```

Since `bool(None)` is `False`, some caveat would be helpful to warn users about unexpected errors that wouldn't arise in the Python equivalent.

Regardless, throwing an error is still better than the present situation, since the branch that is selected is currently the opposite of what the documentation implies.
