### ISSUE TITLE
How to slice when using @mask?

### ISSUE THREAD

**Issue by terhorst** [google/jax#11583]
```
@partial(mask, in_shapes=["n"])
def f(x):
  return x[1:]
x = np.arange(10)
f([x], dict(n=5))
# IndexError: Cannot use NumPy slice indexing on an array dimension whose size is not statically known (n). Try using lax.dynamic_slice/dynamic_update_slice
```

lax.dynamic_slice won't work because I don't know the size of the array, or rather is a PolymorphicShape object that is not recognized as a static length.

**Comment by mattjj** [comment]
Thanks for the question!

`jax.mask` is being deprecated. Someday we'll replace it with something better, but that something isn't ready yet. (This is a classic meme: old thing deprecated, new thing not ready yet...) It looks like [slicing doesn't work with it](https://github.com/google/jax/blob/6110be40dc66f0de9d0e3770645a7db81434910f/tests/masking_test.py#L643) anyway, as you found.

If you want to perform slicing with a padded array, we can "write it out manually" in a few different ways, e.g.:

```python
def f(x_padded, x_len):
  xx = jnp.concatenate([x, x])
  y_padded = xx[1:1+len(x_padded)]  # works if we replace `1` with any value in 0 .. len(x_padded)
  return y_padded, x_len - 1
```

This is basically spelling out what `mask` would do internally, i.e. represent a logical array with a padded-out physical array and some integers representing its logical shape (here just a single integer).

What do you think?

**Comment by terhorst** [comment]
Got it. Thanks for the quick reply as always!
