### ISSUE TITLE
scan produces wrong results

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#11586]
Consider the following simple program, with `theta > 1` (e.g. theta=2) we get wrong outputs, while things are expected with theta <= 1.0

```python
from jax import random
import jax

rng_key = random.PRNGKey(12)
theta = 2.0

noise = random.normal(shape=(2000,), key=rng_key)
noise = noise.at[0].set(0.0)
ys = noise[1:] + theta * noise[:-1]

def body_fn(noise, y):
  noise_new = y - theta * noise
  return noise_new, noise_new

expected = noise[1:]
actual = jax.lax.scan(body_fn, 0.0, ys)[1]
print(expected)
print(actual)
```

This issue is observed by @paulsbrookes in https://github.com/pyro-ppl/numpyro/issues/1453

**Comment by jakevdp** [comment]
Isn't this just a matter of accumulating floating point roundoff errors? Say you're off by 1E-16 in the first step... by the hundredth step, you've effectively multiplied this error by theta^100... so any time theta is even marginally larger than 1, it will blow up.

**Comment by fehiepsi** [comment]
Oh, good point! This is interesting...

**Comment by fehiepsi** [comment]
Thanks, @jakevdp!
