### ISSUE TITLE
Target //build:install_xla_in_source_tree failed to build

### ISSUE THREAD

**Issue by qwertpi** [google/jax#1160]
While compiling I got the following error
```
INFO: Analyzed target //build:install_xla_in_source_tree (109 packages loaded, 10023 targets configured).
INFO: Found 1 target...
ERROR: /home/rory/jax/jaxlib/BUILD:24:1: Executing genrule //jaxlib:lapack.pyx_cython_translation failed (Exit 1)
module.js:540
    throw err;
    ^

Error: Cannot find module '/home/rory/.cache/bazel/_bazel_rory/7428d4622c43829d3557b4741ba55bca/execroot/__main__/python'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Target //build:install_xla_in_source_tree failed to build
INFO: Elapsed time: 496.624s, Critical Path: 1.84s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by hawkinsp** [comment]
Can you say more about what platform you are building on and what version of `jax` you have? Could you perhaps use one of the prebuilt wheels instead?

Do you have `cython` and `scipy` installed?

**Comment by qwertpi** [comment]
> Can you say more about what platform you are building on and what version of `jax` you have? Could you perhaps use one of the prebuilt wheels instead?
> 
> Do you have `cython` and `scipy` installed?

I'm building on x86 Ubuntu Xenial, I'm using an Intel Celeron 3215U, when I use the prebuilt wheels I get an `Illegal instruction (core dumped)` error when running jax.grad (I've had these before with tensorflow due to the use of AVX instructions which my CPU doesn't support). I have scipy installed but didn't have cython installed a compile-time although by complete coincidence do have it installed now

**Comment by hawkinsp** [comment]
Is this still a problem with an up to date `jaxlib`? (Closing, but reopen if you can still reproduce.)
