### ISSUE TITLE
Regression: CustomCall with side effect gets optimized out

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#11620]
Since JAX 0.3.15, our MPI CustomCalls are getting optimized out even though they are declared as having side effects (`has_side_effect=True`).

Example:

```python
import os
os.environ["MPI4JAX_DEBUG"] = "1"

import jax
import jax.numpy as jnp

from mpi4py import MPI
from mpi4jax import send

comm = MPI.COMM_WORLD
assert comm.Get_size() == 1

@jax.jit
def send_jit(x):
    send(x, dest=0, comm=comm)


print("send without JIT")
send(jnp.ones(10), dest=0, comm=comm)

print("send with JIT")
send_jit(jnp.ones(10))
```

With `jax==0.3.15`, the second call prints no debug information, indicating that `send` is being optimized out:

```bash
send without JIT
r0 | ie1Jnxae | MPI_Send -> 0 with tag 0 and 10 items
r0 | ie1Jnxae | MPI_Send done with code 0 (4.43e-05s)
send with JIT
``` 

With `jax==0.3.14` I get the expected output:

```bash
send without JIT
r0 | NCAn8Kbh | MPI_Send -> 0 with tag 0 and 10 items
r0 | NCAn8Kbh | MPI_Send done with code 0 (3.68e-05s)
send with JIT
r0 | Cn7a5QRb | MPI_Send -> 0 with tag 0 and 10 items
r0 | Cn7a5QRb | MPI_Send done with code 0 (5.04e-06s)
```

**Comment by sharadmv** [comment]
I double checked the optimized HLO and it's still there:
Pre-compiled HLO
```
HloModule jit_send_jit.1, entry_computation_layout={(f32[10]{0})->f32[10]{0}}

xla_fallback_send_mpi.3 {
  constant.6 = s32[] constant(10)
  Arg_0.4 = f32[10]{0} parameter(0)
  constant.7 = s32[] constant(0)
  constant.8 = u64[] constant(139673914379968)
  constant.9 = u64[] constant(139673914351872)
  Arg_1.5 = token[] parameter(1)
  custom-call.10 = (token[]) custom-call(constant.6, Arg_0.4, constant.7, constant.7, constant.8, constant.9, Arg_1.5), custom_call_target="mpi_send", custom_call_has_side_effect=true
  ROOT get-tuple-element.11 = token[] get-tuple-element(custom-call.10), index=0
}

send_mpi.12 {
  Arg_0.13 = f32[10]{0} parameter(0)
  Arg_1.14 = token[] parameter(1)
  ROOT call.15 = token[] call(Arg_0.13, Arg_1.14), to_apply=xla_fallback_send_mpi.3
}

ENTRY main.17 {
  ROOT Arg_0.1 = f32[10]{0} parameter(0)
  after-all.2 = token[] after-all()
  call.16 = token[] call(Arg_0.1, after-all.2), to_apply=send_mpi.12
}
```

Optimized HLO:
```
HloModule jit_send_jit.2, entry_computation_layout={(f32[10]{0})->f32[10]{0}}

ENTRY %main.17 (Arg_0.1: f32[10]) -> f32[10] {
  %constant.4 = s32[] constant(10)
  %Arg_0.1 = f32[10]{0} parameter(0)
  ROOT %copy = f32[10]{0} copy(f32[10]{0} %Arg_0.1)
  %constant.5 = s32[] constant(0)
  %constant.10 = u64[] constant(139673914379968)
  %constant.11 = u64[] constant(139673914351872)
  %after-all.2 = token[] after-all(), metadata={op_name="jit(send_jit)/jit(main)/create_token" source_file="/usr/local/google/home/sharadmv/workspace/mpi4jax/mpi4jax/_src/collective_ops/send.py" source_line=54}
  %custom-call.1 = (token[]) custom-call(s32[] %constant.4, f32[10]{0} %copy, s32[] %constant.5, s32[] %constant.5, u64[] %constant.10, /*index=5*/u64[] %constant.11, token[] %after-all.2), custom_call_target="mpi_send", custom_call_has_side_effect=true, metadata={op_name="custom-call.8"}
}
```

I think this is an async issue (the Python program is ending before the message can happen).

I was able to get it to show up in this repro:
```python
import os
os.environ["MPI4JAX_DEBUG"] = "1"

import jax
import jax.numpy as jnp

from mpi4py import MPI
from mpi4jax import send

comm = MPI.COMM_WORLD
assert comm.Get_size() == 1

@jax.jit
def send_jit(x):
    send(x, dest=0, comm=comm)
    return x


print("send without JIT")
send(jnp.ones(10), dest=0, comm=comm)

print("send with JIT")
send_jit(jnp.ones(10)).block_until_ready()
```

Output:
```
r0 | 9zBLijKJ | MPI_Send -> 0 with tag 0 and 10 items
r0 | 9zBLijKJ | MPI_Send done with code 0 (2.90e-05s)
send with JIT
r0 | LyW0FOeZ | MPI_Send -> 0 with tag 0 and 10 items
r0 | LyW0FOeZ | MPI_Send done with code 0 (7.85e-06s)
```

**Comment by dionhaefner** [comment]
Huh. Actually, `mpi4jax` registers an `atexit` handler to prevent this kind of stuff:

```python
def flush(platform):
    """Wait for all pending XLA operations"""
    devices = jax.devices(platform)

    for device in devices:
        # as suggested in jax#4335
        noop = jax.device_put(0, device=device) + 0
        noop.block_until_ready()
```

Is that not sufficient anymore to wait for all async operations? 🤔

**Comment by dionhaefner** [comment]
That doesn't seem to be it. I get the same behavior even if I add a 10 second sleep in the end:

```python
import os
os.environ["MPI4JAX_DEBUG"] = "1"

import jax
import jax.numpy as jnp

from mpi4py import MPI
from mpi4jax import send

comm = MPI.COMM_WORLD
assert comm.Get_size() == 1

def flush(platform):
    """Wait for all pending XLA operations"""
    devices = jax.devices(platform)

    for device in devices:
        # as suggested in jax#4335
        noop = jax.device_put(0, device=device) + 0
        noop.block_until_ready()

# send to non-existing rank
@jax.jit
def send_jit(x):
    send(x, dest=0, comm=comm)


print("send without JIT")
send(jnp.ones(10), dest=0, comm=comm)

print("send with JIT")
send_jit(jnp.ones(10))

import time
time.sleep(10)
```

**Comment by dionhaefner** [comment]
Actually, it works for any return argument that is not `None`:

```python
# works
@jax.jit
def send_jit(x):
    send(x, dest=0, comm=comm)
    return 0

# nope
@jax.jit
def send_jit(x):
    send(x, dest=0, comm=comm)
    return None
```

Do functions that don't return anything get optimized away since recently?

**Comment by hawkinsp** [comment]
I'm trying to run your repro but it just hangs for me.

I did:
```
$ apt install libmpich-dev
$ git clone https://github.com/mpi4jax/mpi4jax.git
$ cd mpi4jax
$ git fetch origin pull/151/head
$ git checkout FETCH_HEAD
$ pip install -e .
```

and then tried running your repro:
```
$ python m.py
send without JIT
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
r0 | yrpTbyMM | MPI_Send -> 0 with tag 0 and 10 items
```
At this point it hangs apparently forever.

What am I doing wrong?

**Comment by dionhaefner** [comment]
Sorry, my bad. Because the example code sends without receiving, it will deadlock with many MPI providers.

Here's one that should work for all setups:

```python
import os
os.environ["MPI4JAX_DEBUG"] = "1"

import jax
import jax.numpy as jnp

from mpi4py import MPI
from mpi4jax import sendrecv

comm = MPI.COMM_WORLD
assert comm.Get_size() == 1

@jax.jit
def sendrecv_jit(x):
    sendrecv(x, x, source=0, dest=0, comm=comm)

print("sendrecv without JIT")
sendrecv(jnp.ones(10), jnp.ones(10), source=0, dest=0, comm=comm)

print("sendrecv with JIT")
sendrecv_jit(jnp.ones(10))

import time
time.sleep(10)
```

Output:

```bash
sendrecv without JIT
r0 | 05WTiqzD | MPI_Sendrecv <- 0 (tag -1, 10 items) / -> 0 (tag 0, 10 items)
r0 | 05WTiqzD | MPI_Sendrecv done with code 0 (3.26e-05s)
sendrecv with JIT
```

After adding `return 0` to `sendrecv_jit`:

```bash
sendrecv without JIT
r0 | 05WTiqzD | MPI_Sendrecv <- 0 (tag -1, 10 items) / -> 0 (tag 0, 10 items)
r0 | 05WTiqzD | MPI_Sendrecv done with code 0 (3.26e-05s)
sendrecv with JIT
r0 | XoGaYz72 | MPI_Sendrecv <- 0 (tag -1, 10 items) / -> 0 (tag 0, 10 items)
r0 | XoGaYz72 | MPI_Sendrecv done with code 0 (3.92e-06s)
```

**Comment by hawkinsp** [comment]
@sharadmv I think the bug is here:
https://github.com/google/jax/blob/c08b4ee6d9a13787c16bcf867d04e04d81fca063/jax/_src/dispatch.py#L329

note that `jaxpr.outvars` is empty, and a custom call with a side effect isn't considered to have a `jaxpr` effect. I suspect we need to treat effectful custom calls as effectful for `jaxpr` purposes as well?

**Comment by sharadmv** [comment]
I see. You need to define your primitives to be effectful. To do that, use:
```python
effect = <some hashable>
def _effectful_abstract_eval(...):
  return ..., {effect}
prim.def_effectful_abstract_eval(_effectful_abstract_eval)
from jax.interpreters import mlir

mlir.lowerable_effects.add(effect)
```

This will automatically make any jaxpr that contains these primitives have an effect and we will bypass the check that Peter mentioned.

An added benefit will be that you no longer need to use your `atexit` handler. Instead you can call `jax.effects_barrier()` which does the same thing.

**Comment by dionhaefner** [comment]
That seems to work, thanks. 

What are the semantics of the `effect` object? Can I re-use the same object for all primitives?

**Comment by sharadmv** [comment]
The effect object can be any hashable (internally we use enums usually). It functions as tag that shows up in jaxprs (in `jaxpr.effects`). You can re-use it for whichever primitives you want this blocking behavior for.

**Comment by PhilipVinc** [comment]
@sharadmv Would it be posssible to make `from jax._src.lax import control_flow as lcf` part of the public/exported API? We have several users and would like to avoid `mpi4jax` breaking too often because we rely on internal things.

If this is part of the API necessary to define custom effectfull primitives, then it might make sense to have it in the public API.

**Comment by sharadmv** [comment]
The custom effectful primitive API is considered internal and experimental and will likely change in the future. We can't at the moment promise a public, stable interface. Using custom JAX primitives is also technically internal / unstable (although probably less likely to dramatically change than the new effects system).

I initially recommended an unstable solution because I was under the impression that `mpi4jax` was okay being broken by JAX internal changes given the existing dependence on primitives.

An alternate, stable solution would be to do manual token threading (this is what the effects system current does underneath the hood) and to block on the output tokens:

```python
@jax.jit
def sendrecv_jit(token, x):
    sendrecv(x, x, source=0, dest=0, comm=comm)
    return token
```

`token` can be something as simple as a zero-length array (`np.zeros(0, np.bool_)` for example) and is just needed to block on the computation. You can look at [this design note](https://jax.readthedocs.io/en/latest/design_notes/sequencing_effects.html) which informed the current effect system's design.

**Comment by dionhaefner** [comment]
@sharadmv Thanks for the clarification. We actually already do token threading to enforce order of our primitives, and it's sort of a major pain. So this piqued my interest:

> An alternate, stable solution would be to do manual token threading (this is what the effects system current does underneath the hood)

So the effects system actually does automated token tracking? In this case we could just abandon our manual token threading, which would be amazing. But kind of hard to depend on if this is an unstable feature... 🤔

**Comment by PhilipVinc** [comment]
>An alternate, stable solution would be to do manual token threading (this is what the effects system current does underneath the hood) and to block on the output tokens:

This is not really an option right now because we'd have to force users to weave tokens themselves in and out of jitted functions, which we are severely trying to avoid.

>The custom effectful primitive API is considered internal and experimental and will likely change in the future. We can't at the moment promise a public, stable interface. Using custom JAX primitives is also technically internal / unstable (although probably less likely to dramatically change than the new effects system).

Ah, ok. We have several downstream users so we try to rely on as stable APIs as possible. The current iteration of `mpi4jax` has persisted practically unbroken for 12+ months (if not for reshuffling of your API entry points), and I would be happy if this could continue.

I was under the impression that `jax.core` is part of the public API, and since `jax.core.Primitive` is there as well I expected that to be stable. This is why I asked to make `control_flow` stable as well. 
But if that's not the case it's good to know.

**Comment by sharadmv** [comment]
> I was under the impression that jax.core is part of the public API, and since jax.core.Primitive is there as well I expected that to be stable. This is why I asked to make control_flow stable as well.

The official list of public modules [is available here](https://jax.readthedocs.io/en/latest/api_compatibility.html).

> Ah, ok. We have several downstream users so we try to rely on as stable APIs as possible. The current iteration of mpi4jax has persisted practically unbroken for 12+ months (if not for reshuffling of your API entry points), and I would be happy if this could continue.

Is it possible to release `mpi4jax` versions with pinned JAX/jaxlibs?

**Comment by dionhaefner** [comment]
That's certainly an option. Thanks for the support @sharadmv.
