### ISSUE TITLE
Bad error message on `vmap` arity mismatch

### ISSUE THREAD

**Issue by LenCewa** [google/jax#1162]
Hello,

you give an example how to implement a matrix-matrix product using a vector dot product using vmap. But when I reproduce this example:
```
a = np.array([[1, 2, 3]]).transpose()
m1 = np.array([[1, 1, 1], [2, 2, 2]])

vv = lambda x, y: np.vdot(x, y)
mv = vmap(vv, (0, None), 0)
mm = vmap(mv, (None, 1), 1)

print(mm(m1, a))
```
 
I get this error: `Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)`.

The same happens when I try this:
```
b = np.array([1, 2, 3])
m1 = np.array([[1, 1, 1], [2, 2, 2]])

vv = lambda x, y: np.vdot(x, y)
mv = vmap(vv, (0, None), 0)

print(mv(m1, b))
```

When I call `print(mm(m1)(a))` or for the second example `print(mv(m1)(b))` I get an `AssertionError: length mismatch: [2, 1]`.

I don't get what I'm doing wrong. Changing for example the dimensions of m1 leaves the length mismatch: [2, 1] unchanged...

**Comment by hawkinsp** [comment]
Thanks for the issue report!

I think I can guess the problem. You should
`import jax.numpy as np`
not
`import numpy as np`

That said, neither of the two behaviors you saw are good (a crash and a length mismatch). There's definitely something we should improve here!

**Comment by LenCewa** [comment]
Yes, the `import jax.numpy as np` solved the problem. Thanks!

**Comment by hawkinsp** [comment]
The SIGSEGV actually happens inside NumPy. I filed a NumPy bug (https://github.com/numpy/numpy/issues/14247)

**Comment by hawkinsp** [comment]
For the second issue happens because there is a mismatch between the number of arguments passed to `mm` and the arity of the `vmap` axis specifications. We should give a better error in this case.

Even if you do pass the right number of arguments you still need to use the correct `jax.numpy`, unless we merge something like https://github.com/google/jax/pull/611 .

**Comment by hawkinsp** [comment]
All the issues in this bug seem to be fixed (and have been for a while!). Closing.
