### ISSUE TITLE
Numerical error in Jacobian computation

### ISSUE THREAD

**Issue by ChenAo-Phys** [google/jax#11628]
Hi,

The error can be reproduced by the following code

```
import jax
from jax import grad, vmap, jacfwd, jacrev
import jax.numpy as jnp
from jax.random import PRNGKey, normal

nbatch, nparams = 100, 1000
seed = 0
mat = normal(PRNGKey(seed), (nbatch, nparams))

def f(x):
    return mat @ x

def fi(x, i):
    return f(x)[i]
gradf = grad(fi)

x = normal(PRNGKey(seed+1), (nparams,))
idx = jnp.arange(nbatch)

jac1 = jnp.stack([gradf(x, i) for i in idx], axis=0)

jac2 = vmap(gradf, in_axes=(None, 0))(x, idx)

jac3 = jacfwd(f)(x)

jac4 = jacrev(f)(x)

print(jnp.std(jac1 - mat), jnp.std(jac2 - mat), jnp.std(jac3 - mat), jnp.std(jac4 - mat))
#output 0.0 0.00020866805 0.00020866805 0.00020866805
```
Only the jacobian without vmap parallel is exactly the same as `mat`, while other approaches produce some finite error much higher than the float32 precision 1e-7.

We test it in different cases and the error only happens with:
- Geforce RTX 3090 or A100 GPU (no error on CPU, TPU and T4, P100, V100 GPU)
- float32 (no error on float16, float64, complex64, complex128)
- large enough matrix (for example, no error on `nbatch, nparams = 10, 100`)

The error can be reproduced only when all the above conditions are satisfied.

Some other information on our RTX 3090 GPU
cuda 11.6, cudatoolkit 11.6.0, cudnn 8.4.1.50, 
python 3.8.13, jax 0.3.13 or python 3.9.7, jax 0.3.15 (error happens in both cases)

On A100, cuda 11.1, cudnn 7.0.5, python 3.8, jax 0.2.25

**Comment by YouJiacheng** [comment]
Hmmm. I guess the numerical error tolerance should be `max(n, m) * eps` for `(n, m)` shape matrix multiplication?
But it is interesting that `mat @ jnp.eye((nparams, nparams))`(I believe `jacfwd` is equivalent to this) can lead to such a large numerical error, since there shouldn't be any error accumulation.

**Comment by ChenAo-Phys** [comment]
> Hmmm. I guess the numerical error tolerance should be `max(n, m) * eps` for `(n, m)` shape matrix multiplication? But it is interesting that `mat @ jnp.eye((nparams, nparams))`(I believe `jacfwd` is equivalent to this) can lead to such a large numerical error, since there shouldn't be any error accumulation.

Thanks for your reply. I just did some tests and the error is always around 0.0002 independent of the matrix size.
Furthermore, `mat @ jnp.eye((nparams, nparams))` also gives 0 error. The error only happens when we compute the `vmap` parallel of `grad` (or `jvp`, `vjp`)

**Comment by ChenAo-Phys** [comment]
I just run the following code
`jnp.std(jac2 - mat.astype(jnp.float16))`
The output is 5.828777e-06, which is much smaller than the origional error 0.0002.
I believe the numerical error is because the values are somehow converted to float16 during computation.

**Comment by YouJiacheng** [comment]
Hi. Could you run `print(jax.make_jaxpr(jacfwd(f))(x))` to see the actual computation?

**Comment by ChenAo-Phys** [comment]
> Hi. Could you run `print(jax.make_jaxpr(jacfwd(f))(x))` to see the actual computation?

```
{ lambda a:f32[100,1000]; b:f32[1000]. let
    c:i32[1000,1000] = iota[dimension=0 dtype=int32 shape=(1000, 1000)] 
    d:i32[1000,1000] = add c 0
    e:i32[1000,1000] = iota[dimension=1 dtype=int32 shape=(1000, 1000)] 
    f:bool[1000,1000] = eq d e
    g:f32[1000,1000] = convert_element_type[new_dtype=float32 weak_type=False] f
    h:f32[1000,1000] = slice[
      limit_indices=(1000, 1000)
      start_indices=(0, 0)
      strides=None
    ] g
    _:f32[100] = dot_general[
      dimension_numbers=(((1,), (0,)), ((), ()))
      precision=None
      preferred_element_type=None
    ] a b
    i:f32[100,1000] = dot_general[
      dimension_numbers=(((1,), (1,)), ((), ()))
      precision=None
      preferred_element_type=None
    ] a h
    j:f32[100,1000] = slice[
      limit_indices=(100, 1000)
      start_indices=(0, 0)
      strides=None
    ] i
  in (j,) }
```

**Comment by YouJiacheng** [comment]
Looks strange. Jaxpr shows it should be identical to `mat @ jnp.eye((nparams, nparams))` unless `slice` has bugs.
`foo` should yield nearly identical jaxpr to `jacfwd(f)` except `slice`.
```python
def foo(x):
    identity = jnp.eye((nparams, nparams))
    _ = mat @ x
    return mat @ identity
print(jax.make_jaxpr(foo)(x))
```

**Comment by ChenAo-Phys** [comment]
> Looks strange. Jaxpr shows it should be identical to `mat @ jnp.eye((nparams, nparams))` unless `slice` has bugs. `foo` should yield nearly identical jaxpr to `jacfwd(f)` except `slice`.
> 
> ```python
> def foo(x):
>     identity = jnp.eye((nparams, nparams))
>     _ = mat @ x
>     return mat @ identity
> print(jax.make_jaxpr(foo)(x))
> ```

I tried it again and now `mat @ jnp.eye(nparams)` reproduces the error. I remember there was no error when I tested it some hours ago. I guess I made some mistakes before. So sorry for that

Here is the full code.
```
import jax.numpy as jnp
from jax.random import PRNGKey, normal

mat = normal(PRNGKey(0), (100, 1000))

print(jnp.std(mat @ jnp.eye(1000) - mat))
#output: 0.00020866805

print(jnp.std(mat @ jnp.eye(1000) - mat.astype(jnp.float16)))
#output: 5.828777e-06
```

**Comment by YouJiacheng** [comment]
Thanks for clarification. (I made a mistake that I used wrong argument for `jnp.eye` as well, sorry).
Now I think it should be related to matrix multiplication, might be related to `cutlass` on XLA GPU.
I am not familiar with it, maybe @hawkinsp could give some insights?

**Comment by hawkinsp** [comment]
Try with `NVIDIA_TF32_OVERRIDE=0`.

This is probably because on A100 we will use TensorCores and TF32 math by default.

Ideally this should be controllable from Python inside JAX; it is not yet.

**Comment by ChenAo-Phys** [comment]
> Try with `NVIDIA_TF32_OVERRIDE=0`.
> 
> This is probably because on A100 we will use TensorCores and TF32 math by default.
> 
> Ideally this should be controllable from Python inside JAX; it is not yet.

This fixes the problem on RTX 3090. Thanks a lot!

**Comment by pschuh** [comment]
With the newest jaxlib, this is possible using the normal default precision scopes:

```
with jax.default_matmul_precision('float32'):
  return x @ y
```

**Comment by ChenAo-Phys** [comment]
> With the newest jaxlib, this is possible using the normal default precision scopes:
> 
> ```
> with jax.default_matmul_precision('float32'):
>   return x @ y
> ```

Thanks for your suggestion! It has the same effect as `jnp.matmul` with `precision='float32'`, right?

**Comment by pschuh** [comment]
Yes, if `precision=None`, any matmul (or dot_general) will read from `jax.config.jax_default_matmul_precision` which that `with` statement sets within that scope.
