### ISSUE TITLE
[P0] Launching JAX experiments not from Colab broken.

### ISSUE THREAD

**Issue by kibergus** [google/jax#11664]
Changes introduced in cl/462665740 unconditionally imports google.colab when not running under colab. This breaks the official way to detect if one is running under Colab, which in turn breaks libraries depending on this. XManager team needs your assistance to roll back these changes.

**Comment by kibergus** [comment]
It is very important to get this pull request submitted: https://github.com/google/jax/pull/11666

**Comment by LenaMartens** [comment]
this seems to be fixed by merging #11666, closing this issue.
