### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by Chen-Beer** [google/jax#1166]
With Python 2.7 and Ubuntu 18.04, after running this line:
python build/build.py --enable_cuda

I get the following errors:

Building XLA and installing it in the jaxlib source tree...
DEBUG: /home/chen/.cache/bazel/_bazel_chen/e15eb051390cace74a40a2626236fc36/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:118:5:
Auto-Configuration Warning: 'TMP' environment variable is not set, using 'C:\Windows\Temp' as default
INFO: Analyzed target //build:install_xla_in_source_tree (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/chen/.cache/bazel/_bazel_chen/e15eb051390cace74a40a2626236fc36/external/com_google_absl/absl/hash/BUILD.bazel:28:1: C++ compilation of rule '@com_google_absl//absl/hash:hash' failed (Exit 1)
gcc: error trying to exec 'cc1plus': execvp: No such file or directory
Target //build:install_xla_in_source_tree failed to build
ERROR: /home/chen/.cache/bazel/_bazel_chen/e15eb051390cace74a40a2626236fc36/external/org_tensorflow/tensorflow/compiler/xla/python/BUILD:242:1 C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
INFO: Elapsed time: 0.494s, Critical Path: 0.10s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build/build.py", line 334, in <module>
    main()
  File "build/build.py", line 329, in main
    [":install_xla_in_source_tree", os.getcwd()])
  File "build/build.py", line 50, in shell
    output = subprocess.check_output(cmd)
  File "/home/chen/anaconda3/envs/LFADS/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/chen/bin/bazel', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', '--config=cuda', ':install_xla_in_source_tree', '/home/chen/jax/build']' returned non-zero exit status 1

Any help would be much appreciated.

**Comment by hawkinsp** [comment]
It sounds to me like you don't have a C++ compiler installed or it isn't working for some reason. Can you double check that?

Try something like
```
sudo apt-get install build-essential python3-scipy cython3
python3 build/build.py
```

I'll confirm exactly which packages are needed.
