### ISSUE TITLE
Add a batching rule for `lax.linalg.tridiagonal_solve`

### ISSUE THREAD

**Issue by emilyfertig** [google/jax#11674]
Is it possible to add this? It'll let us have a tridiagonal linear operator in TFP's JAX backend. Thanks!

**Comment by mattjj** [comment]
Great idea! Thanks for the request.

**Comment by mattjj** [comment]
#11674 would've fixed this within hours of the issue being opened (so cool), but it got stalled because of an XLA:GPU bug I believe (not cool). I think I need to:
1. just merge this with the GPU test skipped, and
2. file an XLA:GPU bug with a reproducer.

**Comment by mattjj** [comment]
7dfc8ff49d aka cl/555700103 fixed this!
