### ISSUE TITLE
Argument `argnums` for jvp, vjp

### ISSUE THREAD

**Issue by exenGT** [google/jax#11703]
Hi JAX developers,

Sometimes I find it necessary to calculate Jacobian-vector product of a function `f(*X)` with respect to a particular argument `X[i]`. For example, if the approximate Hessian `H` of the function `f(*X)` has block-diagonal form, then the "block-`i` Hessian-vector product" `H[i, i] @ V[i]` could in principle be calculated with:

```
jvp(grad(f, argnums=i), *X, V[i], argnums=i)[1]
``` 
if `argnums` were available as an option for `jvp()`. Could it be added as a new feature? If not, is there a limitation for its implementation? Thanks!

**Comment by patrick-kidger** [comment]
If I understand what you want to do correctly, this should be doable already:
```python
before = x[:i]
after = x[i+1:]
jax.jvp(lambda xi: f(*before, xi, *after), (x[i],), (xi_tangent,))
```

**Comment by exenGT** [comment]
Thanks @patrick-kidger! I think this is what I need.

**Comment by hawkinsp** [comment]
Are you happy with @patrick-kidger 's solution? Should we close this issue?

**Comment by exenGT** [comment]
Yes, you can close the issue. Thanks!
