### ISSUE TITLE
Releases are off?

### ISSUE THREAD

**Issue by gianlucadetommaso** [google/jax#11785]
Just wanted to signal that most releases disappeared from [https://storage.googleapis.com/jax-releases/jax_cuda_releases.html](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html). It would be great if you could put them back! :-)

**Comment by Bam4d** [comment]
Yeah same for me too (althought I thought it was my fault and spent two hours trying to work out why I couldnt install jax properly)

**Comment by yashk2810** [comment]
Should be fixed. Can you please check and confirm? (you might need to refresh to get the updated index)

**Comment by gianlucadetommaso** [comment]
Works, thanks!

**Comment by yashk2810** [comment]
Awesome! Thanks for confirming.

**Comment by nickmcgreivy** [comment]
Hi, would it be possible to update the website https://storage.googleapis.com/jax-releases/jax_cuda_releases.html with the newest releases? I see the releases through jaxlib-0.3.15 from July, but not since then.

**Comment by hawkinsp** [comment]
We haven't made any jaxlib releases since July (only `jax`, which can be released separately from `jaxlib`). We're trying to make a new one now, though.

**Comment by nickmcgreivy** [comment]
Ah, okay. I figured out my issue, thanks.
