### ISSUE TITLE
BUG: Unable to use jax after building from source with GPU (cudaGetErrorString symbol not found)

### ISSUE THREAD

**Issue by JuanGMendoza** [google/jax#11828]
### Description

I have built jaxlib from source with cuda and cudnn included (cuda 11.6.2 and cudnn 8.4.0.27) using a linux centos7 haswell device on gcc 8.3.0 I then managed to finish installing jax with no problem inside a conda environment. 

I should also mention that I checked out branch jaxlib-v0.3.15 to install and build, because I require this version.

When I try using the library, I obtain the following error 
`jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: CustomCall failed: jaxlib/cuda/cuda_prng_kernels.cc:32: operation cudaGetLastError() failed: cudaGetErrorString symbol not found.

`

Any suggestions on what could be going on?

### What jax/jaxlib version are you using?

jax v0.3.15

### Which accelerator(s) are you using?

- [X] CPU
- [X] GPU
- [ ] TPU

**Comment by jakevdp** [comment]
This error suggests there may be a CUDA version mismatch. What is the result of running `nvidia-smi`?

**Comment by JuanGMendoza** [comment]
I set my $PATH to point to the right cuda version and now it works, thanks!

**Comment by jakevdp** [comment]
Glad you figured out the problem! I'll close this issue; feel free to chime in here or open another if you run into anything else.
