### ISSUE TITLE
BUG: Should test_prim in jax2tf reraise exceptions caught from ConvertAndCompare?

### ISSUE THREAD

**Issue by shaobohou** [google/jax#11835]
### Description

Otherwise it seems like this could hide some test failures.

In fact, this might already be the case, see related PR https://github.com/google/jax/pull/11747

### Which accelerator(s) are you using?

- [ ] CPU
- [ ] GPU
- [ ] TPU

**Comment by apaszke** [comment]
Nice catch! This seems to have been fixed in 856d91d25138cf8cc2ea689371799e6c2b84b0d4
