### ISSUE TITLE
BUG: can create 64-bit arrays using dlpack when x64 is disabled

### ISSUE THREAD

**Issue by sharadmv** [google/jax#11895]
### Description

Repro:
```python
import tensorflow as tf
import jax
import jax.dlpack

assert not jax.config.jax_enable_x64
x = jax.dlpack.from_dlpack(tf.experimental.dlpack.to_dlpack(tf.ones(5, tf.int64)))
assert x.dtype == jax.numpy.int64
```

This can cause loud and confusing errors down the line when our MHLO expects 32-bit numbers but gets 64-bit. For example, with our illegal 64-bit `x` array, try doing `x[0]`.

### What jax/jaxlib version are you using?

HEAD/0.3.15

### Which accelerator(s) are you using?

CPU

**Comment by froystig** [comment]
> This can cause loud and confusing errors down the line

Arguably a separate issue to file regarding this: if we do somehow end up with unexpected 64-bit device (or abstract) arrays, we ideally catch that and err early on, ahead of lowering in particular.

**Comment by froystig** [comment]
@hawkinsp @jakevdp – So long as the x64 flag exists and means what it means, how should we behave on `jax.dlpack.from_dlpack` given a 64-bit-dtyped array, when x64 mode is off? Some options:

1. Error
2. Convert to 32-bit silently
3. Convert to 32-bit and `warnings.warn`

I'll send a PR for what we think is best.

**Comment by jakevdp** [comment]
converting silently is consistent with how the x64 flag works in similar situations, e.g. `jnp.asarray(numpy_arr)`
