### ISSUE TITLE
BUG: checkify of a vmap-ed while loop fails with an obscure error

### ISSUE THREAD

**Issue by hr0nix** [google/jax#11905]
### Description

Consider the following code:
```python
def test_checkify_with_batched_while():
    def func_to_check_with_loop(n, v):
        def while_condition(loop_state):
            counter, _ = loop_state
            return counter > 0

        def loop_body(loop_state):
            counter, value = loop_state
            checkify.check(value > 0, 'value must be positive')
            return counter - 1, value - 1

        _, result = jax.lax.while_loop(while_condition, loop_body, (n, v))
        return result

    batched_func = jax.vmap(func_to_check_with_loop)
    checked_f = checkify.checkify(batched_func)

    err, val = checked_f(jnp.asarray([1, 2, 3]), jnp.asarray([5, 2, 4]))
    err.throw()
    assert jnp.all(val == jnp.asarray([4, 0, 1]))
```

The code above fails when calling `checked_f` with the following error (truncated):
```
def _pred_bcast_select_mhlo(
        pred_aval: core.ShapedArray, pred: ir.Value, xs: Sequence[ir.Value],
        ys: Sequence[ir.Value], x_y_aval: core.AbstractValue) -> Sequence[ir.Value]:
      if x_y_aval is core.abstract_token:
        x, = xs
        y, = ys
        return [mhlo.AfterAllOp(mlir.aval_to_ir_type(x_y_aval), [x, y]).result]
      else:
        assert isinstance(x_y_aval, core.ShapedArray), x_y_aval
        x, = xs
        y, = ys
        assert x.type == y.type, (x.type, y.type)
>       assert (pred_aval.shape == x_y_aval.shape[:len(pred_aval.shape)]), (
                pred_aval.shape, x_y_aval)
E       jax._src.traceback_util.UnfilteredStackTrace: AssertionError: ((3,), ShapedArray(bool[]))
```

If one modifies the code by either removing `checkify`, or making a non-batched version by removing `vmap`, everything works as expected.

Can you please confirm that this is indeed a bug in JAX and, if so, provide a workaround?

### What jax/jaxlib version are you using?

0.3.16

### Which accelerator(s) are you using?

CPU

### Additional System Info

Mac

**Comment by hr0nix** [comment]
Given that many library users will likely use checkify on the top-most function (i.e. `train`), it would be nice to have some transformation that would allow the user to locally exclude functions from the checkify transform even if the calling code has been transformed. It should help to work around such problems until the new functionality is perfectly stable and will probably be useful in general.

For instance, in my case I would have liked to just label the function with the vmap-ed while loop as non-checkifiable, while continuing to check the rest of the code.

**Comment by hr0nix** [comment]
Hello, can someone take a look at this please?

**Comment by LenaMartens** [comment]
Sorry for the delayed response! I've been out of office for the past 2 weeks.

Thanks for the clear and minimal repro, I'll send a fix for this soon with your repro as a test-case.
Also, good point on adding some ability to locally exclude functions from being checkified. We've been thinking of a way to support "nullifying" any enabled checks from an outer checkify. I'll take this as a +1 to get that feature added!
