### ISSUE TITLE
REQ: Support effects in custom_vjp

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#11916]
cc @dionhaefner 

The recent internal changes in jax forced us to use effects in mpi4jax. 
Unfortunately, I just found out that this is incompatible with `custom_vjp` so we now have a feature regression.

How hard would it be to support them in `custom_vjp`?

**Comment by sharadmv** [comment]
Could you check if this was fixed in https://github.com/google/jax/commit/7cd81ca1a8118a821036c5daad073066da94515d?

**Comment by sharadmv** [comment]
You will need to add your effect to another allowlist

**Comment by PhilipVinc** [comment]
Thanks @sharadmv !
I checked and indeed adding the `MPIEffect` to the list of allowed effects makes it work.

To get a better idea of why you are blocking effects... what kind of effects are supposed to be not supported in custom_vjp?

Right now we use effects in mpi4jax to represent operations similar to jax's `jax.lax.psum/pgather/pmean`. Would you agree that those are safe to be used in `custom_vjp`?

**Comment by sharadmv** [comment]
The purpose of the various allowlists is to selectively enable effects when we understand their behavior. For example, we haven't exactly worked out what a "state" side-effect might look like inside of a `custom_jvp` so for now we disable it by default. 

The collectives you've listed are pure functions and should just work in `custom_jvp/vjp` (they already work in JAX via `lax.pmean/pgather/psum`). If these collectives are broken down into effectful components (e.g. MPI send/recvs), then you could bundle them into a (pure) primitive that lowers into a series of `CustomCalls`.

Does that make sense?
