### ISSUE TITLE
BUG: build warning of download tensorflow runtime package

### ISSUE THREAD

**Issue by ThomsonTan** [google/jax#11959]
### Description

Tried build jaxlib in WSL2 on Windows 11 and got below warnings. Seems the files cannot be downloaded with below URL, but the files are available in the original URL like "https://github.com/tensorflow/runtime/archive/e3da90c2cb1bd594a90ffb06b80f6d8df47c4e11.tar.gz". Are these build warnings critical for a successful build?

```console
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/e3da90c2cb1bd594a90ffb06b80f6d8df47c4e11.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/2c3ca3b684bb2b188d977d47548e79dc559fb8ad.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

### What jax/jaxlib version are you using?

Build from latest source

### Which accelerator(s) are you using?

CPU

### Additional System Info

Windows 11, WSL2.

**Comment by hawkinsp** [comment]
These are benign warnings. They happen because we haven't added that particular file to a mirror repository.
