### ISSUE TITLE
BUG: ROCm builds failing on master

### ISSUE THREAD

**Issue by brettkoonce** [google/jax#11972]
### Description

Regression with ROCm builds against master.

04b751c549a2c03681bd95cb3796df78cb26bc5b version:

    sudo ./build/rocm/ci_build.sh --keep_image bash -c "./build/rocm/build_rocm.sh"

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
+ [[ '' != \-\-\r\m ]]
+ [[ 0 == \0 ]]
+ echo 'Committing the docker container as jax-rocm'
Committing the docker container as jax-rocm
+ docker stop jax_ci.rocm
jax_ci.rocm
+ docker commit jax_ci.rocm jax-rocm
sha256:75e5123394e48e1492e1bb281a8b4b7051b7829e16b3fbf381d6ae79c0e94b81
+ docker rm jax_ci.rocm
jax_ci.rocm
+ echo 'ROCm build was successful!'
ROCm build was successful!
```

cleared docker images

build jax 2bc3e39cd9104071ee39dacac22abd51b94eb27e

```
TPU enabled: no
Remote TPU enabled: no
ROCm enabled: yes
ROCm toolkit path: /opt/rocm-5.2.0
ROCm amdgpu targets: gfx900,gfx906,gfx908,gfx90a,gfx1030

Building XLA and installing it in the jaxlib source tree...
./bazel-5.1.1-linux-x86_64 run --verbose_failures=true :build_wheel -- --output_path=/workspace/dist --cpu=x86_64
b''
    main()
  File "/workspace/./build/build.py", line 551, in main
    shell(command)
  File "/workspace/./build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-5.1.1-linux-x86_64', 'run', '--verbose_failures=true', ':build_wheel', '--', '--output_path=/workspace/dist', '--cpu=x86_64']' returned non-zero exit status 1.
```

**Comment by hawkinsp** [comment]
We're in the process of reverting https://github.com/google/jax/commit/2bc3e39cd9104071ee39dacac22abd51b94eb27e which may help.

**Comment by brettkoonce** [comment]
@hawkinsp starting a bisect!

**Comment by brettkoonce** [comment]
git bisect reports ae6e0e0950a37e78da71742975828241a0acda46 is the commit that broke builds, eg

    sudo ./build/rocm/ci_build.sh --keep_image bash -c "./build/rocm/build_rocm.sh"

no longer is successful!

**Comment by brettkoonce** [comment]
Ps ping @rsanthanam-amd, would guess the above change is exposing something in the ROCm customizations on top!

**Comment by rsanthanam-amd** [comment]
We are aware of the issue.  It should be resolved by the end of this week or early next week.

**Comment by mattjj** [comment]
@rsanthanam-amd could you follow up with more info when you have it? Let me know if I should assign to someone on the JAX team to sort out anything here.

**Comment by rsanthanam-amd** [comment]
@mattjj assigning this to me is fine.  it should be resolved some time this week.  i will update this ticket.

**Comment by hawkinsp** [comment]
#12032 is merged. Sound to me like we can close this!
