### ISSUE TITLE
BUG: Jax no longer able to see TPUs 

### ISSUE THREAD

**Issue by bycn** [google/jax#12005]
### Description

Using a TPUVM v3-8 (from TRC). Jax is working fine w/ TPUs but the next day (no actions taken afaik) no longer able to see it.

bryanchen.bxc at gmail.com project ID mimetic-slate-353618 
TPU name xtpu1

Happy to provide more info

### What jax/jaxlib version are you using?

jax 0.3.16, 0.3.15

### Which accelerator(s) are you using?

TPUVM v3-8

**Comment by jakevdp** [comment]
Possibly related, though Colab uses older 2VM TPUs: https://github.com/googlecolab/colabtools/issues/3009

**Comment by bycn** [comment]
Note that what I mean by "no longer able to see TPUs" is that jax.local_devices() only returns the CpuDevice

**Comment by hawkinsp** [comment]
I'm not saying this is a great solution, but does restarting the TPU VMs help?

**Comment by bycn** [comment]
I already restarted it (stop and start in tpu console) to no effect. I can check on it again later today

**Comment by bycn** [comment]
Sorry for the delayed response but they are back when I checked on it today.
