### ISSUE TITLE
BUG: Many JAX tests fail on A100 because of TF32 math

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#12008]
Quite a few tests in the JAX test suite fail because of defaulting to TF32 math on A100.

The right fix would be to override the precision of the matmul/conv operations in those tests.

There's already a mechanism for this which works on TPU: `jax.default_matmul_precision`, and it could be used as a decorator on the relevant tests:

```
@jax.default_matmul_precision("float32")
def test(...):
   ...
```

This decorator has the effect of setting the `precision` attribute on HLO Dot and Conv operators. However, it seems that unfortunately this attribute is not yet plumbed through XLA and doesn't work.

**Comment by mjsML** [comment]
@sudhakarsingh27

**Comment by mattjj** [comment]
@pschuh once your CL goes in, can you reassign this bug to me and I'll take care of updating the tests?

**Comment by jakeh-gc** [comment]
> The right fix would be to override the precision of the matmul/conv operations in those tests.

I'm not sure if this issue is still alive, but I think it would be better to change the default of the CUDA backend to respect the user's input datatypes (`float32` in this case) by default instead of changing the tests.

PyTorch had a similar experience which caused issues for non-ML users.
https://dev-discuss.pytorch.org/t/pytorch-and-tensorfloat32/504

**Comment by hawkinsp** [comment]
Indeed, this has been a persistent source of debate on TPU for a long time, which by default uses bf16 inputs with f32 accumulation for matrix multiplications (#7010). Either you default to low precision and scientific users opt into high precision, or you default to high precision and neural network users opt into low precision. No choice makes everyone happy.  One has a correctness footgun and the other has a performance footgun.

On TPU, we default to low precision but I am quite tempted to change it. On GPU we do the same thing (TF32 by default on Ampere).

Either way there are two issues here (a) make the mechanism for overriding the default precision work correctly on GPU and (b) what should the default be.

Let's scope this issue to "making the tests pass" for the moment, and have the other discussion on #7010.

**Comment by jakeh-gc** [comment]
Ah, that makes sense. I didn't see the older issue (#7010).
> Let's scope this issue to "making the tests pass" for the moment

Sure. Seems reasonable. I just worry that can become a little "sticky" when in. But is likely a minor issue.

[tangent]
My slightly biased point of view (and how I found this issue) comes from me testing Graphcore's IPU against these implementations and getting larger differences than I expected. 
[/tangent]

**Comment by hawkinsp** [comment]
#13262 explicitly opts into high precision everywhere it seemed to matter for A100 in my tests. This does not preclude switching the default later.
