### ISSUE TITLE
BUG: pjit results in incorrect/incompatible shapes with distributed setup

### ISSUE THREAD

**Issue by dlwh** [google/jax#12024]
### Description

Note: I can only reproduce this when I'm using more than 1 machine (namely, the v3-256 cloud TPU VM I'm getting to play with)

I was trying to implement ZeRO-3 (along the lines hinted in https://github.com/google-research/t5x/blob/main/docs/usage/partitioning.md#data-parallel-with-parameter-gather) , when I ran into a bug/limitation in pjit.

When using pjit, if I try to elementwise-multiply two arrays together that have "conflicting" PartitionSpecs I get a shape error that I don't get when not using pjit. (They conflict in that one is sharded along the first axis and the other along the second using the same axis of the mesh)

```python
import jax
import jax.numpy as jnp
from jax.experimental.pjit import pjit
from jax.interpreters.pxla import Mesh, PartitionSpec
import numpy as np

devices = jax.devices()
mesh = Mesh(np.array(devices).reshape((-1, 4)), ["data", "model"])

with mesh:
    spec = PartitionSpec("data")
    array = jnp.zeros(512, dtype=jnp.bfloat16)

    def foo(weight, data):
        return weight.reshape(1, -1) * data

    # ok
    out1 = foo(array, jnp.zeros((256, 512)))
    print(out1.shape)

    # error
    pjit_foo_novmap = pjit(foo, in_axis_resources=(spec, PartitionSpec("data", None)), out_axis_resources=PartitionSpec("data", None))
    out = pjit_foo_novmap(array, jnp.zeros((256, 512)))
```

The error is `TypeError: mul got incompatible shapes for broadcasting: (1, 16384), (8192, 512).`

Using with_sharding_constraint to force weight to be replicated doesn't fix it. i.e. I still get the same error if I do:

```python
 def foo(weight, data):
        return with_sharding_constraint(weight, PartitionSpec(None)).reshape(1, -1) * data
```

16384 is 32 * 512 and 8192 is 32 * 256, and 32 is the number of worker VMs

### What jax/jaxlib version are you using?

jax 0.3.16 (main from a week ago or so)/ jaxlib 0.3.14

### Which accelerator(s) are you using?

TPU (must be more than one VM)

### Additional System Info

Cloud TPU VM v3-256, Python 3.10.5,

**Comment by yashk2810** [comment]
It seems to work for me locally with 4 devices: 

```
In [2]: import jax
   ...: import jax.numpy as jnp
   ...: from jax.experimental.pjit import pjit
   ...: from jax.interpreters.pxla import Mesh, PartitionSpec
   ...: import numpy as np
   ...:
   ...: devices = jax.devices()
   ...: mesh = Mesh(np.array(devices).reshape((-1, 4)), ["data", "model"])
   ...:
   ...: with mesh:
   ...:     spec = PartitionSpec("data")
   ...:     array = jnp.zeros(512, dtype=jnp.bfloat16)
   ...:
   ...:     def foo(weight, data):
   ...:         return weight.reshape(1, -1) * data
   ...:
   ...:     # ok
   ...:     out1 = foo(array, jnp.zeros((256, 512)))
   ...:     print(out1.shape)
   ...:
   ...:     # error
   ...:     pjit_foo_novmap = pjit(foo, in_axis_resources=(spec, PartitionSpec("data", None)), out_axis_resources=PartitionSpec("data", None))
   ...:     out = pjit_foo_novmap(array, jnp.zeros((256, 512)))
   ...:     print(out.shape)
   ...:
(256, 512)
(256, 512)
```

```
In [6]: jaxlib.__version__
Out[6]: '0.3.15'

In [7]: jax.__version__
Out[7]: '0.3.16'
```

**Comment by dlwh** [comment]
It has to be more than one node, not just multiple devices

**Comment by yashk2810** [comment]
Got it! I'll try to reproduce on 4 processes and see if I can hit this error. If I still don't hit that then I can try on 256 devices.

**Comment by yashk2810** [comment]
I am hitting this on 4 processes too.

**Comment by yashk2810** [comment]
I think the problem is that `arr` and the `data` value is host-local and pjit internally converts it to a global value which is where the mismatch is coming from.

Since you are using pjit (without GDA) on multiple processes, you need to pass host-local shaped inputs to pjit. Can you try doing that and see if it works?

**Comment by dlwh** [comment]
ah, right ok. Switching to pjit initialization of the arrays fixed it. Thank you!

I've been bitten by this before with xmap but didn't realize I was doing it again! 

I keep assuming that if I pass in arrays created identically on different nodes they get treated as though they were equal/replicated, and not concatenated.

I seem to have missed the `note` in the pjit docs!

Sorry about that.

**Comment by dlwh** [comment]
Gotcha. That sounds great!
