### ISSUE TITLE
BUG: [sparse] Tracer leak when instantiating a BCOO array with `DeviceArray`-valued `shape` in `jit`

### ISSUE THREAD

**Issue by rciric** [google/jax#12028]
### Description

When we instantiate a BCOO array, there are situations in which we might like its `shape` to be a `DeviceArray` (or sequence of `DeviceArray`s). In particular, we might like the `shape` to be returned by a compiled function. JAX doesn't complain when we do this — great.

However, if we call the `BCOO` constructor inside a `jit`-compiled function with a `DeviceArray`-valued `shape`, it results in a tracer leak. Here's a minimal example:

### Setup
```python
import jax
import jax.numpy as jnp
from jax.experimental.sparse import BCOO

mk_bcoo = lambda data, indices, shape: BCOO((data, indices), shape=shape)

data = jnp.array([1, 1])
indices = jnp.array([[0], [1]])
shape = jnp.array([99])
```

### Results

It works as expected when we don't use `jit` compilation.
```python
>> mk_bcoo(data, indices, shape)
BCOO(int32[DeviceArray(99, dtype=int32)], nse=2)

>> mk_bcoo(data, indices, shape).todense()
# Works!
```
But if we `jit`, the tracer for the shape is leaked.
```python
>> jax.jit(mk_bcoo)(data, indices, shape)
BCOO(int32[Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=0/1)>], nse=2)

>> result = jax.jit(mk_bcoo)(data, indices, shape); result.shape
(Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=0/1)>,)

>> jax.jit(mk_bcoo)(data, indices, shape).todense()
# Raises a TracerArrayConversionError
```

Apologies if this is a duplicate.

### What jax/jaxlib version are you using?

JAX v0.3.16

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks - we need to catch this case and raise an error. Shapes must be static, and you can fix your issue by doing something like this:
```python
jax.jit(mk_bcoo, static_argnames=['shape'])(data, indices, shape)
```

**Comment by rciric** [comment]
Thanks! This makes sense.

Unfortunately since the `shape` here is a `DeviceArray`, it’s not hashable and so doesn’t work out of the box with `static_argnames`. (Side note: I also tried adapting [this method](https://github.com/google/jax/issues/4572#issuecomment-709809897) to wrap the `shape` argument into a hashable container at compile time and then using `static_argnames`, but I’m still getting the leaked tracer if I do that.)

**Comment by jakevdp** [comment]
I see - shapes in JAX must be static, and you're not going to find any workaround for that.
