### ISSUE TITLE
use log1p in logsumexp

### ISSUE THREAD

**Issue by mattjj** [google/jax#1205]
I'm guessing that, analogous to #1204, we should use `log1p` in `logsumexp` if possible (though it might not be).

@majnemer any specific advice on this one?

**Comment by rbrishabh** [comment]
I would like to take this up as my first contribution! Of course, after @majnemer gives his advice on this!

**Comment by mattjj** [comment]
Awesome! I'd say no need to wait on @majnemer: if you can take a look at `logsumexp` and the change in #1204 and can come up with an analogous change, make a PR for it and I'll check it out.

**Comment by zhongwen** [comment]
This might explain certain numerical issues when we are using `logsoftmax` thus `logsumexp`.

**Comment by mattjj** [comment]
@rbrishabh any chance you can try to make a PR for this in the next ~24 hours? @zhongwen's comment made me realize this is important to get in soon, since it might squash some numerical inaccuracy bugs that have been slowing down his work. If not, I can suggest another good first issue! :)

**Comment by rbrishabh** [comment]
I will give a PR in 6-8 hours for sure! Just finishing work right now =)

**Comment by mattjj** [comment]
Thanks for jumping into that so quickly @rbrishabh!

However, based on checking how both [TF](https://github.com/tensorflow/tensorflow/blob/612e0969d65e8615f1ef0610733edb49ba1a15a4/tensorflow/python/ops/math_ops.py#L2446-L2462) and [SciPy](https://github.com/scipy/scipy/blob/13ba7a563518dda6619f3e8a832947f11fba09b4/scipy/special/_logsumexp.py#L94-L129) implement this function, I think the guess that led me to open this issue was mistaken: I don't think there's a more numerically stable way to write logsumexp with log1p (or at least, not a vectorized one that we'd want). For that reason, I'm going to close this issue.

@rbrishabh I really appreciate you jumping on this, even though it ended up my idea was bad! We should look for another "good first issue" for you to jump into. I can't think of one right this minute, but we'll be sure to keep up with the "good first issue" GitHub issue tags!

If anyone thinks of a more numerically stable way to compute logsumexp, let's reopen this issue (or open a new one).

**Comment by mattjj** [comment]
I also checked [how the TF2XLA bridge lowers SoftmaxCrossEntropyWithLogits](https://github.com/tensorflow/tensorflow/blob/f81d84e452709d85a390ef125b319cd26fad3095/tensorflow/compiler/tf2xla/kernels/softmax_op.cc#L165) and my reading of that file is that [it's computing things the same way JAX is too](https://github.com/tensorflow/tensorflow/blob/f81d84e452709d85a390ef125b319cd26fad3095/tensorflow/compiler/tf2xla/kernels/softmax_op.cc#L102-L134) (and in particular not using `log1p` in a clever way).
