### ISSUE TITLE
Drop Python 3.7 support

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#12100]
Per our [compatibility policy](https://jax.readthedocs.io/en/latest/deprecation.html) we should have dropped support for Python 3.7 in December 2021.

The only reason we have kept Python 3.7 support alive is because Colab is still on Python 3.7. When Colab upgrades, we will drop support.

**Comment by shoyer** [comment]
> The only reason we have kept Python 3.7 support alive is because Colab is still on Python 3.7. When Colab upgrades, we will drop support.

This happened!
https://medium.com/google-colab/colab-updated-to-python-3-8-4922f9970a72

**Comment by hawkinsp** [comment]
And we already dropped it!

**Comment by jakevdp** [comment]
I haven't done walrus operators, but I have done better f-strings #13458
