### ISSUE TITLE
accessing data on GPU

### ISSUE THREAD

**Issue by mgbukov** [google/jax#1215]
If my understanding is correct, jax is designed to have increased performance on GPUs. I have a few questions about accessing data in jax:

-- are the DeviceArray data types stored on the GPU? What is the rationale behind, and the desired use of, this data type? 

-- what is an efficient way to access the data stored in a DeviceArray without copying it (there's the DeviceArray._value private attribute but it's private so I figured it is not meant to be used for some good reason)? Is there a way to access the memory address of a DeviceArray, (e.g. if I need to use it the data outside jax but I don't want to make a physical copy)? 

-- is there a way to pass the address of a jitted function to a customized cpp code where the function can be called? 

Thanks!

**Comment by shoyer** [comment]
-- are the DeviceArray data types stored on the GPU? What is the rationale behind, and the desired use of, this data type?

Yes, DeviceArray objects will be stored on GPUs (if available). Or they can be stored on CPUs or TPUs.

-- what is an efficient way to access the data stored in a DeviceArray without copying it

`__cuda_array_interface__` would solve this: https://github.com/google/jax/issues/1100

-- is there a way to pass the address of a jitted function to a customized cpp code where the function can be called?

I know this is possible in principle, though I don't know exactly how :)

**Comment by mgbukov** [comment]
When it comes to passing a jax-jitted function to cpp, this can be done using cython, as follows:

- define a cdef/cpdef function which uses jax in its body. This is a C object, and one can pass a pointer to it to C using cython. 

- if the function is intended to be jitted, the input/output data types should be of type `object`. 

If one uses the cython-numpy data types (e.g. `ndarray`) in the definition of the cdef/cpdef-function arguments/output, then after jitting it, python throws this error when calling the function: 
```
incorrect type (expected numpy.ndarray, got JaxprTracer)
```
Note that Cython does allow to compile the function, probably because it doesn't know what's going on.

Since cython is also a prereq for jax, it might be useful to provide a `JaxprTracer` datatype to use with cython, since this will likely lead to speedup.

**Comment by hawkinsp** [comment]
`__cuda_array_interface__` is now supported, so that part should be resolved.

I see there was a question about calling into a JAX jit-compiled function from C/C++. Perhaps open a separate issue for that if it's something you want? It's not clear to me whether it's something you are asking for or merely curious about.

(Closing, since I'm not sure what's actionable in this issue, but please reopen if you want to add something!)
