### ISSUE TITLE
cannot import name 'stax' from 'jax.experimental' (in Jupyter notebook)

### ISSUE THREAD

**Issue by Brandsma** [google/jax#12160]
### Description

I have been trying to run some example code from a repository implementing normalizing flows in Jax (https://github.com/ChrisWaites/jax-flows). Trying to import 'stax' from 'jax.experimental' seems to fail with the following error:

```bash
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_66047/1298984118.py in <module>
      3 
      4 from jax import grad, jit, random
----> 5 from jax.experimental import stax, optimizers

ImportError: cannot import name 'stax' from 'jax.experimental' (/home/user/.pyenv/versions/3.7.11/lib/python3.7/site-packages/jax/experimental/__init__.py)
```

This happens during the import statement and can simply be reproduced with

```python
from jax.experimental import stax
```

The full code in which this bug occurred can be found [here](https://github.com/ChrisWaites/jax-flows/blob/master/examples/intro.ipynb).

Any ideas on how to fix this? Is it simply the wrong version of jax (v0.3.16) or jaxlib (v0.3.15)?

Thanks in advance!

### What jax/jaxlib version are you using?

jax v0.3.16, jaxlib v0.3.15

### Which accelerator(s) are you using?

CPU

### Additional System Info

Python 3.7.11, Linux Manjaro

**Comment by jakevdp** [comment]
`jax.experimental.xtax` was [deprecated in JAX version 0.2.25](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-2-25-nov-10-2021) and [removed in JAX version 0.3.16](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-16). Instead you can use
```python
from jax.example_libraries import stax
```
