### ISSUE TITLE
More concise naming for tree utilities

### ISSUE THREAD

**Issue by danijar** [google/jax#12195]
It would be a lot nicer to write `jax.tree.map()`, `jax.tree.flatten()` etc instead of the repetitive and longer `jax.tree_utils.tree_map()`, etc (and after running the code realize that it's actually `tree_util` and not `tree_utils`). It's probably a bit late to consider a change like that but I think it would be more Pythonic (remind less of Java) and increase user happiness! 🙂

**Comment by jakevdp** [comment]
Thanks for the request! This is actually quite timely because we've been discussing exactly this idea in another thread. I think @froystig has plans to look into this idea in the coming weeks.

**Comment by jakevdp** [comment]
As of jax v0.4.25, the `jax.tree` module now has concise versions of common `jax.tree_util` functions: https://jax.readthedocs.io/en/latest/jax.tree.html
