### ISSUE TITLE
pure_callback passes jax.DeviceArray to the callback on CPU when not jitted

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#12194]
### Description

As title. 
This only happens when the callback is executed outside of jit boundaries.

This is different from the documented behaviour.

```python
➜ python
Python 3.10.6 (main, Aug 23 2022, 11:35:18) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> def test(x):
...   print(type(x))
...   return x
...
>>> def f(x):
...   return jax.pure_callback(test, x, x)
...
>>> x= jax.numpy.ones(3)
>>> f(x)
<class 'jaxlib.xla_extension.DeviceArray'>
DeviceArray([1., 1., 1.], dtype=float32)
>>> jax.jit(f)(x)
<class 'numpy.ndarray'>
DeviceArray([1., 1., 1.], dtype=float32)
```

### What jax/jaxlib version are you using?

jax 0.3.17

### Which accelerator(s) are you using?

CPU

### Additional System Info

MacOs

**Comment by sharadmv** [comment]
This is a straightforward fix on our end, though I'm curious, does this cause problems for you given that `DeviceArray`s behave like `np.ndarray`s?

**Comment by PhilipVinc** [comment]
They almost do.

I have a Python callback that creates a `np.random.default_rng` with the current PRNGKey I am using in order to have deterministic RNG across the Python/jax boundary.

Unfortunately, `default_rng` fails with jax arrays. (It's probably a bug on their end, but still, as you documented the callback to always return numpy arrays...)
