### ISSUE TITLE
add convenience wrapper for array updating with fancy index expressions

### ISSUE THREAD

**Issue by mattjj** [google/jax#122]
We should provide an `update` function that lets users write

```python
A = lax.update(A, (slice(1, None, 2), Ellipsis, slice(None, -3)), value)
```

which would behave similarly to this kind of expression in regular NumPy

```python
A[1::2, ...,  :-3] = value
```

except without the in-place mutation that would update any aliases. 

This wrapper would be similar to the `lax_numpy._rewriting_take` function we already have for handling complex indexing expressions, and would ultimately call into primitives like `lax.dynamic_update_slice` and `lax.index_untake`. Better name suggestions welcome!

This is a separate issue from whether to provide more convenient syntax for this kind of operation.

**Comment by georgedahl** [comment]
This is a really important operation for making it simple to express certain models. When using TF I have often had to spend a lot of time figuring out exactly how to use scatter_nd or whatever so making a clear correspondence with numpy syntax is useful.
