### ISSUE TITLE
Implement i0e and i1e bessel functions

### ISSUE THREAD

**Issue by brianwa84** [google/jax#1220]
These are useful for the von-Mises distribution on the unit circle.

**Comment by mattjj** [comment]
I'm hoping you can help us with these :) I didn't see any mention of these in TF2XLA; is there an existing implementation we can draw on? Or should we treat this as a CustomCall on CPU and GPU (like we treat linalg)?

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/1541

adds these. The Bessel functions were already added to XLA, so all we needed to do is plumb them through and define derivatives for them.
