### ISSUE TITLE
Add impl of `scipy.linalg.lu_solve`

### ISSUE THREAD

**Issue by brianwa84** [google/jax#1228]
This is used by the Glow generative model to parameterize an invertible 1x1 convolution.

A TF implementation in terms of triangular solve is here:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/math/linalg.py#L306

**Comment by hawkinsp** [comment]
Pretty much exactly the same functionality is already available via `jax.numpy.linalg.solve`, but I guess there's no harm in adding the `scipy` variant too. (It supports an additional transpose or conjugate transpose.)
