### ISSUE TITLE
JAX should throw an error (or warning?) when asked to cast to a dtype it does not support on a device

### ISSUE THREAD

**Issue by Sohl-Dickstein** [google/jax#1230]
I believe JAX should in some way notify the user when a cast operation cannot be performed.
``` python
a = np.ones((1,2,3))
print(a.dtype) # reports float32
a = np.array(a, dtype='float64') # JAX should throw an error on this line
print(a.dtype) # reports float32
```

**Comment by mattjj** [comment]
Great point, you're right! Let's do this.

By the way, if you want to switch on support for 64-bit values (in which case this cast will work as you expect), see the first item in our [Gotchas list](https://github.com/google/jax#current-gotchas).
