### ISSUE TITLE
Support for non-scalar np.repeat arguments.

### ISSUE THREAD

**Issue by thomaskeck** [google/jax#1233]
Hello, 

I noticed that jax.numpy.repeat does not support non-scalar repeats.

```
np.repeat(np.array([[1, 2, 3]]), np.array([2, 3, 1]))

NotImplementedError                       Traceback (most recent call last)
<ipython-input-120-c0c19bd58e3a> in <module>()
----> 1 np.repeat(np.array([[1, 2, 3]]), np.array([2, 3, 1]))

google3/third_party/py/jax/numpy/lax_numpy.py in repeat(a, repeats, axis)
   1539   if not isscalar(repeats):
   1540     raise NotImplementedError(
-> 1541         "np.repeat implementation only supports scalar repeats")
   1542   if axis is None or isscalar(a):
   1543     a = ravel(a)
```

The expected results with numpy:
```
array([1, 1, 2, 2, 2, 3])
```

Note that the documentation indicates that this is supported:
https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.repeat.html

Is it possible to add support for this in jax, and/or is there a workaround?

**Comment by mattjj** [comment]
Certainly doable! Anyone who wants to get started on this (maybe you!) should start by looking at [the current `np.repeat` implementation in lax_numpy.py.](https://github.com/google/jax/blob/d7894198a1ad0e54de42450c27ad5e715cb59aa1/jax/numpy/lax_numpy.py#L1596-L1622).

**Comment by xysun** [comment]
I have created a PR #1349 . Let me know if I missed anything. Thanks!

**Comment by thomaskeck** [comment]
Thanks for adding the support for non-scalar arguments.

There is still a difference to the numpy implementation, in case of zeros in the repeat argument:
```
(Pdb) np.repeat([1, 2], [1, 0])
array([1])
(Pdb) np.repeat([1, 2], [1, 1])
array([1, 2])
(Pdb) jnp.repeat(jnp.array([1, 2]), [1, 0])
*** ValueError: Need at least one array to concatenate.
(Pdb) jnp.repeat(jnp.array([1, 2]), [1, 1])
DeviceArray([1, 2], dtype=int32)
```

Full stack-trace:
```
  File "jax/numpy/lax_numpy.py", line 1959, in repeat
    ret = concatenate((ret, tile(a_splitted[i], repeat)))
  File "jax/numpy/lax_numpy.py", line 1526, in tile
    a = concatenate([a] * int(rep), axis=i)
  File "jax/numpy/lax_numpy.py", line 1532, in concatenate
    raise ValueError("Need at least one array to concatenate.")
ValueError: Need at least one array to concatenate.
```

I believe the issue could be fixed by adding:
if repeat != 0:
here https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L1961

I will submit a PR for this soon.
