### ISSUE TITLE
jax.config.update('jax_platforms', 'gpu') fails

### ISSUE THREAD

**Issue by ilemhadri** [google/jax#12335]
### Description

```
import jax
jax.config.update('jax_platforms', 'gpu')
jax.default_backend()
```

returns
```
RuntimeError: Unable to initialize backend 'rocm': NOT_FOUND: Could not find registered platform with name: "rocm". Available platform names are: Interpreter CUDA Host
```

On the other hand,
```
import jax
jax.default_backend()
```
succeeds and returns `gpu`.

### What jax/jaxlib version are you using?

jax 0.3.14, jaxlib 0.3.14

### Which accelerator(s) are you using?

GPU

### Additional System Info

V100 GPU,  Driver Version: 470.57.02,  CUDA Version: 11.4

**Comment by jakevdp** [comment]
The naming is confusing, but I think what you want is:
```python
jax.config.update('jax_platforms', 'cuda')
```

**Comment by ilemhadri** [comment]
thanks -- that works. it'd be great to have this in the doc as well!
