### ISSUE TITLE
`jnp.squeeze` will fail unexpectedly with `jit` compilation

### ISSUE THREAD

**Issue by Doraehhh** [google/jax#12331]
`jnp.squeeze` will fail unexpectedly with `jit` compilation but direct invocation will succeed. For example,

```py
import jax

def fn(inp):
    axis = jax.numpy.array(1, dtype=jax.numpy.int32)
    return jax.numpy.squeeze(inp, axis)

mykey = jax.random.PRNGKey(0)
inp = jax.random.uniform(mykey, [3, 1], jax.numpy.float32, minval=0, maxval=1)

print(fn(inp))
# [0.9653214  0.31468165 0.63302994]

jax.jit(fn)(inp)
# TypeError: iteration over a 0-d array
```

I think the input is valid since the dim-`1` has shape 1.

## Version

jax 0.3.17

**Comment by Doraehhh** [comment]
BTW, `jnp.expand_dims` has a similar issue

```
import jax

def fn(inp):
    axis = jax.numpy.array(0, dtype=jax.numpy.int64)
    return jax.numpy.expand_dims(inp, axis)

inp = jax.numpy.array(128, dtype=jax.numpy.float32)

print(fn(inp))
# [128.]

jax.jit(fn)(inp)
# TypeError: iteration over a 0-d array
```

**Comment by jakevdp** [comment]
The error is misleading here, but I believe the issue is that in both cases the `axis` argument must be static, and when you pass a jax array it becomes traced. We should update the `_ensure_index_tuple` helper function to return a more suitable error in this case.
