### ISSUE TITLE
Unexpected CPU memory allocation when running on GPU with torch

### ISSUE THREAD

**Issue by aldethux** [google/jax#12340]
### Description

The first call to `jax.random.split` allocates ~3GB of RAM and keeps it until the process finishes.
- the issue occurs when running the script with GPU support **and** with `torch` being imported
- the issue does not occur when I force jax to use CPU **or** do not import `torch`

Minimal example:
```
import os
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '0.8'

import jax
import torch  # if torch is not imported, no memleak is observed
from memory_profiler import profile

# if using CPU, no memleak is observed
# jax.config.update('jax_platform_name', 'cpu')

@profile
def memleak():
    key = jax.random.PRNGKey(220)
    # MEMLEAK: next line increases RAM consumption
    key_1, key_2 = jax.random.split(key, 2)

memleak()
```
which prints:
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    14    388.3 MiB    388.3 MiB           1   @profile
    15                                         def memleak():
    16    713.6 MiB    325.2 MiB           1       key = jax.random.PRNGKey(220)
    17                                             # MEMLEAK: next line increases RAM consumption
    18   3754.8 MiB   3041.3 MiB           1       key_1, key_2 = jax.random.split(key, 2)
```

<details>
<summary>Dockerfile to replicate the env</summary>

```
FROM nvidia/cuda:11.4.3-devel-ubuntu18.04

ARG DIR=/root/jax-memleak
RUN mkdir $DIR
WORKDIR $DIR

RUN apt-get update && apt-get install -y wget

ARG CONDA=miniconda.sh
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.10.3-Linux-x86_64.sh -O $CONDA \
    && bash $CONDA -b -p ~/opt/miniconda \
    && rm $CONDA

RUN eval "$(~/opt/miniconda/bin/conda shell.bash hook)" \
    && conda init \
    && conda create -y -n jax python=3.9 \
    && conda activate jax \
    && echo "conda activate jax" >> ~/.bashrc\
    && conda install -y pytorch==1.11.0 cudatoolkit=11.3 -c pytorch \
    && pip install "jax[cuda11_cudnn82]==0.3.13" \
            -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html \
        memory_profiler

ENTRYPOINT ["/bin/bash"]
```

</details>

(run container with GPU forwarding: `--gpus=all`)

### What jax/jaxlib version are you using?

jax v0.3.13, jaxlib v0.3.10+cuda11.cudnn82 (system wide cuda v11.4)

### Which accelerator(s) are you using?

GPU

### Additional System Info

Python 3.9.12, Ubuntu

**Comment by hawkinsp** [comment]
That working as intended. See https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

I'm guessing 3GB is 80% of your available GPU memory?

**Comment by aldethux** [comment]
> I'm guessing 3GB is 80% of your available GPU memory?

No. The issue is with host memory, not GPU memory. For example, if I set `XLA_PYTHON_CLIENT_MEM_FRACTION = 0.2`, I get the same result. `sleep(*)` at the end + `htop` confirm that the memory profiler is sane.

**Comment by mattjj** [comment]
@pschuh are you up for taking a look at this?

**Comment by pschuh** [comment]
`jax.random.split` contains a custom call to `cuda_threefry2x32`. Cuda will initialize all linked kernels every time you dispatch a kernel (each of which require ram for loading). This means that cuda is picking up and loading all of the linked kernels. If we insert any pytorch calls before the jax.random.split call, the memory increase will be assigned there instead.
