### ISSUE TITLE
lax.scatter inconsistent results between CPU and GPU

### ISSUE THREAD

**Issue by seanmor5** [google/jax#12359]
### Description

Checked for duplicates but I might have missed something.

The following snippet returns inconsistent results between CPU and GPU runtimes. I checked this on Google Colab.

```python
from jax import lax
import numpy as np

inp = np.array([0, 0, 0])
indices = np.array([[1], [2], [1]])
updates = np.array([3, 4, 2])

update_window_dims = ()
inserted_window_dims = (0,)
scatter_dims_to_operand_dims = (0,)

scatter_dim_nos = lax.ScatterDimensionNumbers(update_window_dims=update_window_dims,
                                              inserted_window_dims=inserted_window_dims,
                                              scatter_dims_to_operand_dims=scatter_dims_to_operand_dims)

lax.scatter(inp, indices, updates, scatter_dim_nos)
```

On CPU it returns: 

```
DeviceArray([0, 2, 4], dtype=int32)
```

On GPU it returns:

```
DeviceArray([0, 3, 4], dtype=int32)
```

### What jax/jaxlib version are you using?

jax v0.3.17, jaxlib v0.3.15

### Which accelerator(s) are you using?

CPU/GPU

### Additional System Info

Google Colab

**Comment by hawkinsp** [comment]
This is working as intended:
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scatter.html

"If multiple updates are performed to the same index of operand, they may be applied in any order."

Make sense?

**Comment by seanmor5** [comment]
I should have read deeper into it, thanks! :)
