### ISSUE TITLE
Allow pjit to close over values sharded on multiple devices

### ISSUE THREAD

**Issue by nikolamomchev** [google/jax#12354]
Consider the following code fragment:

```py
x = load_checkpoint()

@partial(pjit, in_axis_resources=in_sharding, out_axis_resources=out_sharding):
def foo(a)
  return a + x

y = load_another_checkpoint()
z = foo(y)
```
The call to `foo(y)` fails if the value of `x` is sharded over multiple hosts.

One scenario when supporting this would be very useful is if one need to close over a large static model in order to adapt to the interface required by an existing library they use. E.g. assume one wants to use the `XTraner` class below, which is a part of a library they don't have control over. I.e. they can't modify or extend `XTrainer` or `loss_fn`.

```py
@dataclass
class XTrainer:
  loss_fn: Callable[[Prediction, BatchType], LossValue]
  
  @partial(pjit, ...)
  def train_step(self, input_batch: BatchType, train_state: TrainState) -> TrainState:
    """Performs a single gradient descent step on the model represented with `train_state`.
       Runs a prediction in the model and computes the value of the loss by calling `loss_fn`.
    """
    ...
```

There are cases in which one would want to exercise a static pre-trained model inside the implementation of `loss_fn`. Some that come to mind are:
1. One wants to train from human feedback as in [InstructGPT](https://arxiv.org/abs/2203.02155).
2. One wants to distill the trained model to be close to a target, pre-trained model.

Unfortunately, if the static model needs to be sharded over multiple hosts, this is currently not supported and AFAIK, one can't use `XTrainer` without modification in this case.

**Comment by yashk2810** [comment]
Yes, please use what @GallagherCommaJack suggested or pass the sharded Array as an argument.

Feel free to reopen if both techniques don't work.
