### ISSUE TITLE
JAX Sets Basic Logging Config

### ISSUE THREAD

**Issue by daskol** [google/jax#12374]
### Description

JAX configures the root logger facility what is a little breaking behavior since using JAX in a third-party application changes logging configuration of the whole app! In my opinion, such side-effects are not desirable and should be fixed. 

```python3
import logging, jax
# The next line does nothing since the root logger is already created. We need
# to reset the root logger with force=True option.
logging.basicConfig(level=logging.INFO)
logging.error('error')
logging.info('info')
```
#### Expected output
```
ERROR:root:error
INFO:root:info
```
#### Actual output
```
ERROR:root:error
```

### What jax/jaxlib version are you using?

jax v0.3.17, jaxlib v0.3.15

**Comment by jakevdp** [comment]
Hi - thanks for the report! I believe this is the same issue discussed here: https://github.com/google/jax/discussions/12182 and there's a potential fix in progress here: https://github.com/google/jax/pull/10968 (though it seems like it may have stalled?)

**Comment by daskol** [comment]
This issue is totally the same one as #12182. Close this issues as duplicated.
