### ISSUE TITLE
jax.numpy.average can't take tuple axis

### ISSUE THREAD

**Issue by AllanChain** [google/jax#12388]
### Description

Tuple axis is documented: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.average.html#jax.numpy.average

And supported in numpy:

```python
import numpy as np
np.average(np.arange(0, 4), axis=(0,), weights=np.arange(1, 5))  # 2.0
```

But will result an error

```python
from jax import numpy as jnp
jnp.average(jnp.arange(0, 4), axis=(0,), weights=jnp.arange(1, 5))
```

```
TypeError: 'tuple' object cannot be interpreted as an integer
```

Possibly related: #6451

### What jax/jaxlib version are you using?

jax v0.3.17, jaxlib v0.3.15

### Which accelerator(s) are you using?

CPU

### Additional System Info

Linux

**Comment by mattjj** [comment]
@jakevdp are you up for taking this one?
