### ISSUE TITLE
Error on large TPU Pods

### ISSUE THREAD

**Issue by wilson1yan** [google/jax#12456]
### Description

Hi,

I'm not sure if this is a jax bug, or an issue on the TPU side. Steps to replicate my issue:

1) Create a v3-128 TPU instance
2) Install `jax`: `pip install "jax[tpu]" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`
3) Run `script.py` (for all instances)

```
# script.py
import jax
print(jax.device_count())
```

I get the following error **only on the first machine (....-w-0)**. The other machines just stall with the `TPU backend initializatoin is taking ....` warning.
```
$ python3 script.py
/home/wilson/.local/lib/python3.8/site-packages/jax/_src/lib/xla_bridge.py:184: UserWarning: TPU backend initialization is taking more than 60.0 seconds. Did you run your code on all TPU hosts? See https://jax.readthedocs.io/en/latest/multi_process.html for more information.
  warnings.warn(
https://symbolize.stripped_domain/r/?trace=7facba4a8de2,7fadfda3d08f,7facba4ad373,7facb845d7c2,7facbd753668,7facbd74f0fd,7fadfd9df608&map=068bf80b76f830987166dd8847d0248f:7faca8298000-7facbdbcade0 
*** SIGSEGV (@(nil)), see gl__________41#s15 received by PID 11743 (TID 12350) on cpu 17; stack trace: ***
PC: @     0x7facba4a8de2  (unknown)  (unknown)
    @     0x7facbd838294        976  (unknown)
    @     0x7fadfda3d090    1120528  (unknown)
    @     0x7facba4ad374         32  (unknown)
    @     0x7facb845d7c3         48  (unknown)
    @     0x7facbd753669        112  (unknown)
    @     0x7facbd74f0fe        240  (unknown)
    @     0x7fadfd9df609  (unknown)  start_thread
https://symbolize.stripped_domain/r/?trace=7facba4a8de2,7facbd838293,7fadfda3d08f,7facba4ad373,7facb845d7c2,7facbd753668,7facbd74f0fd,7fadfd9df608&map=068bf80b76f830987166dd8847d0248f:7faca8298000-7facbdbcade0 
E0922 01:12:51.498153   12350 coredump_hook.cc:370] RAW: Remote crash data gathering hook invoked.
E0922 01:12:51.498165   12350 coredump_hook.cc:416] RAW: Skipping coredump since rlimit was 0 at process start.
E0922 01:12:51.498174   12350 client.cc:242] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0922 01:12:51.498181   12350 coredump_hook.cc:477] RAW: Sending fingerprint to remote end.
E0922 01:12:51.498186   12350 coredump_socket.cc:118] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0922 01:12:51.498196   12350 coredump_hook.cc:481] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0922 01:12:51.498202   12350 coredump_hook.cc:555] RAW: Discarding core.
E0922 01:12:51.645117   12350 process_state.cc:774] RAW: Raising signal 11 with default behavior
Segmentation fault (core dumped)
```

My `jax` versions across all instances are
```
jax==0.3.17
jaxlib==0.3.15
libtpu-nightly==0.1.dev20220723
```

A few notes:

- This worked fine on and before 9/20
- I get a similar error on `jax==0.3.13`, so I don't think it's version dependent (hence I'm not sure if this is a jax bug)
- **This only happens on a larger instance. This does not happen on v3-32 and v3-64.**

**Comment by skye** [comment]
Just to check, you're using `--version tpu-vm-base` when you're creating the v3-128?

Can you share `/tmp/tpu_logs/tpu_driver.INFO` from the failing worker after you get that segfault? The same file from other workers may also be useful if it's easy to grab, but the failing one is likely the most useful.

**Comment by wilson1yan** [comment]
Thanks for getting back!

It seems like the issue has fixed itself somehow. I don't think it was random yesterday either since every v3-128 I allocated had the same issue, but seems to work fine on the first time today.

I'll close the issue for now unless it happens against sometime in the future

**Comment by sumanthd17** [comment]
I'm having the same issue. The worker is stalled at the warning. Any ideas on why this could be happening?

**Comment by skye** [comment]
@sumanthd17 could you file a new issue giving more information (e.g. TPU type, what you're running, what you get on each host, anything else that could be useful)? Please tag me in it too.

**Comment by skye** [comment]
Also make sure you're invoking your Python script on each TPU node if you're not already.

**Comment by sh0416** [comment]
In my log file, there is an error message.
```
FAILED_PRECONDITION: Failed to read file [type.googleapis.com/util.ErrorSpacePayload='util::PosixErrorSpace::Bad file descriptor']
```
How to resolve it?
