### ISSUE TITLE
Tensorflow XLA overview.md renamed to architecture.md (Broken link)

### ISSUE THREAD

**Issue by muller0** [google/jax#1248]
In Readme.md the XLA is linking to:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/g3doc/overview.md 

But it seems it moved to:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/g3doc/architecture.md

It is minor bug, but can be annoying for newcommers.

**Comment by mattjj** [comment]
Thanks for catching this! I think we now want to link here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/g3doc/index.md
