### ISSUE TITLE
eig bug in M1 mac

### ISSUE THREAD

**Issue by yonghakim** [google/jax#12505]
### Description

Hi,

Thanks for this great code!

I encountered that a complex matrix larger than 4x4 shows nans in eigen decomposition.
This happened on M1 mac air so I tried on Ubuntu and it was OK.

Code and result are below.

```
import jax.numpy as np

mat = np.array([
                    [1+1j, 3+2j, 4.0+1.1j, 11-0.00001j, 44+100j],
                    [22+0j, 23+2j, 0.5+0.93j, 33+12j, 0.0001+0.000001j],
                    [-11-1j, 23+87j, 11-0.002j, 32-0.03423j, 32+9j],
                    [0.0002+23j, 10+0.324j, 0.003+0.999j, 10.434+2j, 33+0j],
                    [3+0.9j, 12+12j, 3.22+98j, 0.024+99.123j, 0+123j]
                ])

print(np.linalg.eig(mat[:-1, :-1]))
print(np.linalg.eig(mat))

```

> WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
> [DeviceArray([-5.2624492e+03+1.4113758e+04j,  4.1820871e+02-1.0527565e+03j,
>              -1.2092521e+00+1.9994103e+00j,  1.9019674e+01-9.6972170e+00j],            dtype=complex64), DeviceArray([[-0.02891346-0.03971068j,  0.02957509-0.0474329j ,
>               -0.44557735+0.02970533j, -0.02008874-0.26034266j],
>              [-0.2935256 -0.21373105j,  0.37181988-0.1171477j ,
>                0.23084457-0.00424225j,  0.6908359 +0.j        ],
>              [ 0.76046956+0.j        ,  0.91793585+0.j        ,
>                0.8543233 +0.j        , -0.62931746+0.16163293j],
>              [ 0.21497846-0.49114057j, -0.00752115+0.04731937j,
>               -0.01526484+0.13103274j, -0.04365756-0.17462084j]],            dtype=complex64)]
> [DeviceArray([nan+nanj, nan+nanj, nan+nanj, nan+nanj, nan+nanj], dtype=complex64), DeviceArray([[nan+nanj, nan+nanj, nan+nanj, nan+nanj, nan+nanj],
>              [nan+nanj, nan+nanj, nan+nanj, nan+nanj, nan+nanj],
>              [nan+nanj, nan+nanj, nan+nanj, nan+nanj, nan+nanj],
>              [nan+nanj, nan+nanj, nan+nanj, nan+nanj, nan+nanj],
>              [nan+nanj, nan+nanj, nan+nanj, nan+nanj, nan+nanj]],            dtype=complex64)]
> 
> Process finished with exit code 0

Thanks!

### What jax/jaxlib version are you using?

jax v0.3.13

### Which accelerator(s) are you using?

CPU

### Additional System Info

M1 Mac

**Comment by hawkinsp** [comment]
I can't reproduce this on a Macbook M1 Pro.

Can you please try updating `jax`, `jaxlib` and `scipy` and trying again?

If it still fails, let me know the versions of: `python`, `numpy`, `scipy`, `jax` and `jaxlib` and how you installed them.

**Comment by yonghakim** [comment]
updating jax fixed it!
Thanks.

Just in case, this is what I used before.
python == 3.9.6
numpy == 1.21.1
scipy == 1.7.0
jax == 0.3.13
jaxlib == 0.3.10

**Comment by hawkinsp** [comment]
If I had to guess, updating `scipy` probably fixed it, because the `eig` kernel comes from the LAPACK inside scipy.
