### ISSUE TITLE
jax_debug_nans interaction with buffer donation

### ISSUE THREAD

**Issue by mattjj** [google/jax#12514]
When we set `jax_debug_nans`, we might try to re-run jitted computations. But if those jitted computations involve buffer donation, then we'll get a low-level runtime error about repeatedly donating the same input:

```
Invalid nan value encountered in the output of a C++-jit/pmap function. Calling the de-optimized version.
[10:13:36 pjrt_stream_executor_client.cc:2130] Execution of replica 0 failed: INVALID_ARGUMENT: Invalid buffer passed to Execute() as argument 0 to replica 0: INVALID_ARGUMENT: Donation requested for invalid buffer
```

TODO: make a repro

**Comment by mattjj** [comment]
As a workaround: anyone encountering this issue should just disable argument donation!

**Comment by Abandonist** [comment]
Thanks for the information @mattjj! I encountered the same error, but don't know how to fix it by code. Can you give more detail on how to disable argument donation?

**Comment by mattjj** [comment]
Perhaps when debug_nans is set, we should ignore donate_agnums...

@Abandonist is there any use of the `donate_argnums` parameter to `jit` in your code? If so, just delete it. Or is it in a library you're calling?

**Comment by Abandonist** [comment]
> Perhaps when debug_nans is set, we should ignore donate_agnums...
> 
> @Abandonist is there any use of the `donate_argnums` parameter to `jit` in your code? If so, just delete it. Or is it in a library you're calling?

It's fixxed, thank you very much! @mattjj This parameter was found in the invoked library. 
Interestingly, the same code can run well in the Colab, but doesn‘t work in Kaggle. Maybe it is caused by different Cudda versions?
