### ISSUE TITLE
Incorrect comments in setup.py

### ISSUE THREAD

**Issue by cemlyn007** [google/jax#12528]
### Description

Documented URLs are wrong for TPU in `setup.py`, please see: https://github.com/google/jax/blob/1bcf8d646dfa9f5c87a42280b37bb125c46d447f/setup.py#L86 as an example.

This should reference the URL documented in: https://github.com/google/jax#pip-installation-google-cloud-tpu

### What jax/jaxlib version are you using?

JAX 0.3.17

### Which accelerator(s) are you using?

TPU

### Additional system info

Python 3.8

**Comment by hawkinsp** [comment]
https://github.com/google/jax/commit/8d8643664c9fa9a0ab3ac2eaff0d9d003cbf8852 fixed this.

**Comment by cemlyn007** [comment]
Thanks mate, have a good day!
