### ISSUE TITLE
Array typing/IDE errors since version 0.3.18

### ISSUE THREAD

**Issue by brentyi** [google/jax#12536]
### Description

JAX 0.3.18 seems to have included some updates to the way array types are handled (via the introduction of `jax.Array`).

This seems to have broken some things for those of us running type checkers. Basic operations like `some_array.shape` now result in errors in both `pyright` and `mypy`:

![image](https://user-images.githubusercontent.com/6992947/192605080-591e182a-ed32-4ee0-90d8-91b8aae0d155.png)

Tab completion for common array operations like `.shape`, `.reshape()`, `.astype()`, etc also seems broken.

Is this a bug? If so is there a fix planned?

Thanks so much!!

### What jax/jaxlib version are you using?

jax v0.3.18, v0.3.19

**Comment by jakevdp** [comment]
Thanks for the report, and sorry for this issue! In 0.3.18 we introduced more restrictive array types as part of the work in #12049. Those array attributes are defined in the stub file here: https://github.com/google/jax/blob/main/jax/_src/basearray.pyi

This is enough to satisfy mypy in our github CI checks, as well as google's internal fork of pytype, which is used for Google's internal static type checking.

I wonder why it's not working for you? Perhaps the `.pyi` file is somehow not being properly registered?

**Comment by jakevdp** [comment]
Looks like we needed to include the pyi files in the package data. #12538 should fix the issue for the next release.

Would you mind trying an install from that branch and let me know if it fixes your issue?

**Comment by brentyi** [comment]
That did it, thanks!!

It's also super exciting to read through the type annotation roadmap in your link, particularly if `ParamSpec` ever makes it into function transforms :smiling_face_with_tear:

**Comment by jakevdp** [comment]
Nice, thanks for checking. Unfortunately we just pushed an 0.3.19 release, so I'll have to get the packaging fix into 0.3.20
