### ISSUE TITLE
PyPI macOS binaries missing for jaxlib 0.1.26

### ISSUE THREAD

**Issue by JuliusKunze** [google/jax#1254]
`pip install --upgrade jax jaxlib`

currently fetches `jaxlib==0.1.25` on macOS, which breaks all [JAXnet tests](https://github.com/JuliusKunze/jaxnet/tree/master/tests), while

`pip install --upgrade jax jaxlib==0.1.23`

makes them run fine. The macOS binary for `jaxlib==0.1.26` seems to be missing.

**Comment by JuliusKunze** [comment]
Can confirm, `0.1.26` works with Anaconda and fails without it.

**Comment by JuliusKunze** [comment]
Can't install 0.1.27 with pip. Can you double-check it's up?

**Comment by JuliusKunze** [comment]
Yes, I was using `pip install --upgrade jax jaxlib==0.1.27`. Maybe the PyPI servers need some time? Will try again tomorrow.

**Comment by JuliusKunze** [comment]
Can confirm that 0.1.27 is found in Python 3.7 even without conda. For Python 3.6.5 however, `pip install --upgrade jaxlib` resolves to 0.1.26.

**Comment by JuliusKunze** [comment]
Yes it does work properly (forgot to mention!)

**Comment by hawkinsp** [comment]
We added Python 3.6 wheels for Jaxlib 0.1.27, so I think this is now fixed.

**Comment by JuliusKunze** [comment]
Can confirm.

**Comment by thierrymoudiki** [comment]
Hi, does it still work for all of you? I'm having the same issue on my mac (trying to import the extension 'xla_extension.so'). 

Here is the detailed error message: 

`Python 3.7.4 (default, Aug 13 2019, 15:17:50)
Type "copyright", "credits" or "license" for more information.

IPython 7.8.0 -- An enhanced Interactive Python.

import jax.numpy as np
Traceback (most recent call last):

  File "<ipython-input-1-122f308a8eba>", line 1, in <module>
    import jax.numpy as np

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/__init__.py", line 19, in <module>
    from jax.api import *

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/api.py", line 45, in <module>
    from . import ad_util

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/ad_util.py", line 20, in <module>
    from .tree_util import register_pytree_node

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/tree_util.py", line 44, in <module>
    from .lib import pytree

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/lib/__init__.py", line 40, in <module>
    from jaxlib import xla_client

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_client.py", line 37, in <module>
    from . import xla_extension as _xla

ImportError: dlopen(/Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: __ZNSt3__118shared_timed_mutex11lock_sharedEv
  Referenced from: /Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_extension.so
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_extension.so`

**Comment by shoyer** [comment]
Please open a new issue with a description of how you installed JAX

**Comment by thierrymoudiki** [comment]
ok, thanks

**Comment by DhruvDh** [comment]
Installed jax with (on Ubuntu inside WSL) 
```
pip3 install --upgrade jax jaxlib
```

While import anything from jax I get the error 
```
ValueError: jaxlib is version 0.1.23, but this version of jax requires version 0.1.26.
```

And no version 0.1.26 is available -
```
 ✘  .../Documents/HPC  python3 --version
Python 3.7.3
 .../Documents/HPC  pip3 install jaxlib==0.1.27
Collecting jaxlib==0.1.27
  Could not find a version that satisfies the requirement jaxlib==0.1.27 (from versions:
0.1, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.11, 0.1.12, 0.1.1
3, 0.1.14, 0.1.15, 0.1.16, 0.1.17, 0.1.18, 0.1.19, 0.1.20, 0.1.21, 0.1.22, 0.1.23)
No matching distribution found for jaxlib==0.1.27
```

**Comment by jekbradbury** [comment]
You need to upgrade your pip (`pip install --upgrade pip`)

**Comment by CharlesJQuarra** [comment]
Even with the latest PyPI binaries the problem keeps happening in my case:

```ImportError: dlopen(/usr/local/lib/python3.7/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: __ZNSt3__118shared_timed_mutex11lock_sharedEv
  Referenced from: /usr/local/lib/python3.7/site-packages/jaxlib/xla_extension.so
  Expected in: /usr/lib/libc++.1.dylib```
