### ISSUE TITLE
Create DeviceArray using device pointers

### ISSUE THREAD

**Issue by imoneoi** [google/jax#12558]
Can we instantiate a DeviceArray by pointers to device memory, shape and dtype, to integrate with other CUDA programs?

There is the `unsafe_buffer_pointer` API to obtain device memory address from a DeviceArray, but can we construct one by the pointer? (as https://github.com/google/jax/issues/1031)

Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by hawkinsp** [comment]
The only supported method for this is using `dlpack` (https://jax.readthedocs.io/en/latest/jax.dlpack.html)

There is also a feature request for supporting `__cuda_array_interface__`. (https://github.com/google/jax/issues/1100)

Hope that helps!
