### ISSUE TITLE
Discrepancy between timeit function call vs %timiet

### ISSUE THREAD

**Issue by SaitejaUtpala** [google/jax#12564]
### Description

```
def fun(a,b):
  "some computation which computes results" 
  return result

**approach 1** : 
temp = lambda: fun(a, b).block_until_ready()
time = timeit(temp, setup=temp, number=N)/N   # run N number of times and take avg

**approach 2**
# warmup call 
fun(a,b).block_until_ready()
%timeit fun(a,b).block_until_ready()
```

I am finding significant discrepancy between these two approaches of measuring times. 
1) am I doing everything correctly ?
2) If so, which is best one for measuring time 
3) If both are correct, this shouldn't happen. Is this bug ?

Thanks in advance

### What jax/jaxlib version are you using?

jax   : 0.3.17 jaxlib: 0.3.15+cuda11.cudnn805

### Which accelerator(s) are you using?

GPU

### Additional system info

linux

**Comment by jakevdp** [comment]
It looks like you're doing the warmup call for `%timeit` but not for `timeit()`. That could cause a discrepancy.

**Comment by SaitejaUtpala** [comment]
@jakevdp Thanks for reply. But `setup` argument already does this right ?. Even if not timeit() reported much less time, so if we made warmup call , it will be even more less?

I wanted to report results in a paper. Just wanted to make sure I am not doing anything silly !

**Comment by jakevdp** [comment]
I think this is working as intended, given the information from the `%timeit` docs above. Let us know if you have other questions
