### ISSUE TITLE
Jax documentation night theme ? 

### ISSUE THREAD

**Issue by thibmonsel** [google/jax#12572]
I was wondering if a night theme is available for jax documentation, i have looked around and haven't found one. 
It would be a nice feature for obvious reasons :) 

Thanks !

**Comment by jakevdp** [comment]
We currently use `sphinx_book_theme` for our docs. It looks like dark theme is not available, but there is a tracking issue here: https://github.com/executablebooks/sphinx-book-theme/issues/265
