### ISSUE TITLE
Please make jnp.delete jittable.

### ISSUE THREAD

**Issue by chansoo-google** [google/jax#12592]
Current workaround:
```
@jax.jit
def apply_except_one(x, i):
  idx = jnp.arange(x.shape[0])
  idx = jnp.where(idx >= i, idx + 1, idx)[:-1]
  return _complex_jittable_function(x[idx])
```

Desired state:
```
@jax.jit
def apply_except_one(x, i):
  return _complex_jittable_function(jnp.delete(x, i))
```

**Comment by zhangqiaorjc** [comment]
```
>>> jax.jit(jnp.delete, static_argnums=1)(jnp.arange(5), 2)
DeviceArray([0, 1, 3, 4], dtype=int32)
```

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError and https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html#jax.jit

**Comment by mattjj** [comment]
Sorry, there's chat context here! We don't want to use `static_argnums`, and indeed we don't really have to. (See the JAXers thread with Blake.)

**Comment by zhangqiaorjc** [comment]
Just saw that thread :)

Assigning to you instead :)

**Comment by mattjj** [comment]
Assign Peter to everything, like we talked about! ;)

**Comment by JiaYaobo** [comment]
> Sorry, there's chat context here! We don't want to use `static_argnums`, and indeed we don't really have to. (See the JAXers thread with Blake.)

@mattjj Hi matthew, I think I miss the chat or thread ? so how exactly make jnp.delete jittable without static_argnums? :)

**Comment by mattjj** [comment]
For posterity, the googlers-only link to the chat thread is go/jax-jittable-jnp-delete.
