### ISSUE TITLE
Possible contribution: scipy.stats.truncnorm

### ISSUE THREAD

**Issue by adrn** [google/jax#12618]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

I notice there is functionality for generating samples from a truncated normal in `jax.random.truncated_normal`, but no way of evaluating the pdf/cdf of a truncated normal (a la `scipy.stats.truncnorm`). I need this for one of my own projects, so implemented it locally, but I would be happy to contribute it here! I implemented it as a parallel implementation to `sciyp.stats.truncnorm` (and could contribute that to `jax.scipy.stats.truncnorm`), but I would also be happy to have a modified version with limits in the scaled/shifted space (`lower`, `upper` vs. `a`, `b`) like `jax.random.truncated_normal`.

**Comment by jakevdp** [comment]
Hey Adrian, thanks for the request! I think we'd welcome that contribution to `jax.scipy.stats`, along the lines of the existing distributions defined there. Are you interested in contributing your implementation?

**Comment by adrn** [comment]
👋 Hey! Nice to hear from you :).

Yes, happy to — I'll open a PR. thanks!

**Comment by jakevdp** [comment]
Cool, feel free to request a review from me when it's ready
