### ISSUE TITLE
PRNG performance regression on XLA:GPU

### ISSUE THREAD

**Issue by mattjj** [google/jax#1267]
This is the public version of the internal bug b/140251596. We think the new way we lower `lax.while_loop` to the While HLO (where we generate a `Call` for convenience) caused a big performance regression for PRNGs on GPU.

EDIT: it turns out that avoiding the `Call`s didn't help: it was a rolled vs unrolled loops thing, cf #1175. More commentary below and in #1269.

**Comment by mattjj** [comment]
Before #1269 (on current master) I see this on a public gpu colab instance:

![image](https://user-images.githubusercontent.com/1458824/63995350-085d5c80-caad-11e9-9fd8-684bd7263c3a.png)

After removing the Calls we were generating under While in 133b082 I see this:

![image](https://user-images.githubusercontent.com/1458824/63995308-e49a1680-caac-11e9-85e5-32f665399f45.png)

After further unrolling the loops in f77e265 (undoing #1175) I see this:

![image](https://user-images.githubusercontent.com/1458824/63995215-9dac2100-caac-11e9-82cd-32f034c14754.png)

So I think this is a loop rolling/unrolling issue on XLA:GPU (I only checked CPU execution time in #1175), though it remains a question why XLA:GPU performance is falling off a bit of a cliff with these loops. There may be a missing optimization.

cc @fehiepsi @jekbradbury @cheshire

**Comment by mattjj** [comment]
For completeness, on a CPU-backed public colab I see this on master (loops rolled):

![image](https://user-images.githubusercontent.com/1458824/63995555-ca146d00-caad-11e9-9198-2ef71a4578fc.png)

and this on f77e265 (loops unrolled):

![image](https://user-images.githubusercontent.com/1458824/63995579-e9ab9580-caad-11e9-8b10-74b5cb1725b2.png)


So the performance cliff of rolling the PRNG loops is GPU-specific, which might suggest it's about round-tripping the loop condition or something.

**Comment by fehiepsi** [comment]
@mattjj I just test your PR and observe that when using unroll loop, compiling time grows linearly (which is expected) in GPU  but it grows nonlinear in CPU. If I remember correctly, the before that PR, compiling time in GPU also grows nonlinear. So I guess using unroll loop is fine and there is an enhancement in GPU, but it is not yet adopted to CPU.
