### ISSUE TITLE
PYTHONOPTIMIZE=1 causes KeyErrors

### ISSUE THREAD

**Issue by benjamin-macadam** [google/jax#12688]
### Description

When I set the flag: `export PYTHONOPTIMIZE=1`, the code:
```
import jax.numpy as jnp
m = jnp.eye(5)
a = jnp.ones(5)
jnp.linalg.solve(m,a)
```
returns the following error:
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "error.py", line 6, in <module>
    jnp.linalg.solve(m,a)
  File "/home/ben/.../python3.8/site-packages/jax/_src/numpy/linalg.py", line 553, in solve
    return lax_linalg._solve(a, b)
KeyError: 139645559661888
```

### What jax/jaxlib version are you using?

jax v0.3.21, jaxlib v0.3.20

### Which accelerator(s) are you using?

CPU

### Additional system info

Ubuntu, jax is installed into a site_packages repo for ROS.

**Comment by mattjj** [comment]
Thanks for the report! I see the issue; there's an assert statement we're counting on running.
