### ISSUE TITLE
pjit outputs GDA with non-matching mesh_axes/pspec

### ISSUE THREAD

**Issue by dlwh** [google/jax#12702]
### Description

When using GDA, if you have a case where one of your mesh axes is of size 1, the GDA output by pjit will sometimes ignore the provided pspec and just return a prefix pspec that doesn't include the size=1 mesh axis.

In particular, for an output with shape `(128, 128)` partitioned according to `('data', 'model')`, then *if the model axis is size 1*, it will return one that it says is partitioned according to `('data',)`. This is all well and good except if you continue to pass in pspecs to pjit, as below. This behavior makes it harder to develop code that works for cases where the model axis is size 1 vs not size 1 (and where you're evolving your code base from pre-GDA to GDA)

(Should I just be using jax.Array? they seemed even more experimental than GDAs)

(Run with `XLA_FLAGS=--xla_force_host_platform_device_count=8`, or adjust to suit)
```python
import jax
from jax.experimental.global_device_array import GlobalDeviceArray
from jax.random import PRNGKey
import jax.random as jrandom
from jax.experimental.pjit import pjit
from jax.interpreters.pxla import Mesh, PartitionSpec
import numpy as np

jax.config.update("jax_parallel_functions_output_gda", True)

# OK:
# mesh_shape (4, 2)
mesh_shape = (8, 1)

devices = jax.devices()

mesh = Mesh(np.array(devices).reshape(mesh_shape), ('data', 'model'))

key = PRNGKey(0)

with mesh:
    def f():
        return jrandom.normal(key, (128, 128))
    # GDA tupleizes the args here, which is fine
    desired_pspec = PartitionSpec( ('data', ),('model', ))

    f_pjit = pjit(f, in_axis_resources=None, out_axis_resources=desired_pspec)

    out: GlobalDeviceArray = f_pjit()
    assert out.shape == (128, 128)
    # BOOM
    assert out.mesh_axes == desired_pspec, f"{out.mesh_axes} != {desired_pspec}"

    def g(a):
        return a + a

    g_pjit = pjit(g, in_axis_resources=desired_pspec, out_axis_resources=desired_pspec)

    # also BOOM!
    out2: GlobalDeviceArray = g_pjit(out)
    # ValueError: Got an input GDA to pjit with different partitioning than specified in the in_axis_resources argument to pjit. The partitioning must match, or use `jax.experimental.pjit.FROM_GDA` in `in_axis_resources` for GDA. Got GDA sharding: MeshPspecSharding(mesh={'data': 8, 'model': 1}, partition_spec=PartitionSpec(('data',),)) and pjit sharding: MeshPspecSharding(mesh={'data': 8, 'model': 1}, partition_spec=PartitionSpec(('data',), ('model',)))
```

### What jax/jaxlib version are you using?

3.17, also main as of today 2022-10-07

### Which accelerator(s) are you using?

CPU, TPU

**Comment by yashk2810** [comment]
Seems to work for me at HEAD!

Can you confirm that you are using the latest jaxlib? This error will happen for an old jaxlib but not with the jaxlib on pypi!

**Comment by yashk2810** [comment]
You can try jaxlib nightly: `pip install -U --pre jaxlib -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_releases.html` and `pip install -U libtpu-nightly -f https://storage.googleapis.com/jax-releases/libtpu_releases.html` and then use JAX at HEAD

**Comment by yashk2810** [comment]
This will still fail at HEAD: `assert out.mesh_axes == desired_pspec, f"{out.mesh_axes} != {desired_pspec}"` but the last `out2: GlobalDeviceArray = g_pjit(out)` will work which I think is the thing you care about.

**Comment by dlwh** [comment]
ok great, even jaxlib 3.20 fixed it. Sorry about that! I tried jax HEAD but forgot to do jaxlib.

(My preference would be that the assert passes, but I get why it's not that important!)
