### ISSUE TITLE
Multi GPU deadlock when using collective ops

### ISSUE THREAD

**Issue by aaronbuhendwa** [google/jax#12701]
### Description

Hi,

we are facing strange behavior when using collective ops. Whenever a pmapped function includes jax.lax.all_gather or jax.lax.ppermute, the compilation of said function will stall indefinitely at 100% GPU utilization. However, the collective ops jax.lax.psum, jax.lax.pmean, jax.lax.pmin, jax.lax.pmax work fine.

Setup of the server/versions of the software:
-     Ubuntu 20.04
-     Nvidia Driver Version 515.65.01
-     CUDA Version: 11.7
-     8x NVIDIA A6000
-     jax 0.3.21, jaxlib 0.3.20

We tried installing jax/jaxlib both using the pip installation and building it from source. In the latter case, we manually install NCCL 2.13.4 before building jax/jaxlib from source. Both approaches yield the same outcome. We got the idea to build jax/jaxlib from source after reading the threads about similar issues https://github.com/google/jax/issues/10969, https://github.com/google/jax/issues/11637. Also, using different CUDA versions did not help. 

E.g., this simple code snippet will produce a deadlock.

import os
import jax
import numpy as np
os.environ["CUDA_VISIBLE_DEVICES"] = "0,1"
x = np.arange(2)
y = jax.pmap(lambda x: jax.lax.all_gather(x, axis_name='i'), axis_name='i')(x)

However, this code snippet works just fine:
x = np.arange(2)
y = jax.pmap(lambda x: jax.lax.pmin(x, axis_name='i'), axis_name='i')(x)

**Comment by hawkinsp** [comment]
I wasn't able to reproduce this on an 8xA100 machine (I ran the repro many times with those jax and jaxlib versions). I don't have access to any A6000 GPUs.

Any more tips on reproducing this?

**Comment by aaronbuhendwa** [comment]
It seems that the problem is related to NCCL. When we disable GPU-to-GPU (P2P) communication by setting the environment variable NCCL_P2P_DISABLE=1, everything works as expected.

We then upgraded the OS to Ubuntu 22.04 which (apparently) solved the issue.

**Comment by aaronbuhendwa** [comment]
This issue seems to have been fixed by the OS upgrade.
