### ISSUE TITLE
Key array is not an instance of `jax.random.KeyArray`

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#12706]
### Description

```python
import jax.random as rand
from typeguard import check_type

key = rand.PRNGKey(42)
check_type('key', key, rand.KeyArray)
```

```
Traceback (most recent call last):
  File "/nfs_share/bart-base-jax/3.py", line 5, in <module>
    check_type('key', key, rand.KeyArray)
  File "/home/ayaka/.venv310/lib/python3.10/site-packages/typeguard/__init__.py", line 785, in check_type
    raise TypeError(
TypeError: type of key must be jax._src.prng.PRNGKeyArray; got jaxlib.xla_extension.DeviceArray instead
```

### What jax/jaxlib version are you using?

jax v0.3.21, jaxlib v0.3.20

### Which accelerator(s) are you using?

TPU

### Additional system info

Python 3.10, Linux t1v-n-39911fbc-w-0 5.8.0-1035-gcp

**Comment by mattjj** [comment]
Thanks for surfacing this!

I think it may be intended behavior, in that `KeyArray` is only enabled behind a flag right now:

```bash
$ JAX_ENABLE_CUSTOM_PRNG=1 python -c "import jax.random as rand; from typeguard import check_type; check_type('key', rand.PRNGKey(42), rand.KeyArray)"
$
```

How'd you run into this?

**Comment by ayaka14732** [comment]
I was trying to add type annotation to my [code](https://github.com/ayaka14732/bart-base-jax/blob/9c4754200ced1b5ab3b2cc10ff7ffe1001d33a76/lib/model/fwd_transformer_encoder.py#L18). Before introducing jaxtyping + typeguard, I was using `np.ndarray` to annotate regular JAX arrays, and `KeyArray` to annotate key arrays. However, after I introduced typeguard, it complains that key array is not an instance of `jax.random.KeyArray`.

**Comment by jakevdp** [comment]
I would probably annotate it `key: Union[jax.Array, jax.random.KeyArray]` for now, and then once `JAX_ENABLE_CUSTOM_PRNG` becomes the default sometime in the future, change it to `key: jax.random.KeyArray`

**Comment by ayaka14732** [comment]
@jakevdp 

> When it's true, they're of type `jax.random.KeyArray`. The default is False now, but will become True at some point in the future. 

I am wondering what the purpose of this design is? And is this change going to happen soon?

**Comment by jakevdp** [comment]
The introduction of `KeyArray` is part of the new custom PRNG feature; you can read more in https://github.com/google/jax/issues/9263
