### ISSUE TITLE
np.stack raises incorrect exception when given a traced array 

### ISSUE THREAD

**Issue by gehring** [google/jax#1271]
```python
@jax.jit
def foo(x):
  return np.stack(x)

foo(np.zeros(2))  # this fails
```
Raises an exception because of a `if not arrays` check which assumes `arrays` is an object without a `__bool__` method so that the size of arrays would be used instead. Using `len(arrays) == 0` might be sufficient to fix this. This issue might be present in a few other places and might warrant a test.

Error message:
```python
TypeError: Abstract value passed to `bool`, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```

**Comment by mattjj** [comment]
Thanks for finding this, and explaining the fix! I updated `stack` and `concatenate` (the only two places in lax_numpy.py I could find with this pattern after a quick look) and added a simple test based on your code. #1299 should squash this.
