### ISSUE TITLE
iterate for extracting aux_data of custom pytree node

### ISSUE THREAD

**Issue by SaitejaUtpala** [google/jax#12711]
Consider following custom Pytree with auxillary data.

```
from jax.tree_util import register_pytree_node_class

@register_pytree_node_class
class CustomPytreeWithAuxData:
    def __init__(self, value, attr) :
        self.value = value
        self.attr = attr

   
    def tree_flatten(self):
        children = (self.value,)
        aux_data = self.attr
        return children, aux_data

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(children[0], aux_data)

```

Now consider transforming a two Pytree which have node of above type using jax.tree_map. But I want to transform using attribute which is an `aux data`, which will not be available if we using treemap, as transformation is done using only leaves.

jax.tree_map( lambda leave1, leave2 : # auxdata is not accessible here, Pytree1, Pytree2)

Any best solution ?

Thanks in advance.

**Comment by jakevdp** [comment]
One way you can do this is by using the `is_leaf` argument to specify that you want instances of your pytree class to be treated as leaves. For example:
```python
from jax.tree_util import tree_map

def f(x, y):
  return CustomPytreeWithAuxData(x.value * y.value, x.attr + y.attr)

A = CustomPytreeWithAuxData(2.0, 'A')
B = CustomPytreeWithAuxData(4.0, 'B')

out = tree_map(f, A, B, is_leaf=lambda x: isinstance(x, CustomPytreeWithAuxData))

print(out.value, out.attr)
# 8.0 AB
```

**Comment by SaitejaUtpala** [comment]
@jakevdp  Thats perfect and slick.
