### ISSUE TITLE
Memory leak when closing over large constants in compiled jax.lax.cond statement

### ISSUE THREAD

**Issue by wiep** [google/jax#12719]
### Description

I was running into an issue that I could condense to an elementary example. It seems to me as if closing over large constants in lax.cond creates a memory leak.

I've reported a similar issue concerning lax.fori_loop in #11448 which was solved in PR #11461. However, my followup post in the original issue got no attention so I decided to close the original issue since the originally reported issue was fixed and to open this one. I hope that is ok.

I'm aware that closing over large constant is not recommended and instead they should be passed as arguments. Nonetheless, this leaking behaviour is unexpected. Maybe it can be -- similar to #11448 --  easily fixed taking weak references to true_fun and false_fun.

## MRE

The side-effect-free function leak creates in ints body a large constant and later compiles a function which closes over the large constant within a lax.cond statement. The compiled function called. When leaving the function leak, all references to the large constant are destroyed, including the closure and the compiled closure and the memory should be freed. However, it is not.

```py
import numpy as np
import jax
import psutil


def print_mem_usage() -> None:    
    print(
        f"Resident memory: {psutil.Process().memory_info().rss // (1024 * 1024)} MB"
    )

def print_live_buffers() -> None:
    lbs = jax.lib.xla_bridge.get_backend().live_buffers()
    print(f"Number live buffers: {len(lbs)}")
    for idx, lb in enumerate(lbs):
        print(f"\tlbs[{idx}]: shape {lb.shape} at 0x{lb.unsafe_buffer_pointer():x}")


def print_num_live_executables() -> None:
    les = jax.lib.xla_bridge.get_backend().live_executables()
    print(f"Number live executables: {len(les)}")



def leak():
    # ~ 1 GB of float32s
    size = 1024 * 1024 * 1024 // 4
    data = jax.device_put(np.empty((size, ), dtype=np.float32) + 1)
    
    def g():
        return jax.lax.cond(
            True,
            lambda: data[0],
            lambda: data[1],
        )


    jg = jax.jit(g)

    _ = jg().block_until_ready()

    del g, jg, data, _


def run() -> None:
    for iter in range(5):
        print(f"iter: {iter} ================================================================")
        print_mem_usage()
        _ = leak()
        print_mem_usage()
        print_live_buffers()
        print_num_live_executables()
        

if __name__ == "__main__":
    run()
```

<details><summary>Output</summary>

```
$ python leak3.py     
iter: 0 ================================================================
Resident memory: 116 MB
Resident memory: 1168 MB
Number live buffers: 1
	lbs[0]: shape (268435456,) at 0x293698000
Number live executables: 0
iter: 1 ================================================================
Resident memory: 1168 MB
Resident memory: 2192 MB
Number live buffers: 2
	lbs[0]: shape (268435456,) at 0x2d3698000
	lbs[1]: shape (268435456,) at 0x293698000
Number live executables: 0
iter: 2 ================================================================
Resident memory: 2192 MB
Resident memory: 3216 MB
Number live buffers: 3
	lbs[0]: shape (268435456,) at 0x313698000
	lbs[1]: shape (268435456,) at 0x2d3698000
	lbs[2]: shape (268435456,) at 0x293698000
Number live executables: 0
iter: 3 ================================================================
Resident memory: 3216 MB
Resident memory: 4242 MB
Number live buffers: 4
	lbs[0]: shape (268435456,) at 0x353698000
	lbs[1]: shape (268435456,) at 0x313698000
	lbs[2]: shape (268435456,) at 0x2d3698000
	lbs[3]: shape (268435456,) at 0x293698000
Number live executables: 0
iter: 4 ================================================================
Resident memory: 4242 MB
Resident memory: 5266 MB
Number live buffers: 5
	lbs[0]: shape (268435456,) at 0x393698000
	lbs[1]: shape (268435456,) at 0x353698000
	lbs[2]: shape (268435456,) at 0x313698000
	lbs[3]: shape (268435456,) at 0x2d3698000
	lbs[4]: shape (268435456,) at 0x293698000
Number live executables: 0
```

</details>

### What jax/jaxlib version are you using?

jax v0.3.21, jaxlib v0.3.20

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.5 on a Mac with M1Pro/Ultimate (MacOS 12.6)

**Comment by mattjj** [comment]
October 10 2022! Oh man...

If we comment out [this `@cache`](https://github.com/google/jax/blob/7e2107b1eefb8280e9c6b72d230d3b789e747613/jax/_src/lax/control_flow/common.py#L79), the leak goes away.

And looking at the code, that cache is clearly holding strong references to the callables! We need it to be more like `weakref_lru_cache`. But the first arg is a list here...
