### ISSUE TITLE
Jax uses "CUDA_VISIBLE_DEVICES" incorrectly

### ISSUE THREAD

**Issue by chrisrothUT** [google/jax#12721]
### Description

I'm finding that Jax is using device 0 even when CUDA_VISIBLE_DEVICES is set to a different number. 

Script:
"""
import os

from mpi4py import MPI
rank = MPI.COMM_WORLD.Get_rank()
os.environ["CUDA_VISIBLE_DEVICES"] = f'{rank}'

import jax
print(f"{rank} -> {jax.devices()}")
"""

Output:
0 -> [GpuDevice(id=0, process_index=0)]
2 -> [GpuDevice(id=0, process_index=0)]
1 -> [GpuDevice(id=0, process_index=0)]

Versions are 
jax v0.3.21
jaxlib v0.3.20+cuda11.cudnn82

### What jax/jaxlib version are you using?

jax v0.3.21, jaxlib v0.3.20+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux

### NVIDIA GPU info

0  NVIDIA A100-PCI
1  NVIDIA A100-PCI
2 NVIDIA A100-PCI

**Comment by hawkinsp** [comment]
`CUDA_VISIBLE_DEVICES` simply controls which GPUs are even visible to JAX. 

Can you say more about what's problematic in your example above? Is it that the "id" of the GPUs shows up as 0? That simply means that the GPU is the first GPU known to JAX; it does not say anything about the hardware ID.

**Comment by chrisrothUT** [comment]
>  CUDA_VISIBLE_DEVICES simply controls which GPUs are even visible to JAX.

Yes, I've now realized that Jax is simply assigning each GPU with the ID zero which is the correct behavior. Sorry for the false alarm
