### ISSUE TITLE
jax.numpy.lcm int8 overflow difference with np

### ISSUE THREAD

**Issue by Ishticode** [google/jax#12728]
### Description

The following code in jax

```python
import jax.numpy as jnp
a = jnp.array([5], dtype=jnp.int8)
b = jnp.array([26], dtype=jnp.int8)
print(jnp.lcm(a, b))
```
produces `[126]` 

while in numpy (checked in 1.23.0 and 1.21.6) (and pytorch 1.11 and 1.12 ) it gives `[-126]` keeping true to the overflow for an `int8` dtype.

Is this difference of results between **`np`** and **`jnp`** desired here?

Surely, `jax.numpy` cannot follow NumPy API in every single output but this is something achievable in this case.
The cause is perhaps that jax uses `abs` at the end of lcm operation. I suppose it should suffice to apply `abs` on `x1` and `x2` as `gcd` does.

Note: Mathematically lcm(5,26)=130, so getting a negative value (as with numpy) can at least signal a warning but getting a positive (but incorrect) value close to the correct value can easily mislead.

int8 dtype was just picked for the sake of simpler example but I am guessing this won't be restricted to int8 dtype.

If you want then I can create a PR for this and in case I m totally mistakened please do enlighten me. Thank you very much.

### What jax/jaxlib version are you using?

jax 0.3.21, jaxlib v0.3.20. Also checked with jax master repo on GitHub.

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.8.10, Ubuntu 20, Google Colab

**Comment by jakevdp** [comment]
Thanks for the report. The reason for the difference is the `abs` call here: https://github.com/google/jax/blob/ec5b1c93d73da2fefb99940f629b41a5f3540de2/jax/_src/numpy/lax_numpy.py#L4192

I'm not sure why the `abs` is there, but I think in principle we could remove it in order to match numpy's behavior in this.

**Comment by Ishticode** [comment]
> Thanks for the report. The reason for the difference is the `abs` call here:
> 
> https://github.com/google/jax/blob/ec5b1c93d73da2fefb99940f629b41a5f3540de2/jax/_src/numpy/lax_numpy.py#L4192
> 
> I'm not sure why the `abs` is there, but I think in principle we could remove it in order to match numpy's behavior in this.

Exactly. I had checked and removed this abs call and it does match with np. Let me know if this is approved for for a PR alongside any other changes if required.

**Comment by jakevdp** [comment]
So long as it doesn't break any existing tests, that sounds good.
