### ISSUE TITLE
jax.scipy.special.erf: Doesn't support complex arguments despite documentation promising that

### ISSUE THREAD

**Issue by 2xB** [google/jax#12756]
### Description

From the documentation ( https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.special.erf.html ):
```
Returns the error function of complex argument.
```

But:
```
from jax.scipy.special import erf
erf(1j)
```

gives 
```
TypeError: erf does not accept dtype complex64. Accepted dtypes are subtypes of floating.
```

.

So either the implementation or the documentation seem broken here.

Needless to say, it would be very useful if `erf` would indeed support complex arguments. A related feature request: #9098

### What jax/jaxlib version are you using?

jax v0.3.21, jaxlib v0.3.20

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.6, linux

**Comment by jakevdp** [comment]
Thanks for the report! It's a bit confusing, but the documentation comes from scipy rather than JAX (notice the "*Original docstring below*" on the page you linked to.

We should add a note to the docs mentioning the restriction on input types.
