### ISSUE TITLE
Jax functions getting mixed

### ISSUE THREAD

**Issue by aniquetahir** [google/jax#12773]
### Description

I am creating two seperate samplers with different parameters. The samplers are initialized inside two separate `Learner` classes. However, if I create individual samplers and provide the two seperate parameters, they both sample from the same distribution.

The weird behavior is present in the following function:
```python3
  def __init__(self, key, score_fn, parameters, epsilon, sigmas, data_shape, data_for_bounds=None):
      L = len(sigmas)
      self.L = L
      self.epsilon = epsilon
      self.sigmas = sigmas
      self.score_fn = score_fn

      def langevin_step(params, key, x, step_idx, alpha):
          key, split = jax.random.split(key)
          # draw a normal noise
          noise = jax.random.normal(split, x.shape)
          x_t = x + alpha * self.score_fn(params, x, jnp.repeat(step_idx, x.shape[0])) + jnp.sqrt(2 * alpha) * noise
          return x_t

      def annealed_langevin(params, key, x):
          def langevin_t(key_x_t, l_i):
              key, x_t = key_x_t
              key, split = jax.random.split(key)
              alpha = epsilon * (self.sigmas[l_i] ** 2) / (self.sigmas[0] ** 2)
              x = langevin_step(params, split, x_t, l_i, alpha)
              return (key, x), x
          (_, final_x), path = jax.lax.scan(langevin_t, (key, x), jnp.arange(self.L)[::-1])
          return final_x, path

      self.langevin_fn = jax.jit(annealed_langevin)
      # self.langevin_fn = annealed_langevin
      self.key = key
      self.params = parameters
      self.bounds = None
      if data_for_bounds is not None:
          bounds_min, bounds_max = data_for_bounds.min(axis=0), data_for_bounds.max(axis=0)
          self.bounds = (bounds_min, bounds_max, data_for_bounds.shape[1])
      else:
          print('Bounds not specified')
      # Initialize the variables by calling
      self.langevin_fn(self.params, self.key, jnp.zeros(data_shape))
```

A full example of the weird behavior can be found here:
https://colab.research.google.com/drive/1vZPm4T4TTIwG9Jf5THPAcZKfeGyW1oRD?usp=sharing

### What jax/jaxlib version are you using?

jax v0.3.21

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9, Ubuntu 20.04

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 30%   40C    P8    35W / 350W |    980MiB / 24576MiB |     24%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3013      G   /usr/lib/xorg/Xorg                 90MiB |
|    0   N/A  N/A      3882      G   /usr/lib/xorg/Xorg                442MiB |
|    0   N/A  N/A      4028      G   /usr/bin/gnome-shell              104MiB |
|    0   N/A  N/A      4431      G   ...dates/2.3.0/proton-bridge       42MiB |
|    0   N/A  N/A    751182      G   /usr/lib/firefox/firefox           13MiB |
|    0   N/A  N/A   1992309      G   ...RendererForSitePerProcess       20MiB |
|    0   N/A  N/A   2099547      G   /usr/lib/firefox/firefox          134MiB |
|    0   N/A  N/A   2149144      G   ...veSuggestionsOnlyOnDemand       41MiB |
|    0   N/A  N/A   2150565      G   ...964796958109718564,131072       37MiB |
+-----------------------------------------------------------------------------+

```

**Comment by jakevdp** [comment]
Thanks for the question – my bet is that this is a cacheing issue due to your class not having an appropriately defined hash function. When you reference a custom object from a closed-over jit-compiled function (the `self.xyz` in your case), `self` is treated as a static variable for the purpose of the JIT cache. And the default hash function for such a class is the class ID – meaning that if you modify attributes of the class, as far as the JIT machinery is concerned, it's unchanged.

There are several possible approaches to fixing this; they are outlined in this FAQ entry: https://jax.readthedocs.io/en/latest/faq.html#how-to-use-jit-with-methods This is relevant because you're indirectly jit-compiling `self.score_fn` when you jit-compile the function that calls it. In your case, since your classes have a mix of static and array attributes, registering them as pytrees (strategy 3) is probably the best option.

Let me know if you have any questions, or if the description of the issue there is unclear

**Comment by aniquetahir** [comment]
The functions that exhibit the weirdness are used last, and the class variables don't change for them (see colab notebook).

**Comment by mattjj** [comment]
I agree with Jake's guess, though I would focus not on the hashability but on the mutation: I suspect the attributes of a closed-over instance are being mutated, and using mutating side-effects voids the `jax.jit` warranty.

We could validate this guess with a minimal repro, but as it stands that colab is huge! Could you try to minimize? I bet this same behavior could be exhibited in <10 lines.

**Comment by jakevdp** [comment]
> The functions that exhibit the weirdness are used last, and the class variables don't change for them (see colab notebook).

Sure, but your `random_sample` function modifies the class in-place (it updates `self.key`) and then calls a JIT-compiled function with `self` as an implicit argument (`self.langevin_fn`). The result is that you'll be calling a cached version of the function, without these updates reflecte.

**Comment by mattjj** [comment]
The easiest way (IMO) to avoid issues with mutation is not to deal with defining pytrees but rather just to use `jit` on top-level functions, i.e. ones that are fully de-dented in a module, rather than methods. Then there's no risk of implicit/bound arguments like `self` creeping in.

**Comment by jakevdp** [comment]
Sounds like @mattjj is advocating for Strategy 1 in the FAQ entry – agreed that's much simpler!

**Comment by mattjj** [comment]
Like, is this a model of the issue?

```python
import jax

def foo(tot):
  @jax.jit
  def increment(x):
    tot[0] += x
    return tot[0]
  return increment

incrementer = foo([0.])

print(incrementer(3))  # 3.0
print(incrementer(3))  # 3.0 (!!)
```

**Comment by mattjj** [comment]
Actually, I was trying to model the instance as `tot`, but this is really just like a side-effect on a global:

```python
import jax

tot = 0

@jax.jit
def increment(x):
  global tot
  tot += x
  return tot

print(increment(3))  # 3
print(increment(3))  # 3 (!!)
```

Here's yet another version, actually using an instance and a bound method:

```python
import jax

class A:
  def __init__(self):
    self.tot = 0

    @jax.jit
    def increment(x):
      self.tot += x
      return self.tot

    self.increment = increment


a = A()
print(a.increment(3))  # 3
print(a.increment(3))  # 3
```

All of these are essentially doing the same thing: mutating side-effects!

**Comment by mattjj** [comment]
Interestingly, JAX can detect the side-effect and raise an error if you set `jax_raise_tracer_leaks`:

```python
import jax
jax.config.update('jax_check_tracer_leaks', True)

class A:
  def __init__(self):
    self.tot = 0

    @jax.jit
    def increment(x):
      self.tot += x
      return self.tot

    self.increment = increment


a = A()
print(a.increment(3))  # Exception raised!!!
print(a.increment(3))
```

Unfortunately we can't set this mode on by default, since it has performance impacts, though maybe we can foreground it more...

**Comment by mattjj** [comment]
Finally, here's how I'd adapt the last example to fix it:

```python
import jax

class A:
  def __init__(self):
    self.tot = 0

  def increment(self, x):
    self.tot = _increment_fun(self.tot, x)
    return self.tot

@jax.jit
def _increment_fun(tot, x):
  tot = tot + x
  return tot

a = A()
print(a.increment(3))  # 3
print(a.increment(3))  # 6
```

Using `jit` with top-level functions makes everything easier!

**Comment by aniquetahir** [comment]
I tried moving the functions out of the class to no avail:
```python3
...
@functools.partial(jax.jit, static_argnums=5)
def langevin_step(params, key, x, step_idx, alpha, score_fn):
    key, split = jax.random.split(key)
    # draw a normal noise
    noise = jax.random.normal(split, x.shape)
    x_t = x + alpha * score_fn(params, x, jnp.repeat(step_idx, x.shape[0])) + jnp.sqrt(2 * alpha) * noise
    return x_t

@functools.partial(jax.jit, static_argnums=2)
def langevin_t(key_x_t, l_i, m_score_fn):
    key, x_t, m_sigmas, m_params, m_epsilon = key_x_t
    key, split = jax.random.split(key)
    alpha = m_epsilon * (m_sigmas[l_i] ** 2) / (m_sigmas[0] ** 2)
    x = langevin_step(m_params, split, x_t, l_i, alpha, m_score_fn)
    return (key, x, m_sigmas, m_params, m_epsilon), x

class LangevinSampler():
    @staticmethod
    def materialize(obj, score_fn, sigmas):
        sampler = LangevinSampler(obj['key'], score_fn, obj['params'], obj['epsilon'], sigmas)
        sampler.bounds = obj['bounds']
        return sampler

    def __init__(self, key, score_fn, parameters, epsilon, sigmas, data_shape, data_for_bounds=None):
        L = len(sigmas)
        self.L = L
        self.epsilon = epsilon
        self.sigmas = sigmas
        self.score_fn = score_fn

        def annealed_langevin(params, key, x):
            (_, final_x, _, _, _), path = jax.lax.scan(functools.partial(langevin_t, m_score_fn=self.score_fn),
                                                       (key, x, self.sigmas, params, epsilon), jnp.arange(self.L)[::-1])
            return final_x, path

        # self.langevin_fn = jax.jit(annealed_langevin)
        self.langevin_fn = annealed_langevin
        self.key = key
        self.params = parameters
        self.bounds = None
        if data_for_bounds is not None:
            bounds_min, bounds_max = data_for_bounds.min(axis=0), data_for_bounds.max(axis=0)
            self.bounds = (bounds_min, bounds_max, data_for_bounds.shape[1])
        else:
            print('Bounds not specified')
        # Initialize the variables by calling
        self.langevin_fn(self.params, self.key, jnp.zeros(data_shape))
...
```

**Comment by jakevdp** [comment]
I think this line still has the issues mentioned above:
```python
jax.lax.scan(functools.partial(langevin_t, m_score_fn=self.score_fn)
```
`scan` will effectively JIT compile the function you pass to it, and you're passing a function that closes over `self`.

**Comment by aniquetahir** [comment]
`self.score_fn` was a variable of the class rather than a method of the class, I tried with `jax.lax.scan(functools.partial(langevin_t, m_score_fn=score_fn)` since `score_fn` is also an argument to `__init__` but the same results are reproduced.

**Comment by jakevdp** [comment]
But `score_fn` is not a simple function, it is a bound method (you instantiate it with `fav_learner.apply`), which is bound to the state of that object at compile time. So you still have some issues with implicitly bound static wrappers around objects that mutate.

**Comment by aniquetahir** [comment]
I found the bug. It was actually random number generation which was done in the wrong way for each generator (not related to jax). Thanks for all the help!
