### ISSUE TITLE
function signatures are missing after jax.jit with the latest jax

### ISSUE THREAD

**Issue by llan-ml** [google/jax#12828]
### Description

Currently (tested with `jax==0.3.21`), the function signatures are missing after decorated with `jax.jit`. 

I found a previous [issue](https://github.com/google/jax/issues/5612), and the function signatures can be correctly preserved with `jax==0.2.10`.

I created a [colab notebook](https://colab.research.google.com/drive/1uulGRY6nH9zOmINqWTvVoC5K-retuDAs?usp=sharing) to illustrate this issue.

### What jax/jaxlib version are you using?

jax v0.3.21

### Which accelerator(s) are you using?

CPU/GPU

### Additional system info

python 3.9.12

**Comment by jakevdp** [comment]
Thanks for the report. Do you know what mechanism jedi uses to determine the signature? `jax.jit` currently sets all the attributes that `functools.wraps` sets on wrapped functions, and runtime signature inspection appears to be correct:
```python
import inspect
import jax
@jax.jit
def foo(x: int, y: float):
    return x + y
print(inspect.signature(foo))
```
```
(x: int, y: float)
```

**Comment by llan-ml** [comment]
It seems that Jedi obtains function signatures using its own implementations, and I don't know about the details for now.

However, AFAIK, Jedi can handle decorated functions:
```
import jedi

code = '''
from functools import wraps
def dec(func):
    def wrapper(*a, **k):
        return func(*a, **k)
    return wraps(func)(wrapper)

@dec
def foo(x: int, y: float):
    return x + y
foo('''

s = jedi.Script(code, path="")
s.get_signatures(11, 4)
```
```
[<Signature: index=0 foo(x: int, y: float)>]
```

**Comment by llan-ml** [comment]
Hi @jakevdp , I found that the internal implementation of `wraps` leads to this issue. I replaced the `wraps` in the file `api.py` with `fucntools.wraps`, and `jedi` gets the expected signatures:
```
○ → ipython
Python 3.9.12 (main, Apr  5 2022, 06:56:58)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import jedi

In [2]: !sed -n 54,59p /home/lanlin/.pyenv/versions/3.9.12/envs/jedi/lib/python3.9/site-packages/jax/api.py
                        treedef_is_leaf, treedef_children, Partial)
from ._src.util import (unzip2, curry, partial, safe_map, safe_zip, prod,
                        split_list, extend_name_stack, wrap_name, cache,
                        HashableFunction)
from functools import wraps       # -----> this line
from . import lib

In [3]: code = '''
   ...: import jax
   ...: @jax.jit
   ...: def foo(x: int, y: float):
   ...:     return x + y
   ...: foo('''

In [4]: s = jedi.Script(code, path="")

In [5]: s.get_signatures(6, 4)
Out[5]: [<Signature: index=0 foo(x: int, y: float)>]

In [6]: 
```

**Comment by jakevdp** [comment]
I've been looking into this, but I'm still quite confused. It's not JAX's version of `wraps` alone that's causing issues; it work when used directly in a decorator, e.g.
```python
script = """
from jax._src.util import wraps

def decorator(f):
  @wraps(f)
  def wrapped(*args, **kwargs):
    return f(*args, **kwargs)
  return wrapped

@decorator
def f(x: int, y: int) -> int:
  return x + y

f(1, 2)
"""
import jedi
s = jedi.Script(script, path="")
s.get_signatures(14, 2)
```
```
[<Signature: index=0 wrapped(x: int, y: int)>]
```
My current theory is it has something to do with the fact that the object returned by `jax.jit` is not a function, but an instance of a `CompiledFunction` object which is implemented in C++. Somehow that's preventing JAX's version of `wraps` from working correctly.

**Comment by jakevdp** [comment]
I'm going to close this, as it's not clear that there's anything we can do on JAX's side to fix the issue.
