### ISSUE TITLE
Wrong benchmarks in the documentation

### ISSUE THREAD

**Issue by Mustapha-AJEGHRIR** [google/jax#12824]
### Description

In the QuickStart documentation page: 
https://jax.readthedocs.io/en/latest/notebooks/quickstart.html

The indicated benchmarks are as follows (544 ms, 478 ms, 469 ms) as the image below, but the second one should be slower than the two others as it is also indicated in the same image.
 
![image](https://user-images.githubusercontent.com/66799406/195980887-db5c5e66-9b16-4aa2-81a6-22ab92606daf.png)

I have tested this in a Colab free tier with T4 GPU and got the following:
 
![image](https://user-images.githubusercontent.com/66799406/195980890-c9c4c9d3-98a3-4fca-a769-5cc284054abe.png)

I think there is a problem in the reported benchmarks of the documentation.
Thank you

### What jax/jaxlib version are you using?

0.3.21

### Which accelerator(s) are you using?

GPU T4

### Additional system info

Colab free tier

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   53C    P0    28W /  70W |  14204MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2250      C   /usr/bin/python3                14201MiB |
+-----------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment]
I think the issue is that we're regenerating the documents on a CI node that is probably on CPU and quite slow...

**Comment by jakevdp** [comment]
What do you think the best fix is: maybe add a disclaimer that timings may vary depending on hardware?
