### ISSUE TITLE
Add scipy.optimize.linprog

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#12827]
Add [scipy.optimize.linprog](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linprog.html), which performs [linear programming](https://en.wikipedia.org/wiki/Linear_programming). For some approaches to differentiable optimization modules, see the following papers:
* [OptNet: Differentiable optimization as a layer in neural networks](https://arxiv.org/abs/1703.00443)
* [Differentiable convex optimization layers](https://arxiv.org/abs/1910.12430)
* [Efficient differentiable quadratic programming layers: an ADMM approach](https://arxiv.org/abs/2112.07464)

**Comment by shoyer** [comment]
This is probably a better fit for JAXopt rather than JAX itself: https://github.com/google/jaxopt

**Comment by froystig** [comment]
cc @mblondel

**Comment by mblondel** [comment]
Agreed with @shoyer but it isn't a small endeavour...

**Comment by hawkinsp** [comment]
Closing because this seems like a fine thing to add to JAXopt instead of JAX itself. It would make sense to continue the discussion on the JAXopt repository.

(If it's important to provide scipy's exact interface, we could add a shim to JAX that calls JAXopt if present.)

**Comment by carlosgmartin** [comment]
@shoyer @hawkinsp Is the same true for [nnls](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.nnls.html) (for [non-negative least squares](https://en.wikipedia.org/wiki/Non-negative_least_squares))?

**Comment by froystig** [comment]
I would expect so, yes. Broadly speaking, if it's a module/function with a substantial implementation and it's part of `scipy`, then it's worthwhile to consider a specialized library to contribute to instead. There is not always a clear rule here (nor is there always a specialized library), so it's fine to ask and we can decide collectively on a case-by-case basis. In this case, as is common for complex pieces of `scipy.optimize`, JAXopt seems to be a good candidate.
