### ISSUE TITLE
make `jax.Array` json serializable

### ISSUE THREAD

**Issue by GallagherCommaJack** [google/jax#12862]
would be nice to have something here - probably should guard with an `assert self.is_fully_addressable()`

**Comment by yashk2810** [comment]
What's the use-case? Is DA or SDA json serializable?

**Comment by GallagherCommaJack** [comment]
- being able to include jax arrays without extra boilerplate in objects that are going to eg get returned in an http json response
- being able to pass jax arrays directly to `wandb.log`

**Comment by GallagherCommaJack** [comment]
numpy arrays are also serializable, it's generally a fairly convenient feature to have easy human-readable serialization (as opposed to just binary)

**Comment by yashk2810** [comment]
Okay. But DA is not serializable currently and I'll find out what the reason is and post the reason here.

**Comment by jakevdp** [comment]
NumPy arrays are not serializable either, and from what I've seen the general workaround there is to call `arr.tolist()`. This same approach should work for JAX arrays.

**Comment by GallagherCommaJack** [comment]
huh - sounds like the issue is on the `wandb` side then. good to know, will close the issue.
