### ISSUE TITLE
CPU-only linux wheels for jaxlib 0.3.22 are not published

### ISSUE THREAD

**Issue by samuela** [google/jax#12879]
### Description

Breaking with tradition from prior releases, the 0.3.22 release of jaxlib does not have published linux CPU-only wheels in https://storage.googleapis.com/jax-releases.

Would it be possible to get linux, CPU jaxlib wheels published in https://storage.googleapis.com/jax-releases?

### What jax/jaxlib version are you using?

jaxlib 0.3.22

### Which accelerator(s) are you using?

CPU

### Additional system info

MacOS

### NVIDIA GPU info

n/a

**Comment by yashk2810** [comment]
I can see 0.3.22 wheels here: https://storage.googleapis.com/jax-releases/jax_releases.html

```
[nocuda/jaxlib-0.3.22-cp310-cp310-manylinux2014_x86_64.whl](https://storage.googleapis.com/jax-releases/nocuda/jaxlib-0.3.22-cp310-cp310-manylinux2014_x86_64.whl)
[nocuda/jaxlib-0.3.22-cp37-cp37m-manylinux2014_x86_64.whl](https://storage.googleapis.com/jax-releases/nocuda/jaxlib-0.3.22-cp37-cp37m-manylinux2014_x86_64.whl)
[nocuda/jaxlib-0.3.22-cp38-cp38-manylinux2014_x86_64.whl](https://storage.googleapis.com/jax-releases/nocuda/jaxlib-0.3.22-cp38-cp38-manylinux2014_x86_64.whl)
[nocuda/jaxlib-0.3.22-cp39-cp39-manylinux2014_x86_64.whl](https://storage.googleapis.com/jax-releases/nocuda/jaxlib-0.3.22-cp39-cp39-manylinux2014_x86_64.whl)
```

**Comment by samuela** [comment]
@yashk2810 Oh interesting... I'm not seeing those on https://storage.googleapis.com/jax-releases (the XML version). Why the difference between https://storage.googleapis.com/jax-releases/jax_releases.html and https://storage.googleapis.com/jax-releases?

**Comment by yashk2810** [comment]
The second link is the link to the bucket which cannot be read. The first link is the actual link to the index.

**Comment by samuela** [comment]
> The second link is the link to the bucket which cannot be read. The first link is the actual link to the index.

I'm confused... What does the XML output represent?

**Comment by jakevdp** [comment]
The XML output only lists the first 1000 objects in the bucket (I'm not sure how the order is determined), and since there are more than 1000 items in the storage bucket it doesn't show everything.

**Comment by samuela** [comment]
ahhh gotcha, that would explain it! thanks @jakevdp!
