### ISSUE TITLE
Disable compilation from jax.lax.(cond, while_loop, fori_loop)?

### ISSUE THREAD

**Issue by tbenthompson** [google/jax#12874]
As I understand it, code underneath one of these `jax.lax` control flow constructs will be JIT compiled regardless of whether there is a `jax.jit` used. This is a bit annoying when I am running unit tests because our compilation times inflate the test runtime dramatically. 

Any advice would be appreciated!

**Comment by mattjj** [comment]
Thanks for the suggestion!

Instead of compiling these higher-order primitives, we could effectively run a Python-level jaxpr interpreter. Then there wouldn't be compile times, but there would be high Python overheads. I wonder if that would be a better tradeoff, at least in some cases.

Luckily I think you can experiment with that behavior now by using [`jax.disable_jit`](https://jax.readthedocs.io/en/latest/_autosummary/jax.disable_jit.html). In fact, I think you can do `nojit_cond = jax.disable_jit()(jax.lax.cond)` and similar.

WDYT about trying that use of `jax.disable_jit` to see if it helps?

**Comment by mattjj** [comment]
Here are some examples of the relevant logic:
* [`scan`](https://github.com/google/jax/blob/8536faec6768d89e54481e145ebf0d675758716c/jax/_src/lax/control_flow/loops.py#L223-L235)
* [`cond`](https://github.com/google/jax/blob/8536faec6768d89e54481e145ebf0d675758716c/jax/_src/lax/control_flow/conditionals.py#L124-L126)
* [`while_loop`](https://github.com/google/jax/blob/8536faec6768d89e54481e145ebf0d675758716c/jax/_src/lax/control_flow/loops.py#L1078-L1083)

**Comment by JamesYang007** [comment]
It would be ideal if we didn't have to change our codebase just for test code. But looking at the examples you listed, there seems to be a more non-invasive strategy:
```python3
### test.py
from jax.config import config
config.update('jax_disable_jit', True)

# import codebase

# test code ...

config.update('jax_disable_jit', False)
```
Would this work?

**Comment by tbenthompson** [comment]
Thanks @mattjj and @JamesYang007. Between these two solutions, I think we're all set! I've gotten the particular unit test I was looking at down from 32s to 1.2s which is great. Thanks!!

**Comment by mattjj** [comment]
You can also put that kind of thing in setUp / tearDown methods on your test classes or modules. Those can be more robust to e.g. exceptions being raised in tests. (That is, if a test fails with an exception, you may want to clean up any changes to the global state as it exits.)

**Comment by tbenthompson** [comment]
Would setUp/tearDown be more robust to exceptions than wrapping the test in the `jax.disable_jit` context manager like this?

```
def test_f():
    with jax.disable_jit():
        f()
```

or, possibly better and works great because `disable_jit` is written using `@contextmanager`.

```
@jax.disable_jit
def test_f():
    f()
```

**Comment by mattjj** [comment]
I think that will work well too! Our config context managers attempt to be robust to exceptions [by using `try`/`finally`](https://github.com/google/jax/blob/1a0affddd815a05c2fcd24299e7eb520a3b1938d/jax/_src/config.py#L461-L471), and putting the clean up under the `finally`.
