### ISSUE TITLE
Owens T function

### ISSUE THREAD

**Issue by rezaaskary** [google/jax#12888]
I am writing a probabilistic package and I am using jax as the backend. I am looking for Owens T function for calculating the CDF of  a  skewed Normal likelihood function. I searched through lax and jax.scipy.special and I think Owens T function is not implemented yet. Please let me know if this is the case. If so, is there any possiblity in the near future that you implement the function? I really don't want to switch to either SciPy pf tensorflow and integrate those in my code.

Thanks,

https://www.tensorflow.org/probability/api_docs/python/tfp/math/owens_t
https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.owens_t.html

- [x] Check for duplicate requests.
- [ ] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by mattjj** [comment]
Thanks for the question!

A good place to look for this stuff is [TFP-on-JAX](https://www.tensorflow.org/probability/examples/TensorFlow_Probability_on_JAX). After doing `from tensorflow_probability.substrates import jax as tfp` I think you should be able to use `tfp.math.owens_t`.

**Comment by rezaaskary** [comment]
Thank you!
