### ISSUE TITLE
Failed to Create an Empty Array with IREE

### ISSUE THREAD

**Issue by daskol** [google/jax#12895]
### Description

The code below fails with `CompilerToolError`.

```python
#!/usr/bin/env python
import jax, jax.numpy as jnp
import jaxlib

jax.config.update('jax_platform_name', 'iree')
x = jnp.empty(10)
# iree.compiler.tools.binaries.CompilerToolError: Error invoking IREE compiler tool iree-compile
# Diagnostics:
# <stdin>:0:0: error: invalid section ID: 6
# <stdin>:0:0: note: in bytecode version 0 produced by: MLIR16.0.0git
```

### What jax/jaxlib version are you using?

jax-v0.3.23, jaxlib-v0.3.22

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10, IREE Compiler/Runtime 20220902.254

**Comment by hawkinsp** [comment]
This works for me.

I think you need a newer IREE version. JAX is newer than IREE and the IR is probably incompatible.

Try:
```
pip install --upgrade iree-compiler iree-runtime --find-links https://iree-org.github.io/iree/pip-release-links.html
```
to get a nightly.

There is a plan to have more api stability between JAX and IREE (e.g., via StableHLO) but it's not something we promise yet, so you'll in general need to use JAX and IREE of similar ages.

**Comment by daskol** [comment]
It works now for me as well. I expected that JAX works with IREE version labeled as stable.

**Comment by jpienaar** [comment]
Unfortunately we got delayed in updating the IREE stable release. Currently in the iree-jax repo we capture some compatible rev versions, but a conservative one (e.g., it's an older Jax and iree than necessary, no ranges of working commits etc) at the moment that we are tracking to improve.

One can check when integrates happened in the different projects and so match the mlir-hlo repo revision across the repos as a workaround until we fix this more holistically.
