### ISSUE TITLE
live_buffers doesn't report GDAs (unless accessed from Python explicitly)

### ISSUE THREAD

**Issue by qstanczyk** [google/jax#12913]
### Description

When a tree of GlobalDeviceArrays is returned from Jited function, those GDAs are not reported by the `live_buffers` call.
They show up in the output of `live_buffers` when `addressable_shards` is accessed one by one on those GDAs from Python. Looks like the reason is that GDA creates Python-side of the buffer lazily.
When not using GDAs, memory tracking works as expected.

### What jax/jaxlib version are you using?

jax-0.3.23

### Which accelerator(s) are you using?

CPU / TPU

### Additional system info

3.10, Debian GNU/Linux rodete

**Comment by hawkinsp** [comment]
We've actually fixed this already at head, but it requires a new `jax` and `jaxlib` release. Fortunately we are trying to make one right now. The new API is `jax.live_arrays()`.
