### ISSUE TITLE
"jit changes the exact numerics of outputs" FAQ example not working as expected

### ISSUE THREAD

**Issue by mlpotter** [google/jax#12939]
## Issue
When running JIT for the example "jit changes the exact numerics of outputs" (https://jax.readthedocs.io/en/latest/faq.html) I do not get the same result. For jit and non-jit function I receive 0.0010000467 (see in code).

jax version 0.3.23

## CUDA Info
GeForce 2700
NVIDIA-SMI 522.25      
Driver Version: 522.25      
CUDA Version: 11.8

## OS Version
Edition	Windows 10 Home
Version	21H2
Installed on	‎12/‎8/‎2021
OS build	19044.2006
Experience	Windows Feature Experience Pack 120.2212.4180.0

## Code
```
>>> import jax
>>> jax.devices()
[GpuDevice(id=0, process_index=0)]
>>> from jax import jit
>>> def f(x, y):
...   return x + y - x
...
>>> import jax.numpy as jnp
>>> x = jnp.array(1.0)
>>> y = jnp.array(0.001)
>>> print(f(x, y))
0.0010000467
>>> print(jit(f)(x, y))
0.0010000467
```

### What jax/jaxlib version are you using?

jax v0.3.23 jaxlib v0.3.20

### Which accelerator(s) are you using?

GPU

### Additional system info

Windows

### NVIDIA GPU info

> Sat Oct 22 15:56:32 2022
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 522.25       Driver Version: 522.25       CUDA Version: 11.8     |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                               |                      |               MIG M. |
> |===============================+======================+======================|
> |   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
> | N/A   39C    P8     8W /  N/A |      0MiB /  8192MiB |      0%      Default |
> |                               |                      |                  N/A |
> +-------------------------------+----------------------+----------------------+
> 
> +-----------------------------------------------------------------------------+
> | Processes:                                                                  |
> |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
> |        ID   ID                                                   Usage      |
> |=============================================================================|
> |    0   N/A  N/A      3528    C+G   ...IA GeForce Experience.exe    N/A      |
> +-----------------------------------------------------------------------------+

**Comment by jakevdp** [comment]
Thanks for flagging this - it seems that XLA has changed some of its optimization paths since the documentation was first written, so this is no longer a good example of the issue.

**Comment by mattjj** [comment]
It's a good meta-example of the issue, in that it shows `jit` numerics are unpredictable (and can hence invalidate our docs). 😛

**Comment by mlpotter** [comment]
So I should not expected `jit` to optimize my numerical computations anymore essentially?

**Comment by jakevdp** [comment]
JIT still optimizes numerical computations, but the particular optimization that led to those two outputs differing has been removed.

**Comment by jakevdp** [comment]
Thanks again for raising this - should be fixed now: https://jax.readthedocs.io/en/latest/faq.html#jit-changes-the-exact-numerics-of-outputs
