### ISSUE TITLE
`DeviceArray` operators can't easily be distinguished

### ISSUE THREAD

**Issue by mattbarrett98** [google/jax#12947]
As far as I can tell, different operators on the `DeviceArray` class aren't distinguishable. For example, 

```
>>> import jaxlib.xla_extension
>>> import jax.numpy as jnp
>>> x = jnp.array(1)
>>> jaxlib.xla_extension.DeviceArray.__add__
<function jax._src.numpy.lax_numpy._defer_to_unrecognized_arg.<locals>.deferring_binary_op(self, other)>
```

gives the same result as 

```
>>> jaxlib.xla_extension.DeviceArray.__mul__
<function jax._src.numpy.lax_numpy._defer_to_unrecognized_arg.<locals>.deferring_binary_op(self, other)>
```

They all point to this function https://github.com/google/jax/blob/a4e366394bec6054f6d5029eb5bfea30a8411e98/jax/_src/numpy/lax_numpy.py#L4753 . Of course the `binary_op` in this function is different for each operator, but this can't be accessed and so you can't easily see which operator is being used (without tediously trying values to figure out what the operator is). 

Maybe it'd be good to have something like `deferring_binary_op.binary_op = binary_op` to facilitate introspection.

**Comment by jakevdp** [comment]
Thanks for the report – this is an interesting question. Can you say more about what you're trying to accomplish, and how you would like to distinguish the operators? For example, you can currently distinguish them using operator identity – does this suit your needs?
```python
import jax.numpy as jnp
x = jnp.array(1)
cls = type(x)
method = cls.__add__

print(method is cls.__add__)
# True

print(method is cls.__mul__)
# False
```
