### ISSUE TITLE
JIT returns a different value for `add+sinh` 

### ISSUE THREAD

**Issue by YangChenyuan** [google/jax#12949]
### Description

JIT returns a different value for `add+sinh` 

```py
import jax

def fn(arg_0):
    arg_0 = jax.numpy.add(arg_0, jax.numpy.array(16, dtype=jax.numpy.float32))
    fn_res = jax.lax.sinh(arg_0)
    return fn_res

arg_0 = jax.numpy.array(-6.9080677, dtype=jax.numpy.float32)
arg_0 = jax.numpy.sin(arg_0)

print(fn(arg_0))
print(jax.jit(fn)(arg_0))
```

```
2475248.5
2475246.2
```

If we put the add out of the function, the result will be the same

```py
import jax

def fn(arg_0):
    fn_res = jax.lax.sinh(arg_0)
    return fn_res

arg_0 = jax.numpy.array(-6.9080677, dtype=jax.numpy.float32)
arg_0 = jax.numpy.sin(arg_0)
arg_0 = jax.numpy.add(arg_0, jax.numpy.array(16, dtype=jax.numpy.float32))

print(fn(arg_0))
print(jax.jit(fn)(arg_0))
```

```
2475248.5
2475248.5
```
Thus, it should be that the optimization of `add` and `sinh` changes the value

### What jax/jaxlib version are you using?

jax v0.3.23, jaxlib v0.3.22

### Which accelerator(s) are you using?

CPU and GPU

### NVIDIA GPU info

```
NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7  
```

**Comment by jakevdp** [comment]
Hi - this sort of behavior is expected (See [FAQ: JIT changes the exact numerics of outputs](https://jax.readthedocs.io/en/latest/faq.html#jit-changes-the-exact-numerics-of-outputs). JAX defaults to float32, which has 23 bits of mantissa, meaning that errors of 1 part in $2^{23}$ can be expected; the difference you're seeing (0.3 / 2475246.2) is right at this floating point uncertainty threshold.

If your application needs higher precision, you might consider using `float64` instead; see [Sharp Bits: 64-bit precision](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision).

**Comment by YangChenyuan** [comment]
Hi @jakevdp, thanks for your timely reply!

For this example, does JIT in jax leverages the floating point uncertainty threshold to do some acceleration?

I think the difference between with and without JIT sometimes is confusing, actually, here is the original example that I observe this difference

```py
import jax

def fn(arg_0):
    arg_0 = jax.numpy.sin(arg_0)
    arg_0 = jax.numpy.add(arg_0, jax.numpy.array(16, dtype=jax.numpy.float32))
    fn_res = jax.lax.sinh(arg_0)
    fn_res = jax.lax.sin(fn_res)
    return fn_res

arg_0 = jax.numpy.array(-6.9080677, dtype=jax.numpy.float32)

print(fn(arg_0))
print(jax.jit(fn)(arg_0))
```

```
0.21296367
-0.89400244
```

The difference is so big that they even have different symbols. Is this a feature?

**Comment by jakevdp** [comment]
Good question! The issue here is the same as above, except the function you're computing (sine) in this case is highly sensitive to the exact value at the level of the inherent floating-point uncertainty. This is not a JAX issue, this is a floating point arithmetic issue, and you'll find it in any numerical system that uses floating point arithmetic (see [Is Floating Point Math Broken](https://stackoverflow.com/q/588004) for some more discussion).

**Comment by YangChenyuan** [comment]
Thanks for your explanation!
