### ISSUE TITLE
Pmap issue

### ISSUE THREAD

**Issue by patrickbryant1** [google/jax#12966]
### Description

I have code that runs on one processor, but I can't seem to distribute it. The problem seems to be the communication between the processes:

jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:245: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

This is strange since the distributed process is initialised successfully. It is also possible to run simpler pmap operations across processors. When I try to train a network, however, the error above is the result.

I know you are working with NVIDIA to make things easier for GPU. Is it possible to try the results from this collaboration out? 
 

### What jax/jaxlib version are you using?

0.3.17

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. ||                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:3B:00.0 Off |                    0 |
| N/A   42C    P0    52W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |

**Comment by zhangqiaorjc** [comment]
Could you turn on `NCCL_DEBUG`?

https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-debug

I just googled "unhandled cuda error", it seems to a common issue if users installed the wrong CUDA version. But you might need to see more logging to confirm

**Comment by patrickbryant1** [comment]
Hi, I don't see how this can be the issue if the distributed process works for some calculations - such as simple pmap updates, but not for model parallelism. Is it possible to run some pmap calculations with a "wrong" CUDA version but not others? I would think no calculations should be possible on GPU with the wrong CUDA version.

**Comment by patrickbryant1** [comment]
I set os.environ['NCCL_DEBUG']='INFO', the output is the same. I also set TRACE - no difference.

**Comment by almogsegal** [comment]
Please share the following:
1. What GPUs do you have?
2. Are the GPUs connected via NVLink?
3. What pmap operation are you trying to run that fail? Is it a custom function?
4. What was the pmap operation that succeeded?
5. Do you set CUDA_VISIBLE_DEVICES?
6. Is it a single/multi node?

Please try to set the NCCL_DEBUG=INFO env prior to app launch.

**Comment by patrickbryant1** [comment]
Hi,
1. I have NVIDIA A100
2. The GPUs within each node should be
3. Yes it is a custom function: "train step" following the syntax here: https://github.com/deepmind/dm-haiku/blob/main/examples/imagenet/train.py
The 0-axis of a batch is pmapped, jax.value_and_grad is applied and jax.lax.pmean is taken over the resulting gradients. The batch dimension is set to the number of local devices.
4. I have a small test script, which updates gradients using optax on simulated data. I noticed here that partial functions cause errors - e.g. wrapping a function in @functools.partial(jax.pmap). Running the same function, but specifying pmap(fun) does not. The difference between this small test script compared to the one this issue is about is that no pmean is applied and the parameters are replicated from one processor and not kept across devices. This means that the updates are really performed on one processor. The forward pass across GPUs (tested on 2 and 4 GPUs, respectively) works however since predictions over num_local_devices are obtained. The problem, therefore, seems to be with the gradient updates.
5. I have tried both, but makes no difference if jax.local_device_count() is the number of devices to map over.
6. Single node (for now)
7. Slurm interactive 

I will check if there is a difference in output by setting  NCCL_DEBUG=INFO before launching.

**Comment by patrickbryant1** [comment]
I ran with NCCL_DEBUG=INFO set before running the training on two devices. 
There is no difference in the error message (below). Communication btw processes seem to be the problem. My question is why I can run simple pmap operations (e.g. pmean over an array works) but not gradient updates. Is there something I am missing? I would also be surprised if this is related to my CUDA. If so, how come some calculations work?

line 498, in train_net
  ain_state, loss, aux = p_train_step(train_state, batch, rng)
  Fi "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
  turn fun(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2136, in cache_miss
  t_tree, out_flat = f_pmapped_(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/jax/_src/api.py", line 2012, in pmap_f
  t = pxla.xla_pmap(
File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 2066, in bind
  turn map_bind(self, fun, *args, **params)
File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 2098, in map_bind
  ts = primitive.process(top_trace, fun, tracers, params)
File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 2069, in process
  turn trace.process_map(self, fun, tracers, params)
File "/usr/local/lib/python3.8/dist-packages/jax/core.py", line 689, in process_call
  turn primitive.impl(f, *tracers, **params)
File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py", line 953, in xla_pmap_impl
  turn compiled_fun(*args)
File "/usr/local/lib/python3.8/dist-packages/jax/_src/profiler.py", line 313, in wrapper
  turn func(*args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py", line 2034, in __call__
out_bufs = self.xla_executable.execute_sharded_on_local_devices(
jax._src.traceback_util.UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:245: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

**Comment by nvlcambier** [comment]
@patrickbryant1 Can you share a repro and how you launch your app?

If `NCCL_DEBUG=INFO` is defined **before** you run `python3 ./myapp...` it **should** print a lot of output. If it doesn't print anything, it's most likely before NCCL is loaded before `NCCL_DEBUG` is set in the environment.

This is, imho, most likely a CUDA driver/CUDA runtime/NCCL version mismatch, but it's hard to tell without more debug information.

**Comment by patrickbryant1** [comment]
Hi,
I can't share this atm. Yes, I think you are right that NCCL is loaded when I allocate the resources which make this not provide additional info. This is something I can't change currently.  

What is strange to me is that I can run pmap for everything except gradient updates. Here is a test script (below) I run which works across GPUs. As you can see, I replicate the params and keep them on one device in this case. If I spread them across devices this also works. The forward function works, pmean works, but if I want to pmap something like:
updates, new_opt_state = make_optimiser().update(gradients, opt_state) 
new_params = optax.apply_updates(params, updates)
- it fails with the error above. I would like to keep the params across devices to reduce the memory consumption of each device. How come I can pmap everything except the updates? Is this really due to CUDA version errors and why does e.g. the forward pass work then? (I have monitored the GPU utilisation and can see that processes are run across GPUs, which means that pmap and the forward pass is allocating memory.)


import jax.numpy as jnp
import jax
from jax import grad, jit, vmap, pmap
from jax import random
from jax.scipy.special import logsumexp
import functools
import numpy as np
import time
import sys
import argparse
import optax
import pdb
####FUNCTIONS####
def make_optimiser(lr=0.001):
    '''Make adam optimiser
    Include weight decay: https://optax.readthedocs.io/en/latest/api.html#optax.adamw
    AF use clipping as well:
    quote: To stabilize the training, we apply gradient clipping by the global norm on the
    parameters independently to every training example in a mini-batch, with a clipping value 0.1.
    '''
    return optax.chain(optax.clip_by_global_norm(0.1),optax.adamw(learning_rate=lr),)

# A helper function to randomly initialize weights and biases
# for a dense neural network layer
def random_layer_params(m, n, key, scale=1e-2):
  w_key, b_key = random.split(key)
  return scale * random.normal(w_key, (n, m)), scale * random.normal(b_key, (n,))

# Initialize all layers for a fully-connected neural network with sizes "sizes"
def init_network_params(sizes, key):
  keys = random.split(key, len(sizes))
  return [random_layer_params(m, n, k) for m, n, k in zip(sizes[:-1], sizes[1:], keys)]

#Relu
def relu(x):
  return jnp.maximum(0, x)

def predict(params, image):
  # per-example predictions
  activations = image
  for w, b in params[:-1]:
    outputs = jnp.dot(w, activations) + b
    activations = relu(outputs)

  final_w, final_b = params[-1]
  logits = jnp.dot(final_w, activations) + final_b
  return logits - logsumexp(logits)

# Make a batched version of the `predict` function
batched_predict = vmap(predict, in_axes=(None, 0))

def one_hot(x, k, dtype=jnp.float32):
  """Create a one-hot encoding of x of size k."""
  return jnp.array(x[:, None] == jnp.arange(k), dtype)

def accuracy(params, images, targets):
  target_class = jnp.argmax(targets, axis=-1)
  predicted_class = jnp.argmax(batched_predict(params, images), axis=-1)
  return jnp.mean(predicted_class == target_class)

def loss_fn(params, images, targets):
  preds = batched_predict(params, images)
  #Take mean over all axes
  return -jnp.mean(preds * targets)


def update(params, opt_state, x, y):

  vg = jax.value_and_grad(loss_fn)
  vg_pmap = pmap(vg)
  loss, grads = vg_pmap(params, x, y)

  #Take mean over pmapped axis
  grads = jax.tree_map(lambda x: jnp.mean(x,axis=0),grads)
  #loss = jnp.mean(loss)
  # and synchronise gradients, the params stay in sync.
  #new_params = jax.tree_map(lambda param, g: param - g * step_size, params, grads)
  params = jax.tree_map(lambda x: x[0], params)
  updates, new_opt_state = make_optimiser().update(grads, opt_state, params)
  new_params = optax.apply_updates(params, updates)

  replicated_params = jax.tree_map(lambda x: jnp.array([x] * n_devices), new_params)
  return replicated_params, loss

def get_train_batches(n_targets, batch_size):
    #Get batch size examples
    x =  random.normal(random.PRNGKey(1), (batch_size, 28 * 28))
    y =  np.random.choice(n_targets, batch_size)

    return x, y

#Get params
layer_sizes = [784, 512, 512, 10]
step_size = 0.01
num_epochs = 10
per_device_batch_size = 128
n_targets = 10


#pmap
n_devices = jax.local_device_count()
batch_size = int(per_device_batch_size*n_devices)
params = init_network_params(layer_sizes, random.PRNGKey(0))
#Replicate across devices
replicated_params = jax.tree_map(lambda x: jnp.array([x] * n_devices), params)
opt_state = make_optimiser().init(params)
# This works on single examples
# random_flattened_image = random.normal(random.PRNGKey(1), (28 * 28,))
# preds = predict(params, random_flattened_image)
# print(preds.shape)

# `batched_predict` has the same call signature as `predict`
# random_flattened_images = random.normal(random.PRNGKey(1), (10, 28 * 28))
# batched_preds = batched_predict(params, random_flattened_images)
# print(batched_preds.shape)

#Train loop
num_pixels=784
for epoch in range(num_epochs):
    start_time = time.time()
    x, y = get_train_batches(n_targets, batch_size)
    x = jnp.reshape(x, (n_devices, per_device_batch_size, num_pixels))
    y = jnp.reshape(one_hot(y, n_targets), (n_devices, per_device_batch_size, n_targets))
    replicated_params, loss = update(replicated_params, opt_state, x, y)
    epoch_time = time.time() - start_time
    print(loss, epoch_time)

**Comment by patrickbryant1** [comment]
I think this issue is related to how JAX has been installed. It is installed in a singularity env and somehow this allows for some communication btw processes, but not all. I am simply surprised that it works to do some pmap computations, but not others. Perhaps this is not a bug with JAX, but it is surprising.
