### ISSUE TITLE
JAX with GPU support requires jaxlib version 0.1.26

### ISSUE THREAD

**Issue by sursu** [google/jax#1297]
I've got an issue.

So, I followed the installation instructions here:
![image](https://user-images.githubusercontent.com/12001304/64115427-e8b98300-cd8f-11e9-879c-b4935195991c.png)

Then I run the following line in `JupyterLab`:
```python
import jax.numpy as jnp
```
And that produces the following error:
```python
ValueError: jaxlib is version 0.1.23, but this version of jax requires version 0.1.26.
```

I went back and changed the second last line to:
```bash
pip install --upgrade $BASE_URL/$CUDA_VERSION/jaxlib-0.1.26-$PYTHON_VERSION-none-$PLATFORM.whl
```
Tried running. But, was denied.
![image](https://user-images.githubusercontent.com/12001304/64115630-6bdad900-cd90-11e9-92d6-ebc6dc1c15a0.png)

**Comment by mattjj** [comment]
Thanks! I think our documentation is out-of-date, as we forgot to update it when we bumped the minimum jaxlib version.
