### ISSUE TITLE
Get values of the hidden layers 

### ISSUE THREAD

**Issue by ravidziv** [google/jax#1301]
Hi,

Can I get the values of the hidden layers when I'm using stax.serial?

thanks!

**Comment by samuela** [comment]
Do you mean get the parameters (weights, biases, etc) or the "activations" for a particular input, eg. `g(x)` in a network `f(g(x))`?

**Comment by hawkinsp** [comment]
Closing because there was no response, and because we aren't really recommending `stax` any more these days.
