### ISSUE TITLE
add the double where trick to 'sharp bits'

### ISSUE THREAD

**Issue by mattjj** [google/jax#13047]
> It might be worth adding the double where trick to [JAX - the sharp bits](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html). (I looked there first, before eventually finding an explanation for my error here.)

_Originally posted by @Sohl-Dickstein in https://github.com/google/jax/issues/1052#issuecomment-1295824996_

**Comment by mattjj** [comment]
And/or: we can suggest the use of `vmap`-of-`cond`, which naturally avoids the problem.

**Comment by jakevdp** [comment]
Do we have any action items here? Is the existing discussion insufficient or too hard to find?

**Comment by jakevdp** [comment]
I think this is addressed.
