### ISSUE TITLE
jvp takes tuple of primals but linearize and vjp does not

### ISSUE THREAD

**Issue by jessebett** [google/jax#1310]
The call for `jvp` is `jax.jvp(fun, primals, tangents)` which expects the `primals` to be a tuple. This is required to avoid ambiguity with the `tangents`.

However, `vjp` and `linearize` follow a different convention which expects the primals to be unpacked.
`jax.linearize(fun, *primals)`
`jax.vjp(fun, *primals, **kwargs)`

Why not keep them consistent? 

Proposing:
`linearize(fun,primals)`
`vjp(fun,primals,**kwargs)`

**Comment by mattjj** [comment]
Too late to change now, sorry Jesse ;)
