### ISSUE TITLE
typo in docstring for `jax.lax.approx_min_k`

### ISSUE THREAD

**Issue by newalexander** [google/jax#13161]
### Description

Hello! I believe the example usage in the docstring for `jax.lax.approx_min_k`(https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.approx_min_k.html#jax.lax.approx_min_k)  contains a typo. Specifically, the halved database norm term `half_db_norms` should be the squared norm, not the full norm. This follows from the derivation in Appendix A.2 of the algorithm's paper (https://openreview.net/forum?id=OoNmOfYVhEU).

**Comment by hawkinsp** [comment]
@dryman ?

**Comment by hawkinsp** [comment]
@dryman fixed this in https://github.com/google/jax/pull/13204

Hope that helps!
