### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by sursu** [google/jax#1317]
Glad to see support for CUDA 10.1, but I'm again encountering installation issues:

HTTP error 404

![image](https://user-images.githubusercontent.com/12001304/64424437-5ecc2b80-d0a9-11e9-8d20-45e800dad94e.png)

I've looked at the BASE_URL: https://storage.googleapis.com/jax-releases and there is no release for `cuda101`.

**Comment by hawkinsp** [comment]
@skye It looks like the 0.1.28 wheels aren't present in the jax-releases bucket?

**Comment by mattjj** [comment]
Thanks for catching this! They should be uploaded now.
