### ISSUE TITLE
Cannot use tokens in custom calls with layout

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#13187]
### Description

At [mpi4jax](https://github.com/mpi4jax/mpi4jax) we are using tokens passed to custom calls to prevent re-ordering of stateful operations. We recently noticed that we are getting wrong results when transposes are not manifested on GPU (mpi4jax/mpi4jax#176), so we tried switching to `CustomCallWithLayout`.

Now to the main problem: when passing tokens to `CustomCallWithLayout`, XLA fails when trying to determine the layout of the token. (We are getting the same issue when using the new `jaxlib.mhlo_helpers.custom_call` instead.)

Example:

```python
def my_dummy_op_encode_cpu(ctx, x, token):
    # ...
    return custom_call(
      b"my_dummy_op",
      [dtype, token.type],
      [x, token],
      backend_config=None,
      operand_layouts=[layout, ()],
      result_layouts=[layout, ()],
      has_side_effect=True)
```

This crashes the interpreter with:

```
 2022-11-09 19:13:37.960054: F external/org_tensorflow/tensorflow/compiler/xla/shape.h:162] Check failed: IsArray() element_type: TOKEN
```

[MWE on Colab](https://colab.research.google.com/drive/1qS3yE5Zav2L5XNzszWmtXJY0uaXxP0d4?usp=sharing), thanks to @EiffL.

If this is indeed a bug in XLA, is there a simple workaround? Explicitly making a copy would be acceptable as a temporary fix, but `jnp.ascontiguousarray` is not available.

**Comment by sharadmv** [comment]
I ran into this bug a few days as well! It is fixed at HEAD in XLA: https://github.com/tensorflow/tensorflow/commit/c84f2805db56e9739c90619ea6bd6926cd20aba7. A new jaxlib release should have this issue.
