### ISSUE TITLE
Compilation error (nv-nsight-cu-cli not found)

### ISSUE THREAD

**Issue by adityaiitb** [google/jax#1320]
I am trying to compile JAX from source with GPU support. My GCC version is 8.3. When I run

$ python build/build.py --enable_cuda

It looks for the file /usr/local/cuda-10.1/NsightCompute-*/nv-nsight-cu-cli but it doesn't exist.

I fixed it temporarily by creating the following soft link.

$ ln -s /usr/local/cuda-10.1/NsightCompute-*/nv-nsight-cu-cli.orig /usr/local/cuda-10.1/NsightCompute-*/nv-nsight-cu-cli

**Comment by hawkinsp** [comment]
I suspect this issue is obsolete now; closing. Please feel free to reopen if you can still reproduce it!
