### ISSUE TITLE
Support for TFLite FloorMod

### ISSUE THREAD

**Issue by galah92** [google/jax#13207]
I'm creating JAX functions and convert them to TFLite models using `tf.lite.TFLiteConverter.experimental_from_jax`.

When trying to convert a simple `i = (i + 1) % buff_size` operation, I'm getting the following error:
> 'tf.Mod' op is neither a custom op nor a flex op

TFLite does support [`floor_mod`](https://www.tensorflow.org/mlir/tfl_ops#tflfloor_mod_mlirtflfloormodop), which seems to be ok for my case. So I tried `i = jnp.fmod(i + 1, buff_size)` but got the exact same error.

**Comment by gnecula** [comment]
Can you try an alternative conversion using jax2tf followed by the TFLite converter, as described [here](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/examples/tflite/mnist/README.md)?

**Comment by galah92** [comment]
On a coincidence, I switched laptops and installed updated TensorFlow & JAX versions, seems like `i = (i + 1) % buff_size` expressions are correctly being converted to `FloorMod` ops. Thank you for your help.
