### ISSUE TITLE
[sparse] Difference between BCOO matrices removes zeros

### ISSUE THREAD

**Issue by lucagrementieri** [google/jax#13296]
### Description

The difference operation between two `BCOO` sparse matrices implicitly removes zeros. The behaviour is different from the one observed for the addition. Consider the example below.

```python
import jax.experimental.sparse as jsp
import jax.numpy as jnp

a = jsp.BCOO((jnp.array([1.0]), jnp.array([[0, 0]])), shape=(3, 3))
b_values = jnp.array([0.0, 1.0, 0.0])
b_indices = jnp.array([[0, 0], [1, 1], [2, 2]])
b = jsp.BCOO((b_values, b_indices), shape=(3, 3))

print("Difference\n", (a - b).indices)
print("Addition\n", (a + b).indices)
```

The output is 
```
Difference
 [[0 0]
 [1 1]
 [3 3]
 [3 3]]
Addition
 [[0 0]
 [0 0]
 [1 1]
 [2 2]]
```

As you can see, in the difference operation the indices associated to null values in `a` or `b` have disappeared and they have been replaced with the out-of-bounds index `[3,3]`.

The expected behaviour can be obtained using `a + (-1)*b`.

### What jax/jaxlib version are you using?

jax v0.3.25, jaxlib v.0.3.25

### Which accelerator(s) are you using?

CPU/GPU

### Additional system info

Python 3.10.8, ArchLinux

### NVIDIA GPU info

NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8

**Comment by jakevdp** [comment]
Hi - thanks for the report. The issue isn't in subtraction, but rather the sparse rule for `neg_p`. Currently it's treated as any other unary operation, and in general unary operations do not commute with addition (i.e. `op(x + y) != op(x) + op(y)` in general for operations like `sin` and `cos`). For this reason, the unary operation sparse rule will deduplicate indices, which has the side effect of removing explicit zeros. This is fine in general if you consider the sparse data structure only as an abstract representation of a dense matrix.

Is it important in your application for explicit zeros to be maintained during operations? The sparse design currently does not include that in its design considerations, and so I expect you'll run into this kind of thing frequently.

So, that said, I think this is "working as intended" for now, but we may be able to think about change the design goals of the sparse functionality if it's required for important use-cases.

**Comment by lucagrementieri** [comment]
Thank you for the clarification on the reasons leading to this behaviour!
In my application, I use BCOO matrices as "dictionaries" where the listed indices can be associated even to a null value, while non-listed indices are considered as undefined. I believe that this use case can be quite common: for example if we want to represent scalar values associated to points scattered on a N-dimensional grid, we can use a sparse matrix to represent points and values and we want to allow the null value.

Surely, I think that the `neg_p` behaviour should be consistent with the sum as you propose!
For the other operations, I agree that the duplicates should be removed, but I'm not sure that zeros should be removed too. In particular, for functions like `cos` (`cos(0) != 0`) that transform null values in non-null values, if the code does not explicitly prescribe to remove zeros, maybe the author expects that zero values will become non-null values after the transformation.

**Comment by jakevdp** [comment]
Makes sense - so I think we could call `sum_duplicates` with `remove_zeros=False` for unary ops, and also specialize `lax.neg_p` to avoid index modification.

Also, regarding cosine, I shouldn't have brought that up because unary ops that map zeros to non-zero values are not implemented in sparse (because the result is generally a dense matrix).

**Comment by jakevdp** [comment]
#13300 should address these issues - thanks for raising them!
