### ISSUE TITLE
Installing with minimum-jaxlib fails for Python 3.11

### ISSUE THREAD

**Issue by lumip** [google/jax#13309]
### Description

Trying to install jax v0.3.25 on Python 3.11 via pip with the `minimum-jaxlib` extra fails to resolve a jaxlib version:

```
pip install "jax[minimum-jaxlib]==0.3.25"
```

gives output

```
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.22; extra == "minimum-jaxlib" (from jax[minimum-jaxlib]) (from versions: 0.3.24, 0.3.25)
ERROR: No matching distribution found for jaxlib==0.3.22; extra == "minimum-jaxlib"
```
.

The problem appears that only jaxlib versions >= 0.3.24 are available on PyPI for Python 3.11. 

Possible fixes:
- update minimum-jaxlib to 0.3.24
- make jaxlib 0.3.22 available for python 3.11
- instead of freezing any particular jaxlib version via `minimum-jaxlib`, maybe an extra `compatible-jaxlib` that defines a version range of known good jaxlib versions and is updated with every jax release would be a better option. For jax v0.3.25 it would now be `jaxlib >= 0.3.22, <=0.3.25` for example. That would give a bit more freedom to which particular version to resolve from the package index, while still restricting it to one that is known to work with that particular jax version.

### What jax/jaxlib version are you using?

jax v0.3.25, jaxlib v0.3.22

### Which accelerator(s) are you using?

CPU/any

### Additional system info

Python 3.11, Ubuntu Linux, Anaconda

**Comment by mjsML** [comment]
@hawkinsp @yashk2810 @nouiz @yhtang for viz

**Comment by hawkinsp** [comment]
Metaquestion: why are you installing the minimum jaxlib at all?

This particular problem will resolve itself when we bump the minimum, which we are technically free to do at any time, but we typically try to not do it right after a new release just in case the new release is problematic.

**Comment by lumip** [comment]
I mostly need this in automated tests that verify that my project still works with older jax versions. I cannot use the `cpu` extra/target for that as it would just install the newest (and likely incompatible) jaxlib version.

**Comment by hawkinsp** [comment]
You should be able to use the `cpu` extra along with a version constraint, e.g.,
```
pip install "jax[cpu]==0.3.24"
```
should install jax 0.3.24 along with whatever `jaxlib` that version of `jax` pinned.

Is there a particular reason you care about the jaxlib version and not just the jax version?

**Comment by lumip** [comment]
It seems I have missed the change in jax version v 0.2.27 that freezes the jaxlib version. I set up my tests before then and there had the problem that jax would always pull the latest jaxlib version available, which tended to cause incompatibilities for older versions of jax. So it seems that now I can switch to using the `cpu` extra then..

Remaining questions is then, why is there still a `minimum-jaxlib` extra?
