### ISSUE TITLE
jnp.sum signature doesn't have `promote_integers` argument

### ISSUE THREAD

**Issue by hirwa-nshuti** [google/jax#13301]
### Description

As noted from the `jax.numpy.sum` function here in the [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.sum.html)
The function should receive the `promote_integers` parameter but the binding of the function doesn't have it.

```python
import jax.numpy as jnp
from inspect import signature as sig


x = sig(jnp.sum)
print(str(x)) # (a, axis: Union[int, Tuple[int, ...], NoneType] = None, dtype=None, out=None, keepdims=None, initial=None, where=None)

```
Also calling the function with this parameter will always return type error.

```python
import jax.numpy as jnp
from inspect import signature as sig

x = jnp.array([[1, 2, 3], [4, 5, 6]])
promote_integers = False

y = jnp.sum(x, promote_integers=promote_integers)
# y = jnp.sum(x, promote_integers=promote_integers)
# TypeError: sum() got an unexpected keyword argument 'promote_integers''
```

Not sure if this parameter can be added to the function's binding or be removed from the documentation.
Thanks

### What jax/jaxlib version are you using?

0.3.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by jakevdp** [comment]
The `promote_integers` argument was added in https://github.com/google/jax/pull/12382, which was part of the JAX v0.3.20 release. If you're using JAX v0.3.14, the argument will not be supported.

**Comment by hirwa-nshuti** [comment]
Thanks for clarifying
