### ISSUE TITLE
Enable float16 cuda support for jax.experimental.sparse.BCOO?

### ISSUE THREAD

**Issue by Lalaland** [google/jax#13324]
Would it be possible to enable float16 support for the CUDA backend of jax.experimental.sparse.BCOO?

Right now the code asserts that the dtype is either float32, float64, complex64 or complex128

This assert is in https://github.com/google/jax/blob/main/jax/experimental/sparse/bcoo.py#L753 and https://github.com/google/jax/blob/main/jax/experimental/sparse/bcoo.py#L902

However, per the cusparse docs, this should be supported: https://docs.nvidia.com/cuda/cusparse/index.html#cusparse-generic-function-spmm

I tried adding float16 to those two checks and the code did seem to work (although we would want to add an if statement in https://github.com/google/jax/blob/main/jaxlib/gpu/sparse_kernels.cc#L530 to force the use of 32 bit intermediates).

If this would be a good change, let me know and I can submit a PR to flip those flags and add the if check.

**Comment by Lalaland** [comment]
CC @hawkinsp as I believe you wrote the code involved here

**Comment by Lalaland** [comment]
Closing this issue as I just realized that BCOO doesn't really work on GPUs at all yet.

**Comment by hawkinsp** [comment]
@jakevdp
