### ISSUE TITLE
sparse.eye calls Numpy preventing JIT

### ISSUE THREAD

**Issue by terhorst** [google/jax#13340]
### Description

```
from jax import jit, numpy as jnp
from jax.experimental.sparse import eye


def f(A):
    n = A.shape[0]
    return eye(n)


A = jnp.ones([3, 3])
f(A)
# BCOO(float32[3, 3], nse=3)
jit(f)(A)
# TracerArrayConversionError ...
```

The problem function is:

https://github.com/google/jax/blob/42e367af9c58cb67496e235eddf325aa285600e4/jax/_src/lax/lax.py#L4708-L4713

I think the return could just be changed to `jnp.array`. 

### What jax/jaxlib version are you using?

v0.3.23

**Comment by jakevdp** [comment]
Thanks for the report - looks like the implementation is a bit sloppy with respect to static and dynamic values. Who wrote this code anyway? [oh no...](https://github.com/google/jax/pull/10782) 😀
