### ISSUE TITLE
Unexpected behavior in jax.lax.switch

### ISSUE THREAD

**Issue by MauricioGS99** [google/jax#13351]
### Description

I'm seeing an unexpected behavior in jax.lax.switch

`
def fun_a():
    print('a')
    
def fun_b():
    print('b')
    
def fun_c():
    print('c')

functions_list=[fun_a,fun_b,fun_c]

jax.lax.switch(0,functions_list)
`

returns 

`a b c`

shouldn't it return only "a"?

**Comment by soraros** [comment]
I think this is working as intended™. `lax.swtich` traces all its branches, so side-effects will happen before 'real` evaluation (numerical computation, for instance) of the branches. If you want to print intermediate values in a traced function, [`jax.debug.print`](https://jax.readthedocs.io/en/latest/_autosummary/jax.debug.print.html#jax.debug.print) might be helpful.

**Comment by MauricioGS99** [comment]
Thanks!

**Comment by apaszke** [comment]
Yup, confirming that this is working as intended. JAX assumes that your code is pure, and you might see surprising results like this if it's not.
