### ISSUE TITLE
odeint keeps throwing unexpected keyword argument 'args' TypeError:

### ISSUE THREAD

**Issue by amdee** [google/jax#13362]
### Description
While trying to use odeint I noticed that the documentation states that "*args: tuple of additional arguments for `func`, which must be arrays scalars, or (nested) standard Python containers (tuples, lists, dicts, namedtuples, i.e. pytrees) of those types" but if I follow above instruction from the documentation I get the above-mentioned TypeError:
```python
def pend(y, t, b, c):
    theta, omega = y[0], y[1]
    dydt = jnp.array([omega, -b*omega - c*jnp.sin(theta)])
    return dydt

b = 0.25
c = 5.0

t = np.linspace(0, 10, 101)
y0 = np.array([np.pi - 0.1, 0.0])
sol = odeint(pend, y0, t, args=(b, c))
```
The above code throws TypeError: odeint() got an unexpected keyword argument 'args'

But if the additional parameters a passed as separate arguments the errors goes away, see the code below;
```python
def pend(y, t, b, c):
    theta, omega = y[0], y[1]
    dydt = jnp.array([omega, -b*omega - c*jnp.sin(theta)])
    return dydt

b = 0.25
c = 5.0

t = np.linspace(0, 10, 101)
y0 = np.array([np.pi - 0.1, 0.0])
sol = odeint(pend, y0, t, b, c)
```
### What jax/jaxlib version are you using?
0.3.25

### Which accelerator(s) are you using?
CPU

### Additional system info:
The above code was run on google colab

**Comment by pharringtonp19** [comment]
@amdee I don't believe this is an issue with jax, but rather related to the workings of `*args` in python.

To highlight this, consider the following function. 

```
def f(t, *args):
  print(type(args))
  for arg in args:
    print(arg)
``` 

The following won't work:

```
f(1., args=("Hi", 2.0, "Hello"))
TypeError: f() got an unexpected keyword argument 'args'
```

But, this will
```
f(1., 'Hi', 2.0, 'Hello')
<class 'tuple'>
Hi
2.0
Hello
```

**Comment by amdee** [comment]
I figured that might be the issue. I guess I am used to the[ scipy.integrate.odeint](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.odeint.html). I think this might be one of those gotcha things for someone used to scipy
