### ISSUE TITLE
jnp.linalg.eigh doesn't give correct output

### ISSUE THREAD

**Issue by zengjk** [google/jax#13392]
### Description

I noticed that for complex hermitian matrix jnp.linalg.eigh gives weird answer. For example:
```
sy=np.array([[ 0.+0.j, -0.-1.j],[ 0.+1.j,  0.+0.j]])
jnp.linalg.eigh(sy)

(DeviceArray([-1.,  1.], dtype=float32),
 DeviceArray([[-0.70710677-0.70710677j, -0.70710677-0.2071068j ],
              [-0.70710677+0.70710677j,  0.49999997-0.7071067j ]],            dtype=complex64))
```
while the output from eig is correct:
```
jnp.linalg.eig(sy)
(DeviceArray([ 1.+0.j, -1.+0.j], dtype=complex64),
 DeviceArray([[ 0.70710677+0.j        ,  0.70710677+0.j        ],
              [-0.        +0.70710677j,  0.        -0.70710677j]],            dtype=complex64))
```

I noticed this issue appeared in normal numpy in an older version but is then fixed after an upgrade.

### What jax/jaxlib version are you using?

jax v0.3.25 jaxlib v0.3.25

### Which accelerator(s) are you using?

CPU

### Additional system info

M1 Mac

**Comment by jakevdp** [comment]
Hi - thanks for the question. I suspect this is somehow related to the particular LAPACK version that the M1 jaxlib build is linked against. I ran your code on a Colab CPU, Colab GPU, and non-M1 mac CPU and saw the expected output. Assigning to @yashk2810 because I think he has some context on M1 wheel builds.

**Comment by hawkinsp** [comment]
The most important version here is the version of `scipy`. What version do you have installed?

**Comment by zengjk** [comment]
Sorry for this late update. This is indeed likely an issue with scipy. The problem is fixed after a scipy update. I don't remember which version my scipy was tho.
