### ISSUE TITLE
np.asarray is slow

### ISSUE THREAD

**Issue by lukemetz** [google/jax#1344]
np.asarray is quite slow on larger python based data structures. Jitting it helps, but default numpy is still way faster. Did a bit of benchmarking. This was tested on CPU.

jax np.asarray: 3.5 seconds
jit: 555 ms
onp.asarray: 1ms

Full timing colab: https://colab.research.google.com/drive/1afYvTDC1MQlF7m_xxP5vGmG0q6-h-YwS#scrollTo=duvkdsjnmF3I

**Comment by jakevdp** [comment]
There is further discussion here: https://github.com/google/jax/issues/10662
