### ISSUE TITLE
`jit` obscures unbound axis errors

### ISSUE THREAD

**Issue by froystig** [google/jax#1347]
Evaluating a parallel primitive without parallel context—that is, with an unbound axis variable—typically raises a legible error. However, the error is obscured under `jit`: 

```
from jax import lax, jit
import jax.numpy as np

(lambda x: lax.psum(x, 'i'))(np.ones(2))     # NameError: unbound axis name: i

jit(lambda x: lax.psum(x, 'i'))(np.ones(2))  # ValueError: max() arg is an empty sequence
```

**Comment by mattjj** [comment]
We fixed this at some point!
