### ISSUE TITLE
jax.numpy.bincount returns different values than numpy.bincount

### ISSUE THREAD

**Issue by EmJay276** [google/jax#13472]
### Description

Using exactly the same values for np.bincount and jnp.bincount returns different values
```
np.allclose(np.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()), 
            jnp.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()))
>>> False
```

```
np.abs(np.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()) - jnp.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel())).max()
>>> 0.0007534027
```

With a minimal example I couldn't reproduce it, seems to be due to my data.
I will check back if I can find why.

### What jax/jaxlib version are you using?

jax/jaxlib v0.3.25

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.8, numpy 1.23.5

**Comment by EmJay276** [comment]
@jakevdp thank you for your fast response!
I figured it out, it was due to numerical error with jax using float32 as default.

```
np.allclose(np.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()), 
            jnp.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()))
>>> False
```

```
from jax.config import config
config.update("jax_enable_x64", True)

np.allclose(np.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()), 
            jnp.bincount(B_rows.ravel(), weights=Bq_elementwise[k].ravel()))
>>> True
```

**Comment by jakevdp** [comment]
OK, thanks for following up. I'm going to close the issue since it seems like there are no action items here - feel free to let us know if you run into other problems!
