### ISSUE TITLE
No CUDA kernels in jax profiler trace view

### ISSUE THREAD

**Issue by FindHao** [google/jax#13477]
### Description

Hi, I tested an example  resnet model with jax in [phlippe's repo](https://github.com/phlippe/uvadlc_notebooks_benchmarking/blob/main/PyTorch/Tutorial5_Inception_ResNet_DenseNet.py). 
The code snippet is in [this gist](https://gist.github.com/FindHao/db610e0b7d38c362558f413793eb7207). I split only the resnet model from the original file and add the jax profiler to [line 285](https://gist.github.com/FindHao/db610e0b7d38c362558f413793eb7207#file-resnet-py-L285). You can directly run `python3 resnet.py` and it will generates profiling results in `/tmp/jax-trace/`.

When I use tensorboard to open the trace, no CUDA kernels are shown in GPU row under trace view during the model execution. only several memory copy functions and XLA operations occur on GPU before model execution like figure shown. 

But there are collected CUDA kernels information in kernel_stats view such as `ampere_scudnn_winograd_128x128_ldg1_ldg4_relu_tile148t_nt_v1`. 

![Screenshot from 2022-12-01 14-29-11](https://user-images.githubusercontent.com/3823240/205143867-85c5f3ae-63e0-46ee-91ed-c808f4e76cb0.png)
Figure 1

I tested jax 0.3.25 jaxlib 0.3.25+cuda11.cudnn82 and jax 0.3.22 jaxlib 0.3.22+cuda11.cudnn82. They both have same results. 

### What jax/jaxlib version are you using?

jax 0.3.25 jaxlib 0.3.25+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 20.04, python 3.8.14

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  Off  | 00000000:00:04.0 Off |                    0 |
| N/A   30C    P0    45W / 400W |      0MiB / 40960MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

GPU 0: NVIDIA A100-SXM4-40GB

**Comment by FindHao** [comment]
I have found a workaround to this issue. It is caused by missing device synchronization. 

```
    dummy = jnp.array(1.)
    start_time = time.time()
    with jax.profiler.trace("/tmp/jax-trace"):
        trainer.train_model(train_loader, val_loader, num_epochs=num_epochs)
        (dummy * dummy).block_until_ready()  # synchronize CUDA.
    train_time = time.time()
```
It is tricky. I'm wondering is the `with` clause supposed to have a device synchronization?

**Comment by hawkinsp** [comment]
Belated response:

This is working as intended: the `jax.profiler.trace` scope doesn't synchronize the device. If you want to make sure something is traced, you have to add a `.block_until_ready()` as you note. See the documentation here: https://jax.readthedocs.io/en/latest/profiling.html#programmatic-capture

Hope that helps!

**Comment by am001122** [comment]
Still having this same issue now, seems like can also be caused by #21295, potentially?
