### ISSUE TITLE
Change in behavior of jax.distributed

### ISSUE THREAD

**Issue by jjwilke** [google/jax#13474]
### Description

Originally posted in the discussion, but maybe better to report as a bug since I am seeing a significant change in behavior.
https://github.com/google/jax/discussions/13439

I am getting different behaviors for each of these scenarios:
1. 2 GPUs on a node in the same process (both recent commit and release)
2. 1 GPU per process, 2 processes (recent commit: 7495a9e3705d67c498723240cfed3f14c5916567)
3. 1 GPU per process, 2 processes (0.3.25 release commit: a683186570404a05a2aea9f7e452400bb0299e57)

I launch the following simple program that adds two arrays and reduces the sum.
```
mpirun -n 2 python test.py
```

```
import jax
import os
import numpy as np
import jax.numpy as jnp
from mpi4py import MPI
from jax.experimental.pjit import pjit
from jax.experimental.pjit import PartitionSpec as P
from jax.experimental.maps import Mesh
from jax import make_jaxpr

rank = MPI.COMM_WORLD.Get_rank()
size = MPI.COMM_WORLD.Get_size()
rc = jax.distributed.initialize("localhost:1234", size, rank)

os.environ["CUDA_VISIBLE_DEVICES"] = str(rank)

def fxn(a,b):
    return (a + b).sum()

fp = pjit(fxn, in_axis_resources=(P('x',), P('x',)), out_axis_resources=None)

a = jnp.arange(8)
b = jnp.arange(8)
devices = np.array(jax.devices())
with Mesh(devices, ('x',)):
    if rank == 0:
        print(devices)
        print(make_jaxpr(fp)(a,b))
    c = fp(a,b)

if rank == 0:
    print(c)
```

For recent commit, I get the following output (jaxpr and result):

```
[StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)
 StreamExecutorGpuDevice(id=1, process_index=1, slice_index=0)]
{ lambda ; a:i32[8] b:i32[8]. let
    c:i32[] = pjit[
      donated_invars=(False, False)
      in_positional_semantics=(<_PositionalSemantics.GLOBAL: 1>, <_PositionalSemantics.GLOBAL: 1>)
      in_shardings=(OpShardingSharding({devices=[2]0,1}), OpShardingSharding({devices=[2]0,1}))
      jaxpr={ lambda ; d:i32[8] e:i32[8]. let
          f:i32[8] = add d e
          g:i32[] = reduce_sum[axes=(0,)] f
        in (g,) }
      name=fxn
      out_positional_semantics=_PositionalSemantics.GLOBAL
      out_shardings=(OpShardingSharding({replicated}),)
      resource_env=ResourceEnv(Mesh(array([0, 1]), ('x',)), ())
    ] a b
  in (c,) }
56
```
For 2 GPUs in the same process, the output is basically the same except the GPUs are both `process_index=0`

For 0.3.25 release, I get a different output and different jaxpr:
```
[StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)
 StreamExecutorGpuDevice(id=1, process_index=1, slice_index=0)]
{ lambda ; a:i32[8] b:i32[8]. let
    c:i32[] = pjit[
      donated_invars=(False, False)
      in_positional_semantics=(<_PositionalSemantics.LOCAL: 0>, <_PositionalSemantics.LOCAL: 0>)
      in_shardings=(OpShardingSharding({devices=[2]0,1}), OpShardingSharding({devices=[2]0,1}))
      jaxpr={ lambda ; d:i32[16] e:i32[16]. let
          f:i32[16] = add d e
          g:i32[] = reduce_sum[axes=(0,)] f
        in (g,) }
      name=fxn
      out_positional_semantics=_PositionalSemantics.LOCAL
      out_shardings=(OpShardingSharding({replicated}),)
      resource_env=ResourceEnv(Mesh(array([0, 1]), ('x',)), ())
    ] a b
  in (c,) }
112
```

So basically multi-GPU in one process and multi-process (recent commit) treat the input arrays `a` and `b` as global arrays of size 8 and create two shards of size 4 on each GPU.

Multi-process on the most recent release treats the input arrays `a` and `b` as global arrays of size 16 that have already been sharded. It was not obvious to me glancing through recent history why this behavior would have changed.

What is the expected or defined behavior? I would have thought the behavior would be the same regardless of whether multiple devices are in the same process or in different processes.  The "new" distributed behavior makes more sense to me since you would expect the answer to be independent of the number of GPUs or how the GPUs are distributed.

### What jax/jaxlib version are you using?

7495a9e3705d67c498723240cfed3f14c5916567 and 0.3.25

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 20.04, Python 3.10.6

### NVIDIA GPU info

Probably not relevant, but:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:01:00.0 Off |                  Off |
| 30%   38C    P8    25W / 300W |     40MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000    On   | 00000000:61:00.0 Off |                  Off |
| 30%   46C    P8    23W / 300W |    122MiB / 49140MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+                                     
```

**Comment by yashk2810** [comment]
I replied on the discussion

**Comment by yashk2810** [comment]
I am going to close this issue as this is an intended change in pjit (see the discussion where we can continue this). Feel free to open if we identify an actual bug.
