### ISSUE TITLE
Remove `jax.experimental.maps.Mesh` and `jax.experimental.PartitionSpec` since they are deprecated

### ISSUE THREAD

**Issue by yashk2810** [google/jax#13487]
Remove the APIs in 3 months from today.

The replacement is `jax.sharding.Mesh` and `jax.sharding.PartitionSpec`.

**Comment by shoyer** [comment]
These APIs are still introduced in the new "Parallelism with JAX" guide -- seems like they should probably be replaced with alternatives?
https://jax.readthedocs.io/en/latest/notebooks/Parallelism_with_JAX.html#namedsharding-gives-a-way-to-express-shardings-with-names

**Comment by yashk2810** [comment]
Yeah great point! Well there are not deprecated but the public endpoint has moved to a new location.
