### ISSUE TITLE
XlaRuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm for scipy correlate

### ISSUE THREAD

**Issue by heliogabale** [google/jax#13496]
### Description

Hello 
When running the following code 
(the pure scipy version of this snippet runs)
```python
from jax.scipy.signal import correlate as jcorrelate

def jcorr(x,y):
    return jcorrelate(x,y,mode='valid')

sig = jnp.repeat(jnp.array([0., 1., 1., 0., 1., 0., 0., 1.]))

jit(jcorr(sig,sig),backend='cpu')
```
I am getting the following error

XlaRuntimeError: UNKNOWN: Failed to determine best cudnn convolution algorithm for:
%cudnn-conv-bw-filter = (f32[1,1,1]{2,0,1}, u8[0]{0}) custom-call(f32[1,1,8]{2,0,1} %bitcast, f32[1,1,8]{2,0,1} %bitcast.1), window={size=1}, dim_labels=fb0_io0->fb0, custom_call_target="__cudnn$convBackwardFilter", metadata={op_name="jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1,) padding=((0, 0),) lhs_dilation=(1,) rhs_dilation=(1,) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 1, 2), rhs_spec=(0, 1, 2), out_spec=(0, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 1, 8) rhs_shape=(1, 1, 8) precision=None preferred_element_type=None]" source_file="/home/sld5866/Desktop/proofs-of-concept/lloid/vmap.py" source_line=44}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"

Original error: INTERNAL: All algorithms tried for %cudnn-conv-bw-filter = (f32[1,1,1]{2,0,1}, u8[0]{0}) custom-call(f32[1,1,8]{2,0,1} %bitcast, f32[1,1,8]{2,0,1} %bitcast.1), window={size=1}, dim_labels=fb0_io0->fb0, custom_call_target="__cudnn$convBackwardFilter", metadata={op_name="jit(conv_general_dilated)/jit(main)/conv_general_dilated[window_strides=(1,) padding=((0, 0),) lhs_dilation=(1,) rhs_dilation=(1,) dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 1, 2), rhs_spec=(0, 1, 2), out_spec=(0, 1, 2)) feature_group_count=1 batch_group_count=1 lhs_shape=(1, 1, 8) rhs_shape=(1, 1, 8) precision=None preferred_element_type=None]" source_file="/home/sld5866/Desktop/proofs-of-concept/lloid/vmap.py" source_line=44}, backend_config="{\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}" failed. Falling back to default algorithm.  Per-algorithm errors:
  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng20{k2=7,k3=0}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng1{k3=0,k2=6}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng21{k4=1,k5=0,k6=0,k7=0,k2=2}: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng18{k11=2}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng22{k2=7,k5=2,k14=5}: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng25{k5=2,k14=2,k0=2,k2=3}: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng34{k5=3,k14=3,k0=1,k2=5}: UNKNOWN: CUDNN_STATUS_INTERNAL_ERROR
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng0{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng1{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'
  Profiling failure on cuDNN engine eng20{}: UNKNOWN: CUDNN_STATUS_EXECUTION_FAILED
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc(4369): 'status'

To ignore this failure and try to use a fallback algorithm (which may have suboptimal performance), use XLA_FLAGS=--xla_gpu_strict_conv_algorithm_picker=false.  Please also file a bug for the root cause of failing autotuning.

Thank you for your help

### What jax/jaxlib version are you using?

jax 3.17

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.7 , Linux

**Comment by jakevdp** [comment]
Hi - thanks for raising the issue. Can you double-check your code snippet is correct? It looks like there's an argument missing in `jnp.repeat`, and the `jit` function call does not look like it's called correctly. Thanks!
