### ISSUE TITLE
Integration with TensorBoard

### ISSUE THREAD

**Issue by alexbw** [google/jax#135]
This could be a simple example of how to do it, since PyTorch users have already extracted it from TensorFlow as a whole (https://github.com/lanpa/tensorboardX, but that's just one example)

**Comment by hawkinsp** [comment]
I'm wondering if we still want to do this in Jax itself.

Trax already has a TensorBoard integration (jaxboard):
https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/trax/jaxboard.py

**Comment by mattjj** [comment]
I think we do not want to do this in JAX itself. We're starting to point more and more to trax as an example, and this is one more reason to do it. We could point to the TensorBoard integration specifically, but since trax mentions it prominently in its readme, I don't think that's necessary.
