### ISSUE TITLE
cannot serialize 'Array' object when jax_array = True

### ISSUE THREAD

**Issue by wookayin** [google/jax#13540]
### Description

```python
import jax.numpy as jnp
from flax import serialization

s = jnp.zeros(5)
t = serialization.msgpack_serialize(s)
print(len(t))
```

jax 0.3.25: works OK (prints 36)
jax HEAD:

```
 File "jaxbug.py", line 5, in <module>
    t = serialization.msgpack_serialize(s)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/flax/serialization.py", line 334, in msgpack_serialize
    return msgpack.packb(pytree, default=_msgpack_ext_pack, strict_types=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/msgpack/__init__.py", line 38, in packb
    return Packer(**kwargs).pack(o)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "msgpack/_packer.pyx", line 294, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 300, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 297, in msgpack._cmsgpack.Packer.pack
  File "msgpack/_packer.pyx", line 291, in msgpack._cmsgpack.Packer._pack
TypeError: can not serialize 'Array' object
```

I guess the new global default `jax.Array` in ea930e1d8 might have caused the bug. Note that this serialization API can be called through `checkpoint.save` or any other relevant codes.

### What jax/jaxlib version are you using?

jax master (61398ff409bd1afc7fb96bf9f0b0c43444baca2b, any version since ea930e1d8)

### Which accelerator(s) are you using?

CPU

### Additional system info

macOS, Linux x86_64

### NVIDIA GPU info

N/A

**Comment by yashk2810** [comment]
Hi, can you open this bug in the flax repo? This is not a JAX bug.

**Comment by wookayin** [comment]
Thank you. I opened google/flax#2696.

But I'm not sure this is a flax bug either; this seems to be an issue of msgpack (which Google doesn't own). But can I ask for an explanation about [which changes](https://jax.readthedocs.io/en/latest/jax_array_migration.html) would make the new jax Array no longer serializable with msgpack?

**Comment by wookayin** [comment]
Yes --- my flax installation was somehow outdated and my apologies for having missed them. Flax was using a custom serializer and it's updated, can confirm flax 0.6.1+ works with no problems. Thank you.
