### ISSUE TITLE
Accessing an element in a DeviceArray is slow and adds significant compute time

### ISSUE THREAD

**Issue by kyrollosyanny** [google/jax#13572]
### Description

Hello, 

I am running into an issue where accessing elements in a jnp.array takes too long. Usually much longer than the computation itself. I have a feeling this is because of the lazy execution of jax DeviceArrays. I wonder if there is a way to speed this up. Here is an example below where accessing DeviceArray elements takes **13x** longer. 

``` 
x=jnp.ones((1000,1))
y=jnp.zeros((200))
def test(x,y):
    out=0
    for i in range(y.shape[0]):
        if i==1:
            out=out+x*y[i]
        elif i==2:
            out=out+x*y[i]*4.
        else: 
            out=out+x*y[i]*10.
        
    return out

%timeit test(x,y).block_until_ready()
33 ms ± 2.98 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

However, if I do not access y[i], it only takes 2.52 ms. 

```
x=jnp.ones((1000,1))
y=jnp.zeros((200))
def test(x,y):
    out=0
    for i in range(y.shape[0]):
        if i==1:
            out=out+x*i
        elif i==2:
            out=out+x*i*4.
        else: 
            out=out+x*i*10.
        
    return out
%timeit test(x,y).block_until_ready()
2.52 ms ± 267 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Is there a workaround for this? Thanks a lot. 

### What jax/jaxlib version are you using?

pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

### Which accelerator(s) are you using?

CPU

### Additional system info

Python V 3.10.6. WSL.

**Comment by jakevdp** [comment]
Hi - thanks for the question. This is working as expected: JAX is not optimized for speed of individual operations like array indexing, but rather optimized for speed of JIT-compiled sequences of operations. If you modify your timings to do this instead, you should see that the two approaches are quite similar in speed:
```python
jit_test = jax.jit(test)
_ = jit_test(x, y)  # trigger compilation

%timeit test(x,y).block_until_ready()
%timeit jit_test(x, y).block_until_ready()
```
You can read more about what kind of performance to expect from JAX in [FAQ: Is JAX Faster Than Numpy](https://jax.readthedocs.io/en/latest/faq.html#is-jax-faster-than-numpy).

**Comment by jakevdp** [comment]
Also, side-note, generally in JAX (as in numpy) for optimal performance it's best to avoid using `for` loops over array values, and instead use vectorized operations. I suspect you used loops here only for the sake of example, but I thought I'd add that just in case! For example, it would be better to write your first function as something like this, avoiding the for-loop:
```python
def test(x, y):
  return x * (10 * y[0] + y[1] + 4 * y[2] + 10 * y[3:].sum())
```

**Comment by kyrollosyanny** [comment]
That makes perfect sense. Thanks a lot for your help. 

Best,
