### ISSUE TITLE
Use tracing for program logging and benchmarking

### ISSUE THREAD

**Issue by alexbw** [google/jax#136]
JAX has a great tracer. Who says it can't be used to log information about the programs it traces? Useful applications:
 - Profiling speed
 - Profiling memory
 - Keeping a log of what ops were run
 - Gradient magnitudes
 - Activation magnitudes

**Comment by mattjj** [comment]
These ideas may be worth discussing, but they seem a bit under-baked for an issue, and some versions of them sound pretty far out of JAX’s scope.

**Comment by hawkinsp** [comment]
I'm going to close this issue, given it has sat peacefully undisturbed here for a long time. If we have concrete ideas on how to make progress, let's open new issues for them.
