### ISSUE TITLE
Program seems to hang after my first train_step() in the first epoch, not returning to the train_epoch()

### ISSUE THREAD

**Issue by elisejiuqizhang** [google/jax#13601]
### Description

I tried to adapt one implementation of LMU from pytorch to jax, and I'm putting my implementation [here](https://github.com/elisejiuqizhang/jax-lmu/blob/fab527a6523d03304ccf606495801d686599877a/src/jax_lmu_run_exp.py#L114). I wasn't currently getting any error message, but as I was debugging and going by each every step, I seemed to have noticed that at the first epoch/step, the train_step() function's return values was never entering the train_epoch() function, and the program just seemed to hang there... 

I'm new to jax and a fairly inexperienced programmer 😅  so I'm not certain if it might be an issue with jax or it's completely something on my side. 

Thanks for taking the time and would greatly appreciate any insights!

### What jax/jaxlib version are you using?

jax v0.3.25; jaxlib v0.3.25+cuda11.cudnn82

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9.15

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:02:00.0  On |                  N/A |
| 30%   49C    P0    97W / 350W |   1317MiB / 24258MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2295      G   /usr/lib/xorg/Xorg                150MiB |
|    0   N/A  N/A      9348      G   /usr/lib/xorg/Xorg                505MiB |
|    0   N/A  N/A      9495      G   /usr/bin/gnome-shell              157MiB |
|    0   N/A  N/A      9933      G   ...RendererForSitePerProcess      249MiB |
|    0   N/A  N/A     10700      G   /usr/lib/firefox/firefox          236MiB |
+-----------------------------------------------------------------------------+

**Comment by zhangqiaorjc** [comment]
Could you rule out any data pipeline issue? also you could just adding a much print statements, enable/disable jax.jit and print debug what's going wrong?
```
        # how about print batch?
        print('batch=', batch)
        state, metrics = train_step(state, batch)
        # maybe print here as well?
        print(jax.tree_map(lambda x: x.shape, state))
```

**Comment by elisejiuqizhang** [comment]
Thanks, will try that! (It could just be an issue on my side since I'm still quite new to it and trying to grab ahold
