### ISSUE TITLE
Pickling support

### ISSUE THREAD

**Issue by AbdealiJK** [google/jax#1362]
Following https://github.com/HIPS/autograd/issues/38

My understanding is that `autograd` wont have support for pickling.

So, i'm wondering what direction is `jax` planning on taking?
 - Supporting only some pickling methods which support everything jax does
 - Writing jax in a way so its compatible with cPickle (default python pickle)

There are various pros/cons of each - maintenance vs ubiquitousness etc.

I believe the only major hinderance in jax for python-pickling are:
 - Functions inside functions
 - Lambda functions

They can be easily avoided if the code is structured slightly differently in most (if not all) cases.

For my usecase, due to a bunch of constraints on our side, we cannot use libraries that don't support default python pickle (dill, cloudpickle, joblib, etc. are not solutions we can use).

**Comment by AbdealiJK** [comment]
Quick ping on this one - would appreciate some direction in what the thought here is

**Comment by skye** [comment]
Are you trying to pickle jax-transformed functions? Unfortunately we don't have any plans to support pickling functions produced via jax (and I'm not a pickle expert, but I don't think jax functions are so different from any other Python functions, except maybe for the C bindings). Out of curiosity, why do you need to pickle functions?

**Comment by AbdealiJK** [comment]
Packages that use autograd/jax's numpy functions and other functions may need to support pickling.
Specifically this comes from the `lifelines` package.

Here's a simpler example of the issue with pickling. The class uses

```python
import jax.numpy as np
# import numpy as np

class ExampleClass(object):
    def __init__(self):
        self.func = np.exp

cls = ExampleClass()
cls.func(2)

import pickle
_ = pickle.dumps(cls)
```

If I use `import numpy as np` it works fine.
With jax, it throws the error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-951dbdfe2c25> in <module>
      1 import pickle
----> 2 _ = pickle.dumps(cls)

AttributeError: Can't pickle local object '_one_to_one_unop.<locals>.<lambda>'
```

**Comment by skye** [comment]
Thanks for the example. This makes sense, but removing the use of lambdas and functions inside functions in jax's code base would be a massive effort (and impossible in some cases), and continuing to enforce that would slow down jax development, so unfortunately we can't reasonably support default Python pickling.
