### ISSUE TITLE
data type not understood on simple expression `np.exp([[[1.], [2.]]])`

### ISSUE THREAD

**Issue by brianwa84** [google/jax#1363]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-6d573a3a9d02> in <module>()
----> 1 np.exp([[[1.], [2.]]])

2 frames
/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in <lambda>(x)
    294 def _one_to_one_unop(numpy_fn, lax_fn, promote_like=False):
    295   if promote_like:
--> 296     fn = lambda x: lax_fn(lax.convert_element_type(x, _result_dtype(numpy_fn, x)))
    297   else:
    298     fn = lambda x: lax_fn(x)

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in _result_dtype(op, *args)
    214 def _result_dtype(op, *args):
    215   """Compute result dtype of applying op to arguments with given dtypes."""
--> 216   args = [onp.ones((0,) * ndim(arg), _dtype(arg)) for arg in args]
    217   return _dtype(op(*args))
    218 

/usr/local/lib/python3.6/dist-packages/jax/numpy/lax_numpy.py in <listcomp>(.0)
    214 def _result_dtype(op, *args):
    215   """Compute result dtype of applying op to arguments with given dtypes."""
--> 216   args = [onp.ones((0,) * ndim(arg), _dtype(arg)) for arg in args]
    217   return _dtype(op(*args))
    218 

TypeError: data type not understood

**Comment by mattjj** [comment]
Thanks for raising this.

We could improve the error message and docs here (PRs welcome!), but actually this is working-as-intended: we don't follow NumPy's convention of automatically converting lists and other (nested) sequence data types to arrays. It's mentioned in the [What's Supported](https://github.com/google/jax#whats-supported) section of the READme (see "Don't use: Implicit casting to arrays").

**Comment by brianwa84** [comment]
In that case, as you say, a more precise error message like "arg 0 is not a
DeviceArray" would be sensible.

Brian Patton | Software Engineer | bjp@google.com

**Comment by hawkinsp** [comment]
@jakevdp already fixed this!

```
In [10]: import jax.numpy as jnp

In [11]: jnp.exp([[[1.], [2.]]])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-1b163cd99599> in <module>
----> 1 jnp.exp([[[1.], [2.]]])

~/p/jax/jax/_src/numpy/lax_numpy.py in <lambda>(x)
    364 def _one_to_one_unop(numpy_fn, lax_fn, promote_to_inexact=False, lax_doc=False):
    365   if promote_to_inexact:
--> 366     fn = lambda x: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x))
    367   else:
    368     fn = lambda x: lax_fn(*_promote_args(numpy_fn.__name__, x))

~/p/jax/jax/_src/numpy/lax_numpy.py in _promote_args_inexact(fun_name, *args)
    327
    328   Promotes non-inexact types to an inexact type."""
--> 329   _check_arraylike(fun_name, *args)
    330   _check_no_float0s(fun_name, *args)
    331   return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))

~/p/jax/jax/_src/numpy/lax_numpy.py in _check_arraylike(fun_name, *args)
    303                     if not _arraylike(arg))
    304     msg = "{} requires ndarray or scalar arguments, got {} at position {}."
--> 305     raise TypeError(msg.format(fun_name, type(arg), pos))
    306
    307 def _check_no_float0s(fun_name, *args):

TypeError: exp requires ndarray or scalar arguments, got <class 'list'> at position 0.
```
