### ISSUE TITLE
nan from the example notebooks if set param_scale to 0.1

### ISSUE THREAD

**Issue by xysun** [google/jax#1365]
The [neural network and data loading with pytorch](https://colab.research.google.com/github/google/jax/blob/master/notebooks/neural_network_and_data_loading.ipynb) example notebook is a bit confusing in the sense that: 

- `param_scale` is defined to be 0.1 but is never used (it was never passed into the `random_layer_params` function, as a result `scale` there is always of default value 1e-2)
- If one actually use this `param_scale` of value 0.1, the training will actually return nan errors. 

I couldn't figure out the root cause of those nans but I suspect it's some numerical instability issue, maybe related to #475. 

I would suggest to remove the separate declaration of `param_scale` from the notebook. 

Also if anyone can point me in the right direction of debugging the nans from a large init value I'm more than happy to dig deeper.

**Comment by jakevdp** [comment]
This appears to have been fixed in https://github.com/google/jax/pull/8195
