### ISSUE TITLE
Feature request: nondifferentiable_argnums for jax.custom_gradient

### ISSUE THREAD

**Issue by schmrlng** [google/jax#1366]
Is there a way to define `jax.custom_gradient`s for functions that take non-differentiable (i.e., not valid Jax type) arguments? That is, it would be nice if I could write something like
```python
@jax.custom_gradient
def f(func, x, y):
  output, f_vjp = jax.vjp(func, x, y)
  return output, lambda g: (None,) + tuple(2 * p for p in f_vjp(g))  # double the correct grads

f(np.multiply, 2., 3.)  # TypeError: <type 'function'> is not a valid Jax type
jax.grad(f, argnums=(1, 2))(np.multiply, 2., 3.)  # TypeError: <type 'function'> is not a valid Jax type
```
Currently something like this works:
```python
def make_f_with_custom_gradient(func):

  @jax.custom_gradient
  def f(x, y):
    output, f_vjp = jax.vjp(func, x, y)
    return output, lambda g: tuple(2 * p for p in f_vjp(g))  # double the correct grads

  return f

jax.grad(make_f_with_custom_gradient(np.multiply), argnums=(0, 1))(2., 3.)  # (DeviceArray(6.), DeviceArray(4.))
```
but this doesn't have quite the same semantics as the version above.

A third option that doesn't work (related to the "wrapper trick" discussed here https://github.com/google/jax/issues/1338#issuecomment-531980071):
```python
def f(func, x, y):
  output, f_vjp = jax.vjp(func, x, y)

  @jax.custom_gradient
  def _f(x, y):
    return output, lambda g: tuple(2 * p for p in f_vjp(g))  # double the correct grads
  
  return _f(x, y)

f(np.multiply, 2., 3.)  # DeviceArray(6.)
jax.grad(lambda x, y: f(np.multiply, x, y), argnums=(0, 1))(2., 3.)  # NotImplementedError: Forward-mode differentiation rule for 'primal_fun_lin' not implemented
```

Notably `jax.jit` takes a `static_argnums` argument; would something like `nondifferentiable_argnums` make sense for `jax.custom_gradient`?

**Comment by mattjj** [comment]
#2026 fixed this. It changed the API for custom derivative rules, and added a `nondiff_argnums` option in there somewhere. Check out [the tutorial notebook](https://github.com/google/jax/blob/master/docs/notebooks/Custom_derivative_rules_for_Python_code.ipynb).
