### ISSUE TITLE
Support dynamic shapes in the lowering and compilation paths when jax.Array is enabled

### ISSUE THREAD

**Issue by yashk2810** [google/jax#13671]

**Comment by langka** [comment]
Hi. I'd like to know the solution for this issue;
`
#coding=utf-8
import jax
from jax import nn
import jax.numpy as jnp

def mul(x):
  return x * x

jit_f = jax.jit(mul)

a = jnp.asarray([0.,0.,0.])
b = jnp.asarray([0.,0.,0., 0.])

print(jit_f.lower(a).compiler_ir('mhlo'))
print(jit_f.lower(b).compiler_ir('mhlo'))
`
They output different mhlo ir with static shapes (tensor<3xf32> / tensor<4xf32>), while my expected shape is tensor<?xf32>;  
Can any one show me the right way to emit dynamic-shaped IR?
