### ISSUE TITLE
np.prod does not work with jacfwd

### ISSUE THREAD

**Issue by lonelykid** [google/jax#1370]
This example illustrate this issue. 
np.prod works with jacrev but not with jacfwd. Both work and give the same result when explicitly code the multiplication.
````
def func(x):
  x = x.reshape((2,3))
  a = np.array([[2.,2.,2.],[3.,3.,3.]])
  o = np.exp(-(a-x)**2)
#   o = o[:,0] * o[:,1] * o[:,2]
  o = np.prod(o,axis=1).flatten()
  return o
jrfunc = jacrev(func)
jffunc = jacfwd(func)
````
I'm testing this in colab. The built-in version appears to be 0.1.44

**Comment by hawkinsp** [comment]
This seems to work with `jax` version 0.1.46, so I'm guessing whatever the  issue was has already been fixed.

You can upgrade your `jax` release in colab by  running  `pip install --upgrade jax`  in a cell.

Hope  that helps!
