### ISSUE TITLE
pjrt_compiler.cc:Compile is unconditionally transpiling MLIR->HLO

### ISSUE THREAD

**Issue by stellaraccident** [google/jax#13722]
### Description

This code in pjrt_ifrt/pjrt_compiler.cc seems suspect:

```
StatusOr<std::unique_ptr<LoadedExecutable>> PjRtCompiler::Compile(
    mlir::ModuleOp mlir_module, CompileOptions options) {
  DCHECK(this);
  XlaComputation xla_computation;
  TF_RETURN_IF_ERROR(MlirToXlaComputation(
      mlir_module, xla_computation,
      /*use_tuple_args=*/options.parameter_is_tupled_arguments,
      /*return_tuple=*/false));
  return PjRtLoadedExecutable::Create(client_, xla_computation,
                                      std::move(options));
}
```

I am attempting to use the new C plugin API to plugin an MLIR based compiler, and this is really unfortunate. It seems like there should be a way for the PJRT plugin to advertise what program format it accepts vs just getting whatever happens to come down. It looks like this code is in a high degree of flux, so I'm sure I'm missing a subtlety of the layering.

It would be great if this part of the project had more publicly visible discussion or design docs.

### What jax/jaxlib version are you using?

HEAD

**Comment by hawkinsp** [comment]
It probably started doing this after https://github.com/openxla/xla/commit/48c75881737e5872ec29b0f48a247d2a13b86e9d . Will look into it.

**Comment by stellaraccident** [comment]
Indeed, turning that flag back to false results in MLIR bytecode making it all the way to the backend. (been poking around for a bit and I can't see a load bearing reason why it has to be the way it is -- looks to just be not done yet?)

**Comment by hawkinsp** [comment]
There's no good reason for it. I should have a fix for you in the next few days.

**Comment by stellaraccident** [comment]
> I'm going to remove the opt-out tomorrow (I want to get it in before the holidays) but you can just avoid syncing until I land the fix.

No problem - I'll hang out at this commit for a bit.

**Comment by hawkinsp** [comment]
We fixed this a long time back. IFRT only ever deals with MLIR modules these days. The code highlighted in the first comment is long deleted.
