### ISSUE TITLE
Outside Call is not Eliminated

### ISSUE THREAD

**Issue by daskol** [google/jax#13762]
### Description

It seems that dead call of `host_callback.call` is not eliminated. Consider the piece of code below which is actually `flax` module. It calls a py-function `phase_boundary` which returns a 1D array of shape `2` and assigns it to class instance members with pattern matching. The issue is that these variables (`self.varw` and `self.varb`) are not used anywhere further but the execution time is faster without calling the host callback.

```python
import jax
import flax.linen as nn

class CNN(nn.Module):

    depth: int = 16

    def setup(self):
        self.varw, self.varb = jax.experimental.host_callback.call(
            callback_func=phase_boundary,
            arg=1 / self.depth,
            result_shape=jax.ShapeDtypeStruct((2, ), jnp.float32))

        self.head = nn.Dense(features=10)

    def __call__(self xs: jax.Array) -> jax.Array:
        # Expecting `xs` shape to be (?, 28, 28, C).
        return xs.mean(axis=(1, 2))
```

A quick use of  `jaxpr` shows that outside call produces two dangling variables `e` and `f` which are not eliminated.

```python
>>> jax.make_jaxpr(model.apply)({...}, jnp.empty((5, 28, 28, 1)))
{ lambda ; a:f32[10] b:f32[1,10] c:f32[5,28,28,1]. let
    d:f32[2] = outside_call[
      arg_treedef=PyTreeDef(*)
      callback=<jax.experimental.host_callback._CallbackWrapper object at 0x7fac61f092d0>
      flat_results_aval=(ShapedArray(float32[2]),)
      identity=False
      result_treedef=PyTreeDef(*)
    ] 0.0625
    e:f32[1] = slice[limit_indices=(1,) start_indices=(0,) strides=(1,)] d
    _:f32[] = squeeze[dimensions=(0,)] e
    f:f32[1] = slice[limit_indices=(2,) start_indices=(1,) strides=(1,)] d
    _:f32[] = squeeze[dimensions=(0,)] f
    g:f32[5,1] = reduce_sum[axes=(1, 2)] c
    h:f32[5,1] = div g 784.0
    i:f32[5,10] = dot_general[
      dimension_numbers=(((1,), (0,)), ((), ()))
      precision=None
      preferred_element_type=None
    ] h b
    j:f32[1,10] = reshape[dimensions=None new_sizes=(1, 10)] a
    k:f32[5,10] = add i j
  in (k,) }
```

I am not sure whether I should submit an issue here or to `flax` (please see a related issue google/flax#2750). Is there any straightforward workaround?

### What jax/jaxlib version are you using?

jax v0.4.1 jaxlib v0.4.1 flax v0.63

### Which accelerator(s) are you using?

GPU

### Additional system info

Python v3.10 Linux v5.4 CUDA v11.4 CUDNN v8.2.4.15

### NVIDIA GPU info

Used GPU is Nvidia Tesla V100-SXM2 16GB.

Packages `jax`, `jaxlib` were installed as
```shell
pip3.10 install --no-cache-dir \
    -f "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html" \
    "jax[cuda11_cudnn82]"
```

**Comment by mattjj** [comment]
Thanks for raising this!

If I understand correctly (though @sharadmv should correct any mistakes I make), we can't eliminate `host_callback.call`s, even when the outputs are unused, because the callback may be side-effecting.

But we may be in luck: we're in the process of deprecating `host_callback` in favor of new callback APIs, which in particular are more clear about when they should be used. For example, there's [`jax.pure_callback`](https://jax.readthedocs.io/en/latest/_autosummary/jax.pure_callback.html) (see also [here](https://jax.readthedocs.io/en/latest/notebooks/external_callbacks.html)), where because the callback is promised to be functionally pure (and in particular isn't side-effecting), we know it can be safely dead-code eliminated if its outputs aren't used.

Is `phase_boundary` side-effecting, or pure? If it's pure, then perhaps you can use `jax.pure_callback`. If it's side-effecting, is there some other reason it would be safe to eliminate?

**Comment by daskol** [comment]
There is no side-effects in the sense of IO but it calls py-function `scipy.integrate.quad` for adaptive integration (not sure about `/dev/urandom` in QUADPACK). I replaced `jax.experimental.host_callback.call` with `jax.pure_callback` (@mattjj thank you!). It works perfectly fine and there is no slow down whatsoever! However, I found that `pure_callback` is not eliminated as well (please, see below).
```python
>>> jax.make_jaxpr(model.apply)({...}, jnp.empty((5, 28, 28, 1)))
{ lambda ; a:f32[10] b:f32[1,10] c:f32[5,28,28,1]. let
    d:f32[2] = pure_callback[
      callback=<function pure_callback.<locals>._flat_callback at 0x7f6d787a77f0>
      result_avals=(ShapedArray(float32[2]),)
      vectorized=False
    ] 0.0625
    e:f32[1] = slice[limit_indices=(1,) start_indices=(0,) strides=(1,)] d
    _:f32[] = squeeze[dimensions=(0,)] e
    f:f32[1] = slice[limit_indices=(2,) start_indices=(1,) strides=(1,)] d
    _:f32[] = squeeze[dimensions=(0,)] f
    g:f32[5,1] = reduce_sum[axes=(1, 2)] c
    h:f32[5,1] = div g 784.0
    i:f32[5,10] = dot_general[
      dimension_numbers=(((1,), (0,)), ((), ()))
      precision=None
      preferred_element_type=None
    ] h b
    j:f32[1,10] = reshape[dimensions=None new_sizes=(1, 10)] a
    k:f32[5,10] = add i j
  in (k,) }
```
Am I right that the difference between `host_callback` and `pure_callback` is that the latter memoizes the results of the execution? How large is result cache in `pure_callback`?

**Comment by mattjj** [comment]
`pure_callback` won't memoize results. But I think now the issue may be just in how we're inspecting the computation: `make_jaxpr` doesn't apply dead-code elimination, but XLA will. (Actually, JAX itself also [does](https://github.com/google/jax/blob/57840dd9167a2e3289144d3219d1eadb80ef8eb0/jax/_src/dispatch.py#L463) some [DCE](https://github.com/google/jax/blob/57840dd9167a2e3289144d3219d1eadb80ef8eb0/jax/_src/dispatch.py#L597) before lowering to XLA, but `make_jaxpr` doesn't show that.)

I can think of three ways to verify it's being eliminated, and hence the callback is never called:
1. put a print statement in your callback;
2. inspect the optimized XLA HLO to see what's really going to be compiled and executed;
3. manually apply JAX's internal DCE pass to the result of `make_jaxpr`.

I recommend doing the first. But here's how to do all three:

```python
import jax

def callback(x):
  print('called!')
  return x

@jax.jit
def f(x):
  _ = jax.pure_callback(callback, x, result_shape=x)
  return x

f(3.)  # method 1, no print!

print(f.lower(3.).compile().as_text())  # no callback in optimized computation!
# HloModule jit_f, entry_computation_layout={(f32[])->f32[]}, allow_spmd_sharding_propagation_to_output=true
#  
# ENTRY %main.2 (Arg_0.1: f32[]) -> f32[] {
#   %Arg_0.1 = f32[] parameter(0), sharding={replicated}
#   ROOT %copy = f32[] copy(f32[] %Arg_0.1)
# }

from jax.interpreters import partial_eval as pe
jaxpr = jax.make_jaxpr(f)(3.)
jaxpr, _, _ = pe.dce_jaxpr_consts(jaxpr.jaxpr, [True])
print(jaxpr)  # after JAX's DCE (before any XLA DCE), no callback!
{ lambda ; a:f32[]. let
    b:f32[] = xla_call[call_jaxpr={ lambda ; c:f32[]. let  in (c,) } name=f] a
  in (b,) }
```

WDYT?

**Comment by mattjj** [comment]
If we replace `jax.pure_callback` with `hcb.call` (where we did `from jax.experimental import host_callback as hcb`) then all three methods show the call is not eliminated.

**Comment by mattjj** [comment]
IIUC this issue is resolved, since `pure_callback` is indeed removed when dead, while `host_callback` can't be removed in general. Let me know if I'm mistaken and there's still some outstanding issue here!

**Comment by daskol** [comment]
@mattjj You are absolutely right. Pure callback works perfectly. There is no visible performance degradation despite that the call is possibly not eliminated. Thank you for your time and explanation.

**Comment by mattjj** [comment]
That's great! (And to be clear I'm pretty sure the call is eliminated!)

Good luck with your work.
