### ISSUE TITLE
Full support for pluggable PJRT backends

### ISSUE THREAD

**Issue by stellaraccident** [google/jax#13765]
I've landed a first version of a dynamically loaded IREE PJRT plugin (https://github.com/iree-org/iree-samples/pull/81). The code is in our samples repo here, along with notes on how to reproduce:
  https://github.com/iree-org/iree-samples/tree/main/pjrt-plugin 

It will stay there until ready to raise a real RFC in the new year.

There's been a private-to-Google chat for getting it to this point, but I think this is a good checkpoint to bring that and the related artifacts public so we can collaborate on finishing this (since these are all OSS projects). Any objections?

I've got a number of next steps on the functionality side to get this all good:

* Create plugins for more backends and make them more configurable (i.e. even the CPU backend can shard devices based on NUMA nodes, etc -- but this requires configuration).
* Derive device tuning compile flags from querying the runtime for the actual connected devices (vs just compiler defaults).
* Implement async invoke and h2d/d2h transfers (the sync APIs are harder to get wrong and easy so just did that first but obviously not a real solution).
* Enable the CUDA backend and Tracy for local profiling (both of which are missing Bazel build support in IREE :( ).
* Package this up so it can be pip installed (presumably that will also be implicated in plugin discovery?)

It'd be great to work in tandem on getting the plugin infra itself to a level of completion so that I can run the test suite without hacking Jax internals or doing custom builds.

**Comment by stellaraccident** [comment]
Note also that I took some liberties on adding some layering with respect to platforms and types of plugins (and configuration). While most folks can't see this, I expect this will let us instantiate the plugins in the internal Google static builds of Jax, and that is different enough that I just implemented the things that would be necessary to wire that up later.

**Comment by stellaraccident** [comment]
FYI - if justification to further clean up the C API deps is needed, here is an abbreviated bloaty report of the IREE CPU plugin:

```
    FILE SIZE        VM SIZE
 --------------  --------------
  53.9%  13.7Mi  54.7%  1.15Mi    protobuf
  28.1%  7.14Mi  22.6%   486Ki    tensorflow
  12.2%  3.09Mi  16.6%   357Ki    iree
   4.5%  1.14Mi   3.0%  64.2Ki    absl
   0.4%   114Ki   1.1%  23.2Ki    cpuinfo
```

Afaict, this is coming from the need to interop with the XlaShape proto and use a couple of utilities for constructing layouts. Although some of it may be coming from things coming in transitively from the way the C API depends on the TPU support library (which results in a bunch of static initializers, I think). Without all of that, the size would roughly be the combination of the iree and cpuinfo row.

Note that the "iree" row includes the compiler interface and the CPU runtime but not the compiler (which is installed separately).

**Comment by stellaraccident** [comment]
And for the CUDA plugin:

```
    FILE SIZE        VM SIZE
 --------------  --------------
  55.3%  13.7Mi  57.9%  1.16Mi    protobuf
  28.8%  7.14Mi  23.8%   486Ki    tensorflow
  10.4%  2.58Mi  13.2%   269Ki    iree
   4.6%  1.14Mi   3.1%  64.1Ki    absl
```

**Comment by hawkinsp** [comment]
I think we can declare this issue fixed. We're now ourselves shipping:
* XLA/CUDA GPU via a plugin (on PyPi)
* Google TPU
and we welcome more! (AMD/ROCM?)
