### ISSUE TITLE
jax.numpy.float_power doesn't promote dtype as specified

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#13839]
### Description

```python
import jax.numpy as jnp
x = jnp.ones(1)
jnp.float_power(x, x).dtype  # float32!
```
Violates the documented behaviour: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.float_power.html:
> This differs from the power function in that integers, float16, and float32 are promoted to floats with a minimum precision of float64 so that the result is always inexact.

**Comment by jakevdp** [comment]
Sorry for the confusion: that part of the docstring is describing numpy's behavior, not JAX's behavior (look for *original docstring below*). JAX specifically avoids promotion to float64 in many places where numpy does so, so I think this is working as intended. But the documentation should probably be updated to reflect this – are you interested in sending a fix?

**Comment by NeilGirdhar** [comment]
I'll just close this.  It's not too important to me.  I just thought it was weird 😄

**Comment by NeilGirdhar** [comment]
Also, just curious, but when you implement the Array API, will you be ditching the functions (like `float_power`) that aren't part of it?  (I'm happy just sticking to the Array API interface.)

**Comment by jakevdp** [comment]
I'm not sure what you mean by Array API, but the `jax.numpy` interface is designed to match what is in `numpy`. So we probably wouldn't deprecate/remove any functionality unless it were deprecated/removed in NumPy itself.

**Comment by NeilGirdhar** [comment]
@jakevdp I mean this: https://data-apis.org/array-api/latest/.  Numpy added `numpy.array_api`, so I assumed that Jax would eventually follow suit?  This would allow library code to be written in a way that supports all libraries that implement the Array API.  For example, my efax library would support jax, numpy, pytorch, etc.

**Comment by jakevdp** [comment]
Oh, right, I've seen the discussions around that in the NumPy forums. I don't know of any concrete plans to implement that in JAX at the moment, but it looks like it would make sense.

**Comment by NeilGirdhar** [comment]
> Though it's pretty clear that JAX can't support the entirety of the Array API as currently proposed: for example, it allows for mutation of data buffers, which is not possible in JAX.

I don't totally understand what they promise.  They did discuss Jax here: https://data-apis.org/array-api/latest/design_topics/copies_views_and_mutation.html.

**Comment by jakevdp** [comment]
Oh, I was just referring to the fact that `__setitem__` is listed as part of the supported operations in the Array API. This is a mutating operation that JAX can't support.

**Comment by NeilGirdhar** [comment]
> Oh, I was just referring to the fact that __setitem__ is listed as one of the operations in the Array API. This is a mutating operation that JAX can't support.

I understand, but this is discussed in the linked thread.  Stephen had some ideas on how to make it work in this comment: https://github.com/data-apis/array-api/issues/24#issuecomment-682092006

**Comment by jakevdp** [comment]
I see, thanks for the link. In my mind it would be clearer to just have attempted mutation raise an error as JAX currently does.

In any case, I'll reiterate that I don't know of any concrete efforts to add Array API compatiblity to JAX, and even if we were to do that some day, I doubt we'd drop existing functionality in the `jax.numpy` interface (just as I doubt numpy itself would ever deprecate or remove those legacy APIs)

**Comment by NeilGirdhar** [comment]
Right, that makes sense!
