### ISSUE TITLE
forward-mode eigh derivatives return NaN's

### ISSUE THREAD

**Issue by adabbott** [google/jax#1383]
First off, thanks for developing JAX, it's awesome!

I recently noticed that when one computes higher order derivatives of expressions involving eigenvectors obtained from `jax.numpy.eigh` or `jax.scipy.eigh`, NaNs are returned. However, it only appears to be a problem with forward-mode autodiff. This is unfortunate, since forward-mode tends to be more efficient for higher order derivatives.

A minimal example:
```python
import jax
import jax.numpy as np

# Create a random symmetric matrix
seed = jax.random.PRNGKey(0)
tmp = jax.random.uniform(seed, (2,2))
a = np.dot(tmp, tmp.T)

def test(inp):
    val, vec = np.linalg.eigh(inp)
    return np.dot(np.dot(vec, inp), vec.T)

def test_deriv(func, inp):
    grad_func = jax.jacfwd(func)
    hess_func = jax.jacfwd(grad_func)
    cube_func = jax.jacfwd(hess_func) # This derivative returns NaN, but jax.jacrev works!
    print(grad_func(inp))
    print(hess_func(inp))
    print(cube_func(inp))

test_deriv(test, a)
```

Additional notes:
- Expressions involving eigenvalues do not appear to have this issue
- Any array contractions involving eigenvectors and other arrays (`dot`, `einsum`, etc) also exhibit similar behavior: `jacfwd` fails, while `jacrev` works.
- I'm using CPU
- JAX version 0.1.46

Thanks for your time!

**Comment by hawkinsp** [comment]
The first NaN in the computation appears to come from the forward-mode derivative of `pow` where the LHS is negative:
`jax.jvp(lax.pow, (-1.5, 2.), (0., 0.))`

This in turn comes from the `y ** 2` term in the RHS JVP for `div`.
