### ISSUE TITLE
`jax.lax.integer_pow` is not `jit` compilable. 

### ISSUE THREAD

**Issue by Jordan-Dennis** [google/jax#13838]
### Description

Hi the JAX team,
here is a minimal working example demonstrating the title. 
```python 
import jax

x: float = jax.numpy.arange(100, dtype=float)
y: int = 4

jax.make_jaxpr(jax.lax.integer_pow)(x, y)
```
On my machine this produces the error. 
```python 
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    jax.make_jaxpr(jax.lax.integer_pow)(x, y)
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[], weak_type=True
)>with<DynamicJaxprTrace(level=1/0)>
The problem arose with the `bool` function. 

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```
Thanks in advance 
Jordan

### What jax/jaxlib version are you using?

jax 0.4.1 and jaxlib 0.4.1

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux (Ubuntu 22.04)

**Comment by soraros** [comment]
It is `jit`-compatible. It's just that the exponent has to be static.
```python
jax.make_jaxpr(lax.integer_pow, static_argnums=(1,))(x, y)
```

**Comment by Jordan-Dennis** [comment]
Sorry, I forgot to specify that I am using it in a case where this is not a useful possibility (y is looped over). I assume that this is not a bug in that case and have closed the issue.
