### ISSUE TITLE
AttributeError: _src when importing jax

### ISSUE THREAD

**Issue by marcdelabarrera** [google/jax#13857]
### Description

I'm trying to use `jax` in a brand new virtual environment. I have `jax 0.4.1` and `jaxlib 0.4.1` .

When I try to import jax. 

```
File ~/git_supply/monopsonistic_nk/code/quantitative_model/venv/lib/python3.9/site-packages/jax/__init__.py:162
    158 from jax import util as util
    160 import jax.lib  # TODO(phawkins): remove this export.
--> 162 del jax._src

AttributeError: _src
```

If I comment this line in the `__init__` file then everything works fine. 

### What jax/jaxlib version are you using?

0.4.1

### Additional system info

Linux

**Comment by jakevdp** [comment]
Thanks for the report – this is a very strange error and I'm not sure what might be causing it. Can you say more about what exactly you are executing, and how you created your environment?

**Comment by pnsvk** [comment]
I faced this issue too, when I tried to install the package from within IPython console.. but went off, when restarted the py-kernel.

**Comment by jakevdp** [comment]
Thanks for the info. I've been able to reproduce the issue this way:
```python
In [1]: import jax

In [2]: import importlib

In [3]: importlib.reload(jax)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)

File ~/github/google/jax/jax/__init__.py:166
    162 from jax import util as util
    164 import jax.lib  # TODO(phawkins): remove this export.
--> 166 del jax._src

AttributeError: _src
```
also like this:
```python
In [1]: import jax
imp
In [2]: import sys

In [3]: del sys.modules['jax']

In [4]: import jax
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In [4], line 1
----> 1 import jax

File ~/github/google/jax/jax/__init__.py:166
    162 from jax import util as util
    164 import jax.lib  # TODO(phawkins): remove this export.
--> 166 del jax._src

AttributeError: _src
```
I suspect you were somehow reloading / re-importing JAX, which led to this error.

Still, it would probably be better to proactively prevent this, although I suspect reloading the library in an active runtime could probably lead to other issues as well (for example, objects that are assumed to be singletons may no longer pass the `is` check, etc.)

**Comment by apaszke** [comment]
Yeah, maybe it would be a good idea to handle that situation by raising a more informative error message? It might be safer to pass on this given that it's not a standard use case and would require some careful thinking from us

**Comment by jakevdp** [comment]
I would propose for now we do something like this:
```python
if hasattr(jax, '_src'):
  del jax._src
else:
  import warnings
  warnings.warn("The jax module appears to have been reloaded within the python process, either with reload_module() "
                "or the %autoreload extension. Be aware that this can cause unintended side-effects.")
```

**Comment by apaszke** [comment]
Looks very reasonable to me!

**Comment by jakevdp** [comment]
Sounds great - thanks! I'll send you a PR to review.
