### ISSUE TITLE
Bazel build: Read timed out  OR unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by eylenth** [google/jax#13856]
### Description

Hi

I try to install jax with the following command on my linux server (RHEL7.9 - With GPU cards)
```bash
python build/build.py ...
```
inside that build process it is generating the following sub-buildcommand:
```bash
./bazel-5.1.1-linux-x86_64 --output_user_root=/opt/build/jax/0.3.14/foss-2020b-CUDA-11.4.1/tmpgw78e5ny-bazel run --verbose_failures=true --jobs=64 --subcommands --action_env=PYTHONPATH --action_env=EBPYTHONPREFIXES --copt=-O2 --copt=-ftree-vectorize --copt=-march=native --copt=-fno-math-errno --config=mkl_open_source_only --config=cuda --config=nonccl :build_wheel -- --output_path=/opt/build/jax/0.3.14/foss-2020b-CUDA-11.4.1/jax-jaxlib-v0.3.14/dist --cpu=x86_64
```
But when the sub-buildcommand is performed, I'm getting the following error messages:
```bash
Error in download: java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz] to /opt/build/jax/0.3.14/foss-2020b-CUDA-11.4.1/tmpgw78e5ny-bazel/e78bb3ad1496d64288efaf8ecbb01eb1/external/go_sdk/go_sdk.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`
```

I already tried to add the correct cacerts file inside the bazel-5.1.1-linux-x86_64 command with the following parameter: `--server_javabase=/opt/software/Java/11.0.2`
But then I'm getting the following error message:
```bash
Error in download: java.io.IOException: Error downloading [https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz] to /opt/build/jax/0.3.14/foss-2020b-CUDA-11.4.1/tmp999kd5zh-bazel/e78bb3ad1496d64288efaf8ecbb01eb1/external/go_sdk/go_sdk.tar.gz: Read timed out
```

I have also tried to set the following parameter:
```bash
--host_jvm_args="-Dhttps.proxyHost=$PROXY_SERVER Dhttps.proxyPort=8080 -Dhttp.proxyHost=$PROXY_SERVER -Dhttp.proxyPort=8080"
```

but that didn't work either

Has anyone a clue how I can manipulate the build process of bazel so that the correct cacerts and/or proxy server can be found to download the packages inside the bazel build process ?

### What jax/jaxlib version are you using?
jax 0.3.14

### Which accelerator(s) are you using?
GPU
### Additional system info
Python 3.8.6

probably related with https://github.com/google/jax/issues/11304

**Comment by eylenth** [comment]
probably related with #11304

**Comment by hawkinsp** [comment]
I think this issue is likely obsolete. 0.3.14 was quite old.

Please reopen if you can still reproduce it with the current release of JAX!
