### ISSUE TITLE
Undefined Behaviour in jax_jit.cc with MSVC

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#13870]
### Description

In external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc, lines 808-810 are undefined behaviour with MSVC compiler and causes an error. Commenting out those lines solves this problem in the case (at the moment).

```
806 TF_ASSIGN_OR_RETURN(xla::DevicePutResult on_device,
807                        DevicePut(arg,
808 ifdef JAX_ENABLE_IFRT
809                                  arguments.ifrt_client,
810 endif
811                                  data_device, options));
```

### What jax/jaxlib version are you using?

Jaxlib v0.4.1

### Which accelerator(s) are you using?

GPU

### Additional system info

Windows 10, Python 3.9, Cuda 11.7, Cudnn 8.4.0

**Comment by apaszke** [comment]
Seems like those lines [have already been removed](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/jax_jit.cc#L796) so it should be ok? What was causing undefined behavior, I can't see anything wrong. Were the `#` characters missing?

**Comment by adam-hartshorne** [comment]
No, the # characters were there (they got cut off when copied/pasted across). It is putting a #ifdef ... #endif instead a function call like that isn't fully supported in MSVC, and thus caused a compiler error.

**Comment by mattjj** [comment]
As Adam pointed out, I think this is fixed at HEAD. Please reopen if I'm mistaken.
