### ISSUE TITLE
TPU file included in build even when tpu enabled set to false.

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#13871]
### Description

The following file ends up being involved in the build process even when TPU enabled is set to false,

external/org_tensorflow/tensorflow/compiler/xla/stream_executor/tpu/pjrt_api.cc

the problem with this that it contains an #include dlfcn.h, which doesn't exist in windows c++ and thus causes a build failure.

### What jax/jaxlib version are you using?

Jaxlib v0.4.1

### Which accelerator(s) are you using?

GPU

### Additional system info

Windows 10, Python 3.9, Cuda 11.7, Cudnn 8.4.0

**Comment by PhilipVinc** [comment]
bump. 
would be handy if this could be addressed...

**Comment by hawkinsp** [comment]
@PhilipVinc the original problem is now stale; that file no longer exists. Can you share what error you see at head?

**Comment by hawkinsp** [comment]
I'm pretty sure this issue is stale and the problem does not exist at head. We have a CI build for Windows CPU that succeeds at head.
