### ISSUE TITLE
Hand Vectorisation Gives Unexpected Poor Performance

### ISSUE THREAD

**Issue by Jordan-Dennis** [google/jax#13891]
### Description

Hi there The JAX Team,
thanks for your patience and support! I am finding inconsistent performance when I hand vectorize code. Here is a simple example writing alternatives to `np.hypot` for a very specific input shape of coordinates. 
```python
import jax 

def coords(n: int, rad: float) -> float:
    arange: float = jax.lax.iota(float, n)
    max_: float = np.array(n - 1, dtype=float)
    axes: float = arange * 2. * rad / max_ - rad
    
    s: int = axes.size
    shape: tuple = (1, s, s) 
    
    x: float = jax.lax.broadcast_in_dim(axes, shape, (2,))
    y: float = jax.lax.broadcast_in_dim(axes, shape, (1,))
    return jax.lax.concatenate([x, y], 0)

@jax.jit
def hypotenuse_v0(ccoords: float) -> float:
    return jax.lax.sqrt(jax.lax.integer_pow(ccoords, 2).sum(axis = 0))

@jax.jit
def hypotenuse_v1(ccoords: float) -> float:
    x: float = ccoords[0]
    y: float = ccoords[1]
    return np.hypot(x, y)

@jax.jit
def hypotenuse_v2(ccoords: float) -> float:
    x: float = jax.lax.index_in_dim(ccoords, 0)
    y: float = jax.lax.index_in_dim(ccoords, 1)
    x_sq: float = jax.lax.integer_pow(x, 2)
    y_sq: float = jax.lax.integer_pow(y, 2)
    return jax.lax.sqrt(x_sq + y_sq)

ccoords: float = coords(100, 1.)

%%timeit
hypotenuse_v0(ccoords)

%%timeit
hypotenuse_v1(ccoords)

%%timeit
hypotenuse_v2(ccoords)
```
On my device (:sigh: not those keywords) I get the following times 
![image](https://user-images.githubusercontent.com/93350879/210898306-f80d304c-fc31-47cd-8305-7a2b5dcb6471.png)
What's more, I can't seem to wrap my head around how the timing relates to the `jaxpr` representation. I was not expecting to be able to predict times perfectly, but I was expecting more complex `jaxpr`, with more visited instructions of similar size, to take longer, but this does not seem to be the case. Is there any merit in trying to "optimise" the `jaxpr` i.e. reduce the number of instructions. Obviously some instructions take more time than others, is there any way of knowing which instructions to avoid?

Regards

Jordan

### What jax/jaxlib version are you using?

jax 0.4.1 and jaxlib 0.4.1

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.8 Ubuntu 22.04

**Comment by Jordan-Dennis** [comment]
Sorry, the times I gave were for `1024` not `100`.

**Comment by jakevdp** [comment]
In general I wouldn't expect the length of a jaxpr to always be directly correlated with the runtime, for a couple reasons:

- individual primitives require widely varying numbers of flops. As an extreme example, `lax.linalg.svd` and `lax.neg` both lower to a single primitive, but will have vastly different runtimes as the size of the input increases.
- even if you're looking at operations with comparable runtimes, the jaxpr doesn't directly map onto the eventual operations done in the compiled code. In general the compiler is able to fuse, elide, and otherwise optimize sequences of operations, and this is not reflected in the jaxpr.

That said, it's hard to guess by looking at code (or jaxprs) exactly how fast it will execute, because it has to do with the details of the compiler and the execution engine. For example, when I run your benchmark on a GPU, I find the three approaches to be essentially indistinguishable in performance
```python
%timeit hypotenuse_v0(ccoords).block_until_ready()
# 161 µs ± 993 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit hypotenuse_v1(ccoords).block_until_ready()
# 161 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit hypotenuse_v2(ccoords).block_until_ready()
# 161 µs ± 1.19 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by Jordan-Dennis** [comment]
Thanks for the feedback on the `jaxpr`. I thought it translated a little more closely to the machine, but that matches the actual results I have been getting. I'll chalk this up as a machine problem and avoid vectorising code that I am only going to run locally. 

Thanks again,

Jordan

**Comment by jakevdp** [comment]
I should have added one thing: if you want to get a better idea of what the compiler is doing with your code, there are APIs for that. for example:
```python
print(jax.jit(hypotenuse_v2).lower(ccoords).compile().as_text())
```
```
HloModule jit_hypotenuse_v2, entry_computation_layout={(f32[2,1024,1024]{2,1,0})->f32[1,1024,1024]{2,1,0}}

%fused_computation (param_0.3: f32[2,1024,1024]) -> f32[1,1024,1024] {
  %param_0.3 = f32[2,1024,1024]{2,1,0} parameter(0)
  %slice.7 = f32[1,1024,1024]{2,1,0} slice(f32[2,1024,1024]{2,1,0} %param_0.3), slice={[0:1], [0:1024], [0:1024]}, metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/slice[start_indices=(0, 0, 0) limit_indices=(1, 1024, 1024) strides=(1, 1, 1)]" source_file="<ipython-input-7-a1c5658167c2>" source_line=28}
  %bitcast.16 = f32[1024,1024]{1,0} bitcast(f32[1,1024,1024]{2,1,0} %slice.7)
  %multiply.5 = f32[1024,1024]{1,0} multiply(f32[1024,1024]{1,0} %bitcast.16, f32[1024,1024]{1,0} %bitcast.16), metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/mul" source_file="<ipython-input-7-a1c5658167c2>" source_line=30}
  %slice.6 = f32[1,1024,1024]{2,1,0} slice(f32[2,1024,1024]{2,1,0} %param_0.3), slice={[1:2], [0:1024], [0:1024]}, metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/slice[start_indices=(1, 0, 0) limit_indices=(2, 1024, 1024) strides=(1, 1, 1)]" source_file="<ipython-input-7-a1c5658167c2>" source_line=29}
  %bitcast.15 = f32[1024,1024]{1,0} bitcast(f32[1,1024,1024]{2,1,0} %slice.6)
  %multiply.4 = f32[1024,1024]{1,0} multiply(f32[1024,1024]{1,0} %bitcast.15, f32[1024,1024]{1,0} %bitcast.15), metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/mul" source_file="<ipython-input-7-a1c5658167c2>" source_line=31}
  %add.2 = f32[1024,1024]{1,0} add(f32[1024,1024]{1,0} %multiply.5, f32[1024,1024]{1,0} %multiply.4), metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/add" source_file="<ipython-input-7-a1c5658167c2>" source_line=32}
  %sqrt.2 = f32[1024,1024]{1,0} sqrt(f32[1024,1024]{1,0} %add.2), metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/sqrt" source_file="<ipython-input-7-a1c5658167c2>" source_line=32}
  ROOT %bitcast.14 = f32[1,1024,1024]{2,1,0} bitcast(f32[1024,1024]{1,0} %sqrt.2), metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/sqrt" source_file="<ipython-input-7-a1c5658167c2>" source_line=32}
}

ENTRY %main.11 (Arg_0.1: f32[2,1024,1024]) -> f32[1,1024,1024] {
  %Arg_0.1 = f32[2,1024,1024]{2,1,0} parameter(0)
  ROOT %fusion = f32[1,1024,1024]{2,1,0} fusion(f32[2,1024,1024]{2,1,0} %Arg_0.1), kind=kLoop, calls=%fused_computation, metadata={op_name="jit(hypotenuse_v2)/jit(main)/jit(hypotenuse_v2)/sqrt" source_file="<ipython-input-7-a1c5658167c2>" source_line=32}
}
```
Raw HLO is definitely not the easiest thing to read, but this can help you get a better idea of the low level execution of your code.

**Comment by Jordan-Dennis** [comment]
Awesome thanks, 
I nearly asked how to view the assembly but this is probably better. Is HLO separate from `mlir` or is this `mlir` HLO (possibly a dumb question)?
Regards
Jordan

**Comment by jakevdp** [comment]
I believe that in the current version of JAX, this is MHLO, which is also used by MLIR, but @hawkinsp would know the details of that.
