### ISSUE TITLE
Broken link in readme. 

### ISSUE THREAD

**Issue by lockwo** [google/jax#13901]
### Description

The link in the readme under the current gotchas section is broken. "[Random numbers are different](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#random-numbers), but for [good reasons](https://github.com/google/jax/blob/main/docs/design_notes/prng.md). The 'google/jax' repository doesn't contain the 'docs/design_notes/prng.md' path in 'main'.

**Comment by mattjj** [comment]
Thanks for flagging this!

**Comment by lockwo** [comment]
Should be fixed with https://github.com/google/jax/pull/13902!

**Comment by mattjj** [comment]
Ah great, I was about to fix it, so thanks for pointing that out!
