### ISSUE TITLE
Should we register `str` as a pytree by default?

### ISSUE THREAD

**Issue by jakevdp** [google/jax#13914]
It occurred to me that it might be convenient if `str` were registered as a trivial pytree: the effect would essentially be that string arguments would effectively be marked static by default in JAX transformations.

here's how things work now:
```python
import jax

@jax.jit
def f(x, y, op):
  return x + y if op == 'add' else x * y

f(1, 2, 'add')
# TypeError: Argument 'add' of type <class 'str'> is not a valid JAX type.
```
The typical fix is to mark the argument static:
```python
from functools import partial
@partial(jit, static_argnames=['op'])
def f2(x, y, op):
  return x + y if op == 'add' else x * y

f2(1., 2., 'add')
# 3.0
```
But if we register string as a pytree, this explicit static marking is no longer required:
```python
jax.tree_util.register_pytree_node(
    str,
    lambda x: ((), x),
    lambda x, _: x
)

f(1., 2., 'add')
# 3.0
```
This might be a convenient enhancement for users, and I can't think of any major downside at the moment. What do you think?

**Comment by sharadmv** [comment]
One downside I can see is that it would be no longer explicit from the code that changing `op` triggers recompilation, whereas when it is marked as a `static_argname` it is immediately clear.

We'd have to additionally educate users that `str` arguments to `jax.jit` functions are specially treated as static.

**Comment by carlosgmartin** [comment]
I support this proposal.

```shell
$ python3 -c "import jax; print(jax.grad(lambda x: x['a'])({'a': 3., 'b': None}))"
{'a': Array(1., dtype=float32, weak_type=True), 'b': None}
$ python3 -c "import jax; print(jax.grad(lambda x: x['a'])({'a': 3., 'b': 'none'}))"
TypeError: Argument 'none' of type <class 'str'> is not a valid JAX type.
```

@sharadmv Personally, it seems obvious to me that strings would be treated as static.

If you think it might not be obvious, it could be noted explicitly in the docs.
