### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream

### ISSUE THREAD

**Issue by tcoates5** [google/jax#13951]
### Description

While using AlphaFold, jax threw the following error marked internal:

jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream 0x557b78e02e40: stream did not block host until done; was already in an error state

This appears to be the cause of a CUDA error that immediately followed. If this issue is not within jaxlib, I will promptly move this issue to the AlphaFold repo. I am more than happy to provide more information as requested

### What jax/jaxlib version are you using?

jax==0.3.25, jaxlib==0.3.25+cuda11.cudnn805

### Which accelerator(s) are you using?

GPU

### Additional system info

python 3.8, CUDA 11.1.1

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   37C    P0    38W / 300W |   2099MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     10603      C   python                            305MiB |
+-----------------------------------------------------------------------------+
As an important sidenote, this was run on the same hardware, but not within the docker environment used.

**Comment by nouiz** [comment]
Can you give us a way to reproduce this? Without that, we can't do anything.

**Comment by tcoates5** [comment]
Unfortunately, it seems that I cannot reproduce this either... Running it again seems to have worked, so unless someone gets something more consistent I think I should probably close this. Thank you for responding @nouiz!
