### ISSUE TITLE
`jax.scipy.linalg.solve_triangular` gives false result with GPU

### ISSUE THREAD

**Issue by dkn16** [google/jax#13979]
## Code 
```
import os
#os.environ['XLA_PYTHON_CLIENT_ALLOCATOR']='platform'
from jax.config import config
config.update("jax_enable_x64", True)
dim = 258
import jax
import jax.numpy as jnp
mat = jax.scipy.linalg.solve_triangular(jnp.ones((dim,dim,dim),dtype=jnp.float64),jnp.ones((dim,dim,4096),dtype=jnp.float64))
```

## Problem 
When dim>256, `mat` result is wrong. `mat[j]=DeviceArray([[1., 1., 1., ..., 1., 1., 1.],
             [1., 1., 1., ..., 1., 1., 1.],
             [1., 1., 1., ..., 1., 1., 1.],
             ...,
             [1., 1., 1., ..., 1., 1., 1.],
             [1., 1., 1., ..., 1., 1., 1.],
             [1., 1., 1., ..., 1., 1., 1.]], dtype=float64)` when `j>=255`, which is false. However, when `j<255`, the answer is correct.

When I set `XLA_PYTHON_CLIENT_ALLOCATOR` as `platform`, i got an error with the same code: when dim>258, i got
```
---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
[<ipython-input-2-ab58c9c414b1>](https://gb0t3qxh13u-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230110-060108-RC00_500940925#) in <module>
      7 import jax.numpy as jnp
----> 8 mat = jax.scipy.linalg.solve_triangular(jnp.ones((dim,dim,dim),dtype=jnp.float64),jnp.ones((dim,dim,4096),dtype=jnp.float64))

6 frames
UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream 0x28ebe80: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

XlaRuntimeError                           Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/jax/_src/scipy/linalg.py](https://gb0t3qxh13u-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab-20230110-060108-RC00_500940925#) in solve_triangular(***failed resolving arguments***)
    404                      debug: Any = None, check_finite: bool = True) -> Array:
    405   del overwrite_b, debug, check_finite  # unused
--> 406   return _solve_triangular(a, b, trans, lower, unit_diagonal)
    407 
    408 

XlaRuntimeError: INTERNAL: Failed to complete all kernels launched on stream 0x28ebe80: Could not synchronize CUDA stream: CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
```

This whole problem only happens with GPU. CPU does not have this problem.

A [Colab](https://colab.research.google.com/drive/1p8_Qj1DhOjQvnLTsrvH90n1ZUF_bvSZg?usp=sharing) is here, which reproduces the error. 

### What jax/jaxlib version are you using?

jax==0.4.1 jaxlib==0.4.1

### Which accelerator(s) are you using?

GPU

### Additional system info

Google Colab

### NVIDIA GPU info

```
Tesla V100
Tesla T4
```

**Comment by dkn16** [comment]
I tested fp32 and found fp32 has this problem too, but with a larger `dim` limit.

**Comment by mattjj** [comment]
Thanks so much for finding and analyzing this!

It looks like on CPU we call into LAPACK, but on GPU we call into the XLA HLO [`TriangularSolveOp`](https://github.com/google/jax/blob/8f538f95dcb56a68dbeb9fe9a44d90e82b3f0757/jax/_src/lax/linalg.py#L900). If I'm understanding that correctly, that means it could be a bug in XLA (or whatever library XLA is calling, since it looks like it CustomCalls a trsm routine).

@hawkinsp is this something you could quickly sort out?

**Comment by hawkinsp** [comment]
I looked into this (sorry for the delay) and the root cause is an integer overflow in XLA, for which I filed 
 https://github.com/openxla/xla/issues/6834.

**Comment by hawkinsp** [comment]
This is fixed at head in jaxlib (due to https://github.com/openxla/xla/pull/6871 ). Hope that helps!
