### ISSUE TITLE
Unexpected result when solving a spring-mass system

### ISSUE THREAD

**Issue by ayhteo** [google/jax#13975]
### Description

Would like to report a strange result when trying to implement a spring-mass solver using `jax.experimental.ode.odeint`.

```
import matplotlib.pyplot as plt
import jax.numpy as jnp
import jax.experimental.ode

def mass_spring_damper(arr, F=5.0, k=2.0, m=20.0, c=4.0):
    """
    arr is in the form of [x, \dot{x}]
    """
    return jnp.matmul(jnp.array([[0, 1.0], [-k / m, -c / m]]), arr.T) + jnp.array(
        [[0], [F / m]]
    )


time_array = jnp.linspace(0, 60.0, 1000, dtype=jnp.float64)
result = jax.experimental.ode.odeint(
    mass_spring_damper,
    jnp.array([[0.0, 0.0]]),
    t=time_array,
).squeeze(axis=1)

fig, ax = plt.subplots(1, 1)
plt.plot(time_array, result[:, 0], label="displacement", alpha=0.5)
plt.plot(time_array, result[:, 1], label="velocity", alpha=0.5, color="k")
plt.tight_layout()
```
![0a5d0577-2a72-4f26-829b-7c7be5afbb95](https://user-images.githubusercontent.com/32873190/211939705-1b732188-fa7d-4c46-a507-1d2630c42939.png)

The result above shows the displacement going to a large positive number which I thought would have been controlled by both the spring constant k and damper c.

Here is some working code using `scipy.integrate.odeint`: 

```
import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# Initialization
tstart = 0
tstop = 60
increment = 0.1
# Initial condition
x_init = [0, 0]
t = np.arange(tstart, tstop + 1, increment)
# Function that returns dx/dt
def mass_spring_damper(x, t):
    c = 4  # Damping constant
    k = 2  # Stiffness of the spring
    m = 20  # Mass
    F = 5
    dx1dt = x[1]
    dx2dt = (F - c * x[1] - k * x[0]) / m
    dxdt = [dx1dt, dx2dt]
    return dxdt


# Solve ODE
x = odeint(mass_spring_damper, x_init, t)
# Plot the Results
fig, ax = plt.subplots(1, 1)
ax.plot(t, x[:, 0])
ax.plot(t, x[:, 1])
ax.set(
    title="Simulation of Mass-Spring-Damper System",
    xlabel="time (s)",
    ylabel="displacement x(t)",
)
fig.tight_layout()
```
![0de086c8-04ce-44cf-90ba-9038027deb04](https://user-images.githubusercontent.com/32873190/211940755-fca2deed-81c5-4474-a052-f6e2285447b0.png)

### What jax/jaxlib version are you using?

jax v0.4.1

### Which accelerator(s) are you using?

CPU

### Additional system info

Apple silicone

**Comment by jakevdp** [comment]
It looks like `F` is always applied as a positive force - shouldn't it multiply the sign of the position in order to be a damping term?

**Comment by ayhteo** [comment]
The reason why I wrote it that way is because I thought the above would evaluate as the following :

$$
\left[\begin{array}{c} \dot{x} \\ \ddot{x} \end{array} \right]
= 
\left[ \begin{array}{cc}0 & 1 \\ -\frac{k}{m} & -\frac{c}{m} \end{array}  \right]
\left[\begin{array}{c} x \\ \dot{x} \end{array} \right] 
+
\left[\begin{array}{c} 0 \\ \frac{1}{m} \end{array} \right] F
$$

The intention would be that the force balance is evaluated as $\ddot{x} = -\frac{k}{m}x - \frac{c}{m}\dot{x} + \frac{F}{m} $

At some point, $kx$ would grow large enough that it counteracts the constant $F$. Is there some nuance in my implementation that is forcing $\frac{F}{m}$ to be additive at each time step?

**Comment by jakevdp** [comment]
Oh, thanks for the details. It's easier to see when it's written out like that

**Comment by jakevdp** [comment]
Is it a problem that your input has shape `(1, 2)` and you output has shape `(2, 1)`?

**Comment by ayhteo** [comment]
Yeah that's my bad. Have now corrected this so that inputs and outputs are (2,1). However the result appears to be the same.

```
import matplotlib.pyplot as plt
import jax.numpy as jnp
import jax.experimental.ode

def mass_spring_damper(arr, F=5.0, k=2.0, m=20.0, c=4.0):
    """
    arr is in the form of [x, \dot{x}]
    """
    return jnp.matmul(jnp.array([[0, 1.0], [-k / m, -c / m]]), arr) + jnp.array(
        [[0], [F / m]]
    )


time_array = jnp.linspace(0, 60.0, 1000, dtype=jnp.float64)
result = jax.experimental.ode.odeint(
    mass_spring_damper,
    jnp.array([[0.0], [0.0]]),
    t=time_array,
).squeeze(axis=-1)

fig, ax = plt.subplots(1, 1)
plt.plot(time_array, result[:, 0], label="displacement", alpha=0.5)
plt.plot(time_array, result[:, 1], label="velocity", alpha=0.5)
ax.set(xlabel="time (s)", title="Mass-Spring-Damper System")
plt.legend()
plt.tight_layout()
```
![c3e9ff88-8c67-45ab-b743-0a486b341b55](https://user-images.githubusercontent.com/32873190/212148133-7911f878-0b1f-4daa-ab93-f99aad2e6e2f.png)

**Comment by jakevdp** [comment]
I see the issue: the call signature for the function passed to odeint is `func(y, t, *args)`: https://github.com/google/jax/blob/f7c915e6a239b87b1e4f35710adb35014cdc940f/jax/experimental/ode.py#L153-L154

Your function signature is `func(y, F, *args)`. So you are integrating a function where the external force is increasing monotonically with time, which is enough to overcome the force of the spring trying to pull it back. If you define your function like this, I think it should work as expected:
```python
def mass_spring_damper(arr, t, F=5.0, k=2.0, m=20.0, c=4.0):
  ...
```

**Comment by ayhteo** [comment]
I see my mistake now, that's worked perfectly. I should read the docstrings in more detail, thanks so much for looking into this.

![6a934b51-ee65-4207-bbe3-108789c1f5cb](https://user-images.githubusercontent.com/32873190/212150751-fe274a21-4fa6-4130-86fe-9d092e790ab3.png)

**Comment by jakevdp** [comment]
Great, glad it's working!
