### ISSUE TITLE
`shaped_abstractify` is too permissive on its inputs

### ISSUE THREAD

**Issue by jakevdp** [google/jax#13976]
For example:
```python
>>> import numpy as np
>>> from jax._src.api_util import shaped_abstractify
>>> shaped_abstractify(np.dtype('float32'))
ShapedArray(float32[])
```
I don't think that a `float32` dtype should be interpreted as a scalar with dtype float32.

In general, anything that `np.result_type` converts to a dtype passes through without an appropriate error.

**Comment by dime10** [comment]
Maybe this is not the intention, but I've used it to abstractify Python scalar types as well before this patch. I think the `float` type can reasonable be interpreted as a scalar ShapedArray.
