### ISSUE TITLE
Typo in function `initial_step_size` in `jax/experimental/ode.py`

### ISSUE THREAD

**Issue by AlbertMitjans** [google/jax#13983]
### Description

The function `initial_step_size` is based from an algorithm in [this book](http://mezbanhabibi.ir/wp-content/uploads/2020/01/ordinary-differential-equations-vol.1.-Nonstiff-problems.pdf) (page 169). This is the algorithm:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/49232747/212095806-ce29dcd6-40f1-4bc1-af54-f567330c0acb.png">

In step `e`, we need to compute `max(d1, d2)`, but in the `initial_step_size` function you compute `max(d1 + d2)`.

### What jax/jaxlib version are you using?

jax v0.4.1, jaxlib v0.4.1

### Which accelerator(s) are you using?

CPU

**Comment by mattjj** [comment]
Thanks for noticing this and bringing it to our attention! Amazing!
