### ISSUE TITLE
Get a warning`jax.scipy.linalg.expm` produces nan values because `max_squarings` is not high enough

### ISSUE THREAD

**Issue by zaccharieramzi** [google/jax#13986]
Please:

- [ ] Check for duplicate requests.
- [ ] Describe your goal, and if possible provide a code snippet with a motivating example.

I would like to have a warning that tells me that I should consider increasing the value of `max_squarings` when `expm` outputs nan values. For example `Warning: expm outputs is nan because max_squarings was reached. Consider increasing max_squarings in order to solve this problem.`
I had this issue and did not realize that it was the cause of my problem (see [this](https://github.com/google/jax/issues/13985)).

Typically this would be useful in this example:
```python
import jax
import jax.numpy as jnp
from jax.scipy.linalg import expm as jexpm

dimension_x = 10
t = 1e6


# the jax way
sqrt_H = jax.random.normal(jax.random.PRNGKey(1), (dimension_x, dimension_x))
H = jnp.dot(sqrt_H, sqrt_H.T)
print(jexpm(-t*H))
```

**Comment by froystig** [comment]
This would indeed be a nice enhancement, but warnings are side effects, and won't be captured by JAX's transformations—compilation in particular. The function `jax.scipy.linalg.expm` is itself [`jax.jit`-compiled](https://github.com/google/jax/blob/17785a4ded535cee44ceee5ba6f40db827ca0005/jax/_src/scipy/linalg.py#L434-L435). Even if it were not, we write these with the expectation that they may be called from other `jax.jit`-compiled functions.

**Comment by froystig** [comment]
Closing for now, since it seems infeasible, but please reopen if I've misunderstood!

**Comment by mcharrak** [comment]
I agree that this this warning should be implemented so that whenever the `jax_debug_nans` flag is enabled to automatically detect NaNs in `jax.jit`-compiled code, it provides more actionable feedback explaining why the NaNs were produced.
