### ISSUE TITLE
Jax should expose options to disable CSE.

### ISSUE THREAD

**Issue by nshepperd** [google/jax#13999]
Common subexpression elimination (CSE) is an optimization performed by by XLA (and likely by MLIR whenever that will be used), but CSE isn't always an optimization. It trades higher memory usage for less compute cost, but in an overly absolute and unconfigurable way. It also breaks other optimizations like explicit rematerialization which do allow customization, requiring error prone manipulation of HLO (eg. the insertion of barriers done by jax.checkpoint/jax.remat) to defeat it. XLA itself offers some form of compiler options allowing certain optimizations to be skipped, including CSE; this should be exposed by jax. As far as I can tell, it currently isn't, there's no way to provide those options to XLA from jax.

This is currently preventing me from experimenting with custom rematerialization algorithms in jax, which should be straightforward with the ability to easily manipulate jaxprs but is unfortunately rendered impossible by the mandatory CSE undoing all this work (and the complexity that would be involved in automatically peppering a large computation graph with jax.remat-style barriers to prevent all cse).

**Comment by nshepperd** [comment]
(As an aside, the ability to selectively disable optimizations would also be very useful to help reduce extremely long compilation times on large jit/pmap computations, which I've had take up to 20 minutes, seriously harming the efficiency of the editing/debugging cycle.)

**Comment by mattjj** [comment]
Thanks for the clear explanation and excellent suggestion!

@pschuh does this sound feasible?

**Comment by pschuh** [comment]
This sounds good, but unless I'm mistaken it is not actually true that there is an option to disable CSE in XLA. (please send a pointer if I'm wrong). I would also note that you should be careful peppering your code with remat-style barriers because these thwart other optimizations than CSE.

**Comment by nshepperd** [comment]
Well I guess what I was thinking of was this: https://github.com/tensorflow/tensorflow/blob/f099608e9d4026d4c5accac9b953bef4579465f3/tensorflow/compiler/xla/xla.proto#L38

Which, unfortunately because they're debugging options there is "no guarantees about backward or forward compatibility" for the fields... but being able to at least set DebugOptions from jax and punt on compatibility would be a good start.

**Comment by pschuh** [comment]
You can set anything in debug options like so: `XLA_FLAGS=--xla_disable_hlo_passes=cse`  .

**Comment by nshepperd** [comment]
Oooh! Well that will work for my purposes. Is there a way to set it per jit/pmap? Either way I guess I'll think about filing a bug with tensorflow to ask them for a stable interface to enable/disable this.

**Comment by nouiz** [comment]
For remat algo, you can check how jax checkpoint does it.
It add some special XLA node in the graph to block the cse optimization:
grep for _optimization_barrier
here: 
https://jax.readthedocs.io/en/latest/_modules/jax/_src/ad_checkpoint.html#checkpoint

Disabling CSE globally isn't the best option.
