### ISSUE TITLE
`jax.random.uniform` returns `nan` if `minval` or `maxval` has `inf` or an extreme value

### ISSUE THREAD

**Issue by epignatelli** [google/jax#14003]
### Description

```python
import jax
import jax.numpy as jnp

inf = float("inf")

minval = jnp.array(-inf)
maxval = jnp.array(0)
k = jax.random.PRNGKey(0)

jax.random.uniform(k, (1,), minval=minval, maxval=maxval)

# Outputs:
# DeviceArray([nan], dtype=float32)
```

The same happens also if I set `minval=jnp.iinfo(jnp.float32).min`.

### What jax/jaxlib version are you using?

0.3.25

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by jakevdp** [comment]
Thanks for the report – it's not obvious to me that a uniform distribution with infinite range is well-defined. Cosider that the uniform distribution is defined such that the probability density function satisfies
$$
\int_{x_min}^{x_max} u(x) dx = 1
$$
and when `x_min` or `x_max` approach infinity, the pdf is everywhere zero, meaning you have zero probability of choosing any finite range of values. What do you think?

**Comment by epignatelli** [comment]
Thanks for the quick answer @jakevdp, I very much agree!

I raised the issue because I was expecting `inf` to translate to the max representable `jnp.float32`, with the range being finite.

**Comment by jakevdp** [comment]
Thanks - that makes sense. I think though the current behavior is more consistet. For example, numpy's uniform distribution also treats infinite bounds as invalid:
```python
In [1]: import numpy as np
   ...: np.random.uniform(low=0, high=np.inf)
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
Cell In[1], line 2
      1 import numpy as np
----> 2 np.random.uniform(low=0, high=np.inf)

File mtrand.pyx:1139, in numpy.random.mtrand.RandomState.uniform()

OverflowError: Range exceeds valid bounds
```
JAX cannot raise an error in this case for the same reasons that it cannot error on out-of-bound indices (erroring on runtime values is not supported), so JAX returns NaN.

**Comment by epignatelli** [comment]
Got it -- I'll close the issue as there seems to be no action here in jax, but thanks very much for the exchange!
