### ISSUE TITLE
Tracing prevents concretization of DeviceArrays passed in as aux_data

### ISSUE THREAD

**Issue by SJSeckmeyer** [google/jax#14033]
### Description

I use aux_data not only for data-types like strings but also as trace-time constants. If you put DeviceArrays into an entry in aux_data they behave at least surprisingly during tracing. Their behavior is also inconsistent with python scalars and `numpy` arrays.
Is the usage of aux_data as trace-time constants not meant to be valid?

This might be connected to or another facet of the issues discussed in [#9298](https://github.com/google/jax/issues/9298) but I am not sure.

The below code snippet contains a simple class whose only member is stored in aux_data.
Calling `fun` with `fun(CustomValue(1.))` or `fun(CustomValue(numpy.array(1.)))` works as expected.

But when the first call is done with `fun(CustomValue(jax.numpy.array(1.)))`:
- x.a simply prints the concrete `1.0` but `copy(x.a)` returns an abstract `Traced<ShapedArray(float32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>` 
- `x.a == 1` raises a `ConcretizationTypeError`.

First converting `x.a` into a float and then comparing it via `float(x.a) == 1` on the other hand works fine for all three calling variants.

First tracing `fun` by calling it with a numpy array or a scalar succeeds. Calling `fun` then with DeviceArrays works because the compilation cache is hit and tracing was already done.

```python
import numpy
import jax
from jax.tree_util import register_pytree_node_class
from copy import copy

@jax.jit
def fun(x):
    print(x.a)
    print(copy(x.a))
    # This variant even works when passing a DeviceArray in x.a.
    # if float(x.a) == 1.:
    if x.a == 1.:
        return 1
    else:
        return 2

@register_pytree_node_class
class CustomValue:
    def __init__(self, a):
        self.a = a
    
    def tree_flatten(self):
        children = ()
        aux_data = (self.a,)
        return (children, aux_data)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*aux_data)

# If this is called first it crashes on x.a == 1 with a ConcretizationError
fun(CustomValue(jax.numpy.array(1.)))

# These two work
fun(CustomValue(1.))
fun(CustomValue(numpy.array(1.)))

# If this is called after one of the two above it also works since tracing already happened
# and the compiled function from the cache is used.
fun(CustomValue(jax.numpy.array(1.)))

```

### What jax/jaxlib version are you using?

jax v0.4.1 jaxlib v0.4.1

### Which accelerator(s) are you using?

CPU

### Additional system info

Anaconda Python 3.9.15, macOS 13.1

**Comment by jakevdp** [comment]
Thanks for the question! In general, elements of `aux_data` should be hashable and have a meaningful equality comparison (See https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees). Device Arrays meet neither of these criteria, so I'd expect strange behavior if you're attempting to include these in `aux_data`.

A good rule of thumb in custom PyTree lowering is that `children` should contain array data, and `aux_data` should contain static content, so in your case I would write:
```python

    def tree_flatten(self):
        children = (self.a,)
        aux_data = ()
        return (children, aux_data)
```

**Comment by SJSeckmeyer** [comment]
Ah okay, thank you. In my case the "arrays" in aux_data are finite floats that emerged from a design where some computations where encoded in types. So those are basically meant as "const generics" in Rust speak or as "non-type template parameter" in C++-speak.
And the value of those determines whether some computations are necessary or not which is why I want to keep them concrete inside a trace.

Would finite floats (so that we can fulfill the meaningful equality criterium) be fine as aux_data?

**Comment by jakevdp** [comment]
Sure, non-array floats or bits should be fine because they are hashable and have meaningful equality comparisons. The only place this might be tricky is if you construct your object in a JIT-compiled function, you’ll have to make sure the source of these values is static. But in general I’m having trouble thinking of any benefit to doing things this way, rather than just including your numerical data in children.

**Comment by SJSeckmeyer** [comment]
The benefit is that I can statically decide whether some expensive operations are necessary. Because in our case we can elide these operations statically in the hot loops. If I would put those values into `children` I would have to use `jax.lax.cond` which in combination with `vmap` becomes a select. And I also have no feeling for how `jax.lax.select` (without `vmap`) is implemented in the different backends so I cannot really gauge the performance impact there. Do you have any links or insights there?

So I actually want to trigger recompilation for cases where these values change. Though your comment prompted me to rethink whether I should not maybe specialize this to some `bool` values or something.

I would close this issue since my original question was very well answered. Thank you. :)
