### ISSUE TITLE
jit compilation with large inlined arrays crashes JAX.

### ISSUE THREAD

**Issue by ethanluoyc** [google/jax#14080]
### Description

The following code snippet would result in kernel crashing on Colab (due to OOM).

```python
import jax
import jax.numpy as jnp
import numpy as np

batch_size = 256
dataset_size = 5000

def sample(data, key):
    key1, key2 = jax.random.split(key)
    indices = jax.random.randint(
        key1, (batch_size,),
        minval=0,
        maxval=dataset_size)
    data_sample = jax.tree_map(lambda d: jnp.take(d, indices, axis=0), data)
    return data_sample, key2

dataset = np.random.randint(0, 10, (dataset_size, 84, 84, 9), dtype=jnp.uint8)
dataset = jax.device_put(dataset)
sample_fn = jax.jit(lambda key: sample(dataset, key))

sample_fn(jax.random.PRNGKey(0))
```

Not inlining the `dataset` array works.

This is a simplified usage from the code here https://github.com/deepmind/acme/blob/master/acme/datasets/tfds.py#L199-L200. My temporary workaround is to fork and change the code to not inline the jax array.

### What jax/jaxlib version are you using?

jax v0.4.1, jax 0.3.5

### Which accelerator(s) are you using?

CPU/GPU

### Additional system info

Colab or Local machine with 3080

**Comment by pschuh** [comment]
What is happening is that it is recompiling it every time and baking the dataset into the graph. This is causing the oom because dataset is large enough that we run out of memory before the caching logic kicks in and starts evicting programs. Seems like a bug in the acme repository.

**Comment by ethanluoyc** [comment]
I am not sure if I understand what you mean by recompiling in this case though. Wouldn't the JIT happen only once in this case?

**Comment by pschuh** [comment]
My mistake, I thought that this was getting called in a loop. Regardless, by capturing dataset you are 'baking' that constant into the XLA graph itself which will copy it to the CPU for the compilation process (which might be what causes the OOM) and generally isn't a good idea. Additionally, I cannot reproduce the oom.

**Comment by ethanluoyc** [comment]
I can reproduce this when running on colab.. not sure what's different...

It's still quite weird to me that I either get a hang locally or run OOM on Colab. The constant array is at most a few hundred Mb large and I don't expect that to cause any issue for XLA.

**Comment by pschuh** [comment]
Can you post some of the details of the oom?

**Comment by ethanluoyc** [comment]
No problem, here is the colab that I use.
https://colab.research.google.com/drive/1mSaw6wxlSCGjiC-mXWRo2_1RtbAye1s9?usp=sharing

**Comment by pschuh** [comment]
Looks like the constant is getting copied many times (At least when I run this locally). There is possibly something slightly different in colab (I'm seeing an 8GB alloc in the oom logs). This leads to a significant blowup.

I also noticed in your logs the following message which implies that you're not even using GPU:
```
WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

This problem might not be present in the GPU/TPU backends which is why the it isn't a problem for other users of this deepmind code.

**Comment by ethanluoyc** [comment]
For GPU, I do not have OOM but instead the process hangs and after some
time I get the slow JIT compile error.

**Comment by ethanluoyc** [comment]
I have not encountered this issue previously working with other datasets. I only found that this becomes a problem (when I use GPU, it hangs) when my dataset consists of images (so they are significantly larger than other datasets that I used). Still, it is a little surprising for me since the dataset is at most a few hundred megabytes large which should still fit nicely in memory.

**Comment by pschuh** [comment]
For me this is a 300MB constant copied ~9 times for some reason which roughly works out to be multiple GB. These allocations happen inside the XLA compiler, so we would need to make a bug against XLA. This is somewhat surprising to me, but the use case is not very convincing. @hawkinsp Maybe the constant is getting converted to a text constant in the colab backend which is causing additional blowups?

**Comment by ethanluoyc** [comment]
Agree that the use case is a bit artificial, as I also don't see particular reasons that I would want to inline the array. I will file an issue on the acme side suggesting not to inline the array as well.
