### ISSUE TITLE
mode has no effect in at[].add

### ISSUE THREAD

**Issue by mariogeiger** [google/jax#14095]
### Description

```python
jnp.array([0.0]).at[jnp.array([-1])].add(jnp.array([1.0]), mode="drop")
```

Returns
```
Array([1.], dtype=float32)
```

Expected
```
Array([0.], dtype=float32)
```

### What jax/jaxlib version are you using?

0.4.1

### Which accelerator(s) are you using?

CPU

### Additional system info

Mac

**Comment by hawkinsp** [comment]
I think that's just because we support negative indices with their usual Python semantics. I suspect you want a different `drop` that doesn't do that?

**Comment by mariogeiger** [comment]
Ah ok fine, then it's just me who did not guess correctly the meaning of that `drop` keyword. I close the issue, Thanks for the quick answer :)

**Comment by hawkinsp** [comment]
Yes. If you tried index `-2` it would be dropped, because negative indices only wrap around "once":

```
In [5]: jnp.array([0.0]).at[jnp.array([-2])].add(jnp.array([1.0]), mode="drop")
Out[5]: Array([0.], dtype=float32)
```
