### ISSUE TITLE
psum of complex64 not supported for multi GPU.

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#1409]
Complex numbers are not supported for AllReduce.

I found this bug when trying to do psum across 4 GPUs with complex64 as the dtype.

```
RuntimeError: Unimplemented: Requested AllReduce not implemented on GPU; replica_count: 4; operand_count: 1; IsCrossReplicaAllReduce: 1; NCCL support: 1; first operand array element-type: C64
```

**Comment by mattjj** [comment]
We can fix this at the JAX level by making [the `psum` lowering](https://github.com/google/jax/blob/01f81875623d7548402d0224703a70e9052492b5/jax/lax/lax_parallel.py#L190-L194) switch on the array element type, and just generate a pair of AllReduces for complex types.
