### ISSUE TITLE
using `jax.tree_util.Partial` or `lambda` function triggers compilation

### ISSUE THREAD

**Issue by marcdelabarrera** [google/jax#14183]
When a new function is created with `Partial` or `lambda`, once the function is called compilation happens again. For example:

```python
from jax.tree_util import Partial

@jax.jit
def some_function(x,parameter):
    return x+parameter

def test_compilation():
    some_function(1,1) #compiles
    patial_function = Partial(some_function, parameter=1)
    patial_function(1) #compiles again
    patial_function(1)
    return
```

And then profiling it `%lprun -f test_compilation  test_compilation()` I get that the first call of partial_function takes longer than the second. 
```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
     7                                           def test_compilation():
     8         1   24826093.0 24826093.0     53.7      some_function(1,1) #compiles
     9         1       8352.0   8352.0      0.0      patial_function = Partial(some_function, parameter=1)
    10         1   21135745.0 21135745.0     45.7      patial_function(1) #compiles again
    11         1     110175.0 110175.0      0.2      patial_function(1)
    12         1        158.0    158.0      0.0      return
```

Is there a workaround to this? Lambda functions seem not to work either. My understanding that partial_function is a *new* function and therefore it's compiled again, but conceptually `some_function(1,1)` is equivalent to `Partial(some_function, parameter=1)(1)`, so I don't see a reason to compile again.
 
I'm asking this because I'm working with `Partial` functions inside a `loop`, which triggers compilation in every iteration.

**Comment by jakevdp** [comment]
This is not related to `Partial`, but rather related to calling the function with different signatures. For example:
```python
In [1]: import jax
   ...: from jax.tree_util import Partial
   ...: 
   ...: @jax.jit
   ...: def some_function(x,parameter):
   ...:     print('compiling')
   ...:     return x+parameter
   ...: 

In [2]: some_function(1, 1)  # compiles: this signature has not yet been seen
compiling
Out[2]: Array(2, dtype=int32, weak_type=True)

In [3]: some_function(1, 1)  # does not compile: this signature has been seen (In [2])
Out[3]: Array(2, dtype=int32, weak_type=True)

In [4]: some_function(1, parameter=1)  # compiles: this signature has not been seen
compiling
Out[4]: Array(2, dtype=int32, weak_type=True)

In [5]: some_function(1, parameter=1)  # does not compile: this signature has been seen (In [4])
Out[5]: Array(2, dtype=int32, weak_type=True)

In [7]: Partial(some_function, parameter=1)(1)  # does not compile: this signature has been seen (In [4])
Out[7]: Array(2, dtype=int32, weak_type=True)
```
Now you could imagine a world in which JAX understands that `args=(1, 1), kwargs={}` is equivalent to `args=(1,), kwargs={'parameter':1}` for the particular function being called, but that would require a level of introspection into python's calling machinery that might be too expensive to use at dispatch time for JIT-compiled functions.

Does that make sense?

**Comment by marcdelabarrera** [comment]
Excellent. I would not have thought that different signatures trigger compilation. Thank's a lot!
