### ISSUE TITLE
pure_callback for eigendecomposition

### ISSUE THREAD

**Issue by yonghakim** [google/jax#14199]
### Description

Hi,

eigen-decomposition with host_callback was successful with jit and pmap.
But while I was trying to do vmap, host_callback was not the option so tried pure_callback option.

    import numpy as np
    import jax.numpy as jnp

    X = jnp.arange(1000**2).reshape((1000,1000))
    
    def eig(X):
        type_complex=jnp.complex64
        _eig = lambda x: np.linalg.eig(x)  
        eigenvalues_shape = jax.ShapeDtypeStruct(X.shape[:-1], type_complex)
        eigenvectors_shape = jax.ShapeDtypeStruct(X.shape, type_complex)
        result_shape_dtype = jax.ShapeDtypeStruct(
        shape=(eigenvalues_shape.shape, eigenvectors_shape.shape),
        dtype=type_complex
        )
        return jax.pure_callback(_eig, result_shape_dtype, X)
    
    print(eig(X))

> TypeError: Shapes must be 1D sequences of concrete values of integer type, got ((1000,), (1000, 1000)).

It seems that pure_callback doesn't accept multiple return values with different size (like eigen-decomposition).
Is it by design? Thanks!

### What jax/jaxlib version are you using?

jax 0.4.1,  jaxlib 0.4.1+cuda11.cudnn86

### Which accelerator(s) are you using?

CPU

### Additional system info

M1

**Comment by jakevdp** [comment]
A couple issues with your first implementation:

- dtypes must match. numpy routines return `complex128`, so we must specify that
- your funciton returns two values, so you must specify this with two `ShapeDtypeStruct` objects rather than one

With those changes, the code works:
```python
import jax.numpy as jnp
import jax
import numpy as np
jax.config.update('jax_enable_x64', True)

X = jnp.arange(1000**2).reshape((1000,1000))

def eig(X):
    type_complex=jnp.complex128
    _eig = lambda x: np.linalg.eig(x)  
    eigenvalues_shape = jax.ShapeDtypeStruct(X.shape[:-1], type_complex)
    eigenvectors_shape = jax.ShapeDtypeStruct(X.shape, type_complex)
    result_shape_dtype = (eigenvalues_shape, eigenvectors_shape)
    return jax.pure_callback(_eig, result_shape_dtype, X)

print(eig(X))
```

**Comment by yonghakim** [comment]
Aha, No need to bundle in one ShapeDtypeStruct.
Yes, I was switching a lot between 64 and 128 so wasn't careful with that.

Thanks a lot!

**Comment by rkruegs123** [comment]
Why do you call `np.linalg.eig(x) ` instead of `jnp.linalg.eig(x)`?

Including @ellamichelleking as we have the same question

**Comment by jakevdp** [comment]
If you want `pure_callback` to be compatible with autodiff, you have to define the gradients explicitly. There's an example here: https://jax.readthedocs.io/en/latest/notebooks/external_callbacks.html#example-pure-callback-with-custom-jvp

**Comment by rkruegs123** [comment]
Thank you, Jake!

**Comment by yonghakim** [comment]
@rkruegs123,

Hope this can help.
This enables backprop of eigendecomposition and enforces running on CPU while the whole process running on GPU.

Mathematics was adopted from other papers.

https://github.com/kc-ml2/meent/blob/main/meent/on_jax/primitives.py 

```python
import jax
import jax.numpy as jnp

from functools import partial


@partial(jax.custom_vjp, nondiff_argnums=(1, 2))
def eig(x, type_complex=jnp.complex128, perturbation=1E-10):

    _eig = jax.jit(jnp.linalg.eig, device=jax.devices('cpu')[0])

    eigenvalues_shape = jax.ShapeDtypeStruct(x.shape[:-1], type_complex)
    eigenvectors_shape = jax.ShapeDtypeStruct(x.shape, type_complex)

    result_shape_dtype = (eigenvalues_shape, eigenvectors_shape)

    return jax.pure_callback(_eig, result_shape_dtype, x)


def eig_fwd(x, type_complex, perturbation):
    return eig(x, type_complex, perturbation), eig(x, type_complex, perturbation)


def eig_bwd(type_complex, perturbation, res, g):
    """
    Gradient of a general square (complex valued) matrix
    Reference: https://github.com/kch3782/torcwa and https://github.com/weiliangjinca/grcwa
    """
    eigval, eigvec = res

    grad_eigval, grad_eigvec = g

    grad_eigval = jnp.diag(grad_eigval)

    s = eigval.reshape((1, -1)) - eigval.reshape((-1, 1))

    F = jnp.conj(s) / (jnp.abs(s) ** 2 + perturbation)
    F = F.at[jnp.diag_indices_from(s)].set(0)

    XH = jnp.conj(eigvec).T
    tmp = jnp.conj(F) * (XH @ grad_eigvec)

    XH_i = jnp.linalg.inv(XH)

    grad = (XH_i @ (grad_eigval + tmp)) @ XH

    if not jnp.iscomplexobj(eigval):
        grad = grad.real

    return grad,


eig.defvjp(eig_fwd, eig_bwd)
```

**Comment by yonghakim** [comment]
Above code has bug and below is fixed.

```python
import jax
import jax.numpy as jnp

from functools import partial


@partial(jax.custom_vjp, nondiff_argnums=(1, 2, 3))
def eig(x, type_complex=jnp.complex128, perturbation=1E-10, device='cpu'):

    _eig = jax.jit(jnp.linalg.eig, device=jax.devices('cpu')[0])

    eigenvalues_shape = jax.ShapeDtypeStruct(x.shape[:-1], type_complex)
    eigenvectors_shape = jax.ShapeDtypeStruct(x.shape, type_complex)

    result_shape_dtype = (eigenvalues_shape, eigenvectors_shape)
    if device == 'cpu':
        res = _eig(x)
    else:
        res = jax.pure_callback(_eig, result_shape_dtype, x)

    return res


def eig_fwd(x, type_complex, perturbation, device):
    return eig(x, type_complex, perturbation), eig(x, type_complex, perturbation)


def eig_bwd(type_complex, perturbation, device, res, g):
    """
    Gradient of a general square (complex valued) matrix
    Reference: https://github.com/kch3782/torcwa and https://github.com/weiliangjinca/grcwa
    """
    eigval, eigvec = res

    grad_eigval, grad_eigvec = g

    grad_eigval = jnp.diag(grad_eigval)

    s = eigval.reshape((1, -1)) - eigval.reshape((-1, 1))  # original

    F = s / (jnp.abs(s) ** 2 + perturbation)
    F = F.at[jnp.diag_indices_from(s)].set(0)

    XH = eigvec.T
    tmp = F * (XH @ grad_eigvec)

    XH_i = jnp.linalg.inv(XH)

    grad = (XH_i @ (grad_eigval + tmp)) @ XH

    if not jnp.iscomplexobj(eigval):
        grad = grad.real

    return grad,


eig.defvjp(eig_fwd, eig_bwd)
```

**Comment by rkruegs123** [comment]
Thank you so much!

**Comment by yonghakim** [comment]
@rkruegs123 Hi, I found another bug in the code. Below is the fixed.
FYI, the previous code showed ~3E-5 difference between backproped gradient and numerical gradient.

```python

import jax
import jax.numpy as jnp

from functools import partial


@partial(jax.custom_vjp, nondiff_argnums=(1, 2, 3))
def eig(x, type_complex=jnp.complex128, perturbation=1E-10, device='cpu'):

    _eig = jax.jit(jnp.linalg.eig, device=jax.devices('cpu')[0])

    eigenvalues_shape = jax.ShapeDtypeStruct(x.shape[:-1], type_complex)
    eigenvectors_shape = jax.ShapeDtypeStruct(x.shape, type_complex)

    result_shape_dtype = (eigenvalues_shape, eigenvectors_shape)
    if device == 'cpu':
        res = _eig(x)
    else:
        res = jax.pure_callback(_eig, result_shape_dtype, x)

    return res


def eig_fwd(x, type_complex, perturbation, device):
    return eig(x, type_complex, perturbation), (eig(x, type_complex, perturbation), x)


def eig_bwd(type_complex, perturbation, device, res, g):
    """
    Gradient of a general square (complex valued) matrix
    Eq. 30~32 in https://www.sciencedirect.com/science/article/abs/pii/S0010465522002715
    Eq 4.77 in https://arxiv.org/pdf/1701.00392.pdf
    https://github.com/kch3782/torcwa
    https://github.com/weiliangjinca/grcwa
    """

    (eig_val, eig_vector), x = res
    grad_eigval, grad_eigvec = g
    grad_eigval = jnp.diag(grad_eigval)

    X_h = eig_vector.T.conj()

    Fij = eig_val.conj().reshape((1, -1)) - eig_val.conj().reshape((-1, 1))
    Fij = Fij / (jnp.abs(Fij) ** 2 + perturbation)
    Fij = Fij.at[jnp.diag_indices_from(Fij)].set(0)
    grad = jnp.linalg.inv(X_h) @ (grad_eigval.conj() + Fij.conj() * (X_h @ grad_eigvec.conj())) @ X_h
    grad = grad.conj()
    if not jnp.iscomplexobj(x):
        grad = grad.real
    return grad,


eig.defvjp(eig_fwd, eig_bwd)
```

> /Users/yongha/miniforge3_m1/envs/rcwa/bin/python /Users/yongha/project/rcwa/meent/QA/backprop.py 

> JAX grad_ad:
>  [[[-0.31936418 -0.21070505 -0.08193991 -0.56743577 -0.22805356]
>   [ 0.09779809 -0.05806508  0.1413275   0.26680362 -0.04509193]]
>  [[-0.07998023 -0.06814561 -0.0119665  -0.16095988 -0.10340981]
>   [-0.02519205 -0.07270359  0.01071986 -0.00646068 -0.02300493]]
>  [[-0.01214202 -0.06787044 -0.0075716  -0.02270837 -0.08079771]
>   [-0.003161   -0.09658575 -0.02822204 -0.0118468  -0.03896227]]]
>
> JAX grad_numeric:
>  [[[-0.31936418 -0.21070505 -0.08193991 -0.56743577 -0.22805356]
>   [ 0.09779809 -0.05806508  0.1413275   0.26680362 -0.04509193]]
>  [[-0.07998023 -0.06814561 -0.0119665  -0.16095988 -0.10340981]
>   [-0.02519205 -0.07270359  0.01071986 -0.00646068 -0.02300493]]
>  [[-0.01214202 -0.06787044 -0.0075716  -0.02270837 -0.08079771]
>   [-0.003161   -0.09658575 -0.02822204 -0.0118468  -0.03896227]]]
> JAX norm:  5.965338263715071e-09
> 
> Torch grad_ad:
>  tensor([[[-0.3194, -0.2107, -0.0819, -0.5674, -0.2281],
>          [ 0.0978, -0.0581,  0.1413,  0.2668, -0.0451]],
>         [[-0.0800, -0.0681, -0.0120, -0.1610, -0.1034],
>          [-0.0252, -0.0727,  0.0107, -0.0065, -0.0230]],
>         [[-0.0121, -0.0679, -0.0076, -0.0227, -0.0808],
>          [-0.0032, -0.0966, -0.0282, -0.0118, -0.0390]]], dtype=torch.float64)
>
> Torch grad_numeric:
>  tensor([[[-0.3194, -0.2107, -0.0819, -0.5674, -0.2281],
>          [ 0.0978, -0.0581,  0.1413,  0.2668, -0.0451]], 
>         [[-0.0800, -0.0681, -0.0120, -0.1610, -0.1034],
>          [-0.0252, -0.0727,  0.0107, -0.0065, -0.0230]],
>         [[-0.0121, -0.0679, -0.0076, -0.0227, -0.0808],
>          [-0.0032, -0.0966, -0.0282, -0.0118, -0.0390]]])
>
> torch.norm:  tensor(3.3405e-08, dtype=torch.float64)
> 
> Process finished with exit code 0
>
