### ISSUE TITLE
libdevice not found 

### ISSUE THREAD

**Issue by 1kaiser** [google/jax#14198]
### Description

(lambda x: args * jnp.power(2.0, x))(jnp.arange(4))

---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
[<ipython-input-47-384ff1e31327>](https://localhost:8080/#) in <module>
----> 1 (lambda x: args * jnp.power(2.0, x))(jnp.arange(4))

14 frames
UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INTERNAL: libdevice not found at /usr/local/lib/python3.8/dist-packages/jaxlib/cuda/nvvm/libdevice/libdevice.10.bc

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

XlaRuntimeError                           Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/ufuncs.py](https://localhost:8080/#) in power(x1, x2)
    345       x1, = _promote_dtypes_numeric(x1)
    346       return lax.integer_pow(x1, x2)
--> 347   return _power(x1, x2)
    348 
    349 

XlaRuntimeError: INTERNAL: libdevice not found at /usr/local/lib/python3.8/dist-packages/jaxlib/cuda/nvvm/libdevice/libdevice.10.bc

### What jax/jaxlib version are you using?

0.4.2

### Which accelerator(s) are you using?

gpu

**Comment by hawkinsp** [comment]
That's really weird! `libdevice` is distributed as part of the jaxlib wheel.

Can you try uninstalling and reinstalling jaxlib? Let me know if that helps!

**Comment by 1kaiser** [comment]
now it works first we have to install `!python -m pip install jax==0.4.2` then its gets to working condition
