### ISSUE TITLE
`lax.cond` failing with `jacfwd` that depend on type

### ISSUE THREAD

**Issue by Randl** [google/jax#14216]
### Description

Assume I have the following (simplified) function `f1` which uses `jacfwd`:
```python3
import jax
from jax import lax
from jax import numpy as jnp
```

```python3
@jax.jit
def f1(flat):
    curried = lambda z: z**2
    x = jax.jacfwd(curried)(flat)
    return x
```
It works as intended if I call it with `f1(jnp.zeros(1))`.

Now assume I want to use the same function with both complex and float inputs. I tried to do that with `lax.cond`:
```python3
@jax.jit
def f2(flat):
    curried = lambda z: z**2
    x = lax.cond(jnp.iscomplex(flat)[0],
             jax.jacfwd(curried, holomorphic=True),
             jax.jacfwd(curried), flat)
    return x
```
I expected it would work as intended since only one branch would be executed. In fact it fails for any input:
```
UnfilteredStackTrace: TypeError: jacfwd with holomorphic=True requires inputs with complex dtype, but got float32.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------


The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)

[<ipython-input-8-7185f30dfd3c>](https://localhost:8080/#) in f2(flat)
      2 def f2(flat):
      3     curried = lambda z: z**2
----> 4     x = lax.cond(jnp.iscomplex(flat)[0],
      5              jax.jacfwd(curried, holomorphic=True),
      6              jax.jacfwd(curried), flat)

TypeError: jacfwd with holomorphic=True requires inputs with complex dtype, but got float32.
```
and
```
UnfilteredStackTrace: TypeError: jacfwd requires real-valued inputs (input dtype that is a sub-dtype of np.floating), but got complex64. For holomorphic differentiation, pass holomorphic=True. For differentiation of non-holomorphic functions involving complex inputs or integer inputs, use jax.jvp directly.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------


The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)

[<ipython-input-8-7185f30dfd3c>](https://localhost:8080/#) in f2(flat)
      2 def f2(flat):
      3     curried = lambda z: z**2
----> 4     x = lax.cond(jnp.iscomplex(flat)[0],
      5              jax.jacfwd(curried, holomorphic=True),
      6              jax.jacfwd(curried), flat)

TypeError: jacfwd requires real-valued inputs (input dtype that is a sub-dtype of np.floating), but got complex64. For holomorphic differentiation, pass holomorphic=True. For differentiation of non-holomorphic functions involving complex inputs or integer inputs, use jax.jvp directly.
```

I'm not sure whether jax is unable to trace function or tries to execute both branches, but I think there should be a way to achieve the intended behavior (call the same function with complex and floating inputs and get the gradients through it).

### What jax/jaxlib version are you using?

jax v0.4.2

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by soraros** [comment]
IMO it's working as intended. You don't need a staged conditional (i.e. `lax.cond`) when you want to branch on static information of an array such as `dtype` or `shape`.

You could do the following or simply use a if statement

```python
@jit
def f2(flat):
  curried = lambda z: z**2
  return jacfwd(curried, holomorphic=np.iscomplexobj(flat))(flat)
```

**Comment by Randl** [comment]
Hmm the problem was I used `iscomplex` instead of `iscomplexobj`. Not sure if it is documented anywhere. Thanks anyway!

**Comment by soraros** [comment]
> Hmm the problem was I used iscomplex instead of iscomplexobj.

@Randl Glad your problem got resolved. However, as I explained above, the fact that you cannot use `iscomplex` here is the menifestation and not the cause of the problem. You can see that from the following

```python
@jit
def f(x):
  return lax.cond(True, 
                  lambda: jnp.zeros_like(x, dtype=complex),
                  lambda: jnp.zeros_like(x))

print(jax.make_jaxpr(f)(1.))  # raises TypeError
```

The error reads

```python
TypeError: true_fun and false_fun output must have identical types, got
DIFFERENT ShapedArray(complex128[]) vs. ShapedArray(float64[], weak_type=True).
```

since `lax.cond` traces both its branches, and the whole `lax.cond(...)` expression (or more generally, the whole staged program) should be `dtype` monomorphic. I think the latter point is more fundamental. One way to think about this is to think of JAX as an embedded language where python is the meta-language. Branching on `dtype` (or other static information) can only happen in python land and in not JAX land (I wrote `np.iscomplexobj` and not `jnp.iscomplexobj` in the example to make that clear). It's touched a bit in the [document](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-autodiff).

More generally, if one wants ad hoc shape polymorphism, python control flow statements is the way to go:

```python
def f(a: Array): ...
def g(a: Array): ...

def h(a: Array):
  if a.ndim == 1 and a.dtype == np.float32:  # or any other value-independent condition
    return f(a)
  else:
    return g(a)
```
