### ISSUE TITLE
`lax.cond` excessive caching behavior, how to avoid?

### ISSUE THREAD

**Issue by thisiscam** [google/jax#14220]
### Description

I noticed that when using `lax.cond`, the conditional functions are [converted to jaxprs and are cached](https://github.com/google/jax/blob/main/jax/_src/lax/control_flow/common.py#L66).  
This causes a memory-leak like behavior when the conditionals are changing across compilation runs. Here's a MWE:
```python
import jax

def f(x):
  return x**2

identity = lambda x: x

def g(x):
  return jax.lax.cond(x > 0.0, identity, jax.grad(f), operand=x)

while True:
  g1 = jax.jit(g)
  r = f1(1.)
  g1.clear_cache()
```

In this example, I expect `f1.clear_cache` to discard anything related to compiling `g`. However, I'm observing that memory keeps growing across iterations. The memory footprint only reaches a plateau after a few thousand iterations of the loop.

Here's a plot of the memory growth of the above snippet:
![mem](https://user-images.githubusercontent.com/7684342/215710748-90d11427-e377-4850-88f7-c1fc384c07d6.png)

Notice the linear memory growth from 1 ~ 80 seconds. 

My use case is that I have an `g` with varying shapes across the outer loop. 
Therefore, recompilation is required. Moreover, `clear_cache` is required, to avoid excessively caching `g1` that are used only once.

My understanding is: Each new reference produced by `jax.grad(f)` confuses `lax.cond`, causing it to cache all the jaxprs of `jax.grad(f)`.  This problem is really unfortunate for me, since my `f` is quite complicated, and a few iterations of the loop produces more than 4 GBs of cached jaxprs (that are never used again, due to the varying shapes). 

Is there a good way to prevent this behavior? Or, perhaps, this could be addressed together with #12719?

### What jax/jaxlib version are you using?

jax v0.4.2

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
I don't think this has anything to do with the jit cache; we can directly query the size of the jit cache this way, and see that it is not growing:
```python
import jax
from jax._src.api import _cpp_jit_cache

def f(x):
  return x**2

identity = lambda x: x

def g(x):
  return jax.lax.cond(x > 0.0, identity, jax.grad(f), operand=x)

for i in range(10):
  print(_cpp_jit_cache.size(), end=' ')
  g1 = jax.jit(g)
  r = g1(1.)
print()
# 0 1 2 2 2 2 2 2 2 2 
```
I suspect the memory growth you're seeing has to do with other cacheing that JAX is using internally; for example JAX uses `functools.lru_cache` in many places to trade-off between memory and runtime cost. An example is here: https://github.com/google/jax/blob/574c0e704722ca6a336458521d4bd7597c268cd6/jax/_src/util.py#L243-L259

Unfortunately, there's currently no way to globally clear all those caches during the course of running a JAX program. A related request that you might follow is here: https://github.com/google/jax/issues/10828

**Comment by thisiscam** [comment]
Thanks for the prompt response! Yes I agree with you that it has less to do with jit cache.

The line of `lax.cond` that creates jaxpr is:
https://github.com/google/jax/blob/main/jax/_src/lax/control_flow/conditionals.py#L238
But then, this gets cached by
https://github.com/google/jax/blob/b374080e855deb2af6d7c5f9decfefd547c94e95/jax/_src/lax/control_flow/common.py#L65

This cache uses a default size of 4096 entries. My problem is that each entry (a jaxpr) in my case takes a few to maybe 100 megabytes of RAM. This quickly become out of control and get me OOMs, since I'm running on a cluster with memory constraints.

Further, `jax.clear_backends` doesn't seem to clear this cache (I'm still seeing OOMs)

**Comment by thisiscam** [comment]
@mattjj Thanks! These options looks quite promising!

One curious question, though, is why `lax.while_loop` does not have this problem? 
Could we use the same caching mechanism for `while_loop` and `cond`?

For now, I will workaround the issue using `select`.

**Comment by jakevdp** [comment]
I think the reason `cond` and `while_loop` behave differently is because `cond` traces with this function, which has a strong reference cache: https://github.com/google/jax/blob/518bb56c6eb1b94b82c457607fa4217fbf769d8d/jax/_src/lax/control_flow/common.py#L65-L66

And `while_loop` traces with this function, which has a weak reference cache: https://github.com/google/jax/blob/518bb56c6eb1b94b82c457607fa4217fbf769d8d/jax/_src/lax/control_flow/common.py#L57-L58

I'm not sure what the reason is for the different cacheing mechanisms between these two functions.

**Comment by mattjj** [comment]
@jakevdp good find. I suspect we just haven't gotten to adding `weakref_lru_cache` everywhere it should be, since it was a later development.

One simple issue here is that `weakref_lru_cache` creates a weakref to its first argument, and cond/switch uses `_initial_style_jaxprs_with_common_consts` which has a sequence of funs as its first argument. Builtin sequence types don't work with weakrefs, and I vaguely recall some complexity with making our own weakref-able sequence type... like, if we drop a reference to one element in the sequence, we need to drop the whole cache entry.

Yeah now that I think about this, I recall talking about this with @pschuh. Parker, if you remember anything else / different, let us know! Otherwise the todo item may be to work out a scheme for applying something like `weakref_lru_cache` to functions which have a `Sequence[Callable]` first argument.

**Comment by jakevdp** [comment]
We could change the call signature of the utility to accept `*args` if the sequence argument is the only problem.

**Comment by jakevdp** [comment]
Giving it a try in #14231

**Comment by jakevdp** [comment]
Looking at this closer, I'm not sure that cache is the issue. For example:
```python
from jax._src.lax import control_flow
for i in range(10):
  g1 = jax.jit(g)
  r = g1(1.)
  print(control_flow._initial_style_jaxprs_with_common_consts.cache_info())
```
```
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
```
The cache for this function is only hit once in your sample code.

I'm having trouble replicating the memory growth you're reporting. Is it possible that you're seeing memory growth on-device? Each of your loops creates an on-device buffer which is then immediately de-referenced, but it won't actually be deleted from device until python garbage collection cleans up the reference and triggers an asynchronous buffer deletion on your device.

**Comment by thisiscam** [comment]
@jakevdp Try this code:

```python
import jax


def f(x):
  return x**2


identity = lambda x: x


def g(x):
  return jax.lax.cond(x > 0.0, identity, jax.grad(f), operand=x)

from jax._src.lax import control_flow
while True:
  g1 = jax.jit(g)
  r = g1(1.)
  g1.clear_cache()
  print(control_flow._initial_style_jaxprs_with_common_consts.cache_info())
```

I got the following output for the two seconds:
```
CacheInfo(hits=0, misses=1, maxsize=4096, currsize=1)
CacheInfo(hits=0, misses=2, maxsize=4096, currsize=2)
CacheInfo(hits=0, misses=3, maxsize=4096, currsize=3)
CacheInfo(hits=0, misses=4, maxsize=4096, currsize=4)
CacheInfo(hits=0, misses=5, maxsize=4096, currsize=5)
CacheInfo(hits=0, misses=6, maxsize=4096, currsize=6)
CacheInfo(hits=0, misses=7, maxsize=4096, currsize=7)
CacheInfo(hits=0, misses=8, maxsize=4096, currsize=8)
CacheInfo(hits=0, misses=9, maxsize=4096, currsize=9)
CacheInfo(hits=0, misses=10, maxsize=4096, currsize=10)
CacheInfo(hits=0, misses=11, maxsize=4096, currsize=11)
CacheInfo(hits=0, misses=12, maxsize=4096, currsize=12)
CacheInfo(hits=0, misses=13, maxsize=4096, currsize=13)
CacheInfo(hits=0, misses=14, maxsize=4096, currsize=14)
CacheInfo(hits=0, misses=15, maxsize=4096, currsize=15)
CacheInfo(hits=0, misses=16, maxsize=4096, currsize=16)
CacheInfo(hits=0, misses=17, maxsize=4096, currsize=17)
CacheInfo(hits=0, misses=18, maxsize=4096, currsize=18)
CacheInfo(hits=0, misses=19, maxsize=4096, currsize=19)
CacheInfo(hits=0, misses=20, maxsize=4096, currsize=20)
CacheInfo(hits=0, misses=21, maxsize=4096, currsize=21)
CacheInfo(hits=0, misses=22, maxsize=4096, currsize=22)
CacheInfo(hits=0, misses=23, maxsize=4096, currsize=23)
CacheInfo(hits=0, misses=24, maxsize=4096, currsize=24)
CacheInfo(hits=0, misses=25, maxsize=4096, currsize=25)
CacheInfo(hits=0, misses=26, maxsize=4096, currsize=26)
CacheInfo(hits=0, misses=27, maxsize=4096, currsize=27)
CacheInfo(hits=0, misses=28, maxsize=4096, currsize=28)
CacheInfo(hits=0, misses=29, maxsize=4096, currsize=29)
CacheInfo(hits=0, misses=30, maxsize=4096, currsize=30)
....
```

In your snippet, `jit` cache is catching all the recompilations. But, in my use case, `jit` cannot cache since the shapes are varying.

**Comment by mattjj** [comment]
#22610 fixed this!

To verify, I ran this variant of the repro code:

```python
import jax


def f(x):
  return x**2


identity = lambda x: x


def g(x):
  return jax.lax.cond(x > 0.0, identity, jax.grad(f), operand=x)

from jax._src.lax import control_flow
while True:
  g1 = jax.jit(g)
  r = g1(1.)
  g1.clear_cache()
  print(control_flow.common._pad_jaxpr_constvars.cache_info())
```

Woohoo!
