### ISSUE TITLE
jnp.max/jnp.min allow non-scalar value for `initial`.

### ISSUE THREAD

**Issue by keunhong** [google/jax#14258]
### Description

Hello!

I would like to report a sort of inverse feature request. Our code currently relies on the following logic working:

```python
def f(a, b):
  return jnp.max(a, axis=-1, initial=b, where=jnp.isfinite(a))

>> a = jnp.full((5,), fill_value=2)
>> b = jnp.array([1, 2, 3, 4, 5])
>> f(a, b)
Array([2, 2, 3, 4, 5], dtype=int32)
```

_Technically_ this shouldn't work since the `initial` argument of `jnp.max` is supposed to be a scalar. Numpy throws an exception `ValueError: Input object to FillWithScalar is not a scalar`, but it appears that JAX's implementation is more general and works as intended.

Can we continue to rely on this behavior?

### What jax/jaxlib version are you using?

0.4.2

### Which accelerator(s) are you using?

GPU

**Comment by yashk2810** [comment]
This behavior breaks with jit pjit merge! But magically works with the old jit.

**Comment by keunhong** [comment]
Actually this works with both jit and pjit. The pjit merge breaks the case when `initial` has a trailing dimension of 1:

```
def f(a, b):
  return jnp.max(a, axis=-1, initial=b, where=jnp.isfinite(a))


a = jnp.full((4, 5, 3), fill_value=2)
b = jnp.zeros((4, 5, 1))
jax.vmap(f)(a, b)  # Works with old jit, but fails with pjit.
```

The exception is `TypeError: max: arrays must have same number of dimensions, got (5, 1), (5,).`.

**Comment by jakevdp** [comment]
I think this is an unintended implementation detail, and the behavior is untested so I would probably not rely on it.  In fact, your original example looks like a bug to me, because the reduced array is the wrong size, so I'd lean toward checking the shape on `initial` and raising an error if it's not a scalar.

**Comment by jakevdp** [comment]
So I think we're going to move toward explicitly requiring `initial` to be a scalar (see https://github.com/google/jax/pull/14365#issuecomment-1426538150)

You'd still be able to effectively use broadcasted initial values by wrapping your call in `vmap`, and passing a mapped value to the `initial` argument.
