### ISSUE TITLE
Default value of `Array` type in dataclass fields throws `ValueError` in python 3.11

### ISSUE THREAD

**Issue by ASEM000** [google/jax#14295]
### Description

Starting from python 3.11 , dataclass fields check for existence of [hash function to determine if a field value is mutable or not.](https://github.com/python/cpython/commit/e029c53e1a408b89a4e3edf30a9b38b094f9c880)

Any suggestion to use `Array`/`jnp.ndarray` annotation without using field factory as before ?

```python
import dataclasses as dc

# this will fail for python 3.11
@dc.dataclass
class Test:
    a: jnp.ndarray = jnp.array([1,2,3])

# this works
@dc.dataclass
class Test:
    a: int = dc.field(default_factory=lambda: jnp.array([1,2,3]))

```

### What jax/jaxlib version are you using?

0.4.2

### Which accelerator(s) are you using?

NA

### Additional system info

Python 3.11

**Comment by jakevdp** [comment]
This is a tough one  – the linked commit uses hashability as a proxy for immutability, but that is wrong. JAX arrays are both immutable and un-hashable, so the assumption fails and the code errors incorrectly.

Given that, I think this should be considered a bug in the logic of Python 3.11, and I can't think of anything we can do on the JAX side to fix it that wouldn't have other undesirable side-effects.

I'd suggest reporting this as a bug in CPython, and in the meantime unfortunately you'll have to avoid using `Array` type annotations within dataclasses. Perhaps you could use `Union[None, jax.Array]` or something like it to get around the CPython bug.

**Comment by ASEM000** [comment]
I rechecked the CPython code, and they seem to check for the field default for the hash function existence.

Thanks for the suggestion.

**Comment by jakevdp** [comment]
Thanks - I still think this is a bug. A JAX array should be fine as a default argument, because it's immutable. The fact that it's not hashable does not imply mutability.

**Comment by ASEM000** [comment]
I agree with you ,I posted about this issue to CPython github. However, It does not seem that JAX is the only affected library by that decision.

**Comment by jakevdp** [comment]
Ok- thanks for bringing this to our attention!

**Comment by ASEM000** [comment]
For reference, this change was suggested by [Raymond Hettinger](https://bugs.python.org/msg403103)

**Comment by jakevdp** [comment]
Thanks for the context. Reading the rest of the discussion at https://bugs.python.org/issue44674, it seems the implications of this change was not fully thought through. I suspect the ship has probably sailed at this point, though, which is unfortunate.
