### ISSUE TITLE
Expose inverse DCT implementation

### ISSUE THREAD

**Issue by crowsonkb** [google/jax#14330]
The inverse DCT appears not to be implemented in JAX right now:

```
>>> jax.scipy.fft.dctn(jnp.eye(4), norm="ortho", type=3)
NotImplementedError: Only DCT type 2 is implemented.
```

But the IDCT is the backward pass of the DCT so it actually *is* implemented and you can access it manually with `jax.vjp()`! Could this implementation please be exposed to users? Filters of the form DCT->process coefficients->IDCT are a thing I do commonly and I would appreciate having it explicitly available.

**Comment by jakevdp** [comment]
It looks like only type 2 inverse DCT is implemented currently. These kinds of features are generally implemented on an as-needed basis. I don't know of any plans to implement other DCT types, but we'd certainly accept such a contribution!

**Comment by crowsonkb** [comment]
Sorry for not being clear, type 3 DCT = type 2 IDCT and vice versa. Since there is no explicit jax.scipy.idct()/idctn() I tried to access the type 2 IDCT by specifying type 3 to dct().

**Comment by jakevdp** [comment]
Cool - then it sounds like implementation would be fairly straightforward. Just a light wrapper plus some tests. Is that something you're interested in contributing?

**Comment by Skylion007** [comment]
@crowsonkb Would you mind sharing a code snippit about how to do this practically? I am bit confused about how to access the backwards pass via vjp,

**Comment by rajasekharporeddy** [comment]
Hi @crowsonkb 

It appears `jax.scipy.fft.idct` and `jax.scipy.fft.idctn` were implemented in PR https://github.com/google/jax/pull/15636. Could you take a look at the corresponding documentation here: https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.fft.idct.html#jax.scipy.fft.idct

Thank you

**Comment by jakevdp** [comment]
Thanks for following up!
