### ISSUE TITLE
dlpack/jax2torch doesn't work with GPU + multi-dimensional arrays w/ some singleton dims

### ISSUE THREAD

**Issue by sokrypton** [google/jax#14399]
### Description
I'm getting error:
```UnfilteredStackTrace: jaxlib.xla_extension.XlaRuntimeError: INVALID_ARGUMENT: Executable expected shape f32[1,3]{1,0} for argument 0 but got incompatible shape f32[1,3]{0,1}```

See example here:
https://colab.research.google.com/drive/1PgbBQK7Q2gNMT3FZHtQSOuDN-b2TqdVS

if I change:
```python
x = torch.tensor([[1., 2., 3.]]).cuda()
```
to 
```python
x = torch.tensor([1., 2., 3.]).cuda()
```
it works (also works on CPU if I remove the `.cuda()` flag)

@mattjj @hawkinsp

### What jax/jaxlib version are you using?
Google Colab
jax=0.3.25
jaxlib=0.3.25

### Which accelerator(s) are you using?
GPU

### Additional system info

Google Colab

**Comment by sokrypton** [comment]
This (shape=[2, 2]) works
```python
x = torch.tensor([[1., 2.], [3., 4.]]).cuda()
```
This (shape=[2, 2, 1]) works:
```python
x = torch.tensor([[[1.], [2.]], [[3.], [4.]]]).cuda()
```
This (shape=[1, 2, 2]) doesn't work:
```python
x = torch.tensor([[[1., 2.], [3., 4.]]]).cuda()
```

So I think it's just leading singleton dim

**Comment by sokrypton** [comment]
Actually, this (shape=[2,1,1,]) also doesn't work:
```python
x = torch.tensor([[[1.0]],[[1.0]]]).cuda()
```

**Comment by sokrypton** [comment]
actually this fixes the error:
```python
def t2j(x_torch):
    shape = x_torch.shape
    x_torch_flat = torch.flatten(x_torch)
    x_jax = jax_dlpack.from_dlpack(torch_dlpack.to_dlpack(x_torch_flat))
    return x_jax.reshape(shape)
```
but then backprop doesn't work...
<img width="846" alt="image" src="https://user-images.githubusercontent.com/4187522/218028693-5fc4cf36-e96e-4324-9ed8-4abf30aaed34.png">

**Comment by mattjj** [comment]
Context:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1458824/218150936-c2831ec8-f1e5-4d34-ab8a-0fc8fdbe5520.png">
[tweet](https://twitter.com/SingularMattrix/status/1623919590547009536)

@hawkinsp might this be an easy fix?

**Comment by hawkinsp** [comment]
Note you'll need to build jaxlib from source at head with an up to date XLA (TF) pin. Or you can wait until the next jaxlib release, which probably won't be that far off.

**Comment by sokrypton** [comment]
🙏 thanks!!

**Comment by mattjj** [comment]
@sokrypton if there are other problems with jax2torch + AlphaFold, let us know! It seems like a good end-to-end test case.
