### ISSUE TITLE
Standardize code style

### ISSUE THREAD

**Issue by joaogui1** [google/jax#1445]
In #1442 discussion we thought about the possibility of standardizing code style, I think it would make development easier as it helps with reading code, removes "useless" linter warnings and overall makes things more organized.
One of the main points in my opinion is at least standardizing indentation size, as in lax_numpy.py we have some places using indentation of 2 spaces and a few using 4 spaces.
I propose using yapf with the following .yapf.style file:
`[style]`
`based_on_style = chromium`
`split_before_logical_operator = true`
`join_multiple_lines = true`
`column_limit = 100`
`split_before_named_assigns = false`

**Comment by levskaya** [comment]
I think the major reluctance among devs here to adopt yapf, (or black, etc.) is that nearly every python formatter out there tends to mutilate math-heavy code and causes a net -decrease- in readability, even though they might decrease linter noise.  They're all rather over-specialized on the conventions for webdev, systems code, etc.

That's not to say that stylistic consistency isn't a worthy goal to be pursued (e.g. consistent indentation...), but I've personally been sorely underwhelmed by the utility of _automated_ python formatters in scientific code in the past, and typically have spent as much time fighting them as I have deriving any tangible benefits.  ...perhaps if there was an extremely "light-touch" configuration that only fixed obvious issues, it might be considered?  Any full chromium/pep-8 enforcement probably won't be welcomed at the moment.

**Comment by joaogui1** [comment]
Well we can add a .yapf.style file and customize what yapf will do, the configs I posted above for example already make it waste less vertical space by telling it to not split before names assigns. Probably adding rules that forbid it from splitting before arithmetical operators could help?
Can you test the config above and give me some feedback on it's effects?

**Comment by shoyer** [comment]
I've become quite partial to black, which I find to produce nicer results than YAPF (at least, with Google's default settings). There are still (very rare) fail cases with poor formatting, but most of those are solved by splitting expressions manually into multiple lines. And it's really nice not to need to argue about code formatting anymore

Take a look at https://github.com/google/jax/pull/1449 if you're curious what this looks like on JAX. Probably the main downside is that you get one commit that changes literally every line in the Git history, but we still found it to be quite worthwhile for xarray.

**Comment by joaogui1** [comment]
So, I think this one has the problem of wasting too much vertical space as @skye pointed out, also it's using 4 spaces instead of 2 (which seems to be  the standard used in jax programs), and it seems black is not configurable. 
Should I open a PR using my yapf configuration so we can compare them?

**Comment by joaogui1** [comment]
So, the yapf version looks more compact and we can customize the style. What do you think?
