### ISSUE TITLE
Jax on Colab can not detect TPU

### ISSUE THREAD

**Issue by onegigbyte** [google/jax#14481]
### Description

Running jax code on Colab with TPU, however, it failed to find TPU and fell back to CPU as a result. GPU works, but I'm looking for more speed.
```
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
print(jax.__version__)
```
When running jax code:
```
2023-02-15 09:24:56.763483: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

```
Any help would be appreciated.

Tried solutions with previous issues:
https://github.com/google/jax/issues/10860

### What jax/jaxlib version are you using?

jax 0.3.25

### Which accelerator(s) are you using?

TPU

### Additional system info

Python 3.8.10

**Comment by jakevdp** [comment]
Thanks for the report, and sorry you're running into issues! I just tried executing the following on a fresh Colab TPU VM, and got the expected output:
```python
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
print(jax.__version__)
```
```
0.3.25
```
```python
import jax.numpy as jnp
x = jnp.arange(10)
print(x.device().device_kind)
```
```
Cloud TPU
```
Could you try again on a fresh VM? (i.e. choose *Runtime -> Disconnect and Delete Runtime* and then run your code again) One thing that could cause this issue is if you imported `jax` before running the TPU setup, and so the VM is stuck in a misconfigured state.

**Comment by onegigbyte** [comment]
Thanks @jakevdp!
Your example works, but I still couldn't get the TPU to work if I wrap the code inside a file.
For example,
```
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
print(jax.__version__)

import jax.numpy as jnp
x = jnp.arange(10)
print(x.device().device_kind)
```
```
0.3.25
Cloud TPU
```
------------
```
! cat test.py
```
```
import jax.tools.colab_tpu
import jax.numpy as jnp

if __name__ == "__main__":
    print(jax.__version__)
    x = jnp.arange(10)
    print(x.device().device_kind)
```
------------
```
!python3 test.py
```
```
0.3.25
2023-02-15 19:41:05.042025: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:267] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
WARNING:jax._src.lib.xla_bridge:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
cpu
```
Weird, isn't it? I have tried with "Disconnect and Delete Runtime" many times, but this problem still persists.
Can you repo?

**Comment by jakevdp** [comment]
It looks like your `test.py` never calls `jax.tools.colab_tpu.setup_tpu()`? When you run `!python3`, it starts a new process, and the TPU setup must be done in every process. For example, this works:
```python
%%writefile test.py
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
print(jax.__version__)

import jax.numpy as jnp
x = jnp.arange(10)
print(x.device().device_kind)
```
```python
!python3 test.py
```
```
0.3.25
Cloud TPU
```

**Comment by onegigbyte** [comment]
Ah, you are correct.
Sorry for the stupid question, somehow I was thinking they will run on the same process.
