### ISSUE TITLE
Colab INTERNAL: RET_CHECK failure

### ISSUE THREAD

**Issue by Honza9723** [google/jax#14521]
### Description

Dear All,

I am facing a weird error message when running my code on Colab Nvidia GPU. It is very strange because the same code worked previously (2 weeks ago), and it also works seamlessly when run on Colab CPU. Here is a minimal working example.  Here, I install JAX & associated libraries.
`'''(1) Import JAX '''
USE_CPU = False
USE_GPU = True
if USE_CPU:
 !pip install --upgrade -q pip jaxlib jax
if USE_GPU:
  !pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
!pip install --upgrade -q git+https://github.com/deepmind/dm-haiku.git
!pip install --upgrade -q git+https://github.com/deepmind/optax.git  
import jax`
Outputing:
`Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Requirement already satisfied: jax[cuda] in /usr/local/lib/python3.8/dist-packages (0.4.3)
Requirement already satisfied: scipy>=1.5 in /usr/local/lib/python3.8/dist-packages (from jax[cuda]) (1.7.3)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.8/dist-packages (from jax[cuda]) (1.21.6)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.8/dist-packages (from jax[cuda]) (3.3.0)
Requirement already satisfied: jaxlib==0.4.3+cuda11.cudnn86 in /usr/local/lib/python3.8/dist-packages (from jax[cuda]) (0.4.3+cuda11.cudnn86)
  Preparing metadata (setup.py) ... done
  Preparing metadata (setup.py) ... done`

It looks JAX sees the GPU without any problems.
`'''(2) Check devices '''
jax.devices()`

`[StreamExecutorGpuDevice(id=0, process_index=0, slice_index=0)]
`
However, if I want to try something, for example just to sample random numbers
`jax.random.PRNGKey(0)`

I get some weird XLA error.
`---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
[<ipython-input-26-5e9d59225894>](https://localhost:8080/#) in <module>
----> 1 jax.random.PRNGKey(0)

23 frames
[/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in backend_compile(backend, built_c, options, host_callbacks)
   1024   # TODO(sharadmv): remove this fallback when all backends allow `compile`
   1025   # to take in `host_callbacks`
-> 1026   return backend.compile(built_c, compile_options=options)
   1027 
   1028 _ir_dump_counter = itertools.count()

XlaRuntimeError: INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:626) dnn != nullptr`

Can somebody please give me some advice, on what to do? The same codes which worked previously are now broken...

### Which accelerator(s) are you using?

GPU

### Additional system info

Colab

### NVIDIA GPU info

Thu Feb 16 16:13:21 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    28W /  70W |  13962MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      3009      C                                   13959MiB |

**Comment by hawkinsp** [comment]
You're using the wrong version of jaxlib: it requires a newer cudnn than colab has installed. See https://github.com/google/jax/issues/14464

Hope that helps!
