### ISSUE TITLE
Support for BSR sparse matrix

### ISSUE THREAD

**Issue by renecotyfanboy** [google/jax#14524]
Hi,

Is there any intend to support the Block Sparse Row matrix format in the future? This is “simply” an extension of the CSR which is already being developed, and further described here in [scipy's doc](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.bsr_matrix.html). This could help in cases where the matrices are sparse but contiguously defined in line, but I have no clue about how moving from float operation as in CSR to local vector operation would be hard to handle in JAX.

**Comment by jakevdp** [comment]
I've been experimenting with a general block sparse format on this branch: https://github.com/google/jax/compare/main...jakevdp:jax:block-bcoo

On the lower level, we've been experimenting with some efficient block-sparse matmul operations via jax-triton: https://github.com/jax-ml/jax-triton/blob/7a1c0d00cbfa80f8207b2d5e021d693a68a8138b/examples/pallas/blocksparse_matmul.py#L33

I have no definite plans to land it in `jax.experimental.sparse`, but if there are compelling use-cases I could be encouraged to finish the implementation

**Comment by renecotyfanboy** [comment]
Well, I'm not very much into ML architectures so I don't have use cases in mind for this specific field. However in my field (astrophysics) we require to do a lot of Matrix.Vector reductions using matrices which are well-defined in the BSR format 
I'll take a look at this in the meantime, ty for answering so quickly !

**Comment by jakevdp** [comment]
I'm going to close this, as BSR and other matrix formats are not currently on our roadmap.
