### ISSUE TITLE
Layers with state in stax

### ISSUE THREAD

**Issue by joaogui1** [google/jax#1454]
So, there are some layers where it would be better if we could keep an state, for example batch normalization and LSTMs.
I think this here kind of solves it (but maybe it's an abuse of python?)
```
   def funs():
      def init_fun():  
           return 1
      def apply_fun(x):
          apply_fun.states += 2
          return x*apply_fun.states
      apply_fun.states = 1
      return init_fun, apply_fun
```
What do you think of a solution like this?

**Comment by shoyer** [comment]
JAX’s function transformations (jit, grad, etc) will not work properly if you mutate state. So I don’t think this is really a viable option.

**Comment by joaogui1** [comment]
Oh, got it, thanks!
