### ISSUE TITLE
latest release requires jax_array config set to True in order to import Optax

### ISSUE THREAD

**Issue by krahnikblis** [google/jax#14544]
### Description

i don't know if this is a "bug" per se, but today's release breaks existing scripts, yet per the error hint it can be resolved. simply importing Optax after importing Jax causes the error

following the error's hint/instruction, if you add these lines configuring for `jax_array`, the Optax import succeeds as normal. i don't know if it's good or bad to do this `jax_array` config, so doing this might set me up for other problems?

EDIT: posted 3 mins too soon, yes this `jax_array=True` setting causes downstream problems, appears to have caused this other error: 
```python
TypeError: Unsupported type for elements in `arrays`: <class 'jaxlib.tpu_client_extension.PyTpuBuffer'>'
```
/EDIT

```python
import jax
### without these 2  newly required lines, Optax import fails:
from jax.config import config as jax_cfg
jax_cfg.update("jax_array", True)
###
import optax
```
error (without the config) is reported at:
```python
---> 17 import optax
...
ValueError: in_shardings and out_shardings should not be the unspecified singleton value. Please enable `jax.Array` to use this feature. You can use jax.config.update('jax_array', True) or set the environment variable  JAX_ARRAY=1 , or set the `jax_array` boolean flag to something true-like.
```

### What jax/jaxlib version are you using?

0.4.4

### Which accelerator(s) are you using?

TPU

### Additional system info

Colab Pro

**Comment by yashk2810** [comment]
I am confused. What is the error? Or did you end up resolving this? The description is not very clear.

**Comment by yashk2810** [comment]
Did you upgrade from 0.3.35 to 0.4.4 directly or were you using 0.4.3 before?

**Comment by krahnikblis** [comment]
yeah sorry that's out of order from chronology the way i wrote/edited...
first i did:
import latest jax > import optax >>> error about jax_array needs to be True
so then i try:
import jax > import/set sax config ad advised > import optax >>> success yay optax simply imports!
but then:
run usual program >>> get error about array type/PyTpuBuffer

**Comment by yashk2810** [comment]
If you upgraded from 0.3.25 -> 0.4.4 directly, please downgrade to 0.3.25 because JAX won't work with >= 0.4 on colab TPU because it is on an old architecture.

If you upgraded from 0.4.3 -> 0.4.4, then I need to investigate :)

**Comment by krahnikblis** [comment]
> Did you upgrade from 0.3.35 to 0.4.4 directly or were you using 0.4.3 before?

for whatever reason, in Colab i can't use the pre-installed Jax for the other libraries i install (i think one of them sneaky upgrades the jax version without upgrading jaxlib? i don't know how to begin to diagnose that), so at the top of my script i have `pip install -U jax jaxlib` which gets the latest of those. usually this is fine and prevents the errors i get with the default Colab Jax version, but today, this

> If you upgraded from 0.3.25 -> 0.4.4 directly, please downgrade to 0.3.25 because JAX won't work with >= 0.4 on colab TPU because it is on an old architecture.

i think, per above, one/more of the libraries i'm using requires (and installs without permission) a higher Jax version than Colab default. i've adjusted this already and specified 0.4.3 and my notebook is currently running per usual (i.e. now all the problems that it raises should be my own fault)

i've been playing with my notebook mostly daily, with this `pip install -U` method, for months. seems the 4.x versions have been around all year, so TPU has worked on these versions so far (or maybe, my other TPU memory allocation/fragmentation issues are caused by this?)

i find using deprecated versions counter-intuitive; usually one wants all the latest versions, patches, drivers, fixes, etc., so specifically downgrading or using an obsolete/deprecated version won't scale well and will cause more and more conflicts in the future as other libraries continue to move on. especially with **all** of these products  (Colab environment, TPU hardware, JAX and Optax software) coming from a single service provider, it should be the case that everything is 100% inter-compatible (i.e., i'd expect Google hardware to work with Google software more so than/before Google software OR hardware works with other software like [_dare i use such a dirty word_] pytorch [_yuck, sorry, just making a point; sometimes you gotta curse_]

**Comment by krahnikblis** [comment]
ok @yashk2810 i found what's causing a sneaky JAX upgrade - it's y'all! 
installing Google Flax causes an update of Google Jax to the version that you say is not compatible with Google TPUs on Google Colab! 

right here - https://github.com/google/flax/blob/main/setup.py Google Flax requires Google "jax>=0.4.2"
this setup file runs a function `from setuptools import setup` >> where `setup` is a library from https://github.com/pypa/setuptools/blob/main/setup.py which uses the `install_requires` list of software and [does that "sneaky" install](https://github.com/pypa/setuptools/blob/bd37bfc622a6f2220c2e4e30b18f2cd2904b7da6/docs/references/keywords.rst) i described above 

so, when i install Flax in Colab, it installs Jax 4.X. **but it doesn't install the accompanying Google jaxlib** (why not?), which then causes extra errors, so that's why i had included the install of the latest Jax versions at the top of my scripts, to avoid the jaxlib error... 

so here we are, Google Flax says i have to have Google Jax > 4.x, but Google Jax says i can't because Google TPU can't handle the non-obsolete stuff, and Google Optax just can't even...

_je suis perplexe_

**Comment by jakevdp** [comment]
Hi @krahnikblis – thanks for the question. Since Colab TPUs are only compatible with jax v0.3.25 and older, you'll also have to use a compatible flax version. I believe flax v 0.6.4 is the last version compatible with jax v0.3.25.

**Comment by jakevdp** [comment]
The reason installing flax only updates jax and not jaxlib is because flax pins only jax, not jaxlib: https://github.com/google/flax/blob/60ab1ccb53ec33ca6a54beebccf83d3b404b23ca/setup.py#L29

The reason jax does not pin jaxlib is becuse the jaxlib installation is platform-specific, and in general pypi does not have support for expressing platform-specific dependencies.

In either case, though, if you follow the installation documentation for [jax](https://github.com/google/jax#installation) or [flax](https://github.com/google/flax#quick-install) you should get the appropriate libraries installed.

**Comment by krahnikblis** [comment]
thanks, i'll try that older Flax version, and i see some other posting similar issues on the Flax side and i'll watch those as well...
