### ISSUE TITLE
Add token_type to public API

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#14551]
We are using `token_type` in [mpi4jax](https://github.com/mpi4jax/mpi4jax) to define stateful custom call operators (and not have them optimized out).

Would it be possible to add that to the public API [here](https://github.com/google/jax/blob/main/jax/interpreters/mlir.py) so we can do

```python
from jax.interpreters.mlir import token_type
```

instead of importing from `jax._src`?

**Comment by hawkinsp** [comment]
Sure. The changes that locked down the visibility of exports were mostly at this point intended to capture the world as it is (i.e., figure out what people are actually using from these modules). I'll readd this export.

(We're thinking more broadly about more stable extension points for custom ops, but that's not the goal of the changes so far.)
