### ISSUE TITLE
Potential bug in Student's T random sampling

### ISSUE THREAD

**Issue by Tennessee-Wallaceh** [google/jax#14597]
### Description

The current implementation of Student's-t sampling uses the same random key to generate both normal and gamma components.
See current implementation below (from jax._src.random line 1485)
```python
  df = lax.convert_element_type(df, dtype)
  key_n, key_g = _split(key)
  n = normal(key_n, shape, dtype)
  two = _lax_const(n, 2)
  half_df = lax.div(df, two)
  g = gamma(key_n, half_df, shape, dtype)
  return n * jnp.sqrt(half_df / g)
```

To me, it appears that line 1490 should use `key_g`, that is `g = gamma(key_g, half_df, shape, dtype)`.

The impact of this is not immediately clear to me, but this could be subtly  biasing any code currently sampling Student's-t.

### What jax/jaxlib version are you using?

jax v0.4.1

### Which accelerator(s) are you using?

n/a

### Additional system info

n/a

**Comment by jakevdp** [comment]
That looks like a bug – are you interested in opening a PR with the fix?

**Comment by Tennessee-Wallaceh** [comment]
Hi, yes I can do that now.

**Comment by Tennessee-Wallaceh** [comment]
PR ready for review here - https://github.com/google/jax/pull/14598
