### ISSUE TITLE
README's conda-based installation with CUDA fails to install cuda-aware jaxlib

### ISSUE THREAD

**Issue by tlangfor** [google/jax#14606]
### Description

In the README, the provided conda installation step for CUDA-aware Jax sometimes pulls in a CPU-only build of jaxlib.  

```
$ conda install jax cuda-nvcc -c conda-forge -c nvidia

The following NEW packages will be INSTALLED:

  jax                conda-forge/noarch::jax-0.4.4-pyhd8ed1ab_0
  jaxlib             conda-forge/linux-64::jaxlib-0.4.4-cpu_py311h7146453_1
```

This was noted in issue #189, with a solution, but the README was not updated to include the fix. 

```
conda install jaxlib=*=*cuda* jax cuda-nvcc -c conda-forge -c nvidia
```

This ensures that the cuda build of jaxlib is installed. 

### What jax/jaxlib version are you using?

0.4.4

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux

**Comment by tlpss** [comment]
came here to say the exact same thing af struggling for a while to get the GPU-enabled conda install working.
I agree it would be very convenient to include this in the readme

**Comment by hawkinsp** [comment]
Done! Hope that helps.

**Comment by tlangfor** [comment]
Awesome, thanks @hawkinsp!
