### ISSUE TITLE
jitting a method inside class performs __init__ again

### ISSUE THREAD

**Issue by yonghakim** [google/jax#14619]
### Description

Hi,

Seems that jitting method inside Class does operation in __init__() one more time.
no-jit and outside-jit work as I expected (theta: 2) but inside-jitted method divides theta once again(theta: 1)

Should I avoid manipulating input args in __init__()?

Thanks!

```python
import jax


class A:
    def __init__(self, theta=0.,):
        self.theta = theta // 2

    def _tree_flatten(self):
        children = (self.theta, )
        aux_data = {}
        return children, aux_data

    @classmethod
    def _tree_unflatten(cls, aux_data, children):
        return cls(*children, **aux_data)

    @jax.jit
    def solve_jit(self):
        return self.theta

    def solve_no_jit(self):
        return self.theta


jax.tree_util.register_pytree_node(A, A._tree_flatten, A._tree_unflatten)

theta = 4
print(theta, ': theta original')

solver = A(theta=theta)
print(solver.theta, ': theta after __init__')

a = solver.solve_no_jit()
b = jax.jit(solver.solve_no_jit)()
c = solver.solve_jit()

print(a, ': theta from no-jit', )
print(b, ': theta from outside_jit', )
print(c, ': theta from inside-jit', )

```

> 4 : theta original
> 2 : theta after __init__
> 2 : theta from no-jit
> 2 : theta from outside_jit
> 1 : theta from inside-jit
> Process finished with exit code 0

### What jax/jaxlib version are you using?

jax 0.4.1,  jaxlib 0.4.1

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9, M1 Mac

**Comment by soraros** [comment]
This is the expected behaviour. It has to do with the line `cls(*children, **aux_data)` in `_tree_unflatten` which runs automatically when `A` passes across the JIT boundary.

> Should I avoid manipulating input args in init()?

Short answer: yes. You can write a smart constructor `init` and move the logic there. Something like

```python
class A:
  ...
  @classmethod
  def init(cls, ...):
    return cls(theta // 2, ...)
  ...
```

**Comment by jakevdp** [comment]
Another approach is to avoid calling `__init__` within `tree_unflatten`. This can be helpful for other reasons as well; see https://jax.readthedocs.io/en/latest/pytrees.html#custom-pytrees-and-initialization

**Comment by yonghakim** [comment]
@soraros, Thanks for the answer!

I tried to apply your tip but wasn't able to use it properly. Could you be more elaborate? How can I use that `init` ?

And I hope this can be included in documents (https://jax.readthedocs.io/en/latest/faq.html?highlight=class%20static#strategy-3-making-customclass-a-pytree) to prevent people encounter this.

**Comment by yonghakim** [comment]
@jakevdp, aa I didn't reach that part... Thanks!
