### ISSUE TITLE
BCOO sparse-dense matrix-matrix products produce high memory usage due to nonzero entry copies

### ISSUE THREAD

**Issue by aterenin** [google/jax#14642]
### Description

If we have a BCOO matrix `A` of size `(n,m)` with `z` nonzeroes, and a dense matrix `B` of size `(m,p)`, and multiply them, for some reason arrays of size `(z,p)` are produced by JAX during computation. This results in very high memory usage. MWE:
```python
import jax 
import jax.numpy as jnp
import jax.random as jr
from jax.experimental.sparse import BCOO

key = jr.PRNGKey(0)
k1,k2 = jr.split(key)
n = 1000
m = 777
p = 11
nonzeroes = jnp.stack((jnp.arange(0,m), jnp.arange(p,m+p)), axis=-1)
values = jr.normal(k2, (m,))
target = jr.normal(k1, (n,p))

def sparse_op(p):
    x1 = nonzeroes[...,0]
    x2 = nonzeroes[...,1]
    values = (x1 - x2)**2 / p
    matrix = BCOO((values, nonzeroes), shape=(n,n), unique_indices=True)
    return (matrix @ target).sum()

graph = jax.xla_computation(sparse_op)(1.0)

with open("t.dot", "w") as f:
    f.write(graph.as_hlo_dot_graph())
```

The computational graph for this MWE is here: [t.pdf](https://github.com/google/jax/files/10815587/t.pdf). Observe that `dot.51` has shape `f32[777,11]` where the computation should only require `f32[777]` arrays since the nonzero arrays are the same.

To avoid this, I've tried tricks with `vmap`, but this still results in the same computational graph. I've also tried computing the columns of the result one-by-one, then concatenating them, but unless I am mistaken this also results in copies of the array being materialized somewhere, since I'm running out out of memory while doing this. To give a rough sense of scale, my nonzero entry arrays are ~100mb in size, so a handful of copies is okay, but I really don't want to produce 500 of them.

Thanks for reading! If there are any ideas on how to fix or work around this, these would be greatly appreciated!

### What jax/jaxlib version are you using?

v0.4.4

### Which accelerator(s) are you using?

N/A

### Additional system info

N/A

### NVIDIA GPU info

N/A

**Comment by jakevdp** [comment]
Hi, thanks for the report!

It looks like this is coming from this line: https://github.com/google/jax/blob/a0f635430757cb4afabf5df4406e8bae9be469d2/jax/experimental/sparse/bcoo.py#L707-L708

For a sparse-dense matrix product `Asp @ B`, this intermediate result is of shape `[Asp.nse, B.shape[1]]`

I think it would be possible to re-express this to limit `prod` to the same shape as `B` – let me think about that for a bit.

**Comment by jakevdp** [comment]
One note on this: the size of the memory usage here actually reflects the number of computations necessary to compute the sparse-dense matrix product. If you have a sparse matrix `A` and a dense matrix `B`, the number of individual element multiplications required to compute `A @ B` is `A.nse * B.shape[1]`, and in general there's no way to do better than that if the `nse` are all unique indices.

So this large memory allocation actually reflects the true intrinsic computational complexity of the operation.

**Comment by aterenin** [comment]
I agree - the total amount of operations required here is `A.nse * B.shape[1]`. However, the memory complexity is smaller, by reusing the `A` arrays for each column of `B`. 

This kind of memory optimization is similar to JAX' while loop and scan functionality, such as the one used in the conjugate gradient solver, which if I am not mistaken does not unroll the loop to avoid memory blowup.

**Comment by jakevdp** [comment]
Right, agreed that in some cases it would make sense to batch this operation and do it sequentially in order to save on memory usage, but it's hard to come up with general heuristics for when doing so would be beneficial. In some cases you definitely *do* want the full array to be allocated at one, for example to take advantage of parallel registers in your GPU.

**Comment by jakevdp** [comment]
Right – but sometimes dispatching those operations in separate calls would not be the most efficeint approach. Really what you're asking for an optimization that should be done by the compiler, but the XLA compiler does not support this sort of optimization at the moment. So it's not obvious to me how we can fix the problem in the meantime.

Since you mention cuSparse: on GPU we do have the ability to lower these operations to cuSparse if you wish (set `jax_bcoo_cusparse_lowering=true`). It's not enabled by default right now because of some issues in corner cases, but I'm actively working on getting those fixed (you can follow the progress in #14531).

**Comment by aterenin** [comment]
To add just one more way of thinking that came into my head to this: another analogy to think of is dense matrix-matrix multiplication, which for matrices A, B can be written (AB)_{ik} = \sum A_{ij} B_{jk}. The compute cost is O(n^3), and memory cost is the same if we materialize the entire array A_{ij} B_{jk} before winning over j. But modern implementations avoid this by not materializing this array, instead giving a memory complexity of O(n^2) - my issue can be viewed as the sparse analog of this.

**Comment by jakevdp** [comment]
Sure, and in cusparse I think you'll find that is the case. But XLA does not have built-in sparse matmul primitives, so I don't know any way to make that happen in general in the XLA reference implementation. I'm not disagreeing with you, I'm just saying that what you want can't currently be done in a general manner in XLA.

**Comment by jakevdp** [comment]
... that's why my main focus at the moment is to get cuSparse lowering up and running!

**Comment by jakevdp** [comment]
Let me know how the cusparse lowering works! You currently need two things:
1. set `jax_bcoo_cusparse_lowering=true`
2. jit-compile the matmul operations

We're hoping to soon have both of those things done by default, so just running `Asp @ b` on a GPU will use cusparse rather than XLA.

**Comment by aterenin** [comment]
Looks like it works! Just ran the modified MWE
```python
import jax 
import jax.numpy as jnp
import jax.random as jr
from jax.experimental.sparse import BCOO

jax.config.update("jax_bcoo_cusparse_lowering", True)

key = jr.PRNGKey(0)
k1,k2 = jr.split(key)
n = 1000
m = 777
p = 11
nonzeroes = jnp.stack((jnp.arange(0,m), jnp.arange(p,m+p)), axis=-1)
values = jr.normal(k2, (m,))
target = jr.normal(k1, (n,p))

def sparse_op(p):
    x1 = nonzeroes[...,0]
    x2 = nonzeroes[...,1]
    values = (x1 - x2)**2 / p
    matrix = BCOO((values, nonzeroes), shape=(n,n), unique_indices=True).sort_indices()
    return (matrix @ target).sum()

graph = jax.xla_computation(sparse_op)(1.0)

with open("t.dot", "w") as f:
    f.write(graph.as_hlo_dot_graph())
``` 
where the only differences are `jax.config.update("jax_bcoo_cusparse_lowering", True)` and `.sort_indices()`, and it produces this computational graph: [t.pdf](https://github.com/google/jax/files/10819090/t.pdf). I don't see any large-memory arrays in that, so it looks like it fixes the problem. 

Tried the ~large-ish example in my codebase which prompted this issue, and it now runs! Amazing! 🎉

**Comment by jakevdp** [comment]
Great to hear! I'd like to keep this issue open to track the non-cusparse issue if you don't mind... perhaps we can find some way of pushing batching logic to the compiler.

**Comment by aterenin** [comment]
I don't mind at all - there are many settings where supporting sparse-dense matrix-matrix products is useful! Thanks very much for taking a look at this!

**Comment by jakevdp** [comment]
I'm going to close this, because we don't have plans at the moment to further improve BCOO-BCOO matmul.
