### ISSUE TITLE
FFTs on CPUs use only single thread

### ISSUE THREAD

**Issue by eelregit** [google/jax#14664]
CPU FFTs is using ducc (https://github.com/google/jax/pull/12122), but do not seem to use multithreads.
I tried export `DUCC0_NUM_THREADS=8` (https://gitlab.mpcdf.mpg.de/mtr/ducc/-/blob/1c8af2a792c1aeaf9d5c5425bbaa17b81e3c8cfc/ChangeLog#L51) and that didn't work either.

**Comment by hawkinsp** [comment]
Yes, this is a known limitation at the moment. I'll look into it.

**Comment by hawkinsp** [comment]
@mreineck Indeed, that would have been exactly what I wanted to look for next. Thanks!

I suspect I'm going to want to fix this by changing XLA to use ducc for its FFTs. Currently XLA uses Eigen FFTs on CPU, which are both inaccurate and slow. JAX overrides them with ducc. If we upstream that work to XLA JAX can inherit that support and within XLA there is easy access to a thread pool.

@cantonios might be looking at this already, I'm not sure.

**Comment by cantonios** [comment]
I'm away this week, but will hopefully have some time to look at it when I get back.

**Comment by jmsull** [comment]
I'm also in seeing the better jax FFTs on CPU - would be great if you get a chance to look at changing XLA to ducc FFTs!

**Comment by jon-chuang** [comment]
Hello, I've worked with parallelising FFTs for cryptography and have contributed to pytorch. I would love to be assigned this issue to get my feet wet contributing to JAX/XLA.

**Comment by jon-chuang** [comment]
@hawkinsp could you explain why you expect getting XLA to use ducc will fix this for JAX? 

Don't we have to fix for non JIT which uses the JAX runtime impl? 

Secondly, how does JAX override the XLA runtime's dispatch of operations?

**Comment by jon-chuang** [comment]
Another question: I can't seem to find where `jaxlib/cpu/ducc_fft_generated.h` gets generated. It's not in any Bazel `BUILD` file.

**Comment by hawkinsp** [comment]
@jon-chuang having XLA use ducc would make it easier to access the Eigen thread pool, which makes parallelism easy to do.

It would also reduce code complexity (we could just delete the ducc code from JAX and use XLA's implementation).

If you want JAX to use XLA's FFT so you can try JAX with a candidate XLA change, just delete this registration: https://github.com/google/jax/blob/0d3272488224ee1cab71aa84a667b7626c540021/jax/_src/lax/fft.py#L181
which overrides the default (XLA) implementation on CPU with JAX's ducc wrapper.

**Comment by cantonios** [comment]
Fixed with XLA change [da67903](https://github.com/openxla/xla/commit/da67903a4c1128a70a7b30fae6c263dbf9a40f23)

**Comment by hawkinsp** [comment]
#18404 will stop JAX from using its own custom call and instead use XLA's FFT implementation, and that implementation is now multithreaded (see above).
