### ISSUE TITLE
jax.lax.dot_general has minimal documentation

### ISSUE THREAD

**Issue by imh** [google/jax#14670]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

----------

The docs for [`jax.lax.dot_general`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.dot_general.html) are unclear. In particular, the `dimension_numbers` argument isn't clear to me.

**Comment by mattjj** [comment]
Thanks for the request!

Just brainstorming ways to improve: do the [XLA HLO docs](https://www.tensorflow.org/xla/operation_semantics#dotgeneral) clarify the `dimension_numbers` argument? Or are those unclear too?

There is a [reference implementation in terms of standard `numpy`](https://github.com/google/jax/blob/d27735820049bdb9b0828ee95abf86d1ec50f1f9/jax/_src/lax_reference.py#L208) which we could point to, but I don't think it's concise/clear enough to be helpful.

(By the way, I went to elementary school with someone with your name... any chance you're from The Peninsula originally?)

**Comment by jakevdp** [comment]
I wonder if it might make sense to add a note similar to what we have in [`lax.gather`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.gather.html), something along the lines of:

> The semantics of `dot_general` are complicated, but most users should not have to use it directly. Instead, you can use more user-friendly functions like `jax.numpy.dot`, `jax.numpy.tensordot`, `jax.numpy.einsum`, and others which will call dot_general` in the background. If you really want to understand `dot_general` itself, we recommend reading XLA's [DotGeneral](https://www.tensorflow.org/xla/operation_semantics#dotgeneral) documentation.

**Comment by imh** [comment]
@jakevdp A note like that would be helpful.

@mattjj The XLA docs are more helpful, but still not totally clear. This line is the most helpful

> It follows that the resulting dimension number starts with the batch dimension, then the 'lhs' non-contracting/non-batch dimension, and finally the 'rhs' non-contracting/non-batch dimension.

However, "It follows that" makes it unclear whether it's implied by something about the example, or if it's general to the function. In the jax docs, it would be useful to simply specify output dimensions. If it's just a general property of the return, a change like this could improve things greatly:

> Returns: An array whose first dimensions are the batch dimensions, followed by the the 'lhs' non-contracting/non-batch dimensions, and finally the 'rhs' non-contracting/non-batch dimensions.

**Comment by jakevdp** [comment]
Proposed doc update in https://github.com/google/jax/pull/14674; let me know what you think!

**Comment by imh** [comment]
This was great, thank you!
