### ISSUE TITLE
Jax for Web? (JS api or web assembly guide)

### ISSUE THREAD

**Issue by bionicles** [google/jax#1472]
Hi,

it’s not clear how to make production level decentralized projects with Python, and the GIL is often a big limit. 

Do you think it would be possible to make Jax.js, or (less ideally) use it with web assembly?

Just curious because, If there were a JavaScript API for Jax, or some clear path to make it work with WASM inside a web worker, then I could die happy because I could finally do everything in JavaScript ... Jax plus Ramda sounds like a dream. Showing your work in React sounds epic. And there are a LOT of JavaScript devs itching to play with deep learning. This could be their gateway drug. 

Tensorflow JS is cool but, having spent wayyy too much time working on Tensorflow, I find it to be a bit, ah, feature-creepy, and I guess JAX could really help with that

Thanks in advance for any help, and I’d love to contribute and meet up or chat on this,

Bionicles

**Comment by samuela** [comment]
A few ideas come to mind:
* Run Python in the browser via some WA-based interpreter/implementation.
* Compile the whole model down to XLA (just like `jit` does) and then figure out a way to run that in the browser.
* Develop and train the model in JAX, then export it to a portable format, eg ONNX, etc.

**Comment by JonathanSum** [comment]
@gnechula
I guess it is not difficult to make JAX run in javascript with webassbmy. The main problem is what JAX requires? I see people run numpy or sklearn in javascript with webassbmy, but it is difficult to do this with Pytorch because Pytorch will require a couple GB of cuda library to be installed. But how about JAX? Does it require other libraries to be installed?

**Comment by gnecula** [comment]
The closest we are today to running JAX in the browser is by way of jax2tf and TFjs. See, e.g., [this](https://github.com/google/jax/tree/97a5719fcb40af7231b5f803f965063538282f8e/jax/experimental/jax2tf/examples/tf_js).

**Comment by gnecula** [comment]
Please feel free to re-open if you want to discuss further.

**Comment by josephrocca** [comment]
Some notes on this:

* @JonathanSum PyTorch has a CPU backend, and until we get WebGPU plus a CUDA-to-WGSL transpiler (or similar), the best bet would be to at least start with a Wasm port of the CPU backend. There are people working on this (e.g. [see here](https://github.com/pyscript/pyscript/issues/85#issuecomment-1114287186)). I think it would be the same for JAX - i.e. just start with the CPU side of things first.
* There is a lot of energy around Python-in-the-browser at the moment, with [Pyodide](https://github.com/pyodide/pyodide/) becoming more mature, Anaconda (the company) releasing [PyScript](https://github.com/pyscript/pyscript), and people like @wolfv working on improving the [package management/resolution/linking situation](https://twitter.com/wuoulf/status/1523972325833691136).
* jax2tf is slowly but steadily moving toward a point where it works "out of the box" which allows us to do inference in the browser with [tfjs](https://github.com/tensorflow/tfjs)/[tflite](https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite)/[onnx](https://github.com/microsoft/onnxruntime/tree/master/js/web), but this doesn't help if you want to actually run JAX in the browser (e.g. to get JAX working in [JupyterLite](https://jupyter.org/try-jupyter/lab/)).
* I wonder whether there are any "core components" of JAX that are mostly pure C++ or C, which wouldn't be too hard to port as an initial first step. E.g. if it were possible to isolate the code that does the complicated "core" work for auto-differentiation and make a Wasm build of it, that could be fun to experiment with.

@gnecula Would you be interested in re-opening this just to keep it open as a possibility for people to discuss and think about?

**Comment by gnecula** [comment]
Currently the best way to run JAX "in the browser" is by way of Colab. Porting the JAX backend to the browser seems like la large project that is not currently staffed. I can leave this open.

**Comment by wolfv** [comment]
Hi @josephrocca thanks for the mention! I would be happy to support such an effort. We're workign on emscripten-forge to package a number of `python` packages in a familiar way (similar to `conda-forge`), and we're making them installable / usable in the browser.
I do not know what's needed for JAX. Especially when it comes to code-generation, things might be more tricky.

PS: https://github.com/conda-forge/jaxlib-feedstock/blob/main/recipe/meta.yaml is the conda-forge recipe for `jaxlib` – getting official help + CUDA support there would also be a big deal for conda-forge.

**Comment by josephrocca** [comment]
I've been experimenting with getting jaxlib compiling to wasm with Pyodide's build tooling, and I'm a long way from having anything working, but I'm at least trying to smooth some sharp edges for those who come after me in attempting this (assuming that I hit into a road block that I can't get past at some point).

I've been documenting my progress building it here: https://github.com/pyodide/pyodide/issues/2198 and @hoodmane (core Pyodide dev and hero of the people) has been helpful and fast in fixing some stuff to make the build process less hacky/buggy:

* https://github.com/pyodide/pyodide/issues/2736 and incoming fix: https://github.com/pyodide/pyodide/pull/2738
* https://github.com/pyodide/pyodide/issues/2726 and incoming fix: https://github.com/pyodide/pyodide/pull/2734
* (amongst other tips and help...)

I'm currently working on an error related to threading:
* https://github.com/google/jax/issues/11168
* https://github.com/pyodide/pyodide/discussions/2720

I thought Emscripten could handle threads now that `SharedArrayBuffer`s are back, but I'm following hoodmane's suggestion to get it building without threads, which seems like a good first step if that's possible.

As you can probably tell I don't really have the expertise for this sort of thing, but I'm learning as I go. If anyone wants to send tips/ideas or help try stuff out, please let me know.

(@gnecula, btw, RE your comment "I can leave this open" --  I see you tagged this issue P3, but potentially forgot to open it, or thought it was already open?)

**Comment by zhangqiaorjc** [comment]
I'll keep this open with P3 (no schedule) since there are contributors who are still working on this.

**Comment by JonathanSum** [comment]
Yeah. If it happens, I will try to make a demo on CV(including Image Generation), NLP, or ASR. I am looking forward to seeing this happens.

**Comment by gnecula** [comment]
There is not progress afaik, and I do not think there is anybody working on this.

**Comment by JacobFV** [comment]
😭😭😭


On Nov 28, 2023, at 08:32, George Necula ***@***.***> wrote:

﻿

There is not progress afaik, and I do not think there is anybody working on this.

**Comment by josephrocca** [comment]
Last month @ryanking13 mentioned they were going to look into a wasm build for use in Pyodide:

* https://github.com/pyodide/pyodide/issues/2198#issuecomment-1748454124

Gyeongjae has the chops to get this done, but I'm sure how high up on their priority list this is at the moment.

**Comment by gszep** [comment]
Can running JAX models in the browser be done in the following steps?
1. [Export StableHLO using JAX export module](https://openxla.org/stablehlo/tutorials/jax-export)
2. [Use IREE compiler to emit WGSL code](https://github.com/iree-org/iree/tree/main/experimental/web/sample_webgpu)

Maybe relevant repos:
* Burn (rust ML framework with wgpu backend) https://github.com/tracel-ai/burn
* wgpu in python https://github.com/pygfx/wgpu-py, https://github.com/pygfx/pygfx
* rendering in JAX https://github.com/JoeyTeng/jaxrenderer
* TVM compiled example https://github.com/mlc-ai/web-stable-diffusion
* IREE compiler wgpu tracking https://github.com/iree-org/iree/issues/13702

**Comment by agriyakhetarpal** [comment]
The primary blocker for this, at the moment, has been a way to proceed forward with gh-11168.

**Comment by gszep** [comment]
Suppose the ultimate aim is to simply run exported JAX functions in the browser (i.e. inference time, no need to train etc.). My sense is that this can be one without pyodide?

**Comment by ekzhang** [comment]
Hey there — I've been really interested in NumPy (and generally WebGL/WebGPU-based computing) in the browser for a while now and a big fan of JAX. For the past few months as a side project I've been working on making `import numpy` / `import jax` kind of _just work_ in the browser, with the same API. But with a pure-JS compiler, and backends designed for web use cases: Wasm for CPU, and WebGPU for GPU compute.

The rationale here is that XLA is a massive project, and even if you could compile it to Wasm, it's probably overkill for the kinds of workloads you expect people to run in browsers, where the hardware differs between people anyway. If XLA can get you within 1-2% of optimal, maybe jax-js gets you within 3-5x of optimal, and that's good enough since it's 100x better than anything else anyway!

So I'm working on a pure JS compiler and so on without much prior background. I started with Autodidax (which works as a frontend to mimic JAX very closely) and then spent a bunch of time trying to figure out the backend. It's actually been going pretty smoothly so far and I'm almost done with `jax.jit()`, and then I can start making some browser demos.

I [wrote a bit more about this](https://substack.com/home/post/p-163548742) here. It's not open-source quite yet, but I would love any feedback from any of y'all who are experts on ML compilers. Also I'm happy to add anyone to the repository.

**Comment by ekzhang** [comment]
I have finally released this! https://github.com/ekzhang/jax-js

There is a writeup here with a bunch of details about how it works: https://ekzhang.substack.com/p/jax-js-an-ml-library-for-the-web

**Comment by anutosh491** [comment]
Hi, 

This is Anutosh here (llvm, clang, Jupyterlite maintainer/contributor)

I just got the Numba JIT compiler to WebAssembly some days back and presented my work at the Numba community call. 

This is the first working demonstration of Numba compiling and executing Python and NumPy code entirely inside the browser through JupyterLite. Try it out here : https://notebook.link/@anutosh491/numba

That brings me to Jax jit and XLA. It would be great to see it running in Jupyterlite just like I did with Numba (probably not switching to JS like the comment above shows but working with the present source code)

 I'd like to ask if there's still interest here ? If yes feel free to reach out !

For the record I have been involved in getting quite some compiler infrastructures to Jupyterlite like 
- compiling clang-repl to wasm to support Jupyter's C++ kernel ([demo1](https://notebook.link/@quantstack/xeus-cpp), [demo2](https://notebook.link/@quantstack/advanced_cpp))
- compiling lfortran to wasm to support Jupyter's Fortran kernel ([demo](https://lfortran.github.io/lfortran/lab/index.html?path=Mandelbrot.ipynb)
- compiling mlir python bindings & llvmlite to wasm ([demo](https://notebook.link/@anutosh491/mlir_wasm))

**Comment by anutosh491** [comment]
Quick update following my earlier comment: I now have a working prototype of the original Python JAX package and XLA compiling and executing `jax.jit` functions entirely inside the browser through JupyterLite.


https://github.com/user-attachments/assets/96f44f77-dca7-4ec5-8218-d8019ebcfefc

This is the real JAX/XLA pipeline—not model export, a JavaScript reimplementation or remote compilation. 
JAX traces the function, XLA lowers it for `wasm32-unknown-emscripten`, emits WebAssembly objects, links them in-process with LLD, dynamically loads the resulting modules and executes the compiled function in the browser.

The current prototype is CPU-only, single-device and single-process. The main work involved a Bazel Emscripten toolchain, wasm32 ABI corrections, a threadless local PJRT CPU path, the XLA WebAssembly execution path, and packaging JAX’s _jax/MLIR extensions around a common runtime.

I’m now exploring how to package this work reproducibly through emscripten-forge. 

Before deciding how far to take the upstream integration, I’d really appreciate feedback from the JAX and XLA maintainers to know if there's interest in supporting this and which parts might make sense upstream. I’ll share an executable notebook and more technical details soon.
