### ISSUE TITLE
Unexpected NaN in jax.jacfwd of polynomial with variable coefficients

### ISSUE THREAD

**Issue by spenrich** [google/jax#14745]
### Description

In the following code, I define a polynomial function with fixed coefficients, and one with coefficients that can be provided as an argument.
```python
import jax
import jax.numpy as jnp

# Define a quadratic polynomial with fixed coefficients
f_fixed = lambda x: x**0 + x**1 + x**2

# Define a polynomial with variable order and coefficients
def polynomial(x, cs):
    powers = jnp.arange(cs.size)
    monomials = x**powers
    y = jnp.sum(cs * monomials)
    return y

order = 2
cs = jnp.ones(order + 1)  # matches `f_fixed` above
f = lambda x: polynomial(x, cs)

# Evaluate each polynomial and their derivatives at `x = 0`
for x in [1., 0.]:
    print('x = {}'.format(x))
    print('-------')
    print(f_fixed(x), ',', jax.jacfwd(f_fixed)(x))
    print(f(x), ',', jax.jacfwd(f)(x))
    print()
```
The output of this code is:
```python-traceback
x = 1.0
-------
3.0 , 3.0
3.0 , 3.0

x = 0.0
-------
1.0 , 1.0
1.0 , nan
```
The functions and their derivatives match as expected at `x = 1`, but I get a NaN for the derivative of the second implementation at `x = 0`. This is unexpected to me, but perhaps there is nuance I'm failing to see. Any ideas?

### What jax/jaxlib version are you using?

jax v0.4.4, jaxlib v0.4.4+cuda11.cudnn86

### Which accelerator(s) are you using?

CPU, GPU

### Additional system info

Python 3.10.4, Ubuntu 22.04

**Comment by mattjj** [comment]
Thanks for raising this! It's a bug.

Luckily it's one I think we know how to fix: this is probably #14397, and [this comment in the thread](https://github.com/google/jax/issues/14397#issuecomment-1426386290) describes our fix plan.

**Comment by mattjj** [comment]
Is this blocking your work, i.e. do you need a workaround?

**Comment by spenrich** [comment]
Ah ok, sorry for missing that issue, and thank you!

**Comment by spenrich** [comment]
@mattjj currently yes it is blocking me. I have more complicated code that does polynomial spline fitting and evaluation that this bug has broken unfortunately.

**Comment by mattjj** [comment]
One workaround is to replace `x ** n` with an `int_pow(x, n)`, which is a function with a `custom_jvp` specialized to the case where `n` is an integer:

```python
import jax
import jax.numpy as jnp

# Define a quadratic polynomial with fixed coefficients
# f_fixed = lambda x: x**0 + x**1 + x**2

@jax.custom_jvp
def int_pow(x, n):
  return jnp.where(n == 0, jnp.ones_like(x), jnp.power(x, n))

@int_pow.defjvp
def int_pow_jvp(primals, tangents):
  x, n = primals
  x_dot, _ = tangents
  jac = jnp.where(n == 0, jnp.zeros_like(x_dot), n * int_pow(x, n - 1))
  return int_pow(x, n), jac * x_dot

f_fixed = lambda x: int_pow(x, 0) + int_pow(x, 1) + int_pow(x, 2)

# Define a polynomial with variable order and coefficients
def polynomial(x, cs):
    powers = jnp.arange(cs.size)
    monomials = int_pow(x, powers)
    y = jnp.sum(cs * monomials)
    return y

order = 2
cs = jnp.ones(order + 1)  # matches `f_fixed` above
f = lambda x: polynomial(x, cs)

# Evaluate each polynomial and their derivatives at `x = 0`
for x in [1., 0.]:
    print('x = {}'.format(x))
    print('-------')
    print(f_fixed(x), ',', jax.jacfwd(f_fixed)(x))
    print(f(x), ',', jax.jacfwd(f)(x))
    print()
```

Does that work for you?

**Comment by spenrich** [comment]
Looks like it should work -- I'll give that a shot. Thanks for the quick response!

**Comment by mattjj** [comment]
Great! Let us know if it doesn't work. In the meantime, I'll close this issue so we can consolidate further discussion on the other thread. Thanks again for raising it.

**Comment by mattjj** [comment]
We finally fixed #14397 btw!

**Comment by spenrich** [comment]
Awesome -- thanks for the fix and for following up on this thread!

**Comment by mattjj** [comment]
Sorry it took so long. We'll be faster on the next one...
