### ISSUE TITLE
AttributeError: 'UnspecifiedValue' object has no attribute '_parsed_pspec'

### ISSUE THREAD

**Issue by zxexz** [google/jax#14758]
### Description

I created a new colab notebook, and installed a new version of jax.
```
!pip install --upgrade -q pip jax jaxlib
```

When I run the following code:
```
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
from jax import random
import jaxlib
import inspect
print(f"tpu_driver_version: {inspect.signature(jax.tools.colab_tpu.setup_tpu).parameters['tpu_driver_version'].default}")
print(f"jaxlib version: {jaxlib.__version__}")
print(f"jax version: {jax.__version__}")
random.PRNGKey(0)
```

I get the following error:

```
tpu_driver_version: tpu_driver_20230216
jaxlib version: 0.4.4
jax version: 0.4.4

---------------------------------------------------------------------------

UnfilteredStackTrace                      Traceback (most recent call last)

[<ipython-input-4-f21cec99a362>](https://localhost:8080/#) in <module>
      8 print(f"jax version: {jax.__version__}")
----> 9 random.PRNGKey(0)

22 frames

UnfilteredStackTrace: AttributeError: 'UnspecifiedValue' object has no attribute '_parsed_pspec'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------


The above exception was the direct cause of the following exception:

AttributeError                            Traceback (most recent call last)

[/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py](https://localhost:8080/#) in threefry_seed(seed)
    824     # TODO(jakevdp): in X64 mode, this can generate 64-bit computations for 32-bit
    825     # inputs. We should avoid this.
--> 826     k2 = convert(jnp.bitwise_and(seed, np.uint32(0xFFFFFFFF)))
    827   return lax.concatenate([k1, k2], 0)
    828 

AttributeError: 'UnspecifiedValue' object has no attribute '_parsed_pspec'
```

### What jax/jaxlib version are you using?

jax 0.4.4, jaxlib 0.4.4

### Which accelerator(s) are you using?

TPU

### Additional system info

colab

**Comment by skye** [comment]
Colab TPU requires jax/jaxlib 0.3.25, which is the version that comes installed by default on TPU runtimes. We can't support newer versions of jax on Colab TPU at this time.

If possible, I recommend trying Kaggle Notebooks (https://www.kaggle.com/code, click on "New Notebook" near the top), which does support newer jax versions. You have to create an account and log in to get accelerator support. Once you do that, there's a new "TPU VM v3-8" accelerator option. This gives you a TPU notebook environment similar to Colab, but using the newer TPU VM architecture. This should be a less buggy, more performant, and overall better experience than the older TPU Node architecture (see [this blog post](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) for a brief overview of the difference).

If you do try Kaggle Notebooks, there's a known issue (https://github.com/google/jax/issues/14600) that causes the TPU runtime to take a while to come up, but that should only affect the first time you access the TPU in a session. Please file more issues if you run into any other problems!

Other options include applying to TRC (https://sites.research.google/trc/about/), which can provide free Cloud TPU VM credits, or trying out a Cloud TPU VM yourself (not free).

Hope this helps.

**Comment by skye** [comment]
Gonna close this issue since I don't think there's anything to do here, but please feel free to comment if you have more questions or comments.
