### ISSUE TITLE
`jax.make_jaxpr` incorrectly typed

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#14787]
### Description

The type annotation for the return value should be a 2-tuple if `return_shape=True`. Right now it is incorrectly fixed to just a `ClosedJaxpr`.

https://github.com/google/jax/blob/2ccd785e167ab424f0c0d79de7b549a7f94aea61/jax/_src/api.py#L2912

### What jax/jaxlib version are you using?

0.4.4

**Comment by mattjj** [comment]
I just ran into this in something I'm working on, will include the fix in that PR!
