### ISSUE TITLE
`flatten_func` generation in `register_pytree_with_keys`

### ISSUE THREAD

**Issue by ASEM000** [google/jax#14844]
Hello,

After reviewing the following code
https://github.com/google/jax/blob/b4ec72deaefa1094891829cd0b78efb5cc19c28b/jax/_src/tree_util.py#LL545-L571C4
If I understood correctly, if the user defines `flatten_func_with_keys` , `register_pytree_with_keys` will generate `flatten_func` registered with the non-key `jax` registry.

I think, In some scenarios, the overhead from the list comprehension required for conversion from `flatten_func_with_keys` to `flatten_func` can not be justified by the usability of registering the tree once.

Is it possible to decouple registering the `flatten_func_with_keys` from `flatten_func` inside `register_pytree_with_keys`

```python
  def flatten_func(tree):
    key_children, treedef = flatten_with_keys(tree)
    return [c for _, c in key_children], treedef
```

**Comment by ASEM000** [comment]
for MWE using the latest 0.4.6 on colab. [Colab link](https://colab.research.google.com/drive/1gdebMU_4ogEvwyMDpqtsMESj_5FAesJB?usp=sharing)


```python
import functools as ft
import jax.tree_util as jtu
import dataclasses as dc

def tree_flatten_with_keys(tree):
    keys_leaves = ((jtu.GetAttrKey(key), vars(tree)[key]) for key in tree.__dataclass_fields__)
    return (keys_leaves, None)

def tree_flatten(tree):
    leaves = (vars(tree)[key] for key in tree.__dataclass_fields__)
    return (leaves, None)

def tree_unflattes(cls, treedef, leaves):
    return cls(*leaves)

# registering with keys
Test = dc.make_dataclass("Test", [[f"leaf_{i}",int,i] for i in range(1000)])
jtu.register_pytree_with_keys(Test, tree_flatten_with_keys, ft.partial(tree_unflattes, Test))
tree = Test()
%timeit jtu.tree_map(lambda x: x, tree)
# 2.03 ms ± 1.06 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)

# registering without keys
Test2 = dc.make_dataclass("Test2", [[f"leaf_{i}",int,i] for i in range(1000)])
jtu.register_pytree_node(Test2, tree_flatten, ft.partial(tree_unflattes, Test))
tree2 = Test2()
%timeit jtu.tree_map(lambda x: x, tree2)
# 479 µs ± 23.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by mattjj** [comment]
Thanks for raising this!

As you may be able to tell from your MWE, you can just call `register_pytree_node` after if you want to register a key-less flattener function. So isn't this decoupling already possible?

(I'm also curious: is this actually a performance bottleneck in real code you have, or is it just hypothetical? The differences here may not matter in practice.)

**Comment by ASEM000** [comment]
Hello , 
(1) Once I register `Test` Class using `jtu.register_pytree_with_keys`, It's not possible to register it again with  `jtu.register_pytree_node` without raising Duplicate registration error.  AFAIK,  `register_pytree_with_keys` registers it with `register_pytree_node` with the generate flatten func

```python
import functools as ft
import jax.tree_util as jtu
import dataclasses as dc

def tree_flatten_with_keys(tree):
    keys_leaves = ((jtu.GetAttrKey(key), vars(tree)[key]) for key in tree.__dataclass_fields__)
    return (keys_leaves, None)

def tree_flatten(tree):
    leaves = (vars(tree)[key] for key in tree.__dataclass_fields__)
    return (leaves, None)

def tree_unflattes(cls, treedef, leaves):
    return cls(*leaves)

# registering with keys
Test = dc.make_dataclass("Test", [[f"leaf_{i}",int,i] for i in range(1000)])
jtu.register_pytree_with_keys(Test, tree_flatten_with_keys, ft.partial(tree_unflattes, Test))
jtu.register_pytree_node(Test, tree_flatten, ft.partial(tree_unflattes, Test))
# ValueError: Duplicate custom PyTreeDef type registration for <class 'types.Test'>.
```

In the MWE, I had to create a new class, `Test2`, to showcase the difference. so the following code will raise a Duplicate registration error.


(2) Practically, as you said, the overhead might not be significant, but the overhead of the extra traversal can be mitigated in case of decoupling the registration process. I think the deprecated API `register_keypath` adopted this decoupled approach.

**Comment by mattjj** [comment]
Ah I misread your MWE, sorry!

**Comment by mattjj** [comment]
The downside of the `register_keypath` approach was that it made more errors possible, like errors where the key order doesn't match the child order. Ruling out errors by construction is nice!

I think unless the overhead is actually significant, we shouldn't complicate the APIs to reduce it. (If we did want to reduce it, I guess we could allow an optional `flatten_func` argument on `register_pytree_with_keys`.)

**Comment by mattjj** [comment]
I pinged some other folks for their thoughts, hopefully they will weigh in too!
