### ISSUE TITLE
Support linear extrapolation in jnp.interp?

### ISSUE THREAD

**Issue by shoyer** [google/jax#14858]
`numpy.interp` does not support extrapolation, instead leaving this functionality to the much more complex [scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html), which uses a class based interface.

So I propose to interpret the string values `left='extrapolate'` and `right='extrapolate'` as indicating that extrapolation should be done instead of only using a constant value:

- This value would be consistent with the keyword argument used by the `fill_value` argument to scipy.interpolate.interp1d.
- There is no potential confusion about strings indicating interpolation modes versus values because `left` and `right` currently only support numeric arguments.

This would be useful and extremely easy to implement in JAX. Basically all that needs to be done to obtain linear extrapolation is to conditionally remove these calls to `where` at the end of `jnp.interp`
https://github.com/google/jax/blob/6634600c46c99e3f0861e9258aace3fdfe250baf/jax/_src/numpy/lax_numpy.py#L1042-L1043

Any thoughts? I can see a case for asking to do this in NumPy first, but I'm not sure there would be large enough benefits to the NumPy users given that they can use SciPy instead. Also it would be slightly more annoying to implement in NumPy since the implementation of `np.interp` is written in C.

**Comment by mattjj** [comment]
Deviating from the NumPy API in ways @shoyer suggests SGTM!
