### ISSUE TITLE
device_put leaks references on numpy inputs

### ISSUE THREAD

**Issue by jakevdp** [google/jax#14882]
First reported in #14876; here's a minimal repro that reproduces on CPU and GPU:
```python
import sys
import jax
import numpy as np

x = np.arange(1000, dtype='float32')
print(sys.getrefcount(x))
# 2

y = jax.device_put(x)
print(sys.getrefcount(x))
# 3

del y
print(sys.getrefcount(x))
# 3
```

**Comment by jakevdp** [comment]
From @hawkinsp, it looks like triggering XLA's internal garbage cleanup is the solution here:
```python
import sys
import jax
import numpy as np
from jax._src.lib import xla_client

x = np.arange(1000, dtype='float32')
print(sys.getrefcount(x))
# 2

y = jax.device_put(x)
print(sys.getrefcount(x))
# 3

del y
print(sys.getrefcount(x))
# 3

xla_client._xla.collect_garbage()
print(sys.getrefcount(x))
# 2
```

**Comment by jakevdp** [comment]
This internal garbage collection is called frequently within XLA, but @mattjj suggested we might also add it to [`gc.callbacks`](https://docs.python.org/3/library/gc.html#gc.callbacks) so that when the user forces Python garbage collection, it triggers XLA garbage collection as well.

**Comment by jakevdp** [comment]
With this addition, `gc.collect()` causes the reference counts to be as expected.
```python
from jax._src.lib import xla_client
import gc

def _xla_gc_callback(phase, info):
  if phase == 'start':
    xla_client._xla.collect_garbage()
gc.callbacks.append(_xla_gc_callback)

x = np.arange(1000, dtype='float32')
```

**Comment by jjyyxx** [comment]
@jakevdp It seems this change leads to inconsistent Ctrl-C behavior? In other words, interrupting a training loop with Ctrl-C oftentimes leads to the following stdout
```
Exception ignored in: <function _xla_gc_callback at 0x7f503fb748b0>
Traceback (most recent call last):
  File "<PYTHON_ENV>/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 103, in _xla_gc_callback
    def _xla_gc_callback(*args):
KeyboardInterrupt:
```
thus I have to press Ctrl-C several times in order to interrupt a program. Happens with v0.4.9 and v0.4.10.

**Comment by jjyyxx** [comment]
(Should I make a separate issue for this?)

@jakevdp I did not come up with a fix yet, but I made the mechanism clear and wrote a reproducible example for this. There are two basic facts:
1. Any exceptions (including `KeyboardInterrupt`) will be ignored when raised from GC callbacks (for this case `_xla_gc_callback`)
2. Jitted XLA computation is not interruptable when running

So, when the jitted training step takes most of the time in the training loop, and somehow triggers a GC collection immediately after finishing the computation (reason see below), it's very likely that pressing Ctrl-C happens in the jitted training step then ignored in the GC callback.

A simple snippet to reproduce this. The key point is the the large input tree which is common for `TrainState` of large networks
```python
import tqdm
import jax

# Initialize Pytree data with a lot (1000) of leaves
# A small number of leaves (e.g. 10) does not trigger the this behavior
key = jax.random.PRNGKey(0)
subkeys = jax.random.split(key, 1000)
input = { i: jax.random.normal(k, (100, 100)) for i, k in enumerate(subkeys)}

@jax.jit
def f(d):
    def slow(x):
        # To waste enough time
        return jax.lax.while_loop(lambda args: args[0] < 10000, lambda args: (args[0] + 1, args[1] + 0.01), (0, x))[1]

    d = { **d, 0: slow(d[0]) }
    return d

# Warmup
f(input)

for _ in tqdm.trange(1000):
    # Spam Ctrl-C here
    input = f(input)
```
Spamming Ctrl-C could interrupt this, but it's undesirable, as it's very likely to also interrupt any clean-up code (e.g. saving latest checkpoint).

**Comment by jjyyxx** [comment]
I guess there are several options to consider:
1. Provide a flag to disable this behavior
2. Lower the frequency, e.g., check if `phase` is `"start"` and if `info["generation"]` is `2`
3. Manually check signals with `PyErr_CheckSignals` before `Convert the ifrt::Array objects to PyArray.` in pjit.cc and handle early before GC happens

**Comment by MarkDaoust** [comment]
I'm not using Jax (I just see that it gets imported when I import tensorflow). 
I'm writing some code interactively in colab, and I keep seeing these 10-15second pauses. 

When I try to Ctrl-C when it's paused, it waits till it was going to finish anyway, and then prints that same error @jjyyxx reported. 

Is it the callback taking that long? or is something else happening?

**Comment by jakevdp** [comment]
I don't have plans to roll back the change – the change in question fixes some important issues, and the downside (keyboard interrupt taking longer than strictly necessary) seems like a worthwhile tradeoff. If you know of a way to fix the second issue without impacting the fix for the first issue, I'd love to know!

**Comment by jakevdp** [comment]
If you can file a new issue (rather than commenting on a merged CL) it will be easier to track & triage.

**Comment by MarkDaoust** [comment]
I started writing a new issue, but eventually came to the conclusion that the problem I've been seeing is **not** caused by jax. 

I'm not using jax in my code, it just gets incidentally imported, which adds the callback to `gc.callbacks`

If I pop the jax callback from `gc.callbacks`, and add my own callback to print some stuff, I see the same pauses, and the error triggered by Ctrl-C points to my callback instead of jax.

I think this makes sense because python only ignores Ctrl-C when the interpreter isn't running (python's down in a C-extension). I think what's probably happening is that I'm getting a long GC pause, hitting Ctrl-C during that, and the callback is just the first line of python that gets run after the GC is done.

So whatever this is I'm pretty sure Jax is not at fault.
