### ISSUE TITLE
Accumulate gradients

### ISSUE THREAD

**Issue by neon5d** [google/jax#1488]
Can you show me a correct way to accumulate gradients ?
The below pseudo code is just my thought.

@jit
def update (i, opt_state):
params = get_params(opt_state)
gradient_cur = grad(objective)(params, i)
gradient_all += gradient_cur
if i % update_interval==0 :
  opt_state = opt_update(i, gradient_all, opt_state)
  set(gradient_all, 0)
return opt_state

**Comment by gnecula** [comment]
You can find a simple example in: https://github.com/google/jax/blob/master/examples/mnist_classifier_fromscratch.py

In general, though, you should try to use higher-level libraries, as it is done in https://github.com/google/jax/blob/master/examples/mnist_classifier.py

**Comment by neon5d** [comment]
Thank you for comments.
I used higher-level libraries to accumulate gradients.
I am not completely sure what I did correctly, but somewhat it is working.
But I can't use jit with condition. Definitely, both i and update_interval are declared with static_argnums, It works. But it will be recompiled every time.

Do you have any way to avoid this?

```
@jit
def grad_zeros(acc_grad):
  for i, val in enumerate(acc_grad):
      if (len(val) == 0):
        continue
      acc_grad[i] = (np.zeros_like(val[0]), np.zeros_like(val[1]))
  return acc_grad
```

```
@jit
def grad_add(acc_grad, cur_grad):
  for i, val in enumerate(acc_grad):
      if (len(val) == 0):
        continue
      acc_grad[i] = (np.add(val[0], cur_grad[i][0]), np.add(val[1], cur_grad[i][1]))
  return acc_grad
```


```
#@partial(jit, static_argnums=(0,)) <= failed
def update(update_interval, i, opt_state, acc_grad, batch):
    params = get_params(opt_state)
    cur_grad = grad(loss)(params, batch)
    acc_grad = grad_add(acc_grad, cur_grad)
    if (i % update_interval == 0):
        opt_state = opt_update(i, acc_grad, opt_state)
        acc_grad = grad_zeros(acc_grad)

    return opt_state, acc_grad
```

**Comment by joaogui1** [comment]
Have you tried using lax.cond?

**Comment by neon5d** [comment]
Thank you for comments.
It works with lax.cond as the below code.  

```
def update_acc_grad(args):
        i, acc_grad, opt_state = args
        opt_state = opt_update(i, acc_grad, opt_state)
        acc_grad = grad_zeros(acc_grad)
        return opt_state, acc_grad

def else_fun(args):
      acc_grad, opt_state = args
      return opt_state, acc_grad

@partial(jit, static_argnums=(0,))
def update(update_interval, i, opt_state, acc_grad, batch):
    params = get_params(opt_state)
    cur_grad = grad(loss)(params, batch)
    acc_grad = grad_add(acc_grad, cur_grad)

    return lax.cond((i % update_interval == 0), (i, acc_grad, opt_state), update_acc_grad, (acc_grad, opt_state), else_fun)

```
