### ISSUE TITLE
Should `array_equal` and `array_equiv` enforce array like for their arguments?

### ISSUE THREAD

**Issue by soraros** [google/jax#14901]
Type hints says yes, yet they are permissive in their arguments.
```python
jnp.array_equal(np.array([1, 2, 3]), [1, 2, 3])
# Array(True)
```

Does #7737 apply here?

**Comment by jakevdp** [comment]
Yes, it probably should. We’ve been slow to implement #7737 because every change is an API breakage that needs a deprecation cycle, and that can be difficult to land due to necessary downstream changes.
