### ISSUE TITLE
`argmax` and `argmin` doesn't raise when the argument `out` is used.

### ISSUE THREAD

**Issue by soraros** [google/jax#14904]
### Description

https://github.com/google/jax/blob/3fbe4e8230c60e40a1c54732d879438b9d39bd16/jax/_src/numpy/lax_numpy.py#L3401-L3410

`out` is never passed to `_argmax` where the error handling is actually implemented. I guess wrapped functions like `_argmax` shouldn't have default arguments.

Also, `keepdims` should be key word only.

**Comment by jakevdp** [comment]
Thanks for the report!

**Comment by soraros** [comment]
@jakevdp Thank you for the quick fix.
