### ISSUE TITLE
Make arguments of index update helper functions keyword only

### ISSUE THREAD

**Issue by soraros** [google/jax#14913]
For instance, the following code will fail silently, especially given that `at` is not type hinted. One could argue it's just the user (me) being silly, but it's still surprising and difficult to debug. Making arguments like `mode` keyword-only will eliminate this kind of problem.

```python
I = jnp.array([0, 10])
a = jnp.arange(5).at[I].get('fill', fill_value=-1)
#     this is actually: get(indices_are_sorted='fill', fill_value=-1)
```

**Comment by jakevdp** [comment]
This is a great idea – let me explore a bit to see how many downstream projects it would break.
