### ISSUE TITLE
How to trace memory usage?

### ISSUE THREAD

**Issue by neon5d** [google/jax#1491]
I got out-of-memory error during the backward, after run four times forward and backward plus one forward.
I have no idea why it keep increasing memory usage.
Do you have any method to trace memory usage?
I knew Jax initially allocate 90% memory, but I want to trace actual usage. 

  File ".local/lib/python3.6/site-packages/jax/api.py", line 398, in value_and_grad_f
    g = vjp_py(onp.ones((), dtype=dtype))
  File ".local/lib/python3.6/site-packages/jax/api_util.py", line 66, in apply_flat_fun_nokwargs
    ans = fun(*args)
  File ".local/lib/python3.6/site-packages/jax/interpreters/ad.py", line 114, in vjp_
    _, arg_cts = backward_pass(jaxpr, consts, (), dummy_args, dummy_primals_and_cts)
  File ".local/lib/python3.6/site-packages/jax/interpreters/ad.py", line 178, in backward_pass
    eqn.params, subjaxpr, sub_consts, sub_freevar_vals, invals, cts_in)
  File ".local/lib/python3.6/site-packages/jax/interpreters/ad.py", line 458, in call_transpose
    out_flat = primitive.bind(fun, *all_args, **params)
  File ".local/lib/python3.6/site-packages/jax/core.py", line 569, in call_bind
    outs = primitive.impl(f, *args, **params)
  File ".local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 369, in _xla_call_impl
    return compiled_fun(*args)
  File ".local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 403, in _execute_compiled
    out_bufs = compiled.Execute(input_bufs).destructure()
RuntimeError: Resource exhausted: Out of memory while trying to allocate 2692743312 bytes.

**Comment by skye** [comment]
I'm assuming you're running on GPU? Unfortunately we don't have great tooling for memory profiling. You can try setting the following environment variables: `TF_CPP_MIN_LOG_LEVEL=0` and `TF_CPP_VMODULE=bfc_allocator=1`, which should make it log every allocation and deallocation (within the 90% pre-allocated chunk).

If you're steadily accumulating memory, make sure you don't have references to values that you're not using. JAX uses Python's garbage collection to automatically release memory, so if you keep references to values during training, you'll eventually run out of memory.

**Comment by neon5d** [comment]
Thank you for useful tips. I might have the issue which you mentioned in the second paragraph.
However, It is hard for me to understand the second paragraph.
Mainly, I am not familiar with the meaning of  "references to values".
Do you have any examples or documentation to show avoid possible memory issues?

**Comment by neon5d** [comment]
```
[bfc_allocator.cc:228] AllocateRaw xla_gpu_host_bfc  25165824
bfc_allocator.cc:148] Extending allocation by 32.00MiB bytes.
bfc_allocator.cc:152] Total allocated bytes: 36.00MiB
bfc_allocator.cc:155] Allocated memory at 0x207b00000 to 0x209b00000
bfc_allocator.cc:548] DeallocateRaw xla_gpu_host_bfc 25165824
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  1610612736
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  1073741824
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  1073741824
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  25165824
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  25165824
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  1536
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  64
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  2684354816
bfc_allocator.cc:148] Extending allocation by 8.00GiB bytes.
bfc_allocator.cc:152] Total allocated bytes: 16.04GiB
bfc_allocator.cc:155] Allocated memory at 0xd6f280000 to 0xf6f280000
bfc_allocator.cc:548] DeallocateRaw GPU_0_bfc 2684354816
bfc_allocator.cc:548] DeallocateRaw GPU_0_bfc 64
bfc_allocator.cc:548] DeallocateRaw GPU_0_bfc 25165824
bfc_allocator.cc:548] DeallocateRaw GPU_0_bfc 4
bfc_allocator.cc:228] AllocateRaw GPU_0_bfc  4
bfc_allocator.cc:228] AllocateRaw xla_gpu_host_bfc  4](url)
```

**Comment by skye** [comment]
See the "Reference counting" section of https://rushter.com/blog/python-garbage-collector/ for an overview of what I meant by "references to values". I'm specifically talking about references to array objects returned by JAX, which will hold on to the GPU memory until there are no more references and they're garbage collected.

Unfortunately it's hard to debug Python memory leaks like this, but make sure you're not holding on to arrays across training loop iterations (e.g. by putting them in a list of another global collection).

**Comment by neon5d** [comment]
Thank you for the information.
I figured out a little bit.
I think jit has a memory leak as 1) pseudo code:
jit has some issues under a class and individual functions' jit.
After changing 2), It looks fine.

1)    
```
@partial(jit, static_argnums = (1,))
def custom_conv2d(params, scale, input, **kwargs):
    return lax.conv_general_dilated(input, np.cos(scale*param[0][0]), (1,1), 'SAME')

class example():

    @partial (jit, static_argnums = (0,))
    def mse(self, preds, targts):
        return np.mean((preds - targets) ** 2)

    def loss(self, params, inputs, targets): <= introduce the memory leak
         preds = custom_conv2d(params, self.scale, inputs)
         return self.mse(preds, targets)
```

2)    
```
@partial(jit, static_argnums = (1,))
def custom_conv2d(params, scale, input, **kwargs):
    return lax.conv_general_dilated(input, np.cos(scale*param[0][0]), (1,1), 'SAME')

class example():

    @partial (jit, static_argnums = (0,))
    def mse(self, preds, targts):
        return np.mean((preds - targets) ** 2)

    @partial (jit, static_argnums = (0,))
    def loss(self, params, inputs, targets): 
         preds = custom_conv2d(params, self.scale, inputs)
         return self.mse(preds, targets)
```

**Comment by skye** [comment]
Hi, sorry for the delay. Could you provide a full example we can run that demonstrates the memory leak?

**Comment by neon5d** [comment]
Here is an example code based on mnist_classifier.py
Without jit at loss, OOM will occur ( you might need to adjust Dense(1024***256**)  to set 34% initial memory.
During the training, it keep increasing 68%, 90% and OOM.
With jit at loss, It keep maintaining 68% memory usage.


```
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from functools import partial
import time
import itertools

import numpy.random as npr

import jax.numpy as np
from jax.config import config
from jax import jit, value_and_grad, random
from jax.experimental import optimizers
from jax.experimental import stax
from jax.experimental.stax import Dense, Relu, LogSoftmax
from examples import datasets
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "1"
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "False"

class exnet():
  @partial(jit, static_argnums = (0,))
  def mxe(self, preds, targets):
    return -np.mean(preds * targets)

  #@partial(jit, static_argnums = (0,)) <= memory leak
  def loss(self, params, batch):
    inputs, targets = batch
    preds = predict(params, inputs)
    return self.mxe(preds, targets)

  @partial(jit, static_argnums = (0,))
  def accuracy(self, params, batch):
    inputs, targets = batch
    target_class = np.argmax(targets, axis=1)
    predicted_class = np.argmax(predict(params, inputs), axis=1)
    return np.mean(predicted_class == target_class)

init_random_params, predict = stax.serial(
    Dense(1024), Relu,
    Dense(1024*256), Relu,
    Dense(10), LogSoftmax)

if __name__ == "__main__":
  rng = random.PRNGKey(0)

  step_size = 0.001
  num_epochs = 100000
  batch_size = 2
  momentum_mass = 0.9

  train_images, train_labels, test_images, test_labels = datasets.mnist()
  num_train = train_images.shape[0]
  num_complete_batches, leftover = divmod(num_train, batch_size)
  num_batches = num_complete_batches + bool(leftover)

  network = exnet()

  def data_stream():
    rng = npr.RandomState(0)
    while True:
      perm = rng.permutation(num_train)
      for i in range(num_batches):
        batch_idx = perm[i * batch_size:(i + 1) * batch_size]
        yield train_images[batch_idx], train_labels[batch_idx]
  batches = data_stream()

  opt_init, opt_update, get_params = optimizers.momentum(step_size, mass=momentum_mass)

  _, init_params = init_random_params(rng, (-1, 28 * 28))
  opt_state = opt_init(init_params)
  itercount = itertools.count()

  print("\nStarting training...")
  tloss = 0
  for epoch in range(num_epochs):
    start_time = time.time()
    for i in range(num_batches):
      closs, g = value_and_grad(network.loss, 0)(get_params(opt_state), next(batches))
      opt_state = opt_update(i, g, opt_state)
      tloss += closs
      #if (i % 100 == 0):
      print("%d: %f"%(i, closs/batch_size))

    print("train loss (%d/%d) = %f" %(epoch, num_epochs, tloss/(batch_size*i)))
    epoch_time = time.time() - start_time

    params = get_params(opt_state)
    train_acc = network.accuracy(params, (train_images, train_labels))
    test_acc = network.accuracy(params, (test_images, test_labels))
    print("Epoch {} in {:0.2f} sec".format(epoch, epoch_time))
    print("Training set accuracy {}".format(train_acc))
    print("Test set accuracy {}".format(test_acc))

```

**Comment by hawkinsp** [comment]
We just added a device memory profiler to JAX that should be exactly what you need to track down this sort of memory leak.

https://jax.readthedocs.io/en/latest/device_memory_profiling.html

I tried to reproduce the OOM you describe with JAX from head and it doesn't seem to reproduce. The memory usage appears to remain constant at around 4GB. I've attached a device memory profile visualization as produced by the memory profiling tool (on CPU).
[profile002.pdf](https://github.com/google/jax/files/4842378/profile002.pdf)

Please feel free to reopen if you have any more problems!

**Comment by NightMachinary** [comment]
How can we see the TPU memory usage from the CLI, ala htop?

**Comment by skye** [comment]
There's no such utility for viewing TPU memory at this time. I'd really like to programmatically expose per-device memory usage from jax, and then you could write a small python utility to print the TPU usage. Unfortunately due to other priorities, I'm not sure when I or someone else will implement this feature, but it's on our radar! Thanks for posting because questions + feature requests help us prioritize.

**Comment by Lime-Cakes** [comment]
> There's no such utility for viewing TPU memory at this time. I'd really like to programmatically expose per-device memory usage from jax, and then you could write a small python utility to print the TPU usage. Unfortunately due to other priorities, I'm not sure when I or someone else will implement this feature, but it's on our radar! Thanks for posting because questions + feature requests help us prioritize.

Is there any change to this? Any API we could use to see how much memory is taken up on a tpu device?

**Comment by skye** [comment]
It turns out @ayaka14732 has implemented a super-cool CLI htop-like utility! Check out https://github.com/ayaka14732/jax-smi

**Comment by cnsgsz** [comment]
Is memory_profile drop-down in tensorboard supported too, besides pprof? Is pprof recommended over tensorboard for memory profile (and perfetto over tensorboard for traces)? See [discussion](https://github.com/google/jax/discussions/14583).

**Comment by sshleifer** [comment]
This needs love. https://pytorch.org/docs/stable/generated/torch.cuda.memory_summary.html way way way easier.

**Comment by skye** [comment]
> This needs love. https://pytorch.org/docs/stable/generated/torch.cuda.memory_summary.html way way way easier.

Thanks @sshleifer for the suggestion! As of jax 0.4.12, you can access per-device memory statistics via `Device.memory_stats()`.
```python
In [1]: import jax

In [2]: jax.local_devices()[0].memory_stats()
Out[2]: 
{'bytes_in_use': 12288,
 'bytes_limit': 33014415360,
 'bytes_reservable_limit': 33014415360,
 'bytes_reserved': 0,
 'largest_alloc_size': 12288,
 'largest_free_block_bytes': 33014403072,
 'num_allocs': 1,
 'peak_bytes_in_use': 12288,
 'peak_bytes_reserved': 0}

In [3]: x = jax.numpy.ones(10000)

In [4]: jax.devices()[0].memory_stats()
Out[4]: 
{'bytes_in_use': 76288,
 'bytes_limit': 33014415360,
 'bytes_reservable_limit': 33014415360,
 'bytes_reserved': 0,
 'largest_alloc_size': 40960,
 'largest_free_block_bytes': 33014338560,
 'num_allocs': 3,
 'peak_bytes_in_use': 76800,
 'peak_bytes_reserved': 0}
```

(You can only access memory stats for local devices.)

Please feel free to file feature requests for any improvements!
