### ISSUE TITLE
jax numpy take do not accept range

### ISSUE THREAD

**Issue by jakubMitura14** [google/jax#14942]
### Description

Jax numpy take is not behaving as numpy take function 
```
jnp.take(jnp.arange(10),indices=range(0, 2), axis=0)
```
gives
```
TypeError: Argument 'range(0, 2)' of type  is not a valid JAX type.

```

### What jax/jaxlib version are you using?

using oficial docker nvcr.io/nvdlfwea/jax/jax:23.01-py3

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

2 x rtx 3090

**Comment by soraros** [comment]
This is the expected behaviour. `jax.numpy` functions don't accept non-`Array` dynamic arguments. Motivation for this can be found in #7737. You could convert the `range` object before passing to JAX, or use `jnp.arange` directly in this case.

**Comment by jakubMitura14** [comment]
thank you!
