### ISSUE TITLE
Training Multiple Steps with TPU as in TensorFlow

### ISSUE THREAD

**Issue by ranlucienwang** [google/jax#14971]
Hello, 

When using TPU training, one of the accelerating tricks is using training with multiple steps, as is shown [here](https://www.tensorflow.org/guide/tpu). However, it seems that according to [this flax example](https://colab.research.google.com/github/google/flax/blob/main/examples/imagenet/imagenet.ipynb) from the [official tutorial](https://flax.readthedocs.io/en/latest/examples_core_examples.html#image-classification), we can only feed one batch to the TPU. 

Is there a way to mimic the performance of the TensorFlow example? Thank you.

**Comment by young-geng** [comment]
There's nothing stopping you from jitting n steps of training. For example, given a `train_step_fn` function:
```python
@jax.jit
def train_for_n_steps(train_state, batches):
    for batch in batches:
        train_state = train_step_fn(train_state, batch)
    return train_state
```

**Comment by ranlucienwang** [comment]
Thank you very much. This is very helpful!

**Comment by hawkinsp** [comment]
Closing because the answer above seems to cover it!
