### ISSUE TITLE
The most outer function jit vs. Multiple functions' jit

### ISSUE THREAD

**Issue by neon5d** [google/jax#1498]
I have tested regarding jit position based on mnist_classifier.py example.

The most outer function jit as in mnist_classifier.py example is significantly faster than individual functions jit 

1) most outer function jit
```
  @jit
  def update(i, opt_state, batch):
    params = get_params(opt_state)
    return opt_update(i, grad(loss)(params, batch), opt_state)
```

2) individual functions jit
```
  @jit
  def loss(params, batch):
     inputs, targets = batch
     preds = predict(params, inputs)
     return -np.mean(preds * targets)

  def update(i, opt_state, batch):
    params = get_params(opt_state)
    return opt_update(i, grad(loss)(params, batch), opt_state)

  opt_init, opt_update, get_params = optimizers.momentum(step_size, mass=momentum_mass)
  get_params = jit(get_params)
  opt_update = jit(opt_update)
```

Execution time of two approaches is significantly different.
Even the individual functions jit seems not to work. 
Someone can explain this?
Also, can you add more details about jit documentation?

```
1)
Epoch 0 in 3.34 sec
Training set accuracy 0.1369333416223526
Test set accuracy 0.1128000020980835
Epoch 1 in 0.75 sec
Training set accuracy 0.22956666350364685
Test set accuracy 0.24060000479221344
Epoch 2 in 0.75 sec
2)
Epoch 0 in 57.29 sec
Training set accuracy 0.09938333183526993
Test set accuracy 0.059300001710653305
Epoch 1 in 55.57 sec
Training set accuracy 0.22956666350364685
Test set accuracy 0.24060000479221344
Epoch 2 in 54.44 sec
```

**Comment by jakevdp** [comment]
Late here, but the key insight is that JAX's `jit` optimizes *sequences of operations*, and that transforms like `grad` generate sequences of operations.

So `grad(jit(f))` will generate an unoptimized sequence of (individually optimized) operations, whereas `jit(grad(f))` will generate a fully-optimized sequence of operations. The latter will be faster because it allows XLA to optimize the full sequence.
