### ISSUE TITLE
Sparse rule for div is not implemented

### ISSUE THREAD

**Issue by quattro** [google/jax#14983]
### Description

Hi all, I've been prototyping some functionality using the experimental `BCOO` interface and quickly run into `NotImplementedError` for basic functionality. For example, computing the mean across a given axis. 

```python
import jax.experimental.sparse as xsp
import jax.numpy as jnp

X = jnp.hstack([jnp.ones(5)[:,jnp.newaxis], jnp.zeros(5)[:,jnp.newaxis]])
sX = xsp.BCOO.fromdense(X)
smean = xsp.sparsify(jnp.mean)
smean(sX)
```
Will output `Array(0.5, dtype=float32)`, however, `smean(sX, axis=0)` (or `axis=1`) throws 
```python
NotImplementedError: sparse rule for div is not implemented.
```

Is this expected at this time, and are there plans to extend the functionality for `div`?

### What jax/jaxlib version are you using?

jax v0.4.5

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9.12

**Comment by jakevdp** [comment]
Thanks - we haven't implemented sparse div because in general it's unsafe: if the divisor is zero, then it would be a densifying operation (all unspecified entries would become `NaN`).

**Comment by jakevdp** [comment]
I added an implementation of div in https://github.com/google/jax/pull/14987; though it runs into issues with division by zero, it's probably better to have it than not. What do you think?

**Comment by quattro** [comment]
Hi @jakevdp , that works for my case. Thanks for the speedy response.
