### ISSUE TITLE
Jax Tree import error 

### ISSUE THREAD

**Issue by kenndshi** [google/jax#15002]
### Description

I have an error in importing "tree" for https://github.com/ohuelab/Solubility_AfDesign.
I have tried installing different versions of Jax and jaxlib, still didn't work?
Currently installed using "pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"

### What jax/jaxlib version are you using?

jax 0.4.6 kib 0.4.6+cuda11+cudnn82

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

I have RTX 3050 laptop version

**Comment by hawkinsp** [comment]
The "tree" package isn't part of JAX. I think you're looking for `dm-tree` (https://pypi.org/project/dm-tree/)
