### ISSUE TITLE
Sparse rule for `pow` 

### ISSUE THREAD

**Issue by quattro** [google/jax#15013]
Hi all, piggybacking off of yesterday's discussion and fix for division in sparse matrices (#14983), would it be possible to add a partial implementation of a rule for `jnp.power` ? I can understand the rationale behind not wanting to blow up the sparisity structure when exponents are non-positive, but the sparsity structure should be preserved for positive powers (e.g., `x ** 2`). 

My current workaround is to perform repeated multiplication (e.g., `x * x`), but this seems suboptimal if powers are large.

**Comment by jakevdp** [comment]
Thanks - we don't plan on implementing general `power` operations for sparse arrays, because for `p <= 0`, `0 ** p` is not zero. So raising a sparse matrix to an arbitrary power is a densifying operation.

That said, on the main branch, static integer powers are already supported. For example:
```python
In [1]: from jax.experimental import sparse

In [2]: import jax.numpy as jnp

In [3]: x = sparse.BCOO.fromdense(jnp.arange(4.0))

In [4]: x ** 2
Out[4]: BCOO(float32[4], nse=3)
```
Is that sufficient for your use case?

**Comment by quattro** [comment]
My apologies! I was still using jax version 0.4.5. Upgrading to 0.4.6 fixed this. Sorry about that!

**Comment by quattro** [comment]
Apologies I spoke too soon. Here is an issue that crops up if using sparsify. 

```python
import jax.experimental.sparse as xsp

@xsp.sparsify
def func_sp(x, p):
    return x ** p

def func(x, p):
    return x ** p

X = jnp.hstack([jnp.ones(5)[:,jnp.newaxis], jnp.zeros(5)[:,jnp.newaxis]])
sX = xsp.BCOO.fromdense(X)

sX ** 2  # works
func(sX, 2) # works
func_sp(sX, 2) # doesn't work; throws NotImplementedError: sparse rule for pow is not implemented.
```

The workaround here would be for me to drop the sparsify function (which can be done), but this seems like it should work on its own?

**Comment by quattro** [comment]
Yes that works.
