### ISSUE TITLE
jax.ShapeDtypeStruct isn't documented

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#15023]
It is helpful for AOT compilation!

**Comment by jakevdp** [comment]
We should also probably update the documentation of [`jax.eval_shape`](https://jax.readthedocs.io/en/latest/_autosummary/jax.eval_shape.html) to make use of `jax.ShapeDtypeStruct` rather than suggesting that users define a similar structure themselves.

**Comment by froystig** [comment]
We use `types.SimpleNamespace` to a similar end as an example throughout our reference documentation, e.g. [here](https://github.com/google/jax/blob/d5f8fd3d851acca570cc588ee4a8ef833a9fe7c1/jax/_src/api.py#L2338).

On the one hand, this isn't `ShapeDtypeStruct`. On the other hand, it helps emphasize that anything that duck-types is meant to work. Should we keep those examples as is, or give up on emphasizing the duck-typing point as part of the docstring example, and switch it over to `ShapeDtypeStruct` as well?

**Comment by hawkinsp** [comment]
We should either document `ShapeDtypeStruct` or remove it from the API.

If we expect users to use duck types, we should describe clearly what attributes the duck types are expected to have.

**Comment by froystig** [comment]
Do you mean to state those as mutually exclusive? It seems at least possible to have SDS, document it, allow for anything that duck types like SDS on the input side, and always output SDS. With that, it might make sense to have the SDS symbol in the API for type annotations. (?)

We could entertain a protocol for annotations, but by the time we've written a class to define the protocol, it seems easy to fill it out into a concrete class for optional use too?

**Comment by hawkinsp** [comment]
I didn't mean they were exclusive. I just mean without documentation, it's hard to work out what attributes matter, and maybe the best form of that documentation is a class like SDS.

**Comment by jakevdp** [comment]
I agree with @hawkinsp – using `ShapeDtypeStruct` in the docs is helpful in that it's self-documenenting. We could also mention that any duck-typed object will work. but defining a struct in the example makes it look more complicated than it needs to be.

**Comment by froystig** [comment]
Yeah, great, I agree!
