### ISSUE TITLE
PyPI OSX 'Symbol not found' for jaxlib 0.1.31 

### ISSUE THREAD

**Issue by thierrymoudiki** [google/jax#1502]
Hi, 

I am installing the package (version 0.1.31) from Pypi (on OSX Yosemite) by doing: 

```bash
pip install --upgrade jax jaxlib
```

After that, I try to import the package:

```python
import jax.numpy as np
```

And get the following error message (seemingly, because of the extension 'xla_extension.so' that can't be imported):

```python
Traceback (most recent call last):

  File "<ipython-input-1-122f308a8eba>", line 1, in <module>
    import jax.numpy as np

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/__init__.py", line 19, in <module>
    from jax.api import *

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/api.py", line 45, in <module>
    from . import ad_util

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/ad_util.py", line 20, in <module>
    from .tree_util import register_pytree_node

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/tree_util.py", line 44, in <module>
    from .lib import pytree

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jax/lib/__init__.py", line 40, in <module>
    from jaxlib import xla_client

  File "/Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_client.py", line 37, in <module>
    from . import xla_extension as _xla

ImportError: dlopen(/Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: __ZNSt3__118shared_timed_mutex11lock_sharedEv
  Referenced from: /Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_extension.so
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/moudiki/anaconda3/lib/python3.7/site-packages/jaxlib/xla_extension.so
```
Thanks

**Comment by hawkinsp** [comment]
We built our wheels on Mac OS Mojave, and we must be using a symbol that isn't present on the older release of `libc++`. I'll take a look and see if we can target an older Mac OS version.

**Comment by thierrymoudiki** [comment]
Cool! Looking forward to it.

**Comment by hawkinsp** [comment]
Hmm, now I look more closely, this might not be easy to fix. JAX uses parts of TensorFlow (in particular, the XLA compiler), and TensorFlow itself has a minimum version requirement of Mac OS 10.12:  https://www.tensorflow.org/install#install-tensorflow-2

I think this particular problem is due to TensorFlow now allowing C++14 code.

Mac OS Yosemite is now 5 years old (10.10, released October 2014) and the current version 10.15. Perhaps it would be simpler to upgrade? What do you think?

**Comment by thierrymoudiki** [comment]
Oh... Ok, I see.

Upgrading the OS might be the best solution, indeed.  

Thanks for your response!

**Comment by hawkinsp** [comment]
I added a comment to the installation instructions in the README specifying that the minimum Mac OS version is 10.12.
