### ISSUE TITLE
`jax.debug.breakpoint()` behavior under `vmap` seems strange

### ISSUE THREAD

**Issue by dieterichlawson** [google/jax#15039]
### Description

When I use `jax.debug.breakpoint` within a `cond` that checks whether a value is finite, it seems to work well.

```python
import jax
import jax.numpy as jnp

def breakpoint_if_nonfinite(x):
  is_finite = jnp.isfinite(x).all()
  def true_fn(x):
    pass
  def false_fn(x):
    jax.debug.breakpoint()
  jax.lax.cond(is_finite, true_fn, false_fn, x)

def f(x):
  out = (jnp.exp(x) - 1)/x
  breakpoint_if_nonfinite(out)
  return out

f(10.) # Doesn't trigger breakpoint
f(0.) # Triggers a breakpoint
```

However, when I `vmap` the function, it seems to always trigger the breakpoint, even when the results are finite. The above function should only return nonfinite results when x=0.

```python
jax.vmap(f)(jnp.array([1., 2., 3.])) # Triggers a breakpoint
```

### What jax/jaxlib version are you using?

v0.4.6

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9, google colab

**Comment by jakevdp** [comment]
Thanks for the question! This is expected behavior. As mentioned in the [`jax.lax.cond` documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cond.html), under mapping transforms, `cond` gets transformed to `select`, and in general `select` evaluates both branches of the conditional.

**Comment by dieterichlawson** [comment]
Gotcha, so there is no way to use the debug within a vmapped function?

**Comment by jakevdp** [comment]
You can use debug within a vmapped function (you did it above, and it worked 😁 )

But I may be misunderstanding your question...

**Comment by dieterichlawson** [comment]
Haha, yes, I guess I'd like to have a version of `breakpoint_if_nonfinite` that works in vmapped code. It seems one way to do that is to swap the vmap for a python loop, is that correct? Are there other, easier ways?

**Comment by jakevdp** [comment]
Oh, I see. I don't think there's any way to add a `debug.breakpoint` in a way that is conditional on a vmapped value. @sharadmv might have ideas here...

**Comment by dieterichlawson** [comment]
Not sure if this is appropriate, but I think it might be nice to have a debugging flag that replaces all `vmap`s with python for loops, with the goal of not replacing `cond` with `select`. I've hit this issue also when trying to conditionally print values. Just some way to maintain the `cond` behavior under `vmap` while debugging would be great.

**Comment by patrick-kidger** [comment]
Try using: `equinox.internal.unvmap_all`:
```python
import equinox.internal as eqxi
import jax
import jax.numpy as jnp

def breakpoint_if_nonfinite(x):
  is_finite = eqxi.unvmap_all(jnp.isfinite(x))
  def true_fn(x):
    pass
  def false_fn(x):
    jax.debug.breakpoint()
  jax.lax.cond(is_finite, true_fn, false_fn, x)

def f(x):
  out = (jnp.exp(x) - 1)/x
  breakpoint_if_nonfinite(out)
  return out

f(10.)
f(0.)
jax.vmap(f)(jnp.array([1., 2., 3.]))  # no breakpoint!
```
`unvmap_all` acts like `jnp.all`, except that it also reduces over any batch dimensions that happen to be present. In this case this ensures that `lax.cond` stays as a `lax.cond` without getting promoted to a `lax.select`.

[Link to the Equinox library.](https://github.com/patrick-kidger/equinox)

**Comment by sharadmv** [comment]
`jax.debug.breakpoint` is "working-as-intended" here. Part of the goal behind debug callbacks is to reveal how programs are executed and vmap-of-cond turning into select is a consequence.

> Not sure if this is appropriate, but I think it might be nice to have a debugging flag that replaces all vmaps with python for loops, with the goal of not replacing cond with select. I've hit this issue also when trying to conditionally print values. Just some way to maintain the cond behavior under vmap while debugging would be great.

We're working on `checkify`, which should be able to handle cases like this.

**Comment by alik-git** [comment]
Hi there, I would like to request / suggest that this caveat be added to this page in the docs.

https://github.com/jax-ml/jax/blob/b74b16f9b9fd13bd90dc9ed8683c54660913de0a/docs/debugging/print_breakpoint.md?plain=1#L272

Currently, there is nothing on that page to warn the user that the provided conditional breakpoint example simply won't work if used within a vmap. I believe this would save many users (and myself from the past) a bunch of time.

**Comment by alik-git** [comment]
I've made a PR for this here. Hope it helps!

https://github.com/jax-ml/jax/pull/27203
