### ISSUE TITLE
jnp.mean and jnp.std crash on large arrays.

### ISSUE THREAD

**Issue by delesley** [google/jax#15068]
### Description

I have a large array of shape float32[16,32,1280,4096].  When I call jnp.std on this array, jit crashes and fails with the following error:  "Python int 2684354560 too large to convert to int32".

Clearly the implementation of jnp.std is dividing by the number of elements in the array, which in this case does not fit into a 32-bit integer.  

Target platform: pjit on TPU. 

### What jax/jaxlib version are you using?

v0.4.2

### Which accelerator(s) are you using?

TPU

**Comment by mattjj** [comment]
Thanks, Delesley! I presume we should convert to float earlier, which the division will do anyway.
