### ISSUE TITLE
random.* docs are not specific enough about probability density function

### ISSUE THREAD

**Issue by billmark** [google/jax#15083]
### Description

jax.random.normal and other jax.random.* should specify the actual probability density function (see numpy.random.normal for an example).  Otherwise there is the potential for confusion (see e.g. https://math.stackexchange.com/questions/1013575/continuous-probability-average-power-of-a-gaussian-random-variable-mathcaln)

For the doc fix, one possibility would be to put the PDF equation inline in the docs, as numpy.random.normal does.  Another possibility would be to state that the PDF is the same as some numpy routine. 
 For jax.random.normal, that would be numpy.random.normal(loc=0.0, scale=1.0).

**Comment by jakevdp** [comment]
Thanks, this is a great suggestion.
