### ISSUE TITLE
TypeError: Cannot interpret value of type <class '__main__.opt'> as an abstract array; it does not have a dtype attribute

### ISSUE THREAD

**Issue by NoteDancing** [google/jax#15115]
### Description

[here](https://colab.research.google.com/drive/1BMmpPacIYBQUaLezLms-jUkavFJMxLg5?usp=sharing)

### What jax/jaxlib version are you using?

jax v0.4.6

### Which accelerator(s) are you using?

GPU

### Additional system info

Python3.9

**Comment by lumip** [comment]
You applied the `@jit` decorator to a class method (namely `opt.opt`). Note that class methods have `self` as the first argument, which is an instance of the class itself and therefore not a type jax knows how to compile (and usually shouldn't need to) - so you get the mentioned exception. Use the `static_argnums` argument of `jit` to notify jax which arguments is should consider static during compilation (i.e., roughly speaking they will not become arguments of the compiled function but are treated as constants during compilation. I.e., in your case, use
```
@functools.partial(jit, static_argnums=(0,))
def opt(self, ....):
```
There are some other places where you appear to indirectly cause jit compilation of class methods (via `vmap` and `grad`), which may cause you similar problems.

**Comment by NoteDancing** [comment]
@lumip How can I use functools?

**Comment by NoteDancing** [comment]
@lumip @jakevdp Thank you for your answer.
