### ISSUE TITLE
Add equivalent of torch.Tensor.flatten

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#15156]
It would be convenient for `jax.Array` to have the equivalent of the [`torch.Tensor.flatten`](https://pytorch.org/docs/stable/generated/torch.Tensor.flatten.html) method. (For example, when flattening an input with arbitrary batch dimensions in a convolutional neural network.) Here is an example implementation:

```python3
from jax import numpy as jnp, Array

def flatten_axes(a: Array, start: int = 0, end: int = -1) -> Array:
    return a.reshape(a.shape[:start] + (-1,) + a.shape[end:][1:])

def main():
    a = jnp.arange(2 * 3 * 4 * 5 * 6).reshape(2, 3, 4, 5, 6)
    assert flatten_axes(a, 1, -2).shape == (2, 3 * 4 * 5, 6)
    assert flatten_axes(a, -3).shape == (2, 3, 4 * 5 * 6)

if __name__ == '__main__':
    main()
```

**Comment by mattjj** [comment]
Seems reasonable to me! Thanks for the suggestion.

@jakevdp do you foresee any issue with this? If not, I can add it.

**Comment by soraros** [comment]
I think `lax.collapse` would work.

**Comment by carlosgmartin** [comment]
@soraros Thanks for the suggestion. `lax.collapse` is less convenient in that

1. It is not a method attached to `jax.Array`, like `torch.Tensor.flatten`. This could be resolved by attaching it as a method.
2. Its axis arguments are required rather than optional, and its end axis argument is exclusive rather than inclusive. For example, "flatten the last 3 axes" must be written as `lax.collapse(a, -3, a.ndim)` rather than simply `a.collapse(-3)`. This could be resolved by making the start and end axis arguments optional, defaulting to `0` and `a.ndim` respectively.

Thoughts?

```python3
from jax import numpy as jnp, Array, lax

def flatten_axes(a: Array, start: int = 0, end: int = -1) -> Array:
    return a.reshape(a.shape[:start] + (-1,) + a.shape[end:][1:])

def main():
    a = jnp.arange(2 * 3 * 4 * 5 * 6).reshape(2, 3, 4, 5, 6)
    assert flatten_axes(a, 1, -2).shape == (2, 3 * 4 * 5, 6)
    assert flatten_axes(a, -3).shape == (2, 3, 4 * 5 * 6)
    assert lax.collapse(a, -3, a.ndim).shape == (2, 3, 4 * 5 * 6)

if __name__ == '__main__':
    main()
```

**Comment by jakevdp** [comment]
We could probably extend the existing `jax.Array.flatten` method with optional arguments. The only issue would be if numpy someday adds conflicting arguments to the method.

**Comment by jakevdp** [comment]
Well, we'd probably want to make `start` and `end` keyword-only

**Comment by shoyer** [comment]
Personally, I think [einops.rearrange](https://einops.rocks/api/rearrange/) is a better way to write these sort of operations.

I definitely don't think this is fundamental enough to be worth adding as a method. JAX and NumPy already have too many array methods.

**Comment by carlosgmartin** [comment]
@shoyer How would you write this flatten function in terms of einops.rearrange?

**Comment by jon-chuang** [comment]
e.g. 
```python
einops.rearrange(images, 'b h w c -> (b h) w c')
```

This flattens b, h axes into (b, h) axis. However, not sure if rearrange will compile down to primitive JAX ops. @shoyer are you are if it does?

**Comment by shoyer** [comment]
> e.g.
> 
> ```python
> einops.rearrange(images, 'b h w c -> (b h) w c')
> ```
> 
> This flattens b, h axes into (b, h) axis. However, not sure if rearrange will compile down to primitive JAX ops. @shoyer are you aware if it does?

Yes, it does, which you can verify with `jax.make_jaxpr`:
```python
import einops
import jax.numpy as jnp
import jax

jax.make_jaxpr(
    lambda images: einops.rearrange(images, 'b h w c -> (b h) w c')
)(jnp.zeros((2, 3, 4, 5)))
```
Prints:
```
{ lambda ; a:f32[2,3,4,5]. let
    b:f32[6,4,5] = reshape[dimensions=None new_sizes=(6, 4, 5)] a
  in (b,) }
```

**Comment by carlosgmartin** [comment]
@jon-chuang What I meant was: Is there a way to express the operation "flatten axes from `start` to `end`" in einops, where `start` and `end` are arbitrary integers?

@shoyer 
> I definitely don't think this is fundamental enough to be worth adding as a method.

Flattening seems like a pretty fundamental array operation to me.

**Comment by jakevdp** [comment]
Coming back to this: I'm a bit wary of adding additional arguments to `array.flatten` that diverge from NumPy. I think given that we have an existing API that accomplishes this, we can close this request:
```python
In [1]: import jax
   ...: x = jax.numpy.zeros((2, 3, 4, 5))
   ...: jax.lax.flatten(x, 1, -1)
Out[1]: (2, 12, 5)
```

**Comment by VachanVY** [comment]
> Coming back to this: I'm a bit wary of adding additional arguments to `array.flatten` that diverge from NumPy. I think given that we have an existing API that accomplishes this, we can close this request:
> 
> ```python
> In [1]: import jax
>    ...: x = jax.numpy.zeros((2, 3, 4, 5))
>    ...: jax.lax.flatten(x, 1, -1)
> Out[1]: (2, 12, 5)
> ```

```python
>>> x = jax.numpy.zeros((2, 3, 4, 5))
>>> jax.lax.flatten
AttributeError: module 'jax.lax' has no attribute 'flatten'
>>> jax.lax.collapse(x, 1, -1).shape
(2, 12, 5)
```

**Comment by jakevdp** [comment]
Thanks - I should have written `collapse` instead of `flatten`.

**Comment by cisimon7** [comment]
Seems like the last dimension can not be flattened used jax.lax.collapse. I mean for example in the last example, to flatten all dimensions except the first dimension and get a final shape of (2, 60), how can that be done using collapse? 

```py
>>> x = jax.numpy.zeros((2, 3, 4, 5))
>>> jax.lax.collapse(x, 1, -1).shape
(2, 12, 5)
```

When the shape of `x` is known, I suppose this can be achieved using 1 and 4 for the start and stop dimension, but using -1 is cool especially for cases where the shape of `x` is unknown, so would be nice to have this. Of course there is always a work around, but one would expect this function to be able to handle that.

**Comment by carlosgmartin** [comment]
@cisimon7 Doesn't `stop_dimension=None` (its default value) do what you're asking?

```sh
py -c "import jax; print(jax.lax.collapse(jax.numpy.zeros((2, 3, 4, 5)), 1).shape)"
```
```
(2, 60)
```

**Comment by cisimon7** [comment]
Seems to work. I guess I expected it to work like numpy and pytorch, but a bit different here. Thanks.
