### ISSUE TITLE
Notebook score_matching uses sklearn, which does not exist at Travis

### ISSUE THREAD

**Issue by gnecula** [google/jax#1516]
It would be useful to remove the dependency on sklearn (seems to be only for a couple of 
data sets). This dependency prevents the notebook to be built automatically at Travis. At the moment, this notebook is excluded from automatic building and testing, but if we can remove the dependency then we could test it automatically.

Relates to https://github.com/google/jax/pull/1493 and commit 2e84774

**Comment by shoyer** [comment]
Could we simply add sklearn to our Travis-CI builds? Pre-built wheels should be available for all platforms via pip.

**Comment by gnecula** [comment]
pip works. Tried conda before and did not work. 
See https://github.com/google/jax/pull/1547
