### ISSUE TITLE
Batching np.split doesn't work, or at least error message is cryptic

### ISSUE THREAD

**Issue by sussillo** [google/jax#1517]
I *think* this is a probably a bug. 

```from jax import np, vmap

def mysplit(split_idx, z):
  a, b = np.split(z, (split_idx,), axis=0)
  return a, b

batch_mysplit = vmap(mysplit, in_axes=(None, 0))

z = np.zeros([10])
b, c = mysplit(4, z)
print(b, c)

zs = np.zeros([4, 10])
bs, cs = batch_mysplit(3, zs)
print(bs, cs)


[0. 0. 0. 0.] [0. 0. 0. 0. 0. 0.]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-c66905d82b5c> in <module>()
     13 
     14 zs = np.zeros([4, 10])
---> 15 bs, cs = batch_mysplit(3, zs)
     16 print(bs, cs)

7 frames
google3/third_party/py/numpy/lib/shape_base.py in array_split(ary, indices_or_sections, axis)
    764         st = div_points[i]
    765         end = div_points[i + 1]
--> 766         sub_arys.append(_nx.swapaxes(sary[st:end], axis, 0))
    767 
    768     return sub_arys

TypeError: slice indices must be integers or None or have an __index__ method
```

I guess this breaks because np.split cannot take different split values, and jax does not know that all the split values are the same? np.split is natural to use in larger functions where the split is just one of many operations in a sequence, and one batches the larger function.

**Comment by gnecula** [comment]
I think this could be called a bug in vmap. In the implementation of np.split, JAX calls down to original np.split passing down the split_idx. But when doing vmap, the tracing is done with an abstract value for the split_idx, even though you specifically said that in_axis[0]=None. This kind of situation arises also for `jit`. 

One workaround I can think of is to use partial functions to take the index out of `vmap`s view:
```
from functools import partial
batch_mysplit = vmap(partial(mysplit, 3))
```

Also, better error message would be nice.

**Comment by gnecula** [comment]
Question for JAX experts: Checking that we do not push abstract values into the original numpy functions seems like something generally useful. Is there a good example of how this should be done?

I can try to catch the exception from numpy and display a better error message if I see abstract values anywhere inside the arguments. For this I have to understand which exact exceptions to catch, and I need a way to scan a pytree for abstract values. 

Better it seems to scan some of the arguments for abstract values. This seems better. I assume ConcreteArray are tolerated everywhere?

**Comment by jakevdp** [comment]
Not sure when this was fixed, but it appears to work correctly in the current JAX version:
```python
In [1]: import jax.numpy as np 
   ...: from jax import vmap 
   ...:  
   ...: def mysplit(split_idx, z): 
   ...:   a, b = np.split(z, (split_idx,), axis=0) 
   ...:   return a, b 
   ...:  
   ...: batch_mysplit = vmap(mysplit, in_axes=(None, 0)) 
   ...:  
   ...: z = np.zeros([10]) 
   ...: b, c = mysplit(4, z) 
   ...: print(b, c) 
   ...:  
   ...: zs = np.zeros([4, 10]) 
   ...: bs, cs = batch_mysplit(3, zs) 
   ...: print(bs, cs)                                                                                                                                                                                                                                                                                             
[0. 0. 0. 0.] [0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] [[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
```
