### ISSUE TITLE
jax.scipy.stats module missing Poisson distribution

### ISSUE THREAD

**Issue by matthewfeickert** [google/jax#1518]
Hi. At the moment, the [`jax.scipy.stats` module does not include the Poisson distribution](https://github.com/google/jax/tree/245f40678ed79ff958481dd87b10e03673bdeaa6/jax/scipy/stats).
Poissons would be quite nice to have, and is needed for use in physics libraries such as [pyhf](https://github.com/diana-hep/pyhf/issues/416).

Are there any plans to add the Poisson? If not, are there specific issues that are keeping it from being added or just that a volunteer from the community hasn't stepped up to volunteer the time to do so?

cc @lukasheinrich @kratsg

**Comment by hawkinsp** [comment]
We welcome contributions! I'm not aware of anything preventing a Poisson distribution. Most likely all it needs is a motivated person who wants to add it. If it's useful to you, perhaps implement it and send a PR!

**Comment by matthewfeickert** [comment]
@hawkinsp As it isn't covered in `CONTRIBUTING.md`, does the dev team want contributors to open up WIP PRs right away so they can give early feedback? Or would they prefer that a PR not be opened until it is passing all the tests locally so that the Travis builds don't get clogged with contributor PRs running?

**Comment by justicezyx** [comment]
I want to help with, primary for learning as a new member.

**Comment by hawkinsp** [comment]
@matthewfeickert We are happy either way, at the moment. It's probably not worth opening a PR until you have something that is more or less functionally correct, e.g., some tests passing.

**Comment by matthewfeickert** [comment]
> @matthewfeickert We are happy either way, at the moment. It's probably not worth opening a PR until you have something that is more or less functionally correct, e.g., some tests passing.

Okay great. This was my plan more-or-less, as I have just a few tests failing at the moment due to `nan` vs `inf` behavior.

@justicezyx I'm at a physics conference and travelling for the next few days, so if you have time to implement this in the next week then I say just go for it. :)

**Comment by justicezyx** [comment]
Let me take a look at the existing samples and see how much I can do over the weekends. Let me know if you have any suggestions on where to get started.

Don't expect much, as I am completely new. :( I meant to say that if there is any tasks for newbies, which helps accelerate your work (like doing some manual testing etc.).

So in the worst case, I get nothing done, you (or someone) would need to get the work done anyway.

**Comment by matthewfeickert** [comment]
It looks like this was resolved by @TuanNguyen27 in PR #1608. Thanks!
