### ISSUE TITLE
ndarray.round() stopped working without an argument.

### ISSUE THREAD

**Issue by ssjhv** [google/jax#15190]
### Description

Numpy `round()` as a ndarray member function used to work without an argument but it is no longer working.

```python
_ = jnp.zeros(1).round()
```

Expected to execute without an error, but fails with error message

```
TypeError: round() missing required argument 'number' (pos 1)
```

According to Numpy documentation, this should work without an argument.
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.round.html

### What jax/jaxlib version are you using?

head

### Which accelerator(s) are you using?

cpu

### Additional system info

python 3.10, linux

**Comment by ssjhv** [comment]
Probably related to https://github.com/google/jax/pull/15172

**Comment by mattjj** [comment]
Thanks for the report! #15192 should fix
