### ISSUE TITLE
convolve2d real arrays

### ISSUE THREAD

**Issue by jecampagne** [google/jax#15219]
Hello, 
After discussion  [#15204](https://github.com/google/jax/discussions/15204)

Here is a code to deal with the convolution using FFT of two 2D real arrays. It is mostly inspired from the `scipy.fftconvolve`function.  One use-case & test of this function is available on Colab  [HERE](https://colab.research.google.com/drive/1Ze7nxlQQc05FT_bt1YuxX7PjjYBmBe17?usp=sharing) with the JAX 0.4.6 version (this is the current one at least today). For sure my code is not the best one. Feel free to improve it. 
- I do nit know if the second array in2 can be smaller in size than the first one
- for sure the complex-complex case would need some adaptation
- finally the `next_fast_len` available in scipy  would improve the computation of the "good" FFT size.

```python
@jax.jit
def convolve2r(in1,in2):

  # suppose
  # in1 = jnp.asarray(x1)
  # in2 = jnp.asarray(x2)
  #  "assert" in1.ndim == in2.ndim == 2
  #  "assert" in1.size == in2.size
  #  "assert" in1.dtype.kind == 'f' and in2.dtype.kind == "f"

  axes = range(in1.ndim)

  s1 = in1.shape
  s2 = in2.shape
  shape = [s1[i] + s2[i] -1 for i in range(in1.ndim)]
  
  # crude next_fast_len equivalent with just power of 2
  fshape = 2**np.ceil(np.log2(np.array(shape))).astype('uint16')

  fslice = tuple([slice(sz) for sz in shape])

  sp1 = jnp.fft.fftn(in1, fshape, axes=axes)
  sp2 = jnp.fft.fftn(in2, fshape, axes=axes)
  conv = jnp.fft.irfftn(sp1 * sp2, fshape, axes=axes)
  conv = conv[tuple(map(slice, shape))]   #conv = jax.lax.slice(conv,(0,0),(shape))

  def _centered(arr, newshape):
    # Return the center newshape portion of the array.
    newshape = np.asarray(newshape)
    currshape = np.array(arr.shape)
    startind = (currshape - newshape) // 2
    endind = startind + newshape
    myslice = [slice(startind[k], endind[k]) for k in range(len(endind))]
    return arr[tuple(myslice)]

  return _centered(conv, s1)
```

- [X] Check for duplicate requests.

**Comment by jakevdp** [comment]
Thanks! JAX can't accept code contributions without a CLA, so the best way to proceed if you wanted this pulled into the JAX codebase would be to open a Pull Request. See [Contributing Code using Pull Requests](https://jax.readthedocs.io/en/latest/contributing.html#contributing-code-using-pull-requests) for some information on this.
