### ISSUE TITLE
Solution to issue cannot be found in the documentation.

### ISSUE THREAD

**Issue by Ley-lele** [google/jax#15259]
### Description

when i import jax
i got
```
Using /home/sunlinjun/.cache/torch_extensions/py36_cu102 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/sunlinjun/.cache/torch_extensions/py36_cu102/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adam_upd_cuda...
Traceback (most recent call last):
File "run.py", line 24, in
import train_exp, train_imp
File "/home/sunlinjun/Projects/PureCLIPNeRF/train_exp.py", line 23, in
from lib import utils, dvgo_exp
File "/home/sunlinjun/Projects/PureCLIPNeRF/lib/dvgo_exp.py", line 12, in
from lib.jax_bkgd import augment
File "/home/sunlinjun/Projects/PureCLIPNeRF/lib/jax_bkgd/augment.py", line 19, in
from lib.jax_bkgd import optvis
File "/home/sunlinjun/Projects/PureCLIPNeRF/lib/jax_bkgd/optvis.py", line 22, in
import flax.linen as nn
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/flax/init.py", line 18, in
from . import core as core
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/flax/core/init.py", line 15, in
from .axes_scan import broadcast as broadcast
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/flax/core/axes_scan.py", line 19, in
import jax
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/jax/init.py", line 35, in
from jax import config as _config_module
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/jax/config.py", line 17, in
from jax._src.config import config # noqa: F401
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/jax/_src/config.py", line 25, in
from jax._src import lib
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/jax/_src/lib/init.py", line 87, in
import jaxlib.xla_client as xla_client
File "/home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/jaxlib/xla_client.py", line 26, in
from . import xla_extension as _xla
ImportError: /home/sunlinjun/.conda/envs/PureCLIPNeRF/lib/python3.8/site-packages/jaxlib/xla_extension.so: undefined symbol: PyVectorcall_Call
```

### What jax/jaxlib version are you using?

0.4.6

### Which accelerator(s) are you using?

gpu

### Additional system info

python 3.8 Linux

### NVIDIA GPU info

Tue Mar 28 19:32:39 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.161.03   Driver Version: 470.161.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 5000     Off  | 00000000:02:00.0 Off |                  Off |
| 39%   63C    P2    74W / 230W |   6673MiB / 16125MiB |    100%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Quadro RTX 5000     Off  | 00000000:04:00.0 Off |                  Off |
| 33%   34C    P8    11W / 230W |      3MiB / 16125MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Quadro RTX 5000     Off  | 00000000:83:00.0 Off |                  Off |
| 33%   28C    P8    14W / 230W |      3MiB / 16125MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Quadro RTX 5000     Off  | 00000000:84:00.0 Off |                  Off |
| 33%   29C    P8    12W / 230W |      3MiB / 16125MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      4166      C   python                           5985MiB |
+-----------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
How did you install the jaxlib wheels?

If it's from conda-forge, you should file this issue on the conda-forge feedstock.

`PyVectorcall_Call` is a Python 3.9 symbol (in Python 3.8, it is called `_PyVectorcall_Call`, so it seems like you have a version of jaxlib built for the wrong version of Python to me.)

**Comment by hawkinsp** [comment]
`/home/sunlinjun/.cache/torch_extensions/py36_cu102 as PyTorch extensions root.` is concerning: that sounds like Python 3.6 is involved, somehow?

**Comment by Ley-lele** [comment]
> I use the command 'pip install jax'

**Comment by Ley-lele** [comment]
> 

it's strange. My conda info shows that my python version is 3.8

**Comment by hawkinsp** [comment]
My strong suspicion is that this is a problem with your installation, not JAX. Can you try a fresh installation in a clean environment?

**Comment by Ley-lele** [comment]
> My strong suspicion is that this is a problem with your installation, not JAX. Can you try a fresh installation in a clean environment?

yes. I try a frensh install and it works! Tks a lot!
