### ISSUE TITLE
RuntimeError: Unable to initialize backend 'tpu': module 'jaxlib.xla_extension' has no attribute 'get_tpu_client' (set JAX_PLATFORMS='' to automatically choose an available backend)

### ISSUE THREAD

**Issue by showpiecep** [google/jax#15273]
### Description

%%capture
!pip install --upgrade pip # To support manylinux2010 wheels.
!pip install --upgrade jax jaxlib # CPU-only
!pip install flax
!pip install jax
!pip install optax
!pip install transformers
!pip install datasets
!pip install -U jax[cuda11_cudnn82] -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
!pip install -U jax[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
!git clone https://github.com/huggingface/transformers.git

!python run_t5_mlm_flax.py \
	--output_dir="./norwegian-t5-base" \
	--model_type="t5" \
	--config_name="./norwegian-t5-base" \
	--tokenizer_name="./norwegian-t5-base" \
	--dataset_name="oscar" \
	--dataset_config_name="unshuffled_deduplicated_no" \
	--max_seq_length="512" \
	--per_device_train_batch_size="8" \
	--per_device_eval_batch_size="8" \
	--adafactor \
	--learning_rate="0.005" \
	--weight_decay="0.001" \
	--warmup_steps="2000" \
	--overwrite_output_dir=True \
	--logging_steps="500" \
	--save_steps="10000" \
	--eval_steps="2500" \
    --num_train_epochs=3 \

### What jax/jaxlib version are you using?

jax v0.4.7

### Which accelerator(s) are you using?

TPU

### Additional system info

Google Colab

**Comment by hawkinsp** [comment]
Also note "Google Colab"

Note that JAX has dropped support for Colab (Remote) TPUs in 0.4. If you want a hosted notebook with TPUs, you can either (a) downgrade to 0.3.25, or (b) use Kaggle TPUs, which are fully supported by JAX 0.4.

Hope that helps!

**Comment by hawkinsp** [comment]
Closing. Feel free to comment further if the suggestions above don't help.
