### ISSUE TITLE
Version matched error while "pip install -r requirements.txt"?

### ISSUE THREAD

**Issue by sh0416** [google/jax#15306]
### Description

I've just transport a new machine and found that using pip install through requirements.txt doesn't working.

It seems interesting that it works when I use the script in the README.md.

Working: `pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

Not working: `pip install -r requirements.txt`

Requirements.txt:

```
-f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
jax[cuda11_pip]
```

**Comment by sh0416** [comment]
I think it is just my machine issue. Other package has also encounter the same issue. Sorry;

**Comment by mattjj** [comment]
Glad you got it sorted out!
