### ISSUE TITLE
Best way to define gradient for linear black box function

### ISSUE THREAD

**Issue by clemisch** [google/jax#1530]
Dear jax team,

I'd like to use a black box function in jax with `grad` where the function is a linear operator, i.e. a function `f(x)` executing `A.dot(x)` where `A` is a matrix too large for memory so `A` is computed on-the-fly.

I guess I could define its gradient with `jax.custom_gradient`, but I assumed there are performance benefits in telling jax that the operation is linear? Either way, I would have to provide another black box function computing `A.T.dot(x)`.

Is there a way in jax to do this? Or should I just provide the gradient rule via `jax.custom_gradient`?

**Comment by clemisch** [comment]
From what I've read in #1142 I should rather define `f(x)` as a primitive and define the custom transformations from there. But the question about the linearity remains, can I tell jax about it in a meaningful way?

**Comment by shoyer** [comment]
I don't think JAX has any specific machinery that can take advantage of linear functions yet, but @mattjj and @dougalm would know better than I do.

I agree that this is an interesting question. Which specific gradients of matrix-vector multiplication do you want to compute? You may find my helper functions `_tangent_linear_map` and `_transpose_function` from  `custom_linear_solve` (https://github.com/google/jax/pull/1402) to be helper, but neither implementation is doing anything particularly clever.

I'm also curious about your intended application for these linear functions, and if it might have any overlap with the broader task of writing higher order functions for matrix-free linear algebra (https://github.com/google/jax/issues/1531).

**Comment by jekbradbury** [comment]
If you're willing to define your function as a `core.Primitive`, you can set it up for AD using `ad.deflinear(primitive, transpose_rule)`, where `transpose_rule` is a function that behaves like `A.T.dot(x)`. [This notebook](https://github.com/google/jax/blob/master/docs/notebooks/How_JAX_primitives_work.ipynb) may be helpful for elucidating the current (internal/unstable) API surface for primitives.

**Comment by jekbradbury** [comment]
The kinds of solutions brought up by @shoyer come up if you want to work with (for instance) a _family_ of matrix-free linear operators parameterized by some user-provided function; if you're only interested in a particular operator, or a family of operators parameterized by values rather than functions, implementing the `core.Primitive` interface will be (relatively) straightforward.

**Comment by clemisch** [comment]
Thank you @shoyer for the pointer to your recent work on linear and sparse operations! I'm specifically working on tomographic projection for medical imaging and would be cool to connect that with sparse linear ops, but (with my limited knowledge of the latter) I fear the tomographic system matrix is too big / not sparse enough to fit into that method.

**Comment by shoyer** [comment]
> Are the non-zero entries of the sparse matrices all in memory at some point? Or can the operators be totally opaque black-box functions?

The idea is make everything work based on black-box functions for computing matrix-vector products.

(We don't have support for explicit sparse matrices in JAX yet.)

**Comment by jekbradbury** [comment]
If you want to use black boxes for both of them, you can make the transpose be a call to another primitive function you define. (Note that if you want these functions to be `jit`able, you currently need to use XLA's `CustomCall` interface to wrap your black boxes; a good example on GPU is the cusolver wrappers in jaxlib/cusolver.(py,cc,cu) that are called from [here](https://github.com/google/jax/blob/master/jax/lax_linalg.py#L732-L733))

**Comment by clemisch** [comment]
Thank you for the tip! Ultimately I would like to use end-to-end jit, but having autodiff is already nice to play around. I will look into hooking up the `CustomCall` interface.

**Comment by clemisch** [comment]
Hey @jekbradbury, I have been thinking about this discussion recently. 

I assume `CustomCall` is still the way for hooking up black boxes for jit? My problem is that the implementation of `A.dot(x)` is only available to me as a Python import from a binary blob (compiled .so file). This means that I don't have access to the C++ source. 

Is it possible to hook up `CustomCall` and jit in this situation?

**Comment by shoyer** [comment]
In the worst case, you could back into Python from the `CustomCall` function, e.g., using CPython APIs. It would be nice if we had a wrapper in JAX for doing this on arbitrary code, but it should be doable manually...

**Comment by clemisch** [comment]
Thank you @shoyer for the swift reply! Using CPython's APIs from C++ would be quite a learning curve for me, but definitely good to know! 

I assume there are no concrete plans to realize an interface like #766? As in:

> [...] piping array shape/dtype information and Python functions into XLA's interface, and then reconstructing them on the other side

**Comment by shoyer** [comment]
There is interest in expanding `jax.experimental.host_callback` to support this sort of thing, but not concrete plans that I am aware of at the moment.

**Comment by clemisch** [comment]
Thank you @shoyer for the clarification.

Concerning `grad` without `jit`: I added `A.dot(x)` and `A.T.dot(x)` as primitives and used (something like)

```python
ad.deflinear(Adotx_p, ATdotx_p)
ad.deflinear(ATdotx_p, Adotx_p)
```

to setup autodiff. When I use them in a cost function and request the gradient, I get

```
TypeError: Cannot convert JVPTracer to numpy.ndarray
```

when calling the black box function within the Primitive, as the black box wants a numpy ndarray. When I add an explicit `numpy.array(x)` inside the code called by the Primitive, I get

```
Exception: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ConcreteArray([
[[0. 0. 0. ... 0. 0. 0.]
[...]
[0. 0. 0. ... 0. 0. 0.]]]):JaxprTrace(level=1/0)>
       tangent = Traced<ShapedArray(float32[30,500,500]):JaxprTrace(level=1/0)>.
```

I looked in the [Primitives notebook](https://github.com/google/jax/blob/master/docs/notebooks/How_JAX_primitives_work.ipynb) again but I can't find a hint what to do. Do I have to extract the concrete values from the tracer in a special way?

**Comment by clemisch** [comment]
With #4374 closed, this issue is solved for me. 

I use `host_callback` inside wrapper functions for `A.dot(x)` and `A.T.dot(y)`, respectively. This already enables jit. I get grad by using `jax.custom_vjp` on the wrappers and calling the (respective) other function inside the `bwd` pass. 

This is what I dreamed of when opening this issue!
