### ISSUE TITLE
Bind nccl for jax installation

### ISSUE THREAD

**Issue by sh0416** [google/jax#15307]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

Clear improvement for CUDA installation has been made in 0.4.7.

I really appreciate the contributor's development.

I recently found that nccl also impact the jax execution and @hawkinsp informs me that nccl 2.16.5 is needed. (checkout https://github.com/google/jax/discussions/15233)

I think it would be better to install automatically through pip install.

Or, just informing "installing nccl with 2.16.5 is needed" in the README.md installation section would be sufficient for the user.

Thanks for the library.

**Comment by hawkinsp** [comment]
This is fixed! We now install NCCL via `pip` as of JAX 0.4.18! You can upgrade NCCL via a pip package.
