### ISSUE TITLE
add tests for jax.random shape semantics

### ISSUE THREAD

**Issue by mattjj** [google/jax#1532]
add tests for the logic in #1515

**Comment by rajasekharporeddy** [comment]
Hi @mattjj 

I can see that the PR [#1515](https://github.com/google/jax/pull/1515) has been merged with the required tests are being added. 

Thank you

**Comment by mattjj** [comment]
Thanks for checking! Actually it looks like I made this issue because #1515 did not include enough testing, so the fact that #1515 was merged doesn't by itself mean this issue is complete. 

That said, this is a 4.5 year old issue requesting more tests on one specific feature, and we could probably use more tests on many features. So I'll close this issue as not very useful.

Thanks again!
