### ISSUE TITLE
Create a new PJRT API for registering custom calls and use that instead of xla_client.register_custom_call_target

### ISSUE THREAD

**Issue by vmurali** [google/jax#15357]
In order to run JAX programs with custom calls on other compiler/runtime backends (eg. OpenXLA/IREE), the custom call implementations have to be registered with the backend. PJRT is meant to be the shim-layer between frontends like JAX and backends like XLA and OpenXLA. Right now custom calls are registered only on the XLA backend using `xla_client.register_custom_call_target`. It would be ideal to create a new `register_custom_call_target` in the PJRT API and allow the PJRT clients (such as https://github.com/openxla/openxla-pjrt-plugin) to implement the registration. JAX calls `pjrt.register_custom_call_target` to register the custom call implementations.

**Comment by hawkinsp** [comment]
Indeed.

Currently JAX has three in-tree backends, and on each the behavior is:
* CPU, where a registration is a `(name, function pointer)` pair, where the function pointer is a CPU kernel per https://www.tensorflow.org/xla/custom_call
* GPU, where a registration is a `(name, function pointer)` pair, where the function pointer is to a CPU function that launches GPU kernels per https://www.tensorflow.org/xla/custom_call
* TPU, where you can't register anything yourself at the moment.

However, I note that XLA:current also recently grew a richer FFI interface, courtesy of @ezhulenev . Here what you pass is not a single pointer, but it is instead a richer API: https://github.com/openxla/xla/blob/7f8cfc91dae856f01fa70760f03b01f51b3afe98/xla/runtime/ffi/ffi_c_api.h

JAX does not yet use this, but plans to do so.

I'm unsure whether there is value in trying to come up with a backend-independent API for registering custom kernels at all! Is there enough in common that it is worth it? Perhaps each plugin should have a separate API  for registering custom kernels.

**Comment by vmurali** [comment]
There are two levels of backends here:
a) CPU/GPU/TPU (let's call it the hardware backend)
b) The framework that compiles/jits the code (let's call it the framework backend. e.g. IREE, XLA)

Having a framework-independent API but one that potentially depends on the hardware backend is useful, for instance, to switch between IREE and XLA frameworks.

(Indeed the two types of backends are being conflated, for instance, in the [openxla-pjrt-plugin](https://github.com/openxla/openxla-pjrt-plugin), where `JAX_PLATFORM=iree_cpu` runs the IREE framework with the CPU backend which `JAX_PLATFORM=cpu` runs the XLA framework with the CPU backend.)

**Comment by hawkinsp** [comment]
The approach we've taken so far for our other plugins is that each backend will define its own API for registering custom calls. I'm not sure there is a sensible abstraction for registering custom calls that makes sense between different hardware and software stacks!
