### ISSUE TITLE
JAX profiler will crash on NV gpu

### ISSUE THREAD

**Issue by jzhoulon** [google/jax#15384]
### Description

I installed the jax through "pip install --upgrade "jax[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
", my OS is ubuntu 20.04, my cuda version is 12.1, cudnn version is 8.8.0, python version is 3.9,  the profiler will crash even on the simple 
case.
test case:
```
import jax

with jax.profiler.trace("/tmp/tensorboard"):
  key = jax.random.PRNGKey(0)
  x = jax.random.normal(key, (5000, 5000))
  y = x @ x
  y.block_until_ready()
~                         
```
log info
```
2023-04-04 13:20:26.999736: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
double free or corruption (!prev)
Aborted (core dumped)

```

### What jax/jaxlib version are you using?

jaxlib    0.4.7+cuda12.cudnn88

### Which accelerator(s) are you using?

GPU

### Additional system info

3.9, ubuntu, cuda12.1, cudnn 8.8.0

### NVIDIA GPU info

+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-PCIE-40GB           Off| 00000000:01:00.0 Off |                    0 |
| N/A   39C    P0               35W / 250W|      0MiB / 40960MiB |     38%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
Looks like there are at least two things going on here:
a) on CUDA 11, we're missing a dependency on `cupti` in our `pip` dependencies, and the rpath necessary to find it
b) on CUDA 12, I'm not sure, but I agree it crashes as you say.

**Comment by hawkinsp** [comment]
b) looks to me like a bug in either cupti or the profiler support in XLA.

gdb backtrace:
```
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140460199964672) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140460199964672) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140460199964672, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007fbf70572476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007fbf705587f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007fbf705b96f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7fbf7070bb8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007fbf705d0d7c in malloc_printerr (str=str@entry=0x7fbf7070e7d0 "double free or corruption (!prev)") at ./malloc/malloc.c:5664
#7  0x00007fbf705d2efc in _int_free (av=0x7fbf70749c80 <main_arena>, p=0x557aa7d043a0, have_lock=<optimized out>) at ./malloc/malloc.c:4591
#8  0x00007fbf705d54d3 in __GI___libc_free (mem=<optimized out>) at ./malloc/malloc.c:3391
#9  0x00007fbe4670b77a in ?? () from /home/phawkins/.local/lib/python3.10/site-packages/nvidia/cuda_cupti/lib/libcupti.so.12
#10 0x00007fbe466f4a1a in cuptiFinalize () from /home/phawkins/.local/lib/python3.10/site-packages/nvidia/cuda_cupti/lib/libcupti.so.12
#11 0x00007fbf5344d9e6 in xla::profiler::CuptiErrorManager::Finalize() () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#12 0x00007fbf53438e3b in xla::profiler::CuptiTracer::Finalize() () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#13 0x00007fbf5343afbf in xla::profiler::CuptiTracer::Disable() () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#14 0x00007fbf5342b8d0 in xla::profiler::GpuTracer::Stop() () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#15 0x00007fbf534605cc in tsl::profiler::ProfilerController::Stop() () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#16 0x00007fbf5345f87c in tsl::profiler::ProfilerCollection::Stop() () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#17 0x00007fbf5345f016 in tsl::ProfilerSession::CollectDataInternal(tensorflow::profiler::XSpace*) () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#18 0x00007fbf5345f134 in tsl::ProfilerSession::CollectData(tensorflow::profiler::XSpace*) () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#19 0x00007fbf5342874a in pybind11::cpp_function::initialize<xla::BuildProfilerSubmodule(pybind11::module_*)::{lambda(tsl::ProfilerSession*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#4}, tsl::Status, tsl::ProfilerSession*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, pybind11::name, pybind11::is_method, pybind11::sibling>(xla::BuildProfilerSubmodule(pybind11::module_*)::{lambda(tsl::ProfilerSession*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)#4}&&, tsl::Status (*)(tsl::ProfilerSession*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
#20 0x00007fbf531fb531 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /home/phawkins/.local/lib/python3.10/site-packages/jaxlib/xla_extension.so
```

**Comment by jzhoulon** [comment]
is there any workaround, cuda 11 is not working , it will crash with cudnn intilization failed, seem currently it requires cudnn 8.8

**Comment by jakubMitura14** [comment]
Having the same problem

**Comment by vputz** [comment]
Same problem here, jax-0.4.8 or 0.4.7 with the GPU, tried cuda 11 or 12.  I get the "double free or corruption (!prev)" before the crash, but I also get the "TF-TRT Warning: Could not find TensorRT" both times even after trying to install tensorrt (but I may have done that incorrectly).

Very frustrating as we're trying to find out why many of our routines are taking so very long with the GPU enabled.

**Comment by hawkinsp** [comment]
This issue is only about a CUDA 12 bug. The workaround is to downgrade to CUDA 11.

If you are having problems on CUDA 11, please share details on how to reproduce.

**Comment by hawkinsp** [comment]
I'm not sure which change fixed it, but I can't reproduce this with JAX 0.4.20 under CUDA 12. I think we can declare this fixed.
