### ISSUE TITLE
Sparsified einsum throws exception

### ISSUE THREAD

**Issue by quattro** [google/jax#15393]
### Description

Hi all, I ran into another issue with `jax.experimental.sparse.sparsify` and `jax.numpy.einsum`. The issue seems to be with how the `subscripts` argument is dealt with. Here is a MWE,

```python
import jax
import jax.numpy as jnp
import jax.experimental.sparse as xsp

import jax.random as rdm

N, P, K = 50, 10, 2

key = rdm.PRNGKey(2)
key, g_key = rdm.split(key)
G = xsp.random_bcoo(g_key, (N, P))

key, l_key = rdm.split(key)
L = rdm.normal(l_key, shape=(K, N))

key, r_key = rdm.split(key)
R = rdm.normal(r_key, shape=(P, K))

def func(L, M, R):
    return jnp.einsum("kn,np,pk->", L, M, R)
    
sp_f = xsp.sparsify(func)
print(sp_f(L, G, R))  # prints 5.192682

sp_einsum = xsp.sparsify(jnp.einsum)
print(sp_einsum("kn,np,pk->", L, G, R))  # throws ValueError: format number 3 of "kn,np,pk->" is not recognized
```

It isn't clear to me if this is expected behavior or not.  

### What jax/jaxlib version are you using?

0.4.8 / 0.4.7

### Which accelerator(s) are you using?

CPU

### Additional system info

Mac

**Comment by jakevdp** [comment]
This is expected: at the moment, the sparsify transform has no support for static arguments. The best way to proceed is by sparsifying a function that closes over any static arguments, as in you did in your working example.

**Comment by quattro** [comment]
Thanks again. And apologies for multiple bug submissions that match expected behavior.
