### ISSUE TITLE
AttributeError: module 'jax.scipy' has no attribute 'gamma'

### ISSUE THREAD

**Issue by williambeordo** [google/jax#15409]
Hi everyone, I was wondering why the gamma() function is missing, while gammaln() is present.
I suggest you add it in a future edit, because this raises an AttributeError using the function pytensor.tensor.math.gamma() in a pymc model. Thank you so much for your work.

**Comment by williambeordo** [comment]
Thanks for your reply. Yes, I could try!

**Comment by laqua-stack** [comment]
Thanks! 
I am interested in this as well. I need the gamma function for pymc when using blackjax for sampling NUTS.

@jakevdp Do you have resources on how to implement such a function? Is there a template? I would be happy to contribute in that case.

**Comment by jakevdp** [comment]
In this case, I suspect the best implementation would be
```python
def gamma(z):
  return jnp.exp(loggamma(z)
```
