### ISSUE TITLE
Add preferred_element_type to jax.numpy.einsum

### ISSUE THREAD

**Issue by jewillco** [google/jax#15471]
The `jax.lax.dot_general`, `jax.lax.conv_general_dilated`, etc. functions have a `preferred_element_type` parameter to set their output types. Since `jax.numpy.einsum` is a user-friendly way of accessing these, it would be nice to have the `preferred_element_type` parameter there as well.

**Comment by jakevdp** [comment]
Thanks! Seems like a reasonable addition.
