### ISSUE TITLE
L-BFGS fails when ftol is met

### ISSUE THREAD

**Issue by Linusnie** [google/jax#15486]
### Description

Hi, I'm looking into using the experimental L-BFGS (implemented in https://github.com/google/jax/pull/6053) solver for a convex optimization problem. However I noticed the solver fails with status 4 (saddle point reached) whenever f_k - f_kp1 < ftol in any iteration, see [here](https://github.com/google/jax/blob/main/jax/_src/scipy/optimize/_lbfgs.py#L169). Can be reproduced by setting `gtol` low enough that `ftol` is reached first:

```
def f(x):
    return (x**2).sum() + jnp.exp(x.sum())

results = jax.scipy.optimize.minimize(f, jnp.array([0.0]), method='l-bfgs-experimental-do-not-rely-on-this', options=dict(gtol=1e-10))
print(results.success) # prints False
```
in this case the solver reaches the global minimum, but reports failure since the reduction in function value eventually becomes too small
![Figure 3](https://user-images.githubusercontent.com/12471058/230714789-a1454a18-fcd8-4188-9c86-4976b56a48d9.png)

As far as I can tell this is a bug, I'd expect one of the following behaviors:
* converge whenever either ftol or gtol is reached
* converge when ftol and gtol are both reached
* remove the ftol option (as in [BFGS](https://github.com/google/jax/blob/main/jax/_src/scipy/optimize/bfgs.py))

I'm not familiar enough with optimizer implementations to say which way is more appropriate in this case, but I'd be happy to submit a PR if people here can offer some guidance

### What jax/jaxlib version are you using?

jax v0.4.8, jaxlib v0.4.7

**Comment by jakevdp** [comment]
Thanks for the report! With a method name like `'l-bfgs-experimental-do-not-rely-on-this'` I think it's safe to say this is a bug 😀 

Looking at #6053, it seems that it was merged with the expectation that there would be some followup work. GIven that it's been two years and that work hasn't happened, I think the best solution to this bug would be to delete the code (unless someone steps up to take it on). What do you think?

**Comment by Linusnie** [comment]
on initial tests the code seems to work very well (ignoring the bug :smile:), so would be a shame to delete I think.

Judging from https://github.com/google/jax/pull/6053 what's missing for a "full merge" is a test that checks step-by-step equivalence with scipy, but that seems overly tricky since implementation details differ in non-obvious ways. Also should note [BFGS](https://github.com/google/jax/blob/5b3d20345361de51897fa9a4f326900907ccfbfe/tests/scipy_optimize_test.py#L67) doesn't have such a test either

Depending on what's missing I'd be able to spend some time improving the tests, perhaps @shoyer or @Jakob-Unfried could comment?

**Comment by shoyer** [comment]
JAXopt has L-BFGS now (see https://jaxopt.github.io/stable/_autosummary/jaxopt.LBFGS.html) and would be my recommended alternative.

**Comment by Linusnie** [comment]
thanks for the suggestion! works about the same on my problem so I'll probably end up switching to jaxopt
