### ISSUE TITLE
jax.scipy.optimize missing from simple jax install

### ISSUE THREAD

**Issue by kwesiRutledge** [google/jax#15488]
### Description

I am attempting to use `jax.scipy.optimize` in a small extension to the external project `trajax`. Unfortunately, when I tried to access the method (which is documented on Jax's website), I received this error:
```
AttributeError: module 'jax.scipy' has no attribute 'optimize
```

I realized that it looks like optimize is not yet exported from jax.scipy. I implemented a simple fix on my local machine. Would the jax developers appreciate me making a small pull request for this?

### What jax/jaxlib version are you using?

v0.4.8 (jax)/ v0.4.7 (jaxlib)

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.9.6,

**Comment by jakevdp** [comment]
Thanks! You should be able to import it explicitly:
```python
from jax.scipy import optimize
```
`optimize` is not imported by default in the `jax.scipy` namespace; I'm not sure whether or not this is intentional.

**Comment by kwesiRutledge** [comment]
Ah! I didn't know this! 

If this was intentional, then feel free to delete my PR!

**Comment by jakevdp** [comment]
Re-opening because I'm not sure if this was intentional!

Peter, should we add `optimize` to the default `jax.scipy` namespace imports?

**Comment by hawkinsp** [comment]
I'm going to close this issue, because at this point I think we're leaning towards removing `jax.scipy.optimize` entirely and having users use a package such as `jaxopt`.
