### ISSUE TITLE
Looped collectiveeinsum for hiding communication cost

### ISSUE THREAD

**Issue by sh0416** [google/jax#15490]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

I've found that there is some direction that hiding the communication time while computing einsum ops.
Link: https://dl.acm.org/doi/pdf/10.1145/3567955.3567959
I think it would be implemented somewhere since the affiliation of the paper is Google and used in TPU chips.
Is there any reference implementation that I could follow?

Also, I found this information while reading the following paper.
Link: https://arxiv.org/abs/2211.05102
If anyone who knows some reference implementations or materials that help to implement it, please let me know.

Thank you for your support.

**Comment by shoyer** [comment]
Code for "Efficiently scaling transformer inference" can be found here:
https://github.com/google-research/google-research/tree/master/scaling_transformer_inference_efficiency

**Comment by sh0416** [comment]
Thank you. I will dig out that code.
