### ISSUE TITLE
OverflowError on assignment of valid value to uint32 array

### ISSUE THREAD

**Issue by Sohl-Dickstein** [google/jax#15505]
### Description

```python
import jax.numpy as jnp

a = jnp.zeros((1), dtype=jnp.uint32)
val = 2**32 - 1
# val and its uint32 representation are identical
print(val, jnp.uint32(val))
# assignment works with an explicit cast to uint32
b = a.at[1].set(jnp.uint32(val))
# assignment with an implicit cast throws an exception
b = a.at[1].set(val) # returns OverflowError 
```

**Comment by mattjj** [comment]
Thanks for reporting this, and the clear repro!

#15506 might fix it, but it currently causes a "deprecation warning" test to fail (i.e. we no longer raise a warning), and so I need advice from @jakevdp on how to proceed.

**Comment by Sohl-Dickstein** [comment]
(Unlikely to be relevant, but I just noticed that I wrote `a.at[1]` while `a.at[0]` would have made more sense, since `a` is length 1.)

**Comment by jakevdp** [comment]
@mattjj - is this something we can fix? At the JIT boundary, Python scalars like `1` have to be converted to objects of specific dtypes, and we made the decision long ago to not use value-dependent semantics when choosing that dtype. So, unless `jax_enable_x64` is set to True, every Python integer will be represented as an `int32`, regardless of whether it eventually is intended to be converted to `uint32`.

With that in mind, isn't this working as expected?

**Comment by jakevdp** [comment]
I should spell-out the subtext of my comment. We want
```python
x.at[0].set(1)
```
to act the same inside and outside JIT, so it follows that this should produce the same result:
```python
jax.jit(x.at[0].set)(1)
```
But when `1` hits a `jit` boundary, it must be converted to a JAX array with a particular `dtype`. We always choose `int32`, and so passing a python scalar that does not fit into `int32` should result in an error.

**Comment by Sohl-Dickstein** [comment]
Thanks for spelling it out clearly! If I understand correctly, I think consistency across the jit boundary is a separate issue from whether assignment works without a jit boundary. Especially, I think assignment of uint32 is already handled differently when it crosses a jit boundary. See this snippet:

```Python
def gen_a(val):
  a = jnp.zeros((1), dtype=jnp.uint32)
  return a.at[0].set(jnp.uint32(val))

val = 2**32 - 1
gen_a(val) # executes
jit(gen_a)(val) # throws OverflowError
```

**Comment by jakevdp** [comment]
Yeah, that's a good point. We should be able to support this kind of assignment in the case that the scalar does not cross a tracing boundary.
