### ISSUE TITLE
FP8 or F1 type support

### ISSUE THREAD

**Issue by sh0416** [google/jax#15580]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

I think h100 support fp8. And it is actually inside cuda12.1. Is there ant plan to support this datatype?

**Comment by jakevdp** [comment]
We have made some progress on this – for example, there are two fp8 types defined within JAX currently: https://github.com/google/jax/blob/39f7e16c331e77e05f2944acea6863798aa6036d/jax/_src/dtypes.py#L40-L42

**Comment by sh0416** [comment]
Great! Could I get some snippet to use this functionality? I want something like this.

```
import jax
import jax.numpy as jnp

x = jnp.zeros((4, 4), dtype=jnp.float8)
```

**Comment by sh0416** [comment]
Ah..! It works.
```
import jax
import jax.numpy as jnp

x = jnp.zeros((4, 4), dtype=jnp.float8_e4m3fn)
```
