### ISSUE TITLE
jaxlib-0.1.31-cp36-none-linux_x86_64 missing

### ISSUE THREAD

**Issue by JuliusKunze** [google/jax#1558]
`https://storage.googleapis.com/jax-wheels/cuda100/jaxlib-0.1.31-cp36-none-linux_x86_64.whl` does not exist. Is this build still being added?

**Comment by hawkinsp** [comment]
The storage bucket name changed, it's now `jax-releases`. See:
https://github.com/google/jax#pip-installation

Hope that helps!
