### ISSUE TITLE
jnp.linalg.lstsq returns very different results from np.linalg.lstsq

### ISSUE THREAD

**Issue by brianwa84** [google/jax#15591]
### Description

JAX produces a wildly different value, perhaps because of the heavy regularization implied by the appended rows?

```python
import numpy as np
import jax.numpy as jnp

np.random.seed(123)
dtype = np.float32
scale = 1.
d = 2
n=int(1e4)
model_coefficients = (np.random.uniform(size=(d,)) - .5).astype(dtype)
radius = np.sqrt(2.).astype(dtype)
model_coefficients *= radius / np.linalg.norm(model_coefficients)
model_matrix = np.random.randn(n, d).astype(dtype)
scale = dtype(scale)
linear_response = np.tensordot(
    model_matrix, model_coefficients, axes=[[1], [0]])
response = (
    np.random.randn(*linear_response.shape) * scale + linear_response
    ).astype(dtype)

print('numpy:',
      np.linalg.lstsq(np.concatenate((model_matrix, [[0, 0], [0, 3e6]]), axis=0),
                      np.pad(response, ((0, 2),)),
                      rcond=None)[0])
print('jax:',
      jnp.linalg.lstsq(np.concatenate((model_matrix, [[0, 0], [0, 3e6]]), axis=0),
                       np.pad(response, ((0, 2),)),
                       rcond=None)[0])
```

=>

```
numpy: [ 9.40102752e-01 -1.14622907e-09]
jax: [-3.3566094e-20 -1.1180160e-09]
```

### Which accelerator(s) are you using?

CPU

### Additional system info

Colab

**Comment by jakevdp** [comment]
Hi - thanks for the question! This looks like a precision issue: numpy uses `float64` by default, while JAX uses `float32` by default (See [JAX Sharp Bits: Double Precision](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision)).

You can enable 64-bit precision by putting this at the top of your script:
```python
import jax
jax.config.update('jax_enable_x64', True)
```
If I do that then I see the following output:
```
numpy: [ 9.40102752e-01 -1.14622907e-09]
jax: [ 9.40102752e-01 -1.14622907e-09]
```

**Comment by brianwa84** [comment]
Pulling a tip from https://github.com/google/jax/issues/11433, setting rcond=0. does the trick, I'll do that if we're in f32 precision.

**Comment by jakevdp** [comment]
Sounds good! I think this can probably be closed, as it's working as expected.
