### ISSUE TITLE
What is the most efficient way to compute diagonal elements of a square Jacobian?

### ISSUE THREAD

**Issue by aeftimia** [google/jax#1563]
I am working on implementing some normalizing flows in Jax. In the Pytorch implementations, they make custom forward passes that pass around and modify the log(det(jac)) with each layer. While this is obviously possible in Jax, I thought there was a decent chance there was a more compact way of doing this.

Most published realizations are engineered to produce a triangular jacobian, and we only need the trace of the [elementwise] log of this matrix to get logdetjac for training. Therefore, I thought there might be a clever way to use `vmap` to efficiently retrieve the diagonal elements of the jacobian. If there is, I have not been able come up with it.

Any thoughts?

**Comment by shoyer** [comment]
`vmap` isn't magic -- all it does is rewrite code for you with an extra broadcasting dimensions, i.e., from N dimensional arrays to N+1 dimensional arrays. For example, you can use vmap to turn a computation that acts on vectors into a computation that acts on matrices.

If you can't figure out how to write what you want by hand with extra dimensions by hand, then vmap probably can't help. It's a little hard to say without a concrete example. but computing only diagonal elements of a matrix doesn't sound like a vmap problem to me.

**Comment by aeftimia** [comment]
@shoyer 
The following code
```
import jax

f = lambda x: x**2

def diag_grad(f, x):
    def partial_grad_f_index(i):
        def partial_grad_f_x(xi):
            catted = jax.numpy.concatenate((x[:i], jax.numpy.asarray([xi]), x[i:]), axis=0)
            return f(catted)[i]
        return jax.grad(partial_grad_f_x)(x[i])
    print(partial_grad_f_index(jax.numpy.arange(x.shape[0])[1]))
    return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))

diag_grad(f, jax.numpy.arange(4, dtype='float'))
```

Produces the following error:

```
2.0
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-44-c58d3aadcd5c> in <module>
     12     return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))
     13 
---> 14 diag_grad(f, jax.numpy.arange(4, dtype='float'))

<ipython-input-44-c58d3aadcd5c> in diag_grad(f, x)
     10         return jax.grad(partial_grad_f_x)(x[i])
     11     print(partial_grad_f_index(jax.numpy.arange(x.shape[0])[1]))
---> 12     return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))
     13 
     14 diag_grad(f, jax.numpy.arange(4, dtype='float'))

/usr/lib/python3.6/dist-packages/jax/api.py in batched_fun(*args)
    612     flat_fun, out_tree = flatten_fun_nokwargs(f, in_tree)
    613     out_flat = batching.batch(flat_fun, args_flat, _flatten_axes(in_tree, in_axes),
--> 614                               lambda: _flatten_axes(out_tree(), out_axes))
    615     return tree_unflatten(out_tree(), out_flat)
    616 

/usr/lib/python3.6/dist-packages/jax/interpreters/batching.py in batch(fun, in_vals, in_dims, out_dim_dests)
     39 
     40 def batch(fun, in_vals, in_dims, out_dim_dests):
---> 41   out_vals, out_dims = batch_fun(fun, in_vals, in_dims)
     42   size, = {x.shape[d] for x, d in zip(in_vals, in_dims) if d is not not_mapped}
     43   return map(partial(matchaxis, size), out_dims, out_dim_dests(), out_vals)

/usr/lib/python3.6/dist-packages/jax/interpreters/batching.py in batch_fun(fun, in_vals, in_dims)
     46   with new_master(BatchTrace) as master:
     47     fun, out_dims = batch_subtrace(fun, master, in_dims)
---> 48     out_vals = fun.call_wrapped(*in_vals)
     49     del master
     50   return out_vals, out_dims()

/usr/lib/python3.6/dist-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    163 
    164     del gen
--> 165     ans = self.f(*args, **dict(self.params, **kwargs))
    166     del args
    167     while stack:

<ipython-input-44-c58d3aadcd5c> in partial_grad_f_index(i)
      8             catted = jax.numpy.concatenate((x[:i], jax.numpy.asarray([xi]), x[i:]), axis=0)
      9             return f(catted)[i]
---> 10         return jax.grad(partial_grad_f_x)(x[i])
     11     print(partial_grad_f_index(jax.numpy.arange(x.shape[0])[1]))
     12     return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))

/usr/lib/python3.6/dist-packages/jax/core.py in __array__(self)
    284 
    285   def __array__(self):
--> 286     raise Exception("Tracer can't be used with raw numpy functions. "
    287                     "You might have\n  import numpy as np\ninstead of\n  import jax.numpy as np")
    288 

Exception: Tracer can't be used with raw numpy functions. You might have
  import numpy as np
instead of
  import jax.numpy as np
```

Based on the print statement, I would think this approach should work. Maybe I'm misusing `vmap` here, and I should not assume would work in this scenario, but it is not obvious to me why it would not work.

**Comment by shoyer** [comment]
`jax.numpy.arange()` has some strange behavior which explains the error you're seeing (https://github.com/google/jax/issues/1564). Try replacing your last line with:
```python
diag_grad(f, jax.device_put(jax.numpy.arange(4, dtype='float')))
```

You'll see that you run into another error, from the line `catted = jax.numpy.concatenate((x[:i], jax.numpy.asarray([xi]), x[i:]), axis=0)`:
`IndexError: Array slice indices must have static start/stop/step to be used with Numpy indexing syntax. Try lax.dynamic_slice/dynamic_update_slice instead.`

It seems that we currently don't support `vmap` over a slice operation with a dynamic start/stop, because this can't be rewritten into a single array indexing operation.

**Comment by aeftimia** [comment]
@shoyer 

```
import jax

f = lambda x: x**jax.numpy.arange(len(x))

def diag_grad(f, x):
    def partial_grad_f_index(i):
        def partial_grad_f_x(xi):
            return f(jax.ops.index_update(x, i, xi))[i]
        return jax.grad(partial_grad_f_x)(x[i])
    return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))

diag_grad(f, jax.device_put(jax.numpy.arange(4, dtype='float')))
```

returns
```
diag_grad(f, jax.device_put(jax.numpy.arange(4, dtype='float')))
```

Which, indeed matches the diagonal of
```
jax.jacfwd(f)(jax.numpy.arange(4, dtype='float'))
```

I also found this can be batched as follows:

```
import jax

f = lambda x: x**jax.numpy.arange(len(x))

def jacdiag(f):
    def _jacdiag(x):
        def partial_grad_f_index(i):
            def partial_grad_f_x(xi):
                return f(jax.ops.index_update(x, i, xi))[i]
            return jax.grad(partial_grad_f_x)(x[i])
        return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))
    return _jacdiag

a = jax.device_put(jax.numpy.asarray([jax.numpy.arange(4, dtype='float')] * 3))
jax.vmap(jacdiag(f))(a)
```

This returns
```
DeviceArray([[ 0.,  1.,  4., 27.],
             [ 0.,  1.,  4., 27.],
             [ 0.,  1.,  4., 27.]], dtype=float32)
```

Thank you very much for your help! 
Alex

**Comment by shoyer** [comment]
OK, that looks pretty clever! I would be curious to learn how efficient this is.

**Comment by aeftimia** [comment]
Something might be wrong with my mental model of how Jax works.

```
import jax

f = lambda x: jax.numpy.exp(-x / jax.numpy.arange(len(x))) * x.mean()

def jacdiag(f):
    def _jacdiag(x):
        def partial_grad_f_index(i):
            def partial_grad_f_x(xi):
                return f(jax.ops.index_update(x, i, xi))[i]
            return jax.grad(partial_grad_f_x)(x[i])
        return jax.vmap(partial_grad_f_index)(jax.numpy.arange(x.shape[0]))
    return _jacdiag

vmap_jacdiag = jax.jit(jax.vmap(jacdiag(f)))

def naive_jacdiag(f):
    def _naive_jacdiag(x):
        return jax.numpy.diagonal(jax.jacfwd(f)(x))
    return _naive_jacdiag

vmap_naive_jacdiag = jax.jit(jax.vmap(naive_jacdiag(f)))

def test_fast(a):
    vmap_jacdiag(a)
    
def test_naive(a):
    vmap_naive_jacdiag(a)

import timeit
print(min(timeit.repeat('test_naive(a)',
    '''
from __main__ import test_naive, jax
a = jax.device_put(jax.numpy.asarray([jax.numpy.arange({n}, dtype='float')] * 32))
test_naive(a)
    '''.format(n=500),
    number=100)))
print(min(timeit.repeat('test_fast(a)',
    '''
from __main__ import test_fast, jax
a = jax.device_put(jax.numpy.asarray([jax.numpy.arange({n}, dtype='float')] * 32))
test_fast(a)
    '''.format(n=500),
    number=100)))
```
returns (on my laptop)

```
1.0334390750000004
2.8360289849999987
```

I've tried playing around with the input size, and generally found the "fast" approach was at best very slightly faster than just taking the diagonal of the output of `jacfwd`.

Possible factors:
1. I'm not using a complicated enough function--the one I used generally has nonzero elements in ever entry of the Jacobian
2. I do not understand how `jit` works, and this is to be expected--technically the "fast" approach computes the entire vector valued function `N` times (where `N` is the number of inputs and outputs) the with each forward pass, but I thought that backpropagating would eliminate the redundancy.
3. I am not using enough inputs--if my custom approach works the way I think it should be working, the "fast" method should be `O(N)` and the "naive" method should be (worst case) `O(N^2)`. It's also possible that `jacfwd` is working efficiently enough to on the function I tested on that I'm not hitting the worst case asymptote.

**Comment by mattjj** [comment]
This issue is super old, so I'm going to close it for staleness!
