### ISSUE TITLE
jacfwd fails on a function that returns BCOO

### ISSUE THREAD

**Issue by terhorst** [google/jax#15654]
### Description

This code returns a sparse weight vector for linearly interpolating the input point `x` on a one-dimensional regular grid:

```
def w(x, M) -> BCOO:
    r"linear interpolation weights for x \in [0, 1] with M equispaced grid points"
    z = jnp.linspace(0, 1, M)
    i = jnp.searchsorted(z, x) - 1
    delta = 1 / (M - 1)
    w = (x - z[i]) / delta
    data = jnp.array([1. - w, w])
    inds = jnp.array([[i, i + 1]]).T
    return BCOO((data, inds), shape=(M,))
```
The primal output does what I expect:
```
>>> w(.3, 5)
BCOO(float32[5], nse=2)
>>> w(.3, 5).todense()  
Array([0.        , 0.79999995, 0.20000005, 0.        , 0.        ],      dtype=float32)
```
The Jacobian of above should be a sparse vector with entries `[0, -1/delta, 1/delta, 0, 0]`. Indeed, this is what I get if I cast the output to dense:
```
>>> jacfwd(lambda x: w(x, 5).todense())(.3)
Array([ 0., -4.,  4.,  0.,  0.], dtype=float32)
```
However, for some reason jacfwd chokes if the function returns a `BCOO`:
```
>>> jacfwd(w)(.3, .5)
...
File ~/opt/py310/lib/python3.10/site-packages/jax/experimental/sparse/bcoo.py:146, in _validate_bcoo_indices(indices, shape)
    145 def _validate_bcoo_indices(indices: Buffer, shape: Sequence[int]) -> BCOOProperties:
--> 146   assert jnp.issubdtype(indices.dtype, jnp.integer)
    147   shape = tuple(shape)
    148   nse, n_sparse = indices.shape[-2:]

AssertionError: 
```
Is this just a limitation of the current sparse matrix implementation? Or is there some sort of workaround?

### What jax/jaxlib version are you using?

jax v0.4.8, jaxlib v0.4.7

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10

**Comment by jakevdp** [comment]
This is expected, unfortunately. It's not possible to override the semantics of `jax.jacfwd` for sparse outputs. This should give you the result you're after:
```python
mat = w(0.3, 5)
mat.data = jax.jacfwd(lambda x, M: w(x, M).data)(0.3, 5)
print(mat.todense())
# [ 0. -4.  4.  0.  0.]
```
