### ISSUE TITLE
Cache compiled functions to disk

### ISSUE THREAD

**Issue by clemisch** [google/jax#1566]
Dear jax team,

is there any API to cache compiled `jit`ed functions to disk? Maybe similar to [numba's](https://numba.pydata.org/numba-doc/dev/user/jit.html#cache) `@jit(cache=True)`.

**Comment by jekbradbury** [comment]
Unfortunately, XLA:GPU is purely a just-in-time compiler and doesn't currently support serializing its binaries. (XLA on CPU does support this, but we don't wrap that functionality in JAX).

**Comment by clemisch** [comment]
Too bad, but thank you for the clarification!

**Comment by samuela** [comment]
Note that this does seem to be experimentally supported on TPUs now: https://github.com/google/jax/issues/476#issuecomment-1015773039. tbd on CPU/GPU support

**Comment by onurdanaci** [comment]
I hope this is supported for GPU in the future. The community needs it.

**Comment by hawkinsp** [comment]
@onurdanaci I believe this *does* work on GPUs now!

**Comment by cool-RR** [comment]
As far as I can see, this works on CPU as well.
