### ISSUE TITLE
`jax.numpy.asarray` does not function under autodiff

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#15676]
### Description

```python
import jax
p, t = jax.jvp(jax.numpy.asarray, (1.,), (2.,))
print(p, type(p))
print(t, type(t))
# 1.0 <class 'float'>
# 2.0 <class 'float'>
```
In particular the primal computation produces a different type than is produced without autodiff, via just `jax.numpy.asarray(1.)`.

### What jax/jaxlib version are you using?

JAX 0.4.8

**Comment by mattjj** [comment]
Thanks for noticing this and reporting it so clearly!

**Comment by patrick-kidger** [comment]
For anyone else still getting bit by this, my workaround is pretty simple:
```python
@jax.custom_jvp
def fixed_asarray(x):
    return jnp.asarray(x)

@fixed_asarray.defjvp
def _fixed_asarray_jvp(x, tx):
    (x,) = x
    (tx,) = tx
    return fixed_asarray(x), fixed_asarray(tx)
```

**Comment by jakevdp** [comment]
I just hit this in refactoring `jnp.dot` in #16721. @mattjj - any plans on this?
