### ISSUE TITLE
feat (scipy.special): Add hyp1f1 confluent hypergeometric function

### ISSUE THREAD

**Issue by laqua-stack** [google/jax#15670]
I would like to implement a logpdf for the sum of n=2 independent gamma distributions for pymc.
For the special case of n=2 Mathai's Method can be used like Eqn. 3 in [https://doi.org/10.1007/s00180-019-00924-9](https://doi.org/10.1007/s00180-019-00924-9) which involves the confluent hypergeometric function $\prescript{}{1}{\mathbf{F}}{_1}(a,b,z)$. 
- scipy.special ships with the hyp1f1 function.
- The C source code can be found [here](https://github.com/scipy/scipy/blob/main/scipy/special/cephes/hyperg.c).

What would be the way to go? Translate the code into pure Python/Numpy and let jax handle it with jit?
I think Tensorflow's XLA has no variant of the function, but one for the (~~confluent~~) hypergeometric function $\prescript{}{2}{\mathbf{F}}{_1}(a,b,z)$ [cf. here](https://www.tensorflow.org/probability/api_docs/python/tfp/math/hypergeometric/hyp2f1_small_argument)

Are there any plans (maybe also considering XLA developement) to add such a functionality?

**Comment by JGameCreation** [comment]
This would be useful for me too! Did you find an alternative in the meantime?

**Comment by CAClaveau** [comment]
For me as well! +1

**Comment by renecotyfanboy** [comment]
I think that the implementation proposed by [Gil & al 2023](https://doi-org.insu.bib.cnrs.fr/10.1007/s11075-023-01515-y) might be suited for JAX. I'll try to translate it in LAX/JAX in the next days
