### ISSUE TITLE
Add support back for 'preferred_element_type' arg in jnp.dot

### ISSUE THREAD

**Issue by dallatt** [google/jax#15683]
Hello Jax team,

I hope you are doing well.

Do you intend to support the `preferred_element_type` argument in `jnp.dot` in the near future? This was already integrated in [#4465](https://github.com/google/jax/issues/4465) but removed right away because "the numeric behavioral and return type rules of the dtype parameter in numpy seem to differ quite substantially from the preferred_element_type in XLA" (from this [comment](https://github.com/google/jax/pull/5213#issuecomment-749328317)). 

Thank you!

**Comment by rajasekharporeddy** [comment]
Hi @dallatt

Looks like ```preferred_element_type``` argument has been added to ```jnp.dot``` in latest version of JAX. The [PR](https://github.com/google/jax/pull/18647) related to the documentation of the same was merged already. You can find the related documentation here: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.dot.html

Thank you

**Comment by jakevdp** [comment]
Thanks! Indeed this looks like it's been fixed by #17506. Thanks!

**Comment by dallatt** [comment]
Awesome, thank you all!
