### ISSUE TITLE
exceptions that reach the user should have public type (e.g. ConcretizationTypeError)

### ISSUE THREAD

**Issue by mattjj** [google/jax#15691]
Consider `except jax._src.errors.ConcretizationTypeError: # pylint: disable=protected-access`. Lame!

**Comment by mattjj** [comment]
Actually, these already have a public name, and are [documented](https://jax.readthedocs.io/en/latest/errors.html), e.g. `jax.errors.ConcretizationTypeError` after we `import jax`.

**Comment by jakevdp** [comment]
We can improve this situation by making the repr of the errors print their public path; #15698 should take care of that
