### ISSUE TITLE
Support for complex numbers in jax.lax.linalg.tridiagonal_solve

### ISSUE THREAD

**Issue by tomsturges** [google/jax#15718]
It seems that tridiagonal_solve does not support complex128. But I believe the algorithm used is, in general, valid for matrices with complex entries. So can it be modified to support complex128?

Thanks,
Tom

```
File ~/opt/anaconda3/envs/pml/lib/python3.9/site-packages/jax/_src/lax/linalg.py:1811, in tridiagonal_solve(dl, d, du, b)
   1809 t = dl.dtype
   1810 if t not in (np.float32, np.float64):
-> 1811   raise ValueError(f'Only f32/f64 are supported, got {t}')
   1813 return tridiagonal_solve_p.bind(dl, d, du, b, m=m, n=n, ldb=ldb, t=t)

ValueError: Only f32/f64 are supported, got complex128
```

**Comment by rajasekharporeddy** [comment]
Hi @tomsturges 

I tried an example code on `jax.lax.linalg.tridiagonal_solve` with `complex128` dtype arrays in Google Colab (jax version 0.4.23). It returns an array of `complex128` dtype. You can refer the [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/98733699f294dbc085f180893f2bdbdd/-15718.ipynb) here.

Please verify and let us know the response.

Thank you

**Comment by tomsturges** [comment]
Hi, thank you, I confirm that the code you pasted works.

I can't now remember which project I had this problem for, so I can't check if it works in that environemnt etc. Sorry about that. But anyway it all seems to be working now. Maybe I had an older version of JAX
