### ISSUE TITLE
Missing in reference docs: `jax.lax.with_sharding_constraint`

### ISSUE THREAD

**Issue by rhaps0dy** [google/jax#15729]
This page should have everything in `jax.lax`: https://jax.readthedocs.io/en/latest/jax.lax.html#

but it's missing `jax.lax.with_sharding_constraint`, which is part of the public API, because it's mentioned [here](https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html#constraining-shardings-of-intermediates-in-jitted-code)

**Comment by jakevdp** [comment]
Thanks for the report! Fixed in #15755
