### ISSUE TITLE
Simple data parallelism via jax.Array feels unergonomic to use

### ISSUE THREAD

**Issue by jjyyxx** [google/jax#15734]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html describes a new way to handle data and model parallellism, and looks very promising. But when I experiment with its API on a model with complex PyTree as input (of multiple kind of `ndim`), simply following the documentation leads to assertion error and internal check error. While, after some debugging, the error seems to be at the user side, and I fixed by "inventing" `compatible_sharding`
```python
sharding = jax.sharding.PositionalSharding(jax.devices())
train_state = jax.device_put(train_state, sharding.replicate())

compatible_sharding = jax.tree_util.tree_map(lambda x: sharding.reshape(-1, *[1] * (x.ndim-1)), batch)
batch = jax.device_put(batch, compatible_sharding)
```
This works, but I'm not sure if this is the best practice. Also this feels like an overkill for my simple data parallel use case. Sorry in advance if I was missing some thing or reinventing the wheel.

**Comment by jjyyxx** [comment]
@yashk2810 Thanks for your reply! I will definitely take a look at `NamedSharding`.

The error I got is definitely another aspect for possible improvement.  The same kind of error pattern (dimension mismatch, from my perspective), lead to multiple kind of error reports! See my test case below.

```python
"""
CUDA_VISIBLE_DEVICES=0,1 python test_shard.py
"""

import jax, jax.numpy as jnp

if __name__ == '__main__':
    sharding = jax.sharding.PositionalSharding(jax.devices())

    x_1d = jnp.zeros((8,))
    x_2d = jnp.zeros((2, 4))
    x_3d = jnp.zeros((2, 2, 2))

    # Success
    jax.device_put(x_1d, sharding)
    jax.device_put(x_2d, sharding.reshape(2, 1))
    jax.device_put(x_3d, sharding.reshape(2, 1, 1))

    # Success!?
    jax.device_put(x_1d, sharding.reshape(1, 1, 2))
    jax.device_put(x_2d, sharding.reshape(1, 2, 1))

    # Exception with `AssertionError: (1, ?)`
    jax.device_put(x_2d, sharding)
    jax.device_put(x_3d, sharding)

    # Exception with `INTERNAL: RET_CHECK failure` and long C stack trace
    jax.device_put(x_1d, sharding.reshape(2, 1))
    jax.device_put(x_3d, sharding.reshape(2, 1))
```

Also, the document feels not helpful enough. All examples uses a two-dimensional sharding, and all PyTree leaves have consistent shape, which hides potential misuses until a `INTERNAL: RET_CHECK failure` hits me and I almost abandoned the new way of parallelism before I discover my workaround 🤣.

**Comment by yashk2810** [comment]
> I almost abandoned the new way of parallelism before

Ohh noo :)

I would give NamedSharding a try before you do that and watch the magic unfold :)

Can you file different issues for PositionalSharding please?

**Comment by jjyyxx** [comment]
Actually, despite looking strange, my current workaround of `compatible_sharding` works well for me, and I will keep it for now. I looked at the document of NamedSharding, but it seems more complicated (or systematic) than PositionalSharding to me. Could you leave an example about this, sharding the first dimension of all leaves (potentially of varying `ndim`) of an arbitrary PyTree?

Also, I do not quite understand what does "file different issues for PositionalSharding" mean. I file this issue mainly to seek enhancement for PositionalSharding. If you ask me to file another issue, what you suggest the title to be? And is it considered enhancement or bug?

**Comment by yashk2810** [comment]
> sharding the first dimension of all leaves (potentially of varying ndim) of an arbitrary PyTree?

You can do:

```
mesh = jax.sharding.Mesh(jax.devices(), ('x',))
sharding = jax.sharding.NamedSharding(mesh, P('x'))
```

This will shard the first dim of your input `num_devices` way and mark all your other dimensions as replicated. Also it will work for varying number of dims.

For train_state you can do: `jax.sharding.NamedSharding(mesh, P())` which will mark it as replicated.
