### ISSUE TITLE
Jax jit-compile functions many times

### ISSUE THREAD

**Issue by Badr-MOUFAD** [google/jax#15761]
### Description

I assume running a function one single time is sufficient to jit-compile it. However, I came across a situation where the jit compilation might require an arbitrary number of function runs.

Here is a snippet that showcases this behavior where:
1. I create a function to be jit-compiled (the function is for the sake of illustration)
2. I run it and time its execution for several input sizes

<details>
<summary>(click to expend code snippet)</summary>

```python
import time
import jax
import jax.numpy as jnp


# A dummy function
@jax.jit
def some_func(vec, indices):
    out = jnp.zeros(len(indices))

    for idx, j in enumerate(indices):
        out_j = vec[j]
        out = out.at[idx].set(out_j)

    return out


timings = []
x = jnp.ones(20)

for n_indices in [5, 8, 10, 10, 10]:
    # make a list of indices
    li = jnp.arange(n_indices)

    # time the execution of function
    start = time.perf_counter()
    some_func(x, li)
    end = time.perf_counter()

    timings.append(end - start)
```
</details>

Plotting the timings gives the following figure.
One can observe that:
- The jit compilation process was executed 3 times
- The last two runs (with the same input size) didn't trigger any compilation

![timings](https://user-images.githubusercontent.com/65614794/234680075-9e786238-f9fb-4d99-91c9-67806faa4763.png)

I'm pretty confused about the origin of this behavior: I can't tell whether it is a bug or an inherent functioning of Jax.
My concern is that jit compilation comes with a time overhead which would be amplified if it requires many function runs.

### What jax/jaxlib version are you using?

v0.3.25, v0.3.22

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.7, OS Linux Ubuntu 64-bit

### NVIDIA GPU info

```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA T600 Lap...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   49C    P0     8W /  N/A |      9MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1767      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2721      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Thanks for the question! This is how JAX's JIT works: it requires array shapes to be static, and re-compiles if the shapes of input arrays change. With that in mind, the performance characteristics you're seeing are exactly what you should expect.

**Comment by Badr-MOUFAD** [comment]
Thanks @jakevdp for your response, I appreciate it.

Do you see any workaround? Perhaps something to alleviate this drawback?

**Comment by jakevdp** [comment]
Well, in most cases of interest the compilation time should be small compared to the runtime. Your example here is somewhat of a worst case, because it uses Python `for` loops (which are unrolled by the compiler) over very cheap operations, so the output is dominated by compile time. If this is really reflective of the kind of problem you're trying to solve, my recommendation would be to not use `jit`. If this is not reflective of the kind of problem you're trying to solve, then you're probably in the regime where you don't really have to worry about compilation time. What do you think?

Side-note, I'm not sure it's relevant to your true problem of interest, but for best results you should avoid `for` loops and use vectorized operations directly. For example, this is the vectorized equivalent of your original function, and should have at least 10x faster compilation & execution time.
```python
@jax.jit
def some_func(vec, indices):
    out = jnp.zeros(len(indices))
    return out.at[indices].set(vec[:len(indices)])
``

**Comment by Badr-MOUFAD** [comment]
Vectorization seems a fair workaround.
Thanks again @jakevdp :pray:
