### ISSUE TITLE
Cannot access `sharding` of tracers despite it being in `dir`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#15908]
### Description

```python
import jax
import jax.numpy as jnp

@jax.jit
@jax.vmap
def f(x):
    assert "sharding" in dir(x)
    x.sharding

f(jnp.arange(2))
# AttributeError: BatchTracer has no attribute sharding
```

### What jax/jaxlib version are you using?

JAX 0.4.8, jaxlib 0.4.7

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.8.16

**Comment by hawkinsp** [comment]
This is working as intended, in the sense that `Tracer` is a subclass of `Array` and `Array` has a `.sharding` attribute, but a `Tracer` does not in general have a concrete sharding.

(Just as many other "array" methods don't work on most tracers: e.g., `__bool__`.)

**Comment by shoyer** [comment]
Somewhat related: https://github.com/google/jax/issues/15208

**Comment by patrick-kidger** [comment]
Closing as apparently working as intended.

**Comment by lorenrose1013** [comment]
For future reference:

`jax.debug.inspect_array_sharding(x, callback=print)`
