### ISSUE TITLE
Re-enable GPU builds for windows after openxla migration and triton integration

### ISSUE THREAD

**Issue by cloudhan** [google/jax#15907]
### Description

Build on windows is not possible since 0.4 release along with the introduction of openxla and triton. This is a meta thread to track the work needs to enable the building again.

- [x] https://github.com/openxla/xla/pull/2264
- [x] https://github.com/openxla/xla/pull/2842
- [x] https://github.com/openxla/xla/pull/2843
- [x] https://github.com/openxla/xla/pull/2844
- [x] https://github.com/openxla/xla/pull/2853
- [ ] https://github.com/openxla/triton/pull/2  This fix compiling flags issue for MSVC.
- [x] https://github.com/openxla/xla/issues/2845
- [x] https://github.com/google/jax/issues/14466 This one needs careful consideration. I don't know how to solve the weak symbol of `xla::runtime::ffi::GetXlaFfiStream`
- [x] https://github.com/openxla/xla/issues/2855

This fixes #13646 #14165 #14369 #15876 #14950 #14939

### What jax/jaxlib version are you using?

jaxlib 0.4.9 rc

### Additional system info

Native Windows 11

### NVIDIA GPU info

not apply

**Comment by cloudhan** [comment]
@hawkinsp do you mind coordinating this?

**Comment by cloudhan** [comment]
cl.exe version 19.35.32217.1 ICE, 19.24 is not affected.
https://developercommunity.visualstudio.com/t/ICE-for-invoking-template-with-same-id-n/10362085

Introduced by legit change: https://github.com/openxla/xla/commit/0636d61d0169fef34105ecc1066f5fa26d337a70

**Comment by adam-hartshorne** [comment]
Looks like dlfcn-win32 dependency is fixed,

https://github.com/openai/triton/commit/323843cde89f3258229377f3f9048e4409ad4380

**Comment by cloudhan** [comment]
@hawkinsp @chsigg only one in openxla/trition is needed. All other issues is fixed at the moment.

bazel 5.1.1 is needed, otherwise, `nvcc fatal : Stray '"'` due to `-DBAZEL_CURRENT_REPOSITORY =\"xla\"`

**Comment by jlperla** [comment]
Hi all.  Excited to see the movement here.  Is there any chance for a cpu-only windows JAX installable through standard pip/conda for the fall?  I would love to teach with it for a course at that time (yes, I know that I can tell people to use the colab, WSL, and an unofficial conda build, but those aren't the same thing as windows support with a replicable pip requirements file/etc. I can give to low-tech users).

**Comment by hawkinsp** [comment]
With
* https://github.com/openxla/xla/pull/5501
* https://github.com/openxla/xla/pull/5499
and the patch in https://github.com/google/jax/issues/14369
I can build a jaxlib CUDA wheel on Windows. I didn't test it, but it builds.

**Comment by hawkinsp** [comment]
And with https://github.com/openxla/xla/commit/972cd211a24458be7a867678059a4a4652955f9f all the necessary changes have landed! jaxlib should build on Windows with CUDA enabled using XLA head.
