### ISSUE TITLE
Serializing function using Dill fails with a shape-checking error.

### ISSUE THREAD

**Issue by finbarrtimbers** [google/jax#1590]
Hey folks! I have an agent that uses JAX. I'm trying to serialize it, and doing the naive thing- dumping it to disk using dill- didn't work. It gave the following error:
`RuntimeError: Invalid argument: Convert does not allow non-arrays, so cannot convert from s32[] to TOKEN`. Partial stacktrace: 

```
E1029 10:16:10.101430 16812 app.py:658] Top-level exception: Invalid argument: Convert does not allow non$
arrays, so cannot convert from s32[] to TOKEN.:     @     0x56425db0f04a  xla::XlaBuilder::ReportErrorOrR$
turn()                                                                                                    
    @     0x56425db0e7c9  xla::XlaBuilder::ReportErrorOrReturn()                                          
    @     0x56425db14d15  xla::XlaBuilder::ConvertElementType()                                           
    @     0x56425db1bdc7  xla::ConvertElementType()                                                       
    @     0x7f588080e935  pybind11::detail::argument_loader<>::call_impl<>()                              
    @     0x7f588080e546  pybind11::detail::argument_loader<>::call<>()                                   
    @     0x7f588080e3ce  pybind11::cpp_function::initialize<>()::{lambda()#1}::operator()()              
    @     0x7f588080e325  pybind11::cpp_function::initialize<>()::{lambda()#1}::__invoke()                
    @     0x7f58807762b5  pybind11::cpp_function::dispatcher()                                            
    @     0x5642686c2ea7  PyCFunction_Call                                                                
    @     0x56426874d336  _PyEval_EvalFrameDefault                                                        
    @     0x564268750c3f  _PyEval_EvalCodeWithName                                                        
    @     0x564268751518  fast_function                                                                   
    @     0x564268750165  call_function                                                                   
    @     0x56426874d0d4  _PyEval_EvalFrameDefault                                                        
    @     0x564268750c3f  _PyEval_EvalCodeWithName                                                        
    @     0x564268747854  PyEval_EvalCodeEx                                                               
    @     0x5642686a8046  function_call                                                                   
    @     0x5642686721cb  PyObject_Call                                                                   
    @     0x56426874d259  _PyEval_EvalFrameDefault                                                        
    @     0x564268750c3f  _PyEval_EvalCodeWithName                                                        
    @     0x564268747854  PyEval_EvalCodeEx
    @     0x5642686a8046  function_call
    @     0x5642686721cb  PyObject_Call
    @     0x7f5881874139  cache_call
    @     0x5642686721cb  PyObject_Call
    @     0x56426874d259  _PyEval_EvalFrameDefault
    @     0x564268750c3f  _PyEval_EvalCodeWithName
    @     0x564268747854  PyEval_EvalCodeEx
    @     0x5642686a8046  function_call
    @     0x5642686721cb  PyObject_Call
    @     0x7f5881874139  cache_call
 
 
This is a bug in JAX's shape-checking rules; please report it!                                            
https://github.com/google/jax/issues     
```

I'm reporting it as the message explicitly says to report it.

Note: I work at DeepMind so I can share my code and a reproducible test-case if that's desirable (but that'd have to be done through corp channels).

**Comment by jekbradbury** [comment]
That error message can be a little misleading; it really means "JAX was able to run some Python code and specialize it into a jaxpr without encountering any errors, but then hit some kind of error condition while trying to convert that jaxpr into an XLA computation." That has in the past typically meant a bug in JAX's shape-checking rules, but here it's something weirder (I don't see why TOKEN would be showing up when no infeeds/outfeeds are present). @hawkinsp any ideas? Should dill work at all (I would be a little surprised)?

Separately we should figure out what to tell people who want to serialize JAX models (currently it's pretty much "serialize your network weights any way you want, then make sure you have a copy of the corresponding Python code, e.g. by storing a git hash or hermetic .par")

**Comment by levskaya** [comment]
My higher-order advice is to give up on dill.  The only pickling library that's going to have a chance in hell of working with jax is cloudpickle.  I know of a few people who have been successfully using it in the context of multiprocessing serialization.

**Comment by finbarrtimbers** [comment]
I ended up pickling the network params and the network apply function- works fine so far. 

I only reported this because the message explicitly said to, so if you folks want to close this, fine by me.

**Comment by hawkinsp** [comment]
If we can reproduce this bug then there is still something to fix here. What is not clear to me is how to do that...

If you can still reproduce this bug, could you please provide code that reproduces the failure?

Closing on the assumption that the issue is likely stale, but please reopen if you can still reproduce it!
