### ISSUE TITLE
Jit unnecessarily re-compiles with `jax.device_put(x, sharding)`

### ISSUE THREAD

**Issue by jjyyxx** [google/jax#15924]
### Description

I was loading some pretrained parameters in JAX and found my `train_step` got compiled more than once unexpectedly. I was able to reproduce with the following simple snippet

```python
from contextlib import contextmanager

import numpy as np
import jax, jax.numpy as jnp

@contextmanager
def print_barrier(name: str):
    import sys
    print(f"--- ENTER {name} ---", file=sys.stderr)
    yield
    print(f"--- EXIT  {name} ---", file=sys.stderr)

@jax.jit
def test(x):
    return x

if __name__ == '__main__':
    x_jax = jnp.zeros((1,))
    x_np = np.zeros((1,))
    x_np2jax = jax.device_put(x_np)
    x_np2jax_sharded = jax.device_put(x_np, x_jax.sharding)

    jax.config.update("jax_log_compiles", True)

    with print_barrier("jax.Array"):
        test(x_jax)

    with print_barrier("np.ndarray"):
        test(x_np)

    with print_barrier("np.ndarray -> jax.Array"):
        test(x_np2jax)

    with print_barrier("np.ndarray -> jax.Array (with sharding)"):
        test(x_np2jax_sharded)

    jax.config.update("jax_log_compiles", False)

    test_aot = test.lower(x_jax).compile()
    test_aot(x_jax)
    test_aot(x_np)
    test_aot(x_np2jax)
    test_aot(x_np2jax_sharded)
```
finishes without error and logs to stderr the following
```
--- ENTER jax.Array ---
Finished tracing + transforming test for pjit in 0.0008282661437988281 sec
Compiling test for with global shapes and types [ShapedArray(float32[1])]. Argument mapping: (GSPMDSharding({replicated}),).
--- EXIT  jax.Array ---
--- ENTER np.ndarray ---
--- EXIT  np.ndarray ---
--- ENTER np.ndarray -> jax.Array ---
--- EXIT  np.ndarray -> jax.Array ---
--- ENTER np.ndarray -> jax.Array (with sharding) ---
Compiling test for with global shapes and types [ShapedArray(float32[1])]. Argument mapping: (GSPMDSharding({replicated}),).
--- EXIT  np.ndarray -> jax.Array (with sharding) ---
```

The fourth call `test(x_np2jax_sharded)` triggers jit re-compilation, but I did not find it necessary. Two compilations have identical log and jaxpr. I did not find any difference between `x_np2jax` and `x_np2jax_sharded`. And the AOT version below could finish without error.

### What jax/jaxlib version are you using?

jax v0.4.8, jaxlib v0.4.7

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9

**Comment by yashk2810** [comment]
The recompilation is because `x_np2jax_sharded` is sharded which would lead to a different HLO than the non-sharded one.

You can check that by printing `test_aot.as_text()` for both sharded and unsharded and they will be different.

**Comment by jjyyxx** [comment]
@yashk2810 Thanks for your reply, but they are no different. There are several concerns.

1. You mentioned that `x_np2jax_sharded` is sharded, but I set its sharding to be identical to `x_jax`'s sharding, I guess if `x_jax` is non-sharded, so should `x_np2jax_sharded` be.
2. **The whole snippet above run without error**, so `test_aot` is compatible with all four inputs.
3. The HLOs are identical, verified by `assert test.lower(x_jax).compile().as_text() == test.lower(x_np2jax_sharded).compile().as_text()`

A bit of use case for more context: I would like to load some pretrained parameters in NumPy format to an already initialized and possibly sharded network parameter (by haiku), so I roughly do `params[key] = jax.device_put(new_param, params[key].sharding)`, but got jit recompiles. This is non-fatal, only slowing down a long running program for about 10 seconds, but it would be better to get things clear.

**Comment by yashk2810** [comment]
Ohh I missed that the sharding was the same. I'll take a look and report back

**Comment by yashk2810** [comment]
I don't see any recompilation:

```
In [4]: @jax.jit
   ...: def test(x):
   ...:     return x
   ...:

In [5]: x_jax = jnp.zeros((1,))
   ...: x_np = np.zeros((1,))
   ...: x_np2jax = jax.device_put(x_np)
   ...: x_np2jax_sharded = jax.device_put(x_np, x_jax.sharding)
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)

In [6]: jax.config.update("jax_log_compiles", True)

In [7]: test(x_np2jax)
Finished tracing + transforming test for pjit in 0.000431060791015625 sec
Out[7]: Array([0.], dtype=float32)

In [8]: test(x_np2jax_sharded)
Out[8]: Array([0.], dtype=float32)

In [9]: test(x_jax)
Out[9]: Array([0.], dtype=float32)
```

**Comment by yashk2810** [comment]
Maybe upgrade to jax and jaxlib 0.4.9 and see if it's fixed?

**Comment by jjyyxx** [comment]
Indeed, with v0.4.9 released 2 hours ago this problem went away! So this issue is considered fixed and I will close this issue. But I am a bit interested with Jax internals, so could you point to a specific commit that fixes this issue? @yashk2810

**Comment by yashk2810** [comment]
The fix was over a lot of commits. https://github.com/google/jax/commit/5d2f4530940f247fc7a4a6bc7e0f2b41fa39f7fb was the main one that fixed these kind of problems.
