### ISSUE TITLE
`jnp.where` condition does not accept multiple

### ISSUE THREAD

**Issue by yonghakim** [google/jax#15948]
### Description

Hi, 

`jnp.where` with `jit` doesn't accept multiple conditions. 
Can you please check?

```python
import jax
import jax.numpy as jnp
import numpy as np


def a(wavelength):

    np.where(500 < wavelength, 0, 2)
    print('OK')
    np.where(500 < wavelength <= 600, 0, 2)
    print('OK')


def aa(wavelength):

    jnp.where(500 < wavelength, 0, 2)
    print('OK')
    jnp.where(500 < wavelength <= 600, 0, 2)
    print('OK')


a(900)
aa(900)
jax.jit(aa)(900)
```

> OK
OK
OK
OK
OK
...
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/Users/yongha/project/rcwa/meent/research/closet/jax_where.py", line 25, in <module>
    jax.jit(aa)(900)
  File "/Users/yongha/project/rcwa/meent/research/closet/jax_where.py", line 19, in aa
    jnp.where(500 < wavelength <= 600, 0, 2)
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
The problem arose with the `bool` function. 
The error occurred while tracing the function aa at /Users/yongha/project/rcwa/meent/research/closet/jax_where.py:15 for jit. This concrete value was not available in Python because it depends on the value of the argument wavelength.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
Process finished with exit code 1
>

### What jax/jaxlib version are you using?

jax 0.4.8,  jaxlib 0.4.7

### Which accelerator(s) are you using?

CPU

### Additional system info

M1

**Comment by jakevdp** [comment]
Thanks for the question! This is working as expected. When combining multiple traced boolean conditions, you must use bitwise operators:
```python
jnp.where((500 < wavelength) &  (wavelength <= 600), 0, 2)
```
(note the parentheses: this is important due to operator precedence) This is similar to what is required for combining conditions over numpy arrays. It would be nice if numpy or JAX could support chained comparisons, but this is not possible due to their semantics and the fact that Python's `and` statement cannot be overloaded.

**Comment by yonghakim** [comment]
Ok. Thanks!
