### ISSUE TITLE
Jax requires driver version 520.61.5, although any >= 450.80.02 is specified for CUDA 11

### ISSUE THREAD

**Issue by Khimer** [google/jax#15961]
### Description

Hello! Thanks for your hard work!
Faced the following problem:
I installed jax like pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
my Driver Version is 470.182.03 (>= 450.80.02 for CUDA 11 on Linux).
But when I try:
 
import jax
num_devices = jax.device_count()

I get:
2023-05-11 05:14:42.079662: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:268] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2023-05-11 05:14:42.079796: E external/xla/xla/stream_executor/cuda/cuda_diagnostics.cc:312] kernel version 470.182.3 does not match DSO version 520.61.5 -- cannot find working devices in this configuration
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Unfortunately my graphics card does not support the latest drivers than 470

### What jax/jaxlib version are you using?

jax==0.4.9 jaxlib==0.4.9+cuda11.cudnn86

### Which accelerator(s) are you using?

Tesla K80

### Additional system info

docker image nvidia/cuda:11.8.0-cudnn8-devel-ubuntu18.04

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.182.03   Driver Version: 470.182.03   CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:06:00.0 Off |                    0 |
| N/A   23C    P8    27W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |

**Comment by hawkinsp** [comment]
JAX has dropped support for Kepler series GPUs, so we're not going to be able to take any actions here.
