### ISSUE TITLE
ROCM build is broken

### ISSUE THREAD

**Issue by dcunited001** [google/jax#15983]
I was able to run the Hessian code using [rocm/jax-build](https://hub.docker.com/r/rocm/jax-build/tags). I have not run the tests on that docker image. 

#### Fixing Dockerfile.ms is probably not worth it

I was in the middle of putting together a minimal pull request to fix this when I realized that most of the tests were broken and that basically, no one has tested the ROCm build in quite some time, which means that there's no planned support from Google -- or at least that AMD ROCm support is not considered "essential" in the same way that CUDA/TPU support would be. 

That's quite frustrating because screwing with ROCm while learning the python ecosystem is about all I've done for a month and I cannot afford a GPU. I haven't really written a line of python during that time.

If this issue seems a little scattered, it's because I pulled the content from my notes.

### Description

I built JAX

```sh
./build/rocm/ci_build.sh --keep_image --runtime bash -c "./build/rocm/build_rocm.sh"
```

And launched:

```sh
sudo docker run -it --device=/dev/kfd --device=/dev/dri --security-opt seccomp=unconfined --group-add video --entrypoint /bin/bash jax-rocm:latest
```

#### Initial Problems

Seeing this in =step 17/21=. This is similar to [RadeonOpenCompute/ROCm/issues#1714](https://github.com/RadeonOpenCompute/ROCm/issues/1713)

```
W: Conflicting distribution: https://repo.radeon.com/rocm/apt/5.4 ubuntu InRelease (expected ubuntu but got focal)
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

...

debconf: delaying package configuration, since apt-utils is not installed
```

And then in =Step 21/21= after git clone, the image learns that numpy 1.20 was installed. 

##### Fixed Dockerfile.ms by bumping numpy to 0.21.6

Change =Dockerfile.ms= to fix the pip version

- google/jax#13613: pullreq to change build_ci.sh to default to multistage
- both dockerfiles should have numpy bumped
- `build_ci.sh` comments should change to indicate Dockerfile.ms is default

##### Bazel Build Warnings

I changed numpy to 0.21.6 and the build script succeed.

```
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/boringssl/archive/c00d7ca810e93780bd0c8ee4eea28f4f2ea4bcdc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
```

##### Running Tests

Start the container with `${PWD}/jax` bound to the `/workspace` volume.

```sh
sudo docker run -it --device=/dev/kfd --device=/dev/dri \
     --security-opt seccomp=unconfined --group-add video \
     --volume=${PWD}/jax:/workspace \
     -e 'HSA_OVERRIDE_GFX_VERSION=10.3.0' \
     --entrypoint "/bin/bash" jax-rocm:latest
```

I ran the tests after removing the `-x` argument in `python ./build/rocm/run_single_gpu.py`

32 Tests Failed

```
----------------------------- Captured stderr call -----------------------------
2023-05-12 05:43:25.807625: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.gemm' failed: Not implemented on ROCm.

...

----------------------------- Captured stderr call -----------------------------
2023-05-12 05:43:26.279208: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.gemm' failed: Not implemented on ROCm.
=========================== short test summary info ============================
FAILED tests/ann_test.py::AnnTest::test_approx_max_k0 - jaxlib.xla_extension....

...

FAILED tests/ann_test.py::AnnTest::test_approx_min_k0 - jaxlib.xla_extension....

...

FAILED tests/ann_test.py::AnnTest::test_approx_min_k9 - jaxlib.xla_extension....
FAILED tests/ann_test.py::AnnTest::test_pmap0 - jaxlib.xla_extension.XlaRunti...

... 

FAILED tests/ann_test.py::AnnTest::test_pmap9 - jaxlib.xla_extension.XlaRunti...
FAILED tests/ann_test.py::AnnTest::test_vmap_after - jaxlib.xla_extension.Xla...
FAILED tests/ann_test.py::AnnTest::test_vmap_before - jaxlib.xla_extension.Xl...
=================== 32 failed, 10 passed, 96 rerun in 34.09s ===================
```

No pmap?  .... [isn't that just clojure's r/fold?](https://github.com/dcunited001/bioclj/blob/master/src/bioclj/core.clj#L170-L181)

python is the wrong language... and lifting to the network for distributed programming is why haskell was written (or so I've always imagined)

##### I Couldn't Run The Hessian Example

The main issue for me was that I was unable to pushfwd/pullback in order to do hessians.

Error: [Hessian not implemented on ROCm](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#jacobians-and-hessians-using-jacfwd-and-jacrev)

```python
>>> J = jacfwd(f)(W)
>>> J = jacrev(f)(W)

2023-05-12 05:47:40.848932: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2469] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.gemm' failed: Not implemented on ROCm.
#12840 
```

### What jax/jaxlib version are you using?

0.4.11

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux e5fc65f21cda 6.3.1-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Mon, 01 May 2023 17:42:12 +0000 x86_64 x86_64 x86_64 GNU/Linux

### NVIDIA GPU info

rocm-smi

```
======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr  SCLK    MCLK     Fan     Perf  PwrCap  VRAM%  GPU%
0    55.0c           26.0W   500Mhz  1000Mhz  32.55%  auto  211.0W   16%   0%
================================================================================
============================= End of ROCm SMI Log ==============================
```

rocminfo

```
ROCk module is loaded
=====================
HSA System Attributes
=====================
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE
System Endianness:       LITTLE

==========
HSA Agents
==========
*******
Agent 1
*******
Name:                    AMD Ryzen 9 5950X 16-Core Processor
Uuid:                    CPU-XX
Marketing Name:          AMD Ryzen 9 5950X 16-Core Processor
Vendor Name:             CPU
Feature:                 None specified
Profile:                 FULL_PROFILE
Float Round Mode:        NEAR
Max Queue Number:        0(0x0)
Queue Min Size:          0(0x0)
Queue Max Size:          0(0x0)
Queue Type:              MULTI
Node:                    0
Device Type:             CPU
Cache Info:
L1:                      32768(0x8000) KB
Chip ID:                 0(0x0)
ASIC Revision:           0(0x0)
Cacheline Size:          64(0x40)
Max Clock Freq. (MHz):   3400
BDFID:                   0
Internal Node ID:        0
Compute Unit:            32
SIMDs per CU:            0
Shader Engines:          0
Shader Arrs. per Eng.:   0
WatchPts on Addr. Ranges:1
Features:                None
Pool Info:
Pool 1
Segment:                 GLOBAL; FLAGS: FINE GRAINED
Size:                    32771392(0x1f40d40) KB
Allocatable:             TRUE
Alloc Granule:           4KB
Alloc Alignment:         4KB
Accessible by all:       TRUE
Pool 2
Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
Size:                    32771392(0x1f40d40) KB
Allocatable:             TRUE
Alloc Granule:           4KB
Alloc Alignment:         4KB
Accessible by all:       TRUE
Pool 3
Segment:                 GLOBAL; FLAGS: COARSE GRAINED
Size:                    32771392(0x1f40d40) KB
Allocatable:             TRUE
Alloc Granule:           4KB
Alloc Alignment:         4KB
Accessible by all:       TRUE
ISA Info:
*******
Agent 2
*******
Name:                    gfx1030
Uuid:                    GPU-XX
Marketing Name:          AMD Radeon RX 6700 XT
Vendor Name:             AMD
Feature:                 KERNEL_DISPATCH
Profile:                 BASE_PROFILE
Float Round Mode:        NEAR
Max Queue Number:        128(0x80)
Queue Min Size:          64(0x40)
Queue Max Size:          131072(0x20000)
Queue Type:              MULTI
Node:                    1
Device Type:             GPU
Cache Info:
L1:                      16(0x10) KB
L2:                      3072(0xc00) KB
L3:                      98304(0x18000) KB
Chip ID:                 29663(0x73df)
ASIC Revision:           0(0x0)
Cacheline Size:          64(0x40)
Max Clock Freq. (MHz):   2855
BDFID:                   2816
Internal Node ID:        1
Compute Unit:            40
SIMDs per CU:            2
Shader Engines:          4
Shader Arrs. per Eng.:   2
WatchPts on Addr. Ranges:4
Features:                KERNEL_DISPATCH
Fast F16 Operation:      TRUE
Wavefront Size:          32(0x20)
Workgroup Max Size:      1024(0x400)
Workgroup Max Size per Dimension:
x                        1024(0x400)
y                        1024(0x400)
z                        1024(0x400)
Max Waves Per CU:        32(0x20)
Max Work-item Per CU:    1024(0x400)
Grid Max Size:           4294967295(0xffffffff)
Grid Max Size per Dimension:
x                        4294967295(0xffffffff)
y                        4294967295(0xffffffff)
z                        4294967295(0xffffffff)
Max fbarriers/Workgrp:   32
Pool Info:
Pool 1
Segment:                 GLOBAL; FLAGS: COARSE GRAINED
Size:                    12566528(0xbfc000) KB
Allocatable:             TRUE
Alloc Granule:           4KB
Alloc Alignment:         4KB
Accessible by all:       FALSE
Pool 2
Segment:                 GROUP
Size:                    64(0x40) KB
Allocatable:             FALSE
Alloc Granule:           0KB
Alloc Alignment:         0KB
Accessible by all:       FALSE
ISA Info:
ISA 1
Name:                    amdgcn-amd-amdhsa--gfx1030
Machine Models:          HSA_MACHINE_MODEL_LARGE
Profiles:                HSA_PROFILE_BASE
Default Rounding Mode:   NEAR
Default Rounding Mode:   NEAR
Fast f16:                TRUE
Workgroup Max Size:      1024(0x400)
Workgroup Max Size per Dimension:
x                        1024(0x400)
y                        1024(0x400)
z                        1024(0x400)
Grid Max Size:           4294967295(0xffffffff)
Grid Max Size per Dimension:
x                        4294967295(0xffffffff)
y                        4294967295(0xffffffff)
z                        4294967295(0xffffffff)
FBarrier Max Size:       32
*** Done ***
```

**Comment by dcunited001** [comment]
Are JAX tracers limited to optimizing python calls to XLA? Or does the trace analysis select from binding to different possible XLA functionality based on the JIT optimization process? If it does, then my comment about pmap is totally wrong.

I see that XLA optimizes or interacts with [PTX bytecode](https://github.com/search?q=repo%3Atensorflow%2Ftensorflow%20ptx&type=code). And I've found the super helpful `autodidax.md`. 

Anyways, I'm just glad I can run the code on my GPU.

**Comment by hawkinsp** [comment]
@reza-amd @rsanthanam-amd can you perhaps take a look?

Note that we (Google) don't ship a ROCM build of JAX: one main reason for this is we have no way to test it. Without CI testing it is expected that it will break frequently. The ROCM build is community supported: we welcome PRs to fix it, but it's something the community maintains.

**Comment by jayfurmanek** [comment]
This is a bit of a scatter-shot issue description but if you are having trouble building, there are some pre-built options:

Dockerhub: 
   - https://hub.docker.com/r/rocm/jax-build
whl files: 
   - https://pypi.org/project/jaxlib-rocm/
   - https://github.com/ROCmSoftwarePlatform/jax/releases/download/jaxlib-v0.4.6-rocm55/jaxlib-0.4.6.550-cp39-cp39-manylinux2014_x86_64.whl

Also note the consumer boards are not strictly supported by ROCM at this point, but generally should work.

@rahulbatra85

**Comment by dcunited001** [comment]
So I've got the docker image running with jaxlib-rocm, tensorflow-rocm and jupyter.  I'm starting with `JAX_PLATFORMS=cpu,rocm jupyter-lab`, but when I run this:

```python
# this returns CPU/GPU devices
import tensorflow as tf
tf.config.list_physical_devices()

# this either gives a "No GPU/TPU" warning or throws the error below
import jax.numpy as jnp
from jax import config as jcfg
from jax import grad, jit, vmap
from jax import random

key = random.PRNGKey(0)
#jcfg.jax_platforms
```

Then I'm getting the error below

I think I need to check out the [ROCmSoftwarePlatform/jax@0.4.6](https://github.com/ROCmSoftwarePlatform/jax/tree/jaxlib-v0.4.6-rocm55) tag to figure out how to get past this error.

```
File ~/.local/lib/python3.9/site-packages/jax/_src/lib/xla_bridge.py:350, in backends()
    348 if config.jax_platforms:
    349   err_msg += " (set JAX_PLATFORMS='' to automatically choose an available backend)"
--> 350   raise RuntimeError(err_msg)
    351 else:
    352   _backends_errors[platform] = str(err)

RuntimeError: Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig' (set JAX_PLATFORMS='' to automatically choose an available backend)
```

I'm trying to resolve by tracing through these references/modules in the jax codebase. I could definitely use help, but I should be able to figure this stuff out. 

```python
from jax._src.lib import xla_client
from jax._src.lib import xla_bridge
from jax._src.config import flags

#FLAGS = flags.FLAGS
#FLAGS.jax_platflorm_name

xla_bridge.is_known_platform('rocm') # True
xla_client.CompileOptions()

xla_bridge.backends()
```

**Comment by rahulbatra85** [comment]
**Try this wheel**
https://github.com/ROCmSoftwarePlatform/jax/releases/download/jaxlib-v0.4.6-rocm55/jaxlib-0.4.6.550-cp39-cp39-manylinux2014_x86_64.whl

P.S.- Building jaxlib for ROCm is a bit tricky. You also need to pull in XLA changes to build and there is ROCm fork for that as well.

**Comment by dcunited001** [comment]
thanks @rahulbatra85 

one of the biggest problems i've had in figuring out how to use the ROCm stuff is trying to learn how the builds/dependencies differ between the upstream tensorflow/etc repositories and the ROCmSoftwarePlatform repositories.

i think diffing across the repositories checked out to specific repo's helps alot. the process i'm using is in [org-babel scripts here](https://github.com/dcunited001/nb-jax/#repo). using repo is a little heavy handed, but it just makes managing the repository clones easier.

the resulting diff here [jaxrocm046.diff](https://github.com/dcunited001/nb-jax/blob/master/rocm046.diff)
