### ISSUE TITLE
Add way to run jax program on CPU

### ISSUE THREAD

**Issue by jviereck** [google/jax#1598]
In my case, I have a small numpy array and a relative simple computation. 

Is there a way to place the computation on the CPU to benchmark what's the overhead of transfering the computation to the GPU is?

Related to #957.

**Comment by mattjj** [comment]
Indeed, @levskaya added this functionality in #1211! In fact, #957 is fixed too, we just haven't documented it...

The APIs are a bit in flux, though, as we're trying to simplify a couple things.

For placing on CPU:

```python
def f(x): return x**2

f_cpu = jit(f, backend='cpu')
f_gpu = jit(f, backend='gpu')
```

cc @skye who helped with this example code

I'm going to leave this issue open as a documentation request.

**Comment by mattjj** [comment]
@skye pointed out that there is a mention in the [`jit` docstring](https://jax.readthedocs.io/en/latest/jax.html#jax.jit)

> device – This is an experimental feature and the API is likely to change. Optional, the Device the jitted function will run on. (Available devices can be retrieved via jax.devices().) The default is inherited from XLA’s DeviceAssignment logic and is usually to use jax.devices()[0].

So let's actually close this issue, but leave up #957 as a request to finalize the API and document device placement of computations in a "Note" at jax.readthedocs.io. (I think one of the changes might be to unify "device" and "backend" arguments.)

By the way, if you want to measure just the transfer time, you can also use `jax.device_put` which itself also takes `device` and `backend` arguments.

**Comment by mattjj** [comment]
Please reopen if the above answers aren't satisfactory!

**Comment by jviereck** [comment]
Thanks for the quick replies!

**Comment by jwnys** [comment]
If I understand correctly, there is no way to specify that _all_ computations should be on CPU, right? It seems we need to adjust all the code to put all jits on CPU backend. It would be useful to have something similar to "config.update("jax_disable_jit", True)" to test your code when it won't run properly on GPU. Is such a config update available?

**Comment by tomhennigan** [comment]
You can set the default platform globally with:

```python
import jax
jax.config.update('jax_platform_name', platform)
```

**Comment by NightMachinary** [comment]
How do I tell jnp.array to put the data on the CPU from the start? I can’t afford the perf hit of it going to the TPU and then getting it back. (The whole point of using the CPU is to avoid such a trip for small networks.)

**Comment by jakevdp** [comment]
You can use the `device` argument of `jax.device_put` to specify which device the data should be put on. For example, on a TPU runtime:
```python
import jax
import numpy as np

x = jax.device_put(np.arange(5), device=jax.devices("tpu_driver")[0])
print(x.device_buffer.device())
# TPU_0(host=0,(0,0,0,0))

y = jax.device_put(np.arange(5), device=jax.devices("cpu")[0])
print(y.device_buffer.device())
# TFRT_CPU_0
```
