### ISSUE TITLE
Increase minimum CUDNN version to 8.9.1, and track CUDNN more closely in the future.

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#16059]
For a long time, JAX has built wheels that depend on a conservatively old version of CUDNN to make it easy for users to install JAX. This allowed users to install either that version or a newer version.

However, this approach prevents JAX from making use of new CUDNN features, and newer CUDNN releases contain features that we want to deploy to users. Notably, CUDNN 8.9.1 adds improved support for fused flash attention that we want to get into the hands of our users.

Now that we have the `cuda11_pip` and `cuda12_pip` wheel installations of JAX, updating `cudnn` is as simple as a `pip install --upgrade` command. So there is no reason we cannot ship JAX wheels built against more recent CUDNN releases: it is easy for users to upgrade.

I propose that:
* we update the CUDNN version used in JAX wheel builds to the latest (8.9.1), at least for the CUDA 12 version of JAX, and
* future JAX releases should be built against a recent CUDNN releases..

As always, users are free to build against a different CUDNN version if they want, but hopefully that will not be needed most of the time.

**Comment by hawkinsp** [comment]
@yashk2810 can you update our CUDA 12 CI/release image to the newer CUDNN?

**Comment by yashk2810** [comment]
I can update Cuda 12. Cuda 11.8 we share with TF for speed so i can't diverge from them.

**Comment by hawkinsp** [comment]
We're tracking a current CuDNN for our CUDA 12 release these days.
