### ISSUE TITLE
zeros_like does not preserve sharding information

### ISSUE THREAD

**Issue by dlwh** [google/jax#16080]
### Description

It looks like zeros_like doesn't preserve sharding information (@sholtodouglas found something different a while back here: https://github.com/google/jax/discussions/12799#discussioncomment-3887579). I feel like it probably should, as Sholto indicated in his post as well.

```python
import jax
import jax.numpy as jnp
from jax.experimental.pjit import pjit
from jax.sharding import PositionalSharding


@pjit
def init_zeros_like(arr):
    zz = jnp.zeros_like(arr)
    return zz

pos_sharding = PositionalSharding(jax.devices()).reshape((-1, 1))

arr0 = jnp.ones((16, 2))
arr0 = jax.device_put(arr0, pos_sharding)

print("initial array, sharded")
jax.debug.visualize_array_sharding(arr0)

arr1 = init_zeros_like(arr0)

print("result array, should be sharded but isn't")
jax.debug.visualize_array_sharding(arr1)
assert arr0.sharding.is_equivalent_to(arr1.sharding, 2), (arr0.sharding, arr1.sharding)  # fails
```

<details><summary>Output showing failure</summary>
<pre>
/opt/homebrew/Caskroom/miniforge/base/envs/levanter/bin/python /Users/dlwh/src/levanter/zeros_like_issue.py 
initial array, sharded
┌───────┐
│ CPU 0 │
├───────┤
│ CPU 1 │
├───────┤
│ CPU 2 │
├───────┤
│ CPU 3 │
├───────┤
│ CPU 4 │
├───────┤
│ CPU 5 │
├───────┤
│ CPU 6 │
├───────┤
│ CPU 7 │
└───────┘
result array, should be sharded but isn't
┌───────┐
│       │
│       │
│       │
│       │
│ CPU 0 │
│       │
│       │
│       │
│       │
└───────┘
Traceback (most recent call last):
  File "/Users/dlwh/src/levanter/zeros_like_issue.py", line 24, in <module>
    assert arr0.sharding.is_equivalent_to(arr1.sharding, 2), (arr0.sharding, arr1.sharding)
AssertionError: (PositionalSharding([[{CPU 0}]
                    [{CPU 1}]
                    [{CPU 2}]
                    [{CPU 3}]
                    [{CPU 4}]
                    [{CPU 5}]
                    [{CPU 6}]
                    [{CPU 7}]]), SingleDeviceSharding(device=CpuDevice(id=0)))

Process finished with exit code 1
</pre>
</details>

### What jax/jaxlib version are you using?

jax 0.4.10 jaxlib 0.4.10

### Which accelerator(s) are you using?

CPU (haven't checked TPU/GPU yet)

### Additional system info

Python 3.10.8, MacOS

**Comment by jakevdp** [comment]
Hi - thanks for the report! This issue is tracked in #15600, so I think we can close this as a duplicate.

**Comment by dlwh** [comment]
sorry, did a search but obviously not a good enough one
