### ISSUE TITLE
consider duck typing for jnp.ones_like, other similar functions

### ISSUE THREAD

**Issue by GallagherCommaJack** [google/jax#16122]
right now, `jnp.ones_like(jax.ShapeDtypeStruct(shape=(1, 2, 3), dtype=jnp.float32)` throws a type error
it probably shouldn't, and in fact `jnp.ones_like` should probably work on anything that has `shape`, `dtype`, etc attributes

**Comment by GallagherCommaJack** [comment]
`jnp.ones_like` et al would ideally get shape, dtype, etc from `x` whatever `x` is and only check that the shape, dtype, etc are themselves well typed

**Comment by mattjj** [comment]
Seems reasonable! (In fact I vaguely recall this coming up before...)

What do you think, @jakevdp ?

**Comment by jakevdp** [comment]
Sure, sounds reasonable to me. We have to be somewhat careful because some valid inputs won't have a `dtype` or `shape` defined (e.g. Python scalars) and some non-array inputs we want to be errors (e.g. lists and tuples).

**Comment by mattjj** [comment]
Maybe we can try to look for `shape` and `dtype` attributes first, and if that fails fall back to the current path.

**Comment by davisyoshida** [comment]
I just ran into a case where this would be nice as well. Would it be possible for me to make a PR for this or are there non-obvious things that could get broken?

**Comment by mattjj** [comment]
@davisyoshida thanks for the ping and the offer! Looks like @jakevdp got it in #16265 though.

**Comment by davisyoshida** [comment]
Someday I hope to fix an issue or even just answer a stackoverflow question before he gets to it!
