### ISSUE TITLE
Is pjit version functionally identical to pmap?

### ISSUE THREAD

**Issue by Young768** [google/jax#16184]
### Description

I was running PAXML experiment with pmap and pjit versions on the node with 2* A100 40G. Add two classes to nvidia.py file: https://github.com/google/paxml/blob/main/paxml/tasks/lm/params/nvidia.py#L36
jax.pmap version:
```
@experiment_registry.register
class NVIDIA1_3BPmap(NVIDIA1_3B):
  DCN_MESH_SHAPE = None
  ICI_MESH_SHAPE = None
```
jax.pjit version:
```
@experiment_registry.register
class NVIDIA1_3BPjit(NVIDIA1_3B):
  DCN_MESH_SHAPE = [1, 1, 1]
  # [replica, data, model]
  ICI_MESH_SHAPE = [2, 1, 1]
```
I was assuming that pjit version was functionally identical to pmap . However, I hit the OOM issue when running the pjit version.
Any idea why this happened?

Attaching the pjit and pmap logs.
[pjit.log](https://github.com/google/jax/files/11602737/pjit.log)

[pmap.log](https://github.com/google/jax/files/11602738/pmap.log)

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 12.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|

|   0  NVIDIA A100-PCI...  On   | 00000000:81:00.0 Off |                    0 |
| N/A   39C    P0    34W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-PCI...  On   | 00000000:C1:00.0 Off |                    0 |
| N/A   38C    P0    32W / 250W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

**Comment by Young768** [comment]
@nouiz could you or someone else take a look at this?

**Comment by yashk2810** [comment]
This issue belongs in the paxml repo BTW.

My guess is that your ici_mesh_shape is not sharding the arrays so as to not OOM. Maybe try a different combination like (2, 4, 1) or something like this?

How they should be sharded is something that the pax folks can help you with if you file this issue there 😃

**Comment by nouiz** [comment]
At the jax level, pmap and pjit aren't identical and can give different result.
Looking at the PAX DCN_MESH_SHAPE and ICI_MESH_SHAPE value as suggested above sound right.
