### ISSUE TITLE
Sharding "devices" arg unexpected behavior

### ISSUE THREAD

**Issue by wbrenton** [google/jax#16193]
### Description

The following is a minimal reproducible example of the problem. I'm reproducing the podracer sebulba architecture and I'm meeting to create a sharding for the actor using one core and a sharding for the learner using the other three cores on a TPU V4. 

This works fine.
```
import jax
import numpy as np
from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding

x = jax.random.normal(jax.random.PRNGKey(0), (8192, 8192))
jax.debug.visualize_array_sharding(x)

locals_devices = jax.devices()
actor_devices = locals_devices[0] # using the first core
learner_devices = locals_devices[0:3]
mesh = np.asarray(actor_devices).reshape((1,))
actor_mesh = mesh_utils.create_device_mesh(mesh_shape=(1,1), devices=[actor_devices])
actor_sharding = PositionalSharding(actor_mesh)
x = jax.device_put(x, actor_sharding)

x = jax.random.normal(jax.random.PRNGKey(0), (8192, 8192))
jax.debug.visualize_array_sharding(x)
```

This throws the error below.
```
actor_devices = locals_devices[-1] # using the last core
learner_devices = locals_devices[0:3]
mesh = np.asarray(actor_devices).reshape((1,))
actor_mesh = mesh_utils.create_device_mesh(mesh_shape=(1,1), devices=[actor_devices])
actor_sharding = PositionalSharding(actor_mesh)
x = jax.device_put(x, actor_sharding)

x = jax.random.normal(jax.random.PRNGKey(0), (8192, 8192))
jax.debug.visualize_array_sharding(x)
```
Exception has occurred: ValueError
axes don't match array
  File "/home/will/cleanba/sharding_demo.py", line 13, in <module>
    actor_mesh = mesh_utils.create_device_mesh(mesh_shape=(1,1), devices=[actor_devices])
ValueError: axes don't match array

### What jax/jaxlib version are you using?

0.4.10

### Which accelerator(s) are you using?

TPU v4

### Additional system info

Linux

**Comment by yashk2810** [comment]
It seems to work for me but I tried on TPU v3. Can you try on TPU v3 and see if you can repro?

Also maybe do a clean install of jax and jaxlib and see if you can repro it?

**Comment by yashk2810** [comment]
Closing due to lack of response. Feel free to reopen if this problem persists but I couldn't repro it.
