### ISSUE TITLE
`tests/pjit_test.py::PJitTest::testOutfeed` hangs with numpy 1.25.0

### ISSUE THREAD

**Issue by jakevdp** [google/jax#16233]
Reproduce with
```
$ pip install -U --pre numpy
$ python -m pytest -v tests/pjit_test.py::PJitTest::testOutfeed  # hangs
```
This is the source of the timeouts in  #14516

**Comment by pschuh** [comment]
I can't reproduce this on numpy2.5 and python10 built from head.

**Comment by jakevdp** [comment]
Thanks, I can no longer reproduce either. I suspect something was fixed upstream. Thanks!
