### ISSUE TITLE
logaddexp and logsumexp do not handle -inf correctly, don't match numpy/scipy

### ISSUE THREAD

**Issue by tombagby** [google/jax#1624]
logaddexp(-inf, -inf) should be -inf, is nan in jax implementations.

numpy.logaddexp(np.NINF, np.NINF) => -inf
jax.numpy.logaddexp(np.NINF, np.NINF) => nan

Same issue for special.logsumexp

**Comment by jekbradbury** [comment]
I'm seeing -inf for logaddexp but NaN for logsumexp. Can you share the exact code that gives you NaN with jax.numpy.logaddexp?

**Comment by tombagby** [comment]
The jax.numpy.logaddexp behavior is really weird, I only see it when running on an array with more than one item:

import jax.numpy as np
np.logaddexp(np.NINF, np.NINF) -> -inf
np.logaddexp(np.array([np.NINF]), np.array([np.NINF])) -> [-inf]
np.logaddexp(np.array([np.NINF, -1.0]), np.array([np.NINF, -1.0])) -> [nan, -0.30685282]

**Comment by hawkinsp** [comment]
I think the last behavior is because of XLA mishandling `exp` for NaN inputs on CPU:

```
In [7]: lax.exp(np.nan)
Out[7]: DeviceArray(0., dtype=float32)

In [8]: lax.exp(np.array([np.nan, 0.]))
Out[8]: DeviceArray([inf,  1.], dtype=float32)
```

I filed a bug with the XLA folks.

**Comment by tombagby** [comment]
Er, why is lax.exp(np.nan) = 0 in the first case? Shouldn't it just be nan? 

In both the numpy/scipy functions, there is a special case to handle logsum of two -infs that the jax implementations don't do:

logsumexp: 
https://github.com/scipy/scipy/blob/0781734e45886567f84d9fc0caa56476a32d82bb/scip
y/special/_logsumexp.py#L104

logaddexp: https://github.com/numpy/numpy/blob/31ffdecf07d18ed4dbb66b171cb0f998d4b190fa/numpy/core/src/npymath/npy_math_internal.h.src#L587

The logaddexp numpy thing would give weird results for autodiff.

**Comment by hawkinsp** [comment]
It should be `nan` in both cases. Both are bugs, but exhibiting slightly differently in the scalar and vector cases.
