### ISSUE TITLE
shard_map replication rule for `shard_map conv_general_dilated` not implemented

### ISSUE THREAD

**Issue by keunhong** [google/jax#16249]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

Trying to use a model that uses `conv_general_dilated` raises the following exception:

```
UnfilteredStackTrace: NotImplementedError: No replication rule for conv_general_dilated. As a workaround, pass the `check_rep=False` argument to `shard_map`. To get this fixed, open an issue at https://github.com/google/jax/issues
```

**Comment by mattjj** [comment]
We fixed this in #18740!
