### ISSUE TITLE
eliminate use of `jnp.ravel` in `jnp.histogram`

### ISSUE THREAD

**Issue by GallagherCommaJack** [google/jax#16258]
In general, `jnp.ravel` tends to behave extremely badly in a distributed context, and should probably be avoided wherever possible - it will at least create large amounts of ICI traffic, and at worst produce giant replicated tensors on every chip.

I've got a draft implementation that isn't quite equivalent enough for a PR.

```py
def bincount(
    x,
    *,
    length: int,
    weights=None,
) -> Array:
    if not jnp.issubdtype(x.dtype, jnp.integer):
        raise TypeError(
            f"x argument to bincount must have an integer type; got {x.dtype}"
        )
    if weights is None:
        weights = np.array(1, dtype=jnp.int_)
    return jnp.zeros(length, weights.dtype).at[jnp.clip(x, 0)].add(weights)


def efficient_hist(
    x: jax.Array,
    bins: int = 100,
    density: bool = False,
):
    min = jnp.min(x)
    max = jnp.max(x)
    bin_edges = jnp.linspace(min, max, bins + 1)
    bin_idx = jnp.searchsorted(bin_edges, x, side="right")
    bin_idx = jnp.clip(bin_idx, 0, len(bin_edges) - 1)
    counts = bincount(bin_idx, length=len(bin_edges))[1:]
    if density:
        bin_widths = jnp.diff(bin_edges)
        counts = counts / bin_widths / jnp.sum(counts)
    return counts, bin_edges
```

I needed the new `bincount` function because the current implementation has an assertion that `x` is one dimensional which is entirely unnecessary.

I've tested and this implementation works without issue in a distributed setting where the intermediate tensors are too large to construct on any single chip.

**Comment by jakevdp** [comment]
Thanks - the reason that `jax.numpy.bincount` raises an error for two-dimensional inputs is that `numpy.bincount` also raises an error in such cases, and the semantics of `jax.numpy` functions by design match the semantics of `numpy` functions.

That said, if this more efficient histogram implementation passes existing tests, we'd be happy to change the implementation. Are you interested in putting together a pull request?

**Comment by Gattocrucco** [comment]
Since `efficient_hist` accepts only evenly spaced bins, you can replace `searchsorted` with `bin_idx = (x - min) // ((max - min) / bins)`
