### ISSUE TITLE
Wheels for CUDA 12 CUDNN 8.9 are incorrectly named as CUDNN 8.8 wheels

### ISSUE THREAD

**Issue by alexk101** [google/jax#16275]
### Description

In the local install instructions for jaxlib, it's said that cuda 12 and cudnn 8.9 is supported. However, looking at the wheels that are actually provided, none of them included support for cudnn 8.9, with the most recent being cudnn 8.8. It looks like in 69cf67f252c72f34e8dde0a457ce9811ab9b6fc4 that these instructions were updated prematurely. Currently stuck with a broken install because of the mismatch between 8.8 and 8.9. Would prefer not to downgrade CUDNN, but just wanted to see if this could be fixed. And yes, I am using locally installed CUDA and CUDNN.

### What jax/jaxlib version are you using?

jax v0.4.11 jaxlib v0.4.11

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux Arch

### NVIDIA GPU info

```Tue Jun  6 11:59:38 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3070 T...    Off| 00000000:01:00.0  On |                  N/A |
| N/A   47C    P8               17W /  N/A|    980MiB /  8192MiB |     10%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+```

**Comment by hawkinsp** [comment]
Wheels built for CUDNN 8.8 will work on CUDNN 8.9. Can you say more about what goes wrong?

**Comment by alexk101** [comment]
```2023-06-06 12:50:46.986761: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:427] Loaded runtime CuDNN library: 8.8.0 but source was compiled with: 8.9.1.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.```

Looking at this again I think this might be a problem with my cudnn install. I think I need to reinstall since this looks to be using 8.8, and the commit I previously linked pushed the minimum version to 8.9. Though I still think that the naming of the wheels needs to be updated. They are built with 8.9 but are labeled as `cuda12.cudnn88-cp310-cp310-manylinux2014_x86_64.whl`. I think that was my main source of confusion. They are built for the new cudnn, just not labeled as such.

**Comment by hawkinsp** [comment]
@yashk2810 sounds like we need to update the wheel file name?

**Comment by yashk2810** [comment]
Yeah
