### ISSUE TITLE
Freeing memory for unreferenced jitted functions?

### ISSUE THREAD

**Issue by lewkowycz** [google/jax#1630]
Hi, I often run into memory issues with jax when training different models within the same script. In particular, after there is no reference to a jitted function, I would like to remove that function from memory, is there any way I can do this?
A simple example of what I am referring to is:
~~~~
import jax.numpy as np
import numpy as onp
from jax import random, grad, jit
import jax
from jax.experimental import stax

def linearize(f, params):
  def f_lin(p, x):
    dparams = jax.tree_util.tree_multimap(lambda x, y: x - y, p, params)
    f_params_x, proj = jax.api.jvp(lambda param: f(param, x), (params,), (dparams,))
    return f_params_x + proj
  return f_lin

init_random_params, predict = stax.serial(*[stax.Dense(20000), stax.Dense(10)] ) 
_, init_params = init_random_params(random.PRNGKey(970), (-1, 1000))
predict = linearize(predict, init_params)
x,y=( onp.random.randn(500,1000),onp.random.randn(500,1) )
lossf=lambda params,x,y: 0.5*np.mean((predict(params, x)-y)**2)  

for k in range(10):
    gradf=jit(grad(lossf))
    print(k)
    for j in range(1000):
        gradf(init_params, x,y)
~~~~
This would not run out of memory if grad(lossf) is defined outside of the k loop, but in my use case, I would like to jit different functions inside that loop without them staying in memory after the iteration is done.

**Comment by mattjj** [comment]
I think #1605 fixed this. We haven't updated pypi yet though.

If it's not inconvenient for you, could you try your test case against GitHub master (which includes #1605) to see if it's still an issue?

We should update pypi too, but it'd be great to know whether the update will fix this issue for you.

**Comment by mattjj** [comment]
Just updated jax on pypi to 0.1.50 to include #1605. A `pip install --upgrade jax` should do the trick!
