### ISSUE TITLE
Custom forward and reverse rule for function via transpose hitting python error

### ISSUE THREAD

**Issue by wsmoses** [google/jax#16336]
### Description

I was chatting with @jekbradbury about how to register both a custom vjp and jvp for use in https://github.com/EnzymeAD/Enzyme-JAX (a plugin for Jax to import foreign code as a layer using Enzyme, testing out C++ to begin with).

So far I have separate functions for use in a vjp/vjp since JaX isn't able to do both a custom forward and reverse registration on a single function. A conversation with @jekbradbury led me to trying to  making a custom transpose. I couldn't find docs on this so please forgive my ignorance here.

I tried to use the custom_transpose in a variety of ways that all seemed to lead to errors that I don't quite understand.

For example, one such attempt:
```python

@partial(jax.custom_jvp, nondiff_argnums=(0, 1, 2, 3))
@jax.custom_transpose
def cpp_fwd_internal(source: str, fn:str, argv: Sequence[str], out_shapes: Sequence[jax.core.ShapedArray], *args):
  return _enzyme_primal_p.bind(
      *args, source=source, fn=fn, argv=argv, out_shapes=out_shapes)

@cpp_fwd_internal.def_transpose
def ft(*args):
  print(args)
  return 3. * args[-1]

...
``` 

will hit
```python
wmoses@beast:~/git/Enzyme-JaX (main) $ python test/test.py 
Traceback (most recent call last):
  File "/home/wmoses/git/Enzyme-JaX/test/test.py", line 3, in <module>
    from enzyme_jax import cpp_fwd, cpp_rev
  File "/home/wmoses/anaconda3/lib/python3.9/site-packages/enzyme_jax/__init__.py", line 1, in <module>
    from enzyme_jax.primitives import cpp_fwd, cpp_rev
  File "/home/wmoses/anaconda3/lib/python3.9/site-packages/enzyme_jax/primitives.py", line 265, in <module>
    def cpp_fwd_internal(source: str, fn:str, argv: Sequence[str], out_shapes: Sequence[jax.core.ShapedArray], *args):
TypeError: 'module' object is not callable
```

### What jax/jaxlib version are you using?

commit 21fc6e0229e0f5f1cb5f1f69d2c3daa2e5c2ca11

cc @ftynse

**Comment by Edenhofer** [comment]
I was briefly using `custom_transpose` for the same purpose but eventually ran into issues. The issue that I filed about this shows a working example #13298 .

Currently, I am using something along the lines of
```python3
def f(ry, x):
    r, y = ry
    return y**2 * x / r


def t(ry, t):
    r, y = ry
    return y**2 * t / r


@partial(jax.custom_jvp, nondiff_argnums=(2, ))
def div(x, y, denom):
    return linear_call(f, t, (denom, y), x)


@div.defjvp
def div_jvp(denom, primals, tangents):
    x, y = primals
    x_tan, y_tan = tangents
    print(tangents)

    return div(x, y, denom), div(x_tan, y, denom)


d = partial(div, denom=3., y=10.)
jax.jvp(d, (6., ), (2., ))
jax.vjp(d, 6.)[1](2.)
```

Unfortunately, `linear_call` does not support batching nor higher-order derivatives :( (which doesn't matter to Enzyme in this case though)

**Comment by wsmoses** [comment]
bump @froystig any updates?

**Comment by froystig** [comment]
Custom transposition is (very gradual) work in progress, and not yet functioning. It's not documented for that reason, and I think shouldn't have it exposed as a public symbol altogether; most attempts to use it today will raise errors. I should figure out how to do that so as to to avoid confusion.

The remaining question is: what can we do for your use case without involving `custom_transpose`? One answer is to set up a custom primitive with a transposition rule. Custom primitives usually take more work, since they need a rule for every transformation. But, looking at your example (plus guessing from this being Enzyme), I gather you're already quite familiar with setting up custom primitives. Is that right? If so, what do you think of setting up one more for this purpose?

To be a bit more precise, what I have in mind is that you use a custom primitive in place of where you were trying to use custom transpose. This primitive would be bound from within the JVP rule of another operation.

**Comment by wsmoses** [comment]
I followed this guide (https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html) to move AD onto the primitives themselves (https://github.com/EnzymeAD/Enzyme-JAX/pull/6/files).

An issue I have come across for reverse mode (forward mode works fine) is that I would need to specify a custom modified forward and reverse pass (with tape passed to it), which doesn't seem to have nice support. 

Looking at how custom_vjp is handled, it looks like its manually written in? https://github.com/google/jax/blob/f4eed78e9079aece4feffe6ab31e7c76b6826e7d/jax/_src/interpreters/ad.py#L390

**Comment by froystig** [comment]
We don't define VJPs for primitives (see for instance [this note](https://arxiv.org/abs/2105.09469)). A primitive can have a JVP rule and it can have a transpose rule.

What I had in mind here was that you make one custom primitive `P1` whose JVP rule binds another primitive `P2`. You endow `P2` with a transposition rule. Together, these define the reverse-mode (i.e. VJP) behavior of the original primitive `P1`.

**Comment by wsmoses** [comment]
Yeah, and that style of custom rule is now implemented in the sample PR (https://github.com/EnzymeAD/Enzyme-JAX/pull/6).

The sole issue with this at the moment, which I'm curious if you have thoughts on, is as follows:

In both forward and reverse mode, the registration mechanism requires redundantly computing the forward pass results (as well as potentially preserving primal values further into the reverse pass).

For example, in forward mode, Enzyme can compute both the primal and derivative together in the same custom op.

Unfortunately, having the generated forward mode op return both the primal and tangent, breaks the custom transpose (https://github.com/EnzymeAD/Enzyme-JAX/blob/fa8893b4c230e096e8acb412ebaad60cd80f49cc/enzyme_jax/primitives.py#L307). In particular the error recieved is as follows (replace that return with simply res):

```python
Traceback (most recent call last):
  File "/Users/wmoses/git/Enzyme-JAX/test/test.py", line 43, in <module>
    primals, f_vjp = jax.vjp(do_something, ones)
  File "/Users/wmoses/opt/anaconda3/lib/python3.9/site-packages/jax/_src/api.py", line 2164, in vjp
    return _vjp(
  File "/Users/wmoses/opt/anaconda3/lib/python3.9/site-packages/jax/_src/api.py", line 2173, in _vjp
    out_primal, out_vjp = ad.vjp(
  File "/Users/wmoses/opt/anaconda3/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 139, in vjp
    out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
  File "/Users/wmoses/opt/anaconda3/lib/python3.9/site-packages/jax/_src/interpreters/ad.py", line 130, in linearize
    assert all(out_primal_pval.is_known() for out_primal_pval in out_primals_pvals)
AssertionError
```

Notably in forward mode (aka without the custom tangent) that's fine, presumably since it doesn't have the unknown value.

Therefore, the remedy I found at the moment to allow the custom_tangent to work is to duplicate the forward pass for the return.

A similar issue occurs for forward mode, wherein Enzyme has its own augmented forward pass (that generates a tape of the minimum computed values needed for reverse, as well as any desired outputs). We need that tape for the reverse pass, so we have to run the augmented forward. However, doing this during the transposition itself puts this in the reverse pass, unnecessarily keeping around all of the primal values until that point, in addition to unnecessarily re-computing the primal (wherein that would have been potentially save redundant forward-pass computation).

See below for an example:
```python

@jax.jit
def g(a, b, x, y):
    primals, f_vjp = jax.vjp(do_something, a, b)
    return primals, f_vjp((x, y))

print(g.lower(ones, twos, x, y).compiler_ir(dialect="stablehlo"))
print(g.lower(ones, twos, x, y).compiler_ir(dialect="mhlo"))
```

```mlir
module @jit_g attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {
  func.func public @main(%arg0: tensor<2x3xf32> {jax.arg_info = "a", mhlo.sharding = "{replicated}"}, %arg1: tensor<5x7xf32> {jax.arg_info = "b", mhlo.sharding = "{replicated}"}, %arg2: tensor<6x9xf32> {jax.arg_info = "x", mhlo.sharding = "{replicated}"}, %arg3: tensor<4x6xf32> {jax.arg_info = "y", mhlo.sharding = "{replicated}"}) -> (tensor<6x9xf32> {jax.result_info = "[0][0]"}, tensor<4x6xf32> {jax.result_info = "[0][1]"}, tensor<2x3xf32> {jax.result_info = "[1][0]"}, tensor<5x7xf32> {jax.result_info = "[1][1]"}) {
    %0 = mhlo.constant dense<3> : tensor<1xi64>
    %1:2 = mhlo.custom_call @jaxzyme.primal(%0, %arg0, %arg1) {backend_config = ""} : (tensor<1xi64>, tensor<2x3xf32>, tensor<5x7xf32>) -> (tensor<6x9xf32>, tensor<4x6xf32>)
    %2 = mhlo.constant dense<4> : tensor<1xi64>
    %3:3 = mhlo.custom_call @jaxzyme.aug(%2, %arg0, %arg1) {backend_config = ""} : (tensor<1xi64>, tensor<2x3xf32>, tensor<5x7xf32>) -> (tensor<6x9xf32>, tensor<4x6xf32>, tensor<0xi8>)
    %4 = mhlo.constant dense<5> : tensor<1xi64>
    %5:2 = mhlo.custom_call @jaxzyme.rev(%4, %3#2, %arg2, %arg3) {backend_config = ""} : (tensor<1xi64>, tensor<0xi8>, tensor<6x9xf32>, tensor<4x6xf32>) -> (tensor<2x3xf32>, tensor<5x7xf32>)
    return %1#0, %1#1, %5#0, %5#1 : tensor<6x9xf32>, tensor<4x6xf32>, tensor<2x3xf32>, tensor<5x7xf32>
  }
}
```

**Comment by froystig** [comment]
> For example, in forward mode, Enzyme can compute both the primal and derivative together in the same custom op.

I think I see what you mean now.

For jax to generate a VJP from a JVP, we need the JVP to be "unzippable" (i.e. support partial evaluation over primals, for unknown tangents).

You'll have to tell me if this is possible with Enzyme, but one way to design this would be for Enzyme to supply to Python more than one underlying operation. Namely:

* For forward-mode:
  * A JVP op `O1`, mapping (primal inputs, tangent inputs) -> (primal outputs, tangents outputs) efficiently. I believe this is what you currently have.
* For reverse-mode:
  * A "forward" op `O2`, mapping (primal inputs, tangent inputs) -> (primal outputs, residuals), and
  * A "reverse" op `O3`, mapping (residuals, cotangent outputs) -> cotangent inputs

Then you can set up two JAX primitives like we said before:

* `P1` has a JVP rule that calls out to `O1`
* `P1` has a partial evaluation rule that calls out to `O2` and stages out a bind of `P2`
* `P2` has a transposition rule that calls out to `O3`

Is this reasonable?

**Comment by wsmoses** [comment]
Yeah I think that design remedies the redundant computation (with the possible exception of tape preservation which I need to think more on).

But if there are two primitives, would that not force users to have one primitive for forward mode support as distinct from reverse mode?

Or is it possible upon say the MLIR lowering phase to check if there is a transpose interpreter in the stack and switch between the forward and reverse mode lowered primitives?

Or if you have a different alternative.

**Comment by wsmoses** [comment]
Oh never mind I missed the custom partial evaluation rule, I think that would fix the double user primitive issue.

Let me take a stab at that.

**Comment by wsmoses** [comment]
Got it fully working, thanks!

**Comment by froystig** [comment]
Great to hear. We'll try to improve the interfaces here with time (custom transpose, primitives, etc.).
