### ISSUE TITLE
Implement matrix exponential

### ISSUE THREAD

**Issue by jekbradbury** [google/jax#1635]
This is `np.linalg.expm`. It probably makes sense to port the TF implementation in terms of Pade approximants (https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/ops/linalg/linalg_impl.py#L228-L339), which itself is a port from Eigen.

**Comment by mattjj** [comment]
We probably want to do the Pade approximant under a primitive, so that we can define a JVP rule for the primitive and thus approximate the derivative too (rather than differentiating the approximation). (Tip from @axch !)

**Comment by mattjj** [comment]
@j-towns did you think about this at one point?

**Comment by j-towns** [comment]
I remember pointing out at some point in the past that [the jvp is implemented in scipy](https://docs.scipy.org/doc/scipy-1.3.0/reference/generated/scipy.linalg.expm_frechet.html#scipy.linalg.expm_frechet]. You’re probably right that it should be wrapped in a primitive.

**Comment by Jakob-Unfried** [comment]
Any news on this? Is there some way i could help with the implementation?
I am new to Jax so I don't feel overly confident. But with a pointer to where it should be implemented, maybe a reference to some already implemented primitive and the available algorithms i would feel up to the task

**Comment by sriharikrishna** [comment]
I have been working on an implementation with @jhueckelheim. The JVP rule for the primitive uses Frechet derivatives (thanks @tpr0p). I will contribute this shortly.

**Comment by hawkinsp** [comment]
`expm` is implemented, together with its JVP. I'm going to close this issue, leaving https://github.com/google/jax/issues/3447 open for the reverse-mode derivative.

**Comment by alexmathfb** [comment]
Do you plan to support batches as done in ```torch.matrix_exp```?

https://pytorch.org/docs/stable/generated/torch.matrix_exp.html

**Comment by jakevdp** [comment]
Batching is supported through the [vmap](https://jax.readthedocs.io/en/latest/jax.html#vectorization-vmap) transform; for example:
```python
In [1]: from jax import vmap

In [2]: import numpy as np

In [3]: A = np.random.randn(10, 4, 4)

In [4]: out_batched = vmap(expm)(A)

In [5]: out_iter = jnp.array([expm(mat) for mat in A])

In [6]: np.allclose(out_batched, out_iter)                                                                                                                  
Out[6]: True
```

**Comment by alexmathfb** [comment]
Thanks, I should've just read the documentation, sorry for the stupid question.
