### ISSUE TITLE
Installation Bug: No Matching distribution found for jaxlib==0.4.12+cuda12.cudnn88; extra == "cuda12_local" (from jax[cuda12_local])

### ISSUE THREAD

**Issue by KapilKhanal** [google/jax#16362]
### Description

For CUDA 12.1 and cuDNN 8.8 No wheel is available. The suggested whl to use was CUDA 12 and cuDNN 8.9 but this does not work and I only have cuDNN 8.8. 

Thanks,

### What jax/jaxlib version are you using?

jaxlib==0.4.12

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.8.10, Ubuntu 20.04.6 LTS

### NVIDIA GPU info

Mon Jun 12 14:37:26 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.41.03              Driver Version: 530.41.03    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000                Off| 00000000:65:00.0  On |                  Off |
| 32%   61C    P2               79W / 300W|  48625MiB / 49140MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1189      G   /usr/lib/xorg/Xorg                           77MiB |
|    0   N/A  N/A      1939      G   /usr/lib/xorg/Xorg                          161MiB |
|    0   N/A  N/A      2074      G   /usr/bin/gnome-shell                         75MiB |
|    0   N/A  N/A      6749      C   python3                                   37240MiB |
|    0   N/A  N/A      7046      C   python3                                   10934MiB |
|    0   N/A  N/A     11541      G   /usr/lib/firefox/firefox                    121MiB |
+---------------------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
Oops, it looks like we got the name of the wheel wrong in our last JAX release. #16364 will fix. Once it is merged, you could either install from git head, or for now you can simply install the latest wheel directly. For you, it's this one:
https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.12+cuda12.cudnn89-cp38-cp38-manylinux2014_x86_64.whl

Note that CUDNN 8.9 is *required* for CUDA 12. So update if you have an older CUDNN.
