### ISSUE TITLE
Best practices for ODE reverse mode differentiation

### ISSUE THREAD

**Issue by ronan-keane** [google/jax#1645]
I am developing a differentiable traffic simulator as part of my dissertation. Right now, I have been using the adjoint method (i.e. doing it completely by hand) to do reverse mode differentiation. I want to switch over to automatic differentiation. As a result, I'm trying to figure out the best way to differentiate a large simulation using Jax. The simulation I'm taking the derivative of, you can think of as a system of ODEs being solved by forward euler. My issue is that the first call of the jitted objective function takes an extremely long time to run, or it may not even be possible to jit.

Here is a google collab notebook with a toy example 
https://colab.research.google.com/drive/1zKHw5kHSWcNTJI-9se6JaieCdBDnenA5
I've tested the following options for the timestepping 
1.  using python list and append 
2.  using numpy array and in place modification

For 1., passing the entire function through Jax will work, but the first call of the jitted function takes an extremely long time, after which it is very fast. If I don't jit, it is always very slow. 
For 2., when I try to jit, it crashes my computer. If I don't jit, again it is very slow. 

So based on this, my conclusion is that it is not tractable to pass the entire function through Jax. Other people may also like to know that the tests show that using native python lists and append is actually a lot faster than using numpy arrays. Note that if you use np.append instead of in place modification numpy becomes even worse. 

I know one option is to only use auto differentiation on the model (i.e. only apply it to the ODE function which is applied at each timestep). Here, you will still need to implement code to solve the adjoint system, but it saves you from actually having to differentiate the model yourself (this technique, to my knowledge, was first proposed in https://arxiv.org/pdf/1806.07366.pdf). It looks like this is the most promising option since just passing the entire objective through Jax does not look feasible, since the first jit call takes too long. 
**Any experts on using automatic differentiation with differential equations who want to weigh in on this?** 
I saw in the fluid simulation example in autograd they are simply passing the whole thing through autograd.

**Comment by shoyer** [comment]
You need to rewrite your function in terms of vectorized operations, if possible, and use JAX's native control flow operations:
https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Control-Flow

You can also find an adaptive time-step ODE solver (with an adjoint method for backwards differentiation) in `jax.experimental.ode`.

**Comment by ronan-keane** [comment]
Unfortunately in my actual application it's not possible to vectorize. It's also not going to be possible for me to use the `experimental.ode` function. It is good to know though that `experimental.ode` is implementing the same paper I mentioned. 

Thank you for sharing the documentation on control flow. Being able to differentiate conditionals is important for me - any idea when lax.cond will do this? 

I'm still a bit confused as to why the first run of the jitted function takes so long in my example. My understanding is that it's because the entire nested for loop gets unrolled - can someone confirm?

**Comment by shoyer** [comment]
Yes, your loops are being unrolled. This results in a giant computation graph, which is very slow to compile.

Can you use np.where instead of conditionals? That is usually faster in JAX.

**Comment by ronan-keane** [comment]
np.where is an option. It seems like using np.where would be doing something similar to tensorflow, where each part of the conditions gets differentiated. In the models I'm using, there are many possible regimes (e.g. you are in a state where you are basically just following the car in front of you, you are in a state where you are braking strongly, etc.). So at every timestep for the adjoint system, I'm going to need to differentiate this model, which will have 5-10+ branches corresponding to the different situations.
