### ISSUE TITLE
Apple Silicon: jax.numpy.dot and jax.numpy.matmul crashes

### ISSUE THREAD

**Issue by nikolajjensen** [google/jax#16471]
### Description

I am seeing an issue in jax.numpy-dot and jax.numpy.matmul as illustrated by this example of jax.numpy.dot:

```
import jax.numpy as jnp
import numpy as np

x = np.array(np.random.rand(3, 3))
y = np.array(np.random.rand(3))
z = np.array(np.random.rand(3))

print("X: ", x)
print("Y: ", y)
print("Z: ", z)

print("Numpy 1D*1D: ", np.dot(y, z))
print("Jax Numpy 1D*1D: ", jnp.dot(y, z))
print("Numpy 2D*1D: ", np.dot(x, y))
print("Jax Numpy 2D*1D: ", jnp.dot(x, y))
```

```
loc("-":4:5): error: type of return operand 0 ('tensor<*xf32>') doesn't match function result type ('tensor<3xf32>') in function @main
/AppleInternal/Library/BuildRoots/1a7a4148-f669-11ed-9d56-f6357a1003e8/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphExecutable.mm:1950: failed assertion `Error: MLIR pass manager failed'
zsh: abort      python test.py
```

I am using the Metal backend:
```
Metal device set to: Apple M1 Max

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB
```

### What jax/jaxlib version are you using?

Jax 0.4.11, jaxlib 0.4.10, and Jax-metal 0.0.2

### Which accelerator(s) are you using?

GPU (Apple M1 Max)

**Comment by nikolajjensen** [comment]
Apologies, I forgot to mention it. I am on macOS 14 (Sonoma). I know this is still experimental, but thought I would share the issue anyways.

**Comment by kylemcdonald** [comment]
When I try to run the test code above on my Mac M1 computer, I get the error:

```
X:  [[0.61398573 0.92741047 0.09098625]
 [0.34769729 0.61374832 0.82537727]
 [0.09943488 0.0612767  0.75947767]]
Y:  [0.24543303 0.10244599 0.62912991]
Z:  [0.56156122 0.37598055 0.21090334]
Numpy 1D*1D:  0.30902896698998683
[/var/folders/cv/96wzgj4x73l9szhbb0cbhsqw0000gn/T/ipykernel_39313/935748896.py:13](https://file+.vscode-resource.vscode-cdn.net/var/folders/cv/96wzgj4x73l9szhbb0cbhsqw0000gn/T/ipykernel_39313/935748896.py:13): DeprecationWarning: ml_dtypes.float8_e4m3b11 is deprecated. Use ml_dtypes.float8_e4m3b11fnuz
  print("Jax Numpy 1D*1D: ", jnp.dot(y, z))
Metal device set to: Apple M1 Max

systemMemory: 64.00 GB
maxCacheSize: 24.00 GB
```

Followed by a kernel crash.

I installed Jax following the instructions [here](https://developer.apple.com/metal/jax/) with the only change being that I replaced `python -m pip install jax` with `python -m pip install jax==0.4.11`

- Python 3.9.16
- jax 0.4.11
- jaxlib 0.4.10
- jax-metal 0.0.2
- MacOS 13.4

**Comment by hawkinsp** [comment]
The warning about `ml_dtypes` is benign and would go away if you downgraded `ml_dtypes` or upgraded `jax`. However you cannot update `jax` and still use the metal plugin until a new release of `jax-metal` is made by Apple.

The kernel crash is more interesting.

**Comment by nikolajjensen** [comment]
For good measure I will also mention that I get the same deprecation warning. The code executes fine until the crash in the last line: `print("Jax Numpy 2D*1D: ", jnp.dot(x, y))`.

**Comment by shuhand0** [comment]
Close as it is fixed by the latest metal plugin.
