### ISSUE TITLE
Batching rule for `dyanmic_slice` not defined

### ISSUE THREAD

**Issue by alexbw** [google/jax#165]
If you use indexing , e.g. `x[0]` in a function you `vmap`, it fails.

**Comment by hawkinsp** [comment]
Related: we are also missing the XLA Gather primitive, which is the right way to write many batch dynamic slices.

**Comment by mattjj** [comment]
+1 hawkinsp, our index_take predated the Gather HLO (and I find that HLO confusing) so it could be that index_take can be replaced entirely. I’m interested to know if you think that’s possible. 

(I would love to take this, but probably can’t for about 36 hours.)
