### ISSUE TITLE
AttributeError: module 'jax.interpreters.xla' has no attribute 'DeviceArray'

### ISSUE THREAD

**Issue by louieworth** [google/jax#16505]
### Description

Hi, I am trying to save the model in. my network, but it appears an error in the title.
```
def save(self, save_path: str):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    with open(save_path, 'wb') as f:
        f.write(flax.serialization.to_bytes(self.params))
```

error track:
```
module 'jax.interpreters.xla' has no attribute 'DeviceArray'
  File "common.py", line 95, in save
    f.write(flax.serialization.to_bytes(self.params))
AttributeError: module 'jax.interpreters.xla' has no attribute 'DeviceArray'
```

### What jax/jaxlib version are you using?

0.4.12

### Which accelerator(s) are you using?

GPU

### Additional system info

Linux

### NVIDIA GPU info

3090

**Comment by hawkinsp** [comment]
Well, that's correct, `DeviceArray` was removed from JAX several versions ago. The question is what other code is trying to refer to it. It's not really possible to tell based on the information you gave, but perhaps try updating other packages like `flax`?

**Comment by louieworth** [comment]
Thanks for your reply. I am trying to save the checkpoint.  Should I discard this approach to save the checkpoint rather than turn to other solutions, like this [URL](https://flax.readthedocs.io/en/latest/guides/use_checkpointing.html)?

**Comment by hawkinsp** [comment]
Well, what you are doing may work. I think the problem is you have an older version of some package that refers to the old JAX type.

I think in particular it is likely your`flax` version is much too old: the current release is 0.6.11.

**Comment by HelloTaeyeon** [comment]
> Thanks for your reply. I am trying to save the checkpoint. Should I discard this approach to save the checkpoint rather than turn to other solutions, like this [URL](https://flax.readthedocs.io/en/latest/guides/use_checkpointing.html)? I have updated the package to `flax==0.4.2`.
> 
> Could you please give me a quick example about how to save and load the model at the state-of-the-art JAX version(`0.4.12`)?

Did you solve this problem?

**Comment by louieworth** [comment]
> > Thanks for your reply. I am trying to save the checkpoint. Should I discard this approach to save the checkpoint rather than turn to other solutions, like this [URL](https://flax.readthedocs.io/en/latest/guides/use_checkpointing.html)? I have updated the package to `flax==0.4.2`.
> > Could you please give me a quick example about how to save and load the model at the state-of-the-art JAX version(`0.4.12`)?
> 
> Did you solve this problem?

Yes. I uninstall the flax and reinstalled `flax==0.6.11` and `jax==0.4.12`. 3090. (do not update the `flax==0.6.11` model)

**Comment by Nahush26** [comment]
My code is using flax.optim optimizers and I am using flax==0.5.1. I am unable to checkpoint using orbax ( unexpected attribute .step) or the legacy api  (same error as mentioned in the thread) . Can't update to flax 0.6.0 or greater since there won't be any optim support. How do I save the train state in this case?

**Comment by jakevdp** [comment]
Hi @Nahush26 - you'll probably have more luck getting this question answered at https://github.com/google/flax/discussions. Best of luck!
