### ISSUE TITLE
Use PEP 585 type hints

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#16537]
Since JAX just dropped Python 3.8 support, we can update our type hints to use the PEP 585 syntax.
https://peps.python.org/pep-0585/

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/16544 does half of the PEP 585 conversion. The remaining piece is that many names should now be imported from, e.g., `collections.abc` instead of `Typing`. I won't have time to take that part right now.

**Comment by lgeiger** [comment]
> The remaining piece is that many names should now be imported from, e.g., `collections.abc` instead of `Typing`.

[`pyupgrade --p39-plus`](https://github.com/asottile/pyupgrade) should be able to [automatically re-write these imports](https://github.com/asottile/pyupgrade#import-replacements) as well as a few other upgrades related to new syntax. Just mentioning it here for future reference in case that wasn't already used for the above PR.
