### ISSUE TITLE
jax.scipy.stats.binom missing

### ISSUE THREAD

**Issue by edsgunn** [google/jax#16550]
I can't find an implementation of the jax equivalent of the binomial from scipy.stats. Specifically in my case I am looking for a jittable way to calculate the binomial cdf i.e. `jax.scipy.stats.binom.cdf(k, n, p)`

**Comment by davisyoshida** [comment]
Based on reading the boost code [here](https://www.boost.org/doc/libs/1_67_0/boost/math/distributions/binomial.hpp), it looks like scipy computes this using the incomplete beta function.

You could try using `jax.scipy.special(n - k, k + 1, 1 - p)` as follows:

```python
>>> scipy.stats.binom.cdf(7, 10, 0.6)
0.8327102464
>>> jax.scipy.special.betainc(3, 8, 1 - 0.6)
Array(0.8327104, dtype=float32, weak_type=True)
```

The boost version is using `ibetac(k + 1, n - k, p)` which is mathematically identical to `ibeta(n - k, k + 1, 1 - p)`, but there's presumably some numerical reason why it's better to do the former.

**Comment by edsgunn** [comment]
Thank you that looks perfect

**Comment by jakevdp** [comment]
Thanks for the report - I'm going to re-open this to track adding support for `jax.scipy.stats.binom`.
