### ISSUE TITLE
Indexing a pytree with a `Tracer`

### ISSUE THREAD

**Issue by epignatelli** [google/jax#16559]
This is a follow up on https://github.com/google/jax/issues/2962, but also too off-topic to be included in it.
The problem is in accessing pytree addresses using `Tracer`s.

Consider an arbitrary pytree, for example `PyTreeDef((*, (*, *))`,  where all the leaves have the same shape `shape`.
What would be the problem in indexing the pytree with a `Tracer`, in a method that promises to return any of the leaves?
Is there a way to write that promise as an explicit constraint, and enable using the `Tracer` as an index?

Currently, indexing `Tracer`s with `Tracer`s works quite nicely (amazing btw):
```python
def get(collection, idx):
    print(collection, idx)
    return collection[idx]

collection = jnp.asarray((0, 1))
idx = jnp.asarray(1)
jax.jit(get)(collection, idx)

# Array(1, dtype=int32)
```

But as soon as `collection` is not a `Tracer` anymore (a `tuple` of `Tracer`s here), it stops working, even though the promise above is guaranteed to be maintaned.

```python
collection = (jnp.asarray((0, 1)), jnp.asarray((0, 1)))
jax.jit(get)(collection, idx)

# TracerIntegerConversionError: The __index__() method was called on the JAX Tracer object Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>
# See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerIntegerConversionError
```

Would it be possible to extend the ability to index with `Tracer`s to registered pytrees?

**Comment by jakevdp** [comment]
A traced value is a value that is only available at runtime, in an operation recognized by XLA. A PyTree is a Python data structure, which is only available at trace-time. XLA has no conception of a "PyTree" – XLA only knows about operations on arrays. This is why a tracer cannot be used to index into a PyTree – the two values exist at different levels of the stack.

That said, you can make this work if you convert  your pytree into some kind of structure that *can* be represented in XLA. The closest match in this case is the `lax.switch` operation, perhaps something like this:
```python
import jax

tree = (10, [11, 12], [13, 14])

@jax.jit
def index(tree, i):
  tree_flat, _ = jax.tree_util.tree_flatten(tree)
  funcs = [lambda i=i: tree_flat[i] for i in range(len(tree_flat))]
  return jax.lax.switch(i, funcs)

print(index(tree, 2))
# 12
```

**Comment by epignatelli** [comment]
Thanks for the answer!

The limitation of `switch` is that, unless the pytree has only one level of nodes, I couldn't find a way to access the leaves with multiple indexes without nesting multiple `switch`es.

For the moment, I resorted to padding the pytree with a copy of a leaf if the branch has a fewer number elements than than maximum one. Which is quite expensive, but I am doing it on a constant, luckly.

It would be great if there was a simpler way to access leaves at a level deeper than 1 with a `Tracer`, even though it doesn't seem like something on the roadmap?

**Comment by jakevdp** [comment]
If you have multiple levels in the pytree, you can use `tree_flatten`:
```python
import jax
import jax.numpy as jnp

@jax.jit
def get_switch(x, i):
  x_flat, _ = jax.tree_util.tree_flatten(x)
  funcs = [lambda i=i: x_flat[i] for i in range(len(x_flat))]
  return jax.lax.switch(i, funcs)

collection = [jnp.array([1, 1]), (jnp.array([2, 2]), jnp.array([3, 3]))]
print(get_switch(collection, 1))
# [2, 2]
print(get_switch(collection, 2))
# [3, 3]
```

**Comment by patrick-kidger** [comment]
This actually speaks to a feature I've wanted for a while: to have assurances that a pytree, and its flattened representation, are just views on to the same block of memory.

This would be amazingly useful in the context of a lot of linear algebra operations -- stuff like QR decompositions are only written to handle matrices. But in practice we often actually have pytrees of the appropriate structure instead.

I expect that right now there's a lot of inefficient copying data around in memory.

**Comment by epignatelli** [comment]
> This actually speaks to a feature I've wanted for a while: to have assurances that a pytree, and its flattened representation, are just views on to the same block of memory.

I very much agree, and that was the underlying idea behind the request.
The same way one can reshape an array to access it with different semantics, one could also decompose it with a more complex address that does not respect those simmetries in the array.

Pytrees kind of work like, mapping from flatten to unflatten and viceversa, though?
To me the only bit that is missing is to be able to do the same, but after compilation.

**Comment by davisyoshida** [comment]
> This actually speaks to a feature I've wanted for a while: to have assurances that a pytree, and its flattened representation, are just views on to the same block of memory.

In what circumstances flattening cause copying? Or do you mean copying of the python objects for the nodes?

**Comment by jakevdp** [comment]
> Pytrees kind of work like, mapping from flatten to unflatten and viceversa, though?
> To me the only bit that is missing is to be able to do the same, but after compilation.

I think `lax.switch` is the way that this can be done after compilation, and I doubt XLA will develop any other mechanism for indexing into Python tuples and other object structures. Perhaps we could come up with some kind of helper function that would make it easier to do what you have in mind? It sounds hard in general, though, because a PyTree can be literally *any* Python object. Mapping arbitrary Python-side indexing semantics into a deliberately constrained IR sounds impossible.
