### ISSUE TITLE
What is the distributed strategy of jax.distributed, just like tf.distributed, data parallelism?

### ISSUE THREAD

**Issue by a-seeker** [google/jax#16574]

**Comment by jakevdp** [comment]
Hi, thanks for the question! Could you please add some more detail about what you're asking? I'm having trouble understanding what information you're seeking from the title alone.

**Comment by a-seeker** [comment]
Thank for your answer! In tf, I can find from the link: https://www.tensorflow.org/guide/distributed_training?hl=ja about the tf distributed training strategy。 But in jax, from https://jax.readthedocs.io/en/latest/_autosummary/jax.distributed.initialize.html I can only find a little bit about the content of the distributed, I want to know more information about the distributed of jax

**Comment by jakevdp** [comment]
I see - I would start with these docs:

- https://jax.readthedocs.io/en/latest/multi_process.html
- https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html
