### ISSUE TITLE
Custom primitives breaking in >=0.4.9

### ISSUE THREAD

**Issue by nishadgothoskar** [google/jax#16580]
### Description

I have a few custom primitives that I have written that worked on <=0.4.8 but break on 0.4.9.

After some searching around in the jax repo, I found some examples of primitives that have to branch on the version of jax:

https://github.com/google/jax/blob/f463437c7ee81f915d2404d302b6bc5b32ecffbe/jax/experimental/rnn.py#L409
https://github.com/google/jax/blob/f463437c7ee81f915d2404d302b6bc5b32ecffbe/jax/_src/prng.py#L1080

I would like to update my custom primitives such that they work on newer versions of jax. What changed in 0.4.9?

### What jax/jaxlib version are you using?

jax v0.4.9

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.9

### NVIDIA GPU info

Wed Jun 28 16:00:59 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  On   | 00000000:00:1E.0 Off |                    0 |
| N/A   44C    P0    52W / 300W |   3438MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A    157117    C+G   ...nvs/bayes3d/bin/python3.9     3434MiB |
+-----------------------------------------------------------------------------+

**Comment by nishadgothoskar** [comment]
There is actually no error. I've written a custom primitive that calls out to a CUDA kernel. And my tests show that the CUDA kernel when called on its own (through python bindings) is functioning correctly and producing the correct output. However when I call the jax primitive that uses that kernel the outputs are empty. But what's even more odd is that it's not deterministic. The first time I call the Jax primitive the outputs are empty. The second time, it is correct. And then every time after that it is empty again.

Has something changed in how custom primitives, lowering, or abstract eval are done?

**Comment by jakevdp** [comment]
No, offhand I don't know of any changes that would have that effect. Can you provide a reproduction of the issue? And can you clarify which jax & jaxlib versions seem to introduce the problem?

**Comment by PhilipVinc** [comment]
In mpi4jax we have quite a few cpu and gpu  primitives and the most recent version of jax that broke something was 0.4.4.

**Comment by hawkinsp** [comment]
One thing we noticed that changed around jax 0.4.8 was that we no longer synchronize with respect to the default GPU stream (stream 0). You *must* synchronize with respect to the stream passed to the custom kernel.

**Comment by hawkinsp** [comment]
Put another way: JAX now creates its streams with the semantics `CU_STREAM_NON_BLOCKING`, see https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__STREAM.html

**Comment by hawkinsp** [comment]
I'm going to declare this issue fixed!
