### ISSUE TITLE
Execution time of `lax.scan` >> `lax.fori_loop` > unrolled python `for`

### ISSUE THREAD

**Issue by epignatelli** [google/jax#16611]
I haven't been able to reduce the problem yet, but at this high level I found that the exact same computation, performed with a `lax.scan` or with a `lax.fori_loop` or with an unrolled python `for` loop has very different exection times.

I'll try to make this example as minimal as possible, but the phaenomenon is already visible at this high level.

Colab to reproduce here:
https://colab.research.google.com/drive/11SNojrjrLxr9NK22MzYVienHyaY2taWg?usp=sharing

### Results for a `gpu` backend
- `lax.scan`:
```
Profiling observation <function rgb at 0x7f1ec0778b80>, N_SEEDS = 1000, N_TIMESTEPS = 10
	Compiling <function rgb at 0x7f1ec0778b80>...
	Compiled in 2.58s
	Running <function rgb at 0x7f1ec0778b80>...
	 1.7561769485473633 ± 0.04301055893301964
```

- `lax.fori_loop`
```
Profiling observation <function rgb at 0x7f1ec0778b80>, N_SEEDS = 1000, N_TIMESTEPS = 10
	Compiling <function rgb at 0x7f1ec0778b80>...
	Compiled in 3.28s
	Running <function rgb at 0x7f1ec0778b80>...
	 0.6279381513595581 ± 0.015154112130403519
```

- python `for` loop
```
Profiling observation <function rgb at 0x7f1ec0778b80>, N_SEEDS = 1000, N_TIMESTEPS = 10
	Compiling <function rgb at 0x7f1ec0778b80>...
	Compiled in 11.15s
	Running <function rgb at 0x7f1ec0778b80>...
	 0.10700666159391403 ± 0.012459419667720795
```

Here is the original, unsplit code:

```python
import time
from timeit import repeat

import jax
import jax.numpy as jnp
import navix as nx


N_TIMEIT_LOOPS = 10
N_REPEAT = 30
N_TIMESTEPS = 10
N_SEEDS = 1000


def test_observation(observation_fn):
    def test(seed):
        env = nx.environments.Room(
            height=5, width=10, max_steps=100, gamma=1.0, observation_fn=observation_fn
        )
        key = jax.random.PRNGKey(seed)
        timestep = env.reset(key)

        # option 1
        actions = jax.random.randint(key, (100,), 0, 6)
        timestep = jax.lax.scan(lambda c, x: (env.step(c, x), ()), timestep, actions)[0]

        # option 2
        # actions = jax.random.randint(key, (100,), 0, 6)
        # timestep = jax.lax.fori_loop(0, N_TIMESTEPS, lambda i, val: env.step(val, jnp.asarray(actions[i])), timestep)

        # option 3
        # for i in range(N_TIMESTEPS):
        #     action = jax.random.randint(key, (), 0, 6)
        #     timestep = env.step(timestep, jnp.asarray(action))

        return timestep

    # profile navix scanned
    print(
        "Profiling observation {}, N_SEEDS = {}, N_TIMESTEPS = {}".format(
            observation_fn, N_SEEDS, N_TIMESTEPS
        )
    )

    seeds = jnp.arange(N_SEEDS)

    print(f"\tCompiling {observation_fn}...")
    start = time.time()
    test_jit = jax.jit(jax.vmap(test)).lower(seeds).compile()
    print("\tCompiled in {:.2f}s".format(time.time() - start))

    print(f"\tRunning {observation_fn}...")
    res = repeat(
        lambda: test_jit(seeds).observation.block_until_ready(),
        number=N_TIMEIT_LOOPS,
        repeat=N_REPEAT,
    )
    res = jnp.asarray(res)
    print(f"\t {jnp.mean(res)} ± {jnp.std(res)}")


if __name__ == "__main__":
    test_observation(nx.observations.rgb)
```

**Comment by jakevdp** [comment]
Thanks for the report – I think this is all behaving as expected.

Considering `fori_loop` vs.`scan`, we'd generally expect the timing to be equivalent in this case, because for static loop boundaries `fori_loop` is just a wrapper around `scan`. I believe the reason `scan` is slower in this case is because it returns the stacked intermediate values, while `fori_loop` does not, and thus your benchmarked `scan` test function has to allocate and transfer a large array that your `fori_loop` test function does not.

Regarding the difference between `fori_loop` and Python `for` loop, in general you should expect this to be a tradeoff between compilation time and execution time: `fori_loop` saves on compilation cost at the expense of a somewhat slower runtime, because all operations must be executed serially. A Python `for` loop increases compilation cost (because JAX unrolls the loop, leading to a larger XLA program that must be compiled) but can lead to faster execution (because by unrolling the loop, XLA is able to optimize computations across iterations and/or execute some of them in parallel). Your timings seem consistent with that.

I hope that background helps – let me know if you have other questions!

**Comment by epignatelli** [comment]
Hi Jake, thanks for the answer!

The general behaviour makes very much sense.
I'd really wish a python `for` was much quicker to compile, since the gap in performance is not negligible, but I understand there's no magic wand for that.

Focusing on `scan` vs `fori_loop`, I don't understand what is happening here, though.
`scan` returns an empty tuple and, assuming that the computational and memory cost of stacking empty tuples is negligible, there should be really no added cost.

The only difference I see between the `fori_loop` and the `scan` is in the supported AD mode.
Maybe something's getting cached under the hood to enable backward-mode AD in `scan` that is causing the slow-down?

**Comment by epignatelli** [comment]
I actually debugged the `fori_loop` and its internal mechanisms fall into using `scan` (`use_scan = True`), because `lower` and `upper` are `ConcreteArray`s representing integers.

**Comment by jakevdp** [comment]
> I'd really wish a python `for` was much quicker to compile, since the gap in performance is not negligible, but I understand there's no magic wand for that.

I too wish we could achieve the benefits of compiling a program without having to pay the cost of compiling it!

> I actually debugged the `fori_loop` and its internal mechanisms fall into using `scan` (`use_scan = True`), because `lower` and `upper` are `ConcreteArrays` representing integers.

Right, this is what I mentioned above: `fori_loop` lowers to `scan` in this case. You're right to point out I was mistaken about the stacked results making `scan` slower. I'm actually not sure what's causing the difference between the `scan` and the `fori_loop` versions, but I'll note one thing: the `fori_loop` function is scanning over an array of indices, and then repeatedly indexing into your `actions` array, while the `scan` function is scanning over the actions array itself. Something about this difference probably changes how the compiler is able to optimize the operation.

**Comment by jakevdp** [comment]
Closing, because I think this is all working as expected!
