### ISSUE TITLE
orin agx failure

### ISSUE THREAD

**Issue by malv-c** [google/jax#16616]
### Description

ERROR: JAX requires Python 3.9 or newer, found  (3, 8)
3.8 is the  only version supported by nvidia

### What jax/jaxlib version are you using?

git

### Which accelerator(s) are you using?

gpu

### Additional system info

ubunt 20.

**Comment by malv-c** [comment]
ubuntu 20.04
no nvidia.smi
cuda 11.4

**Comment by jakevdp** [comment]
The most recent release of JAX (0.4.13) is the last version to support Python 3.8. If you're getting this message, I suspect you're attempting to install JAX from the main github branch (where Python 3.8 support has already been dropped).

Perhaps you could try installing JAX v0.4.13?

**Comment by malv-c** [comment]
thanks

Le jeu. 6 juil. 2023 à 13:20, Jake Vanderplas ***@***.***> a
écrit :
