### ISSUE TITLE
pip cuda11 install installs the wrong cudnn

### ISSUE THREAD

**Issue by TimCargan** [google/jax#16625]
### Description

When you install with `pip install jax[cuda11_pip]...` it installs an older version of cudnn (I think 8.5), not 8.8.  This looks to be because the setup has`nvidia-cudnn-cu11>=8.8` however checking the available version with `pip index versions nvidia-cudnn-cu11` 

```
Available versions: 2022.5.19, 2022.4.2, 2022.1.13, 2021.12.8, 2021.11.18, 2021.10.26, 8.9.2.26, 8.9.1.23, 8.9.0.131, 8.8.1.3, 8.8.0.121, 8.7.0.84, 8.6.0.163, 8.5.0.96
  INSTALLED: 8.8.1.3
  LATEST:    2022.5.19
```

The `nvidia-cudnn-cu11==2022.5.19` ends up installing the incorrect cudnn resulting in the following error: 
```
Could not load library libcudnn_ops_infer.so.8. Error: libcublas.so.11: cannot open shared object file: No such file or directory
Fatal Python error: Aborted   
```

This was fixed by running `pip install -U nvidia-cudnn-cu11==8.8.1.3`

### What jax/jaxlib version are you using?

jax v4.13  jaxlib v0.4.13+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.11, Linux

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.74       Driver Version: 470.74       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A6000    On   | 00000000:24:00.0 Off |                  Off |
| 30%   35C    P8    20W / 300W |      1MiB / 48685MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
````

**Comment by jakevdp** [comment]
Thanks for the report – it seems like we need to guard against the older versioning convention. Could you check whether specifying `nvidia-cudnn-cu11>=8.8<2020` would fix the issue for you?

**Comment by TimCargan** [comment]
I think it needs a comma between the filters and it works  e.g `pip install -U nvidia-cudnn-cu11>=8.8,<2020` installed `8.9.2.26`

**Comment by jakevdp** [comment]
One thing I'm confused about: where are you getting these year-based versions? If I run the following, I only see 8.X-style versions:
```
$ pip index versions nvidia-cudnn-cu11
nvidia-cudnn-cu11 (8.9.2.26)
Available versions: 8.9.2.26, 8.9.1.23, 8.9.0.131, 8.8.1.3, 8.8.0.121, 8.7.0.84, 8.6.0.163, 8.5.0.96
```
And indeed, only these versions are listed on pypi: https://pypi.org/project/nvidia-cudnn-cu11/#history

Is it possible that you are using some non-standard package index, or perhaps you have some versions of the package with non-standard version metadata in your local pip cache?

**Comment by TimCargan** [comment]
Ahh yeah, It looks like they have been pulled in from Nvidia's index ([https://pypi.ngc.nvidia.com](https://pypi.ngc.nvidia.com))

**Comment by jakevdp** [comment]
OK, thanks – given that these are pre-releases with non-standard version numbers, I think it's probably not important to fix this in JAX itself, and mark this up as user error. What do you think?

**Comment by TimCargan** [comment]
Yeah, I would say so, I don't think most people would have the Nivida index setup on a clean install. I would say it falls in the category of standard CUDA install pain.

**Comment by jakevdp** [comment]
OK, thanks for digging in!
