### ISSUE TITLE
`jax.scipy.linalg.schur` sometimes outputs worse results than `scipy.linalg` does.

### ISSUE THREAD

**Issue by tfunatomi** [google/jax#16624]
### Description

I found that `jax.scipy.linalg.schur` outputs worse results than `scipy.linalg` does for some matrices.
An example is as follows: 

- input matrix $a$:
```
 [[ 5.40766931e+11 -2.54249498e+12  1.29377457e+15]
 [ 6.95271769e+11 -3.26892212e+12  1.66342444e+15]
 [-7.31332695e-08  1.01474525e-06  9.98950247e-01]] 
```
- scipy outputs $T, Z$:
```
 [[[ 1.34033203e-01+0.j -3.23776675e+12+0.j -1.61152312e+15+0.j]
  [ 0.00000000e+00+0.j -2.72815518e+12+0.j -1.35787582e+15-0.j]
  [ 0.00000000e+00+0.j  0.00000000e+00+0.j  9.99466611e-01+0.j]]

 [[-9.78120762e-01+0.j  2.08037918e-01+0.j  0.00000000e+00+0.j]
  [-2.08037918e-01+0.j -9.78120762e-01+0.j  3.10421971e-19+0.j]
  [ 6.45795408e-20+0.j  3.03630175e-19+0.j  1.00000000e+00+0.j]]] 
```
- scipy_reconst_error $(Z T Z^\top)-a$:
```
 [[-1.22070312e-04+0.j  4.88281250e-04+0.j  0.00000000e+00+0.j]
 [ 0.00000000e+00+0.j  4.88281250e-04+0.j  0.00000000e+00+0.j]
 [-1.42694364e-07+0.j -2.11758237e-22+0.j  0.00000000e+00+0.j]] 
```
- jax outputs $T, Z$:
```
 [[[ 9.6824047e+04+0.j -3.2377665e+12+0.j -1.6115230e+15+0.j]
  [ 0.0000000e+00+0.j -2.7281549e+12+0.j -1.3578758e+15-0.j]
  [ 0.0000000e+00+0.j  0.0000000e+00+0.j  9.9946660e-01+0.j]]

 [[-9.7812068e-01+0.j  2.0803790e-01+0.j  0.0000000e+00+0.j]
  [-2.0803790e-01+0.j -9.7812074e-01+0.j  3.1042201e-19+0.j]
  [ 6.4579541e-20+0.j  3.0363021e-19+0.j  1.0000000e+00+0.j]]] 
```
- jax_reconst_error $(Z T Z^\top)-a$:
```
 [[-3.2768000e+04+0.j  5.2428800e+05+0.j -2.6843546e+08+0.j]
 [-1.3107200e+05+0.j  2.6214400e+05+0.j -1.3421773e+08+0.j]
 [-1.4269435e-07+0.j  0.0000000e+00+0.j  0.0000000e+00+0.j]] 
```

### What jax/jaxlib version are you using?

0.4.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Python3.10 Ubuntu22.04

**Comment by jakevdp** [comment]
I suspect this is due to the fact that JAX defaults to 32-bit precision, while numpy defaults to 64-bit precision (see [JAX Sharp Bits: Double Precision](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision))

You can enable 64-bit precision in JAX with the following:
```
jax.config.update('jax_enable_x64', True)
```
With this enabled, I suspect that you'll see JAX's results exactly match those of scipy.

**Comment by tfunatomi** [comment]
I appreciate your great help.
It really the cause. Sorry for that it must be FAQ.
