### ISSUE TITLE
Adding `kl_div` and `rel_entropy` to `jax.scipy.special`

### ISSUE THREAD

**Issue by SalamanderXing** [google/jax#16630]
Hi, right now `jax.scipy.special` does not have a `kl_div` function, and computing this function naively in its closed form does not have the same numerical stability.
I checked the [implementation](https://github.com/scipy/scipy/blob/899f4efbcd8020b538bd97eb54353b3249af6e43/scipy/special/_convex_analysis.pxd#L13)  from `scipy.special.kl_div`, equivalent to:

```math
    \text{kldiv}(p,q)= \begin{cases}
    p\textrm{log}(p/q) -p +q , & \text{if } p \gt 0, q \gt 0\\
    q, & p = 0, q \ge 0 \\
    \infty,              & \text{otherwise}
\end{cases}
```
A possible LAX implementation:

```python
def kl_div(
    p: ArrayLike,
    q: ArrayLike,
) -> Array:
    both_gt_zero_mask = lax.bitwise_and(lax.gt(p, 0.0), lax.gt(q, 0.0))
    one_zero_mask = lax.bitwise_and(lax.eq(p, 0.0), lax.ge(q, 0.0))

    one_filler = lax.full_like(p, 1.0)
    inf_filler = lax.full_like(p, np.inf)

    safe_p = lax.select(both_gt_zero_mask, p, one_filler)
    safe_q = lax.select(both_gt_zero_mask, q, one_filler)

    log_val = lax.add(
        lax.sub(lax.mul(safe_p, lax.log(lax.div(safe_p, safe_q))), safe_p), safe_q
    )
    result = lax.select(
        both_gt_zero_mask, log_val, lax.select(one_zero_mask, q, inf_filler)
    )
    return result
```

Notice that scipy upgrades floats to double precision, so this JAX implementation only gives a result that matches scipy's up to an absolute tolerance of `1e-6`.
I was thinking of making a pull request adding this function, and perhaps `rel_entropy` function, (similarly implemented). What do you think?

@j-towns

**Comment by jakevdp** [comment]
Looks useful, thanks! If you make the PR, feel free to tag me as a reviewer.
