### ISSUE TITLE
Different result while using ``at[].apply`` inside jax.vmap

### ISSUE THREAD

**Issue by yashjha123** [google/jax#16655]
### Description

Jax's Array index helper `at` potentially has a bug when used inside `jax.vmap`. Using ``apply(lambda...)``  inside ``jax.vmap`` gives me a different result as to when run sequentially and inside jit. 
Here's the following code that I'm trying to run
```python
import jax
import jax.numpy as np

a = np.array([1,2,3,4,5,6])
def adder(a,val):
    a = a.at[val].apply(lambda a:a-1)
    return a

ind = np.array([3])
print(adder(a,ind))
```
I get the expected result;
``[1 2 3 4 5 6]``
However, when the same function is used inside jax.vmap I get a different result
```python
v_adder = jax.vmap(adder,in_axes=(0,None))
a = np.array([[1,2,3,4,5,6]])
ind = np.array([3])
print(v_adder(a,ind))
```
``[[1 2 3 0 5 6]]``
Note that I had to add another dimension in order to use it inside vmap which I don't think is the root cause.
Took me a day of debugging to hunt down this bug 😭. 

### What jax/jaxlib version are you using?

jax==0.4.13 jaxlib==0.4.13

### Which accelerator(s) are you using?

CPU

### Additional system info

WSL

**Comment by mattjj** [comment]
Thanks for the report, and sorry for the difficulty in tracking down the bug. We really appreciate it though, especially with the minimal repro.

> I get the expected result;
> [1 2 3 4 5 6]

Did you mean `[1 2 3 3 5 6]`?

This certainly looks like a bug to me! It reproduces on TPU too. Here are the jaxprs:

```python
print(jax.make_jaxpr(adder)(a,ind))
```
```
{ lambda ; a:i32[6] b:i32[1]. let
    c:bool[1] = lt b 0
    d:i32[1] = add b 6
    e:i32[1] = select_n c b d
    f:i32[1,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(1, 1)] e
    _:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    g:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    h:i32[6] = scatter[
      dimension_numbers=ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))
      indices_are_sorted=False
      mode=GatherScatterMode.FILL_OR_DROP
      unique_indices=False
      update_consts=()
      update_jaxpr={ lambda ; i:i32[] j:i32[]. let k:i32[] = sub i 1 in (k,) }
    ] a f g
  in (h,) }
```

```python
print(jax.make_jaxpr(v_adder)(a,ind))
```

```
{ lambda ; a:i32[1,6] b:i32[1]. let
    c:bool[1] = lt b 0
    d:i32[1] = add b 6
    e:i32[1] = select_n c b d
    f:i32[1,1] = broadcast_in_dim[broadcast_dimensions=(0,) shape=(1, 1)] e
    _:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    g:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    h:i32[1,1] = broadcast_in_dim[broadcast_dimensions=(1,) shape=(1, 1)] g
    i:i32[1,6] = scatter[
      dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(1,), scatter_dims_to_operand_dims=(1,))
      indices_are_sorted=False
      mode=GatherScatterMode.FILL_OR_DROP
      unique_indices=False
      update_consts=()
      update_jaxpr={ lambda ; j:i32[] k:i32[]. let  in (k,) }
    ] a f h
  in (i,) }
```

What's up with that second `update_jaxpr`!?

**Comment by mattjj** [comment]
Yeah sorry, scatter-apply just isn't batchable; there's a rule defined but it doesn't work. In particular, it [ignores the `update_jaxpr` (and hence the user-defined fucntion)](https://github.com/google/jax/blob/1795b12a9f7bca118d75c981fadd61331680de57/jax/_src/lax/slicing.py#L2070) it's given.

**Comment by jakevdp** [comment]
Thanks for the report! The fix should make it into the next JAX release.

**Comment by jakevdp** [comment]
Note #16684 – it looks like `scatter_apply` still doesn't work correctly with autodiff. I'm going to try to tackle this soon.
