### ISSUE TITLE
 Sudden problem importing JAX 

### ISSUE THREAD

**Issue by leialorenzo** [google/jax#16666]
### Description

Hello!
I use jax within PyMC to run inference. 
I've returned to a previously working jupyter notebook and suddenly 
```import pymc.sampling_jax```
as well as 
```import jax```
returns the following error
```ModuleNotFoundError: No module named 'jax.experimental'; 'jax' is not a package```

I've run this in the same environment as before as well as in a brand new one with conda installation to no avail.

All of this is running in Ubuntu 22.04.2 and Numpy is v1.25.1.
Thanks in advance!

### What jax/jaxlib version are you using?

jax v0.4.13 jaxlib v0.4.12

### Which accelerator(s) are you using?

CPU

### Additional system info

Python v3.11.4

**Comment by jakevdp** [comment]
I suspect you've created a file named `jax.py` somewhere in your path, and Python's import mechanism is finding this before it finds the installed JAX package.
