### ISSUE TITLE
pmap equivalent of `static_argnums` (broadcast_argnums)

### ISSUE THREAD

**Issue by botev** [google/jax#1671]
It would be nice to have `pmap` be able to cover some arguments in a similar way to the way `jit` treats `static_argnums` and is able to do a separate compilation for every new arguments. For instance I was trying to do `pmap(jit(f...))` where the jit function have static_arnums but it did not work, and currently is impossible to set. E.g. as a  tiny example:
```
import jax 
import jax.numpy as np

def bcast_all_devices(obj, num_devices):
  obj_stacked = jax.tree_map(lambda x: np.stack([x] * num_devices, axis=0), obj)
  obj_all_devices = jax.pmap(lambda x: x)(obj_stacked)  # shard across devices
  return obj_all_devices

def func(a, b, use_b):
  if use_b:
    return a * b
  else:
    return a ** 2
    
jit_func = jax.jit(func, static_argnums=2)
def wrapper(a, b=None):
  b, use_b = (1, False) if b is None else (b, True)
  return jit_func(a, b, use_b)

pmapped = jax.pmap(jit_func)

def p_wrapper(a, b=None):
  num_devices = a.shape[0]
  b, use_b = (1, False) if b is None else (b, True)
  use_b = bcast_all_devices(use_b, num_devices)
  return pmapped(a, b, use_b)

a = np.ones([8, 2]) * 2
b = np.arange(16).reshape([8, 2])
print(wrapper(a[0], b[0]))
print(wrapper(a[0]))
print(p_wrapper(a, b))
```
Can't be made to work since:
1. If you don't broadcast the boolean value the function complains beacause the boolean does not have the correct axis being passed to pmap
2. If you broadcast the boolean value then there is an error that the jitted function wants a concrete value but it go an abstract value.
3. If you switch the order - e.g. jit(pmap(f)) you get similar issue with concrete values - it seems jit(pmap(f)) currently can never work if there are any static_argnums.

**Comment by levskaya** [comment]
Just for the record, the reason the "obvious" solution of lexical closures isn't ideal, e.g. for pmap(jit(f)) case:

```python
import jax 
import jax.numpy as np
from functools import partial

def bcast_all_devices(obj, num_devices):
  obj_stacked = jax.tree_map(lambda x: np.stack([x] * num_devices, axis=0), obj)
  obj_all_devices = jax.pmap(lambda x: x)(obj_stacked)  # shard across devices
  return obj_all_devices

def func(a, b, use_b):
  if use_b:
    return a * b
  else:
    return a ** 2
    
jit_func = jax.jit(func, static_argnums=2)
def wrapper(a, b=None):
  b, use_b = (1, False) if b is None else (b, True)
  return jit_func(a, b, use_b)

# use lexical closure:
def pmapped(a, b, use_b):
  return jax.pmap(lambda x, y: jit_func(x, y, use_b))(a, b)

def p_wrapper(a, b=None):
  num_devices = a.shape[0]
  b, use_b = (1, False) if b is None else (b, True)
  # notice we're not broadcasting use_b!
  return pmapped(a, b, use_b)

a = np.ones([8, 2]) * 2
b = np.arange(16).reshape([8, 2])
print(wrapper(a[0], b[0]))
print(wrapper(a[0]))
print(p_wrapper(a, b))
```

Is that this lexical closure trick screws up our compilation memoization and triggers re-compilation, which is less than helpful!  So we need to plumb the same tricks used to implement the static_argnums case in `jit` for `pmap` to avoid excessive recompilation.

**Comment by botev** [comment]
Doesn't that require essentially to make sure you cache the recompilations based on the `static_argnums`?

**Comment by levskaya** [comment]
Yeah, that's how `jit` works - changes in any of the static args triggers a re-compilation.  If I'm not misremembering the issue, the lexical closure may always trigger recompilation due to the way things are memoized though.  (I would double-check this for you right now to make sure I'm not telling lies, but another bug is preventing me from verifying the actual cache behavior, lol.)

**Comment by botev** [comment]
So I can make a PR for wrapping the `broadcast_args` in `pmap` equivalently to how static argnums are wrapped (which I would assume will work similar to `jit`). E.g. with `_argnums_partial`.

Nevertheless, that has an issue compared to `jit` that still the different compilations of `pmap` (the ones that are expected for different static args) do some form of allocations each so I run out of memory on the 4th recompile. When I get the time I will do a self contained repro of that to raise a bug, but busy atm with other stuff.

**Comment by levskaya** [comment]
It would be interesting to see a repro for that OOM issue.  Does your computation by any chance have any large constants created inside it?

I also confirmed re: the above discussion that the current caching mechanism always treats the lexical closure lambda as a "new" function, so you hit re-compilation every time you evaluate, which is why that's a non-starter.

**Comment by botev** [comment]
I don't think that there are large constants, but not 100% sure. Is there any way to check the resulting function or jaxexpr for this?

**Comment by botev** [comment]
Something like this:
```
def pmap(fun, broadcast_argnums=(), axis_name=None, devices=None, backend=None):
  _check_callable(fun)
  axis_name = _TempAxisName(fun) if axis_name is None else axis_name
  if isinstance(broadcast_argnums, int):
    broadcast_argnums = (broadcast_argnums,)

  @wraps(fun)
  def f_pmapped(*args, **kwargs):
    f = lu.wrap_init(fun)
    if broadcast_argnums:
      dyn_argnums = [i for i in range(len(args)) if i not in broadcast_argnums]
      f, dyn_args = _argnums_partial(f, dyn_argnums, args)
    else:
      dyn_args = args
    args_flat, in_tree = tree_flatten((dyn_args, kwargs))
    axis_size = _pmap_axis_size(args_flat)
    _check_args(args_flat)
    flat_fun, out_tree = flatten_fun(f, in_tree)
    out = pxla.xla_pmap(flat_fun, *args_flat, axis_name=axis_name, axis_size=axis_size,
                        devices=tuple(devices) if devices is not None else devices,
                        backend=backend)
    return tree_unflatten(out_tree(), out)

  namestr = "pmap({}, axis_name={})".format
  f_pmapped.__name__ = namestr(f_pmapped.__name__, axis_name)
  return f_pmapped
```

**Comment by mattjj** [comment]
I think #1786 fixed this!
