### ISSUE TITLE
GPU not found

### ISSUE THREAD

**Issue by kenndshi** [google/jax#16753]
### Description

I am trying to use jax gpu.
I have installed tensorflow with gpu and it works.
After pip install --upgrade "jax[cuda11_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
I still get the same error, although I am using tensorflow 2.13.0 and it works fine.
Please help me to solve the error

**Comment by hawkinsp** [comment]
Please include the information requested by the bug template.

What does `nvidia-smi` output?

What version of CUDA and CUDNN do you have installed and how did you install them?

Can you try the `cuda11_pip` packages, which are much easier to install and install everything necessary but the CUDA driver?

**Comment by erfanzar** [comment]
To better understand your situation, could you please provide the following information:
1️⃣ What version of JAX and JAXlib are you currently using? This will help us identify any compatibility issues.
2️⃣ Which accelerator(s) are you utilizing? Knowing the specific GPU or other accelerators you're working with will aid in troubleshooting.
Once we have these details, we can proceed with finding a solution to the error you're experiencing. Additionally, if you could provide any additional system information, such as your operating system and hardware specifications, it would be helpful in diagnosing the problem.
Regarding the NVIDIA GPU information, if you could share details about your GPU model and driver version, it would assist us in understanding the hardware setup.
Please provide the requested information, and I'll do my best to help you resolve the error and get your JAX GPU integration up and running smoothly.

first, check for CuDnn and cuda versions for debugging and make sure that Jax currently supports cuda 11.8 the best

**Comment by hawkinsp** [comment]
Closing because no further information was provided.
