### ISSUE TITLE
Potential name conflict between `build/build.py` and https://pypi.org/project/build/

### ISSUE THREAD

**Issue by yhtang** [google/jax#16768]
### Description

https://github.com/google/jax/commit/f540ae4338baa87a06e4e3079e20b9543cb580e7 added `PyPI/build` as a dependency. Once the package is installed, `import build` in the `tests/` folder may no longer load `build.py`. This apparently is not causing trouble currently for Google, but is causing NVIDIA's [tests to fail](https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5574084801/jobs/10182227820#step:7:132) because it imports the `build.py` module. It may also contribute to potential errors in the future if people inadvertently try to reference the module.

What would be the recommended approach here to avoid confusion between the `build` package and the `build.py` module?

**Comment by hawkinsp** [comment]
Discussed offline. Importing `build.py` is an off-label use of JAX's build scripts: it's a program that we don't really intend you to import.

For the use case of "download bazel", I recommend bazelisk (https://github.com/bazelbuild/bazelisk) which should do the right thing.

Or you can just run `python build/build.py --configure_only`, which will download, configure, but not run `bazel`.
