### ISSUE TITLE
Adding events for `jax.experimental.ode.odeint`

### ISSUE THREAD

**Issue by dpanici** [google/jax#16774]
Might be a naive question, but I was wondering if it is possible to add events to `odeint`, that could also terminate integration early? 

I am dealing with integrations of magnetic field line trajectories which are either well-behaved and have confined trajectories, or have trajectories which diverge. I only care about the non-divergent trajectories, so I would like to be able to terminate the integration if the value of the function I am integrating (the position of the field line) becomes larger than some threshold, to avoid unnecessary computations.

I know scipy's ode [solve_ivp](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_ivp.html) has this functionality, but I am unsure if this type of conditional can be implemented in JAX

**Comment by adam-hartshorne** [comment]
Have you looked to see if the Diffrax library has this functionality? It is a feature-rich ODE/SDE solver library for JAX.

https://docs.kidger.site/diffrax/

**Comment by shoyer** [comment]
+1 I highly recommend using Diffrax instead.

**Comment by dpanici** [comment]
Ah I see it may have exactly what I am looking for, closing for now, thanks!
