### ISSUE TITLE
Multihost gather operation

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#16816]
Currently there exists `jax.experimental.multihost_utils.process_allgather`, but no `process_gather`.

I am running the script on TPU v4-16.

Example:

```python
import jax
from jax import Array
import jax.numpy as jnp
from jax.sharding import Mesh, NamedSharding, PartitionSpec as P
import numpy as np
from types import EllipsisType

def shard_array_to_multihost(arr: Array, axis: int | EllipsisType) -> Array:
    shape = arr.shape
    devices: np.ndarray = np.array(jax.devices())

    if axis is ...:
        mesh = Mesh(devices, ('a',))
        sharding = NamedSharding(mesh, P(None))
    else:
        sharding_tuple_ = [1] * len(shape)
        sharding_tuple_[axis] = -1
        sharding_tuple = tuple(sharding_tuple_)
        name_tuple = tuple('abcdefghijklmnopqrstuvwxyz'[:len(shape)])

        mesh = Mesh(devices.reshape(sharding_tuple), name_tuple)
        sharding = NamedSharding(mesh, P(*name_tuple))

    xs = [jax.device_put(arr[i], device) for device, i in sharding.addressable_devices_indices_map(shape).items()]
    return jax.make_array_from_single_device_arrays(shape, sharding, xs)

arr = jnp.arange(2 * 16 * 8).reshape((2, 16, 8))
arr = shard_array_to_multihost(arr, axis=2)

arr = jax.experimental.multihost_utils.process_allgather(arr)
if jax.process_index() == 0:
    print(arr)
```

However, what I want to achieve is:

```python
if jax.process_index() == 0:
    print(process_gather(arr))
```

**Comment by ayaka14732** [comment]
Besides, `jax.experimental.multihost_utils.process_allgather` returns a Numpy array instead of a JAX array. Why?

**Comment by yashk2810** [comment]
What does process_gather mean? If it means to gather all the local shards of the array then you can just write that on your own using `arr.addressable_shards`.

**Comment by ayaka14732** [comment]
Thank you! However, I think I cannot find the documentation of `arr.addressable_shards`. It is not included in https://jax.readthedocs.io/en/latest/_autosummary/jax.Array.html

**Comment by yashk2810** [comment]
I guess we need to fix that! Thanks for letting me know.

**Comment by azzeddineCH** [comment]
> Besides, `jax.experimental.multihost_utils.process_allgather` returns a Numpy array instead of a JAX array. Why?

when using this method within a jitted update method (syncing gradients across devices) it's failing for me with the following error `jax.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on traced array with shape float32[768,768].
`

**Comment by yashk2810** [comment]
You can only call `process_allgather` outside of a jitted function. Inside you can use `jax.lax` primitives for gathers or reducing across an axis.
