### ISSUE TITLE
Missing error if an integer is raised to a negative power

### ISSUE THREAD

**Issue by hylkedonker** [google/jax#16898]
### Description

It looks like that the exponentiation operation causes numerical overflow on 64 bit precision:
```python
from jax import config
config.update("jax_enable_x64", True)

import jax.numpy as jnp
10 ** (jnp.arange(0, 2) - 1)
```
Which gives the output: 
```
Array([-9223372036854775808,                    1], dtype=int64)
```

When I run the same code on single precision
```python
from jax import config
config.update("jax_enable_x64", False)

import jax.numpy as jnp
10 ** (jnp.arange(0, 2) - 1)
```
the code words as expected:
```
Array([0, 1], dtype=int32)
```

### What jax/jaxlib version are you using?

jax 0.4.14, jaxlib 0.4.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11.2, Ubuntu 23.04

### NVIDIA GPU info

N/A

**Comment by hawkinsp** [comment]
Note that this is an illegal operation (raising an integer to a negative power). If you try it in classic NumPy, you get:
```
In [8]: 10 ** (np.arange(0, 2) - 1)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[8], line 1
----> 1 10 ** (np.arange(0, 2) - 1)

ValueError: Integers to negative integer powers are not allowed.
```

JAX as a rule doesn't raise errors from operations, so you will get an implementation-defined value if you raise an integer to a negative power.

I think we're unlikely to change that behavior, but it probably should be documented.

**Comment by hylkedonker** [comment]
Thanks for clarifying!

**Comment by hai-dang-dau** [comment]
Yes, please add this to the documentation (still don't find it anywhere as of today).

In addition, I think it's reasonable to expect illegal operations like this to return `nan`, which would allow users to catch them via `jax_debug_nans` flag.

**Comment by jakevdp** [comment]
Note that as long as the power is a concrete integer, a TypeError is raised:
```python
In [1]: import jax.numpy as jnp

In [2]: jnp.power(2, -10)
TypeError: Integers cannot be raised to negative powers, got integer_pow(ShapedArray(int32[], weak_type=True), -10)
```
For a non-concrete negative integer power, the returned value will be implementation-defined.
