### ISSUE TITLE
AttributeError: module 'jax.numpy' has no attribute 'DeviceArray' on 0.4.14

### ISSUE THREAD

**Issue by jkosek** [google/jax#16902]
### Description

Using latest version of JAX library 0.4.14 cause errors on importing `DeviceArray` from `jax.numpy`. Seeme like there is API breaking change on patch version.

The library 0.4.13 works correctly.

### What jax/jaxlib version are you using?

0.4.14 

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10, Ubuntu 22.04

**Comment by hawkinsp** [comment]
That's correct, `DeviceArray` was deprecated in `jax` 0.4 and removed during the `0.4` series. So that's working as intended. Can you say more about why you need it? `jax.Array` replaced it.

**Comment by jkosek** [comment]
We are using a model implementation from HuggingFace and simply using latest version fails. If this is intentional is fine, just though it is an issue as patch version provide breaking change.

**Comment by hawkinsp** [comment]
JAX doesn't at the moment really use semver versioning (and the leading version is `0` anyway, so `semver` says "anything can change at any time" in this case), so "patch" releases can do this. However this particular API has been deprecated (and hopefully issuing a warning to you) for many months now.

I would follow up with the owner of the model (or whichever library was using the deprecated API). Hope that helps!

**Comment by jackyvava** [comment]
When using the jaxfluids library, which is a computational fluid dynamics library that requires JAX, I encountered a similar issue. I installed JAX and jaxlib with versions jax=0.4.14 and jaxlib=0.4.14, respectively. When running the examples, I faced the same problem as you did.

I took a bold approach by using PyCharm's "Replace in file" feature and replaced all instances of jnp.DeviceArray with jnp.Array. This ultimately resolved the issue for me.

finally，success。

**Comment by Yang-Xijie** [comment]
You may change `jax.numpy.DeviceArray` to `jax.numpy.array`.

**Comment by 623851394** [comment]
> You may change `jax.numpy.DeviceArray` to `jax.numpy.array`.

good

**Comment by hawkinsp** [comment]
For posterity, I'll note the advice these days would be: "You may change `jax.numpy.DeviceArray` to `jax.Array` or `jax.numpy.ndarray`". `jax.numpy.array` is a function, whereas `jax.numpy.ndarray` is a type, which is an alias for `jax.Array`.
