### ISSUE TITLE
Possible BUG: Different behavior of 64-bit integers when used inside Sharding ops

### ISSUE THREAD

**Issue by yashjha123** [google/jax#16903]
### Description

Hey,
I'm trying to vmap a function over a sharded integer array. The arrays are distributed over 8 TPU cores and have divisible dimensions. In the code below, when I run the function, ``jax.vmap(simple_op)`` with an int8 array, I get the following output.
```python
import jax
import jax.numpy as jnp


from jax.experimental import mesh_utils
from jax.sharding import PositionalSharding
sharding8 = PositionalSharding(mesh_utils.create_device_mesh((8,)))
viz = jax.debug.visualize_array_sharding

a = jnp.arange(64,dtype=jnp.uint8)
a = jax.device_put(a,sharding8)

def simple_op(a):
    return a+1

out = jax.vmap(simple_op)(a)

```
<img src="https://github.com/google/jax/assets/53092553/cffeb859-fa0f-4ae4-a0ba-a64999e18a17" height="100" />

However, when I use ``jnp.uint64`` instead. I get a different result

<img src="https://github.com/google/jax/assets/53092553/59b8b60c-333e-460b-b0a0-073c78e6da0a" height="100" />

The corresponding code 
```python
jax.config.update("jax_enable_x64", True)
a = jnp.arange(64,dtype=jnp.int64)
a = jax.device_put(a,sharding8)
out = jax.vmap(simple_op)(a)
```
This is a very strange bug. What could be the possible cause? 

### What jax/jaxlib version are you using?

jax==0.4.6, jaxlib==0.4.6

### Which accelerator(s) are you using?

TPU

### Additional system info

Python 3.8.16 (Kaggle Environment)

**Comment by yashk2810** [comment]
Can you upgrade to the latest jax and jaxlib versions and see if you can still repro it?
