### ISSUE TITLE
arithmetic operations not implemented for BCSR

### ISSUE THREAD

**Issue by jiachenguoNU** [google/jax#16922]
I'm writing a scientific computing code using jax. Now I'm using the scipy.sparse.csr_matrix to first create the csr matrix and then transform it into jax using BCOO.from_scipy_sparse() method (but it's very slow now). If I directly using the BCSR matrix implemented in jax, I have to compute the submatrix step by step and then add them up since the size of the sparse matrix is large (1 billion nonzero terms), 

I checked the source code of BCSR and it seems the arithmetic operations are not implemented. Could you kindly add this feature in jax?

**Comment by jakevdp** [comment]
Sure, we could take a look at that. Could you show an example of the types of operations you have in mind?

**Comment by jiachenguoNU** [comment]
Hi Jake:

Thanks for the quick reply. I'm thinking if jax can provide these functionalities similar to scipy.sparse.csr_matrix.

(1) Efficient arithmetic operations:

BCSR + BCSR, BCSR * BCSR, etc.

(2) Defining BCSR with the coordinates

BCSR((data, (row_ind, col_ind)), [shape=(M, N)])
where data, row_ind and col_ind satisfy the relationship a[row_ind[k], col_ind[k]] = data[k].

**Comment by jakevdp** [comment]
The workaround for now would be (1) convert to BCOO, (2) do the desired operation, (3) convert back to BCSR. Any “native” support for these kinds of operations would essentially look like that under the hood.

**Comment by jakevdp** [comment]
OK - do you have suggestions for how `+` could be implemented for BCSR using available XLA operations? I don't know any other way to do it.

For what it's worth, issues like these are why `jax.experimental.sparse` remains experimental.

**Comment by jiachenguoNU** [comment]
OK thank you

**Comment by jakevdp** [comment]
Closing, as I don't think there's anything actionable here at the moment.
