### ISSUE TITLE
[sparse] Feature request: add grad support to experimental.sparse.linalg.spsolve

### ISSUE THREAD

**Issue by Alessio-Amaolo** [google/jax#16935]
`experimental.sparse.linalg.spsolve` is implemented via the [`cuda_csrlsvqr` routine](https://github.com/google/jax/blob/7708cf5c21e3296d0a607125f8686d5a9712c1ca/jaxlib/gpu_solver.py#L258). If I am not mistaken, the gradient should be computable (GPU only) with another call to `spsolve`.

**Comment by patrick-kidger** [comment]
FWIW you should be able to do this by wrapping into a `lineax.AbstractSolver`. ([Lineax is here](https://github.com/google/lineax).) This automatically synthesises the backward pass given just the forward solve.

**Comment by jakevdp** [comment]
Out of curiosity, how do you automatically construct the transpose rule for an abstract solver if no transpose solver is available?

**Comment by patrick-kidger** [comment]
Transposition is handled as a property of the operator, rather than the solver. I.e. we basically just do `linear_solve(operator.transpose(), solver, ...)`.

**Comment by jakevdp** [comment]
Makes sense, thanks!

**Comment by patrick-kidger** [comment]
> Makes sense, thanks! Since spsolve_p does not provide any built-in transpose solve, it sounds like a simple lineax wrapper would not be sufficient to make it work with a backward pass.

I think it should. It's the *matrix* that is transposed, not the solver.

**Comment by patrick-kidger** [comment]
> Makes sense, thanks! Since spsolve_p does not provide any built-in transpose solve, it sounds like a simple lineax wrapper would not be sufficient to make it work with a backward pass.

I think it should. It's the *matrix* that is transposed, not the solver.

**Comment by jakevdp** [comment]
Agreed, I used "transpose solve" as a shorthand for "transpose the matrix and then solve", sorry that wasn't clear.

The issue is that this primitive takes a CSR representation as the input, and unlike COO there's no trivial way to transpose a CSR representation without calling out to some other kernel. Some solvers have a transpose flag built-in to handle this case, but `spsolve_p` does not.

**Comment by patrick-kidger** [comment]
Right, I see! I hadn't fully appreciated that (a) `spsolve` only accepts CSR, and that (b) the transpose rule for a `CSR` matrix wasn't already defined (due to it being so inefficient).
