### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: batch in most minor dimension

### ISSUE THREAD

**Issue by alberthli** [google/jax#16991]
### Description

I recently upgraded my JAX versions in a project from `jax` v0.4.10 and `jaxlib` v0.4.10+cuda11.cudnn86 to `jax` v0.4.14 and `jaxlib` v0.4.14+cuda11.cudnn86 and started seeing the following error on a piece of jitted code:
```
jaxlib.xla_extension.XlaRuntimeError: UNIMPLEMENTED: batch in most minor dimension
```
Unfortunately, I haven't been able to put together a minimal reproducible example and there are a lot of moving parts to the code, but I have noted the following behavior:

1. The code runs without error on CPU - it is only a problem on GPU.
2. When commenting out the return value of the function in question, the code runs without error:
```
@jit
def f(args):
    # many lines of code
    # return value  # when this is commented out, the code JIT compiles and runs without error
```
After bisecting on JAX versions, I've found that the error starts afflicting all versions >=0.4.11. What are some possible causes or further directions to look that might help yield a minimal reproducible example or fix?

### What jax/jaxlib version are you using?

Working on 0.4.10/0.4.10+cuda11.cudnn86, not working on all versions >=0.4.11/>=0.4.11+cuda11.cudnn86

### Which accelerator(s) are you using?

CPU and GPU

### Additional system info

Python 3.10.12, Ubuntu 22.04

### NVIDIA GPU info

Tested on two different machines. The output of `nvidia-smi` on each is

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               On  | 00000000:01:00.0 Off |                  Off |
| 72%   86C    P2             287W / 300W |  45861MiB / 49140MiB |    100%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A6000               On  | 00000000:02:00.0 Off |                  Off |
| 68%   85C    P2             296W / 300W |  38173MiB / 49140MiB |     99%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```
and
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.30.02              Driver Version: 530.30.02    CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090         On | 00000000:41:00.0 Off |                  Off |
|  0%   46C    P8               32W / 450W|    647MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA GeForce RTX 4090         On | 00000000:42:00.0 Off |                  Off |
|  0%   50C    P8               25W / 450W|     17MiB / 24564MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
```
I'm running the code in a conda environment with `cuda-toolkit` v11.8 as some of the dependencies of this project are not compatible with Cuda 12.

**Comment by yashk2810** [comment]
Can you provide a minimal repro please?

**Comment by dehorsley** [comment]
I'm getting the same issue. I've managed to reduce it down to this:

```
import jax
import jax.numpy as jnp

def f(x):
    C = jnp.zeros((10,10))
    C = C.at[jnp.triu_indices(10)].set(x)
    A = jnp.dot(C,C.T)
    return A

@jax.jit
def g(x):
    return jax.vmap(jax.vmap(f))(x)

x = jnp.ones((10,3,55))
g(x)
```

Throws 
```
XlaRuntimeError: UNIMPLEMENTED: batch in most minor dimension
```


Confirmed it occurs on my local machine and on Colab. The code works with CPU, but breaks on GPU. Also works if the jit is removed.

**Comment by alberthli** [comment]
Thanks for putting together the minimal repro! I hadn't found the time to get around to it. I can confirm that this snippet throws the error on both machines tested above under the same conditions on version 0.4.14 (works without JIT on GPU, works on CPU with JIT, breaks with JIT on GPU).

**Comment by dehorsley** [comment]
No worries, it's been on my list for a while too. 

Note I'm able to work-around this by flattening the batch dimensions. I.e. something like:

```
@jax.jit
def g(x):
    y = x.reshape(-1,x.shape[-1])
    z = jax.vmap(f)(y)
    return z.reshape(x.shape[:-1])
```

**Comment by hawkinsp** [comment]
I filed an XLA bug (https://github.com/openxla/xla/issues/4833).

**Comment by ameya98** [comment]
I still have this issue, even though the XLA bug seems to be resolved.

**Comment by hawkinsp** [comment]
That's correct. The issue is fixed at jax head, but you'll need to either build `jaxlib` from source or wait until we make a new release. I suspect we'll make a new release this week, as it happens.

Hope that helps!
