### ISSUE TITLE
Same functions but not same result

### ISSUE THREAD

**Issue by erfanzar** [google/jax#17121]
## Different results in Jax and torch and Numpy on CPU/TPU and GPU

this is the function that I'm using to find are two arrays different or no
```python
def is_same(t1, t2):
    for t1_, t2_ in zip(t1.reshape(-1), t2.reshape(-1)):
        if not t1_ == t2_:
            return False
    return True   
 ```
and this is the function that I'm trying to recreate from Torch (RoPE)
and the part that my code is getting error or different results in calculating sin and cos and freq if you do the same as what iv done in jax for original numpy you wont get any error or False results 

```python
base_torch = 1. / (10000. ** (torch.arange(0, 64, 2, dtype=torch.float32) / 64))
base_jax = 1. / (10000. ** (jnp.arange(0, 64, 2, dtype=jnp.float32) / 64))
t_t = torch.arange(64)
j_t = jnp.arange(64)


einsum_torch = torch.einsum('i,j->ij', t_t, base_torch)
einsum_jax = jnp.einsum('i,j->ij', j_t, base_jax)

# is_same(einsum_jax, einsum_torch.detach().numpy()) -> True

freq_torch = torch.cat([einsum_torch, einsum_torch], dim=-1)
freq_jax = jnp.concatenate([einsum_jax, einsum_jax], axis=-1)

# is_same(freq_jax, freq_torch.detach().numpy()) -> True

sin_jax = jnp.sin(freq_jax)
cos_jax = jnp.cos(freq_jax)

sin_torch = torch.sin(freq_torch)
cos_torch = torch.cos(freq_torch)

# is_same(sin_jax, sin_torch.detach().numpy()) -> False
# is_same(cos_jax, cos_torch.detach().numpy()) -> False
```

### What jax/jaxlib version are you using?

jax/jaxlib v0.4.13

### Which accelerator(s) are you using?

CPU/GPU/TPU

### Additional system info

Linux Ubuntu 22.04 LTS

### NVIDIA GPU info

GPU = [RTX 3080](https://www.nvidia.com/de-de/geforce/graphics-cards/30-series/rtx-3080-3080ti/)
Cuda 11.8
driver 530
CPU = [Intel® Core™ i7-9700K](https://www.intel.com/content/www/us/en/products/sku/186604/intel-core-i79700k-processor-12m-cache-up-to-4-90-ghz/specifications.html)
TPU = Kaggle TPUs

**Comment by jakevdp** [comment]
Thanks for the question! I think this is working as expected. In general, using exact equality checks for floating point computations is an anti-pattern: floating point operations are inexact representations of real numbers, and so will always have some degree of rounding error. This is not a JAX-specific thing: this is true of any library that uses floating point (which includes jax, torch, numpy, and almost all other modern computing frameworks)

To compare equivalent floating point outputs, you need to account for this computation error. One function you could use for this is [`numpy.allclose`](https://numpy.org/doc/stable/reference/generated/numpy.allclose.html), and indeed if you replace `is_same` with `numpy.allclose`, you'll see that the results in your code match.

For a good practical read on rounding errors in floating point math, I'd check out this StackOverflow answer: [Is Floating Point Math Broken?](https://stackoverflow.com/q/588004).

**Comment by erfanzar** [comment]
thanks<3
