### ISSUE TITLE
jax2tf: support mixed-precision inputs to `dot_general`

### ISSUE THREAD

**Issue by jakevdp** [google/jax#17151]
This is the issue that led to the rollback in https://github.com/google/jax/pull/17150, because `jnp.einsum` started to lower to mixed-precision `dot_general` and broke downstream code.

Minimal repro:
```python
import jax
import numpy as np
from jax.experimental import jax2tf

x = np.ones(4, dtype=bool)
y = np.ones(4, dtype='int32')

print(jax.lax.dot(x, y))
# 4

print(jax2tf.convert(jax.lax.dot)(x, y))
# InvalidArgumentError: Value for attr 'LhsT' of bool is not in the list of allowed values...
```
Depending on the serialization mode, this may also affect other mixed types; e.g.
```python
x = np.ones(4, dtype='int8')
y = np.ones(4, dtype='float32')

print(jax.lax.dot(x, y))
# 4.0

print(jax2tf.convert(jax.lax.dot, enable_xla=False, native_serialization=False)(x, y))
# InvalidArgumentError: Value for attr 'T' of int8 is not in the list of allowed values:...
```

**Comment by gnecula** [comment]
There seem indeed to be a problem with the non-native jax2tf, but starting with #16749 most people use native serialization, which does not have this problem. (@jakevdp please check your local setup for running the above example if the `jax2tf_default_native_serialization` config flag is set to True).

I might not fix the non-native serialization behavior because most users should switch aware from it (will investigate the internal test failures).

**Comment by jakevdp** [comment]
Thanks for the fix @necula!

It looks like there's one more related issue where `jax2tf` errors on code that executes correctly in XLA. The issue arises in non-native serialization when `preferred_element_type` is narrower than the inputs:
```python
import jax
from jax.experimental import jax2tf

x = jax.numpy.ones(4, dtype='int32')
y = jax.numpy.ones(4, dtype='float16')

func = lambda x, y: jax.lax.dot(x, y, preferred_element_type='float16')

print(func(x, y))
# 4.0

print(jax2tf.convert(func, enable_xla=False, native_serialization=False)(x, y))
# tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute MatMul as
# input #1(zero-based) was expected to be a int32 tensor but is a half tensor
```

**Comment by jakevdp** [comment]
Sorry, I just realized this new repro does not actually hit the new problem... I'll try to come up with a better one
