### ISSUE TITLE
The docs for hard_swish describe hard_silu instead

### ISSUE THREAD

**Issue by jshepherd01** [google/jax#17171]
### Description

https://jax.readthedocs.io/en/latest/_autosummary/jax.nn.hard_swish.html

The description is identical to that for the hard_silu function (the previous page) rather than being a description of hard_swish

**Comment by hawkinsp** [comment]
They are actually aliases of one another, so this is somewhat intentional. ("swish" and "silu" are names for the same thing from different authors.) We could clearly improve the docs to make it clear they are aliases, though.
