### ISSUE TITLE
Support FP8 GEMM kernels which are already support in OpenXLA.

### ISSUE THREAD

**Issue by MoFHeka** [google/jax#17176]
Please:

Support FP8 GEMM kernels which are already support in OpenXLA. 

When I ran nsys profiler the code below, I found there are all `sm90_xmma_gemm_f16f16_f16f32_f32_nn_n_tilesize128x256x32_warpgroupsize2x1x1_execute_segment_k_off_kernel__5x_cublas` kernels when calculate dense layer. It should be fp8 tensor core kernel which is already supported in cublas and OpenXLA, but not running fp16 kernel and then convert data type.

Test code:
```python
import time
import jax
import jax.numpy as jnp
import flax

# dtype=jnp.float8_e4m3fn
dtype=jnp.float8_e5m2

a = jnp.ones((4096,4096*8),dtype=dtype)
ram_kernel_init=lambda key,shape,dtype:jax.nn.initializers.normal()(key,shape,jnp.float32).astype(dtype)
dense=flax.linen.Dense(5120*16, use_bias=False, dtype=dtype, param_dtype=dtype, kernel_init=ram_kernel_init)
w = dense.init(jax.random.PRNGKey(0), a)
dense.apply(w,a)

start = time.time()
for i in range(2):
    dense.apply(w,a)
end = time.time()
print("time: ", end-start)

def f(x): return dense.apply(w,x)
impl = jax.xla_computation(f)(a)
print(impl.as_hlo_text())
```

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by hawkinsp** [comment]
I tried this at head. If you use the e4m3fn type for at least one argument to the matmul, you get an fp8 kernel on H100. You won't get one if you use e5m2 for both arguments to the matrix: cublas doesn't support e5m2 x e5m2 matmuls.

I think we can declare this fixed!
