### ISSUE TITLE
Jaxlib fails to build from source on Windows

### ISSUE THREAD

**Issue by Sha-x2-nk** [google/jax#17174]
### Description

Here's the complete output

(dljax) C:\Users\shash\jax>python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2" --cuda_version="12.2" --cudnn_version="8.9.4"

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\

Bazel binary path: C:\bazel\bazel.EXE
Bazel version: 6.3.2
Python binary path: C:/Users/shash/.conda/envs/dljax/python.exe
Python version: 3.9
NumPy version: 1.25.2
MKL-DNN enabled: yes
Target CPU: AMD64
Target CPU features: release
CUDA enabled: yes
CUDA toolkit path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2
CUDNN library path: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2
CUDA version: 12.2
CUDNN version: 8.9.4
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
C:\bazel\bazel.EXE run --verbose_failures=true //jaxlib/tools:build_wheel -- --output_path=C:\Users\shash\jax\dist --cpu=AMD64
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from c:\users\shash\jax\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/shash/.conda/envs/dljax/python.exe
INFO: Reading rc options for 'run' from c:\users\shash\jax\.bazelrc:
  Inherited 'build' options: --nocheck_visibility --apple_platform_type=macos --macos_minimum_os=10.14 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true --define=tsl_link_protobuf=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir. --@xla//xla/python:enable_gpu=false --@xla//xla/python:enable_tpu=false
INFO: Reading rc options for 'run' from c:\users\shash\jax\.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=C:/Users/shash/.conda/envs/dljax/python.exe --action_env=PYENV_ROOT --python_path=C:/Users/shash/.conda/envs/dljax/python.exe --action_env CUDA_TOOLKIT_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2 --action_env CUDNN_INSTALL_PATH=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2 --action_env TF_CUDA_PATHS=C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v12.2 --action_env TF_CUDA_VERSION=12.2 --action_env TF_CUDNN_VERSION=8.9.4 --config=mkl_open_source_only --config=cuda
INFO: Found applicable config definition build:short_logs in file c:\users\shash\jax\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file c:\users\shash\jax\.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file c:\users\shash\jax\.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=sm_52,sm_60,sm_70,sm_80,compute_90 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --@xla//xla/python:enable_gpu=true --@xla//xla/python:jax_cuda_pip_rpaths=true --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:windows in file c:\users\shash\jax\.bazelrc: --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --incompatible_strict_action_env=trueDEBUG: C:/users/shash/_bazel_shash/b3x3rdg2/external/xla/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'tf_runtime' because it already exists.
DEBUG: C:/users/shash/_bazel_shash/b3x3rdg2/external/xla/third_party/repo.bzl:132:14:
Warning: skipping import of repository 'llvm-raw' because it already exists.
WARNING: Download from https://mirror.bazel.build/github.com/bazelbuild/rules_cc/archive/081771d4a0e9d7d3aa0eed2ef389fa4700dfb23e.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/pybind/pybind11_abseil/archive/2c4932ed6f6204f1656e245838f4f5eae69d2e29.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/abseil/abseil-cpp/archive/b971ac5250ea8de900eae9f95e06548d14cd95fe.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/re2/archive/03da4fc0857c285e3a26782f6bc8931c4c950df4.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/openxla/triton/archive/cl547802044.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/openxla/stablehlo/archive/5aa1adeb2a412d1aca8972385cd9b26b1a524052.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/NVIDIA/cudnn-frontend/archive/refs/tags/v0.9.zip failed: class java.io.FileNotFoundException GET returned 404 Not Found
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/google/boringssl/archive/c00d7ca810e93780bd0c8ee4eea28f4f2ea4bcdc.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
INFO: Analyzed target //jaxlib/tools:build_wheel (220 packages loaded, 18304 targets configured).
INFO: Found 1 target...
ERROR: C:/users/shash/_bazel_shash/b3x3rdg2/external/flatbuffers/BUILD.bazel:84:10: Linking external/flatbuffers/flatc.exe [for tool] failed: (Exit 1120): link.exe failed: error executing command (from target @flatbuffers//:flatc)
  cd /d C:/users/shash/_bazel_shash/b3x3rdg2/execroot/__main__
  SET INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt
    SET LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.22621.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.22621.0\\um\x64
    SET PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;;C:\Windows\system32;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\shash\AppData\Local\Temp
    SET TMP=C:\Users\shash\AppData\Local\Temp
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\link.exe @bazel-out/x64_windows-opt-exec-50AE0418/bin/external/flatbuffers/flatc.exe-2.params
# Configuration: d960a019c29abfe37a18e15ad5a5dad5a3057c532cbeb0efbd45b2fd0b0808a3
# Execution platform: @local_execution_config_platform//:platform
Target //jaxlib/tools:build_wheel failed to build
INFO: Elapsed time: 222.900s, Critical Path: 26.63s
INFO: 782 processes: 430 internal, 352 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
b'LINK : warning LNK4001: no object files specified; libraries used\r\nLINK : error LNK2001: unresolved external symbol mainCRTStartup\r\nbazel-out\\x64_windows-opt-exec-50AE0418\\bin\\external\\flatbuffers\\flatc.exe : fatal error LNK1120: 1 unresolved externals\r\n'
Traceback (most recent call last):
  File "C:\Users\shash\jax\build\build.py", line 559, in <module>
    main()
  File "C:\Users\shash\jax\build\build.py", line 554, in main
    shell(command)
  File "C:\Users\shash\jax\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\shash\.conda\envs\dljax\lib\subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\shash\.conda\envs\dljax\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\bazel\\bazel.EXE', 'run', '--verbose_failures=true', '//jaxlib/tools:build_wheel', '--', '--output_path=C:\\Users\\shash\\jax\\dist', '--cpu=AMD64']' returned non-zero exit status 1.

**Comment by hawkinsp** [comment]
Windows builds are community supported.

I'll note that jaxlib built fine in the most recent CI run from today: https://github.com/google/jax/actions/workflows/windows_ci.yml

Can you try building from a checkout at github head?

**Comment by Sha-x2-nk** [comment]
Hey there. Thank you very much for replying. Can you please tell me what is
this flatc.exe error and how to correct it.

**Comment by hawkinsp** [comment]
`flatc` is a binary built as part of the jaxlib build process.

Did you try from github head, as I already suggested?

**Comment by hawkinsp** [comment]
I also strongly recommend installing a binary release of JAX, rather than building it yourself. I'm not sure that CUDA support even builds on Windows right now, for what its worth. So it's CPU-only or nothing.

**Comment by Sha-x2-nk** [comment]
I'm sorry but I don't understand what is meant by checking out by github
head.  Can you please explain

**Comment by hawkinsp** [comment]
Please use a binary release of jaxlib (`pip install jax[cpu]`). Hope that helps!
