### ISSUE TITLE
`jnp.tan` and `jnp.arccos` give incorrect values for certain complex numbers

### ISSUE THREAD

**Issue by jshepherd01** [google/jax#17172]
### Description

For example, using numpy as the baseline (which agrees with other frameworks and with WolframAlpha)
```py
In [1]: import jax.numpy as jnp

In [2]: import numpy as np

In [3]: jnp.tan(-1.-45.j)
No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Out[3]: Array(-0.-0.j, dtype=complex64, weak_type=True)

In [4]: np.tan(np.array(-1.-45.j, dtype=np.complex64))
Out[4]: (-1.490159e-39-1j)

In [5]: jnp.arccos(-1-4500j)
Out[5]: Array(0.+8.227262j, dtype=complex64, weak_type=True)

In [6]: np.arccos(np.array(-1-4500j, dtype=np.complex64))
Out[6]: (1.5710186+9.1049795j)
```

### What jax/jaxlib version are you using?

jax v0.4.13, jaxlib v0.4.13

### Which accelerator(s) are you using?

CPU only

### Additional system info

Python 3.8.10, IPython 8.12.2, WSL with Ubuntu 20.04.5 LTS

**Comment by hawkinsp** [comment]
For `tan` at least, I suspect this is a precision problem. If you enable x64 types in JAX:
```
In [12]: jax.config.update('jax_enable_x64', True)

In [13]: jnp.tan(-1.-45.j)
Out[13]: Array(-1.49015892e-39-1.j, dtype=complex128, weak_type=True)
```

So it's possible either the formulation `jax` is using for the tangent is less numerically stable than how NumPy calculates it, or it's possible that NumPy is doing the calculation in 64-bit arithmetic always.

**Comment by rajasekharporeddy** [comment]
Hi @jshepherd01 

Issues with inaccuracies in `jnp.tan` and `jnp.arccos` for complex-valued inputs have been resolved in https://github.com/openxla/xla/pull/10525 and https://github.com/openxla/stablehlo/pull/2411, respectively. I tested this with JAX version 0.4.31, and can confirm that `tan` and `arccos` in JAX now produce consistent results with NumPy for complex data types.

```python
import jax.numpy as jnp

import numpy as np

print("JAX tan: ", jnp.tan(-1.-45.j))
print("NumPy tan: ", np.tan(np.array(-1.-45.j, dtype=np.complex64)))
print("Is JAX consistent with NumPy: ", jnp.allclose(jnp.tan(-1.-45.j), np.tan(np.array(-1.-45.j, dtype=np.complex64))))

print("JAX arccos: ", jnp.arccos(-1-4500j))
print("NumPy arccos: ", np.arccos(np.array(-1-4500j, dtype=np.complex64)))
print("Is JAX consistent with NumPy: ", jnp.allclose(jnp.arccos(-1-4500j), np.arccos(np.array(-1-4500j, dtype=np.complex64))))
```

Output:
```
JAX tan:  (-0-1j)
NumPy tan:  (-1.490159e-39-1j)
Is JAX consistent with NumPy:  True
JAX arccos:  (1.5710186+9.1049795j)
NumPy arccos:  (1.5710186+9.1049795j)
Is JAX consistent with NumPy:  True
```

Attaching [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/729d35fb23ca956d6e830910d6244731/-17172.ipynb) for reference.

Thank you

**Comment by pearu** [comment]
@rajasekharporeddy , thanks for checking! Closing the issue as resolved.
