### ISSUE TITLE
Numerically inaccurate `scipy.stats.norm.sf`

### ISSUE THREAD

**Issue by Gattocrucco** [google/jax#17199]
### Description

Since a distribution cdf's goes asymptotically to 1 as $x \to \infty$, computing it numerically rounds to 1 at a certain point. For this reason, distributions in `scipy.stats` also provide the method `sf = 1 - cdf` that retains the precision.

I was about to use `jax.scipy.stats.norm.sf`, but I noticed that it is not accurate:

```python
from jax.scipy import stats as jstats
from scipy import stats
import numpy as np

value = np.array(10, np.float32)
print('scipy:', stats.norm.sf(value))
print('jax:', jstats.norm.sf(value))
```

```
scipy: 7.61985302416047e-24
jax: 0.0
```

Indeed, looking at the code, the implementation just does `1 - cdf`:

```python
@_wraps(osp_stats.norm.sf, update_doc=False)
def sf(x: ArrayLike, loc: ArrayLike = 0, scale: ArrayLike = 1) -> Array:
  cdf_result = cdf(x, loc, scale)
  return lax.sub(_lax_const(cdf_result, 1), cdf_result)
```

For the normal distribution, one can use `sf(x) = cdf(-x)`. I have not looked at what jax is doing for other distributions.

### What jax/jaxlib version are you using?

0.4.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11.2, macOS 13.4

**Comment by jakevdp** [comment]
Thanks for the report! #17204 fixes this for `norm.sf`; I'll look into similar fixes for the other distributions as well.
