### ISSUE TITLE
JAX dtype conversion seems incorrect

### ISSUE THREAD

**Issue by YingHH1** [google/jax#17198]
### Description

for a floating point number -1.6171875.

x=jax.numpy.asarray([-1.6171875],dtype=jax.numpy.float32)

if you use astype bf16:
x.astype(jax.numpy.bfloat16)
DeviceArray([-1.61719], dtype=bfloat16)

or astype fp16:
x.astype(jax.numpy.float16)
DeviceArray([-1.617], dtype=float16)

Both of them seem incorrect for IEEE754 floating point format. For -1.6171875, both fp16 and bf16 truncation should result in the same float as the extra mantissa bits in fp32 are all zeros: -1.6171875 in binary is '10111111110011110000000000000000'

Of course, it is possible that I was not using the correct way to do dtype conversion in Jax. If someone could point me in the right direction?

**Comment by samblouir** [comment]
Interestingly, this appears to be even worse in Torch.


I just tested this with these versions: 

> jax==0.4.14
> jaxlib==0.4.14+cuda12.cudnn89
> 
> numpy==1.23.1
> 
> torch==2.1.0.dev20230819+cu121
> torchaudio==2.1.0.dev20230820+cu121
> torchvision==0.16.0.dev20230820+cu121

>   jax.devices(): [gpu(id=0)] # An NVIDIA 3090, CUDA 12.1
>
>   x: [-1.6171875]
>
>    jnp.float32(x): [-1.6171875]
>   jnp.bfloat16(x): [-1.61719]
>    jnp.float16(x): [-1.617]
>
>   np.float32(x): [-1.6171875]
>   np.float16(x): [-1.617]
>
>   torch.float32(x): tensor([-1.6172])
>   torch.float16(x): tensor([-1.6172], dtype=torch.float16)
>   torch.bfloat16(x): tensor([-1.6172], dtype=torch.bfloat16)

However, the issue only appears to affect the bf16 datatype, when x is not an array.


>   x: -1.6171875
>
>   jnp.float32(x): -1.6171875
>   jnp.bfloat16(x): -1.61719
>    jnp.float16(x): -1.6171875
>
>   np.float32(x): -1.6171875
>   np.float16(x): -1.6171875
>
>   torch.float32(x): -1.6171875
>   torch.float16(x): -1.6171875
>   torch.bfloat16(x): -1.6171875

**Comment by jakevdp** [comment]
I think the conversion is working as expected, but the default decimal representation is misleading. Taking a look at the bits, it's clear that bf16 maintains the original bit pattern as expected (i.e. chopping off the extra mantissa bits compared to f32):
```python
import jax

x = jax.numpy.asarray([-1.6171875],dtype=jax.numpy.float32)
print(jax.numpy.unpackbits(x.view('uint8')))
# [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1]

x_bf16 = x.astype('bfloat16')
print(jax.numpy.unpackbits(x_bf16.view('uint8')))
# [1 1 0 0 1 1 1 1 1 0 1 1 1 1 1 1]

x_f16 = x.astype('float16')
print(jax.numpy.unpackbits(x_f16.view('uint8')))
# [0 1 1 1 1 0 0 0 1 0 1 1 1 1 1 0]
```
You can confirm that the casts do not lose precision by casting back to the original type and finding that it is bitwise equal:
```python
print(x_bf16.astype('float32') == x)
# [ True]

print(x_f16.astype('float32') == x)
# [ True]
```

**Comment by YingHH1** [comment]
Thank you for confirming the behaviour. Is there a way to change the default decimal representation? Since I would like to compare intermediate results with torch, but I found it difficult this way.

**Comment by jakevdp** [comment]
JAX printing is outsourced to NumPy, so it can be controlled using numpy's [`printoptions`](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html).
