### ISSUE TITLE
bf16 * int8 matmul results in incorrect value

### ISSUE THREAD

**Issue by YingHH1** [google/jax#17214]
### Description
```
# Let us define a bf16 array and an int8 array:

X=jnp.array([[-1.6171875,0.5703125]],dtype=jax.numpy.bfloat16)
W=jnp.array([[127],[-4]],dtype=jax.numpy.int8)

# perform matrix multiplication:
jax.numpy.matmul(X,W,precision=jax.lax.Precision.HIGHEST)
DeviceArray([[-208]], dtype=bfloat16)


# However, if we manually do the multiplication:
X[0,0]*W[0,0]
DeviceArray(-205, dtype=bfloat16)
X[0,1]*W[1,0]
DeviceArray(-2.28125, dtype=bfloat16)
X[0,0]*W[0,0]+X[0,1]*W[1,0]
DeviceArray(-207, dtype=bfloat16)

# That is -207 which is different to -208 from the matmul function. 
```
I have been trying to find a DL framework that does bf16 and int8 matrix multiplication, so far only Jax supports it, but it seems to have this rounding issue at the moment.

### What jax/jaxlib version are you using?

0.3.20+cuda11.cudnn82

### NVIDIA GPU info

A100

**Comment by jakevdp** [comment]
Thanks for the question! I believe this is working as expected: you're doing math at `bfloat16` precision, and `bfloat16` only has 7 bits of mantissa, meaning that you should generally expect numerical results to be good to within roughly one part in $2^7$.

Doing this computation in `float32` reveals the "true" result:
```python
X.astype('float32') @ W.astype('float32')
# Array([[-207.66406]], dtype=float32)
```
In `bfloat16`, you got `-208`, which is actually the closest bfloat16-representable value to the true answer. You can see this by using the `jnp.nextafter` function to see what the next representable value is:
```python
print(jnp.nextafter(jnp.bfloat16(-208), jnp.bfloat16(0)))
# -207
```
The next bfloat16-representable value greater than `-208` is `-207`, so it's clear that `-208` is the best possible bfloat16 representation of the answer to your computation.

**Comment by YingHH1** [comment]
Great, thank you for the help!

**Comment by YingHH1** [comment]
I guess this implies that matmul internally converts the bf16/int8 arrays to fp32 for both multiplication and accumulation? i.e.
y=x1.float32()@W1.float32()+x2.float32()@W2.float32()+...

but this means we cast everything to fp32 such that the acceleration from low-bit computation is lost. Thus, what I would have expected is:
y=(x1@W1).float32()+(x2@W2).float32()+...

I am unfamiliar with A100's internal instruction, but I would have thought the bf16/int8 matrix multiplication is performed in low-bit for mul and high-bit for add, in order to reduce accumulation error whilst maintaining a performance edge.

**Comment by jakevdp** [comment]
The implementation of bfloat16 matmul is hardware-specific, and I’m not sure of the details on A100.
