### ISSUE TITLE
memory leak when calling odeint

### ISSUE THREAD

**Issue by Roger-luo** [google/jax#17232]
### Description

I managed to make the following MWE

```python
import jax.numpy as jnp
from jax.experimental.ode import odeint

while True:
    vector_field = lambda y, t: -y
    sol = odeint(vector_field, jnp.asarray(1.0), jnp.asarray([0., 1., 2., 3.]))
```

and you can see the memory usage keep growing, while scipy.odeint has no such issue

```python
from scipy.integrate import odeint

while True:
    vector_field = lambda y, t: -y
    sol = odeint(vector_field, 1, [0, 1, 2, 3])
```

thus I suspect there are memory leak somewhere. This happens to diffrax as well, and it seems to be an issue with jax itself. See also @patrick-kidger's comments in https://github.com/patrick-kidger/diffrax/issues/142 

### What jax/jaxlib version are you using?

jax/jaxlib 0.4.14

### Which accelerator(s) are you using?

CUDA

### NVIDIA GPU info

this behaviour can be reproduced on CPU

**Comment by patrick-kidger** [comment]
I believe this is due to #16226. I think everyone agrees something should probably be done about it. @mattjj?

**Comment by Roger-luo** [comment]
> FWIW this issue doesn't usually turn up very often in real-life programs. It's fairly rare to dynamically define functions in a loop outside of JIT. E.g. I don't think I've ever needed this.

Indeed, I realize in my case I should just use the parameters instead of creating a new equation object. I think I'm gonna close this issue then given this is reported already.

> (Side note -- Roger, it's great to see your interest in JAX!)

I've been writing JAX since Jan actually ;-)
