### ISSUE TITLE
ENH: Reflect changes from numpy namespace refactor Part 4

### ISSUE THREAD

**Issue by mtsokol** [google/jax#17244]
Hi!
There are new changes coming to NumPy's top namespace in https://github.com/numpy/numpy/pull/24445/:

- `row_stack` (an alias for `vstack`) is being removed - I see that it's already deprecated in `jax`
- Deprecated `trapz` and deprecated `in1d` - Would you like to also deprecate these functions in `jax`?

**Comment by hawkinsp** [comment]
We'll follow upstream NumPy on both. For `trapz`, we'd probably better also add `jax.scipy.integrate.trapezoid` so the new name is available.
