### ISSUE TITLE
JAX_DISABLE_JIT=1 doesn't disable (xmap's) jitting

### ISSUE THREAD

**Issue by paulbricman** [google/jax#17266]
### Description

I'm trying to run a multi-host data-parallel job using JAX. Due to working with a nested mess of xmap-scan-grad-pmap-scan-grad (multi-host outer optimization loop, multi-device inner optimization loop), I'm trying to disable jit altogether in an attempt to avoid some suspected performance gotchas. However, means of disabling jitting don't seem to affect xmap. In fact, I suspect it is disabling jit that (ironically) yields obscene compilation times of minutes to hours in my case (depending on configuration), because the sub-xmap logic gets unrolled into non-jitted versions, and xmap jits the entirety of that, maybe?

This issue was already mentioned in a [comment on a closed issue](https://github.com/google/jax/issues/252#issuecomment-1001290150), but seemed not to have much visibility. A minimal repro can also be found there. Opening a dedicated issue for better visibility.

### What jax/jaxlib version are you using?

jax==0.4.14 jaxlib==0.4.14

### Which accelerator(s) are you using?

CPU, TPU

### Additional system info

3.11

**Comment by paulbricman** [comment]
Thanks for the suggestion, @yashk2810, will definitely take a look!

**Comment by Ridhamz-nd** [comment]
Is there a way to disable jit for xmapped models (say for existing codebases)?

**Comment by apaszke** [comment]
xmap was removed from JAX, so this is obsolete
