### ISSUE TITLE
Change in jax 0.4.15 breaks distributed.py on multi-node GPU setups, fix inside

### ISSUE THREAD

**Issue by samblouir** [google/jax#17288]
### Description

JAX 0.4.15 makes this change:
"The option --jax_coordination_service has been removed. It is now always True."

jax_coordination_service was removed from jax's config. This causes an exception in jax/_src/distributed.py, since it tries to access "config.jax_coordination_service".

This commit shows the change that is working for me:
https://github.com/samblouir/jax/commit/a460231b6a149ad0bef1fe5a8c3d1dce009e7759

Only two small modifications are needed.

Line 80 of jax/_src/distributed.py:
`                      coordinator_address, num_processes, config.jax_coordination_service)`
can be changed to:
`          coordinator_address, num_processes, True)`

and line 92:
`          coordinator_address, process_id, config.jax_coordination_service,`
can be changed to:
`          coordinator_address, process_id, True,`

This appears to fix the issue. Training using a multi-host GPU-based setup appears to work again.

### What jax/jaxlib version are you using?

jax==0.4.15? (-e git+https://github.com/google/jax@eea2603363db1ef07b7017d498c96ec744e71218#egg=jax),  jaxlib==0.4.14+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU

### Additional system info

RHEL 8.5, NVIDIA DGX A100

### NVIDIA GPU info

Fri Aug 25 10:41:01 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.86.10              Driver Version: 535.86.10    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100-SXM4-80GB          On  | 00000000:01:00.0 Off |                    0 |
| N/A   26C    P0              66W / 500W |  77444MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100-SXM4-80GB          On  | 00000000:41:00.0 Off |                    0 |
| N/A   25C    P0              68W / 500W |  77444MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100-SXM4-80GB          On  | 00000000:81:00.0 Off |                    0 |
| N/A   25C    P0              68W / 500W |  77444MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100-SXM4-80GB          On  | 00000000:C1:00.0 Off |                    0 |
| N/A   25C    P0              71W / 500W |  77444MiB / 81920MiB |      0%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A    860464      C   ...h/sblouir/mount/venvs/p0/bin/python    77430MiB |
|    1   N/A  N/A    860496      C   ...h/sblouir/mount/venvs/p0/bin/python    77430MiB |
|    2   N/A  N/A    860550      C   ...h/sblouir/mount/venvs/p0/bin/python    77430MiB |
|    3   N/A  N/A    860582      C   ...h/sblouir/mount/venvs/p0/bin/python    77430MiB |
+---------------------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
#17290 will fix. Thanks for the bug report!
