### ISSUE TITLE
Error importing jax

### ISSUE THREAD

**Issue by acycliq** [google/jax#17309]
### Description

I have created a fresh environemnt `conda create --name myenv`. Then I activate the environment and the very first package I am installing is `jax` with the command:
`pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

That looks to install everything in this folder under my home directory: `$HOME/.local/lib/python3.10/site-packages`

However when I install the other packages that I need to work with, these go into the typical location for conda enviroments:
`$HOME/miniconda3/envs/myenv/lib/python3.8/site-packages`

Hence, when I try to import jax from within my new environment, I got the `ModuleNotFoundError: No module named 'jax'` error.

What am I doing wrong please?

**Comment by jakevdp** [comment]
When you install a package with `pip install`, it will be installed in the `python` environment associated with the `pip` executable you are using.

From your description, it sounds like the `pip` executable you are using is not the one associated with your conda environment (you can check this by running `type pip`).

Rather than digging into system paths to try to figure out how `pip` is being found, it's often easier to fix situations like this by specifying exactly which Python environment you want to run `pip` in; you can do this with
```
python -m pip install "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
This will ensure that JAX is installed in the packages directory associated with the Python executable you are using.

**Comment by acycliq** [comment]
Oh ok! yes you are right! I installed pip with `sudo apt install python3-pip` and that messed thinks up with the conda pip.
Do you know by the way how to unistall jax (and all its dependencies like nvidia cuda binaries) that sit under my  `$HOME/.local/lib/python3.10/site-packages`

Many thanks!

**Comment by samblouir** [comment]
[This line should do it: (link to list of packages)](https://github.com/google/jax/blob/841baabd3ffa63b27fa1c4199adc65fbf073c7c0/setup.py#L114C16-L114C16)
pip uninstall -y jax jaxlib nvidia-cublas-cu12 nvidia-cuda-cupti-cu12 nvidia-cuda-nvcc-cu12 nvidia-cuda-runtime-cu12 nvidia-cudnn-cu12>=8.9 nvidia-cufft-cu12 nvidia-cusolver-cu12 nvidia-cusparse-cu12

[These are other required packages, but may have already been installed](https://github.com/google/jax/blob/841baabd3ffa63b27fa1c4199adc65fbf073c7c0/setup.py#L65C10-L65C11):
ml_dtypes
numpy
opt_einsum
scipy 

[If your python is <3.10](https://github.com/google/jax/blob/841baabd3ffa63b27fa1c4199adc65fbf073c7c0/setup.py#L73C33-L73C33), then it should have also installed "importlib_metadata"

I imagine some of these packages had their own dependencies, which may have fetched more from there... if you want it 100% clean, it may be easier to just delete your Python packages directory and re-install your other packages.

**Comment by acycliq** [comment]
Thanks so much! I am now left with these. 
                                      
```
scikit_learn.libs                                    
sklearn
joblib                                     
snowballstemmer
joblib-1.3.2.dist-info                     
snowballstemmer-2.2.0.dist-info
nvidia                                     
third_party
nvidia_cuda_nvrtc_cu12-12.2.128.dist-info  
threadpoolctl-3.2.0.dist-info
nvidia_nvjitlink_cu12-12.2.128.dist-info   
threadpoolctl.py
__pycache__                                
wcwidth
scikit_learn-1.3.0.dist-info              
wcwidth-0.2.6.dist-info
```

As you said these must be dependencies fetched from the packages that have just been removed. The timestamp of all these dependencies that I list above matches the time when I was trying to install jax. They are the only contents under `~/.local/lib/python3.10/site-packages`

Just want to double check, would you guys think it will be ok to just manually delete inside `~/.local/lib/python3.10/site-packages`. My miniconda is in a totally different location anyway.

**Comment by hawkinsp** [comment]
I think of those packages only those ending with `cu12` might have been installed as `jax` dependencies.

I'm not sure if it's safe for you to delete that directory: there's no way for us to tell without knowing your setup.

Sounds like this issue is resolved, so closing...
