### ISSUE TITLE
Running Pallas issue

### ISSUE THREAD

**Issue by mehdiataei** [google/jax#17311]
### Description

Installing jax, jaxlib, and jax-triton nightly builds cause the following error for the examples in the documentation:

  File "/home/mehdi/Repos/venvs/jax-dev/lib/python3.10/site-packages/jax/_src/pallas/triton/lowering.py", line 1721, in pallas_call_lowering
    backend_config=zlib.compress(kernel_call.to_proto(serialized_metadata)),
TypeError: to_proto(): incompatible function arguments. The following argument types are supported:
    1. (self: jaxlib.cuda._triton.TritonKernelCall, arg0: str, arg1: str) -> bytes

Invoked with: <jaxlib.cuda._triton.TritonKernelCall object at 0x7faebfce6ef0>, b''
I0000 00:00:1692795278.467295  180484 tfrt_cpu_pjrt_client.cc:469] TfrtCpuClient destroyed.
Package Version Editable project location

absl-py 1.4.0
filelock 3.12.2
jax 0.4.15
jax-triton 0.1.4 /home/mehdi/Repos/jax-triton
jaxlib 0.4.15.dev20230822+cuda12.cudnn89
ml-dtypes 0.2.0
numpy 1.25.2
opt-einsum 3.3.0
pip 22.0.2
scipy 1.11.2
setuptools 59.6.0
triton-nightly 2.1.0.dev20230714011643

### Which accelerator(s) are you using?

GPU

### NVIDIA GPU info

2x RTX ada 6000 (CUDA 12.2)

**Comment by jon-chuang** [comment]
seems like a versioning issue, I've run into tonnes of those using jax-triton due to its use of nightly triton.

**Comment by mehdiataei** [comment]
Since pallas is integrated into JAX now, there shouldn't be a need to install jax-triton. If you don't install triton or only install triton with the nightly build from the jax-triton repo the error is:

NotImplementedError: MLIR translation rule for primitive 'pallas_call' not found for platform cuda

**Comment by sharadmv** [comment]
> Since pallas is integrated into JAX now, there shouldn't be a need to install jax-triton.

This is true in principle but we haven't yet done this.

We still need a Triton dependency because we need to use the Triton compiler with Pallas. That is why we depend on jax-triton at the moment. Jax-triton also contains specific logic for creating Triton custom calls.

In the future, we can decouple the two by using the Triton compiler that already ships with XLA. Unfortunately this is a large undertaking because there are no Python bindings exposed and it would take some work to add them.

**Comment by mehdiataei** [comment]
So the way to run Pallas (currently):
Install JAX (head) and build jaxlib (head) + install jax-triton nightly?

**Comment by sharadmv** [comment]
> Install JAX (head) and build jaxlib (head) + install jax-triton nightly?

Yes, but unfortunately, jax-triton works with not *exactly* a Triton nightly but close to Triton nightly. As of today (8/29/23) here is a set of pinned versions I tested and should work:
```
-e git+ssh://git@github.com/sharadmv/jax@7ec2a8835ecc4ffcb632b43cc47c892d1b323d47#egg=jax
-e git+ssh://git@github.com/jax-ml/jax-triton.git@321a19e901ee318a43345485a47e711944011c77#egg=jax_triton
jaxlib @ https://storage.googleapis.com/jax-releases/nightly/cuda12/jaxlib-0.4.15.dev20230822+cuda12.cudnn89-cp310-cp310-manylinux2014_x86_64.whl
nvidia-cublas-cu12==12.2.4.5
nvidia-cuda-cupti-cu12==12.2.131
nvidia-cuda-nvcc-cu12==12.2.128
nvidia-cuda-nvrtc-cu12==12.2.128
nvidia-cuda-runtime-cu12==12.2.128
nvidia-cudnn-cu12==8.9.4.25
nvidia-cufft-cu12==11.0.8.91
nvidia-cusolver-cu12==11.5.1.129
nvidia-cusparse-cu12==12.1.2.129
nvidia-nvjitlink-cu12==12.2.128
triton-nightly==2.1.0.dev20230722054455
```

**Comment by mehdiataei** [comment]
Hi Sarad,

Thanks. I'll give it a try. There are potentially some cool applications of Pallas in [XLB](https://github.com/Autodesk/XLB) that I am planning to explore.

It would be nice to have installation documented by the next release version of JAX.

**Comment by sharadmv** [comment]
> 2023-08-30 14:00:03.110213: F external/xla/xla/python/jax_jit.cc:134] Check failed: global_state.enable_memories.has_value() 

This looks like an unrelated issue unfortunately. I will try to triage it.

**Comment by superbobry** [comment]
jaxlib 0.4.25 no longer uses Triton Python APIs for lowering Pallas kernels on GPU, so I will close this issue.
