### ISSUE TITLE
Passing `time.time()` into JAX jitted function is not the correct value inside the jitted function

### ISSUE THREAD

**Issue by cemlyn007** [google/jax#17319]
### Description

Passing objects created from `time.time()` into this jitted function does not seem to actually pass that value into the jitted function. At least on my Mac M2, here is my example:
```
import jax
import time


@jax.jit
def print_t(t):
    jax.debug.print("t {t}", t=t)
    return t


if __name__ == "__main__":
    print("Testing with fixed values")
    for i in range(5):
        print_t(i)
    print("Testing with time.time()")
    for _ in range(5):
        t = time.time()
        print("outside of jit", t)
        print_t(t)
        time.sleep(0.1)
    print("Testing with time.monotonic()")
    for _ in range(5):
        print_t(time.monotonic())
        time.sleep(0.1)
```
Running outputs to terminal:
```
(py311jax) cemlyn@192 jax_time_debug % python main.py
Testing with fixed values
t 0
t 1
t 2
t 3
t 4
Testing with time.time()
outside of jit 1693178784.298062
t 1693178752.0
outside of jit 1693178784.410149
t 1693178752.0
outside of jit 1693178784.5138052
t 1693178752.0
outside of jit 1693178784.6200619
t 1693178752.0
outside of jit 1693178784.726197
t 1693178752.0
Testing with time.monotonic()
t 212217.1875
t 212217.28125
t 212217.390625
t 212217.5
t 212217.609375
```

It is interesting because values obtained from `time.monotonic()` do not cause this problem but `time.time()` does?

### What jax/jaxlib version are you using?

JAX 0.4.14 JAXLIB 0.4.14

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11 Mac M2

**Comment by jakevdp** [comment]
Hi - thanks for the question! JAX uses 32-bit floating point by default, so unless you enable X64 mode any 64-bit floats passed to JAX functions will be truncated to 32-bit (see [JAX Sharp Bits: 64-bit Precision](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision) for more info).

If I run your code with `jax_enable_x64=true`, I find the output you were expecting:
```
$ JAX_ENABLE_X64=1 python main.py 
Testing with fixed values
t 0
t 1
t 2
t 3
t 4
Testing with time.time()
outside of jit 1693239476.6471722
t 1693239476.6471722
outside of jit 1693239476.7575831
t 1693239476.7575831
outside of jit 1693239476.8632388
t 1693239476.8632388
outside of jit 1693239476.969988
t 1693239476.969988
outside of jit 1693239477.0751739
t 1693239477.0751739
Testing with time.monotonic()
t 1.146224041
t 1.254679291
t 1.360897291
t 1.464344416
t 1.571398583
```

**Comment by cemlyn007** [comment]
Sorry I forgot to reply! Things have been a bit hectic lately! Thank you very much, sorry I was completely flabbergasted by seeing weird numbers that I didn't comprehend that it's simply truncation mistake! Hope you have a good week! 💯
