### ISSUE TITLE
add explicit checkpointing (rematerialization) control

### ISSUE THREAD

**Issue by mattjj** [google/jax#1732]
Analogous to [`checkpoint` in Autograd](https://github.com/HIPS/autograd/blob/c6f630a5ec18bd30f1485bc0dbbccb8664c77510/autograd/differential_operators.py#L192-L202) (but handling closed-over tracers).

**Comment by j-towns** [comment]
Doesn't custom_transforms already to this?

**Comment by mattjj** [comment]
@j-towns yes and no: `custom_transforms` is kind of rickety right now (I can unpack that, but basically it's ripe for revision), and it places constraints on what Python control flow can be executed.

It might be that we can implement `rematerialize` in terms of a revised and improved `custom_transforms`, but I'm not sure about that: I think we want `rematerialize` to behave a specific way under partial evaluation, and we don't necessarily want that behavior for `custom_transforms` functions (though we might). We also want `rematerialize` to foil XLA's CSE.

#1749 is meant in part to be an initial exploration of what a revised `custom_transforms` could look like, so we might end up being able to de-duplicate things if they end up coinciding.
