### ISSUE TITLE
Missing warning on requesting float64 in random.uniform

### ISSUE THREAD

**Issue by andportnoy** [google/jax#17366]
### Description

It's a known gotcha that by default JAX very aggressively uses fp32, overriding fp64 even when requested explicitly. Warnings about this are very helpful but are not displayed consistently.

`jax.numpy.zeros`:
```python
In [1]: import jax.numpy as jnp

In [2]: jnp.zeros(1, dtype=jnp.float64).dtype
<ipython-input-2-cf3e83ec7758>:1: UserWarning: Explicitly requested dtype <class 'jax.numpy.float64'> requested in zeros is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  jnp.zeros(1, dtype=jnp.float64).dtype
Out[2]: dtype('float32')
```
`jax.random.uniform`:
```python
In [3]: from jax import random

In [4]: random.uniform(random.PRNGKey(0), dtype=jnp.float64).dtype
Out[4]: dtype('float32')
```

### What jax/jaxlib version are you using?

0.4.14

**Comment by jakevdp** [comment]
Thanks! We're aware of this issue. I have a work-in-progress PR that cleans up dtype handing in `jax.random`, but it stalled because it led to breakages in so many downstream projects: #15177

**Comment by andportnoy** [comment]
Good to know, thanks.
