### ISSUE TITLE
kwargs support for `in_shardings`

### ISSUE THREAD

**Issue by Conchylicultor** [google/jax#17400]
In Python, using dict / kwargs rather than tuple / args is good practice as it make the code more robust and explicit (e.g. to function signature change, argument re-ordering,...).

Currently, `in_shardings` only supports `tuple`. It would be nice if it was also supporting explicit argument names with `dict`:

```python
@functools.partial(
    jax.jit,
    in_shardings=dict(
        state=REPLICATED,  # << Explicit mapping argument name to sharding :)
        batch=SHARDED,
    ),
)
def step(state, batch):
  return x + y
```

In complex signatures with many static arguments, this would really help readability.

**Comment by Conchylicultor** [comment]
Actually it's even worse. Currently `jit` raises an error when trying to use kwargs:

```python
@functools.partial(
    jax.jit,
    in_shardings=(REPLICATED,  SHARDED),
)
def step(state, batch):
  return x + y

step(state=state, batch=batch)
```

Raises:

```
ValueError: pjit does not support kwargs when in_shardings is specified.
```

**Comment by yashk2810** [comment]
A better approach here is to not use in_shardings at all. Just shard your inputs the way you want them to be sharded and pass the to jit without using in_shardings.

**Comment by yashk2810** [comment]
Is there a case where you need to write in_shardings? The example you pasted above tells me that the state and batch can be sharded outside of jit perfectly well so there's no need to use in_shardings at all.

**Comment by Conchylicultor** [comment]
There's a few reasons while `in_shardings=` is preferable:

* To be explicit / self-documenting. With `in_shardings=`, an explicit error would be raised if the wrong sharding their inputs
* Users might forgot to shard their data (e.g. on Colab). Sharding outside make the code more verbose, thus it's very likely some users might not think about this

**Comment by yashk2810** [comment]
Maybe write your own function for the error thing?

I don't think sharding outside makes the code more verbose FWIW. It's just a device_put outside jit. 

My point is that we are not going to allow kwargs for in_shardings (and other features on it) because there's no need for in_shardings to be specified. It only exists as a backwards compatible argument to not break a lot of code.

**Comment by Conchylicultor** [comment]
>  It only exists as a backwards compatible argument

If `in_sharding` is deprecated or not recommended, it should be said in the doc. Otherwise, more users are gonna lost some time with this or similar issues.

> It's just a device_put outside jit.

Not really (for example `device_put` won't work for multi-process).

That's a separate issue, but the actual logic to shard values is actually very non trivial and verbose:

```python
global_devices = np.asarray(jax.devices())
global_mesh jax.sharding.Mesh(global_devices, axis_names=('devices',))

local_devices = np.asarray(jax.local_devices())
local_mesh = jax.sharding.Mesh(local_devices, axis_names=('devices',))

replicated_sharding = jax.sharding.NamedSharding(
    global_mesh, jax.sharding.PartitionSpec()
)
sharded_sharding = jax.sharding.NamedSharding(
    global_mesh, jax.sharding.PartitionSpec('devices')
)
local_replicated_sharding = jax.sharding.NamedSharding(
    local_mesh, jax.sharding.PartitionSpec()
)
local_sharded_sharding = jax.sharding.NamedSharding(
    local_mesh, jax.sharding.PartitionSpec('devices')
)


def _replicate(array):
    array = jax.device_put(array, local_replicated_sharding)
    global_shape = array.shape
    return jax.make_array_from_single_device_arrays(
        global_shape,
        replicated_sharding,
        array.device_buffers,
    )


def _shard(array):
    array = jax.device_put(array, local_sharded_sharding)
    global_shape = (array.shape[0] * jax.process_count(),) + array.shape[1:]
    return jax.make_array_from_single_device_arrays(
        global_shape,
        sharded_sharding,
        array.device_buffers,
    )

params = model.init()
params = jax.tree_map(_replicate, params)

for batch in ds:
  batch = jax.tree_map(_shard, batch)
  step(batch, params)
```

Where previously `pmap` only required very little lines, users now are require to write 35+ additional lines of boilerplate code logic to have simple data parallelism.

Don't get me wrong, I really like `jax.Array` and automatic differentiation. I think this greatly simplify some previous code.

However in the current version, I find it way too complicated with too many abstractions, making it tricky to use. I've lost a few days to try to make it work and this turned out much harder than I expected. I'm still struggling dealing with errors.
I feel this is not a cost that users should have to pay.

I personally had to develop my [own version](https://critique.corp.google.com/cl/561669843/depot/google3/third_party/py/kauldron/utils/sharding_utils.py) of `device_put` to support multi-process:

```python
state = kd.sharding.device_put(ex, kd.sharding.REPLICATED)

for ex in ds:
  ex = kd.sharding.device_put(ex, kd.sharding.SHARDED)

  state = step(batch, state)
```

It would be nice if `jax` was supporting something similar simple like this. Data parallelism is a very standard use-case. I feel it shouldn't require so much mental overhead to make it work.

**Comment by yashk2810** [comment]
> users now are required to write 35+ additional lines

This seems a bit exaggerated to me. I can write the same in 5 lines or so (keeping it readable) but it is very much dependent on coding style and python formatters. Also, I think you have mixed 2 issues here. So if you want to talk about how to reduce your number of lines of code, we can talk offline about that. 

As far as the original issue goes, you would have to shard the input regardless of specifying in_shardings or not. What in_shardings really buys you here is the checks which you can do too. So adding more features to in_shardings or supporting it for kwargs is a P3 or a P4. I'll keep the issue open and I'll get to it when I can. But again, you don't have to use in_shardings.

**Comment by Conchylicultor** [comment]
> I think you have mixed 2 issues here

Yes, the complexity is another issue. I'm fine with not supporting `in_shardings` kwargs (though I still feel this should be explicitly described in the doc that `in_shardings`)

> I can write the same in 5 lines or so.

I'll be very curious how you'll manage to achieve this. But yes, let's chat offline.
