### ISSUE TITLE
pass-by-reference semantics is violated when calling function through vmap 

### ISSUE THREAD

**Issue by RezaRob** [google/jax#17415]
### Description

Why are these 2 ways of calling `h(l,x)` inconsistent in behavior?

```
import jax
from jax import numpy as jnp
from jax import jit

def h(l, x):
        l[0]=9999
def f1():
        l=[0]
        h(l, jnp.array([1,2]))
        return l
def f2():
        l=[0]
        jax.vmap(h, (None,0))(l, jnp.array([1,2]))
        return l
f1=jax.jit(f1)
f2=jax.jit(f2)

a = f1()
print("a: ", a)

a = f2()
print("a: ", a)
```

**Result:**
**Inconsistent behavior:**
```
a:  [Array(9999, dtype=int32, weak_type=True)]
a:  [Array(0, dtype=int32, weak_type=True)]
```

**Expected semantics/behavior** (sort-of! You basically want `l` to be modified by `h()` in _both_ cases, i.e. "pass-by-reference" semantics):
```
import jax
from jax import numpy as jnp
from jax import jit

def h(l, x):
        l[0]=9999
        return l         # <--------
def f1():
        l=[0]
        l = h(l, jnp.array([1,2]))       # <---------
        return l
def f2():
        l=[0]
        l = jax.vmap(h, (None,0))(l, jnp.array([1,2]))   # <---------
        return l
f1=jax.jit(f1)
f2=jax.jit(f2)

a = f1()
print("a: ", a)

a = f2()
print("a: ", a)
```

**Consistent / correct behavior:**
```
a:  [Array(9999, dtype=int32, weak_type=True)]
a:  [Array([9999, 9999], dtype=int32, weak_type=True)]
```

### What jax/jaxlib version are you using?

jaxlib  0.4.13+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux

**Comment by erfanzar** [comment]
instead of using a normal Python list try to use `Jax Numpy Array` and I think that gon workout just fine

```python

import jax
from jax import numpy as jnp
from jax import jit


def h(l, x):
    l.at[0].set(9999)


def f1():
    l = jnp.asarray([0])
    h(l, jnp.array([1, 2]))
    return l


def f2():
    l = jnp.asarray([0])
    jax.vmap(h, (None, 0))(l, jnp.array([1, 2]))
    return l


if __name__ == '__main__':
    # f1 = jax.jit(f1)
    # f2 = jax.jit(f2)
    f2_expe = jax.make_jaxpr(f2)()
    f1_expe = jax.make_jaxpr(f1)()
    print(f1_expe)
    print(f2_expe)
    # Both Funcs  worked just fine for me wit jax 0.4.14
```

Result
```text
{ lambda a:i32[1]; . let
    b:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    _:i32[1] = scatter[
      dimension_numbers=ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))
      indices_are_sorted=True
      mode=GatherScatterMode.FILL_OR_DROP
      unique_indices=True
      update_consts=()
      update_jaxpr=None
    ] a b 9999
  in (a,) }
{ lambda a:i32[1]; . let
    b:i32[1] = broadcast_in_dim[broadcast_dimensions=() shape=(1,)] 0
    _:i32[1] = scatter[
      dimension_numbers=ScatterDimensionNumbers(update_window_dims=(), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))
      indices_are_sorted=True
      mode=GatherScatterMode.FILL_OR_DROP
      unique_indices=True
      update_consts=()
      update_jaxpr=None
    ] a b 9999
  in (a,) }
```

**Comment by RezaRob** [comment]
> instead of using a normal Python list try to use `Jax Numpy Array` and I think that gon workout just fine

That doesn't address the issue. That just wasn't the point. And it also doesn't work for dictionaries. 

Only as  an unrelated side note, using "at" is also not the "typical/preferred" Jax usage pattern. 

And moreover, the solution seems wrong: multiple vmap'ed threads writing into a pytree automatically write an _array'ed_ output into the pytree node. I don't believe the "at.set" thing here is really doing that anyway.

But let's not lose focus from the main issue here.

**Comment by RezaRob** [comment]
Please note, the code that I posted shows that Jax is _already_ doing all of this. It's just a matter of "returning" the right value and assigning it to the original.

**Comment by jakevdp** [comment]
Hi - thanks for the question! This is working as expected. The issue here is that your function is not pure: updating the list value (without returning it) is a side-effect, and JAX transforms only work with pure, functional code (see [JAX Sharp Bits: Pure Functions](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html) for a discussion of this).

Hope that helps!

**Comment by RezaRob** [comment]
Please take a look at my code samples. I provided two functions, f1 and f2, both of them are pure *jit*'ed functions. They both call another function h and pass the parameter in question *internally* within Jax jit'ed functions. *Only* the vmap'ed call doesn't modify the parameter as expected – bug. The other call, without vmap, works as expected.

**Comment by jakevdp** [comment]
This calls `vmap` on `h`, which is an impure function that attempts to modify the input without returning it:
```
def f2():
        l=[0]
        jax.vmap(h, (None,0))(l, jnp.array([1,2]))
        return l
```
Therefore its semantics are undefined, because it breaks the contract of JAX transformations.

**Comment by RezaRob** [comment]
`f1` and `f2` are jit'ed functions. Once compilation takes place (when it's taking place) h becomes strictly internal to Jax. It has no influence on the outside. 

Contract? Break the contract! Write anew! Jax is already doing all of this correctly in other situations (see code samples). This vmap case is when Jax _isn't_ following its usual pattern.

`h` doesn't behave _consistently_ when called from `f1` versus `f2`. 

(a) There is no reason for this inconsistency. 

(b) The pass-by-reference semantics when `h` is called from `f1` makes much more sense, is correct "pythonic" behavior, and very useful.

(c) The "solution" I provided (see code samples) demonstrates that Jax is already fully capable of doing this; it was designed to do this. A simple change to the code allows the modified variable to be returned. Therefore, fixing this issue is probably not even costly.

**Comment by jakevdp** [comment]
> (a) There is no reason for this inconsistency.

The reason for this inconsistency is that you are breaking the contract of JAX transformations, which explicitly require pure functions.

**Comment by RezaRob** [comment]
I can see that there is an important point here: you want vmap to have the same behavior whether it's called inside a jit function or not. Consistency. That's fair.

However, the main principle behind that point is this: "we want functions to behave the same when jax is used." And functions don't behave the same under Jax. Transformations change the behavior of the user's functions by treating them as pure (no outside influence on the Python environment).

The right solution to that dilemma would have been to make one very simple change (and explain it on the "Sharp Bits" page as you always do). Namely, "pure function" should be defined as a function that **may** change it's Pytree parameters as per "pass-by-reference" semantics. That change would make other things much more consistent, and it would be very beautiful for the following reason:

The main point of jax is compiling. It just makes everything so much more efficient. That's why you guys don't care too much about dispatch overhead, because: "just compile." What happens "inside" Jax space (the contract of Jax with itself) is much more important. And it would be very nice if Jax'es internal behavior was well defined and consistent, not to mention more "pythonic." 

It is also (probably) trivial to change "pure functions" (and Jax transformations) because Jax transformations **already** influence the Python environment, they just do it through the return value - that's all. So treating Pytree function parameters as "return value" and modifying the reference would work just fine. **If** the user doesn't want to modify the parameter, they should just copy it (`copy = tree_map(lambda x:x, original)`). And then things would be consistent inside and outside of Jax, not to mention compatible with Python behavior.

The only caveat is that breaking existing users is bad.

[Side Note]
Linus Torvalds never beaks user-space. He apparently hates doing so. As a remedy, he tries to make sure things are very well thought out at the outset. That's one reason why 20 years after the fact, everyone is still using Linux.
[/Side Note]

Jax is extremely beautifully designed and well thought out. Almost everything there seems exactly right, with a great sense of the objective and main goal of clean Python integration with math/AI hardware devices. This pass-by-reference business is one instance where it probably could have been different, and I wish it was.

As it stands, Jax changes function behavior anyway (so the idealistic principle above that it wants to adhere to is violated anyway), it just does it inconsistently. `jit(h)` turns `h` into a pure function (turning off pass-by-reference semantics), whereas `jit(f(h))` does not do that to `h`.

**Comment by RezaRob** [comment]
Unless there is a fundamental reason to oppose this, it would still be a great idea to make this option available with an opt-in flag in a future version.

**Comment by jakevdp** [comment]
I'm sorry, I don't really understand the point you're making here. JAX transformations presume they are operating on pure functions. If you pass an impure function to a JAX transformation, you get undefined behavior. That seems like a pretty simple rule, no? I don't see much benefit to providing situational workarounds for impure functions.

**Comment by jakevdp** [comment]
Hi - I thought about this a bit more and I think I understand a bit more what you're getting at: you are proposing extending the definition of "pure" functions in JAX by treating all (possibly mutated) inputs of a function as implicit outputs. I could see how this might be done self-consistently within JAX's tracing framework, but it does seem like it would add to the complexity of both JAX and the mental model required to use it.

Additionally, it brings up other complications: for example, you'd need a way to specify the `out_axes` within `vmap` for the implicit function arguments, and for operations like `vjp` and `jvp`, the semantics of in-place modification are hard to work out (e.g. for `jacrev`, would the input be overwritten with a nested container representing the identity jacobian?)

Overall it's an interesting idea, but the relative simplicity of JAX's current computational model is overall a better choice in my opinion.

**Comment by RezaRob** [comment]
I'm really sorry about the late reply.

Thank you very much for the good points that you brought up. Although I don't really know what you're saying regarding jacrev and "identity" Jacobian, your basic concern is very clear: How and when should Jax function modifiers deal with these extra implicit "outputs?"

Let's discuss the "when" first, then we'll discuss the "how" and then we give some reasons "why?" 

**Additional/Brief Motivation**

Note that under section "why" (below) we will give more motivation about the "deeper benefits" of doing this and why it's very useful. But here, I'll add another code sample to demonstrate that these inconsistencies already exist  **even** entirely inside a jax.jit compiled function and having nothing at all to do with Python. This demonstrates that having these inconsistencies isn't really helping to clarify and simplify the jax "mental model," and it'll serve as a brief motivation for us until we get to the "why" section below.

So, here is a code sample that should be self-explanatory. The inconsistency happens entirely inside jax.jit, and it demonstrates the problem even better than vmap does because, in this case, the user is *explicitly* indicating that he wants the function evaluated **and** wants the value of the function returned. Despite this, Jax refuses to process the side effect of `g()` (modify the input dictionary `x` as per pass-by-reference semantics) which **does** happen if `g()` is called directly rather than through `value_and_grad()`.

```
from jax import jit, value_and_grad

def g(x):
        x['a'] = x['a'] + 1.0  # modified
        return x['a'] * x['a']

@jit
def f():
        x = {'a':1.0}   # original
        g(x)
        modified = x['a']

        val_grad = value_and_grad(g)(x)
        not_modified = x['a']
        return modified, val_grad, not_modified

modified, val_grad, not_modified = f()
print(f"modified after call to g(x): {modified}\nval_grad: {val_grad}\nnot_modified after call to value_and_grad(g)(x): {not_modified}")
```

Result:
```
modified after call to g(x): 2.0
val_grad: (Array(9., dtype=float32, weak_type=True), {'a': Array(6., dtype=float32, weak_type=True)})
not_modified after call to value_and_grad(g)(x): 2.0
```

**When should Jax function modifiers "deal with" implicit outputs?**

The `value_and_grad()` function offers the best explanation of the problem and points to a possible solution. As an aside, it's interesting that this is a separate function and not amalgamated with `grad()`. But the main principle that it offers is: **be explicit**. In other words, function modifiers must do what they are "explicitly" asked to do and not produce other side effects. Both of these functions return "almost the same" function, but what that function does to the Python environment (the values that it returns to the Python stack) are determined by explicit request, not implicit modification. I think that's a very good principle because it clears any confusion about how Python state is being modified. 

**How should Jax function modifiers deal with implicit outputs when they are requested to do so, and how should their interface be modified to deal with these implicit outputs?**

Note: these interface issues should best be discussed with a larger community besides "just me" or the "Jax team." Nevertheless, discussions shouldn't take forever! The matter is a simple matter. Everything that Jax already does is (much) more complex than this. Unless there are really good objections, I'll argue (below under "why") that there are really good reasons for supporting mutability. 

In my view, these implicit outputs should **not** be thought of as the (mathematical) function's "(official) output." First, because, as you suggest, that would make the "mental model" cumbersome and complex. Second, because function modifiers like vmap are major events. The user already has to be quite mentally committed and explicit about what the function does. Likewise, also, the "official output" of the function which Jax function modifiers directly care about, can be explicitly specified using a "return" statement. It would appear ugly and redundant to specify implicit outputs/mutations as function return values, and I'm not sure what benefits it would add. The point of implicit outputs is to allow the function to "report/return" an internal state, and doing so automatically without explicit user intervention or explicit return values that might become long and cumbersome. We will further discuss this point in the "why" section below. 

Therefore, the core function and behavior of Jax function modifiers doesn't need to change. However, on a case-by-case basis, precisely like every function has an "aux:bool" parameter to deal with auxiliaries, they should also have a parameter (when doing so makes sense) for specifying whether to implicitly update each Pytree parameter or not. Perhaps a "mutate" parameter with defaults that are reasonable for each function. This is no different than the case of `value_and_grad()` (possibly better amalgamated with grad() into one function) which explicitly provides a way to retrieve the function value when it makes sense to do so (i.e. because grad actually evaluates the function).

None of this would add to the complexity of Jax in any way, nor would it be difficult to implement. In fact, we shall see that it makes Jax more consistent and useful.

**Why? What are the "deeper" benefits of doing this?**

We've already discussed consistency as a motivation for doing this, and I think that's important in its own right because it'd make jax more beautiful.

Also, why does Python already do this? Because pass-by-reference permits easy and smooth communication within a deep function call stack between different functions without the use of cumbersome, redundant, or long-winded return statements. Especially in the case when a "dictionary" or "Pytree" value is clearly intended to be statefully manipulated by a deep function call stack (or deep "op tree"), making returns explicit is tedious and redundant.

But mutations are also particularly useful to Jax because "pure" Jax functions need a way of keeping, updating, and returning state. How does Jax work? The idea of "scope" is apparently central to Flax. Just like neural network modules have scope (like Module_2__Conv_Layer_3__Filter_5; just making up something for argument's sake) and these "scopes" may be represented by various functions calling each other (e.g. `Module_2` calling `Conv_Layer(scope_3, ...))`) 

However, Flax hides all of this detail under many layers (thousands of lines of object oriented code) from the user. The user is detached from how Jax actually works and its internal beauty! 

**[side note]**
I actually don't know enough about Flax. It's big. I haven't read all the code. It feels a little like using a nuclear bomb to shoot a fly! I'm sure it has its uses. Maybe enterprise users appreciate something big. It reminds me of Microsoft Foundation Classes (MFC). It's the sort of thing that big companies have to do to look serious about a technology - I guess?!

However, sometimes you need something smaller and unobstructed access to the lower-level, smooth, efficient, well-defined internals.
**[/side note]**

This idea of "scoping" can be used very effectively to build neural networks and work with Jax without going through a huge object-oriented library stack, simply by `push`ing and `pop`ing names onto a scope stack to create different scoping levels and using these name scopes to save layer parameters/state under.

You can have a really tiny library in literally 50 lines of python code to give you a nice (named) "scoping" mechanism where individual functions like, say, "linear_dense_layer()" create their **own** parameters and manage their own state using proper (named) "scopes" where those parameters and internal states are saved. Here is an example of doing this which I post here "as is" just to demo it. It should be obvious and straightforward what I'm trying to do. I was hoping to very soon release this (publicly) with executable code samples. (see first 50 lines)

https://gist.github.com/RezaRob/27ef4b2c35e037c3f5b59493c7dea02c

The only thing that Jax is missing is a way to "connect" function code with parameters/state. That's all. That's what jax needs. You can work with that very efficiently, at least if you're a researcher, you want "direct" unobstructed access to jax and all its internal capabilities, and you don't want/need a massive library on top.

Now, in a system like this, imagine you want to keep track of the random state of a "dropout" layer. The layer gets called through vmap and manipulates its random state. You want, without explicit return values, that state to be saved, preserved, and communicated back to the python environment. 

**And** it makes perfect sense to do this for other reasons already discussed: it makes jax more beautiful by resolving its apparent inconsistencies, it integrates perfectly with Python and a "pythonic" mindset, and it does **not** make jax more mentally complex. In fact, as argued at the beginning of this comment, it clears up the mental model a little bit and makes it even cleaner.

**Parallel distribution and pmap:** I haven't poked around the multi-device features of Jax and `pmap` to know all it's possible intricacies, but just looking at the documentation, everything seems straightforward. I don't see any problems here. `pmap` is a "well-defined" "atomic" operation, no?! Presumably multi-device jax arrays are represented by a typical `jaxlib.xla_extension.ArrayImpl` object or something like that, right? And `pmap` can trivially return a Pytree just like vmap, correct? Well, all it takes is just updating some Pytree with all the new "jax_device_array" links. I am not sure if there is something else going on there that makes this more complicated.

**[Side note]**
I had thought that dynamic_update_slice actually updates the array. So, I thought you were worried about such array updates (to function array parameters) modifying the array outside of "jax.jit." It seems that I was wrong about dynamic_update_slice, and we only have to worry about actual Pytrees like lists and dictionaries.
**[/Side note]**

**Comment by jakevdp** [comment]
> Although I don't really know what you're saying regarding jacrev and "identity" Jacobian

What I mean is this. Suppose we have a function that looks like this:
```python
@jax.jit
def f(x: list):
  x[0], x[1] = x[1], x[0]
  return jnp.sin(x[0]), jnp.cos(x[1])
```
We call it and get something like this:
```python
x = [0.0, 1.0]
result = f(x)
print(result, x)
```
```
(0.84147096, 1.) [0.0, 1.0]
```
Because the modification of `x` is a side-effect, it's not reflected in the output.

So say we decide to address this by somehow making the input values implicit outputs of the function under the hood. What we're saying is that `result = f(x)` really means something like this:
```python
@jax.jit
def f_with_explicit_mutation(x):
  x[0], x[1] = x[1], x[0]
  return (jnp.sin(x[0]), jnp.cos(x[1])), x

x = [0.0, 1.0]
result, x[:] = f_with_explicit_mutation(x)
print(result, x)
```
```
(0., 0.5403023) [1., 0.]
```
The implicit return values of the function are overwritten in the mutable inputs in order to make `jit` handle Python-style mutability. In terms of `jit` (and probably also `vmap`) I think this does roughly what you want.

But now consider an operation like `jax.jacobian`. What results do we get?
```python
jac_result, x[:] = jax.jacobian(f_with_explicit_mutation)(x)
print(x)
```
```
[[0., 1.], [1., 0.]]
```
By the proposed underlying semantics here, `x` is overwritten by its identity jacobian. This would be really confusing and surprising behavior, in my opinion. And the alternatives (make implicit outputs only work for some transformations but not others?) strike me as even worse, because they add to both the complexity of the implementation, as well as the complexity of the mental model for users of JAX.

I appreciate your thoughts here, but I want to be absolutely clear since I see you're investing a lot of time in these responses: I don't think this idea will gain any traction.

**Comment by RezaRob** [comment]
I have already carefully explained these concerns in my comment, if you refer to it. But please appreciate the fact that I need this issue to receive justice and proper attention because it is important for Jax.

I'll address your comments more directly here (even though I still suggest looking at my comments above more carefully if more details are needed):

First, (and this isn't my main point), I think your calculations are a bit hasty and there are some errors there with the derivatives.

Second, (and this isn't my main point either), I have no idea what this means. 

> if the mutated value of x can affect later computations, then the gradient of the mutated value of xmust be present during autodiff, or else gradients for your full computation will be wrong!

Please note that if there are legitimate concerns then I might need them explained to me very clearly in order to address them. I cannot do magic here!

Now... regarding your main concerns which I think you're trying to explain to me...

First of all, I am **not** suggesting any kind of hocus-pocus modification of the original value. I have no idea why you think I'm proposing this:

> By the proposed underlying semantics here, x is overwritten by its jacobian with respect to the input

And the code is not correct. You're just making x "point to the Jacobian return value" "somehow" (I don't know how!) and you're saying that I'm proposing this. I am not proposing that. I am proposing something else...

Jax is **already** doing what I'm proposing and doing it very beautifully and effectively (at least some of the time). For example, both Jacobian functions, `jacrev` and `jacfwd`, can handle auxiliary function return values via the `has_aux` field. This is a "side effect" value that the function just returns but it's not part of the function's "official" mathematical value and the Jacobian doesn't care about the aux data, correct?

That is all I'm proposing. Right before the function returns (to Python), `x` is in some state. It is modified and can be thought of as an "auxiliary" extra value computed by the function, correct?

The proposal here is to allow the user (just like with the `has_aux` flag) to retrieve this extra information and write it back to Python, if the user so desires, except by pass-by-reference mutation semantics.

This does not harm Jax, it's not weird, and it's not hard to implement.

**Comment by jakevdp** [comment]
Thanks for the extra description, but I can't say I entirely understand what you have in mind.

> it's not hard to implement.

From my understanding of what you're proposing, I believe this would be very hard to implement consistently. But I may be wrong: if you think it's not hard, I'd suggest preparing a small pull request demonstrating the modifications to JAX that you have in mind. That would probably be the most effective way to move the discussion forward if you're interested in continuing to pursue the idea.

**Comment by RezaRob** [comment]
That's tempting. I thought about doing that, and it would be an opportunity to give myself a fun programming exercise and learn more about Python/Jax internals. 

That's tempting, but it's not fair. 

> I believe this would be very hard to implement consistently

Give me some credit! Do you think I don't know who I'm talking to?

You guys can trace Python code, unfold it, break down high level PyTree instructions and translate them completely seamlessly to equivalent xla/machine code which runs on any accelerator optimized, then take the result, put it back together into a PyTree, and return it back to the user as if it all never even left Python!

You people can do vmap of pmap, and pmap of vmap, and any combination thereof! 

You got Jacobians figured out backwards and forwards – literally! 

You do in the literal what other people swear to in the figurative!

And you tell me that what I'm asking would be "very hard to implement consistently?" 

I've given ample reasons why this is needed and why it would make Jax better and more user friendly.

I don't want to do this, because I don't **know** how to do this. It would take me time to familiarize myself with all that intricacies of tracing Python code and converting it to xla in order to inject this relatively small change into it.

I want people who are already doing this, and know it well, and can do it efficiently, to do this. That's **you** guys, the Jax team, not me! 

Now, why is it that despite being reasonable I'm not getting the proper attention that I deserve?!

**Comment by jakevdp** [comment]
> I'm not getting the proper attention that I deserve?!

I'm sorry you feel this has not gotten attention. I've given this a lot of attention over the past week: I've thought about the proposal, and given concrete examples of where it would introduce inconsistencies and confusion. I'm not sure what additional attention you're expecting. Again, I'm sorry my responses have made you feel unseen and I hope you can believe that I've considered your idea and am not ignoring it.

**Comment by hawkinsp** [comment]
I just want to +1 Jake's comments.

Yes, it's possible that an extension along the lines you name can be done. But the cost/benefit ratio doesn't seem worth it. JAX *assumes* pure functions in many, many places, and this is a key simplification that underlies many parts of JAX. It would be a major project to change that, even if it could be done and done well, which is not at all clear. And remember simplicity, both in interface contract and in implementation, is a virtue, as well!
