### ISSUE TITLE
Scanning over (named) tuples

### ISSUE THREAD

**Issue by jeffgortmaker** [google/jax#1745]
Is there a nice way to retain the structure of the objects that `jax.lax.scan` and `jax.lax.map` etc. loop over without resorting to using arrays?

For example the below code that loops over rows in an array works fine:

```python
xs = jax.numpy.eye(2)
sums = jax.lax.map(lambda x: x[0] + x[1], xs)
```

But for cases when the objects I'm looping over have a lot of different types of (nested) information, I'd prefer to organize `xs` as, e.g. named tuples. This is where I'm having some trouble:

```python
Point = collections.namedtuple('Point', ['a', 'b'])
xs = (Point(1, 0), Point(0, 1))
sums = jax.lax.map(lambda x: x.a + x.b, xs)
```

This raises

    ValueError: scan got value with no leading axis to scan over: [1, 0, 0, 1].

because `jax.lax.scan` flattens the tuples.

I'm hoping the solution is something simple that already exists in this (wonderful) package!

**Comment by shoyer** [comment]
You can use labeled data structures, but you have to write things a little differently:
```
Point = collections.namedtuple('Point', ['a', 'b'])
xs = Point(*jax.numpy.eye(2))
sums = jax.lax.map(lambda x: x.a + x.b, xs)
```

Looking at `xs` may be helpful:
```
Point(a=array([1., 0.], dtype=float32), b=array([0., 1.], dtype=float32))
```

map still needs arrays to scan over, but those can be nested inside of another structure.

**Comment by jeffgortmaker** [comment]
Perfect, thanks!

For anyone else trying to wrap their head around how nested data needs to be structured, here's an example with two levels:

```python
Point = collections.namedtuple('Point', ['subpoint', 'b'])
Subpoint = collections.namedtuple('Subpoint', ['c', 'd'])

subpoints = Subpoint(jax.numpy.array([1, 2]), jax.numpy.array([3, 4]))
points = Point(subpoints, jax.numpy.array([5, 6]))

sums = jax.lax.map(lambda p: p.subpoint.c * p.subpoint.d + p.b, points)
```
