### ISSUE TITLE
You all got any of those sweet, sweet v0.4.15 cuda12 wheels?

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#17455]
👋 I'd love to try out pallas, but v0.4.14 is jamming me up.

**Comment by hawkinsp** [comment]
We had to yank 0.4.15 because of a minor problem with the release. We should release 0.4.16 this week, with any luck.

**Comment by sschoenholz** [comment]
Amazing, thanks @hawkinsp!

**Comment by sharadmv** [comment]
@sschoenholz if you want to get started ASAP, I wrote a little guide on how to install it/setup or you can try it in Colab: https://github.com/google/jax/discussions/17367#discussioncomment-6880177

**Comment by sschoenholz** [comment]
Ah, this looks awesome. Thanks @sharadmv. Out of curiosity, do you all have any idea what your timeline is like for a clean install if I was interested in having a pallas kernel in e.g. jaxmd?

**Comment by sharadmv** [comment]
We're mostly blocked on a clean Triton release. Once that is out, we don't need to pin to a Triton nightly and can release JAX+JAX-Triton pinned to the PyPI release.

**Comment by jakevdp** [comment]
I think this can be closed, because jax 0.4.16 was released with CUDA 12 wheels; installation instructions are here: https://jax.readthedocs.io/en/latest/installation.html

Please let us know if other related issues come up!
