### ISSUE TITLE
JAX uses the first CUDA libraries found in `LD_LIBRARY_PATH` instead of the bundled CUDA libraries installed by pip

### ISSUE THREAD

**Issue by olokshyn** [google/jax#17497]
### Description

# Problem

## Description
Most CUDA-enabled systems tend to have CUDA libraries' directory paths added to `LD_LIBRARY_PATH` automatically by a `~/.bashrc` script, or similar.

When installed through [the pip installation option with CUDA installed via pip](https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier), JAX doesn't use the CUDA libraries installed by pip. Instead, JAX uses whatever CUDA libraries it finds first when searching through the directories specified in the `LD_LIBRARY_PATH` variable.

This is confusing, as when I use the pip installation option that also installs CUDA, I expect JAX to use the bundled CUDA instead of any other, possibly older and incompatible, CUDA version I have on the system.

Notably, PyTorch with CUDA installation handles this case as expected, see details below.

## Expected result

- If JAX was installed using [the pip installation option that also installs CUDA](https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier), then JAX should use the CUDA libraries that were installed by pip during the JAX installation, disregarding the value of the `LD_LIBRARY_PATH` variable.
- If JAX was installed using [the pip installation option without CUDA](https://github.com/google/jax#pip-installation-gpu-cuda-installed-locally-harder), then JAX should use the first CUDA libraries it finds when searching through the directories in the `LD_LIBRARY_PATH` variable.

# Reproduction
As I understand, CUDA libraries can come from the driver installation or the toolkit installation:
- `libcuda.so`: CUDA Driver API library. Installed by the NVIDIA driver installation. It is **not** included with the CUDA Toolkit distributed with JAX.
- `libcudart.so`: CUDA Runtime API library. It is included with the CUDA Toolkit distributed with JAX.

The problem is that JAX ignores `libcudart.so` that was installed by pip and uses the first `libcudart.so` it finds on `LD_LIBRARY_PATH`.

Create a clean Python 3.10 conda environment and activate it:
```bash
(base) olokshyn@NEPTUNE:~$ conda create -n testjax python=3.10 -y
(base) olokshyn@NEPTUNE:~$ conda activate testjax
```

Install JAX with CUDA 12 following the [pip installation: GPU (CUDA, installed via pip, easier)](https://github.com/google/jax#pip-installation-gpu-cuda-installed-via-pip-easier) flow:
```bash
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
<details>
  <summary>Installation output</summary>

```bash
(testjax) olokshyn@NEPTUNE:~$ pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Looking in links: https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
Collecting jax[cuda12_pip]
  Using cached jax-0.4.14-py3-none-any.whl
Collecting ml-dtypes>=0.2.0 (from jax[cuda12_pip])
  Obtaining dependency information for ml-dtypes>=0.2.0 from https://files.pythonhosted.org/packages/d1/1d/d5cf76e5e40f69dbd273036e3172ae4a614577cb141673427b80cac948df/ml_dtypes-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached ml_dtypes-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (20 kB)
Collecting numpy>=1.22 (from jax[cuda12_pip])
  Obtaining dependency information for numpy>=1.22 from https://files.pythonhosted.org/packages/71/3c/3b1981c6a1986adc9ee7db760c0c34ea5b14ac3da9ecfcf1ea2a4ec6c398/numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (5.6 kB)
Collecting opt-einsum (from jax[cuda12_pip])
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Collecting scipy>=1.7 (from jax[cuda12_pip])
  Obtaining dependency information for scipy>=1.7 from https://files.pythonhosted.org/packages/a8/cc/c36f3439f5d47c3b13833ce6687b43a040cc7638c502ac46b41e2d4f3d6f/scipy-1.11.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached scipy-1.11.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (59 kB)
Collecting jaxlib==0.4.14+cuda12.cudnn89 (from jax[cuda12_pip])
  Using cached https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.14%2Bcuda12.cudnn89-cp310-cp310-manylinux2014_x86_64.whl (191.3 MB)
Collecting nvidia-cublas-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cublas-cu12 from https://files.pythonhosted.org/packages/b6/6a/e8cca34f85b18a0280e3a19faca1923f6a04e7d587e9d8e33bc295a52b6d/nvidia_cublas_cu12-12.2.5.6-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cublas_cu12-12.2.5.6-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cuda-cupti-cu12 from https://files.pythonhosted.org/packages/cf/27/7c2f33b4fbab658117fce3b029f44cce7886fc5a50f526a81b4b0436af02/nvidia_cuda_cupti_cu12-12.2.142-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_cupti_cu12-12.2.142-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvcc-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cuda-nvcc-cu12 from https://files.pythonhosted.org/packages/a7/a5/1b48eeda9bdc3ac5bf00d84eca6f31b568ab3da9008f754bf1fdd98ee97b/nvidia_cuda_nvcc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_nvcc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cuda-runtime-cu12 from https://files.pythonhosted.org/packages/95/46/6361d45c7a6fe3b3bb8d5fa35eb43c1dcd12d14799a0dc6faef3d76eaf41/nvidia_cuda_runtime_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_runtime_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cudnn-cu12>=8.9 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cudnn-cu12>=8.9 from https://files.pythonhosted.org/packages/fa/d7/f46bd08337201ec875bda25e29fcb65d26bdc6d0be306dc33fc0b092faa6/nvidia_cudnn_cu12-8.9.4.25-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cudnn_cu12-8.9.4.25-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cufft-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cufft-cu12 from https://files.pythonhosted.org/packages/8f/86/311c32926aa321ebc169d6c910a1ecd30339ae198014e0d4a7cf448f6ce9/nvidia_cufft_cu12-11.0.8.103-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cufft_cu12-11.0.8.103-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cusolver-cu12 from https://files.pythonhosted.org/packages/1f/af/29126e0bae18bad59fe4018c2e32fd5d7ec0aa354a4b1e08c051515a25d1/nvidia_cusolver_cu12-11.5.2.141-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cusolver_cu12-11.5.2.141-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12 (from jax[cuda12_pip])
  Obtaining dependency information for nvidia-cusparse-cu12 from https://files.pythonhosted.org/packages/a9/b4/21af603eba3a803276bbcbbc41d6cf3a20919a2807217084cacef13ec779/nvidia_cusparse_cu12-12.1.2.141-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cusparse_cu12-12.1.2.141-py3-none-manylinux1_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cuda-nvrtc-cu12 (from nvidia-cudnn-cu12>=8.9->jax[cuda12_pip])
  Obtaining dependency information for nvidia-cuda-nvrtc-cu12 from https://files.pythonhosted.org/packages/cb/84/bb975ca63e3d4017824ad3d62e141db8492bc53cec6dc84705fb0650c22d/nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-nvjitlink-cu12 (from nvidia-cusolver-cu12->jax[cuda12_pip])
  Obtaining dependency information for nvidia-nvjitlink-cu12 from https://files.pythonhosted.org/packages/0a/f8/5193b57555cbeecfdb6ade643df0d4218cc6385485492b6e2f64ceae53bb/nvidia_nvjitlink_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata
  Using cached nvidia_nvjitlink_cu12-12.2.140-py3-none-manylinux1_x86_64.whl.metadata (1.5 kB)
Using cached ml_dtypes-0.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
Using cached numpy-1.25.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Using cached nvidia_cudnn_cu12-8.9.4.25-py3-none-manylinux1_x86_64.whl (720.1 MB)
Using cached scipy-1.11.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (36.3 MB)
Using cached nvidia_cublas_cu12-12.2.5.6-py3-none-manylinux1_x86_64.whl (417.8 MB)
Using cached nvidia_cuda_cupti_cu12-12.2.142-py3-none-manylinux1_x86_64.whl (13.9 MB)
Using cached nvidia_cuda_nvcc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (21.3 MB)
Using cached nvidia_cuda_runtime_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (845 kB)
Using cached nvidia_cufft_cu12-11.0.8.103-py3-none-manylinux1_x86_64.whl (98.6 MB)
Using cached nvidia_cusolver_cu12-11.5.2.141-py3-none-manylinux1_x86_64.whl (124.9 MB)
Using cached nvidia_cusparse_cu12-12.1.2.141-py3-none-manylinux1_x86_64.whl (195.3 MB)
Using cached nvidia_cuda_nvrtc_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (23.4 MB)
Using cached nvidia_nvjitlink_cu12-12.2.140-py3-none-manylinux1_x86_64.whl (20.2 MB)
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-nvcc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, numpy, scipy, opt-einsum, nvidia-cusparse-cu12, nvidia-cudnn-cu12, ml-dtypes, nvidia-cusolver-cu12, jaxlib, jax
Successfully installed jax-0.4.14 jaxlib-0.4.14+cuda12.cudnn89 ml-dtypes-0.2.0 numpy-1.25.2 nvidia-cublas-cu12-12.2.5.6 nvidia-cuda-cupti-cu12-12.2.142 nvidia-cuda-nvcc-cu12-12.2.140 nvidia-cuda-nvrtc-cu12-12.2.140 nvidia-cuda-runtime-cu12-12.2.140 nvidia-cudnn-cu12-8.9.4.25 nvidia-cufft-cu12-11.0.8.103 nvidia-cusolver-cu12-11.5.2.141 nvidia-cusparse-cu12-12.1.2.141 nvidia-nvjitlink-cu12-12.2.140 opt-einsum-3.3.0 scipy-1.11.2
```

</details>

Check that JAX uses the bundled `libcudart.so` when `LD_LIBRARY_PATH` is empty:
```bash
(testjax) olokshyn@NEPTUNE:~$ export LD_LIBRARY_PATH=""
(testjax) olokshyn@NEPTUNE:~$ strace -f python -c "import jax; jax.numpy.array([1, 2, 3]);" 2>&1 | grep -v ENOENT | grep libcudart
openat(AT_FDCWD, "/home/olokshyn/anaconda3/envs/testjax/lib/python3.10/site-packages/jaxlib/../nvidia/cuda_runtime/lib/libcudart.so.12", O_RDONLY|O_CLOEXEC) = 3
```

Above, we can see JAX correctly using the bundled `libcudart.so` library from `~/anaconda3/envs/testjax/lib/python3.10/site-packages/nvidia/cuda_runtime/lib/libcudart.so.12`.

My system has a CUDA toolkit installed in `/usr/local/cuda/lib64`. You can see that the toolkit was installed back in May, so it was not installed by pip:
```bash
(testjax) olokshyn@NEPTUNE:~$ ll /usr/local/cuda/lib64/libcudart.so
lrwxrwxrwx 1 root root 15 May  1 04:31 /usr/local/cuda/lib64/libcudart.so -> libcudart.so.12
```

If we point `LD_LIBRARY_PATH` to a directory containing the CUDA toolkit libraries, JAX uses them instead of the bundled CUDA libraries:
```bash
(testjax) olokshyn@NEPTUNE:~$ export LD_LIBRARY_PATH=/usr/local/cuda/lib64
(testjax) olokshyn@NEPTUNE:~$ strace -f python -c "import jax; jax.numpy.array([1, 2, 3]);" 2>&1 | grep -v ENOENT | grep libcudart
openat(AT_FDCWD, "/usr/local/cuda/lib64/libcudart.so.12", O_RDONLY|O_CLOEXEC) = 3
```

Now, JAX uses some other CUDA library from `/usr/local/cuda/lib64/libcudart.so.12` that might be incompatible with the installed JAX version.

# The inevitable PyTorch comparison :)
PyTorch comes with a bundled CUDA and uses it disregarding the value of the `LD_LIBRARY_PATH` variable.

Create a new conda environment and install torch:
```bash
(base) olokshyn@NEPTUNE:~$ conda create -n testtorch python=3.10 -y
(base) olokshyn@NEPTUNE:~$ conda activate testtorch
(testtorch) olokshyn@NEPTUNE:~$ pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
```

Set `LD_LIBRARY_PATH` to some other CUDA Toolkit installation and check that torch still uses the CUDA libraries bundled with it:
```bash
(testtorch) olokshyn@NEPTUNE:~$ export LD_LIBRARY_PATH=/usr/local/cuda/lib64
(testtorch) olokshyn@NEPTUNE:~$ strace -f python -c "import torch; torch.tensor([1, 2, 3], device='cuda');" 2>&1 | grep -v ENOENT | grep libcudart
openat(AT_FDCWD, "/home/olokshyn/anaconda3/envs/testtorch/lib/python3.10/site-packages/torch/lib/libcudart-9335f6a2.so.12", O_RDONLY|O_CLOEXEC) = 3
```

Above, we can see torch using `~/anaconda3/envs/testtorch/lib/python3.10/site-packages/torch/lib/libcudart-9335f6a2.so.12` instead of `/usr/local/cuda/lib64/libcudart.so.12` that is specified in `LD_LIBRARY_PATH`.

### What jax/jaxlib version are you using?

jax==0.4.14, jaxlib==0.4.14+cuda12.cudnn89

### Which accelerator(s) are you using?

NVIDIA GeForce RTX 2080 Ti, Driver Version: 535.54.03, CUDA Version: 12.2

### Additional system info

Python 3.10, Ubuntu 22.04.2 LTS

### NVIDIA GPU info

```bash
(testjax) olokshyn@NEPTUNE:~$ nvidia-smi
Thu Sep  7 18:33:13 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.54.03              Driver Version: 535.54.03    CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2080 Ti     Off | 00000000:0E:00.0  On |                  N/A |
|  0%   46C    P8              18W / 300W |    565MiB / 11264MiB |     20%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      2146      G   /usr/lib/xorg/Xorg                          342MiB |
|    0   N/A  N/A      2294      G   /usr/bin/gnome-shell                         60MiB |
|    0   N/A  N/A      4805      G   ...,WinRetrieveSuggestionsOnlyOnDemand       50MiB |
|    0   N/A  N/A      5069      G   ...47012894,5011754882495144318,262144       79MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment]
I'm not sure I consider this a bug.

If you're interested in why this happens: JAX sets a field called `RUNPATH` on its shared libraries, which specifies an additional search path for dependent shared libraries. Notably `RUNPATH` comes lower in the search priority order than the `LD_LIBRARY_PATH` environment variable. This is arguably a good thing: it allows users and system administrators to override the choice of libraries if they want.

There is another field that can be set instead called `RPATH`, which also adds an additional search path, but does so at a *higher* priority than the `LD_LIBRARY_PATH` environment variable. I would guess (but have not personally confirmed) that is what PyTorch is setting. There is no mechanism to override an `RPATH`, even if you wanted to, bar tools like `patchelf`.

JAX on CUDA can be installed in two modes: `cuda12_pip`, which installs the CUDA dependencies as `pip` packages, and `cuda12_local`, which does not and relies on the user having the right libraries installed. The `jaxlib` binaries we ship is the same in both cases.

For `jaxlib` to be able to locate the `pip`-installed NVIDIA libraries, `jaxlib` sets `RUNPATH` on its shared libraries to the relative location of the CUDA libraries when `pip`-installed. If the `pip` packages aren't installed, this likely doesn't do much because the libraries won't be present: we'll fall back searching `LD_LIBRARY_PATH`.

It would be possible to change `jax` to set `RPATH` instead of `RUNPATH`, but the catch would be that then if the CUDA `pip` packages were installed, then we would use them always and there would be no way to override that choice for development or by a system administrator. If you had the CUDA `pip` packages installed but needed to use another CUDA installation, you'd be forced to uninstall the CUDA pip packages.

`RPATH` is also deprecated, according to some authorities: https://akkadia.org/drepper/dsohowto.pdf

Is there a reason that it doesn't suffice simply not to set `LD_LIBRARY_PATH`? i.e., just don't override JAX's choice? That's the point of `LD_LIBRARY_PATH` --- to override the app's choice!

**Comment by liukidar** [comment]
I agree that the lack of clarity is the main issue here.

The fact the JAX behaves differently from PyTorch in such a common scenario is already a reason to think about what's going on. I also believe that since there are already two packages provided (i.e., pip and local) the user has already the ability to chose the behaviour of JAX with regard to LD_LIBRARY_PATH and so, maybe, the pip version shouldn't be affected by its value (if I'm a new user and I download the "easy-to-use" cuda1x_pip version I expect it to work out of the box, independently of how the system administrator configured my machine).

**Comment by nico-bohlinger** [comment]
In my case I had to import jax first and do an initial computation before importing tensorflow, otherwise tensorflow would set the wrong cudnn version and I would get `jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed` afterwards

**Comment by hawkinsp** [comment]
I'll note that *none* of these things will help if you try to import two libraries that want different CUDA/CuDNN versions. Irrespective of how we do things, whichever library you import first will "win".

If you just want TF for a data pipieline, I recommend the `tensorflow-cpu` package!

**Comment by hawkinsp** [comment]
I suspect that https://github.com/google/jax/commit/9404518201c5ac8af6c85ecdf12a7cc34c102585 will help catch this case. We will now raise an exception if we detect that the versions of the CUDA libraries loaded are too old, which would happen if you override the `LD_LIBRARY_PATH` to point to an old version.

**Comment by tljstewart** [comment]
`rpath` is not overridden by `LD_LIBRARY_PATH` ; while `runpath` can be overridden by `LD_LIBRARY_PATH` 

why set `rpath` for `jax[cuda12_local]` .. the whole purpose for `local` is linking local .so ... currently if you install torch gpu sudden `jax[cuda12_local] is no longer local 

just don't set `rpath` on `jax[cuda12_local]`  wheels
