### ISSUE TITLE
Raise error when using `jax.grad` with instance methods

### ISSUE THREAD

**Issue by neel04** [google/jax#17532]
When using `jax.grad`, we differentiate w.r.t the first argument.

However, when we use some instance method:

```py
class test:
    def __init__(self, ...):
        ...
     
    @jax.value_and_grad 
    def compute_loss(self, model, ...):
        ...
    
    loss, grads = compute_loss(...)
```

The first argument is `self`, so the `grads` with be `None`.

This shouldn't be silent - there should be some error mechanism which detects this error and informs the user (As a `warning` perhaps that the `grads` with be `None`) or a straight-up error if we detect both `self` and `None` grads as there's no use-case where the user would want this.

This could possibly save hours of debugging time 😄

**Comment by patrick-kidger** [comment]
Side note, I'd recommend [Equinox](https://github.com/patrick-kidger/equinox) if you're trying to do any sort of JAX-with-classes, as it's designed to makes the two interop smoothly.

**Comment by mattjj** [comment]
Thanks for the suggestion! This is already an error though:

```python
import jax

class test:
  @jax.value_and_grad
  def foo(self, x):
    return 3.0

test().foo(1.0)
```

```
mattjj at mattjj1 in ~/packages/jax on main ?
○ PYTHONPATH=. python 17532.py                                                                                                                                                (base)
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/mattjj/packages/jax/17532.py", line 8, in <module>
    test().foo(1.0)
TypeError: Argument '<__main__.test object at 0x7fd91c1fff40>' of type <class '__main__.test'> is not a valid JAX type.
```

There must be something else going on in your code which made it not an error. Can you share a runnable repro?

**Comment by neel04** [comment]
Apologies @mattjj the problem is with equinox's `filter_value_and_grad` - I assumed that it was just a wrapper for `jax.value_and_grad`; I should've investigated further.

@patrick-kidger Since you're here already:

```py
In [1]: import equinox as eqx

In [2]: import jax
   ...:
   ...: class test:
   ...:   @eqx.filter_value_and_grad
   ...:   def foo(self, x):
   ...:     return 3.0
   ...:
   ...: test().foo(1.0)
Out[2]: (3.0, None)
```

Is the problem. A warning might be effective here - that the value passed can't be handled by `Jax`, as well as printing out  the object in question :)

Once again, sorry for opening the issue in the wrong place. 2 a.m debugging can leave me woozy sometimes

**Comment by neel04** [comment]
@patrick-kidger Thanks for understanding! 😄  I'm busy with school and my project currently - but I'll take a look at it in the weekend. 

Perhaps something as simple as raising a warning if the first arg is `self` would probably be a nice QoL?  "Warning: grad works w.r.t first argument, which is `self` and can potentially lead to `None` grads" - I don't think we need to hide it behind a flag necessarily as passing `self` is 99.9% an instance method...
