### ISSUE TITLE
JAX does not load bundled CUDNN

### ISSUE THREAD

**Issue by mees** [google/jax#17553]
### Description

Somehow JAX does not use the bundled cudnn. How to reproduce:
```
conda create -n debug_jax_cudnn python=3.10
conda activate debug_jax_cudnn
pip install --upgrade "jax[cuda11_pip]==0.4.13" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
export LD_LIBRARY_PATH=""
python -c "import jax; A = jax.numpy.zeros((10, 10));"
```
Error:
```
2023-09-11 18:02:05.062414: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:439] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
  2023-09-11 18:02:05.062576: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:443] Memory usage: 7995392 bytes free, 11721572352 bytes total.
  2023-09-11 18:02:05.062650: E external/xla/xla/stream_executor/cuda/cuda_dnn.cc:453] Possibly insufficient driver version: 510.47.3
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/nfs/kun2/users/oier/miniconda3/envs/debug_jax_cudnn/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 2153, in zeros
      return lax.full(shape, 0, _jnp_dtype(dtype))
...
  jaxlib.xla_extension.XlaRuntimeError: FAILED_PRECONDITION: DNN library initialization failed. Look at the errors above for more details.
```
The nvidia driver is  510.47.3, which should support cuda 11.

### What jax/jaxlib version are you using?

0.4.13

### Which accelerator(s) are you using?

GPU

### Additional system info

Ubuntu 20.04

### NVIDIA GPU info

NVIDIA GeForce GTX 1080 Ti

**Comment by liukidar** [comment]
I'm not 100% I interpret it correctly, but isn't 'Memory usage: 7995392 bytes free' implying that you only have ~8 MB of free memory on your GPU?

**Comment by mees** [comment]
> I'm not 100% sure I interpret it correctly, but isn't 'Memory usage: 7995392 bytes free' implying that you only have ~8 MB of free memory on your GPU?

When I try another GPU I get:
`2023-09-11 22:50:18.801369: E external/xla/xla/service/gpu/gpu_compiler.cc:1423] The CUDA linking API did not work. Please use XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1 to bypass it, but expect to get longer compilation time due to the lack of multi-threading. Original error: INTERNAL: nvlink exited with non-zero error code 256, output: nvlink fatal   : Input file '/tmp/tempfile-grace-e8fbd375-3485130-60523048fe531.cubin' newer than toolkit (118 vs 116)`

**Comment by hawkinsp** [comment]
This should be fixed with jax 0.4.20. JAX will prefer the pip-packaged CUDA libraries if they are present.

**Comment by liukidar** [comment]
I just tried to reinstall 0.4.20 and I still have to set LD_LIBRARY_PATH to "" for it to work. Could there be a conflict with the changes in 0.4.17?
> CUDA: JAX now verifies that the CUDA libraries it finds are at least as new as the CUDA libraries that JAX was built against. If older libraries are found, JAX raises an exception since that is preferable to mysterious failures and crashes.
as without setting LD_LIBRARY_PATH I get
```CUDA backend failed to initialize: Found cuDNN version 8600, but JAX was built against version 8904, which is newer. The copy of cuDNN that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)```

**Comment by Micky774** [comment]
> EDIT: apparently I also have to modify PATH to include the directory containing the 'ptxas" executable installed by Jax as it's not picked up automatically

This should actually be resolved by https://github.com/openxla/xla/pull/7884 for future releases!

**Comment by hawkinsp** [comment]
We think this is fixed! Please comment if you're still having a problem.
