### ISSUE TITLE
Incorrect result for in1d on Apple GPU using jax-metal

### ISSUE THREAD

**Issue by sfc-gh-arozenshteyn** [google/jax#17590]
### Description

Following the build instructions for [`jax-metal`](https://developer.apple.com/metal/jax/), I was able to get JAX to run on the GPU. When I try to run [`in1d`](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.in1d.html), the results do not match numpy, though.

```
In [1]: from jax import numpy as jnp
In [2]: import numpy as np
In [3]: a = jnp.array([123,2,4])
In [4]: b = jnp.array([123,1])
In [5]: jnp.in1d(a,b)
Out[5]: Array([ True,  True,  True], dtype=bool)
In [6]: np.in1d(a,b)
Out[6]: array([ True, False, False])
```

### What jax/jaxlib version are you using?

jax==0.4.11, jaxlib==0.4.10 (from source), jax-metal==0.0.3 

### Which accelerator(s) are you using?

GPU (Apple M1 Max)

**Comment by kulinseth** [comment]
@sfc-gh-arozenshteyn , the latest `jax-metal 0.0.5` version addresses this issue. Can you please verify ?
https://pypi.org/project/jax-metal/

**Comment by benjaminvatterj** [comment]
Hi @kulinseth, I can confirm this is resolved (replacing in1d with isin as the former has been deprecated)
