### ISSUE TITLE
jax.debug.print without terminal newline

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#17636]
Add a way to perform [`jax.debug.print`](https://jax.readthedocs.io/en/latest/_autosummary/jax.debug.print.html) without printing a terminal newline, like `print(string, end="")` in plain Python. Currently, the terminal newline is appended by [this](https://github.com/google/jax/blob/main/jax/_src/debugging.py#L264) line of code inside the function `_format_print_callback`.

**Comment by jakevdp** [comment]
If you want more control, you can always use `jax.debug.callback` to print whatever format you want; e.g.
```python
jax.debug.callback(lambda x: print(x, end=''), x)
```

**Comment by carlosgmartin** [comment]
@jakevdp I guess defining the following function also works:
```python3
def debug_print(string, *args, **kwargs):
    def f(*args, **kwargs):
        print(string.format(*args, **kwargs), end="")
    return jax.debug.callback(f, *args, **kwargs)
```
