### ISSUE TITLE
Device.platform not defined: code breaks after recent change unless one builds new jaxlib not 

### ISSUE THREAD

**Issue by gnecula** [google/jax#1764]
After pulling the latest version I see an error for any execution (`AttributeError: 'jaxlib.xla_extension.CpuDevice' object has no attribute 'platform'`.)

I believe that problem is that #1762 relies on very recent changes in the Tensorflow xla_client (adding Device.platform field in https://github.com/tensorflow/tensorflow/commit/72e362bba74a617dfdd326ecae299a6588247e1a), while I had jaxlib version 0.1.32.

Should we at a minimum upgrade the minimum_jax_lib to 0.1.36 (it is 0.1.31)? 

How is it guaranteed that a jaxlib with 0.1.36 will include a particular change from xla_client, e.g., if one builds from source? 

====
The actual bug is, for `np.sin(3.0)` produces:

```
  File "/Users/necula/Source/jax/jax/lax/lax.py", line 166, in sin
    return sin_p.bind(x)
  File "/Users/necula/Source/jax/jax/core.py", line 150, in bind
    return self.impl(*args, **kwargs)
  File "/Users/necula/Source/jax/jax/interpreters/xla.py", line 141, in apply_primitive
    return compiled_fun(*args)
  File "/Users/necula/Source/jax/jax/interpreters/xla.py", line 189, in _execute_compiled_primitive
    input_bufs = [device_put(x, device) for x in args if x is not token]
  File "/Users/necula/Source/jax/jax/interpreters/xla.py", line 189, in <listcomp>
    input_bufs = [device_put(x, device) for x in args if x is not token]
  File "/Users/necula/Source/jax/jax/interpreters/xla.py", line 85, in device_put
    return device_put_handlers[type(x)](x, device)
  File "/Users/necula/Source/jax/jax/interpreters/xla.py", line 94, in _device_put_array
    return xc.Buffer.from_pyval(x, device, backend=xb.get_device_backend(device))
  File "/Users/necula/Source/jax/jax/lib/xla_bridge.py", line 150, in get_device_backend
    platform = device.platform if device else None
AttributeError: 'jaxlib.xla_extension.CpuDevice' object has no attribute 'platform'
```

**Comment by gnecula** [comment]
BTW, this problem goes away on a recompile from source, presumably also if updating to jaxlib 0.1.36

**Comment by gnecula** [comment]
The remaining questions are:
* How is it guaranteed that a jaxlib with 0.1.36 will include a particular change from xla_client, e.g., if one builds from source?

* What process we need to have to tell that we need to bump the minimum version?

**Comment by hawkinsp** [comment]
For the former question, it is simply a question of looking at the TensorFlow git hash in the `WORKSPACE` file. e.g., right now it is:
https://github.com/google/jax/blob/8547050b09318414190b88d29a2d0914ccc325a3/WORKSPACE#L24
which has git hash `883b5becaced22f7dd9e3c23d9d259f55e087cb5` and which corresponds to https://github.com/tensorflow/tensorflow/commit/883b5becaced22f7dd9e3c23d9d259f55e087cb5

One way to test the latter would be to pin the oldest legal `jaxlib` version in the travis configuration. We'd then see presubmit errors if a `jax` PR required a newer `jaxlib`.
