### ISSUE TITLE
Tfrt logging before absl::InitilalizeLog()

### ISSUE THREAD

**Issue by pranavsetpal** [google/jax#17664]
### Description

In the latest version, if I simply run `jax.devices()`, `tfrt_cpu_pjrt_client.cc` logs when the device creation and destroyed. Ideally these logs should run after absl has been initialized

![image](https://github.com/google/jax/assets/68775426/4fadcfcc-1fa5-42e2-bdf6-ace0feda9435 "JAX 0.4.16")
![image](https://github.com/google/jax/assets/68775426/8467fdf3-45be-465e-b729-639fc56fa2e9 "JAX 0.4.14")

### What jax/jaxlib version are you using?

v0.4.16

### Which accelerator(s) are you using?

CPU

### Additional system info

Python: 3.11.5; OS: Linux (Endeavour OS)

**Comment by hawkinsp** [comment]
This is fixed at XLA head.

**Comment by hawkinsp** [comment]
Fixed by jaxlib 0.4.17.
