### ISSUE TITLE
module 'jaxlib.xla_client' has no attribute 'register_cpu_custom_call_target'

### ISSUE THREAD

**Issue by joamatab** [google/jax#17662]
### Description

```
module 'jaxlib.xla_client' has no attribute 'register_cpu_custom_call_target'
```

https://github.com/gdsfactory/gplugins/actions/runs/6230788778

@flaport

### What jax/jaxlib version are you using?

jax 0.4.16 jaxlib 0.4.16

### Which accelerator(s) are you using?

CPU

### Additional system info

Linux

**Comment by hawkinsp** [comment]
Sorry for the breakage.

You'll need to update the caller to use `register_custom_call_target` instead.

APIs under `jaxlib` aren't technically public, so some breakage is possible. We're working on a more stable custom kernel API.

**Comment by hawkinsp** [comment]
Closing because there's no action for us here.
