### ISSUE TITLE
No replication rule for erf

### ISSUE THREAD

**Issue by shoyer** [google/jax#17691]
### Description

I'm getting the following error from shard_map:

NotImplementedError: No replication rule for erf. As a workaround, pass the `check_rep=False` argument to `shard_map`. To get this fixed, open an issue at [https://github.com/google/jax/issues](https://www.google.com/url?q=https://github.com/google/jax/issues&sa=D)

**Comment by jwnys** [comment]
I am getting this error for: "No replication rule for **custom_linear_solve**"

**Comment by mattjj** [comment]
@jwnys that one was fixed by #22543; it was also opened as #20162.
