### ISSUE TITLE
jnp.asarray making copies in latest jax

### ISSUE THREAD

**Issue by mattbarrett98** [google/jax#17702]
### Description

```python 
import numpy as np
import jax.numpy as jnp
import os, psutil

process = psutil.Process(os.getpid())
print(process.memory_info().rss / 1e9)  # 0.1 GB
x = np.random.uniform(0, 1, (10000, 20000)).astype("float32")
print(process.memory_info().rss / 1e9)  # 0.9 GB
y = jnp.asarray(x)
print(process.memory_info().rss / 1e9)  # 1.7 GB
```

In version 0.4.16, `jnp.asarray` now seems to be making copies when called on numpy arrays. In earlier versions, it would just reuse the underlying data and no (little) extra memory would be consumed. Is this intended?

### What jax/jaxlib version are you using?

jax, jaxlib 0.4.16

### Which accelerator(s) are you using?

CPU

**Comment by hawkinsp** [comment]
I think not copying (while it has only ever been best effort) is an important optimization.

**Comment by yashk2810** [comment]
https://github.com/google/jax/pull/17721 should fix

**Comment by mattbarrett98** [comment]
Thanks guys! before the next release is there another way of converting without copies?

**Comment by jakevdp** [comment]
If you want to convert a numpy array to a jax array without copying in version 0.4.16, you can use `y = jax.device_put(x)`

This will only be avoid copies if using a CPU device, and if your numpy array's byte alignment is compatible with XLA.
