### ISSUE TITLE
Jaxlib v0.1.64 through v0.3.10 deleted from PyPI?

### ISSUE THREAD

**Issue by rameshvarun** [google/jax#17717]
### Description

A number of Jaxlib releases seem to have been deleted from PyPI - is there any info on why this is the case? Is there a reason why they weren't yanked instead?

Current Version History: https://pypi.org/project/jaxlib/#history
![image](https://github.com/google/jax/assets/889879/db579f38-051c-4af2-95b5-3767606f34ed)

Archived History: https://web.archive.org/web/20230418134637/https://pypi.org/project/jaxlib/#history

**Comment by yashk2810** [comment]
They were deleted because there was no more storage available for jaxlib wheels.

They are still available on this index: https://storage.googleapis.com/jax-releases/jax_releases.html that you can download from.
