### ISSUE TITLE
document why jnp.arange (like np.arange) is unsafe with `step`

### ISSUE THREAD

**Issue by mattjj** [google/jax#17723]
The NumPy docs explain why using `np.arange` with the `step` argument is difficult to use correctly. As @jewillco observed, it's even more dangerous with the lower-precision dtypes that JAX users might employ (like fp8 and bf16).

So we should:
1. add a note to the `jnp.arange` docs warning about the dangers (perhaps mainly pointing to the NumPy docs' explanation), and
2. suggest an additional workaround not involving linspace (i.e. just write an expression like `(jnp.arange(-600, 600, dtype=float) * .01).astype(jnp.bfloat16)`.

**Comment by alhridoy** [comment]
Hi @mattjj  I made the changes and created a PR, Please check this out.
