### ISSUE TITLE
Inaccurate `jax.scipy.special.polygamma`

### ISSUE THREAD

**Issue by Gattocrucco** [google/jax#17738]
### Description

For some inputs, `polygamma` is inaccurate. This bug appeared in 0.4.16, and could be related to #17734.

```python
from jax import config
config.update("jax_enable_x64", True)

from jax.scipy import special as jspecial
from scipy import special

k = 1
x = 2.0

print('jax:  ', jspecial.polygamma(k, x).item())
print('scipy:', special.polygamma(k, x))
```

```
jax:   0.6449342001492976
scipy: 0.6449340668482266
```

### What jax/jaxlib version are you using?

jax 0.4.16, jaxlib 0.4.16

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11.2, macOS 13.4

**Comment by jakevdp** [comment]
Thanks for the report. `jax.scipy.special.polygamma` calls directly into XLA's Polygamma operation, so the best place to file this issue would be at https://github.com/openxla/xla

**Comment by rajasekharporeddy** [comment]
Hi @Gattocrucco 

This issue appears to be resolved. I tested the mentioned code with JAX 0.4.26 on Google Colab. The results produced by `JAX` closely match those of `SciPy` and `mpmath` up to 15 decimal places.

```python
from jax import config
config.update("jax_enable_x64", True)

from jax.scipy import special as jspecial
from scipy import special
import mpmath

k = 1
x = 2.0

print('jax   :', jspecial.polygamma(k, x).item())
print('scipy :', special.polygamma(k, x))
print('mpmath:', mpmath.polygamma(k, x))
```
Output:
```
jax   : 0.6449340668482265
scipy : 0.6449340668482266
mpmath: 0.644934066848226
```

Please find the [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/e24ad7c94ecf3355969e3dec73022a0d/-17738.ipynb) for reference.

Thank you.

**Comment by jakevdp** [comment]
Thanks for following up!
