### ISSUE TITLE
Cannot use multiple PRNG implementations in the same process due to _check_prng_key using default.

### ISSUE THREAD

**Issue by m01** [google/jax#17743]
### Description

I'd like to use two different jax PRNG implementations in the same process. This should be possible it seems, because I can pass an `impl=` kwarg to jax.PRNGKey ([docs link](https://jax.readthedocs.io/en/latest/_autosummary/jax.random.PRNGKey.html#jax.random.PRNGKey)).

However, the `_check_prng_key(key)` function always uses the default implementation: https://github.com/google/jax/blob/main/jax/_src/random.py#L76, leading to shape errors, e.g.:

```
<user code>
  self._key, subkey = jax.random.split(self._key)
jax/_src/random.py, in split
  key, wrapped = _check_prng_key(key)
_src/random.py", in _check_prng_key
  wrapped_key = prng.random_wrap(key, impl=default_prng_impl())
_src/prng.py", in random_wrap
  _check_prng_key_data(impl, base_arr)
_src/prng.py", in _check_prng_key_data
      raise TypeError("JAX encountered invalid PRNG key data: expected key_data.shape to "
TypeError: JAX encountered invalid PRNG key data: expected key_data.shape to end with (4,); got shape=(2,) for impl=PRNGImpl(key_shape=(4,), seed=<function _rbg_seed at 0xhex>, split=<function _rbg_split at 0xhex>, random_bits=<function _rbg_random_bits at 0xhex>, fold_in=<function _rbg_fold_in at 0xhex>, tag='rbg')

```

### What jax/jaxlib version are you using?

latest

### Which accelerator(s) are you using?

GPU

**Comment by jakevdp** [comment]
Hi, thanks for the report. This is working as designed.

If you want to use multiple prng implementations in a single runtime, you have to use typed PRNG keys (see [JEP 9263](https://jax.readthedocs.io/en/latest/jep/9263-typed-keys.html)). We're just about to update the main docs to recommend these over the old-style keys (see #17741).

**Comment by m01** [comment]
Thanks, that does seem to work.
