### ISSUE TITLE
vmap gives the most bizarre error

### ISSUE THREAD

**Issue by half-potato** [google/jax#17747]
The code snippet is a little complex and I can't post it, but if vmap simply checked how many arguments were passed to a function and compared it to the length of `in_axes`, you would never fill a screen with the following cryptic error:
![image](https://github.com/google/jax/assets/3977802/2cc353e3-a753-4dda-b37b-c9ef8d17fecd)

**Comment by half-potato** [comment]
Okay so this happened because I fed a very large tuple to a batch argument instead of an array. I still don't understand how to feed an array of PRNGKeys to a vmapped function.

**Comment by jakevdp** [comment]
(side-note: using large tuples or lists of values in JAX is not recommended, because it will lead to very long compilation and execution times. You should use arrays of values instead)

**Comment by half-potato** [comment]
I literally couldn't scroll up to see where the error began because this went on for 2k+ lines. It was not useful for debugging. I think it should be, at the very least, truncated.

**Comment by rajasekharporeddy** [comment]
Hi @half-potato 

Looks like this issue has been resolved by improving the error message with the PR #18550. Now the error message for the repro provided by @jakevdp is raised as follows:

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-12-50e10c8cad06>](https://localhost:8080/#) in <cell line: 8>()
      6 
      7 x = tuple(range(1000))
----> 8 jax.vmap(f, in_axes=(0,))(x, 0)

    [... skipping hidden 1 frame]

[/usr/local/lib/python3.10/dist-packages/jax/_src/api.py](https://localhost:8080/#) in vmap_f(*args, **kwargs)
   1247   def vmap_f(*args, **kwargs):
   1248     if isinstance(in_axes, tuple) and len(in_axes) != len(args):
-> 1249       raise ValueError("vmap in_axes must be an int, None, or a tuple of entries corresponding "
   1250                        "to the positional arguments passed to the function, "
   1251                        f"but got {len(in_axes)=}, {len(args)=}")

ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments passed to the function, but got len(in_axes)=1, len(args)=2
```
Attaching the [gist](https://colab.research.google.com/gist/rajasekharporeddy/c61ccc48e190b65125ffe52cebf08c61/-17747.ipynb) for reference.

Could you please verify the same for your use case and let us know if the issue still exists.

Thank you.

**Comment by jakevdp** [comment]
Thanks for the follow up @rajasekharporeddy! I think this can be closed.
