### ISSUE TITLE
AttributeError: module 'jax' has no attribute 'Array'

### ISSUE THREAD

**Issue by fangkaiqi** [google/jax#17748]
### Description

My trouble happens when I try to repoduce the article,code and the article is from https://github. com/peterparity/symder.

After install jaxlib and jax, I try to run the code,it reported  " AttributeError: module 'jax' has no attribute 'Array'".

PS C:\Users\fkq\Desktop\symder-master\symder-master> & D:/Users/fkq/anaconda3/envs/fkq1/python.exe c:/Users/fkq/Desktop/symder-master/symder-master/nlse_1d_model_embed.py
Traceback (most recent call last):
  File "c:/Users/fkq/Desktop/symder-master/symder-master/nlse_1d_model_embed.py", line 6, in <module>
    import haiku as hk
  File "D:\Users\fkq\anaconda3\envs\fkq1\lib\site-packages\haiku\__init__.py", line 19, in <module>
    from haiku import data_structures
  File "D:\Users\fkq\anaconda3\envs\fkq1\lib\site-packages\haiku\data_structures.py", line 21, in <module>
    from haiku._src.filtering import filter  # pylint: disable=redefined-builtin
  File "D:\Users\fkq\anaconda3\envs\fkq1\lib\site-packages\haiku\_src\filtering.py", line 51, in <module>
    predicate: Callable[[str, str, jax.Array], bool],
AttributeError: module 'jax' has no attribute 'Array'

### What jax/jaxlib version are you using?

jax 0.3.2 jaxlib 0.3.2  

### Which accelerator(s) are you using?

GPU

### Additional system info

python 3.7

**Comment by jakevdp** [comment]
`jax.Array` was added in JAX version 0.4.1, so to run this code you’ll need to update your JAX version. Note that JAX 0.4.1 requires Python 3.8 or newer, so you’ll need to update your Python version in order to install a newer JAX version. You can read more about api changes and version requirements in the change log: https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-1-dec-13-2022

**Comment by fangkaiqi** [comment]
> `jax.Array` was added in JAX version 0.4.1, so to run this code you’ll need to update your JAX version. Note that JAX 0.4.1 requires Python 3.8 or newer, so you’ll need to update your Python version in order to install a newer JAX version. You can read more about api changes and version requirements in the change log: https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-1-dec-13-2022

thank you so much

**Comment by jakevdp** [comment]
> The author used jax.Array which needs jax>0.4.1, while he used jax.tree_util.pytree.

I don't know what to tell you: from this description, it doesn't sound like that code is not runnable under any released version of JAX. I would get in touch with the code's author to ask how to run it.
