### ISSUE TITLE
ImportError: ..... ____chkstk_darwin

### ISSUE THREAD

**Issue by ljmartin** [google/jax#1782]
Hi folks,
Wondering if someone can please help with this import error on a fresh install. 

Background: Recently started a new conda environment with a couple of basics like jupyter, numpy, scipy. I'm using MacOS High Sierra 10.13.4, and python3.7

The specific error is:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-77da20ac745a> in <module>
----> 1 from jax import vmap # for auto-vectorizing functions
      2 from functools import partial # for use with vmap
      3 from jax import jit # for compiling functions for speedup
      4 from jax import random # stax initialization uses jax.random
      5 from jax.experimental import stax # neural network library
```
...

```
~/miniconda3/envs/lew_jax/lib/python3.7/site-packages/jaxlib/xla_client.py in <module>
     36 # and TensorFlow may fail with duplicate protocol buffer message definitions.
     37 
---> 38 from . import xla_extension as _xla
     39 from .xla_extension import ops
     40 

ImportError: dlopen(/Users/lmar3213/miniconda3/envs/lew_jax/lib/python3.7/site-packages/jaxlib/xla_extension.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: /Users/lmar3213/miniconda3/envs/lew_jax/lib/python3.7/site-packages/jaxlib/xla_extension.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/lmar3213/miniconda3/envs/lew_jax/lib/python3.7/site-packages/jaxlib/xla_extension.so
```

To install, I ran as per the installation instructions i.e. `pip install --upgrade pip` which was already up to date, and then `pip install --upgrade jax jaxlib` which installed happily. 

The only clue I have as to understanding the error is that it mentions `xla_extension.so` was built for mac OS X 10.15 but Im on 10.13. Any help is appreciated! Thankyou!

**Comment by hawkinsp** [comment]
I believe that #1807 will fix this once we make a new `jaxlib` release.

**Comment by DylanMuir** [comment]
@hawkinsp Thanks for the update. In the meantime, which version of jax and jaxlib should we use on OSX 10.13?

**Comment by Razcle** [comment]
Any update on which versions to use on OXS 10.13? Im running into the same issues. thanks!

**Comment by hawkinsp** [comment]
You'll need to wait for us to build a new wheel, which should hopefully happen today.

**Comment by Razcle** [comment]
ok thanks

**Comment by hawkinsp** [comment]
I pushed new `jaxlib` Mac wheels (0.1.37). Could you please try them out and confirm they fix the problem? Thanks!

**Comment by ljmartin** [comment]
Works for me - thanks @hawkinsp !

**Comment by hawkinsp** [comment]
Great! Glad to hear it!

**Comment by fehiepsi** [comment]
@hawkinsp I am facing the same error in macOS 10.12 (CPU, python=3.8) with the latest `jaxlib=0.1.52` (jaxlib=0.1.51 and previous versions work well).

**Comment by YinanCao** [comment]
Hi jax team,

I'm having this issue for python3.9 and the newest version of jax...
could you please be so kind as to fix it and release an update? thanks so much...

**Comment by fabiannagel** [comment]
+1 for me. Python 3.8.6 and High Sierra 10.13.6
