### ISSUE TITLE
Local CUDA install directions with pip missing alternative to symlink

### ISSUE THREAD

**Issue by felker** [google/jax#17831]
### Description

This is just a documentation error/typo, so apologies in advance if I should report this elsewhere. 

https://github.com/google/jax/blob/173a2701794571f3a102b0dd80bdedb4adbd8a5c/docs/installation.md?plain=1#L155-L161

The "either" here seems misplaced, or the doc is missing an alternative to creating a symbolic link. If there is a recommended alternative, I would love to hear it, since I cannot create a symbolic link there on the shared cluster I am building JAX on. We dynamically swap CUDA Toolkit versions based on the loaded Environment Modules on our machine. 

### What jax/jaxlib version are you using?

0.4.16

### Which accelerator(s) are you using?

GPU

### Additional system info

SUSE Linux Enterprise Server 15 SP3

### NVIDIA GPU info

```
❯ nvidia-smi
Thu Sep 28 16:33:56 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.103.04   Driver Version: 470.103.04   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  On   | 00000000:A3:00.0 Off |                   On |
| N/A   35C    P0    46W / 300W |      0MiB / 80994MiB |     N/A      Default |
|                               |                      |              Enabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| MIG devices:                                                                |
+------------------+----------------------+-----------+-----------------------+
| GPU  GI  CI  MIG |         Memory-Usage |        Vol|         Shared        |
|      ID  ID  Dev |           BAR1-Usage | SM     Unc| CE  ENC  DEC  OFA  JPG|
|                  |                      |        ECC|                       |
|==================+======================+===========+=======================|
|  No MIG devices found                                                       |
+-----------------------------------------------------------------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment]
I strongly recommend using the `pip` installation of CUDA, as we recommend in our installation docs.
It's 1000x easier to install that way (https://github.com/google/jax#installation).

If you are determined to use a local installation, then I think you just need to set
`LD_LIBRARY_PATH` to point to your cuda libraries (typically `/usr/local/cuda/lib64`, although you might need some additional directories for `libcupti.so`) and `PATH` to include your CUDA binaries (typically `/usr/local/cuda/bin`).

**Comment by felker** [comment]
Indeed we set `LD_LIBRARY_PATH` accordingly, and it _seems_ to be working. Should I add your note to the docs in a PR?

**Comment by hawkinsp** [comment]
I updated the docs to just  mention `LD_LIBRARY_PATH` and `PATH`.
