### ISSUE TITLE
jit of scan gives XlaRuntimeError: UNIMPLEMENTED: Dot with multiple contracting dimensions not implemented.

### ISSUE THREAD

**Issue by f0uriest** [google/jax#17834]
### Description

Getting some weird behavior and trying to diagnose. 

I have something of the form

```python

thing = Thing()

def compute_field(params):

    def scanfun(out, params_i):
        out += thing.compute(params_i)
        return out, None

    return jax.lax.scan(scanfun, jnp.zeros(n), params)[0]

```

Where `Thing` is a custom pytree class, `params` is a dict of arrays im scanning over, and `Thing.compute` is some big long function.
As written above, things seem to run ok. However, if I jit `compute_field` I get the following:

```
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Cell In[18], line 1
----> 1 compute_field(params)

    [... skipping hidden 14 frame]

File ~/miniconda3/envs/desc/lib/python3.10/site-packages/jax/_src/dispatch.py:465, in backend_compile(backend, module, options, host_callbacks)
    460   return backend.compile(built_c, compile_options=options,
    461                          host_callbacks=host_callbacks)
    462 # Some backends don't have `host_callbacks` option yet
    463 # TODO(sharadmv): remove this fallback when all backends allow `compile`
    464 # to take in `host_callbacks`
--> 465 return backend.compile(built_c, compile_options=options)

XlaRuntimeError: UNIMPLEMENTED: Dot with multiple contracting dimensions not implemented.
```

I'm unable to give a more complete MWE as I'm not even sure what operation is causing the issue, as far as I know there aren't any dot operations with multiple contracting dimensions, and the error message doesn't give any more detail about where it's failing.

Also curious that although `scanfun` should be getting compiled by `jax.lax.scan` it seems like it recompiles on every call (from running `with jax.log_compiles()`)

Any clues?

### What jax/jaxlib version are you using?

jax version=0.4.13, jaxlib version=0.4.13

**Comment by jewillco** [comment]
I searched for this message in the code and it appears to be in the CPU XLA-to-LLVM IR translator [here]( https://github.com/tensorflow/tensorflow/blob/1bd1b7f4b0311575ead19f14e74488a97b524555/third_party/xla/xla/service/cpu/ir_emitter.cc#L884).

**Comment by hawkinsp** [comment]
Closing; we need a reproduction or an HLO dump. We'd be happy to look into this if you can provide either.
