### ISSUE TITLE
FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated

### ISSUE THREAD

**Issue by gnecula** [google/jax#1784]
Some of our tests print the numpy warning about using non-tuple sequence for indexing. For example, in tests/lax_numpy_indexing_test.py we use Ellipsis, None, slice, lists, all of which trigger this warning. 

Should we do something about this? 

Where in numpy this comes from:
https://github.com/numpy/numpy/blob/3fcf144be4939a6a785dc80b75189c2e05d6bd22/numpy/core/src/multiarray/mapping.c#L313

**Comment by mattjj** [comment]
I think it’s okay as-is: we support the deprecated numpy behavior, but when our tests compare against numpy it generates the warning. (Actually, I guess we could have the test case slurp up the warning... I only just realized that might be one of the solutions you have in mind.)

That said I’m interested to hear @shoyer ’s thoughts!

**Comment by shoyer** [comment]
I think we should try to eliminate all warnings from JAX's test suite, and then turn on the setting that turns warnings into errors. This is helpful for catching upstream changes, e.g., when NumPy deprecates some behavior that JAX inadvertantly relied upon.

Sometimes (e.g., when we are testing capability with deprecated behavior) the right solution is to explicitly silence warnings, but most of the time warnings indicate something about our code or tests that should be changed. It's not immediately obvious which is the case here without seeing where the warnings are coming from.

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/2674 fixes this.

Interestingly the warning mentioned in this issue was in fact pointing to a bug: some of the indexing tests were accidentally testing NumPy's behavior!
