### ISSUE TITLE
Divergence between `jnp.load` and `np.load`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#17858]
### Description

```python
import jax.numpy as jnp
import numpy as np

jnp.save("hi.npy", 1e-8)
x = np.load("hi.npy").item()
y = jnp.load("hi.npy").item()
print(x)  # 1e-08
print(y)  # 9.99999993922529e-09
```
I assume this is due to some internal dtype conversion that isn't supposed to be happening.

### What jax/jaxlib version are you using?

JAX: 173a27017; jaxlib: 0.4.16

### Additional system info

Linux

**Comment by jakevdp** [comment]
Unless you `ENABLE_X64`, `x` is float64 and `y` is float32, which would explain the discrepancy. Try this:
```python
import jax.numpy as jnp
import numpy as np
import jax

jax.config.update('jax_enable_x64', True)

jnp.save("hi.npy", 1e-8)
x = np.load("hi.npy").item()
y = jnp.load("hi.npy").item()
print(x)  # 1e-08
print(y)  # 1e-08
```

**Comment by patrick-kidger** [comment]
Right, but I don't always have 64-bit enabled. I understand the reason for this behaviour, it's just hard to work around!

Maybe simply to target my actual use-case: given an `np.generic` to deserialise, then this behaviour means that `np.load` must be used for `np.float64`, but `jnp.load` must be used for `jax.dtypes.bfloat16`. Is there a clean way to handle both of these cases, or must a manual whitelist be constructed? I'm hoping to avoid doing something like
```python
if dtype.__module__ == "ml_dtypes":
    jnp.load(...)
else:
    np.load(...)
```

**Comment by jakevdp** [comment]
I think if you want the output to be JAX arrays, use `jnp.load`. If you want the output to be numpy arrays, use `np.load`. Note that `jnp.load` is just a light wrapper around `np.load`: https://github.com/google/jax/blob/ef6fd2ebb6cb31174c63338a07bdec88886dcd8b/jax/_src/numpy/lax_numpy.py#L282-L294

If the baked-in logic doesn't work for you, then you could write your own utility in a few lines.

**Comment by patrick-kidger** [comment]
Closing. This makes things a bit tricky for downstream libraries, but on reflection I appreciate there's not that much more JAX can do here.
