### ISSUE TITLE
Producing JAXPR code from a function containing sparse matrix

### ISSUE THREAD

**Issue by PierrickPochelu** [google/jax#17852]
### Description

Getting the JAXPR of the function is not possible.

```python
import jax
from jax.experimental import sparse

M = jax.numpy.array([[0., 1., 0., 2.],
               [3., 0., 0., 0.],
               [0., 0., 4., 0.]])
def f(M):
    return sparse.COO.fromdense(M)

print( f(M) ) # f is working fine

out=jax.make_jaxpr(f)(M) # crash

```

It raises a jax._src.errors.ConcretizationTypeError:

```
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=1/0)>
coo_fromdense nse argument
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```

I annotated the argument as static but still the same issue

### What jax/jaxlib version are you using?

jax v0.2.17

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.8 OS Linux

**Comment by jakevdp** [comment]
To elaborate: `make_jaxpr` is similar to `jit`, in that it evaluates the function for abstract inputs. Becuase your input array is abstract, there's no way to determine the number of specified elements in the output array, which means the function cannot be abstractly evaluated.

To address this, you can statically specify `nse`:
```python 
def f(M, nse=4):
    return sparse.COO.fromdense(M, nse=nse)

print(jax.make_jaxpr(f)(M))
```
```
    b:f64[4] c:i32[4] d:i32[4] = coo_fromdense[
      index_dtype=<class 'numpy.int32'>
      nse=4
    ] a
  in (b, c, d) }
```
