### ISSUE TITLE
Random Bernoulli allocates massive amounts of unnecessary memory  

### ISSUE THREAD

**Issue by half-potato** [google/jax#17865]
I am running jax.random.bernoulli to run 64*64 trials for 4 million different mean values. However, this consumes ~800GB of VRAM. It probably shouldn't.

```
external/tsl/tsl/framework/bfc_allocator.cc:485] Allocator (GPU_0_bfc) ran out of memory trying to allocate 207.07GiB (rounded to 222343890432)requested by op
```

**Comment by jakevdp** [comment]
Thanks for the report! This certainly seems like a lot of memory, but you should keep in mind that just storing 64*64*4000000 float32 values will take ~60GB (64 * 64 * 4000000 * 4 bytes), and `random.bernoulli` needs several times this memory to perform the operations it uses to go from random bits to bernoulli-distributed floats. You can get some sense of what's involved by looking at the jaxpr for this operation:
```python
In [1]: import jax

In [2]: jax.make_jaxpr(lambda key: jax.random.bernoulli(key, 0.5, (64, 64, 4000000)))(jax.random.key(0))
Out[2]: 
{ lambda ; a:key<fry>[]. let
    b:bool[64,64,4000000] = pjit[
      jaxpr={ lambda ; c:key<fry>[] d:f32[]. let
          e:f32[64,64,4000000] = pjit[
            jaxpr={ lambda ; f:key<fry>[] g:f32[] h:f32[]. let
                i:f32[] = convert_element_type[
                  new_dtype=float32
                  weak_type=False
                ] g
                j:f32[] = convert_element_type[
                  new_dtype=float32
                  weak_type=False
                ] h
                k:f32[1,1,1] = broadcast_in_dim[
                  broadcast_dimensions=()
                  shape=(1, 1, 1)
                ] i
                l:f32[1,1,1] = broadcast_in_dim[
                  broadcast_dimensions=()
                  shape=(1, 1, 1)
                ] j
                m:u32[64,64,4000000] = random_bits[
                  bit_width=32
                  shape=(64, 64, 4000000)
                ] f
                n:u32[64,64,4000000] = shift_right_logical m 9
                o:u32[64,64,4000000] = or n 1065353216
                p:f32[64,64,4000000] = bitcast_convert_type[new_dtype=float32] o
                q:f32[64,64,4000000] = sub p 1.0
                r:f32[1,1,1] = sub l k
                s:f32[64,64,4000000] = mul q r
                t:f32[64,64,4000000] = add s k
                u:f32[64,64,4000000] = max k t
              in (u,) }
            name=_uniform
          ] c 0.0 1.0
          v:bool[64,64,4000000] = lt e d
        in (v,) }
      name=_bernoulli
    ] a 0.5
  in (b,) }
```
Since each `64,64,4000000` value occupies ~60GB, it's not unreasonable that the whole operation would require several hundred gigabytes.

If you need to be more memory efficient, you might try generating your bernoulli samples in batches, within `lax.scan` for example. Do you think an approach like that might work for your use-case?

**Comment by half-potato** [comment]
Is it not just a simple boolean comparison between p and some uniforms? I understand that there are technical reasons for what is happening. However, in theory, writing this in CUDA would result in 2GB of VRAM. That means that Jax Bernoulli has a 100x memory overhead for this operation.

**Comment by jakevdp** [comment]
> Is it not just a simple boolean comparison between p and some uniforms?

Those uniforms take up 60GB on their own, so I'm not sure how you could fit that into 2GB in theory without doing some sort of batched operation.

**Comment by half-potato** [comment]
Why do those uniforms need to be stored in VRAM? Can’t they be generated, stored in one of the warp registers, then discarded immediately? They don’t need to be accumulated, right? I’m not familiar with TPU architecture.

**Comment by jakevdp** [comment]
It's true that there is only one bit of information per boolean value, but JAX/XLA (like many other numerical computing systems) stores booleans as bytes for computational efficiency reasons.

**Comment by jakevdp** [comment]
I'm going to close this, because it seems to be working as expected.
