### ISSUE TITLE
Warning message displayed by default in last version

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#17879]
### Description

In the last version of jax  a message is always printed when initialising the runtime. 
I don't have any particular env variable set.
I think this should be hidden by default.

```python
python-3.11.2 ❯ python -c 'import jax;print(jax.numpy.ones(3))'
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1696178045.970178       1 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
[1. 1. 1.]
```

### What jax/jaxlib version are you using?

jax 0.4.16, jaxlib 0.4.16

### Which accelerator(s) are you using?

cpu

### Additional system info

python 3.11, macOS

**Comment by jakevdp** [comment]
Thanks for the report! This has been fixed, and the warning should not appear in the next jaxlib version.

**Comment by PhilipVinc** [comment]
sorry for the noise then. Thanks!
