### ISSUE TITLE
grad and vmap do not composable with gamma sampler

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#1789]
Here is a repro code, which triggers error `NotImplementedError: Forward-mode differentiation rule for 'while' not implemented` when trying to take gradient of `g`.
```
import jax
import jax.numpy as np
jax.config.update('jax_platform_name', 'cpu')

def f(a):
    return jax.random.gamma(jax.random.PRNGKey(0), a)

def g(x):
    return np.sum(jax.vmap(f)(x))

print(g(np.ones(3)))
print(jax.grad(g)(np.ones(3)))
```

**Comment by shoyer** [comment]
This is another manifestation of https://github.com/google/jax/issues/1249.

**Comment by fehiepsi** [comment]
Oh... Thanks, @shoyer! That seems like the problem which I get. I'll try to see if I can go back to several months ago to not use custom_transform for gamma sampler.
