### ISSUE TITLE
cannot install jaxlib on alpine linux

### ISSUE THREAD

**Issue by dchatterjee172** [google/jax#1792]
```
/life # pip install jaxlib
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib
/life # pip search jaxlib
jaxlib (0.1.36)  - XLA library for JAX
```

Dockerfile
```
FROM python:3.7-alpine
RUN apk --no-cache add curl g++ redis py3-redis openblas-dev lapack   
```

**Comment by hawkinsp** [comment]
My guess is that you have an old version of `pip`. Try first running `pip install --upgrade pip`.

**Comment by dchatterjee172** [comment]
```
/life # pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python3.7/site-packages (19.3.1)

```

**Comment by hawkinsp** [comment]
Another guess: is this an `x86` or `x86_64` linux installation? We don't support `x86`, only `x86_64`.

Otherwise this issue is probably in the "contributions welcome" category. We don't have the engineering cycles to debug installation issues with every possible Linux distribution.

**Comment by dchatterjee172** [comment]
This is `x86_64`

Can you give me some directions for debugging?

**Comment by hawkinsp** [comment]
I'm unsure. This is a `pip` issue, not a JAX issue. The question is why `pip` doesn't think the available wheels for `jaxlib` are installable on your system.

**Comment by joaogui1** [comment]
I think [this issue](https://github.com/docker-library/docs/issues/904) can shed a light on the problem, and it seems alpine linux has problems with pip wheels in general

**Comment by hawkinsp** [comment]
I think @joaogui1 has answered this one: Alpine linux doesn't support `pip` wheels. So none of the distributions we provide are installable.  This isn't a configuration we support ourselves. You can try building from source, if you like. Contributions are welcome!
