### ISSUE TITLE
Unexpected behavior when using custom_jvp and BCOO sparse matrices

### ISSUE THREAD

**Issue by inversecrime** [google/jax#17953]
### Description

I encountered a strange behavior while using custom_jvp in combination with BCOO matrices.
It seems like the native autodiff rules work fine, but using custom_jvp gives strange results.
(Maybe my implementation for the custom jacobian-vector-product is wrong, but I'm pretty sure I did it correctly)

This problem seems similar to #10163.

The following code shows what I mean.

```python
import jax
from jax import Array
from jax import numpy as jnp
from jax import random as rnd
from jax.experimental.sparse import BCOO


def mvp(A: BCOO, b: Array) -> Array:
    x = A @ b
    return x


def mvp_jvp(primals: tuple[BCOO, Array], tangents: tuple[BCOO, Array]) -> tuple[Array, Array]:
    (A, b) = primals
    (A_dot, b_dot) = tangents
    x = A @ b
    x_dot = A_dot @ b + A @ b_dot
    return (x, x_dot)


mvp_with_custom_jvp = jax.custom_jvp(mvp)
mvp_with_custom_jvp.defjvp(mvp_jvp)


A_shape = (3, 3)
A_indices = jnp.asarray([[0, 0],[1,1],[2,2]])
A_data_shape = (A_indices.shape[0],)
b_shape = (A_shape[1],)


def to_sparse(A_data: Array) -> BCOO:
    return BCOO((A_data, A_indices), shape=A_shape)


def data_mvp(A_data: Array, b: Array) -> Array:
    return mvp(to_sparse(A_data), b)


def data_mvp_with_custom_jvp(A_data: Array, b: Array) -> Array:
    return mvp_with_custom_jvp(to_sparse(A_data), b)


key = rnd.PRNGKey(0)

key, subkey = rnd.split(key)
A_data = rnd.uniform(subkey, shape=A_data_shape)

key, subkey = rnd.split(key)
b = rnd.uniform(subkey, shape=b_shape)


print(jnp.diag(b)) # since the sparse matrix is diagonal, the result should be this
print(jax.jacfwd(data_mvp)(A_data, b))  # correct
print(jax.jacrev(data_mvp)(A_data, b))  # correct
print(jax.jacfwd(data_mvp_with_custom_jvp)(A_data, b))  # wrong
print(jax.jacrev(data_mvp_with_custom_jvp)(A_data, b))  # wrong
```

### What jax/jaxlib version are you using?

jax v0.4.17, jaxlib v0.4.17

### Which accelerator(s) are you using?

cpu

**Comment by jakevdp** [comment]
Thanks for the report! The problem is that `custom_jvp` does not propagate sparse indices correctly. You can fix it by doing this:
```python
def mvp_jvp(primals: tuple[BCOO, Array], tangents: tuple[BCOO, Array]) -> tuple[Array, Array]:
    (A, b) = primals
    (A_dot, b_dot) = tangents
    A_dot.indices = A.indices
    x = A @ b
    x_dot = A_dot @ b + A @ b_dot
    return (x, x_dot)
```
This is a fundamental issue with the design of `custom_jvp` as it relates to the design of `sparse.BCOO`. In the past we've thought about ways to allow types like `BCOO` to register with the autodiff system how their attributes should be handled within autodiff operations, but we haven't come up with a good solution. So unfortunately, there are corner cases that remain broken, and you've found one of them.

**Comment by inversecrime** [comment]
Thanks for the quick reply! I didn't expect that you could provide a working solution this fast, so this is a welcome surprise.
Is there any way I could have known this in advance?

**Comment by jakevdp** [comment]
No, unfortunately the experimental sparse APIs don't have very complete documentation
