### ISSUE TITLE
Reshape layer for stax

### ISSUE THREAD

**Issue by dwidemann** [google/jax#1796]
I'm trying to write a reshape layer with stax. However, I'm getting errors. Here's my approach.

    def Reshape(newshape):
      """Layer construction function for a reshape layer."""
      init_fun = lambda rng, input_shape: (input_shape, ())
      apply_fun = lambda params, inputs, **kwargs: jnp.reshape(inputs,newshape)
      return init_fun, apply_fun

However, when I do this:

    decode_init, decode = stax.serial(
        Dense(100),
        Elu,
        Reshape((10,10,1,-1)),
        GeneralConvTranspose(('HWCN', 'OIHW', 'NHWC'),2, (3,3), (1,1), padding=padding))

and call it:

    decode_input_shape = encode_out.shape
    _, decode_params = decode_init(rng, decode_input_shape)
    decode_out = decode(decode_params,encode_out)
    print(decode_out.shape)

i get this error:

IndexError                                Traceback (most recent call last)
<ipython-input-41-d6135a38cdd7> in <module>()
      5     GeneralConvTranspose(('HWCN', 'OIHW', 'NHWC'),2, (3,3), (1,1), padding=padding))
      6 decode_input_shape = encode_out.shape
----> 7 _, decode_params = decode_init(rng, decode_input_shape)
      8 decode_out = decode(decode_params,encode_out)
      9 print(decode_out.shape)

/.../experimental/stax.py in init_fun(rng, input_shape)
    280     for init_fun in init_funs:
    281       rng, layer_rng = random.split(rng)
--> 282       input_shape, param = init_fun(layer_rng, input_shape)
    283       params.append(param)
    284     return input_shape, params

/.../experimental/stax.py in init_fun(rng, input_shape)
    105     kernel_shape = [out_chan if c == 'O' else
    106                     input_shape[lhs_spec.index('C')] if c == 'I' else
--> 107                     next(filter_shape_iter) for c in rhs_spec]
    108     output_shape = lax.conv_transpose_shape_tuple(
    109         input_shape, kernel_shape, strides, padding, dimension_numbers)

/.../experimental/stax.py in <listcomp>(.0)
    105     kernel_shape = [out_chan if c == 'O' else
    106                     input_shape[lhs_spec.index('C')] if c == 'I' else
--> 107                     next(filter_shape_iter) for c in rhs_spec]
    108     output_shape = lax.conv_transpose_shape_tuple(
    109         input_shape, kernel_shape, strides, padding, dimension_numbers)

IndexError: tuple index out of range

**Comment by shoyer** [comment]
Your `init_fn` also needs to update the shape.

**Comment by dwidemann** [comment]
That fixed it. Thanks.

    def Reshape(newshape):
      """Layer construction function for a reshape layer."""
      init_fun = lambda rng, input_shape: (newshape,())
      apply_fun = lambda params, inputs, **kwargs: jnp.reshape(inputs,newshape)
      return init_fun, apply_fun

Could I also ask you, I'm inputting my data to the encoder (not shown) as (H,W,C,batch_size). However, the encoder outputs (batch_size, latent_dimension). This seems unintuitive because I thought it would preserve the batch as the last dimension?

**Comment by sschoenholz** [comment]
Glancing at your traceback notice that your first layer seems to be `GeneralConvTranspose(('HWCN', 'OIHW', 'NHWC'),2, (3,3), (1,1), padding=padding))`. The first argument are "dimension numbers" which tell XLAs convolution operator which input / kernel / output dimensions are which. The first string `"HWCN"` indicates that your inputs are `height, width, channel, batch`. The last string `"NHWC"` indicates that the outputs of the convolution are `batch, height, width, channel`. So the first convolution you send the input to will swap the batch dimension. If this is undesirable you can always change the dimension numbers to be whatever you want.

**Comment by dwidemann** [comment]
I see. Thank you!

**Comment by hawkinsp** [comment]
Closing since we aren't going to evolve `stax` any further. Others have built better and more fully-featured neural network libraries on top of JAX, such as Flax and Haiku.
