### ISSUE TITLE
GPU version slower than CPU for small networks

### ISSUE THREAD

**Issue by mgbukov** [google/jax#1797]
I'm testing jax's performance on a CPU vs GPU for a small (36x6) network and relatively large batch size. It seems like the GPU is slower. I wonder if I am doing something wrong, or just the xla speedup is designed for the regime of large networks only? 

Here's my script: 

[single_batch.txt](https://github.com/google/jax/files/3913237/single_batch.txt)

And here's the timing for the first 10 epochs: 

**CPU:**

UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
0 epoch time: 0.559627
1 epoch time: 0.000196
2 epoch time: 0.000172
3 epoch time: 0.000125
4 epoch time: 0.000128
5 epoch time: 0.000126
6 epoch time: 0.000115
7 epoch time: 0.000114
8 epoch time: 0.000109
9 epoch time: 0.000108

total time: 0.560949

**GPU:**

(jax) marin@cuiw-ubuntu:~/varqmc/gpu_profile$ nvprof python single_batch.py 
==22168== NVPROF is profiling process 22168, command: python single_batch.py
0 epoch time: 1.203086
1 epoch time: 0.011073
2 epoch time: 0.040703
3 epoch time: 0.013159
4 epoch time: 0.010278
5 epoch time: 0.062659
6 epoch time: 0.013734
7 epoch time: 0.010502
8 epoch time: 0.013077
9 epoch time: 0.009990

total time: 1.388779

==22168== Profiling application: python single_batch.py
==22168== Profiling result:
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
 GPU activities:   57.89%  362.09ms     33051  10.955us     608ns  6.9039ms  [CUDA memcpy HtoD]
                   25.25%  157.96ms        66  2.3933ms  1.6400ms  4.0832ms  maxwell_dgemm_64x64_nn
                    4.67%  29.227ms        10  2.9227ms  2.8957ms  2.9411ms  fusion_2
                    4.63%  28.971ms        10  2.8971ms  2.8803ms  2.9095ms  fusion_3
                    3.10%  19.387ms        10  1.9387ms  1.8993ms  1.9608ms  fusion_6
                    2.26%  14.147ms         3  4.7156ms  3.2612ms  7.4618ms  maxwell_dgemm_128x64_nn
                    1.07%  6.6651ms        72  92.570us  91.969us  94.145us  redzone_checker
                    0.55%  3.4347ms         6  572.44us  345.28us  686.95us  __xla_fp64_comparison
                    0.23%  1.4538ms        10  145.38us  144.83us  146.05us  fusion_1
                    0.22%  1.3911ms        22  63.229us  1.1200us  137.28us  fusion
                    0.10%  645.70us         7  92.243us     960ns  257.22us  [CUDA memcpy DtoD]
                    0.01%  65.152us        83     784ns     576ns  1.8560us  [CUDA memset]
                    0.01%  42.528us        50     850ns     736ns  1.1520us  [CUDA memcpy DtoH]
                    0.00%  6.9440us         4  1.7360us     928ns  2.4320us  convert_2
                    0.00%  1.9520us         1  1.9520us  1.9520us  1.9520us  and_3
                    0.00%  1.3440us         1  1.3440us  1.3440us  1.3440us  concatenate_3
      API calls:   36.95%  657.42ms         2  328.71ms  328.61ms  328.82ms  cuDevicePrimaryCtxRetain
                   17.73%  315.45ms     33062  9.5410us     151ns  325.27us  cuMemcpyHtoDAsync
                   15.47%  275.19ms         1  275.19ms  275.19ms  275.19ms  cudaFree
                   12.57%  223.55ms     66214  3.3760us     299ns  190.78ms  cudaPointerGetAttributes
                    6.78%  120.62ms         4  30.154ms  1.6627ms  49.871ms  cuMemHostAlloc
                    3.49%  62.134ms        24  2.5889ms  15.480us  60.814ms  cuModuleUnload
                    2.50%  44.535ms         4  11.134ms  373.35us  22.036ms  cuMemFreeHost
                    1.62%  28.783ms         9  3.1981ms  1.6392ms  7.4502ms  cuEventSynchronize
                    0.77%  13.644ms        24  568.51us  45.342us  7.2426ms  cuModuleLoadFatBinary
                    0.57%  10.213ms        50  204.27us  22.768us  690.77us  cuMemcpyDtoHAsync
                    0.39%  6.8995ms        19  363.13us  3.3280us  4.2994ms  cuMemFree
                    0.21%  3.6508ms     33131     110ns      71ns  341.71us  cudaGetLastError
                    0.14%  2.4558ms       146  16.820us  3.1280us  320.94us  cuLaunchKernel
                    0.13%  2.4010ms       444  5.4070us      94ns  521.68us  cuDeviceGetAttribute
                    0.13%  2.3906ms        19  125.82us  3.9030us  882.11us  cuMemAlloc
                    0.13%  2.2507ms         6  375.12us  197.13us  636.01us  cuDeviceTotalMem
                    0.08%  1.5027ms        98  15.333us  1.3920us  172.73us  cuStreamAddCallback
                    0.08%  1.4842ms        69  21.509us  6.4650us  73.006us  cudaLaunchKernel
                    0.06%  1.1209ms       336  3.3360us     225ns  66.772us  cuEventRecord
                    0.05%  828.01us        83  9.9750us  2.8250us  61.937us  cuMemsetD32Async
                    0.04%  662.78us        22  30.126us  2.4740us  327.50us  cuStreamCreate
                    0.03%  563.85us       218  2.5860us     401ns  15.083us  cuStreamWaitEvent
                    0.02%  271.61us         7  38.801us  8.1540us  66.251us  cuMemcpyDtoDAsync
                    0.01%  182.07us         6  30.344us  14.225us  49.183us  cuDeviceGetName
                    0.01%  160.75us       184     873ns     171ns  15.018us  cuEventCreate
                    0.01%  126.96us        76  1.6700us     521ns  9.1350us  cuStreamSynchronize
                    0.01%  109.34us        22  4.9700us  1.5460us  34.501us  cuStreamDestroy
                    0.01%  107.33us       184     583ns     173ns  8.5000us  cuEventDestroy
                    0.00%  83.223us         2  41.611us  30.733us  52.490us  cuMemGetInfo
                    0.00%  40.882us        10  4.0880us     764ns  11.075us  cuCtxSetCurrent
                    0.00%  40.646us         3  13.548us  3.7230us  28.296us  cudaMalloc
                    0.00%  27.105us        28     968ns     313ns  3.9890us  cuModuleGetFunction
                    0.00%  26.592us        21  1.2660us     152ns  3.3750us  cuDeviceGet
                    0.00%  23.520us        56     420ns     112ns  1.0110us  cuFuncGetAttribute
                    0.00%  13.864us         5  2.7720us  1.4380us  3.3960us  cuCtxSynchronize
                    0.00%  13.136us        22     597ns     413ns  2.4680us  cuStreamQuery
                    0.00%  10.872us         1  10.872us  10.872us  10.872us  cudaMemcpy
                    0.00%  10.748us         9  1.1940us     702ns  2.6440us  cuEventElapsedTime
                    0.00%  9.6960us         2  4.8480us  1.6610us  8.0350us  cuInit
                    0.00%  7.4810us        16     467ns     358ns  1.6440us  cudaEventCreateWithFlags
                    0.00%  5.2260us         2  2.6130us  2.1330us  3.0930us  cuDeviceGetPCIBusId
                    0.00%  3.6100us        11     328ns     200ns     976ns  cudaDeviceGetAttribute
                    0.00%  3.1630us         2  1.5810us  1.4480us  1.7150us  cuDevicePrimaryCtxGetState
                    0.00%  2.9960us         6     499ns     151ns  1.5250us  cuDeviceGetCount
                    0.00%  2.5630us         4     640ns     176ns  1.5350us  cuDriverGetVersion
                    0.00%  1.8240us         2     912ns     757ns  1.0670us  cuCtxGetCurrent
                    0.00%  1.3170us         1  1.3170us  1.3170us  1.3170us  cudaGetDevice
                    0.00%  1.3020us         4     325ns     164ns     579ns

**Comment by hawkinsp** [comment]
Without looking too hard, please read:
https://jax.readthedocs.io/en/latest/async_dispatch.html

From a quick look it appears your script is timing the dispatch time and not the execution time.

**Comment by mgbukov** [comment]
Thanks! Indeed, if I add 

```
log_psi.block_until_ready()
phase_psi.block_until_ready()
```

inside the epoch loop, the CPU time grow up, but the GPU time remains the same [see below]. Why did the GPU time not change?

CPU:

UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
0 epoch time: 0.818023
1 epoch time: 0.237345
2 epoch time: 0.236716
3 epoch time: 0.249315
4 epoch time: 0.251007
5 epoch time: 0.264165
6 epoch time: 0.239016
7 epoch time: 0.253645
8 epoch time: 0.263471
9 epoch time: 0.254056

total time: 3.067296

GPU:

0 epoch time: 1.062669
1 epoch time: 0.039428
2 epoch time: 0.039182
3 epoch time: 0.039281
4 epoch time: 0.039049
5 epoch time: 0.039092
6 epoch time: 0.038686
7 epoch time: 0.038537
8 epoch time: 0.038470
9 epoch time: 0.038565

total time: 1.413245

**Comment by hawkinsp** [comment]
Well, the GPU times you show did go up... just not as much. I'd say that's working as intended? 

Note you should probably ignore the first iteration of the benchmark in each case: that's mostly measuring the time to JIT-compile your code. If you look at the iterations other than the first one the pattern is clear.

Does that answer everything to your satisfaction? Can we close this issue?

**Comment by mgbukov** [comment]
Yup, thanks!
