### ISSUE TITLE
ERROR when i build jaxlib from source

### ISSUE THREAD

**Issue by OptNuo** [google/jax#18036]
### Description

python3.9.5
bazel6.1.2
numpy1.26.0

I execute ：python build/build.py --enable_cuda 

BUG：
ERROR: /home/nkn/.cache/bazel/_bazel_nkn/b4d615bfc19ac426847a2ea815c61f11/external/local_config_python/BUILD:78:8: in outs attribute of genrule rule @local_config_python//:python_include: Genrules without outputs don't make sense
ERROR: /home/nkn/.cache/bazel/_bazel_nkn/b4d615bfc19ac426847a2ea815c61f11/external/local_config_python/BUILD:78:8: Analysis of target '@local_config_python//:python_include' failed

How can i solve it？

### What jax/jaxlib version are you using?

jaxlib 0.4.16

### Which accelerator(s) are you using?

GPU

### Additional system info

WSL ubuntu20.04

### NVIDIA GPU info

CUDA11.8   cudnn8.9.5

**Comment by hawkinsp** [comment]
Can you try again at JAX head?

In addition, since this is a WSL build, can you instead just install JAX from `pip`, following the JAX on CUDA installation instructions? https://github.com/google/jax#instructions

**Comment by joyeewang** [comment]
Is it possible that there are network download restrictions in your region, and the required libraries might need to be specified as local paths during the build process?

**Comment by hawkinsp** [comment]
There was no response; closing.
