### ISSUE TITLE
Bitwise negation bug/no support

### ISSUE THREAD

**Issue by knyazer** [google/jax#18031]
### Description

Hey there,

I've recently encountered an interesting problem when using bitwise negation (```~```) operation on booleans that are immediate results of the functions. Here is a sample code:

```
from jax import numpy as jnp
f = lambda x: x > 5

~f(0)  # returns -1, equivalent to ~0
~f(10) # returns -2, equivalent to ~1
```

It looks like JAX (or XLA) incorrectly reduces the negation operation with (probably) an intermediate representation of function output, though I don't know.

This bug is extremely annoying to debug when passing a function as an argument to another function, so I think it is quite important to fix this, or do something else that would mitigate the problem. Of course, if one knows about the bug, it is easy to fix it with ```jnp.logical_not``` instead of ```~```.

Cheers

### What jax/jaxlib version are you using?

jax v0.4.18; jaxlib v0.4.18

### Which accelerator(s) are you using?

CPU

### Additional system info

3.10.4; Ubuntu 22.04; Kernel 5.15.81

**Comment by hawkinsp** [comment]
Note your reproduction doesn't use JAX at all! You're importing JAX but not using it:

```
f = lambda x: x > 5

~f(0)  # returns -1, equivalent to ~0
~f(10) # returns -2, equivalent to ~1
```

Did you get the correct repro?

**Comment by knyazer** [comment]
Oh wow, I reduced my example so much, that it looks like it is not a bug in jax, but a 'bug' in python lambdas. Sorry! I have a piece of code that allows passing both python functions, and pjit functions, hence the confusion: jax counterpart (when doing ```~f(jnp.array(0))``` works as expected, unexpected was the difference in behaviours with pure Python lambdas.
