### ISSUE TITLE
Is there a way to register a particular Python object as a PyTree leaf?

### ISSUE THREAD

**Issue by NightMachinery** [google/jax#18049]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

---

I need to make `jax.tree_map` treat certain Python lists as leaves. Is this possible without using a dummy class `LeafList(list)`? I can't use a dummy class for reasons.

**Comment by jakevdp** [comment]
You can pass an `is_leaf` function to `tree_map`; for example:
```python
def is_leaf(x):
  return isinstance(x, list) and len(x) == 3  # or whatever logic you need
tree_map(func, values, is_leaf=is_leaf)
```
