### ISSUE TITLE
Matmul using nested loops is slow

### ISSUE THREAD

**Issue by rietmann-nv** [google/jax#1811]
I'm experimenting implementing finite-difference operators in Jax, which, in the simplest implementation requires 2 or 3 nested `for` loops using the `loops.Scope()` pattern. I didn't get very good performance, and as part of that investigation I came across the `matmul` routine in the tests, which also has poor performance. My finite-difference example will have similar looking loops, and if the simplest `matmul` example doesn't work, I don't expect my marginally more complex code to work well either. I've included a standalone version for testing. The documentation (and location of `loops`) make it clear that this pattern is a WIP, but I wanted to make sure I'm not missing something. 

Experimental output:
```
In [51]: test_matmul()                                                                                                                                                                            
jax-loop X*Y time= 0.2301085509971017
jax-native X*Y time= 0.001427540002623573
```
The default is running a 10x10 matrix-matrix multiplication. Using the loop it takes 0.23 seconds (I do make sure not to count compilation). Using a native version its dramatically less. If I double matrix size:
```
In [4]: test_matmul(20)                                                                                                                                                                           
jax-loop X*Y time= 1.4509809279988986
jax-native X*Y time= 0.001520120000350289
In [5]: test_matmul(40)                                                                                                                                                                           
jax-loop X*Y time= 10.647515208998811
jax-native X*Y time= 0.0016823579935589805
```
System info:
```
GPU: Titan Xp, CUDA 10.1
Ubuntu 16.04
jax                       0.1.53                   pypi_0    pypi
jaxlib                    0.1.36                   pypi_0    pypi
```
Code:
```python
from timeit import default_timer as timer
import jax.numpy as np
import jax
from jax.experimental import loops
from jax import ops

def matmul(x, y):
    "Testing JAX loop performance using simple matrix multiplication"
    with loops.Scope() as s:
        n, m = x.shape
        m1, p = y.shape
        assert m == m1
        s.out = np.zeros(shape=[n, p], dtype=np.float32)
        for i in s.range(n):
            for j in s.range(p):
                for k in s.range(m):
                    s.out = ops.index_add(s.out, (i, j), x[i, k] * y[k, j])
        return s.out


def test_matmul(N=10):
    X = np.ones((N,N))
    Y = np.ones((N,N))

    matmul_jit = jax.jit(matmul)

    Z = matmul_jit(X, Y)
    start = timer()
    for i in range(10):
        X = matmul_jit(X, Y)
    X.block_until_ready()
    end = timer()
    print("jax-loop X*Y time=", end-start)

    X = np.ones((N,N))
    Y = np.ones((N,N))
    Z = X@Y
    start = timer()
    for i in range(10):
        X = X@Y
    X.block_until_ready()
    end = timer()
    print("jax-native X*Y time=", end-start)
```

**Comment by shoyer** [comment]
My (limited) understanding is that all control flow on GPUs with XLA is currently done on the CPU. So right now `jax.experimental.loops` is mostly aspirational, and only generates good performance code on CPUs.

You can get good performance from JAX for finite difference codes on GPU, but you need to write your operations in terms of higher level operations on entire slices of arrays, e.g., something like `2 * x[1:-1] - x[2:] - x[:-2]` to calculate a Laplacian. This github project has some good examples of accelerating core operations in an ocean dynamics code:
https://github.com/dionhaefner/pyhpc-benchmarks

**Comment by shoyer** [comment]
With regards to your specific benchmark, it probably makes sense to do a few more repeats and to be also `jit` accelerate `np.matmul`, e.g.,
```python
def test_matmul(N=10, repeats=1000):
    X = np.ones((N,N))
    Y = np.ones((N,N))

    matmul_jit = jax.jit(matmul)
    Z = matmul_jit(X, Y)

    start = timer()
    for i in range(repeats):
        X = matmul_jit(X, Y)
    X.block_until_ready()
    end = timer()
    print("jax-loop X*Y time=", end-start)

    X = np.ones((N,N))
    Y = np.ones((N,N))
    matmul_jit = jax.jit(np.matmul)
    Z = matmul_jit(X, Y)

    start = timer()
    for i in range(repeats):
        X = matmul_jit(X, Y)
    X.block_until_ready()
    end = timer()
    print("jax-native X*Y time=", end-start)
```

When I run it on CPUs with 1000 repeats, the loop example for small matrices (N=10) is actually very slightly faster 0.415 vs 0.467 seconds. It's significantly slower for large matrices (e.g., by ~25x for 100x100), so there's definitely still lots of room for compiler improvements even on CPU.

**Comment by gnecula** [comment]
The experimental.loops module does not yet have acceptable performance for deeply nested loops, this is WIP. In my experiments, I was able to get somewhat better performance if I can vmap so that more batches are pushed in the inner loop.

**Comment by romanodev** [comment]
Hi, I am coding up two nested loops using nested ``lax.scan``. Does this approach have the same limitations as ``jax.experimental.loops`` (in terms of GPU performances, as mentioned above)? 

A related question: in my case the inner loop can be done with ``vmap`` (the iterations are independent) - however, for memory issues I wanted to avoid stacking outputs (I only need a reduction from those results). For this reason, I am using ``lax.scan``, since I can read up results from the state. Is this the recommended approach? Thanks

**Comment by shoyer** [comment]
> Hi, I am coding up two nested loops using nested ``lax.scan``. Does this approach have the same limitations as ``jax.experimental.loops`` (in terms of GPU performances, as mentioned above)? 

Yes, exactly the same.

> A related question: in my case the inner loop can be done with ``vmap`` (the iterations are independent) - however, for memory issues I wanted to avoid stacking outputs (I only need a reduction from those results). For this reason, I am using ``lax.scan``, since I can read up results from the state. Is this the recommended approach? Thanks

Yes, this is the recommended approach for saving memory.
