### ISSUE TITLE
JAX always uses pip-installed CUDA, even when better version is local

### ISSUE THREAD

**Issue by FlorinAndrei** [google/jax#18172]
### Description

Ubuntu 22.04, RTX 3090

PyTorch 2.1.0 is installed in the same Python env, which installed several CUDA modules as dependencies:

```
nvidia-cublas-cu12                12.1.3.1
nvidia-cuda-cupti-cu12            12.1.105
nvidia-cuda-nvrtc-cu12            12.1.105
nvidia-cuda-runtime-cu12          12.1.105
nvidia-cudnn-cu12                 8.9.2.26
nvidia-cufft-cu12                 11.0.2.54
nvidia-curand-cu12                10.3.2.106
nvidia-cusolver-cu12              11.4.5.107
nvidia-cusparse-cu12              12.1.0.106
nvidia-nccl-cu12                  2.18.1
nvidia-nvjitlink-cu12             12.2.140
nvidia-nvtx-cu12                  12.1.105
```

The NVIDIA driver 535.113.01 is installed from the graphics-drivers PPA.

The CUDA version that Pytorch installed as modules would not work for JAX, so I've installed CUDA 12.2 from the runfile installer, in `/usr/local`. In this configuration, cupy-cuda12x works just fine.

But JAX does not work. I get this warning, and after that JAX falls back on using the CPU:

_CUDA backend failed to initialize: Found CUDA version 12010, but JAX was built against version 12020, which is newer. The copy of CUDA that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)_

How can I tell JAX to not use the CUDA version from the Python modules, but use the version in `/usr/local` instead?

The local CUDA installation is reflected in the PATH variable, and I also have declared it in ld.so.conf.d and then I ran ldconfig:

```
$ cat /etc/ld.so.conf.d/cuda-12-2.conf
/usr/local/cuda-12.2/targets/x86_64-linux/lib
```

### What jax/jaxlib version are you using?

jax 0.4.18, jaxlib 0.4.18+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.11.4, Ubuntu 22.04

### NVIDIA GPU info

```
$ nvidia-smi
Wed Oct 18 11:06:08 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:2D:00.0 Off |                  N/A |
|  0%   46C    P8              26W / 370W |    240MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1333      G   /usr/lib/xorg/Xorg                          182MiB |
|    0   N/A  N/A      1577      G   /usr/bin/gnome-shell                         48MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment]
The easiest solution is to use two separate virtualenvs, and install PyTorch and JAX in separate environments. JAX will use your local CUDA installation if the packages are not installed in the virtualenv.

Does that work for you?

**Comment by FlorinAndrei** [comment]
Is there any way to keep them in the same virtualenv and have JAX use the correct CUDA version?

(I would not have opened this ticket if the multiple venvs solution was okay.)

**Comment by hawkinsp** [comment]
The fundamental problem is that PyTorch pins an exact CUDA version, and that CUDA version is not compatible with the CUDA version that JAX chooses.

It is *highly* likely that PyTorch's CUDA dependencies are too tight, and if you simply install JAX after PyTorch JAX's newer CUDA version will be chosen. NVIDIA's libraries are backward compatible, at least in theory. I've raised this with the PyTorch maintainers in the past.

It sounds like going forward there's a strong desire to keep at least one version compatible with PyTorch's CUDA version.

I note that we both have CUDA 11.8 releases, so that's an option.

**Comment by danjenson** [comment]
I'm having the same problem, on a fresh install of python 3.11.3, I ran `pip install ipython torch "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

Then, when Is started up ipython and ran `import jax.numpy as jnp; jnp.linspace(-1, 1, 20)` I got the following error

```
In [1]: import jax.numpy as jnp

In [2]: jnp.linspace(-1, 1, 30)
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1697727616.908622   25182 tfrt_cpu_pjrt_client.cc:349] TfrtCpuClient created.
---------------------------------------------------------------------------
XlaRuntimeError                           Traceback (most recent call last)
Cell In[2], line 1
----> 1 jnp.linspace(-1, 1, 30)

File ~/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/numpy/lax_numpy.py:2396, in linspace(start, stop, num, endpoint, retstep, dtype, axis)
   2394 num = core.concrete_or_error(operator.index, num, "'num' argument of jnp.linspace")
   2395 axis = core.concrete_or_error(operator.index, axis, "'axis' argument of jnp.linspace")
-> 2396 return _linspace(start, stop, num, endpoint, retstep, dtype, axis)

    [... skipping hidden 14 frame]

File ~/.pyenv/versions/3.11.3/lib/python3.11/site-packages/jax/_src/compiler.py:251, in backend_compile(backend, module, options, host_callbacks)
    246   return backend.compile(built_c, compile_options=options,
    247                          host_callbacks=host_callbacks)
    248 # Some backends don't have `host_callbacks` option yet
    249 # TODO(sharadmv): remove this fallback when all backends allow `compile`
    250 # to take in `host_callbacks`
--> 251 return backend.compile(built_c, compile_options=options)

XlaRuntimeError: FAILED_PRECONDITION: Couldn't get ptxas/nvlink version string: INTERNAL: Couldn't invoke ptxas --version

In [3]: import torch

In [4]: torch.ones(10)
Out[4]: tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```
However, torch does seem to work.

**Comment by hawkinsp** [comment]
@danjenson That sounds like a different problem. Can you open a separate issue? (In that issue, please show the output of `pip list` and `which ptxas`, and let me know if you have any other CUDA installations.)

**Comment by FlorinAndrei** [comment]
> I note that we both have CUDA 11.8 releases, so that's an option.

Ah, yes, good point that I've somehow missed. Let me try that.

**Comment by FlorinAndrei** [comment]
Looks like using CUDA 11.8 made everyone happy. Thanks for the suggestion!
