### ISSUE TITLE
x86_64-specific infinities bug in logsumexp (arm works fine)

### ISSUE THREAD

**Issue by alleSini99** [google/jax#18183]
### Description

`jax.scipy.special.logsumexp` returns a different output on x86_64 and ARM. 

MWE: 
```
import jax
import jax.numpy as jnp
import scipy
from jax import config

a = jnp.array([1e20, 1e20, 1.1])
loga = jnp.log(a)
coeffs = jnp.array([1, -1, 1])

print("Jax with float32:", jax.scipy.special.logsumexp(loga, b=coeffs))

config.update("jax_enable_x64", True)

print("Jax with float64:", jax.scipy.special.logsumexp(loga, b=coeffs))
print("Scipy:", scipy.special.logsumexp(loga, b=coeffs))
print("log(1.1): ", jnp.log(1.1))

```

On x86_64, the MWE returns incorrect results for `jax`: 
```
Jax with float32: -inf
Jax with float64: -inf
Scipy: 0.09531020207313645
log(1.1):  0.09531017980432493
```
while on ARM it gives the correct outputs:
```
Jax with float32: 0.09531021
Jax with float64: 0.09531021
Scipy: 0.09531020207313645
log(1.1):  0.09531017980432493
```

@PhilipVinc 

### What jax/jaxlib version are you using?

jax 0.4.18, jaxlib 0.4.18

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.10.4, Linux and Mac

**Comment by jakevdp** [comment]
Thanks for the clean repro: I've reduced the problem to this:
```python
import jax.numpy as jnp
a = jnp.array([1, -1, 1E-20])
print(a.sum())
```
On x86_64, the result is `0.0`. On AMD, the result is `1e-20`.

Clearly the difference here is order of operations within the `sum` implementation combined with typical floating point precision: if you sum front to back, the ones cancel and you're left with `1e-20`. If you sum back to front, the `1E-20` is lost to float rounding error and you're left with `0.0`.

I'm not sure whether this can be considered a bug or just an expected consequence of rounding errors in floating point math.

What do you think?

**Comment by jakevdp** [comment]
I also just noticed that numpy has this problem as well, depending on the ordering of the inputs:
```python
import numpy as np
import scipy

a = np.log([1e20, 1e20, 1.1])
b = np.array([1, -1, 1])
print(scipy.special.logsumexp(a, b=b))
# 0.0953101798043221
print(scipy.special.logsumexp(a[::-1], b=b[::-1]))
# -inf
```
I don't think there's anything to fix here: this is just a fact of life when approximating real-valued math with floating point operations.
