### ISSUE TITLE
`jnp.linalg.eig` errors for invalid inputs instead of returning nan

### ISSUE THREAD

**Issue by f0uriest** [google/jax#18226]
### Description

```python
A = jnp.nan*jnp.ones((3,3))

jnp.linalg.eig(A)
```

The above code gives the following:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
ValueError: On entry to DHSEQR parameter number 4 had an illegal value
```

This seems to be at odds with the rest of the operations in JAX that would silently return nan of the correct shape/dtype. For example, `eigh`, `qr`, `svd` etc all return nan without throwing an error.

Is this behavior intended? 

### What jax/jaxlib version are you using?

jax:    0.4.13 jaxlib: 0.4.13 numpy:  1.24.3 python: 3.10.11 (main, May 16 2023, 00:28:57) [GCC 11.2.0]

**Comment by jakevdp** [comment]
Thanks for the report – the behavior here seems to differ depending on the lapack package you have installed. On OSX, I'm seeing warnings printed to stderr rather than any ValueError; on Colab CPU the computation hangs.

**Comment by hawkinsp** [comment]
#18611 should fix this.
