### ISSUE TITLE
Raise Error in `jax.distributed.initialize()` if called after a JAX computation

### ISSUE THREAD

**Issue by mehdiataei** [google/jax#18237]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

It makes sense if in distributed environments the `jax.distributed.initialize()` function raises an error when invoked after a JAX computation or memory allocation has already taken place. This is useful for projects with multiple files and libraries where computations might occur during the initialization of other classes. Currently, no error or warning message is produced.

#### Examples

```python
import jax
jax.distributed.initialize()  # Should not produce any error
```

```python


import jax
x = jax.numpy.array([1.])
jax.distributed.initialize()  # Should produce an error
```

**Comment by hawkinsp** [comment]
#18374 means that `jax.distributed.initialize` will raise a `RuntimeError` if you've already initialized jax.

**Comment by mehdiataei** [comment]
Thanks!
