### ISSUE TITLE
`BCOO.fromdense` is not compatible with `jax.vmap`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#18245]
### Description

Something unrelated that I bumped into whilst investigating #18244:
```python
import jax
import jax.numpy as jnp
from jax.experimental import sparse

matrix = jax.vmap(sparse.BCOO.fromdense)(jnp.arange(16.).reshape(1, 4, 4))
#   File ".../jax/experimental/sparse/util.py", line 106, in _count_stored_elements
#     return int(_count_stored_elements_per_batch(mat, n_batch, n_dense).max(initial=0))
#            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
# jax.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: traced array with # shape int32[].
# The problem arose with the `int` function. If trying to convert the data type of a value, try using `x.astype(int)` or # `jnp.array(x, int)` instead.
```
I know about the `fromdense(..., n_batch=...)` argment, but I think it'd be reasonable for `fromdense` to occur within traced code.

### What jax/jaxlib version are you using?

JAX 0.4.19

**Comment by jakevdp** [comment]
This is working as intended. You need to pass a static value to `nse` in order to use `BCOO.fromdense` within `vmap` and other JAX transformations.

**Comment by patrick-kidger** [comment]
Ah, gotcha. In that case I think treat this as a report that the error message could be improved.

**Comment by jakevdp** [comment]
Thanks - I think the intent is that it would hit this line and raise a useful error, but it's clearly not doing that: https://github.com/google/jax/blob/20e583834ee8e8dc6e4d0c43d2eb86cfe9428f58/jax/experimental/sparse/bcoo.py#L289
