### ISSUE TITLE
Allow vmap to accept unbatchable arguments if they aren't mapped over

### ISSUE THREAD

**Issue by duvenaud** [google/jax#183]
I want to use vmap on functions that have some arguments which don't need to be mapped over.  I can specify this using in_axes, but vmap doesn't allow this for some argument types.  It seems to check if every argument is a valid type for batching, even if that argument is ignored due to in_axes.  Can you remove this check for those arguments which won't be batched over?

A simple example:

```Python
from jax.api import vmap
import jax.numpy as np

def mymap(f, x):
    return f(x)

vmap(mymap, in_axes=(None, 0))(np.sin, np.linspace(0, 1, 10))
```

Fails with `TypeError: <type 'function'> is not a valid type for batching`

This is a minor issue, because I could get around with with `partial` or by making closures, but that clutters up the code a bit.

**Comment by mattjj** [comment]
I think we can make this work by making an in-axis of `None` do something similar to what `argnums` does in `grad` (i.e. basically doing the `partial`/closure thing).
