### ISSUE TITLE
Potential type promotion bug.

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#1830]
Since the latest jax type promotion changes I'm seeing the following strange type promotion behavior (x64, CPU at head):

```python
import jax.numpy as np
from jax.config import config
config.update('jax_enable_x64', True)
xs = np.array([1., 2.], np.float32)
sigma = np.float32(1.0)
print(np.exp(xs / sigma ** 2).dtype)  # Float64
```

**Comment by hawkinsp** [comment]
This isn't really a bug, but I agree it's something we might like to improve. I believe this behavior hasn't been altered by the recent type promotion changes; it has always held.

This behavior follows from two facts:
* `jax.numpy.float32` is an alias for `numpy.float32`. This means it acts identically in every way.
* Numpy has the following promotion behavior:
```
In [6]: type(onp.float32(1.0) ** 2)
Out[6]: numpy.float64
```
i.e., the RHS argument to the `/` operator in your example above is a `float64`, which JAX respects. So this is really a NumPy vs JAX difference.

The best fixes I can think of is:
a) use an array instead of a `NumPy` scalar:
```
print(np.exp(xs / np.array(sigma) ** 2).dtype)
float32
```
b) we change JAX to offer its own scalar objects whose promotion behavior matches the JAX array promotion behavior.
c) we change `jax.numpy.float32(x)` to return a JAX array object.

**Comment by shoyer** [comment]
For what it's worth, I think the idiomatic way to write something like this, in both JAX and NumPy, is now to use Python floats:
```python
xs = np.array([1., 2.], np.float32)
sigma = 1.0
print(np.exp(xs / sigma ** 2).dtype)  # float32
```
These end up giving the same result in `jax.numpy` and `numpy`, but for two different reasons:
- JAX special cases Python's builtin `float` in its casting rules as having lower priority than array dtypes.
- NumPy has *value dependent casting* for scalars and 0d arrays. So NumPy has different behavior than JAX if you use Python scalars not representable in float32, e.g., `sigma = 1e40`.

**Comment by shoyer** [comment]
> c) we change `jax.numpy.float32(x)` to return a JAX array object.

This seems like a reasonable choice, but keep in mind we will probably also have to special-case `jax.numpy.float32` (whatever it is) when it's passed into a `dtype` argument in JAX. One of the most common uses for these type scalars is to write something like `x.astype(np.float32)`.

The downside is that there is no way we can make `x.astype(np.float32)`  work if `x` is a NumPy array. Users will get `TypeError: data type not understood`.

Given that it may be impossible to make something that matches all user expectations, this may be an argument for dropping aliases like `jax.numpy.float32` entirely, though I'm sure that would encounter resistance :)

**Comment by hawkinsp** [comment]
@shoyer I'm not so sure about that:
```
In [1]: import numpy as onp; from jax import numpy as np, lax; import jax                             
c
In [2]: class Foo(onp.int32): 
   ...:     pass 
   ...:                  

In [3]: Foo              
Out[3]: __main__.Foo

In [4]: Foo(3)           
Out[4]: 3

In [5]: onp.array([2, 4], dtype=Foo)               
Out[5]: array([2, 4], dtype=int32)

In [8]: x = onp.random.randn(3, 4)                                                                        

In [9]: x                                                                                                 
Out[9]: 
array([[ 0.61102705, -1.28747357, -0.87507959, -0.83302679],
       [-1.21343036, -1.44278927,  1.71148559,  1.00484012],
       [-0.09954842, -0.32945393,  0.75188577,  1.38867382]])

In [10]: x.astype(Foo)                                                                                    
Out[10]: 
array([[ 0, -1,  0,  0],
       [-1, -1,  1,  1],
       [ 0,  0,  0,  1]], dtype=int32)

```
I don't know why it works, but it does!

**Comment by hawkinsp** [comment]
```
import numpy as onp
from jax import numpy as np

class MyMeta(type):
  def __call__(cls, *args, **kwds):
    return np.array(*args, dtype=onp.int32)

class MyInt32(onp.int32, metaclass=MyMeta):
  pass
```
seems pretty promising.

```
In [31]: MyInt32(77)                                                                                      
Out[31]: DeviceArray(77, dtype=int32)
```

**Comment by shoyer** [comment]
This looks like good luck rather than an intentional feature, so I would be hesitant to count on long term :)

Either way, if we use it definitely use `__new__` rather than writing a meta class.

**Comment by hawkinsp** [comment]
This appears not to be an accident:
https://github.com/numpy/numpy/blob/bf9614b3253e9ef4dbbcef1f48751955b8f2a598/numpy/core/src/multiarray/scalarapi.c#L466

To quote:
```
    /*
     * Otherwise --- type is a sub-type of an array scalar
     * not corresponding to a registered data-type object.
     */
```

The numpy tests also pointed me to what appears to be a slightly cleaner solution:
https://github.com/numpy/numpy/blob/bf9614b3253e9ef4dbbcef1f48751955b8f2a598/numpy/core/tests/test_dtype.py#L1057

```
import numpy as onp
from jax import numpy as np

class MyInt32(object):
  dtype = onp.dtype(onp.int32)
  def __new__(cls, x):
    return np.array(x, dtype=onp.int32)
```

i.e., it appears to be a tested property of `np.dtype` that it checks for a `dtype` attribute.

**Comment by shoyer** [comment]
> i.e., it appears to be a tested property of `np.dtype` that it checks for a `dtype` attribute.

Yes, this looks like a clean solution. It's tested, so we can probably rely on it, though of course it appears to be undocumented!

**Comment by hawkinsp** [comment]
I verified the original example in this bug now yields `float32`.

Hope that helps!
