### ISSUE TITLE
The default argument optimize of einsum in the document is 'optimal', not False.

### ISSUE THREAD

**Issue by nasyxx** [google/jax#18313]
### Description

The default argument optimize of einsum in the document is 'optimal', not False.

It seems like the documentation comes directly from numpy and jax changes the defaults.

<img width="930" alt="Screenshot 2023-10-29 at 1 57 19 PM" src="https://github.com/google/jax/assets/5007613/ee7adac3-9086-4caf-a99b-3816764be545">

<img width="843" alt="Screenshot 2023-10-29 at 2 00 26 PM" src="https://github.com/google/jax/assets/5007613/8bbee68c-fcb6-4dea-9f11-38aa0ccfd88d">

**Comment by jakevdp** [comment]
Thanks - you're correct that the documentation comes straight from NumPy (we note that with *original documentation below* at the top of the docstring). We can add a note about the different default value at the top of the JAX docstring.
