### ISSUE TITLE
jaxlib versions deprecated from PyPi repository

### ISSUE THREAD

**Issue by sergiuiacob1** [google/jax#18368]
### Description

This is the second / third time I've experienced CI pipelines failing suddenly over night due to jaxlib / jax / iree libraries having versions deprecated in the PyPi repository. Not to mention the amount of breaking changes that happen between version bumps, which means upgrading is not so straightforward.

This breaks long-living projects and should be treated more seriously. Specifically in my case, `jaxlib==0.3.15` is not available anymore.

In my case, upgrading is very time consuming – looking for a solution to install 0.3.15 from an archive, if there's any

### What jax/jaxlib version are you using?

0.3.15

### Which accelerator(s) are you using?

CPU

### Additional system info

*

### NVIDIA GPU info

-

**Comment by sergiuiacob1** [comment]
For iree, there's this: https://iree.dev/pip-release-links.html

Is there something like this for jaxlib?

**Comment by yudonglee** [comment]
+1， why jaxlib's 0.3.25 is deprecated ? It's not too old. Could you just recover it please ?

**Comment by hawkinsp** [comment]
Simple: we ran out of space on Pypi. This happens regularly: for pretty much every new release, we have to delete one or more old releases.

Older jax releases are available in this GCS bucket: https://storage.googleapis.com/jax-releases/jax_releases.html

i.e.: `pip install jax==VERSION -f https://storage.googleapis.com/jax-releases/jax_releases.html`

Perhaps it's time to ask pypi again for more space. They weren't very excited about giving us more last time we asked.

**Comment by cemlyn007** [comment]
I think in the future it would have been nice to have had a heads up!

**Comment by jakevdp** [comment]
> I think in the future it would have been nice to have had a heads up!

What medium would have worked to give you this heads-up? A pinned discussion? A CHANGELOG entry?

**Comment by cemlyn007** [comment]
I check the CHANGELOG regularly thanks to GitHub notifications as I'm always excited to see what is happening with JAX, but to be honest we might just install jaxlib using https://storage.googleapis.com/jax-releases/jax_releases.html that Hawkins pointed out since this is a friction point with PyPi having a storage limit!

Do you think https://storage.googleapis.com/jax-releases/jax_releases.html will be more stable than PyPi going forward?

**Comment by jakevdp** [comment]
We plan to keep wheels indefinitely on https://storage.googleapis.com/jax-releases/jax_releases.html

**Comment by cemlyn007** [comment]
Okay great, hope you guys have a good weekend! 💯

**Comment by sergiuiacob1** [comment]
@hawkinsp @jakevdp Thank you for your answers and for your contributions. The link above to the GCS bucket should do for now.

One improvement which could be done here is make the jax/jaxlib library output a "This version will be deprecated after `Date`" message at startup, but I realize that may not be so foreseeable unless there's a fixed release schedule.

That being said, I consider this issue done, thank you!

**Comment by lucaslingle** [comment]
@hawkinsp @jakevdp 

I am looking at the Google Storage bucket linked above and I don't see anything hosted for Jax ```0.2.*```. 

The [LRA codebase](https://github.com/google-research/long-range-arena/) raises an error indicating a breaking change when I used Jax ```0.3.*```, and the LRA repo [provides](https://github.com/google-research/long-range-arena/blob/main/requirements.txt) a loosely-specified dependency of ```jax>=0.2.4```, so including Jax ```0.2.*``` on the aforementioned Google Storage bucket would be very helpful. 

Can you make these versions available as well? Thank you!

**Comment by jakevdp** [comment]
This question is answered here: https://github.com/google/jax/issues/18993#issuecomment-1857881855

All previous jaxlib versions are available at the cloud storage bucket, but note that there was never a v0.2.X release of jaxlib (it went straight from 0.1.76 to 0.3.0).

**Comment by royfrancis** [comment]
I was able to install `jax==0.3.1` but I also need `jaxlib 0.3.0`.

```
pip install jaxlib==0.3.0 -f https://storage.googleapis.com/jax-releases/jax_releases.html

Looking in links: https://storage.googleapis.com/jax-releases/jax_releases.html
ERROR: Ignored the following yanked versions: 0.4.32
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.0 (from versions: 0.4.18, 0.4.19, 0.4.20, 0.4.21, 0.4.22, 0.4.23, 0.4.24, 0.4.25, 0.4.26, 0.4.27, 0.4.28, 0.4.29, 0.4.30, 0.4.31, 0.4.32, 0.4.33, 0.4.34, 0.4.35, 0.4.36, 0.4.38, 0.5.0)
ERROR: No matching distribution found for jaxlib==0.3.0
```

**Comment by jakevdp** [comment]
@royfrancis what version of Python are you using? Note that older jaxlib wheels were only released for the versions of Python that were available at the time of their release, so for example you won't find a jaxlib 0.3.0 wheel for Python 3.12.
