### ISSUE TITLE
[Pallas] GPU: CUDA error when kernel launch dimensions >= 65536 in Y or Z

### ISSUE THREAD

**Issue by shacklettbp** [google/jax#18361]
### Description

The following code (adapted from the pallas quickstart) results in a CUDA error, because Pallas tries to launch the resulting CUDA kernel with too large a grid in the Y dimension.

```python
import jax
from jax import random
from jax.experimental import pallas as pl

def add_vectors_kernel(x_ref, y_ref, o_ref):
  x, y = x_ref[...], y_ref[...]
  o_ref[...] = x + y

@jax.jit
def add_vectors(x: jax.Array, y: jax.Array) -> jax.Array:
  return pl.pallas_call(add_vectors_kernel,
                        out_shape=jax.ShapeDtypeStruct(x.shape, x.dtype)
                        )(x, y)

# add batch dimension
add_vectors = jax.vmap(add_vectors)

# Standard [N, C] succeeds because leading dimension is mapped to X dim in launch grid
print(add_vectors(random.uniform(random.PRNGKey(5), (65536, 64)),
                  random.uniform(random.PRNGKey(6), (65536, 64))))

# Adding another batch dimension
add_vectors = jax.vmap(add_vectors)

# Fails, because now N = 65536 is mapped to the Y dim in launch grid
print(add_vectors(random.uniform(random.PRNGKey(5), (4, 65536, 64)),
                  random.uniform(random.PRNGKey(6), (4, 65536, 64))))
```

On my machine (jax & jaxlib head, jax-triton 1f41ec2 and triton-nightly-2.1.0.dev20231014192330, cuda 12), the above code prints the following:
```
Launching [N, C]
[N, C] success 0.9997495412826538
Launching [P, N, C]
2023-11-02 14:19:11.657404: W external/xla/xla/service/gpu/runtime/support.cc:58] Intercepted XLA runtime error:
INTERNAL: jaxlib/gpu/triton_kernels.cc:259: operation gpuLaunchKernel( kernel, grid[0], grid[1], grid[2], block_dim_x_, 1, 1, shared_mem_bytes_, stream, params, nullptr) failed: CUDA_ERROR_INVALID_VALUE
2023-11-02 14:19:11.657424: E external/xla/xla/pjrt/pjrt_stream_executor_client.cc:2716] Execution of replica 0 failed: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/triton_kernels.cc:259: operation gpuLaunchKernel( kernel, grid[0], grid[1], grid[2], block_dim_x_, 1, 1, shared_mem_bytes_, stream, params, nullptr) failed: CUDA_ERROR_INVALID_VALUE; current tracing scope: custom-call.0; current profiling annotation: XlaModule:#hlo_module=jit_add_vectors,program_id=6#.
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pallas_error.py", line 29, in <module>
    r = add_vectors(random.uniform(random.PRNGKey(5), (4, 65536, 64)),
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to execute XLA Runtime executable: run time error: custom call 'xla.gpu.custom_call' failed: jaxlib/gpu/triton_kernels.cc:259: operation gpuLaunchKernel( kernel, grid[0], grid[1], grid[2], block_dim_x_, 1, 1, shared_mem_bytes_, stream, params, nullptr) failed: CUDA_ERROR_INVALID_VALUE; current tracing scope: custom-call.0; current profiling annotation: XlaModule:#hlo_module=jit_add_vectors,program_id=6#.
```

For context, I'm hitting this issue in my population-based-training codebase, where I'm training an ensemble of models simultaneously using jax.vmap over my update loop (this expands the training loop inputs from shape [N, C] to [P, N, C], where P is my population size and P << N). I'm using pallas to optimize certain layers within my model, and I hit this error when N >= 65536.

The core issue is twofold:
1. The pallas_call batching rule internally *prepends* the vmapped dimension to GridMapping
2. When mapping this to a 3D CUDA grid, [`_process_grid_to_3d_grid`](https://github.com/google/jax/blob/main/jax/_src/pallas/triton/lowering.py#L167) just assigns the GridMapping dims from left to right to X, Y, and Z in the kernel launch.

The problem is that the CUDA API [specifies](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#features-and-technical-specifications) that the max dimensions for a launch are [2^31 - 1, 65535, 65535] for the 3D grid. I believe the intent is that adjacent threadblocks will be assigned along the x dimension first (like the inner loop in a triple nested for loop over z, y, then x). 

Given these semantics, I think it would actually make the most sense for the pallas_call batching rule to *append* the vmapped dimensions to the GridMapping rather than prepending them, but I don't know if that would have negative implications for the TPU backend. That would result in a 2D kernel launch of size [65536, 4] in my above example. For >3 grid dimensions, `_process_grid_to_3d_grid` could collapse the additional dimensions into the Z launch dimension rather than X, although something would need to be done if the resulting Z dimension was greater than 65535.

To sidestep all these issues in my own repo and avoid changing the pallas_call batching rule, I've replaced `_process_grid_to_3d_grid` with an implementation that just collapses all the dimensions into X, resulting in a one dimensional kernel launch, leveraging the fact that the X launch dimension can go all the way up to 2^31 - 1:
```python
def _process_grid_to_3d_grid(builder, grid_mapping: GridMapping):
  if len(grid_mapping.grid) == 0:
    return grid_mapping.grid, []

  total_axis_size = np.prod(grid_mapping.grid)
  new_grid = (total_axis_size,)

  def make_subidx(cur_idx, s):
    return (
        cur_idx.__floordiv__(s, _builder=builder),
        cur_idx.__mod__(s, _builder=builder),
    )

  grid0 = tl.program_id(0, _builder=builder)
  out_indices = [0] * len(grid_mapping.grid)

  # Preserve existing ordering for non-mapped dims
  for i, s in enumerate(grid_mapping.grid):
    if i in grid_mapping.mapped_dims:
      continue

    grid0, out_indices[i] = make_subidx(grid0, s)

  # For mapped dims, iterate the inner mapped dims to the outer dims. This 
  # follows the pallas_call batching rule that prepends the vmapped dimension.
  # Intuitively, it makes sense to iterate over the inner mapped dimensions first.
  for dim in reversed(grid_mapping.mapped_dims):
    s = grid_mapping.grid[dim]
    grid0, out_indices[dim] = make_subidx(grid0, s)

  return new_grid, out_indices
```

This fixes the above crash for me (and all the pallas tests still pass). The downside of this approach is that the resulting kernel has to do a bit more indexing math. I haven't checked for a performance impact yet (although I doubt it would be significant).

Please let me know if I should open a pull request with this solution (or I'd be happy to implement it differently if some other strategy is more desirable).

### What jax/jaxlib version are you using?

jax c8b7c1b80 (HEAD), jaxlib c8b7c1b80

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.10, Linux

### NVIDIA GPU info

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        Off | 00000000:01:00.0  On |                  N/A |
| 30%   48C    P8              42W / 350W |   1296MiB / 24576MiB |      3%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+------------------
----+
```

**Comment by sharadmv** [comment]
Thanks for the thorough investigation. The batch dimensions do need to be major dimensions on the TPU, so I don't think changing the batching rule is a good idea. Handling this issue in `_process_grid_to_3d_grid` makes sense.

I'm wondering if we can end up with a solution in between yours and the current one. Rather than folding all the thread indices into a 1d grid, could we treat the `x` dimension in the grid as the 'catch all' dimension (aka use a reversed CUDA launch grid). Are there any downsides to that approach?

**Comment by shacklettbp** [comment]
Thanks for the fast response: I've submitted a PR (linked above) that implements roughly your proposed solution. It has to be a bit more complicated, because you can hit easily hit this bug even with less than 3 axes. I've added code that collapses >3 dimensions into X, and then also will collapse further if the resulting Y or Z dimensions are too large.
