### ISSUE TITLE
Setting values in a matrix by broadcasting slower than using a loop after jit compilation

### ISSUE THREAD

**Issue by BH4** [google/jax#18420]
### Description

When inserting an array of values into a matrix using a for loop seems to run faster than setting the values by broadcasting after compilation. The compilation of the for loop is much slower as expected. This issue only seems to show up when using "jax_enable_x64" as when I remove that and use the default dtype for the matrices the broadcasting solution is faster than the loop as expected. 

```python
import jax
import jax.numpy as jnp
from time import time
from jax.config import config
config.update("jax_enable_x64", True)


npart = 50

npair = npart * (npart - 1)
k = jnp.arange(npair)
ip = jnp.empty(npair, dtype=int)
jp = jnp.empty(npair, dtype=int)
k = 0
for i in range(npart):
    for j in range(npart):
        if (i != j):
            ip = ip.at[k].set(i)
            jp = jp.at[k].set(j)
            k += 1

key = jax.random.PRNGKey(17)
key, key_input = jax.random.split(key)


@jax.jit
def loop_set(pf):
    Rho = jnp.zeros((npart+1, npart+1), dtype='complex128')
    for k in range(npair):
        Rho = Rho.at[ip[k], jp[k]].set(pf[k])
    return Rho


@jax.jit
def broadcast_set(pf):
    Rho = jnp.zeros((npart+1, npart+1), dtype='complex128')
    Rho = Rho.at[ip, jp].set(pf)
    return Rho


pf = jax.random.normal(key_input, shape=[npair])
key, key_input = jax.random.split(key)
t = time()
a = loop_set(pf)
a.block_until_ready()
print(f'loop_set compile time = {time()-t} (s)')

pf = jax.random.normal(key_input, shape=[npair])
key, key_input = jax.random.split(key)
t = time()
a = broadcast_set(pf)
a.block_until_ready()
print(f'broadcast_set compile time = {time()-t} (s)')


pf = jax.random.normal(key_input, shape=[npair])
key, key_input = jax.random.split(key)
t = time()
a = loop_set(pf)
a.block_until_ready()
print(f'loop_set run time = {time()-t} (s)')

pf = jax.random.normal(key_input, shape=[npair])
key, key_input = jax.random.split(key)
t = time()
a = broadcast_set(pf)
a.block_until_ready()
print(f'broadcast_set run time = {time()-t} (s)')
```

### What jax/jaxlib version are you using?

jax v0.4.13, jaxlib v0.4.13+cuda11.cudnn86

### Which accelerator(s) are you using?

GPU

### Additional system info

Python 3.8.10, Linux

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.129.06   Driver Version: 470.129.06   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100-SXM...  On   | 00000000:BD:00.0 Off |                    0 |
| N/A   27C    P0    53W / 400W |      0MiB / 40536MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Hi - thanks for the report! When I run your code on a Colab T4 GPU I see this:
```
loop_set compile time = 53.260170459747314 (s)
broadcast_set compile time = 0.1718456745147705 (s)
loop_set run time = 0.022067546844482422 (s)
broadcast_set run time = 0.02761054039001465 (s)
```
This is not all that different than what I'd expect for code like this: the compilation of the `for`-loop version takes a long time becuase JAX tracing unrolls python loops. In general, if you find yourself looping over array values, you should expect  compilation time to grow approximately quadratically with the number of iterations: this is becuse the compiler must consider each statement in sequence and use heuristics to figure out how to execute it efficiently withing the program.

On the other hand, a single broadcast statements will have relatively quick compilation, because it's only a single statement for the compiler to consider.

The flip-side of this is that loop-based implementations give the compiler a lot of freedom to select an efficient implementation, so the resulting function is often a bit faster than if the computation is expressed in terms of pre-defined kernels.

All of that seems consistent with the results you're seeing in your experiment.

**Comment by BH4** [comment]
I didn't realize the loop-based implementation would give the compiler more freedom. In my case I see the "loop_set run time" is quite a bit faster than the "broadcast_set run time" 
```
loop_set compile time = 44.53834414482117 (s)
broadcast_set compile time = 0.13554906845092773 (s)
loop_set run time = 0.009951353073120117 (s)
broadcast_set run time = 0.025753021240234375 (s)
```
From your explanation it seems this difference just comes down to what the hardware is built for? Thank you for the thorough and quick response!

**Comment by jakevdp** [comment]
Yeah, it's a combination of what operations the hardware can do efficiently, and what sequences of operations the XLA compiler has heuristics for. If you're curious about the details, you can dig deeper by printing out the optimized HLO using the [Ahead of time compilation](https://jax.readthedocs.io/en/latest/aot.html) APIs, but the HLO for your loop-based approach is going to be very long!

**Comment by jakevdp** [comment]
I'm going to close this as I think the question is addressed – thanks!
