### ISSUE TITLE
Derivative of jitted function gives NaN, but derivative of regular function gives 0

### ISSUE THREAD

**Issue by f0uriest** [google/jax#18450]
### Description

```python
jax.jit(lambda x, k: x**k)(0.0, 0)
```
this gives ```Array(1., dtype=float64, weak_type=True)``` as expected

```python
jax.jacfwd(lambda x, k: x**k)(0.0, 0)
```
gives ```Array(0., dtype=float64, weak_type=True)``` as (I think) expected - `x**0 == 1` for all `x`, and derivative of a constant is zero.

```python
jax.jacfwd(jax.jit(lambda x, k: x**k))(0.0, 0)
```
this gives ```Array(nan, dtype=float64, weak_type=True)``` Which seems possibly wrong, or at least inconsistent.

The same behavior holds true whether its the inner function that gets jitted or the jacobian funtion, and in both forward and reverse mode

### What jax/jaxlib version are you using?

jax version=0.4.13, jaxlib version=0.4.13

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks for the report!

I believe this issue was fixed by #17996; if you upgrade to jax version 0.4.19 or later you should see the expected output.
