### ISSUE TITLE
Large (but simple to compute) expression is constant folded

### ISSUE THREAD

**Issue by jewillco** [google/jax#18475]
### Description

It seems like constant folding does not consider the size of the generated constants versus the amount of computation needed for them. For example, `jnp.where(jnp.arange(100000) == 5, 1, 2)` is treated as a constant, even though it takes a lot of memory and is easy to compute. This is especially an issue on TPU, in which case the JAX-level constant folding prevents XLA from doing its own optimizations on the computation. It is possible to work around this using an extra `jax.jit`-wrapped function, but a better JAX heuristic would be helpful.

### What jax/jaxlib version are you using?

Top of tree

### Which accelerator(s) are you using?

TPU

**Comment by hawkinsp** [comment]
Can you give a reproduction? As best I can tell, JAX isn't constant-folding this expression:

```
$ print(jax.jit(lambda x: x + jnp.where(jnp.arange(100000) == 5, 1, 2)).lower(7).as_text(dialect="hlo"))

HloModule jit__lambda_, entry_computation_layout={(s32[])->s32[100000]{0}}

_where.8 {
  Arg_0.9 = pred[100000]{0} parameter(0)
  Arg_1.10 = s32[] parameter(1)
  broadcast.12 = s32[100000]{0} broadcast(Arg_1.10), dimensions={}
  Arg_2.11 = s32[] parameter(2)
  broadcast.13 = s32[100000]{0} broadcast(Arg_2.11), dimensions={}
  ROOT select.14 = s32[100000]{0} select(Arg_0.9, broadcast.12, broadcast.13)
}

ENTRY main.18 {
  Arg_0.1 = s32[] parameter(0), sharding={replicated}
  broadcast.16 = s32[100000]{0} broadcast(Arg_0.1), dimensions={}
  iota.6 = s32[100000]{0} iota(), iota_dimension=0
  constant.2 = s32[] constant(5)
  broadcast.3 = s32[100000]{0} broadcast(constant.2), dimensions={}
  compare.7 = pred[100000]{0} compare(iota.6, broadcast.3), direction=EQ
  constant.5 = s32[] constant(1)
  constant.4 = s32[] constant(2)
  call.15 = s32[100000]{0} call(compare.7, constant.5, constant.4), to_apply=_where.8
  ROOT add.17 = s32[100000]{0} add(broadcast.16, call.15)
}
```

**Comment by jewillco** [comment]
The larger code this was taken from did get constant-folded until we changed the function to have a separate `jax.jit` annotation and an `ndarray` input rather than a plain `int`. Are there things outside the code given that might have caused constant-folding? It would have been inside a JITted region but indirectly.

**Comment by jewillco** [comment]
It looks like we might have run the wrong version of the software when testing this.
