### ISSUE TITLE
libtpu.so present but jax fails with ".local/lib/python3.9/site-packages/libtpu/libtpu.so: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by Akinetopsia1** [google/jax#18486]
### Description

i just got my hands on an usb coral tpu and wanted to try JAX, however i can't seem to get it to work. I get:

```Exception occurred during processing of request from ('127.0.0.1', 45428)
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.9/site-packages/jax/_src/xla_bridge.py", line 623, in backends
    backend = _init_backend(platform)
  File "/home/username/.local/lib/python3.9/site-packages/jax/_src/xla_bridge.py", line 734, in _init_backend
    backend = registration.factory()
  File "/home/username/.local/lib/python3.9/site-packages/jax/_src/xla_bridge.py", line 139, in tpu_client_timer_callback
    client = xla_client.make_tpu_client(_get_tpu_library_path())  # type: ignore
  File "/home/username/.local/lib/python3.9/site-packages/jaxlib/xla_client.py", line 188, in make_tpu_client
    load_pjrt_plugin_dynamically('tpu', library_path or 'libtpu.so')
  File "/home/username/.local/lib/python3.9/site-packages/jaxlib/xla_client.py", line 144, in load_pjrt_plugin_dynamically
    return _xla.load_pjrt_plugin(plugin_name, library_path)
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: Failed to open /home/username/.local/lib/python3.9/site-packages/libtpu/libtpu.so: /home/username/.local/lib/python3.9/site-packages/libtpu/libtpu.so: cannot open shared object file: No such file or directory
```

however libtpu.so is present at that location:

```username@host:/var/www/temp $ ls /home/username/.local/lib/python3.9/site-packages/libtpu/libtpu.so
-rwxr-xr-x 1 username username 265M Nov 10 12:54 /home/username/.local/lib/python3.9/site-packages/libtpu/libtpu.so
```

of note, i'm just trying things out and did not setup a venv

### What jax/jaxlib version are you using?

jax-0.4.20

### Which accelerator(s) are you using?

TPU

### Additional system info

Raspberry Pi 4, Debian GNU/Linux 11 (bullseye) 64bit

**Comment by hawkinsp** [comment]
Ah! `libtpu` is for Google's Cloud TPU VM product (https://cloud.google.com/tpu), which is a datacenter accelerator.  Cloud TPUs are a different thing to "Edge TPU"s, which are a very different kind of TPU for low-power edge devices.

JAX doesn't support edge TPU at the moment, I'm afraid!

The error loading the `.so` file is because it is the wrong architecture: it's an x86-64 library, but the Raspberry Pi is an ARM machine.

Hope that helps! I'm sorry I don't have better news.

**Comment by Akinetopsia1** [comment]
oops. *facepalm*

i was hoping to accelerate numpy operations on large datasets. I guess i didn't read enough beforehand. Another search tells me the tensorflow package might offer what i need. 

Thanks!
