### ISSUE TITLE
jax.eval_shape silence the typing annotations

### ISSUE THREAD

**Issue by Conchylicultor** [google/jax#18502]
`jax.eval_shape` is badly annotated, so users loose type-checking and auto-complete on returned input.

Current anntations:

```python
def eval_shape(fun: Callable, *args, **kwargs)
```

Should be instead:

```python
P = ParamSpec('P')
OutT = TypeVar('OutT')

def eval_shape(fun: Callable[P, OutT], *args: P.args, **kwargs: P.kwargs) -> OutT:
```

The `ParamSpec` is less important, but loosing the type checking on the function output is quite annoying as there's no more auto-complete on the output:

```
x = jax.eval_shape(my_fn)
x.attr  # < No auto-complete here :'(
```

**Comment by jakevdp** [comment]
Thanks! I think this annotation predates the availability of `typing.ParamSpec`.

However, there's a bit of a problem here: `eval_shape` does not return the same type as the input function, rather it returns the same pytree structure, with all array & scalar entries replaced by `ShapeDtypeStruct`. I'm not sure that Python type annotations are expressive enough to actually annotate that behavior.

What do you think?

**Comment by Conchylicultor** [comment]
Thank you for the answer. I agree that python annotations are not expressive enough, however this seems a case where practicality should beat purity.

```python
@flax.struct.dataclass
class Batch:
  img: Float['h w c']
  label: Float['h w c']


def fn() -> Batch:
  ...

type(fn()) is Batch
type(jax.eval_shape(fn)) is Batch
```

I think loosing auto-complete has quite a big impact on productivity. In our codebase, we reduce friction to the minimum and forcing users to inspect the original function and having to navigate multiple levels in the codebase to understand the structure.

**Comment by jakevdp** [comment]
Sure, we can give it a try, but fundamentally the proposed annotation is incorrect, so if it breaks too many downstream packages we won't be able to add it.

**Comment by Conchylicultor** [comment]
I expect this will break code. Not because of the `jax.Array` vs `ShapeDtypeStruct`, but because it will uncover actual pytype error that were previously hidden.

I recently sent cl/582235119 to fix annotations for `@jax.named_call` (which should be a no-op), but this exposed many bad calls that were ignored by pytype because decorated function were loosing their type checking.

It should also be possible to support the simple cases of simple nested structures with overload:

```python
PyTree = _T | list['PyTree[_T]'] | dict[str, 'PyTree[_T]'] | tuple['PyTree[_T]',...]

@overload
def eval_shape(fun: Callable[P, jax.Array], *args: P.args, **kwargs: P.kwargs) -> jax.ShapeDTypeStruct:
  ...

@overload
def eval_shape(fun: Callable[P, PyTree[jax.Array]], *args: P.args, **kwargs: P.kwargs) -> PyTree[jax.ShapeDTypeStruct]]:
  ...

@overload
def eval_shape(fun: Callable[P, OutT], *args: P.args, **kwargs: P.kwargs) -> OutT:
  ...
```

But this might add too much complexity

**Comment by jakevdp** [comment]
That works for the simplest cases, but arbitrary types can be registered as pytrees at runtime so fundamentally there's no way to correctly annotate PyTrees in Python's type system.

**Comment by patrick-kidger** [comment]
I don't think this will help JAX itself, but if it helps any third-party projects: the next jaxtyping release will have enough to make annotating this possible.
```python
from collections.abc import Callable
from typing import TypeAlias

import jax
from jaxtyping import ArrayLike, PyTree

ArrayOut: TypeAlias = PyTree[ArrayLike, "T"]
StructOut: TypeAlias = PyTree[jax.ShapeDtypeStruct, "T"]

def eval_shape(Callable[..., ArrayOut], ...) -> StructOut:
    ...
```
where the `"T"` is bound to the PyTree structure, so both input and output must have matching structures. (And the `ArrayLike`  / `ShapeDtypeStruct` indicate the leaf types as usual.)

(
Actually, the next release will even make it possible to annotate that the array shapes match too:
```python
ArrayOut: TypeAlias = PyTree[Shaped[ArrayLike, "?*shape"], "T"]
StructOut: TypeAlias = PyTree[Shaped[jax.ShapeDtypeStruct, "?*shape"], "T"]
```
but that one is probably unreadable magic unless you really like your type annotations.
)

**Comment by jakevdp** [comment]
I'm going to close this; I don't think it's really possible to do better than the current annotation, given the fact that pytree types are not statically resolveable.
