### ISSUE TITLE
Add nn.squareplus

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#18519]
Add the [squareplus function](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Squareplus), as described in [_Squareplus: A Softplus-Like Algebraic Rectifier_](https://arxiv.org/abs/2112.11687), to [jax.nn](https://jax.readthedocs.io/en/latest/jax.nn.html). It's a smooth rectifier like softplus, but without numerical stability issues and faster (1 algebraic function instead of 2 transcendental functions):

```python3
import timeit

import jax
from jax import numpy as jnp, nn, random


def squareplus(x, b=4):
    y = x + jnp.sqrt(jnp.square(x) + b)
    return jnp.ldexp(y, -1)  # fast division by 2


key = random.PRNGKey(0)
x = random.normal(key, [10**8])

jit_softplus = jax.jit(nn.softplus)
jit_squareplus = jax.jit(squareplus)

jit_softplus(x).block_until_ready()
jit_squareplus(x).block_until_ready()

start = timeit.default_timer()
jit_softplus(x).block_until_ready()
print(timeit.default_timer() - start)

start = timeit.default_timer()
jit_squareplus(x).block_until_ready()
print(timeit.default_timer() - start)
```

```
0.23485908400016342
0.0861067619998721
```

I can submit a PR.

**Comment by hawkinsp** [comment]
Looks like we did this!

**Comment by carlosgmartin** [comment]
@jakevdp Out of curiosity, is there a reason why XLA doesn't have an ldexp primitive, or has it just not been requested/added yet? Seems like it could yield speed optimizations when users multiply/divide floats by a known power of 2.
