### ISSUE TITLE
Can you provide version 0.3.14 of jaxlib for download

### ISSUE THREAD

**Issue by whsybzz** [google/jax#18671]
Please:Can you provide version 0.3.14 of jaxlib

 ```
ERROR: Ignored the following yanked versions: 0.1.63, 0.4.0, 0.4.15
ERROR: Could not find a version that satisfies the requirement jaxlib==0.3.14 (from tensorflow-federated) (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20)
ERROR: No matching distribution found for jaxlib==0.3.14
```

**Comment by yashk2810** [comment]
It's not on pypi because of storage issues.

You can install it via this command:

pip install -U jaxlib==0.3.14 -f https://storage.googleapis.com/jax-releases/jaxlib_releases.html

**Comment by whsybzz** [comment]
@yashk2810 
Excuse me, is this the Linux version? I am using a remote server to execute ``` pip install - U jaxlib=0.3.14- f https://storage.googleapis.com/jax-releases/jaxlib_releases.html ```Post error

```

Looking in links: https://storage.googleapis.com/jax-releases/jaxlib_releases.html

Error: Ignored the following yang versions: 0.1.63, 0.4.0, 0.4.15

Error: Could not find a version that satisfies the requirement jaxlib=0.3.14 (from versions: 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.4.7, 0.4.9, 0.4.10, 0.4.11, 0.4.12, 0.4.13, 0.4.14, 0.4.16, 0.4.17, 0.4.18, 0.4.19, 0.4.20)

Error: No matching distribution found for jaxlib==0.3.14

```

**Comment by yashk2810** [comment]
Ohh, sorry this is the right command: `pip install -U jaxlib==0.3.14 -f https://storage.googleapis.com/jax-releases/jax_releases.html`

**Comment by jakevdp** [comment]
This is also mentioned in the docs here: https://jax.readthedocs.io/en/latest/installation.html#installing-older-jaxlib-wheels
