### ISSUE TITLE
multivariate_normal unexpected variances

### ISSUE THREAD

**Issue by reziproke87** [google/jax#1869]
Hello!

multivariate_normal does not produce the variances that I would expect. I checked the output of the multivariate_normal function in Numpy, which does provide the behaviour I expected.

In the code, I perform a sanity check that the covariance matrix is indeed positive definite (symmetric, positive eigenvalues), get 10.000 samples and calculate the variances.

```
import jax.numpy as np
import numpy as onp
from jax import random

N = 10000

cov_list = [[ 0.19,  0., -0.13, 0.], 
            [ 0., 0.19, 0., -0.13], 
            [-0.13, 0., 0.19, 0.], 
            [ 0., -0.13, 0., 0.19]]

cov_np = np.array(cov_list)
cov_onp = onp.array(cov_list)

mean_np = np.zeros(4)
mean_onp = onp.zeros(4)

positive_eig = (onp.linalg.eigvals(cov_onp) > 0.).all()
symmetric = ((cov_onp - cov_onp.T) == 0.).all()
print('Covariance matrix is symmetric:', symmetric, '\nAll eigenvalues are positive:', positive_eig)

out_onp = onp.random.multivariate_normal(mean_onp, cov_onp, N)
var = out_onp.var(axis=0)
print('\nNumpy: Variance of samples \n', var)

key = random.PRNGKey(0)
out_np = random.multivariate_normal(key, mean=mean_np, cov=cov_np, shape=(N,))
var = out_np.var(axis=0)
print('\nJax: Variance of samples \n', var)
```

The resulting output is as follows:

```
Covariance matrix is symmetric: True 
All eigenvalues are positive: True

Numpy: Variance of samples 
 [0.19001905 0.18978024 0.18641562 0.18503367]

Jax: Variance of samples 
 [0.28731692 0.28114378 0.09892643 0.10218105]
```

I get this result on two different machines (Ubuntu 16 and 18).

**jax version used**

jax 0.1.53
jaxlib 0.1.36

Any idea why this happens?

Cheers
Christian

**Comment by mattjj** [comment]
Thanks for catching this. [There's a missing transpose in `random.multivariate_normal`](https://github.com/google/jax/blob/96677d9c6f549b643fd0cdf5664da2f22f45fbaf/jax/random.py#L523) (I think because I assumed the result would be lower-triangular, like in `numpy.linalg`, but imported the `cholesky` from `scipy.linalg`.) More concerning is we didn't have a good enough test on `multivariate_normal` to catch this.

**Comment by mattjj** [comment]
Our previous tests [didn't check the covariance matrix](https://github.com/google/jax/blob/96677d9c6f549b643fd0cdf5664da2f22f45fbaf/tests/random_test.py#L407-L410), and everything is either tested or broken.
