### ISSUE TITLE
Failure while indexing across both dimensions of a 2D jax.lax.FilledConstant array

### ISSUE THREAD

**Issue by greydanus** [google/jax#187]
The same indexing works when applied to a numpy.ndarray. According to the README, all NumPy indexing (excepting indexed assignments) should work.

Screenshots:

Indexing works in original numpy but fails with jax's numpy
https://drive.google.com/file/d/1bpj4RWV9_oFajeEDAN43IdiN9VHeRHJE/view?usp=sharing

Indexing over one dimension works, but not over two:
https://drive.google.com/file/d/10nCNyIIj2Gr9vOcSKV0p203hfKqEuQd_/view?usp=sharing

Any idea why this is happening?

**Comment by greydanus** [comment]
Current workaround: cast to a numpy array immediately before the indexing operation (I assume this will hurt performance though)

```python
f = npo.asarray(f) # workaround
result = f[[0,2,4], [0,2,4]] # line that throws the error
```

**Comment by mattjj** [comment]
Nevermind, it's not #140, and actually is just a bug in our indexing implementation. In particular, this fails the same way:

```python
import numpy as onp
from jax import jit
jit(lamda x: x[[0, 2, 4], [0, 2, 4]])(onp.ones((5, 5))
```

**Comment by mattjj** [comment]
This is just a case we never handled correctly, due to one incorrect `isinstance(idx, list)` that should have been an `isinstance(idx, (list, tuple))`.
