### ISSUE TITLE
Option to sanitise MLIR dumps

### ISSUE THREAD

**Issue by ZacCranko** [google/jax#18734]
When JAX is exporting MLIR (via whatever incantation you like, my preferred one is `JAX_DUMP_IR_TO="tmp/jax_logs"`) a lot of sensitive information is included, in the form of lines that look like this
```
#loc105 = loc("state.params[“all”][“my”].company.everything.proprietary")
```
It would be good to have an option to emit sanitised mlir dumps.

**Comment by hawkinsp** [comment]
This should be easy enough to do. We have code in the compilation cache that strips MLIR location information for caching. We just need to do the same in the IR dumping path.
