### ISSUE TITLE
rocm 5.7.1 + 7900 xtx + jax:latest docker image not working

### ISSUE THREAD

**Issue by brettkoonce** [google/jax#18747]
hardware: 7900xtx
ubuntu 22.04 lts
rocm 5.7.1 (first version w/ official 7900xtx support)

I am able to run the pytorch image, eg:

```
drun rocm/pytorch
root@minerva:~# python3
Python 3.9.18 (main, Sep 11 2023, 13:41:44) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.device(0)
device(type='cuda', index=0)
>>> torch.cuda.get_device_properties(0).total_memory
25753026560
```

and have trained simple CNN models using this setup.

However, when I run the jax version of the same image I get the following error on launch of the image:

```
drun rocm/jax:rocm5.7.0-jax0.4.20-py3.11.0
root@minerva:/root# python3
Python 3.11.0 (main, Nov 16 2023, 20:45:15) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
2023-11-29 19:56:58.717575: E external/xla/xla/stream_executor/plugin_registry.cc:90] Invalid plugin kind specified: DNN
>>> jax.devices()
[CpuDevice(id=0)]
```

Is there something I should be doing differently?  Is this configuration officially supported?

**Comment by brettkoonce** [comment]
same for the latest image:
```
drun rocm/jax:latest
[sudo] password for skoonce: 
root@minerva:/root# python3
Python 3.10.0 (default, Nov 16 2023, 22:24:12) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
2023-11-30 12:48:26.684744: E external/xla/xla/stream_executor/plugin_registry.cc:90] Invalid plugin kind specified: DNN
```

**Comment by brettkoonce** [comment]
Per discussion in https://github.com/google/jax/issues/7598, waiting for Rocm 6.0!

**Comment by brettkoonce** [comment]
Updated to ROCm 6.0.  Pytorch image working!

Still getting this with rocm/jax:latest

```
drun rocm/jax
root@minerva:/root# python3
Python 3.10.0 (default, Dec 12 2023, 19:54:24) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
2023-12-16 22:23:14.261510: E external/xla/xla/stream_executor/plugin_registry.cc:90] Invalid plugin kind specified: DNN

```

**Comment by mjolk** [comment]
> Updated to ROCm 6.0. Pytorch image working!
> 
> Still getting this with rocm/jax:latest
> 
> ```
> drun rocm/jax
> root@minerva:/root# python3
> Python 3.10.0 (default, Dec 12 2023, 19:54:24) [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import jax
> 2023-12-16 22:23:14.261510: E external/xla/xla/stream_executor/plugin_registry.cc:90] Invalid plugin kind specified: DNN
> ```

used rocm/dev-ubuntu-22.04:latest, rocm 6.0.0, compiled jax from source branch v0.4.23 (with rocm/xla repo same branch) no dice, same error, running gpu tests via bazel crashed the system..

**Comment by PhilipVinc** [comment]
In another HPC (France's Adastra, MI250) I managed to get jax running under Singularity.

I get the same error ås you 

```python
2024-01-09 00:35:03.802451: E external/xla/xla/stream_executor/plugin_registry.cc:90] Invalid plugin kind specified: DNN
```
but rocm does work
```python
>>> jax.devices()
[rocm(id=0), rocm(id=1), rocm(id=2), rocm(id=3), rocm(id=4), rocm(id=5), rocm(id=6), rocm(id=7)]
>>> vs.samples.sharding
SingleDeviceSharding(device=rocm(id=0))
>>>
```

**Comment by mjolk** [comment]
default="gfx900,gfx906,gfx908,gfx90a,gfx1030"
i'm thinking new gpus aren't supported yet and fall back to cpu?
so yes it will work but i don't think it's using your mi250?
the error means it couldn't load the dnn plugin meaning gpu, this is all speculation fyi

**Comment by PhilipVinc** [comment]
I think it is running calculations on GPU (also judging on rutime of the code, it matches that of similar Nvidia GPUs, and surely ain't cpu).

**Comment by mjolk** [comment]
> I think it is running calculations on GPU (also judging on rutime of the code, it matches that of similar Nvidia GPUs, and surely ain't cpu).

oh ok, well i just have a consumer rx 7900 xtx that has rdna3 which is not supported i think. gfx90a is mi250x so maybe it's a spurious error? no idea

**Comment by brettkoonce** [comment]
I am specifically asking about CDNA3, which requires upstream support!

**Comment by allegro0132** [comment]
In a MI100(gfx908)system, Ubuntu 22.04, ROCm 6.0.4
Compiled jax v0.4.24 from rocm/jax with rocm/xla, I got the same error
```shell
2024-03-14 02:07:55.868414: E external/xla/xla/stream_executor/plugin_registry.cc:91] Invalid plugin kind specified: DNN
```
However, rocm does work(with significantly low performance)
```python
>>> jax.devices()
[rocm(id=0)]
```

**Comment by brettkoonce** [comment]
@allegro0132 Your machine might be pulling in some bits from https://github.com/vllm-project/vllm/pull/2792

FWIW, I think you are not utilizing your time wisely if you are using CDNA1/2 devices instead of a CUDA setup!

**Comment by brettkoonce** [comment]
See also https://github.com/google/jax/issues/19453#issuecomment-1927543572!

**Comment by allegro0132** [comment]
Thanks... It's rather surprising that ROCm doesn't even support a computation card.

**Comment by Ruturaj4** [comment]
> In another HPC (France's Adastra, MI250) I managed to get jax running under Singularity.
> 
> I get the same error ås you
> 
> ```python
> 2024-01-09 00:35:03.802451: E external/xla/xla/stream_executor/plugin_registry.cc:90] Invalid plugin kind specified: DNN
> ```
> 
> but rocm does work
> 
> ```python
> >>> jax.devices()
> [rocm(id=0), rocm(id=1), rocm(id=2), rocm(id=3), rocm(id=4), rocm(id=5), rocm(id=6), rocm(id=7)]
> >>> vs.samples.sharding
> SingleDeviceSharding(device=rocm(id=0))
> >>>
> ```
> 
> So now I wonder what this error does mean...

https://github.com/openxla/xla/pull/10954 fixes that warning/ error. Although, it had no functional implications, it was annoying nonetheless.

**Comment by brettkoonce** [comment]
@rahulbatra85 With ROCm 6.1, I am able to train basic convolutional networks on my 7900 xtx!  I will run some more advanced networks and report back any issues that I find!
