### ISSUE TITLE
Closing old issues

### ISSUE THREAD

**Issue by joaogui1** [google/jax#1874]
JAX has 265 open issues as of now, but many of them are old and already solved, so it would be better to close them.
#432 : tested on my computer, didn't show any problem nowadays JAX uses a more updated version of scipy);
#620 : From the discussion this merge https://github.com/numpy/numpy/pull/9686 seems to fix the issue
#623 : Seems resolved, maybe add an issue asking for documentation?
#679 : The person that opened the issue hasn't answered in 7 months and another person added a workaround, maybe add the workaround to a notebook/sharp edges document and close the issue?
#803 : The problem is addressed on the "Sharp Edges" notebook and the person that opened the issue hasn't responded in 6 months
#928 : Tested it on colab with no problem and then increased N 10x and still no error (maybe a faster cpu still crashes? or it was solved)
#939 : Also seems ok in my test, probably someone fixed jaxlib at some point
#973 : Seems pretty much resolved
#1033 : Seems solved
#1067 : Likely solved by #1224 
So, this covers issues from page 6-11, there are some that I couldn't determine the status, for example people stopped discussing the issue without a clear solution, and some that didn't receive any answers but that may have been resolved, as the team is small and has many things to implement I decided not to list those here and possible waste their time.
Pinging @gnecula, @shoyer, @skye , @jekbradbury, @hawkinsp

**Comment by hawkinsp** [comment]
#432 is definitely still open.

**Comment by joaogui1** [comment]
> #432 is definitely still open.

Oh, it's one of those bugs related to LAPACK on Mac? Sorry

**Comment by skye** [comment]
Thank you for doing this Joao!

**Comment by mattjj** [comment]
Wow, this is super helpful @joaogui1 . Thank you!

**Comment by mattjj** [comment]
I closed 1033 and 1067 just now.

**Comment by joaogui1** [comment]
Closing this for now (as the whole point is having less open issues), will try to come back later to comb over pages 2-5
