### ISSUE TITLE
`lax.dynamic_slice` fails even with static argnum

### ISSUE THREAD

**Issue by zmjjmz** [google/jax#1879]
It's not clear to me that this is a bug with JAX versus me just not quite using it properly, but essentially I'm trying (with some success so far) to create a minibatch-SGD training setup for the recsys version of SVD (i.e. [this](https://sifter.org/~simon/journal/20061211.html) oft-cited blog post) in JAX. Currently I'm trying to get comparable performance to [`surprise`](https://github.com/NicolasHug/Surprise/blob/master/surprise/prediction_algorithms/matrix_factorization.pyx).

Anyways, one of the main things that's been challenging for this is, surprisingly, the minibatch flexibility part. I've gotten to a fairly fast setup (0.2ms per epoch at batch size 1 for 500 examples) by creating a jitted `train_outer` function that iterates through the given dataset. A bigger slice of the code (not all of it) is in [this gist](https://gist.github.com/zmjjmz/21965e3de7c3e9966bf6aaa6732c96c3) but the essential part that I'm trying to figure out is how to do a batched run through the input data.

My first approach looks like this, using `lax.dynamic_slice`

```
from jax.lax import lax
<...>
@partial(jit,static_argnums=(7,8)) # recompile on batch_size change                        
def train_outer(vem, tem, vbv, tbv,                                                        
                voter_indices, target_indices, ratings,                                    
                batch_size, batched_dataset_size):                                         
    with loops.Scope() as s:                                                               
        s.vem = vem                                                                        
        s.tem = tem                                                                        
        s.vbv = vbv                                                                        
        s.tbv = tbv                                                                        
        for i in s.range(0, batched_dataset_size):                                         
            batch_start = i * batch_size                                                   
            batch_end = (i + 1) * batch_size                                               
            voter_ib = lax.dynamic_slice(voter_indices, (batch_start,), (batch_end,))      
            target_ib = lax.dynamic_slice(target_indices, (batch_start,), (batch_end,))    
            ratings_b = lax.dynamic_slice(ratings, (batch_start,), (batch_end,))           
                                                                                           
            s.vem, s.tem, s.vbv, s.tbv = train_inner(                                      
                s.vem, s.tem, s.vbv, s.tbv,                                                
                voter_indices=voter_ib,                                                    
                target_indices=target_ib,                                                  
                ratings=ratings_b)                                                         
        return s.vem, s.tem, s.vbv, s.tbv                                                  
```

However, when I try to do this I get the following error (full stacktrace in the gist):

```
<...>
File "jax_models.py", line 140, in train_outer
  voter_ib = lax.dynamic_slice(voter_indices, (batch_start,), (batch_end,))
File "/home/u1/zach/proj/dataplayground3/lib/python3.5/site-packages/jax/lax/lax.py", line 690, in dynamic_slice
  operand_shape=operand.shape)
<...>
TypeError: Abstract value passed to `bool`, which requires a concrete value. The function to be transformed can't be traced at the required lev
el of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```

I'm _fairly_ certain that the stuff `dynamic_slice` depends on is in `static_argnums`, however I might be wrong. I also tried to have the dataset arguments (`voter_indices, target_indices, ratings`) as static args, and got the same error (even though it would recompile every time it got a shuffled version of those).

Is there something specific I'm missing?

I should note that the rest of my code _does_ work, with a different batching method that occurs outside of `train_outer` where `voter_indices` and etc. have been reshaped into ndarrays of shape `(batched_dataset_size x batch_size)`, and the extraction is simply `voter_ib = voter_indices[i]`within `train_outer`. However the batching done outside of the loop is quite a bit slower.

I have some ways forward, but I wanted to put this issue up while I pursue them in case there is a proper way to use `dynamic_slice` that I'm just missing. Thanks for whatever help you can offer!

**Comment by hawkinsp** [comment]
I can't verify this because the example isn't self-contained and runnable, but is it possible you are passing the `batch_end` value where `dynamic_size` expects a size?
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.dynamic_slice.html#jax.lax.dynamic_slice

Shouldn't the `(batch_end,)` be `(batch_size,)`?

**Comment by jekbradbury** [comment]
You may want to reshape your data into something with shape `(n_batches, batch_size, ...)` and `lax.scan` over the first axis? (This will end up with similar XLA code as your loop over `dynamic_slice`)

**Comment by zmjjmz** [comment]
@hawkinsp that's a good catch, I didn't realize `dynamic_slice` operated that way -- I doubt it will change this error but I'll go ahead and fix it. I'll also clean up and put the full script up in a bit.

@jekbradbury I'm actually doing that now, and I've gotten it down to 1ms per epoch (for a batch size of 1) for 10k examples (but a small voter/target matrix). However when I profile it .8ms are spent doing the shuffling/reshaping. It's not clear to me which part of that is irreducibly due to the shuffling versus the reshaping. Additionally, reshaping requires me to pad out the end of the dataset if the batch size doesn't evenly divide it, which is a bit more work but not a huge issue.

**Comment by zmjjmz** [comment]
Update: I set `dynamic_slice` to take in `batch_size` instead of `batch_end`, and while I'm not really clear on why that would work -- it did! So I'm closing this issue.
