### ISSUE TITLE
Is there any upsample in JAX?

### ISSUE THREAD

**Issue by kayhan-batmanghelich** [google/jax#1889]
Hi Everyone,

This might be a naive question: Is there any upsampling in JAX? Similar to the Upsample in Torch:

```
import torch.nn as nn

nn.Upsample(scale_factor=2, mode='bilinear', align_corners=True)
```

Thanks

**Comment by mattjj** [comment]
Hey Kayhan!

Take a look at #862, which I think tracks this very issue. There's a code snippet there which might do what you need, though I suspect at some point someone will close #862 by contributing a faster conv-based solution.

If #862 tracks the same issue (and the code snippet there might unblock you), should we close this issue?

**Comment by kayhan-batmanghelich** [comment]
Hey @mattjj , Thank you for your reply! 

#862  covers this issue for the most part, so I am going to follow that up as well. Meanwhile, it might be helpful if I explain what I was trying to do:

To learn JAX, I wanted to implement Unet from here:

https://github.com/usuyama/pytorch-unet/blob/master/pytorch_unet.py
 
and this is where I stuck:
https://github.com/usuyama/pytorch-unet/blob/063cf7bb99e1f1f2ec80eabbb4ce33709e1a5306/pytorch_unet.py#L24

Another way of doing that is to transpose convolution as you can also find it here:
https://github.com/milesial/Pytorch-UNet/blob/4dcb7b8440c5f36ff2565c67f56f8f029b589c80/unet/unet_parts.py#L50

There is very little documentation for JAX `ConvTranspose`. The following was my try to covert that line from Torch to JAX but apparently it is wrong:

```
# Torch
nn.ConvTranspose2d(in_channels // 2, in_channels // 2, kernel_size=2, stride=2)
```

```
#JAX -- my understanding
ConvTranspose(filters, (2,2), stride=(2,2))
```
