### ISSUE TITLE
cannot import name 'shape_poly' from 'jax.experimental.jax2tf'

### ISSUE THREAD

**Issue by RizwanMunawar** [google/jax#18978]
### Description

Greetings Google Jax Team!

Within [Ultralytics](https://github.com/ultralytics/ultralytics), we have been successfully utilizing Jax in our projects, and it seamlessly integrated with the previous version. However, the recent update is presenting an issue: **cannot import name 'shape_poly' from 'jax.experimental.jax2tf'**.

This error is currently hindering our ability to incorporate the latest version of `jax` into our project. We are hoping that this issue will be resolved soon!

Thank you,
Ultralytics Team!

### What jax/jaxlib version are you using?

jax 0.4.23

### Which accelerator(s) are you using?

CPU

### Additional system info?

Python 3.10

**Comment by hawkinsp** [comment]
`shape_poly` is now at `jax.experimental.export.shape_poly` because it can be used independently of `jax2tf`. Note these are unstable API ("experimental"); you should expect a certain amount of churn.

Are you referring  to it directly in your code, or is there a reference to the old location in JAX itself?

**Comment by gnecula** [comment]
As Peter said, adding also a question about what APIs are you using directly from shape_poly? It was meant to be exposed directly from `jax2tf` and not from `jax.experimental.export`. In fact, I am further tightening the public APIs for `shape_poly`.

**Comment by glenn-jocher** [comment]
@gnecula @hawkinsp thanks for the response. Ultralytics does not use jax directly, `tensorflowjs` uses it and the bug is caused there. I assume it's popped up in `ultralytics` first since we CI test tensorflowjs export of YOLOv8 models every 24 hours. The failing CI is https://github.com/ultralytics/ultralytics/actions/runs/7209394673/job/19640667044?pr=6971

<img width="2365" alt="Screenshot 2023-12-14 at 17 50 36" src="https://github.com/google/jax/assets/26833433/dde8259c-d571-4f23-9ad1-dce52ad97bbb">

**Comment by gnecula** [comment]
Understood. We have fixed already the uses in tensorflowjs internally a few days ago, but they have not released a new version.

**Comment by gnecula** [comment]
@pyu10055 Is there an upcoming tensorflowjs release?

**Comment by glenn-jocher** [comment]
@gnecula @hawkinsp this seems to be fixed now in `jax>=0.4.23` and `jaxlib>=0.4.23` in https://github.com/ultralytics/ultralytics/pull/7039

**Comment by pyu10055** [comment]
@gnecula we are having some issues with the CI, but we are expecting to have a new build in the new year.

**Comment by oohgan** [comment]
Is there any workaround for this issue?

**Comment by vaguely-tagged** [comment]
if you need a temporary fix before the new version, you can go into jax_conversion.py then delete the PolyShape declaration and change the poly_shape import to from jax.experimental.jax2tf import PolyShape

**Comment by tamaghna-saha** [comment]
Thanks 

> if you need a temporary fix before the new version, you can go into jax_conversion.py then delete the PolyShape declaration and change the poly_shape import to from jax.experimental.jax2tf import PolyShape

**Comment by gungui98** [comment]
> if you need a temporary fix before the new version, you can go into jax_conversion.py then delete the PolyShape declaration and change the poly_shape import to from jax.experimental.jax2tf import PolyShape

I have to use TF again after 3 years, and the API change nightmare seems to never change.

**Comment by ibnzahoor98** [comment]
Still unable to convert model to tfjs from model.h5 

```
2024-01-05 05:49:30.129206: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-01-05 05:49:30.129260: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-01-05 05:49:30.130556: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-01-05 05:49:31.573899: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/usr/local/bin/tensorflowjs_converter", line 5, in <module>
    from tensorflowjs.converters.converter import pip_main
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/__init__.py", line 21, in <module>
    from tensorflowjs import converters
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/__init__.py", line 26, in <module>
    from tensorflowjs.converters.jax_conversion import convert_jax
  File "/usr/local/lib/python3.10/dist-packages/tensorflowjs/converters/jax_conversion.py", line 20, in <module>
    from jax.experimental.jax2tf import shape_poly
ImportError: cannot import name 'shape_poly' from 'jax.experimental.jax2tf' (/usr/local/lib/python3.10/dist-packages/jax/experimental/jax2tf/__init__.py)
```

**Comment by davidhorner** [comment]
Running into the same issue tonight.
`ImportError: cannot import name 'shape_poly' from 'jax.experimental.jax2tf'`

**Comment by somtoval** [comment]
> if you need a temporary fix before the new version, you can go into jax_conversion.py then delete the PolyShape declaration and change the poly_shape import to from jax.experimental.jax2tf import PolyShape

I am using jax 0.4.25, and I was getting 

 from jax.experimental.export.shape_poly import PolyShape
ModuleNotFoundError: No module named 'jax.experimental.export.shape_poly'

So I went to the jax_conversion.py and changed "from jax.experimental.export import shape_poly" with "from jax.experimental.export import _shape_poly"

hope it helps someone ☺

**Comment by pventura-mam** [comment]
I had the same issue. I am using [tensorflowjs 4.22.0] and [jax 0.4.34] and I was getting: 

`ImportError: cannot import name 'shape_poly' from 'jax.experimental.jax2tf'`

I had to change in ".venv\Lib\site-packages\tensorflowjs\converters\jax_conversion.py":

Old: from jax.experimental.jax2tf import shape_poly
New: from jax._src.export import shape_poly

Hope it helps.
