### ISSUE TITLE
jaxlib 0.4.22 has very spammy GPU compiler logs

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#18970]
We messed up this release and the GPU compiler is very spammy, with lots of LOG output from C++.

Workaround: set `TF_CPP_MIN_LOG_LEVEL=2`, and we're trying to cut another release.

**Comment by WangHanSolo** [comment]
FWIW, upgrading `jax` isn't enough with `pip install jax --upgrade`. You will also need to upgrade `jaxlib` with `pip install jaxlib --upgrade`

**Comment by hawkinsp** [comment]
Yes, that's right! You need to update both `jax` and `jaxlib`. Sorry for the disruption.
