### ISSUE TITLE
global_array_to_host_local_array documentation needs improvement

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#18986]
Two things:
https://jax.readthedocs.io/en/latest/_autosummary/jax.experimental.multihost_utils.global_array_to_host_local_array.html

a) the example doesn't render correctly, and
b) the documentation doesn't say what the `global_mesh` and `partition_specs` actually mean.

**Comment by rajasekharporeddy** [comment]
Hi @hawkinsp 

The issue will move to closed status once the PR #20728 is merged. Thanks!
