### ISSUE TITLE
Make jax versions 0.2.* available on Google Storage

### ISSUE THREAD

**Issue by lucaslingle** [google/jax#18993]
@hawkinsp @jakevdp 

I am looking at the Google Storage bucket linked above and I don't see anything hosted for Jax ```0.2.*```. 

The [LRA codebase](https://github.com/google-research/long-range-arena/) raises an error indicating a breaking change when I used Jax ```0.3.*```, and the LRA repo [provides](https://github.com/google-research/long-range-arena/blob/main/requirements.txt) a loosely-specified dependency of ```jax>=0.2.4```, so including Jax ```0.2.*``` on the aforementioned Google Storage bucket would be very helpful. 

Can you make these versions available as well? Thank you!

_Originally posted by @lucaslingle in https://github.com/google/jax/issues/18368#issuecomment-1857432763_

**Comment by jakevdp** [comment]
Hi - all previous jaxlib versions are available at https://storage.googleapis.com/jax-releases/jax_releases.html; you can find information on installing them at https://jax.readthedocs.io/en/latest/installation.html#installing-older-jaxlib-wheels

Note that `jaxlib` 0.2.X does not exist: prior to 0.3.0, the jax and jaxlib versioning scheme did not match, and the last jaxlib version released before 0.3.0 was was (I believe) 0.1.76. Finding matching versions from that era of jax/jaxlib is a bit difficult, but from the release dates it looks like jax v0.2.4 is compaible with jaxlib v0.1.55 or so.

So it sounds like you want something like this:
```
pip install jax==0.2.4 jaxlib==0.1.55 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
Note however that this jaxlib wheel is only available on linux, and only for Python 3.6, 3.7, and 3.8 (which were the supported Python versions 3+ years ago when this version was released).

Best of luck!

**Comment by hawkinsp** [comment]
Closing, but feel free to comment if Jake's answer didn't solve the problem!

**Comment by lucaslingle** [comment]
The issue is resolved, thanks! 

I had been under the impression the versions were synchronized the whole time. This, combined with the numbering jump of Jaxlib versions in the GCS bucket and a Jax-specific pip error message, led me to believe Jax 0.2.* wasn't on PyPI or GCS. In fact, while not on GCS, Jax 0.2.* is available on PyPI still.
