### ISSUE TITLE
CUDA error when importing torch before creating any jax.numpy.array

### ISSUE THREAD

**Issue by OmerRochman** [google/jax#19004]
### Description

If pytorch is imported before creating a jax.numpy.array then jax can't use cuda.
```
if __name__ == '__main__':
    import jax.numpy as jnp
    import torch
    a = jnp.array([1, 2, 3])
    print(a.devices()) # CPU
    print(torch.backends.cudnn.version()) # 8500 

```
will fail with `CUDA backend failed to initialize: Found cuDNN version 8500, but JAX was built against version 8600, which is newer. The copy of cuDNN that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)`

while 
```
if __name__ == '__main__':
    import jax.numpy as jnp
    a = jnp.array([1, 2, 3])
    print(a.devices()) # GPU
    import torch
    print(torch.backends.cudnn.version()) # 8906 
```
will work with only a mildly annoying warning `The NVIDIA driver's CUDA version is 11.7 which is older than the ptxas CUDA version (11.8.89). Because the driver is older than the ptxas version, XLA is disabling parallel compilation, which may slow down compilation. You should update your NVIDIA driver or use the NVIDIA-provided CUDA forward compatibility packages.`

I don't know how reproducible this is outside of my own setting as I'm working on a server of which I don't have privileges to update. We are running `NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7  ` (output of `nvidia-smi`).

Jax was installed using `pip install --upgrade "jax[cuda11_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`, which gives a warning `WARNING: jax 0.4.23 does not provide the extra 'cuda11-pip'` but otherwise runs fine. Pytorch was installed using `pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`

`LD_LIBRARY_PATH` is empty.

If it's of any help the output of `pip list` is below (all the nvidia* packages where installed by the pip install jax command) 

Let me know if I can give any more info!

```
Package                  Version
------------------------ ---------------------
absl-py                  2.0.0
appdirs                  1.4.4
asttokens                2.4.1
attrs                    23.1.0
certifi                  2022.12.7
charset-normalizer       2.1.1
chex                     0.1.85
click                    8.1.7
cmake                    3.25.0
comm                     0.2.0
contextlib2              21.6.0
contourpy                1.2.0
cycler                   0.12.1
dataclasses              0.6
debugpy                  1.8.0
decorator                4.4.2
dm-haiku                 0.0.11
docker-pycreds           0.4.0
e3nn-jax                 0.20.3
einops                   0.7.0
etils                    1.6.0
exceptiongroup           1.2.0
executing                2.0.1
filelock                 3.9.0
flax                     0.7.5
fonttools                4.46.0
fsspec                   2023.12.1
gitdb                    4.0.11
GitPython                3.1.40
h5py                     3.10.0
idna                     3.4
imageio                  2.33.1
imageio-ffmpeg           0.4.9
importlib-resources      6.1.1
ipykernel                6.27.1
ipython                  8.18.1
jax                      0.4.23
jax-md                   0.2.8
jaxlib                   0.4.23+cuda11.cudnn86
jaxopt                   0.8.2
jedi                     0.19.1
Jinja2                   3.1.2
jmp                      0.0.4
jraph                    0.0.6.dev0
jupyter_client           8.6.0
jupyter_core             5.5.0
kiwisolver               1.4.5
lit                      15.0.7
markdown-it-py           3.0.0
MarkupSafe               2.1.3
matplotlib               3.8.2
matplotlib-inline        0.1.6
mdurl                    0.1.2
ml-collections           0.1.1
ml-dtypes                0.3.1
moviepy                  1.0.3
mpmath                   1.3.0
msgpack                  1.0.7
nest-asyncio             1.5.8
networkx                 3.0
numpy                    1.26.2
nvidia-cublas-cu11       11.11.3.6
nvidia-cuda-cupti-cu11   11.8.87
nvidia-cuda-nvcc-cu11    11.8.89
nvidia-cuda-nvrtc-cu11   11.8.89
nvidia-cuda-runtime-cu11 11.8.89
nvidia-cudnn-cu11        8.9.6.50
nvidia-cufft-cu11        10.9.0.58
nvidia-cusolver-cu11     11.4.1.48
nvidia-cusparse-cu11     11.7.5.86
nvidia-nccl-cu11         2.19.3
opt-einsum               3.3.0
optax                    0.1.7
orbax-checkpoint         0.4.7
packaging                23.2
pandas                   2.1.4
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.3.0
pip                      23.3.1
platformdirs             4.1.0
plotly                   5.18.0
proglog                  0.1.10
prompt-toolkit           3.0.41
protobuf                 4.25.1
psutil                   5.9.6
ptyprocess               0.7.0
pure-eval                0.2.2
Pygments                 2.17.2
pyparsing                3.1.1
python-dateutil          2.8.2
pytz                     2023.3.post1
PyYAML                   6.0.1
pyzmq                    25.1.2
requests                 2.28.1
rich                     13.7.0
scipy                    1.11.4
seaborn                  0.13.0
sentry-sdk               1.39.1
setproctitle             1.3.3
setuptools               68.2.2
six                      1.16.0
smmap                    5.0.1
stack-data               0.6.2
sympy                    1.12
tabulate                 0.9.0
tenacity                 8.2.3
tensorstore              0.1.51
toolz                    0.12.0
torch                    2.0.1+cu117
torchaudio               2.0.2+cu117
torchvision              0.15.2+cu117
tornado                  6.4
tqdm                     4.66.1
traitlets                5.14.0
triton                   2.0.0
typing_extensions        4.9.0
tzdata                   2023.3
urllib3                  1.26.13
wandb                    0.16.1
wcwidth                  0.2.12
wheel                    0.42.0
zipp                     3.17.0
```

### What jax/jaxlib version are you using?

jax==0.4.23, jaxlib==0.4.23

### Which accelerator(s) are you using?

NVIDIA GPU

### Additional system info?

Server running linux:
>>> import platform, sys, numpy; print(numpy.__version__); print(sys.version); print(platform.uname())
1.26.2
3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
uname_result(system='Linux', node='compute-14', release='4.18.0-448.el8.x86_64', version='#1 SMP Wed Jan 18 15:02:46 UTC 2023', machine='x86_64')

### NVIDIA GPU info

+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.76       Driver Version: 515.76       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000    On   | 00000000:61:00.0 Off |                  Off |
| 30%   30C    P8    17W / 230W |      3MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

**Comment by hawkinsp** [comment]
There's nothing we can do about this. If you have two libraries that use cudnn, the first one to load it "wins". If you load torch first, you end up with the older cudnn version loaded by your torch version.

JAX loads cudnn when the backend is initialized, which happens during the first op usually. Calling `jax.devices()` would work also.

However, cudnn is usually backward compatible, so you can probably just work around by loading JAX first.

Hope that helps!

**Comment by OmerRochman** [comment]
Oh I see, thanks for the answer. Is there any way to ask jax which cuda/cudnn is it using and where is it located in the system? Something like `torch.backends.cudnn.version()`.

**Comment by selamw1** [comment]
Hi @OmerRochman, 

You can use alternative solution, look for CUDA and cuDNN versions in dependencies:

`pip show jaxlib ` 
OR
`pip show jaxlib | grep cudatoolkit`

You can find below code snippet to point out the CUDA installation directory:
```
import os
print(os.environ.get("CUDA_HOME"))  # Check CUDA_HOME
print(os.environ.get("LD_LIBRARY_PATH"))  # Check LD_LIBRARY_PATH (Linux/macOS)
print(os.environ.get("PATH"))  # Check PATH (Windows)
```
Hope this helps!

**Comment by OmerRochman** [comment]
Hey @selamw1, thanks for answering. I'm not sure those commands work (maybe because of how the cluster is set up or because of micromamba). The variable are empty but jax still works on the GPU so cuda must be in use.

![image](https://github.com/google/jax/assets/49922998/ff455cc3-192e-4073-b4ce-b71494936aee)
