### ISSUE TITLE
scipy.special.gammaln inaccurate compared to TensorFlow/Numpy.

### ISSUE THREAD

**Issue by SiegeLordEx** [google/jax#19010]
### Description

`scipy.special.gammaln` is on JAX is noticeably less accurate than TensorFlow's and Numpy's variant. See the below absolute relative error plot.

```python
import scipy.special
import matplotlib.pyplot as plt
import jax.scipy as jsp
import jax
import tensorflow as tf
import numpy as np

print(jax.devices())

x = np.linspace(2 + 1e-6, 10, 1000).astype(np.float32).astype(np.float64)
x_32 = x.astype(np.float32)

y_gt = scipy.special.gammaln(x)
y_tf = np.array(tf.math.lgamma(x_32), np.float64)
y_jax = np.array(jsp.special.gammaln(x_32), np.float64)
y_np = np.array(scipy.special.gammaln(x_32), np.float64)

plt.plot(x, np.abs(y_jax - y_gt) / y_gt, label='jax')
plt.plot(x, np.abs(y_tf - y_gt) / y_gt, label='tf')
plt.plot(x, np.abs(y_np - y_gt) / y_gt, label='np')
plt.yscale('log')
plt.title('log gamma rel abs error')
plt.legend()
```
![image](https://github.com/google/jax/assets/43966695/bae13d99-1c87-4e57-8477-bc8bb700b5ae)

### What jax/jaxlib version are you using?

0.4.20/0.4.20

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks for the report. I think the precision is as good as can be expected for float32 computations. Note that the scipy version always performs its computations at 64-bit precision; to get comparable results in JAX you can enable float64 computation, and pass a float64 array to `jsp.special.gammaln`.
