### ISSUE TITLE
jnp.min or jnp.max returns nan if input array dtype is fp8

### ISSUE THREAD

**Issue by hsinyuu** [google/jax#19011]
### Description

Below is a toy example to reproduce. Can be reproduced with CPU, TPU and GPU. Tested on colab.

```python
import jax
import jax.numpy as jnp
import jax.lax as lax

# Define a function to generate random arrays
def random_array(shape):
  return jax.random.uniform(jax.random.PRNGKey(0), shape, minval=-1, maxval=1
  
test = random_array((2,))
print(test, test.astype(jnp.float8_e4m3fn))
print(jnp.isnan(test))
print(jnp.min(test), jnp.max(test))
print(jnp.isnan(test.astype(jnp.float8_e4m3fn)))
print(jnp.min(test.astype(jnp.float8_e4m3fn)), jnp.max(test.astype(jnp.float8_e4m3fn)))

[0.21629536 0.8041241 ] [0.21875 0.8125]
[False False]
0.21629536 0.8041241
[False False]
nan nan
```

### What jax/jaxlib version are you using?

jax v0.4.22

### Which accelerator(s) are you using?

CPU/GPU/TPU

### Additional system info?

1.26.2 3.11.6 (stable, redacted, redacted) [Clang google3-trunk (af7a1453526a88a0e242baf156244aa4ae42ae4b)] uname_result(system='Linux', node='11a0354b588110fa-30029b6032f.borgtask.google.com', release='5.10.0-smp-1100.464.0.0', version='#1 [v5.10.0-1100.464.0.0] SMP @1700037056', machine='x86_64')

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:B3:00.0 Off |                    0 |
| N/A   40C    P0    72W / 300W |  12449MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     88841      C   .../mount/server/ml_notebook    12446MiB |
+-----------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Hi, thanks for the question! 8-bit floating point types are experimental and in general you should not expect them to be compatible with most operations in JAX (we focus on matrix multiplication and a few related operations that `float8*` were designed for).

I believe the particular behavior here is caused by the fact that `float8_e4m3fn` cannot represent infinities (the "`f`" in the type name stands for "finite only") and the `min` and `max` computation assume the presence of $\pm\inf$ as the identity for the reduction.

With that in mind, this working as expected for the time being. If you are doing general floating point operations, you should stick with non-experimental dtypes. For this particular application, you might try `float8_e5m2` which can represent infinite values.

**Comment by jakevdp** [comment]
So thinking more about this, we probably should make `min` and `max` do something sane in this case, and we need to do a better job of explicitly erroring for unsupported fp8 operations. I'm going to take a look

**Comment by hsinyuu** [comment]
> Hi, thanks for the question! 8-bit floating point types are experimental and in general you should not expect them to be compatible with most operations in JAX (we focus on matrix multiplication and a few related operations that `float8*` were designed for).
> 
> I believe the particular behavior here is caused by the fact that `float8_e4m3fn` cannot represent infinities (the "`f`" in the type name stands for "finite only") and the `min` and `max` computation assume the presence of ±∞ as the identity for the reduction.
> 
> With that in mind, this working as expected for the time being – we could certainly modify the `reduce_min`/`reduce_max` lowering code to account for this special case, but it's only one of many examples where `float8` inputs will not be correctly handled in JAX, and it's not clear at the moment that addressing those cases more comprehensively is a goal for the project.
> 
> If you are doing general floating point operations, you should stick with non-experimental dtypes. For this particular application, you might try `float8_e5m2` which is able to represent infinite values.

Thanks for explaining. That makes sense.
