### ISSUE TITLE
custom_partitioning doesn't work with plugins

### ISSUE THREAD

**Issue by yashk2810** [google/jax#19039]
This is a problem as `pip install jax[cuda12]` uses the plugin API for cuda.

Nvidia depends heavily on custom_partitioning. So before we make the plugin cuda the default way of installation, this needs to be fixed.

**Comment by jyingl3** [comment]
With https://github.com/openxla/xla/pull/8655, https://github.com/openxla/xla/commit/3c8260f614901f5cf2dd81530e009db8e6c9789b, and https://github.com/google/jax/pull/20378, custom_partitioning should work with the cuda plugin now.
