### ISSUE TITLE
Setting PRNGKey on Ubuntu 16 + CUDA9 results in dump error

### ISSUE THREAD

**Issue by ericmjl** [google/jax#191]
Pasting this output from an IPython session on my GPU box.

```python
$ ipython
Python 3.7.1 (default, Dec 14 2018, 19:28:38)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from jax.random import PRNGKey

In [2]: key = PRNGKey(0)
2019-01-03 11:19:54.239883: W external/org_tensorflow/tensorflow/compiler/xla/service/platform_util.cc:253] unable to create StreamExecutor for CUDA:0: failed
 initializing StreamExecutor for CUDA device ordinal 0: Internal: failed call to cuDevicePrimaryCtxRetain: CUDA_ERROR_UNKNOWN: unknown error
2019-01-03 11:19:54.239973: F external/org_tensorflow/tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Inter
nal: no supported devices found for platform CUDA
Aborted (core dumped)
```

I'm not quite sure what caused this error - `nal: no supported devices found for platform CUDA` does not seem valid, because the output from nvidia-smi shows that my GPU is visible.

**Comment by mattjj** [comment]
My best guess is this must be some kind of CUDA setup / build issue making everything fail (not just PRNG stuff), but that could be a lot of things...

A few starter questions:
1. can you share the full output of `nvidia-smi`? I'd like to know the driver version in particular.
2. which wheel did you install, or if you built from source, what was the full build command you used?
3. which version of CUDA9 do you have (9.0, 9.1, 9.2)? Do you have multiple CUDA installs on your system?
4. if you can find the `_pywrap_xla.so` file, can you run `ldd` on it and share the output? Depending on how you installed, you might want to check the site-packages directories (`python -m site`); on my setup it's in `~/miniconda2/lib/python2.7/site-packages/jaxlib/_pywrap_xla.so`.

**Comment by froystig** [comment]
See also #39 and [the related pull request to TF](https://github.com/tensorflow/tensorflow/pull/24345) for better error handling when this happens.

**Comment by ericmjl** [comment]
Thanks for the feedback, @mattjj! 

Here's my responses to your questions.

> 1. can you share the full output of `nvidia-smi`? I'd like to know the driver version in particular.

```
$ nvidia-smi
Thu Jan  3 13:39:03 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
| 27%   34C    P8    13W / 180W |   8093MiB /  8116MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       972      G   /usr/lib/xorg/Xorg                           157MiB |
|    0      2328      G   unity-control-center                           2MiB |
|    0      3555      C   ...icmjl/anaconda/envs/bayesian/bin/python   121MiB |
|    0     12862      C   ...e/ericmjl/anaconda/envs/mpnn/bin/python  6727MiB |
|    0     16665      C   ...icmjl/anaconda/envs/bayesian/bin/python   301MiB |
|    0     24354      G   compiz                                       242MiB |
|    0     29470      C   ...cmjl/anaconda/envs/fundl-dev/bin/python   529MiB |
+-----------------------------------------------------------------------------+
```

> 2. which wheel did you install, or if you built from source, what was the full build command you used?

I installed from source, enabling CUDA. Specifically:

```
python build/build.py --enable_cuda
pip install -e build  # install jaxlib (includes XLA)
pip install -e .      # install jax (pure Python)
```

> 3. which version of CUDA9 do you have (9.0, 9.1, 9.2)? Do you have multiple CUDA installs on your system?

I only have one CUDA install on my system, version 9.2.


> 4. if you can find the `_pywrap_xla.so` file, can you run `ldd` on it and share the output? Depending on how you installed, you might want to check the site-packages directories (`python -m site`); on my setup it's in `~/miniconda2/lib/python2.7/site-packages/jaxlib/_pywrap_xla.so`.

This is the output:

```
$ ldd _pywrap_xla.so
        linux-vdso.so.1 =>  (0x00007ffcd73d4000)
        libcudart.so.9.2 => /usr/local/cuda/lib64/libcudart.so.9.2 (0x00007f46bce65000)
        libcuda.so.1 => /usr/lib/x86_64-linux-gnu/libcuda.so.1 (0x00007f46bbeea000)
        libcudnn.so.7 => /usr/local/cuda/lib64/libcudnn.so.7 (0x00007f46a9a6c000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f46a9864000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f46a9647000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f46a9443000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f46a913a000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f46a8db8000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f46a8ba2000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f46a87d8000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f46c1ac3000)
        libnvidia-fatbinaryloader.so.396.37 => /usr/lib/nvidia-396/libnvidia-fatbinaryloader.so.396.37 (0x00007f46a858c000)
```

Thanks for the help here, @mattjj!

**Comment by ajweiss** [comment]
Your GPU looks to be very nearly out of RAM, have you tried killing the other CUDA processes that are attached?

**Comment by ericmjl** [comment]
@ajweiss thanks for looping back. Those errors came even without the other CUDA processes attached, i.e. when the IPython session I was running (as a test) was the only thing that was using the GPU, apart from the display.

**Comment by mattjj** [comment]
@ericmjl is this still an issue? I'm optimistic that the updates to jaxlib may have resolved this.

**Comment by ericmjl** [comment]
@mattjj I just tested it on my home GPU tower - everything works great! I am going ahead to close this issue!

**Comment by franciscovargas** [comment]
Hi I am havving exactly the same issue. However its with the CPU build.

I have followed the installation instructions using pip and also the installation instructions building from source (cloned the latest version `git clone https://github.com/google/jax`):

```
python build/build.py 
pip install -e build  # install jaxlib (includes XLA)
pip install -e .      # install jax (pure Python)
```

Linux version:
``` 
$ lsb_release -a
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic
```

Script:
```python
fav25@dev-gpu-0:~$ python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> key = jax.random.PRNGKey(0)
/auto/homes/fav25/jax/jax/lib/xla_bridge.py:116: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
>>> jax.random.normal(key, shape=(3,))
```

Output
```
Illegal instruction (core dumped)
```

I could not find the file `_pywrap_xla.so` searched inside the build directory and in the jax folder since the package was installed from there it wont be in site-packages. 

```
 $ find . | grep "_pywrap_xla.so"
fav25@dev-gpu-0:~/jax$                                 
```

Most similar binary I found was:

```
 $ ldd xla_extension.so
        linux-vdso.so.1 (0x00007ffd981c2000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe050339000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe04ff9b000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe04fd97000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe04fb78000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe04f960000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe04f56f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fe053f3a000)
```

The outcomes are the same when installed using pip.

**Comment by hawkinsp** [comment]
@franciscovargas Can you open a new issue, please? I'm fairly confident this is not the same issue. For your new issue, I'd want to know what CPU model you have. Is this a cloud machine or similar on which we could reproduce the problem?

**Comment by franciscovargas** [comment]
Opened a new issue https://github.com/google/jax/issues/2906 thanks the prompt response. You are correct I mis-identified the issue it looked similar but I understand how it may be different. I included the output of lscpu, the machine is a local university sever so not cloud.
