### ISSUE TITLE
jax.lax.scan "tuple index out of range error" when using as described in docs

### ISSUE THREAD

**Issue by samskiter** [google/jax#19113]
### Description

I'm trying to migrate a for-loop to `scan` as per the docs. Here's the code I'm trying:

```python3
    def _calculate_node_errors(
        branching_nodes: tuple[Node, ...],
    ) -> jnp.NDArray[jnp.float_]:
        # THIS IS THE OLD CODE
        # values = jnp.empty(shape=(len(branching_nodes)))
        # for idx, node in enumerate(branching_nodes):
        #     error = node.get_normalised_error()
        #     values = values.at[idx].set(error)

        # THIS IS THE NEW CODE
        _, values = jax.lax.scan(         # <----- IndexError: tuple index out of range
            lambda _, branching_node: (
                None,
                branching_node.get_normalised_error(),
            ),
            None,
            branching_nodes,
        )
        return values
```

The docs I'm reading on jax.lax.scan says:

>When the type of xs (denoted a above) is an array type or None, and the type of ys (denoted b above) is an array type, the semantics of [scan()](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html#jax.lax.scan) are given roughly by this Python implementation:

```python3
def scan(f, init, xs, length=None):
  if xs is None:
    xs = [None] * length
  carry = init
  ys = []
  for x in xs:
    carry, y = f(carry, x)
    ys.append(y)
  return carry, np.stack(ys)
```

The error doesn't seem to make much sense - are my `xs` not an array type? (tuple)? In fact further down it says:

>**xs** (X) – the value of type [a] over which to scan along the leading axis, where [a] can be an array or any pytree (nested Python tuple/list/dict) thereof with consistent leading axis sizes.

What am I missing? Is this a bug or are the docs confusing me?

### What jax/jaxlib version are you using?

0.4.23 0.4.23

### Which accelerator(s) are you using?

GPU

### Additional system info?

1.26.2 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] uname_result(system='Linux', node='double-trouble', release='5.10.0-26-cloud-amd64', version='#1 SMP Debian 5.10.197-1 (2023-09-29)', machine='x86_64')

### NVIDIA GPU info

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA L4           On   | 00000000:00:03.0 Off |                    0 |
| N/A   40C    P8    16W /  72W |      0MiB / 23034MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA L4           On   | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8    16W /  72W |      0MiB / 23034MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Thanks for the report! I'm having trouble figuring out how to call your function in order to reproduce this error. Could you put together a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that I could paste into a code interpreter to see the same output you're seeing?

**Comment by jakevdp** [comment]
Closing as not reproducible – feel free to open another issue if you're still having this problem. Thanks!
