### ISSUE TITLE
cuBLAS and JAX version mismatch

### ISSUE THREAD

**Issue by GiftedNovaHD** [google/jax#19121]
### Description

I noticed that the update for JAX 0.4.23 introduced some version mismatch errors when I am running a training script: 
`CUDA backend failed to initialize: Found cuBLAS version 120103, but JAX was built against version 120205, which is newer. The copy of cuBLAS that is installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)`

I shall note that this issue was mentioned (#18027) not long ago by another fellow user, and I have attempted the following command to fix, but to no avail. 
`pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

The error unfortunately still persisted, and I suspect that this could be something to do with the CUDA backend. Please correct me if I am wrong. 
### What I have done
- Did a fresh install for CUDA and CUDA Toolkit to upgrade it to the latest version (12.3) 
`cuda-toolkit-12-3 is already the newest version (12.3.1-1).` My installation steps were based on the settings provided [here](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=22.04&target_type=deb_local). In addition, I have also updated my PATH and environment variables after the installation.
- Ran `nvcc --version`; here is my latest output after updating CUDA to the latest version. 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
```
- Attempted to pip install a stable jaxlib build: `pip install https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.23+cuda12.cudnn89-cp310-cp310-manylinux2014_x86_64.whl#sha256=8e42000672599e7ec0ea7f551acfcc95dcdd0e22b05a1d1f12f97b56a9fce4a8` , before installing JAX (again): `pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` via the default manner. 

### What jax/jaxlib version are you using?

jax 0.4.23, jaxlib 0.4.23

### Which accelerator(s) are you using?

RTX A6000

### Additional system info?

Ubuntu Linux 22.04

### NVIDIA GPU info

```
Mon Dec 25 18:41:09 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA RTX A6000               On  | 00000000:05:00.0 Off |                  Off |
| 30%   38C    P8              17W / 300W |      3MiB / 49140MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by GiftedNovaHD** [comment]
I've managed to fix my issue, simply pip installing a previous version of JAX. 

`pip install jax[cuda12_pip]==0.4.21 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

**Comment by Garbaz** [comment]
Just in case it helps anyone coming here from Google (as I did):

I got this version mismatch error in Google Colab when using _both_ Jax and Torch in one Notebook. For some to me unexplainable reason, the following reliably fixes the issue for me:

Instead of

```python
import jax
import torch

# ... your code here ...
```

insert any call to jax _between_ the `import jax` and `import torch`, for example:

```python
import jax
print(f"The jax default backend is: {jax.default_backend()}")
import torch

# ... your code here ...
```

I assume this has something to do with how Jax and Torch handle initialisation of the GPU backend, with Torch messing things up for Jax upon being imported. Perhaps.

**Comment by surak** [comment]
Please check #20133 . Installing it from pip works, provided you don't have another CUDA loaded. That downloads the correct CUDA and cuBLAS to site_packages.
