### ISSUE TITLE
Unexpected behavior of `jax.scipy.stats.binom.pmf`

### ISSUE THREAD

**Issue by Qazalbash** [google/jax#19150]
### Description

pmf of a random variable should be zero outside of its range. While plotting the graph for `jax.scipy.stats.binom.pmf`, I notice that for $n>5$ and $p>0.5$, there are some oscillations in the values of the pmf, which should not be there. For evidence, I am attaching a plot too.

```python
import jax
from jax import numpy as jnp
from matplotlib import pyplot as plt

x = jnp.linspace(-1, 10, 1000)
xxf = jax.scipy.stats.binom.pmf(k=x, n=5, p=0.8)

plt.plot(x, xxf)
plt.tight_layout()
plt.show()
```
![xyxy](https://github.com/google/jax/assets/62182585/c35a2ebb-e914-4b37-9f59-6ccd7cc10b28)
The side left to the zero is as expected.

### What jax/jaxlib version are you using?

jax v0.4.23

### Which accelerator(s) are you using?

CPU

**Comment by jakevdp** [comment]
Thanks for the report! Should be fixed by #19166
