### ISSUE TITLE
sum and cumsum have very different FLOPs counts

### ISSUE THREAD

**Issue by LeoXinhaoLee** [google/jax#19296]
### Description

Hi, I noticed that ```jnp.sum()``` and ```jnp.cumsum()``` have very different FLOPs when counted by the profile tool from jax, although theoretically they should have the same FLOPs. Could you help me understand why this happens? Thank you very much!

Below is my code:
```
import jax
import jax.numpy as jnp

def compute_sum(x):
    s = x.sum(axis=0)
    return s

def compute_cumsum(x):
    s = jnp.cumsum(x, axis=0)
    return s

rng = jax.random.PRNGKey(0)
X = jax.random.uniform(rng, (10,), dtype=jnp.float32)

Y_1 = compute_sum(X)
Y_2 = compute_cumsum(X)

wrapped = jax.xla_computation(compute_sum)
computation = wrapped(X)
module = computation.as_hlo_module()
client = jax.lib.xla_bridge.get_backend()
analysis = jax.lib.xla_client._xla.hlo_module_cost_analysis(client, module)
flops_sum = analysis['flops']

wrapped = jax.xla_computation(compute_cumsum)
computation = wrapped(X)
module = computation.as_hlo_module()
client = jax.lib.xla_bridge.get_backend()
analysis = jax.lib.xla_client._xla.hlo_module_cost_analysis(client, module)
flops_cumsum = analysis['flops']

print(f'FLOPs of Computing: '
      f'sum: {flops_sum} | '
      f'cumsum {flops_cumsum}')
```

Theoretically, their FLOPs should both be 9 additions, but the actual output is:

<img width="439" alt="image" src="https://github.com/google/jax/assets/62500792/3fb78243-f9c3-4ef4-9ad7-cb9a436f5088">

Besides, I am wondering if this profiling tool (from  #10542) is accurate?

Thanks! cc @jakevdp 

### What jax/jaxlib version are you using?

jax==0.4.13  jaxlib==0.4.13+cuda12.cudnn89

### Which accelerator(s) are you using?

GPU

### Additional system info?

Python 3.9.18; Ubuntu 20.04.

### NVIDIA GPU info

<img width="908" alt="image" src="https://github.com/google/jax/assets/62500792/57cc5027-de72-4283-8a7a-01ff0cec5585">

**Comment by jakevdp** [comment]
I believe the reason this is the case is because the compiler optimizes the implementation of `cumsum` for your available hardware.

If you were computing in a single-threaded serial environment, the optimal way to compute `cumsum` would likely be to walk through the array, adding each element to the element before it and storing the result, leading to nine floating point operations.

But you're not in a single-threaded serial environment: you're running on a GPU, which can do many floating point operations in parallel. Because of this, the compiler will split your `cumsum` operation into a number of sub-computations that can be run in parallel: the result uses more flops than the simple serial approach, but those flops are (hopefully) distributed in a way that optimizes use of your hardware.

You can get a sense for what exactly the compiler is doing by printing the optimized HLO, e.g.:
```python
print(jax.jit(compute_cumsum).lower(x).compile().as_text()
```

**Comment by LeoXinhaoLee** [comment]
Thank you very much for your kind reply. I am also wondering if the profile tool for FLOPs that I used is accurate. To test it, I have a very simple example:

```
import jax
import jax.numpy as jnp
from jax import make_jaxpr

@jax.jit
def compute(x):
    s = 0.
    for i in range(x.shape[0]):
        s += x[i] * 2
    return s

rng = jax.random.PRNGKey(0)
X = jax.random.uniform(rng, (3,), dtype=jnp.float32)

### Show jaxpr ###
print(make_jaxpr(compute)(X))
print('==================')

### Show compile ###
print(compute.lower(X).compile().as_text())
print('==================')

### Tool 1 ###
wrapped = jax.xla_computation(compute)
computation = wrapped(X)
module = computation.as_hlo_module()
client = jax.lib.xla_bridge.get_backend()
analysis = jax.lib.xla_client._xla.hlo_module_cost_analysis(client, module)
flops_1 = analysis['flops']
print(f'Tool 1 FLOPs count: {flops_1}')

### Tool 2 ###
flops_2 = compute.lower(X).compile().cost_analysis()[0]['flops']
print(f'Tool 2 FLOPs count: {flops_2}')
```

The FLOPs counts output by 2 tools are:
<img width="250" alt="image" src="https://github.com/google/jax/assets/62500792/131ce7fd-1fcc-4aff-b28f-3176718b9da4">

I have printed out jaxpr and ```.lower(x).compile().as_text()```, but unfortunately I am not familiar with compiler so I could not understand them. **Could you please help me understand which tool is correct and what's really going on in this program regarding FLOPs?** Thank you so much!

### jaxpr
```
{ lambda ; a:f32[3]. let                                                                         b:f32[] = pjit[
      jaxpr={ lambda ; c:f32[3]. let                                                                   d:f32[1] = dynamic_slice[slice_sizes=(1,)] c 0                                               e:f32[] = squeeze[dimensions=(0,)] d
          f:f32[] = mul e 2.0
          g:f32[] = add 0.0 f
          h:f32[1] = dynamic_slice[slice_sizes=(1,)] c 1
          i:f32[] = squeeze[dimensions=(0,)] h
          j:f32[] = mul i 2.0                                                                          k:f32[] = add g j                                                                            l:f32[1] = dynamic_slice[slice_sizes=(1,)] c 2                                               m:f32[] = squeeze[dimensions=(0,)] l
          n:f32[] = mul m 2.0
          o:f32[] = add k n
        in (o,) }
      name=compute
    ] a
  in (b,) }
```

### .lower(x).compile().as_text()
```
%fused_computation (param_0.3: f32[3]) -> f32[] {
  %param_0.3 = f32[3]{0} parameter(0)
  %slice.7 = f32[1]{0} slice(f32[3]{0} %param_0.3), slice={[0:1]}, metadata={op_name="jit(compute)/jit(main)/dynamic_slice[slice_sizes=(1,)]" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
  %slice.5 = f32[1]{0} slice(f32[3]{0} %param_0.3), slice={[1:2]}, metadata={op_name="jit(compute)/jit(main)/dynamic_slice[slice_sizes=(1,)]" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
  %add.7 = f32[1]{0} add(f32[1]{0} %slice.7, f32[1]{0} %slice.5), metadata={op_name="jit(compute)/jit(main)/mul" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
  %slice.4 = f32[1]{0} slice(f32[3]{0} %param_0.3), slice={[2:3]}, metadata={op_name="jit(compute)/jit(main)/dynamic_slice[slice_sizes=(1,)]" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
  %add.6 = f32[1]{0} add(f32[1]{0} %add.7, f32[1]{0} %slice.4), metadata={op_name="jit(compute)/jit(main)/add" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
  %constant_3 = f32[1]{0} constant({2})
  %multiply.4 = f32[1]{0} multiply(f32[1]{0} %add.6, f32[1]{0} %constant_3), metadata={op_name="jit(compute)/jit(main)/add" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
  ROOT %bitcast.18 = f32[] bitcast(f32[1]{0} %multiply.4), metadata={op_name="jit(compute)/jit(main)/add" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
}

ENTRY %main.14 (Arg_0.1: f32[3]) -> f32[] {
  %Arg_0.1 = f32[3]{0} parameter(0), sharding={replicated}
  ROOT %fusion = f32[] fusion(f32[3]{0} %Arg_0.1), kind=kLoop, calls=%fused_computation, frontend_attributes={fingerprint_before_lhs="7507634f8e49ccaefc9bcba2ef63ae90"}, metadata={op_name="jit(compute)/jit(main)/add" source_file="/juice5/scr5/yusun/data/xinhao/MTTT-LLM/profile_model/test_tool.py" source_line=10}
}
```

**Comment by LeoXinhaoLee** [comment]
It seems like in `jaxpr` there are `3 mul and 2 add`, which is 5 FLOPs in total. But in `.lower(x).compile().as_text()`, there are `2 add and 1 multiply`, which is 3 FLOPs in total.

However, I have no idea what these expressions correspond to, and what the real FLOPs are when my machine executes this function.

**Comment by jakevdp** [comment]
That looks reasonable. Note that the FLOPS counts output by those tools are only estimates, and you should not depend on their exact value.

It looks like the `Tool 1` approach does not run the code through the XLA compiler, while `Tool 2` does, and this probably explains why they differ. Also, you 

Also please note that the APIs you are accessing in `Tool 1` are non-public, and may change at any time. The public way to access pre-compilation flop estimates would look like this:
```python
uncompiled_flops = compute.lower(X).cost_analysis()['flops']
print(f'Uncompiled FLOPs count: {uncompiled_flops}')
```

**Comment by LeoXinhaoLee** [comment]
Thank you so much for your explanation. Indeed, these tools are only giving estimates, which rely on how far they can go in the compilation process. 

BTW, I saw `Tool 2` from the example in the official jax doc (https://jax.readthedocs.io/en/latest/aot.html), which could be confusing as it differs from your ```compute.lower(X).cost_analysis()['flops']```. Hopefully, my confusion today could help the jax team improve the doc in the future.

Thank you very much for your time and help again!

**Comment by jakevdp** [comment]
To be clear, your approach in tool 2 is fine. I was suggesting an alternative for your use of private APIs in tool 1. The difference is whether or not you call `.compile()`.

**Comment by LeoXinhaoLee** [comment]
Got it. Thank you very much.
