### ISSUE TITLE
vmap conditional debug.print ignores conditioning

### ISSUE THREAD

**Issue by benjaminvatterj** [google/jax#19314]
### Description

I'm trying to debug a vmapped code and wanted to print a message when certain conditions are met, and notices some odd results. Here's a minimal reproducible example:

```

import jax

def f(x):
    key = jax.random.PRNGKey(123)
    u = jax.random.uniform(key)
    jax.lax.cond(u > x, lambda w,z: jax.debug.print("selecting u: {w}>{z}",w=w,z=z), lambda x,y: None, u, x)
    v = jax.lax.select(u > x, u, x)
    return v

vmapped = jax.vmap(f, in_axes=(0,))
key = jax.random.PRNGKey(1)
x_grid = jax.random.uniform(key, (4,))
vmapped(x_grid)

```

This prints out the debug print for all values of x_grid regardless if they meet the condition or not.

### What jax/jaxlib version are you using?

0.4.23 0.4.23

### Which accelerator(s) are you using?

GPU

### Additional system info?

1.26.2 3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0] uname_result(system='Linux', node='node2415', release='4.18.0-348.el8.0.2.x86_64', version='#1 SMP Sun Nov 14 00:51:12 UTC 2021', machine='x86_64')

### NVIDIA GPU info

NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0

**Comment by jakevdp** [comment]
Hi, thanks for the question! This is behaving as expected: a vmapped `cond` becomes a `select` (as noted in the [docstring](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cond.html)) and a `select` executes both branches.

**Comment by benjaminvatterj** [comment]
Thank you for the quick reply! I misunderstood what that part of the docstring meant! Sorry about the unnecessary issue report.
