### ISSUE TITLE
Array `any` and `all` methods missing `where` parameter in type signature

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#19356]
### Description

The JAX array methods for [any](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.any.html) and [all](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.all.html) are missing the `where` parameter in [their type signatures](https://github.com/google/jax/blob/f539187c053bf1819f05d0f8e9e66e45da2af17b/jax/_src/basearray.pyi#L113):

```python3
from jax import numpy as jnp

array = jnp.zeros(10, dtype=bool)
mask = jnp.arange(array.size) < 7

assert array.any(where=mask) == jnp.any(array, where=mask)
assert array.all(where=mask) == jnp.all(array, where=mask)
```

```shell
$ python3 test.py
$ pyright test.py
test.py
  test.py:6:18 - error: No parameter named "where" (reportGeneralTypeIssues)
  test.py:7:18 - error: No parameter named "where" (reportGeneralTypeIssues)
2 errors, 0 warnings, 0 informations
```

### What jax/jaxlib version are you using?

jax 0.4.23, jaxlib 0.4.23

### Which accelerator(s) are you using?

CPU

### Additional system info?

Python 3.11.6, macOS 14.2.1 (23C71)

**Comment by jakevdp** [comment]
Thanks for the report! #19380 should fix this.
