### ISSUE TITLE
Document how to use keyword arguments with jit

### ISSUE THREAD

**Issue by shoyer** [google/jax#1936]
Here's the recommendation, which JAX uses internally (from 
https://github.com/google/jax/issues/1925#issuecomment-569800183):

> The standard way to handle keyword arguments or unusual function signatures with `jit` is to write a helper function, e.g.,
> 
> ```python
> @functools.partial(jax.jit, static_argnums=(1,))
> def _my_func(x, y):
>   ...
> 
> def my_func(x, y):
>   return _my_func(x, y)
> ```
> 
> Now you can write something like `my_func(x=1, y=2)` and `y` will still be a static argument.

It would be nice to add this into the docs somewhere since this question seems to come up with some frequency.

**Comment by ziyadedher** [comment]
What's the reasoning behind not implementing this functionality or a derivative of it directly within `jit`?

We can use introspection to assign keyword arguments to their respective positional arguments. I guess this might be a little bit hacky with all the parameter passing, and it might not have support for positional-only arguments.

Just for reference, are there any more fundamental reasons?

**Comment by shoyer** [comment]
The main concern is that introspection is slow compared to Python’s builtin argument parsing. Jitted functions are often called in critical paths, and already have more overhead than we would like.

**Comment by mattjj** [comment]
Actually it’s not that it’s slow, it’s that it’s super brittle to the point of not really working. Decorators and any other kind of wrapping can obscure the signature so that we can’t robustly identify kwargs with positions.

Things may be slightly better in Py3-only but I think the fundamentals are still that Python signature introspection is not robust.

**Comment by shoyer** [comment]
I do think we could make keyword only arguments work reliably with `jit` (which would indeed probably be worthwhile). The hard part is figuring out when a positional argument corresponds to a keyword argument.

Inspect can do this sort of thing but it relies on knowing the original function signature exactly. `functools.wraps` does preserve signatures on Python 3 but it's still pretty common to use `*args` without that, which breaks introspection. We might be able to make something that works most of the time and raises an error when it can't, but it is indeed a little fragile.

**Comment by hawkinsp** [comment]
Also recall I had an alternate proposal, which is to require the user to specify both names *and* numbers, e.g.:
`jit(static_argnums = ((2, "foo"), (3, "bar"))`

While a little tedious to write, it doesn't require an accurate signature; you only need a signature to know which actual arguments correspond to which formal parameters. If you take the `static_argnums` specification in terms of the actual arguments, you don't need to know.

**Comment by ziyadedher** [comment]
I drafted a simple, but crude, possible fix. It does still break down if the arguments are occluded, but it might be a rough starting point to do something about this.

I was also toying with the idea of a `static_argnames` where a user could specify the names of keywords that they would want to be static; however, I have not investigated this.

**Comment by shoyer** [comment]
I noticed that NumPy uses "excluded names or numbers" for identifying arguments to skip in `np.vectorize`. This actually seems pretty reasonable to me:
https://docs.scipy.org/doc/numpy/reference/generated/numpy.vectorize.html

Basically this the flattened version of @hawkinsp's version above, `jit(static_args={2, 3, "foo",  "bar"})`

**Comment by shoyer** [comment]
I think we can consider this solved now that `jit` supports `static_argnames`.
