### ISSUE TITLE
Jax with cuda  installation command not correct

### ISSUE THREAD

**Issue by pingzhili** [google/jax#19430]
### Description

I'm installing jax following the command in README:
`pip install -U "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

However, this raises warning:
```
WARNING: jax 0.4.23 does not provide the extra 'cuda12-pip'
```
and the installed cuda Jax is not available with the failure below:
```
CUDA backend failed to initialize: Found cuBLAS version 120103, but JAX was built against version 120205, which is newer. The copy of cuBLAS that is 
installed must be at least as new as the version against which JAX was built. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)     
```

After checking the release website I tried to change the installation command to:
`pip install -U "jax[cuda12]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
and it gave the correctly installed Jax

### What jax/jaxlib version are you using?

jax 0.4.23; jaxlib 0.4.23

### Which accelerator(s) are you using?

GPU

### Additional system info?

1.26.3 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0] uname_result(system='Linux', node='kellislab3.csail.mit.edu', release='5.15.0-86-generic', version='#96-Ubuntu SMP Wed Sep 20 08:23:49 UTC 2023', machine='x86_64')

### NVIDIA GPU info

```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A100 80GB PCIe          On  | 00000000:17:00.0 Off |                    0 |
| N/A   60C    P0             345W / 300W |  15353MiB / 81920MiB |    100%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A100 80GB PCIe          On  | 00000000:31:00.0 Off |                    0 |
| N/A   62C    P0             300W / 300W |  24753MiB / 81920MiB |     92%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   2  NVIDIA A100 80GB PCIe          On  | 00000000:B1:00.0 Off |                    0 |
| N/A   56C    P0             248W / 300W |   4281MiB / 81920MiB |     86%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   3  NVIDIA A100 80GB PCIe          On  | 00000000:CA:00.0 Off |                    0 |
| N/A   37C    P0              66W / 300W |    583MiB / 81920MiB |      3%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
```

**Comment by jakevdp** [comment]
Hi, thanks for the report. JAX does specify the `cuda12_pip` extra, but not `cuda12-pip`. Can you check whether you had a typo when you ran the installation command?

**Comment by pingzhili** [comment]
> Hi, thanks for the report. JAX does specify the `cuda12_pip` extra, but not `cuda12-pip`. Can you check whether you had a typo when you ran the installation command?

Thanks for reply. I checked the command and it is 'cuda12_pip'. However, it seems like then pip identify it as `cuda12-pip`. This happens when I just created a new conda env with python=3.10

**Comment by jakevdp** [comment]
What version of `pip` do you have installed?

**Comment by jakevdp** [comment]
It looks like you're running into the issue discussed here: https://discuss.python.org/t/what-extras-names-are-treated-as-equal-and-why/7614

**Comment by pingzhili** [comment]
many thanks for pointing this out. according to their discussion, this is fixed in PEP685, so i tried python 3.12 and it works!

**Comment by rupeshknn** [comment]
Is there a resolution for python<3.12?

**Comment by jakevdp** [comment]
I've never been able to reproduce this issue personally; I'm sure it arises with some special combination of Python version, pip version, and jax version. I'd try installing newer or older pip versions and see if that fixes things for you.
