### ISSUE TITLE
sm_scale in flash_attention_tpu does not work like what it should

### ISSUE THREAD

**Issue by erfanzar** [google/jax#19450]
### Description

hi. I'm trying to create a port for flash_attention and when I read the code I found out that (I guess I'm wrong) that the sm_scale is replace for attn_w / sqrt(head_dim)  but it's being multiplied instead of that so I thought the  calculated sm_scale should be  `2 ** -(head_dim / 2)` and I set sm_scale to that but that simply wont work and even made predictions worst is it just  a bug or I'm not doing that right ?

where sm_scale being used 

https://github.com/google/jax/blob/main/jax/experimental/pallas/ops/tpu/flash_attention.py#L888

and why I thought this will work?
```python
sqrt_ = sqrt(head_dim)
(x * ( 2 ** -(head_dim / 2) )== x / sqrt_)
```
thanks for any help :)

### What jax/jaxlib version are you using?

0.4.23

### Which accelerator(s) are you using?

TPU

### Additional system info?

Linux

**Comment by erfanzar** [comment]
https://github.com/google/jax/blob/main/jax/experimental/pallas/ops/tpu/flash_attention.py#L832

**Comment by sharadmv** [comment]
You can set sm_scale to 1/sqrt(head_dim). I think that should work.
