### ISSUE TITLE
Expose XLA compiler options

### ISSUE THREAD

**Issue by jglaser** [google/jax#19468]
I'd like to be able to control XLA lowering options using a configuration setting, for debugging purposes.

e.g. 
`jax.config.update('xla_compile_options', {'xla_gpu_graph_min_graph_size': 123})`

XLA accepts the compiler options in `env_override_options`, which does not seem to be exposed in jax (except through the `.lower().compile(.., compiler_options=..)` interface.

See https://github.com/openxla/xla/issues/8692 for an example of why it can be useful to be able to set these options

Please:

- [X] Check for duplicate requests.
- [X] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by jakevdp** [comment]
You can pass XLA flags to JAX via the `XLA_FLAGS` environment variable. For example:
```python
$ XLA_FLAGS="--xla_gpu_graph_min_graph_size=123" python script.py
```

**Comment by jglaser** [comment]
yup, thanks for pointing out
