### ISSUE TITLE
jax.grad(has_aux=True) leaks identity tracers

### ISSUE THREAD

**Issue by trevorcai** [google/jax#1950]
```
def f(x):
  aux = dict(identity=x, p1=x+1)
  return x ** 2, aux

jax.grad(f, has_aux=True)(3.)

(DeviceArray(6., dtype=float32),
 {'identity': Traced<ConcreteArray(3.0, weak_type=True):JaxprTrace(level=0/0)>,
  'p1': DeviceArray(4., dtype=float32)})
```

**Comment by mattjj** [comment]
It's surprising that one of them is being unboxed properly...

A workaround for now is just to use `lax.stop_gradient(x)` when you build the dictionary.

**Comment by mattjj** [comment]
Really the whole `has_aux` stuff is bad and we should revise it away.

In the meantime #1955 should fix this issue.
