### ISSUE TITLE
sharded jit of einsum fails whereas pmap of einsum works

### ISSUE THREAD

**Issue by MaxiLechner** [google/jax#19523]
### Description

I have some code involving ```jnp.einsum``` that I would like to automatically parallelize using jit/pjit, but this results in a ValueError due to a indices mismatch. Pmap on the other hand handles einsum just fine.

```python #
import jax
from jax import jit, vmap, pmap
from jax.sharding import Mesh, NamedSharding
from jax.sharding import PartitionSpec as P
import jax.numpy as jnp

q = jnp.ones((2,2))
a = jnp.ones((1,2))
f = lambda x: jnp.einsum('ij,kj->ki', x, a)
print(f(q))

mesh = Mesh(jax.devices(), ("x",))
sharding = NamedSharding(mesh, P("x"))

w = q[None,...]

pmap_f = jax.pmap(f)
print(pmap_f(w).shape) # this works

jit_f = jit(f)
w = jax.device_put(w, sharding)
print(jit_f(w).shape) # ValueError: Einstein sum subscript 'ij' does not contain the correct number of indices for operand 0.
```

### What jax/jaxlib version are you using?

jax 0.4.23, jaxlib 0.4.23

### Which accelerator(s) are you using?

CPU/GPU

**Comment by jakevdp** [comment]
Hi - this looks to be operating as expected. `pmap` is a rank-reducing map, meaning the inputs to `f` when wrapped in `pmap` are logically of shape `w.shape[1:]`. On the other hand, `jit` is not a rank-reducing operation, so the inputs to `f` when wrapped in `jit` are of shape `w`.

In your case, you could fix this with a `vmap`, as `vmap` is also a rank-reducing map:
```python
jit_f = jit(vmap(f))
```
Does that help address your issue?

**Comment by MaxiLechner** [comment]
Yes this works for me. 
I think it would be helpful to also add the disclaimer about rank-reducing vs rank-preserving maps to the distributed array docs: [https://jax.readthedocs.io/en/latest/notebooks/Distributed_arrays_and_automatic_parallelization.html](). The impression I got from the distributed array docs was that I could parallelize any jax function by simply sharding the inputs and calling jit.

**Comment by jakevdp** [comment]
I'm not sure what you're referencing: can you point to a particular spot in that doc that you found misleading?
