### ISSUE TITLE
jax.lax.rng_uniform(k,k) has different behaviour in CPU (RANDOM int32) /TPU (ALWAYS k)

### ISSUE THREAD

**Issue by andresusanopinto** [google/jax#19616]
### Description

rng_uniform claims "Returns uniformly distributed random numbers in the range [a, b)".

When calling it with a == b, it has a different behaviour from CPU and TPU:
  - CPU: it seems to use the full int32 range.
  - TPU: it ALWAYS returns the same!!!

Example:

```
import jax.tools.colab_tpu
# jax.tools.colab_tpu.setup_tpu()

import jax
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)
print(jax.devices())
print(jax.lax.rng_uniform(3, 3, (10,)))
```

CPU:
```
cpu
[CpuDevice(id=0)]
[-1752798562  1744106001  -688905896  -376700610    28523420  -600052118
  1113020891   874027959   762190079  -467109515]
```

GPU:
```
gpu
[cuda(id=0)]
[-1752798562  1744106001  -688905896  -376700610    28523420  -600052118
  1113020891   874027959   762190079  -467109515]
```

On TPU:

```
tpu
[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0), TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1), TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0), TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1), TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0), TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1), TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0), TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
[3 3 3 3 3 3 3 3 3 3]
```

### What jax/jaxlib version are you using?

0.4.23

### Which accelerator(s) are you using?

CPU/GPU/TPU

### Additional system info?

https://colab.research.google.com/

**Comment by jakevdp** [comment]
Thanks for the report! I think this is working as expected. From the [XLA:RngUniform docs](https://www.tensorflow.org/xla/operation_semantics):

> if *b <= a* the result is implementation-defined.

I think we could make that more clear in the JAX documentation for `jax.lax.rng_uniform`.
