### ISSUE TITLE
jax tensor and numpy array convertion

### ISSUE THREAD

**Issue by yfji** [google/jax#1961]
How to convert numpy array to the jax tensor, or from jax tensor to numpy array?

**Comment by mattjj** [comment]
Thanks for the question!

```python
import numpy as onp
import jax.numpy as jnp

numpy_array = onp.array([1, 2, 3])
jax_array = jnp.array(numpy_array)
numpy_array_again = onp.array(jax_array)
```

Does that answer your question?

**Comment by shoyer** [comment]
I recommend using `asarray` instead of `array` to avoid unnecessary memory copies.

**Comment by yfji** [comment]
Thank you very much!^_^ @mattjj @shoyer

**Comment by dsantiago** [comment]
> I recommend using `asarray` instead of `array` to avoid unnecessary memory copies.

Sadly it will still copy even when using asarray(), tried this `np.array(jax_array, copy=False, subok=True)` but still generating new ids on each call... maybe just have to live with that for now

**Comment by jakevdp** [comment]
Hi @dsantiago - `copy=False` should result in no-copy device transfers if you're on a CPU backend (note that `subok` is not relevant here, becuase JAX arrays are not a subtype of numpy arrays). For more information on this, see the discussion in #4486, and particularly this comment: https://github.com/google/jax/issues/4486#issuecomment-736703827

**Comment by dsantiago** [comment]
> Hi @dsantiago - `np.array(x, copy=False)` (or equivalently, `np.asarray(x)`) should result in no-copy device transfers if you're on a CPU backend (note that `subok` is not relevant here, becuase JAX arrays are not a subtype of numpy arrays). For more information on this, see the discussion in #4486, and particularly this comment: [#4486 (comment)](https://github.com/google/jax/issues/4486#issuecomment-736703827)

Agree but there's lot of nuances to not make a copy(copy=False to work), as the dtypes must match, etc, etc...

Here is a good explanation about it:
https://stackoverflow.com/questions/14415741/what-is-the-difference-between-numpys-array-and-asarray-functions

**Comment by jakevdp** [comment]
It would not be possible for `id(jax_array)` to be equal to `id(np_array)`, because `jax_array` must be of type `jnp.DeviceArray` and `np_array` must be of type `np.ndarray`. The best we can do here is ensure that the buffers are shared when that is possible, and this is what `np.asarray(jax_array)` does.

**Comment by jakevdp** [comment]
Reading the StackOverflow question you linked to, it seems like your question is coming from the assumption that `jnp.DeviceArray` is a subclass of `np.ndarray`, but for various good reasons it is not. If you're interested, I may be able to dig up some discussion about why this design choice was made.

**Comment by dsantiago** [comment]
Ohh i see your point Jake. If i try this:

```python
x = random.split(random.PRNGKey(0), 10)
print(id(x))
print(id(np.asarray(x)))
print(id(np.array(x, copy=False)))
```
last 2 preserves the same id but of course not equal the original id of x(DeviceArray), like you mentioned. So i still think, in the end, we can use np.asarray or np.arrary interchangeably for converting from one type to another.

**Comment by jakevdp** [comment]
> So i still think, in the end, we can use np.asarray or np.array interchangeably for converting from one type to another.

No, not quite: `np.array` will always copy the underlying buffer, while `np.asarray` will use the existing buffer when possible. For example, on a CPU backend:
```python
import jax.numpy as jnp
import numpy as np
x_jnp = jnp.arange(10)

buffer_pointer = x_jnp.device_buffer.unsafe_buffer_pointer()

x_asarray = np.asarray(x_jnp)
print(np.byte_bounds(x_asarray)[0] == buffer_pointer)
# True

x_array = np.array(x_jnp)
print(np.byte_bounds(x_array)[0] == buffer_pointer)
# False
```

**Comment by dsantiago** [comment]
> > So i still think, in the end, we can use np.asarray or np.array interchangeably for converting from one type to another.
> 
> No, not quite: `np.array` will always copy the underlying buffer, while `np.asarray` will wrap the existing buffer when possible. For example, on a CPU backend:
> 
> ```python
> import jax.numpy as jnp
> import numpy as np
> x_jnp = jnp.arange(10)
> 
> buffer_pointer = x_jnp.device_buffer.unsafe_buffer_pointer()
> 
> x_asarray = np.asarray(x_jnp)
> print(np.byte_bounds(x_asarray)[0] == buffer_pointer)
> # True
> 
> x_array = np.array(x_jnp)
> print(np.byte_bounds(x_array)[0] == buffer_pointer)
> # False
> ```

Ohh i was just watching the surface results so.... Thanks for clarifying it, makes more sense for me and probably others that somehow drop off in this topic.!

**Comment by rokity** [comment]
I have a feature propose to create a jax function that convert DeviceArray to ndarray without explicit import numpy .

**Problem**
Convert DeviceArray to ndarray

**Actual Code Solution**
```python
import jax.numpy as jnp
import numpy as np

x_jnp = jnp.arange(10)
y_np =np.asarray(x_jnp)
```

**Proposal Code Solution**
```python
import jax.numpy as jnp

x_jnp = jnp.arange(10)
y_np =np.to_ndarray(x_jnp)
```

Let me know what you think about this propose I can afford the integration if you need.
I'm open to every comments review  feedback ect ect
@mattjj @jakevdp @shoyer

**Comment by shoyer** [comment]
@rokity  I presume you meant to write `jnp.to_ndarray()`?

> I have a feature propose to create a jax function that convert DeviceArray to ndarray without explicit import numpy .

Avoiding explicit imports of NumPy is a non-goal for JAX.

**Comment by jakevdp** [comment]
I'd agree with @shoyer – I don't think there's much need to add a new `jax.numpy` API for this, because `np.array(x_jnp)` does exactly what you want.

One side-note: it is possible currently to convert a jax array to numpy by calling the `__array__` method directly, which is what `np.asarray` delegates to under the hood:
```python
x_jnp = jnp.arange(10)
x_np = x_jnp.__array__()

print(type(x_np))
# <class 'numpy.ndarray'>
```

**Comment by rokity** [comment]
Thanks for the reply I'll use your tips.

**Comment by rokity** [comment]
This is not related to this issue @rabeehkarimimahabadi

**Comment by rabeehkarimimahabadi** [comment]
@rokity  it is about the first solution proposed in this issue. Could you elaborate why this is not related?
