### ISSUE TITLE
alternative to numpy.delete

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#1964]
I would like to delete a singleton index from an axis. Is there a way to achieve it using JAX?
```
x = np.ones((3, 5))
i = 1
y = np.delete(x, i, axis=0)
```
(here I am assuming that `i` is a DeviceArray int).

**Comment by fehiepsi** [comment]
Nvm, I think we can use `np.where(np.arange(3) < i, x[:-1], x[1:])` here.

**Comment by hawkinsp** [comment]
It looks quite feasible to implement `np.delete` using `lax.gather` (aka indexing)... except if we want to correctly handle repeated "deleted" elements under a `jit`. (We would need to know the elements form a set with no duplicates in order to know the output shape statically.)

**Comment by fehiepsi** [comment]
Yeah, I think it is doable too as long as the output shape is static. Having support for this would be very nice! (though I am satisfied with the `np.where` solution)
