### ISSUE TITLE
"E1130: bad operand type for unary -: ArrayImpl (invalid-unary-operand-type)" pylint errors in latest release (0.4.24)

### ISSUE THREAD

**Issue by fabianp** [google/jax#19713]
### Description

Running pylint (`pylint test.py`) on this simple file
```
"""Test file for 'E1130: bad operand type for unary -:'."""
from jax import numpy as jnp

a = -jnp.ones([])
```

fails with the latest release of jax (0.4.24) :

```
❯ pylint test.py
************* Module test
test.py:4:4: E1130: bad operand type for unary -: ArrayImpl (invalid-unary-operand-type)

-------------------------------------
```

The same code doesn't raise any error with jax 0.4.23.

This has led to some tests failures in other packages such as [optax](https://github.com/google-deepmind/optax)

### What jax/jaxlib version are you using?

0.4.24 0.4.24

### Which accelerator(s) are you using?

CPU

### Additional system info?

Tried on both linux and mac

**Comment by jakevdp** [comment]
Hi - thanks for the report. Do you understand where pytype is inferring that `ones` returns `ArrayImpl`? The pyi file has not changed, and declares that `ones` returns `Array` unconditionally: https://github.com/google/jax/blob/4c505f8bac45517970149b13343988090fdaa920/jax/numpy/__init__.pyi#L610-L611

I just double-checked that the pyi file is included in the v0.4.24 distribution, so I'm not sure why pytype would be ignoring it. Do you have any ideas?

**Comment by fabianp** [comment]
Thanks Jake for the prompt reply.

No, I don't understand why pylint is doing that inference. A couple of more observations:

* changing `-jnp.ones([])` to `jnp.negative(jnp.ones([]))` works fine (does not raise the error)
* I don't think the error is specific to `jnp.ones`. In particular, `-jnp.full([], 2.)` has the same issue

**Comment by jakevdp** [comment]
Chatting with @superbobry, it seems this is coming from `pylint`, not `pytype`. `pylint` has some level of type checking built-in, but it seems that it ignores `pyi` files and thus will not work correctly with dynamically-defined attributes. Here's a repro:
```bash
$ ls
mymodule.py  mymodule.pyi  test.py

$ cat mymodule.py
class Foo:
  pass
setattr(Foo, "__neg__", lambda self: self)

$ cat mymodule.pyi
class Foo:
  def __neg__(self) -> Foo: ...

$ cat test.py
"""Test file for incorrect E1130"""
from mymodule import Foo
result = -Foo()

$ mypy test.py
Success: no issues found in 1 source file

$ pylint test.py
************* Module test
test.py:3:9: E1130: bad operand type for unary -: Foo (invalid-unary-operand-type)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

**Comment by fabianp** [comment]
Thanks @jakevdp for reporting this upstream! I'll close the issue here since it does seem more of an issue in pylint
