### ISSUE TITLE
Unexpected numerical imprecision from jax.lax.scan

### ISSUE THREAD

**Issue by zhihanyang2022** [google/jax#19732]
### Description

I'm training some complex models and experienced some unexpected numerical problems with `jax.lax.scan`, so I cooked up the following minimally reproducible example to illustrate my point:

```python
from jax import config
config.update("jax_enable_x64", True)
import jax
import jax.numpy as jnp

key = jax.random.PRNGKey(42)

init = jax.random.normal(key, (100, ))
As = jax.random.normal(key, (10, 100, 100))

# method 1

def matrix_vector_multiplication(x, A):  # i know, this is the some weird function I cooked up
    return jnp.tanh((A @ A) @ x), None

res1 = jax.lax.scan(
    f=matrix_vector_multiplication,
    init=init,
    xs=As
)[0]

# method 2 (this method pre-computes `A@A`)

def matmul(A, B):
    return A @ B

vectorized_matmul = jax.vmap(matmul, (0, 0), 0)

AmAs = vectorized_matmul(As, As)

def matrix_vector_multiplication_v2(x, AmA):
    return jnp.tanh(AmA @ x), None

res2 = jax.lax.scan(
    f=matrix_vector_multiplication_v2,
    init=init,
    xs=AmAs
)[0]

jnp.max(jnp.abs(res2 - res1))  # gives Array(5.18931143e-09, dtype=float64)
```

The final result should be 0, but why is it not? To me, an error of order 1e-9 is rather big because I'm not changing the order of computation.

For a sanity check, I did the same comparison in plain Python and everything's fine:

```python
x1 = init
for A in As:
    x1, _ = matrix_vector_multiplication(x1, A)

x2 = init
for A in As:
    x2, _ = matrix_vector_multiplication_v2(x2, A@A)

jnp.max(jnp.abs(x1 - x2))  # Array(0., dtype=float64)
```

Crucially, it seems like `res2` is actually **wrong**:

```python
jnp.max(jnp.abs(res1 - x2)), jnp.max(jnp.abs(res2 - x2))
# (Array(0., dtype=float64), Array(5.18931143e-09, dtype=float64))
```

Again, this is a simple example derived from a much complex model that I'm working with. This little difference actually reduced my training performance, which is why I want to bring it to your attention.

### What jax/jaxlib version are you using?

0.4.23 0.4.23

### Which accelerator(s) are you using?

CPU

### Additional system info?

1.26.3 3.9.12 (main, Jun  1 2022, 06:34:44)  [Clang 12.0.0 ] uname_result(system='Darwin', node='zhihanyang.local', release='22.6.0', version='Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000', machine='arm64')

**Comment by jakevdp** [comment]
> The final result should be 0, but why is it not?

In general, you should not expect different approaches to the "same" computation to be bitwise-identical when using floating point numbers. To your question of why exactly errors accumulate differently in this particular case, I'm not sure, but  if you wish to understand it in more detail you could dig into it using [Ahead-of-time lowering](https://jax.readthedocs.io/en/latest/aot.html) to inspect what the compiler is doing in these cases.

Overall though, rounding errors of this magnitude are to be expected when working with floating point arithmetic, and if your algorithm is sensitive to errors at this level, you should look into how to make your algorithm more robust to the uncertainties of floating point math.
