### ISSUE TITLE
jax.lax.create_token() always returns the same object

### ISSUE THREAD

**Issue by chaserileyroberts** [google/jax#19744]
### Description

The method `jax.lax.create_token()` always returns the same singleton object, meaning all tokens are the same. This may be an issue if you want to do concurrent things. 

```
>>> jax.lax.create_token()
<jax._src.core.Token object at 0x7fff35329930>
>>> jax.lax.create_token()
<jax._src.core.Token object at 0x7fff35329930>
>>> jax.lax.create_token()
<jax._src.core.Token object at 0x7fff35329930>
>>> jax.lax.create_token()
<jax._src.core.Token object at 0x7fff35329930>
```

### What jax/jaxlib version are you using?

0.4.25

### Which accelerator(s) are you using?

GPU

### Additional system info?

Linux

**Comment by rajasekharporeddy** [comment]
Hi @chaserileyroberts 

This issue appears to be resolved with JAX 0.4.28. I tested this on Colab GPU using JAX cuda version 0.4.28. Now, `jax.lax.create_token()` produces different tokens at different runs. 

Please find the [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/5dd0ae962b95200a67c36cd1fc43eae7/-19744.ipynb) for reference.

Thank you

**Comment by hawkinsp** [comment]
I think @yueshengys fixed this... Yue confirm?

**Comment by yueshengys** [comment]
Yes, it's been fixed since https://github.com/google/jax/pull/20706.
