### ISSUE TITLE
C128 type in `XlaRuntimeError` when Float64 is used: "Element type C128 is not supported on TPU"

### ISSUE THREAD

**Issue by Danc2050** [google/jax#19769]
### Description

When creating an array with `dtype=jnp.float64` and passing this to Jax's `lax.fft` and `fft.fft` functions, an error is generated that indicates an element type of C128 was passed in.
```
XlaRuntimeError: INVALID_ARGUMENT: Element type C128 is not supported on TPU.
```

Here is a reproducible notebook: https://www.kaggle.com/zyrellla/c128-error

### What jax/jaxlib version are you using?

jax 0.4.17 jaxlib 0.4.17 and jax 0.4.4 jaxlib 0.4.4

### Which accelerator(s) are you using?

TPU

### Additional system info?

1.26.3 3.10.13 (main, Jan 17 2024, 06:53:56) [GCC 12.2.0] uname_result(system='Linux', node='a77b3ba272f3', release='6.1.75+', version='#1 SMP PREEMPT_DYNAMIC Sat Feb 10 15:23:41 UTC 2024', machine='x86_64')

**Comment by jakevdp** [comment]
Hi - thanks for the report! FFT operations require complex inputs, and when you input 64-bit floats, the corresponding complex type is complex128.

As for why this is erroring: TPU does not have support for many 64-bit operations. If you're working on TPU, we generally would suggest using the default `jax_enable_x64=False` setting, to limit all operations to 32-bit.

Hope that helps!
