### ISSUE TITLE
Improve GitHub bug template

### ISSUE THREAD

**Issue by carlosgmartin** [google/jax#19771]
To make the process easier for users, I suggest putting a _single_ shell snippet in the [bug template](https://github.com/google/jax/blob/main/.github/ISSUE_TEMPLATE/bug-report.yml) that can be easily copy-pasted by a user and outputs all the desired information in one go. Example:

```bash
python3 --version; \
python3 -c "import jax; print('jax version:', jax.__version__)"; \
python3 -c "import jaxlib; print('jaxlib version:', jaxlib.__version__)"; \
python3 -c "import numpy; print('numpy version:', numpy.__version__)"; \
python3 -c "import sys; print('sys version:', sys.version)"; \
python3 -c "import jax; print('jax devices:', jax.devices())"; \
uname; \
cat /etc/os-release; \
hostnamectl; \
nvidia-smi
```

And so on.

**Comment by jakevdp** [comment]
How about `python -c "import jax; jax.print_environment_info()"`

**Comment by carlosgmartin** [comment]
@jakevdp That works too!
