### ISSUE TITLE
Fused gather-scatter-add implementation

### ISSUE THREAD

**Issue by irhum** [google/jax#1979]
Suppose you have an input and a source vector of size M, and a vector of input indices and output indices of N, where N>>M. The idea is that the value of the input at index input_indices[i] is to be added to the value of output at output_indices[i]. In this case, the first operation is a gather op, while the latter is a scatter-add, but an intermediate vector is required which has a memory cost of O(N) (the gather op outputs a vector of size N). Would it be possible to provide a directly fused op that avoids the intermediary to lower the cost to O(M)?

Probably best described in a diagram:
![gather-scatter](https://user-images.githubusercontent.com/13271155/72177632-52672f00-340b-11ea-9d46-7b6ad54f3426.png)

and would look like this in code:
```
gather_output = input[input_indices]
scatter_add_output = ops.index_add(output, output_indices, gather_output)
```

Not sure if there's an appropriate XLA op, but if there is it'd make it considerably easier to work with large graphs when training graph neural networks, as instead of making many, many copies of node features as the output of the gather op, the results can be directly fused to the output.

**Comment by jekbradbury** [comment]
Are you interested in a particular backend? The way something like this would work in XLA probably wouldn't be to add an op, but to make sure that the gather and scatter are fused by the compiler (and that's a backend-specific question).
@blakehechtman is this a fusion the TPU backend can do?

**Comment by irhum** [comment]
I see; I am primarily interested in the TPU backend, and was indeed curious to learn if this is a possible fusion, or if this is unfeasible (in which case I'll need to have to figure out some alternate way to implement the NN). Thanks!

**Comment by blakehechtman** [comment]
If N and M are a similar size and are less are less than 8k a matmul is very likely the fastest solution.

**Comment by shoyer** [comment]
I would suggest trying to write this as matrix-multiplication, which is very efficient on TPUs. If you end up needing to use explicit array indexing that's something that might be a better fit for implementing on GPUs instead.

**Comment by mattjj** [comment]
![image](https://user-images.githubusercontent.com/1458824/72190697-1608e400-33b5-11ea-8ea2-1cb190ef6911.png)

XLA:GPU will fuse these it seems, and my guess is that XLA:TPU will do it too, since generally XLA:TPU is the most super-optimizing. I'll check with Blake, though.

**Comment by blakehechtman** [comment]
aren't input_indices already O(N)?

**Comment by irhum** [comment]
Right, they are, I probably should have worded it better. 

The indices are just a vector where each quantity is a scalar, while the input and output are vectors of vectors (i.e. a matrix), say, of dim d. The question is whether it's possible to lower the memory requirement from O(N*d) to O(M*d), as for many graph applications there can be a two orders of magnitude difference between N (the number of edges in this specific case), and M (the number of nodes). 

The full layer looks like the node features, (already batched into an N*dim_in matrix), being passed through an affine transform (now an N*dim_out matrix), then aggregated via the gather scatter operations (i.e. the node features in location 2 should have features from 3, 4 and 8 since there exists an edge from them to 2)

**Comment by mattjj** [comment]
Sounds like the answer is we expect XLA to fuse it automatically in cases where it's beneficial to do so. Should we close this question issue for now, and if you see it's not fusing automatically on some backend you can open a bug issue for us to look into it more?

**Comment by irhum** [comment]
Sure thing, thanks for the answers!
