### ISSUE TITLE
Problem with Pallas in JAX 0.4.24

### ISSUE THREAD

**Issue by southfreebird** [google/jax#19825]
### Description

I trying to setup an environment for jax 0.4.24
When I try to running a pallas kernel (like an [example](https://github.com/google/jax/blob/main/jax/experimental/pallas/ops/softmax.py)), I get an error:
`LLVM ERROR: Trying to register different dialects for the same namespace: builtin`
Triton kernels work well

### System info (python version, jaxlib version, accelerator, etc.)

Tax 0.4.24, jaxlib 0.4.24, triton on commit https://github.com/openai/triton/commits/9f816a7b984ce20ec684866f9c8bb5ffd49e2500, jax-triton on commit 3666738dd9fef74f702a82a3fa068d7e2bc80e2a

**Comment by olupton** [comment]
That error should have been fixed in https://github.com/google/jax/commit/5e2e609a9b8da90989a593575ad83eb2e43109e8, so you would need a version including that.
If it suits your workflow, you could try the containers distributed as `ghcr.io/nvidia/jax:pallas-YYYY-MM-DD` (or `ghcr.io/nvidia/jax:pallas` for the latest one).

**Comment by southfreebird** [comment]
Got it! Thank you for the answer

**Comment by southfreebird** [comment]
Tried the latest one (2024-02-14) and got en error:
"""
python3: /opt/openxla-triton/include/triton/Tools/Sys/GetEnv.hpp:49: bool triton::tools::getBoolEnv(const string&): Assertion `::triton::ENV_VARS.find(env.c_str()) != ::triton::ENV_VARS.end() && msg.c_str()' failed.
"""
As I understand, it rises because of the commit: https://github.com/openxla/triton/commit/f2d49c8fd08cef4adbfddd6e428d93f98576653f

The flag `ENABLE_MMA_V3` was renamed to `ENABLE_MMA_V3` without fixing it in https://github.com/openxla/triton/blob/f2d49c8fd08cef4adbfddd6e428d93f98576653f/include/triton/Tools/Sys/GetEnv.hpp#L32-L35

**Comment by superbobry** [comment]
jaxlib 0.4.25 no longer has this issue. Closing as fixed.
