### ISSUE TITLE
Improve Custom Partioning API Documentation

### ISSUE THREAD

**Issue by ASKabalan** [google/jax#19881]
improve jax.experimental.custom_partitioning.html#jax.experimental.custom_partitioning.custom_partitioning) documentation

**Comment by ASKabalan** [comment]
So I have scanned the XLA & JAX repo to get a better understanding and here is what I learned

The custom SPMD call is registered with a `CustomCallPartitioner` that  XLA uses to learn how does this particular custom call wants to be partitioned.

[XLA/custom_call_sharding_helper.cc#L63](https://github.com/openxla/xla/blob/e83773328ac3b327e4925b877f2988bb45aa7bf1/xla/service/custom_call_sharding_helper.cc#L63)

```cpp
void RegisterCustomCallPartitioner(
    const std::string& custom_call_target,
    std::unique_ptr<CustomCallPartitioner> partitioner) {
  auto& partitioners = GetPartitioners();
  partitioners.emplace(custom_call_target, std::move(partitioner));
}
```

the `CustomCallPartitioner` derived by `PyCustomCallPartitioner` for exposure in python and thus JAX defines the three functions mentionned in [jax.readthedocs.io/](https://jax.readthedocs.io/en/latest/jax.experimental.custom_partitioning.html)

[`PyCustomCallPartitioner`](https://github.com/openxla/xla/blob/main/xla/python/custom_call_sharding.cc#L109C7-L109C30) consumes the three functions `partition`, `infer_sharding_from_operands` and `propagate_user_sharding` from the JAX user 

## Propagate User Sharding

The goal here is to override the sharding of an array given by the user

[XLA/custom_call_sharding.cc#L198](https://github.com/openxla/xla/blob/main/xla/python/custom_call_sharding.cc#L198)

```cpp
HloSharding PropagateUserSharding(
    const HloInstruction* instruction, const HloInstruction* user,
    const HloSharding& sharding) const override {


 auto result = py::cast<HloSharding>(prop_user_sharding_(
          sharding, instruction->shape(),
          py::bytes(instruction->raw_backend_config_string())));
...
    }
```
The returned result is also a `HloSharding` and it supposed to override the input 


__Note:__ Propagate sharding does not work because it is not used in XLA [github search](https://github.com/search?q=repo%3Aopenxla%2Fxla%20InferShardingFromUsers&type=code)
The funtion is declared but not used anywhere (maybe I am wrong??) any ways using print and inspect statement I am not able to get anything and the overriding is not working.

It is (supposed to be) called here

```cpp
bool ShardingPropagation::InferShardingFromUsers
```

[xla/service/sharding_propagation.cc#L2809](https://github.com/openxla/xla/blob/main/xla/service/sharding_propagation.cc#L2809)
```cpp
std::optional<HloSharding> user_sharding =...
...
if (partitioner->IsCustomCallShardable(instruction)) {
    user_sharding = partitioner->PropagateUserSharding(instruction, user,
                                                        *user_sharding);
}
```

On the JAX side : 

[JAX/custom_partitioning.py#L109](https://github.com/google/jax/blob/21656115847079981e3915f88ab4533790970f53/jax/experimental/custom_partitioning.py#L109)

```python
def _custom_partitioning_propagate_user_sharding(user_sharding, shape,
                                                 backend_string):
...
 return _pack_result_sharding(shape, result_shardings)

```

Then is it registered for the SPMD CustomCall

## Next Infering the output sharding from the input sharding

The second function defined by the XLA's `PyCustomCallPartitioner` is used to infer the output sharding from the input directy.

[XLA/custom_call_sharding.cc#L215](https://github.com/openxla/xla/blob/main/xla/python/custom_call_sharding.cc#L215C1-L216C58)
```cpp
std::optional<HloSharding> InferShardingFromOperands(
    const HloInstruction* instruction) const override {
...

auto py_result = infer_sharding_from_operands_(
        arg_shapes, arg_shardings, instruction->shape(),
        py::bytes(instruction->raw_backend_config_string()));
...
 return py::cast<HloSharding>(py_result);

```

The function takes the input shape and sharding and the result shape and should return the result sharding.

On JAX side it is declared here

[JAX/custom_partitioning.py#L199](https://github.com/google/jax/blob/21656115847079981e3915f88ab4533790970f53/jax/experimental/custom_partitioning.py#L199C1-L201C71)


```python
def _custom_partitioning_infer_sharding_from_operands(arg_shapes, arg_shardings,
                                                      result_shape,
                                                      backend_string):
...
  result_sharding = info.infer_sharding_from_operands(
      *info.static_args,
      info.mesh,
      info.unflatten_arg_shapes(arg_shapes, arg_shardings),
      info.out_tree.unflatten([_to_jax_shape(s) for s in result_shapes]),
  )
...
    return _pack_result_sharding(result_shape, result_shardings)

```

## Finally and most importantly : Partition

On the XLA side 

[XLA/custom_call_sharding.cc#L124](https://github.com/openxla/xla/blob/main/xla/python/custom_call_sharding.cc#L124)
```cpp
xla::Status Partition(spmd::SpmdPartitioningVisitor* partitioner,
                    HloInstruction* instruction) const override {
...
auto py_result =
partition_(GetArgShapes(instruction), GetArgShardings(instruction),
           instruction->shape(), instruction->sharding(),
           py::bytes(instruction->raw_backend_config_string()));
...
 std::tie(m, arg_shardings, result_sharding) = py::cast<
            std::tuple<py::object, std::vector<HloSharding>, HloSharding>>(
            py_result);

...
partitioner->SetPartitionedHlo(instruction, result_partitioned); // <-- In here XLA now knows how to partition the primitive
```

The required function takes shapes and shardings for each argument and a single shape and sharding fot the output + the HLO MLIR code

Then on JAX side

[jax/experimental/custom_partitioning.py#L142](https://github.com/google/jax/blob/21656115847079981e3915f88ab4533790970f53/jax/experimental/custom_partitioning.py#L142)
```python
def _custom_partitioning_partition(arg_shapes, arg_shardings, result_shape,
                                   result_sharding, backend_string):
...

mesh, lower_fn, result_sharding, arg_shardings = info.partition(
      *info.static_args,
      info.mesh,
      info.unflatten_arg_shapes(arg_shapes, arg_shardings), # <-- A tuple of all operands shapes and sharding
      info.out_tree.unflatten(
          [
              info.unflatten_arg_shape(s, sharding)
              for s, sharding in zip(result_shapes, result_shardings)  # <-- a single sharding and shape for the output
          ]
      ),
...
closed_jaxpr = jax.make_jaxpr(lower_fn, axis_env=list(mesh.shape.items()))(
module = mlir.build_mlir_module_helper(
closed_jaxpr,

return mlir.module_to_bytecode(module), arg_shardings, result_sharding
```

***I can safely say the CustomPartitioning Does not support multi output with different shardings because XLA doesn't allow custom SPMD call with multi outputs***

[xla/python/custom_call_sharding.cc#L147](https://github.com/openxla/xla/blob/main/xla/python/custom_call_sharding.cc#L147C1-L152C8)
```cpp
} catch (const py::cast_error& e) {
return xla::Internal(
    "Shardings returned from partitioning %s: expected "
    "Tuple[bytes, List[HloSharding], HloSharding] got: %s",
    instruction->ToString(), py::repr(py_result));
}
```
It takes a list for the input but a single element for the output


# For JAX users


We need to decalre two functions then 

**partition :**

as defined in 

```python

def partition(mesh, arg_shapes, result_shape):
    """
    Tells XLA how to partition the primitive

    Args:
        mesh (Mesh): The contextual mesh 

        arg_shapes (tuple): A tuple of ShapeDtypeStruct that contains the shape and the sharding of each input operand

        result_shape (ShapeDtypeStruct) : a ShapeDtypeStruct reprsenting a single output

    Returns:
        Mesh (Mesh) : The mesh. 

        function: The lowered function, to allow the user to redefine how the primitive is called in a context of a specific sharding 
                
        result_sharding (XLACompatibleSharding): The sharding result for example a NamedSharding. 

        arg_shardings (tuple): a tuple of all XLACompatibleSharding of the input operands
    """
```
Next **infer_sharding_from_operands**

```python

def infer_sharding_from_operands(mesh, arg_shapes, shape):
    """
    Tell XLA how to infer the sharding of the output from the input sharding.

    Args:
        mesh (Mesh): The contextual mesh 

        arg_shapes (tuple): A tuple of ShapeDtypeStruct that contains the shape and the sharding of each input operand

        result_shape (ShapedArray) : a single ShapedArray reprsenting a single output without the sharding information

    Returns:
            
        result_sharding (XLACompatibleSharding): The sharding result for example a NamedSharding. 

    """
```

BTW: the infered sharding from `infer_sharding_from_operands` is in the input `result_shape` of the `partition` function

# Use cases

In numerical computing for physics and where algorithms are not typically decomposable in a straight forward way like a deep learning network way, this is very powerfull.\
For example 3D FFTs, linear algebra solvers and matrix inversions.

I can make a simple example as guide to showcase this

**Comment by nouiz** [comment]
Note, an example is being added here: https://github.com/google/jax/pull/20179
