### ISSUE TITLE
Installing jax on an M1 Mac with Python 3.9 doesn't work

### ISSUE THREAD

**Issue by isaacdevlugt** [google/jax#19899]
### Description

I created a fresh virtual environment with the python 3.9 binary via `python3.9 -m venv <path>`, activated it and installed jax and jaxlib via `python -m pip install jax jaxlib` and everything seems to go off without a hitch. But, when I import jax I get this:

```
>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/isaac/.virtualenvs/jax-only/lib/python3.9/site-packages/jax/__init__.py", line 39, in <module>
    from jax import config as _config_module
  File "/Users/isaac/.virtualenvs/jax-only/lib/python3.9/site-packages/jax/config.py", line 15, in <module>
    from jax._src.config import config as _deprecated_config  # noqa: F401
  File "/Users/isaac/.virtualenvs/jax-only/lib/python3.9/site-packages/jax/_src/config.py", line 28, in <module>
    from jax._src import lib
  File "/Users/isaac/.virtualenvs/jax-only/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 84, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.
```

Everything is peachy with Python 3.10 or 3.11 🍑. 

### System info (python version, jaxlib version, accelerator, etc.)

I can't do this because I can't import jax on python 3.9. But, I'm using an M1 macbook air with MacOS 14.3.1. If you require more information please let me know.

**Comment by hawkinsp** [comment]
This means that your Python installation is an x86 Python installation running under Rosetta, not a Mac ARM build. Please use an *ARM* build of Python!

Hope that helps!

**Comment by curlup** [comment]
@isaacdevlugt how did you resolve it?

**Comment by isaacdevlugt** [comment]
@curlup make sure you have the proper python binary installed! You need an ARM build, not x86 (for the older macs with intel chips). So, wherever you download python, make sure it's the ARM one and then make sure that that's the one you're actually using!

**Comment by curlup** [comment]
Thanks, yes, that solved it.
