### ISSUE TITLE
Implement all of numpy.linalg

### ISSUE THREAD

**Issue by shoyer** [google/jax#1999]
- [x] cholesky
- [x] cond
- [x] det
- [x] eig
- [x] eigh
- [x] eigvals
- [x] eigvalsh
- [x] inv
- [x] lstsq
- [x] matrix_power
- [x] matrix_rank
- [x] multi_dot
- [x] norm
- [x] pinv
- [x] qr
- [x] slogdet
- [x] solve
- [x] svd
- [x] tensorinv
- [x] tensorsolve

**Comment by StephenHogg** [comment]
I'm interested in doing `cond`. 

The original numpy code shows functions like:

```
_assertRankAtLeast2(x)
_assertNdSquareness(x)
```

How can I check that I have access to these, is it a question of looking in `lax.py`?

**Comment by sudsj** [comment]
Hi, I'm interested in doing `multi_dot`, I've looked at numpy's implementation of it, this is my first issue here, so can you please give me some pointers on how to proceed?

**Comment by shoyer** [comment]
> I'm interested in doing `cond`.
> 
> The original numpy code shows functions like:
> 
> ```
> _assertRankAtLeast2(x)
> _assertNdSquareness(x)
> ```
> 
> How can I check that I have access to these, is it a question of looking in `lax.py`?

You can search for the relevant helper functions in `jax/numpy/linalg.py` but if you don't see them, they probably need to be reimplemented in JAX.

> Hi, I'm interested in doing `multi_dot`, I've looked at numpy's implementation of it, this is my first issue here, so can you please give me some pointers on how to proceed?

Thanks for your interest here. You have two choices:
1. reimplement the algorithm from scratch without reference to NumPy
2. if you want to use/adapt NumPy's implementation, that's fine, but the code needs to go into a [dedicated `third_party` directory](https://opensource.google/docs/releasing/preparing/#third-party-components) that includes the LICENSE file copied from NumPy, e.g., `jax/third_party/numpy`

**Comment by StephenHogg** [comment]
Hi again - I'm most of the way with `cond` but in the original source code it is using `with errstate(all='ignore')` for some parts of code so that poorly defined matrix inverses etc will not flip out and be handled later if for example `Inf` is returned. Do you have any advice on how I might proceed in a similar fashion here?

**Comment by shoyer** [comment]
JAX does not issue warnings for invalid values, so you can ignore all of
that.

**Comment by StephenHogg** [comment]
Thanks for this - I now have `cond` written and loaded into the appropriate namespace. The final question is how to go about writing an appropriate test. So far, I am thinking of just cloning https://github.com/google/jax/blob/master/tests/lax_numpy_test.py#L638 but am not sure how to constrain the shapes tested to just be 2D or whether I should, given that it might be worth checking that errors are raised appropriately. Grateful for any guidance on what you'd like here.

**Comment by shoyer** [comment]
Yes, you can use that example with an explicit list of shapes rather than `all_shapes`, e.g., as done here: https://github.com/google/jax/blob/4e575e1492afc08c8307d77cf7c784a17a52016e/tests/linalg_test.py#L210

**Comment by Guillem96** [comment]
Hi, everybody, I am implementing the tensorsolve function. For now, seems it is working. Should I implement any test case? Any Suggestion?

Also, when I finish the implementation, Is there any guide on how to do a proper pull request for JAX? 

Thanks in advance

**Comment by StephenHogg** [comment]
> Yes, you can use that example with an explicit list of shapes rather than `all_shapes`, e.g., as done here:
> 
> https://github.com/google/jax/blob/4e575e1492afc08c8307d77cf7c784a17a52016e/tests/linalg_test.py#L210

Thanks for this - one more question, if that's alright. I've noticed that `inv` as implemented in Jax isn't tested for how it handles complex-valued matrices:

https://github.com/google/jax/blob/be2704e425e8325a6eddbbc317e6c00da390acb1/tests/linalg_test.py#L563

This means that testing `cond` for complex-valued matrices can also fail seeing as it uses an inverse operation. Is it alright if I leave that out, or should `inv` be changed?

**Comment by shoyer** [comment]
A lack of tests doesn’t necessarily mean it doesn’t work :)

Certainly it would be great to add more test coverage for existing functions, e.g., with complex dtypes.

For any new functions, you should certainly test them with a full range of valid inputs. I would definitely include complex values, unless for some reason it’s easier to make a version of cond only works for real values (in which case you should raise an error for complex numbers).

**Comment by StephenHogg** [comment]
Fair enough, point taken :) PR is open

**Comment by StephenHogg** [comment]
I've ported `tensorinv` as well, but notice that some of the tests (e.g. on 3D or complex-valued matrices), can take some time. Any thoughts on whether these should still be included? Sorry for the bother.

**Comment by StephenHogg** [comment]
A question about implementing `multi_dot`: I've ported the code over from numpy, but it uses the recursive algorithm found [here, under "A dynamic programming algorithm"](https://en.wikipedia.org/wiki/Matrix_chain_multiplication). This means that the jax implementation throws a `RecursionError` even though the equivalent numpy code doesn't for the same input. 

In light of this, my question is as follows: what to do about this? If there's some way of unrolling that recursion I'm more than happy to code it up. Otherwise, if there's something wrong with the way I've ported things I'm also happy to address that, though it may take someone looking at the code to reach a decision about that. On the face of it, it does seem rather odd that one implementation would have no recursion issue whereas another would, unless numpy is doing stuff in C that this current attempt in jax isn't? The implementation I have is available here:

https://github.com/StephenHogg/jax/blob/7e0d8a92cc2285f62686b830b3074240a96f695c/jax/third_party/numpy/linalg.py#L158

**Comment by sudsj** [comment]
Hi, I'm trying to implement the `multi_dot` function in `jax/numpy/linalg.py` using helper functions from `jax/numpy/lax_numpy.py`. I wanted to test my code, but building jax is taking too much time on my pc. Is that normal? 
I am new to this so I apologize if it may seem silly, but it doesn't seem convenient to wait so much to test little changes in the code, am I missing something?

**Comment by Jakob-Unfried** [comment]
@sudsj 

I am interested in using `multi_dot` as soon as possible.
Any news on your progress?
Do you need help?

**Comment by sudsj** [comment]
@Jakob-Unfried, I need some help with testing my changes, as I'm facing errors while importing the modules in the python interpreter to test the functions. Do you have a Gitter account, where I can message screenshots/code ?

**Comment by joaogui1** [comment]
I'm interested in doing `lstsq`

**Comment by Jakob-Unfried** [comment]
@sudsj 
I have a Gitter account now.
Will move my conversation with you about `multi_dot` with you to private messages there.

**Comment by oleg-kachan** [comment]
Implementing the `scipy.linalg` functionality will be good also:

- [ ] lu
- [ ] polar
- [ ] expm
- [ ] logm
- [ ] sqrtm
- [ ] fractional_matrix_power

**Comment by Jakob-Unfried** [comment]
@oleg-kachan 
`expm` and `lu` exist in `jax.scipy.linalg`

**Comment by AidanGG** [comment]
@oleg-kachan `polar` calls `svd` as in https://github.com/scipy/scipy/blob/master/scipy/linalg/_decomp_polar.py. I can make a PR when I have time.
