### ISSUE TITLE
Documentation Errors in jax.scipy module

### ISSUE THREAD

**Issue by selamw1** [google/jax#20086]
I've found the following errors in the documentation for [`jax.scipy`](https://jax.readthedocs.io/en/latest/jax.scipy.html) module:
https://jax.readthedocs.io/en/latest/jax.scipy.html

1. Duplicate `sqrtm` function:

- [ ] The `sqrtm` function is listed twice under `jax.scipy.linalg`.

2. Typo in idctn description:

- [ ] The description for `idctn` incorrectly states "Discrete Cosine Transform." It should be "Inverse Discrete Cosine Transform" to match the function's behavior.

**Comment by jakevdp** [comment]
Thanks! Fixed in #20087
