### ISSUE TITLE
Proposal for PRNG key replacement.

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#2009]
Right now, the PRNG key usage is a huge foot gun. Almost every single new use (including myself!) will incorrectly reuse the PRNG key in this way:

```python
key = jax.random.PRNGKey(0)
a = jax.random.uniform(key, (10, 10))
b = jax.random.uniform(key, (10, 10))
```
Causing `a` and `b` to be the exact same values, which is very unlikely to be what a new user wants. 

I am proposing a new `PRNGKeyGenerator` class to alleviate some of these issues. The class will basically just look like this.

```python
class PRNGKeyGenerator():
  def __init__(self, seed):
    self._key = jax.random.PRNGKey(seed)

  def next(self):
     self._key, new_key = jax.random.split(self._key)
     return new_key
```

Now, (assuming all of the docs are updated), a new user would just do this instead:

```python
keygen = jax.random.PRNGKeyGenerator(0)
a = jax.random.uniform(keygen.next(), (10, 10))
b = jax.random.uniform(keygen.next(), (10, 10))
```
and `a` and `b` will now have different random values. It now is less of a foot gun while still maintaining the reproducibility that JAX's random library original sought. If a user passes just `keygen` instead of `keygen.next()`, a type check can quickly detected it and crash with a very clear error.

**Comment by Thenerdstation** [comment]
The main argument against this is that `PRNGKeyGenerator` is now a mutable object, which goes against the functional nature of JAX.

**Comment by mattjj** [comment]
Well, that makes it sound like an aesthetic complaint, but it's very much practical. Here's the example from chat:

```python
@jit  # consider keeping or removing this jit
def f():
  return random.uniform(keygen.next(), (10, 10))

f()
f()
```

With a `jit`, those two calls return the same value. Without a `jit`, they almost surely won't. That violates one of the basic promises of `jit`.

Unfortunately this proposal is one we've considered (and has been brought up before), and we rejected it for the above issue.

I think the right solution is to add a check for key reuse.

**Comment by mattjj** [comment]
I'm going to take your thumbs-up reaction as "hm okay, I guess we can close this." But please reopen / comment more if you're still not satisfied!

**Comment by jaymody** [comment]
Is there a good/standard way to check for key reuse in my code? Currently, I put together the following test which seems to work well:

```python
import jax

def good():
    key = jax.random.PRNGKey(123)
    key, a_subkey, b_subkey = jax.random.split(key, 3)
    a = jax.random.normal(a_subkey, (10, 5))
    b = jax.random.normal(b_subkey, (10, 5))
    return a + b

def bad():
    key = jax.random.PRNGKey(321)
    a = jax.random.normal(key, (10, 5))
    b = jax.random.normal(key, (10, 5))
    return a + b

def test_initialization_does_not_reuse_keys():
    """Tests that we didn't reuse any keys during initialization."""
    from inspect import getfullargspec, getmembers, isfunction

    used_keys = set()

    def check_key_is_not_reused_wrapper(func):
        argspec = getfullargspec(func)
        if "key" not in argspec.args:
            return func
        key_arg_index = argspec.args.index("key")

        def wrapper(*args, **kwargs):
            if len(args) > key_arg_index:  # check if key is in args
                key = args[key_arg_index]
            else:  # otherwise it should be in kwargs
                key = kwargs["key"]

            key = tuple(key.tolist())  # turn key into a hashable type
            assert key not in used_keys, f"key {key} is reused by {func.__name__}"
            used_keys.add(key)

            return func(*args, **kwargs)

        return wrapper

    for name, func in getmembers(jax.random, isfunction):
        setattr(jax.random, name, check_key_is_not_reused_wrapper(func))

    good() # passes
    bad() # fails
```

**Comment by jakevdp** [comment]
We've been working on some ideas for checking key reuse: see e.g. https://github.com/google/jax/pull/8953. @froystig  and @LenaMartens may be able to update on the current status.

**Comment by froystig** [comment]
Key reuse checking currently depends on #9263
