### ISSUE TITLE
error: failed to legalize operation 'mhlo.pad'

### ISSUE THREAD

**Issue by nullhook** [google/jax#20119]
### Description

is there support for associative scan operation on metal device yet? 

also, why is the code lowering to mhlo rather than stablehlo?

```
jaxlib.xla_extension.XlaRuntimeError: UNKNOWN: test.py:42:0: error: failed to legalize operation 'mhlo.pad'
test.py:42:0: note: see current operation: %34 = "mhlo.pad"(%33, %1) {edge_padding_high = dense<1> : tensor<1xi64>, edge_padding_low = dense<0> : tensor<1xi64>, interior_padding = dense<1> : tensor<1xi64>} : (tensor<1xsi32>, tensor<si32>) -> tensor<2xsi32>
```

```python
from jax import lax, jit
import jax.numpy as jnp

@jit
def a(): return lax.associative_scan(jnp.add, jnp.arange(0, 4))

a()
```

### System info (python version, jaxlib version, accelerator, etc.)

```Metal device set to: Apple M1 Max

systemMemory: 64.00 GB
maxCacheSize: 24.00 GB

jax:    0.4.20
jaxlib: 0.4.20
numpy:  1.26.2
python: 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)]
jax.devices (1 total, 1 local): [METAL(id=0)]
process_count: 1
```

**Comment by jakevdp** [comment]
Hi, thanks for the report! It looks like this has already been reported at https://github.com/google/jax/issues/19402. I'm going to close this so we can track the issue in one place. Thanks!

**Comment by jakevdp** [comment]
Actually, I'll keep this open since it may not be the same as other `mhlo.pad` issues.

**Comment by shuhand0** [comment]
This is the same issue as  in https://github.com/google/jax/issues/19402 and the fix will be in next release.

**Comment by hawkinsp** [comment]
Closing as duplicate.
