### ISSUE TITLE
Received "NotImplementedError: Singular value decomposition JVP not implemented for full matrices" while evaluating gradient of mse

### ISSUE THREAD

**Issue by Bonado** [google/jax#2011]
I am trying to write a very simple code for a linear regression problem, However, I received 
"NotImplementedError: Singular value decomposition JVP not implemented for full matrices" error 
while trying to run grad on the mse loss. Can someone look into this issue for me? 

```
#preamble 
import jax.numpy as np
from jax import grad, random
key = random.PRNGKey(1)

#generate random data
n, d = 20, 1 
x = random.uniform(key, (n, d), dtype=np.float64,  minval = -5., maxval = 5.)    
t = np.sin(np.pi*x) + 0.3*random.normal(key, (n, d))    

#build mean squared error || y - t ||^2

def make_mse_vector(x, t):  
  def mse_vector(w):
    return np.linalg.norm(np.dot(x, w) - t, ord = 2)
  return mse_vector 

w =  np.zeros(())

epsilon = 0.1
iter = 100

#The following line throws me SVD error
w_gradient = grad(make_mse_vector(x, t))(w) 

#run gradient descent 
for _ in range(iter):
  w = w - epsilon * w_gradient
  w_gradient = grad(make_mse_vector(x, t))(w)
```

**Comment by shoyer** [comment]
The forwards gradient for SVD (which is being used internally by the call to `np.linalg.norm`) is indeed unimplemented. There is a reference on how to implement it though, so presumably this could be done:
https://github.com/google/jax/blob/19fb494adbd4cefc984f08edf1982e644fe4a2b1/jax/lax_linalg.py#L780

For your particularly calculation, though, I'm not sure you're calculating the right thing. `ord=2` for matrices input into `np.linalg.norm` doesn't calculate the mean squared error, but rather the largest singular value.

**Comment by AidanGG** [comment]
I came across this issue caling for `'nuc'` norm with `np.linalg.norm`. It appears that in https://github.com/google/jax/blob/363f9e07fc157c97678a26dc7b70d4df3ad07a5d/jax/numpy/linalg.py#L244-L250
even though the singular vectors are not computed, the default argument `full_matrices=True` for SVD is triggering the error.

I believe `svd_jvp_rule` needs to be altered to output only `ds` when not `full_matrices`. I'm happy to open a PR @shoyer you believe this will work.

**Comment by cjerzak** [comment]
This is very helpful. Perhaps the documentation for `jax.numpy.linalg.svd` could mention that gradients are implemented only for `full_matrices=False`.
