### ISSUE TITLE
`grad(jit(f))` can fail when an output which is a forwarded input precedes an output which is also a residual

### ISSUE THREAD

**Issue by davisyoshida** [google/jax#20267]
### Description

Example:

```python
import jax
import jax.numpy as jnp

def f(x):
    @jax.jit
    def inner(a, x):
        return a, jnp.exp(x)
    return inner(0., x)[0]
jax.grad(f)(1.)
# IndexError: list index out of range
```
The error occurs in the call to `subs_list2` [here](https://github.com/google/jax/blob/a5d32c41c336368d8ec01bda17072d34189f7faa/jax/_src/pjit.py#L1844). It looks like the problem is that `idx_map` is built using indices into `out_vars`, so initially the `exp(x)` value is marked as being in output index 1. When the forwarded inputs and duplicated residuals are pruned, this index doesn't get updated, and can end up being out of bounds.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.25.2
python: 3.11.6 (main, Nov 14 2023, 09:36:21) [GCC 13.2.1 20230801]
jax.devices (2 total, 2 local): [cuda(id=0) cuda(id=1)]
process_count: 1
```

**Comment by mattjj** [comment]
Oof, what a bad bug! Thanks for reporting this!

**Comment by davisyoshida** [comment]
@mattjj Thanks for the quick fix! I had quite the experience tracking this down.

**Comment by mattjj** [comment]
Sorry for costing you time :(((

**Comment by davisyoshida** [comment]
It wasn't meant as a criticism! JAX is awesome.

**Comment by mattjj** [comment]
Thanks for the positivity! But still I feel bad for inserting this bug. Alas.
