### ISSUE TITLE
Bug with jnp.unique output shape

### ISSUE THREAD

**Issue by benmoseley** [google/jax#20274]
### Description

Hi, the shape of the output arrays from `jnp.unique` when using the `return_inverse` option is inconsistent between the current jax version (0.4.25) and a previous version (0.4.19). See below a minimal implementation:

```python
import jax
import jaxlib
import jax.numpy as jnp
import numpy as np

x = jnp.array(np.arange(200).reshape(20,10))
a,b = jnp.unique(x, axis=0, return_inverse=True)
print(a.shape, b.shape)

print(jax.__version__, jaxlib.__version__)
```

Output when running with jax version 0.4.19:
```
(20, 10) (20,)
0.4.19 0.4.19.dev2023102
```

Output when running with jax version 0.4.25:
```
(20, 10) (20, 1)
0.4.25 0.4.25
```

Note that the `b` array has an extra trailing dimension in the latest version.

This is breaking my current project code, please let me know if this is intentional or not, so I can update my project code if necessary?

### System info (python version, jaxlib version, accelerator, etc.)

Old version:
jax:    0.4.19
jaxlib: 0.4.19.dev20231024
numpy:  1.26.0
python: 3.10.13 (main, Sep 11 2023, 08:39:02) [Clang 14.0.6 ]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1

New version:
jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.26.4
python: 3.12.2 | packaged by Anaconda, Inc. | (main, Feb 27 2024, 17:35:02) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='eu-login-45', release='3.10.0-1160.108.1.el7.x86_64', version='#1 SMP Thu Jan 25 16:17:31 UTC 2024', machine='x86_64')

**Comment by benmoseley** [comment]
Actually, I see that this change was intentional looking at the change log entry (https://jax.readthedocs.io/en/latest/changelog.html) jax 0.4.24 (Feb 6, 2024), so closing the issue

**Comment by jakevdp** [comment]
Yeah, this was a deliberate change based on a similar change made in numpy unique. Thanks for the report!
