### ISSUE TITLE
Incorrect documentation for mode='wrap' of `jax.scipy.ndimage.map_coordinates`.

### ISSUE THREAD

**Issue by alvarosg** [google/jax#20333]
### Description

The documentation of [jax.scipy.ndimage.map_coordinates](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.ndimage.map_coordinates.html) currently says:
>  Note that interpolation near boundaries differs from the scipy function, because we fixed an outstanding bug ([scipy/scipy#2640](https://github.com/scipy/scipy/issues/2640)); this function interprets the mode argument as documented by SciPy, but not as implemented by SciPy.

And also says:

> ’grid-wrap’ (a b c d | a b c d | a b c d)
The input is extended by wrapping around to the opposite edge.

> ’wrap’ (d b c d | a b c d | b c a b)
The input is extended by wrapping around to the opposite edge, but in a way such that the last point and initial point exactly overlap. In this case it is not well defined which sample will be chosen at the point of overlap.

However, empirically, it seems that the implementation of ’wrap’ in the jax version, actually corresponds to the implementation of  ’grid-wrap’ in the scipy version. Example:

```
import jax 
import numpy as np
import scipy

kwargs = dict(
    input=np.array([[1., 2., 3., 4., 5.]]),
    coordinates=np.array([
        [0, 0.5],
        [0, 1.5],
        [0, 2.5],
        [0, 3.5],
        [0, 4.5],  
        ]).T,
    order=1,   
)

print(scipy.ndimage.map_coordinates(**kwargs, mode="wrap"))  # [1.5 2.5 3.5 4.5 1.5]  # Vestigial, unintuitive scipy behavior.
print(jax.scipy.ndimage.map_coordinates(**kwargs, mode="wrap"))  # [1.5 2.5 3.5 4.5 3. ]  # Correct intuitive behavior.

print(scipy.ndimage.map_coordinates(**kwargs, mode="grid-wrap"))  # [1.5 2.5 3.5 4.5 3. ]  # Correct intuitive behavior.
print(jax.scipy.ndimage.map_coordinates(**kwargs, mode="grid-wrap"))  # Not implemented error.
```

Note JAX behavior of `mode="wrap"` is in my opinion the most intuitive one, so I am not advocating for any behavior change. However, the documentation of the scipy version was eventually changed, so this comment:

> Note that interpolation near boundaries differs from the scipy function, because we fixed an outstanding bug ([scipy/scipy#2640](https://github.com/scipy/scipy/issues/2640)); this function interprets the mode argument as documented by SciPy, but not as implemented by SciPy.

is no longer true, and in fact, now it is the jax version that has inconsistencies between the documentation and the implementation (`mode="wrap"` is documented as `mode="grid-wrap"`).

### System info (python version, jaxlib version, accelerator, etc.)

Version 0.4.26

**Comment by jakevdp** [comment]
Hi - sorry for the confusion. The docstring comes from scipy. so the clause that you quoted is meant to describe how the JAX function differs from the original function.

**Comment by rajasekharporeddy** [comment]
Hi @alvarosg 

Documentation of [`jax.scipy.ndimage.map_coordinates`](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.ndimage.map_coordinates.html) has been changed with the PR #21042. Now the documentation says that "`This function interprets the mode argument as documented by SciPy, but not as implemented by SciPy`".

Thank you.

**Comment by alvarosg** [comment]
Thanks for the update, however I don't think this is actually the correct fix to the documentation.

> Now the documentation says that "This function interprets the mode argument as documented by SciPy, but not as implemented by SciPy".

This sentence implies that SciPy documentation is not consistent with SciPy. However this is not true. In current SciPy documentation, documentation and implementation are totally consistent. The problem is that they way SciPy ended up fixing the bug to avoid backwards compatibility issues, is to, rather than change the behavior for `mode="wrap"`, to work as documented, they changed the documentation to actually document how `mode="wrap"` behave when it was buggy, and they added a new mode `mode="grid-wrap"`, to implement the behavior of how it should have worked.

So the correct way to document this in jax should be something like:

> Note `mode="wrap"` in `jax.scipy.ndimage.map_coordinates` behaves just as `mode="grid-wrap"` in `scipy.ndimage.map_coordinates`, (rather than `mode="wrap"`, due to a long-standing bug in `scipy`, that was first fixed in `jax`, and then it was later on fixed in `scipy`, but following a different approach.)

And then in the long term, and to avoid confusion and converge back to scipy, I think it make make sense to rename the `mode="wrap"` as `mode="grid-wrap"`, and either deprecate `mode="wrap"`, or implement it like in scipy.

**Comment by jakevdp** [comment]
> So the correct way to document this in jax should be something like: ...

Would you like to send a PR updating the documentation as you suggest?

**Comment by alvarosg** [comment]
Create the PR, but meant to leave this open (somehow github seems to have closed it when I merged into my own repo?)
