### ISSUE TITLE
has_aux optional parameter for jvp, jacfwd and jacrev

### ISSUE THREAD

**Issue by pierthodo** [google/jax#2035]
I am relying on the parameter has_aux to avoid recalculating the same function twice however it is not available for the function jvp, jacfwd, jacrev. Is there a technical reason for this that I would not be aware of ? If not I could look into making a pull request.

**Comment by RodrigoAVargasHdz** [comment]
Hi, did you manage to solve your problem? I'm curious cause I have the same issue. Thanks :)
