### ISSUE TITLE
Implementation of np.trapz

### ISSUE THREAD

**Issue by VanWieren** [google/jax#20410]
I would like to see the implementation of np.trapz  in jax.numpy, seems like a useful addition.

**Comment by njwfish** [comment]
I believe this is already essentially available with `jax.scipy.integrate.trapezoid`: https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.integrate.trapezoid.html

**Comment by jakevdp** [comment]
`jax.numpy.trapz` was [deprecated in JAX v0.4.16](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-16-sept-18-2023) following NumPy's deprecation of `numpy.trapz`. After the deprecation cycle, it was [removed in JAX v0.4.24](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-24-feb-6-2024). `jax.scipy.integrate.trapezoid` is a drop-in replacement.

**Comment by VanWieren** [comment]
It seems that `numpy.trapz` is not being deprecated anymore and simply being renamed under `numpy.trapezoid`. ([https://github.com/numpy/numpy/issues/25586](see this issue). I understand removing in JAX following numpy, however I still feel like having to rely on jax.scipy.integrate is more cumbersome than it should be for a simple function like jax.numpy.trapz

**Comment by jakevdp** [comment]
Thanks, I hadn't seen that. We can re-add this as `jax.numpy.trapezoid` for consistency with the NumPy API.

**Comment by jakevdp** [comment]
`jnp.trapezoid` added in #20524 – thanks!
