### ISSUE TITLE
`numpy.memmap.flush()` in `jax`

### ISSUE THREAD

**Issue by hjnnjh** [google/jax#20418]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

I'm implementing Stochastic Variational Inference algorithm of my model, during which, to avoid OOM, I try to use `jnp.load('*.npy', mmap_mode='r+')` load a huge batch parameter array from disk. However, when I attempt to do `flush()` on the loaded array I got `'ArrayImpl' object has no attribute 'flush'`.  Does `flush()` not be implemented in `jax`?

**Comment by hjnnjh** [comment]
I found that using `numpy.memmap` load parameters then convert it to `jax.Array` seems feasible and efficiently acceptable(My parameters are saved on a M.2 solid disk). After some update steps, I convert it back to `ndarray` and do `flush()`.

**Comment by hawkinsp** [comment]
Yes. Certainly on CPU JAX can exchange buffers with NumPy zero-copy, so you can save an array by calling `np.asarray` on it and then using NumPy's facilities to do it. `jnp.load` and `jnp.save` are thin wrappers around the NumPy features.

I'm not completely sure it makes sense for us to implement `flush` since our arrays are immutable.

**Comment by hjnnjh** [comment]
> Yes. Certainly on CPU JAX can exchange buffers with NumPy zero-copy, so you can save an array by calling `np.asarray` on it and then using NumPy's facilities to do it. `jnp.load` and `jnp.save` are thin wrappers around the NumPy features.
> 
> I'm not completely sure it makes sense for us to implement `flush` since our arrays are immutable.

Thanks for your reply. I mean is there some kind of `np.memmap` in `jax`?

**Comment by hjnnjh** [comment]
> > Yes. Certainly on CPU JAX can exchange buffers with NumPy zero-copy, so you can save an array by calling `np.asarray` on it and then using NumPy's facilities to do it. `jnp.load` and `jnp.save` are thin wrappers around the NumPy features.
> > I'm not completely sure it makes sense for us to implement `flush` since our arrays are immutable.
> 
> Thanks for your reply. I mean is there some kind of `np.memmap` in `jax`?

I just finished the SVI algorithm and ran some experiments, in which I found there is no need to implement the so-called `jnp.memmap` because using `np.asarray` to convert parameters and then update the corresponding `np.memmap` object is efficient enough. It can save a lot of GPU memory while completing each step very fast. I think I can close this issue. Thank you! @hawkinsp
