### ISSUE TITLE
vmap nested within pmap

### ISSUE THREAD

**Issue by HHalva** [google/jax#2041]
Am I right to assume that using vmap nested within pmap is all fine and safe to do? Say I have a function to do message-passing on a (1, T) long data array. I could then use vmap to do this simultaneously for N independent data-sequences, i.e. it allows us to operate on (N, T).  And finally if we were to reshape that to (device_count, -1, T) then in principle I should be able to have pmap on top of vmap. Just checking if there are any gotchas with this / more "correct" way of doing this.

**Comment by HHalva** [comment]
p.s. im asking this just in principle -- i realize in real application there will complications such as probably having to replicate parameters etc.

**Comment by shoyer** [comment]
Yes, that work.

If you just want this for simulating a larger batch size, you might also find the currently undocumented/experimental `jax.soft_pmap` transform useful for this. It basically exists to do exactly this, splitting a `vmap` across multiple devices.

**Comment by HHalva** [comment]
thanks - that's very cool!

**Comment by mattjj** [comment]
We hope to clean up and document `soft_pmap` in the next month or two. It works now, but I think we can make it cover more cases and simplify the implementation.

For now, though, I'll close this question. Please reopen if I'm mistaken, or open new ones for new questions!

**Comment by gerdm** [comment]
Hi @mattjj, @shoyer 
I have an embarrassingly parallel training loop that I'd like to pmap. Since the total number of trials I want to to run is greater than the number of devices, I was considering using `soft_pmap` as suggested in this issue, but I can't seem find any mention of it in the documentation.

Is `soft_pmap` still part of jax?
