### ISSUE TITLE
pmap of expm causes kernel to die if matrix dimension >= 100

### ISSUE THREAD

**Issue by DanPuzzuoli** [google/jax#20428]
### Description

Ran into this bug today in a Jupyter notebook. The following code causes the kernel to die without any errors being raised

```
# put number of cores here
num_cpu_cores = 2
import os
os.environ['XLA_FLAGS'] = f"--xla_force_host_platform_device_count={num_cpu_cores}"

# configure jax to use 64 bit mode
import jax
jax.config.update("jax_enable_x64", True)

# tell JAX we are using CPU
jax.config.update('jax_platform_name', 'cpu')

import jax.numpy as jnp
from jax.scipy.linalg import expm

from jax import pmap

x = jnp.eye(100)

pmap(expm)(jnp.array([x, x]))
```

However, if I change the dimension to `99`, e.g. `x = jnp.eye(99)`, the code runs without issue.

### System info (python version, jaxlib version, accelerator, etc.)

python: 3.12
jax: 0.4.25
jaxlib: 0.4.25
device: CPU
OS: MacOS

**Comment by selamw1** [comment]
Hi @DanPuzzuoli 
I successfully ran the provided code on Linux environments (Colab with JAX v0.4.23 and a virtual machine with JAX v0.4.25) with dimensions of 100 and even 1000. You can find the code for reference in the attached [Gist](https://colab.sandbox.google.com/gist/selamw1/63bf3a284b241c485b8ddf4a70831331/-20428.ipynb).

If the same code execution on macOS crashes the kernel without any error messages. Would it be possible to debug by using [jax.debug.print](https://jax.readthedocs.io/en/latest/debugging/print_breakpoint.html) within [jax.pmap](https://jax.readthedocs.io/en/latest/debugging/print_breakpoint.html#printing-under-jax-pmap)? This might provide more detailed error information to help us identify the issue.

**Comment by DanWaxman** [comment]
I was able to reproduce this on MacOS. It seems to be related to memory: running a script from the terminal results in a bus error, and sizes of 199 work but 200 dies when using 32-bit floating point numbers instead of 64-bit. Perhaps it could related to [this old thread](https://github.com/google/jax/issues/432#issuecomment-621917354), which found that MacOS-specific bus errors were because of default stack sizes in thread pools.

**Comment by hawkinsp** [comment]
Yes, you're right, this is an old issue reasserting itself. https://github.com/openxla/xla/pull/11066 fixes.

There also seems to be some sort of shutdown race happening in this test case, but everything works fine if you actually consume the output (e.g., via `block_until_ready`) before waiting for the process to shutdown. I may not have time to look into that part but it doesn't seem as critical.

**Comment by zifeitong** [comment]
The added test fails on my machine.


```
Program terminated with signal SIGSEGV, Segmentation fault.

#0  0x00000d03d835300e in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
[Current thread is 1 (Thread 0xd03b5a006c0 (LWP 3515632))]
(gdb) 
(gdb) bt
#0  0x00000d03d835300e in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#1  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#2  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#3  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#4  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#5  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#6  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#7  0x00000d03d835318f in sgetrf_parallel ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#8  0x00000d03d811d068 in sgetrf_ ()
   from /home/zifei/code/jax/.venv/lib/python3.11/site-packages/scipy/linalg/../../scipy.libs/libopenblasp-r0-24bff013.3.26.dev.so
#9  0x00000d04024deb99 in jax::Getrf<float>::Kernel(void*, void**, XlaCustomCallStatus_*) ()
   from /home/zifei/.cache/bazel/_bazel_zifei/885e10efb1640c3c785be14854b80785/execroot/__main__/bazel-out/k8-opt/bin/tests/pmap_test_cpu.runfiles/__main__/jaxlib/cpu/_lapack.so
#10 0x00000d03d5206422 in main ()
#11 0x00000d03de11dfdf in xla::TfrtCpuExecutable::ExecuteHelper(absl::lts_20230802::Span<xla::PjRtBuffer* const>, int, int, xla::RunId const&, xla::ExecuteOptions const&, tsl::AsyncValueRef<xla::runtime::CpuEvent>, bool, xla::TfrtCpuDevice*)::{lambda()#1}::operator()() ()
   from /home/zifei/.cache/bazel/_bazel_zifei/885e10efb1640c3c785be14854b80785/execroot/__main__/bazel-out/k8-opt/bin/tests/pmap_test_cpu.runfiles/__main__/jaxlib/xla_extension.so
```

I have to change the stack size here to 8mb in order to get the test pass:
https://github.com/openxla/xla/blob/91281d53c341529b1ee965edc5ee45b433053d04/xla/pjrt/cpu/cpu_client.cc#L370

The underlying issue seems to be a known problem for OpenBLAS: https://github.com/OpenMathLib/OpenBLAS/issues/3229
