### ISSUE TITLE
101/02-jitting doc has a long traceback and the traceback contains links to deleted code

### ISSUE THREAD

**Issue by yashk2810** [google/jax#20446]
https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html#why-can-t-we-just-jit-everything -- the traceback here should be filtered. Maybe it's just a matter of re-running the notebook?

**Comment by rajasekharporeddy** [comment]
Hi @mattjj

Can I raise PR for this by re-running the notebook?

**Comment by rajasekharporeddy** [comment]
Hi @mattjj 

Can I raise PR for this.

**Comment by jakevdp** [comment]
Just a note: this doc will very soon be removed in favor of https://github.com/google/jax/blob/main/docs/tutorials/jit-compilation.md

**Comment by rajasekharporeddy** [comment]
Hi @yashk2810 

Since the old tutorials were replaced with the new content with the PR #21064, I think this issue can be considered as resolved. Now the `Just-in-time compilation` doc displays only short tracebacks as expected.

Thank you.
