### ISSUE TITLE
'Can't lift Traced value' errors when nesting traces

### ISSUE THREAD

**Issue by MikeInnes** [google/jax#2048]
Reduced example:

```python
def D(f, x):
    return jax.jvp(f, (x,), (1.0,))[1]

def f(x):
    def inner(y):
        nonlocal x
        x = y
        return x
    return D(inner, x)*x

D(f, 1.0) # Exception: Can't lift Traced<ConcreteArray(1.0)>with<JVPTrace(level=4/0)> to JVPTrace(level=3/0)
```

Presumably related to JAX's mechanism for distinguishing between different traces when nesting. Seems like this could come up in a few different ways; I couldn't find any mention in the gotchas.

Related example:

```python
def test():
    x = 1
    def inner(y):
        nonlocal x
        x = x*y
        return x
    a = D(inner, 1.0)
    b = D(inner, 1.0)
    return b

test() # Exception: Different traces at same level: Traced<ConcreteArray(1.0, weak_type=True)>with<JVPTrace(level=4/0)>, JVPTrace(level=4/0)
```

**Comment by mattjj** [comment]
Thanks for the question, Mike!

The trouble here is there's a side-effect, namely where you write `x = y` for the nonlocal `x`. Side-effects void your JAX warranty (i.e. JAX transformations only work on pure functions), and this is exactly the error you see when your code has side effects.

So this is working as intended, insofar as JAX disallows side effects (and there are no plans to support general Python side effects, which we consider impossible without owning the Python language implementation).

WDYT?

**Comment by mattjj** [comment]
I think we can be clearer in the readme's gotcha section that JAX only works with pure functions (I wonder if it used to be clearer and the readme revision in December removed some key lines), and even point out that this is the kind of error you'd see if you have side effects in code you're trying to transform with JAX.

**Comment by mattjj** [comment]
I attempted to improve the language a bit in a61bcff. WDYT?

**Comment by MikeInnes** [comment]
Thanks a lot for the explanation! Yeah, that makes total sense to me, and I think the text you added to the gotchas is very helpful.

I think there's a slight subtlety here in that most (internal) side effects are actually OK as long as the function being traced is referentially transparent overall. If "function" is read as "the function object passed to JAX" then the text you added is completely clear on that, but if it's read as "each function definition involved" it might be taken in an overly-strict way. Just a thought; I'm personally quite happy to encourage people to use pure functions everywhere :)

If you wanted to be really precise I think you'd have to say something along the lines of "the set of functions that JAX traces must behave like a set of referentially transparent functions." I say "behaves like" because things like unnecessary `nonlocal`s will work, even if they violate referential transparency. (I just mention this as a curiosity, it's obviously not necessary to document at this level even if it's a reasonable statement.)

<details>

```python
def f1(x):
    def f2(y):
        nonlocal x
        x = 2*x
        return x*y
    return D(f2, x)

D(f1, 1.0) # => 2.0
```
</details>

Anyway, I think this issue is resolved; thanks a lot for addressing it.
