### ISSUE TITLE
Issue installing JAX with Nvidia GPU: CUDA backend failed to initialize: Unable to load cuDNN.

### ISSUE THREAD

**Issue by YudiXie** [google/jax#20519]
### Description

After installing JAX with Nvidia GPU using the recommended method [here](https://jax.readthedocs.io/en/latest/installation.html#pip-installation-gpu-cuda-installed-via-pip-easier), essentially running:

```
pip install --upgrade pip

# CUDA 12 installation
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda12_pip]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

doing something as simple as 
```
import jax.numpy as jnp
jnp.arange(-180, 180, 10, dtype=jnp.float32)
```

will trigger an error like this, although I have a GPU on my node.

```
CUDA backend failed to initialize: Unable to load cuDNN. Is it installed? (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

I was able to fix this problem by doing as suggested here:
https://github.com/google/jax/issues/18027#issuecomment-2028488429

Although I am not sure, but I think there might be a bug in detecting the correct version of cuDNN when installing JAX using the recommended method. 

### System info (python version, jaxlib version, accelerator, etc.)

Before the fix, here is the system info after jax installation
```
jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.26.4
python: 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='node100', release='4.18.0-372.9.1.el8.x86_64', version='#1 SMP Tue May 10 14:48:47 UTC 2022', machine='x86_64')


$ nvidia-smi
Mon Apr  1 12:44:54 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          On  |   00000000:83:00.0 Off |                    0 |
| N/A   36C    P0             56W /  300W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
```

**Comment by hawkinsp** [comment]
Yes, this is because CuDNN 9.0 was released and we didn't have a maximum version guard. We're making a new release soon that will fix the problem.

Closing as duplicate of #18027.

**Comment by tharun571** [comment]
"Unable to load cuDNN" errors with JAX often stem from library path issues rather than missing cuDNN.

Common cuDNN troubleshooting steps:
```bash
# Verify cuDNN is findable:
ldconfig -p | grep libcudnn
# Check LD_LIBRARY_PATH includes cuDNN location
echo $LD_LIBRARY_PATH
```

JAX cuDNN requirements:
- JAX expects cuDNN in standard system paths or LD_LIBRARY_PATH
- cuDNN version must match JAX build requirements (stricter than PyTorch)
- In containers, cuDNN paths often need explicit mounting/configuration
- LD_LIBRARY_PATH must be set before importing JAX

I built **[env-doctor](https://github.com/mitulgarg/env-doctor)** specifically to diagnose these cuDNN path issues:
- Validates cuDNN is in correct paths
- Checks JAX-specific CUDA/cuDNN requirements
- Tests library loading before JAX import
- Helps identify path configuration problems

Full disclosure: I'm the author. Sharing because "Unable to load cuDNN" is often a path issue, not a missing cuDNN issue. Hope it helps!
