### ISSUE TITLE
Please add upper bounds to dependencies for v0.4.23

### ISSUE THREAD

**Issue by jamesowers-cohere** [google/jax#20565]
### Description

Version 0.4.23 requires an old version of scipy (because a bunch of methods were removed in https://github.com/google/jax/pull/19001). However, this restriction is not specified this in the dependencies, i.e. [the line listing scipy in setup.py has no upper bound](https://github.com/google/jax/blob/1c68577dcdf70b4c0b42805d279b6a5c04d144fe/setup.py#L82)).

This means that people using jax as a dependency will get errors upon use unless they specify , e.g.

```shell
conda create --name test python=3.10.11 --yes
conda activate test
tag=jaxlib-v0.4.23
git clone --depth 1 --branch "${tag}" git@github.com:google/jax.git
cd jax
pip install '.[cpu]'
pip install jaxlib
pip list
# Package    Version
# ---------- --------------------------
# jax        0.4.23.dev20231214+1c68577
# jaxlib     0.4.23
# ml-dtypes  0.4.0
# numpy      1.26.4
# opt-einsum 3.3.0
# pip        24.0
# scipy      1.13.0
# setuptools 69.2.0
# wheel      0.43.0
python -c 'import jax._src.scipy.linalg'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../jax/jax/_src/scipy/linalg.py", line 403, in <module>
    @_wraps(scipy.linalg.tril)
AttributeError: module 'scipy.linalg' has no attribute 'tril'
```

# Proposed fix
Change:
https://github.com/google/jax/blob/1c68577dcdf70b4c0b42805d279b6a5c04d144fe/setup.py#L81-L82
to:
```python
        "scipy>=1.9,<1.13",
        "scipy>=1.11.1,<1.13; python_version>='3.12'",
```

### System info (python version, jaxlib version, accelerator, etc.)

`python -c 'import jax; jax.print_environment_info()'`:
```
jax:    0.4.23.dev20231214+1c68577
jaxlib: 0.4.23
numpy:  1.26.4
python: 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
```

**Comment by hawkinsp** [comment]
We don't retroactively fix old JAX releases. However, I think 0.4.25 should work, and we're about to release 0.4.26 soon which certainly will work.

**Comment by jamesowers-cohere** [comment]
Unfortunately I cannot upgrade the version of jax I'm using easily. I will therefore have to add this restriction to my dependencies.
