### ISSUE TITLE
Some usability problems for new users

### ISSUE THREAD

**Issue by skye** [google/jax#2057]
@Thenerdstation reports the following:

So, I have some usability responses from some post docs who are using JAX for the first time.

1. Every single person I've seen always get burned by slice updating. Things like A[0,0] = 1.0 are always issues they hit from porting their numpy code to jax.
2. When they first try to do anything complicated, it almost always is slower than the numpy version. They main issues are 1) They don't know about jit, so everything is running eagerly and is slow and 2), they almost always cast something in python space vs JAX space.
So for example they would do complex(device_array), which make their eager execution go back to python space and slow things way down

And then when they try wrapping everything in a jit, they hit the error 
```
TypeError: Abstract value passed to complex, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using jit, try using static_argnums or applying jit to smaller subfunctions instead.
```
Which just confuses they heck out of them.
I have no suggestions on how to fix it, just comments.
Although for the second issue, a more clear error message might be good, especially for functions that new users are likely to accidentally use, mainly complex, float, int, etc.

[I'm recording here in case there's anything we want to do to address these (new + improved error message?). We should close this if/when there's nothing concrete left to do.]

**Comment by mattjj** [comment]
Some TODOs we might extract here:
- [ ] have `__complex__` and similar methods suggest using `jax.numpy.complex` instead of the Python builtin `complex`
- [ ] raise an error from `ShapedArray.__setitem__` and `DeviceArray.__setitem__` suggesting the functional alternatives
- [ ] add a gotcha that JAX without `jit` can be slower than NumPy, especially on CPU (can't out-NumPy NumPy!),

**Comment by Thenerdstation** [comment]
First TODO should be done.

**Comment by jakevdp** [comment]
The first two TODOs have been addressed; e.g.

```python
In [2]: jit(complex)(1.0)
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(float64[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `complex` function. If trying to convert the data type of a value, try using `x.astype(complex)` or `jnp.array(x, complex)` instead.
While tracing the function <unknown> for jit, this concrete value was not available in Python because it depends on the value of the argument 'real'.
```

```python
In [3]: @jit 
   ...: def f(x): 
   ...:     x[0] = 1 
   ...:      
   ...: f(jnp.arange(5))   
TypeError: '<class 'jax.interpreters.partial_eval.DynamicJaxprTracer'>' object does not support item assignment.
JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html
```

**Comment by jakevdp** [comment]
For the third TODO, we have a relevant FAQ section now: https://jax.readthedocs.io/en/latest/faq.html#is-jax-faster-than-numpy
