### ISSUE TITLE
jax.scipy.special.beta results are different from scipy.special.beta for certain input

### ISSUE THREAD

**Issue by Mostafa86** [google/jax#20587]
### Description

When I use` jax.scipy.special.beta`, I get different results from the scipy one for some input as below:

```
b = 14.25
n = b - 1
k = jnp.arange(40)
plt.plot(k, scipy.special.beta(1 + n - k, 1 + k), label="scipy", ls=":")
plt.plot(k, jax.scipy.special.beta(1 + n - k, 1 + k), label="jax")
plt.plot(k, np.array([cephes4py.beta(1 + n - k, 1 + k) for k in np.arange(40)]), label="cephes", ls="-.")
plt.legend();
plt.show();
```
Here is the result:

![image](https://github.com/google/jax/assets/8914509/c0cfd3c2-1027-4d2e-b59e-412d90d44237)

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.26
jaxlib: 0.4.25
numpy:  1.26.4
python: 3.10.13
```

**Comment by jakevdp** [comment]
Thanks for the report! It looks like we weren't properly setting the sign of `beta` for negative inputs. #20589 should fix this.
