### ISSUE TITLE
Tracer's imag method returns float; crashes with the Array API

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#20624]
### Description
The following:
```python
import jax.numpy as jnp
from jax.lax import while_loop
from array_api_compat import get_namespace

def body(x):
    assert False

def cond(x):
    # x is a tracer, x.real is a tracer, x.imag is a float!
    xp = get_namespace(x)
    xp.square(x.imag)  # No problem with x.real!

while_loop(cond, body, jnp.asarray(0.0))
```
crashes with:
```
ValueError: square: inputs must be arrays; got types [<class 'float'>]
```

Also broken:
```python
import jax.numpy as jnp
from jax.lax import while_loop

def body(x):
    assert False

def cond(x):
    x.imag.shape  # Crash!

while_loop(cond, body, jnp.asarray(0.0))
```
According to the Array API spec, `x.imag` must be a _Jax array_ (not a NumPy array, nor a float).

### System info (python version, jaxlib version, accelerator, etc.)

An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.11.8 (main, Feb 22 2024, 17:25:49) [GCC 11.4.0]

**Comment by NeilGirdhar** [comment]
@jakevdp (This breaks Array API usage)

**Comment by jakevdp** [comment]
Thanks - it seems that the validation for array API inputs is too strict: we should probably allow Python scalars here: https://github.com/google/jax/blob/1d26365e601528d4cb63ca9d39213248eb320adb/jax/experimental/array_api/_elementwise_functions.py#L25-L26

**Comment by NeilGirdhar** [comment]
> Thanks - it seems that the validation for array API inputs is too strict: we should probably allow Python scalars here:

Hmm, are you sure that's enough?   If you allow scalars, it means that client code has to handle scalars, which often means wrapping return values in `jnp.asarray`.  Also, the [Array API spec](https://data-apis.org/array-api/latest/API_specification/generated/array_api.imag.html) says that `imag` returns an "array".  Doesn't that mean that the return value should be a `jax.Array`?

**Comment by jakevdp** [comment]
In general JAX code uses scalars and arrays interchangeably: for example, in jaxprs, compile-time constants are represented by scalars, not by JAX arrays. I suspect it would be very intrusive to try to change this.

Another aspect of this change: evenutally, when `jax.numpy` itself subsumes `jax.experimental.array_api`, the functions will accept scalar arguments, so this change makes the current temporary namespace more inline with how it will look in the future.

**Comment by NeilGirdhar** [comment]
> In general JAX code uses scalars and arrays interchangeably: for example, in jaxprs, compile-time constants are represented by scalars, not by JAX arrays. I suspect it would be very intrusive to try to change this.

I understand that, but I think we're talking about different things.

Whether the library _accepts_ scalars in place of arrays is up to you.  That's not the issue.

The issue is what the Jax library _returns_.  As a user, I think we should be able to count on the return value being an array because that's what the spec promises.  Otherwise, Array API compliant code will not run with Jax.

**Comment by jakevdp** [comment]
> The issue is what the Jax library returns

Understood: within traced code, `tracer.imag` returns a float `0.0` for a real-valued tracer, representing the fact that it's a constant that does not depend on any input value. Changing this will be a very intrusive change, and not easy to do.

**Comment by jakevdp** [comment]
This is a bit of a tricky area: note that `x.imag` will always return an array if the input is an array (rather than something derived from a Python scalar).
```
In [2]: def f(x):
   ...:     print(type(x.imag))
   ...:     return x
   ...: 

In [3]: f(1.0)
<class 'float'>
Out[3]: 1.0

In [4]: jax.jit(f)(1.0)
<class 'float'>
Out[4]: Array(1., dtype=float32, weak_type=True)

In [5]: f(jnp.arange(4))
<class 'jaxlib.xla_extension.ArrayImpl'>
Out[5]: Array([0, 1, 2, 3], dtype=int32)

In [6]: jax.jit(f)(jnp.arange(4))
<class 'jax._src.interpreters.partial_eval.DynamicJaxprTracer'>
Out[6]: Array([0, 1, 2, 3], dtype=int32)
```
`jnp.array(0.0)` is kind of a strange thing: it's essentially JAX's representation of a float scalar, which lets us trace functions with scalar arguments so that they'll have the same semantics as a non-traced version of the function. This does lead to weird corner cases, but my experience is that changing those corner cases often leads to other, deeper errors.

**Comment by NeilGirdhar** [comment]
> Changing this will be a very intrusive change, and may not be easy to do.

Okay, glad we're on the same page :smile:   It's unfortunate that's a difficult change, but I guess it has to do with declaring that the value is constant?

Regarding your last comment, yeah I was just trying various things like that.  I understand your point.  From the outside, it is a bit odd that scalar arrays are so fundamentally different from non-scalar arrays.

Would it be possible to use `np.empty((), dtype=float0` in place of 0.0?  Perhaps this can be solved in tandem with https://github.com/google/jax/issues/20620?

**Comment by jakevdp** [comment]
`float0` is an autodiff thing; this is unrelated.

**Comment by jakevdp** [comment]
Strangely enough, all of this scalar array weirdness comes from the fact that we want `x + 1` to have the same dtype as `x`. It's hard to change these things without affecting those promotion semantics.

**Comment by NeilGirdhar** [comment]
Okay, I thought it was just a way to represent a constant zero, which seems to be the motivation for using 0.0 instead of `jnp.zeros(())` ?  Thanks for correcting me.

**Comment by jakevdp** [comment]
> Okay, I thought it was just a way to represent a constant zero,

`float0` is the sole element of a zero-dimensional vector space. Constant zero is a particular value within a 1-dimensional vector space.

**Comment by NeilGirdhar** [comment]
So `float0` arrays should always have shape ()?  If that's the case, I've been using it completely wrong.

**Comment by jakevdp** [comment]
No, `float0` can have arbitrary shape. Each element in a `float0` array represents the sole elements in a zero-dimensional vector space.

**Comment by jakevdp** [comment]
Reopening, we fixed the initial issue, but we need to think about the fact that `jax.jit(lambda x: x.imag.shape)(1.0)` fails for weakly-typed scalar inputs. It's a strange corner case...
