### ISSUE TITLE
jit compiled closures in fori loop

### ISSUE THREAD

**Issue by kovasb** [google/jax#207]
Hi,

This might be misunderstanding, but the following errors:

```
def iterate(f, init_row, steps):
  def body_fun(step, result):
    return f(result)
  return lax.fori_loop(0, steps, body_fun, init_row)

def test_get(a,b): return iterate(lambda x: x[a], b, 10)
test_get_jit = jit(test_get)
test_get_jit(np.array([0,1,2,3]), np.array([0,1,2,3]))
```

```
/usr/local/lib/python3.6/dist-packages/jax/lib/xla_bridge.py in Constant(self, py_val)
    319       return _constant_handlers[py_type](self, py_val)
    320     else:
--> 321       raise TypeError("No constant handler for type: {}".format(py_type))
    322 
    323 

TypeError: No constant handler for type: <class 'jax.interpreters.partial_eval.JaxprTracer'>
```

**Comment by kovasb** [comment]
Got it! Thanks a lot.

**Comment by kovasb** [comment]
Reopening this since I now understand it was meant to be tracked for future improvement.

**Comment by mattjj** [comment]
We're on it!

**Comment by jonasrauber** [comment]
I am facing a similar problem. What's the recommended workaround for the above example?

**Comment by mattjj** [comment]
Instead of closing over values, you need to add them as formal parameters to `body_fun` and `cond_fun` and thread them through the loop carry. In other words, `init_fun` and `body_fun` shouldn't close over anything that could be traced.

**Comment by dougalm** [comment]
Just merged #334 which should closed-over tracers in the cond/body functions of `_while_loop` and `fori_loop`. It's only lightly tested so let us know if it works!

**Comment by kovasb** [comment]
Thanks for fixing this!

I would like to try this out. I'm working in Colab. Is there an easy way to install the master branch? 

Related: how often are new releases pushed to pypi? (is there a nightly??)

**Comment by mattjj** [comment]
We’ve just been updating pypi manually. The last update was yesterday I think. Doing a `pip install —upgrade jax` will do it. (The jaxlib code is just for updating XLA, which we do less frequently.)

I’m not sure if you can point pip to a git repo, but that would be useful.

**Comment by jekbradbury** [comment]
Yes, `pip install git+https://github.com/google/jax` should work for that.
