### ISSUE TITLE
JIT does not optimize multiplication and division by the same number

### ISSUE THREAD

**Issue by romanngg** [google/jax#2071]
Not sure if this is realistic, but it would be nice to not have to worry about some simple cancellations in the expression that I'm computing. E.g. for the following identity function
```
import jax.numpy as np
from jax.api import jit

def f(x):
  a = np.e
  b = np.pi
  c = 2.

  for i in range(10):
    x *= a
    x *= b
    x *= c

  for i in range(10):
    x /= c
    x /= b
    x /= a
  return x
```
I get
```
f(1) == 1.0000000000000002  # This is OK since no optimization
```
and
```
jit(f)(1) == DeviceArray(0.999999, dtype=float32)
```
Further, the jitted call is slower than just an identity call, e.g 
```
from jax import random as random
matrix = random.normal(random.PRNGKey(1), (10000, 1000))

def id(x):
  return x

id_jit = jit(id)
```
Gives timings of 50 and 227 µs for 
```
%timeit id_jit(matrix).block_until_ready()
%timeit f_jit(matrix).block_until_ready()
```
Is this and similar kind of situations something that could be canceled-out during the jit-compilation? Thanks!

**Comment by shoyer** [comment]
`x/x == 1` is mostly true, but fails for a few pathological inputs, e.g., zero, NaN and infinity. So I'm not sure it's really safe to rely upon...

**Comment by romanngg** [comment]
I see, but perhaps these values could be filtered out? Also, here's an example that should arguably return the original value regardless of the value of `b`, including NaNs etc. (currently it does not)

```
import jax.numpy as np
from jax.api import jit

def f(x):
  b = np.pi

  for i in range(10):
    x *= b

  for i in range(10):
    x /= b
  return x
```

Relatedly to this, is there a simple summary of what optimization `jit` / XLA does so that I could decide what to optimize manually and what to leave for the compiler?

**Comment by hawkinsp** [comment]
I observe that even for the example you give classic NumPy doesn't have that property: the property you want isn't true of floating point math, independent of any optimizations. So requiring JAX to do guarantee it seems unreasonable; if nothing else a mode without optimization should presumably produce a similar result.

```
In [1]: import numpy as np

In [2]: def f(x):
   ...:   b = np.pi
   ...:
   ...:   for i in range(10):
   ...:     x *= b
   ...:
   ...:   for i in range(10):
   ...:     x /= b
   ...:   return x
   ...:

In [3]: f(1.0)
Out[3]: 0.9999999999999999
```

There's no simple summary of what optimizations XLA does. There's a pretty complicated stack of software in between you and the hardware (e.g., XLA and LLVM).

It's possible that XLA *may* optimize `(x * b) / b` to `x` but it isn't completely sound by the strictest rules of floating point arithmetic. Most of XLA's optimizations of this kind are in:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/algebraic_simplifier.cc
but that doesn't, for example, include the many LLVM optimizations that happen later. If a particular optimization is important to you we could propose it to the XLA team.

Does that help?

**Comment by hawkinsp** [comment]
Closing because there's no action for us to take here.
