### ISSUE TITLE
JAX + third party library can't find GPU in oss colab.

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#2074]
Consider a library (e.g. jax-md or neural tangents) - that is installed via pip and depends on JAX - being run in OSS colab. If one runs the magic,
```
!pip install -q git+https://www.github.com/google/neural-tangents
```
before importing JAX, then JAX is unable to find the GPU. However, if one first imports JAX and then runs the magic then JAX can find the GPU. For example, the following 
```
import jax.numpy as np
!pip install -q git+https://www.github.com/google/neural-tangents
```
is able to find the GPU. Is it possible that default JAX installation is being overwritten with one that doesn't have GPU support?

To reproduce, run the first two cells in this notebook:
https://colab.research.google.com/github/google/jax-md/blob/master/notebooks/minimization.ipynb
Then restart the kernel and add `import jax.numpy as np` into a cell at the top and re-run. 

You should see no GPU in the first case and JAX should be able to find GPU in the second.

**Comment by romanngg** [comment]
(This turned out to be exactly the case since Colab had [GPU] jaxlib 0.1.36 installed and our libraries required jaxlib 0.1.37 which was installed with pip over the GPU version.)
