### ISSUE TITLE
Implement NaN aggregation functions from NumPy

### ISSUE THREAD

**Issue by shoyer** [google/jax#2077]
Extracted from #70:

 - [x] np.nansum
 - [x] np.nanprod
 - [x] np.nancumsum
 - [x] np.nancumprod
 - [x] np.nanmean
 - [x] np.nanmedian
 - [x] np.nanpercentile
 - [x] np.nanquantile
 - [x] np.nanvar
 - [x] np.nanstd
 - [x] np.nanargmin
 - [x] np.nanargmax
 - [x] np.nanmin
 - [x] np.nanmax

**Comment by StephenHogg** [comment]
`nanmean` looks like it is already done: https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L1498

**Comment by hawkinsp** [comment]
@StephenHogg Thanks, I marked `nanmean` as done.

**Comment by StephenHogg** [comment]
Hi again, I'm thinking of seeing how many of the remaining ones on the list I can knock off. I've got `nanargmin` and `nanargmax` done, but for `nanmedian` and similar it looks like I need a reducer. Is there anything that works in a similar way to the one used in numpy (located below) that you could point me towards?:

https://github.com/numpy/numpy/blob/dae4f67c797176c66281101be8f3b4d6c424735c/numpy/lib/function_base.py#L3333

I've had a bit of a dig through the code base but am not as confident as I'd like to be that I'm looking at the right thing for the job. Hope this isn't a bother.

**Comment by shoyer** [comment]
I don't think we have any direct equivalent of that utility function. I would guess nanmedian could be implemented in a similar way to median (i.e., in terms of lax.sort).

**Comment by djdongjin** [comment]
I will take `np.nanvar` and  `np.nanstd`.

**Comment by hawkinsp** [comment]
It looks like someone actually tried that out: https://github.com/google/jax/pull/2310
but we dropped the ball on reviewing it.

**Comment by djdongjin** [comment]
oh, I just found the pr. seems all functions in this issue have been added or PRed :). I can go to find some other issues.

**Comment by hawkinsp** [comment]
These are now all implemented.
