### ISSUE TITLE
Implement NumPy set routines

### ISSUE THREAD

**Issue by shoyer** [google/jax#2078]
Extracted from #70:

 - [x] np.unique
 - [x] np.ediff1d
 - [x] np.in1d
 - [x] np.intersect1d
 - [x] np.isin
 - [x] np.setdiff1d
 - [x] np.setxor1d
 - [x] np.union1d

Implementation wise, we could use either sorting (like NumPy) or hash-tables (of some sort) for most of these fucntions.

Some of these could be challenging to implement (would not work under `jit`), because the output has a dynamic shape. `in1d` and `isin` don't have dynamic shapes, but that they probably require `searchsorted` from https://github.com/google/jax/issues/2080 first (at least if using sorting).

**Comment by jakevdp** [comment]
#5665 finishes this work!
