### ISSUE TITLE
Implement NumPy search routines

### ISSUE THREAD

**Issue by shoyer** [google/jax#2080]
xref https://docs.scipy.org/doc/numpy/reference/routines.sort.html

Extracted from #70:

 - [x] np.argmax
 - [x] np.argmin
 - [x] np.argwhere
 - [x] np.compress
 - [x] np.nonzero
 - [x] np.flatnonzero
 - [x] np.where
 - [x] np.searchsorted
 - [x] np.extract

(see https://github.com/google/jax/issues/2077 for nanargmax/nanargmin)

Notes:
- argwhere/flatnonzero/extractcould should just be minimal wrappers around nonzero
- searchsorted is harder: it need would need low-level routines/wrappers for efficient binary search, which to my knowledge do not currently existing in XLA

**Comment by djdongjin** [comment]
@shoyer  I'd like to work on the last `searchsorted`. Where and how should I implement the efficient binary search you mentioned? Should I implement it in tensorflow.xla first and wrap it in Jax when it is merged into tensorflow?

And a more general question, if we want to add some functions using ops that don't exist in XLA (like here), how should we do? Can we implement the ops directly in python, or we need to implement it in XLA first?

**Comment by terhorst** [comment]
If your data don't have ties, then the following should work:
```
def hacky_argsorted(a, v):
    i = np.argsort(np.concatenate([a, v]))
    ranks = i.argsort()
    return np.concatenate([
        np.ones(a.shape, dtype=int), 
        np.zeros(v.shape, dtype=int)
    ])[i].cumsum()[ranks[len(a):]]
```

**Comment by hawkinsp** [comment]
#2938 implemented `searchsorted`.
