### ISSUE TITLE
Cannot lower pallas kernels to TPU due to missing absl-py dependence

### ISSUE THREAD

**Issue by justinjfu** [google/jax#20908]
### Description

Pallas kernels fail to lower to TPU without installing the `absl-py` library separately.

Code to reproduce (this is an example taken from the Pallas documentation):
```
import jax
import jax.numpy as jnp
from jax.experimental import pallas as pl

def add_kernel(x_ref, y_ref, o_ref):
  # In this code, `x_ref`, `y_ref` and `o_ref` are (8,)-shaped `Ref`s
  x = x_ref[:]
  y = y_ref[:]
  o_ref[:] = x + y
x, y = jnp.arange(8), jnp.arange(8, 16)
add = pl.pallas_call(add_kernel, out_shape=jax.ShapeDtypeStruct((8,), jnp.int32))
add(x, y)
```

Initial error from running this code:
```
Traceback (most recent call last):
  File "/home/justinfu/code/tmp/test_kernel.py", line 9, in <module>
    pl.pallas_call(kernel, out_shape=x)(x)
  File "/home/justinfu/code/venvs/3_12_fresh/lib/python3.12/site-packages/jax/_src/pallas/pallas_call.py", line 544, in _pallas_call_lowering
    raise _unsupported_lowering_error(platform)
ValueError: Cannot lower pallas_call on platform: tpu. To use Pallas on GPU, install jaxlib GPU 0.4.24 or newer. To use Pallas on TPU, install jaxlib TPU and libtpu. See https://jax.readthedocs.io/en/latest/installation.html.
```

Upon further inspection, it seems like this is due to a failure to import `absl` inside of `tpu_custom_call.py`. If we raise the [ImportError](https://github.com/google/jax/blob/8239674dabdcaaf2ba7146e60e68af4d8128d7ce/jax/_src/pallas/pallas_call.py#L537) causing this message, we see the following:
```
File "/home/justinfu/code/jax/jax/_src/pallas/pallas_call.py", line 538, in _pallas_call_lowering
    raise err
  File "/home/justinfu/code/jax/jax/_src/pallas/pallas_call.py", line 536, in _pallas_call_lowering
    from jax._src.pallas.mosaic import pallas_call_registration  # type: ignore
    ^^^^^^^^^
  File "/home/justinfu/code/jax/jax/_src/pallas/mosaic/__init__.py", line 25, in <module>
    from jax._src.pallas.mosaic.lowering import LoweringException
  File "/home/justinfu/code/jax/jax/_src/pallas/mosaic/lowering.py", line 58, in <module>
    from jax.experimental.mosaic.dialects import tpu
  File "/home/justinfu/code/jax/jax/experimental/mosaic/__init__.py", line 17, in <module>
    from jax._src.tpu_custom_call import as_tpu_kernel
  File "/home/justinfu/code/jax/jax/_src/tpu_custom_call.py", line 29, in <module>
    from absl import flags
ModuleNotFoundError: No module named 'absl'
```

After running `pip install absl-py`, the script runs successfully.

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.12.3 (main, Apr 23 2024, 23:22:24) [GCC 9.3.0]
jax.devices (8 total, 8 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1) ... TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0) TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
process_count: 1
platform: uname_result(system='Linux', node='t1v-n-baa5bf8c-w-0', release='5.4.0-1043-gcp', version='#46-Ubuntu SMP Mon Apr 19 19:17:04 UTC 2021', machine='x86_64')

**Comment by superbobry** [comment]
Do you want to have a go at the fix @justinjfu? :)

**Comment by justinjfu** [comment]
Fixed (https://github.com/google/jax/pull/20945)
