### ISSUE TITLE
Autodiff Cookbook Docs Out of Sync

### ISSUE THREAD

**Issue by cleichner** [google/jax#2092]
In second-to last part of the section [Jacobians and Hessians using jacfwd and jacrev](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Jacobians-and-Hessians-using-jacfwd-and-jacrev), the readthedocs markdown is not rendering correctly, namely there is a list that is being rendered inline like:

"This shape makes sense: if we start with a function f:Rn→Rm, then at a point x∈Rn we expect to get the shapes * f(x)∈Rm, the value of f at x, * ∂f(x)∈Rm×n, the Jacobian matrix at x, * ∂2f(x)∈Rm×n×n, the Hessian at x,

and so on."

In the checked in ipython notebook, [this same section](https://github.com/google/jax/blob/master/docs/notebooks/autodiff_cookbook.ipynb) is rendered correctly as:
"
This shape makes sense: if we start with a function $f : \mathbb{R}^n \to \mathbb{R}^m$, then at a point $x \in \mathbb{R}^n$ we expect to get the shapes

$f(x) \in \mathbb{R}^m$, the value of $f$ at $x$,
$\partial f(x) \in \mathbb{R}^{m \times n}$, the Jacobian matrix at $x$,
$\partial^2 f(x) \in \mathbb{R}^{m \times n \times n}$, the Hessian at $x$,
and so on.
"

I don't know if readthedocs uses a different markdown parser than ipython or if this is just a case of out of date docs, but figured it would be useful to flag.

**Comment by gnecula** [comment]
It was a missing blank line.  Should be fixed.

**Comment by cleichner** [comment]
Thanks for taking a look!
