### ISSUE TITLE
psum_scatter does not allow scatter_dimension to be negative

### ISSUE THREAD

**Issue by jewillco** [google/jax#21015]
### Description

In `jax.lax.psum_scatter`, I tried to use -1 as `scatter_dimension` to indicate that the last dimension should be used. However, this triggers an error: `expects scatter_dimension &gt;= 0`. Negative indices are normally supported for axes in JAX and Python in general.

### System info (python version, jaxlib version, accelerator, etc.)

N/A

**Comment by rajasekharporeddy** [comment]
Hi @jewillco 

Thanks for reporting. There's a related issue reported under #20125  that's still open. It might be helpful to reference it.

**Comment by jewillco** [comment]
Duplicate of #20125

**Comment by jewillco** [comment]
Duplicate of #20125
