### ISSUE TITLE
jax.random seems to have unnecessary buffer allocations on stack

### ISSUE THREAD

**Issue by py4** [google/jax#21045]
### Description

The following simple code is supposed to allocate ~4GB of random array in BF16.

```
import jax
import jax.numpy as jnp


if __name__ == "__main__":
    key = jax.random.key(0)

    jax.profiler.start_trace("/tmp/profile/tmp")
    arr = jax.random.uniform(key, (524288, 4096), dtype=jnp.bfloat16, minval=-1, maxval=1)
    arr.block_until_ready()

    jax.profiler.stop_trace()
```

In the profile, I see to things:

1. First a `u32[524288,4096]{0,1:T(8,128)}` buffer is allocated through broadcast (~8GB)
2. Then it's reshaped to `u32[524288,4096]{0,1:T(8,128)}` but still has resulted in an additional copy (~8GB)
3. Then it's copied to `bf16[524288,4096]{1,0:T(8,128)(2,1)}`

So I have two questions:
1. Isn't it possible to directly allocate 4GB in HBM and then initialize it? What's the usage of the stack allocations?
2. If not possible, why the reshape has resulted in an additional copy. That seems complete unnecessary to me. 

![image](https://github.com/google/jax/assets/747819/94aaa369-ac62-47b9-86f9-c30e0be10f90)

![image](https://github.com/google/jax/assets/747819/98591134-c6e0-4761-a3e6-353cf4be11ff)

Overall, I feel ~20GB allocation for having a 4GB buffer seems a lot of overhead to me.

### System info (python version, jaxlib version, accelerator, etc.)

```
TPU V4-8
jax:    0.4.26
jaxlib: 0.4.26
numpy:  1.26.4
python: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
jax.devices (4 total, 4 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(1,0,0), core_on_chip=0) TpuDevice(id=2, process_index=0, coords=(0,1,0), core_on_chip=0) TpuDevice(id=3, process_index=0, coords=(1,1,0), core_on_chip=0)]
process_count: 1
platform: uname_result(system='Linux', node='t1v-n-0549b5be-w-0', release='5.13.0-1023-gcp', version='#28~20.04.1-Ubuntu SMP Wed Mar 30 03:51:07 UTC 2022', machine='x86_64')
```

**Comment by jakevdp** [comment]
Have you tried it under `jit`?

**Comment by py4** [comment]
@jakevdp yeah same result:

```
import jax
import jax.numpy as jnp

@jax.jit
def get_random_array(key):
    return jax.random.uniform(key, (524288, 4096), dtype=jnp.bfloat16, minval=-1, maxval=1)

if __name__ == "__main__":
    key = jax.random.key(0)
    jax.profiler.start_trace("/tmp/profile/moe/tmp")
    arr = get_random_array(key)
    arr.block_until_ready()
    jax.profiler.stop_trace()
```

![image](https://github.com/google/jax/assets/747819/d7e34175-2348-4c46-b20e-ad2bf120c1aa)

**Comment by froystig** [comment]
What RNG implementation are you using? If it's the default (threefry), have you tried using it in "partitionable" mode? You can do that by adding the line:
```python
jax.config.update('jax_threefry_partitionable', True)
```
at the top of your file.

https://github.com/google/jax/discussions/18480 has more details (and other ways to set the option).

I ask because partitionable Threefry mode often involves fewer reshapes and stacking.

**Comment by py4** [comment]
@froystig the original issue is resolved, however FYI, the context manager seems not to be working (the memory issue apears with context manager, but not with `jax.config.update('jax_threefry_partitionable', True)` at top:

```
import jax
import jax.numpy as jnp

@jax.jit
def get_random_array(key):
    with jax.threefry_partitionable(True):
        return jax.random.uniform(key, (524288, 4096), dtype=jnp.bfloat16, minval=-1, maxval=1)

if __name__ == "__main__":
    key = jax.random.key(0)
    jax.profiler.start_trace("/tmp/profile/moe/tmp")
    arr = get_random_array(key)
    arr.block_until_ready()
    jax.profiler.stop_trace()
```

**Comment by froystig** [comment]
Thanks! Minimized and filed as #21061.
