### ISSUE TITLE
Better support for handling block diagonal matrices

### ISSUE THREAD

**Issue by martiningram** [google/jax#2104]
Dear JAX team,

Thanks for the amazing work with JAX!

I'm currently doing some work which would really benefit from support for handling block diagonal matrices. In particular, I would like to assemble matrices using something like `scipy.linalg.block_diag` (https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.block_diag.html). It would also be nice to be able to split them again, but that's a bit awkward in numpy too and I think could be done using slicing. I've been able to work around this for now using kronecker products, but it's not very neat.

Would this be hard to add? Could give it a go too if it's not too hard and there's a rough plan (maybe scatter would be one way to go?).

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/2106 adds an implementation of `np.block`, which might help with assembling block matrices.

**Comment by shoyer** [comment]
How large are your blocks?

To me, this looks like something that might be better solved by a `LinearOperator` object that supports (at least) matrix-vector multiplication, e.g., https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorBlockDiag

**Comment by martiningram** [comment]
Thanks both of you! 

@hawkinsp I think np.block will do the trick! It doesn't look quite as nice as block_diag because you have to explicitly create the zero parts, but that's not a big deal. Happy to have the issue closed!

@shoyer The blocks are currently really small, definitely under 10x10. For larger ones I agree, the linear operator approach should be much more efficient. Are there any plans to implement them in JAX?

**Comment by shoyer** [comment]
> Are there any plans to implement them in JAX?

Not that I know of, currently
