### ISSUE TITLE
Remaining API changes for array API compliance

### ISSUE THREAD

**Issue by Micky774** [google/jax#21088]
This issue tracks the deprecations that must still be started to ensure that the `jax.numpy` namespace is array API compliant. This covers some issues remaining which are not explicitly tracked in https://github.com/google/jax/issues/18353, with some overlap between both. 

## Core
- [x] https://github.com/google/jax/pull/21130
- [x] Add `device` kwarg
    - `jnp.arange`
    - `jnp.array`
    - `jnp.eye`
    - `jnp.linspace`
- [x] Wait on final decision on https://github.com/data-apis/array-api/issues/405
- [ ] Preserve integral `dtype`
    - `jnp.ceil`
    - `jnp.floor`
    - `jnp.trunc`
- [x] https://github.com/google/jax/pull/21262
    - `jnp.std`
    - `jnp.var`

## Compliance Finalization
- [ ] https://github.com/google/jax/pull/21323
    - Add `__array_namespace__` to `ArrayImpl`
    - Add `to_device` to `ArrayImpl`
    - Add `device` to `ArrayImpl`
    - Add `__array_namespace_info__` to `jax.numpy`
    - Add `__array_api_version__` version information

## FFT
- [x] Add `device` kwarg #22734
    - `jnp.fft.fftfreq`
    - `jnp.fft.rfftfreq` 

## Linalg
- [x] https://github.com/google/jax/pull/21442
- [x] https://github.com/google/jax/pull/21226
    - `jnp.linalg.matrix_rank`: Change `tol` arg to `rtol`
    - `jnp.linalg.pinv`: Change `rcond` arg to `rtol`

**Comment by vfdev-5** [comment]
Task 
> Add info namespace containing the same functions as https://github.com/google/jax/pull/20294

Nothing to be done in jax as array-api-tests should be fixed: https://github.com/google/jax/pull/21506

**Comment by jakevdp** [comment]
Closed by #22818
