### ISSUE TITLE
Checking if an object is an array

### ISSUE THREAD

**Issue by Jakob-Unfried** [google/jax#2115]
Is there a best practice to verify that an object is an array, e.g. during input checks?
Comparing types seems unfeasable, since the function will be be called with abstract array types during tracing.

Essentially i want to do something like
```python
import jax.numpy as np

def is_array(obj):
   return type(obj) == np.ndarray
```
But also consider all jax types that might occur during tracing.

If it doesn't already exist, such an `is_array` function would be nice to have, especially if the abstract types used during racing should change in the future

**Comment by jekbradbury** [comment]
I think `isinstance(x, jax.numpy.ndarray)` does what you want (it'll return True for JAX arrays, including abstract ones, as well as NumPy ndarrays and subtypes of ndarrays)

**Comment by mattjj** [comment]
@jekbradbury 's answer is the right one; though we might revise it (see #2014) right now you should check `isinstance(x, jax.numpy.ndarray)`.

Hope that answers your question!
