### ISSUE TITLE
Saving arrays or pytrees to file

### ISSUE THREAD

**Issue by Jakob-Unfried** [google/jax#2116]
Does Jax already have functionality to store (and read) arrays or pytrees of arrays to file?
- If yes: I did not find any documentation for this
- If no: I want to request this feature. 
   essentially i would want function `def save(file, *args, **kwargs):` and `def load(file)`
   They could behave like `onp.savez` ([numpy doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.savez.html)) and `onp.load` ([numpy doc](https://docs.scipy.org/doc/numpy/reference/generated/numpy.load.html?highlight=load#numpy.load))

**Comment by j-towns** [comment]
I'm pretty sure you can just use [`pickle`](https://docs.python.org/3/library/pickle.html), not sure if this needs to be documented since it's just a standard Python interface, but maybe it would be helpful.

**Comment by Jakob-Unfried** [comment]
@j-towns 

You are right, `pickle` does the job!
Thank you, i didn't even think to just try it out.

So, IMO there is no need for any further functionality, but it might be nice to add documentation somewhere

Minimal example:

```python
import pickle
import jax.numpy as np
from jax.tree_util import tree_multimap, tree_flatten

x = np.array([1, 2, 3])
y = np.array([[1, 1], [2, 2.]])
z = np.array([1.j, 2.j, 3.])

example_pytree = ([[x, y], (z, 7)])

path = '/Users/jakobunfried/Desktop/testing/test.pickle'

with open(path, 'wb') as file:
    pickle.dump(example_pytree, file)

print('Done saving')

with open(path, 'rb') as file:
    data = pickle.load(file)


def pytree_compare(tree1, tree2):
    structure_equal = tree_flatten(tree1)[1] == tree_flatten(tree2)[1]
    entries_equal = np.all(tree_flatten(tree_multimap(np.array_equal, tree1, tree2))[0])
    return structure_equal and entries_equal


assert pytree_compare(data, example_pytree)

print('All went well')

```

**Comment by Jakob-Unfried** [comment]
I ended up writing this utility file for myself, should it be of interest to anyone:

```python
from jax.tree_util import pytree
import pickle
from pathlib import Path
from typing import Union

suffix = '.pickle'


def save(data: pytree, path: Union[str, Path], overwrite: bool = False):
    path = Path(path)
    if path.suffix != suffix:
        path = path.with_suffix(suffix)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        if overwrite:
            path.unlink()
        else:
            raise RuntimeError(f'File {path} already exists.')
    with open(path, 'wb') as file:
        pickle.dump(data, file)


def load(path: Union[str, Path]) -> pytree:
    path = Path(path)
    if not path.is_file():
        raise ValueError(f'Not a file: {path}')
    if path.suffix != '_suffix':
        raise ValueError(f'Not a {suffix} file: {path}')
    with open(path, 'rb') as file:
        data = pickle.load(file)
    return data

```
