### ISSUE TITLE
Support for plain, non-vectorizing Map

### ISSUE THREAD

**Issue by kovasb** [google/jax#212]
Hi,

I'm having issues with vmap, for example batching rule for index_take is not implemented. 

For my use case plain old traditional non-vectorizing map would be fine, such as the Map in XLA. 

However I can't seem to find the binding for that in JAX. Is it there and I'm not seeing it, or if not can we add it? Thanks!!

**Comment by mattjj** [comment]
Can you just use Python's `map`?

**Comment by mattjj** [comment]
To say a bit more: XLA's Map HLO is actually pretty limited in its capabilities, and it would be tricky (but doable) to connect up to JAX, just because higher-order functions take more work than other primitives.

But you can use Python's `map`, or list comprehensions or any arbitrary Python, with JAX. The difference from `jit`'s point of view would be that it stages out the 'unrolled' computation, rather than staging out a Map HLO.

**Comment by kovasb** [comment]
This is likely doable for me, a couple of questions so I understand:
- In this case I'm mapping over 256 elements, but in the future it will be thousands or more; is there a limit to unrolling size, code-gen wise?
- I want to treat the result as a contiguous tensor, so presumably I should follow the unrolling by feeding all the individual tensors to the likes of np.vstack? 

In the meantime I've been working on a different solution, which leads to a different issue. 

I've manually batched parts of my code to avoid the map/vmap altogether, but I'm having problems manually batching the index_take bit. Conceptually what I want is exactly the Gather op, but that also seems unavailable at this time. 

How can I implement this op myself? 

Its a little tricky understanding how the ops are bridged to XLA since it seems to be semi-automated, would it be possible to provide some pointers?

Thanks!

**Comment by hawkinsp** [comment]
Aside: I have a work-in-progress gather/scatter here: https://github.com/google/jax/compare/master...hawkinsp:gather_scatter (but it's not quite done yet)

**Comment by kovasb** [comment]
Good timing, I will see if that code works for me. 

How is the name (like 'gather') mapped onto XLA primitives? Is that just mapped onto a field in the protobuf?

Thanks!

**Comment by mattjj** [comment]
> In this case I'm mapping over 256 elements, but in the future it will be thousands or more; is there a limit to unrolling size, code-gen wise?

Great point. We've found that unrolling things like this can make the XLA compilation step really slow. Maybe that can be improved on the XLA side, but it probably means using Python's `map` isn't a great solution for this use case.

We can provide a `lax.map` that lowers into a While HLO. That will keep the graph small and work with general functions.

I'll re-tag this issue as an enhancement so we can add it!

> I want to treat the result as a contiguous tensor, so presumably I should follow the unrolling by feeding all the individual tensors to the likes of np.vstack?

Yes that would work, but lead to slow compile times for the above reason.

**Comment by mattjj** [comment]
> How is the name (like 'gather') mapped onto XLA primitives? Is that just mapped onto a field in the protobuf?

Every primitive (like `gather_p`) has a translation rule associated with it, and [that translation rule just calls into an XLA computation builder to add a Gather to the computation being built](https://github.com/google/jax/compare/master...hawkinsp:gather_scatter#diff-83af7470f545f46d4476e047532d26f0R1911). (That builder constructs the C++ data structures that XLA uses to represent computations pretty directly; I don't think there are necessarily any protos involved, though from our point of view that's an implementation detail.)

We actually wrote that Python XLA client as part of the JAX project, to make JAX possible, but it's also potentially interesting for direct use. If you want to build, compile, and execute your own computations by talking directly to XLA, that's an easy way to do it from Python! We call the package "jaxlib" right now but we plan to rename it to "xlapy" or something.

**Comment by mattjj** [comment]
Our recommended solution here is to use `vmap`, since that will lead to fast compile times and even better code than if we made a `map` primitive. And `vmap` now works with index_take!

I'm going to close this issue, but please reopen if I've misunderstood and there's more work to be done here.
