### ISSUE TITLE
JAX argsort has different behavior on ties compared to {np,tf}.argsort

### ISSUE THREAD

**Issue by srvasude** [google/jax#2124]
```
import numpy as onp
import jax.numpy as jnp
import tensorflow as tf

x = onp.array([0., -0.])
onp.argsort(x)   # array([0, 1])
tf.argsort(x)       # <tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>
jnp.argsort(x)    #  DeviceArray([1, 0], dtype=int32)
```

We caught this when testing the TFP jax backend. Presumably, it won't make that much difference in practice but worth documenting.

**Comment by jekbradbury** [comment]
Do you know if this behavior is also shared by TF argsort when XLA-compiled (and/or if the XLA OpKernel has to go through hoops to get there?)

**Comment by hawkinsp** [comment]
TF2XLA will sort -0 < 0, because it uses the following comparator:
https://github.com/tensorflow/tensorflow/blob/97f3666d8c10d317a050d786c645d181cbb4d0bb/tensorflow/compiler/xla/client/lib/comparators.cc#L70

We can easily do the same in JAX.

**Comment by hawkinsp** [comment]
Although on reflection I note that both NumPy and TF classic treat them as equal:

```
In [9]: np.argsort([-0., 0.])                        
Out[9]: array([0, 1])

In [10]: np.argsort([0., -0.])                       
Out[10]: array([0, 1])

In [15]: tf.argsort(np.array([0., -0.]))                                                                  
Out[15]: <tf.Tensor: id=32, shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>

In [16]: tf.argsort(np.array([-0., 0.]))                                                                  
Out[16]: <tf.Tensor: id=43, shape=(2,), dtype=int32, numpy=array([0, 1], dtype=int32)>
```

@srvasude Can you say more about what behavior you expected? It seems that neither TF or NumPy guarantee anything about the relative ordering of `-0.` and `0.`; the sort is neither stable nor ordered in any particular way.

**Comment by srvasude** [comment]
I don't actually have a preference here, just wanted to point this out when we were running some coherence tests in TFPs backend. I hope nothing in practice should/will depend on this. For our purposes, we can just do a sanity check that x indexed by it's argsort, is sorted.

**Comment by ekelsen** [comment]
FWIW, I think the GPU in TF classic will treat -0 as less than 0 because it does a radix sort using a conversion similar to the one linked to by @hawkinsp  (to make things even less defined).  The CPU probably treats them as equal because it uses a comparison sort and -0 should compare equal to 0 according to IEEE.

To make matters even worse, the implementation of top_k on the GPU in TF-classic switches from one that uses comparisons for small k, to one based on radix sorts for large k.

**Comment by hawkinsp** [comment]
Closing because I don't think there's an action for us to take here. I agree this might perhaps be the wrong behavior for a stable sort, but that's not what we implement at the moment. So the operator is obeying its contract. Feel free to reopen if you think differently!
