### ISSUE TITLE
BUG: `scipy.special.rel_entr(0., 1.)` gives `1.` instead of `0.`

### ISSUE THREAD

**Issue by lucascolley** [google/jax#21265]
### Description

```python
from scipy.special import rel_entr
from jax.scipy.special import rel_entr as rel_entr_jax
rel_entr(0., 1.)  # 0.0
rel_entr_jax(0., 1.)  # Array(1., dtype=float32, weak_type=True)
```

<img width="612" alt="image" src="https://github.com/google/jax/assets/51488791/28735f6f-ad5d-44aa-8191-80efa29d8ec3">

Found over at https://github.com/scipy/scipy/pull/20085#issuecomment-2115272340.

### System info (python version, jaxlib version, accelerator, etc.)

jax-0.4.28

**Comment by jakevdp** [comment]
Thanks! This was reported in #21192 and is being addressed in #21193
