### ISSUE TITLE
Reference implementations

### ISSUE THREAD

**Issue by notEvil** [google/jax#2126]
Hi!
I tried to implement a jaxpr interpreter that produces numpy code (ast). The idea was to feed this code to numba to see how it compares to XLA. I came pretty far pretty quick because many jax primitives directly map to numpy functions. Then came gather, broadcast_in_dim, tie_in, ...
I see that some are already implemented in lax_reference.py.
Any chance the other more complex functions get a reference (numpy) implementation in the future? And would you discourage implementing such an interpreter in general?

**Comment by hawkinsp** [comment]
In general I'd say: if you want to contribute more reference implementations to `lax_reference.py`, that'd be very welcome. You might find it hard to do in general, particularly for some of the more parametric operators.

I have sitting around in a branch a JAX transformation/interpreter that *runs* JAX programs using classic NumPy (as opposed to building an AST.) I should probably clean it up and check it in at some point.

**Comment by shoyer** [comment]
> I have sitting around in a branch a JAX transformation/interpreter that _runs_ JAX programs using classic NumPy (as opposed to building an AST.) I should probably clean it up and check it in at some point.

Yes, this would be pretty awesome!

The upside of this approach is that by being able to swap out XLA -> NumPy, we potentially could also execute JAX on top of any other library that implements NumPy's API, e.g., we could use JAX's auto-diff and auto-vectorization on top of Dask for distributed/out-of-memory arrays.

**Comment by clemisch** [comment]
Would that in any way facilitate parallelizing "embarrassingly parallel" auto-vectorized code on CPU? 

I have been dreaming about this for some time, as our usecase does not benefit massively from GPU computing per-se and could in theory be parallelized nicely on CPU. Just not in JAX with `vmap` ;-)

**Comment by shoyer** [comment]
> Would that in any way facilitate parallelizing "embarrassingly parallel" auto-vectorized code on CPU?

Yes, in theory. In practice I imagine it could require a bit of work to smooth out the kinks, e.g., with dask you might to make JAX aware of some special operations like `rechunk` used for reshaping data.

It would also be nice if JAX/XLA's parallel operations worked directly across a cluster of CPUs (e.g., via MPI?)

**Comment by clemisch** [comment]
Hmm, I was thinking of "only" parallelizing over CPU cores on one machine. Although this may be harder to implement in the end compared to distributing over multiple CPUs (as multiple "devices")...

I'm sorry for having invaded this issue. I am just very curious about jax's plans with CPU support.

**Comment by shoyer** [comment]
> Hmm, I was thinking more of "only" parallelizing over CPU cores on one single machine.

This is already possible by setting the appropriate flags for XLA: https://github.com/google/jax/issues/1408

**Comment by clemisch** [comment]
Thank you! But that is not really feasible if I'm vectorizing over thousands of projections or pixels? At least I ran into problems with setting `--xla_force_host_platform_device_count` in the thousands, so that `pmap` does not complain.

**Comment by notEvil** [comment]
Thanks for your answers! It sounds very promissing :) Just fyi, the reason why I went with AST instead of an interpreter is that numba operates on python bytecode.

In the meantime I tried to implement the gather primitive. The description in https://www.tensorflow.org/xla/operation_semantics#gather is extensive but overly complicated imo (e.g. different names for the same things like `operand` and "Input Tensor", `start_indices` and "Gather Indices", ...). The pseudo code helps most, yet I still don't understand where `Out` is coming from ... I don't find it in the arguments.

**Comment by notEvil** [comment]
Eventually I managed to implement `gather` and `scatter` in a very straightforward way and got correct results (my example only needs trivial gather and scatter though). Then I tried to come up with a vectorized numpy version of `gather` and it yields the same results.

<details>

```python
def _gather(
    operand,
    start_indices,
    index_vector_dim,
    offset_dims,
    slice_sizes,
    collapsed_slice_dims,
    start_index_map,
):
    result_shape = []
    batch_dims = []

    adjusted_slice_sizes = [
        slice_size
        for index, slice_size in enumerate(slice_sizes)
        if index not in collapsed_slice_dims
    ]

    for index in itertools.count():
        try:
            k = offset_dims.index(index)

        except ValueError:
            pass

        else:
            _ = adjusted_slice_sizes[k]
            result_shape.append(_)
            continue

        k = len(batch_dims)  # WARNING assumed
        batch_dims.append(index)

        _ = k if k < index_vector_dim else (k + 1)
        if len(start_indices.shape) <= _:  # WARNING assumed
            batch_dims.pop()
            break
        _ = start_indices.shape[_]
        result_shape.append(_)

    remapped_offset_dims = [
        index
        for index in range(len(operand.shape))
        if index not in collapsed_slice_dims
    ]

    if False:
        result = numpy.ndarray(result_shape)

        for Out in itertools.product(*[range(length) for length in result_shape]):
            G = [Out[k] for k in batch_dims]
            G.insert(index_vector_dim, slice(None))
            S = start_indices[tuple(G)]
            S_in = numpy.zeros((len(operand.shape),), dtype=int)
            S_in[start_index_map] = S
            O_in = numpy.zeros((len(operand.shape),), dtype=int)
            O_in[remapped_offset_dims] = [Out[index] for index in offset_dims]
            In = O_in + S_in
            result[Out] = operand[tuple(In)]

    if True:
        Out = numpy.meshgrid(
            *[list(range(length)) for length in result_shape], indexing="ij"
        )
        G = [Out[k] for k in batch_dims]
        G.insert(index_vector_dim, slice(None))
        S = start_indices[tuple(G)]
        axes = {}
        axes.update((_, index) for index, _ in enumerate(start_index_map))
        axes.update(
            (remapped_index, index)
            for index, remapped_index in zip(offset_dims, remapped_offset_dims)
        )
        axes = [axes[index] for index in range(len(axes))]
        In = numpy.transpose(S, axes=axes)
        result = operand[In]

    return result
```

</details>

It would be great if someone could verify the approach/code! Mind that a lot of it can be done at translation time (many arguments are constant).

**Comment by thisiscam** [comment]
@notEvil Do you have any update on this? Turned out that I'd be very interested in such an interpreter!

**Comment by notEvil** [comment]
Unfortunately no, but I managed to extract the core of my attempt and push it to https://github.com/notEvil/jax2numpy. The reason why its not developed further is that compile times of jax improved since then and numba proved to be a larger obstacle than anticipated, see the Readme of the repo.

**Comment by mattjj** [comment]
I think we've added more docs over the years about interpreters and primitive rules, but we're unlikely to make them complete because they're not public APIs.

I'm going to close this old issue!
