### ISSUE TITLE
Gamma sample gradients has incorrect dtype in x64 mode

### ISSUE THREAD

**Issue by srvasude** [google/jax#2130]
The following snippet of code fails in JAX:
```
import jax
import jax.numpy as jnp
import jax.random as jaxrand
jax.config.update('jax_enable_x64', True)

key = jaxrand.PRNGKey(0.)
a = jnp.array(1., dtype=jnp.float32)
b = jnp.array(3., dtype=jnp.float32)
f = lambda x, y: jaxrand.gamma(key=key, a=x, dtype=jnp.float32) / y
y, f_vjp = jax.vjp(f, a, b)
```
with
```
TypeError: body_fun output and input must have identical types, got
(ShapedArray(float32[]), ShapedArray(float32[]), ShapedArray(float64[]), ShapedArray(bool[]))
and
(ShapedArray(float32[]), ShapedArray(float32[]), ShapedArray(float32[]), ShapedArray(bool[]))
```

Some dtype information is being lost along the way.

**Comment by brianwa84** [comment]
Unless gamma sampler is implementing implicit reparam, it should probably raise for the vjp.

**Comment by srvasude** [comment]
The sampler is reparameterized the same way as TF

**Comment by brianwa84** [comment]
I was referring to gradients wrt the shape parameter, implemented here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cwise_op_random_grad.cc
I guess the issue here is simpler than that, just an unstable while body.

**Comment by brianwa84** [comment]
@hawkinsp this is a similar error to what what I was trying to give a minimal-case for in https://github.com/google/jax/issues/2004
