### ISSUE TITLE
Generator/yield-support

### ISSUE THREAD

**Issue by ok-drama** [google/jax#2132]
Functions with yield does not seem to be supported and gives funny results in jit.

```
from jax import jit

def yf(x):
    yield(x)
    
jyf = jit(yf)
print(yf, jyf)
print(next(yf(1.5)))
print(next(jyf(1.5)))
```
Gives:

> <function yf at 0x7f79f01a7e18> <function jit.<locals>.f_jitted at 0x7f79f01ab1e0>
1.5
Traced<ShapedArray(float32[], weak_type=True):JaxprTrace(level=-1/1)>

**Comment by hawkinsp** [comment]
It is intentional that this is not supported.

I'm not sure whether we could detect this case and issue a more graceful error. If we could, we should do so. Otherwise I think the best we could do is add a note to the documentation of `jit`.
