### ISSUE TITLE
jax.pure_callback produces "TypeError: mul got incompatible shapes for broadcasting" error after update

### ISSUE THREAD

**Issue by yachmena** [google/jax#21331]
### Description

```python
from scipy.special import factorial
from jax import config
import jax
import numpy as np
from numpy.polynomial.hermite import hermval

config.update("jax_enable_x64", True)


def _hermite(x, n):
    sqsqpi = np.sqrt(np.sqrt(np.pi))
    c = np.diag(1.0 / np.sqrt(2.0**n * factorial(n)) / sqsqpi)
    f = hermval(x, c) * np.exp(-(x**2) / 2)
    return f.T


def hermite(x, n):
    shape_dtype = jax.ShapeDtypeStruct(x.shape + n.shape, x.dtype)
    return jax.pure_callback(_hermite, shape_dtype, x, n, vectorized=True)


if __name__ == "__main__":
    from numpy.polynomial.hermite import hermgauss

    n = np.arange(0, 30)
    x, w = hermgauss(80)
    h = _hermite(x, n)

    h_jax = jax.jit(jax.vmap(hermite, in_axes=(0, None)))(x, n)
    # h_jax = jax.jit(hermite)(x, n)
    print("max difference:", np.max(np.abs(h - h_jax)))
```

The `jax.pure_callback` raises a TypeError with the message `"mul got incompatible shapes for broadcasting: (30,), (80,)."`, which is traced back to the `hermval` numpy function.

The code works fine, including custom gradients (skipped in the example above), with the jax version 0.4.1

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.28
jaxlib: 0.4.28
numpy:  1.26.4
python: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='max-wgse001.desy.de', release='3.10.0-1160.114.2.el7.x86_64', version='#1 SMP Wed Mar 20 15:54:52 UTC 2024', machine='x86_64')

**Comment by jakevdp** [comment]
Hi - thanks for the report! The relevant change was that callback functions now receive JAX arrays rather than NumPy arrays (see [CHANGELOG](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-27-may-7-2024)); it appears that `hermval` does not work correctly for JAX array inputs, for reasons I'm not entirely sure of.

In any case, the workaround would be to explicitly cast the input to a NumPy array when using `hermval`:
```python
f = hermval(np.asarray(x), c) * np.exp(-(x**2) / 2)
```

**Comment by yachmena** [comment]
Amazing, works now! Thank you.
