### ISSUE TITLE
Errors in the references

### ISSUE THREAD

**Issue by mateuszmalinowski** [google/jax#2135]
The scan function in https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html#jax.lax.scan assumes the following signature `scan :: (c -> a -> (c, b)) -> c -> [a] -> (c, [b])` while in reality the following signature works `scan :: ((c, a) -> (c, b) -> c -> [a] -> (c, [b])`, and the former doesn't.

The hvp function in https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html also doesn't look properly. It is 
`
def hvp(f, x, v):
    return grad(lambda x: np.vdot(grad(f)(x), v))
`
making the argument `x` irrelevant. Perhaps it should be without `x` or
`
def hvp(f, x, v):
    return grad(lambda x: np.vdot(grad(f)(x), v))(x)
`

Finally, 'Edit on GitHub' on some site like https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html leads to 404.

**Comment by hawkinsp** [comment]
The second fix has already been made.

The first fix I think I disagree with: the type signature of `scan` is correct as is, ut it is perhaps making a loose interpretation of the Haskell-style `->` for passing multiple parameters. But I don't think the clarity is improved by explicit tupling of only one of the functions. You could argue that
`(((c, a) -> (c, b)), c, [a]) -> (c, [b])` would be more strictly correct given Python doesn't curry, but it's less readable.
