### ISSUE TITLE
RuntimeError: Bad StatusOr access: INTERNAL: Mosaic failed to compile TPU kernel: Bad lhs type in tpu.matmul

### ISSUE THREAD

**Issue by brianchunkang** [google/jax#21408]
### Description

Using PyTorch XLA and flash attention in JAX. Using amp_bf16 mixed precision. Error occurs on the backward pass using CrossEntropyLoss

Last part of the error points to a tpu.matmul operation:

[rank0]: The MLIR operation involved:
[rank0]:   %6936 = "tpu.matmul"(%6933, %6934, %6935) <{precision = #tpu.contract_precision<fp32>, transpose_lhs = false, transpose_rhs = true}> : (vector<512x128xbf16>, vector<128x128xbf16>, 
[rank0]: vector<512x128xf32>) -> vector<512x128xf32>
[rank0]: ... additional diagnostics were skipped.

Full trace attached here:
[mlir-error.trace.txt](https://github.com/google/jax/files/15422924/mlir-error.trace.txt)

### System info (python version, jaxlib version, accelerator, etc.)

>>> import jax
>>> jax.print_environment_info()
jax:    0.4.29.dev20240514
jaxlib: 0.4.29.dev20240514
numpy:  1.26.4
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
jax.devices (4 total, 4 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(1,0,0), core_on_chip=0) TpuDevice(id=2, process_index=0, coords=(0,1,0), core_on_chip=0) TpuDevice(id=3, process_index=0, coords=(1,1,0), core_on_chip=0)]
process_count: 1
platform: uname_result(system='Linux', node='t1v-n-88d3fcca-w-0', release='5.19.0-1027-gcp', version='#29~22.04.1-Ubuntu SMP Thu Jun 22 05:13:17 UTC 2023', machine='x86_64')

**Comment by brianchunkang** [comment]
This seems to be an issue with bfloat16 only, and mentioned in an internal bug b/340263269#comment9

**Comment by brianchunkang** [comment]
TPUv5p-8

**Comment by apaszke** [comment]
It looks like the problem is that you have requested the matmul to run in fp32 precision, but your operands are bf16. How did you generate this kernel?

**Comment by apaszke** [comment]
(^this means that it is expected to fail. you should adjust the code that creates this kernel to reduce requested precision when using low-precision operands)

**Comment by brianchunkang** [comment]
I'm using the PyTorch XLA library. The repo is here and I get issues when I
run this in amp_bf16 or bf16. Runs fine with float32:
https://github.com/pytorch-tpu/llm-foundry

"you should adjust the code that creates this kernel to reduce requested
precision when using low-precision operands" : I followed an example on the
PyTorch XLA repo, that has me set JAX precision to highest (
https://github.com/pytorch/xla/blob/aeed61a94cbe32099ee4e896ca6afd37d4ac9456/test/test_pallas_spmd.py#L34).
Let me try removing that.

Here's a simple repro:

export PJRT_DEVICE=TPU
export XLA_USE_BF16=1
python3
xla/examples/flash_attention/train_decoder_only_flash_attention_fsdp_v2.py


Internal bug with the actual repo and issue is here: b/341696816

**Comment by brianchunkang** [comment]
I commented out the JAX jax_default_matmul_precision config update, and it
all runs smoothly. Thanks for the tip!

The example is this, and I'll let the PyTorch XLA team know:
https://github.com/pytorch/xla/blob/master/test/test_pallas_spmd.py
