### ISSUE TITLE
jax/jaxlib not working

### ISSUE THREAD

**Issue by RivasLab** [google/jax#21491]
### Description

I followed standard instructions for a jax installation in an arm Mac:

pip install --upgrade "jax[cpu]"
Requirement already satisfied: jax[cpu] in ./jax-metal/lib/python3.9/site-packages (0.4.28)
Requirement already satisfied: ml-dtypes>=0.2.0 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (0.2.0)
Requirement already satisfied: numpy>=1.22 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (1.26.4)
Requirement already satisfied: opt-einsum in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (3.3.0)
Requirement already satisfied: scipy>=1.9 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (1.13.0)
Requirement already satisfied: importlib-metadata>=4.6 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (7.1.0)
Requirement already satisfied: jaxlib==0.4.28 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (0.4.28)
Requirement already satisfied: zipp>=0.5 in ./jax-metal/lib/python3.9/site-packages (from importlib-metadata>=4.6->jax[cpu]) (3.18.2)

yet the standard test fails:

python -c 'import jax; print(jax.numpy.arange(10))'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/erivas/jax-metal/lib/python3.9/site-packages/jax/__init__.py", line 37, in <module>
    import jax.core as _core
  File "/Users/erivas/jax-metal/lib/python3.9/site-packages/jax/core.py", line 18, in <module>
    from jax._src.core import (
  File "/Users/erivas/jax-metal/lib/python3.9/site-packages/jax/_src/core.py", line 39, in <module>
    from jax._src import dtypes
  File "/Users/erivas/jax-metal/lib/python3.9/site-packages/jax/_src/dtypes.py", line 33, in <module>
    from jax._src import config
  File "/Users/erivas/jax-metal/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/Users/erivas/jax-metal/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 84, in <module>
    cpu_feature_guard.check_cpu_features()
RuntimeError: This version of jaxlib was built using AVX instructions, which your CPU and/or operating system do not support. You may be able work around this issue by building jaxlib from source.

### System info (python version, jaxlib version, accelerator, etc.)

Requirement already satisfied: jax[cpu] in ./jax-metal/lib/python3.9/site-packages (0.4.28)
Requirement already satisfied: ml-dtypes>=0.2.0 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (0.2.0)
Requirement already satisfied: numpy>=1.22 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (1.26.4)
Requirement already satisfied: opt-einsum in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (3.3.0)
Requirement already satisfied: scipy>=1.9 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (1.13.0)
Requirement already satisfied: importlib-metadata>=4.6 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (7.1.0)
Requirement already satisfied: jaxlib==0.4.28 in ./jax-metal/lib/python3.9/site-packages (from jax[cpu]) (0.4.28)
Requirement already satisfied: zipp>=0.5 in ./jax-metal/lib/python3.9/site-packages (from importlib-metadata>=4.6->jax[cpu]) (3.18.2)

**Comment by dfm** [comment]
This means that your Python installation is an x86 Python installation running under Rosetta, not a Mac ARM build. You'll want to install a native ARM build and (as an added bonus) you'll get better performance! I typically use the installation from [Miniforge](https://github.com/conda-forge/miniforge), but there are other options. Hope this helps!

**Comment by hawkinsp** [comment]
@dfm want to send a PR adding that to the cpu_feature_guard error if we are on Mac?

**Comment by dfm** [comment]
Yes! I'm on it.

**Comment by RivasLab** [comment]
thanks!

I followed the miniforge link, but I did not get very far after downloading the code. Is there any place that provide details instructions of how to remove the ols x86 Python installation and install an arm one?

thanks
Elena

**Comment by dfm** [comment]
I'm not sure how helpful I can be on this front!

Depending on how you previously installed Python, you might not need to uninstall it at all. But if you previously used conda: my usual workflow for uninstalling a conda distribution is to manually delete the lines added to my `.bashrc`/`.zshrc`/etc. file, but it [looks like conda does have support for uninstallation](https://github.com/conda-forge/miniforge#uninstallation) (I don't think those instructions are specific to miniforge).

Then you should be able to follow the [installation instructions on that README page](https://github.com/conda-forge/miniforge#install) to get your new installation up and running. You might want to check that the command `uname -m` prints `arm64` in your shell.

Beyond this advice, I'm not sure there's much I can add - hope this is enough to get you started!

**Comment by dfm** [comment]
Over in #21494 I added some extra text to the `RuntimeError` which will hopefully help with future instances of this issue. I'm going to close this issue now, but @RivasLab please comment again if you continue to have issues with this.
