### ISSUE TITLE
jitted functions can't return generic callables

### ISSUE THREAD

**Issue by mattjj** [google/jax#2152]
But we don't raise this error very nicely!

The earliest we could catch it is just above [this line](https://github.com/google/jax/blob/3c9ae5e221316c82f1dda34aa7f12173b12e3a21/jax/interpreters/partial_eval.py#L349). We should check that every element of `ans` is a valid jaxtype, e.g. by calling `core.get_aval` on it to see if that raises an error.

Right now when the user returns a callable that closes over Traced values (which breaks `jit`'s contract by not returning pytrees of arrays), they get a mysterious "Can't lift sublevels 1 to 0" error.

**Comment by matt-graham** [comment]
I came up against this issue in relation to #2046 - a more informative error message would definitely have saved some initial confusion about the source of the error!

**Comment by mattjj** [comment]
We added a check for this at some point!

```python
jax.jit(lambda: lambda x: x)()
```
```
TypeError: Value <function <lambda>.<locals>.<lambda> at 0x7fe074689440> with type <class 'function'> is not a valid JAX type
```

Could be even better, but I think that's good enough.
