### ISSUE TITLE
pure_callback is not passing `np.ndarray` typed inputs

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#21526]
### Description

I updated JAX and am getting inputs to callback functions coming in as `jax.ArrayImpl` and not `np.ndarray`.

```python
import jax
import jax.numpy as jnp
import numpy as np


def fn(x: jax.Array) -> jax.Array:
    # Define the expected shape & dtype of output.
    result_shape_dtype = jax.ShapeDtypeStruct(
        shape=np.shape(x),
        dtype=x.dtype
    )

    return jax.pure_callback(_host_fn, result_shape_dtype, x)


def _host_fn(x: np.ndarray):
    print('x', type(x))
    assert isinstance(x, np.ndarray)
    return x


if __name__ == '__main__':
    fn(jnp.asarray([1.]))
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax==0.4.28
jaxlib==0.4.28
```

**Comment by yashk2810** [comment]
Yes, that was a deliberate change we made.

Is there a problem or an issue? The current description does not seem to specify the issue.

cc @superbobry

**Comment by dfm** [comment]
Where do the docs say `np.ndarray`? I couldn't track that down. The change was listed [in the changelog here](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-27-may-7-2024), and the [current docs](https://jax.readthedocs.io/en/latest/_autosummary/jax.pure_callback.html) say "JAX arrays" AFAICT.

**Comment by Joshuaalbert** [comment]
The source code:
![Uploading Screenshot from 2024-05-30 21-35-00.png…]()

**Comment by yashk2810** [comment]
Maybe you are not looking at the main branch (https://github.com/google/jax/blob/51e743139b2bbe5146e257610eca31a05f277f83/jax/_src/callback.py#L272)? But anyways, this is WAI. 

I am going to close the issue. Please reopen if this is causing major problems for you :)

**Comment by superbobry** [comment]
I think the documentation update was done after we cut the release, unfortunately. So, the source-level documentation is indeed misleading. Sorry about that.
