### ISSUE TITLE
str(PyTreeDef) identical for two PyTreeDefs, but assert with allclose fails

### ISSUE THREAD

**Issue by johannahaffner** [google/jax#21581]
### Description

I'm trying to understand a [bug ](https://github.com/patrick-kidger/optimistix/issues/63) in optimistix, and came across this behaviour that is unintuitive to me: 

- The PyTreeDef of two jacobians computed using `jax.linearize` is not the same, but the strings of the PyTreeDefs are the same. 

Since the tree structure is what I want to examine for debugging purposes, this should not happen.

Edit: fixed typo in comment.

Here is an MWE that demonstrates the error:

```python
import pytest

import jax
import jax.numpy as jnp
import jax.tree_util as jtu

import equinox as eqx

def _no_nan(x):
    """Compied from test/helpers.py in diffrax."""
    if eqx.is_array(x):
        return x.at[jnp.isnan(x)].set(8.9568)  # arbitrary magic value
    else:
        return x
def tree_allclose(x, y, *, rtol=1e-5, atol=1e-8, equal_nan=False):
    """Copied from test/helpers.py in diffrax."""
    if equal_nan:
        x = jtu.tree_map(_no_nan, x)
        y = jtu.tree_map(_no_nan, y)
    return eqx.tree_equal(x, y, typematch=True, rtol=rtol, atol=atol)

def fn(y):
    def shifted_parabola(x0):
        x = jnp.linspace(0, 10)
        return (x - x0)**2
    true = shifted_parabola(2.)  # True value
    fit = shifted_parabola(y)
    return true - fit

y0 = 1.  # starting guess

_, jac_of_fn = jax.linearize(fn, y0)
_, jac_of_fn_with_lambda = jax.linearize(lambda _y: fn(_y), y0)
assert tree_allclose(jax.jacfwd(fn)(y0), jac_of_fn(y0)) 
assert tree_allclose(jax.jacfwd(fn)(y0), jac_of_fn_with_lambda(y0))

# Using lambda functions produces subtle difference in pytrees, not legible to human
with pytest.raises(AssertionError):
    assert jtu.tree_structure(jac_of_fn) == jtu.tree_structure(jac_of_fn_with_lambda)
assert str(jtu.tree_structure(jac_of_fn)) == str(jtu.tree_structure(jac_of_fn_with_lambda))
```

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.28
jaxlib: 0.4.28
numpy:  1.26.4
python: 3.11.8 (v3.11.8:db85d51d3e, Feb  6 2024, 18:02:37) [Clang 13.0.0 (clang-1300.0.29.30)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='bs-mbpas-0019', release='23.3.0', version='Darwin Kernel Version 23.3.0: Wed Dec 20 21:33:31 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T8112', machine='arm64')

**Comment by superbobry** [comment]
It looks like this is happening because we are using `functools.partial` internally, and `partial` objects do not implement `__eq__`:

```python
>>> import functools
>>> def f(): ...
...
>>> functools.partial(f) == functools.partial(f)
False
```

**Comment by superbobry** [comment]
I removed some unnecessary definitions/calls from the repro:

```python
import jax
import jax.numpy as jnp
import jax.tree_util as jtu


def fn(y):
    def shifted_parabola(x0):
        x = jnp.linspace(0, 10)
        return (x - x0)**2
    true = shifted_parabola(2.)  # True value
    fit = shifted_parabola(y)
    return true - fit


y0 = 1.  # starting guess

_, jac_of_fn = jax.linearize(fn, y0)
_, jac_of_fn_with_lambda = jax.linearize(lambda _y: fn(_y), y0)
assert jtu.tree_structure(jac_of_fn) == jtu.tree_structure(jac_of_fn_with_lambda)
```

**Comment by johannahaffner** [comment]
> You can simplify the repro even further:

> This makes clear that the problem has nothing to do with the function being passed to `linearize`.

Fascinating! And then I really am out of leads, I was sure it must have something to do with the function passed 😃

**Comment by patrick-kidger** [comment]
FWIW I think this behaviour is acceptable in JAX. A jaxpr is just JAX's internal representation of a function, and Python itself does the same thing:
```python
def some_fun():
    pass

def higher_order_fun(fun):
    def inner_fun():
        return fun()
    return inner_fun

assert higher_order_fun(some_fun) == higher_order_fun(some_fun)  # fails
```

Moreover I get a bit antsy about the idea of comparing jaxprs for equality. It's very common for jaxprs to become truly gigantic, and iterating over them to test for equality seems like a compiletime footgun.

**Comment by johannahaffner** [comment]
Good point. 

I went in this direction because I thought it might be at the root of why we can't batch in `GaussNewton`, but I'm not sure that is the case anymore, since I can batch over the output of `jax.linearize`. Definitely not an expert, just an enthusiast :) 

Why does the difference now show up in the string of a PyTreeDef though? Those are equal.

**Comment by superbobry** [comment]
> Why does the difference now show up in the string of a PyTreeDef though? Those are equal.

I think this is because `PyTreeDef.__str__` does not include the auxiliary data stored in the nodes.

**Comment by johannahaffner** [comment]
What would that auxiliary data contain?

Can I conclude that errors such as the one above do not come from the pytree definition if the strings are the same? I currently only use these as debugging tools.

**Comment by superbobry** [comment]
> What would that auxiliary data contain?

It depends on the type and its flattening rule.

> Can I conclude that errors such as the one above do not come from the pytree definition if the strings are the same?

Sorry, I'm not sure I follow. Which errors are you referring to?

**Comment by mattjj** [comment]
Thanks for the discussion, all!

To summarize: equality of string pretty-prints does not imply object equality (for treedefs, and likely for lots of Python classes).

**Comment by johannahaffner** [comment]
> Thanks for the discussion, all!
> 
> To summarize: equality of string pretty-prints does not imply object equality (for treedefs, and likely for lots of Python classes).

This was the question I had :)
