### ISSUE TITLE
Custom partitioning error in fused_attention_stablehlo

### ISSUE THREAD

**Issue by kvablack** [google/jax#21584]
### Description

I'm trying to use the recently added `jax._src.cudnn.fused_attention_stablehlo`, but I'm getting the following error from the `infer_sharding_from_operands` function:

```
AttributeError: 'PositionalSharding' object has no attribute 'spec'
```

Clearly, the function is expecting a `NamedSharding` but getting a `PositionalSharding` instead. This is strange, because I am only using `NamedSharding` in my code. I've even tried adding a `jax.lax.with_sharding_constraing(inputs, NamedSharding(...))` right before calling `fused_attention_stablehlo.dot_product_attention`, to no avail. I inserted a breakpoint into the `infer_sharding_from_operands` function and found that the `mesh` object being passed in is totally empty (`Mesh(device_ids=[], axis_names=())`) and all of the arguments have `PositionalSharding`s.

I'm not sure this is the fault of `fused_attention_stablehlo`, since in the [custom_partitioning docs](https://jax.readthedocs.io/en/latest/jax.experimental.custom_partitioning.html), it does suggest calling `.spec` directly on the sharding, suggesting it's safe to assume it will always be a `NamedSharding`.

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.28
jaxlib: 0.4.28
numpy:  1.26.4
python: 3.11.9 | packaged by conda-forge | (main, Apr 19 2024, 18:36:13) [GCC 12.3.0]
jax.devices (8 total, 8 local): [cuda(id=0) cuda(id=1) ... cuda(id=6) cuda(id=7)]
process_count: 1
platform: uname_result(system='Linux', node='compute-hpc-node-294', release='6.5.0-1018-oracle', version='#18~22.04.1-Ubuntu SMP Sat Feb 17 21:41:13 UTC 2024', machine='x86_64')
```

**Comment by superbobry** [comment]
@yashk2810 can you have a look, please?

**Comment by yashk2810** [comment]
Can you try running your computation under `with mesh:` context manager? That should fix this.

**Comment by kvablack** [comment]
Thanks, that worked!

**Comment by fazega** [comment]
Can we keep that open as
1. It's not documented so I ran into the exact same problem
2. It's not a desirable long term solution (?)
