### ISSUE TITLE
vmap not working with lax.igamma, lax.igammac, lax.betainc 

### ISSUE THREAD

**Issue by adabbott** [google/jax#2163]
The issue occurs when one of the dimensions in the `in_axes` argument of `vmap` contains a `None`:

```python
from jax import vmap,lax
import jax.numpy as np

vmap_igamma = vmap(lax.igamma, (None,0))
vmap_igamma(1.0, np.array([0.5,0.6]))
```
<details>
  <summary>Click for Traceback</summary>
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    vmap_igamma(1.0, np.array([0.5,0.6]))
  File "/home/adabbott/Git/jax/jax/jax/api.py", line 696, in batched_fun
    lambda: _flatten_axes(out_tree(), out_axes))
  File "/home/adabbott/Git/jax/jax/jax/interpreters/batching.py", line 40, in batch
    out_vals, out_dims = batch_fun(fun, in_vals, in_dims)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/batching.py", line 46, in batch_fun
    out_vals = fun.call_wrapped(*in_vals)
  File "/home/adabbott/Git/jax/jax/jax/linear_util.py", line 152, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/adabbott/Git/jax/jax/jax/lax/lax.py", line 211, in igamma
    return igamma_p.bind(_brcast(a, x), _brcast(x, a))
  File "/home/adabbott/Git/jax/jax/jax/core.py", line 162, in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/batching.py", line 114, in process_primitive
    val_out, dim_out = batched_primitive(vals_in, dims_in, **params)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/batching.py", line 184, in broadcast_batcher
    out = prim.bind(*args, **params)
  File "/home/adabbott/Git/jax/jax/jax/core.py", line 159, in bind
    return self.impl(*args, **kwargs)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/xla.py", line 162, in apply_primitive
    compiled_fun = xla_primitive_callable(prim, *map(arg_spec, args), **params)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/xla.py", line 177, in xla_primitive_callable
    built_c = primitive_computation(prim, backend, tuple_args, *avals, **params)
  File "/home/adabbott/Git/jax/jax/jax/interpreters/xla.py", line 228, in primitive_computation
    raise RuntimeError(msg)
RuntimeError: Invalid argument: Arguments to Igamma must have equal shapes and types; got f32[] and f32[2]: 
This is a bug in JAX's shape-checking rules; please report it!
https://github.com/google/jax/issues

</details>

The same error occurs for `lax.igammac` and `lax.betainc`. This behavior is not consistent with other  `naryop`'s in  [jax/lax/lax.py](https://github.com/google/jax/blob/master/jax/lax/lax.py).  For example, the following analogous vmap's of `lax.pow` or  `lax.atan2` work fine:

```python
from jax import vmap,lax
import jax.numpy as np

vmap_pow = vmap(lax.pow, (None,0))
vmap_pow(1.0, np.array([0.5,0.6]))

vmap_atan2 = vmap(lax.atan2, (None,0))
vmap_atan2(1.0, np.array([0.5,0.6]))
```

Thanks!

**Comment by notEvil** [comment]
Is there a workaround for this? In case its supposed to be easy to fix and someone provides a hint where to start looking, I'd try my own luck!

**Comment by hawkinsp** [comment]
The fix probably isn't terribly hard to do: the primitive needs to do its own broadcasting in its XLA translation rule, most likely, rather than assuming that the underlying function it is calling knows how to broadcast itself. Contributions welcome...

**Comment by mattjj** [comment]
cc @srvasude 

Thanks for the clear report @adabbott ! Somehow I missed this issue when it was opened.

@notEvil it may be a short fix but perhaps tricky to explain... I'll take a look at it now and report back.

**Comment by notEvil** [comment]
Thanks for the quick response and the hint! The following seems to work, though I'm not sure if its correct.

```python
def _igamma_translation_rule(c, a, x):
  a_shape = c.GetShape(a).dimensions()
  x_shape = c.GetShape(x).dimensions()
  shape = broadcast_shapes(a_shape, x_shape)
  return c.Igamma(_broadcast(a, a_shape, shape, c), _broadcast(x, x_shape, shape, c))
  
def _broadcast(array, array_shape, result_shape, c):
  if array_shape == result_shape:
    return array
  result = c.BroadcastInDim(array, result_shape, list(range(len(result_shape) - len(array_shape), len(result_shape))))
  return result
```

**Comment by mattjj** [comment]
Wow! That looks good to me, as an implementation of @hawkinsp's suggestion.

However, I'm a bit confused right now. It seems [we do broadcasting at the Python level](https://github.com/google/jax/blob/d11a9ab18577f8a9b7bd7edda821ce67df89f387/jax/lax/lax.py#L184), so explicit broadcasts should already be inserted. Moreover our [tests](https://github.com/google/jax/blob/d11a9ab18577f8a9b7bd7edda821ce67df89f387/tests/lax_test.py#L2634) should already [cover](https://github.com/google/jax/blob/d11a9ab18577f8a9b7bd7edda821ce67df89f387/tests/lax_test.py#L127-L132) this stuff...

**Comment by hawkinsp** [comment]
Ah, but `vmap` doesn't use the Python wrappers. So we should probably remove broadcasting from the wrapper and do it in the translation rule instead? Or alternatively we need a different batching rule.

**Comment by mattjj** [comment]
Ohh, ignore my previous comment. I blame lack of caffeine this morning.

The problem is these primitives are using a standard batching rule (i.e. vmap rule) which assumes broadcasting. (Ah, @hawkinsp commented at the same time!)

Yes I agree: we can either use a different batching rule or just implement broadcasting in the translation. I think the latter is better.

**Comment by mattjj** [comment]
One other alternative solution is to make the batching rule call the Python wrapper rather than the primitive directly. But fusing the broadcast into the primitive seems like the best solution.

@notEvil want to make a PR with translation rules of that form, and also delete [the broadcasts](https://github.com/google/jax/blob/d11a9ab18577f8a9b7bd7edda821ce67df89f387/jax/lax/lax.py#L184) from the Python wrapper layer? You might be able to abstract it a bit, e.g. into something like

```python
def _translate_binop_with_broadcasting(prim, ...):
  ...
```

Looking at lax.py's `standard_translate` might help: we just map the primitive's name to the XLA builder name (i.e. "sin" -> "Sin").

(I'm still confused as to why the tests don't catch this issue...)

**Comment by mattjj** [comment]
Ah, I found the bug in the tests. I'll make a separate PR for that.

**Comment by mattjj** [comment]
The fix is that in lax_test.py, this line:

```python
compatible_shapes = [[(3,)], [(3, 4), (3, 1), (1, 4)], [(2, 3, 4), (2, 1, 4)]]
```

didn't include scalars, and iiuc should instead be:

```python
compatible_shapes = [[()], [(3,)], [(3, 4), (3, 1), (1, 4)], [(2, 3, 4), (2, 1, 4)]]
```

Making that change catches the issue, _but only when enough test cases are generated_, and that requires more than the default:

```bash
env JAX_NUM_GENERATED_CASES=100 pytest -n auto tests/lax_test.py -W ignore
```

Even then, there's only one failure on `igamma`:

```
[ RUN      ] LaxVmapTest.testOpIgamma_float64[]_float64[]_bdims=(0, None)
[(10,), ()]
[  FAILED  ] LaxVmapTest.testOpIgamma_float64[]_float64[]_bdims=(0, None)
======================================================================
ERROR: testOpIgamma_float64[]_float64[]_bdims=(0, None) (__main__.LaxVmapTest)
testOpIgamma_float64[]_float64[]_bdims=(0, None) (__main__.LaxVmapTest)
testOpIgamma_float64[]_float64[]_bdims=(0, None)(op_name='igamma', rng_factory=<function rand_positive at 0x7f3fe6868290>, shapes=((), ()), dtype=<class 'numpy.float64'>, bdims=(0, None), tol={<class 'numpy.float64'>: 1e-14})
[ ... snip ... ]
RuntimeError: Invalid argument: Arguments to Igamma must have equal shapes and types; got f32[10] and f32[]:
This is a bug in JAX's shape-checking rules; please report it!
https://github.com/google/jax/issues


----------------------------------------------------------------------
Ran 100 tests in 13.165s

FAILED (errors=1)
```

This leads me to believe we don't need to add full broadcasting ourselves, but may only need to handle the scalar case. (However, full broadcasting doesn't hurt, since it's what XLA canonicalizes to under the hood.)

Thoughts?

**Comment by mattjj** [comment]
@hawkinsp to put a finer point on it, what do you think about

```python
compatible_shapes = [[()], [(3,)], [(3, 4), (3, 1), (1, 4)], [(2, 3, 4), (2, 1, 4)]]
```

versus

```python
compatible_shapes = [[()], [(), (3,)], [(), (3, 4), (3, 1), (1, 4)], [(), (2, 3, 4), (2, 1, 4)]]
```

The former says scalars are compatible with scalars and we should test them; the latter says scalars are compatible with arrays of all ranks/shapes.

I don't have a strong opinion of one versus the other, but I think the second is the more common convention among lax ops today.

**Comment by notEvil** [comment]
Any thoughts on the PR? I see that you like to use `functools.partial` but I feel a decorator is more suitable (because non intrusive) in this case.

**Comment by hawkinsp** [comment]
#2468 fixed this.
