### ISSUE TITLE
Inconsistent results with shard_map when switching PRNG Implementation from threefry2x32 to rbg

### ISSUE THREAD

**Issue by southfreebird** [google/jax#21663]
### Description

I've noticed strange behavior when I change the `jax_default_prng_impl` from `threefry2x32` to `rbg`. I get the same results with `threefry2x32`, but when I switch to `rbg`, the results with shard_map start to differ. Here is the script to reproduce the issue:
```
import functools

import jax
import jax.numpy as jnp

from jax.experimental import mesh_utils
from jax.sharding import Mesh, PositionalSharding, PartitionSpec as P
from jax.experimental.shard_map import shard_map

jax.config.update("jax_default_prng_impl", "rbg")
# jax.config.update("jax_default_prng_impl", "threefry2x32")


def independent_permutation(rngs, array, axis):
    _permutation_fn = functools.partial(
        jax.random.permutation,
        axis=axis - 1,
    )
    return jax.vmap(_permutation_fn, in_axes=0, out_axes=0)(rngs, array)


if __name__ == "__main__":
    batch_size = 10
    seq_len = 16
    values = jnp.tile(jnp.arange(seq_len)[None, ...], reps=(batch_size, 1))

    num_devices = len(jax.devices())
    device_mesh = mesh_utils.create_device_mesh(mesh_shape=(num_devices))
    mesh = Mesh(device_mesh.reshape(num_devices, 1), axis_names=("data", "model"))

    values = jax.device_put(
        values,
        PositionalSharding(device_mesh).reshape(-1, 1),
    )

    key = jax.random.split(jax.random.PRNGKey(0), batch_size)
    result = independent_permutation(key, values, axis=1)

    perm_fn = functools.partial(independent_permutation, axis=1)

    perm_fn = shard_map(
        perm_fn,
        in_specs=(P("data",), P("data", None)),
        out_specs=P("data", None),
        mesh=mesh,
    )

    result_shard = jax.jit(perm_fn)(key, values)
    print("Results are same:", jnp.sum(jnp.abs(result - result_shard)) == 0)
```

With `jax_default_prng_impl == threefry2x32 ` I get `Results are same: True`,
But with `jax_default_prng_impl == rbg ` I get `Results are same: False`

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.28
jaxlib: 0.4.28
numpy:  1.24.3
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
jax.devices (2 total, 2 local): [cuda(id=0) cuda(id=1)]
process_count: 1

$ nvidia-smi
Wed Jun  5 12:08:42 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA H100 80GB HBM3          On  | 00000000:95:00.0 Off |                    0 |
| N/A   35C    P0              84W / 700W |    537MiB / 81559MiB |      2%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          On  | 00000000:99:00.0 Off |                    0 |
| N/A   33C    P0              88W / 700W |    537MiB / 81559MiB |      1%      Default |
|                                         |                      |             Disabled |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
+---------------------------------------------------------------------------------------+

**Comment by froystig** [comment]
I suspect that this doesn't have much to do with `shard_map` or sharding, but rather results from the `rbg` PRNG implementation's intended behavior under `vmap` (as of https://github.com/google/jax/pull/20094). When generating random numbers with `rbg`, and vmapping over keys, the values produced are not guaranteed to be the same as what we'd get from mapping generation over each key by a means other than `vmap` (e.g. `map`, or a loop).

Here is a concrete local example of what I mean by that:

```python
>>> import jax; import jax.numpy as jnp
>>> def f(k): return jax.random.choice(k, 4)
... 

>>> keys = jax.random.split(jax.random.key(17, impl='threefry2x32'), 12)
>>> jnp.stack([f(k) for k in keys])
Array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1], dtype=int32)
>>> jax.vmap(f)(keys)
Array([1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 2, 1], dtype=int32)

>>> keys = jax.random.split(jax.random.key(17, impl='rbg'), 12)
>>> jnp.stack([f(k) for k in keys])
Array([0, 0, 0, 2, 2, 0, 0, 2, 1, 0, 2, 0], dtype=int32)
>>> jax.vmap(f)(keys)
Array([0, 1, 2, 1, 1, 3, 3, 1, 0, 3, 3, 1], dtype=int32)
```

There isn't an efficient way to batch in `rbg` mode because the XLA compiler's `rng_bit_generator` operation isn't batchable over keys. So we went with this choice instead, where vmap acts as a map "in distribution" although not in value. We could do a better job of documenting this (probably [here](https://jax.readthedocs.io/en/latest/jax.random.html#advanced-rng-configuration))!
