### ISSUE TITLE
reduce_window broken on CPU

### ISSUE THREAD

**Issue by josipd** [google/jax#21672]
### Description

```
import jax
import jax.numpy as jnp

jax.lax.reduce_window(
    jnp.ones((1, 48, 48, 15), dtype=jnp.float32),
    0.,
    jax.lax.add,
    (1, 6, 6, 1),
    (1, 6, 6, 1),
    window_dilation=(1, 1, 1, 1),
    padding='VALID')
```

Produces 

```
TypeError: reduce_window window_dimensions must have every element be an integer type, got (<class 'int'>, <class 'float'>, <class 'float'>, <class 'int'>).
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.29
jaxlib: 0.4.29
numpy:  1.26.3
python: 3.11.8 (stable, redacted, redacted)
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
````

**Comment by jakevdp** [comment]
I'm unable to reproduce this on my machine.

You report JAX v0.4.29, which is not yet released. Are you running from an updated main branch?

Also, since jaxlib 0.4.29 doesn't exist yet, are you using a nightly build?

Thanks!

**Comment by jakevdp** [comment]
We determined offline that this issue does not reproduce at HEAD, but only at some intermediate commit from last week. I won't debug further unless this shows up again
