### ISSUE TITLE
Mistake (?) in the "How to think in Jax" doc

### ISSUE THREAD

**Issue by eadadi** [google/jax#21695]
### Description

Hi,
I am learning to use and to think in Jax, and I was reading the "Thinking in Jax" document.
Maybe there is a mistake in the "Static vs Traced operations" section: https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html#static-vs-traced-operations

It's written there:

> Static operations are evaluated at compile-time in Python; traced operations are compiled & evaluated at run-time in XLA

But I think it should be the opposite - Static operations are compiled and evaluated in run time in python, where traced operations are only evaluated at run-time in XLA.

### System info (python version, jaxlib version, accelerator, etc.)

No need

**Comment by jakevdp** [comment]
Hi - thanks for the question! This is correct as originally written. Static operations are only evaluated once, in Python, at trace/compile-time. Dynamic/traced operations are evaluated by XLA, after compilation, at runtime.
