### ISSUE TITLE
Unable to compile jaxlib from source

### ISSUE THREAD

**Issue by vishwakftw** [google/jax#217]
I have been trying to compile jaxlib from source, and am unable to do so due to the following error:

```
bazel-out/k8-opt/bin/external/org_tensorflow/tensorflow/compiler/xla/python/pywrap_xla.cc:6626:64: error: cannot convert 'google::protobuf::RepeatedField<long int>*' to 'google::protobuf::RepeatedField<long long int>*' for argument '3' to 'bool xla::swig::HandleRepeatedInt64Attribute(PyObject*, const char*, google::protobuf::RepeatedField<long long int>*)'
         dimension_numbers4.mutable_lhs_contracting_dimensions())) {
                                                                ^
```

This seems to be an issue with TensorFlow.

Steps to reproduce the build failure:
1. `git clone https://github.com/google/jax`
2. `python build/build.py`

I have cleared my Bazel cache by performing `rm -rf ~/.cache/bazel`, to ensure that the cached version is not used.

Python: Miniconda3
MKLDNN enabled: Yes
CUDA enabled: No

**Comment by hawkinsp** [comment]
Ah, I see what happened here. My bug :-)

The issue is that xla::int64 and google::protobuf::int64 are not the same type on some platforms.

Fix coming soon.
