### ISSUE TITLE
Problem with installing jax: cannot import name 'xla_data_pb2

### ISSUE THREAD

**Issue by sergueev** [google/jax#2172]
Hello,

I am trying to build jax with jaxlib as instructed in the manual. I tried different versions of jax and jaxlib and everytime I am getting "ImportError: cannot import name 'xla_data_pb2'" when I just import jax in python. Any ideas what I am doing wrong  ?

Thanks.
Here is my installation script attached.
[install-jax.txt](https://github.com/google/jax/files/4161923/install-jax.txt)

**Comment by hawkinsp** [comment]
What version of `jax` do you have? (e.g., `pip show jax`?)

**Comment by hawkinsp** [comment]
Also, can you verify what version of `jaxlib` was successfully installed (`pip show jaxlib`)?

**Comment by sergueev** [comment]
Currently I have :
0.1.35 for jax
0.1.23 for jaxlib  
and python 3.5

**Comment by hawkinsp** [comment]
It looks like you have very old versions of both `jax` and `jaxlib` installed. The current versions are jax: 0.1.58, jaxlib: 0.1.38.

Try:
```
pip uninstall jax jaxlib
pip install --upgrade pip
pip install --upgrade jax jaxlib
```

The `pip install --upgrade pip` is important.

**Comment by sergueev** [comment]
It's not finding a wheel for jaxlib or jax unless I specify the path for the wheel to https://storage.googleapis.com/jax-releases

**Comment by mattjj** [comment]
+1 to `pip install --upgrade pip`

**Comment by sergueev** [comment]
My impression is that I don't have a repo to the wheels . When I do e.g.  "pip install --upgrade jaxlib", I get "ERROR: No matching distribution found for jaxlib"

**Comment by hawkinsp** [comment]
What version of `pip` do you have installed (`pip show pip`?) And what platform/OS are you running on?

**Comment by sergueev** [comment]
Pip version 20.0.2 .  I can install jax with "pip install --upgrade jaxlib=0.1.58" 
but  I can't get the wheels for "pip install --upgrade jaxlib" unless I set path to https://storage.googleapis.com/jax-releases

**Comment by hawkinsp** [comment]
Can you please share:
a) what platform/OS you are using?
b) the errors that `pip` emits? i.e., exactly what you ran, and exactly what was printed.

**Comment by sergueev** [comment]
It's CentOS-7. When I do "pip install --upgrade jaxlib" I get:
ERROR: Could not find a version that satisfies the requirement jaxlib (from versions: none)
ERROR: No matching distribution found for jaxlib

**Comment by mattjj** [comment]
Take a look at #854 for a discussion of CentOS 7 support.

**Comment by hawkinsp** [comment]
I suspect you're still not using the correct version of `pip`.

To help unblock you, here are some instructions for installing JAX that I verified work on a fresh CentOS 7 virtual machine on Google Compute Engine:

```
# Install Python 3.6 using yum and enable it.
sudo yum install centos-release-scl
sudo yum install rh-python36
scl enable rh-python36 bash

# Create and activate a virtualenv, so our pip, etc. don't conflict with the system ones.
python -m venv myvenv
source myvenv/bin/activate

# Update pip to a sufficiently new version
pip install --upgrade pip

# Install jax and jaxlib
pip install --upgrade jax jaxlib

# Use JAX!
python -c "import jax; print(jax.numpy.add(1, 2))"
```

Hope that helps!
