### ISSUE TITLE
TracerBoolConversionError when jitting jax.numpy.linalg.norm

### ISSUE THREAD

**Issue by mvilucchio** [google/jax#21730]
### Description

I am having some problems when trying to `jax.jit` the norm function in `jax.numpy`. 
Ideally I would like to use the jitted version of norm for any ord that is a float and also for inf values.

The minimal working example is:

```
>>> import jax
>>> import jax.numpy as jnp
>>> a_fun = jax.jit(jnp.linalg.norm)
>>> a_fun(jnp.array([1.0,1.0]),ord=1)
```
results in 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/matteovilucchio/Documents/GitHub/linear-regression/.venv/lib/python3.12/site-packages/jax/_src/numpy/linalg.py", line 1106, in norm
    if ord is None or ord == 2:
                      ^^^^^^^^
jax.errors.TracerBoolConversionError: Attempted boolean conversion of traced array with shape bool[]..
The error occurred while tracing the function norm at /Users/matteovilucchio/Documents/GitHub/linear-regression/.venv/lib/python3.12/site-packages/jax/_src/numpy/linalg.py:1020 for jit. This value became a tracer due to JAX operations on these lines:

  operation a:bool[] = eq b c
    from line <stdin>:1 (<module>)
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerBoolConversionError
--------------------
For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.28
jaxlib: 0.4.28
numpy:  1.26.4
python: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.1.0.2.5)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='tsf-508-wpa-6-217.epfl.ch', release='22.6.0', version='Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020', machine='arm64')
```

**Comment by jakevdp** [comment]
`ord` must be static in the current implementation of `norm`. You can try this instead:
```python
>>> import jax
>>> import jax.numpy as jnp
>>> a_fun = jax.jit(jnp.linalg.norm, static_argnames=['ord'])
>>> a_fun(jnp.array([1.0,1.0]),ord=1)
Array(2., dtype=float32)
```
JAX doesn't have any implementation of `norm` that accepts traced `ord` values, but it would be easy enough to create if you wish. Somethings like this should work:
```python
@jax.jit
def norm(x, ord):
  return jnp.sum(abs(x) ** ord) ** (1 / ord)
```

**Comment by ASEM000** [comment]
It seems odd that some `jax.numpy` functions are decorated with`@partial(jax.jit, static_argn{num,name}=...)` by default and some are not. Is there is a rule to decide which function is decorated by default?

If there is no rule, then maybe new users first interacting with `jax.numpy` and `jax` transforms like `jit` should not be facing errors like this. I would say `jax.numpy` functions should be decorated by default. The downside of course is the _unexpected_ recompilation when changing some of the arguments. For this recompilation behavior, maybe it can be indicated in the docstring which arg{nums,names} are static. @jakevdp WDYT?

**Comment by jakevdp** [comment]
> Is there is a rule to decide which function is decorated by default?

Not a hard rule, but some NumPy APIs are incompatible with JIT, so we don't decorate those by default. For example `jnp.unique` cannot be JIT-compiled by default, because it produces dynamically-shaped outputs.

**Comment by ASEM000** [comment]
> Not a hard rule, but some NumPy APIs are incompatible with JIT,

To be more precise, I meant within the set of function that are compatible with jit, and can be decorated with `@partial(jax.jit, static_argn{num,name}=...)`. IIUC, within `numpy` there are:

1.  Function that are jit-compatible and decorated with static argnum/argname.
2. Function that are jit-compatible and need to be decorated with static argnum/argname under `jit`. 
3. Functions that are _not_ jit-compatible.

My suggestion was to push 2) to be like 1).

> For example jnp.unique cannot be JIT-compiled by default, because it produces dynamically-shaped outputs.

 IIRC `numpy.unique` and single argument `numpy.where` -among others- have very clear docstring with a paragraph discussing `jit` and the dynamic shape issue.

>We're working on this as part of https://github.com/google/jax/issues/21461

Looks great as always.
