### ISSUE TITLE
pmax bug on negative numbers on CPU

### ISSUE THREAD

**Issue by bondquant** [google/jax#21820]
### Description

Hi Sirs,

  `pmax` seems to be initialised with smallest representable floating-point number on CPU and therefore fails when an array consists entirely of negative numbers (such as in the example below). I have tested it on 3 different machines with identical  behaviour. GPU works well. TPUs I have no access. Code and results are below. 

```
import os

os.environ['XLA_FLAGS'] = f'--xla_force_host_platform_device_count=2'

import jax
from jax import (numpy as jnp,
                 lax)

if __name__ == '__main__':
    x = jnp.asarray([-1.0])
    devices = jax.local_devices(backend='cpu')
    x = jax.device_put_replicated(x, devices)

    print(jax.pmap(lambda u: lax.pmin(u, axis_name='i'), axis_name='i', devices=devices)(x)[0])
    print(jax.pmap(lambda u: lax.pmean(u, axis_name='i'), axis_name='i', devices=devices)(x)[0])
    print(jax.pmap(lambda u: lax.pmax(u, axis_name='i'), axis_name='i', devices=devices)(x)[0])
    # pmax in disguise
    print(jax.pmap(lambda u: -lax.pmin(jnp.negative(u), axis_name='i'), axis_name='i', devices=devices)(x)[0])
```

Returns 
```
[-1.]
[-1.]
[1.1754944e-38]
[-1.]
```
on CPU, but
```
[-1.]
[-1.]
[-1.]
[-1.]
```
on a multi-GPU machine

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.25
jaxlib: 0.4.25
numpy:  1.24.1
python: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0]
jax.devices (3 total, 3 local): [cuda(id=0) cuda(id=1) cuda(id=2)]
process_count: 1
platform: uname_result(system='Linux', node='bonerattler', release='6.5.0-35-generic', version='#35~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue May  7 09:00:52 UTC 2', machine='x86_64')

$ nvidia-smi
Wed Jun 12 08:38:37 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.78                 Driver Version: 550.78         CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA RTX A4000               Off |   00000000:03:00.0 Off |                  Off |
| 41%   51C    P2             33W /  140W |   12276MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA RTX A4000               Off |   00000000:04:00.0 Off |                  Off |
| 41%   48C    P2             29W /  140W |     175MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA RTX A4000               Off |   00000000:A1:00.0 Off |                  Off |
| 41%   52C    P2             26W /  140W |     175MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A      2325      G   /usr/lib/xorg/Xorg                              9MiB |
|    0   N/A  N/A      2577      G   /usr/bin/gnome-shell                            4MiB |
|    0   N/A  N/A   1018035      C   python                                      12250MiB |
|    1   N/A  N/A      2325      G   /usr/lib/xorg/Xorg                              4MiB |
|    1   N/A  N/A   1018035      C   python                                        160MiB |
|    2   N/A  N/A      2325      G   /usr/lib/xorg/Xorg                              4MiB |
|    2   N/A  N/A   1018035      C   python                                        160MiB |
+-----------------------------------------------------------------------------------------+

**Comment by superbobry** [comment]
I was able to reproduce using the latest JAX/jaxlib release.

**Comment by hawkinsp** [comment]
You're quite right. This is a bug in the in-process CPU collective implementation. https://github.com/openxla/xla/pull/13684 fixes.

**Comment by bondquant** [comment]
Thank you. Impressive speed!
