### ISSUE TITLE
unable to pip install jax and jaxlib

### ISSUE THREAD

**Issue by richylyq** [google/jax#2187]
Hi I am trying to install jax and jaxlib on my Windows device, but i cannot seem to get it up. This error is persistent after I `pip install -q jax==0.1.57 jaxlib==0.1.37`
```
ERROR: Could not find a version that satisfies the requirement jaxlib==0.1.37 (from versions: none)
ERROR: No matching distribution found for jaxlib==0.1.37
```

**Comment by shoyer** [comment]
Sorry, we don't support Windows yet. Please take a look at https://github.com/google/jax/issues/438 for details -- it looks like a few users may have figured out how to get this working.

**Comment by BUAA-JingXiao** [comment]
hope to support the windows soon....

**Comment by Irfan1001** [comment]
Hi, Is it still not working in Windows? can anybody confirm it?

**Comment by jakevdp** [comment]
For up-to-date information on Windows installation, see [README: Installation](https://github.com/google/jax#installation)
