### ISSUE TITLE
Build fails: Can't find amdhip64 and roctracer libs

### ISSUE THREAD

**Issue by brianrobt** [google/jax#21886]
### Description

Hello,

When building v0.4.16 on Arch Linux, I ran into an issue where the amdhip64 and roctracer libs can't be found.  It seems like JAX is looking for them under `/opt/rocm/hip` and `/opt/rocm/roctracer`, respectively.  However, both libs only exist in `/opt/rocm/lib`.  Copying the libs to where JAX is looking for them resolves the issue, but I think that work should be handled by the build script.

I've already reported this issue in the `python-jax-rocm` Arch Linux package: https://github.com/brianrobt/python-jax-rocm/issues/3

The exact command that is failing is this:

```bash
  python build/build.py --enable_rocm \
    "--rocm_amdgpu_targets=gfx803,gfx900,gfx906,gfx908,gfx90a,gfx1030,gfx1100,gfx1101,gfx1102" \
    --bazel_options=--override_repository=xla=src/xla-rocm-jaxlib-v0.4.16.tar.gz
```

Thank you,
Brian

### System info (python version, jaxlib version, accelerator, etc.)

```
OS: Arch Linux
Python: 3.12.3
jaxlib: 0.4.16
```

**Comment by hawkinsp** [comment]
v0.4.16 is quite old at this point. Does the issue still happen with a current version?

**Comment by brianrobt** [comment]
@hawkinsp, Let me try early next week and I'll get back to you.  Thanks!

**Comment by brianrobt** [comment]
The issue doesn't happen on v0.4.29.  I'm closing out the issue.
