### ISSUE TITLE
What is the recommended way of doing differentiable control flow with JIT?

### ISSUE THREAD

**Issue by noahtren** [google/jax#2188]
I have some functions that I'd like to speed up with @jax.jit, but they rely on Python-native control flow.

I'm aware of `lax.cond`, but the documentation warns that this is not differentiable (yet). I'm curious what is the most ideal way to do this. My conditionals are pretty simple -- just calling `continue` in a for loop to skip certain steps.

**Comment by shoyer** [comment]
`lax.cond` actually supports differentiation, as of last week: https://github.com/google/jax/pull/2091

So if you're feeling brave, you could install the development version of JAX and give it a try.

In general, it depends on what you are trying to do. Often Python native control flow can be avoided in favor of `np.where` (this works very well on accelerators).

**Comment by noahtren** [comment]
@shoyer that's great to hear! I will likely try this out soon. I've tried to use `np.where` as much as possible but there are some cases where it just felt much easier to explicitly write a conditional.

Thanks again!

**Comment by shoyer** [comment]
Okay, I’m going to close this for now since it looks like the initial question is answered, but feel free to reopen if you encounter unexpected difficulties.
