### ISSUE TITLE
`[CUDA12_local]` Plans for future cuda wheels

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#21898]
In the changelog of jax 0.4.28 I saw a mention that

> We anticipate that this will be the last release of JAX and jaxlib
supporting a monolithic CUDA jaxlib. Future releases will use the CUDA
plugin jaxlib (e.g. pip install jax[cuda12]).

I would like to know if you plan to keep offering the option to install a version of jaxlib without installing CUDA through pip.

The reason for that is because when using [`mpi4jax`](https://github.com/mpi4jax/mpi4jax) on HPC clusters for distributed calculations we must use the cuda libraries provided by the environment, as MPI is linked to those for fast direct device-to-device transfers.

In theory, I believe that is should be possible to simple offer an `extra` requirement called `cuda12_local` that installs the same plugin, but does not install all the nvidia packages as well.

**Comment by yashk2810** [comment]
Yes, we still offer that option with cuda plugin: https://github.com/google/jax/blob/main/setup.py#L107

It is also documented here: https://jax.readthedocs.io/en/latest/installation.html#pip-installation-nvidia-gpu-cuda-installed-locally-harder

**Comment by PhilipVinc** [comment]
amazing, thanks! 
So you're really just changing how you ship jaxlib itself, nothing else.

Sorry for the noise.
