### ISSUE TITLE
Is there a way to control the pjit to dynamically partition the input IDs into different ranks?

### ISSUE THREAD

**Issue by MoFHeka** [google/jax#21902]
I need to build a model like this:
There is a very large distributed dynamic shape Embedding, which can be seen as a hash table.
In every DP rank, when workers get the IDs input they need to transfer the IDs to another worker for lookup table. 
For example, rank 0 get [0,1,2,2], also rank 1 get [0,3,2,1]. But hash table in rank 0 only stored the key 0,2,..., and  rank 1 with 1,3,.... For now there will be a alltoallv operator, where rank 0 send [1] and receive [0,2], and rank 1 send [0,2] and receive [1]. And then lookup the value back to their origin rank.
![9bdc0d9d711b0980579cdc0eac52f8ed564322](https://github.com/google/jax/assets/90189118/d4ddf0da-e599-4349-8854-11f8e52b7430)

Note: In fact, this procedure uses the send_recv operator to implement asynchronous ring alltoall to overlap the table lookup time.

Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by superbobry** [comment]
Hi @MoFHeka, could you clarify how your question relates to JAX? JAX does not have a concept of a rank, so `jit` probably cannot do the partitioning you are describing.

**Comment by MoFHeka** [comment]
@superbobry Sorry my mistake. A simpler description might be, when I use pmap, how do I implement the all2allv operator? Among them, the data parallel dimension (batch) requires dynamic size data exchange.

For example, GPU0 and GPU1 run the data parallelism training. GPU0 get [0,1,2,2], also GPU1 get [0,3,2,1]. But hash table in GPU0 only stored the key 0,2,..., and GPU1 with 1,3,.... For now there will be an alltoallv operator, where GPU0 send [1] and receive [0,2], and GPU1 send [0,2] and receive [1]. And then lookup the value back to their origin GPUx.

**Comment by yashk2810** [comment]
Try using shard_map? https://jax.readthedocs.io/en/latest/notebooks/shard_map.html

**Comment by MoFHeka** [comment]
> Try using shard_map? https://jax.readthedocs.io/en/latest/notebooks/shard_map.html

@yashk2810 Thanks for your answer, but I don't know if shard_map supports swapping tensor with different dynamic shapes in batch dimensions between different GPU. And also I need to transform the collective operator(alltoallv) into send/recv expressions to achieve the acceleration that can be overlapped by the calculation operator.

**Comment by superbobry** [comment]
I will let Yash comment on dynamic shapes in `shard_map`, but I suspect that this use-case is not supported (since most of JAX assumes static shapes atm).

Re "transform the collective": I don't think we have send/recv operations in lax, so I'm not quite sure what kind of transform you are talking about. Are these custom JAX operations you implemented?

**Comment by MoFHeka** [comment]
@superbobry Assume I have JAX lookup table operations. 
I need to split the Ring AllToAll collective sync operator into several parts to ensure that while some data is being transferred, others are querying the hash-table to overlap the transmission overhead time.

![Ring_visualization_all_to_all](https://github.com/google/jax/assets/90189118/7e558bea-c7ac-4543-a542-0cd9984b10f2)

**Comment by MoFHeka** [comment]
@yashk2810  @superbobry I'm sorry to bother you, but I found that jax.lax.ppermute needs a tensor with the same amount of data for each sharding, while I need a tensor with the same amount of data for each sharding.

**Comment by superbobry** [comment]
I will defer the answer to Yash, as I'm not yet very familiar with sharding APIs in JAX.
