### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by jntdst** [google/jax#21940]
### Description

---> 30 import t5x
     31 from t5x import partitioning
     32 from t5x import train_state as t5x_train_state

File /kaggle/working/t5x/t5x/__init__.py:17
      1 # Copyright 2024 The T5X Authors.
      2 #
      3 # Licensed under the Apache License, Version 2.0 (the "License");
   (...)
     12 # See the License for the specific language governing permissions and
     13 # limitations under the License.
     15 """Import API modules."""
---> 17 import t5x.adafactor
     18 import t5x.checkpoints
     19 import t5x.decoding

File /kaggle/working/t5x/t5x/adafactor.py:65
     63 import jax.numpy as jnp
     64 import numpy as np
---> 65 from t5x import utils
     66 from t5x.optimizers import OptimizerDef
     67 from t5x.optimizers import OptimizerState

File /kaggle/working/t5x/t5x/utils.py:46
     44 import jax.numpy as jnp
     45 import numpy as np
---> 46 import orbax.checkpoint
     47 import seqio
     48 from t5x import checkpoints

File /opt/conda/lib/python3.10/site-packages/orbax/checkpoint/__init__.py:23
     21 import nest_asyncio
     22 from orbax.checkpoint import aggregate_handlers
---> 23 from orbax.checkpoint import args
     24 from orbax.checkpoint import checkpoint_utils
     25 from orbax.checkpoint import msgpack_utils

File /opt/conda/lib/python3.10/site-packages/orbax/checkpoint/args.py:22
     15 """Exported symbols under `orbax.checkpoint.args`."""
     16 # pylint: disable=g-importing-member, g-bad-import-order, unused-import
     17 
     18 # TODO(b/301325921): Since these are being added to the public API, make sure
     19 # that these Args are all documented.
     20 
     21 # Built-in CheckpointArgs.
---> 22 from orbax.checkpoint.array_checkpoint_handler import ArrayRestoreArgs as ArrayRestore
     23 from orbax.checkpoint.array_checkpoint_handler import ArraySaveArgs as ArraySave
     24 from orbax.checkpoint.composite_checkpoint_handler import CompositeArgs as Composite

File /opt/conda/lib/python3.10/site-packages/orbax/checkpoint/array_checkpoint_handler.py:28
     26 from orbax.checkpoint import checkpoint_args
     27 from orbax.checkpoint import future
---> 28 from orbax.checkpoint import type_handlers
     29 from orbax.checkpoint import utils
     31 CheckpointArgs = checkpoint_args.CheckpointArgs

File /opt/conda/lib/python3.10/site-packages/orbax/checkpoint/type_handlers.py:31
     29 from etils import epath
     30 import jax
---> 31 from jax.experimental.array_serialization import serialization
     32 import jax.numpy as jnp
     33 import numpy as np

File /opt/conda/lib/python3.10/site-packages/jax/experimental/array_serialization/serialization.py:36
     34 from jax._src import sharding
     35 from jax._src import sharding_impls
---> 36 from jax._src.layout import Layout, DeviceLocalLayout as DLL
     37 from jax._src import typing
     38 from jax._src import util

ImportError: cannot import name 'DeviceLocalLayout' from 'jax._src.layout' (/opt/conda/lib/python3.10/site-packages/jax/_src/layout.py)

### System info (python version, jaxlib version, accelerator, etc.)

Kaggle site

**Comment by superbobry** [comment]
Please share the version of `jax` and `jaxlib` you are using.

Since you are mentioning Kaggle, it is probably an issue with the notebook kernels Kaggle uses and not JAX itself.

**Comment by mattjj** [comment]
I'm going to close this issue for inactivity, but please reopen (or open a new one) if you can provide reproduction instructions.
