### ISSUE TITLE
Nit: Inconsistent use of `Example` and `Examples` in docstrings

### ISSUE THREAD

**Issue by dfm** [google/jax#21979]
### Description

Looking through the `jax.numpy` docstrings (in relation to #21461) I noticed that we're currently inconsistent with the use of `Example` vs `Examples` as a section heading. Perhaps we should choose one (I propose `Examples`) and stick to it?

@jakevdp WDYT?

### System info (python version, jaxlib version, accelerator, etc.)

N/A

**Comment by jakevdp** [comment]
`Examples` sounds good to me
