### ISSUE TITLE
jax.xla_computation as_hlo_text()

### ISSUE THREAD

**Issue by aoshujiaocheng** [google/jax#21990]
```
import jax

def f(x): return jax.numpy.sin(jax.numpy.cos(x))
c = jax.xla_computation(f)(3.)
print(c.as_hlo_text())
```
How to convert `c.as_hlo_text()` into `c`?

**Comment by justinjfu** [comment]
JAX doesn't have python bindings for parsing HLO strings, however the machinery exists in XLA/C++. If you just want to run the function, you could perhaps try running the module using XLA's infrastructure (run_hlo_module  - https://openxla.org/xla/tools).

Also as a heads up - jax.xla_computation will be deprecated with the upcoming 0.4.30 release.

**Comment by yashk2810** [comment]
Note 0.4.30 is released and jax.xla_computation is deprecated. Please use `jax.jit(f).lower(3.).compiler_ir('hlo')` as the replacement.

**Comment by mattjj** [comment]
I think @justinjfu 's answer covered things, but let us know if I'm mistaken.

**Comment by mattjj** [comment]
That is, it's not in scope for JAX to add a parse-xla-programs feature, but there are such features in XLA.

**Comment by aoshujiaocheng** [comment]
Thank you @justinjfu @mattjj for your help! My issue has been resolved thanks to your assistance. Your reply was very helpful！
