### ISSUE TITLE
Tests for np.linalg.cond fail on GPU

### ISSUE THREAD

**Issue by gnecula** [google/jax#2203]
Newly added test linalg_tests.testCond (#2125) are failing in our internal regression testing. I have disabled them for now, please take a look.

**Comment by gnecula** [comment]
@StephenHogg please take a look

**Comment by StephenHogg** [comment]
Hi @gnecula - I unfortunately can't see how your build failed or what error messages it produced. The laptop I have access to doesn't have a GPU that I can really test anything on (integrated graphics only), is there anything you might recommend as a way of investigating this?

**Comment by gnecula** [comment]
You are right, I am sorry, I meant to add more detail. 
Here are the failures I saw (all for the assertion on line 606 in linalg_test.py):

============
Test
NumpyLinalgTest.testCond_shape=float32[5,5,5]_pnorm=2
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001

x and y nan location mismatch:
 x: array([nan, nan, nan, nan, nan], dtype=float32)
 y: array([7.250044, 9.169751,      nan, 5.428039, 3.066624], dtype=float32)
============
Test
NumpyLinalgTest.testCond_shape=float64[5,5,5]_pnorm=-2
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001

x and y nan location mismatch:
 x: array([nan, nan, nan, nan, nan])
 y: array([0.13793 , 0.109054,      nan, 0.184229, 0.326091])
============
Test
NumpyLinalgTest.testCond_shape=float64[5,5,5]_pnorm=2
AssertionError: 
Not equal to tolerance rtol=0.001, atol=0.001

x and y nan location mismatch:
 x: array([nan, nan, nan, nan, nan])
 y: array([7.250044, 9.169751,      nan, 5.428039, 3.066624])

**Comment by jakevdp** [comment]
It looks like this issue has been fixed.
