### ISSUE TITLE
Command to build jaxlib?

### ISSUE THREAD

**Issue by yurivict** [google/jax#22046]
I need to create the FreeBSD port for jaxlib.
Its [PYPI page](https://pypi.org/project/jaxlib/) only contains wheel files and points here as a project page.
The top-level project here builds the ```jax``` wheel.

How to build the ```jaxlibs``` wheel?

**Comment by jakevdp** [comment]
There is information on how to build jaxlib at https://jax.readthedocs.io/en/latest/developer.html#building-or-installing-jaxlib

Please let us know if anything is unclear!

**Comment by mattjj** [comment]
I think this issue is resolved, but let us know if I'm mistaken.
