### ISSUE TITLE
Batching rule for 'sort_key_val' not implemented

### ISSUE THREAD

**Issue by noahstier** [google/jax#221]
I have implemented argsort like this:
```
@jax.numpy.lax_numpy._wraps(onp.argsort)
def argsort(a, axis=-1, kind='quicksort', order=None):
    assert(a.ndim == 1) # starting simple
    vals = np.arange(len(a), dtype=int)
    sorted_keys, sorted_vals = jax.lax.sort_key_val(keys=a, values=vals)
    return sorted_vals
```

This works:
`argsort(np.ones(3))`

And I can also write an argsort that works with 2d arrays, but instead I would like to use vmap so I don't need to rewrite my code with a batch dimension.

But using vmap gives me an error:
`jax.vmap(argsort)(np.ones((3, 3)))`
`NotImplementedError: Batching rule for 'sort_key_val' not implemented`

So I am trying to implement the batch rule for `jax.lax.sort_key_val`, but it is more complicated than eg https://github.com/google/jax/pull/82 because `jax.lax.sort_key_val` returns multiple values, and the batching code assumes only a single return value.

I've tried a few things but it's tricky. Here's an attempt:
```
def sort_key_val_batched(batched_args, batch_dims, dimension=-1):
    keys, values = batched_args
    sorted_keys, sorted_values = jax.lax.sort_key_val_p.bind(
        keys=keys,
        values=values,
        dimension=dimension
    )
    return sorted_keys, 0
jax.batching.primitive_batchers[jax.lax.sort_key_val_p] = sort_key_val_batched
```

But:
`jax.vmap(argsort)(np.ones((3, 3)))`
`RuntimeError: Invalid argument: Sort keys and values dimensions must match. Keys shape is: f32[10,3], Values shape (operand index 1) is: s32[3]:`
In other words the batching rule recieves the full 2d keys array but only one row at a time of the values array. Not sure how to handle this.

One potential workaround would be to use `np.sort(order=...` to sort rows in place where one column is the values to sort by, and the other column is indices:
```
@jax.numpy.lax_numpy._wraps(onp.argsort)
def jax_argsort(a, axis=-1, kind='quicksort', order=None):
    assert(a.ndim == 1) # starting simple
    inds = np.arange(len(a), dtype=int)
    inds = np.expand_dims(inds, 1)
    a = np.expand_dims(a, 1)
    a = a.view('i8,i8')
    tmp = np.concatenate((a, inds), axis=1)
    tmp_sorted = np.sort(a, order=['f0'])
    sort_inds = tmp_sorted[:, 1]
    return sort_inds
```
But jax does not support the order keyword to np.sort.

Any ideas for a solution or workaround?

**Comment by mattjj** [comment]
Thanks for digging into this! You're on the right track, but you're right that `sort_key_val` is especially tricky.

I don't have any specific suggestions yet, but I'll try to poke at it this week when I can.

**Comment by mattjj** [comment]
In #234 we merged some commits that add a batching rule for `sort_key_val` (so you can use it with vmap) and also add `argsort` to `jax.numpy`. They're only lightly tested, so please reopen if you notice anything amiss with these (or open a new issue if you run into something else!).

**Comment by noahstier** [comment]
Great, thank you for adding this!
