### ISSUE TITLE
`jax.grad` wrt discrete parameters, or anythin that is not diff'able.

### ISSUE THREAD

**Issue by bayerj** [google/jax#2215]
Here is a minimal example of a function being differentiated and then fed with discrete inputs:

```
def func(params):
    c = params['c']
    d = params['d']
    return d * c ** 2


d_func = jax.grad(func)
d_func({'c': 2., 'd': 1})
```
Note that `d=1`, an int, here. Jax bails out for perfect reasons of `d` not being continuous:

```
TypeError: Primal inputs to reverse-mode differentiation must be of float or complex type, got type int32
```

Is there a way to make Jax ignore this part? 

I tried explicitly marking `d` to be of no use for the gradients by via `d = jax.lax.stop_gradient(params['d'])` and also tried a `jax.custrom_gradient` that returns `0`.

If not, is there a best practice on how to apply `jax.grad` in a way that we can feed in objects which explicitly expose their "tangent space" such that meta information can be kept in there as well?

**Background:** I am currently trying to build a convenience layer on top of Jax which encapsulates parameters. The vehicle is `jax.tree_utils.pytree_register_node`, with which I convert the encapsulating objects to PyTrees and back.

This is great because then I can call `jax.grad(f)` directly where `f` takes objects which are registered as a PyTree.

The problem starts when these objects also carry meta information. For example, I might want them to hold their respective keys for random number generation. I might want to have some other meta information in there, such as transfer functions or the like.

**Comment by bayerj** [comment]
For those that have a similar problem, I have devised a workaround. The idea is to go up one level and solve this issue on the level of taking a step with an optimizer. On that level, we can pull out those parameters that one cannot diff wrt, construct the gradient wrt the remaining ones, and keep the others constant.

All it takes is calling `make_resilient_step(loss, sample_params, split, join, optimizer)` where `loss` is the original loss function, `sample_params` is some example parameters (from which the non-trainable ones will be picked), `split` takes the whole set of parameters and returns the diff'able ones and an auxiliary variable, `join` merges the diff'able pars and the auxiliary variable back together.

See this gist: https://gist.github.com/bayerj/4f8d2da5325cf0c69626ee302a0fd8f7

It feels very much like a hack, but all I could come up with without messing with internals.

**Comment by jekbradbury** [comment]
See also https://github.com/google/jax/pull/1439

**Comment by hawkinsp** [comment]
This was fixed by the addition of the `allow_int` argument to `grad`!
