### ISSUE TITLE
RNN's in staxs

### ISSUE THREAD

**Issue by david-waterworth** [google/jax#2224]
I'm doing research into time-series / regression RNN models. I find jax/stax quite useful since it's easy to try different approaches etc. I'm interested in thoughts on what I've done so far, I'm happy to contribute as a pull request.

I created a new combinator called `sequential` which uses `lax.scan` - the implementation of the forward function is:

    def apply_fun(params, inputs, **kwargs):
        rng = kwargs.pop("rng", None)
        rngs = random.split(rng, nlayers) if rng is not None else (None,) * nlayers
        inputs, state = inputs

        def scan_fun(x0, x):
            inputs = (x, x0)

            for fun, param, rng in zip(apply_funs, params, rngs):
                inputs = fun(param, inputs, rng=rng, **kwargs)
            output, state = inputs
            return state, output

        state, output = lax.scan(f=scan_fun, init=state, xs=inputs)
        return output

This requires all the composed layers to accept/return a tuple (inputs, state). Because all the existing layers are single input / single output I created a second combinator which as follows

    def apply_fun(params, inputs, **kwargs):
        inputs, state = inputs
        rng = kwargs.pop("rng", None)
        rngs = random.split(rng, nlayers) if rng is not None else (None,) * nlayers
        for fun, param, rng in zip(apply_funs, params, rngs):
            inputs = fun(param, inputs, rng=rng, **kwargs)
        return inputs, state

My vanilla RNN implementation is simply

    def apply_fun(params, inputs, **kwargs):
        inputs, state = inputs
        Ws, Wi, b = params

        return np.dot(state, Ws) + np.dot(inputs, Wi) + b, state

And I can compose as follows

```
init_fun, apply_fun = serial(
    sequential(RNN(3), feedforward(Sigmoid)), 
    Dense(1), 
    Sigmoid
)
```

I'm wondering if there's a better approach which fits in the framework better (or follows existing conventions)? It seems in general NN layers are assumed to be single input / single output which makes composition harder when there are feedforward/feedback connections.

**Comment by jacobjinkelly** [comment]
[Haiku](https://github.com/deepmind/dm-haiku) is a similar framework which implements RNNs in JAX, perhaps you could have a look at that?

**Comment by dynamicwebpaige** [comment]
@mattjj and @gnecula: Would it make sense to aggregate Stax feature requests for `google/jax` into a doc for the JAX-y high-level APIs teams (Haiku, Flax, etc.)? 

Or to tag them with `high-level APIs`, so they're easily searchable?

**Comment by hawkinsp** [comment]
Closing since we want to encourage users to use more fully featured neural network libraries like Haiku and Flax.

Stax is intended as an example to inspire people about what is possible. If it works for you, great! However we don't plan to evolve it beyond its current state, so I think the best plan would be to look at RNNs in the context of one of the more fully featured libraries.
