### ISSUE TITLE
static_argnames does not support unicode argument names

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#22250]
### Description

When using unicode argnames, `static_argnames` breaks.
Admittedly this is not super-common in Python-land, but I find it very handy to write mathematical formulas.

```python
python-3.11.2 ❯ python
Python 3.11.2 (main, Apr  7 2023, 16:35:55) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax
>>> def f(Vϕ_logfun, x):
...  return Vϕ_logfun(x)
...
>>> jax.jit(f, static_argnames="Vϕ_logfun")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippo.vicentini/Documents/pythonenvs/netket/python-3.11.2/lib/python3.11/site-packages/jax/_src/api.py", line 281, in jit
    return pjit.make_jit(
           ^^^^^^^^^^^^^^
  File "/Users/filippo.vicentini/Documents/pythonenvs/netket/python-3.11.2/lib/python3.11/site-packages/jax/_src/pjit.py", line 529, in make_jit
    jit_info = _parse_jit_arguments(
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/filippo.vicentini/Documents/pythonenvs/netket/python-3.11.2/lib/python3.11/site-packages/jax/_src/pjit.py", line 447, in _parse_jit_arguments
    donate_argnums, donate_argnames, static_argnums, static_argnames = resolve_argnums(
                                                                       ^^^^^^^^^^^^^^^^
  File "/Users/filippo.vicentini/Documents/pythonenvs/netket/python-3.11.2/lib/python3.11/site-packages/jax/_src/api_util.py", line 541, in resolve_argnums
    _validate_argnames(signature, static_argnames, "static_argnames")
  File "/Users/filippo.vicentini/Documents/pythonenvs/netket/python-3.11.2/lib/python3.11/site-packages/jax/_src/api_util.py", line 217, in _validate_argnames
    raise ValueError(f"Jitted function has invalid argnames {invalid_argnames} "
ValueError: Jitted function has invalid argnames {'Vϕ_logfun'} in static_argnames. Function does not take these args.
```

### System info (python version, jaxlib version, accelerator, etc.)

jax 0.4.30

**Comment by superbobry** [comment]
This looks like a Python issue:

```
>>> import inspect
>>> sig = inspect.Signature.from_callable(lambda Vϕ_logfun: ...)
>>> 'Vϕ_logfun' in sig.parameters
False
>>> sig.parameters
mappingproxy(OrderedDict([('Vφ_logfun', <Parameter "Vφ_logfun">)]))
```

`inspect.Signature` uses the `ast` module to reconstruct the signature, and the parser seems to normalize `Vϕ_logfun` to `Vφ_logfun`

```
>>> import ast
>>> ast.dump(ast.parse("Vϕ_logfun"))
"Module(body=[Expr(value=Name(id='Vφ_logfun', ctx=Load()))], type_ignores=[])"
```

**Comment by superbobry** [comment]
I think this is where the normalization (to NFKC) is happening: https://github.com/python/cpython/blob/7c66906802cd8534b05264bd47acf9eb9db6d09e/Parser/pegen.c#L488-L512.

Also,

```
>>> unicodedata.normalize("NFKC", "ϕ")
'φ'
```

**Comment by superbobry** [comment]
Apparently, this behavior is documented in https://docs.python.org/3/reference/lexical_analysis.html#identifiers.

**Comment by superbobry** [comment]
Here is another consequence of using an unnormalized unicode character in an parameter name:

```
>>> (lambda Vϕ_logfun: ...)(**{"Vϕ_logfun": 42})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: <lambda>() got an unexpected keyword argument 'Vϕ_logfun'
```

**Comment by superbobry** [comment]
To conclude, I guess we could do the normalization for `static_argnames=`, but using non-NFKC-normalized characters is still potentially a footgun.

**Comment by superbobry** [comment]
I thought about this a bit more and decided to keep the current behavior, because normalization could be just as surprising as lack of it.

**Comment by shoyer** [comment]
Potentially we could raise a more informative error message about the existence of non-normalized characters?

**Comment by PhilipVinc** [comment]
> I thought about this a bit more and decided to keep the current behavior, because normalization could be just as surprising as lack of it.

I understand. It's probably on me for attempting to use 2020s technologies like unicode in modern programming languages (I'm complaining about python here, not jax :) )

I guess the underlying problem is that Python does not normalise source code, while Julia (where I picked up the habit of using unicode characters for math formulas) does it. So clearly it's on me.

> Potentially we could raise a more informative error message about the existence of non-normalized characters?

You could, but I do understand it's quite a bit of extra effort for you for an exotic use-case.

Again, sorry for the noise!
