### ISSUE TITLE
ModuleNotFoundError: No module named 'jax.experimental.export.shape_poly

### ISSUE THREAD

**Issue by TomasAndersonFang** [google/jax#22286]
### Description

When I import the following API, I got the error `ModuleNotFoundError: No module named 'jax.experimental.export.shape_poly'`. So I want to know `shape_poly` is already removed or replaced?
```
from jax.experimental.export.shape_poly import InconclusiveDimensionOperation
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30
jaxlib: 0.4.30
numpy:  1.26.4
python: 3.11.9 (main, Apr 19 2024, 11:43:47) [Clang 14.0.6 ]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='Sens-MacBook-Pro.local', release='23.4.0', version='Darwin Kernel Version 23.4.0: Fri Mar 15 00:19:22 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T8112', machine='arm64')
```

**Comment by TomasAndersonFang** [comment]
I found [issue-18978](https://github.com/google/jax/issues/18978) seems to report the same problem, in which you transferred it to `jax.experimental.export.shape_poly`.

**Comment by jakevdp** [comment]
The code formerly in `jax.experimental.shape_poly` is now part of the public API under `jax.export`.

For the particular symbol you're looking for, you can use `jax.core.InconclusiveDimensionOperation`.

**Comment by TomasAndersonFang** [comment]
Thanks for your reply.
