### ISSUE TITLE
Profiler fails on kaggle tpu v3-8 notebook

### ISSUE THREAD

**Issue by Lime-Cakes** [google/jax#22294]
### Description
While on kaggle notebook, upgrading to newer version of jax[tpu] breaks profiler.  The follower command was used. (tested with 0.4.29, 0.4.30)
`!pip install -U optax jax[tpu]==0.4.30 -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`

Running a simple example code (as followed) caused an error
```
with jax.profiler.trace("/tmp/jax-trace", create_perfetto_link=True):
  # Run the operations to be profiled
  key = jax.random.key(0)
  x = jax.random.normal(key, (5000, 5000))
  y = x @ x
  y.block_until_ready()
```
It caused the following error.
```
WARNING: Logging before InitGoogle() is written to STDERR
E0000 00:00:1720206589.371430    9554 common_lib.cc:818] Could not set metric server port: INVALID_ARGUMENT: Could not find SliceBuilder port 8471 in any of the 0 ports provided in `tpu_process_addresses`="local"
=== Source Location Trace: ===
learning/45eac/tfrc/runtime/common_lib.cc:483
jax:    0.4.29
jaxlib: 0.4.29
numpy:  1.26.4
python: 3.10.14 (main, May 14 2024, 08:39:53) [GCC 12.2.0]
jax.devices (8 total, 8 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1) ... TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0) TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
process_count: 1
platform: uname_result(system='Linux', node='88c1b3bf794b', release='6.1.42+', version='#1 SMP PREEMPT_DYNAMIC Sun Oct  8 14:23:56 UTC 2023', machine='x86_64')

2024-07-05 19:09:53.244284: F external/local_xla/xla/stream_executor/tpu/tpu_executor_init_fns.inc:25] TpuExecutor_AllocateStream not available in this library.
https://symbolize.stripped_domain/r/?trace=7c7d8eec9e2c,7c7d8ee7b04f&map= 
*** SIGABRT received by PID 9554 (TID 9554) on cpu 31 from PID 9554; stack trace: ***
PC: @     0x7c7d8eec9e2c  (unknown)  (unknown)
    @     0x7c7966e9c181        944  (unknown)
    @     0x7c7d8ee7b050  (unknown)  (unknown)
    @     0x7c7d8ed5f4f0  (unknown)  (unknown)
https://symbolize.stripped_domain/r/?trace=7c7d8eec9e2c,7c7966e9c180,7c7d8ee7b04f,7c7d8ed5f4ef&map= 
E0705 19:09:53.263036    9554 coredump_hook.cc:316] RAW: Remote crash data gathering hook invoked.
E0705 19:09:53.263053    9554 client.cc:269] RAW: Coroner client retries enabled, will retry for up to 30 sec.
E0705 19:09:53.263058    9554 coredump_hook.cc:411] RAW: Sending fingerprint to remote end.
E0705 19:09:53.263080    9554 coredump_hook.cc:420] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] stat failed on crash reporting socket /var/google/services/logmanagerd/remote_coredump.socket (Is the listener running?): No such file or directory
E0705 19:09:53.263087    9554 coredump_hook.cc:472] RAW: Dumping core locally.
E0705 19:10:28.370369    9554 process_state.cc:805] RAW: Raising signal 6 with default behavior
Aborted (core dumped)
```

Also tested without actually running any jax computation, and still got same error.
```
import jax
jax.print_environment_info()
with jax.profiler.trace("/tmp/jax-trace"):
    print('wtf')
```

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.29
jaxlib: 0.4.29
numpy:  1.26.4
python: 3.10.14 (main, May 14 2024, 08:39:53) [GCC 12.2.0]
jax.devices (8 total, 8 local): [TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0) TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1) ... TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0) TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]
process_count: 1
platform: uname_result(system='Linux', node='88c1b3bf794b', release='6.1.42+', version='#1 SMP PREEMPT_DYNAMIC Sun Oct  8 14:23:56 UTC 2023', machine='x86_64')

**Comment by Lime-Cakes** [comment]
Also tested with jax version 0.4.30. Same result

**Comment by djherbis** [comment]
@Lime-Cakes Can you share public Kaggle notebook that fully repos?

One other thing you can usually try is adding `!pip install tensorflow-cpu` before anything else.
Sometimes, having tensorflow-tpu installed can break the other TPU-enabled frameworks.

**Comment by skye** [comment]
Also, are you by any chance updating jax + jaxlib without using the full jax[tpu] command? https://github.com/google/jax?tab=readme-ov-file#instructions

**Comment by Lime-Cakes** [comment]
> @Lime-Cakes Can you share public Kaggle notebook that fully repros?
> 
> One other thing you can usually try is adding `!pip install tensorflow-cpu` before anything else. Sometimes, having tensorflow-tpu installed can break the other TPU-enabled frameworks.

Here [is a public library](https://www.kaggle.com/code/liminchen1/tpu-profiler-error)

I realized it only occurs when updating jax to 0.4.30 version. Testing with kaggle's native 0.4.23 doesn't seem to trigger the error. 

`!pip install tensorflow-cpu` fixes the problem. So for anyone stumbling upon the same error, do `!pip install tensorflow-cpu`
