### ISSUE TITLE
wildy different training results with diffferent versions of jax/jaxlib/flax

### ISSUE THREAD

**Issue by notnot** [google/jax#22292]
### Description

I tried running the jax-ddim code found on https://github.com/daigo0927/jax-ddim on my machines. I can't get good results, like the author could. I tried several versions of jax and am seeing wildly different results. Some jax versions even lead to NaN outputs.
I have been unable to reproduce the setup that the author of the repository used, with which he got good results. Can some of the jax experts try this Denoising Diffusion Implicit Model and figure out why the jax operations aren't doing what they are supposed to be doing?
Note that the jax-ddim project is a port of the keras ddim tutorial. When i run the keras code on my machines, i do get good results.
So somewhere something is not right in jax.  

### System info (python version, jaxlib version, accelerator, etc.)

python 3.12.4
jax: several versions
flax: several versions
CUDA 12.2

**Comment by superbobry** [comment]
Hi @notnot, I think this is a question for the jax-ddim author/maintainer. 

The versions [listed in the README](https://github.com/daigo0927/jax-ddim?tab=readme-ov-file#setup) are quite old, so I wouldn't be surprised if the results are not reproducible exactly with the latest JAX etc.

Feel free to open a new issue if you find specific discrepancies. We would need a minimal reproducer (e.g. a function using JAX APIs) to be able to diagnose and address those.

**Comment by notnot** [comment]
Yes these are old versions he tried it with. The sad fact is that with all the newer versions i tried, the results are no good. I know it is a hard problem to diagnose. if it were not, i would have attempted it myself. I have a plan of approach which would be to compare the keras original and the jax port, with inputs and networks initialised exactly the same, then see where the differences are when calling the model. I hoped the jax team would have handy testing infrastructure ready for this kind of thing.   

Of course i asked the author first, but never got a reply :(

**Comment by notnot** [comment]
I've been experimenting some more. It turns out that the training is stable when using float64 precision (jax version 0.4.30).
This isn't a practical temporary fix though, as my GPU doesn't seem to accelerate 64-bit convolutions. 
I've started a training on the CPU now, using float32. Will report the results later!

**Comment by notnot** [comment]
Training on CPU with float32 precision is stable as well. 
Conclusion: the DDIM code is written properly, as it gives good results with JAX on CPU and on GPU with float64 precision.
The flaw is in the GPU float32 path.

**Comment by notnot** [comment]
Happy update:
after installing the latest jax (0.4.31) the training is stable, using float32 on GPU, jay!
It seems that the flaw has been fixed. Congrats!
