### ISSUE TITLE
DeviceArray.reshape() raises pytype attribute error

### ISSUE THREAD

**Issue by lisa-1010** [google/jax#2232]
When doing type checking with `pytype` on a`DeviceArray` that I  call `reshape()` on, I'm getting an attribute error:
```No attribute 'reshape' on jax.interpreters.xla.DeviceArray [attribute-error]```

The issue here is that JAX dynamically injects methods like `reshape()` into `DeviceArray`, which `pytype` doesn't recognize. This can be fixed by adding the magic attribute `_HAS_DYNAMIC_ATTRIBUTES = True` to the `DeviceArray` class.

Dummy code to reproduce type checking error:

```py
from jax.interpreters.xla import DeviceArray
import jax.numpy as jnp

def flatten(a: DeviceArray):
  a.reshape((1, -1))
  return a

if __name__ == '__main__':
  flatten(jnp.ones((2, 2)))
```

**Comment by jakevdp** [comment]
This has been fixed in the time since it was reported; `jnp.ndarray` now includes an abstract base class that defines methods in the appropriate way, so this typechecks correctly:
```python
def flatten(a: jnp.ndarray):
  a.reshape((1, -1))
  return a
```
