### ISSUE TITLE
Partial of a vmap function

### ISSUE THREAD

**Issue by xiaotai-yang** [google/jax#22339]
### Description

For the following example code:

```python
# Example usage
import jax
import jax.numpy as jnp
from jax import vmap

@partial(vmap, in_axes=(None, 0))
def f(y, x):
    return x + y
x_var = jnp.arange(10)

func_ = partial(f, x=x_var)
func_(1)
```
The following error is raised: 
```
ValueError: vmap in_axes must be an int, None, or a tuple of entries corresponding to the positional arguments passed to the function, but got len(in_axes)=2, len(args)=1
```
### System info (python version, jaxlib version, accelerator, etc.)

python 3 (ipykernel)
jax 0.4.30

**Comment by jakevdp** [comment]
Agreed with @vfdev-5: this is working as documented, though I understand the behavior around `vmap` and keywords can be confusing. For what it's worth, this has nothing to do with `partial`: you can get the same error when calling the function directly with a keyword argument:
```python
f(1, x=x_var)  # ValueError
```
We've talked about changing the way that `vmap` handles explicit keyword arguments, but this would be a large breakage in backward compatibility, so it's probably not something we'll change.
