### ISSUE TITLE
XLA_in_Python notebook fails to build in RTD with XLA shape error

### ISSUE THREAD

**Issue by gnecula** [google/jax#2236]
The [error](https://readthedocs.org/projects/jax/builds/10443704/) is:
```
RuntimeError: Invalid argument: Argument does not match host shape or layout of computation parameter 0: want (f32[], f32[], s32[]), got f64[3]{0}
```
This notebook renders Ok if I open it in the public http://colab.research.google.com, and also on my laptop when running sphinx-build. Perhaps there is a version mismatch with jaxlib in RTD? In the RTD build logs linked above I see:
```
Collecting jaxlib
  Downloading jaxlib-0.1.39-cp37-none-manylinux2010_x86_64.whl 
```

  

For now, I have disabled the RTD auto rendedering of the XLA_in_Python notebook.

**Comment by hawkinsp** [comment]
@zhangqiaorjc recently revived this notebook, so I believe this issue is fixed.
