### ISSUE TITLE
INVALID_ARGUMENT: Mismatched PJRT plugin PJRT API version 

### ISSUE THREAD

**Issue by DefTruth** [google/jax#22416]
### Description

```bash
RuntimeError: Unable to initialize backend 'cuda': INVALID_ARGUMENT: Mismatched PJRT plugin PJRT API version (0.54) and framework PJRT API version 0.51).
```

### System info (python version, jaxlib version, accelerator, etc.)

```bash
pip install jaxlib==0.4.28+cuda12.cudnn89 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install "jax[cpu]==0.4.28" -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

**Comment by justinjfu** [comment]
Hi,

It's possible that there was an issue with the release. As a temporary workaround you can set the environment flag `ENABLE_PJRT_COMPATIBILITY=true`. Does this problem still persist if you install the latest JAX version (v0.4.30)?

**Comment by DefTruth** [comment]
can not find v0.4.30 for cudnn89

**Comment by DefTruth** [comment]
new error:
```bash
E0715 18:02:17.586518  591934 cuda_dnn.cc:523] Loaded runtime CuDNN library: 9.0.0 but source was compiled with: 9.1.1.  CuDNN library needs to have matching major version and equal or higher minor version. If using a binary install, upgrade your CuDNN library.  If building from sources, make sure the library loaded at runtime is compatible with the version specified during compile configuration.
```
but i have install 0.4.28+cuda12.cudnn89

**Comment by justinjfu** [comment]
What hardware are you running on?

Could you print out the output of `nvidia-smi`, `pip list`, and `import jax; jax.print_environment_info()`? I could try to reproduce on my end.

**Comment by DefTruth** [comment]
This problem was solved after I decided not to use conda
