### ISSUE TITLE
jax.numpy.digitize doesn't work with shape polymorphism

### ISSUE THREAD

**Issue by tchatow** [google/jax#22489]
### Description

Error when tracing with shape polymorphism in jax.numpy.digitize
```
  File ".../lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py", line 7548, in searchsorted
    dtype = int32 if len(a) <= np.iinfo(np.int32).max else int64
                     ^^^^^^
TypeError: '_DimExpr' object cannot be interpreted as an integer
```

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30
jaxlib: 0.4.30
numpy:  2.0.0
```

**Comment by mattjj** [comment]
Thanks for reporting this! Any chance you can share a repro?

**Comment by tchatow** [comment]
Here's a simple example
```
N, = jax.export.symbolic_shape("N")
f = jax.export.export(jax.jit(jnp.digitize))

shape0 = jax.ShapeDtypeStruct((10,), jnp.int32)
shape1 = jax.ShapeDtypeStruct((N,), jnp.int32)
f(shape0, shape1)
```

**Comment by mattjj** [comment]
This is trickier than I thought; if we fix that local issue (e.g. by replacing `len(a)` with `a.shape[0]`) then we get a downstream issue that the searchsorted implementations rely on static sizes (or at least size bounds).

@jakevdp any ideas?

**Comment by jakevdp** [comment]
Not sure... it's still not clear to me to what extent we should expect shape polymorphism to be supported in JAX APIs. Do we have those goals documented anywhere?

**Comment by tchatow** [comment]
I narrowed my use case to only needing the result of `jax.eval_shape` with symbolic dimension variables, and not full export support. This still errors on digitize. Since the result shape is well known - ints in the same shape as `x`, the following code appears to work:

```
def exportable_digitize(x, bins):
    if any(jax.export.is_symbolic_dim(d) for d in bins.shape):
        return x.astype(jnp.int32)

    return jnp.digitize(x, bins)
```

Is there a way to reliably check that a function is called inside shape evaluation?

**Comment by tchatow** [comment]
@jakevdp I also observe `np.linalg.inv` polymorphism works in 0.4.31 but regressed in main. Would this be a bug or feature request?

**Comment by gnecula** [comment]
I can take this on. The shape polymorphism support for the JAX APIs is (always) work in progress, but it is pretty far along. I now fix issues as they pop up.
