### ISSUE TITLE
ConcreteArray has no attribute copy

### ISSUE THREAD

**Issue by Jakob-Unfried** [google/jax#2248]
I wanted to use `.copy()` on arrays to avoid working on views and corrupting values elsewhere.
During tracing jax called my function with a `ConcreteArray` and threw an error since these don't support `.copy()`.

Is there a different way i should have done this or should `ConcreteArray`s support a dummy `.copy()` that just returns `self`?

**Comment by shoyer** [comment]
Can you share a full code example? How do you end up with a ConcreteArray?

**Comment by Jakob-Unfried** [comment]
Sure, ill be back soon with a minimal reproducer

**Comment by Jakob-Unfried** [comment]
@ shoyer not sure if you get notified if I edit, so here goes another ping

**Comment by shoyer** [comment]
Here's a simpler example:
```python
import jax
import numpy as np
jax.value_and_grad(lambda x: x.copy())(np.ones((2,)))
```

I guess one reason why `copy()` may not exist on `ConcreteArray` (or its base class `ShapedArray`) is that it the semantics of copying a tracer are not entirely clear:
1. should a copy return the same object on a tracer?
2. should a copy return a "disconnected copy"?

The later is not really possible for tracers, but it may be what users expect.

**Comment by shoyer** [comment]
For context, it may be worth noting that JAX doesn't support in-place operations on arrays, so copies are generally not useful.

Nonetheless, is maybe worth adding a dummy `copy()` method to facilitate duck typing. I think dask does this.

**Comment by Jakob-Unfried** [comment]
You are completely correct!
I was still in the `onp` mindset and trying to protect my class attributes from being a view of an array that could be in-place mutated elsewhere and thus change my class attribute arrays uncontrollably. But since jax doesn't do that, I don't even need to copy.
So for my use-case, just copying the list, i.e. `self._tensors = tensors.copy()` list should be completely fine.

Thanks!

In the end, it was useful for me to run into this error, since it brought my mistake to light.

For my part, I don't see that any changes are called for.
Do you want to close this, or is it still an open qustion if `ShapedArray` and its subclasses should support `.copy()` ?

**Comment by shoyer** [comment]
> Do you want to close this, or is it still an open qustion if `ShapedArray` and its subclasses should support `.copy()` ?

I think this is still a valid open question.

**Comment by mattjj** [comment]
I briefly tried a couple solutions, and I think #2257 is a good balance: add the method, and just do what `np.copy` does, which is just `np.array(x, copy=True)`.

**Comment by gnecula** [comment]
Reopening this bug, because we had to revert the fix due to internal test failures.

**Comment by jakevdp** [comment]
It looks like the original issue is now fixed.
