### ISSUE TITLE
jaxlib is not matching with cuda version 12. 

### ISSUE THREAD

**Issue by khandokaryogesh** [google/jax#22522]
I am trying to use GPU to run scripts but consistently the errors is coming "ERROR: Could not find a version that satisfies the requirement jaxlib==0.4.29+cuda12.cudnn88 (from versions: 0.1.75+cuda11.cudnn805, 0.1.75+cuda11.cudnn82, 0.1.76+cuda11.cudnn805, 0.1.76+cuda11.cudnn82, etc" after pip install pip install --upgrade jax jaxlib==0.4.30+cuda12.cudnn89 -f https://github.com/google/jax#pip-installation-gpu-cuda

- [ ] Check for duplicate requests.
- [ ] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by hawkinsp** [comment]
Please follow the installation instructions: https://github.com/google/jax/issues/22522

```
pip install jax[cuda12]
```

If that doesn't work, you'll need to provide more details of your Python installation. What Python version, for example?

**Comment by khandokaryogesh** [comment]
Yes, it's worked, Thank you so much!!
