### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by joaospinto** [google/jax#22545]
### Description

https://jax.readthedocs.io/en/latest/_autosummary/jax.export.Exported.html#jax.export.Exported.mlir_module_serialized currently links to https://jax.readthedocs.io/en/latest/export.html#module-calling-convention, which doesn't exist.
It should be this instead: https://jax.readthedocs.io/en/latest/export/export.html#export-calling-convention-version

### System info (python version, jaxlib version, accelerator, etc.)

N/A

**Comment by jakevdp** [comment]
Fixed by #22547
