### ISSUE TITLE
When logging cache hit/miss, include cache_key

### ISSUE THREAD

**Issue by cool-RR** [google/jax#22548]
I want these log messages:

```
Persistent compilation cache hit for 'jit_scan_outer_bigs'
```

To look like this:
```
Persistent compilation cache hit for 'jit_scan_outer_bigs' with cache_key `b86d2a45745d2417b7a28b1c38aa39497bf611e8320238cabe31e99142be5f2d`
```

Optionally we can truncate the cache key. I implemented this feature, let me know if you want a pull request.

**Comment by ayaka14732** [comment]
Thank you! Please make a pull request

**Comment by jaro-sevcik** [comment]
I like your proposal - just let me note here that you can already log cache keys (including info about its calculation):
```
import logging
logging.getLogger("jax._src.cache_key").setLevel(logging.DEBUG)
```

**Comment by cool-RR** [comment]
@jaro-sevcik Thank you. However these log lines do not contain the module name which makes them a bit difficult to search for.
