### ISSUE TITLE
Documentation of QR bugged

### ISSUE THREAD

**Issue by Jakob-Unfried** [google/jax#2254]
The [Documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.qr.html#jax.numpy.linalg.qr) of `jax.numpy.linalg.qr` seems to be bugged.

The [Documentation](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.qr.html) of `numpy.linalg.qr` contains a bullet point list when explaining the `mode` argument.

That seems to get lost when wrapping `qr` in [`jax.numpy.linalg`](https://github.com/google/jax/blob/b6e834117616977c85dae1e166124e3254304ca4/jax/numpy/linalg.py#L317)

The docstring in the onp [implementation](https://github.com/numpy/numpy/blob/v1.17.0/numpy/linalg/linalg.py#L769-L979) contains a blank line. Maybe that causes the problem?

**Comment by Tejaswgupta** [comment]
That implementation you linked is from numpy's GitHub page and its documentation is showing everything correctly so the problem lies in the jax docs . I will modify it and raise a PR.

**Comment by Jakob-Unfried** [comment]
Yes i linked numpy GitHub, since thats where `@_wraps` takes the docstring from.

The problem is with [this line](https://github.com/google/jax/blob/eda91a048b508c608d44c2f073429b9bfb26878d/jax/numpy/lax_numpy.py#L331) in `lax_numpy._wraps`

It separates the docstring of the original numpy function into sections, split by `'\n\n'`
Since the Parameters section of the onp QR docstring contains a bullet point list with two occurances of `'\n\n', it gets split into three sections

Then the logic in `update_numpydoc` does no longer work as intended, since the Parameters section is split over three entries of the `sections` list.

My idea to fix it:
refine how the docstring is split into sections and leave `update_numpydoc` as it is.
A section end should be `'\n\n'` followed by a non-whitespace character. This means that empty lines followed by indented text would no longer cause a section split.

I will eventually try this fix myself, but its not high priority for me.
If someone else wants to PR this, go ahead

**Comment by Tejaswgupta** [comment]
You can go forward for it :)

**Comment by Jakob-Unfried** [comment]
https://github.com/Jakob-Unfried/jax/commit/2ea9ec85521e6466c44a03e64eea6fa087ad8734 fixes the issue with `jax.numpy.linalg.qr`.

and *as far as i can tell* it doesnt't break anything else.
However, I have now idea how to make sure, that it doesn't break some docstring somewhere.

@mattjj ideas?

**Comment by Jakob-Unfried** [comment]
I fixed a loophole in https://github.com/Jakob-Unfried/jax/commit/63d8608b8c25c531a55a77f14f9a19257d955344

Any ideas how to test this, without manually looking at every page of the docs...?

**Comment by hawkinsp** [comment]
It looks to me like the `qr` documentation is rendering correctly at head. Closing, since I assume this issue is now stale.
