### ISSUE TITLE
Feature request: implement segment_min and segment_max

### ISSUE THREAD

**Issue by ovolve** [google/jax#2255]
I am porting a model that uses `tf.math.unsorted_segment_max`, and `_min` which are unimplemented in JAX. Implementing the ops is straightforward following the implementation of `segment_sum`, but they seem to be missing the necessary  `scatter_` gradients: 

> `NotImplementedError: Forward-mode differentiation rule for 'scatter-max' not implemented`

https://github.com/google/jax/blob/b6e834117616977c85dae1e166124e3254304ca4/jax/lax/lax.py#L3291

These ops are used heavily in many graph network implementations.

**Comment by jeffgortmaker** [comment]
It'd also be great to have a `segment_prod`. In an application of mine I'm doing something like `np.exp(jax.ops.segment_sum(np.log(x), i))` to get within-group products, which isn't ideal.

**Comment by Joshuaalbert** [comment]
Should this be closed?

**Comment by Joshuaalbert** [comment]
@alexdavies Could this be made into a PR?

**Comment by hawkinsp** [comment]
`segment_min` and `segment_max` are available at head (under `jax.ops`), so I think this issue is fixed!
