### ISSUE TITLE
Feature request: enable XLA PopulationCount op

### ISSUE THREAD

**Issue by j-towns** [google/jax#2263]
I think XLA has a PopulationCount op, listed [here](https://www.tensorflow.org/xla/operation_semantics#element-wise_unary_functions). Is it straightforward for JAX to expose it in lax.py? @hawkinsp I'm thinking you might be the right person to ask.

**Comment by mattjj** [comment]
I haven't added a new primitive in a while, but I think 0f115add is what we'd need on the JAX side.

We need to update jaxlib too, I think just to [add `'PopulationCount'` to this list](https://github.com/tensorflow/tensorflow/blob/28046a55b72fd5b49879259414daa998015b34c8/tensorflow/compiler/xla/python/xla_client.py#L1637) and [`UNARY_OP(PopulationCount)` to this list](https://github.com/tensorflow/tensorflow/blob/28046a55b72fd5b49879259414daa998015b34c8/tensorflow/compiler/xla/python/xla.cc#L498). Then we'd need to update the jaxlib pointer, and release new wheels (though you could build it yourself in the meantime).

**Comment by j-towns** [comment]
Thanks for the quick response @mattjj!

**Comment by mattjj** [comment]
Sent a CL for the XLA changes. Should appear on GitHub soon after it's submitted.

**Comment by mattjj** [comment]
The XLA Python client change [got upstreamed in TF](https://github.com/tensorflow/tensorflow/commit/9456e895fc276b89e2f1f355ba32eecc78ea4d3e), so now we just need to build a jaxlib. @j-towns have you had success doing that yourself? Otherwise we can try to build one, but our builds have been tricky recently due to TF / bazel changes.

**Comment by j-towns** [comment]
Haven't managed to build on my mac, but we can workaround until this op is available in pre-built jaxlib.

**Comment by j-towns** [comment]
Managed to build and looks like it's working as expected. Thanks! I guess this needs a new jaxlib release before you can merge into master?

**Comment by j-towns** [comment]
Pinging @mattjj. You should be able to merge 0f115ad now that there's a new jaxlib.

**Comment by hawkinsp** [comment]
@j-towns Do you want to finish this one off? The branch looks mostly good, assuming the tests pass, except it needs a doc string and to be added to the docs.

**Comment by j-towns** [comment]
Yep, see https://github.com/google/jax/pull/2753.
