### ISSUE TITLE
JAX implementation of `scipy.integrate.cumulative_trapezoid`

### ISSUE THREAD

**Issue by pennbay** [google/jax#22651]
The  `scipy.integrate.cumulative_trapezoid`functionis a useful func. Unfortunately, there is no equivalent implementation in jax.

Here is an example (adapted  from scipy):
```
x = jnp.linspace(-2, 2, num=20)
y = x
y_int = jax.scipy.integrate.cumulative_trapezoid(y, x, initial=0)
plt.plot(x, y_int, 'ro', x, y[0] + 0.5 * x**2, 'b-')
plt.show()
```

**Comment by jakevdp** [comment]
Hi - thanks for the request! We decided a while ago that `scipy.integrate` is out-of-scope for the JAX package; you can see the discussion and reasoning behind this at https://jax.readthedocs.io/en/latest/jep/18137-numpy-scipy-scope.html#scipy-integrate

**Comment by f0uriest** [comment]
This is implemented in `quadax` : https://quadax.readthedocs.io/en/latest/_api/quadax.cumulative_trapezoid.html#quadax.cumulative_trapezoid
