### ISSUE TITLE
Setting XLA flags causes segmentation fault

### ISSUE THREAD

**Issue by AakashKumarNain** [google/jax#22705]
### Description

As per the [docs](https://jax.readthedocs.io/en/latest/gpu_performance_tips.html#), these flags can help improve the performance on a A100 machine. I am running a jax program written in Equinox on a A100 machine with 2 GPUs, and setting any of these flags cause a segfault.

Idk if these flags alone can accelerate the performance, but right now my JAX distributed training is extremely slow compared to torch (which is extremely surprising for me). Couple of reasons that I can think of:

1. torch using tf32 -> not sure how to do this in jax
2. torch using flash attention: there is no equivalent of flash attention but I guess these two flags `--xla_gpu_enable_triton_softmax_fusion=true --xla_gpu_triton_gemm_any=True ` can help bridge the gap
3. torch is using fused adam -> not sure optax uses fused implementation depending on the available hardware

### System info (python version, jaxlib version, accelerator, etc.)

```
GPU: A100 40G - #2
jax==0.4.30
jax-cuda12-pjrt==0.4.30
jax-cuda12-plugin==0.4.30
jaxlib==0.4.30
```

**Comment by superbobry** [comment]
I would recommend filing an issue about the segfault in [openxla/xla](https://github.com/openxla/xla/issues). It would really help if you could include a reproducer for the XLA team.

Re 2: Could you use [`jax.nn.dot_product_attention`](https://jax.readthedocs.io/en/latest/_autosummary/jax.nn.dot_product_attention.html#jax.nn.dot_product_attention)?

**Comment by AakashKumarNain** [comment]
Thanks I can do that.

re 2: Nice, but I don't think this is available in 0.4.30. I have the same version installed on my mac, and it isn't there

**Comment by superbobry** [comment]
Can you try the nightly? https://jax.readthedocs.io/en/latest/installation.html#jax-nightly-installation

**Comment by AakashKumarNain** [comment]
Thanks got it. I will close this and will open an issue for the flags in the XLA repo

**Comment by kxs-dhenshall** [comment]
@AakashKumarNain Did you file that bug with XLA? I encountered this issue with simple repro steps. I am using a DGX system and this is running on an H100:

```python
import os
os.environ['XLA_FLAGS'] = '--xla_gpu_enable_triton_softmax_fusion=true'

import jax.numpy as jnp

data = jnp.array([10, 82, 79, 87, 83, 13, 10], dtype=jnp.uint8)
jnp.where(data == 10)
```

**Comment by AakashKumarNain** [comment]
No, I didn't find any solution.

Re flags: Not only that flag, I think most flags are not tested properly. All the flags that are supposed to provide gains on GPU haven't provided any gains on A100 at least.

**Comment by hawkinsp** [comment]
I reopened the XLA bug. The crash is certainly something that shouldn't happen, although it would be reasonable for the XLA folks not to prioritize a non-default configuration.

The GPU perf tuning document is supposed to suggest things that may help if tweaked, although there's no guarantee that anything will help, or indeed work, for any given workload. The only truly supported configuration is the default one. Perhaps we should mark those flags as more explicitly experimental?

For flash attention, I recommend you use the flash attention API in the most recent JAX, as Sergei suggests.

The other two optimizations (TF32 and fused adam) should be happening by default, assuming your training is inside a `jit` for the fused adam.

**Comment by AakashKumarNain** [comment]
Thanks @hawkinsp for the quick response.

>Perhaps we should mark those flags as more explicitly experimental?

Agreed, that will help clarify things for the end user

**Comment by rohandekate10** [comment]
I get this error on an H100 GPU cluster after the training is completed. When I ran the same code on A100 I don't get this error.
Is this error critical? Is this jax version dependent?
`/var/spool/slurm/job2248435/slurm_script: line 26: 118054 Segmentation fault	 (core dumped) `
This is my jax config on H100
```
jax==0.7.0
jax-cuda12-pjrt==0.7.0
jax-cuda12-plugin==0.7.0
jaxlib==0.7.0
jaxtyping==0.3.2
```
On A100 jax config is
```
jax==0.6.2
jax-cuda12-pjrt==0.6.2
jax-cuda12-plugin==0.6.2
jaxlib==0.6.2
jaxtyping==0.3.2
```
