### ISSUE TITLE
infinite loop when trying to install jax with cuda support on windows

### ISSUE THREAD

**Issue by nullonesix** [google/jax#22776]
### Description

  Downloading jax-0.4.12.tar.gz (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 13.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Downloading jax-0.4.11.tar.gz (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 13.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Downloading jax-0.4.10.tar.gz (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 16.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Downloading jax-0.4.9.tar.gz (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 21.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
  Downloading jax-0.4.8.tar.gz (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 15.5 MB/s eta 0:00:00

infinite loop...
when running
pip install -U -r dreamerv3/requirements.txt -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
same with
python -m pip install jax[cuda]

### System info (python version, jaxlib version, accelerator, etc.)

python 3.10.11

**Comment by nullonesix** [comment]
in particular, it works fine on wsl and linux, only windows has this problem..

**Comment by rajasekharporeddy** [comment]
Hi @nullonesix

As per the documentation, JAX cuda support is not available on Windows. 
<img width="808" alt="image" src="https://github.com/user-attachments/assets/ea00f7fc-9483-4e30-91d4-05cac2018117">


Please have a look at the documentation: https://jax.readthedocs.io/en/latest/installation.html

It is also mentioned in the documentation that [`pip install --upgrade "jax[cuda12]"` do not work with Windows, and may fail silently](https://jax.readthedocs.io/en/latest/installation.html#supported-platforms:~:text=These%20pip%20installations%20do%20not%20work%20with%20Windows%2C%20and%20may%20fail%20silently%3B%20refer%20to%20the%20table%20above.).

Thank you.

**Comment by mattjj** [comment]
@nullonesix unfortunately, I have no idea. But I think it's best we close the issue since, as @rajasekharporeddy pointed out, Windows + GPU is officially unsupported. (There may be some [community projects](https://github.com/cloudhan/jax-windows-builder) though.)
