### ISSUE TITLE
np.var does not match onp.var in some cases

### ISSUE THREAD

**Issue by yurodiviy** [google/jax#2283]
Running this snippet
```python
import jax.numpy as np 
import numpy as onp 
inp_array = np.array([[[5.29215704-0.30965656j,  1.20047163+1.23179551j, 0+0.43213071j,  6.7226796 +4.36282052j]],   
                      [[5.60267397+2.28311318j,           0+0.36502505j,         0 +1j, -0.45407162+1.00102298j]]])  
print(np.var(inp_array, 2, dtype=np.float32)) 
print(onp.var(onp.array(inp_array), 2, dtype=onp.float32))
```
Prints different outputs for numpy and jax.numpy
```
[[10.911064]
 [ 6.728332]]
[[12.953884]
 [ 8.079251]]
```
Not sure if there is an actual use case for np.var on complex arrays with dtype=float, but I guess the outputs are supposed to be the same since jax.numpy is supposed to match numpy where it's possible.

The mismatch happens because the implementation in NumPy uses dtype for all the calculations, meanwhile, jax.numpy only converts the computed value to dtype in the very end and does all the calculations in the promote_types(complex, dtype=float) which evaluates to complex.

If this sounds like something that should be fixed then I can make a PR.

**Comment by hawkinsp** [comment]
I think we should do one of two things:
(a) match NumPy, or
(b) issue an error, if the behavior isn't sensible.

I can't particularly decide if the behavior of NumPy is sensible here; it might make more sense to issue an error.

**Comment by yurodiviy** [comment]
On a second thought, NumPy behaviour here is quite unintuitive, I'd expect it to compute the variance of the real parts, but that's not what it does. So I guess issuing an error sounds better. 
Made a PR.
