### ISSUE TITLE
Data type precision and demote/promote preference config

### ISSUE THREAD

**Issue by bionicles** [google/jax#22842]
Please:

- [x] Check for duplicate requests.
    - https://github.com/google/jax/issues/19033 
    - https://github.com/google/jax/issues/16705
    - https://github.com/google/jax/issues/15580  
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

### TLDR: to benefit the future of AI innovation, we could add config options to enhance JAX support for mixed and reduced precision numbers 

I've hit this error message a billion times in getting rolling with `ml_dtypes`.
![image](https://github.com/user-attachments/assets/3163ac77-1680-4791-a7c8-9168bf8821fb)

_I wish I could set `jax.config` options to make it easier..._

## Ideas:
- A `default_precise_float_dtype` value set to `f32` (same default dtype as now)
- A `default_imprecise_float_dtype` value set to `None` or `bf16`
- A `float_precision_mismatch_behavior` enum with `raise`, `auto_demote`, and `auto_promote` variants which defaults to `raise` (same behavior as now)
- (Optional): A `default_float_dtype_precision` enum with `precise` and `imprecise` variants, defaulting to `precise`

Crucial point: these config options ought to have sensible defaults which yield no change in behavior unless a user changes them. Thus it would be a purely additive change and not negatively impact backward compatiblity.

(ditto for integers possible)

### Explanation: 
We keep the default f32 dtype as the default_precise_float type
If the accelerator can support reduced precision like `bf16` or `f8`, then they could specify the desired imprecise dtype as a config option and select `auto_demote` instead of `raise`

Then the `auto_demote` behavior can be: if one of the dtypes is reduced precision and the other is higher precision, jax could know to reduce the precision of the more precise float to the `default_imprecise_float_dtype`. 

Likewise, if the situation is mostly all clearly specified in the codebase as reduced precision, then a savvy jax user could set `float_precision_mismatch_behavior` to `auto_promote` and jax could know to convert imprecise floats to the more precise type, for use cases like batch norm or bigger number types (and surely I recognize this is default for some dtype pairings)

### Minimal reproduction:
```py
import jax
import ml_dtypes
precise_arr = jax.numpy.ones(3)
imprecise_arr = jax.numpy.ones(3, dtype=ml_dtypes.float8_e5m2)
jax.numpy.array_equal(precise_arr, imprecise_arr)
```

### Error copypasta 
(i'm sure you've seen this already if you're working with mixed precision)
```sh
args = (Traced<ShapedArray(float32[3])>with<DynamicJaxprTrace(level=1/0)>, Traced<ShapedArray(float8_e5m2[3])>with<DynamicJaxprTrace(level=1/0)>)

    def promote_dtypes(*args: ArrayLike) -> list[Array]:
      """Convenience function to apply Numpy argument dtype promotion."""
      # TODO(dougalm,mattjj): This is a performance bottleneck. Consider memoizing.
      if len(args) < 2:
        return [lax.asarray(arg) for arg in args]
      else:
>       to_dtype, weak_type = dtypes._lattice_result_type(*args)
E       jax._src.dtypes.TypePromotionError: Input dtypes ('float8_e5m2', 'float32') have no available implicit dtype promotion path. To avoid unintended promotion, 8-bit floats do not support implicit promotion. If you'd like your inputs to be promoted to another type, you can do so explicitly using e.g. x.astype('float32')
E       --------------------
```

### Final Disclaimer
- I am no expert on jax config options so there might already be something like this (the `jax.config.update("jax_enable_x64", True)` one I sometimes use comes to mind)
- There may exist XLA environment variables to achieve similar aims
- There might be better ways to pull this off
- There might be better names for these config options
- There might be better data structures, imho enums are good, clear
- I'm not really familiar enough with this codebase to make a PR for this.
- I welcome valuable input from the JAX community, WDYT?

**Comment by jakevdp** [comment]
Hi - we've discussed this before, and in general we've found that different users have different opinions when it comes to what the default promotion behavior for float8 should be. Given that, and given that float8 is generally used very deliberately within a very limited range of situations, we've come to the conculsion that it's best for promotion with float8 to be explicit, rather than implicit. What do you think?

**Comment by bionicles** [comment]
f8 will see more use in the future to save memory, so my objective was to prepare to explicitly configure optional sensible defaults to **demote** to more efficient dtypes, not promote

Sadly, I can't contribute to Google projects knowing the Gemini API and Alphafold Server customer noncompetes are unsafe, so I'm closing, no offense to you Jake, I know you're a 10x dev and I really admire all the jax team members, just can't contribute to JAX in good conscience knowing this clause are up. 

![image](https://github.com/user-attachments/assets/0648ca4f-103f-4ff8-a0f1-a7f83a1fe7cf)

my bad for opening this, I was excited because I hadn't noticed that, but that clause makes the set of things one can actually use gemini for without fear of legal risk an empty set, and anything I do to help JAX, just contributes make the "closed output / customer noncompete" problem even worse, so I must cease involvement in the project

if the most critical documents in AI safety are written by corporate lawyers instead of AI engineers, humanity is truly ****ed

here's a better license, not that anyone cares
![image](https://github.com/user-attachments/assets/3ac0ab5a-94fe-4eeb-8ddc-b95ba7aabd4d)
