### ISSUE TITLE
Memory profiler missing in trace

### ISSUE THREAD

**Issue by vikmary** [google/jax#22890]
### Description

Memory profiling data missing for traces captured via the [jax.profiler.start_trace()](https://jax.readthedocs.io/en/latest/_autosummary/jax.profiler.start_trace.html#jax.profiler.start_trace) and [jax.profiler.stop_trace()](https://jax.readthedocs.io/en/latest/_autosummary/jax.profiler.stop_trace.html#jax.profiler.stop_trace) in latest JAX (0.4.29, 0.4.30, 0.4.31), but is present for 0.4.26

Minimal example to reproduce:

```
import jax

jax.profiler.start_trace("/tmp/tensorboard")

# Run the operations to be profiled
key = jax.random.key(0)
x = jax.random.normal(key, (5000, 5000))
y = x @ x
y.block_until_ready()

jax.profiler.stop_trace()
```
Then

```
$ tensorboard --logdir=/tmp/tensorboard
```

Then, go directly to http://localhost:6006/#profile, under “Tools” select `memory_profile`. The page then says "There is no memory profile to display because there were no memory activity data in the captured duration."

![image](https://github.com/user-attachments/assets/6bd1311b-6eb1-43fb-be80-82b9aacf8091)

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.30                                                                                 
jaxlib: 0.4.30
numpy:  1.24.3
python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
jax.devices (8 total, 8 local): [cuda(id=0) cuda(id=1) ... cuda(id=6) cuda(id=7)]
process_count: 1
platform: uname_result(system='Linux', node='computeinstance-e00p65n218bdg7kkxc', release='5.15.0-117-generic', version='#127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024', machine='x86_64')


$ nvidia-smi
Tue Aug  6 06:48:23 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.90.07              Driver Version: 550.90.07      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA H100 80GB HBM3          On  |   00000000:8D:00.0 Off |                    0 |
| N/A   66C    P0            149W /  700W |   76598MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA H100 80GB HBM3          On  |   00000000:91:00.0 Off |                    0 |
| N/A   46C    P0            122W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA H100 80GB HBM3          On  |   00000000:95:00.0 Off |                    0 |
| N/A   67C    P0            149W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA H100 80GB HBM3          On  |   00000000:99:00.0 Off |                    0 |
| N/A   49C    P0            125W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   4  NVIDIA H100 80GB HBM3          On  |   00000000:AB:00.0 Off |                    0 |
| N/A   63C    P0            134W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   5  NVIDIA H100 80GB HBM3          On  |   00000000:AF:00.0 Off |                    0 |
| N/A   49C    P0            124W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   6  NVIDIA H100 80GB HBM3          On  |   00000000:B3:00.0 Off |                    0 |
| N/A   64C    P0            143W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
|   7  NVIDIA H100 80GB HBM3          On  |   00000000:B7:00.0 Off |                    0 |
| N/A   48C    P0            126W /  700W |   76588MiB /  81559MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

**Comment by mattjj** [comment]
@vikmary thanks for reporting this!

@zzzaries FYI, is this something you're aware of?

**Comment by zzzaries** [comment]
Hi Matthrew, yes we are currently aware of this issue and will take a look on the profiler side.

**Comment by zzzaries** [comment]
Hi @vikmary thanks for reporting. I tried with jax 4.26.0 and also cannot see the memory viewer data, could you help provide steps to reproduce this? (both when seeing the memory profile data and not seeing case)
informations might be helpful:
- any devices being used to run the script and being profiled?
- which tensorboard and tensorboard-plugin-profiler versions are you using? ..etc.
thank you!

**Comment by mattjj** [comment]
Just keeping the thread updated: @hawkinsp advised that
1. we almost surely need to reproduce on GPU
2. it's probably related to the profiler being moved into a plugin
3. we can probably only reproduce in OSS land (rather than in Google's monorepo)

**Comment by zzzaries** [comment]
update: now we can see the memory_profile page using the most recent jax versions and all dependencies: jax==0.4.31, jaxlib==0.4.31, jax[cuda12]==0.4.31. And can also see memory_profile for profiles being collected with jax0.4.26, but not jax 0.4.30.

Noticed that we had a fix from the team to collect metadata required for memory_profile page, and the fix is released with jax 0.4.31.

So might still be helpful to show a more complete pip list, to see if anything is wrong there. And would suggest using 0.4.31 for all jax related dependencies.

**Comment by southfreebird** [comment]
Hello, 
thank you for your investigation.
To get this results we used the script from the [example](https://jax.readthedocs.io/en/latest/profiling.html#tensorboard-profiling):
```
import jax

jax.profiler.start_trace("/tmp/tensorboard")

key = jax.random.key(0)
x = jax.random.normal(key, (5000, 5000))
y = x @ x
y.block_until_ready()

jax.profiler.stop_trace()
```

We are using custom environment based on `nvidia/cuda:12.3.0-devel-ubuntu22.04`. We obtained the results (the only JAX and cudnn versions differs):
- jax[cuda12_local] 0.4.26, cudnn 8.9 - memory_profile works
- jax[cuda12_local] 0.4.30, cudnn 9.1 - memory_profile does not work
- jax[cuda12_local] 0.4.31, cudnn 9.1 - memory_profile does not work (I will double check it)

**Comment by southfreebird** [comment]
Profiler works with JAX 0.4.31, my bad
Thank you!

**Comment by mattjj** [comment]
Can we close this?

**Comment by vikmary** [comment]
Thanks for the joint investigation (@southfreebird is my college, so he shared all the details that were linked to my issue as well)

**Comment by mattjj** [comment]
Amazing, thank you!

**Comment by vrnvorona** [comment]
In 0.6.2 nighly I don't have memory profile info. Tracing works as expected. Is this known?

**Comment by biao-geng-me** [comment]
Wanted to add that in 0.6.2, I don't have memory profile info either. Tracing and some other information are available in the profile data.

**Comment by reachtarunhere** [comment]
wanted to add that I don't have the memory profile in 0.7.0. I think we should reopen this. Thanks.

**Comment by Matt-Hurd** [comment]
It looks like this was a regression that started occurring in libtpu version 0.0.16. A fix has been made and will be in the next version of libtpu. As a workaround for now, you can profile setting `host_tracer_level=2`, like below:
```
import jax

options = jax.profiler.ProfileOptions()
options.host_tracer_level = 2

jax.profiler.start_trace("/tmp/tensorboard", profiler_options=options)

# Run the operations to be profiled
key = jax.random.key(0)
x = jax.random.normal(key, (5000, 5000))
y = x @ x
y.block_until_ready()

jax.profiler.stop_trace()
```
