### ISSUE TITLE
Installing jaxlib with CUDA Version: 11.7

### ISSUE THREAD

**Issue by ArturDev42** [google/jax#22932]
### Description

I am trying to install CUDA-enabled jaxlib on a system with `CUDA Version: 11.7`. From the displayed available versions, the lowes I see is `0.4.17+cuda11.cudnn86`. Is it possible to install jaxlib on a sytem with `CUDA Version: 11.7`?

### System info (python version, jaxlib version, accelerator, etc.)

I have jaxlib installe, but not a CUDA-enabled version.
```
An NVIDIA GPU may be present on this machine, but a CUDA-enabled jaxlib is not installed. Falling back to cpu.
jax:    0.4.31
jaxlib: 0.4.31
numpy:  1.26.4
python: 3.12.3 | packaged by conda-forge | (main, Apr 15 2024, 18:38:13) [GCC 12.3.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Linux', node=, release='5.15.0-105-generic', version='#115-Ubuntu SMP Mon Apr 15 09:52:04 UTC 2024', machine='x86_64')


$ nvidia-smi
Thu Aug  8 09:53:42 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.105.01   Driver Version: 515.105.01   CUDA Version: 11.7   
```

**Comment by jakevdp** [comment]
Looking at the [changelog](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-8-march-29-2023), JAX dropped support for CUDA versions older than 11.8 in v0.4.8. So you may have luck with JAX v0.4.7. You can find relevant installation instructions here: https://github.com/google/jax/tree/jax-v0.4.7?tab=readme-ov-file#pip-installation-gpu-cuda
```
pip install --upgrade pip
# Installs the wheel compatible with CUDA 11 and cuDNN 8.6 or newer.
# Note: wheels only available on linux.
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```

**Comment by jakevdp** [comment]
It looks like you’re using Python 3.12, and Jax 0.4.7 only supports Python versions 3.8 through 3.11. You’ll either have to downgrade your Python version, or upgrade your CUDA version.

**Comment by ArturDev42** [comment]
Thanks, that worked. However, when I run `python -c "import jax; print(f'Jax backend: {jax.default_backend()}')"
` to check jax finds the CUDA backend, my system crashes. The same happens when I do `import jax; jax.print_environment_info()`.

**Comment by jakevdp** [comment]
It's hard to say what's causing that crash – is it possible you have cross-talk between multiple Python environments?
