### ISSUE TITLE
AttributeError: module 'jax.random' has no attribute 'KeyArray'

### ISSUE THREAD

**Issue by Azikhalili** [google/jax#22990]
### Description

AttributeError: module 'jax.random' has no attribute 'KeyArray'

### System info (python version, jaxlib version, accelerator, etc.)

0.4.31

**Comment by NDOWAH** [comment]
Hello @Azikhalili, I would like to look in to this issue. Please provide a sample code that resulted to the error above.

**Comment by jakevdp** [comment]
Hello! `jax.random.KeyArray` was [deprecated in JAX v0.4.16](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-16-sept-18-2023) and [removed in JAX v0.4.24](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-4-24-feb-6-2024). You should upgrade your code to use `jax.Array` instead, or if you're using code that you can't upgrade, you should install JAX version 0.4.23 or older.

**Comment by Azikhalili** [comment]
Thanks for replying this issue. I upgrade it and still there is issue. Same Error!
@jakevdp

**Comment by Azikhalili** [comment]
@NDOWAH Thanks for your reply. I am using DCFACE, and this is the error that I get when I want to run DCFACE
"/content/dcface/dcface/src/diffusers/schedulers/scheduling_ddpm_flax.py", line 191, in FlaxDDPMScheduler
    key: random.KeyArray,
  File "/usr/local/lib/python3.10/dist-packages/jax/_src/deprecations.py", line 54, in getattr
    raise AttributeError(f"module {module!r} has no attribute {name!r}")
AttributeError: module 'jax.random' has no attribute 'KeyArray'

**Comment by jakevdp** [comment]
I'm not sure what you mean when you said you upgraded.

If you are still getting the same error, you should either

1. install JAX version 0.4.23 or older, or
2. Change all instances in your code of `jax.random.PRNGKey` to `jax.Array`.

If you do one of these two, then the error will go away.
