### ISSUE TITLE
asscalar workaround for jitted function

### ISSUE THREAD

**Issue by jhmenke** [google/jax#2304]
Suppose a simplified function like this:

```
@jit
def f(idx, mylist):
    return mylist[idx]
```

_idx_ is an integer but will be converted to ShapedArray while _mylist_ is a list of something. There will be an error because mylist cannot be indexed using a ShapedArray. 

Is there any option to actually get the scalar value in idx?

**Comment by clemisch** [comment]
Does `mylist` have to be a list, or could you convert it to an array before passing it to the function?

**Comment by jhmenke** [comment]
I assumed it wasn't possible for my list, because it comes from another library, but it turns out that was no issue at all.

Thanks! @clemisch
