### ISSUE TITLE
When are traces created?

### ISSUE THREAD

**Issue by ethanluoyc** [google/jax#2313]
Hi,

I am playing around with implementing my own final-style tracer for experimenting with some symbolic execution alongside the JAX tracing. I tried to add a custom trace that is stateful. i.e. something like 

```python

class CustomTrace(jcore.Trace):
    def __init__(self, master, sublevel):
        super().__init__(master, sublevel)
        # I am trying to maintain some state for a particualr trace here
        self._path_conditions = []

```

Then I am using the custom trace class with some snippet that looks like this

```python
with jcore.new_master(CustomTrace) as master:
        trace = CustomTrace(master, jcore.cur_sublevel())
        x = CustomTracer(trace, np.ones(3))
        out = (x < 2)
```

However I have found that this will not work. In particular, I was expecting that out will have the same trace as x but this is not the case. The reason for that is because of the code in find_top_trace
https://github.com/google/jax/blob/master/jax/core.py#L264

```python
...
return type(top_trace)(top_trace.master, cur_sublevel())
...
```

Here a new trace is created when we have found a top trace. I am not very sure why JAX does this under the hood. Is there some good documentation / notes on what we should expect from MasterTrace, Trace and subtraces? In general, what would be the best way to maintain state in tracing?
Is is similar to how https://github.com/google/jax/issues/1663 does it?

**Comment by gnecula** [comment]
Sadly, we don't have that part documented yet.

**Comment by gnecula** [comment]
Can you tell us what are you trying to achieve? Perhaps there is a way to do that with the public APIs.

**Comment by ethanluoyc** [comment]
Testing I can't comment for some reason.

**Comment by gnecula** [comment]
Sorry the the late reply. What you are trying to use is not part of the API on which we are focusing the documentation efforts. Eventually we plan to add more internal documentation.

**Comment by gnecula** [comment]
I am closing this issue because there is nothing we plan to do imminently here.
