### ISSUE TITLE
arctan2 and atan2 argument names are misleading

### ISSUE THREAD

**Issue by treyra** [google/jax#23151]
### Description

The arguments for jax.numpy.arctan2 (and its alias jax.numpy.atan2) are (x,y). 

However, this has two major issues. First, since this is an implementation of numpy.arctan2 (https://numpy.org/doc/stable/reference/generated/numpy.arctan2.html) the x argument is the y-coordinates, and the y argument is the x-coordinates. Second, since the numpy argument ordering is the conventional implementation, jax's ordering suggests it may be intentionally breaking with convention, when this is not the case.

This can be easily fixed, however swapping the arguments would silently break any existing implementations that pass values to the functions by keywords. Changing to numpy's convention of (x1, x2) would avoid silently incorrect results in this case, and make the implementation clearer, but would still be a breaking change. Updating the documentation at least, especially for atan2 (https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.atan2.html), would help make this issue more visible. 

I'm unsure what the best way to resolve this would be, so I've held off on submitting a pull request, but wanted to raise the issue.

### System info (python version, jaxlib version, accelerator, etc.)

```jax:    0.4.30
jaxlib: 0.4.30
numpy:  1.26.3
python: 3.12.4 | packaged by conda-forge | (main, Jun 17 2024, 10:23:07) [GCC 12.3.0]
jax.devices (1 total, 1 local): [cuda(id=0)]
process_count: 1
platform: uname_result(system='Linux', node='DESKTOP-VO2OCMO', release='5.15.153.1-microsoft-standard-WSL2', version='#1 SMP Fri Mar 29 23:14:13 UTC 2024', machine='x86_64')


$ nvidia-smi
Tue Aug 20 12:55:49 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.58.02              Driver Version: 556.12         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 2060 ...    On  |   00000000:06:00.0  On |                  N/A |
| 55%   46C    P2             39W /  175W |    7872MiB /   8192MiB |      2%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        50      G   /Xwayland                                   N/A      |
|    0   N/A  N/A      2060      G   /firefox                                    N/A      |
|    0   N/A  N/A     32386      C   /python3.12                                 N/A      |
+-----------------------------------------------------------------------------------------+
```

**Comment by jakevdp** [comment]
Thanks for flagging this! I agree this is confusing – we can do a fix (with a deprecation cycle for the old argument names).

**Comment by pearu** [comment]
TBH, `(x1, x2)` is equally confusing to `(y, x)` as `x1` can mean `x`-coordinate for someone while here/in numpy it is `y`-coordinate. Following numpy convention seems like a reasonable compromise though.

**Comment by treyra** [comment]
Thanks for the fast fix!

You're right, those are position only, so that shouldn't break anything. I agree with @pearu that numpy's convention is also not ideal, but I think since jax.numpy is a drop in replacement in most instances, this change should avoid any one getting the wrong impression that the convention is different.
