### ISSUE TITLE
size of slices can’t be functions of argument values

### ISSUE THREAD

**Issue by david-waterworth** [google/jax#2323]
I'm having problems implementing the following `fori_loop` body. 

```
def body_fun(i, val):
    batch_sizes, packed_input_data, input_offset = val

    batch_size = packed_input.batch_sizes[i]

    #batch = packed_input_data[input_offset:input_offset+batch_size]
    batch = dynamic_slice_in_dim(packed_input_data, input_offset, batch_size)
    input_offset += batch_size

    return batch_sizes, packed_input_data, input_offset
```

I'm trying to replace the commented out code with jax primitives - i.e. slicing `packed_input_data` (n x m) based on the input_offset[i] (int). The issue I'm running into is `dynamic_slice_in_dim` throws:

> TypeError: Abstract value passed to `int`, which requires a concrete value. Try using `value.astype(int)` instead.

What seems to be happening is `dynamic_slice_in_dim` attempts to cast `input_offset` and/or `batch_size` as int() which throws since they're traced and don't support this cast? i.e. If I use literal ints for the start_index, slice_size it works. Also if I call `body_fun(i, val)` from a pure python for loop it also works no problems.

How should I approach this problem? I can paste full code if required, my full implementation also includes packed_output_data (same shape as packed_input_data) which I'm trying to update using `dynamic_update_slice` plus a state array which also slice by batch_size. 

(I'm trying to implement variable length sequence RNN's using PyTorch as inspiration.)

**Comment by david-waterworth** [comment]
I've read through https://github.com/google/jax/issues/2308 which seems similar but I'm still cannot get this to work.

No matter what primitive I use to translate the 2nd slice operation below it fails with an exception that seems to imply batch_size must be a concrete value but an abstract value was supplied.

```
input_offset = 0
for i in range(batch_sizes.shape[0]):
    batch_size = batch_sizes[i]
    batch = packed_input[input_offset:input_offset+batch_size,:]  # issue here
    input_offset = input_offset + batch_size
```

**Comment by david-waterworth** [comment]
I've created a simple reproduction, can someone confirm if I'm trying to do something that's not supported by jax?

An error is raised from line #37 of abtract_arrays.py, it seems that using `batch_size = batch_sizes[i]`cannot be used as an array slice - can you confirm that?

```
import jax
from jax import ops
import jax.numpy as np
from jax.lax.lax import dynamic_slice


@jax.jit
def unpack(i, input_offset, batch_sizes, packed_input_data):
    batch_size = batch_sizes[i]
    batch = dynamic_slice(
        packed_input_data,
        np.array([input_offset, 0]),
        np.array([batch_size, packed_input_data.shape[1]]))

    return batch


# equivalent to packing padded sequences [11,12,13],[21,22,-1],[31,-1,-1]
packed_input_data = np.array([
    [11],
    [21],
    [31],

    [12],
    [22],

    [13]
], dtype=np.float32)
batch_sizes = np.array([3, 2, 1], dtype=np.int32)
unpack(0, 0, batch_sizes, packed_input_data)
```

**Comment by david-waterworth** [comment]
I found this in the documentation "the size of slices can’t be functions of argument values but only functions of argument shapes – the slice start indices have no such restriction."

So it looks like what I'm trying to do isn't supported. I'll have to try and think of another way

**Comment by clemisch** [comment]
A general rmark without understanding the overall purpose of your code:

If the output shape of your function depends on a **value** of an input argument (instead of just the input shapes), you must declare that argument as static via `static_argnums`:

```python
@jax.partial(jax.jit, static_argnums=(0, 1, 2))  # shape depends on i, input_offset, batch_sizes
def unpack(i, input_offset, batch_sizes, packed_input_data):
    # [...]
```

`unpack` will be recompiled for every different value (combination) in those three input arguments, as opposed to different input shapes with normal jit.

**Comment by david-waterworth** [comment]
Thanks @clemisch, that helps - I had tried `static_argnums` but I suspect I didn't understand that they need to be applied to all parameters which affect the output shape.

So in this case does that means it'll `jit` a different version of `unpack` for every (i, input_offset, batch_sizes)?

**Comment by clemisch** [comment]
> So in this case does that means it'll jit a different version of unpack for every (i, input_offset, batch_sizes)?

Yes, that is true.

**Comment by clemisch** [comment]
Did this answer your question?

**Comment by david-waterworth** [comment]
Yes thanks!
