### ISSUE TITLE
compiled .whl file for  AMD GPU

### ISSUE THREAD

**Issue by Jiakui** [google/jax#2324]
Can anybody provide a compiled .whl file for AMD GPU？ 

Thanks

**Comment by Jiakui** [comment]
Or provide a tutorial for running jax on AMD GPU from scratch, I am not very familiar with compiling XLA. Thanks !

**Comment by shoyer** [comment]
Please see https://github.com/google/jax/issues/2012. Contributions would be welcome here, but I don't think we have any generic guidance. As far as I can tell, nobody has done this before.
