### ISSUE TITLE
`eval_shape` should preserve `weak_type`

### ISSUE THREAD

**Issue by garymm** [google/jax#23302]
`eval_shape` does not preserve `weak_type` information.

This contributes to making it hard to debug why a function is being re-compiled. See https://github.com/patrick-kidger/equinox/issues/817, but basically:
If a jitted function is called twice, one with a weak_type and once with a non-weak_type, this triggers recompilation.
`equinox.debug.assert_max_traces` uses `jax.eval_shape` to try to determine which argument triggers recompilation, but in this case it cannot determine that.

I would be happy to attempt adding this if the feature is welcome.

**Comment by yashk2810** [comment]
Do you have a minimal repro?

**Comment by jakevdp** [comment]
I think it's as simple as this:
```python
>>> import jax
>>> jax.numpy.array(1)  # weak type
Array(1, dtype=int32, weak_type=True)
>>> jax.eval_shape(jax.numpy.array, 1)  # no weak type
ShapeDtypeStruct(shape=(), dtype=int32)
```
We currently have no way to represent the weak type bit in `ShapeDtypeStruct` – fixing this would probably involve adding that fields and propagating it through where necessary.

**Comment by yashk2810** [comment]
Ohh I see. Yeah, that kinda sucks. 

Since jax.Array has a weak_type field on it, it makes sense for SDS to also have that.

**Comment by garymm** [comment]
Actually I should ask, since this would make the issue moot for my purposes: would it be correct for jax.jit to not trigger recompilation if the only difference is weak_type?

**Comment by jakevdp** [comment]
`jax.jit` definitely needs to recompile depending on `weak_type`, because it changes type promotion behavior, and thus can change the dtype of arrays within the compiled function.
