### ISSUE TITLE
lax_numpy.concatenate passes through individual argument

### ISSUE THREAD

**Issue by msbauer** [google/jax#2330]
I came about some weird behaviour (to me) where `jax` alters the input to a function when mixed with numpy. I would have expected that x stays unaltered in all cases in the following example:
```
def f(x):
 x = [x]
 x = jnp.concatenate(x)
 x -= 1
 return x

x = np.ones((1))
f(x)
print(x)  # >>> [0.]

x = jnp.ones((1))
f(x)
print(x)  # >>> [1.]
```
When using `x = x - 1` or `np.concatenate` the output is `[1.]` as expected.

With the help of @mattjj I traced this back to https://github.com/google/jax/blob/ce9b03866cf04a378d6cc44a5ce5f99700f0148c/jax/numpy/lax_numpy.py#L1724-L1727

I will commit a PR and test once an issue number is assigned

**Comment by mattjj** [comment]
Fixed by #2331 !
