### ISSUE TITLE
TPU tile in first dim of a 2d array

### ISSUE THREAD

**Issue by oliverdutton-iso** [google/jax#23318]
I am implementing masking in the TPU flash attention kernel. I would like to broadcast in the first dimension of a 2d array. Is there a way I can do this?

Minimal reprod, just masking an input

```python
import jax
import jax.numpy as jnp
from jax import random
from jax.experimental import pallas as pl
from jax.experimental.pallas import tpu as pltpu

def add_vectors_kernel(x_ref, mask_ref, o_ref):
  x = x_ref[...]
  mask = mask_ref[...]
  mask = pltpu.repeat(mask, x.shape[0], 0)
  o_ref[...] = x + jnp.where(mask, 0.0, -1e5)

@jax.jit
def add_vectors(x: jax.Array, mask: jax.Array) -> jax.Array:
  return pl.pallas_call(
      add_vectors_kernel,
      out_shape=jax.ShapeDtypeStruct(x.shape, x.dtype)
  )(x, mask)

x = jnp.ones((16, 16))
mask = random.bernoulli(random.key(42), 0.5, shape=(1, 16))
add_vectors(x, mask)
#MosaicError: INTERNAL: Mosaic failed to compile TPU kernel: Not implemented: Non-trivial layouts unsupported
#
#The MLIR operation involved:
#  %27 = "tpu.repeat"(%26) <{dimension = 0 : i32, times = 16 : i32}> {in_layout = [#tpu.vpad<"32,{0,0},(1,128)">], out_layout = #[#tpu.vpad<"32,{0,0},(1,128)">]} : (vector<1x16xf32>) -> vector<16x16xf32>

```

**Comment by justinjfu** [comment]
Can you try using `lax.broadcast_in_dim`?

e.g. `mask = lax.broadcast_in_dim(mask, x.shape, [0, 1])`

**Comment by oliverdutton-iso** [comment]
Wonderful, thank you. Any reason why the pltpu.repeat exists and use cases for it over broadcast_in_dim?

**Comment by justinjfu** [comment]
Repeat as currently implemented in Pallas is "free" in that the compiler doesn't translate it to an actual broadcast op. Instead it will just repeat any downstream op that consumes the repeated tensor. However, it's limited in usage to cases where the compiler can easily do this. In contrast, broadcast_in_dim actually consumes TPU cycles to compute.
