### ISSUE TITLE
APIs to set the XLA executor's priority

### ISSUE THREAD

**Issue by knightXun** [google/jax#23330]
We found that the priority of XLA's calls to CUDA or CPU is set to default, and we hope this priority can be adjustable.

https://github.com/google/jax/blob/45099b8e09ee87e7ab6531a363ccb832ff4f2a72/jax/_src/xla_bridge.py#L490

**Comment by superbobry** [comment]
@knightXun can you share a bit more about what you are trying to do please? The priority you linked to refers to [platform-specific backend factories](https://github.com/google/jax/blob/45099b8e09ee87e7ab6531a363ccb832ff4f2a72/jax/_src/xla_bridge.py#L166), not executor priority.
