### ISSUE TITLE
jax.random.randint() fails when minval/maxval are traced, but aren't arrays.

### ISSUE THREAD

**Issue by ywrt** [google/jax#23356]
### Description

When using `jax.random.randint()` under nested vmaps and scans, the (non-array) minval and maxval can become traced.

Unfortunately, this causes a failure when `np.shape()` attempts to convert the value to an array to get a shape.

```
...
File "/home/michael/.local/lib/python3.10/site-packages/jax/_src/random.py", line 458, in _randint
    _check_shape("randint", shape, np.shape(minval), np.shape(maxval))
  File "/home/michael/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 2024, in shape
    result = asarray(a).shape
  File "/home/michael/.local/lib/python3.10/site-packages/jax/_src/core.py", line 705, in __array__
    raise TracerArrayConversionError(self)
jax.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on traced array with shape int32[]
The error occurred while tracing the function _randint at /home/michael/.local/lib/python3.10/site-packages/jax/_src/random.py:456 for jit. 
```

This originates from the check in _randint.
```python
@partial(jit, static_argnums=(1, 4))
def _randint(key, shape, minval, maxval, dtype) -> Array:
  _check_shape("randint", shape, np.shape(minval), np.shape(maxval))
  if not jnp.issubdtype(dtype, np.integer):
    raise TypeError(f"randint only accepts integer dtypes, got {dtype}")

  check_arraylike("randint", minval, maxval)
  minval = jnp.asarray(minval)
  maxval = jnp.asarray(maxval)
```

I suspect the fix is to re-order this so that the `_check_shape()` happens after the `jnp.array()` calls?

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.24
jaxlib: 0.4.24
numpy:  1.26.4

**Comment by jakevdp** [comment]
List inputs are invalid for these parameters, whether the elements are traced or not. We could put the `_check_shape` call after `check_arraylike`, and then `check_arraylike` would give a better error. What do you think?

**Comment by ywrt** [comment]
Hmm. My bad, I didn't notice that I was somehow passing a list in, instead of a scalar.
The better error message might be useful, but it's marginal. Closing this!
