### ISSUE TITLE
Bug in single-precision linear system solving 

### ISSUE THREAD

**Issue by lddllddl** [google/jax#23367]
### Description

I initially found the bug solving AX=B in PyTorch, out of curiosity I then tried TensorFlow and Jax, which I rarely use. 
The Jax fp32 solution was much more reasonable than those from PyTorch or TensorFlow, but still wrong for practical purposes, while NumPy was able to produce the correct  answer with single precision.

A,B as python lists can be copied from here https://gist.github.com/lddllddl/6621ce796e09903e7794366d60449ea4

For Jax the reproducing code is
```
import jax
Xj32 = jax.numpy.linalg.solve(jax.numpy.array(A,dtype='float32'),jax.numpy.array(B,dtype='float32'))
print('jax (numpy API) 32',jax.__version__,Xj32.min(),Xj32.max(),
    ((jax.numpy.array(A,dtype='float32') @ Xj32 - jax.numpy.array(B,dtype='float32'))**2).sum())
Xj32 = jax.scipy.linalg.solve(jax.numpy.array(A,dtype='float32'),jax.numpy.array(B,dtype='float32'))
print('jax (scipy API) 32',jax.__version__,Xj32.min(),Xj32.max(),
    ((jax.numpy.array(A,dtype='float32') @ Xj32 - jax.numpy.array(B,dtype='float32'))**2).sum())
Xj64 = jax.numpy.linalg.solve(jax.numpy.array(A,dtype='float64'),jax.numpy.array(B,dtype='float64'))
print('jax (numpy API) 64',jax.__version__,Xj64.min(),Xj64.max(),
    ((jax.numpy.array(A,dtype='float64') @ Xj64 - jax.numpy.array(B,dtype='float64'))**2).sum())
Xj64 = jax.scipy.linalg.solve(jax.numpy.array(A,dtype='float64'),jax.numpy.array(B,dtype='float64'))
print('jax (scipy API) 64',jax.__version__,Xj64.min(),Xj64.max(),
    ((jax.numpy.array(A,dtype='float64') @ Xj64 - jax.numpy.array(B,dtype='float64'))**2).sum())

import numpy as np
Xn = np.linalg.solve(np.array(A),np.array(B))
print('numpy',np.__version__,Xn.min(),Xn.max(),((np.array(A) @ Xn - np.array(B))**2).sum())
Xn32 = np.linalg.solve(np.array(A,dtype=np.float32),np.array(B,dtype=np.float32))
print('numpy 32',np.__version__,Xn32.min(),Xn32.max(),((np.array(A,dtype=np.float32) @ Xn32 - np.array(B,dtype=np.float32))**2).sum())
Xn64 = np.linalg.solve(np.array(A,dtype=np.float64),np.array(B,dtype=np.float64))
print('numpy 64',np.__version__,Xn64.min(),Xn64.max(),((np.array(A,dtype=np.float64) @ Xn64 - np.array(B,dtype=np.float64))**2).sum())
```

Results
```
jax (numpy API) 32 0.4.31 -414.1447 684.9193 20.846794
jax (scipy API) 32 0.4.31 -414.1447 684.9193 20.846794
jax (numpy API) 64 0.4.31 -114.81414097641223 4.718772190879267 1.157631242020755e-16
jax (scipy API) 64 0.4.31 -114.81414097641223 4.718772190879267 1.157631242020755e-16

numpy 2.1.0 -114.81414097641219 4.718772190879264 7.079649230705617e-17
np.array(B,dtype=np.float32))**2).sum())
numpy 32 2.1.0 -114.81414 4.7187724 5.3344417
np.array(B,dtype=np.float64))**2).sum())
numpy 64 2.1.0 -114.81414097641219 4.718772190879264 7.079649230705617e-17
>>> 

```

### System info (python version, jaxlib version, accelerator, etc.)

jax:    0.4.31
jaxlib: 0.4.31
numpy:  2.1.0
python: 3.12.5 (main, Aug 22 2024, 13:11:09) [GCC 14.2.0]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]

( in a Docker container running the official ubuntu image )

**Comment by lddllddl** [comment]
Cross references:

https://github.com/pytorch/pytorch/issues/134905

https://github.com/tensorflow/tensorflow/issues/74965

**Comment by jakevdp** [comment]
The fact that you’re seeing the same issue in so many frameworks makes me suspect that your matrix is ill-conditioned at float32 precision. You can compute its condition number to be sure - it’s probably around `10^9` or larger.

Note that unlike JAX, torch, or tensorflow, NumPy will always do its computations at 64-bit precision even for 32-bit inputs, which would explain why you get better results there.

**Comment by lddllddl** [comment]
You are correct, and the condition number is indeed 5e9 - Interesting though why only JAX gets so much closer? 

> The fact that you’re seeing the same issue in so many frameworks makes me suspect that your matrix is ill-conditioned at float32 precision. You can compute its condition number to be sure - it’s probably around `10^9` or larger. If so, then these results are expected: an ill-conditioned system cannot be solved.
> 
> Note that unlike JAX, torch, or tensorflow, NumPy will always do its computations at 64-bit precision even for 32-bit inputs, which would explain why you get different results there.

**Comment by jakevdp** [comment]
> You are correct, and the condition number is indeed 5e9

In that case, this is behaving as expected, and I think this issue (and the similar issues in the TF & pytorch repositories) can be closed.

> Interesting though why only JAX gets so much closer?

It's probably an accident of implementation. For ill-conditioned linear systems, floating point rounding error dominates, and as you change the details of the implementation (even small things like order of operations) the numerical output can change substantially.
