### ISSUE TITLE
`random.key_impl`wrong return type annotation 

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#23363]
### Description

The code

```python
import jax.random as jr

k = jr.key(1)
impl = jr.key_impl(k)
data = jr.key_data(k)

k2 = jr.wrap_key_data(data, impl=impl)
```
when checked with mypy raises the following error
```python
python-3.11.2 ❯ mypy pp.py
pp.py:7: error: Argument "impl" to "wrap_key_data" has incompatible type "Hashable"; expected "str | PRNGSpec | PRNGImpl | None"  [arg-type]
Found 1 error in 1 file (checked 1 source file)
```

I believe that `key_impl` should return a `PRNGSpec ` instead of an Hashable ?

### System info (python version, jaxlib version, accelerator, etc.)

0.4.31

**Comment by superbobry** [comment]
Thanks @PhilipVinc, this does seem like a typo/outdated annotation. Fix incoming!
