### ISSUE TITLE
what sort of computation caching, if any, does jax provide?

### ISSUE THREAD

**Issue by ogoid** [google/jax#2340]
After having programmed in Haskell, I wonder if jax provides the same environment to write my functions in their mathematical forms without caring for buffering intermediary results to avoid re-computations.

When should I care about building/storing intermediary matrices for functions that are called frequently/at multiple places?

For instance, I'm toying with a rewrite of the trimap package (https://github.com/eamid/trimap). The current official implementation builds matrices not only for the triplets themselves, but also for their weights, which are based on further matrices for the similarities and distances between datapoints; and then uses the triplets and weights to optimize the final embedding.

I wonder if I could do away with all those matrices and simply recall the distance etc. functions as necessary. This includes the triplets list itself: as jax's random number generator is deterministic, I could use `jax.random.fold_in` to simple sample any triplet for a given index.

Would this recompute those values at every call? I suppose if those calls are made inside the same computation graph (like, inside a single `jit`ed function) the optimizer can avoid them? What about multiple calls from non `jit`ed functions?

**Comment by shoyer** [comment]
I believe that in most cases XLA should avoid recomputation if everything is under the same `jit`. But JAX itself has no logic to avoid recomputation, and there’s no caching of computation between calls to jittted functions. If caching is important, you should do that yourself.

**Comment by ogoid** [comment]
Thanks.

Is there a way for me to verify what is actually being recomputed or optimized (outside of writing the intermediary matrices by hand and verifying the impact on performance)? Perhaps by `xla_computation` or some cli tools?
