### ISSUE TITLE
Cannot export with certain symbolic args constraints

### ISSUE THREAD

**Issue by tchatow** [google/jax#23437]
### Description

```
def f1(x,y):
    return x+y

x = jnp.ones((4,), dtype=jnp.int32)
y = jnp.ones((4,), dtype=jnp.int32)
args_specs = jax.export.symbolic_args_specs((x, y), ("a*2", "b*2"), constraints=("a==b",))
exp = jax.export.export(jax.jit(f1))(* args_specs)
```

KeyError: "Encountered dimension variable 'a' that is not appearing in the shapes of the function arguments.\nPlease see https://jax.readthedocs.io/en/latest/export/shape_poly.html#dimension-variables-must-be-solvable-from-the-input-shapes for more details."

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.31.dev20240904
jaxlib: 0.4.31.dev20240904
numpy:  2.0.0
python: 3.11.9 (main, Apr 15 2024, 18:24:23) [Clang 17.0.6 ]
```

**Comment by gnecula** [comment]
Since you use the constraint `a == b`, all occurrences of `a` are replaced by `b`, and at that point the variable `a` does not appear anymore. I agree that this is confusing, but it is easy to work around by just using a single constraint variable instead of use a trivial constraint `a == b`.
