### ISSUE TITLE
Error exporting np.where when unrelated dimension variable is 0

### ISSUE THREAD

**Issue by tchatow** [google/jax#23456]
### Description

```
def f1(x, y):
    return jnp.where(x, 2, 3)

x = jnp.ones((4,), dtype=jnp.bool)
y = jnp.ones((4,), dtype=jnp.int32)
args_specs = jax.export.symbolic_args_specs((x, y), ("a", "b"), constraints=("b<=0",))
exp = jax.export.export(jax.jit(f1))(* args_specs)
```

```
ValueError: Unsatisfiable constraint: b<=0
```

`b<=0` is otherwise a valid constraint (similar error with `b==0`)

### System info (python version, jaxlib version, accelerator, etc.)

```
jax:    0.4.31
jaxlib: 0.4.31
numpy:  2.0.1
python: 3.11.0 (main, Mar  1 2023, 18:26:19) [GCC 11.2.0]
```

**Comment by tchatow** [comment]
This may be related:

```
b, = jax.export.symbolic_shape('b', constraints=['b==5'])
jax.eval_shape(lambda k: jnp.tile(k, 3), jax.ShapeDtypeStruct((b,), jnp.float32))
```
```
jax._src.export.shape_poly.InconclusiveDimensionOperation: Symbolic dimension comparison 'b' >= '0' is inconclusive.
Using symbolic scope 139658045609936 created at <stdin>:1:5 (<module>) with constraints:
  b==5
```
meanwhile constraint `b >= 5` is ok.

**Comment by tchatow** [comment]
For the `np.where` error, the incorrect constraint is generated in `add_implicit_constraints_term`
```
# It is a factor, is it a variable?
if (v := f.to_var()) is not None:
  self.combine_and_add_constraint(Comparator.GEQ, t_e, 1)  # v >= 1
  return
```
Replacing with `>= 0` resolves the issue, but I don't understand the implications of this patch.

**Comment by gnecula** [comment]
The specification of shape polymorphism is that all shape variables have implicitly the constraint `b >= 1` (please see the documentation). Therefore `b <= 0` or `b == 0` are unsatisfiable constraints.

**Comment by tchatow** [comment]
> The specification of shape polymorphism is that all shape variables have implicitly the constraint `b >= 1` (please see the documentation). Therefore `b <= 0` or `b == 0` are unsatisfiable constraints.

Ah, I see I missed this. My use case involves exporting multiple versions of the same function with different constraints, and it turns out having a copy which assumes certain inputs are empty allows substantial optimizations (10x speed up) by eliminating runtime branches on GPU.

I’m also a bit confused since it is legal in JAX to export with a statically known empty shape so I’m not sure why constraints would behave differently.

**Comment by gnecula** [comment]
If you want to allow your shape to be empty, you will need to use `b - 1` as the shape specification. Otherwise a shape `f32[b]` can never be empty. But `f32[b - 1]` can. This choice was because having implicit constraints `b >= 1` allows JAX to prove implicitly many of its shape checks. If we had made the choice to say that shape variables can be any natural number, including 0, then many uses of shape polymorphism would need an explicit constraint `b >= 1`.

**Comment by gnecula** [comment]
> This may be related:
> 
> ```
> b, = jax.export.symbolic_shape('b', constraints=['b==5'])
> jax.eval_shape(lambda k: jnp.tile(k, 3), jax.ShapeDtypeStruct((b,), jnp.float32))
> ```
> 
> ```
> jax._src.export.shape_poly.InconclusiveDimensionOperation: Symbolic dimension comparison 'b' >= '0' is inconclusive.
> Using symbolic scope 139658045609936 created at <stdin>:1:5 (<module>) with constraints:
>   b==5
> ```
> 
> meanwhile constraint `b >= 5` is ok.

This is an actual bug, will be fixed in #23470.

**Comment by tchatow** [comment]
Thanks, `[b - 1]` works as expected.

**Comment by tchatow** [comment]
@gnecula Would you mind taking a look at this one?
```
b, = jax.export.symbolic_shape('b', constraints=['b>= 2'])
jax.eval_shape(lambda x: jnp.arange(x.shape[0]).repeat(x.shape[0]), jax.ShapeDtypeStruct((b-2,), jnp.int32))
```

jax._src.export.shape_poly.InconclusiveDimensionOperation: Symbolic dimension comparison 'b^2 - 4*b + 4' >= '0' is inconclusive.

**Comment by Vjudith77** [comment]
***@***.***
Judith Valenzuela

**Comment by gnecula** [comment]
@tchatow I have tried to explain in the documentation ["JAX has limited support for reasoning with symbolic constraints"](https://jax.readthedocs.io/en/latest/export/shape_poly.html#user-specified-symbolic-constraints). It does not include a complete theorem prover, and likely never will. So, while a human can see that `b^2 -4b + 4` is always >= 0, even more so when `b >= 2`, the JAX symbolic reasoning engine will not be able to verify that.

As explained in the documentation, you can add the constraint "b^2 -4b + 4 >= 0" to work around the limitations, even if it seems redundant.
