### ISSUE TITLE
Jax numpy reduceat function throws error

### ISSUE THREAD

**Issue by varunagrawal** [google/jax#23493]
### Description

Trying to run `np.add.reduceat(data, indices=indices, axis=0)` give the below error:
```
AttributeError: 'jaxlib.xla_extension.PjitFunction' object has no attribute 'reduceat'
```

This is confusing since the [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ufunc.html) says it should work.

Here is a snippet to reproduce the issue:
```python
x = jnp.ones((5, 10))
indices = jnp.array([0, 2])
jnp.add.reduceat(x, indices, axis=0)
```

### System info (python version, jaxlib version, accelerator, etc.)

```
python 3.10.12
```
```
jax:    0.4.31
jaxlib: 0.4.31
numpy:  1.26.4
python: 3.10.12 (main, Feb 26 2024, 17:15:51) [Clang 14.0.0 (clang-1400.0.29.202)]
jax.devices (1 total, 1 local): [CpuDevice(id=0)]
process_count: 1
platform: uname_result(system='Darwin', node='CC-C02FP362Q05P', release='21.6.0', version='Darwin Kernel Version 21.6.0: Mon Dec 19 20:46:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T8101', machine='arm64')
```

**Comment by dfm** [comment]
Thanks for the report and the repro! The full ufunc support described in the docs was just added a week or two ago in https://github.com/google/jax/pull/23304 so this feature isn't available in any release JAX version as far as I know. You can [install JAX from source](https://jax.readthedocs.io/en/latest/developer.html) (I think it would be fine to use the released jaxlib, so source installation wouldn't be too painful) if you need this right away, or I think there will be a new JAX release in the next week or two if it can wait.

**Comment by varunagrawal** [comment]
Oh got it. Thanks for the info @dfm. Is there a way we can schedule docs updates to coincide with releases?

**Comment by dfm** [comment]
There have been requests for more explicit versioning of the docs previously, but that's a bit tricky given how JAX is developed, and we release ~once a month so we've always just landed on the side of always publishing the docs at HEAD. When in doubt, check out the git blame in the source code to see when something was added!

**Comment by varunagrawal** [comment]
Gotcha. I'll close this issue then since it seems like I can get this feature in a few weeks.
