### ISSUE TITLE
Always breaks compilation

### ISSUE THREAD

**Issue by johnnynunez** [google/jax#23503]
### Description

```bash
external/xla/xla/stream_executor/cuda/cuda_status.h:22:10: fatal error: 'third_party/gpus/cuda/include/cuda.h' file not found
#include "third_party/gpus/cuda/include/cuda.h"
```

```bash
python3 build/build.py --enable_cuda --cuda_compute_capabilities=sm_87 --bazel_options=--repo_env=LOCAL_CUDA_PATH="/usr/local/cuda-12.2" --bazel_options=--repo_env=LOCAL_CUDNN_PATH="/usr/lib/aarch64-linux-gnu"
```

### System info (python version, jaxlib version, accelerator, etc.)

Jetson AGX Orin 22.04  cuda 12.2

**Comment by benkirk** [comment]
I have this same issue but see this is now closed, was a fix identified?

**Comment by johnnynunez** [comment]
> I have this same issue but see this is now closed, was a fix identified?

I will automate the compilaton of JAX in Jetson.
https://github.com/dusty-nv/jetson-containers/pull/626#issue-2518380515
