### ISSUE TITLE
jax.lax.nextafter is inconsistent with np.nextafter for float64

### ISSUE THREAD

**Issue by hexahedria** [google/jax#2403]
PR #2393 changes jax.test_util.tolerance to return 0 if given an explicit 0 argument (instead of using a default tolerance). It appears that [a test for `jax.lax.nextafter`](https://github.com/google/jax/blob/ffa03403c9c6d9f071125cdc793c9b88e421cf13/tests/lax_test.py#L86) might have been passing accidentally by using a default tolerance when it was intended to use a tolerance of exactly 0; after the changes in that PR, there are some inconsistencies between the `lax` and `numpy` versions:

```
__________ LaxTest.testOpAgainstNumpyNextafter_float64[3]_float64[3] ___________
[gw0] linux -- Python 3.6.10 /home/travis/miniconda/bin/python
self = <lax_test.LaxTest testMethod=testOpAgainstNumpyNextafter_float64[3]_float64[3]>
op_name = 'nextafter', rng_factory = <function rand_default at 0x7f3fa5c38400>
shapes = ((3,), (3,)), dtype = <class 'numpy.float64'>, tol = 0

...

_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
a = array([5.2921576, 1.2004718, 2.9362137], dtype=float32)
b = array([5.29215704, 1.20047163, 2.93621395]), atol = 0, rtol = 0
    def _assert_numpy_allclose(a, b, atol=None, rtol=None):
      a = a.astype(onp.float32) if a.dtype == dtypes.bfloat16 else a
      b = b.astype(onp.float32) if b.dtype == dtypes.bfloat16 else b
      kw = {}
      if atol: kw["atol"] = atol
      if rtol: kw["rtol"] = rtol
>     onp.testing.assert_allclose(a, b, **kw)
E     AssertionError: 
E     Not equal to tolerance rtol=1e-07, atol=0
E     
E     Mismatched elements: 2 / 3 (66.7%)
E     Max absolute difference: 6.12090903e-07
E     Max relative difference: 1.15660004e-07
E      x: array([5.292158, 1.200472, 2.936214], dtype=float32)
E      y: array([5.292157, 1.200472, 2.936214])
```
PR #2393 disables those tests for now.

**Comment by hexahedria** [comment]
@skye

**Comment by skye** [comment]
I suspect this is a numpy version issue (or a Python version issue? Is that plausible?). This repros with Python 3.6.7 + numpy 1.17.0, but the tests passes with Python 3.7.5 + numpy 1.17.4.

I can narrow it down further, but I'm not sure how to "fix" this short of upgrading the test setup (which I'm in favor of). Does anyone else have thoughts?

**Comment by hawkinsp** [comment]
1e-7 is close to the float32 value, but you'd expect something closer to 1e-15 for float64. Is it possible this test is failing when -x64 mode is disabled by giving the float32 value?

**Comment by skye** [comment]
You're totally right. The version thing was a fluke, my jax install was messed up making it look like it was passing when it wasn't. I'm gonna skip this test if we're testing float64 when -x64 mode is disabled.
