### ISSUE TITLE
Bug in JAX's shape-checking rules for vmap on dynamic_update_slice.

### ISSUE THREAD

**Issue by thomaskeck** [google/jax#2427]
I played around with dynamic_update_slice and hit the following bug:

`
jax.vmap(jax.lax.dynamic_update_slice)(jnp.zeros((3, 10)), jnp.array([1., 1., 1.]), jnp.zeros((3, 1), dtype=jnp.int32))
`

RuntimeError: Invalid argument: Scatter op has window of size 1; doesn't match operand of rank 2.:     @     0x55644e8c711f  xla::Scatter()
    @     0x7f629b6169ed  (unknown)
    @     0x7f629b61fd3d  (unknown)
    @     0x55645d6f942c  _PyCFunction_FastCallDict
    @     0x55645dc77759  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x55645dc778d9  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x556460ca00ff  function_call
    @     0x55645dc77f1b  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x556460ca00ff  function_call
    @     0x55645d89a89f  PyObject_Call
    @     0x556437c92b2f  bounded_lru_cache_wrapper
    @     0x55645dc77f1b  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x556460ca00ff  function_call
    @     0x55645d89a89f  PyObject_Call
    @     0x556437c92b2f  bounded_lru_cache_wrapper
    @     0x55645dc77f1b  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x556460ca00ff  function_call
    @     0x55645d89a89f  PyObject_Call
    @     0x556459088865  partial_call
    @     0x55645dc77f1b  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x55645dc77d79  _PyEval_EvalFrameDefault
    @     0x55645dc7770b  _PyEval_EvalFrameDefault
    @     0x55645dc7770b  _PyEval_EvalFrameDefault
    @     0x55645d87d10c  _PyEval_EvalCodeWithName.llvm.11722122052174390739
    @     0x556460ca00ff  function_call
    @     0x55645dc77f1b  _PyEval_EvalFrameDefault

This is a bug in JAX's shape-checking rules; please report it!
https://github.com/google/jax/issues

Note: The second argument has the wrong shape, so the code should not work, I report it anyway because the trace explicitly asks for it to be reported.

**Comment by hawkinsp** [comment]
Thanks for the report! Yes, it turns out we haven't implemented the shape-checking rule for `scatter` (because it's complicated.) We should do that, although all it will do most likely is give you the same error from Python instead of C++.

The more interesting question to me is whether we should run JAX's shape checking rules earlier during `vmap` tracing, which might have given you a more meaningful error message.
