### ISSUE TITLE
testExamplesJaxprDoc in api_test.py fails on Python 3.5

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#2440]
https://github.com/google/jax/pull/2439 fixes Python 3.5 support in JAX.

However, one test fails under Python 3.5, so I added code to skip it on Python 3.5. I'm guessing this is related to a dependency on set or dictionary ordering somewhere.

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/2445 drops Python 3.5 support, but I suspect there's still a bug here (something is clearly depending on ordering where it shouldn't.) Feel free to close or fix, as you see fit.

**Comment by gnecula** [comment]
I'll just close it.
