### ISSUE TITLE
Need to measure memory usage programmatically

### ISSUE THREAD

**Issue by sracaniere** [google/jax#2451]
It'd be great if there was a way to monitor memory usage programmatically in jax? Something a bit like memory_stats.MaxBytesInUse()  from from google3.third_party.tensorflow.contrib import memory_stats. To start with, I'd like it to work on GPU, but if there's something that works on TPU, I'll take it too 🙂

Some ideas proposed by others (not me):
For GPU, could we extract exactly the same thing that TF is exposing by adding some Python bindings to memory_stats_ops.cc in TF?
Maybe on TPU, we could get equivalent things.

**Comment by hawkinsp** [comment]
We added device memory profiling support: https://jax.readthedocs.io/en/latest/device_memory_profiling.html

Does this resolve this issue, or is there still a need for another API?

**Comment by sracaniere** [comment]
That looks promising, thanks! I suggest we close this issue. I'll open a new one if I have a specific problem with the added device memory profiling.
