### ISSUE TITLE
Initialising arrays using jax.random takes significantly longer than its numpy equivalent np.random.

### ISSUE THREAD

**Issue by h3lio5** [google/jax#2456]
Initializing arrays from the jax.random module takes significantly longer time than its numpy equivalent np.random module. It can be reproduced with the code snippet below. I would appreciate if someone could give me an insight about why this is happening; particularly, I am interested to know in what ways the two initialisation strategies differ.
Thank you.
```Batchfile
import jax
import numpy as np
key = jax.random.PRNGKey(0)

start = time.time()
for i in range(1000000):
    a = np.random.randint(100, size=(100,))
end = time.time()
print("np's randint: ", end-start)

start = time.time()
for i in range(1000000):
    a = jax.random.randint(key, (100,), 0, 100)
end = time.time()
print("jnp's randint: ", end-start)

start = time.time()
for i in range(1000000):
    # a = np.random.randint(100, size=(100,))
    a = np.random.randn(100,)
end = time.time()
print("np's randn: ", end-start)

start = time.time()
for i in range(1000000):
    a = jax.random.normal(key, shape=(100,))
end = time.time()
print("jnp's normal: ", end-start)
```
Output
```Batchfile
np's randint:  19.102942943572998
jnp's randint:  179.5605330467224
np's randn:  3.5840139389038086
jnp's normal:  102.20619702339172
```

**Comment by jakevdp** [comment]
Late to the party here, but when you're running microbenchmarks there are a few things you need to keep in mind to make certain you're measuring what you think you're measuring (see [FAQ: Benchmarking JAX Code](https://jax.readthedocs.io/en/latest/faq.html#benchmarking-jax-code)), and in particular we have a specific FAQ entry for the type of question you're asking here: [FAQ: Is JAX Faster Than NumPy](https://jax.readthedocs.io/en/latest/faq.html#is-jax-faster-than-numpy)?

In this case, applying some of the lessons from those FAQ entries, we can get a better idea of the actual performance differences between these routines (here I use IPython's `%timeit` magic for convenience). The following was computed on a standard Colab CPU runtime:
```python
import numpy as np
from jax import random, jit
from functools import partial

key = random.PRNGKey(0)

# Numpy function
%timeit np.random.randint(100, size=(100,))
# 100000 loops, best of 5: 9.96 µs per loop

# Un-jitted JAX function
%timeit random.randint(key, shape=(100,), minval=0, maxval=100).block_until_ready()
# 10000 loops, best of 5: 22.7 µs per loop

# JIT-compiled JAX function
jit_randint = jit(random.randint, static_argnames=['shape'])
_ = jit_randint(key, shape=(100,), minval=0, maxval=100)
%timeit jit_randint(key, shape=(100,), minval=0, maxval=100).block_until_ready()
# 100000 loops, best of 5: 9.55 µs per loop
```
Hope that helps!
