### ISSUE TITLE
Improved support for nested ShardedDeviceArrays

### ISSUE THREAD

**Issue by trevorcai** [google/jax#2459]
`ShardedDeviceArray`s do not nest. One simple illustration of this is indexing behavior:

```
>>> assert jax.local_device_count() == 8
>>> f = jax.pmap(jax.pmap(lambda x: x))
>>> data = np.broadcast_to(np.arange(8).reshape(2, 4, 1), (2, 4, 2 ** 21))
>>> out = f(data).block_until_ready()
>>> out[0]
... DeviceArray([[0, 0, 0, ..., 0, 0, 0],
                 [1, 1, 1, ..., 1, 1, 1],
                 [2, 2, 2, ..., 2, 2, 2],
                 [3, 3, 3, ..., 3, 3, 3]], dtype=int32)
```
We're returning a DeviceArray with all the data here, instead of another ShardedDeviceArray. This means all the data is moving to one device.

How can I efficiently get an arbitrary single replica's data?
```
# This collects all elements on the second axis to one device before indexing.
>>> %timeit out[0][0].block_until_ready()
... 1 loops, best of 3: 2.64 ms per loop
# This collects all elements onto one device and indexes.
>>> %timeit out[0, 0].block_until_ready()
... 1 loops, best of 3: 19.4 ms per loop
```

I could work around this by manually constructing the DeviceArray:
```
>>> from jax import abstract_arrays
>>> from jax.interpreters import xla
>>> from jax import lazy
>>> def get_from_arbitrary_buffer(sda):
      aval = abstract_arrays.ShapedArray(sda.aval.shape[2:], sda.aval.dtype)
      return xla.DeviceArray(aval, None, lazy.array(aval.shape), sda.device_buffers[0])
>>> %timeit get_from_buffer(out).block_until_ready()
... 100000 loops, best of 3: 6.87 µs per loop
```

But this seems to have weird downstream effects where the buffer doesn't actually match.

**Comment by gnecula** [comment]
@skye is working on changes to ShardedDeviceArray, perhaps this is in the scope of her current work.

**Comment by trevorcai** [comment]
When I filed this issue, I was looking at the immediate consequence of a larger design issue.

My fundamental issue is that I'd like to use nested `jax.pmap` calls to express a grid of computation so that I can easily reduce over different axes of the grid. That is, all my calls to pmap look something like: `jax.pmap(jax.pmap(f, 'inner'), 'outer')`. Semantically, I want to be able to feed sharded inputs (which can be huge!) in & out of each replica individually.

`jax.pmap` also supports something like:
```
def g(x):
  # Arbitrary expensive operation we want to do per-device.
  return jnp.dot(x, jnp.dot(x.T, x))

def f(x):
  y = x - jnp.min(x, axis=0)
  y = jax.pmap(g)(y)
  return jnp.sum(y, axis=0, keepdims=True)

jax.pmap(f)(np.random.normal(size=(2, 4, 8)))
```
This, on one hand, is really cool for expressivity. On the other hand, it mandates that nested pmaps, by default, give each device inputs of size (inner_pmap_size, ...).

This is the opposite of what I want!

I will follow up directly with Skye/James/Matt about this, but posting here in advance.
