### ISSUE TITLE
Batching rule for 'gather' not implemented

### ISSUE THREAD

**Issue by noahstier** [google/jax#246]
Here is a minimal example to reproduce the error.
```
import jax
import jax.numpy as np

a = np.ones((3, 3))
def f(a):
    inds = np.arange(a.shape[0])
    return a[inds]
jax.vmap(f)(a)
```
`NotImplementedError: Batching rule for 'index_take' not implemented`

So if you want to use `vmap`, the only form of indexing you can do is scalar indexing. Am I interpreting this correctly? For me that's a huge limitation.

I would try to implement the batch rule but I think it will be complicated and I have a workaround:
`np.stack([a[ind] for ind in inds])` instead of `a[inds]`. With an ideal JIT compiler those two would be equivalent, but my guess is that the performance of this workaround is not optimal.

**Comment by mattjj** [comment]
Thanks for the request! Fortunately batching rules are pretty easy to write :) We just wait for people to ask for them because we love closing issues.

I started a batching rule in 87673c7 and pushed it to a branch. It should cover examples like the one you wrote. I still need to add support for (1) batching along the index arrays themselves and (2) batching for the transpose operation `index_untake`, which might be needed for vmapping gradients of functions that involve `index_take`. I think both should be pretty straightforward, so I'll get back to them soon.

**Comment by noahstier** [comment]
Thank you for being so responsive! Unfortunately when I run my original example I am hitting the NotImplementedError that you added.

```
import jax
import jax.numpy as np


def index_take_batch_rule(batched_args, batch_dims, **kwargs):
    src = batched_args[0]
    src_bdim = batch_dims[0]
    idxs = batched_args[1:]
    idxs_bdims = batch_dims[1:]
    if any(bdim is not None for bdim in idxs_bdims):
        raise NotImplementedError  # TODO(mattjj)
    axes = tuple(i+1 if i >= src_bdim else i for i in kwargs['axes'])
    return jax.lax.index_take(src, idxs, axes), src_bdim

jax.lax.batching.primitive_batchers[jax.lax.index_take_p] = index_take_batch_rule

a = np.ones((3, 3))
def f(a):
    inds = np.arange(a.shape[0])
    return a[inds]
jax.vmap(f)(a)
```
`NotImplementedError`


```
$ pip freeze | grep jax
jax==0.1.16
jaxlib==0.1.4
```

**Comment by noahstier** [comment]
This seems to work for that case:
```
def index_take_batch_rule(batched_args, batch_dims, **kwargs):
    src = batched_args[0]
    src_bdim = batch_dims[0]
    idxs = batched_args[1:]
    idxs_bdims = batch_dims[1:]
    axes = tuple(i for i in kwargs['axes'])
    return jax.lax.index_take(src, idxs, axes), src_bdim
```

**Comment by mattjj** [comment]
Hm, the example works for me on the branch, and in this code the index array shouldn't have a batch dim on it. Weird! Maybe there's a whitespace issue?

In any case, I'll dig in more when back at a keyboard, either later tonight or tomorrow.

**Comment by noahstier** [comment]
Maybe it doesn't work for me because I'm missing some other recent commit.

I'm using a jax wheel from [here](https://storage.googleapis.com/jax-wheels) and just pasted in your changes from 87673c7 (I would build from source if I could but I can't get bazel to trust the self-signed cert in my network).

**Comment by mattjj** [comment]
Since #307 removed index_take as a primitive, running the OP's code now results in 

```
NotImplementedError: Batching rule for 'gather' not implemented
```

I changed the title of the issue to reflect the new topic: we want a batching rule for `lax.gather`!

**Comment by mattjj** [comment]
Whew! We finally got this one done in #351. The challenge was that [XLA's Gather HLO](https://www.tensorflow.org/xla/operation_semantics#gather) is a bit complex. In fact, it supports more fancy indexing than you can even express in NumPy. But we finally completed the batching rule for it, and as a result we can vmap through all of NumPy's advanced integer array indexing now.

(The story isn't totally over until we get #353 in too, but that should get in momentarily.)
