### ISSUE TITLE
Bug/feature request jax.custom_transforms cannot decorate a method

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#2473]
I'm not sure why this doesn't work:
```
import jax


class C:

    # Works:
    # partial(jax.jit, static_argnums=(0,))
    # Fails:
    @jax.custom_transforms
    def f(self, x):
        return 2 * x


C().f(4.0)
```
I guess
- `jax.linear_utile.WrappedFun` should maybe implement the descriptor protocol, and
- `jax.custom_transforms` should maybe accept a `static_argnums` parameter?

As an aside, is it necessary to `@jax.jit` functions that are decorated with `@jax.custom_transforms`?

**Comment by mattjj** [comment]
Thanks for raising this! If you check out #2026 you’ll see custom_transforms is not long for this world.

**Comment by NeilGirdhar** [comment]
@mattjj Great, I wasn't sure how to proceed with adding custom transforms.  I'll close this in anticipation the linked issue 😄

**Comment by NeilGirdhar** [comment]
@mattjj I just saw that you force-pushed your change?  I'm sorry if this is a bother, but I would really like to start using it now 😃.  I don't see the change in the change history though?  Am I missing something?  Should I wait for it?—or will I get it if I pip install from github?
