### ISSUE TITLE
mypy and pytype for type hints

### ISSUE THREAD

**Issue by gnecula** [google/jax#2474]
As we start using type hints, we have to think about the various methods for enforcing them. At the moment, we use mypy in Travis, primarily because it is fast. But once we import the code into Google we will have to pass pytype checks. These two type checkers are not identical in coverage. 

To start, I plan to add pytype to Travis checks. This will catch typing errors early. 

Longer term it may make sense to figure out how to make pytype fast for JAX.

**Comment by gnecula** [comment]
I had run into situations when mypy passes and pytype does not, also viceversa. The worst is that sometimes to silence the errors a different fix works for each. E.g., `mypy` will accept the var type hint right after the type name `x: Type = foo` (a new Python 3.6 thing), but `pytype` wants a comment instead `x = foo  # type Type`. (mypy accepts the latter too). 

```
x: Tracer = get

**Comment by hawkinsp** [comment]
Do we still want to try adding `pytype` to travis? It's pretty slow, but so long as it isn't our slowest CI build then it probably doesn't matter that much?

**Comment by aslanides** [comment]
+1 to having PyType run on travis. It would be great to have more type safety throughout.

**Comment by gnecula** [comment]
We have since greatly improved the type annotations and we are comfortable with mypy in GH and pytype internally.
