### ISSUE TITLE
Named params in stax

### ISSUE THREAD

**Issue by jimfleming** [google/jax#2498]
It would be useful if parameters in stax were implemented as named tuples to make introspecting instantiated `params` easier. There may be another pattern to accomplish the same goal.

For an example, I implemented a simple gated residual connection, and I'd like to inspect the gate parameter for each layer to understand its progression:

```
GateParams = namedtuple("GateParams", "alpha")

def Gate(alpha_init=zeros):
  def init_fun(rng, input_shape):
    output_shape = input_shape
    alpha = alpha_init(None, ())
    return output_shape, GateParams(alpha)

  def apply_fun(params, inputs, **kwargs):
    alpha = params[0]
    return inputs * alpha

  return init_fun, apply_fun
```

Now with some pattern matching I can pull out instances of `GateParams` from the pytree. Maybe there's an easier way but with nests of unnamed tuples it doesn't appear straightforward to extract this information.

**Comment by hawkinsp** [comment]
Closing, since we don't intend to evolve `stax` any further. `stax` is only intended as an example. If it works for you, great! But for real use we strongly recommend one of the more fully-featured neural network libraries built on top of JAX, such as Flax or Haiku.
