### ISSUE TITLE
Transient bug in Travis about escaped tracers in examples/control_test

### ISSUE THREAD

**Issue by gnecula** [google/jax#2507]
Sometimes in Travis we see the error below. It is suspicious because it sometimes only shows for x64 tests, and if I re-run the tests the error disappears. It is probably some state corruption somewhere.

```
examples/control.py:180: in lqr_predict
    _, X, U = fori_loop(0, T, fwd_loop, (spec, X, U))
examples/control.py:76: in fori_loop
    return lax.fori_loop(lo, hi, loop, init)
jax/lax/lax_control_flow.py:170: in fori_loop
    (lower, upper, init_val))
jax/lax/lax_control_flow.py:227: in while_loop
    body_jaxpr, body_consts, body_tree = _initial_style_jaxpr(body_fun, in_tree, init_avals)
jax/lax/lax_control_flow.py:61: in _initial_style_jaxpr
    wrapped_fun, in_pvals, instantiate=True, stage_out_calls=True)
jax/interpreters/partial_eval.py:393: in trace_to_jaxpr
    jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
jax/linear_util.py:154: in call_wrapped
    ans = gen.send(ans)
jax/interpreters/partial_eval.py:407: in trace_to_subjaxpr
    out_tracers = map(trace.full_raise, map(core.full_lower, ans))
    
E     jax.core.UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
E     The functions being transformed should not save traced values to global state.
E     Details: Can't lift level Traced<ShapedArray(float64[11,2]):JaxprTrace(level=11/0)> to JaxprTrace(level=8/0).
jax/core.py:348: UnexpectedTracerError
=========================== short test summary info ============================
FAILED examples/control_test.py::ControlExampleTest::testIlqrWithLqrProblemSpecifiedGenerally
```

**Comment by gnecula** [comment]
This was mentioned also in chat:

https://travis-ci.org/github/google/jax/jobs/665093795?utm_medium=notification&utm_source=github_status

**Comment by gnecula** [comment]
@froystig Is there anything in the control tests that could save tracers in global state, sometimes?

**Comment by mattjj** [comment]
I looked over that code with @froystig and it all looks canonical to me.

It seems this _only_ repros on Travis, not internally (where we run more tests than travis) or locally (running the same number of tests).

I wonder if this could be travis-specific corruption somehow? Maybe that's too hopeful. But the fact that the same tests pass locally and internally constrains the possibilities of what's going on here.

**Comment by mattjj** [comment]
I think this first arose in #2415, specifically see [this comment](https://github.com/google/jax/pull/2415#issuecomment-600933877) referring to [this Travis failure](https://travis-ci.org/github/google/jax/jobs/664047648?utm_medium=notification&utm_source=github_status). That was before #2026 went in (test failure on March 18, #2026 went in on March 21).

**Comment by mattjj** [comment]
Based on a guess by @hawkinsp , in 1275bc5 I changed the `pytest` command that Travis runs not to take the `-n 1` argument. It seems to have made things go green, but it might just be masking an issue.

**Comment by mattjj** [comment]
Never mind the previous comment: [this run](https://travis-ci.org/github/google/jax/jobs/669044243?utm_medium=notification&utm_source=github_status) failed even without the `-n 1`.
