### ISSUE TITLE
optix.adam produces NaNs with sloppy hyper-parameters

### ISSUE THREAD

**Issue by Hwhitetooth** [google/jax#2517]
I was doing something like this
```python
...
opt_init, opt_update = optix.adam(lr, b1=0)
opt_state = opt_init(params)
...
grads = jax.grad(loss)(params, data)
updates, opt_state = opt_update(grads, opt_state)
params = optix.apply_updates(params, updates)
...
```
and I got NaNs in `updates` but not in `grads`.

The problem was fixed by doing
```python
opt_init, opt_update = optix.adam(lr, b1=0.)
```
(note the dot `.`)

It turns out that the NaNs in the former case came from this line: https://github.com/google/jax/blob/master/jax/experimental/optix.py#L233

I suppose the issue stems from some implicit casting. Is there any chance to explicitly cast the hyper-parameters to the expected type so that sloppy users like me will not get the same trouble again?

Thanks!

P.S. I encountered this issue after upgrading to the latest version. It was fine when I was using JAX 0.1.59.

**Comment by mtthss** [comment]
Thanks for raising this. Interesting! It did indeed use to work fine with ints.
But I think the general issue is that we need more type checking in `optix`.
I will send a pull request for that soon!

**Comment by Hwhitetooth** [comment]
Type annotation was added to optix. Closing this issue.
