### ISSUE TITLE
Add pxla.ShardedDeviceArray to jaxval_zeros_likers

### ISSUE THREAD

**Issue by dpfau** [google/jax#2529]
This is a one-line fix at https://github.com/google/jax/blob/master/jax/lax/lax.py#L1503

Just adding this as an issue as a reminder for @mattjj

**Comment by dpfau** [comment]
Just add `ad_util.jaxval_zeros_likers[pxla.ShardedDeviceArray] = zeros_like_array` below that line

**Comment by dpfau** [comment]
A thought - does `pxla.ShardedDeviceArray` also need to be added to `jaxval_adders`?

**Comment by mattjj** [comment]
Thanks for finding this, and the reminder!
