### ISSUE TITLE
vmap + odeint + grad --> AssertionError

### ISSUE THREAD

**Issue by dsheldon** [google/jax#2531]
I am doing an ode computation that I want to vectorize using vmap. I need gradients. This all works fine until I add vmap --- then I get an AssertionError.

Here is a stripped-down script to reproduce it:

~~~python
import jax
import jax.numpy as np
from jax.experimental.ode import build_odeint

def dx_dt(x, *args):
    return 0.1*x

ode = build_odeint(dx_dt)

def f(x):
    y0 = np.array([x, 0.1])
    t = np.array([0., 5.])
    y = ode(y0, t)
    return y[-1].sum()

def g(x):
    # Two initial values for the ODE
    y0_arr = np.array([[x, 0.1],
                       [x, 0.2]])
    
    # Run ODE twice
    t = np.array([0., 5.])
    y = jax.vmap(lambda y0: ode(y0, t))(y0_arr)
    return y[:,-1].sum()

# Works
print(f(1.))
print(jax.value_and_grad(f)(1.))
print(g(1.))

# Doesn't work
print(jax.value_and_grad(g)(1.))
~~~

Here is the output:
<details>

~~~
1.8135929
(DeviceArray(1.8135929, dtype=float32), DeviceArray(1.6487213, dtype=float32))
3.792058
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-6-1446cf27a440> in <module>
     30 # Doesn't work
     31 print(g(1.))
---> 32 print(jax.value_and_grad(g)(1.))

~/opt/anaconda3/lib/python3.7/site-packages/jax/api.py in value_and_grad_f(*args, **kwargs)
    416     f_partial, dyn_args = _argnums_partial(f, argnums, args)
    417     if not has_aux:
--> 418       ans, vjp_py = _vjp(f_partial, *dyn_args)
    419     else:
    420       ans, vjp_py, aux = _vjp(f_partial, *dyn_args, has_aux=True)

~/opt/anaconda3/lib/python3.7/site-packages/jax/api.py in _vjp(fun, *primals, **kwargs)
   1334   if not has_aux:
   1335     flat_fun, out_tree = flatten_fun_nokwargs(fun, in_tree)
-> 1336     out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
   1337     out_tree = out_tree()
   1338   else:

~/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/ad.py in vjp(traceable, primals, has_aux)
    104 def vjp(traceable, primals, has_aux=False):
    105   if not has_aux:
--> 106     out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
    107   else:
    108     out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)

~/opt/anaconda3/lib/python3.7/site-packages/jax/interpreters/ad.py in linearize(traceable, *primals, **kwargs)
     96   pval_primals, pval_tangents = tree_unflatten(out_tree(), out_pvals)
     97   aval_primals, const_primals = unzip2(pval_primals)
---> 98   assert all(aval_primal is None for aval_primal in aval_primals)
     99   if not has_aux:
    100     return const_primals, pval_tangents, jaxpr, consts

AssertionError: 
~~~
</details>

Can you let me know if I'm trying to do something that is not supported? Or is there some workaround?

**Comment by gnecula** [comment]
This assertion is triggered if you try to do a grad of a lax.while_loop or lax.fori_loop (#2129). I believe that this assertion can also trigger if you have custom gradients (e.g., #2519). Do any of these apply here?

**Comment by mattjj** [comment]
Without looking at the code, I think I have a theory for what's happening here.

First, the version of JAX being used is not from GitHub master but rather the last pypi release (or earlier) because `build_odeint` was removed in #2026. 

Second, this error is being raised because of attempting to do reverse-mode autodiff through a while_loop, as @gnecula said, but the reason has to do with a custom_transforms bug that #2026 fixed: the `vmap` here is effectively removing the custom derivative rule of odeint, hence why this code is differentiating through the implementation of odeint rather than using the custom rule.

Using github master, post #2026, will fix this particular bug. *But* then you'll run into a different vmap-of-odeint bug, which I'm working on in #2500 . In fact, vmap-of-odeint is the main repro I'm using of the last known remaining bug in #2026. 

So in the end vmap-of-odeint is still buggy, but in some sense the error described in this issue's OP is somewhat out of date. (The current behavior is that you get an Unexpected Tracer error.)

**Comment by mattjj** [comment]
Actually, as a workaround using the current version of KAX you’re using (rather than GitHub master) you might try vmap-of-grad instead of grad-of-vmap. Only the latter removes the custom derivative rule. (That is, put the vmap on the outside.)

**Comment by mattjj** [comment]
Here's what I mean:

```python
def h(x, init_val):
  y0 = np.array([x, init_val])
  t = np.array([0., 0.5])
  y = ode(y0, t)
  return y[:, -1].sum()

gradfun = jax.value_and_grad(h, argnums=0)

x = 1.
outs = jax.vmap(lambda init_val: gradfun(x, init_val))(np.array([0.1, 0.2]))
print(np.array(outs))
print(np.array([gradfun(x, init_val) for init_val in [0.1, 0.2]]).T)
```

```
[[0.20512712 0.41025424]
 [0.         0.        ]]
[[0.20512712 0.41025424]
 [0.         0.        ]]
```

I put the `np.array` and transpose on the end there just to make things print out more clearly.

**Comment by gnecula** [comment]
Ah, upon re-reading the message, I saw that the problem is vmap. Thus, I think this is not #2129. It is most likely due to the new code for custom gradients. This is a priority for @mattjj to fix.

**Comment by dsheldon** [comment]
Thanks @mattjj for the response. My real application is a numpyro model and the grad is being taken by the inference routine (NUTS) --- so I don't think I can directly do the grad-of-vmap workaround. But maybe I can define a small module with a custom jvp to encapsulate this piece of the computation?

I'll look into that, but feel free to chime in if If I'm headed in the wrong direction ;)

**Comment by mattjj** [comment]
Unfortunately I think vmap and custom jvp rules aren't friendly right now, neither in the old version of JAX nor on GitHub master, until I fix the bug I'm tracking down (within a few days at most, I hope, though it's already gone on longer than I'd like).

**Comment by mattjj** [comment]
Just curious, is this time sensitive, like COVID-19 modeling stuff?

**Comment by dsheldon** [comment]
Yes, I am working on COVID-19 modeling. I'm somewhat new to numpyro/jax so not completely sure if this is blocking.

**Comment by dsheldon** [comment]
Just to be clear --- do you think vmap will be a problem if it happens _inside_ a custom jvp? I haven't thought this fully through but thought I could write something like `batch_ode` and define a custom jvp for it that does vmap.

**Comment by mattjj** [comment]
> Yes, I am working on COVID-19 modeling.

Awesome! It was a lucky guess based on the combination of Bayesian modeling + ODEs (and the timing).

> Just to be clear --- do you think vmap will be a problem if it happens inside a custom jvp?

I'm really not sure. I haven't thought it through either. But I don't want you to go down a route that ends up with frustrating errors :/

I'm working on this today and so might have made some progress by tomorrow.

**Comment by dsheldon** [comment]
So, this _seems_ to work:

~~~python
def batchify(ode):

    @custom_transforms
    def batch_odeint(x0, t):
        t = np.broadcast_to(t, x0.shape)
        x = jax.vmap(ode)(x0, t)
        return x

    def batch_odeint_vjp(g, ans, x0, t):
        t = np.broadcast_to(t, x0.shape)
        
        # I think this relies on the odeint vjp not using any saved
        # state from the forward pass, but it looks like that's true?
        _, vjp_fun = jax.vjp(ode, x0[0], t[0])
        
        u = jax.vmap(vjp_fun)(g)
        
        # I'm not sure why this needs to be u[0] and not just u
        return u[0]  

    jax.defvjp(batch_odeint, batch_odeint_vjp, None)

    return batch_odeint

def dx_dt(x, *args):
    return 0.1 * x

ode = build_odeint(dx_dt)

def ode_batch_manual(x0, t):
    t = np.broadcast_to(t, x0.shape)
    x = np.stack([ode(x0[i], t[i]) for i in range(len(x0))])
    return x

ode_batch = batchify(ode)

# Inputs
x0 = np.array([[0.1, 0.2],
               [0.3, 0.4]])

t = np.array([0.0, 5.0])

# Forward
x = ode_batch(x0, t)
print(x)

# Reverse
J1 = jacrev(ode_batch)(x0, t)
print(J1)

J2 = jacrev(ode_batch_manual)(x0, t)
print(J2)

print(np.allclose(J1, J2))
~~~

But I think I'm not quite there in terms of a full workaround in the context of my application, so any progress from your end would also be appreciated.

**Comment by dsheldon** [comment]
For what it's worth, I think I've found a suitable workaround for now in a different way --- basically by treating a batch of odes as one big flattened ode, and then moving the vmap all the way down to the dx_dt function.

~~~python
def build_odeint_batch(dx_dt, **kwargs):
    
    def dx_dt_batch(x, t, *args):
        '''
        Time derivative for a flattened batch of inputs to dx_dt
        
        x is the flattened batch of inputs: shape (batch_sz * d,)
        t is a scalar
        other args have shape (batch_sz,) 
        
        Strategy: reshape x to (batch_sz, d) and call vmap(dx_dt)(...),
        then reshape derivative back to (batch_sz * d,)
        '''
        batch_sz = len(args[0])
        x = x.reshape(batch_sz, -1)
        d = jax.vmap(dx_dt, in_axes=(0, None) + (0,) * len(args))(x, t, *args)
        return d.ravel()
    
    ode = build_odeint(dx_dt_batch, **kwargs)
    
    def odeint_batch(x0, t, *args):
        batch_sz, d = x0.shape
        x = ode(x0.ravel(), t, *args)
        # Result has shape (T, batch_sz * d). Convert to (batch_sz, T, d)
        return x.reshape(len(t), batch_sz, d).swapaxes(0,1)

    return odeint_batch
~~~

**Comment by mattjj** [comment]
Thanks so much for working on a workaround, and also sharing it here so clearly.

I added a test for this in #2500 and things seem to work there, but I was kind of in a rush and may have missed some things. Don't let this drop if it still seems buggy!

**Comment by dsheldon** [comment]
Thanks for the fix! I finally had a chance to upgrade my jax version and test this --- it works seamlessly.
