### ISSUE TITLE
"ERROR: jax.test_util.format_test_name_suffix" during JAX test

### ISSUE THREAD

**Issue by HerculesJack** [google/jax#254]
I'm using JAX on SUSE 12, with Python 3.6.6 and GCC 7.2.0 in Anaconda. The binary version doesn't work for me because it needs GLIBC 2.23 while I only have 2.14, so I built it from source. FYI, I changed `[bazel_path, "run", "--verbose_failures=true"]` to `[bazel_path, "run", "--verbose_failures=true", "--linkopt=-lrt"]` in line 302 of `build.py`, which is also because of GLIBC.

The problem is, I found that if I do `python -m "nose"`, it says
```
======================================================================
ERROR: jax.test_util.format_test_name_suffix
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/homes/h/hejia/.conda/envs/hejia@cori/lib/python3.6/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
TypeError: format_test_name_suffix() missing 3 required positional arguments: 'opname', 'shapes', and 'dtypes'
----------------------------------------------------------------------
Ran 4206 tests in 267.815s
FAILED (SKIP=47, errors=1)
```

Then I tried all the python scripts in `/jax/tests/`, but none of them went wrong, and I haven't found any other bugs so far. Maybe there's something wrong with the test script?

**Comment by hawkinsp** [comment]
What version of `nose` do you have installed?

**Comment by HerculesJack** [comment]
> What version of `nose` do you have installed?

It's `nose 1.3.7`. And I've just found out the reason. I should run `python -m "nose" tests` (or `nosetests tests`), instead of simply `python -m "nose"`. This time it passed all the tests.

**Comment by hawkinsp** [comment]
Great! Thanks for figuring out what was happening!
