### ISSUE TITLE
grad of cumprod gives errors

### ISSUE THREAD

**Issue by ofer-kimchi** [google/jax#2542]
Hi JAX team,

One issue I just ran into is that np.cumprod is not differentiable.

Example:
```python
y = grad(np.cumprod)
y(np.arange(1, 5))
``` 
gives an error

For my pruposes, the vectors I input are all positive, so I can just do:

```python
def cumprod_working(arr):
  return(np.exp(np.cumsum(np.log(arr)))
```

And that can be differentiated just fine.

**Comment by hawkinsp** [comment]
`cumprod` is now differentiable to arbitrary order at head.
