### ISSUE TITLE
jax.numpy.lib.stride_tricks.as_stride is missing

### ISSUE THREAD

**Issue by giangtranml** [google/jax#2568]
Hi, I want to implement fast convolution by stride_tricks of numpy, but It's missing in jax.numpy. Do you have plan to update or there is an alternative way? Please let me know, thanks.

**Comment by hawkinsp** [comment]
JAX doesn't support striding at the moment, so I don't think it is possible to implement `stride_tricks`.

However, if you just want convolutions, happily the lower-level `lax` library already exposes them, and they should be efficient (e.g., on GPU they lower onto CuDNN).

https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.conv_general_dilated.html#jax.lax.conv_general_dilated

Does that do everything you need?
