### ISSUE TITLE
from jax import custom_vjp, with latest pip install

### ISSUE THREAD

**Issue by jemisjoky** [google/jax#2576]
Trying the following import after reading the lovely [custom derivatives notebook](https://jax.readthedocs.io/en/latest/notebooks/Custom_derivative_rules_for_Python_code.html) gives an import error:

```python
from jax import custom_vjp
# ImportError: cannot import name 'custom_vjp' from 'jax'
```

I'm using the latest JAX release (0.1.62), and am guessing `custom_vjp` just hasn't made it into there yet. Any sense of when it'll be available via pip?

**Comment by mattjj** [comment]
Glad you liked the notebook!

Yes, quite a cruel trick we've played on users not to update pypi. The main reason is that `custom_jvp` / `custom_vjp` needed some kinks worked out first; they were buggier than I thought! I think all the bugs are squashed now, though I also thought that earlier today, before seeing #2578 which will be fixed momentarily by #2593. Clearly _that_ was the last bug, though.

I'll update pypi when #2593 gets in!

**Comment by jemisjoky** [comment]
Thanks @mattjj :)

**Comment by mattjj** [comment]
That was slower than I intended :) Just uploaded jax==0.1.63 to pypi!

**Comment by jemisjoky** [comment]
Thanks @mattjj, looking forward to trying it out myself 😄
