### ISSUE TITLE
How to implement autograd's notrace_primitive in Jax

### ISSUE THREAD

**Issue by tel** [google/jax#2589]
Hi JAX team,

I'm attempting to translate an autograd algorithm to JAX, but am struggling to work around differentiating a call to `np.digitize`. In the original implementation, this is merely protected with a `@notrace_primitive` decorator—clearly the actual derivative contribution doesn't matter, which is good because digitize clearly won't have great derivatives.

How can I do something similar in JAX? Is there also a decorator? I could not find anything similar in the docs. I've considered adding a primitive to wrap digitize with some kind of no-op derivative, but I'm not sure how to do that either.

Any help appreciated!

**Comment by mattjj** [comment]
Good idea! I don't think we have something with the same API, but we do have [`jax.lax.stop_gradient`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.stop_gradient.html#jax.lax.stop_gradient).

Is the other API better?

**Comment by tel** [comment]
Honestly, I think `stop_gradient` works just fine, I just struggled to find it. 

I guess it's a rarer feature, but I spent a good while looking for something like that unsuccessfully. Thanks for pointing me to it!
