### ISSUE TITLE
Add all interpolation methods to quantile (and percentile)

### ISSUE THREAD

**Issue by matthewfeickert** [google/jax#2607]
# Description

At the moment, only the "linear" interpolation method from [`numpy.quantile`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.quantile.html) and by extension [`numpy.percentile`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.percentile.html) are implemented (as [noted in Issue #70](https://github.com/google/jax/issues/70#issuecomment-509322341)) 

https://github.com/google/jax/blob/1cf708ea77fae0fc1418e0b944f0115646f7f2ec/jax/numpy/lax_numpy.py#L3446-L3447

It would be useful to also have the "nearest" interpolation method, along with the others ("lower", "higher", "midpoint") implemented as well.

cc @lukasheinrich @kratsg

**Comment by shoyer** [comment]
Agreed, this would be nice to have. Contributions would be very welcome here!

**Comment by matthewfeickert** [comment]
> Agreed, this would be nice to have

Great to hear that you're in agreement. I realistically won't have time to give this a shot for at least 2 weeks, but I'll try to do so then and open a PR once I pass the tests. If someone beats me to it that's great too of course. :)
