### ISSUE TITLE
jax_debug_nans does not work with complex numbers

### ISSUE THREAD

**Issue by sracaniere** [google/jax#2612]
Running with flag --jax_debug_nans:

With this this, I get no error (but I do get nans):
```
  @jax.jit
  def fn(x):
    return (x * 0.) / jnp.zeros_like(x)
  print(fn(1j * jnp.ones([2, 3])))
```

but with this, I get an error (as expected):
```
  @jax.jit
  def fn(x):
    return (x * 0.) / jnp.zeros_like(x)
  print(fn(jnp.ones([2, 3])))
```

Could we add support for nan detection on complex numbers?

**Comment by ibab** [comment]
The issue seems to be that the nan checker only looks for `floating` types, not `complexfloating`. Numpy can detect complex nans just fine, so this should be a one line change in this line:
https://github.com/google/jax/blob/master/jax/interpreters/xla.py#L282
