### ISSUE TITLE
`expm([[inf]])` hangs

### ISSUE THREAD

**Issue by terhorst** [google/jax#2634]
If you try to exponentiate a matrix containing `inf` (sort of a silly thing to do, but can happen during numerical optimization), the JAX implementation will hang:

```
>>> scipy.linalg.expm([[np.inf]])
array([[inf]])
>>> scipy.linalg.expm([[-np.inf]])
array([[0.]])
>>> jax.scipy.linalg.exp([[np.inf]])
<runs forever>
>>> jax.scipy.linalg.exp([[-np.inf]])
<same>
```
It's because `n_squarings` is defined equal to the log of the matrix norm, so you wind up in an infinite loop:

https://github.com/google/jax/blob/fa383b4a9fdfd615093767e8af62275b43a56d7a/jax/scipy/linalg.py#L296

Regular `scipy` does the correct thing because for the special case of 1d matrices it drops to `np.exp`. For higher dimensional matrices it throws an exception:

```
>>> scipy.linalg.expm([[np.inf, 0],[0, np.inf]])
...
ValueError: cannot convert float NaN to integer
```

**Comment by terhorst** [comment]
When attempting to work around this, I encountered another expected behavior. Using `jax.lax.cond` to detect non-finite values does work; if I define
```
def safe_expm(A):
    def bad(A):
        return np.full_like(A, np.nan)
    return jax.lax.cond(
        np.all(np.isfinite(A)),
        A, jax.scipy.linalg.expm,
        A, bad
    )
```

then 
```
A = np.array([[np.inf]])
safe_expm(A)
```
correctly returns `array([[np.inf]])`. However,
```
jax.vmap(safe_expm)(np.array([A,A]))
```
still hangs.

**Comment by terhorst** [comment]
This is easy enough to work around in `expm`, and I can submit a PR, but I have to wonder: why should `lax.fori_loop` *ever* allow `upper=+inf`? As far as I can tell there's no way to break out of the loop once it runs.

**Comment by jekbradbury** [comment]
It looks like you're on the right track but it's a bit more complicated. `fori_loop` uses `lax.scan` when it has a static trip count, but it uses `lax.while_loop` when its trip count depends on runtime values. In the lowering to `scan`, there's a conversion to integer; in the lowering of `fori_loop` to `while_loop` there [isn't](https://github.com/google/jax/blob/3ca7f6e4f120853a5f0c9f98c6b8b2db30300820/jax/lax/lax_control_flow.py#L160). But maybe there should be a `cond` added to the dynamic for lowering so the loop is replaced by something like `return nan` if the min or max of the for loop is `inf` or `nan`?

I believe the reason for `vmap` bringing back the hang is that `vmap(cond)` switches its implementation to using `lax.select` (predication) whenever the condition is vmapped. Even though, in this case, the condition is the same across the batch, we don't know that when we compile the jitted function—and we don't have a fast path for returning to `cond` at runtime when we do figure that out. Maybe we should!

WDYT?

**Comment by terhorst** [comment]
Sorry, lost track of this issue. Honestly, I don't know enough about JAX to weigh the pros and cons of these various approaches. I'd settle for being able to check
