### ISSUE TITLE
"Unexpectedly high number of iterations" with clip_grads

### ISSUE THREAD

**Issue by John-Boik** [google/jax#2639]
I am getting an error/warning message when using clip_grads. The message is:
"external/org_tensorflow/tensorflow/compiler/xla/service/hlo_pass_fix.h:49] Unexpectedly high number of iterations in HLO passes, exiting fixed point loop." 

Does anyone know what this means, or how to call clip_grads so it doesn't occur? Does it affect any results?

In the code, with option == 1 (no jit for clip_grads), the message occurs five times. The number is dependent on the number of dense layers in the neural network. If option==1 (with jit), the message occurs only once. I assume the others are suppressed.

Incidently, apart from clip_grads, I also get the message (once) if I change the neural net to one input and send X[:,0] to it in net_apply().

And I also get the same message when I call odeint().

I'm using jax version '0.1.62' and jaxlib version '0.1.43' on the GPU.  

```
from jax import grad
from jax import random
from jax import jit 

from jax.experimental import stax 
from jax.experimental.stax import Dense, Tanh,  BatchNorm
from jax.experimental import optimizers

# setup neural network -------------------------------
L = 2
net_init, net_apply = stax.serial(
    Dense(L), Tanh,
    Dense(L), Tanh,
    Dense(2)
    )

rng = random.PRNGKey(0)
rng, subkey = random.split(rng)

out_shape, net_params = net_init(subkey, (-1, 2))  
opt_init, opt_update, get_params = optimizers.adam(step_size=.001)
opt_state = opt_init(net_params)

# option for jit clip_grads --------------------------
def clip(gr):
    return optimizers.clip_grads(gr, 4)

clip_jit = jit(clip)

# loss function --------------------------------------
def loss(params, X):
    ans = net_apply(params, X[:,0:2])
    return 1.  # return dummy loss

# step function --------------------------------------
def step(opt_state, X):
    params = get_params(opt_state)
    
    gr = grad(loss, argnums=(0,)) (params, X)
    print(len(params))
    # try different options
    option = [0,1,2][2]
    if option == 0:
        gr = optimizers.clip_grads(gr, 4)
    
    elif option == 1:
        gr = clip_jit(gr)
    
    elif option == 2:
        pass
    
    return 1.  # return dummy value

# setup data -----------------------------------------
rng, subkey = random.split(rng)
N = 50
X = random.normal(subkey, (N, 10))

# call step ------------------------------------------
for ii in range(2):
    result = step(opt_state, X)

```

**Comment by mattjj** [comment]
Thanks for the question!

> Does anyone know what this means, or how to call clip_grads so it doesn't occur? Does it affect any results?

I believe it would only affect performance, not correctness. It's an XLA optimization taking too long.

We've seen this warning pop up recently in a few contexts. On GPU at least I believe it's fixed in the latest version of XLA, which we need to build and upload as a new jaxlib release (jaxlib is basically our release of XLA).

We can probably close this issue once we upload a new jaxlib. In the meantime, please ignore the warning!

**Comment by mattjj** [comment]
cc @hawkinsp since he fielded some questions about this earlier.

**Comment by hawkinsp** [comment]
I suspect this is benign and further I suspect it will go away when we make a new `jaxlib` release.

**Comment by hawkinsp** [comment]
You might try again with the newly released `jaxlib` 0.1.44. It may or may not fix the problem.

**Comment by hawkinsp** [comment]
Unfortunately the new jaxlib does not remove the warning. But I would ignore it for now; it's benign.

**Comment by hawkinsp** [comment]
This warning was fixed! (I'm not sure entirely when, but it's fixed at head...)
