### ISSUE TITLE
Why and how to use check_grads?

### ISSUE THREAD

**Issue by durian888** [google/jax#2648]
I'm curious what is the purpose of check_grads  and how should it be used - it seems to return no values and there are no comments associated with the code.

**Comment by shoyer** [comment]
`check_grads` is an internal test utility for verifying that gradients are calculated correctly by JAX's automatic differentiation rules. It compares to finite differences in a randomly chosen direction, so the runtime is still `O(1)` (independent of the dimensionality of the input/output space).

**Comment by durian888** [comment]
Hi Stephen,

Thank you for the info - will check_grads throw an exception if its comparison between algorithmic diff and finite differences fails?

Dominic
________________________________

**Comment by shoyer** [comment]
Yes, see #2656 for a docstring.

**Comment by durian888** [comment]
Thank you!
