### ISSUE TITLE
FeatureRequest: A way to build a ShardedDeviceArray one shard at a time

### ISSUE THREAD

**Issue by peterjliu** [google/jax#2651]
Use case: As part of model, I have an array that uses memory, A, that exceeds the memory of a single device, S, so is sharded using ShardedDeviceArray across multiple devices with total memory NS (assume N devices with same memory). Suppose I have host memory H. If A<H we are good. But it'd be nice to support the the case where A>H but H<NS. This may be achieved by having the ability to build a ShardedDeviceArray one shard at a time, assuming H>S. That way the host only needs memory S instead of NS to build the ShardedDeviceArray.

**Comment by hawkinsp** [comment]
I think these days this is covered by https://jax.readthedocs.io/en/latest/_autosummary/jax.make_array_from_single_device_arrays.html
