### ISSUE TITLE
Documentation: `custom_jvp` functions not allowed to close over values

### ISSUE THREAD

**Issue by danieldjohnson** [google/jax#2676]
Functions passed to `custom_jvp` must be top-level, i.e. they should not be nested inside functions, and, more specifically, should not close over any values. For instance, this is not allowed:
```
def foo(x, y):

  @jax.custom_jvp
  def bar(z, y):
    return z + y
  
  @bar.defjvp
  def bar_jvp(primals, tangents):
    # ... some custom JVP here ...
    pass

  return bar(x, y) + x
```
and this manifests as an error
```
jax.vmap(foo, (None, 0))(jnp.array(1.), jnp.array([4.,5.,6.]))
# UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer
# escaped through global state from a previously traced function.
# The functions being transformed should not save traced values to global state.
# Details: Can't lift sublevels 1 to 0.
```
However, this isn't explicitly documented right now.

@mattjj

**Comment by marcvanzee** [comment]
I'm having a similar error in my code, and I'd like to fix it, but the example given in this thread does not produce an error when I try it. I tried it on a public Colab on which I installed Jax from Git.

**Comment by mattjj** [comment]
After #4008, this works!
