### ISSUE TITLE
No "subok" argument in np.array

### ISSUE THREAD

**Issue by oliverastrand** [google/jax#2683]
Hi, while working on some of the uncompleted numpy functions I noticed that the "subok" argument is missing from the [np.array function](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.array.html#jax.numpy.array). Is there any reason for that or plan to include it?

**Comment by shoyer** [comment]
JAX doesn't support subclassing its array objects, so the argument is irrelevant.

**Comment by oliverastrand** [comment]
Okay, great thanks!
