### ISSUE TITLE
Add index_mul, index_div, index_pow

### ISSUE THREAD

**Issue by dpfau** [google/jax#2694]
Currently the only scatter operations implemented as primitives are update, add, min and max. `index_update` has limited support for transposing, which means some custom_jvp rules implemented using `index_update` cannot be automatically converted into vjp form. Extending the indexing operations would fix this, in particular in the fix for issue #2380.

**Comment by dpfau** [comment]
One third of the way there!

**Comment by hawkinsp** [comment]
#6706 will fix. It turns out that it's easy to add `div` and `pow` once you have `mul`, although I admit the version I added densifies the update more than is needed. We can address that in a future PR if it matters.
