### ISSUE TITLE
Cloud TPU Support

### ISSUE THREAD

**Issue by aidangomez** [google/jax#27]
Hello all,

Super stoked about this project and so glad it's out in the open now! I just wanted to make an issue people can follow to track the support of Cloud TPUs in JAX.

As soon as this is ready to be tested [for.ai](https://for.ai) and I would be super eager to give it a try and help out!

All the best,
Aidan

**Comment by mattjj** [comment]
Great idea! Thanks for opening this. We're working on Cloud TPU support, and will use this issue to track updates.

**Comment by Superman132** [comment]
Does cloud tpu support mean colaboratory tpu support, or is that a seperate issue?

**Comment by mattjj** [comment]
They're related, and will probably be solved simultaneously.

**Comment by dynamicwebpaige** [comment]
Pinging for a status check / update. 🙂

**Comment by joaogui1** [comment]
Guess we can close this? @mattjj, @skye

**Comment by skye** [comment]
Thanks for the ping @joaogui1 !

To everyone following this thread, JAX can now be used with Cloud TPUs! It's still early in development, so we'd appreciate your help trying it out. See https://github.com/google/jax/tree/master/cloud_tpu_colabs.
