### ISSUE TITLE
Failed to connect to my own TPU node on GCP

### ISSUE THREAD

**Issue by HLuSLB** [google/jax#2700]
I tested to duplicate the work I did on colab and run on my Google Cloud Platform. Therefore, I followed this tutorial [https://cloud.google.com/tpu/docs/tutorials/mnist](url) and used the following **ctpu up** to set up VM and cloud TPU resources.
`ctpu up --zone=europe-west4-a \`
`--machine-type=n1-standard-8 \`
`--tf-version=1.15.2 \`
`--name=mnist-tutorial`

It successfully ran the model on a TPU node by using TensorFlow backend. In addition, using the following lines also shows available TPU cores correctly
`tpu_address = os.environ['TPU_NAME']`
`cluster_resolver = tpu_lib.tpu_initialize(tpu_address)`
`tf.distribute.experimental.TPUStrategy(cluster_resolver)`

Then, I tried to connect to my own TPU node on GCP by using JAX backend by the following lines:
`from jax.config import config`
`from jax import random`
`# The following is required to use TPU Driver as JAX's backend.`
`config.FLAGS.jax_xla_backend = "tpu_driver"`
`config.FLAGS.jax_backend_target = "grpc://<TPU-IP-ADDRESS>:8470"`
`key = random.PRNGKey(0)`
`x = random.normal(key, (10,))`
`print(x)`

However, I got some errors like 
![image](https://user-images.githubusercontent.com/55214931/79151937-35325b80-7d80-11ea-8f10-a91400f50d1a.png)

The deployment for the test is as below:
jax==0.1.54 
jaxlib==0.1.37 
Python 3.6.10
TPU software version = 2.1

**Comment by henrytansetiawan** [comment]
Hi HLuSLB,

Thanks for sharing the repro step above, from what I can tell, the TPU backend you created using the ctpu instruction didn't specify the right backend to run.

To run JAX with the right Cloud TPU backend, you may want to follow the steps outlined here:
[running JAX on a cloud tpu](https://github.com/google/jax/tree/master/cloud_tpu_colabs#running-jax-on-a-cloud-tpu-from-a-gce-vm).

Let us know if after following the instruction you still encounter some issue to run JAX on Cloud TPU.

**Comment by HLuSLB** [comment]
Hi @henrytansetiawan, 
Thanks for your reply. After I specified the right backend to run, I am able to use the cloud TPU nodes I created. 
Thanks again.
