### ISSUE TITLE
Feature request: allow jnp.allclose to accept tracers

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#2708]
It appears that explicitly doing the `allclose` (or something like it) works, but `allclose` does not support tracers.  Would it be possible to make `allclose` work?
```
from jax import numpy as jnp
from jax.lax import while_loop


def bf(x):
    return x + 1.0


def cf_ac(x):
    return not jnp.allclose(x, 10.0)


def cf_explicit(x):
    return jnp.abs(x - 10.0) > 1e-4


print(while_loop(cf_explicit, bf, 0.0))
print(while_loop(cf_ac, bf, 0.0))
```
prints
```
10.0
Traceback (most recent call last):
...
TypeError: Abstract value passed to `bool`, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```

**Comment by shoyer** [comment]
The problem here is not `jnp.allclose()`, it's your use of the builtin Python operator `not`, which always casts its inputs into Python booleans using `bool`, as appears in the error message.

If you substitute `jnp.logical_not` your example works:
```python
def cf_ac(x):
    return jnp.logical_not(jnp.allclose(x, 10.0))
```

**Comment by NeilGirdhar** [comment]
Okay, great explanation, thank you!  I didn't realize that's what was happening in the stack trace.  It's another "sharp bit" that I won't forget :)
