### ISSUE TITLE
Jit + Optional argument have slightly surprising behavior 

### ISSUE THREAD

**Issue by botev** [google/jax#2720]
The following code works as intended, but I was very surprised it works:
```
import jax.lax as lax
def f(logits, x_in):
  if x_in is None:
    return logits
  else:
    return logits + x_in

h = jax.jit(f)
a = np.random.randn(10).astype("float32").reshape([1, -1])
print(h(a, 1.0))
print(h(a, None))
```
The main reason is that here `x_in` is not a static_argnum but it seems that it is treated like one. The actual reason is that `None` is treated like a different pytree node and `jit` uses the pytree to hash. As a result I think this should be documented somewhere a bit better so that people do not get confused by this behavior.

**Comment by froystig** [comment]
Does [the control flow section](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-+-JIT) in the "common gotchas" notebook render this less surprising? The notebook section is also linked to by [the main README](https://github.com/google/jax#current-gotchas).

> here `x_in` is not a static_argnum but it seems that it is treated like one

Note that the _type_ of the second argument changes when going from `1.0` to `None`, not only its value.

**Comment by mattjj** [comment]
I think the fact that the type changes here, together with the fact that JAX API-level functions handle Nones, is the answer for why this works.

I'm going to close this because I think the mystery is dispelled.
