### ISSUE TITLE
Support frozen distributions for `jax.scipy.stats`

### ISSUE THREAD

**Issue by ziyadedher** [google/jax#2735]
I am working in a code-base that involves a lot of passing distribution objects around instead of their underlying parameters, a feature which does not really exist with JAX's implementation of the `scipy.stats` module.

For example, here is something I am able to do with `scipy.stats.norm` that I am not able to do in the same straightforward manner using the JAX implementation:
```python
import jax
import scipy

# After constructing the frozen distribution, passing it around or using it is pretty simple.
scipy_frozen_norm = scipy.stats.norm(loc=1, scale=1)
print(scipy_frozen_norm.logpdf(2))

# Emulating this is simple, but can be quite tedious.
jax_frozen_norm_logpdf = lambda x: jax.scipy.stats.norm.logpdf(x, loc=1, scale=1)
print(jax_frozen_norm_logpdf(2))

# This errors since `norm` is just a module.
jax_frozen_norm = jax.scipy.stats.norm(loc=1, scale=1)
```
Frameworks such as `scipy` and `pytorch` have support for these "frozen" distributions that have their parameters set at initialization alongside their regular support for dynamically constructed distributions. As it is closest, I will focus on `scipy` here.

`scipy` has quite a complex mechanism governing the construction of these frozen distributions, something I think might not be worth re-implementing in JAX. Every `scipy` distribution implements a common class interface of functions that are manipulated by a [higher-order class](https://github.com/scipy/scipy/blob/master/scipy/stats/_distn_infrastructure.py#L1375) that allows their calling using frozen parameters in a method setting and dynamic parameters in a function setting.

Given that JAX has scrapped most of that framework for a simpler functional approach (which is in-line with JAX's general principles I believe), it would be a bit tricky to try to implement the same technique as `scipy` for frozen distributions. Instead, we might be able to somewhat emulate the functionality that `scipy` provides by wrapping existing `jax.scipy.stats` functions with functionality that dynamically constructs classes that construct module functions with bound parameters at the dynamically constructed class's object initialization. Probably easier to show than tell:
```python
class Frozen:
    def __init__(self, raw_funcs, assignment):
        self.funcs = {}
        for raw_func in raw_funcs:
            self.funcs[raw_func.__name__] = functools.partial(raw_func, **assignment)

    def __getattr__(self, attr):
        if attr in self.funcs:
            return self.funcs[attr]
        raise AttributeError()


class Freezer:
    def __init__(self, *frozen_names):
        self.frozen_names = frozen_names
        self.funcs = []

    def wrap(self, f):
        # TODO: check that it has frozen_names
        self.funcs.append(f)
        return f

    def construct_freeze(self):
        def freeze(**assignment):
            # TODO: check against frozen_names
            return Frozen(self.funcs, assignment)
        return freeze
```
Using this we could construct a single `Freezer` per distribution with the set bound parameter names and wrap all distribution functions using `wrap`. Then we can promote a function in the module that calls the function returned by `construct_freeze` which in turn creates the `Frozen` objects which inherit all the wrapped functions by way of `__getattr__` and bind them at initialization.

Questionable whether this falls under what JAX would consider the scope of the project, but it is definitely something I would be using. I do have a rudimentary implementation of this system that I am currently using in my projects, if this issue is in-scope I can draft up a simple PR for reference.

**Comment by jacobjinkelly** [comment]
Can +1 that this would be super useful for me as well! KL divergence between some of these distributions would also be super cool (though probably outside the scope of JAX)

**Comment by jekbradbury** [comment]
Great work, @ziyadedher! I agree that this is one of those cases where we probably don't want to follow the NumPy/SciPy API exactly.

One question others on the JAX team raised is whether we can come up with crisp advantages that a class-based frozen distribution API offers over `functools.partial` (one possibility is better introspection). If we don't find enough such advantages, it might be worth documenting `partial` as the supported way to do this (that doesn't mean you can't use this implementation in your own code if you find it more convenient).

**Comment by ziyadedher** [comment]
Those are definitely some important questions @jekbradbury, but I think that I can come up with some advantages to using a limited object-oriented approach to this even though it somewhat conflicts with the functional nature of JAX.

Firstly, I do not think that the rudimentary approach I propose here and implement in #2745 provides any better introspection than `functools.partial`: most functional class-members are hidden behind runtime defined variables, and so static introspection would be quite difficult. Runtime introspection would be on-par with `functools.partial` unless I am missing something. However, a set frozen distribution API would provide this elevated introspection at the cost of that API being inherited by all distributions (which honestly does not seem like such a bad thing). 

In terms of clear-cut advantages, I can think of a few that would help me personally:
1.  Alleviates the repetition in cases where multiple distribution functions are to be bound to the same parameters.
```python
loc, scale = 1, 2

logpdf = partial(jax.scipy.stats.norm.logpdf, loc=loc, scale=scale)
ppf = partial(jax.scipy.stats.norm.ppf, loc=loc, scale=scale)
# etc...

norm = jax.scipy.stats.norm.freeze(loc=loc, scale=scale)
logpdf = norm.logpdf
ppf = norm.ppf
# etc...
```

2. Provides a nice structure to deliver distribution information to functions. If you wanted to effectively pass a distribution to a function currently you have a couple choices: either fix and agree on the family of distribution and pass in the specific parameters for that distribution (e.g. `loc` and `scale` for a Gaussian), this brings up the issue of repetitiveness; or pass in bound functions that you defined previously which can get cumbersome with passing in multiple functions (but allows an arbitrary underlying distribution to be used). This approach brings those together in an object-oriented manner by packaging the parameters and their respective functions together.

3. As @jacobjinkelly mentioned, this also affords extensibility of the frozen distribution API for implementations of other standard manipulations on distributions.

Perhaps it would make more sense for something like this to go under `experimental`? At that point we might even be able to expand the API to emulate and extend the SciPy API a bit more, perhaps with more rigidly defined distributional APIs and nice helper methods such as KL and others.

**Comment by ziyadedher** [comment]
Shelving this, see discussion in #2745
