### ISSUE TITLE
Confused why error message mentions forward mode

### ISSUE THREAD

**Issue by nickmcgreivy** [google/jax#2736]
Hi,

I'm trying to make sense of this error message. 

NotImplementedError: Forward-mode differentiation rule for 'eig' not implemented

I'm doing the following: 

I have a function f_inner and a function f_outer. f_outer computes the Hessian of f_inner, and then computes the eigenvalues of that Hessian. I later take grad of f_outer.

My first thought was that hessian is jacfwd over jacrev, so the forward mode is referring to the jacfwd call. But then I redefined hessian to be jacrev over jacrev, and I got the same error message. 

I was able to get around this by remembering that the sum of the eigenvalues is the trace of a matrix, so I don't actually need the 'eig' primitive in this calculation. But I'm wondering why I'm seeing an error message about forward mode if I'm never performing JVPs to my knowledge, only VJPs.

Thanks,
Nick

**Comment by froystig** [comment]
Forward-mode autodiff is a common subroutine of reverse-mode autodiff in JAX. By default, a VJP will form a JVP in order to perform a linearization step (part of the "forward pass" of reverse-mode AD).

So, separately:

1. We could improve our error reporting when autodiff isn't fully implemented. Calling for reverse-mode and seeing errors about missing forward-mode rules was confusing here. This applies more broadly than to `eig`.

2. We'd like `eig` to support autodiff.

Note that `jax.numpy.linalg.eigh` and `svd` do support autodiff.

**Comment by froystig** [comment]
I filed #2748 for `eig` autodiff. We can use this issue to focus on error-reporting (item 1 above).

**Comment by nickmcgreivy** [comment]
Thanks for the answer.

I'm still confused, but now my confusion is different. I'm confused why you would perform a JVP as part of the linearization step using forward-mode autodiff.

Suppose I have a function f : R^n -> R, and an elementary operation \phi : R^a -> R^b. Say I'm taking grad of f, which means I'm computing adjoints J^T \overline{v} for each elementary operation on the backwards pass. Isn't actually constructing the full Jacobian of \phi far too expensive, the whole point is to only compute vector-Jacobian products (or Jacobian-transpose-vector products) so that the backwards pass is efficient. I thought on the linearization step you'd just store the data you need for the backwards pass once you have the vector in the VJP.

In this case, if you have a 2x2 matrix, then the `eig` operation returns a 2x2 matrix plus 2 eigenvalues, so the Jacobian would be 6x4 which is much too large to store on the forwards pass. You also wouldn't want to compute that with forward-mode, I think.

There must be something I'm missing.

**Comment by gnecula** [comment]
The linearization step uses the rules for forward mode, to compute the primals needed for the backward step and to collect the computation of the tangent, which is then transposed. One place where this is described is [How JAX primitives work](https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html). 

Therefore, if a primitive does not have the JVP rule implemented, neither forward nor reverse differentiation work.

**Comment by nickmcgreivy** [comment]
Okay thanks. I'll read all about it, and that'll probably clear up my confusion.
