### ISSUE TITLE
remat + eager mode = unnecessary FLOPs in backward_pass

### ISSUE THREAD

**Issue by apaszke** [google/jax#2737]
While `remat` takes great care to avoid unnecessary FLOPs during tracing of the primal code (see the discussion around the `concrete` parameter), it looks like some FLOPs have slipped through the cracks in the `backward_pass`! To verify you can apply the diff below, that I'm folding for readability.
<details>

```diff
diff --git a/jax/interpreters/ad.py b/jax/interpreters/ad.py
index 0b730e0a..ba8bcf5c 100644
--- a/jax/interpreters/ad.py
+++ b/jax/interpreters/ad.py
@@ -187,8 +188,14 @@ def backward_pass(jaxpr: core.Jaxpr, consts, args, cotangents_in):
       if any(is_linear(v) for v in eqn.invars):
         linear_eqns.append(eqn)
       if any(not is_linear(v) for v in eqn.invars):
+        print('Evaluating primal call primitive')
         ans = _eval_subjaxpr_primals(eqn.primitive, call_jaxpr,
                                      map(read_primal, eqn.invars), params)
+        print('Results:', ans)
         map(write_primal, eqn.outvars, ans)

   ct_env: Dict[Any, Any] = {}
@@ -220,6 +228,7 @@ def _eval_subjaxpr_primals(prim, jaxpr, in_vals, params):
   return tree_unflatten(out_tree(), out_flat)

 def _eval_primals(jaxpr, args):
+  print('eval_primals >>>>')
   primal_env = {}

   def read_primal(v):
@@ -230,6 +239,7 @@ def _eval_primals(jaxpr, args):

   def write_primal(v, val):
     if not is_undefined_primal(val):
+      print('COMPUTED: ', val)
       primal_env[v] = val

   def is_linear(var):
@@ -256,6 +266,7 @@ def _eval_primals(jaxpr, args):
         ans = _eval_subjaxpr_primals(eqn.primitive, call_jaxpr,
                                      map(read_primal, eqn.invars), params)
         map(write_primal, eqn.outvars, ans)
+  print('eval_primals <<<<')
   return map(read_primal, jaxpr.outvars)

 class UndefinedPrimal:
```

</details>

Then, running this code: 
```py
@checkpoint
def g(x):
    return x ** 3

def f(x):
    return g(x) * 2

vjp(f, x)[1](x)
```
produces the following output:
```
Evaluating primal call primitive
eval_primals >>>>
COMPUTED:  *
COMPUTED:  [2.]
COMPUTED:  [4.]
COMPUTED:  [12.]
eval_primals <<<<
Results: [*, UndefinedPrimal(ShapedArray(float32[1]))]
```
indicating that the call to `_eval_subjaxpr_primals` for the purpose of getting _potential primal outputs_ out of `remat_call` evaluated a bunch of expressions on real data, only to return a unit and an undefined primal. In effect, every `remat_call` gets evaluated twice, with all results of the first evaluation getting thrown away.

A potential solution would be to make `_eval_subjaxp_primals` only compute the primal values that actually affect the primal outputs (none in this case). The problem with that in that JVP jaxprs make no distinction between primals and tangents in their return lists, except that we might be able to depend on the convention that the first half of those always corresponds to primals, while the rest are their tangents. Not sure if that's a sound thing to do though (would that generalize to all call primitives?), so I wanted to discuss this before trying to resolve the issue. If yes, then `partial_eval._dce_jaxpr` might be a sufficient fix.

**Comment by mattjj** [comment]
Wow, brilliant catch!

**Comment by apaszke** [comment]
Another fun fact is that if you have nested remats, then the non-linear equations of the remat at level n are executed O(n^2) times! This can be easily verified by applying the diff from the issue and trying to compute the VJP this program:
```
@checkpoint
@checkpoint
@checkpoint
@checkpoint
def f(x): return np.sin(x)
```
In particular, this example evaluates the sine at least `4 + 3 + 2 + 1 = 10` times.

**Comment by skye** [comment]
I've forgotten the details now, but I think having some structure/bookkeeping to distinguish between primals and tangents from JVPs (and similarly for VJPs) would have been helpful when we were prototyping grad of sharded_jit (specifically in the sharded_jit translation rule I think). Not sure how relevant that is here but just throwing it out there.

**Comment by mattjj** [comment]
@skye that's a really useful point! I think actually we might be able to collect a handful of such examples. (One that was on my mind recently: allowing users to write custom derivatives for higher-order functions that correctly handle closed-over traces in their function-valued arguments.)

@apaszke chatted this morning and, while there's still more thinking to do, it seems like it might not be a big lift to include this information in jaxprs, especially now that we include avals for each variable as a kind of type information. After all, when we differentiate things, we have the linearity information available; we just throw it away rather than recording it in the jaxpr. (There are a couple ad-hoc places we record it, like the `linear` params of `scan` and `cond`. But those feel analogous to the way we used to stash shape data in params, before we had avals available.)

cc @dougalm

**Comment by apaszke** [comment]
Another interesting failure case that I forgot to document properly in here is that `call_p` primitive nested inside remat calls will end up behaving in the same way as if they were nested remat calls. To reproduce this you can use this code:
```python
def g(x):                                                           
    return jax.core.call(lu.wrap_init(lambda x: (np.sin(x),)), x)[0]

# g = remat(np.sin)
                                                                    
@remat                                                              
def f(x):                                                           
    return g(x * 2) * 4                                             
                                                                    
print(jax.make_jaxpr(lambda x, y: jax.jvp(f, [x], [y]))(x, x))      
```
which produces the following jaxpr:
```
{ lambda  ; a b.
  let c d = remat_call[ call_jaxpr={ lambda  ; a b.
                                     let c = mul a 2.0
                                         d = mul b 2.0
                                         e f = call[ call_jaxpr={ lambda  ; a b.
                                                                  let c = sin a
                                                                      d = cos a
                                                                      e = mul b d
                                                                  in (c, e) }
                                                     name=pe(jvp(<lambda>)) ] c d
                                         g = mul e 4.0
                                         h = mul f 4.0
                                     in (g, h) }
                        concrete=False
                        name=pe(jvp(f)) ] a b
  in (c, d) }
```

Uncommenting the line with `remat` produces an identical jaxpr, only with `call` replaced by `remat_call`. Since `remat` is (correctly) not special cased anywhere in AD, they will be treated in exactly the same way (they share their transpose implementation).
