### ISSUE TITLE
vmap + indexing bug on branch index-take-batching-rule

### ISSUE THREAD

**Issue by noahstier** [google/jax#275]
This looks like a bug. I get an error when indexing using a Traced array inside a vmapped function.

Function `f` below fails, only when using `jax.vmap`:
```
def f(vector):
    inds = np.argsort(vector)
    result = vector[inds]
    return result

def g(vector):
    inds = np.zeros(vector.shape[0], dtype=int)
    result = vector[inds]
    return result

batch_size = 10
length = 3

g(np.ones(length)) # works
f(np.ones(length)) # works

jax.vmap(g)(np.ones((batch_size, length))) # works
jax.vmap(f)(np.ones((batch_size, length))) # TypeError: reshape total size must be unchanged, got new_sizes (1,) for shape (3,).
```

This is related to https://github.com/google/jax/issues/246 and it depends on the code from [this branch](https://github.com/google/jax/tree/index-take-batching-rule), but it's possible that the bug is independent of those changes.

**Comment by mattjj** [comment]
(If updating to 63caf13 makes the code raise a NotImplementedError for you, I think we should probably close this issue in favor of tracking the feature in #246.)

**Comment by mattjj** [comment]
In #307 we actually deleted `lax.index_take` as a primitive, and so the branch with 63caf13 dies with it. However, we do need to add a batching rule for `lax.gather` now...

I'm going to close this issue in favor of tracking the feature in #246.
