### ISSUE TITLE
pytrees in jax.experimental.loops.Scope

### ISSUE THREAD

**Issue by yingted** [google/jax#2767]
It would be nice to use pytrees in `jax.experimental.loops.Scope` as part of the loop state. Right now, I'm using `jax.lax.fori_loop`, which supports pytrees.
This would be helpful for complex recurrences such as autoregressive inference.
```python3
import jax
import jax.experimental.loops

# This works:
def fib_array(n):
  with jax.experimental.loops.Scope() as s:
    s.x, s.y = 0, 1
    for _ in s.range(n):
      s.x, s.y = s.y, s.x + s.y
    return s.x
assert fib_array(10) == 55

# This does not:
def fib_pytree(n):
  with jax.experimental.loops.Scope() as s:
    s.xy = 0, 1
    for _ in s.range(n):
      x, y = s.xy
      s.xy = y, x + y
    return s.fib[0]
assert fib_pytree(10) == 55
```

**Comment by jekbradbury** [comment]
Yes, this seems worth doing. Most of the code in loops.py is compatible with pytrees, but `start_tracing_body` and `end_tracing_body` both assume that each value in the state is an array.

(cc @j-towns for "autoregressive inference" and @gnecula for `experimental.loops`)

**Comment by hawkinsp** [comment]
jax.experimental.loops is long gone. Closing as stale.
