### ISSUE TITLE
Implement np.unique

### ISSUE THREAD

**Issue by rlouf** [google/jax#2768]
First thank you for the amazing work on JAX. It has made my life much easier!

I am currently working on a project where I need to use ˋnp.uniqueˋ and as a result I need to use both JAX and Numba in the same project. Which works fine but is not ideal.

It is my understanding that the shape of the output value of the function depends on the values of the input, and that’s something not easy to do in JAX. Thus Numpy’s implementation cannot be naively followed. I was maybe going to give it a shot, but I would first like to have your opinion about

1. Whether it seems doable;
2. How hard it would be

**Comment by jakevdp** [comment]
See #2760

**Comment by rlouf** [comment]
My bad, closing.
