### ISSUE TITLE
hvp_refref in autodiff cookbook is actually vhp?

### ISSUE THREAD

**Issue by jonasrauber** [google/jax#2772]
In the [autodiff cookbook](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html), an `hvp` (Hessian vector product) is defined using two `grad` calls.

```python
def hvp_revrev(f, primals, tangents):
  x, = primals
  v, = tangents
  return grad(lambda x: np.vdot(grad(f)(x), v))(x)
```

Isn't this rather a `vhp` (vector Hessian product) and not an `hvp`?

(Of course for symmetric Hessians that's the same …)

**Comment by mattjj** [comment]
Yes, that's true; we're assuming symmetric Hessians (e.g. assuming continuous second derivatives). I'll add a phrase to the notebook to make that assumption explicit.

Thanks for the catch!
