### ISSUE TITLE
Add support for differentiation of pseudoinverse

### ISSUE THREAD

**Issue by dbankmann** [google/jax#2792]
Consider the following example:
```python
 def f(p): 
    a = jnp.array([[0.,0.],[- p, 1.]]) * 1/ (1 + p**2) 
    return jnp.linalg.pinv(a) 


jax.jacobian(f)(2.)                                                                                                                                 
Out[75]: 
DeviceArray([[nan, nan],
             [nan, nan]], dtype=float32)
```
So it returns `nan` values, whereas the correct values are
```
array(
[[0., -1.], 
[ 0., 0.]])
```
Oddly enough, jax is able to handle this function correctly:
```python
def f2(p): 
   a = jnp.array([[- p, 1.]]) * 1/ (1 + p**2) 
return jnp.linalg.pinv(a)                                                                                                                        

In [77]: jax.jacobian(f)(2.)                                                                                                                                 
Out[77]: 
DeviceArray([[-0.99999976],
             [ 0.        ]], dtype=float32)
```

Thoughts:
1. ~~f2 returns nd arrays and jax.jacobian seems not to handle those cases to well (probably should open another issue for that)~~ (this seems to be fixed in recent versions though) 

2. There is a closed formula for the derivative of the pseudoinverse which uses the derivative of the original array: https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Derivative

**Comment by shoyer** [comment]
Just out of curiosity -- how are actually using `pinv`?

This issue is fixedi n #2794, but if your application it's for doing pseudo-inverse solves, then your derivatives could be 10x faster still with the approach from https://github.com/google/jax/issues/2802

**Comment by dbankmann** [comment]
I'm mostly interested in something like psolves with __matrix__ right-hand sides and/or derivatives of the projectors A^+A AA^+.

As far as I can tell, the approach from #2802 still relies on distinct singular values, which I cannot guarantee in my case.

**Comment by shoyer** [comment]
The approach in #2808 does _not_ rely upon distinct singular values. You can apply it to multiple right hand sides, but you'd need to use `vmap` on that argument (we could also hide that inside `pinv_solve`, like we do for `jnp.linalg.solve`).

**Comment by dbankmann** [comment]
Oh, I'm not sure, if I understood correctly. So the approach still uses the pinv differential formula by implicitly using a reformulation as for the normal solve (as in the linked paper in #2802)? 
And this is somehow hidden in lax.custom_linear_solve?
