### ISSUE TITLE
Batching rule for 'conv_general_dilated' not implemented

### ISSUE THREAD

**Issue by AllanYangZhou** [google/jax#281]
`Batching rule for 'conv_general_dilated' not implemented`
This appears whenever one tries to use vmap with a network defined using `stax.Conv`.

**Comment by mattjj** [comment]
My understanding is that #288 covered this use case (based on an email exchange), so I'm going to close this issue. Please reopen if #288 didn't solve this for you!

**Comment by AllanYangZhou** [comment]
Hi Matt,

Thanks for checking in and sorry for the delay, I was slow to clone and set up jax on my personal machine to test out the fix. Just tried it now, seems to work now (error went away).

Thanks to @sschoenholz for the fix.
