### ISSUE TITLE
disable_jit extensions to control flow constructs break with vmap

### ISSUE THREAD

**Issue by levskaya** [google/jax#2823]
The extension of `jax.disable_jit()` context to the control flow elements (e.g. `while_loop`, `cond`) isn't correct in the presence of batch tracers for `vmap`.   `while_loop` and `cond` are rewritten to use python control flow under this context, but conditional branching can't be evaluated on the batchtracers present when functions using these control flow constructs are inside a `vmap`.

e.g.
```python
def trivial_while(y):
  return lax.while_loop(lambda x: x < 10.0, lambda x: x + 1.0, y)
# works:
jax.vmap(trivial_while)(jnp.array([3.0,4.0]))
# throws a ConcretizationTypeError:
with jax.disable_jit():
  jax.vmap(trivial_while)(jnp.array([3.0,4.0]))
```
likewise:
```python
def trivial_cond(x):
  return lax.cond(x < 1.0, x, lambda x: x, x, lambda x: 2*x)
# works
jax.vmap(trivial_cond)(jnp.array([0.5,2.0]))
# throws a ConcretizationTypeError:
with jax.disable_jit():
  jax.vmap(trivial_cond)(jnp.array([0.5,2.0]))
```

Perhaps the disabled_jit python implementations for these control flow constructs could peak at the tracer value's `val` field which I suspect will be populated in these use-cases?

**Comment by jacobjinkelly** [comment]
#2598 is possibly related? In particular commenting out [these lines](https://github.com/google/jax/blob/2c4ced2143375ed8a4f8e467c501d9c794d385cb/jax/lax/lax_control_flow.py#L219-L223) might fix it?
