### ISSUE TITLE
Accessing DeviceArray pointers in Cython

### ISSUE THREAD

**Issue by skrsna** [google/jax#2825]
Hi,

I'm looking into using `jax.numpy` as an alternative for NumPy for C/C++ codebase with Cython interface. Most of the C++ functions take pointers to original NumPy ndarrays as an argument. This is primarily done by doing `cimport numpy` and defining numpy ndarrays as `cdef numpy.ndarray[dtype, ndim] original_numpy_array` in the `.pyx` files and passing the pointers to original numpy array as an argument to C++ functions e.g `CXX_object.setValue(&original_numpy_array[0])`. Is there an easy way to do this in jax. 

Thanks

**Comment by hawkinsp** [comment]
Can you clarify what exactly you want to do? Is it: on CPU, share access to the buffer that backs a `DeviceArray` with NumPy?

You can do that already using either the Python buffer protocol (e.g., CPU `DeviceArray`s can be passed to `np.asarray` in a zero-copy way right now), or by using DLPack. Do they satisfy your needs?

**Comment by skrsna** [comment]
Sorry for being vague, I’m fairly new to JAX and I'm using JAX on GPUs. I’m working on some code where the core functionality is written in C++ but has an interface to Python using Cython.  The issue I’m facing can be best explained by the following code 
```
def set_values(self, Y):
    cdef np.ndarray[np.double_t, ndim=1] data
    data = np.ascontiguousarray(Y, dtype=np.double)            
    self.CXXObject.setValues(&data[0])
```
This bit of code uses the user supplied `Y` and converts into `numpy.ndarra` and updates the information in C++ object by using the `setValues` C++ method. I’d like to use `jax.numpy` module to do this so that I can use other JAX functionalities like `jit` , `grad` etc. I'm using the following versions of jax and jaxlib 
```
jax                       0.1.64                    <pip>
jaxlib                    0.1.45                    <pip>
```

**Comment by hawkinsp** [comment]
As the comment above mentions, you can already access the buffers of JAX arrays in several ways:
* the Python buffer protocol (on CPU)
* `__cuda_array_interface__` (on GPU)
* DLPack (on CPU or GPU).

So I don't think there's any work remaining for JAX to do here; it sounds like the remaining work is in your code base.
