### ISSUE TITLE
Invalid argument in lax.gather: Gather op has 3 elements in start_index_map and the bound of dimension index_vector_dim=1 of start_indices is 2.

### ISSUE THREAD

**Issue by rhaps0dy** [google/jax#2826]
Hi,

Ordinarily I would consider purely my own fault, but the software itself is telling me to report it as a bug. My jax version is 0.1.59.

Offending code:
```py
import jax
import jax.numpy as np

operand = np.ones((3, 3, 2))
indices = np.ones((20, 2), dtype=np.int64)
jax.lax.gather(
    operand, indices,
    jax.lax.GatherDimensionNumbers(
        offset_dims=(0,),
        collapsed_slice_dims=(),
        start_index_map=(0, 1, 2)),
    slice_sizes=(1, 1, 2))
```
Error message:

> RuntimeError: Invalid argument: Gather op has 3 elements in start_index_map and the bound of dimension index_vector_dim=1 of start_indices is 2. These two numbers must be equal.: 
> This is a bug in JAX's shape-checking rules; please report it!
> https://github.com/google/jax/issues

This code also asks you to report a bug:
```py
jax.lax.gather(
    operand, indices,
    jax.lax.GatherDimensionNumbers(
        offset_dims=(0,),
        collapsed_slice_dims=(),
        start_index_map=(0, 1)),
    slice_sizes=(1, 1, 2))
```

> RuntimeError: Invalid argument: All components of the offset index in a gather op must either be a offset dimension or explicitly collapsed; got len(slice_sizes)=3, output_slice_sizes=0, collapsed_slice_dims=.: 
> This is a bug in JAX's shape-checking rules; please report it!
> https://github.com/google/jax/issues

Hope you did want this bug report! If not please just close it.

I'll also note that the documents for `jax.lax.gather` are a bit hard to understand.

**Comment by mattjj** [comment]
We do indeed want this bug report! Thanks so much for it; it's super clear.

> I'll also note that the documents for `jax.lax.gather` are a bit hard to understand.

I feel the same way :) Imagine how it was to implement NumPy fancy indexing on top of `jax.lax.gather`: you have to keep two complicated APIs in your head at once. Actually I couldn't fit them both in my head at the same time, and could only work on them when pair-programming with @hawkinsp!
