### ISSUE TITLE
Precision argument on jax.numpy functions should be keyword only

### ISSUE THREAD

**Issue by shoyer** [google/jax#2827]
In a recent PRs we added the `precision` argument to various jax.numpy functions: https://github.com/google/jax/pull/1728, https://github.com/google/jax/pull/2747
 
We should make use of Python 3's "keyword only arguments" feature here, to avoid potential confusion about the meaning of positional arguments with NumPy:
```python
# bad (current code)
def dot(a, b, precision=None):
  ...

# good
def dot(a, b, *, precision=None):
  ...
```

**Comment by abhishekshrm53** [comment]
I would like to contrubute here if anyone has not picked it up. Can I start on it?

**Comment by shoyer** [comment]
Sure, this should be relatively straightforward.

**Comment by abhishekshrm53** [comment]
I have made the necessary changes here #2849 ; please review.

**Comment by abhishekshrm53** [comment]
I have made changes to the public functions in #2850. Please check.

**Comment by shoyer** [comment]
Fixed by https://github.com/google/jax/pull/2850
