### ISSUE TITLE
core.call_bind aggressively raises args to top trace

### ISSUE THREAD

**Issue by trevorcai** [google/jax#2833]
```
def f(a_bool, y):
  if a_bool:
    return y + 1
  else:
    return y

jax.jit(jax.remat(f), static_argnums=0)(True, 1)
```

Results in:
```
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected (in `bool`).
Use transformation parameters such as `static_argnums` for `jit` to avoid tracing input values.
See `https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error`.
Encountered value: Traced<ShapedArray(bool[], weak_type=True):JaxprTrace(level=-1/2)>
```

I think this arises from the full_raise occurring here when processing `remat_call_p` - which raise to the JaxprTrace when we told JIT we don't want to!
https://github.com/google/jax/blob/77901e9fa71f5b23066c70132a983ae57f655b39/jax/core.py#L1001

This also applies to user-defined call primitives using `core.call_bind`, resulting in unnecessary workarounds like this one in Haiku:
https://github.com/deepmind/dm-haiku/blob/49b21f7192dfdb3dc0a49cc097c8d3b0ccabb107/haiku/_src/named_call.py#L101-L109

**Comment by mattjj** [comment]
I think this might be working as intended. That is, `remat` itself will raise the abstraction level. You can use `jax.remat(f, concrete=True)` if you want to handle Python control flow inside a `remat`, but when mixing that together with `jit` it's possible to do redundant FLOPs in that case. [This comment](https://github.com/google/jax/pull/1749#issuecomment-558267584) on #1749 has some detail.

WDYT?

**Comment by mattjj** [comment]
Hmm I just tried with `concrete=True` and it didn't work... let's see...

**Comment by mattjj** [comment]
I'm confused because calling `JaxprTrace.full_raise` should neither produce an 'unknown' tracer (see [1](https://github.com/google/jax/blob/77901e9fa71f5b23066c70132a983ae57f655b39/jax/interpreters/partial_eval.py#L98) [2](https://github.com/google/jax/blob/77901e9fa71f5b23066c70132a983ae57f655b39/jax/interpreters/partial_eval.py#L109)) nor raise the abstraction level. An unknown is only introduced when we call `JaxprTrace.instantiate_const`, and then it's only raised past the Concrete level if we call `JaxprTrace.instantiate_const_abstracted`.

Oh... I think I have an idea...

**Comment by mattjj** [comment]
It's because [we stage out as much as possible](https://github.com/google/jax/blob/77901e9fa71f5b23066c70132a983ae57f655b39/jax/interpreters/partial_eval.py#L167) for calls. We really only want that behavior for `xla_call` and not other call primitives...

**Comment by mattjj** [comment]
#2834 has a fix. You'll still need to use `remat(f, concrete=True)` to prevent `remat` from raising the abstraction level and hence allow it to handle Python control flow, but now we won't raise the abstraction level for all call primitives when they encounter an outer `jit` tracer.

**Comment by trevorcai** [comment]
gotcha, remat was just a hasty choice on my part to pick a jax-native call primitive that didn't seem to raise abstraction level; the main motivation is the linked Haiku `named_call_p` (and my other experimental call primitives).

**Comment by trevorcai** [comment]
thanks for the crazy fast fix!

**Comment by mattjj** [comment]
:) Thanks for catching this! Your guess was quite good and that's what let us solve this fast.
