### ISSUE TITLE
How to run an XLA compute server?

### ISSUE THREAD

**Issue by KristianHolsheimer** [google/jax#2837]
Hi there,

I am intrigued by the possibility of using `pmap` to split up my computations across multiple devices. 

I did manage to use `pmap` on multiple local GPUs, but I would like to add remote devices.

How would I spin up remote devices that I can use to send my XLA computations to?

The way I imagine this to work is to spin up a VM and to run XLA compute server (somehow). I found this example in one of the test cases in the tensorflow codebase: [tensorflow/compiler/xla/rpc/grpc_client_test.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/rpc/grpc_client_test.cc), but I'm finding it hard to decipher.

Am I on the right track? Do you have any examples of how to run an XLA server?

Thanks!

**Comment by gnecula** [comment]
Hi, 

At the moment we do not have support for multi-CPU setup, but we do have an early experimental support for multi-GPUs, using NCCL. However, it is not in a form ready to use externally just yet. 

I am going to close this issue, in favor of the similar #2731.
