### ISSUE TITLE
Moving data between CPU/GPU

### ISSUE THREAD

**Issue by Vaishaal** [google/jax#2851]
Apologies if this is a silly question, but I couldn't find anything in the documentation about this.

So I have a pipeline where the first N steps need to be executed on the GPU as they are efficiently batched, and theres fast cudnn code for them.

The last step is something like an outer product, where the resulting matrix won't fit in gpu memory but it will fit in my CPU memory. 

Currently I am casting the output of my jax pipeline that runs on the gpu to a regular numpy array and using a standard numpy dot product, which works but seems some what kludgey. More generally anytime I work with this big object I need to make sure I use `onp` instead of `np` or I get a gpu out of memory error.

My previous iteration of my code written in pytorch would run the gpu code and do .numpy(),
and proceed with the regular cpu portion of the pipeline. 

For what its worth jax.devices() outputs only 1 device (the gpu).

Is this the best way to go about this right now?

**Comment by gnecula** [comment]
Please try this to see your devices
```
print(jax.devices("cpu"))
print(jax.devices("gpu"))
```
My understanding is that if you pass the result of the data computed on GPU to a computation jitted for CPU (`jax.jit(f, device=your_cpu_device)`, it should transfer it to the CPU and continue it there. Does this work for you?

**Comment by gnecula** [comment]
I just tried it, I had to add ` jax.device_put`:
```
cpus = jax.devices("cpu")
gpus = jax.devices("gpu")

x = jax.jit(lambda x: x * 2., device=gpus[0])(1.)
print(x, x.device_buffer.device())
z = jax.device_put(x, cpus[0])
print(z, z.device_buffer.device())
y = jax.jit(lambda x: x * 11., device=cpus[0])(z)
print(y, y.device_buffer.device())
```

prints 
```
2.0 gpu:0
2.0 cpu:0
22.0 gpu:0
```

**Comment by Vaishaal** [comment]
OK this is super helpful I will try it! I didn't realize how jax.devices() works.

**Comment by gnecula** [comment]
The documentation part will be fixed by #2882. Also related #2883.

**Comment by Saipraneet** [comment]
Thanks for the example  @gnecula! I am trying to understand which parts of computation happen over gpu and which ones over cpu. 

Suppose my data is loaded by a function data_load which is not jit-ted and then I do some heavy lifting (e.g. gradient computation) through a Jit'ted function. Am I right in assuming that the data loading part will happen over cpu and the gradient computation will happen on the gpu? Will the data transfer happen automatically?

I would love to find some documentation to understand when and how data transfer occurs in Jax.

Thanks!

**Comment by gnecula** [comment]
Hi, did you read the FAQ entry about computation placement? The model is quite simple and as far as I think it is fully documented there.

**Comment by Saipraneet** [comment]
Thank you for your prompt reply! The [FAQ section](https://jax.readthedocs.io/en/latest/faq.html#controlling-data-and-computation-placement-on-devices) as well as the [test code](https://github.com/google/jax/blob/master/tests/multi_device_test.py) are very clear about where computation happens between if I have multiple GPUs. However, I am not sure how the load is distributed between the CPU and GPU. 

If there is a GPU does all the computation (including non JIT'ted functoins) automatically occur on GPU?

**Comment by cgarciae** [comment]
I think this piece of code should appear on the FAQ to clarify how to actually find all device of interest:

```python
cpus = jax.devices("cpu")
gpus = jax.devices("gpu")
```

Before reading this I was under the impression that `jax.devices()` should return all available devices, I didn't even realize it could accept an argument.

**Comment by pharringtonp19** [comment]
I find that the output from the third function call actually lives on the cpu.

```
cpus = jax.devices("cpu")
gpus = jax.devices("gpu")

x = jax.jit(lambda x: x * 2., device=gpus[0])(1.)
print(x, x.device_buffer.device())
z = jax.device_put(x, cpus[0])
print(z, z.device_buffer.device())
y = jax.jit(lambda x: x * 11., device=cpus[0])(z)
print(y, y.device_buffer.device())
```
Output

```
2.0 gpu:0
2.0 TFRT_CPU_0
22.0 TFRT_CPU_0
```

**Comment by jan-engelmann** [comment]
I think this information is quite hidden in the FAQ. Adding a short reference to it in the quick start would be helpful.
