### ISSUE TITLE
Indexing on new ShardedDeviceArray with array breaks

### ISSUE THREAD

**Issue by levskaya** [google/jax#2855]
repro:
```python
vals = jax.pmap(lambda x: x)(random.uniform(key, (8,7)))
idxs = random.randint(key, (8,7), minval=0, maxval=7)
vals[idxs] # breaks
# if instead we do this in sequence it works:
# jnp.array(vals)
# vals[idxs]
```
the reason is at https://github.com/google/jax/blob/master/jax/interpreters/pxla.py#L512 : 
```python
  def __getitem__(self, idx):
    if self._npy_value is None and idx in self.indices:  # <--- here
```
if we've already fetched the _npy_value the `if` statement short-circuits and things work, but if the ShardedDeviceArray is "fresh" it tries to evaluate `idx in self.indices` which expands into an array of bools and then fails because bool(array) is undefined - the solution might just be to add a type guard to insure that `idx` is a simple integer scalar?  Does that make sense?

**Comment by hawkinsp** [comment]
Good news! We replaced `ShardedDeviceArray` with `Array` and this, naturally, works. Closing as stale.
