### ISSUE TITLE
Improvements on a CPU micro-benchmark

### ISSUE THREAD

**Issue by cgarciae** [google/jax#2856]
Hey, I ported some jax code (its really numpy code trivially ported to jax) I had to Julia so I could start learning the language. The naive port to Julia was surprisingly slow so I ask around, some in the Julia community helped me to get an initial threaded version and I shared a CPU micro-benchmark online. The threaded version in Julia is slower than Jax, since the Julia community is very defensive about being slower than Python tech (although XLA has nothing to do with Python) they started to optimize it until they reached a threaded SIMD which is 1.5x faster than the Jax version.

**Results**
```
julia: distances  1.662 s (40 allocations: 286.18 MiB)
julia: distances_bcast  1.414 s (30 allocations: 95.44 MiB)
julia: distances_threaded  317.086 ms (106 allocations: 190.82 MiB)
julia: distances_threaded_simd  153.072 ms (104 allocations: 190.82 MiB)
numpy: dist_np_test  2.069 s (39 allocations: 190.74 MiB)
jax: dist_jax_test  242.286 ms (8 allocations: 320 bytes)
```

Out of curiosity I wanted to know if the Jax version could be speed up without modifying it much, hopefully with the same code. Can Jax use SIMD? 

Full Julia + Python Code: https://gist.github.com/cgarciae/a69fa609f8fcd0aacece92660b5c2315

Jax Code:

```python
from jax import numpy as jnp
import jax
import numpy as np
import time

@jax.jit
def distances_jax(data1, data2):
    # data1, data2 are the data arrays with 2 cols and they hold
    # lat., lng. values in those cols respectively
    np = jnp
    data1 = np.deg2rad(data1)
    data2 = np.deg2rad(data2)
    lat1 = data1[:, 0]
    lng1 = data1[:, 1]
    lat2 = data2[:, 0]
    lng2 = data2[:, 1]
    diff_lat = lat1[:, None] - lat2
    diff_lng = lng1[:, None] - lng2
    d = (
        np.sin(diff_lat / 2) ** 2
        + np.cos(lat1[:, None]) * np.cos(lat2) * np.sin(diff_lng / 2) ** 2
    )
    data = 2 * 6373 * np.arctan2(np.sqrt(np.abs(d)), np.sqrt(np.abs(1 - d)))
    return data.reshape(data1.shape[0], data2.shape[0])

a = np.random.uniform(-100, 100, size=(5000, 2))
b = np.random.uniform(-100, 100, size=(5000, 2))

t0 = time.time()
distances_jax(a, b).block_until_ready()
print("time jax", time.time() - t0)
```

Thanks!

**Comment by jekbradbury** [comment]
XLA often does a pretty good job of triggering LLVM auto-vectorization, but (evidently!) not to the extent of LoopVectorization.jl here.
