### ISSUE TITLE
Call MPI from jitted code

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#2860]
Is there any possibility to have interoperability between JAX and MPI / mpi4py?

I am porting a physical model to JAX with has lots of interactions like this:

```python
def compute_something(...):
    # instruction block 1
    # ...

    # this communicates boundaries of arr between processes
    # via mpi4py
    arr = boundary_exchange(arr)

    # instruction block 2
    # ...

    return arr
```

Now, in order to JIT this, I would have to transform all of those into

```python
@jax.jit
def compute_something_block_1(...)
    # ...

@jax.jit
def compute_something_block_2(...)
    # ...

def compute_something(...):
    # instruction block 1
    compute_something_block_1(...)

    # this communicates boundaries of arr between processes
    # via mpi4py
    arr = boundary_exchange(arr)

    # instruction block 2
    compute_something_block_2(...)

    return arr
```

which doesn't do the code any favors.

So, the question is this:

1. Is it possible to fall back to Python interactions inside jitted code? (I guess the answer is no)
2. What would be the most convenient way to make XLA aware of MPI? Is it necessary to wrap the MPI calls as custom call targets?

**Comment by shoyer** [comment]
I think you’ve accurately accessed the current options. I’d love to have the ability to easily custom call into Python, but that doesn’t exist currently.

**Comment by dionhaefner** [comment]
This is possible now via [`mpi4jax`](https://github.com/PhilipVinc/mpi4jax).

**Comment by shoyer** [comment]
Nice work!
