### ISSUE TITLE
_index_to_gather produces DeviceArrays for int / onp.ndarray inputs

### ISSUE THREAD

**Issue by mattjj** [google/jax#2878]
The `_index_to_gather` function and some subfunctions, like `_normalize_index`, perform operations with `lax` functions even when dealing with integer or onp.ndarray inputs. That's unfortunate because it means, for example, doing scalar integer operations on the default accelerator device! We should probably revise.

**Comment by mattjj** [comment]
Alternatively, we could re-enable `jit` as per [this TODO](https://github.com/google/jax/blob/790d92965c881e0316876242953009ca6fc8f3eb/jax/numpy/lax_numpy.py#L3192-L3194). Of course, I completely forget why it as hard... can we just make slices into pytrees?

**Comment by skye** [comment]
https://github.com/google/jax/issues/2891 attempts to summarize why re-enabling the `jit` is hard (by quoting Peter).

**Comment by mattjj** [comment]
Yeah, though I realized this issue is somewhat orthogonal because we likely want to keep static index munging in Python / onp anyway.

**Comment by mattjj** [comment]
I think this is stale!
