### ISSUE TITLE
np.array named columns and different column types not working

### ISSUE THREAD

**Issue by lumip** [google/jax#2881]
Classical numpy arrays allow to specify column names/identifiers and assign different types to columns.
From the documentation:

> Data-type consisting of more than one element:
>
> ```
>>>> x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
>>>> x['a']
>array([1, 3])
>  ```

The same documentation is given for jax's `np.array` but trying the above example yields a
```
TypeError: unhashable type: 'list'
```
for the `dtype` argument (raised in function `_check_user_dtype_supported`,  line 5096, `jax/lax/lax.py`).
Is there a chance that this kind of array specifications could be supported? If not, could at least the documentation be clarified?

**Comment by shoyer** [comment]
JAX doesn’t support structured dtypes, but I agree that we provide better a error message here.

**Comment by lumip** [comment]
too bad, but thanks for the clarification!
