### ISSUE TITLE
Add np.unravel_index

### ISSUE THREAD

**Issue by mattwescott** [google/jax#2889]
This is what I've been using. If it looks reasonable, will see about putting together a PR.

```python
def unravel_index(flat_index, shape):
    """
    To support abstract `flat_index` there is no bounds checking. For
    overflow some dimensions of the resulting index will be out of bounds.
    For negative `flat_index` the resulting index is valid, although the first
    dimension will be negative. 
    """

    if len(shape) == 0:
        return ()

    size_of_next_dimension = np.pad(shape[1:], (0, 1), constant_values=1)
    strides = np.cumprod(size_of_next_dimension[::-1], dtype='int32')[::-1]

    _, idx = jax.lax.scan(
        lambda remaining, stride: (
            remaining % stride,
            remaining // stride
        ),
        flat_index,
        strides
    )

    return tuple(idx)
```

Haven't looked at jax testing yet, would be helpful to know whether / how to incorporate these...

```python
def test_unravel_index():

    assert unravel_index(0, (2, 3)) == (0, 0)
    assert unravel_index(5, (2, 1, 3)) == (1, 0, 2)

    assert unravel_index(0, ()) == ()
    assert unravel_index(3, (2,)) == (3,)
    assert unravel_index(-1, (2, 1, 3)) == (-1, 0, 2)
```

**Comment by hawkinsp** [comment]
While it's probably correct as is, I think it would be preferable to avoid the `scan`, along the following lines:

```
In [72]: np.unravel_index(692, [4,6,8,9])
Out[72]: (1, 3, 4, 8)

In [73]: index = 692

In [74]: shape = [4, 6, 8, 9]

In [75]: cp = np.cumprod(np.pad(shape, [(0, 1)], constant_values=1)[::-1])[::-1]

In [76]: index % cp[0:-1] // cp[1:]
Out[76]: array([1, 3, 4, 8])
```

In general vectorizable operations will be faster than `scan`.

Want to send a PR? Tests would go in `lax_numpy_test.py`.

**Comment by mattwescott** [comment]
Thanks @hawkinsp 

Any preference on overflow behavior?

1. `np.unravel_index(3, (2,)) == (3,)`
2. `np.unravel_index(3, (2,)) == (2,)`
3. `np.unravel_index(3, (2,)) == (1,)`

Both (1) and (2) seem consistent with "JAX does not raise an error and instead returns the last value in the array". And (1) is FWIW what I expected to see when I first tried `jax.numpy.unravel_index`

**Comment by rdaems** [comment]
Hi @mattwescott 

Are you still looking into this? I could use this feature as well.

**Comment by mattwescott** [comment]
@rdaems thanks for the motivation, will put together a PR shortly
