### ISSUE TITLE
Consider adding mixin that registers pytree node classes

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#2916]
Along the same lines of the excellent `jax.tree_util.register_pytree_node_class`, could we get a mixin for it so that

- the registration affects subclasses,
- to facilitate type annotation, and
- so that linters like pylint and MyPy can verify the implementation and calls (the decorator is very hard to lint).

This wasn't possible until JAX's recent requirement of Python 3.6, which has `__init_subclass__`.

```python
from __future__ import annotations

from typing import Any, Hashable, Iterable, Tuple, Type, TypeVar

from jax.tree_util import register_pytree_node

from .annotations import PyTree

__all__ = ['PyTreeLike']


T = TypeVar('T', bound='PyTreeLike')


class PyTreeLike:

    def __init_subclass__(cls, **kwargs: Any):
        super().__init_subclass__(**kwargs)

        register_pytree_node(cls,
                             cls.tree_flatten,
                             cls.tree_unflatten)

    @classmethod
    def tree_unflatten(cls: Type[T],
                       aux_data: Hashable,
                       values: Iterable[PyTree],
                       **init_kwargs: Any) -> T:
        """
        Args:
            aux_data:
                Data that will be treated as constant through JAX operations.
            values:
                A JAX PyTree of values from which the object is constructed.
        Returns:
            A constructed object.
        """
        if aux_data is not None:
            raise RuntimeError
        if values != ():
            raise RuntimeError
        return cls(**init_kwargs)

    def tree_flatten(self) -> Tuple[Iterable[PyTree], Hashable]:
        """
        Returns:
            values: A JAX PyTree of values representing the object.
            aux_data:
                Data that will be treated as constant through JAX operations.
        """
        # https://github.com/python/mypy/issues/8768
        return (), None  # type: ignore
```

**Comment by froystig** [comment]
[Flax](https://github.com/google/flax) offers a [struct](https://flax.readthedocs.io/en/latest/flax.struct.html) package with a similar purpose. Would that be useful here?

**Comment by NeilGirdhar** [comment]
Flax looks interesting, but I think this would fit better in `jax.tree_util`?

As for `flax.struct.dataclass`, they could probably extend their dataclass idea to include registering as a PyTree by letting the user specify which components are PyTree-like and which are auxilliary.

**Comment by jekbradbury** [comment]
I believe that last point is something `flax.struct.dataclass` already does?

I agree with your points about benefits to this approach over `register_pytree_node_class`; it's also hard for us to argue that this one doesn't belong in core given the presence of that one (maybe they both don't! They're easy enough to implement in downstream packages...).  I think I for one would support a PR to add it, although the team aren't generally big mixin (or inheritance) fans; for now I'd recommend using it in your own code base and contributing it if you find it routinely useful or others are interested.

**Comment by NeilGirdhar** [comment]
> I believe that last point is something flax.struct.dataclass already does?

You're right, I didn't read it closely enough.  That's a pretty good design for when you can stick with dataclasses.  Too bad dataclasses don't support cooperative inheritance though (a design decision they inherited from attrs).  They do support inheriting other dataclasses, but that's it.  They won't call super in `__init__`, so you can't initialize base classes.

>  although the team aren't generally big mixin (or inheritance) fans; for now I'd recommend using it in your own code base and contributing it if you find it routinely useful or others are interested.

Right, I've noticed that.  Fair enough.  If this issue gets close, no worries, I don't want to drown you guys in minor issues!   I'll probably keep doing this way.

**Comment by NeilGirdhar** [comment]
I use dataclasses exclusively now, so I'm going to close this issue.  It would be nice to have a base class for dataclasses, but that is a huge amount of work to get the mypy plugin fixed.
