### ISSUE TITLE
`jax.numpy.array()` is much slower than `numpy.array()` when called on a list

### ISSUE THREAD

**Issue by phinate** [google/jax#2919]
As pointed out in the docs, converting lists to arrays is terribly slow compared to numpy:

```
import numpy as np
import jax.numpy as jnp

%%timeit
np.array([0] * int(1e6))
> 60.1 ms ± 578 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%%timeit
jnp.array([0] * int(1e6))
> 3min 12s ± 794 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

This is somewhat remedied by first calling numpy:
```
%%timeit
jnp.array(np.array([0] * int(1e6)))
> 61.9 ms ± 574 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```

Ideally, one wouldn't want to make a proxy for `array()` by defining a function that always calls numpy first, so it would be nice to either explicitly do this on a low level, or improve the implementation of `array()` as to avoid this huge discrepancy in speed.

**Comment by mattjj** [comment]
This is something worth fixing! 

@hawkinsp did a quick profile, I'll put the screenshot here just for posterity:

![image](https://user-images.githubusercontent.com/1458824/80822909-7ef8af80-8b90-11ea-8dc9-072e46c69eb6.png)

From the left half:

![image](https://user-images.githubusercontent.com/1458824/80823013-a8194000-8b90-11ea-8a4d-fccc3f777c41.png)

From the right half:

![image](https://user-images.githubusercontent.com/1458824/80822956-93d54300-8b90-11ea-80b4-32414e86695b.png)

Looks like a lot of dumb stuff going on. The good news is we should be able to improve it significantly :P

**Comment by cghawthorne** [comment]
The same problem happens when converting from a bunch of `jnp.array`s to `np.array`. But the bulk of the time is in the creation of the `jnp.array`s.

```
import numpy as np
import jax.numpy as jnp

%%timeit
np.array([0] * int(1e3))
10000 loops, best of 3: 119 µs per loop

%%timeit
arr = jnp.array([0] * int(1e3))
1 loops, best of 3: 212 ms per loop

arr = jnp.array([0] * int(1e3))

%%timeit
np.array(arr)
100000 loops, best of 3: 7.1 µs per loop
```

**Comment by mattjj** [comment]
Sorry for taking so long to look at this! #3350 will awaken us from the long nightmare. See the PR message there for some timings.

By the way, @cghawthorne it seems that your example has improved as well, though that wasn't part of #3350 and so must've happened in some other improvements over the last month:

```
In [1]: import numpy as np
   ...: import jax.numpy as jnp

In [2]: arr = jnp.array([0] * int(1e3))
   ...:

In [3]: %timeit np.array(arr)
1.79 µs ± 43.2 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

Still not amazing, but better!
