### ISSUE TITLE
jax.experimental.loops as a decorator

### ISSUE THREAD

**Issue by yingted** [google/jax#2934]
What do you think about a decorator that transforms code to use `jax.experimental.loops`?
Today you have to write this:
```python3
from jax.experimental import loops
def f(arr):
  with loops.Scope() as s:
    s.arr = arr
    for i in s.range(s.arr.shape[0]):
      s.arr = ops.index_update(s.arr, i, s.arr[i] + 2.)
      for _ in s.cond_range(i % 2 == 0):  # Conditionals as loops with 0 or 1 iterations
        s.arr = ops.index_update(s.arr, i, s.arr[i] + 1.)
    return s.arr
```

This would be more readable:
```python3
from jax.experimental import loops2
# This lets you run this code:
# ret = f.with_scope(loops.Scope())(*args, **kwargs)
@loops2.enable
def f(arr):
  for i in loops2.dynamic_loop(range(arr.shape[0])):
    arr = ops.index_update(arr, i, arr[i] + 2.)
    if loops2.dynamic_branch(i % 2 == 0):
      arr = ops.index_update(arr, i, arr[i] + 1.)
  return arr
```

The semantics of this transform are:
1. All local variable access is mirrored to `$scope` (or we can make it anonymous). Since there is a `$` symbol in the name, it won't conflict with a user-defined variable.
    1. On entry, we call: `$scope.__dict__.update(locals())`
    1. Getting `arr` goes to `$scope.x`.
    1. Setting/deleting `arr` goes to both `x` and `$scope.x`.
    1. Variables referenced in another function are not stored at all:
        ```python3
        # Either of these would disable updating $scope.arr
        send_to_other_thread(lambda: arr)
        send_to_other_thread(lambda value: (arr := value))
        ```
        We know when captured variables are modified by the decorated function, so we could also just instrument those.
1. All control flow becomes a giant switch statement that returns the next branch to run. Alternatively, we could translate for loops into something nice and make everything else a switch statement.

Questions:
1. Does `loops.Scope()` need to be eager? A lazy interface (`locals()` and `set_locals(l)` instead of `set_local`, `get_local`, and `del_local`), would be much easier to implement.
1. Should we default all loops to dynamic?
1. What should this code do?
```python3
for i in range(n):
  if not is_valid(i):
    break
else:
  x += n
```
1. `try-break-finally`, `try-continue-finally`, nested `try-finally`
1. Which should be captured? What if the functions can update the locals? Or globals?
```python3
f = loops2.enable((lambda x: lambda y: lambda z: x + y + z)(0))
```

**Comment by gnecula** [comment]
I personally prefer the current API because it is more explicit, and there is somewhat less "magic" happening. I think it is useful for the user to have the mental model that only fields of the Scope object are being tracked. 

We are also preparing a change to JAX to make it easier to keep track of state. I would rather wait for that to see how it is going to improve the ergonomics of loops.

**Comment by jakevdp** [comment]
Closing, as `jax.experimental.loops` is deprecated and will soon be removed.
