### ISSUE TITLE
Invalid (non-utf8) data written into XlaComputation.instructions.backend_config.

### ISSUE THREAD

**Issue by etarassov** [google/jax#2963]
Jaxlib operations, when serialized into XlaComputation, write binary data into backend_config field.
The field is string on the proto level, and parsing a serialized proto will trigger an error (non utf8 data).
There was (an internal) thread on this, and the Xla team decided to give up on this temporarily and switched the proto field to bytes. However it would be nice to fix this in jax.

**Comment by etarassov** [comment]
Pointers:
the backend_config field:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/hlo.proto#L174
The field used to be a string but degraded to bytes because of this issue.

The offending code (jaxlib codebase):
https://github.com/google/jax/blob/master/jaxlib/kernel_helpers.h#L34

**Comment by hawkinsp** [comment]
This isn't a bug, as discussed over email. Closing.
