### ISSUE TITLE
jaxlib build error in PacketMathAVX512.h

### ISSUE THREAD

**Issue by clemisch** [google/jax#2964]
Dear jax team,

I am running into weird compilation errors when building jaxlib with GPU support. They all come from `PacketMathAVX512.h` and look like

```
external/org_tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX512.h: In function 'typename Eigen::internal::unpacket_traits<T>::type Eigen::internal::predux_min(const Packet&) [with Packet = Eigen::internal::Packet16q32i; typename Eigen::internal::unpacket_traits<T>::type = Eigen::QInt32]':
external/org_tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/src/FixedPoint/PacketMathAVX512.h:432:16: error: could not convert 'Eigen::internal::pfirst<__vector(2) long long int>(_mm_min_epi32(res.Eigen::internal::eigen_packet_wrapper<__vector(2) long long int, 0>::operator __vector(2) long long int&(), _mm_shuffle_epi32(res.Eigen::internal::eigen_packet_wrapper<__vector(2) long long int, 0>::operator __vector(2) long long int&(), ((((0 << 6) | (0 << 4)) | (0 << 2)) | 1))))' from 'Eigen::internal::unpacket_traits<__vector(2) long long int>::type {aka __vector(2) long long int}' to 'Eigen::QInt32'
   return pfirst(
          ~~~~~~^
       _mm_min_epi32(res, _mm_shuffle_epi32(res, _MM_SHUFFLE(0, 0, 0, 1))));
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Full log is in https://gist.github.com/clemisch/3fd1ee08ee8f7c2aafc40e0a34f81a7e.

I am building on a machine with 2x RTX Titan and 2x GTX 1080Ti and CUDA 10.0. The filename reminds me of a recent issue #2906. I am building from github master (cleared bazel cache) and don't have any problems on other machines running GTX 1080Ti only, with similar CUDA setup. 

Sorry for this being so vague, but I don't really know where to look to investigate this error.

**Comment by hawkinsp** [comment]
This appears to be https://github.com/tensorflow/tensorflow/issues/39180

We'll need to wait for that issue to be resolved.

**Comment by hawkinsp** [comment]
I believe #2977 fixes the problem, but I can't verify that because I couldn't reproduce it in the first place. Please reopen the bug if you still have an issue.

**Comment by clemisch** [comment]
Thank you, it's fixed for me!
