### ISSUE TITLE
Handle unimplemented optional arguments in `_wraps`

### ISSUE THREAD

**Issue by mattwescott** [google/jax#2988]
In the `_CheckAgainstNumpy` tests, any unimplemented optional arguments are effectively the numpy defaults. If these unimplemented arguments are passed into the jax version, for some arguments the value is checked against the default, for other arguments an unexpected argument `TypeError` is raised. 

Would it make sense to move this validation and error handling into `_wraps`? Specifically, if an unexpected argument is passed into a `_wraps` function, if the value doesn't match the default value for numpy, raise `NotImplementedError`. 

Possible benefits are (1) more valid inputs that are consistent with numpy, (2) some cleanup in `lax_numpy`, and (3) less maintenance when upgrading the reference numpy version. On the other hand, `inspect.getfullargspec` doesn't seem to be working on `numpy==1.18.4`, possibly related to [this issue](https://github.com/numpy/numpy/issues/12225). There are probably other barriers that I'm overlooking.

**Comment by skye** [comment]
Assuming it's technically feasible, this makes sense to me. Although I'm guessing this would require creating an extra wrapper function to do the argument handling, which might be irritating or confusing when debugging (jax creates enough stack frames already).

**Comment by jakevdp** [comment]
One thing to keep in mind: any extra processing done by _wraps will be done *every* time the package is loaded. Import of jax.numpy is already noticeably slow because of the wrapping and docstring munging that’s happening in _wraps. For something like this that is essentially a static check, I’d lean toward a test instead.

**Comment by mattwescott** [comment]
> this would require creating an extra wrapper function to do the argument handling, which might be irritating or confusing when debugging

Good point. And maybe there is some value to explicit handling, almost as a form of documentation in `lax_numpy` of where the priority gaps are in the implementation. 

> any extra processing done by _wraps will be done every time the package is loaded

Maybe this comes down to the cost of inspection. @jakevdp How did you use `inspect.signature` with numpy? Tried a few versions without success.

**Comment by jakevdp** [comment]
It works for some objects, but not others:
```python
import numpy as np
import inspect
inspect.signature(np.linspace)
```
```
<Signature (start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)>
```

**Comment by jakevdp** [comment]
I think this has been addressed as well as it can be.
