### ISSUE TITLE
Error on NaN?

### ISSUE THREAD

**Issue by duckworthd** [google/jax#30]
Is it possible to raise an error on NaN, a la `np.seterr`?

```python
import numpy as np

np.seterr(all='raise')
np.divide(0, 0)  # FloatingPointError: divide by zero encountered in divide
```

**Comment by mattjj** [comment]
@duckworthd we added a flag to check for NaNs after every computation in #482, see also [this thread](https://github.com/google/jax/issues/475#issuecomment-470417985). It slows things down but might be useful for debugging. There's also the #276 CPU fast math issue, which will still make nans harder to track down in some cases.
