### ISSUE TITLE
pmap static_broadcasted_argnums does not respect keyword arguments.

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#3007]
Tested on internal TPU donut.

This code 

```python
import jax

def f(a, b):
  return a + b

g = jax.pmap(f, static_broadcasted_argnums=(1,))
g(jnp.ones((8, 1)), b=1)
```

Crashse with 
```
      5   return a + b
      6 g = jax.pmap(f, static_broadcasted_argnums=(1,))
----> 7 g(jnp.ones((8, 1)), b=1)

3 frames
google3/third_party/py/jax/api.py in _get_axis_size(i, shape, axis)
    775     return shape[axis]
    776   except (IndexError, TypeError) as e:
--> 777     raise ValueError(f"vmap got arg {i} of rank {len(shape)} but axis to be mapped {axis}") from e
    778 
    779 def _mapped_axis_size(tree, vals, dims, name):

ValueError: vmap got arg 1 of rank 0 but axis to be mapped 0
```

However, changing the last line to 
```python
g(jnp.ones((8, 1)), 1) # No keyword args!
```
works as expected.

**Comment by mattjj** [comment]
Thanks for the report! Just checking: how does this compare to how `jit` works with `static_argnums` together with keyword arguments?

**Comment by mattjj** [comment]
I just checked against `jit`, and indeed I think I'd currently consider this an issue about better errors, though we could upgrade both `jit` and `pmap` to try harder to reconcile arguments passed via keywords to parameter positions.

**Comment by mattjj** [comment]
#3018 will fix the error message. As for improving how jitted and pmapped functions can handle arguments passed via keywords for slots indicated as static, let's keep the discussion in #1936. I suspect we'll be able to improve things, either via extending the API or else improving the implementation using `inspect` (which is gives us more power in Python 3 than it did in Python 2).
