### ISSUE TITLE
How to investigate CUDA error?

### ISSUE THREAD

**Issue by mattwescott** [google/jax#3017]
This is probably something silly, but I'm not sure to best proceed...

> Program hit CUDA_ERROR_ILLEGAL_ADDRESS (error 700) due to "an illegal memory access was encountered" on CUDA API call to cuMemcpyDtoHAsync_v2

```bash
> nvidia-smi
Fri May  8 23:15:55 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           On   | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P8    31W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+                                                                         
```

```bash
> git log -1
commit d4c0a8d165adfc261495e4073e5a110e70d9bc9e 
```
[here is the trace](https://github.com/google/jax/files/4602112/trace.txt) from `cuda-memcheck --binary-patching ...` 

Saw the same behavior on `jaxlib==0.1.47`. The timing of the error seems to be stochastic. Sometimes it runs for several minutes, other times it fails right away. The random seed is fixed.

**Comment by mattjj** [comment]
@hawkinsp any thoughts?

**Comment by mattwescott** [comment]
My XLA size was blowing up. Now that I've fixed that, getting `CUDA_ERROR_OUT_OF_MEMORY`. This happens after hundreds of equivalent computations, between which, as far as I can see, no references should be retained at the python level. Running on a smaller batch with `--leak-check full`.

**Comment by gnecula** [comment]
Not sure if this is going to help, but in the past I was able to get more information by building my own jaxlib from source (see [developer doc](https://jax.readthedocs.io/en/latest/developer.html)) and turning off the optimizations by commenting `build -c opt` in [build.py](https://github.com/google/jax/blob/c171c33b1c3aef0427531b4805213430f3633dbd/build/build.py#L188).

**Comment by hawkinsp** [comment]
I think we'd need a reproduction of either problem in order for us to make progress on them from our end.

**Comment by mattwescott** [comment]
This works fine on CPU. For now I'm working around it on GPU via multiple sequential processes. If any other diagnostics come to mind, let me know.
