### ISSUE TITLE
Inconsistent output type for jnp.array([])

### ISSUE THREAD

**Issue by GeorgOstrovski** [google/jax#3057]
The output type of `jnp.array([])` (input: empty list or tuple) is `numpy.ndarray`, inconsistent with the output type of `jnp.array([1])` (or other non-trivial inputs) which is `DeviceArray`. This seems to be set explicitly [here](https://github.com/google/jax/blob/master/jax/numpy/lax_numpy.py#L2063) and seems an unnecessary inconsistency, as empty DeviceArrays seem generally supported (`device_put(jnp.array([]))` produces what one would expect).

**Comment by gnecula** [comment]
This was just fixed in #3049.
