### ISSUE TITLE
Not releasing GPU memory in the end

### ISSUE THREAD

**Issue by Palak-15** [google/jax#3077]
Hello,
I am using **jax** in my **python script**. It is allocating **90%** of my **GPU** and not releasing memory after completion of the task. I tried `XLA_PYTHON_CLIENT_PREALLOCATE=false` and `XLA_PYTHON_CLIENT_MEM_FRACTION=10`, but nothing is working. I didn't find a function in jax to deallocate memory.

What to do?

**Comment by Palak-15** [comment]
I have found a solution to the problem.
Thanks.

**Comment by Saipraneet** [comment]
Hi Palak-15,

Would it be possible to post your solution? I am facing a similar situation.

Thanks!

**Comment by Palak-15** [comment]
Hello @Saipraneet ,
```
Import os
os.environ[XLA_PYTHON_CLIENT_PREALLOCATE']='false'
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION']='.10'
```
Put these lines in the starting of script. It will work.
Regards.

**Comment by Dhidbsixh** [comment]
When I restore a checkpoint(size 4MB), the GPU memory increase from 500MB to about 24GB, and then throw a error OOM, so could you give me some suggestion about this?
