### ISSUE TITLE
What should JAX do about top-K?

### ISSUE THREAD

**Issue by jekbradbury** [google/jax#309]
This is a pretty common operation in machine learning (e.g., k-nearest-neighbors, beam search), but there's no `np.topk` for JAX to overload. Some options for an API:
- `np.partition` is the closest thing in NumPy, but using it as a topk requires another sort afterwards
- `torch.topk` and `tf.nn.topk` have (approximately?) the same semantics/API, so that could be something worth matching
- ...except that a "unique" topk might be faster on certain devices and have indistinguishable results in almost every case
- perhaps the most XLA-ish thing to do would be to represent topk as a composition of sort and slice—as in, the user would `np.sort` or `np.argsort` the entire array then use indexing to take a slice of only the top/bottom of it, and XLA would optimize the combination to avoid sorting the parts of the array beyond the top k. Too magical?

**Comment by mattjj** [comment]
Great question, and great points!

I think TF2XLA must have already explored efficient lowerings for [topk](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/client/lib/sorting.cc), and indeed it looks like like it ultimately does a Sort HLO. As you point out, we could have users just express it that way themselves, though another option would be to expose a `lax.topk`, either as a non-primitive function that calls those lax primitives or as a primitive that lowers into the shared XLA lib (like we do with some math functions). That way, if and when more efficient lowerings are written, users would benefit from them automatically.

The lax module is meant to be user-facing, and it already covers some functions that aren't in NumPy's canonical API (e.g. convolutions). So `topk` could fit in there.

What do you think?

**Comment by jekbradbury** [comment]
Oh yeah, I didn't realize it was in the client lib—that makes sense as the op to expose then.

**Comment by levskaya** [comment]
Given that lax now exposes XLA's `top_k` I think we can close this issue for now.
