### ISSUE TITLE
Support unrolled steps in jax.lax.scan

### ISSUE THREAD

**Issue by clemisch** [google/jax#3094]
Dear jax team,

this request is motivated by recent PR https://github.com/google/jax/pull/3076 and specifically https://github.com/google/jax/pull/3076/commits/0a45fc3b9bf8ae53b371d0e1175ff37127a6bc34 in which a for-loop is used on a small number of elements inside a larger jax.lax.scan, to improve performance on GPUs. 

This code works for accumulating the carry. I don't have enough jax-fu to imagine a nice, general way to accumulate the `ys` (from the scan docstring) though. It would work with appending to a list inside the inner for-loop, but I guess there must be a better way with pytree tools.

**Comment by froystig** [comment]
closed by #3738
