### ISSUE TITLE
Debugging pmap aborts

### ISSUE THREAD

**Issue by john-heyer** [google/jax#3104]
Hi!

I have a function that I'd like to parallelize with `pmap`. I do this over CPUs, by manually setting the device count (perhaps this is not recommended and this is where my issues arise, but I do not have a GPU atm).

If I am mapping over an array of reasonable size, say 16 (meaning I set devices to at least 16), this seems to work. Once I set it too high, however, python quits unexpectedly:

```
F external/org_tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h:300] Check failed: !initialized_ 
Abort trap: 6
```
Is this a memory issue? Something else? I'm having a hard time debugging these errors. Do you have any advice in general for what we can feasibly `pmap`? Thanks a lot!

P.S. my function over which I'm `pmap`'ing in the future will involve randomly indexing a large array ~(10, 1000, 1000), so I'd imagine that a GPU would not excel here? Currently the function is completely functional and does not involve any indexing, so I don't expect memory issues from copying this large array or anything yet

**Comment by skye** [comment]
Looks like an XLA bug! Are you able to provide a short repro script?

I don't know about GPU performance for random indexing, maybe someone else can comment on that.

**Comment by john-heyer** [comment]
Hmmm.. I'll work on a MWE. Thanks!

**Comment by skye** [comment]
We've hit this error before due to race conditions btw, so keep that in mind if you have trouble producing a MWE. Even a not-so-MWE would be better than nothing in this case.

**Comment by john-heyer** [comment]
Hi, sorry I've been away from work for a few days!

Here is a (not-so)MWE that fails on my macbook with 2 cores:

```
from jax import jit, vmap, pmap
import jax.numpy as np
import matplotlib.pyplot as plt
from functools import partial
import numpy as onp


@partial(jit, static_argnums=(2,))
def distance_power_law_grid(x_coords, y_coords, grid_size):
    # distance power law for given pixel
    def pixel_power_law(i, j, x, y):
        half_length = grid_size // 2
        d = (
            ((half_length - i) - y) ** 2 +
            ((j - half_length) - x) ** 2
        )
        return 1 / (1 + d)

    f_single_grid = vmap(
        vmap(pixel_power_law, in_axes=(None, 0, None, None)),
        in_axes=(0, None, None, None)
    )
    f_all_grids = pmap(f_single_grid, in_axes=(None, None, 0, 0))
    grid_i, grid_j = np.linspace(.5, grid_size - .5, grid_size), np.linspace(.5, grid_size - .5, grid_size)
    all_grids = f_all_grids(grid_i, grid_j, x_coords, y_coords)
    return np.sum(all_grids, axis=0)


rand_x = np.array(onp.random.uniform(-32, 32, 30))
rand_y = np.array(onp.random.uniform(-32, 32, 30))
grid_30_points = distance_power_law_grid(rand_x, rand_y, 64)  # works
plt.matshow(grid_30_points)
plt.show()

rand_x = np.array(onp.random.uniform(-32, 32, 40))
rand_y = np.array(onp.random.uniform(-32, 32, 40))
grid_40_points = distance_power_law_grid(rand_x, rand_y, 64)  # aborts
plt.matshow(grid_40_points)
plt.show()
```

The code is producing a grid where each pixel is the sum of power-law functions centered at a set of points. This set of points is what we `pmap` over, so we get a tensor of `n` (the number of points) `grid_size`x`grid_size` arrays. When the number of points is 30, this works fine, but Python aborts when the number of points is 40.

I run this via: `XLA_FLAGS="--xla_force_host_platform_device_count=40" python pmap_fail_mwe.py`

**Comment by hawkinsp** [comment]
I'm unable to reproduce this at head, so I'm going to guess that it is fixed. Please feel free to reopen if it's still reproducible.
