### ISSUE TITLE
L-BFGS implementation

### ISSUE THREAD

**Issue by OlaRonning** [google/jax#3105]
Hi,

I'm implementing [L-BFGS](https://en.wikipedia.org/wiki/Limited-memory_BFGS) in Jax and is running into some trouble when updating the history, as algorithm maintains only a limited window of the past changes. 

With Jax version 0.1.46, the equivalent to `np.delete` (in the original NumPy) raises "not implemented". So I have to convert my history from arrays to python lists and back to get the desired behavior as shown below:
``` python
import jax.numpy as np

def _update_history(self, pos, grd):
    pos_hist = self.position_history.tolist()
    grd_hist = self.gradient_history.tolist()

    n = self.position_history.shape[0]

    pos_hist.insert(0, pos - self.position_history[0, :])
    grd_hist.insert(0, grd - self.gradient_history[0, :])

    if n == self.history_size:
        pos_hist.pop(-1)
        grd_hist.pop(-1)

    self.position_history = np.array(pos_hist)
    self.gradient_history = np.array(grd_hist))
```
This causes the implementation to be quite slow. Is there plan to add `np.delete` to  `jax.numpy`? And if not, is it possible to do the above update with inplace or index operations on the immutable arrays?

**Comment by clemisch** [comment]
Could you save the history in a tuple instead? You could unpack it at the start, discarding the oldest element, and reconstruct the new tuple in the end.

**Comment by OlaRonning** [comment]
Hi @clemisch, thanks for the suggestion. 

Maintaining a tuple of column vectors is definitely a valid approach, though I would have to reconstruct the arrays whenever I want to access history. I assume this is a low overhead operation from a tuple, can you confirm this?

**Comment by clemisch** [comment]
Do you have to combine the arrays from the history into one array, or can you map some operation over the history? For the latter, using tuples should be fine. If the history is not too large you may get away with an explicit for-loop even.

For the former, I would not know how much memory overhead can be compiled away by XLA.

**Comment by OlaRonning** [comment]
Yes, they are stacked to a matrix. However, most operations can be done with maps and reductions. The `history_size` gives the max size of the window and will generally be < 50.

**Comment by froystig** [comment]
Since the history window is already an array, fixed in its size, would it make sense to update the array's slices in a functional style using JAX's [indexed update operators](https://jax.readthedocs.io/en/latest/jax.ops.html#indexed-update-operators)?

**Comment by hawkinsp** [comment]
It seems likely to me that we could implement `np.delete` (although the out-of-bounds behavior might be hard to model).

Assuming you only want to append to the history, you might also consider using something like the indexed update operators, possibly combined with `np.roll()` or similar, or building something similar out of a slice and concatenation?

**Comment by Joshuaalbert** [comment]
I agree with @hawkinsp best be to jaxify this using indexed updating:
```python
content = np.roll(content, -1)
#content[-1,...] = new_content
content = jax.ops.index_update(content, jax.ops.index[-1,...], content)
```
You could avoid the roll by keeping track of the update index,
```python
latest_position = (latest_position+1)%content.shape[0]
#content[latest_position,...] = new_content
content = jax.ops.index_update(content, jax.ops.index[latest_position,...], content)
```

**Comment by Joshuaalbert** [comment]
BTW, maybe see my PR for implementing BFGS in #3101. We should use the same interface.

**Comment by shoyer** [comment]
Using indexed assignment would be slightly cleaner than `np.roll`, which does a little more work than you need:
```
history = history.at[:-1].set(history[1:])
history = history.at[-1].set(new_vector)
```

This might be good enough. We already have to iterate over the whole history, so copying it should be an asymptotic slow-down. XLA should do the copying inplace, as long as its under `jit`.

An even better approach would be to store history in a rolling buffer, where the start position of the history array is incremented at each iteration.

**Comment by OlaRonning** [comment]
@Joshuaalbert I like the approach with an update and tracking the current (start) position (which is also what you suggest @shoyer, right?). I'll update my code and check your PR. My implementation is target NumPyro, but could just as well be in JAX.

@hawkinsp I think above is a cleaner implementation, so there is no need for implementing `np.delete`.

Thanks for the suggestion/discussion -- I'll close the question.

**Comment by Joshuaalbert** [comment]
@OlaRonning do you plan to submit your L BFGS in a PR to JAX? If so, I've already implemented scipy's most advanced line search which should be handy for you.

**Comment by OlaRonning** [comment]
@joschkabraun yes I saw, it looks really cool! I plan to after I've submitted my PR with NMC for numpyro.
