### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by sursu** [google/jax#3115]
I am going through [The Autodiff Cookbook](https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html) and, in my JupyterLab, I've encountered the following issue:

![Peek 2020-05-16 02-28](https://user-images.githubusercontent.com/12001304/82106172-abc7cd80-971f-11ea-8ee6-19cc663489ca.gif)

> The kernel appears to have died. It will restart automatically.

The problem seems to be with `random.normal()`.

I have closed the session. Upgraded to a new version of JupyterLab. Restarted. Same issue.
When I run the script in the terminal I get this:
```bash
Python 3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import jax.numpy as np
>>> from jax import grad, jit, vmap
>>> from jax import random
>>> 
>>> key = random.PRNGKey(0)
>>> key, W_key, b_key = random.split(key, 3)
>>> W = random.normal(W_key, (3,))
>>> W
DeviceArray([-0.36838785, -2.275689  ,  0.01144757], dtype=float32)
>>> b = random.normal(b_key, ())
Segmentation fault (core dumped)
```
This happens when I use the Nvidia GPU.

---
System info:
- Ubuntu 18.04.4
- CUDA 10.1, V10.1.243
- JupyterLab 2.1.2
- JAX 0.1.63

**Comment by sursu** [comment]
Works fine after upgrading both `jaxlib` and `jax`.

**Comment by ramithuh** [comment]
Having the same issue on, 
- JAX 0.2.17
- jaxlib 0.1.69+cuda111

There was no issue when running it when there were 2 GPUs, when I increased it to 4 GPUs this issue arose. (I'm on a SLURM Cluster btw)

<img width="799" alt="Screenshot 2022-01-15 at 11 32 49" src="https://user-images.githubusercontent.com/3503098/149611130-d4761ea5-fa30-4f9f-8006-6df662a723c2.png">

**Comment by CharlieLeee** [comment]
Same issue with:
```
jax                       0.3.13                                       pypi_0    pypi
jaxlib                    0.3.10+cuda11.cudnn82          pypi_0    pypi
```
on Ubuntu 20.04
