### ISSUE TITLE
Request for better error message when pmap and psum don't match on axis_name.

### ISSUE THREAD

**Issue by jmgilmer** [google/jax#3120]
```
a = np.arange(4)[np.newaxis,:]
print(a.shape)
def test(x):
  return jax.lax.psum(x, axis_name='batch')
jax.pmap(test)(a)
```
Gives an error message of `AttributeError: 'str' object has no attribute 'obj'`.
It took me forever to figure out that the issue was the pmap needed axis_name='batch'. It would be helpful if this gave a better error message here.

**Comment by jekbradbury** [comment]
That might win an overall bad-JAX-error-message award! (Not a competition...)
But yeah, this is just a bug.
