### ISSUE TITLE
Getting all values in a pytree

### ISSUE THREAD

**Issue by joaogui1** [google/jax#3124]
Hi, sorry if this is a question with an obvious answer, but how do I get all the values in a pytree?
I tried using `tree_flatten`, but it gives me the device arrays, not the values they contain
(For extra context I want to implement regularizers using jax and need to sum all the squares/absolute values of the neural network parameters)

**Comment by jacobjinkelly** [comment]
Does work `flat_x, unravel = ravel_pytree(x)`? IIUC you want all your parameters in one long vector?

**Comment by joaogui1** [comment]
That's exactly it! Thanks @jacobjinkelly , didn't know about the `flatten_util` module

**Comment by mattjj** [comment]
It works to ravel things, but that might actually be less efficient because it probably involves concatenating all the values into a single contiguous buffer. It might be better to do something like

```python
def l2_normsq(x):
  leaves, _ = tree_util.tree_flatten(x)
  return sum([np.sum(leaf ** 2) for leaf in leaves])
```

(where `sum` is just Python's builtin.)

**Comment by joaogui1** [comment]
Thanks for the tip @mattjj

**Comment by samuela** [comment]
> Does `flat_x, unravel = ravel_pytree(x)` work? IIUC you want all your parameters in one long vector?

Does `ravel_pytree` still exist? I'm not able to find it in the docs: https://jax.readthedocs.io/en/latest/search.html?q=ravel_pytree&check_keywords=yes&area=default

**Comment by jakevdp** [comment]
It does still exist:
```
from jax.flatten_util import ravel_pytree
```
It looks like it's not listed in JAX's documentation
