### ISSUE TITLE
Jaxlib installation/upgrade broken ?

### ISSUE THREAD

**Issue by LysSanzMoreta** [google/jax#3137]
Hi!

I am trying to update my current Jaxlib (1.43) to the latest version(1.47), just as you state. I have tried several things but I keep getting this warning/error and it's not installed ( I do have internet, I can install/upgrade other packages): 

```
Collecting jaxlib==0.1.47
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0d6033160>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0d6047c50>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0d60478d0>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0d6047940>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0d6047550>: Failed to establish a new connection: [Errno 101] Network is unreachable')': /jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
ERROR: Could not install packages due to an EnvironmentError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl (Caused by NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x7fa0d6047630>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

My installation script:

```
PYTHON_VERSION=cp37  # alternatives: cp35, cp36, cp37, cp38
CUDA_VERSION=cuda101  # alternatives: cuda92, cuda100, cuda101, cuda102
PLATFORM=linux_x86_64  # alternatives: linux_x86_64
BASE_URL='https://storage.googleapis.com/jax-releases'
pip install --upgrade $BASE_URL/$CUDA_VERSION/jaxlib-0.1.47-$PYTHON_VERSION-none-$PLATFORM.whl
python -m pip install --upgrade jax  # install jax
```
Thanks :) !!

**Comment by hawkinsp** [comment]
This sounds like a connectivity problem of some kind, since it is the download is failing. It works for me.

To check you did the shell substitution correctly, try expanding the substitution manually?
```
pip install -e https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
```

The `.whl` file is just a regular file you can download; perhaps verify that
```
wget https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl
```
works? If it does, you can just `pip install` the file you download.

Hope that helps!

**Comment by LysSanzMoreta** [comment]
Hi!

Thanks , sorry for my late reply;

The first command is broken:
ERROR: https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.47-cp37-none-linux_x86_64.whl is not a valid editable requirement. It should either be a path to a local project or a VCS URL (beginning with svn+, git+, hg+, or bzr+).

I could wget it and pip install it though :)

Thanks!!!

**Comment by hawkinsp** [comment]
Ah! Sorry, that should have been `pip install ...` not `pip install -e ...`. That said, sounds like we solved this problem. Great!

**Comment by RylanSchaeffer** [comment]
I'm running into a somewhat related problem. I'm trying

`pip install --upgrade jax jaxlib==0.1.52+cuda101 -f https://storage.googleapis.com/jax-releases/jax_releases.html`

But I'm getting the error `ERROR: Requested jaxlib==0.1.52+cuda101 from https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.52%2Bcuda101-cp37-none-manylinux2010_x86_64.whl has different version in metadata: '0.1.52'`

@hawkinsp , any idea what the problem might be?

**Comment by jakevdp** [comment]
I found that running
```
pip install pip==20.3.3
pip install --upgrade jax jaxlib==0.1.52+cuda101 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
reproduces the `different version in metadata` error, but using older versions of pip do not result in this error. For example, this installs correctly:
```
pip install pip==20.2.4
pip install --upgrade jax jaxlib==0.1.52+cuda101 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```
I suspect that the pip 20.3 dependency resolver places stricter requirements on the contents of package metadata.
