### ISSUE TITLE
Reductions can quietly muck with loop in/out types

### ISSUE THREAD

**Issue by brianwa84** [google/jax#3154]
Simple example:

```python
import jax
jax.config.update('jax_enable_x64', True)
print(jax.config.values)

from jax import lax, numpy as jnp

def f(carry, y):
  return carry + jnp.prod(y, axis=-1), None

lax.scan(f, init=jnp.zeros([2], dtype=jnp.int32), xs=jnp.ones([3, 2, 0],dtype=jnp.int32))[0]
```

```
TypeError: scan carry output and input must have identical types, got
ShapedArray(int64[2])
and
ShapedArray(int32[2]).
```

The issue seems to be that `prod` without the `dtype` arg upcasts (agreeing w/ the numpy spec) to the platform int precision, which jax apparently interprets as 64-bit with `'jax_enable_x64'` set to `True`.

**Comment by mattjj** [comment]
Thanks for catching this, and explaining it!

Hrm, what do you think we should do here instead?

**Comment by brianwa84** [comment]
I guess I don't understand the rationale for numpy behavior here, perhaps it's around avoiding overflows.
If you're not too attached to the behavior, you could change the default to match the input's dtype (TensorFlow behavior; does anyone know pytorch behavior on .sum()?), still allowing the user to override to a higher precision by specifying the dtype arg.
If you want to match numpy, maybe start a list of possible causes of dtypes changing in a loop, and link to the list from the scan exception (and other loop constructs with this constraint)? It's really mostly loops where dtype upcasting bites in JAX.

**Comment by mattjj** [comment]
@hawkinsp has thought the most about our dtype policy. Peter, what do you think? Should we change the promotion behavior, or else raise a better error (perhaps including a link to a list of common issues as @brianwa84 suggested)?

Also cc @shoyer @jakevdp for NumPy-matching expert opinions.

**Comment by shoyer** [comment]
I'm sure It's well-intentioned, but I don't think NumPy default behavior of upcasting makes any sense.

I think JAX should preserve the input dtype, the same as NumPy does for nearly every other functions.

**Comment by mattjj** [comment]
Maybe it's to accumulate in a higher precision and thus avoid numerical issues?

**Comment by shoyer** [comment]
I'm sure that's the idea, but if float32 overflow with multiplication is a serious worry, you should probably be worried about float64 overflow, too. It's only an 8x larger range for the exponent. I just don’t think it makes a big enough difference to be worth the inconsistency.

**Comment by brianwa84** [comment]
Also bear in mind the accumulator could use a higher precision and still
return a downcast matching dtype.

**Comment by jakevdp** [comment]
Revisiting this... it looks like this is only an issue for integer dtypes:
```python
In [1]: import jax.numpy as jnp
   ...: from jax.test_util import dtypes
   ...: from jax import config; config.update('jax_enable_x64', True)
   ...: for dtype in dtypes.all:
   ...:     print(dtype.__name__, "->", jnp.zeros(2, dtype).sum().dtype)
   ...:     
bfloat16 -> bfloat16
float16 -> float16
float32 -> float32
float64 -> float64
int8 -> int64
int16 -> int64
int32 -> int64
int64 -> int64
uint8 -> uint64
uint16 -> uint64
uint32 -> uint64
uint64 -> uint64
complex64 -> complex64
complex128 -> complex128
bool_ -> int64
```
I think it's reasonable to make the result type match the input by default: you could always recover the current behavior via explicit casts, but there's currently no way to make the reduction preserve the input dtype.

**Comment by jakevdp** [comment]
Closing – we ended up adding a `promote_integers` flag to reductions which defaults to `True` for backward compatibility, and you can set it to `False` if you wish:
```
import jax
jax.config.update('jax_enable_x64', True)

from jax import lax, numpy as jnp

def f(carry, y):
  return carry + jnp.prod(y, axis=-1, promote_integers=False), None

lax.scan(f, init=jnp.zeros([2], dtype=jnp.int32), xs=jnp.ones([3, 2, 0],dtype=jnp.int32))[0]
# -> Array([3, 3], dtype=int32)
```
We briefly discussed making this `False` by default, but users pushed back because it led to too many cases where sums of narrow int arrays wrapped unexpectedly; see https://github.com/google/jax/pull/12532
