### ISSUE TITLE
Double jit-compilation in loop when passing plain types

### ISSUE THREAD

**Issue by lumip** [google/jax#3163]
Consider the following code snippet:

```python
import jax
import jax.numpy as np

my_fn_calls = 0

@jax.jit
def my_fn(x, y):
    # side effect to detect multiple tracing
    global my_fn_calls
    my_fn_calls += 1
    print("my_fn")

    return x + y

x = 0

for i in range(10):
    x = my_fn(x, i)

assert(my_fn_calls == 1) # fails because my_fn_calls == 2
```

Here, `my_fn` is traced twice during the loop. The reason for this is that for the first iteration, `x` is a python integer which jax transforms into a `Traced<ShapedArray(int32[], weak_type=True)>` but after the first iteration, it is of type `Traced<ShapedArray(int32[])>`. Due to the missing `weak_type=True`, these are not seen as equivalent and tracing is once more performed in the second for-loop iteration, even though types have actually not changed.

While in this example this is somewhat benign, this has happened to us in cases where the compilation my take some minutes, in which case it would be nice to only perform it once.

An obvious fix would be to ensure that no regular types are passed into jax here, but that puts an additional burden on the programmer that we would wish to avoid.

Could someone explain what the purpose of the `weak_type` parameter is exactly and whether it would be possible for jax to detect these cases and perform compilation only once?

**Comment by mattjj** [comment]
Thanks so much for the crystal-clear explanation!

The `weak_type` parameter was added in #1709. The PR message has a description, but basically it exists to better follow NumPy-like dtype promotion behavior.

Still thinking about this...

**Comment by hawkinsp** [comment]
To some extent, this is working as intended: you passed in a different type (a Python float vs a NumPy float of some fixed type) and so we recompiled. If the behavior was the same, we might avoid the recompilation, but the point of the change is that the behavior isn't always the same.

**Comment by hawkinsp** [comment]
We might consider caching Jaxpr -> XLA computation, if we believe that the same program was generated in both cases.

**Comment by jakevdp** [comment]
Somehow along the way this was fixed!
