### ISSUE TITLE
Binary search function in lax_control_flow_test.py doesn't work where anticipated

### ISSUE THREAD

**Issue by phinate** [google/jax#3177]
I'm trying to find the roots of a function differentiably using `lax.custom_root`, and for an initial test, I've been using the `binary_search` routine defined [here in `lax_control_flow_test.py`](https://github.com/google/jax/blob/7d157c71815e5386f2b449bac69ef9e3ab7e701f/tests/lax_control_flow_test.py#L1516).

The function is very similar in shape to this one: `f = lambda x: -(1+jnp.tanh(x-4))/2 + 0.1`, which has a root at ~2.9. No matter which starting bracket I use, I'm unable to find the root of `f` with this routine. Just as a cross-check, I can find the root with `scipy.optimize.fsolve` with most reasonable starting values.

I hope this is somehow useful, and not just stemming from my apparent lack of ability to understand the midpoint method (:

**Comment by mattjj** [comment]
@shoyer mind taking a look at this one?

**Comment by shoyer** [comment]
I think that binary search routine requires that the function is monotonic increasing, but your function is monotonic _decreasing_. Try taking the negative of your function?

**Comment by phinate** [comment]
Ah, I didn't think about that, this works :) sorry for the issue clutter!
