### ISSUE TITLE
Cast breaks jit

### ISSUE THREAD

**Issue by fvisin** [google/jax#3180]
Casting via `jnp.float32(x)` breaks jit. 

> *** Exception: Tracer can’t be used with raw numpy functions. You might have
> import numpy as np
> instead of
> import jax.numpy as jnp

The workaround is to use `jnp.asarray(x, dtype=jnp.float32)` instead, but the error is very confusing and it would be nice if this was done automatically under the hood by jax.

**Comment by hawkinsp** [comment]
I suspect to fix this all we need to do is change this line of code:
https://github.com/google/jax/blob/bb2127cebd3ade161109ee4919a92aaff5c788c1/jax/numpy/lax_numpy.py#L151
to do something different for JAX array types.
