### ISSUE TITLE
Require for Geometric Distribution

### ISSUE THREAD

**Issue by gao462** [google/jax#3191]
It seems that `jax` does not have geometric distribution in its random module like `scipy.stats`. Will it be added? I really need it.

**Comment by shoyer** [comment]
We would happily accept pull requests to add a geometric distribution, but we have no immediate plans to work on it.

**Comment by terhorst** [comment]
It is easy to simulate geometric random variables given a uniform RNG:

```np.ceil(np.log(np.random.rand()) / np.log1p(-p))```

has a `Geometric(p)` distribution. (Source: http://www.nrbook.com/devroye/Devroye_files/chapter_ten.pdf)

@gao462 I don't have time to package this up into a PR but I encourage you to do so if you end up using it.
