### ISSUE TITLE
Sign error in jax.custom_jvp and jax.custom_vjp docs

### ISSUE THREAD

**Issue by jiawen** [google/jax#3213]
I'm having fun learning JAX but think I found a sign error in the math in [these docs](https://jax.readthedocs.io/en/latest/jax.html).

In the example, f(x, y) = sin(x) * y.

df/dx is cos(x) * y as expected. But df/dy should be sin(x), not -sin(x) as in the example code for both f_jvp and f_bwd.

I'm happy to create a pull request if that's the best practice here.

**Comment by mattjj** [comment]
Yes, please make a PR if you can! This might be another instance of the bug in #3031.

**Comment by mattjj** [comment]
Fixed by @jiawen in #3219 !
