### ISSUE TITLE
State of JAX and Apache Arrow

### ISSUE THREAD

**Issue by jamesthegiantpeach** [google/jax#3215]
Greetings.

This is just a question:

Is there any work on Jax with apache arrow tensors by any chance? I didn’t see any design docs on this.

**Comment by hawkinsp** [comment]
Not to my knowledge. But we welcome PRs!

**Comment by hawkinsp** [comment]
But you might clarify what things you would need that can't already be achieved by passing data as NumPy arrays, which both JAX and pyarrow already support?

**Comment by jamesthegiantpeach** [comment]
I think I can hit everything I need by doing my IO to arrow tensors -> numpy ndarray -> Jax things.

Thanks! I am auditing this for a project.

**Comment by hawkinsp** [comment]
Great! Sounds like there's no action for us to take here, so I'm closing this issue. Feel free to file another issue or reopen this one if there's something for us to do!

**Comment by chaokunyang** [comment]
Arrow support nullablity nativly, numpy doesn't support it. Converting a nullable int64 pyarrow array into numpy will become a float64 array, which will have precision loss, see more in #16289 .
