### ISSUE TITLE
Support higher order functions in shapecheck

### ISSUE THREAD

**Issue by shoyer** [google/jax#3228]
It would be nice to be able to shapecheck numerical algorithms that are functions of functions, like `odeint` or `cg`, e.g., perhaps:
```python
@shapecheck(['n->n', 'n', 'n'], 'n')
def cg(A, b, x0):
  ...
```

**Comment by mattjj** [comment]
Brainstormed for a couple minutes with Dougal about this, and it might be possible!

**Comment by hawkinsp** [comment]
`shapecheck` has been removed.
