### ISSUE TITLE
Error shape checking rule Igamma

### ISSUE THREAD

**Issue by organic-chemistry** [google/jax#3248]
Hello, I am using the function

`sp.special.gammainc(alpha,inside)`

And it generated the error:
```
RuntimeError: Invalid argument: Arguments to Igamma must have equal shapes and types; got f32[7,230,21,1] and f32[7,230,21,13]: 
This is a bug in JAX's shape-checking rules; please report it!
```

As I cannot find what is wrong I assume the statement above is True.

Best

**Comment by froystig** [comment]
Thanks!

I don't encounter any errors when I run the following:

```python
from jax import jit, lax, numpy as jnp, scipy as jsp
args = (jnp.ones((7, 230, 21, 1)), jnp.ones((7, 230, 21, 13)))
jsp.special.gammainc(*args)
lax.igamma(*args)
jit(jsp.special.gammainc)(*args)
jit(lax.igamma)(*args)
```

I tried other shapes within `args` as well.

Could you help us reproduce the error on our end? It would be helpful to have a minimal example that causes it.

**Comment by organic-chemistry** [comment]
Hi,
Here is a minimal example:

```
def cdf(t,p):
    return sp.special.gammainc(p ,t)
cdfs=vmap(cdf,(None,0),0)
print(cdfs(3.,np.array([1.,2.])))
```

**Comment by jekbradbury** [comment]
That code too works correctly for me on master; can you check if you have the latest versions of jax and jaxlib?

**Comment by organic-chemistry** [comment]
Yes sorry, I updated from
jax                       0.1.62                    dev_0    <develop>
jaxlib                    0.1.43                   pypi_0    pypi

to 

jax                       0.1.68                    dev_0    <develop>
jaxlib                    0.1.47                   pypi_0    pypi

and it fixed my problem.
Sorry and thank you for your time.
Best
