### ISSUE TITLE
Random module example not rendered prob

### ISSUE THREAD

**Issue by nkthiebaut** [google/jax#3249]
Hi, 

The example usage for the random package does not render properly in https://jax.readthedocs.io/en/latest/jax.random.html: 
![image](https://user-images.githubusercontent.com/10967508/83291634-7f8b6280-a19d-11ea-828f-69c52aebc12f.png)
 
A simple solution would consist in changing lines 17 to 23 here : https://github.com/google/jax/blob/9208a940a92efeab848b46d7be7b4f41af355e5b/jax/random.py#L17

for

```
Example:
    >>> rng = jax.random.PRNGKey(seed)
    >>> for i in range(num_steps):
    ...     rng, rng_input = jax.random.split(rng)
    >>> params = compiled_update(rng_input, params, next(batches))
```

I've tried locally and it works I can raise a PR if that helps.

**Comment by froystig** [comment]
Thanks for pointing that out. Fixed in 8fbab04d and e7e4cbce.
