### ISSUE TITLE
What does "dimension_numbers" parameter represent in Convolutional layer constructor `GeneralConv` in `jax.experimental.stax.py`?

### ISSUE THREAD

**Issue by DarrenZhang01** [google/jax#3266]
As titled. There are several use cases in the repo [(https://github.com/google/jax/search?q=generalconv&unscoped_q=generalconv),](https://github.com/google/jax/search?q=generalconv&unscoped_q=generalconv) but I am still not clear what they are. Thanks.

**Comment by shoyer** [comment]
`jax.lax.conv_general_dilated` has some documentation on this:
https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.conv_general_dilated.html

**Comment by DarrenZhang01** [comment]
I see. Thanks for bringing up the link, @shoyer !
