### ISSUE TITLE
shouldn't this be jnp instead of np?

### ISSUE THREAD

**Issue by samuela** [google/jax#3267]
https://github.com/google/jax/blob/6124f703afa9c1fe6ef068741b6e6ee140b1f462/tests/ode_test.py#L45

Otherwise, `np_fun` and `jax_fun` are the same...

**Comment by mattjj** [comment]
Yes, it certainly should! This might have been messed up when we rewrite `np`->`jnp` and `onp`->`np`.

Want to make a PR to fix?
