### ISSUE TITLE
bug in np.full / lax.full for DeviceArray wrapped scalars

### ISSUE THREAD

**Issue by levskaya** [google/jax#330]
If you pass in a jax-wrapped scalar as the fill-constant value to np.fill, it breaks, e.g.:
```python
np.full((1,1), np.array([1])[0])
```
this hits the condition in lax.full:
```python
 elif isinstance(fill_value, xla.DeviceValue):
    return FilledConstant(convert_element_type(fill_value, dtype), shape)
```
no matter what dtype is, the convert_element_type result is still a DeviceArray, then
this line in lax.FillConstant:
```python
class FilledConstant(xla.DeviceConstant):
  __slots__ = ["fill_value"]

  def __init__(self, fill_value, shape):
    assert type(fill_value) is onp.ndarray
```
wants the fill value to be an onp ndarray instead.

I'm not too certain about the type logic here to make a PR confidently.

**Comment by mattjj** [comment]
Thanks for catching this! We just needed an `onp.asarray` there to turn the DeviceValue back into a regular ndarray. (We might instead be able to allow FilledConstants to have DeviceValues inside, but this seems like the simpler option.)
