### ISSUE TITLE
scipy.minimize does not work with repeated or redundant constraints

### ISSUE THREAD

**Issue by bernamdc** [google/jax#3311]
When defining a list of constraints as an input for the scipy.minimize (using a default 'SLSQP' method), repeated or redundant constraints will raise messages like "Singular matrix C in LSQ subproblem", and a solution is not achieved, when in fact, these repeated/redundant constraints should just be ignored.

This is very relevant when one has to define multiple inequality and equality constraints, which sometimes partially overlap for some of the constraints.

To replicate the problem: Use a working example of a constrained minimization problem, but now duplicate the list of constraints (two times more constraints, but all of them repeated).

Example where this is useful: Forcing a bivariate polynomial f(x,y) of a certain degree, to be f(0,y)=0 and forcing it's first derivative with respect to x, to be d f(x=1,y) / dx = 0, will provide a large set of equality constraints where a few of them are redundant.

**Comment by shoyer** [comment]
JAX doesn't supply a scipy.minimize function. Did you perhaps mean to open this issue in the SciPy tracker?

**Comment by mattjj** [comment]
Since as @shoyer observes there is no `jax.scipy.minimize`, I'm going to close this issue on the suspicion that it's meant for the [the SciPy issue tracker](https://github.com/scipy/scipy/issues). Please let us know if I've misunderstood!

**Comment by bernamdc** [comment]
@mattjj you are entirely correct. This was my first issue so I did not even know github had so many other topics, I'm sorry.
