### ISSUE TITLE
jax fft padding or n error

### ISSUE THREAD

**Issue by mathildejutras** [google/jax#3315]
Hi,
I try to use the jax fft function with an integer for the n argument (a padding on my time series), as follows:
`jax.numpy.fft.fft(a,n=256, axis=1)`
but I get the following error: `NotImplementedError: jax.numpy.fft.fft only supports s=None, got 256`

Thanks.

**Comment by jakevdp** [comment]
As mentioned in the error message, this functionality is not yet implemented in Jax. You could work around this by manually padding your input before calling the fft function.

**Comment by mathildejutras** [comment]
Ok, I was not sure. Sorry and thank you.

**Comment by jakevdp** [comment]
Something like this should be equivalent for a 1D array, if the length of `a` is shorter than `n`:
```python
jnp.fft.fft(jnp.pad(a, [(0, 0), (0, 256 - a.shape[1])]))
```
