### ISSUE TITLE
np.linalg.svd on TPU

### ISSUE THREAD

**Issue by adler-j** [google/jax#3332]
JAX currently only supports SVD on the CPU or GPU and one gets the following error when attempting to run it on a TPU:

```
NotImplementedError: Singular value decomposition is only implemented on the CPU and GPU backends
```

Afaik the SVD is supported in tensorflow so there should exist XLA primitives for it. What needs to be done to add support in JAX?

**Comment by hawkinsp** [comment]
Done in #3334, which enables the same implementation TF uses in JAX also.

Last time I considered this, the TPU SVD implementation wasn't of sufficient quality to pass our unit tests. It seems to work acceptably now, at least for real types. But YMMV, let us know how it goes.
