### ISSUE TITLE
Question about `feature_group_count` and `batch_group_count` in lax `conv_general_dilated`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/jax#3349]
Could anyone point me the relevant knowledge point or publication (or brief explanation) on these two parameters of [`conv_general_dilated`](https://github.com/google/jax/blob/master/jax/lax/lax.py#L467-L555)? Thanks.

**Comment by mattjj** [comment]
Thanks for the question!

See [this section of the XLA Operation Semantics page](https://www.tensorflow.org/xla/operation_semantics#convwithgeneralpadding_convolution). Does that cover what you have in mind?

**Comment by DarrenZhang01** [comment]
Thanks, Matthew!
