### ISSUE TITLE
How Primitives Work Doc shows raw notebook JSON

### ISSUE THREAD

**Issue by jakevdp** [google/jax#3380]
https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html

**Comment by mattjj** [comment]
I suspect this happened from a change I made yesterday (the notebook had to be updated after #3222, and I just edited the .ipynb text directly rather than re-exporting the notebook).

I think I see the issue!

**Comment by mattjj** [comment]
I think d3ccf0a should fix this.

**Comment by mattjj** [comment]
Fixed!
