### ISSUE TITLE
jnp.asarray does not copy when copy=True

### ISSUE THREAD

**Issue by btanner** [google/jax#3412]
This can be a problem now that we have donate_argnums. It took me a while to realize this, before I smartened up and just used x.copy() in the example below.

```
import functools
import jax
import jax.numpy as jnp

@functools.partial(jax.jit, donate_argnums=(0,))
def _test(array: jnp.ndarray):
  return array.at[0].set(77)

x = jnp.asarray([0, 1])
x_copy = jnp.array(x, copy=True)
new_x = _test(x)

# Gives: RuntimeError: Invalid argument: CopyToHostAsync() called on invalid buffer.
print(x_copy)

```

@tomhennigan

**Comment by mattjj** [comment]
@hawkinsp advises that we don't have in our device runtime a way to copy buffers! He'll add one, but in the meantime I'll add something that bounces back to the host.

**Comment by btanner** [comment]
@mattjj  - Worth pointing out that the failure only happened on TPU. On GPU/CPU, the buffer wasn't able to be donated <shrug>.

**Comment by mattjj** [comment]
@btanner yes thanks for highlighting that; I understood! (We hope buffer donation will start working on GPU pretty soon...)
