### ISSUE TITLE
Applying one filter per batch of data in a convolution

### ISSUE THREAD

**Issue by statsybanksy** [google/jax#3428]
First of all, thank you for the wonderful library!

My question concerns convolutions. I have two tensors for which the first two indices indicate parameters of my problem and the final two specify a 2D distribution. For each fixed values of the first two indices, I would like to perform a convolution of the corresponding distributions. However, I have some issues in using `lax.conv_general_dilated` to do that - it applies each kernel to each batch of data, and in doing so, it does much more computation than necessary.

A repro example below:
```
import jax.numpy as jnp
from jax.lax import conv_general_dilated, conv_dimension_numbers

kernel = jnp.array([1., 1., 1.,
                   1., 0., 1.], dtype=jnp.float64).reshape(2, 3)
data = jnp.array([2.0, 2.0, 2.0,
                  2.0, 2.0, 2.0,], dtype=jnp.float64).reshape(2, 3)

data_tensor = jnp.array([[data], [data + 1], [data + 2]])
kernel_tensor = jnp.array([[kernel], [kernel + 1], [kernel + 2]])

dn = conv_dimension_numbers(data_tensor.shape,  
                                    kernel_tensor.shape,  
                                    ('NCHW', 'OIHW', 'NCHW'))

def compute_conv(data_tensor, aft_tensor, dn):
    p1, p2 = data_tensor.shape[-2:]
    out = conv_general_dilated(data_tensor,    # lhs = image tensor
                                       kernel_tensor[:, :, ::-1, ::-1],    # rhs = conv kernel tensor
                                       (1, 1),  # window strides
                                       ((p1 - 1, p1 - 1), (p2 - 1, p2 - 1)),
                                       (1, 1),  # lhs/image dilation
                                       (1, 1),  # rhs/kernel dilation
                                       dn)     # dimension_numbers = lhs, rhs, out dimension permutation
    return out[:, :, :p1, :p2]

compute_conv(data_tensor, kernel_tensor, dn)
```
This code would compute convolutions of each combination of `(data, data + 1, data + 2)` with `(kernel , kernel + 1, kernel + 2)`, when in fact I'd only like to compute convolutions of `(data with kernel)`, `(data + 1 with kernel + 1)`, and so on. Is this possible to do directly using jax's convolution functions or should I be looking at some kind of vmaping over the first two axes?

**Comment by hawkinsp** [comment]
Sorry this issue was missed in the issue tracker!

I think the easiest way to do what you are asking is to use `jax.vmap` to map over both the data and the kernel simultaneously, something like this:

```
from functools import partial
import jax
import jax.numpy as jnp
from jax.lax import conv_general_dilated, conv_dimension_numbers

kernel = jnp.array([1., 1., 1.,
                   1., 0., 1.], dtype=jnp.float64).reshape(1, 1, 2, 3)
data = jnp.array([2.0, 2.0, 2.0,
                  2.0, 2.0, 2.0,], dtype=jnp.float64).reshape(1, 1, 2, 3)

data_tensor = jnp.stack([data, data + 1, data + 2])
kernel_tensor = jnp.stack([kernel, kernel + 1, kernel + 2])

dn = conv_dimension_numbers(data.shape, kernel.shape, ('NCHW', 'OIHW', 'NCHW'))

def compute_conv(data_tensor, aft_tensor, dn):
    p1, p2 = data_tensor.shape[-2:]
    out = conv_general_dilated(
       data_tensor,
       aft_tensor[:, :, ::-1, ::-1],
       (1, 1),
       ((p1 - 1, p1 - 1), (p2 - 1, p2 - 1)),
       (1, 1),
       (1, 1),
       dn) 
    return out[:, :, :p1, :p2]

print(jax.vmap(partial(compute_conv, dn=dn))(data_tensor, kernel_tensor))
```

(If you look at how this works under the hood, it uses a grouped convolution, which is created with the `feature_group_count` operand to `conv_general_dilated`, but I'd recommend you use `vmap` which forms this for you automatically, and has an API that is far easier to understand!)

Hope that helps!
