### ISSUE TITLE
Documentation for complex JVP and VJP

### ISSUE THREAD

**Issue by Jakob-Unfried** [google/jax#3433]
I have two issues:
- the JVP documentation for complex autodiff in the cookbook is wrong (i.e. it doesnt match the implementation of jax.jvp, i am not completely sure if there is only one correct choice, so maybe it is not "wrong", but it matches neither the implementation nor one JVP formula i know of, that works)
- the VJP is not documented at all (there is a link to autograds doc, but i think it should be all in the same place)

### Demonstration that JVP doc is incorrect

consider this code, that implements a crude version of jvp, using the formula in the cookbook,
my proposed change to the correct formula, and compares both the jax.jvp

```python
from jax import jvp, grad, numpy as np

def w(z):
    # some non-holomorphic complex-to-complex trial-funtion
    return .5 * (z ** 2) + np.conj(z) ** 3 / 3

def jvp_cookbook(fun, primals, tangents):
    # calculating the jvp output like illustrated in the cookbook
    z, = primals
    t, = tangents
    a, b = np.real(z), np.imag(z)
    c, d = np.real(t), np.imag(t)
    
    def u(_a, _b):
        _z = _a + 1.j * _b
        return np.real(fun(_z))
    
    def v(_a, _b):
        _z = _a + 1.j * _b
        return np.imag(fun(_z))
    
    primals_out = fun(z)
    
    # tangents_out = None
    
    tangents_out = c * grad(u, argnums=(0,))(a, b)[0] \
                   + (-d) * grad(v, argnums=(0,))(a, b)[0] \
                   + (-1.j * c) * grad(u, argnums=(1,))(a, b)[0] \
                   + 1.j * d * grad(v, argnums=(1,))(a, b)[0]

    return [primals_out], [tangents_out]

def jvp_proposed_change(fun, primals, tangents):
    # calculating the jvp output like in my proposed change
    z, = primals
    t, = tangents
    a, b = np.real(z), np.imag(z)
    c, d = np.real(t), np.imag(t)
    
    def u(_a, _b):
        _z = _a + 1.j * _b
        return np.real(fun(_z))
    
    def v(_a, _b):
        _z = _a + 1.j * _b
        return np.imag(fun(_z))
    
    primals_out = fun(z)
    
    # tangents_out = None
    
    tangents_out = c * grad(u, argnums=(0,))(a, b)[0] \
                   + 1.j * c * grad(v, argnums=(0,))(a, b)[0] \
                   + d * grad(u, argnums=(1,))(a, b)[0] \
                   + 1.j * d * grad(v, argnums=(1,))(a, b)[0]

    return [primals_out], [tangents_out]
    
primal = 2 + 2.j
tangent = 1. + 1.j

def round_complex(z):
    return round(np.real(z)) + 1.j * round(np.imag(z))

print('cookbook:   ', round_complex(jvp_cookbook(w, [primal], [tangent])[1][0]))
print('proposed:   ', round_complex(jvp_proposed_change(w, [primal], [tangent])[1][0]))
print('jax.jvp:    ', round_complex(jvp(w, [primal], [tangent])[1]))

# cookbook:    (8+12j)
# proposed:    (-8-4j)
# jax.jvp:     (-8-4j)
```

### what the formula in the cookbook should say:

i believe it should be 
(i dont know how to put render a matrix in github markup, so here is the expanded version)

(∂_0 u) * c + i * (∂_0 v) * c + (∂_1 u) * d + i * (∂_1 v) * d

which i derived from a JVP formula using the holomorphic and anti-holomorphic derivatives of the complex primitive (i am happy to discuss about this, but if asked for, i would much prefer a place with descent math rendering)

**Comment by mattjj** [comment]
My guess is that the cookbook is wrong, since that was written a bit hastily during an overnight flight to Australia and perhaps never double-checked :)

Want to make a PR with the fix?

**Comment by mattjj** [comment]
I see a few other typos in there! I can take a stab at fixing them now.

**Comment by Jakob-Unfried** [comment]
I don't think its a good idea for me to patch this together.
As for as my understanding goes, there is no single obvious choice to do complex AD.

[This article](https://arxiv.org/abs/2003.04295) for example, if i understand it correctly, suggests a different convention for what VJPs should do (they call them the "adjoint function").

 So the important thing is that the cookbook reflects what jax is actually doing behind the scenes (and I dont know too much about that), but also what custom JVPs and VJPs should do

**Comment by mattjj** [comment]
Take a look at #3434 if you can, and let me know your thoughts. I think it should disambiguate our conventions (which have a lot to recommend them IMO!).

**Comment by Jakob-Unfried** [comment]
That looks great!
It is clear what autodiff does, and how to obtain useful results.

The definitions of JVP and VJP are rendered weirdly for me, but that is all i have reason to object to.

Btw, is there some published article or review or something about the derivation of complex AD that i could cite?

I am writing about complex AD in my thesis, that's how i stumbled upon the error in the first place.

Feel free to close this

**Comment by mattjj** [comment]
Thanks so much for checking it over, and for spotting this error in the first place. I'm embarrassed we left it broken for so long, but I'm glad we got it fixed! (Hopefully my error here didn't waste too much of your time...)

I don't know of any references unfortunately. As far as I know @dougalm independently came up with this convention early on in Autograd's development, though at least my understanding has improved over time (so that we can produce better and less buggy explanations, like in #610 and now our docs). You could cite Dougal's thesis, though it doesn't unpack as many details as now written in the JAX docs. I wouldn't be surprised if this convention has a long history; I'm just not familiar with it.

Thanks again for the help!
