### ISSUE TITLE
Error while using jax-optimizers with pmap function

### ISSUE THREAD

**Issue by EyalRozenberg1** [google/jax#3435]
Is JAX capable to include optimizers while using pmap functions?

I am trying to solve an optimization problem on multiple GPUs. The code worked perfectly fine when I have included the optimizer and running on a single GPU with @jit functions only.
Unfortunately, when I use the built-in Jax optimizations & pmap I get the following error:
"
...
  File ".../site-packages/jax/api.py", line 1152, in f_pmapped
    local_axis_size = _mapped_axis_size(in_tree, args, in_axes_flat, "pmap")
  File ".../site-packages/jax/api.py", line 883, in _mapped_axis_size
    for i, (x, d) in enumerate(zip(vals, dims))
  File ".../site-packages/jax/api.py", line 884, in <setcomp>
    if d is not None}
  File ".../site-packages/jax/api.py", line 879, in _get_axis_size
    f"but axis to be mapped {axis}") from e
**ValueError: pmap got arg 0 of rank 0 but axis to be mapped 0**
"

The model is implemented as follows:

replicate_array = lambda x: np.broadcast_to(x, (num_devices,) + x.shape)
params             = tree_map(replicate_array, params)
target1             = tree_map(replicate_array, target1)
target2             = tree_map(replicate_array, target2)

@jit
**def** forward_model(params, input):
       ...
       **return** res1, res2

@jit
**def** loss(params, input, target1, target2):
      approx_target1, approx_target2   = forward(params, input)
       **return** some_dist_method(approx_target1, approx_target2, target1, target2)

@pmap
**def** update(i, opt_state, input, target1, target2):
      params = get_params(opt_state)
      batch_loss, grads = value_and_grad(loss)(params, x, target1, target2)
      **return** batch_loss, opt_update(i, grads, opt_state)

opt_init, opt_update, get_params = optimizers.momentum(step_size=1e-3, mass=0.99)
opt_state = opt_init(params)

for epoch in range(num_epochs)
      for i, input in enumerate(batch_set):
            batch_loss, opt_state = update(epoch+i, opt_state, input, target1, target2)  <-- error occure here

**Comment by untom** [comment]
Relevant XKCD for this bug: https://xkcd.com/979/

(i.e., it would be helpful if you could tell us why you closed this)

**Comment by EyalRozenberg1** [comment]
Sure, 
Because update() is a @pmap function its inputs must be mapped on all GPUs. Thus all needed to be done is to map "epoch+i":

`idx = pmap(lambda x: np.array(epoch+i))(np.arange(num_devices))`
`batch_loss, opt_state = update(opt_state, idx, x, P_ss_t, G2t)`

**Comment by EyalRozenberg1** [comment]
you may look at issue #3518 (https://github.com/google/jax/issues/3518#issuecomment-647983357) for more detailed implementation.
