### ISSUE TITLE
jax.numpy.set_printoptions seems to be a no-op

### ISSUE THREAD

**Issue by samuela** [google/jax#3438]
In particular, I'm trying to print JAX arrays to their full precision. Here's an example of the issue and a comparison with numpy: https://colab.research.google.com/drive/1-TrN7ON5XY-bJVTrvyn3Loqzhj-CcYBE?usp=sharing.

**Comment by mattjj** [comment]
Indeed I think we're likely just ignoring that flag. I labeled this as an "enhancement"  rather than a "bug" because we never intended `set_printoptions` to work, but it seems like a reasonable thing to add!

**Comment by samuela** [comment]
FWIW for others looking to do this I wrote this little function:
```python
from jax.tree_util import tree_map
import numpy as onp

def print_pytree(pytree):
  onp.set_printoptions(floatmode="unique")
  print(tree_map(onp.array, pytree))
  # maybe should reset to the previous config if that's your kinda thing
```

**Comment by NeilGirdhar** [comment]
@sam

**Comment by hawkinsp** [comment]
Are you confident there's actually a bug here? It seems to work fine for me. The two differences I see to the original colab are:
(a) one of the outputs seems to be stale.
(b) one of the numpy arrays is `float64` where the JAX version is `float32`.

**Comment by samuela** [comment]
@hawkinsp ah, it could be the float32 vs float64 difference...

**Comment by hawkinsp** [comment]
I can't reproduce. Feel free to reopen if you can!
