### ISSUE TITLE
Add VJP expm

### ISSUE THREAD

**Issue by LoicRaillon** [google/jax#3447]
The pull request #2062 implements the jvp of the matrix exponential by using the Fréchet derivative. I think the vjp can be easily added by transposing the input matrix in `expm_frechet`:
```python
defvjp(expm, lambda g, ans, matrix: expm_frechet(_T(matrix), g, compute_expm=False))
```
I can test and implement this solution if #2062 is merged.

**Comment by NeilGirdhar** [comment]
This is just a casual question, but what is the benefit of defining a vjp if there's already a jvp?  I thought that in this situation the vjp is synthesized by [transposition](https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html#Transposition)?

**Comment by LoicRaillon** [comment]
To my understanding, the vjp can't be synthesized by transposition because the jvp involves a `fori_loop`. I don't have the answer for your second question but I don't see why it's an issue to attach a custom jvp and vjp, its two different functions.

**Comment by LoicRaillon** [comment]
Indeed, it's not possible to define a `custom_vjp` and use the forward mode. What is the best strategy in this case?
- get rid off the forward mode?
- get rid off the `fori_loop`?
- define a new primitive?

**Comment by NeilGirdhar** [comment]
You should probably ping @mattjj?  I'm curious about this too.  How do you attach both a custom jvp and a custom vjp to a function?

**Comment by sriharikrishna** [comment]
When I was writing the rule for expm, I found that writing `custom_vjp` overwrites the `custom_jvp` and vice-versa. It would be nice to be able to have both.

**Comment by hawkinsp** [comment]
In the absence of the ability to define a custom transpose rule which allows JAX to derive the VJP from the JVP, I think the best bet for supporting both forward and reverse-mode autodiff is to upgrade `expm_frechet` into a first-class JAX primitive. This isn't much harder than the current `custom_jvp` approach, but would use internal APIs. See: https://jax.readthedocs.io/en/latest/notebooks/How_JAX_primitives_work.html

**Comment by LoicRaillon** [comment]
Thanks, I'll have a closer look at the primitives.

**Comment by bionicles** [comment]
```
import jax.numpy as jnp
import jax

rng = jax.random.PRNGKey(0)
x = jax.random.uniform(rng, (2, 2))

def f(x):
    y = jax.scipy.linalg.expm(x)
    credit = jnp.sum(jnp.abs(y))
    return credit, y

f = jax.value_and_grad(f)

f(x)
```

> ~/miniconda3/lib/python3.8/site-packages/jax/lax/lax_control_flow.py in _while_transpose_error(*_, **kwargs)
>     536 
>     537 def _while_transpose_error(*_, **kwargs):
> --> 538   raise ValueError("Reverse-mode differentiation does not work for "
>     539                    "lax.while_loop or lax.fori_loop. "
>     540                    "Try using lax.scan instead.")
> 
> ValueError: Reverse-mode differentiation does not work for lax.while_loop or lax.fori_loop. Try using lax.scan instead.

**Comment by zhangqiaorjc** [comment]
Reverse mode diff for expm should be supported now after https://github.com/google/jax/pull/4314
