### ISSUE TITLE
Path Manipulation

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/jax#3469]
https://github.com/google/jax/blob/575216e094ac55866320ae09dff4b05ef47fb7ea/build/build.py#L326
https://github.com/google/jax/blob/575216e094ac55866320ae09dff4b05ef47fb7ea/build/build.py#L329

Allowing user input to control paths used in file system operations could enable an attacker to access or modify otherwise protected system resources

**Comment by jakevdp** [comment]
Since this is a build file, this is working as intended.
