### ISSUE TITLE
Command Injection

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/jax#3470]
https://github.com/google/jax/blob/575216e094ac55866320ae09dff4b05ef47fb7ea/build/build.py#L326
https://github.com/google/jax/blob/575216e094ac55866320ae09dff4b05ef47fb7ea/build/build.py#L371
https://github.com/google/jax/blob/575216e094ac55866320ae09dff4b05ef47fb7ea/build/build.py#L375
https://github.com/google/jax/blob/575216e094ac55866320ae09dff4b05ef47fb7ea/build/build.py#L47

Executing commands from an untrusted source or in an untrusted environment can cause an application to execute malicious commands on behalf of an attacker.

**Comment by jakevdp** [comment]
Since this is a build file, this is working as intended.
