### ISSUE TITLE
Unexpected / Inconsistent behaviour for out-of-bounds access

### ISSUE THREAD

**Issue by thomaskeck** [google/jax#3493]
JAX outputs hard to debug error-messages in some situation if an array is accessed out-of-bounds.
I created a minimal example illustrating the issues:

```
import jax 
import jax.numpy as jnp

def loss(params, obs):
  network_output = params * obs # Network output has shape [4, 10]
  network_output = network_output[20]  # Bug! 20 is out-of-bounds
  # Weird stop-gradient is required to trigger the error.
  loss = jnp.sum(jax.lax.stop_gradient(params[0]) * network_output)
  return loss

def update(params, obs):
  grad = jax.grad(loss)(params, obs)
  return params + grad

params = jnp.ones((10,))
obs = jnp.ones((4, 10))
```

If I run the code without jit compiling, it actually works because JAX does not raise an error on out-of-bound accesses (see https://github.com/google/jax/issues/1451).
`update(params, obs)`

But if I jit compile it I do get an error, but a very hard to interpret one:
`jax.jit(update)(params, obs)`

> 
> RuntimeError: Internal: Expected instruction to have shape equal to f32[21,10]{1,0}, actual shape is f32[4,10]{1,0:T(4,128)}:
> %pad.6 = f32[4,10]{1,0:T(4,128)} pad(f32[1,10]{1,0:T(2,128)} %param_1.12, f32[]{:T(256)} %constant.54), padding=20_0x0_0, metadata={op_type="scatter-add" op_name="jit(update)/scatter-add[ dimension_numbers=ScatterDimensionNumbers(update_window_dims=(0,), inserted_window_dims=(0,), scatter_dims_to_operand_dims=(0,))\n                         update_consts=() ]" source_file="<ipython-input-23-acf08795557d>" source_line=6}

I only get the error if I have the stop-gradient piece in the loss-function.
Honestly, I don't know what the expected behavior should be, but I figured I report it anyway, since the behavior seems to be inconsistent.

Ideally jax would raise always an error on out-of-bound access, or alternatively throw an error without jit as well. But the current situation makes this kind of bug incredibly hard to debug (since it only shows up with jit).

**Comment by mattjj** [comment]
Thank you so much for reporting this! I think there might be a couple things going wrong here. We must improve it!

**Comment by jakevdp** [comment]
It looks like this has been fixed, in that there is no longer an inscrutable error. out-of-bound indices are clipped by default; see https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#out-of-bounds-indexing
