### ISSUE TITLE
parallelize a loop like Numba's prange

### ISSUE THREAD

**Issue by docyyz** [google/jax#3534]
Hi, 

I have the follow code, which I'd like to parallelize over the for loop.  This can be done quite easily using Numba's prange.  Is there something of an equivalent in JAX?
```python
grad_jit = jit(grad(func), static_argnums=[1])
grad_out = np.zeros((n,m,k),dtype=np.float32)
for i in range(n):
    din = de_noise(raw_input[i])
    grad_out[i]=grad_jit(din,params)
```

**Comment by jakevdp** [comment]
Not exactly... what jax provides are mapping transforms (`pmap` and `vmap`) which will transform your function into something that does the loop implicitly. For your function, this is how you would compute `grad_out` via a vmapped function:
```
mapped_grad = vmap(grad(func), (0, None),)
grad_out = mapped_grad(raw_input, params)
```
THe details of `pmap` are slightly different, but it is a similar idea.

**Comment by mattjj** [comment]
Using `vmap` amounts to pushing the parallelism down into every primitive operation, while using `pmap` keeps it at the top level; that is, `pmap` is the closest thing to `prange`. However, `pmap` parallelizes over XLA devices, most commonly used for multiple GPUs or multiple TPU cores. On CPU, you'd need to set the environment variable `XLA_FLAGS=--xla_force_host_platform_device_count=8` or similar to present your multi-core CPU as separate XLA devices.

**Comment by mattjj** [comment]
Concretely, here's how you could write and execute something like this on CPU:

```python
import jax.numpy as jnp
from jax import pmap, grad

@pmap
def process(row_in):
  din = de_noise(row_in)
  grad_out = grad(func)(din)
  return grad_out

# dummy functions and data
de_noise = lambda x: x / 3.
func = lambda x: jnp.sum(x ** 2)
raw = jnp.arange(40).reshape(4, 10)  # 4 sequences of length 10 each

result = process(raw)
```

```
XLA_FLAGS=--xla_force_host_platform_device_count=8 python issue3534.py
```

Notice that we're not pre-allocating an output and then doing in-place updating assignments into it. JAX's programming model is functional!

Multithreading like this isn't really the main intended use case of `pmap` though, as you might guess from the need to set the environment variable; its main purpose is to parallelize over hardware accelerators, and to leave any parallel evaluation on each accelerator up to XLA.

I think this covers the question so I'm going to close this issue, but please don't hesitate to open new ones with new questions!
