### ISSUE TITLE
Forward mode differentiation of `odeint` is not supported, but it does not give an error

### ISSUE THREAD

**Issue by john-m-jumper** [google/jax#3558]
```
def f(k):
  return ode.odeint(lambda x, t: k*x, 1.,  jnp.linspace(0, 1., 50)).sum()
jax.jacfwd(f)(3.)
```
should fail with an error since jvp of `odeint` is not supported, but it returns a value anyway.

**Comment by mattjj** [comment]
Cross-ref to #3557 also: one reason this error isn't raised is that we don't detect the closed-over tracer in the dynamics function.

**Comment by froystig** [comment]
#2718 requests support for closure under `odeint`, and describes a related issue with how it is caught in the meantime.

**Comment by mattjj** [comment]
In a funny way, this is accidentally doing the right thing, even though I told @john-m-jumper it wouldn't!

```python
import jax
from jax.experimental import ode
import jax.numpy as jnp

def f(k):
  return ode.odeint(lambda x, t: k*x, 1.,  jnp.linspace(0, 1., 50)).sum()
print(jax.jacfwd(f)(3.))
print((f(3.+1e-6) - f(3.-1e-6)) / 2e-6)
```

```
$ env JAX_ENABLE_X64=1 python issue3558.py
234.33132392618268
234.33132375316745
```

It's kind of funny: `odeint` has a custom vjp rule, and usually when one has a custom vjp rule that means we can't use forward-mode with it. however, `odeint` also isn't set up to detect closed-over tracers in the dynamics function. As a result, the tracer on `k` is eluding odeint's custom vjp rule, but that means it just gets into odeint's implementation, which is all implemented in terms of while_loops and things that are themselves forward-mode differentiable. So it all just works out!

We should not close this bug yet though; we want to make sure this keeps working when we resolve #3557 / #2718 , and moreover make sure forward-mode works like this even without smuggling a tracer in via closure.

**Comment by mattjj** [comment]
After merging #3562, now we get an error here:

```
NotImplementedError: Batching rule for 'custom_lin' not implemented
```

That's a bad error message, but it makes sense: it's essentially from doing forward-mode on a function with a custom VJP.

At least two possible directions to go:
1. make forward-mode work with custom vjp functions, perhaps ignoring the custom rule and just tracing through the function; or
2. improve the error message.

**Comment by mattjj** [comment]
Well, since this issue is about the error message, let's start with fixing that and we can see about making it work afterward! #3566 should get it.
