### ISSUE TITLE
CUDA issues

### ISSUE THREAD

**Issue by ericmjl** [google/jax#3568]
When trying to use JAX + GPU in a CentOS8 container, I have the following warning message show up:

```python
>>> import jax.numpy as np
>>> a = np.ones(4)
2020-06-26 10:14:51.996044: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:314] failed call to cuInit: CUDA_ERROR_SYSTEM_DRIVER_MISMATCH: system has unsupported display driver / cuda driver combination
2020-06-26 10:14:51.996405: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_diagnostics.cc:313] kernel version 440.36.0 does not match DSO version 440.33.1 -- cannot find working devices in this configuration
/home/docker/anaconda/envs/my-project/lib/python3.7/site-packages/jax/lib/xla_bridge.py:125: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
```

When in the container, the output of `nvidia-smi` is:

```
(base) [docker@4d16b48b1a22 ~]$ nvidia-smi
Fri Jun 26 10:14:29 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.36       Driver Version: 440.36       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
|  0%   25C    P8    12W / 250W |    318MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

The Dockerfile specification is [available as a gist here](https://gist.github.com/ericmjl/2db8a3880b1b475e3b9f3a13b9757b8b).

I have tried asking around on Twitter some friends at NVIDIA. It seems like the host driver is 440.36, but when I install the CUDA toolkit, the version that gets installed is 440.33, resulting in the DSO version error. I am working under the assumption that I can't change the host driver, so I'm stuck with whatever I can get into the container. Have you all encountered this issue before? Is there someone on the team who has experience with XLA + CUDA?

**Comment by hawkinsp** [comment]
I don't think this is an XLA or JAX issue in particular, it sounds to me like the docker file needs fixing. Do any CUDA programs work in this configuration (e.g., say TF or PyTorch)? I'm not sure there's much we can do here; is there a way you can install the matching CUDA toolkit version in the docker configuration?

**Comment by ericmjl** [comment]
I'm not sure, but I did get a pingback from the NVIDIA folks pointing me to how their containers are built. It's exactly what I needed! https://gitlab.com/nvidia/container-images/cuda/-/blob/master/dist/10.2/centos8-x86_64/runtime/cudnn7/Dockerfile

I'm going to close the issue so it doesn't clutter up the issue tracker :smile:.
