### ISSUE TITLE
Question on importing pytree object

### ISSUE THREAD

**Issue by DarrenZhang01** [google/jax#3577]
From my observation, the pytree object is defined under [https://github.com/google/jax/blob/master/jaxlib](https://github.com/google/jax/blob/master/jaxlib) and is initialized in [https://github.com/google/jax/blob/master/jax/lib/\_\_init\_\_.py](https://github.com/google/jax/blob/master/jax/lib/__init__.py). If I want to import pytree object independently in my python file, what helper files do I also need to include? (I assume [https://github.com/google/jax/blob/master/jaxlib/pytree.cc](https://github.com/google/jax/blob/master/jaxlib/pytree.cc)) Thanks!

**Comment by froystig** [comment]
See the docs for [pytrees](https://jax.readthedocs.io/en/latest/pytrees.html) and for [`jax.tree_util`](https://jax.readthedocs.io/en/latest/jax.tree_util.html) as the typical package to import.

As mentioned in the docs, this is an internal library. We don't maintain it for external use, it can change without warning, etc. A similar standalone library such as [dm-tree](https://github.com/deepmind/tree) is worth a look for use outside of jax internals.
