### ISSUE TITLE
random uniform with dtype bfloat16 crashes on TPU backend

### ISSUE THREAD

**Issue by levskaya** [google/jax#3594]
repro:
```
from jax import numpy as jnp
from jax import random
x = random.uniform(random.PRNGKey(0), (3,), dtype=jnp.bfloat16)
```
observation:
 - crashes on TPU backends (both internal and cloud TPU as far as I can tell)
 - CPU and GPU backends don't seem to crash

expect:
even if bfloat16 isn't supported by random.* on TPU it would be better to error-out rather than crashing

**Comment by hawkinsp** [comment]
Google internal bug b/156977343.

**Comment by hawkinsp** [comment]
I should add that it would be possible to workaround this bug by avoiding U16/S16 types on the JAX side. Since we have larger integer types available (U32, S32) this is possible if slightly annoying to do.

**Comment by majnemer** [comment]
I think this should work now.

**Comment by mattjj** [comment]
Thanks, @majnemer! I just double-checked on an internal TPU colab and indeed it works. Thanks to your team for the fix.
