### ISSUE TITLE
Explicitly document Python overhead in JAX computations.

### ISSUE THREAD

**Issue by inoryy** [google/jax#3595]
Often newcomers get confused by JAX's relative performance to NumPy on CPU when using smaller arrays even after using jit.
AFAIK most of this can be explained away by the overhead of dispatching JAX computations from Python which does non-trivial amount of work even when jitted. Currently, description of this extra work is scattered across the docs and some is only apparent after exploring the source code or xprof traces. Would be great if it were succinctly listed somewhere, perhaps in the sharp bits.

**Comment by cloudhan** [comment]
I made a simple comparison (on light workload) with PyTorch, it is 2 order of magnitude slower.

https://colab.research.google.com/drive/1nwjiNsKDBWsbLskEMnB7lMRpUky3UjQs?usp=sharing

**Comment by hawkinsp** [comment]
@cloudhan Note that if you apply `jax.jit` to your `train_step` function, jax is faster than PyTorch (on CPU in Colab).

In general JAX is much more optimized for the case where you `jit` larger blocks of code.

**Comment by cloudhan** [comment]
@hawkinsp that improvement is surprising. I updated that notebook.

**Comment by jakevdp** [comment]
There's some better documentation on this these days: https://jax.readthedocs.io/en/latest/faq.html#is-jax-faster-than-numpy
