### ISSUE TITLE
Improve error message w/ incorrect out_axes argument to vmap

### ISSUE THREAD

**Issue by tgale96** [google/jax#3613]
[This colab](https://colab.research.google.com/drive/1DWziQYqL-tiZHvtSiCz8QJlQtkTSqlq8?usp=sharing) shows an incorrect use of vmap where more `out_axes` arguments are passed than the number of outputs in the mapped function. The error message does not indicate that the issue is with the `out_axes` argument, as opposed to the `in_axes` argument. It would be nice to improve this so that it's clear where the issue is.

**Comment by IgorWilbert** [comment]
@mattjj @tgale96 it seems to be pretty easy to pass a boolean flag `is_in_axes` to the function below to create a custom error message for `in_axes` and `out_axes`. However, it seems a bit naive and could make usage of this function cumbersome.
https://github.com/google/jax/blob/e808681f6c096e95be8532e4e901f5d410e0fb58/jax/api_util.py#L146

**Comment by mattjj** [comment]
@IgorWilbert That line of thinking sounds right to me! Perhaps we can just pass in a string that gets included in the error message; we've used that pattern before and it seems too work out.

I really appreciate your thoughts and advice around here!
