### ISSUE TITLE
shape hint arguments in lax numpy functions to enable compilation

### ISSUE THREAD

**Issue by froystig** [google/jax#3614]
Several functions in `jax.numpy` are not `jit`-compilable for shape-level arguments. Specifically, we can't decide their output shape from input shapes alone.

We've given [`jax.numpy.bincount`](https://github.com/google/jax/blob/db8f66d508d536e1312291ba966905ddf910582d/jax/numpy/lax_numpy.py#L1309) an optional `length` argument that's not in standard numpy because it determines the output shape (when it is static/concrete). It's not uncommon for callers to have this information on hand.

We could consider extending other functions similarly to accept optional shape hints:
- [x] argwhere (#6915)
- [x] compress (#21090)
- [x] extract (#21090)
- [x] nonzero (#6501 #7592)
- [x] flatnonzero (#6913)
- [x] 1-argument where (#6910)
- [x] repeat (#3670)
- [x] unique (#6912, #8121, #8186)
- [x] setdiff1d (#8144)
- [x] union1d (#6930, #8143)
- [x] intersect1d (#22979)
- [ ] setxor1d (#23020)

**Comment by shoyer** [comment]
For something like `unique`, what would the other elements of the result be filled with if not unique values? It seems like we probably would need to add another parameter for indicating the `fill_value`.
