### ISSUE TITLE
public interface for partial evaluation 

### ISSUE THREAD

**Issue by froystig** [google/jax#3617]
Alternatives to consider, not exhaustive:

1. Based on `interpreters.partial_eval`, provide partial evaluation of a function (i.e. `Callable`).
2. Support partial evaluation of jaxprs only.
3. Continue to provide no partial evaluation interface.

The second could be obtained from the first, but could also be written as a standalone jaxpr interpreter.

This has been requested a few times, so this issue is for discussion as much as it is about any related changes.

**Comment by mattjj** [comment]
No! :)

**Comment by froystig** [comment]
One answer to such a request today would be to write a jaxpr interpreter for any particular partial eval need. This can (mostly) be done using `jax.extend.core`.

**Comment by chaserileyroberts** [comment]
Is this not already handled by `jax.extend.core.jaxpr_as_fun`?

**Comment by froystig** [comment]
That'll do "eval," without any option for "partial." But a custom interpreter is easy enough to put together.
