### ISSUE TITLE
[jax2tf] Incorrect out of bound index handling for lax.dynamic_slice

### ISSUE THREAD

**Issue by tberghammer** [google/jax#3621]
To reproduce, add the following test to jax/experimental/jax2tf/tests/primitives_test.py:
```
def test_dynamic_slice_oob(self):
    v = np.array([1, 2])
    f_jax = jax.jit(lambda a: lax.dynamic_slice(a, [5], [1]))
    self.ConvertAndCompare(f_jax, v)
```

The issue is that dynamic_slice have clamping behaviour for the indices but when we translate it into a tf.slice we lose this behaviour so it will assert during tf2xla translation due to the out of bound index.

The two solution I see is either to clamp the index during translation so we can use tf.slice (and hope that it won't impact performance too much) or use tfxla.dynamic_slice what has the clamping semantics.

**Comment by gnecula** [comment]
I wonder what are the operators with index clamping semantics: gather, scatter, dynamic_slice.

**Comment by tberghammer** [comment]
I think any operator what takes an index as a runtime argument what should be:
gather, scatter, dynamic_slice, dynamic_update_slice

**Comment by majnemer** [comment]
Can scatter ignore out of bound indices?

**Comment by gnecula** [comment]
> Can scatter ignore out of bound indices?

This is what lax.scatter seems to do, so this is what the translation should achieve too.
