### ISSUE TITLE
How to select the jax  release version

### ISSUE THREAD

**Issue by XDongiang** [google/jax#3622]
Taking a look again, it looks to me like this issue is resolved at head.

My version of the benchmark looks like this:
```
from jax import device_put
import numpy as onp
import jax.numpy as np
from jax import vmap
from functools import partial
import time
from jax import jit
from jax import grad

def invm_plus(Pb,Pc):
    Pbc = Pb + Pc
    _Pbc = Pbc * np.array([-1,-1,-1,1])
    return np.sum(Pbc * _Pbc,axis=1)

def invm(Pbc):
    _Pbc = Pbc * np.array([-1,-1,-1,1])
    return np.sum(Pbc * _Pbc,axis=1)

def BW(m_,w_,Sbc):
    i = complex(0,1)
    gamma=np.sqrt(m_*m_*(m_*m_+w_*w_))
    k = np.sqrt(2*np.sqrt(2)*m_*np.abs(w_)*gamma/np.pi/np.sqrt(m_*m_+gamma))
    return k/(m_*m_ - Sbc - i*m_*w_)

def phase(theta, rho):
    i = complex(0,1)
    return rho * np.exp(theta*i)

def _abs(bw_):
    conjbw = np.conj(bw_)
    return np.real(bw_*conjbw)

Kp = onp.random.sample(80000*4).reshape(80000,4)
Km = onp.random.sample(80000*4).reshape(80000,4)
Pip = onp.random.sample(80000*4).reshape(80000,4)
Pim = onp.random.sample(80000*4).reshape(80000,4)
phif001 = onp.random.sample(80000*2).reshape(80000,2)
phif021 = onp.random.sample(80000*2).reshape(80000,2)

phif0 = np.asarray([phif001,phif021])
phi = invm_plus(Kp,Km)
f0 = invm_plus(Pip,Pim)

phim = np.array([2.,1.,1.,1.,2.,1.,1.,1.])
phiw = np.array([1.,2.,1.,1.,2.,1.,1.,1.])
f0m = np.array([1.,1.,1.,3.,1.,1.,1.,1.])
f0w = np.array([1.,1.,1.,1.,1.,1.,1.,1.])
const = np.array([[2.,1.,1.,1.,1.,1.,1.,1.],[1.,1.,1.,1.,1.,1.,1.,1.]])
rho = np.array([1.,1.,2.,1.,1.,1.,1.,1.])
theta = np.array([1.,1.,1.,1.,3.,1.,3.,1.])


def BW_f0(phim,phiw,f0m,f0w,phi,f0):
    return vmap(partial(BW,Sbc=phi))(phim,phiw) * vmap(partial(BW,Sbc=f0))(f0m,f0w)

def phase_f0(theta_,rho_):
    result = vmap(phase)(theta_,rho_)
    return result

def test_pw(phim,phiw,f0m,f0w,const,rho,theta,phif0,phi,f0):
    ph = phase_f0(theta,rho)
    bw = BW_f0(phim,phiw,f0m,f0w,phi,f0)
    const_phase = np.einsum('ij,j->ij',const,ph)
    _phif0 = np.einsum('ijk,il->ljk',phif0,const_phase)
    _phif0 = np.einsum('ijk,ij->jk',_phif0,bw)
    _phif0 = np.real(np.sum(_abs(_phif0),axis=1))
    return -np.sum(np.log(_phif0))

test_pw_jit = jit(test_pw)

print(test_pw_jit(phim,phiw,f0m,f0w,const,rho,theta,phif0,phi,f0))

m = (0,1,2,3,4,5,6)
grad_test_pw = jit(grad(test_pw_jit,argnums=m))
_ = grad_test_pw(phim,phiw,f0m,f0w,const,rho,theta,phif0,phi,f0)[0].block_until_ready()
s = time.time()
print(grad_test_pw(phim,phiw,f0m,f0w,const,rho,theta,phif0,phi,f0))
e = time.time()
print("time : ", e - s)

def test_pw1(phim,phiw,f0m,f0w,theta,rho,const,phif001,phif021,phi,f0):
    temp = np.zeros(80000)
    for i in range(8):
        bw = BW(phim[i],phiw[i],phi) * BW(f0m[i],f0w[i],f0)
        _phif001 = phif001.T * bw *const[0,i]
        _phif021 = phif021.T * bw *const[1,i]
        _phif0 = (_phif001 + _phif021) * phase(theta[i],rho[i])
        temp = temp + _phif0
    data = np.real(np.sum(_abs(temp),axis=0))
    return -np.sum(np.log(data))

grad_test_pw1 = jit(grad(test_pw1,argnums=m))

#print(test_pw1_jit(phim,phiw,f0m,f0w,theta,rho,const,phif001,phif021,phi,f0))
_ = grad_test_pw1(phim,phiw,f0m,f0w,theta,rho,const,phif001,phif021,phi,f0)[0].block_until_ready()
s = time.time()
print(grad_test_pw1(phim,phiw,f0m,f0w,theta,rho,const,phif001,phif021,phi,f0))
e = time.time()
print("time : ", e - s)
```

Both versions seem roughly equal in performance, around 4-5ms on a P100.

_Originally posted by @hawkinsp in https://github.com/google/jax/issues/1763#issuecomment-614885455_

Please tell me the JAX version you are using.
Is the version of cuda and cudnn matter?

**Comment by hawkinsp** [comment]
I'd suggest using the current `jaxlib` (0.1.50) and `jax` (0.1.72). I don't think the CUDA/CuDNN versions matter that much. Hope that helps!

**Comment by XDongiang** [comment]
> I'd suggest using the current `jaxlib` (0.1.50) and `jax` (0.1.72). I don't think the CUDA/CuDNN versions matter that much. Hope that helps!

Thank you 
I am using the jax(0.1.55)  and jaxlib(0.1.36) in docker . I will build a new docker use the new version jax and jaxlib. Is there any docker image in the dockerhub ?

**Comment by hawkinsp** [comment]
I'm sorry we don't provide docker images at the moment. Our supported installation instructions use `pip` wheels: https://github.com/google/jax#installation

**Comment by XDongiang** [comment]
I want use complex in my function , but i do not know the faster method to use complex in jax.
please give me some help . 
In python I can creat complex by use ``` i = complex(0,1) ```,  I don't know if it affects performance

**Comment by hawkinsp** [comment]
For general questions about JAX, I suggest using the new "Discussions" tab on Github rather than using issues.

For your specific question, you can either form Python complex numbers using `complex` as you state, although that probably won't work if the arguments are numpy arrays, only Python literals. I usually just write `x + y * 1j` or similar, and that works fine with JAX arrays `x` and `y`.

**Comment by XDongiang** [comment]
> For general questions about JAX, I suggest using the new "Discussions" tab on Github rather than using issues.
> 
> For your specific question, you can either form Python complex numbers using `complex` as you state, although that probably won't work if the arguments are numpy arrays, only Python literals. I usually just write `x + y * 1j` or similar, and that works fine with JAX arrays `x` and `y`.

Sorry , i will follow the questioning rules in my future questions
In python I can creat complex by use ``` i = complex(0,1) ```,  I don't know if it affects performance.
And jax.xla.complex also can creat a complex , what is the difference between them
