### ISSUE TITLE
No details in tensorboard trace profile

### ISSUE THREAD

**Issue by AdrienCorenflos** [google/jax#3640]
Hi,

I'm following the profiling guidelines using tensorboard, but it really doesn't show any details in the trace: https://ibb.co/C7grDt8

Do you know what I could be doing wrong?

Thanks,

Adrien

**Comment by hawkinsp** [comment]
Is this on CPU or GPU? The tracing only really shows anything interesting at the moment on GPU.

**Comment by AdrienCorenflos** [comment]
CPU yes. So that includes my personal tracing

**Comment by AdrienCorenflos** [comment]
CPU yes. So that includes my personal tracing?

**Comment by skrsna** [comment]
Hi, 
There's a typo in the docs for profiling at `jax/docs/profiling.md` which gives 404 error for tensorboard. I think there's an extra `>` in the link for [TensorBoard's profiler](https://www.tensorflow.org/tensorboard/tensorboard_profiling_keras). I didn't wanna open an extra issue just for that and sorry for spamming here.

**Comment by skye** [comment]
I think the 404 is fixed. Please feel free to open a new issue even for small issues like this!

**Comment by mattjj** [comment]
I suspect this is stale!
