### ISSUE TITLE
FAILED: Build did NOT complete successfully

### ISSUE THREAD

**Issue by ElhamSol** [google/jax#3655]
I'm trying to build JAX from the source on ubuntu 18, cuda 10.1, cudnn7.6

I followed the steps here https://jax.readthedocs.io/en/latest/developer.html#building-from-source

But the build fails  after `sudo python3 build/build.py --enable_cuda` or even `sudo python3 build/build.py`

Could you help me resolve this issue? My computer knowledge is very limited (not from computer eng. background) :)

```
Target //build:install_xla_in_source_tree failed to build
INFO: Elapsed time: 742.118s, Critical Path: 113.95s
INFO: 4271 processes: 4271 local.
FAILED: Build did NOT complete successfully
ERROR: Build failed. Not running target
FAILED: Build did NOT complete successfully
Traceback (most recent call last):
  File "build/build.py", line 382, in <module>
    main()
  File "build/build.py", line 377, in main
    shell(command)
  File "build/build.py", line 47, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['./bazel-2.0.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=short_logs', '--config=opt', '--config=mkl_open_source_only', '--config=cuda', '--define=xla_python_enable_gpu=true', ':install_xla_in_source_tree', '/home/mibcat01/jax/build']' returned non-zero exit status 1.
```

**Comment by mattjj** [comment]
I think the real underlying error message is reported somewhere else in the traceback; the part you pasted seems to just report that something went wrong in a sub-command, but it doesn't say what.

Can you share a more complete traceback?

**Comment by aldragan0** [comment]
I'm having the same issue.
[build.log](https://github.com/google/jax/files/4873627/build.log)

**Comment by ElhamSol** [comment]
> I think the real underlying error message is reported somewhere else in the traceback; the part you pasted seems to just report that something went wrong in a sub-command, but it doesn't say what.
> 
> Can you share a more complete traceback?

Well there was an error with numpy, I resolved it. Now the log looks like this:
[mybuild1.txt](https://github.com/google/jax/files/4879820/mybuild1.txt)

**Comment by gnecula** [comment]
I saw 
```
find: ë/usr/include/python3.7mí: No such file or directory
```
Is there a problem with your Python installation? Are you using a virtualenv?

**Comment by hawkinsp** [comment]
@aldragan0 I reproduced your issue, but as far as I can tell it may not be the same as @ElhamSol 's issue. Can you open a separate issue?

**Comment by ElhamSol** [comment]
> I saw
> 
> ```
> find: ë/usr/include/python3.7mí: No such file or directory
> ```
> 
> Is there a problem with your Python installation? Are you using a virtualenv?

I tried to re-install it.
Now for cuda:
[mybuildCUDA.txt](https://github.com/google/jax/files/4879964/mybuildCUDA.txt)

And for cpu only:
[mybuildCPU.txt](https://github.com/google/jax/files/4879965/mybuildCPU.txt)

**Comment by hawkinsp** [comment]
Great! That's easy to fix. I have a fix coming. It seems to be something related to Ubuntu 18.04 specifically.

@aldragan0 Never mind, they are the same issue.

**Comment by ElhamSol** [comment]
> Great! That's easy to fix. I have a fix coming. It seems to be something related to Ubuntu 18.04 specifically.
> 
> @aldragan0 Never mind, they are the same issue.

Great thanks!

**Comment by aldragan0** [comment]
> Great! That's easy to fix. I have a fix coming. It seems to be something related to Ubuntu 18.04 specifically.
> 
> @aldragan0 Never mind, they are the same issue.

Thank you!

**Comment by hawkinsp** [comment]
#3671 should have fixed this.

**Comment by ElhamSol** [comment]
> Great! That's easy to fix. I have a fix coming. It seems to be something related to Ubuntu 18.04 specifically.
> 
> @aldragan0 Never mind, they are the same issue.

Which version of Ubuntu is now working without an issue?

**Comment by hawkinsp** [comment]
I'm not aware of any open problems.
