### ISSUE TITLE
broken link from pytree_util api docs to 'pytrees notebook'

### ISSUE THREAD

**Issue by bionicles** [google/jax#3662]
the bottom of the top introduction on this page:
https://jax.readthedocs.io/en/latest/jax.tree_util.html

reads: 

> See the [JAX pytrees notebook](https://jax.readthedocs.io/en/latest/notebooks/JAX_pytrees.html) for examples.

(this is written here: https://github.com/google/jax/blob/269da0ae584cfe840f34e9f871f13c28e2772de5/jax/tree_util.py#L34)

is this the correct link? or are we missing a notebook?
https://jax.readthedocs.io/en/latest/pytrees.html

just curious because tree_util is my new favorite thing...

**Comment by gnecula** [comment]
Thank for catching this, we had turned the pytree notebook into a [note](https://jax.readthedocs.io/en/latest/pytrees.html). 

Fix underway!
