### ISSUE TITLE
Rename jax.nn.swish to jax.nn.silu to give appropriate credit

### ISSUE THREAD

**Issue by TFUsers** [google/jax#3672]
The swish was originally coined the "SiLU" in https://arxiv.org/pdf/1606.08415.pdf and https://arxiv.org/abs/1702.03118 long before the swish paper. Renaming other peoples' exact same ideas is unacceptable and tensorflow's naming convention implicitly erases the research and work of people outside of Google.
This request inspired by a [recent discussion](https://www.reddit.com/r/MachineLearning/comments/hkiyir/r_google_has_a_credit_assignment_problem_in/) and a recent [tensorflow issue](https://github.com/tensorflow/tensorflow/issues/41066), but this problem has been brought up every few months for the past few years. In light of recent efforts to make the ML community more equitable and _fair_, this is a no-brainer and long overdue.

**Will this change the current api? How?**
jax.nn.swish will eventually be deprecated (jax is still new) and jax.nn.silu will be added and both of the aforementioned papers will be cited in the documentation.

**Comment by hawkinsp** [comment]
Thanks for raising this issue. We can't easily remove an existing name without breaking users, but we can rename `swish` to `silu` and have `swish` be an alias for `silu`. #3673 does this.
