### ISSUE TITLE
Convert array to DeviceArray?

### ISSUE THREAD

**Issue by SamuelMarks** [google/jax#3677]
IIRC, it's not possible to do a direct conversion/promotion/memory-mapping/move.

I've tried replacing all imports from `import numpy as np` to `import jax.numpy as jnp`, but I'm still calling `as_numpy` or `numpy` on something produced by TensorFlow, which naturally doesn't use the type I want.

Maybe I could monkeypatch numpy on the module hierachy?

Or is there actually a direct way to turn a `tf.Tensor`—or `np.ndarray`—to a `DeviceArray`?

**Comment by mattjj** [comment]
Thanks for the question!

Using [`jax.device_put`](https://jax.readthedocs.io/en/latest/jax.html#jax.device_put) is how to turn a `numpy.ndarray` into a `DeviceArray`. You can use [JAX's DLPack support](https://jax.readthedocs.io/en/latest/jax.dlpack.html) to get zero-copy interfacing with PyTorch, and perhaps also with TF. On CPU JAX might already share memory with NumPy; I don't remember if there are still any extra copies involved (@hawkinsp would know).

The second line of your message makes me think you might be asking about some specific TF interop. Could you share a small runnable example which we can talk about concretely?

**Comment by SamuelMarks** [comment]
Thanks that did the trick, made the change here:
https://github.com/SamuelMarks/ml-params/commit/1f5650f
