### ISSUE TITLE
`JaxprTracer` Object

### ISSUE THREAD

**Issue by DarrenZhang01** [google/jax#3681]
Hi, could anyone explain to me about the `<class 'jax.interpreters.partial_eval.JaxprTracer'>` object defined in [https://github.com/google/jax/blob/master/jax/interpreters/partial_eval.py](https://github.com/google/jax/blob/master/jax/interpreters/partial_eval.py)? Thanks!

**Comment by jakevdp** [comment]
Hi - a tracer object is a special kind of object that is used in jax transforms in place of an array, to record the effect of a function on its inputs. We don't currently have very detailed documentation on how custom transforms are defined, but the simplest one is probably the callback transform: https://github.com/google/jax/blob/master/jax/experimental/callback.py

Does that answer your question?

**Comment by DarrenZhang01** [comment]
> Hi - a tracer object is a special kind of object that is used in jax transforms in place of an array, to record the effect of a function on its inputs. We don't currently have very detailed documentation on how custom transforms are defined, but the simplest one is probably the callback transform: https://github.com/google/jax/blob/master/jax/experimental/callback.py
> 
> Does that answer your question?

Thanks for the reply, Jake. Then how to retrieve the ShapedArray inside a `JaxprTracer` object and convert it into a vanilla Numpy array?

**Comment by mattjj** [comment]
ShapedArrays just carry shape information, not values, so you can't turn one into a numpy ndarray. (Also, JaxprTracers don't always have ShapedArrays inside, but could have arrays at different abstraction levels like ConcreteArray or UnshapedArray.)

This is all deep into JAX internals, and so anything built relying on these kinds of JAX implementation details is likely to break as we constantly revise JAX.

Can you say a bit about what led you to look at this stuff, and what you're trying to do?

**Comment by DarrenZhang01** [comment]
> ShapedArrays just carry shape information, not values, so you can't turn one into a numpy ndarray. (Also, JaxprTracers don't always have ShapedArrays inside, but could have arrays at different abstraction levels like ConcreteArray or UnshapedArray.)
> 
> This is all deep into JAX internals, and so anything built relying on these kinds of JAX implementation details is likely to break as we constantly revise JAX.
> 
> Can you say a bit about what led you to look at this stuff, and what you're trying to do?

Hi Matthew! I am in the midway of reconstructing and migrating Neural Tangents from the JAX support into TF 2.x. support, as an R&D project for the TensorFlow team. In the Neural Tangent Kernel initialization step in `stax.py`, some rng key inputs appear to be the JAX Tracer type when running `stax_tests.py`. I am currently trying to replace the `random` support (including the rng key initialization) in `stax_tests.py` and see if the problem will disappear.

[https://github.com/DarrenZhang01/TensorFlow_GSoC/blob/master/neural-tangents/neural_tangents/stax.py#L410](https://github.com/DarrenZhang01/TensorFlow_GSoC/blob/master/neural-tangents/neural_tangents/stax.py#L410)

**Comment by mattjj** [comment]
Thanks for explaining!

When values have that type, it's indicative that there's a `jax.jit` tracing the function. It's essentially like having a `tf.function` decorating the code. If you remove any `jit`s I believe these tracers will disappear.

**Comment by DarrenZhang01** [comment]
Thanks very much, Matthew!
