### ISSUE TITLE
help understanding OOM behavior

### ISSUE THREAD

**Issue by martinjankowiak** [google/jax#3687]
thanks for the wonderful package!

**context:** 
i'm writing custom derivatives for various expressions, e.g. quadratic forms like a^T M^{-1} b. this can use a lot of memory when the dimension(s) gets large. luckily, the needed computation is a sequence of various kinds of tensor contractions, each of which is, at least in principle, easy to partition into smaller subcomputations. so, e.g., in doing a matrix vector multiply i can form moderately sized subsets of the rows and do a moderate number of dot products instead of realizing the entire matrix first.

**my attempt**:
to implement partitioning i've generally used the following simple device. i implement a `chunk_vmap` function that has the same semantics as `vmap`, except that it breaks the computation into the pattern `for loop` + `vmap`. e.g. i do something like
```
result = np.concatenate([vmap(f)(chunk) for chunk in chunks])
```

**outcome**:
while doing this sort of works in that it increases the critical dimension at which i start getting OOM errors, it only increases that dimension moderately (even if if use small chunks), certainly less than i would expect from counting nominal memory usage for various partitioned tensors ops.

**hypotheses**:
-  XLA is fusing operators that i don't want fused and this leads to larger than expected memory usage and thus OOM errors
- my partitioning is effectively undone when jax does invokes linearization or whatever other manipulations it invokes on my `tangent_out`
- asynchronous dispatch is causing lots of expensive ops to be executed simultaneously, leading to OOM errors that wouldn't arise if the ops were executed sequentially

any suggestions for how i might do partitioning in a way that avoids OOM errors? of course one option would be to use something like `pmap`, but i'd like to see how far i can get on a single GPU.

**miscellaneous questions**:
- FWIW i've tried both `custom_jvp` and `custom_vjp`. i'm ultimately computing gradients of a scalar loss. should i expect perf differences (memory or time) between either way of defining a custom derivative? 
- can i use `block_until_ready` within a custom derivative? i get errors like 
`AttributeError: 'ShapedArray' object has no attribute 'block_until_ready'`

```
# system details
>>> print(jax.__version__)
0.1.72
>>> print(jaxlib.__version__)
0.1.50
```

**Comment by sudhakarsingh27** [comment]
@martinjankowiak is it possible to provide a repro?

**Comment by mattjj** [comment]
+1, we should've asked for a repro 2 years ago! Oops.

But without a repro, this may not be actionable... we may have to close the issue without one.

**Comment by martinjankowiak** [comment]
@mattjj @sudhakarsingh27 please go ahead and close the issue as i no longer have a repro script. i'm assuming that the issues i was seeing may have been ironed out by subsequent dev (although perhaps memory usage can still be tricky in some cases in the absence of in-place ops? not sure)

**Comment by mattjj** [comment]
Thanks, @martinjankowiak ! Sorry we didn't address the issue more quickly.
