### ISSUE TITLE
Old version of re2 breaking attempts to build jax on windows 

### ISSUE THREAD

**Issue by durian888** [google/jax#3693]
Hi I'm working to port jaxlib to build on windows and have found that the re2 library is causing some issues.
Specifically if c++ standard 17 is selected when compiling with visual studio 2019 I hit a compile issue in the re2 library in file bitstate.cc. This issue  has appears to have  been addressed  in the Re2 code base - I can compile the latest version of  re2 on windows with c++17 and vs2019.

and see sha 59a5c74ed62be7068d3d3a1afa6261b676b8b03c in the re2 project git repo for details

"
Commit: 59a5c74ed62be7068d3d3a1afa6261b676b8b03c [59a5c74]
Parents: 9d34a04b50
Author: Paul Wankadia <junyer@google.com>
Date: Monday, August 19, 2019 6:40:44 AM
Committer: Paul Wankadia
Commit Date: Monday, August 19, 2019 1:51:50 PM
Don't assume that iterators are just pointers.

That is the case for re2::StringPiece and absl::string_view
and happens to be the case for std::string_view in libstdc++
and libc++, but std::string_view in MSVC has iterators that
aren't just pointers.
"

Please would the Jax team consider updating the version of re2 used by Jax to the latest version. 
I will look into upgrading re2 myself ,but I fear that will not be simple given the intricacies of the bazel build system.

**Comment by hawkinsp** [comment]
JAX doesn't depend on RE2 directly, only indirectly via XLA (in the TensorFlow repository). If you wanted to upgrade the RE2 version used by TensorFlow, you'd need to send a PR (or file an issue) on the TensorFlow GitHub issue tracker.

Once you update TensorFlow, for JAX it's just a matter of updating the TensorFlow revision in the `WORKSPACE` file.

**Comment by durian888** [comment]
Hi Peter

Thank you for the info – I’ll see what I can do.

Dominic

**Comment by hawkinsp** [comment]
I think this is now stale: JAX successfully builds on Windows at head.
