### ISSUE TITLE
documentation: lax.random API 

### ISSUE THREAD

**Issue by murphyk** [google/jax#370]
I had to dig into the RNG design doc (https://github.com/google/jax/blob/master/design_notes/prng.md) to find out that the equivalent of np.rand() < p is random.bernoulli(p).

In general, there needs to be more documentation on how to sample from various distributions (including multivariate).

**Comment by mattjj** [comment]
Thanks for suggesting this!

As a start, in #373 we added [`jax.random`](https://jax.readthedocs.io/en/latest/jax.random.html) to the [jax.readthedocs.io](https://jax.readthedocs.io/en/latest/) page.

What else should we prioritize? One idea might be to add a short notebook showing illustrating some of the basics and some idioms.

**Comment by mattjj** [comment]
Just noticed that those generated docs all have `*args, **kwargs` signatures, which are unhelpful. Will fix...

**Comment by hawkinsp** [comment]
PR #378 fixed the signatures.

Anything else we should improve?

**Comment by mattjj** [comment]
I'm going to take a narrow reading of @murphyk's original post and say by adding `jax.random` to the jax.readthedocs.io reference documentation, we've closed this particular issue. For additional improvements, like a Colab centered around the PRNG system, let's open up new issues.
