### ISSUE TITLE
Unhashable objects are silently accepted as static arguments to jax.jit

### ISSUE THREAD

**Issue by JonyEpsilon** [google/jax#3701]
Consider the following code:

```python
@dataclasses.dataclass
class Config:
  some_value: int
  # many other values omitted

@functools.partial(jax.jit, static_argnums=1)
def do_stuff(data, config):
  # do some stuff

def evaluate():
  config = Config(suitable_value_for_evaluation)
  data = summon_up_evaluation_data()
  do_stuff(data, config)
```
This will unexpectedly (to me at least) retrace/recompile `do_stuff` every time `evaluate` is called. The reason is because the `dataclass` derived `Config` does not have a `__hash__` method by default. (Using `@dataclasses.dataclass(frozen=True)` does yield a `Config` class with a hash, and then behaviour is as expected.)

It would be helpful to warn, or even error, if an unhashable object is passed to `jax.jit`, to make this sort of thing easier to track down. (It took me a long while before I thought to check whether dataclasses were hashable ...)

It looks as though `wrap_hashably` being too lenient is the root cause: https://github.com/google/jax/blob/master/jax/api_util.py#L130 (Thanks @tomhennigan ). It could be better to fail in this function if the unhashable value isn't one of the types that this function intends to wrap, as it seems that the retrace/recompile behaviour would never be the one that user desired.

**Comment by mattjj** [comment]
Thanks for raising this. This was originally intended behavior, but I think we want to revise it so that only hashable values are accepted as static arguments, as you suggest. (I suspect there are some duplicate issues about this.)

**Comment by mattjj** [comment]
See also #3708.

**Comment by NeilGirdhar** [comment]
Also here https://github.com/google/jax/issues/2813

**Comment by mattjj** [comment]
Thanks, @NeilGirdhar !

Let's consolidate the discussion at #2813.
