### ISSUE TITLE
conv_general_dilated do not support complex number

### ISSUE THREAD

**Issue by long1216** [google/jax#3706]
I am currently shifting a project from autograd to Jax which involve the convolution for complex number. In autograd, the convolution function from autograd/autograd/scipy/signal.py/convolve do not restrict the type of input, it works pretty well. However, neither jax/jax/scipy/signal.py/convolve nor jax/jax/lax/lax.py/conv_general_dilated support the usage of data format, complex64. Would i know if there's any plan for supporting complex64 or any direction for me to make it works like HIPS/autograd library? Thank you so much.

**Comment by hawkinsp** [comment]
Can you share a bit more information? What did you run, and on what hardware platform?

**Comment by long1216** [comment]
`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-6-761948a0f0be> in <module>
      5                                (1,1),  # lhs/image dilation
      6                                (1,1),  # rhs/kernel dilation
----> 7                                dn)     # dimension_numbers = lhs, rhs, out dimension permutation
      8 print("out shape: ", out.shape)
      9 print("First output channel:")

~/.local/lib/python3.6/site-packages/jax/lax/lax.py in conv_general_dilated(lhs, rhs, window_strides, padding, lhs_dilation, rhs_dilation, dimension_numbers, feature_group_count, batch_group_count, precision)
    540       batch_group_count=batch_group_count,
    541       lhs_shape=lhs.shape, rhs_shape=rhs.shape,
--> 542       precision=_canonicalize_precision(precision))
    543 
    544 def dot(lhs: Array, rhs: Array, precision: Optional[PrecisionType] = None) -> Array:

~/.local/lib/python3.6/site-packages/jax/core.py in bind(self, *args, **kwargs)
    197     top_trace = find_top_trace(args)
    198     if top_trace is None:
--> 199       return self.impl(*args, **kwargs)
    200 
    201     tracers = map(top_trace.full_raise, args)

~/.local/lib/python3.6/site-packages/jax/interpreters/xla.py in apply_primitive(prim, *args, **params)
    164 def apply_primitive(prim, *args, **params):
    165   """Impl rule that compiles and runs a single primitive 'prim' using XLA."""
--> 166   compiled_fun = xla_primitive_callable(prim, *map(arg_spec, args), **params)
    167   return compiled_fun(*args)
    168 

~/.local/lib/python3.6/site-packages/jax/interpreters/xla.py in xla_primitive_callable(prim, *arg_specs, **params)
    172   device = _device_from_arg_devices(arg_devices)
    173   backend = xb.get_device_backend(device)
--> 174   aval_out = prim.abstract_eval(*avals, **params)
    175   if not prim.multiple_results:
    176     handle_result = aval_to_result_handler(device, aval_out)

~/.local/lib/python3.6/site-packages/jax/lax/lax.py in standard_abstract_eval(prim, shape_rule, dtype_rule, *args, **kwargs)
   1697     return ConcreteArray(prim.impl(*[x.val for x in args], **kwargs))
   1698   elif least_specialized is ShapedArray:
-> 1699     return ShapedArray(shape_rule(*args, **kwargs), dtype_rule(*args, **kwargs))
   1700   elif least_specialized is UnshapedArray:
   1701     return UnshapedArray(dtype_rule(*args, **kwargs))

~/.local/lib/python3.6/site-packages/jax/lax/lax.py in _conv_general_dilated_dtype_rule(lhs, rhs, window_strides, padding, lhs_dilation, rhs_dilation, dimension_numbers, **unused_kwargs)
   2230     dimension_numbers, **unused_kwargs):
   2231   return naryop_dtype_rule(_input_dtype, [_float, _float],
-> 2232                           'conv_general_dilated', lhs, rhs)
   2233 
   2234 _conv_spec_transpose = lambda spec: (spec[1], spec[0]) + spec[2:]

~/.local/lib/python3.6/site-packages/jax/lax/lax.py in naryop_dtype_rule(result_dtype, accepted_dtypes, name, *avals, **kwargs)
   1737       typename = str(onp.dtype(aval_dtype).name)
   1738       typenames = ', '.join(t.__name__ for t in types)
-> 1739       raise TypeError(msg.format(name, typename, i, i, typenames))
   1740   _check_same_dtypes(name, False, *aval_dtypes)
   1741   return result_dtype(*avals)

TypeError: conv_general_dilated does not accept dtype complex64 at position 0. Accepted dtypes at position 0 are subtypes of floating.`

I tried to follow the guide from Advanced Jax tutorials - the sharp bits - convolution part and amend it with complex value, the above error is what i get after running the code. From my understanding, the code from lax.py
`def _conv_general_dilated_dtype_rule(
    lhs, rhs, *, window_strides, padding, lhs_dilation, rhs_dilation,
    dimension_numbers, **unused_kwargs):
  return naryop_dtype_rule(_input_dtype, [_float, _float],
                          'conv_general_dilated', lhs, rhs)`
restricted the input type to float but not complex number, would changing this function  (_conv_general_dilated_dtype_rule) lead to the support of complex-valued convolution? Thank you so much.

**Comment by long1216** [comment]
When i make the amendment changing the data type 
`2020-07-10 16:07:06.243313: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_runner.cc:491] %custom-call = (c64[1,200,198,3]{2,1,3,0}, u8[0]{0}) custom-call(c64[1,200,198,3]{2,1,3,0} %copy.3, c64[3,3,3,3]{1,0,2,3} %copy.4), window={size=3x3 pad=1_1x1_1}, dim_labels=b01f_01io->b01f, custom_call_target="__cudnn$convForward", metadata={op_type="conv_general_dilated" op_name="conv_general_dilated[ batch_group_count=1\n                      dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2))\n                      feature_group_count=1\n                      lhs_dilation=(1, 1)\n                      lhs_shape=(1, 200, 198, 3)\n                      padding=((1, 1), (1, 1))\n                      precision=None\n                      rhs_dilation=(1, 1)\n                      rhs_shape=(3, 3, 3, 3)\n                      window_strides=(1, 1) ]"}, backend_config="{\"algorithm\":\"0\",\"tensor_ops_enabled\":false,\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}"`

And here is the program i run for complex convolution

> import numpy as onp
import jax
import jax.numpy as jnp
from jax import lax
from jax.lax import conv_general_dilated
from matplotlib import pyplot as plt
\
img = onp.zeros((1, 200, 198, 3), dtype=jnp.complex64)
for k in range(3):
    x = 30 + 60*k
    y = 20 + 60*k
    img[0, x:x+10, y:y+10, k] = 1.0
print('image shape',img.shape)
\
kernel = onp.zeros((3, 3, 3, 3), dtype=jnp.complex64)
kernel += onp.array([[1, 1, 0],
                [1, 0,-1],
                [0,-1,-1]])[:, :, onp.newaxis, onp.newaxis]
print('kernel shape:',kernel.shape)
\
dn = lax.conv_dimension_numbers(img.shape,     # only ndim matters, not shape
                                kernel.shape,  # only ndim matters, not shape
                                ('NHWC', 'HWIO', 'NHWC'))  # the important bit
print(dn)
\
out = lax.conv_general_dilated(img,    # lhs = image tensor
                               kernel, # rhs = conv kernel tensor
                               (1,1),  # window strides
                               'SAME', # padding mode
                               (1,1),  # lhs/image dilation
                               (1,1),  # rhs/kernel dilation
                               dn)     # dimension_numbers = lhs, rhs, out dimension permutation
print("out shape: ", out.shape)

It is the problem for compiler?

**Comment by hawkinsp** [comment]
PR #3706 fixes this!

**Comment by long1216** [comment]
Thank you so much for helping me, it finally works. However, when i take the grad from the CNN related function, what i get is 

>  E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:325] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR

> W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_conv_algorithm_picker.cc:767] Failed to determine best cudnn convolution algorithm: Internal: All algorithms tried for convolution %custom-call.15 = (f32[128,14,14,6]{2,1,3,0}, u8[0]{0}) custom-call(f32[128,31,31,1]{2,1,3,0} %pad, f32[5,5,1,6]{1,0,2,3} %real.23), window={size=5x5 stride=2x2}, dim_labels=b01f_01io->b01f, custom_call_target="__cudnn$convForward", metadata={op_type="conv_general_dilated" op_name="jit(update)/conv_general_dilated[ batch_group_count=1\n                                  dimension_numbers=ConvDimensionNumbers(lhs_spec=(0, 3, 1, 2), rhs_spec=(3, 2, 0, 1), out_spec=(0, 3, 1, 2))\n                                  feature_group_count=1\n                                  lhs_dilation=(1, 1)\n                                  lhs_shape=(128, 28, 28, 1)\n                                  padding=((1, 2), (1, 2))\n                                  precision=None\n                                  rhs_dilation=(1, 1)\n                                  rhs_shape=(5, 5, 1, 6)\n                                  window_strides=(2, 2) ]" source_file="test.py" source_line=56}, backend_config="{\"algorithm\":\"0\",\"tensor_ops_enabled\":false,\"conv_result_scale\":1,\"activation_mode\":\"0\",\"side_input_scale\":0}" failed. Falling back to default algorithm. 
\
Convolution performance may be suboptimal

Seems like the problem is mainly related to cudnn library instead of XLA, do i need to submit a feature request to Tensorflow? Or any advice for the next step? Thank you so much.

**Comment by jekbradbury** [comment]
If the problem is replicable, can you post a new issue with the complete repro code? It may ultimately be a problem in XLA or cuDNN but it's fine to file it on JAX for now.
