### ISSUE TITLE
Shape-checking bug

### ISSUE THREAD

**Issue by peterdsharpe** [google/jax#3718]
Hi there,

I've encountered a bug with Jax's shape-checking rules that directed me to report to this forum. I've worked down to roughly the minimum self-contained bug-inducing example:

```python
import jax.numpy as np
from jax import grad, vmap

a = np.arange(4) # example vector
A = np.arange(16).reshape((4, 4)) # example matrix

def fun(x):
    x @ A # this line shouldn't do anything, but commenting it out makes this code run without errors!
    return np.sum(a * x)

jac_diag = vmap(grad(fun)) # element-wise gradient

input = np.arange(4).astype(float) # example input

print(fun(input)) # This runs fine
print(jac_diag(input)) # This throws a "shape-checking" error, see trace below
```
When I run this, I get an error with a long stack trace that I've copied to [Pastebin](https://pastebin.com/5ctS14SU). I'm running on Windows 10 with Windows Subsystem for Linux running Ubuntu 18.04, set up as a remote interpreter through PyCharm.

I suspect it might have something to do with the `@` operator - any ideas here? ~Rewriting that as a series of `np.dot`s might fix the issue~, but I'm curious about what's causing this.

**Comment by peterdsharpe** [comment]
Update: rewriting with `np.dot`s did not resolve this problem.

**Comment by mattjj** [comment]
Thanks for the report! Looks like a bug in `jax.numpy.matmul`, as well as a bug in our shape checking rules (the latter because XLA caught this rather than us catching it earlier in JAX).

However, replacing `x @ A` with `np.dot(x, A)` made the issue go away for me. If it's not working for you, could you share the code that repros it?

**Comment by mattjj** [comment]
#3725 should fix the error message. However, in following NumPy's rules, the code in the OP still raises an error because matmul inputs aren't allowed to be scalars:

```python
In [1]: import numpy as np  # original numpy

In [2]: np.matmul(1., np.zeros(4))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-a087b8135470> in <module>
----> 1 np.matmul(1., np.zeros(4))

ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
```

The lhs input to the matmul is a scalar here because vmap reduces the rank of the input, analogously to this code:

```python
np.stack([grad(fun)(elt) for elt in input])  # each elt is scalar
```

WDYT?

**Comment by peterdsharpe** [comment]
Hey Matt & team,

Thanks for the quick fix and explanation! This makes a lot of sense - in hindsight, it looks like I got a bit too trigger-happy with `vmap` haha!

Also, confirming here that `np.dot` is in fact making those errors go away. (Not sure why it wasn't working on Saturday, might've been a typo of mine, sorry about that!)
