### ISSUE TITLE
cannot `import optimizers' from 'jax.experimental'  even though `import stax` works

### ISSUE THREAD

**Issue by murphyk** [google/jax#372]
I typed
```
pip install --upgrade jax jaxlib  # CPU-only version
```
and the tests pass.
Now I am trying to run the first order opt demo from [here.](https://github.com/google/jax#mini-libraries).
I get this error
```
from jax.experimental import optimizers
ImportError: cannot import name 'optimizers' from 'jax.experimental' (/home/kpmurphy/anaconda3/lib/python3.7/site-packages/jax/experimental/__init__.py)
```
even though ```from jax.experimental import stax``` works fine.

I am using  jax==0.1.18, jaxlib==0.1.7 on a pixelbook.

**Comment by hawkinsp** [comment]
I think this is a version difference — until we release a new `jax` wheel, the module is still called `minmax`. (This was apparently an unwise choice of name because of potential confusion with `minimax`.)

Try `jax.experimental.minmax`.

**Comment by murphyk** [comment]
that works, thx

**Comment by rookiiiie** [comment]
> from jax.experimental import optimizers

hello！Rencently i met the same problem,have u solved?

**Comment by rookiiiie** [comment]
I download the latest jaxlib folder and search "optimizers",i find the package path has changed！from "from jax.experimental import optimizers" to "from jax.example_libraries import optimizers" ，u can have a try😁

**Comment by jakevdp** [comment]
Please note that `jax.experimental.optimizers` was moved to `jax.example_libraries` [in JAX v0.2.25](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-2-25-nov-10-2021), and the old path was removed [in JAX v0.3.16](https://jax.readthedocs.io/en/latest/changelog.html#jax-0-3-16).
