### ISSUE TITLE
`linalg.eigh` precision is too small and backprop unstable

### ISSUE THREAD

**Issue by JonasRigo** [google/jax#3734]
Dear `Jax` Developers,

I'm enjoying a lot your library and currently I try to develop a high precision simulation with your library. Unfortunately I encountered two problems. 
First it seems, like the eigensolver routine for hermitian matrices is significantly less precise than the one provided by `Numpy`. I tried to reproduce the discrepancy in this example code

```
import jax.numpy as jp
from jax import ops as jops
import jax.numpy.linalg as la

U = 0.3 
eps = -0.15
V = 0.1
dim = 4
aux_dim = 4

Lambda = 3.

elemaddedsite = jp.zeros((2,4,4)) 
elemaddedsite = jops.index_update(elemaddedsite,jops.index[0,0,3],1.)
elemaddedsite = jops.index_update(elemaddedsite,jops.index[0,1,2],-1.)
elemaddedsite = jops.index_update(elemaddedsite,jops.index[1,0,1],1.)
elemaddedsite = jops.index_update(elemaddedsite,jops.index[1,3,2],1.)
elemaddedsite_index = [[1,3,2],[1,0,1],[0,1,2],[0,0,3]]

alambda = (Lambda + 1.)/(Lambda - 1.)*jp.log(Lambda)/2. # this factor accounts for the discretation
eps /= Lambda
U /= Lambda

energies = jp.zeros(dim)
energies = jops.index_update(energies,[0,1,2,3],[0.,eps,(2.*eps + U),eps]) 

wilson_t = jp.sqrt(alambda/Lambda) * V # * we account for the descrete bath

elemlastsite = jp.zeros((2,aux_dim,aux_dim))
elemlastsite = jops.index_update(elemlastsite,0,jp.transpose(elemaddedsite[0]))
elemlastsite = jops.index_update(elemlastsite,1,jp.transpose(elemaddedsite[1]))

dim_new = dim

dim_new = dim_new*aux_dim

H = jp.zeros((dim_new,dim_new))

id = lambda x: dim*x

for i in jp.arange(4):  
    H = jops.index_update(H,jops.index[id(i):id(i+1),id(i):id(i+1)], 0.5 * jp.diag(jp.sqrt(Lambda) * energies[0:dim]))

for idx in elemaddedsite_index:
    sign, k, kp = idx
    H = jops.index_update(H,jops.index[id(k):id(k+1),id(kp):id(kp+1)],wilson_t * elemlastsite[sign]*elemaddedsite[sign,k,kp] * (-1.)**(k))

H += H.T

import numpy as np
energies_np, eigs_np = np.linalg.eigh(H,'U')

energies_jp, eigs_jp = la.eigh(H,'U')

print(energies_np - energies_jp)

print("\n")

print(eigs_np-eigs_jp)

print("\n")

print(jp.matmul(eigs_jp.T,eigs_jp))

print("\n")

print(jp.matmul(eigs_np.T,eigs_np))
```

It doesn't look like much, but it causes strongly deviating results from what are known correct results I can reproduce with `Numpy`. 

Second it seems like Jacobians that propagate through more than one eigensolver backwards are not stable and return `nan`.

I would be very happy if I could get feedback for these two issues. I apologize if all this can be solved by using float64, but I think that is not the problem.

Thanks, Jonas

**Comment by jakevdp** [comment]
Hi - from the residuals, it looks like you're using 32-bit arithmetic, which is currently Jax's default. See https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Double-(64bit)-precision for details.

If I run this at the start of the session and then run your code, the residuals look much better:
```
from jax.config import config
config.update("jax_enable_x64", True)
```

This x64 issue is a bit of a wart at the moment, and we're hoping to move soon to matching Numpy's use of 64-bit precision by default.

**Comment by JonasRigo** [comment]
Thanks for the quick response.
That was it!
