### ISSUE TITLE
Question on `abstract_eval_fun`

### ISSUE THREAD

**Issue by DarrenZhang01** [google/jax#3737]
Hi, it seems that `jax.interpreters.partial_eval.abstract_eval_fun` [(https://github.com/google/jax/blob/master/jax/interpreters/partial_eval.py#L326)](https://github.com/google/jax/blob/master/jax/interpreters/partial_eval.py#L326) is only doing shape inference at the abstract level? But why is that the case that sometimes the output `avals_out` will contain `PartialVal` objects with known values like `ConcreteArray`? Thanks.

**Comment by hawkinsp** [comment]
By the way, this is probably better as a GitHub discussion, not an issue. There's no action for us to take here (other than answer the question.). I suggest opening a discussion thread?

**Comment by hawkinsp** [comment]
Actually apparently I can convert it to a discussion. Let me do that!
