### ISSUE TITLE
Inequation inside Jax.jit function

### ISSUE THREAD

**Issue by fasghq** [google/jax#3740]
Hi!
https://github.com/google/jax/pull/2508#issuecomment-657785351
Maybe I miss something obvious, but what should I do if I need to use inequation inside the function for `jax.jit`? Here's my function:
`def tt_round_model(tt, delta):`
`...`
`for x in s:`
`if x < delta:`
`...`
As I found, I should add `static_argnums` in such case, so I added `delta` to it:
`fast_tt_round = jit(tt_round_model, static_argnums=(1))`
`ttr = fast_tt_round(tts_s, eps / math.sqrt(len(tts_s.core) - 1))`
But I still have the problem in compilation:
![screenshot](https://user-images.githubusercontent.com/62699960/87353788-2d907780-c566-11ea-8929-4c16161ce822.jpg)
I suppose that the problem is in my `x` variable which is diagonal element of `s` matrix which I get inside this algorithm, so I can't add it to `static_argnums`.
Thank you for your help!

**Comment by jakevdp** [comment]
In general, you cannot jit-compile code with control flow that depends on the value in an array. It's possible to use [structured control flow](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Structured-control-flow-primitives) primitives in this case, but this sort of loop-based construction will generally be much less efficient than array-based primitives, particularly on GPU or TPU.

For code like yours, it would be best to write your code using broadcasting and [jnp.where](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.where.html?highlight=where):
```
result = jnp.where(s < delta, value1, value2)
```
