### ISSUE TITLE
Cython compile error when `python build/build.py`

### ISSUE THREAD

**Issue by tamuhey** [google/jax#375]
I ran `$ python build/build.py --enable_cuda` and the following error was occurred.

```
Error compiling Cython file:
------------------------------------------------------------
...

  cdef int lwork = heevd_work_size(n)
  cdef int lrwork = heevd_rwork_size(n)
  cdef int liwork = syevd_iwork_size(n)
  zheevd(&jobz, &uplo, &n, a_out, &n, w_out, work, &lwork, rwork, &lrwork,
         iwork, &liwork, info_out)
                        ^
------------------------------------------------------------

jaxlib/lapack.pyx:837:25: Converting to Python object not allowed without gil
Target //build:install_xla_in_source_tree failed to build
```

How to resolve?

**Comment by mattjj** [comment]
What version of Cython do you have? Since this is a Cython error, it might be a good idea to make sure that's up-to-date.

**Comment by tamuhey** [comment]
@mattjj 0.28.5

I will upgrade cython to latest version and try to build again.

**Comment by hawkinsp** [comment]
The most likely explanation is you don't have `scipy` installed. Can you install scipy and try again?

**Comment by mattjj** [comment]
@hawkinsp if we require scipy, should we add it to setup.py?

**Comment by tamuhey** [comment]
This failure was due to the version of cython. Thanks!

**Comment by mattjj** [comment]
Glad to hear you got it solved!

**Comment by mtthss** [comment]
I m also getting the error:

```
Error compiling Cython file:
------------------------------------------------------------
...
      lwork * sizeof(double complex))

  for i in range(b):
    memcpy(a_work, a_in, n * n * sizeof(double complex))
    zgeev(&jobvlr, &jobvlr, &n, a_work, &n, w_out, vl_out, &n, vr_out, &n,
          work, &lwork, r_work, info_out)
                               ^
------------------------------------------------------------

jaxlib/lapack.pyx:1590:32: Converting to Python object not allowed without gil
```

I have cython and scipy installed and updated to the latest version

**Comment by hawkinsp** [comment]
@mtthss Can you share the exact versions of your operating system, Python, Cython, and scipy and how you installed them? This has always so far been a symptom of not having scipy visible to python for some reason.

**Comment by mtthss** [comment]
```
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 

>>> import scipy
>>> scipy.__version__
'1.2.2'
>>> import cython
>>> cython.__version__
'0.29.13'
```

**Comment by mtthss** [comment]
All installed in a clean `virtualenv` with `pip`

**Comment by surak** [comment]
I have the same with cython from python 3.8.5, 0.29.21.

**Comment by elchorro** [comment]
I am also experiencing this issue. 

Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy
>>> scipy.__version__
'1.7.0'
>>> import cython
>>> cython.__version__
'0.29.24'

**Comment by perfumescent** [comment]
I got this error when installing other libs

>  Converting to Python object not allowed without gil

then I upgrade scipy and work well.

So i leave a note here in case someone need it
