### ISSUE TITLE
jax.scipy.special zeta sometimes returns NaN

### ISSUE THREAD

**Issue by srvasude** [google/jax#3758]
For large values of z, `jax.scipy.special.zeta` returns NaN when it should instead return 0.:

`jax.scipy.special.zeta(1e5, q=1.)`  # Return NaN.

Note: I suspect TF and Scipy have this same issue:

`sp.zeta(1e19, 40.)`   # Returns NaN in Scipy. I have to use a large value because Scipy is using internal float64 calculations.

`tf.math.zeta(1e10, q=30.)`  # Returns NaN in TF

**Comment by hawkinsp** [comment]
@fehiepsi contributed this function originally, perhaps they have thoughts.

**Comment by fehiepsi** [comment]
I think you can fix the issue by clipping [T1 term](https://github.com/google/jax/blob/master/jax/scipy/special.py#L208) by `jnp.clip(T1, a_max=jnp.finfo(dtype).max)`. Another way is to add a safemul when multiplying `0` and `inf` at the computation of [T](https://github.com/google/jax/blob/master/jax/scipy/special.py#L211), kind of
```
T = jnp.where(T0 == 0, 0., T0 * (dtype(0.5) + T1.sum(-1)))
```
That way, we don't face `NaN` issue, even for examples that failed on `scipy` and `tf`.

**Comment by sowa9599** [comment]
@hawkinsp

**Comment by sowa9599** [comment]
> For large values of z, `jax.scipy.special.zeta` returns NaN when it should instead return 0.:
> 
> `jax.scipy.special.zeta(1e5, q=1.)` # Return NaN.
> 
> Note: I suspect TF and Scipy have this same issue:
> 
> `sp.zeta(1e19, 40.)` # Returns NaN in Scipy. I have to use a large value because Scipy is using internal float64 calculations.
> 
> `tf.math.zeta(1e10, q=30.)` # Returns NaN in TF
