### ISSUE TITLE
Optix optimizer state hard to serialize

### ISSUE THREAD

**Issue by cgarciae** [google/jax#3759]
Hey, I am using `deepdish` to serialize my model state since it is able to serialize dicts with array like structures to `hdf5`, it works great for most of the stuff (I use Haiku) except for serializing and loading optix optimizer state. Optix internally uses named tuples like `ScaleByRmsState`, before serializing if I run:

```python
jax.tree_map(lambda x: x.shape, model._optimizer_state)
```
I get these named tuples
```
[ScaleByRmsState(nu=frozendict({
   'mlp/~call/linear': frozendict({'b': (300,), 'w': (784, 300)}),
   'mlp/~call/linear_1': frozendict({'b': (100,), 'w': (300, 100)}),
   'mlp/~call/linear_2': frozendict({'b': (10,), 'w': (100, 10)}),
 })),
 ScaleState()]
```
But when I load from disc it I only get generic tuples (which makes sense):
```
[(frozendict({
    'mlp/~call/linear': frozendict({'b': (300,), 'w': (784, 300)}),
    'mlp/~call/linear_1': frozendict({'b': (100,), 'w': (300, 100)}),
    'mlp/~call/linear_2': frozendict({'b': (10,), 'w': (100, 10)}),
  }),),
 ()]
```
The problem is that is if I try to resume training I get:
```
AttributeError: 'tuple' object has no attribute 'nu'
```
How are you getting around this? Would it be possible for optix to use dictionaries or ordinary tuples instead of NamedTuples?

**Comment by jekbradbury** [comment]
Named tuples are a fairly standard built in Python type, and serialization tools should (in general) understand them? I'm not sure what's going wrong here.

**Comment by cgarciae** [comment]
@jekbradbury The problem with `NamedTuples` is that most (all?) serialization tools interprete them as generic tuples, checkout this example of converting a named tuple to JSON:

```python
import typing as tp
import json


class A(tp.NamedTuple):
    u: int

json.dumps({"a": A(u=1)})  # {"a": [1]}
```
Apart from using `pickle` I don't think most serialization formats will actually give you back a full named tuple. More to the point, is there a general strategy for creating checkpoints in Jax?

**Comment by jekbradbury** [comment]
Any reason you can't use `pickle`? I agree that it's tough to store something like a namedtuple to a language-agnostic serialization format; do you need to load the checkpoints in another framework/language?

**Comment by cgarciae** [comment]
@jekbradbury I am building a framework based on Jax + Haiku I will share around here soon, `pickle` is [not recommended](https://www.reddit.com/r/Python/comments/4xc5ok/pickle_shouldnt_be_used_for_large_sets_of_numeric) for saving and sharing data, it also seems to have slower IO and its larger on disk than HDF5. `deepdish` works great for easily saving/loading stuff to HDF5

**Comment by shoyer** [comment]
The default pickle format on Python 3 (i.e,. `protocol=3` or higher) directly copies the binary representation of NumPy arrays into a bytestring. This is at least as fast as HDF5, if not faster. There plenty of downsides to pickle as a serialization format but speed isn't one of them.

**Comment by umangjpatel** [comment]
I've used dill and msgpack to serialize stax models. Check out the v2-branch of my library called dnet. `https://github.com/umangjpatel/dnet/tree/v2-rewrite`.

**Comment by umangjpatel** [comment]
```python
def save_module(file_name: str, **config: dict):
    serialized_config = {}
    for k, v in config.items():
        item_dill: bytes = dill.dumps(v)
        item_msgpack: bytes = msgpack.packb(item_dill, use_bin_type=True)
        serialized_config[k] = item_msgpack

    with open(f"{file_name}.msgpack", "wb") as f:
        serialized_data = msgpack.packb(serialized_config)
        f.write(serialized_data)


def load_module(file_name: str):
    with open(f"{file_name}.msgpack", "rb") as f:
        deserialized_data: bytes = f.read()
        deserialized_config: Dict[str, bytes] = msgpack.unpackb(deserialized_data)
        for k, v in deserialized_config.items():
            item_dill = msgpack.unpackb(v)
            deserialized_config[k] = dill.loads(item_dill)
    return deserialized_config
```

This snippet can not only serialize / deserialize JAX types but also functions (that's why the dill)

**Comment by hawkinsp** [comment]
`optix` is no longer part of JAX, so if this is still an issue it probably needs to be reported against the separate package `optax` (the evolution of `optix`).
