### ISSUE TITLE
jnp.take uses clipped indexes whereas np.take does not

### ISSUE THREAD

**Issue by dbieber** [google/jax#3774]
Hi, I'm reporting a discrepancy between jax.numpy and numpy that I think should be considered a bug.

jnp.take uses clipped indexes whereas np.take does not.

numpy behavior:
```
x = np.array(
  [[1,2,3],
   [4,5,6],
   [7,8,9]])
x.take([4], axis=0)

> IndexError: index 4 is out of bounds for size 3
```

jax.numpy behavior:
```
x = jnp.array(
  [[1,2,3],
   [4,5,6],
   [7,8,9]])
x.take([4], axis=0)

> DeviceArray([[7, 8, 9]], dtype=int32)
```

I think the numpy behavior is preferable. The jax.numpy behavior silently masked a bug for me. My vocab_size for some embeddings was too small, and it took me a while to realize this.

**Comment by jakevdp** [comment]
This is a known issue/feature of Jax; see [JAX - The Sharp Bits: Out-of-Bounds Indexing](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Out-of-Bounds-Indexing) for more information.
