### ISSUE TITLE
Matrix slicing inside Jax.jit function

### ISSUE THREAD

**Issue by fasghq** [google/jax#3794]
Hello!
I want to apply `jax.jit` to my function of rounding tensor-train ranks:
```
def tt_round_model(tt, delta):  
    G = tt.core
    d = len(tt.core)
    rn = []
    time1 = time.perf_counter()    
    
    for k in range(d-1, 0, -1):
        r1, n, r2 = G[k].shape
        G[k] = np.reshape(G[k], (r1, n * r2))
        G[k] = np.transpose(G[k])
        G[k], R = la.qr(G[k])
        G[k] = np.transpose(G[k])
        G[k-1] = np.einsum('ijk,lk->ijl', G[k-1], R) 
    
    for k in range(0, d - 1):
        print(k, G[k].shape, k+1, G[k+1].shape)
        
        if k == 0:
            r1, n1, r2 = G[k].shape
            r3 = G[k+2].shape[0]
            n2 = int(G[k+1].shape[1] / r3)
        elif k == d - 2:
            r1 = G[k].shape[0]
            r2 = G[k+1].shape[0]
            n1 = int(G[k].shape[1] / r2)
            r3 = 1
            n2 = G[k+1].shape[1]
        else:
            r1 = G[k].shape[0]
            r2 = G[k+1].shape[0]
            n1 = int(G[k].shape[1] / r2)
            r3 = G[k+2].shape[0]
            n2 = int(G[k+1].shape[1] / r3)

        G[k] = np.reshape(G[k], (r1 * n1, r2))
        G[k+1] = np.reshape(G[k+1], (r2 , n2 * r3))
        u, s, v = la.svd(G[k])

        rc = s.shape[0]
        rc = jnp.maximum(rc, (s < delta).sum())
        
        s = np.diag(s)
        
        u = u[:, :rc]
        s = s[:rc, :rc]
        v = v[:, :rc]
        
        v = np.dot(v, s)
        G[k] = np.reshape(u, (r1, n1, rc))   
        G[k+1] = np.einsum('ij,ik->jk', G[k+1], v)
    
    
    if len(G[d-1].shape) == 2:
        G[d-1] = np.reshape(G[d-1], (G[d-1].shape[1], G[d-1].shape[0], 1))

    for X in G:
        rn.append(X.shape[0])
    rn.append(G[d-1].shape[2])

    time2 = time.perf_counter()
    print("\n time: ", time2 - time1)
    
    return Model(G)
```

And I have the problem with:
```
u = u[:, :rc]
s = s[:rc, :rc]
v = v[:, :rc]
```
as it causes the error:
```
IndexError: Array slice indices must have static start/stop/step to be used with Numpy indexing syntax. Try lax.dynamic_slice/dynamic_update_slice instead.
```

But I also can't use `lax.dynamic_slice` here as it causes the error:
```
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected (in `bool`).
Use transformation parameters such as `static_argnums` for `jit` to avoid tracing input values.
See `https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error`.
Encountered value: Traced<ShapedArray(bool[]):JaxprTrace(level=-1/1)>
```
How could I replace this part?

Thank you!

**Comment by shoyer** [comment]
These error messages could be improved, but value dependent shapes are not supported inside `jit`. See this section of the docs:
https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#python-control-flow-+-JIT

**Comment by mattjj** [comment]
As you've already observed, I think due to `rc = jnp.maximum(rc, (s < delta).sum())` depending on the values of `s` and `delta`, followed by the expressions you highlighted `u = u[:, :rc]`, we have value-dependent shapes and thus can't `jit` compile this function as written.

However, there is still hope: instead of truncating `u`, `s`, and `v` to be smaller arrays based on the singular value threshold, you might be able to just keep them the same size but replace with zeros the values below the singular value threshold. That is, instead of

```python
u = u[:, :rc]
s = s[:rc, :rc]
v = v[:, :rc]
```

you could use something more like

```python
discard = s < delta
u = jnp.where(discard, 0, u)
s = jnp.where(discard, 0, s)
v = jnp.where(discard[:,None], 0, s)
```

You'd likely have to adapt the code that follows too.

(By the way, the lines like `G[k] = ...` look like mutating side effects on the input `tt`, which also aren't supported in `jax.jit`.)

WDYT?

**Comment by fasghq** [comment]
> As you've already observed, I think due to `rc = jnp.maximum(rc, (s < delta).sum())` depending on the values of `s` and `delta`, followed by the expressions you highlighted `u = u[:, :rc]`, we have value-dependent shapes and thus can't `jit` compile this function as written.
> 
> However, there is still hope: instead of truncating `u`, `s`, and `v` to be smaller arrays based on the singular value threshold, you might be able to just keep them the same size but replace with zeros the values below the threshold. That is, instead of
> 
> ```python
> u = u[:, :rc]
> s = s[:rc, :rc]
> v = v[:, :rc]
> ```
> 
> you could use something more like
> 
> ```python
> discard = s < delta
> u = jnp.where(discard, 0, u)
> s = jnp.where(discard, 0, s)
> v = jnp.where(discard[:,None], 0, s)
> ```
> 
> You'd likely have to adapt the code that follows too.
> 
> (By the way, the lines like `G[k] = ...` look like mutating side effects on the input `tt`, which also aren't supported in `jax.jit`.)
> 
> WDYT?

Yes, I tried to replace those values with zeros, but actually I don't need to do something with them so I just leave these matrixes as they are and cut them outside the algorithm buy smaller ranks which I get on it's output. Thank you!
