### ISSUE TITLE
Build Fails due to c++ compilation failure

### ISSUE THREAD

**Issue by iliailmer** [google/jax#3797]
I get the following error building from source:

`C++ compilation of rule '@org_tensorflow//tensorflow/compiler/xla/python:bfloat16' failed (Exit 1)`

The whole build fails because of this and I am unsure where to look for a fix. I'm building on a macos, here are the environment packages:
```
absl-py==0.9.0
appdirs==1.4.4
appnope==0.1.0
attrs==19.3.0
autopep8==1.5.3
backcall==0.2.0
black==19.10b0
click==7.1.2
Cython==0.29.21
decorator==4.4.2
flake8==3.8.3
ipython==7.16.1
ipython-genutils==0.2.0
jaxlib==0.1.51
jedi==0.17.1
joblib==0.15.1
mccabe==0.6.1
mypy==0.780
mypy-extensions==0.4.3
numpy==1.18.5
opt-einsum==3.2.1
parso==0.7.0
pathspec==0.8.0
pexpect==4.8.0
pickleshare==0.7.5
prompt-toolkit==3.0.5
ptyprocess==0.6.0
pycodestyle==2.6.0
pydocstyle==5.0.2
pyflakes==2.2.0
Pygments==2.6.1
regex==2020.7.14
scikit-learn==0.23.1
scipy==1.4.1
six==1.15.0
snowballstemmer==2.0.0
threadpoolctl==2.1.0
toml==0.10.1
traitlets==4.3.3
typed-ast==1.4.1
typing-extensions==3.7.4.2
wcwidth==0.2.5
```

Not sure what other information would be helpful. Thanks.

**Comment by hawkinsp** [comment]
Can you share a few more details? What version of JAX are you building, and can you share the output of the build?

(Note also that we recommend using the prebuilt `jaxlib` wheels.)

**Comment by hawkinsp** [comment]
No response; closing.
