### ISSUE TITLE
MAML Gradients + Convnets don't work

### ISSUE THREAD

**Issue by ericjang** [google/jax#380]
The attached python code snippet implements a MAML gradient update on 1) an MLP and 2) a CNN.

When MODEL_TYPE = 'mlp', everything works. When MODEL_TYPE = 'conv', I get the following error:

RuntimeError: Invalid argument: Expected LHS feature dimension (value 1) to be a multiple of feature_group_count (value 1), and LHS feature dimension / feature_group_count = RHS feature dimension (value 40); got <conv>(f32[1,1,40,40], f32[10,1,1,40])
Dimension numbers: {kernel_input_feature_dimension: 3
kernel_spatial_dimensions: 1
kernel_spatial_dimensions: 2
input_batch_dimension: 3
output_batch_dimension: 2
output_feature_dimension: 3
input_spatial_dimensions: 1
input_spatial_dimensions: 2
output_spatial_dimensions: 0
[maml-cnn.txt](https://github.com/google/jax/files/2867892/maml-cnn.txt)

output_spatial_dimensions: 1
}.:     @     0x7ff2befc9214  xla::XlaBuilder::ReportErrorOrReturn()
    @     0x7ff2befd6eaa  xla::ConvGeneralDilated()
    @     0x7ff2b82e4cb8  xla::swig::LocalComputationBuilder::ConvGeneralDilated()
    @     0x7ff029565901  _wrap_LocalComputationBuilder_ConvGeneralDilated()
    @           0x4bc454  PyEval_EvalFrameEx

Note that for both model architectures, the maml objective loss can be computed. It's only in the case of attempting to take a gradient of the CNN-based loss, things break.

**Comment by AllanYangZhou** [comment]
[jax_maml_images.txt](https://github.com/google/jax/files/2867918/jax_maml_images.txt)

Also, here is another MAML implementation with a CNN which produces a different error:
`TypeError: reshape total size must be unchanged, got new_sizes (1, 40, 25, 25, 32) for shape (25, 54, 32, 40).`

When there is only one conv layer there is no error (though I haven't verified that the gradient is correct). The error only appears when there are 2+ conv layers.

**Comment by hawkinsp** [comment]
I'm pretty sure https://github.com/google/jax/pull/384 fixes this, but I need to write a test for it before checking it in.

**Comment by hawkinsp** [comment]
Ok, this should be fixed! Updating your copy of the Python `jax` module to git master should resolve the problem.
