### ISSUE TITLE
custom_vjp can't handle vmapping over a nondiff_argnums arg

### ISSUE THREAD

**Issue by mattjj** [google/jax#3808]
@duvenaud sent me a repro. This might be the same as #2912.

**Comment by NeilGirdhar** [comment]
@duvenaud You could try [my shim](https://github.com/NeilGirdhar/tjax/blob/master/tjax/shims.py#L19) over `custom_vjp` that separates the concepts of `nondiff_argnums` and `static_argnums`.

**Comment by mattjj** [comment]
@NeilGirdhar thanks for pointing that out; I meant to ask you about that. Is the idea that "static" args are things like functions (i.e. not jax value types), while nondiff args are jax values that we don't want to differentiate with respect to (like rng keys and the like)?

**Comment by NeilGirdhar** [comment]
@mattjj exactly!

**Comment by mattjj** [comment]
Seems smart! I swear I'll get to helping out with this, just a few more fires to put out first...

**Comment by mattjj** [comment]
This was fixed by #4008 !
