### ISSUE TITLE
Large differences between numerics of jit and op-by-op execution for simulations.

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#3827]
Recently a jax-md user noticed that the output of simulations seemed to be very different depending on whether or not the simulation step was jit (https://github.com/google/jax-md/issues/92) even when the simulation was run at float64. I extracted all of the jax md specific code and came up with the following repro. I have confirmed that this occurs on both CPU and GPU backends with `jax.__version==0.1.72`. Let me know if I can provide any extra information.

```python
from jax.api import jit, vmap, grad
from jax import random

from jax.config import config ; config.update('jax_enable_x64', True)

import jax.numpy as np
from collections import namedtuple

N = 32
dt = 1e-1
temperature = 0.1
box_size = 5.0
key = random.PRNGKey(0)

def displacement(R_1, R_2):
  dR = R_1[:, np.newaxis, :] - R_2[np.newaxis, :, :]
  dR = np.mod(dR + box_size / 2, box_size) - box_size / 2
  return dR
def shift(R, dR):
  return R + dR

def safe_mask(mask, fn, operand, placeholder=0):
  masked = np.where(mask, operand, 0)
  return np.where(mask, fn(masked), placeholder)

def energy_fn(R, **kwargs):
  dr = displacement(R, R)
  dr = np.sum(dr * dr, axis=-1)
  mask = 1 - np.eye(dr.shape[0], dtype=dr.dtype)
  dr = safe_mask(mask, np.sqrt, dr)
  U = mask * np.where(dr < 1.0, 1 / 2 * (1 - dr) ** 2, 0)
  U = 0.5 * np.sum(U)
  return U

NVEState = namedtuple('NVEState', ['position', 'velocity', 'acceleration'])
def nve(energy_fn, shift_fn, dt):
  force_fn = grad(energy_fn)

  dt_2 = 0.5 * dt ** 2
  def init_fun(key, R):
    V = random.normal(key, R.shape, dtype=R.dtype)
    return NVEState(R, V, -force_fn(R))
  def apply_fun(state):
    R, V, A = state
    R = shift_fn(R, V * dt + A * dt_2)
    A_prime = -force_fn(R)
    V = V + 0.5 * (A + A_prime) * dt
    return NVEState(R, V, A_prime)
  return init_fun, apply_fun

def simulation(key, jit_apply):
    pos_key, sim_key = random.split(key)
    R = random.uniform(pos_key, (N, 2), maxval=box_size)
    init_fn, apply_fn = nve(energy_fn, shift, dt)
    if jit_apply:
      apply_fn = jit(apply_fn)
    state = init_fn(sim_key, R)
    for i in range(1000):
        state = apply_fn(state)
    return state.position

a_positions = simulation(key, False)
b_positions = simulation(key, True)

dR = a_positions - b_positions
dR = np.mod(dR + box_size / 2, box_size) - box_size / 2
dr = np.sqrt(np.sum(dR * dR, axis=-1))
print(dr)
```

Which outputs:
```
[2.33171422 0.9812451  1.55086038 1.67008338 0.83624426 2.68838387
 1.68693065 2.30806348 0.91745479 0.61762378 1.86090168 3.32947105
 1.81900706 2.82369629 1.90045383 2.08167286 2.70602523 0.43538554
 2.63444707 3.04734335 1.13659884 2.40687914 2.46497045 0.15266076
 2.4147755  1.71029586 1.70824932 2.42880769 0.34217255 2.97179374
 2.2841274  2.17418844]
```

**Comment by mattjj** [comment]
We could consider this an XLA issue, where there are some fast-math-like optimizations going on under a `jit`(like rewriting or re-ordering operations), and perhaps if there's a way to disable those optimizations we can get the numerics to agree more closely (at the cost of potentially slower code). Another possibility, totally speculative, is that while we should always expect `jit` optimizations to alter numerics somewhat, some algorithms may be more susceptible than others (e.g. less numerically stable routines might see bigger changes than more stable ones, and perhaps we could learn some ways to adjust this computation to make it more stable in this way).

In any case, the best next step might be to open an internal issue with the XLA:CPU/GPU team. Maybe they can eyeball what optimizations may be causing the divergence (or put forward some other hypotheses that haven't occurred to me).

WDYT?

**Comment by sschoenholz** [comment]
Sgtm, I figured it was most likely an XLA issue but thought I'd come here first. I'll file a bug against XLA:CPU/GPU. I was mostly surprised by how large the deviation was with float64 using only 32 particles (so reductions are only over arrays of size 96). Generally I tend to assume that float32 will see significant numerical differences between jit and op-by-op execution but float64 has typically been pretty stable.

**Comment by sschoenholz** [comment]
For posterity, here's an interesting plot of the error verses time. You can see that per-step the error is about numerical precision but this leads to exponential deviation of the trajectories. I suppose this makes sense, but am still a bit surprised at the slope of the exponential!

![image](https://user-images.githubusercontent.com/7719876/88308774-4adde800-ccc2-11ea-9e47-e9767b14bc28.png)
