### ISSUE TITLE
float64 dot on cpu is slow

### ISSUE THREAD

**Issue by alewis** [google/jax#3832]
Dot in Jax currently seems to be about 3-4 times slower than numpy:

```
import time
import jax
import numpy as np
import jax.numpy as jnp
import jax.config as config
jax.config.update("jax_enable_x64", True)

chi = 256
dtype = np.float64
Aj = jnp.ones((chi, chi), dtype=dtype)
Bj = jnp.ones((chi, chi), dtype=dtype)

An = np.ones((chi, chi), dtype=dtype)
Bn = np.ones((chi, chi), dtype=dtype)

%timeit jnp.dot(Aj, Bj).block_until_ready()
%timeit np.dot(An, Bn)
```

```
$ 100 loops, best of 3: 4.54 ms per loop
$ 1000 loops, best of 3: 1.21 ms per loop
```

Those timings are from a Colab notebook, and I get comparable results on my laptop. They are about the same however I express the operation (e.g. using einsum, etc).

**Comment by hawkinsp** [comment]
Thanks for the issue report! I'm curious: is this just something you noticed in a microbenchmark, or is it affecting performance in a significant way for a real use case?

We have improvements coming to how we treat matmuls on CPU, but they may take a little while to land.

**Comment by alewis** [comment]
It appears to be affecting performance in a real use case. I can't confidently say that it's affecting it in a significant way, because it is not clear to me whether the observed slowdown in that case is due to the matmuls or due to spurious extra Jit traces. It's good to hear that there's a speedup on the horizon, even if it's a distant one, though.

**Comment by mattjj** [comment]
To add a bit more background, which @hawkinsp explained to me, XLA:CPU is calling an Eigen kernel for F64 matmul, and that seems not to be competitive with whatever NumPy is using (MKL or OpenBLAS perhaps, depending on your installation). For F32 matmul, XLA:CPU is calling MKLDNN (via Eigen), which has good performance.

The compiler folks are on it!

**Comment by hawkinsp** [comment]
This is fixed!
