### ISSUE TITLE
multi-thread jax.grad fails on jax.lax.scan

### ISSUE THREAD

**Issue by thomaskeck** [google/jax#3843]
Calculating the gradient of a function in multiple independent threads sometimes causes jax to encounter errors of the form.

```
[...]
third_party/py/jax/core.py in pop(self, bottom)
    605   def pop(self, bottom: bool) -> None:
    606     if bottom:
--> 607       self.downward.pop()
    608     else:
    609       self.upward.pop()

IndexError: pop from empty list
```

In my original setup this happened only in 1% of the cases, here is a minimal example which reproduces the issue most of the time:

```
import concurrent
import jax
from jax import numpy as jnp

def unroll(param, sequence):
  def scan_f(prev_state, inputs):
    return prev_state, jax.nn.sigmoid(param * inputs)
  return jnp.sum(jax.lax.scan(scan_f, None, sequence)[1])

def run():
  return jax.grad(unroll)(jnp.array(1.0), jnp.array([1.0]))

# The more workers the more likely the issue appears. Using 1 worker works as expected.
n_workers = 20
with concurrent.futures.ThreadPoolExecutor(max_workers=n_workers) as e:
  futures = []
  for _ in range(n_workers):
    futures.append(e.submit(run))
  unused_results = [f.result() for f in futures]
```

**Comment by mattjj** [comment]
Thanks for finding this, and the excellent repro!

I suspect the `custom_jvp` on `jax.nn.sigmoid` may be an issue here; if I replace `jax.nn.sigmoid` with `jnp.sin` the issue goes away.

(By the way, I think `import concurrent` should be `import concurrent.futures`.)

**Comment by mattjj** [comment]
I further suspect that [this state saving/restoration](https://github.com/google/jax/blob/f6221a663ef6c311e986aeffcef7403be09e8b15/jax/custom_derivatives.py#L61) is not safe.

**Comment by mattjj** [comment]
Yes, that line is definitely not safe; it's swapping a module-level variable! We need to swap only thread-local variables.

I think I've got a fix.

**Comment by mattjj** [comment]
#3845 should fix!

**Comment by thomaskeck** [comment]
Wow, that was an incredibly fast fix! Thank you so much!
