### ISSUE TITLE
Prebuilt wheels compatible with GCP's Deep Learning VMs

### ISSUE THREAD

**Issue by kovasb** [google/jax#386]
Hi,

It would be fantastic to provide wheels compatible with GCP's Deep Learning VM images:
https://cloud.google.com/deep-learning-vm/docs/images

Currently the images are at python 3.5. 

Having prototyped my code in colab, I now want to scale it up to multiple v100s and this would be a very seamless path for me and others. But I'm hitting this issue of lack of a wheel for the platform. 

Thanks!

**Comment by hawkinsp** [comment]
Sure! Next time we do a wheel release I guess we can make wheels for Python 3.5, too. 

Obviously each extra Python version adds to the build time, but I guess there's a reasonable case to made for supporting 3.5, too, since Numpy 1.16 supports {2.7, 3.5, 3.6, 3.7}.

**Comment by hawkinsp** [comment]
I pushed new `jaxlib` wheels (0.1.8), including Python 3.5 wheels. Please try them out!

**Comment by kovasb** [comment]
Can confirm the new wheels work for GCP Deep Learning VM.
