### ISSUE TITLE
Hessian failing on np.clip, when clipping integers

### ISSUE THREAD

**Issue by EiffL** [google/jax#3861]
I'm encountering a problem with `jax.hessian` of functions including np.clip of some integers. It was working fine maybe a month ago, but seems broken in version 0.1.72. Here is a small example:
```python 
import jax
import jax.numpy as np

def test_fn(x):
    # We compute some indices that depend on x
    ind = np.argmin(x.reshape((-1,1)) - x.reshape((-1,1)),axis=1)

    # Ensures indices falls in some restricted range
    ind = np.clip(ind, 1, len(x) - 2)

    return np.sum(x[ind]**2)

test_x = np.linspace(0, 4, 5)

jax.hessian(test_fn)(test_x)
```
This fails with:
```
/usr/local/lib/python3.6/dist-packages/jax/lax/lax.py in _integer_pow_dtype_rule(x, y)
   2093   dtype = unop_dtype_rule(_identity, _int | _float | _complex, 'integer_pow', x)
   2094   if y < 0 and dtypes.issubdtype(dtype, onp.integer):
-> 2095     raise TypeError("Integers cannot be raised to negative powers, got "
   2096                     f"integer_pow({x}, {y})")
   2097   return dtype
TypeError: Integers cannot be raised to negative powers, got integer_pow(ShapedArray(int32[5]), -2)
```
I have the full error log and working example on this notebook: 
https://colab.research.google.com/drive/1JP_QDteLV0VHuzv_7DBMvpRZsHgy4JeY?usp=sharing

This is triggered as far as I can tell, by this line: 
https://github.com/google/jax/blob/5e91965723ac16dda361435d1bfcd4dc99201537/jax/lax/lax.py#L2289
But couldn't immediately work out how to fix the np.clip JVP, nor why it was working before.

The issue doesn't arise when the clipped quantities are cast to float, like so:
```
def test_fn2(x):
    # We compute some indices that depend on x
    ind = np.argmin(x.reshape((-1,1)) - x.reshape((-1,1)),axis=1).astype('float32')

    # Ensures indices falls in some restricted range
    ind = np.clip(ind, 1, len(x) - 2).astype('int')

    return np.sum(x[ind]**2)
```

I can investigate this further but thought I would raise the issue first, to see if maybe it was obvious to anyone :-)

**Comment by mattjj** [comment]
Thanks for the bug report and the clear repro! This seems like enough for us to go on.

One useful thing would be to run a git bisect to pin down which commit caused the error, but before doing that my a priori guess is #3140 could be related since it's semi-recent.

**Comment by mattjj** [comment]
Ah, it's not reproducing for me against github master. I think we just need to do a pypi release.

**Comment by mattjj** [comment]
Actually, it's also not reproducing against jax==0.1.73, which is [the current latest version on pypi](https://pypi.org/project/jax/).

Can you do a `pip install --upgrade jax`?

**Comment by EiffL** [comment]
Arf, my bad. Yes, just checked and works fine with 0.1.73. I had missed that release >.<

Thanks a lot for looking into it so fast, and sorry for the trouble!

**Comment by EiffL** [comment]
And I'm gonna go ahead and close it :-) Thanks again

**Comment by mattjj** [comment]
No worries at all, we love being able to help even for something as small as this, so please never hesitate to open issues! :D
