### ISSUE TITLE
XLA does not support complex value comparison for lax.reduce_window

### ISSUE THREAD

**Issue by long1216** [google/jax#3862]
When i try to implement the function from lax.reduce_window for making a max pooling effect from an array using jnp.max, below is the error i faced

>   File ".local/lib/python3.6/site-packages/jax/api.py", line 170, in f_jitted
    name=flat_fun.__name__, donated_invars=donated_invars)
  File ".local/lib/python3.6/site-packages/jax/core.py", line 1100, in call_bind
    outs = primitive.impl(fun, *args, **params)
  File ".local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 542, in _xla_call_impl
    *unsafe_map(arg_spec, args))
  File ".local/lib/python3.6/site-packages/jax/linear_util.py", line 221, in memoized_fun
    ans = call(fun, *args)
  File ".local/lib/python3.6/site-packages/jax/interpreters/xla.py", line 668, in _xla_callable
    compiled = backend.compile(built, compile_options=options)
RuntimeError: Unimplemented: complex comparison 'GE'

However, there is a precise result comes out from the function of jnp.max when dealing with complex number.  
>import jax.numpy as jnp
a = jnp.array([1+1j,2+0j,0+2j])
DeviceArray([1.+1.j, 2.+0.j, 0.+2.j], dtype=complex64)
jnp.max(a)
DeviceArray(2.+0.j, dtype=complex64)

The function i used is a wrapper of lax.reduce_window, and i am not good at coding, i am unable to reproduce the result just with lax.reduce_window. May i request for a feature for handling complex value in lax.reduce_window which workable with jnp.max? Thank you so much.

**Comment by mattjj** [comment]
Thanks for the request!

Which backend are you using (CPU/GPU/TPU)? It may be that it's implemented on some but not others.

**Comment by long1216** [comment]
I do use Jit in both CPU and GPU, it also pop up the same error as i mentioned above. Thank you so much.

**Comment by long1216** [comment]
Here is the result when i try to log from the input of lax.reduce_window. Hope this information would help. Thank you so much.

`<class 'jax.interpreters.ad.JVPTracer'> Traced<ShapedArray(complex64[128,16,16,16])>with<JVPTrace(level=1/1)>
  with primal = Traced<ShapedArray(complex64[128,16,16,16]):JaxprTrace(level=-1/1)>
       tangent = Traced<ShapedArray(complex64[128,16,16,16]):JaxprTrace(level=0/1)>`

**Comment by hawkinsp** [comment]
This is an old issue, but I think there's a more fundamental question: what do you mean by the `max` of two complex numbers? It doesn't seem to be a well-defined thing.

We could follow the numpy comparison behavior here, but honestly I think it's actually a bug in NumPy that comparison of floating point numbers is defined lexicographically. What do you think?
