### ISSUE TITLE
TypeError: cannot pickle 'jaxlib.pytree.PyTreeDef' object

### ISSUE THREAD

**Issue by bionicles** [google/jax#3872]
jax.experimental.optimizers.Adam returns an OptimizerState with a PyTreeDef, and the PyTreeDef isn't pickleable, so you can't send an optimizer state to a process in multiprocessing

made PR https://github.com/google/jax/pull/3868

**Comment by bionicles** [comment]
```
    state = optimizers.unpack_optimizer_state(state)
```

Another option, found here: [jax.experimental.optimizers docs](https://jax.readthedocs.io/en/latest/jax.experimental.optimizers.html#jax.experimental.optimizers.unpack_optimizer_state)

**Comment by hawkinsp** [comment]
Yes, that's right: if you're trying to pickle an optimizer state, you should probably use `optimizers.unpack_optimizer_state`.

**Comment by BillHuang2001** [comment]
Same issue here.
I tried to send PyTreeDef returned by tree_flatten to a process, so that process can unflatten a list.

**Comment by hawkinsp** [comment]
Looks like we fixed this some time ago! (https://github.com/google/jax/blob/e66f4e94c4841cca762b09a6147f12963f14cec1/tests/tree_util_test.py#L559)
