### ISSUE TITLE
mnist_vae.py "very slow compile"

### ISSUE THREAD

**Issue by wdevazelhes** [google/jax#3891]
Hi, thanks a lot for your awesome library!
I have ran into a bug running the mnist_vae.py example: 
It works fine locally on my computer (WSL linux), but on my server it raises the "slow_operation_alarm.cc" error: 
The file in ran was the mnist_vae.py in the examples folder, where I just changed the path for loading the images, so it shouldn't change the logic of the code (also, the same modified code worked locally).
Attached are the files generated by setting the flag recommended by the message "Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results." 
Do you have any idea of what could cause this ? Maybe some special setting/config on my server that I am not aware of? If needed, I can put all the exact code + the generated output in a same folder for reproduction

Thanks in advance!

I must also precise that in both cases the server and locally use the CPU
Also, the server's CPU has 32 cores, when locally I have only 8

More precisely, locally mnist_vae.py takes just a few seconds to compile and launch the iterations, but on the server it takes more than 45 min to compile

[foo.tar.gz](https://github.com/google/jax/files/4989569/foo.tar.gz)

**Comment by wdevazelhes** [comment]
I must also precise that in both cases the server and locally use the CPU

**Comment by wdevazelhes** [comment]
And in both cases I have GCC7.3.0 and python3.8.3, as well as the latest installs from an upgraded pip of jax

**Comment by wdevazelhes** [comment]
Also, the server's CPU has 32 cores when running htop, when locally I have only 8
Could the long compilation time be due to the high number of CPU ?

**Comment by wdevazelhes** [comment]
Also, the pb happens in jit mode and in non-jitted mode

**Comment by hawkinsp** [comment]
Hmmm... that's pretty odd. If as you say you are using CPU in both places, I'm wondering if we are perhaps hitting some sort of code generation bug that manifests on a particular CPU. Does it eventually terminate on the server or did you simply give up after 45 minutes? One hypothesis is some sort of nontermination behavior.

You should double check that you are using CPU in both cases; one signal for that is that JAX will print:
```
UserWarning: No GPU/TPU found, falling back to CPU.
```
if you are using CPU.

Can you verify that you are using an up to date `jax` and `jaxlib` and share the versions?

Can you also describe the OS versions of both platforms and share the output of `lscpu` on both machines?

**Comment by hawkinsp** [comment]
It's possible #3947 might help. Can you try it out as well?

**Comment by wdevazelhes** [comment]
Thanks a lot for your answer, and for looking into it, here are the answers to your questions:

> Does it eventually terminate on the server or did you simply give up after 45 minutes? One hypothesis is some sort of nontermination behavior.

Yes, it terminates on the server: it's just that the printed iterations did appear but after 45 min, after several messages "very slow compile". However, for the files that I attached, indeed IIRC that time I killed the process before the end of compilation, if you want I can include the files that I get for a complete terminated run ? 

> You should double check that you are using CPU in both cases; one signal for that is that JAX will print:

I confirm that I'm using CPU in both machines (I have "UserWarning: No GPU/TPU found, falling back to CPU." printed on each machine)

- lscpu on my machine: 
<details>

```
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
Address sizes:       36 bits physical, 48 bits virtual
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  2
Core(s) per socket:  4
Socket(s):           1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               142
Model name:          Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
Stepping:            10
CPU MHz:             2112.000
CPU max MHz:         2112.0000
BogoMIPS:            4224.00
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm pn                     i pclmulqdq dtes64 est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 movbe popcnt aes xsave osxsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefe                     tch fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt ibrs ibpb stibp ssbd
```

</details>

- lscpu on the server: 

<details>

```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-4627 v2 @ 3.30GHz
Stepping:              4
CPU MHz:               1778.704
CPU max MHz:           3300.0000
CPU min MHz:           1200.0000
BogoMIPS:              6599.49
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              16384K
NUMA node0 CPU(s):     0-7
NUMA node1 CPU(s):     8-15
NUMA node2 CPU(s):     16-23
NUMA node3 CPU(s):     24-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb kaiser tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm arat pln pts
```

</details>

For jax versions I have jax: `0.1.73` and jaxlib: `0.1.52` on both machines

I tried with the modification of #3947, but there is still the flag "very slow to compile" that appear on the server several times, and it still takes at least 40min to start printing the iterations

I hope this helps, let me know if you need more info

Thanks again,
