### ISSUE TITLE
Hard crash when no compatible cuda devices found

### ISSUE THREAD

**Issue by ajweiss** [google/jax#39]
Hi,

I've been playing around with this trying to get it to work with my GPU and I've been having some issues.  First things first though, do you think it would make sense to add a note to the README about which versions of Python are recommended/supported?  My understanding is that tensorflow doesn't yet support 3.7, is that true here?  What version do you use for development?  3.6?  2.7?   Also, any notes on supported versions of the CUDA libraries (cuda/cudnn)?  (the build times are a bit long, so knowing that I'm starting from a known working environment would be really helpful!)

Thanks!

**Comment by dougalm** [comment]
Good idea to add this to the readme. To start from a known-working build environment you could try [the dockerfile we use to build our wheels](https://github.com/google/jax/blob/master/build/Dockerfile). We build wheels for CUDA versions 9.0, 9.2 and 10.0, and Python 2.7 and 3 (I think it's 3.5 but I'm not sure). We mostly use 2.7 ourselves for development.

What sorts of issues did you run into? Did you try installing with pip instead of building yourself?

**Comment by ajweiss** [comment]
```
In [1]: import jax.numpy as np
   ...: from jax import random
   ...: 

In [2]: key = random.PRNGKey(0)
   ...: 
2018-12-09 16:27:18.979419: F external/org_tensorflow/tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA                                                                            
Aborted (core dumped)
```

I see this on 3.7 and 2.7 with cuda 10.0.130 and cudnn 7.

My GPU is old (capability level 3.0), maybe that has something to do with it?

...and I did poke around briefly with the pip installs, but it said they're experimental, my cuda/cudnn library versions are different as I'm on arch and I'm trying to use the distro packages for them, and most importantly, I'm interested in poking around with the source so I'd like to get it working from sources :)

I can ship stuff to the GPU from Tensorflow though, built from sources on 2.7.

**Comment by dougalm** [comment]
The build script assumes that CUDA and cuDNN are installed at `/usr/local/cuda`. This is configurable with `--cuda_path` and `--cudnn_path`. If you're using Arch, maybe pacman installs CUDA somewhere else, like `/opt`?

**Comment by ajweiss** [comment]
Yeah, I'm passing the path flags for the unusual library locations (/opt/cuda for cuda and /usr (yuck) for cudnn) and it seems to build and install ok.  The problem is the exception at runtime where it's complaining about not finding any devices.  Since it's dumping core it seems at the least there might be a bug there where it fails hard when no device is found, but I'd like to get a handle on why its not finding the device in the first place.  I'm rebuilding with 2.7, I'm going to poke around a bit...  There aren't any known limitations on minimum device/GPU capabilities?  I have a hunch that my device might be getting filtered out somewhere leading to what looks like a late failure...

**Comment by ajweiss** [comment]
It looks like this https://gist.github.com/ajweiss/f93e426a56a992d11822a4e309ba37c8 will stop the hard crashes.  Is there any reason why GetOrCreateLocalClient() wasn't wrapped with the StatusOr stuff to begin with [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/local_computation_builder.cc#L101)?  If it's useful, I can submit a PR to tensorflow since this is in XLA.  Also, how do I run the test suites?

**Comment by hawkinsp** [comment]
This issue should now be fixed, if you use a sufficiently new jaxlib. Until we make another release of the jaxlib wheels, this means rebuilding jaxlib from source.
