### ISSUE TITLE
triangular_solve transposition is flipped

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#3931]
`triangular_solve` is solving `L^T.x=b` when it says it's solving `L.x=b` and vice versa.

``` python
def test_triangular_solve():
    from jax.lax_linalg import triangular_solve
    from scipy.linalg import solve_triangular
    import jax.numpy as jnp
    ndims = 2
    A = jnp.diag(jnp.ones(ndims))
    A = jnp.where(A == 0., 0.95, A)
    b = jnp.ones(ndims)
    L = jnp.linalg.cholesky(A)
    assert jnp.all(L @ L.T == A)

    x = jnp.linalg.solve(L, b)
    print("Solving L.x  = b with scipy")
    print("x should be {}".format(x))
    scipy_x = solve_triangular(L, b, lower=True)
    assert jnp.all(scipy_x == x)
    print("Works as expected!")

    print("Now note JAX's solution to L^T.x = b corresponds to scipy's L.x = b")
    jax_x = triangular_solve(L, b, lower=True, transpose_a=True)
    assert jnp.all(jax_x==scipy_x)
    print("Likewise, JAX's solution to L.x = b corresponds to scipy's L^T.x = b")
    assert jnp.all(triangular_solve(L, b, lower=True) == solve_triangular(L, b, lower=True, trans=1))
    
    print("Note, I have not tested for the L^H.x=b case.")
```

**Comment by mattjj** [comment]
Thanks for raising this! Just to clarify, is the `jax.scipy.linalg.triangular_solve` API consistent with `scipy.linalg.solve_triangular`? We'd certainly hope that is true, though `jax.lax_linalg.triangualr_solve` need not be consistent with it (we'd have to look at what the API of the `lax_linalg` version is meant to be).

**Comment by mattjj** [comment]
It looks like [our test of `jax.scipy.linalg.solve_triangular`](https://github.com/google/jax/blob/master/tests/linalg_test.py#L1090-L1138) does not actually check against scipy AFAICT...

**Comment by Joshuaalbert** [comment]
Hi @mattjj I think I found it. `left_side=False` by default in `jax.lax_linalg.triangular_solve`. There's no explanation of what that means, but `jax.scipy.linalg.solve_triangular` sets it to `True` and then it works as expected. Also, yes its API is the same as scipy's. Lesson here is to not use `lax_linalg` things unless you have to in which case make sure to figure out what the kwargs do.

**Comment by mattjj** [comment]
I find default args to be pretty pernicious in general! Thanks for looking into this.
