### ISSUE TITLE
How to save the params of a jax.experimental.optimizers? 

### ISSUE THREAD

**Issue by BoyuanJackChen** [google/jax#3937]
I built a model and created an adam optimizer from jax.experimental. I wonder how should I save the params so I can keep the training progress for the next time. Thanks for your time in advance! 
```
from jax.experimental import optimizers, stax
from jax.experimental.stax import Dense, FanInConcat, FanOut, Identity, Relu
from jax.nn import relu, sigmoid

def build_model(D: int = 8, W: int = 256) -> Any:
    dense_block = lambda block_brep=1, W=W: [Dense(W), Relu] * 1    # * block_rep
    sub_net = stax.serial(*dense_block(5))
    model = stax.serial(
        FanOut(2),
        stax.parallel(sub_net, Identity),
        FanInConcat(-1),
        *dense_block(3),
        Dense(4))
    return model

key = random.PRNGKey(0)
init_fn, model = build_model()
_, model_params = init_fn(key, input_shape=(3 + 3 * 2 * L_embed,))
opt_init, opt_update, get_params = optimizers.adam(step_size=5e-4, b1=0.9, b2=0.999, eps=1e-08)
opt_state = opt_init(maml_params)
```
My attempt was dumping the opt_state variable with picke: 
```
with open("opt_state.txt", "wb") as fp:
    pickle.dump(opt_state, fp)
```
But it says "TypeError: can't pickle jaxlib.pytree.PyTreeDef objects". So I guess there should be some jax-intrinsic ways to save the values of its types.

**Comment by hawkinsp** [comment]
Does pickling the output of `optimizers.pack_optimizer_state` do what you want?

**Comment by BoyuanJackChen** [comment]
> Does pickling the output of `optimizers.unpack_optimizer_state` do what you want?

Yes it does! Thanks.

**Comment by BoyuanJackChen** [comment]
> Does pickling the output of `optimizers.unpack_optimizer_state` do what you want?
