### ISSUE TITLE
jnp.right_shift incorrect on unsigned ints

### ISSUE THREAD

**Issue by JuliusKunze** [google/jax#3952]
It looks like ~~`lax.shift_right_arithmetic`~~ `jnp.right_shift` incorrectly treats unsigned ints as signed:

```python
import numpy as np
from jax import lax, numpy as jnp
args = np.uint8(0b10000000), np.uint8(2)
print(f"{np.right_shift(*args):#010b} (expected)")
print(f"{jnp.right_shift(*args):#010b}")
print(f"{lax.shift_right_arithmetic(*args):#010b}")
```

results in

```
0b00100000 (expected)
0b11100000
0b11100000
```

Other unsigned int types produce the same issue. Tests for `lax.shift_right_arithmetic` were missing, they will be added with https://github.com/google/jax/pull/3923.

**Comment by hawkinsp** [comment]
I think that's working as intended. `shift_right_arithmetic` does an arithmetic (signed) shift irrespective of the type. If you want a logical shift you should use `shift_right_logical`. `lax` follows XLA in making the type of the shift independent of the carrier type.

**Comment by JuliusKunze** [comment]
@hawkinsp In that case, shouldn't `jnp` resolve to `shift_right_logical`  for unsigned ints?

**Comment by jakevdp** [comment]
Yes, the jnp behavior should match the np behavior when possible. A PR with a fix & tests would be a great contribution!
