### ISSUE TITLE
Wrong jnp.transpose behaviour for wrong axis length

### ISSUE THREAD

**Issue by GeorgOstrovski** [google/jax#3954]
Like the numpy counterpart, `jnp.transpose` correctly throws an error when the axis length is different from the input's number of dimensions and the input is a **numpy** array: 
```python
jnp.transpose(np.zeros((2,3,4)), (1, 0))
>  TypeError: transpose permutation isn't a permutation of operand dimensions, got permutation (1, 0) for operand shape (2, 3, 4).
```
It however fails to do so when the input is a **`jax.numpy`** array: 
```python
jnp.transpose(jnp.zeros((2,3,4)), (1, 0))
> DeviceArray([[0., 0.], [0., 0.], [0., 0.]], dtype=float32)
```

**Comment by hawkinsp** [comment]
I think this might be related to the lazy expression implementation for `jnp.zeros`. However, I think it will shortly be a moot point because we plan to delete the laziness support shortly after enabling omnistaging.

**Comment by GeorgOstrovski** [comment]
Ah indeed - it's not a problem for `jnp.transpose(jnp.array(np.zeros((2, 3, 4))), (1, 0))`. Thanks for the clarification!
