### ISSUE TITLE
clarification to README

### ISSUE THREAD

**Issue by mikkokotila** [google/jax#396]
First, thanks a lot for this amazing package. 

I noted that in the README.md there is an example that says: 

```
In [5]: print(np.dot(x, x.T) / 2)  # fast!
[[  2.52727051e+03   8.15895557e+00  -8.53276134e-01 ...,  # ...

In [6]: print(np.dot(x, x.T) / 2)  # even faster!
[[  2.52727051e+03   8.15895557e+00  -8.53276134e-01 ...,  # ...
```
Given that both examples are exactly the same, maybe there is a mistake here in saying the other is "even faster". 

Thanks again for JAX, I feel that this will be a gift that keeps giving. Bonus points for a funky and very well crafted logo!

**Comment by mattjj** [comment]
Thanks for the kind words!

Actually the idea behind that readme line is that on the second call some JIT-compiled operations are cached, so the second call to them saves on compile time (and things like autotuning).

Does that make sense? Maybe we could add something to the readme to clarify what that line means.
