### ISSUE TITLE
Cannot use static scalar arrays in comparison when using omnistaging

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#3974]
I understand that omnistaging is about staging out as much as possible to XLA, but this leads to some (IMO) unintuitive corner cases with `static_argnums`.

Here is an IPython session showing this:

```python
>>> import jax
>>> import jax.numpy as np

>>> def foo(n):
...     if n > 1:
...         return np.ones(1)
...     return np.zeros(1)

# without omnistaging
>>> jax.jit(foo, static_argnums=(0,))(1)
DeviceArray([0.], dtype=float32)

>>> jax.jit(foo, static_argnums=(0,))(np.ones(1))
DeviceArray([0.], dtype=float32)

# with omnistaging
>>> jax.config.enable_omnistaging()

>>> jax.jit(foo, static_argnums=(0,))(1)
DeviceArray([0.], dtype=float32)

>>> jax.jit(foo, static_argnums=(0,))(np.ones(1))
---------------------------------------------------------------------------
ConcretizationTypeError                   Traceback (most recent call last)
<ipython-input-8-e2263703d9a7> in <module>
----> 1 jax.jit(foo, static_argnums=(0,))(np.ones(1))

~/codes/jax/jax/api.py in f_jitted(*args, **kwargs)
    169     flat_fun, out_tree = flatten_fun(f, in_tree)
    170     out = xla.xla_call(flat_fun, *args_flat, device=device, backend=backend,
--> 171                        name=flat_fun.__name__, donated_invars=donated_invars)
    172     return tree_unflatten(out_tree(), out)
    173

~/codes/jax/jax/core.py in bind(self, fun, *args, **params)
   1136
   1137   def bind(self, fun, *args, **params):
-> 1138     return call_bind(self, fun, *args, **params)
   1139
   1140   def process(self, trace, fun, tracers, params):

~/codes/jax/jax/core.py in call_bind(primitive, fun, *args, **params)
   1494     tracers = map(top_trace.full_raise, args)
   1495     with maybe_new_sublevel(top_trace):
-> 1496       outs = primitive.process(top_trace, fun, tracers, params)
   1497     return map(full_lower, apply_todos(env_trace_todo(), outs))
   1498

~/codes/jax/jax/core.py in process(self, trace, fun, tracers, params)
   1139
   1140   def process(self, trace, fun, tracers, params):
-> 1141     return trace.process_call(self, fun, tracers, params)
   1142
   1143   def post_process(self, trace, out_tracers, params):

~/codes/jax/jax/core.py in process_call(self, primitive, f, tracers, params)
    580
    581   def process_call(self, primitive, f, tracers, params):
--> 582     return primitive.impl(f, *tracers, **params)
    583   process_map = process_call
    584

~/codes/jax/jax/interpreters/xla.py in _xla_call_impl(fun, device, backend, name, donated_invars, *args)
    528 def _xla_call_impl(fun: lu.WrappedFun, *args, device, backend, name, donated_invars):
    529   compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
--> 530                                *unsafe_map(arg_spec, args))
    531   try:
    532     return compiled_fun(*args)

~/codes/jax/jax/linear_util.py in memoized_fun(fun, *args)
    222       fun.populate_stores(stores)
    223     else:
--> 224       ans = call(fun, *args)
    225       cache[key] = (ans, fun.stores)
    226     return ans

~/codes/jax/jax/interpreters/xla.py in _xla_callable(fun, device, backend, name, donated_invars, *arg_specs)
    593   abstract_args, arg_devices = unzip2(arg_specs)
    594   if config.omnistaging_enabled:
--> 595     jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, abstract_args)
    596     if any(isinstance(c, core.Tracer) for c in consts):
    597       raise core.UnexpectedTracerError("Encountered an unexpected tracer.")

~/codes/jax/jax/interpreters/partial_eval.py in trace_to_jaxpr_final(fun, in_avals)
   1065     master.source_info = fun_sourceinfo(fun.f)  # type: ignore
   1066     master.jaxpr_stack = ()  # type: ignore
-> 1067     jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, master, in_avals)
   1068     del master
   1069   return jaxpr, out_avals, consts

~/codes/jax/jax/interpreters/partial_eval.py in trace_to_subjaxpr_dynamic(fun, master, in_avals)
   1046     trace = DynamicJaxprTrace(master, core.cur_sublevel())
   1047     in_tracers = map(trace.new_arg, in_avals)
-> 1048     ans = fun.call_wrapped(*in_tracers)
   1049     out_tracers = map(trace.full_raise, ans)
   1050   jaxpr, out_avals, consts = frame.to_jaxpr(in_tracers, out_tracers)

~/codes/jax/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    148     gen = None
    149
--> 150     ans = self.f(*args, **dict(self.params, **kwargs))
    151     del args
    152     while stack:

<ipython-input-3-2538d79ca30d> in foo(n)
      1 def foo(n):
----> 2     if n > 1:
      3         return np.ones(1)
      4     return np.zeros(1)
      5

~/codes/jax/jax/interpreters/partial_eval.py in __bool__(self)
    851
    852   def __bool__(self):
--> 853     self._concretization_error('__bool__')
    854
    855   def _concretization_error(self, name):

~/codes/jax/jax/interpreters/partial_eval.py in _concretization_error(self, name)
    861            "\n\n" + "\n\n".join(msgs) + "\n\n"
    862            "See the above traceback for where this tracer was encountered.")
--> 863     raise core.ConcretizationTypeError(msg)
    864
    865   def _progenitor_messages(self):

ConcretizationTypeError: Abstract tracer value passed to __bool__ for which a concrete value is required.
While tracing the function foo at <ipython-input-3-2538d79ca30d>:1, this tracer originated from using JAX operations on these lines:

  operation c:bool[1] =
  gt a:float32[1] b:float32[]
    from line <ipython-input-3-2538d79ca30d>:2 (foo)

See the above traceback for where this tracer was encountered.
```

So without omnistaging, JAX can compare a scalar, static device array to a float just fine, but with omnistaging it gives this confusing error message.

JAX version is master@8a8bb702d29c8036807d53b6110fc2fe2051559a

**Comment by mattjj** [comment]
I wonder if this is an interaction between the laziness of `np.ones` and omnistaging...

**Comment by hawkinsp** [comment]
It seems likely the the `<` operator is being staged?

@dionhaefner Could you try passing a classic NumPy array here instead of a JAX NumPy array? We're encouraging the convention

```
import jax.numpy as jnp
import numpy as np
```

and if you want something not to be included in the trace, you can just use classic NumPy (`np`).

**Comment by dionhaefner** [comment]
Sorry for the `np` / `jnp` confusion. Yes, the `>` is being staged, but it wasn't obvious to me that this should be a problem. The input is declared as static, so the comparison should be possible (despite what the error message claims it is not an abstract tracer).

As you suggested, this version of the test function works:

```python
import jax.numpy as jnp
import numpy as np

def foo(n):
    if np.array(n) > 1:
        return jnp.ones(1)
    return jnp.zeros(1)
```

**Comment by hawkinsp** [comment]
That's precisely what omnistaging does. Previously we would only stage things that had a data dependency on a tracer. With omnistaging, we stage all JAX operations within the dynamic scope of the `jit`. This means that we will now stage things where we previously would not, which is very good in some cases (notably: it avoids constant folding away things like your MPI ops!) but perhaps surprising if you are used to the old data-dependency behavior.

**Comment by dionhaefner** [comment]
Maybe it would help to clarify when `static_argnums` should be used with omnistaging. I took it as a way of saying "I want constant folding to happen on this object", but apparently that's not how it works with device arrays.

**Comment by mattjj** [comment]
Indeed the `jit` docstring is incorrect post-omnistaging:

> static_argnums (Union[int, Iterable[int]]) – An int or collection of ints specifying which positional arguments to treat as static (compile-time constant). **Operations that only depend on static arguments will be constant-folded in Python (during tracing), and so the corresponding argument values can be any Python object.** Calling the jitted function with different values for these constants will trigger recompilation. If the jitted function is called with fewer positional arguments than indicated by static_argnums then an error is raised. Arguments that are not arrays or containers thereof must be marked as static. Defaults to ().

Emphasis mine.

We should change that emphasized sentence to be something like: "The corresponding argument values can be any hashable Python object. Original NumPy operations on them are effectively constant-folded during tracing, while jax.numpy operations are always staged out in the dynamic context of applying a jit-decorated function."

**Comment by oliverdutton** [comment]
Is there any way to specify an jax array for constant folding?

It has quite significant performance penalties in some cases. I've jitted a random array (I know on consecutive runs this just gives the same array over and over again), so the overall computation with folding is just multiplying by a known scalar. 

I have seen there is a private method called [partial_eval](https://github.com/google/jax/blob/main/jax/interpreters/partial_eval.py) but there's no documentation on how to use it.


```python
import tensorflow as tf
from jax import jit, random, numpy as jnp
from functools import partial

x = 2
x_tf = tf.constant(x)
x_jax = jnp.array(x)

@jit
def jax_fn(x):
    y = random.randint(random.PRNGKey(0), (1000,1000), 0, 100)
    y2 = y @ y
    x2 = jnp.sum(y2)*x
    return x2

@partial(tf.function, jit_compile=True)
def tf_fn(x):
    y = tf.constant(random.randint(random.PRNGKey(0), (1000,1000), 0, 100))
    y2 = y @ y
    x2 = tf.reduce_sum(y2)*x
    return x2

# Compile
jax_fn(x_jax).block_until_ready()
tf_fn(x_tf)

%timeit jax_fn(x_jax).block_until_ready()
%timeit tf_fn(x_tf)
```
![image](https://user-images.githubusercontent.com/44170519/145984089-fa55ef0a-4e21-4f5e-8b7a-335d5de34bb6.png)

**Comment by dionhaefner** [comment]
If I understand correctly then you should use vanilla NumPy to force constant folding:

```python
import numpy as onp

@jit
def jax_fn(x):
    y = onp.random.randint(0, 100, size=(1000,1000))
    y2 = y @ y
    x2 = onp.sum(y2)*x
    return x2
```

**Comment by oliverdutton** [comment]
Thanks, I agree that does work. 

However, a pure JAX way should exist. I feel numpy should not be in JAX codebases.

I think towards cases where you want the folding to be optional.

I suppose to support both the folded and not folded versions the module can be switched, like
```python3
fold_this_code=True

optionalnp =numpy if fold_this_code else jax.numpy
@jit
def jax_fn(x):
    y = optionalnp.random.randint(0, 100, size=(1000,1000))
    y2 = y @ y
    x2 = optionalnp.sum(y2)*x
    return x2
```

This just seems to ugly, and requires the person to hand trace the variable to fold through the functions, rather than simply marking a jax array to be a ConcreteArray where values are known.

**Comment by dionhaefner** [comment]
You could also use a closure, which may be marginally more elegant:

```python
def make_fun(fold=True)
    @jit
    def jax_fn(x):
        y = onp.random.randint(0, 100, size=(1000,1000))
        if fold:
            y = jnp.asarray(y)
        y2 = y @ y
        x2 = y2.sum()*x
        return x2
```

> I feel numpy should not be in JAX codebases.

From what I've read the JAX devs disagree :)

**Comment by mattjj** [comment]
@oliverdutton I recommend that any code you don't want to be staged out should be moved outside `jit`-decorated functions. You can use lexical closure or `jit`'s `static_argnums`. For example:

```python
import jax
import jax.numpy as jnp
from jax import random

y = random.randint(random.PRNGKey(0), (1000,1000), 0, 100)

@jit
def jax_fn(x):
    y2 = y @ y
    x2 = jnp.sum(y2)*x
    return x2
```

That said, while that's my preferred mechanism, there's also a context manager which says "be sure to constant fold everything evaluated here, and error otherwise." It's currently called `jax.core.eval_context`, but we will make it a public API, probably called `jax.ensure_compile_time_eval`; see #7987.

```python
import jax
import jax.numpy as jnp
from jax import random


@jit
def jax_fn(x):
    with jax.core.eval_context():  # temporary name, see #7987
        y = random.randint(random.PRNGKey(0), (1000,1000), 0, 100)
    y2 = y @ y
    x2 = jnp.sum(y2)*x
    return x2
```

We don't want to do anything automatic here because there are several things that a programmer could intend. For example, a programmer might want the creation of a large constant to be staged out to the XLA computation; then it might be fused with its consumers and perhaps never materialized at all. That programmer might also want to avoid any trace/compile-time host-to-device transfers. Or alternatively the programmer might want to constant-fold but ensure it's done efficiently on the host CPU on small arrays (in which case using original `numpy` may be a good idea, especially for e.g. computations on small integer arrays representing the shapes of other arrays). Or maybe the programmer wants to do the constant folding on an accelerator. We want the programmer to be explicit about which of these is intended.

The 'default' behavior of `jit` is to stage out all `jnp` functions. We did that because it was the overwhelmingly common case for our main users, and also because it's the simplest policy (since any alternative would fold _some_ things automatically and not others, and so one has to explain which things exactly get folded). But all the other options are available as well: using the original `numpy`, or using `jax.ensure_compile_time_eval`.

All that said, my recommended way to write what you explained is still to use lexical closure or `static_argnums`. No new APIs needed!

**Comment by mattjj** [comment]
I just noticed that the code in the OP actually works now! So I'm going to close this issue.

```python
In [7]: jax.jit(foo, static_argnums=(0,))(0)
Out[7]: DeviceArray([0.], dtype=float32)

In [8]: jax.jit(foo, static_argnums=(0,))(2)
Out[8]: DeviceArray([1.], dtype=float32)
```

**Comment by oliverdutton** [comment]
Thank you for the fast and full reply. I am completely satisfied. I also screwed up, I thought that lexical closure (or via static_argnums) wasn't folding Jax arrays.

I see how you can get cases such as 

```python
@jit
def jax_fn(x):
    y = jnp.array(3)
    y_out = jnp.broadcast(HUGE_SHAPE, y)
    do stuff
```
don't incur that transfer you mentioned.

Sorry, and again thank you
