### ISSUE TITLE
Prevent statements with side effects from being re-ordered

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#3976]
With `mpi4jax`, we now run into a problem when doing send-recv operations like this one:

```python
if rank == 0:
    # send, then receive
    send(send_arr, dest=1, comm=rs.mpi_comm)
    recv_arr = recv(recv_arr, source=other_proc, tag=10, comm=rs.mpi_comm)
else:
    # receive, then send
    recv_arr = recv(recv_arr, source=other_proc, tag=10, comm=rs.mpi_comm)
    send(send_arr, dest=0, comm=rs.mpi_comm)
```

This code deadlocks because apparently the send and recv operations are re-ordered on one of the processes, despite using omnistaging and `has_side_effect` on the custom XLA call.

Do we still need to use tokens and fake data-dependencies to fix this, or is there a more elegant way?

**Comment by mattjj** [comment]
The omnistaging change ensures that we trace the Python to a jaxpr in a way that preserves operation ordering, but I suspect we still need to thread tokens in the XLA HLO lowering. That is, JAX now has the tools to avoid reordering without user-level tokens, but XLA may still reorder things.

@hawkinsp does that sound right to you?

**Comment by hawkinsp** [comment]
Yes, in order for XLA to maintain order, you introduce a data dependency. Tokens are the mechanism that XLA uses to represent a "dummy" dependency.

It seems likely that we could teach JAX to automatically thread tokens through these kinds of effectful ops, however?

**Comment by mattjj** [comment]
Yeah that's my thinking too!

**Comment by dionhaefner** [comment]
Bummer, I thought the `has_side_effect=True` argument to `ops.CustomCall` would be enough to prevent this, but apparently it just prevents XLA from optimizing it away completely.

Some automatic token mechanism would be great, and should be the last puzzle piece we need.

**Comment by hawkinsp** [comment]
I note that this turns out to be a problem for our existing (non-MPI) collectives, especially on GPU. JAX has some (very early) support for multi-host GPU collectives via NCCL, but one of the things that can go wrong is that XLA may choose to order collectives differently on different machines. This isn't a problem on TPU where our collective support originated because XLA is deterministic on that platform, but on GPU things like convolution autotuning mean that the compiler's output may depend on, say, GPU's thermal state at compile time during autotuning.

I'm a bit surprised about the nondeterminism on CPU; we could perhaps look into that also if you have a reproduction. I don't think it's intentional that XLA has nondeterministic behavior on CPU, and another way we could fix the problem would be to fix the source of nondeterminism.

By the way, we should probably figure out a mechanism to hook up things like `psum` to your MPI implementation.

**Comment by dionhaefner** [comment]
In my example, the behavior is not really nondeterministic, because the different processes see different code. One process needs to send a message, the other needs to receive it, then switch roles (as in https://github.com/google/jax/issues/3976#issue-674254719), otherwise you deadlock (e.g. if both send at the same time).

There is an atomic `Sendrecv` primitive in MPI where this is not a problem, but in general, implementations using MPI rely heavily on sends and receives not being reordered. Real nondeterminism makes this a lot worse / more unpredictable, of course.

**Comment by dionhaefner** [comment]
I think there is a silver lining here in that only the stateful calls cannot be re-ordered *relative to each other*. So re-orderings like `(pure_func, side_effect_func_1, pure_func, side_effect_func_2) -> (pure_func, pure_func, side_effect_func_1, side_effect_func_2)` would be no problem (only if `side_effect_func_1` and `side_effect_func_2` are switched).

So any token mechanism can focus on those few stateful calls and doesn't need to touch anything else.

**Comment by gnecula** [comment]
I had a similar problem in the implementation of experimental/host_callback:id_tap. The JAXPR rewriter in that module threads a token through control-flow and nested JAXPRs. I think that it should not be hard to extend it to handle a configurable set of primitives. 

I was planning to extract the rewriter into its own library, but won't have time to work on this for the next couple of weeks. How urgent is this for you?

**Comment by dionhaefner** [comment]
That sounds great. For now I introduced a manual token mechanism that seems to work fine:

```python
if rank == 0:
    # send, then receive
    token = send(send_arr, dest=1, comm=rs.mpi_comm)
    recv_arr, token = recv(recv_arr, source=other_proc, tag=10, comm=rs.mpi_comm, token=token)
else:
    # receive, then send
    recv_arr, token = recv(recv_arr, source=other_proc, tag=10, comm=rs.mpi_comm)
    token = send(send_arr, dest=0, comm=rs.mpi_comm, token=token)
```

So it's not that urgent, but it would of course be better to get rid of that boilerplate altogether.

**Comment by gnecula** [comment]
If that works for you, fine. Will you need to put this kind of code inside control-flow primitives? That is when passing the token around becomes more bothersome.

**Comment by dionhaefner** [comment]
Good point. I don't think that's a big use case, but I could imagine some edge cases where passing around the token becomes a hassle.

Looking forward to your rewriter library!

**Comment by PhilipVinc** [comment]
@gnecula any progress on that front? Did you manage to separate the rewriter into a library?

**Comment by gnecula** [comment]
No progress yet. However, handling effectfull operations is still on our TODO list though.

**Comment by dionhaefner** [comment]
Looks like effectful operations have landed in JAX main a while ago. Thanks!
