### ISSUE TITLE
Jax jitted function doesn't raise "Out of bound error" and returns incorrect output

### ISSUE THREAD

**Issue by fischcheng** [google/jax#3989]
When I tried benchmarking the code using `scipy.ndimage.map_coordinates` vs `jax.scipy.ndimage.map_coordinates`, I found an "out of bound" error that's not raised when using jax. 

I found a similar issue https://github.com/google/jax/issues/1451, but here is a much simpler code snippet to reproduce. Switching off the `@jit`, the code fails, and switching `np` to `jax.numpy` the code will run through. 

```python
data = np.ones((100,100))
u = np.random.randn(50, 30)

@jit
def test_should_fail(data, u):
    # Wrap the actual field advection step
    nx, ny = data.shape
    ii, jj = np.mgrid[:nx, :ny]
    coords_x = ii - u[ii, jj]
    return coords_x

test_should_fail(data, u)
```

The code should fail because `u[ii, jj]` is out of bound since its shape is much smaller than `data`.

**Comment by jakevdp** [comment]
This is expected behavior for JAX; see [Common Gotchas: Out-of-bounds Indexing](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Out-of-Bounds-Indexing)
