### ISSUE TITLE
Automatic dtype promotion in loops

### ISSUE THREAD

**Issue by shoyer** [google/jax#3991]
JAX's functional control flow operators (`scan`, `while_loop`, etc) require the exact same type for input and output values.

This is of course required by the low-level loops implemented XLA, but it requires annoying explicit casting sometimes. In other cases (e.g., https://github.com/google/jax/issues/3986) it's non-trivial to resolve, because the loop that needs type promotion happens not in user code, but in the JAX generated backwards pass. This is likely to become even more annoying once float64 gets turned on by default, just because users will encounter type promotion more often.

One way to fix this would be to make loops automatically promote input dtypes to match output dtypes. This is possible in JAX because we have abstract evaluation rules. We could calculate a fixed point of dtype promotion for input and output arrays, similar to what already do for calculating a fixed point of batched axes.

cc @jakevdp

**Comment by mattjj** [comment]
I think @jakevdp fixed this at some point!
