### ISSUE TITLE
Broadcasting minval and maxval in jax.random.uniform

### ISSUE THREAD

**Issue by ethanluoyc** [google/jax#4033]
Hi JAX team!

Currently, it seems that broadcasting of minval and maxval in `jax.random.uniform` is not supported.
https://github.com/google/jax/blob/a169743f64e9ddf826cdad5c225e3e18a980a1db/jax/random.py#L343

In numpy, this is supported
```python
np.random.uniform(low=jnp.zeros(2), high=jnp.ones(2), size=(10,2))
```

In JAX, this will result in a TypeError `TypeError: max got arrays of different rank: (2,), (10, 2).`.

```python
jax.random.uniform(
    key=jax.random.PRNGKey(42),
    shape=(10,2), 
    minval=jnp.zeros(2), 
    maxval=jnp.ones(2))
```

A manual broadcasting will fix this issue
```
jax.random.uniform(
    key=jax.random.PRNGKey(42),
    shape=(1,2), 
    minval=jnp.broadcast_to(jnp.zeros(2), (1,2)), 
    maxval=jnp.broadcast_to(jnp.ones(2), (1,2)))
```

Is JAX's behaviour intended? If not, I am happy to send a PR fixing this.

**Comment by jakevdp** [comment]
I think you're correct that these should broadcast. See for example the `randint` documentation, which explicitly calls this out:
```python
 Args:
    key: a PRNGKey used as the random key.
    shape: a tuple of nonnegative integers representing the shape.
    minval: int or array of ints broadcast-compatible with ``shape``, a minimum
      (inclusive) value for the range.
    maxval: int or array of ints broadcast-compatible with ``shape``, a maximum
      (exclusive) value for the range.
```
Unfortunately, here as well the code does not behave as advertised:
```
import jax.numpy as jnp
from jax import random
random.randint(random.PRNGKey(0), (10, 2), jnp.array([0, 1]), jnp.array([1, 2]))
# TypeError: rem got arrays of different rank: (10, 2), (2,).
```
In both cases I think we should perform the broadcasting when necessary.

A PR would be great - thanks!
