### ISSUE TITLE
Noisy CUDA_ERROR_INVALID_VALUE warning for 0-element tensors outside @jit 

### ISSUE THREAD

**Issue by jonasrauber** [google/jax#406]
```
import jax
x = jax.lax.fori_loop(0, 10, (lambda i, x: x + 1), 0)
```

fails with the following error (with `jit` it works fine):

```
2019-02-19 15:41:04.314945: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:844] failed to allocate 0B (0 bytes) from device: CUDA_ERROR_INVALID_VALUE: invalid argument
```

**Comment by hawkinsp** [comment]
Thanks for the report! 

I'm pretty sure that https://github.com/tensorflow/tensorflow/commit/cf1e86da2bf6047e1ee353db871d42f5fd0d8287 fixed the error message although that change hasn't made its way into a Jaxlib release yet.

While the error message is definitely noisy and something we should fix, it should be benign; the loop should still work and compute the right thing. Is that the case?

**Comment by jonasrauber** [comment]
Looks like it still gives the correct result, yes…

**Comment by mattjj** [comment]
Since this is a warning message problem, should we close this issue?

**Comment by hawkinsp** [comment]
Let's close the issue when we update the jaxlib XLA version to include the fix.

**Comment by hawkinsp** [comment]
PR #411 should fix this, but it requires building jaxlib from source (or waiting until we make another jaxlib wheel release.)
