### ISSUE TITLE
Reverse-mode differentiation rule for 'sub' not implemented

### ISSUE THREAD

**Issue by hughsalimbeni** [google/jax#407]
I get an error with the gradients of multivariate_normal.logpdf wrt the covariance (input and mean are fine). For example, this

```python
import jax.numpy as np
from jax import grad
from jax.scipy.stats import multivariate_normal

f = lambda x: multivariate_normal.logpdf(np.zeros(1), np.zeros(1), np.ones((1, 1))*x)
grad(f)(1.)  # fails
```

gives the error:

```
Traceback (most recent call last):
  File "[...]/jax/jax/interpreters/ad.py", line 149, in get_primitive_transpose
    return primitive_transposes[p]
KeyError: sub

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]", line 43, in <module>
    print(grad(f)(1.))  # fails
  File "[...]/jax/jax/api.py", line 149, in grad_f
    ans, g = value_and_grad_f(*args, **kwargs)
  File "[...]/jax/jax/api.py", line 186, in value_and_grad_f
    g = vjp_py(onp.ones((), onp.result_type(ans)))
  File "[...]/jax/jax/api_util.py", line 56, in apply_jaxtree_fun
    ans = fun(*args)
  File "[...]/jax/jax/api.py", line 457, in out_vjp_packed
    return out_vjp(cotangent_in)
  File "[...]/jax/jax/interpreters/ad.py", line 78, in vjp_
    _, arg_cts = backward_pass(jaxpr, consts, (), dummy_primal_and_ct)
  File "[...]/jax/jax/interpreters/ad.py", line 135, in backward_pass
    cts_out = get_primitive_transpose(eqn.primitive)(ct_in, *invals, **eqn.params)
  File "[...]/jax/jax/interpreters/ad.py", line 152, in get_primitive_transpose
    "Reverse-mode differentiation rule for '{}' not implemented".format(p))
NotImplementedError: Reverse-mode differentiation rule for 'sub' not implemented
```

Also, I notice that the multivariate_normal density is implemented with matrix inverses and determinant rather than the [usual](https://github.com/scipy/scipy/blob/d681fc87f42bbc237d5b7e98fbfbfb5e3a51ae13/scipy/stats/_multivariate.py#L495) more efficient formulation in terms of the square root cov. Is there a reason for this?

**Comment by hawkinsp** [comment]
PR #410 fixes your immediate issue.

As for the less efficient formulation, I suspect the reason is that the formulation in scipy uses a symmetric eigendecomposition, which we only added to JAX relatively recently (https://jax.readthedocs.io/en/latest/jax.scipy.html#jax.scipy.linalg.

PRs to use the more efficient formulation are welcome!

(The only caveat is that `eigh` is only implemented on CPU at the moment, but we should probably just add it on GPU rather than worrying about that.)

**Comment by mattjj** [comment]
I would guess the Cholesky square root (rather than the symmetric square root) is often more efficient, though doesn't have some other nice properties of the symmetric square root solution.
