### ISSUE TITLE
Parallel broadcasting (question)

### ISSUE THREAD

**Issue by alewis** [google/jax#4094]
Hi all,

My apologies if this is well-documented somewhere; I couldn't find an obvious answer.

I'm working with matrices distributed on an r x c processor grid, and am attempting to use Jax to express the "SUMMA" distributed matrix multiplication algorithm. This algorithm expresses C = A@B as the sum of outer products, serialized on the shared dimension. In code,

```
def summa_serial(A, B):
  """
  Compute A @ B as a series of outer product updates.
  """
  m, k = A.shape
  _, n = B.shape
  C = np.zeros((m, n), dtype=A.dtype)
  for s in range(k):
    Ac = A[:, s]
    Br = B[s, :]
    C += np.outer(Ac, Br)
  return C
```

Each s iteration can then be parallelized. In a distributed implementation, this works by broadcasting the necessary data at each iteration. For example, with A and B sharded across the aforementioned r x c processor grid, at the s=0 iteration 
A[:, 0] would need to be copied (broadcasted) to each processor row, and B[0, :] to each processor column.

Can broadcasts of this nature be expressed in Jax? I'm having trouble seeing how to single out a particular processor row/column as the one from which data should be sent.

**Comment by jakevdp** [comment]
I believe what you are looking for is `pmap` (for multi-device) or `vmap` (for single device). For example:
```python
import jax
import jax.numpy as jnp
import numpy as np

def summa_parallel(A, B):
  f = jax.vmap(jnp.outer, in_axes=(1, 0), out_axes=0)
  return f(A, B).sum(0)

A = jax.random.normal(jax.random.PRNGKey(0), (3, 5))
B = jax.random.normal(jax.random.PRNGKey(1), (5, 4))
np.allclose(summa_serial(A, B), summa_parallel(A, B))
# True
```

**Comment by shoyer** [comment]
JAX also does have collective operators that work under a `pmap`: https://jax.readthedocs.io/en/latest/jax.lax.html#parallel-operators

For details of how to use them, see the various pmap notebooks: https://github.com/google/jax/tree/master/cloud_tpu_colabs
