### ISSUE TITLE
non-terminating jit compilation

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#4105]
I find that using jax-0.1.75 and jaxlib-0.1.52 some things compile forever, or at least more than 8 hours. However with jax-0.1.68 and jaxlib-0.1.47 it compiles in a second. I have not tested intermediate versions but that should be trivial to do in order to bisect when this change started. It is very difficult to make small example that showcases it, however I can point the way to a complete example if that is desired.

```bash
conda create -n compilation_issue python=3.8
conda activate compilation_issue
pip install numpy matplotlib scipy
# pip install jax==0.1.67 jaxlib==0.1.47 -> works
pip install jax==0.1.75 jaxlib==0.1.52
pip install git+https://github.com/Joshuaalbert/jaxns.git@53e797a2d8de2a175c973ed1d81c7e1db6c444f1
python -c "from jaxns.examples.mvn_data_mvn_prior import main; main()"
```

**Comment by jakevdp** [comment]
Can you provide an example of code that displays this compile issue?

**Comment by Joshuaalbert** [comment]
Hi @jakevdp I have provided a code example. But to run it you'll need to install my package and run an example in there. I was unable to make it any smaller because when I tried, e.g. compiling smaller pieces of the code it would work just fine. It was only when I tried compiling the whole example that it compiles forever (but not with older jax and jaxlib). 

Or do you mean, you prefer I make a monolithic script so that you don't need to install my package to run the example?

**Comment by Joshuaalbert** [comment]
@jakevdp So upon making a monolithic script and reinstalling a fresh environment jax and jaxlib as above the infinite compile problem disappeared. This seems fishy to me since yesterday it was a working example. Since I can't reproduce it we can close this.

**Comment by jakevdp** [comment]
OK, thanks. Please don't hesitate to open another issue if the problem arises again. We'll do our best to help diagnose it!
