### ISSUE TITLE
Is there a way to differentiate with respect to an induced subtree of a pytree?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#4116]
I'm going to open and close this issue since I don't expect there to be a solution, but it might come in handy later.

I'm starting to work with [optax](https://github.com/deepmind/optax/), and I'm running up against some design problems.  There might be an elegant design that I'm not seeing, or there might be an opportunity for a tool to be added to JAX.

Using optax has revealed that models have essentially four kinds of member variables:

- variables related to the structure of the model,
- parameters of the model,
- meta-parameters of the model, and
- "gradient transformation state" ([for example](https://github.com/deepmind/optax/blob/master/optax/_src/transform.py#L238)).

Learning is the process whereby
- you calculate _g_ the derivative of the loss (a function of the parameters) with respect to model parameters given the structure and meta-parameters.
- you apply _g_ to the parameters and update the "gradient transformation state"

Meta-learning is the process whereby
- you calculate _h_ the derivative of the loss (now a function of the meta-parameters, since we will train within the batch) with respect to the meta-parameters given the structure.
- you apply _h_ to the meta-parameters and update the "gradient transformation state" of the meta-parameters.

The problem is representing such a model is cumbersome.  I'm using a dataclasses to represent the structure of the model.  I end up having parallel tree structures to represent parameters, meta parameters, and gradient transformation states.

I don't have a solution, but I'd like to do something like:
```python
@dataclass
class C:
  x: Array = field(marked='parameter')
  y: Array = field(marked='meta_parameter')
  c: Optional[C]

c = C(1.0, 2.0, C(3.0, 4.0, None))

parameters = tree_util.extract('parameter')  # {x: 1.0, c={x: 3.0}}

# Now, training is something like
def loss(c: C):
  ...

grad(loss, wrt='parameter')(parameters)  # Only takes the derivative with respect to parameters, and fills in the parameters from the dicts
```

**Comment by Theo-Wu** [comment]
Hi, have you achieved this?

**Comment by NeilGirdhar** [comment]
@Theo-Wu I'll happily share my experience with you.

This was a design-related question that I wrote two years ago when I was still getting comfortable with Jax.  My conclusion is that if you want to have "parameter sets" (e.g., in the question parameters and meta-parameters) then each set should be a separate object.

The advantage of doing things this way is that you can pass them to appropriate Jax functions.  The disadvantage is that if the objects comprising your model have structure (e.g., a graph or a tree), then that structure usually needs to be be reflected for each of the parameter sets.

In my research, I ended up deciding that the parallel structure approach was easier.  Then I learned about projects like Haiku and Flax that arrived at the same conclusion.  On the other hand, @cgarciae's [TreeX ](https://github.com/cgarciae/treex) goes with the marked parameter approach.

Flax and Haiku provide an easy way to create parameter sets with a parallel structure to your model.  If you think the marked parameter approach would be easier for you, then try TreeX.

**Comment by Theo-Wu** [comment]
Thank you for your sharing! @NeilGirdhar 
Recently I also choose the parallel structure. But I will go to check TreeX. Thank you again :)
