### ISSUE TITLE
How to create a device array for flax.jax_utils.prefetch_to_device?

### ISSUE THREAD

**Issue by BoyuanJackChen** [google/jax#4164]
I was trying to call the function in a line like this:
```
target_iter = jax_utils.prefetch_to_device(iter(target_data), 2, devices=[1])
```
But the "devices" parameter wants a jaxlib.xla_extension.Device array. I wonder how to make one. Specifically, I want to place the iterator on my GPU:1.

**Comment by mattjj** [comment]
In general Flax questions are better on the Flax issue tracker, but this one is easy enough to answer here! You can use `jax.devices()` or `jax.local_devices()` to get lists of available devices.

**Comment by BoyuanJackChen** [comment]
@mattjj Thank you! It worked!
