### ISSUE TITLE
Documentation issue - associative_scan

### ISSUE THREAD

**Issue by AdrienCorenflos** [google/jax#4165]
https://github.com/google/jax/blob/e95d5701e33bda30299a8c87aa43b61a686c1b01/jax/lax/lax_control_flow.py#L2352

Hi,

It should clearly be used from lax, and not numpy + it seems that the Example format does not follow the docstring style, so it doesn't show properly in the readthedocs page.

Adrien

**Comment by jakevdp** [comment]
Thanks for raising the issue! We'll make certain this gets corrected.
