### ISSUE TITLE
Add reverse flag in associative_scan

### ISSUE THREAD

**Issue by AdrienCorenflos** [google/jax#4182]
This is consistent with the reverse flag in the scan operation

**Comment by AdrienCorenflos** [comment]
I opened a PR with this:

https://github.com/google/jax/pull/4181

**Comment by hawkinsp** [comment]
We've added `reverse` flag to `associative_scan`: https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.associative_scan.html#jax.lax.associative_scan
