### ISSUE TITLE
Broken docs check

### ISSUE THREAD

**Issue by JuliusKunze** [google/jax#4202]
The `docs/readthedocs.org:jax` check fails across PRs lately, i. e. [here](https://readthedocs.org/projects/jax/builds/11796506/). The only error in the [log](https://readthedocs.org/api/v2/build/11796506.txt) is 

```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

myst-parser 0.12.8 requires docutils>=0.15, but you'll have docutils 0.14 which is incompatible.
```

**Comment by shoyer** [comment]
We might be able to fix this by pinning versions in our docs?
https://github.com/google/jax/blob/master/docs/requirements.txt

**Comment by froystig** [comment]
This looks like it may have been fixed (by RTD?) in the past 16+ hours, as the doc builds have started passing again. @shoyer, any thoughts on whether to add the requirement anyway? PR is ready, but I can discard it too.

**Comment by 8bitmp3** [comment]
@froystig Thanks for bringing this up. This discussion on the `readthedocs` repo may be related - it seems to be pointing a similar issue at PiPy/`pip`: https://github.com/readthedocs/readthedocs.org/issues/7362#issuecomment-669828193

**Comment by froystig** [comment]
I'm going to close this because it indeed seems to have been fixed.
