### ISSUE TITLE
AttributeError: module 'jaxlib.xla_client' has no attribute 'ComputationBuilder'

### ISSUE THREAD

**Issue by qianzhang613** [google/jax#4203]
when test the xla_client : https://jax.readthedocs.io/en/stable/notebooks/XLA_in_Python.html#Simple-Computations

there is an error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-4549ee7f8f9e> in <module>
----> 1 c = xla_client.ComputationBuilder("simple_scalar")
      2 
      3 # define a parameter shape and parameter
      4 param_shape = xla_client.Shape.array_shape(np.dtype(np.float32), ())
      5 x = c.ParameterWithShape(param_shape)

AttributeError: module 'jaxlib.xla_client' has no attribute 'ComputationBuilder'
```
my jax is build from master 
```
python3 build/build.py --enable_march_native  --enable_mkl_dnn  --enable_cuda  --cuda_compute_capabilitie=7.0,7.5 
pip3 install -e ./build
```

**Comment by mattjj** [comment]
Another issue is that instead of calling ops like `computation_builder.Sub(x, y)`, we now write `xla_client.ops.Sub(computation_builder, x, y)`.

**Comment by preste-naava** [comment]
Is there any fix available? I am getting this with jaxlib==0.1.74

**Comment by soraros** [comment]
@preste-naava As per #8594, I guess it's the best to avoid using this api altogether?

**Comment by llCurious** [comment]
Hey, just wonder has this issue been fixed that XLA custom_call can be used in Python. If so, could your please give the link to official docs, thanks!
