### ISSUE TITLE
Array shape bug when using jax.lax.scan

### ISSUE THREAD

**Issue by StannisZhou** [google/jax#4207]
I encountered what seems to be a bug in `jax.lax.scan` in my experiments with JAX. The following is a simple example to reproduce the bug:
```
import jax
import jax.numpy as jnp

group_description = jnp.array([0], dtype=jnp.int32)
connections_description = jnp.array([[0, 0]], dtype=jnp.int32)
connections_to_groups = jnp.array([[0]], dtype=jnp.int32)
arr = jnp.zeros((2, 2, 2))


def process_connection(carry, connection_idx):
    idx0, idx1 = connections_description[connection_idx]
    print(arr[idx0, :, connections_to_groups[idx1]].shape)
    return carry, None


jax.lax.scan(process_connection, None, group_description)
for connection_idx in group_description:
    process_connection(None, connection_idx)
```

Running the above script gives the output
```
(1, 2)
(2, 1)
```
But the result should be the same with/without `jax.lax.scan`.

This is on Ubuntu 18.04, python 3.7 with jax==0.1.75 and https://storage.googleapis.com/jax-releases/cuda101/jaxlib-0.1.52-cp37-none-manylinux2010_x86_64.whl

**Comment by selamw1** [comment]
Hi @StannisZhou 
The latest versions(0.4.0+) of jax/jaxlib address this and the above script gives the same output with/without `jax.lax.scan`.
