### ISSUE TITLE
Creating jnp.array on a specific device

### ISSUE THREAD

**Issue by n2cholas** [google/jax#4221]
Is there any way to create a `jax.numpy.array` on a specific device, instead of creating it on the default device then moving it via `device_put`? Also, is there any way to change the default device programmatically? Thanks in advance.

**Comment by mattjj** [comment]
Ah, I think this is a duplicate for #4220. See [this answer](https://github.com/google/jax/issues/957#issuecomment-688950524) for now, and we'll use #4220 to track this improvement to our docs.

**Comment by YiningWang2** [comment]
Hello, After reading these related issues, I have not got an effective way, can you share me how you solved your problems?

**Comment by jakevdp** [comment]
One way to do this if you don't want to use `device_put` is to use the `jax.default_device` context manager:
```python
import jax
device = jax.devices()[0]
with jax.default_device(device):
  arr = jax.numpy.arange(10)

assert arr.device() == device
```
