### ISSUE TITLE
Nested pmap issue on GPU

### ISSUE THREAD

**Issue by hamzamerzic** [google/jax#4223]
Running the code with nested pmap/vmap in the reproducer below works with CPU/TPU but fails on GPU. The explicitly specified `cpu` backend when running `pmap` seems to be ignored, as there are clearly enough devices available.

Changing 

`updates_at_idxs = updates[..., None] * rlax.one_hot(indices, num_classes)` 

to 

`updates_at_idxs = updates[..., None]` 

makes things work on GPU as well. Not entirely sure how this is related to the mapped axes though.

- [Colab reproducer](https://colab.research.google.com/drive/1C8i4xUbu8wDWJKy0EvGhu2Vn7ptAky6W?usp=sharing)

**Comment by hamzamerzic** [comment]
I've further isolated the error. This fails on GPU:

```python
import chex
import jax
from jax import numpy as jnp

chex.set_n_cpu_devices(4)

print('CPUs:', jax.device_count('cpu'))
print('GPUs:', jax.device_count('gpu'))


def fn(indices):
  return jnp.equal(indices, jnp.arange(3)).astype(jnp.float32)

mapped_fn = jax.pmap(fn, axis_name='i', backend='cpu')
mapped_fn = jax.pmap(mapped_fn, axis_name='j', backend='cpu')

indices = np.array([[[2], [1]], [[0], [0]]])

mapped_fn(indices)
```

**Comment by mattjj** [comment]
Thanks for the great reproducer! Thanks to that, this just took 2 mins to spot once I ran your repro.
