### ISSUE TITLE
jax.random.uniform hangs when used in conjunction with concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by whbdupree** [google/jax#4228]
jax.random.uniform hangs when used in conjunction with concurrent.futures.ProcessPoolExecutor but not concurrent.futures.ThreadPoolExecutor.

```
import concurrent.futures
from jax.random import uniform,PRNGKey


def fff(myKey):
    r = uniform(myKey,(3,3))
    return r

key = PRNGKey( 333 )
r = uniform(key,(3,3))
print(r)

myjobs = []
with concurrent.futures.ThreadPoolExecutor() as e:
    for i in range(3):
        myjobs.append( e.submit(fff, key ) )

    for future in myjobs:
        print('thread job')
        print( future.result() )


myjobs = []
with concurrent.futures.ProcessPoolExecutor() as e:
    for i in range(3):
        myjobs.append( e.submit(fff, key ) )

    for future in myjobs:
        print('process job')
        print( future.result() )
```

reproduced with these versions:
jax-0.1.64 jaxlib-0.1.45
jax-0.1.76 jaxlib-0.1.52

**Comment by jakevdp** [comment]
This is interesting, thanks for the clear report. I haven't had a chance to dig-in, but I suspect the root cause of this has something to do with the use of pickle to pass variables back and forth between processes.

**Comment by mattjj** [comment]
Does ProcessPoolExecutor rely on `fork`? See [this comment](https://github.com/google/jax/issues/3691#issuecomment-658270846) by @hawkinsp.

I think perhaps we should close this issue in favor of following up on #3691. Please reopen if that's a bad idea!
