### ISSUE TITLE
Question about releases

### ISSUE THREAD

**Issue by KristianHolsheimer** [google/jax#4233]
Hi there, I subscribed to get notified about new releases of jax and jaxlib, so that I can make sure that my downstream package stays up to date.

Now I noticed that the last couple of **jaxlib** releases didn't propagate to either [pypi](https://pypi.org/project/jaxlib/#history) or https://storage.googleapis.com/jax-releases/
The most recent version there is **0.1.52**, whereas the latest version on [github](https://github.com/google/jax/releases) is **0.1.55** (at the time of this writing).

Are you guys aware of this?

**Comment by mattjj** [comment]
Thanks for raising this!

Sometimes we bump the jaxlib version number in the source code without making wheel releases on pypi or jax-releases. (The version number tracks the XLA snapshot that we build against when building from source, so it's useful to bump even when we don't release new wheels. Recently we've been bumping it for things like #4169.)

So yes, we're aware of it, though I think we've procrastinated on new jaxlib releases recently! I think someone is working on one now.

Does that answer your question?

**Comment by KristianHolsheimer** [comment]
It does, thanks @mattjj and thanks for the quick response!

**Comment by mattjj** [comment]
Just for posterity: my teammates (esp @skye) corrected me and pointed out we probably shouldn't bump jaxlib versions unless we also do wheel releases, and the recent jaxlib version bumps without releases may have been accidental!

**Comment by zhangqiaorjc** [comment]
fyi, jaxlib-v0.1.55 has been released!

https://github.com/google/jax/releases/tag/jaxlib-v0.1.55
