### ISSUE TITLE
add DeviceArray lazy_expr/aval consistency check

### ISSUE THREAD

**Issue by mattjj** [google/jax#4254]
A user ran into a rare (race condition?) issue, leading to the below partial traceback. We might want to add a consistency check to `DeviceArray.__init__` to ensure its `_lazy_expr` and `aval` attributes are consistent at construction time (they should never be mutated).

```
 0910 04:19:04.131436     return _force(x).device_buffer
 0910 04:19:04.131438     force_fun = _lazy_force_computation(x.aval, device, x._lazy_expr)
 0910 04:19:04.131441     param_shape[src] = aval.shape[dst]
 0910 04:19:04.131442 IndexError: list assignment index out of range
```

**Comment by hawkinsp** [comment]
This issue is moot, because lazy_expr is long gone.
