### ISSUE TITLE
Error handling in jitted functions

### ISSUE THREAD

**Issue by rgiordan** [google/jax#4257]
I'm upgrading a library from `autograd` to `jax`, and wondered if there are recommended best practices for handling errors within jitted functions.  The code I'm upgrading raises exceptions on poorly-formed inputs, and I'm having a hard time seeing how to deal with these exceptions with `jax.jit`.  For example, the following code:

```
@jax.jit
def foo(x):
    def raise_error():
        raise ValueError("x too big: " + str(x))
    return jax.lax.cond(x > 10,
                        true_fun=lambda _: raise_error(),
                        false_fun=lambda _: x,
                        operand=[])

foo(5)
```

...fails with the error...

```
ValueError: x too big: Traced<ShapedArray(int64[], weak_type=True):JaxprTrace(level=-1/1)>
```

...presumably because `jit` executes both of the conditional functions.  

I hear that Jax has “una anima di pura programmazione funzionale,” and that raising exceptions are side effects, so I appreciate that what I'm attempting here is not the right way to go.  But I wondered if there is any guidance in the documentation or elsewhere on how to safely terminate `jit`-ted functions when invalid values are produced.

**Comment by mattjj** [comment]
Good to hear from you, @rgiordan !

There's essentially no runtime error mechanism in XLA, and hence in code staged out of Python with `jax.jit`. (By "runtime" i mean "when FLOPs happen", which `jax.jit` separates from "when the Python code is executed as it's being traced.")

One way to rig up your own is to produce nans, or some kind of 'error bit' on the output of your function, to signal the error:

```python
import jax
import jax.numpy as jnp

do_work = lambda x: x ** 2

@jax.jit
def foo1(x):
  return jnp.where(x > 10, jnp.nan, do_work(x))


@jax.jit
def foo2(x):
  return jax.lax.cond(x > 10,
                      lambda _: jnp.nan * x,
                      lambda x: do_work(x),
                      x)
```

Both `foo1` and `foo2` return a nan array as output to signal the error. I think `foo1` may be easier to write, but only `foo2` avoids evaluating the application of `do_work`.

If you want to output an error bit or code instead (like of like LAPACK does) you might write it like

```python
import jax
import jax.numpy as jnp

do_work = lambda x: x ** 2

@jax.jit
def foo(x):
  error = jnp.where(x > 10, 1, 0)
  return error, do_work(x)


@jax.jit
def foo(x):
  return jax.lax.cond(x > 10,
                      lambda _: (1, x),
                      lambda x: (0, do_work(x)),
                      x)
```

This just means we're not using nans as a special value.

(Once nice thing about the nan approach is you can use [jax_debug_nans](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Debugging-NaNs).)

Tangentially: from time to time we've pondered whether we could use a JAX function transformation to add this kind of error plumbing automatically, in a way that's more ergonomic. Maybe that's worth thinking about more!

WDYT?

**Comment by rgiordan** [comment]
Great answer, thank you!  I think I have what I need.  It looks like `jax_debug_nans` is going to be really helpful.  And in the long run, a `jax` transformation that terminates computation with a descriptive error could indeed be a helpful shortcut.  

Thanks for all your work on `jax`, it's really exciting!

**Comment by cvjjm** [comment]
Just wanted to leave a comment for others maybe finding this old thread that it is possible to raise a Python exception from a callback called with `jax.debug.callback()` from inside `lax.cond()` inside a `jit` compiled function. As the callback itself is not executed during jit compilation and the exception isn't triggered during compile time but raised whenever the condition of the `lax.cond()` is met.
