### ISSUE TITLE
Building nonlinear image filters

### ISSUE THREAD

**Issue by kohr-h** [google/jax#4259]
I'm trying to find the pieces in the library to build general image filters that make use of the whole window rather than just comparing individual window elements, e.g. median filter.

The closest I could find was `lax.reduce_window`, but if I understand correctly, it has the above mentioned limitation that the reduction within the window only compares a single value with an accumulator in each step, rather than summarizing the whole window at once. The latter would be needed for filters like `median` or `std`.

Are there other tools available in JAX to achieve that, or am I overlooking something?

**Comment by jekbradbury** [comment]
Right, this is arguably a "missing primitive" in XLA HLO (you can think of it either as a generalization of `conv_general_dilated` to allow nonlinear filters, or a generalization of `reduce_window` to allow functions of the whole window). Adding such a primitive and supporting it on all backends would be quite a bit of work, but it's possible that a more limited use case could be easier to support in another way.

For instance, if your input array multiplied by the window size isn't too big, you could express this as a vmap of your window function on the an array containing all windows. Alternatively, if you're targeting a backend with fast loops (which currently means "not GPU") you might get decent performance expressing this operation as a (possibly nested) `lax.fori_loop` over the windows performing a `lax.dynamic_update_slice` of an output array.

**Comment by kohr-h** [comment]
Thanks @jekbradbury for the pointers! I will see which alternative fits my use case best. Since the images are not large (256x256 maybe), I suspect that the `vmap` approach will be more performant.

> but it's possible that a more limited use case could be easier to support in another way.

That depends on what ambitions there are to fill the `jax.image` package for general image processing stuff, I suppose.

Unless there's any action point left at the moment, I'll close the issue.
