### ISSUE TITLE
Question: globally setting Precision

### ISSUE THREAD

**Issue by mganahl** [google/jax#4260]
Hi!
Wondering if it is possible to globally set the default precision for lax operations.
thanks!

**Comment by mattjj** [comment]
Thanks for the question!

Have you seen [the flag for enabling 64bit mode](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Double-(64bit)-precision)?

**Comment by mganahl** [comment]
Yes, I have! Does this also affect the default of the precision argument in
jax.lax.matmul and dot?

Matthew Johnson <notifications@github.com> schrieb am Fr. 11. Sep. 2020 um
17:00:

**Comment by mattjj** [comment]
Oh, sorry, I think I misunderstood what you meant by "precision"...

**Comment by mattjj** [comment]
#6143 added a `default_matmul_precision` configuration option. See that PR message for details on how to control it via shell environment variable, absl flag, `jax.config.update`, and/or context manager. See also [the docstring for the `default_matmul_precision` context manager](https://jax.readthedocs.io/en/latest/_autosummary/jax.default_matmul_precision.html#jax.default_matmul_precision).

I think that closes this issue!
