### ISSUE TITLE
Open Source Contributions

### ISSUE THREAD

**Issue by bhairavmehta95** [google/jax#43]
Do you have plans for mapping out where open source contributions would be helpful / useful?

**Comment by mattjj** [comment]
Great idea. We'd love open source contributions, and we should have a list of ideas and shovel-ready projects to help people dive in and direct attention to where it's needed the most.

Let's leave this issue open until we've started a list of those potential projects, and linked it from the README. In the meantime, three big categories for contributions that spring to my mind are
1. improve the NumPy and SciPy coverage (e.g. by adding to lax_numpy.py),
2. write examples, both to exercise the code for bugs and to add to our examples directory, and
3. develop benchmarks and, for low-level programmers, optimize [our XLA client](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/) to minimize our dispatch overheads.

Of those three, the first might be the easiest to jump into. Here's an example of how it looks to implement a NumPy function in terms of `lax`:

```python
@_wraps(onp.sinh)
def sinh(x):
  x, = _promote_to_result_dtype(onp.sinh, x)
  return lax.div(lax.sub(lax.exp(x), lax.exp(-x)), _constant_like(x, 2))
```

Those are three ideas, but there are lots of other areas where JAX could use contributions!

What kind of project list would be most helpful, do you think? Do you know of a good example of another project mapping out a plan for open-source contributions?

**Comment by bhairavmehta95** [comment]
I actually really like these suggestions (especially the first two). Although, I am not sure I'd want to read through all your code, and try and find a numpy function that's not implemented (that's where I think you guys can really help the rest of us out. I've seen lots of repos which explictly ask for "xyz" function to be implemented, which is really good for people who want to get involved but don't know where).

One project I really liked and contributed to was CARLA - https://github.com/carla-simulator/carla/issues

They do a good job of making sure issues are marked quickly with the correct tags, which makes it easy to see whether its open for opensource contributions, or if its something the developer will take care of.

I think this project is quite interesting, so even a short list of "xyz" functions to implement (to get your feet wet with jax) would be nice to see!

**Comment by bhairavmehta95** [comment]
Are the ones in #70 up to date?

**Comment by mattjj** [comment]
Yes, we're keeping it somewhat up to date. But not all of the ones in the list have the same priority; we haven't gone over it carefully yet. It might be worth asking in that thread before you set out to implement any particular ones.

Another place to look is scipy, especially scipy.stats. There are a lot of logpdfs and sampling functions functions we could add (though the sampling functions may need a different API to fit [our PRNG model](https://github.com/google/jax#random-numbers-are-different), and so perhaps should go in jax.random).

**Comment by hawkinsp** [comment]
I'm going to close this issue because it's pretty old and it's not clear what action we should take, beyond the existing bugs to track missing functions, etc. If you are looking for more contribution ideas, I suggest starting a new thread in our discussion forum! (https://github.com/google/jax/discussions)
