### ISSUE TITLE
jax.jit(ravel_pytree) broken by omnistaging

### ISSUE THREAD

**Issue by clemisch** [google/jax#4305]
Dear JAX team,

I've found that omnistaging breaks jit'ing of `jax.flatten_util.ravel_pytree`. Without jit, `ravel_pytree` it is 3-5 times slower. 

Background: I am calling it inside a wrapper around scipy LBFGS to be able to optimize on a tuple of arguments and automate the flattening/unflattening of multiple arguments. I am calling ravel_pytree and the corresponding unravel on each iteration. 

I assume the performance influence overall is not large, but I wondered whether the error was intentional? Mainly because the unravel function _can_ be jit'ed. 

Repro:

```python
import jax
from jax.flatten_util import ravel_pytree
ravel_pytree_jit = jax.jit(ravel_pytree)

ravel_pytree(1.)
ravel_pytree_jit(1.)  # with omnistaging: TypeError: <class 'function'> is not a valid JAX type

%timeit ravel_pytree(1.)[0].block_until_ready() # 1 ms (with/without omnistaging)
%timeit ravel_pytree_jit(1.)[0].block_until_ready() # 200-300 µs (without omnistaging)
```

**Comment by clemisch** [comment]
I found a solution for my usecase: since the tree structure does not change, I can jit on the returned raveled tree output only during the optimizaton:

```python
ravel_pytree_jit = jax.jit(lambda tree: ravel_pytree(tree)[0])
```

I can execute the full `ravel_pytree` once at the initialization to obtain the `unravel` function, but from there I only ever need the raveled current tree from `ravel_pytree`.

**Comment by mattjj** [comment]
Thanks for raising this!

I hadn't thought of this case, but it was in a way intentional: I wanted to tighten up the constraints that jitted functions must return pytrees of valid jax types (i.e. pytrees of arrays), and not other Python objects. It'd be possible to allow arbitrary Python objects again, but it's a recipe for trouble, because those Python objects could be smuggling tracers, and if so those'll lead to very confusing downstream errors.

Hmm...

**Comment by clemisch** [comment]
Thank you for your thoughts @mattjj!

FWIW, I think if I had noticed that the returned `unravel` function itself is the problem (rather than some very internal JAX error), I would not have been confused. In this context it is also not surprising at all that `unravel` can be jit'ed, as it only returns a pytree.

As my specific problem is solved and the general rule of "jit only for pytree outputs" is clear for me, I'll close.
