### ISSUE TITLE
Help with array slice indices

### ISSUE THREAD

**Issue by AashinShazar** [google/jax#4309]
Hey guys, I'm quite new to using this library and I'm a little stuck with array slice indexing. I understand that arrays are immutable and to update them, we have to use ops.index_update. But when it comes to accessing arrays, I admit I'm a little confused with how they work especially with a little more complicated array slicing as seen with:

`storeStack.append(x[resMap[j, i + 1], st + dt:en + dt])`

Here's my minimal reproducible code below. 

```python
import jax.numpy as np
from jax import grad, jit, vmap
from jax import random, ops, jit, lax
import numpy 

def getFeature(featData, cc, x, wl, wi, dn, resMap, st, en, numwin):
    resMap = resMap.conj().T
    Fts = 6
    hts = [-dn, 0, dn]
    vts = [-dn, 0, dn]
    n = 0
    outSig = 161
    w = numwin - 1

    n = -1
    for j in range(0, (len(resMap[:, 0]) - 1)):
        for i in range(0, (len(resMap[0]) - 1)):
            n = n + 1

            storeStack = []
            incCounter = 1
            if i < len(resMap[0]):
                for dt in hts:
                    storeStack.append(x[resMap[j, i + 1], st + dt:en + dt])
                    incCounter = incCounter + 1

            else:
                for dt in hts:
                    storeStack.append(x[resMap[j, 1], st + dt:en + dt])
                    incCounter = incCounter + 1

            for dt in vts:
                storeStack.append(x[resMap[j + 1, i], st + dt:en + dt])
                incCounter = incCounter + 1

            Stacked = np.zeros((incCounter, en - st))
            ops.index_update(Stacked, ops.index[0, :], x[resMap[j, i], st:en])
            for val in range(0, len(storeStack)):
                ops.index_update(Stacked, ops.index[val + 1, :], storeStack[val])
            cX =  numpy.random.rand(192,138)

            for f in range(0, Fts):
                ops.index_update(cc, ops.index[f+1], np.sum(np.abs(cX[0, :] - cX[f + 1, :])) / wl)
                ops.index_update(featData, ops.index[f,n,w], cc[f + 1])

    return featData

data = numpy.random.rand(192,138)
windowLen = 128
windowInc = 64
stAF = 1+3-1
enAF = windowLen + 3 -1
i= 0
featData = np.zeros((6, 161, 1))
cc = np.zeros((7))

resVmap = np.array([])
for i in np.arange(1, 25):
    j = ((i - 1) * 8)
    stackThis = np.arange(j, 8 + j)
    resVmap = np.vstack([resVmap, stackThis]
                        ) if resVmap.size else stackThis

jitted= jit(getFeature, static_argnums=(0,1))
%timeit jitted(featData, cc, data, windowLen, windowInc, 1, resVmap, stAF, enAF, i+1).block_until_ready()
```

Any help or pointers would be greatly appreciated!

**Comment by jakevdp** [comment]
Hi - thanks for the question & the nice snippet demonstrating the issue!

When I run your code, I see this error:
```
IndexError: Array slice indices must have static start/stop/step to be used with NumPy indexing syntax. To index a statically sized array at a dynamic position, try lax.dynamic_slice/dynamic_update_slice (JAX does not support dynamically sized arrays within JIT compiled functions).
```
The issue here is that your slices are generating arrays of dynamic shape, which is not allowed in jitted JAX code. A quick fix to this is to mark all inputs that determine shapes of sub-arrays as static in the jit. This seems to do the trick:
```python
jitted= jit(getFeature, static_argnums=(0,1,5,6,7,8))
```
Does that answer your question?

**Comment by AashinShazar** [comment]
That answers my question. Thank you so much!

**Comment by AashinShazar** [comment]
I hate to reopen the issue but I just realized one of the ops.index_update calls does not actually update the index. 

For this line in particular: `ops.index_update(Stacked, ops.index[0, :], x[resMap[j, i], st:en])`.

I've disabled jit to debug further but I'm not sure why this is happening. Is it because I'm trying to update the index with another array containing multiple values?

Could you please have a look?

**Comment by jakevdp** [comment]
`ops.index_update` does not update arrays in-place; it returns a modified copy. So, e.g. rather than
```python
ops.index_update(featData, ops.index[f,n,w], cc[f + 1])
```
you need to do
```python
featData = ops.index_update(featData, ops.index[f,n,w], cc[f + 1])
```

**Comment by AashinShazar** [comment]
That makes sense, thanks again! 

So I have these index_updates within for loops, would it make sense to combine it with the vmap function for better performance?

**Comment by jakevdp** [comment]
Yes, compiling static for-loops will be very slow (the tracing will essentially unroll all the for loops and record the entire linear sequence of operations)

It will be much more efficient if you can express the logic in terms of matrix operations or vmaps. The overall logic of the snippet above is somewhat obscure to me without knowing what each of the parameters mean, but I suspect you'd be able to write this in a way that woudl execute more efficiently in jax.

**Comment by AashinShazar** [comment]
So I've tried optimizing it with the usage of vmap but I'm not certain if my approach is all that optimal, I apologize for the chickenscratch of code :sweat_smile:

 I do get an error with local variable featData being referenced before assignment. What I'm essentially trying to do is the commented out for loop where it iterates over the final variable and assigns a calculation to featData. I've tried doing a vmap version of this but with no luck. 

I can get it to compile and run if I just comment out the last few lines and return the final variable as seen here: `final = vmap(outerLoop)(new)`

But after that point, I get errors or it just is too slow at compiling. 

Here's what I have so far.

```python
def getFeature(featData, cc, x, wl, wi, dn, resMap, st, en, numwin):
    resMap = resMap.conj().T
    x = jnp.asarray(x)
    Fts = 6
    hts = [-dn, 0, dn]
    vts = [-dn, 0, dn]
    n = 0
    outSig = 161
    w = numwin - 1


    def outerLoop(j):
    #for j in range(0, (len(resMap[:, 0]) - 1)):

        def innerLoop(i):     
        #for i in range(0, (len(resMap[0]) - 1)):

            storeStack = []
            incCounter = 1
            storeStack+= [(x[resMap[j, i + 1], st + dt:en + dt]) for dt in hts]
            incCounter = incCounter + 3

            storeStack+= [(x[resMap[j + 1, i], st + dt:en + dt]) for dt in vts]
            incCounter = incCounter + 3

            Stacked = jnp.zeros((incCounter, en - st))
            Stacked = ops.index_update(Stacked, ops.index[0, :], x[resMap[j, i], st:en])
            
            for val in range(0, len(storeStack)):
                Stacked = ops.index_update(Stacked, ops.index[val + 1, :], storeStack[val])

 
            cX = numpy.random.rand(192,138)
            return cX #gives us n x features x values

        this = jnp.arange(0,(len(resMap[0]) - 1))
        calcCX = vmap(innerLoop)(this)

        return calcCX
            
    new = jnp.arange(0,(len(resMap[:,0]) - 1))
    final = vmap(outerLoop)(new)

    # for x in range(0, len(final)): what I'm trying to accomplish
    #     calcCX = final[x,:,:,:]
    #     for n in range(0, len(calcCX[:,0,0])):
    #         for f in range(0, Fts):
    #             featData = ops.index_update(featData, ops.index[f,n,w], jnp.sum(jnp.abs(calcCX[n, 0, :] - calcCX[n, f + 1, :])) / wl)
    #return featData


    def finaloop3(x):
        calcCX = final[x,:,:,:]
        def finalloop2(n):

            def finalloop1(f):
                featData = ops.index_update(featData, ops.index[f,n,w], jnp.sum(jnp.abs(calcCX[n, 0, :] - calcCX[n, f + 1, :])) / wl)
                return featData

            finalloop1It = jnp.arange(0, 6)
            loop1 = vmap(finalloop1)(finalloop1It)
            return loop1

        finalloop2It = jnp.arange(0, len(calcCX[:,0,0]))
        loop2 = vmap(finalloop2)(finalloop2It)
        return loop2


    finalloop3It = jnp.arange(0, len(final))
    loop3 = vmap(finaloop3)(finalloop3It)
   return loop3 #the final featData after all the index updates
```

**Comment by jakevdp** [comment]
Thanks - it's still hard for me to tell what this is doing, because of all the inner-loop indexing that happens. It looks a bit like some sort of convolution – you might try to express it in terms of JAX's built-in convolution operators.

In general, algorithms based on nested loops over inexpensive computations are not going to perform well in JAX, unless they can be re-expressed in terms of existing primitives.

**Comment by AashinShazar** [comment]
As I understand the code, it's essentially doing what's highlighted in this section below. 

![image](https://user-images.githubusercontent.com/44244230/93537803-5edc4980-f901-11ea-80cb-4123856dfe84.png)

Where, 

MAD-L[i,j,dn] would correlate to this: 
`storeStack+= [(x[resMap[j, i + 1], st + dt:en + dt]) for dt in hts]`

MAD-T[i,j,dn] would correlate to this: 
`storeStack+= [(x[resMap[j + 1, i], st + dt:en + dt]) for dt in vts]`

and the final calculation of the summation and division taking place here: 
`featData = ops.index_update(featData, ops.index[f,n,w], jnp.sum(jnp.abs(calcCX[n, 0, :] - calcCX[n, f + 1, :])) / wl)`

**Comment by jakevdp** [comment]
Yeah, that definitely looks like it could be expressed as a convolution. I'd suggest going that route rather than writing all the loops manually. You can construct a kernel that essentially encodes the sums that happen at each location, and do the whole thing in one operation.

**Comment by AashinShazar** [comment]
Do you have any resources that I could look into to constructing kernels and expressing this as a convolution?

**Comment by jakevdp** [comment]
I don't know of any such resource, but a simplified version of what I have in mind is something like this:
```python
import numpy as np
import jax.numpy as jnp
from jax.scipy.signal import convolve2d

def slow_convolve(M, k):
  result = np.zeros_like(M)
  for i in range(M.shape[0]):
    for j in range(M.shape[1]):
      for m in range(k.shape[0]):
        for n in range(k.shape[1]):
          if i + m < M.shape[0] and j + n < M.shape[1]:
            result[i, j] += k[m, n] * M[i + m, j + n]
  return jnp.array(result)

def fast_convolve(M, k):
  full_result = convolve2d(M, k[::-1, ::-1], mode='full')
  return full_result[-M.shape[0]:, -M.shape[1]:]

M = jnp.array(np.random.rand(10, 10))
k = jnp.array([
  [1, 2, 3],
  [4, 2, 1],
  [5, 1, 1]
])

result1 = slow_convolve(M, k).round(1)
result2 = fast_convolve(M, k).round(1)
np.allclose(result1, result2)
# True
```
In the same way that these nested loops can be replaced by a fast built-in convolution operation, I believe that the nested loops in your code can be replaced by a fast built-in convolution operation.

**Comment by AashinShazar** [comment]
Thanks for the helper code for the convolution. I'm trying a different approach where I unrolled the double for loop into a single for loop. I'm trying to achieve it with a vmap operation but I'm running into an error stating list indices must be integers or slices, not BatchTracer. This error arises when I try to access the nth value of the newMap to obtain integers j and i. The nth value seems to be outputting the entire range as opposed to the individual integers the innerLoop should be iterating over.

I've attached the minimal reproducible code below.

```python
def getFeature(featData, cc, x, wl, wi, dn, resMap, st, en, numwin):
    resMap = resMap.conj().T
    Fts = 6
    outSig = 161

    w = numwin - 1

    newMap = []

    for j in range(0, (len(resMap[:, 0]) - 1)):
        for i in range(0, (len(resMap[0]) - 1)):
            newMap.append([j,i])

    def innerLoop(n):
        Stacked = np.zeros((7, en - st))
        j,i = newMap[n] #n should be an integer

        Stacked = ops.index_update(Stacked, ops.index[0, :], x[resMap[j, i], st:en])

        Stacked = ops.index_update(Stacked, ops.index[1, :], x[resMap[j, i + 1], st -1:en -1])
        Stacked = ops.index_update(Stacked, ops.index[2, :], x[resMap[j, i + 1], st:en])
        Stacked = ops.index_update(Stacked, ops.index[3, :], x[resMap[j, i + 1], st+1:en +1])
        
        Stacked = ops.index_update(Stacked, ops.index[4, :], x[resMap[j + 1, i], st -1:en -1])
        Stacked = ops.index_update(Stacked, ops.index[5, :], x[resMap[j + 1, i], st:en])
        Stacked = ops.index_update(Stacked, ops.index[6, :], x[resMap[j  + 1, i], st+1:en+1])

        cX = normalizeM(Stacked)

        featData = ops.index_update(featData, ops.index[0, n, w], np.sum(np.abs(cX[0, :] - cX[0 + 1, :])) / wl)
        featData = ops.index_update(featData, ops.index[1, n, w], np.sum(np.abs(cX[0, :] - cX[1 + 1, :])) / wl)
        featData = ops.index_update(featData, ops.index[2, n, w], np.sum(np.abs(cX[0, :] - cX[2 + 1, :])) / wl)
        featData = ops.index_update(featData, ops.index[3, n, w], np.sum(np.abs(cX[0, :] - cX[3 + 1, :])) / wl)
        featData = ops.index_update(featData, ops.index[4, n, w], np.sum(np.abs(cX[0, :] - cX[4 + 1, :])) / wl)
        featData = ops.index_update(featData, ops.index[5, n, w], np.sum(np.abs(cX[0, :] - cX[5 + 1, :])) / wl) 

    this = np.arange(0,161)
    vmap(innerLoop)(this)

    return featData

data = numpy.random.rand(192,138)
windowLen = 128
windowInc = 64
stAF = 1+3-1
enAF = windowLen + 3 -1
i= 0
featData = np.zeros((6, 161, 1))
cc = np.zeros((7))

resVmap = np.array([])
for i in np.arange(1, 25):
    j = ((i - 1) * 8)
    stackThis = np.arange(j, 8 + j)
    resVmap = np.vstack([resVmap, stackThis]
                        ) if resVmap.size else stackThis



jitted= jit(getAF, static_argnums=(0,1,5,6,7,8))
%timeit jitted(featData, cc, data, windowLen, windowInc, 1, resVmap, stAF, enAF, i+1).block_until_ready()
```

**Comment by jakevdp** [comment]
Hi - so the issue here is your assumption that `n` is an integer. JAX's jit works by feeding *tracers* into the function to determine what the function does. A shorter example of the issue you're encountering is this:
```python
from jax import jit
L = [i for i in range(10)]
def func(n):
  return L[n]
jit(func)(0)
```
When you call the jitted function, JAX "compiles" the function by passing tracers to determine the operations that the function does; this results in the Python list indexing being passed a tracer, which results in
```
TypeError: list indices must be integers or slices, not DynamicJaxprTracer
```
If you want to jit-compile (or vmap, or grad, etc.) a function, that function must only use inputs in jax expressions. So, for example, this would work:
```python
L = jnp.arange(10)
def func(n):
  return L[n]
jit(func)(0)
```
because jax array indexing knows how to respond when it sees a tracer.

Does that make sense?

**Comment by AashinShazar** [comment]
Yeah that helps immensely! 

Solved the error I'm facing but now I can't seem to get the right output out, I just get a 3D array full of 0s for some reason. 

I suspect this is because of the way I'm passing in featData to the vmap partial function. Should I be returning the updated featData instead and collecting it after the innerLoop is complete?

```python
import jax.numpy as np
import jax
from jax import grad, jit, vmap, pmap
from jax import random, ops, jit, lax
import numpy 
from jax.config import config
config.update("jax_enable_x64", True)
from functools import partial


def innerLoop(featData, x, wl, resMap, st, en, newMap, n):
  Stacked = np.zeros((7, en - st))
  j,i = newMap[n]
  Stacked = ops.index_update(Stacked, ops.index[0, :], x[resMap[j, i], st:en])

  Stacked = ops.index_update(Stacked, ops.index[1, :], x[resMap[j, i + 1], st -1:en -1])
  Stacked = ops.index_update(Stacked, ops.index[2, :], x[resMap[j, i + 1], st:en])
  Stacked = ops.index_update(Stacked, ops.index[3, :], x[resMap[j, i + 1], st+1:en +1])
  
  Stacked = ops.index_update(Stacked, ops.index[4, :], x[resMap[j + 1, i], st -1:en -1])
  Stacked = ops.index_update(Stacked, ops.index[5, :], x[resMap[j + 1, i], st:en])
  Stacked = ops.index_update(Stacked, ops.index[6, :], x[resMap[j + 1, i], st+1:en+1])

  cX = numpy.random.rand(192,138)

  featData = ops.index_update(featData, ops.index[0, n, 0], np.sum(np.abs(cX[0, :] - cX[0 + 1, :])) / wl)
  featData = ops.index_update(featData, ops.index[1, n, 0], np.sum(np.abs(cX[0, :] - cX[1 + 1, :])) / wl)
  featData = ops.index_update(featData, ops.index[2, n, 0], np.sum(np.abs(cX[0, :] - cX[2 + 1, :])) / wl)
  featData = ops.index_update(featData, ops.index[3, n, 0], np.sum(np.abs(cX[0, :] - cX[3 + 1, :])) / wl)
  featData = ops.index_update(featData, ops.index[4, n, 0], np.sum(np.abs(cX[0, :] - cX[4 + 1, :])) / wl)
  featData = ops.index_update(featData, ops.index[5, n, 0], np.sum(np.abs(cX[0, :] - cX[5 + 1, :])) / wl) 

def getFeature(featData, cc, x, wl, wi, dn, resMap, st, en, numwin):
    resMap = resMap.conj().T
    Fts = 6
    outSig = 161

    w = numwin - 1

    ithMap = np.zeros((1,161))
    jthMap = np.zeros((1,161))
    newMap = []

    for j in np.arange(0, (len(resMap[:, 0]) - 1)):
        for i in np.arange(0, (len(resMap[0]) - 1)):
            newMap.append([j,i])

    newMap = np.array(newMap)

    nth = np.arange(0, 161)
    vmap(partial(innerLoop, featData, x, wl, resMap, st, en, newMap))(nth)

    return featData


data = numpy.random.rand(192,138)
print(data)
windowLen = 128
windowInc = 64
stAF = 1+3-1
enAF = windowLen + 3 -1
i= 0
featData = np.zeros((6, 161, 1))
cc = np.zeros((7))

resVmap = np.array([])
for i in np.arange(1, 25):
    j = ((i - 1) * 8)
    stackThis = np.arange(j, 8 + j)
    resVmap = np.vstack([resVmap, stackThis]
                        ) if resVmap.size else stackThis


jitted= jit(getFeature, static_argnums=(0,1,5,6,7,8))
gotit = jitted(featData, cc, data, windowLen, windowInc, 1, resVmap, stAF, enAF, i+1).block_until_ready()
print(gotit.shape)
print(gotit[:,:,0]) #all zeros?
```

**Comment by jakevdp** [comment]
You pass in `featData` as an array of zeros, but `getFeature` never modifies the array before returning it. Perhaps you mean to return the result of the vmapped function?

**Comment by AashinShazar** [comment]
Yep, that's exactly what I was missing. Just as a final note before I finally close this issue is there a faster way to perform the ops.index_update without having to do it in a for loop?

This is my current approach:

```python
    got = vmap(partial(innerLoop, x, wl, resMap, st, en, newMap))(nth)

    for x in range(0,161):
        featData = ops.index_update(featData, ops.index[:, x, 0], got[x, :,0]) 
```

Could I somehow update multiple indices at the same time or collect this in a more efficient manner?

**Comment by jakevdp** [comment]
You should be able to do it in one step with something like this:
```python
featData = ops.index_update(featData, ops.index[:, :, 0], got[:, :, 0].T)
```

**Comment by AashinShazar** [comment]
That solves it, thank you so much for all the assistance and pointers! I'm starting to get the hang of JAX and the power it wields. Appreciate it!
