### ISSUE TITLE
psum inconsistent across vmap/pmap context

### ISSUE THREAD

**Issue by froystig** [google/jax#4327]
In particular, the `psum` primitive should behave as a broadcasting sum ("allreduce").

A fix would likely involve changing [this rule](https://github.com/google/jax/blob/8a4ee3d8516662b6f6fd95046f4d28119b3c1db2/jax/lax/lax_parallel.py#L469), plus tests for (i) intended behavior and (ii) consistent behavior across pmap and vmap.

cc @apaszke @mattjj

**Comment by froystig** [comment]
related: #3970

**Comment by apaszke** [comment]
I just checked and it looks like both `pmap` and `vmap` gives me the same result:
```py
def f(w, data):                                                  
  def agg_loss(w):                                               
    return lax.psum(w * data, 'batch')                           
  return jax.grad(agg_loss)(w)                                   
print(jax.vmap(f, axis_name='batch')(jnp.ones(2), jnp.arange(2))) # [0. 2.]
print(jax.pmap(f, axis_name='batch')(jnp.ones(2), jnp.arange(2))) # [0. 2.]
```

**Comment by froystig** [comment]
Sorry, false bug!
