### ISSUE TITLE
Error differentiating QR decomposition

### ISSUE THREAD

**Issue by noahstier** [google/jax#433]
This appears to be a bug but unfortunately I don't have time to delve into it.

Below is a simple script to do gradient descent on a function involving a QR decomposition. It fails when I execute `training_gradient_fun` with `TypeError: No abstraction handler for type: <class 'jax.ad_util.Zero'>`.

Ubuntu 16.04
python 3.6.6
jax 0.1.20
jaxlib 0.1.9

```
import jax
import jax.numpy as np
import numpy as onp

def loss(weights, inputs):
    q, r = np.linalg.qr(weights)
    a = np.matmul(q, weights)
    return np.mean(a ** 2)

training_gradient_fun = jax.jit(jax.grad(loss))

inputs = onp.random.rand(5, 5)
weights = onp.random.rand(5, 5)

for i in range(100):
    weights -= 0.1 * training_gradient_fun(weights, inputs)
```

**Comment by mattjj** [comment]
Thanks for the report, and the super easy repro! The bug was a relatively new transpose rule not handling a symbolic zeros correctly. #437 should close this soon!
