### ISSUE TITLE
re-optimize pmap(lambda x: x) for omnistaging

### ISSUE THREAD

**Issue by trevorcai** [google/jax#4337]
It's good to see `device_put_sharded` get submitted & centralized.
But there are still situations where `jax.pmap(lambda x: x)` is a more natural API; in particular, when you already have an array with the correct leading dimensions that you'd like to (re-)shard for the coming pmap.
(Doing this optimally with `device_put_sharded` would involve reproducing `shard_arg_handlers`.)

With omnistaging enabled, it looks like the empty jaxpr short-circuit doesn't fire:
https://cs.opensource.google/jax/jax/+/master:jax/interpreters/pxla.py;l=573;drc=40e20242db0ed1d8cceb1d93b78d07c248e693a6

One of the hidden benefits of this short-circuit is that it improves TPU memory fragmentation (for the usual donation reasons), so it'd be really useful to see that short-circuit reintroduced.

**Comment by skye** [comment]
@mattjj would it work to have a special no-compile case if the jaxpr has no eqns?

**Comment by mattjj** [comment]
FYI @jblespiau, this might be reason to eventually include "short-circuiting" for at least some trivial jitted and pmapped computations in the C++ path. (That is, I can update the Python path for pmap, but we'd need the C++ path to follow suit.)

**Comment by mattjj** [comment]
@trevorcai you closing these issues makes me 😢 

Come back and open some more someday!
