### ISSUE TITLE
How is JAX differentiating this program?

### ISSUE THREAD

**Issue by krishvishal** [google/jax#435]
I'm trying to differentiate a function using JAX. This is the function:

    import jax.numpy as np
    from jax import grad, jit, vmap
    def f2(a, b):
        c = b * a
        return a

    grad_f2 = grad(f2)
    print(grad_f2(2.0, 3.0))

when the function returns `a`, then `grad_f2`'s value is `1.0` when I change the return to `b`, then `grad_f2`'s value is `0.0` and when the return is changed to `c`, grad_f2 returns `3.0`. I don't understand what is happening here ? How does differentiating programs work ?  

  [1]: https://github.com/HIPS/autograd

**Comment by hawkinsp** [comment]
Thanks for trying JAX! 

Take a look at the docstring for `grad`: it differentiates with respect to a particular argument or arguments: https://jax.readthedocs.io/en/latest/jax.html#jax.grad

By default, it differentiates with respect to the first argument, here `a`.

If you want derivatives with respect to both `a` and `b`, try `grad(f2, argnums=(0, 1))`.

Hope that helps!
