### ISSUE TITLE
Question: Is it possible to globally set the default device?

### ISSUE THREAD

**Issue by markusschmitt** [google/jax#4352]
I could not find an answer to this in the documentation: I would like to use one specific of multiple available devices throughout my program, which is not `jax.devices()[0]`. Is there a way to choose the default device used for data placement and jit?

More specifically, I will have multiple MPI processes running on one node and I want each of them to use a different GPU.

**Comment by jekbradbury** [comment]
There's no way to globally set the default device from inside JAX right now, but you may be able to accomplish the same thing by setting the `CUDA_VISIBLE_DEVICES` environment variable to a different value for each process.

**Comment by mattjj** [comment]
Seems like something worth adding. WDYT @jekbradbury ?

**Comment by markusschmitt** [comment]
Thanks for your comments!

I think adding such a feature would indeed be useful: Using the `CUDA_VISIBLE_DEVICES` environment variable, one has to make sure that this is set prior to any `import jax` statement, which makes is prone to errors. If JAX had a way of setting the default device globally with one function call, that would be much more handy.

**Comment by markusschmitt** [comment]
There seems to be another complication when working with the `CUDA_VISIBLE_DEVICES` environment variable: As I mentioned, I would like to choose a device depending on the MPI rank. Therefore, working with the `mpi4py` library, I need to import `mpi4py` first. However, I observe, that setting the environment variable via `os.environ["CUDA_VISIBLE_DEVICES"] = my_choice_of_devices` after `from mpi4py import MPI` has no effect on the list returned by `jax.devices()`, whereas setting the environment variable before `from mpi4py import MPI` works.

Do you have any idea what is the reason for this behavior?

**Comment by sebamenabar** [comment]
Hi, I think this may help:

```python
def setup_device(gpus=0, default_platform="cpu"):
    if gpus != 0:
        gpu = jax.devices("gpu")[0]
    else:
        gpu = None
        default_platform = "cpu"
    cpu = jax.devices("cpu")[0]
    jax.config.update("jax_platform_name", default_platform)

    return cpu, gpu
```

**Comment by mattjj** [comment]
I think @skye has nearly landed this feature in #9118.

**Comment by nestordemeure** [comment]
As I understand it, #9118 would let you pick the default device within a context manager section (defined by a `with`).

But, is there a way to pick a particular GPU for all of the program (setting a config element once)?

My use case is a library that is being used several times in a number of scripts. It is in an HPC context and control over the GPU used is important.

**Comment by skye** [comment]
@nestordemeure you can also put this somewhere near the top of your code: `jax.config.update("jax_default_device", jax.devices()[0])` (or whatever device you like). Does this work for you? If not, let us know what kind of API would be more useful!

**Comment by nestordemeure** [comment]
@skye It works, thank you!

It might be interesting to add this information (both `config.update` and `default_device`) to the [Controlling data and computation placement on devices](https://jax.readthedocs.io/en/latest/faq.html#faq-data-placement) section of the doc (`default_device` is already mentioned but could do with an actual example).

**Comment by skye** [comment]
Good idea! I filed a new issue https://github.com/google/jax/issues/13684 to better keep track of this suggestion.

I'm gonna go ahead and close this issue since I think it's resolved, but feel free to continue commenting or to reopen if there are still questions / issues around setting the default device (or open a new issue).
