### ISSUE TITLE
linalg.eigh returns error for n >= 32767

### ISSUE THREAD

**Issue by taozhe1036** [google/jax#4358]
Hi all,
I want to calculate the eigenvalue an eigenvector of a big matrix like 60000X60000.
Now I use below code to test the linalg.eigh on large symmetric matrix and encounter some problem. 
```python
import jax.numpy as np
import jax.scipy as spy
import jax

jax.config.update('jax_platform_name', 'cpu')
n=32767
array = np.diag(numpy.random.random(n,))

values, funcs =np.linalg.eigh(array)
values, funcs = spy.linalg.eigh(array)
```
I test both linalg.eigh of jax.numpy and jax.scipy, they all return
```
F external/org_tensorflow/tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Invalid argument: shape's dimensions must not be < 0; dimension at index 0 was -1094727295
Aborted (core dumped)
```
My platform is ubuntu 16.04 LTS, which has  62GB memory.
jax/jaxlib/Python version information:
0.1.77 0.1.55 3.7.3

Thank you very much for your efforts in advance!

Best regards

**Comment by romanngg** [comment]
(May be related to past similar issue ~ https://github.com/google/jax/issues/1644)

**Comment by mattjj** [comment]
This sounds like numpy/numpy#13956. According to [this comment](https://github.com/numpy/numpy/issues/13956#issuecomment-511257515) it's a bug in the 32bit interface to LAPACK. (I just noticed this was noticed over in google/neural-tangents#70 3 days ago.)

@hawkinsp this is a bit above my paygrade. Any ideas?

**Comment by crissallan** [comment]
> Hi all,
> I want to calculate the eigenvalue an eigenvector of a big matrix like 60000X60000.
> Now I use below code to test the linalg.eigh on large symmetric matrix and encounter some problem.
> 
> ```python
> import jax.numpy as np
> import jax.scipy as spy
> import jax
> 
> jax.config.update('jax_platform_name', 'cpu')
> n=32767
> array = np.diag(numpy.random.random(n,))
> 
> values, funcs =np.linalg.eigh(array)
> values, funcs = spy.linalg.eigh(array)
> ```
> 
> I test both linalg.eigh of jax.numpy and jax.scipy, they all return
> 
> ```
> F external/org_tensorflow/tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Invalid argument: shape's dimensions must not be < 0; dimension at index 0 was -1094727295
> Aborted (core dumped)
> ```
> 
> My platform is ubuntu 16.04 LTS, which has 62GB memory.
> jax/jaxlib/Python version information:
> 0.1.77 0.1.55 3.7.3
> 
> Thank you very much for your efforts in advance!
> 
> Best regards

I met the same problem as you did. It seems that solving eigenvalues and eigenvectors for such a large matrix is computational expensive, both in time and storage aspect.
