### ISSUE TITLE
Is id_tap supposed to be called synchronously?

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#4372]
I was using `id_tap` to update a progress bar, but something seems to have changed in JAX whereby the many calls to the tap function (within a scan) seem to all happen at the end of the computation.  Is there some way for me to force `id_tap` to make the calls synchronously?  I really liked having the progress bar since it also gave me an estimated time for the computation to complete.

@gnecula

**Comment by jekbradbury** [comment]
I bet this regression coincided with omnistaging (even though, in principle, omnistaging should make it _easier_ to sequence infeed/outfeed according to program order). If you can put together a MWE, I think we can track down what happened here (it definitely wasn't intentional).

**Comment by gnecula** [comment]
+1 to James's comment. I can look into this if you give me a way to reproduce the problem.

**Comment by NeilGirdhar** [comment]
Thank you!   I'll write a MWE ASAP.

**Comment by NeilGirdhar** [comment]
I'm going to close this since I did a big rewrite and the problem seems to have disappeared.  I'll reopen if it comes up again.
