### ISSUE TITLE
id_print example from docs broken; crash on GPU

### ISSUE THREAD

**Issue by clemisch** [google/jax#4374]
Dear jax team,

I am having problems using `jax.experimental.host_callback.id_print`. I looked at [the docs](https://jax.readthedocs.io/en/latest/jax.experimental.host_callback.html) and tried the example there, but it gives me either an error or crashes completely if altered slightly. 

The crash happens only on GPU. On CPU, `power3_2` prints correctly. 

Am I using `id_print` incorrectly or are the docs not up-to-date? Or am I missing something?

Repro:

```python
import jax
import jax.numpy as jnp
from jax.experimental.host_callback import id_print

def power3(x):
   y = x * x
   _, y = id_print(x, y, what="x,x^2")
   return y * x

jax.vmap(power3)(jnp.arange(3.))
# TypeError: id_print() takes 1 positional argument but 2 were given


def power3_2(x):
   y = x * x
   y = id_print(y, what="x^2")
   return y * x

jax.vmap(power3_2)(jnp.arange(3.))
"""
Works on CPU. Crashed on GPU with:

2020-09-22 09:26:56.242431: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/outfeed_thunk.cc:49] 
Check failed: ShapeUtil::Compatible(hlo_instruction_->operand(0)->shape(), outfeed_buffers->shape()) 
XLA program outfeed request of shape (f32[3]) did not match the runtime's outfeed buffer of shape u32[2]
Aborted
"""
```

I am using jax and compiling jaxlib from HEAD on CUDA 10.0/450.66.

**Comment by gnecula** [comment]
`id_print` takes a single argument, so the `power3` example is expected to fail (and the documentation needs fixing). But `power3_2` is correct. I think that I know what is happening (a bad interleaving of computations), but not why? Does the crash happen just with the code you show above?

**Comment by clemisch** [comment]
Hey @gnecula, thank you for your answer. Yeah, I could have noticed earlier that `id_print((x, y), what="x,x^2")` would have been the correct usage...

Concerning the crash: it consistently happens for me on GPU in every situation so far, but never on CPU.

**Comment by skye** [comment]
FYI host_callback_test.py repros this with the latest released jaxlib (`0.1.56`) on GPU. Something like:
`TF_CPP_MIN_LOG_LEVEL=0 python tests/host_callback_test.py`
CPU is fine.

**Comment by gnecula** [comment]
I think I know the root cause of the bug, it requires some changes in XLA for GPU. I have not been able to look into this yet.

**Comment by clemisch** [comment]
Hey @gnecula, is there any news on this? 

Repro still does not work on GPU with latest releases or compiled from head. For my interest: Is `id_tap` mostly used on TPUs?

**Comment by gnecula** [comment]
Unfortunately there are no news. This requires changes in XLA:GPU and it is not easy for me to make those changes. The best hope I have for this is for the issue to go away in an upcoming alternative implementation of `id_tap` for CPU and GPU. But this is still a few months away. 

You are right that most people use `id_tap` on TPUs.

**Comment by clemisch** [comment]
Just a friendy bump, as I've noticed that this still does not work on GPU while I tried out `host_callback` for the first time. I would be very happy about a fix, as this would solve https://github.com/google/jax/issues/1530 for me!

---

Repro for completeness (nothing special, not related to #1530). Crashed on GPU, works on CPU host.

```python
import numpy as np
import jax
import jax.experimental.host_callback as hcb
import scipy.ndimage as nd
​
def host_filter(x):
    return nd.gaussian_filter(x, 10)
​
@jax.jit
def device_fun(x):
    y = x**2
    z = hcb.call(host_filter, y, result_shape=y)
    return z**2
​
a = jax.device_put(np.random.rand(1000))
b = device_fun(a)
```

crashed with same error

```
2021-03-05 14:49:52.165327: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/outfeed_thunk.cc:56] Check failed: ShapeUtil::Compatible(config_.input_shape, outfeed_buffers->shape()) XLA program outfeed request of shape (f32[1000]) did not match the runtime's outfeed buffer of shape u32[2]
Aborted
```

**Comment by clemisch** [comment]
Hey @gnecula, 

sparked by the discussion in #5577 I tested my snipped again with `CUDA_VISIBLE_DEVICES=0` and it worked! 

```python
import numpy as np
import jax
import jax.experimental.host_callback as hcb
import scipy.ndimage as nd

import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

def host_filter(x):
    return nd.gaussian_filter(x, 10)

@jax.jit
def device_fun(x):
    y = x**2
    z = hcb.call(host_filter, y, result_shape=y)
    return z**2

a = jax.device_put(np.random.rand(1000))
b = device_fun(a)    # works!
```

Because the fix for multi-GPU 

> will take at least a couple of weeks to land

maybe we can implement a nicer error message when people (accidentally) combine multi-GPU and `host_callback`?

**Comment by gnecula** [comment]
Doesn't `CUDA_VISIBLE_DEVICES=0` turn off all GPU devices? This means that your code runs on CPU. In other words, it is not a surprise that your code works because the bug appears only on GPU.

**Comment by clemisch** [comment]
No, PCI bus indexing is 0-based. So `CUDA_VISIBLE_DEVICES=0` runs on GPU #0. 

`CUDA_VISIBLE_DEVICES=""` turns off GPU.
