### ISSUE TITLE
Jax numpy does not throw IndexError when array index out of bounds

### ISSUE THREAD

**Issue by jawolf314** [google/jax#4383]
I was surprised by the behavior the the Jax numpy array not throwing an IndexError when using an index that is out of bounds, since NumPy throws an IndexError. I wanted to file an issue just to see whether this is expected/desired behavior from Jax.  Note the second unit test below will fail.  Thanks.
```
import unittest

class NumPyTestCase(unittest.TestCase):
    def test(self):
        with self.assertRaises(IndexError) as context:
            import numpy as np
            a = np.random.random((10,10))
            a[10,:]

class JaxTestCase(unittest.TestCase):
    def test(self):
        with self.assertRaises(IndexError) as context:
            import jax.random as random
            import jax.numpy as jnp
            a = random.normal(random.PRNGKey(2020), (10,10))
            a[10,:]

np_test_case = NumPyTestCase()
np_test_case.test()

jax_test_case = JaxTestCase()
jax_test_case.test()
```

**Comment by jawolf314** [comment]
One further comment, I was also surprised the when indexing values above the maximum index of the Jax array -- the return values are always the last indexed of the array. E.g., if we access `a[11,:]` or `a[12,:]` above it will be the same as if we accessed `a[9,:]`.

**Comment by jakevdp** [comment]
Hi - thanks for the report!

This is a known feature in JAX that you can read about here: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#%F0%9F%94%AA-Out-of-Bounds-Indexing

**Comment by jawolf314** [comment]
Thanks for doc reference. So much of the API is like NumPy, that I assumed the indexing would be as well. Will definitely take a closer look at "The Sharp Bits".
