### ISSUE TITLE
SVG version of logo

### ISSUE THREAD

**Issue by janosh** [google/jax#4389]
Could you guys make available an SVG version of the JAX logo? Would be useful for websites like the sure-to-come JAX wiki article. Wikipedia stores logos in SVG format if possible (see e.g. [TensorFlow](https://en.wikipedia.org/wiki/TensorFlow#/media/File:TensorFlowLogo.svg) and [PyTorch](https://commons.wikimedia.org/wiki/File:PyTorch_logo_black.svg) for comparison).

**Comment by mattjj** [comment]
Great idea! Attempted in #4400.
