### ISSUE TITLE
Help needed for creating a package for gentoo

### ISSUE THREAD

**Issue by epsilon-0** [google/jax#4396]
I'm trying to pack this up for gentoo and had a few questions about how to best package it.

A few things that come to mind
- Should I make two separate packages for `jax` and `jaxlib` ?
- If I want to keep them as the same package (`jax`) can I just use the `jax` release archives and then use the `jaxlib` from inside that instead of downloading the second archives? I assume that if I do them separately, I should download the separate archives.
- There are a lot of build time options available to `jaxlib` compilation.
  - What versions of bazel are supported? When I tried to compile it manually without bazel, it tried downloading `bazel-2.0.0` even when later bazel releases are available. 
  - What versions of `gcc` are supported? 
  - What versions of `CUDA` are supported?

I am asking this as these are important when installing tensorflow, which is very painful to compile, to say the least.
Would love to get this running in gentoo.

Thanks,
Aisha

**Comment by epsilon-0** [comment]
Bumping for attention :-/

**Comment by hawkinsp** [comment]
If I were going to make such a package, I would probably package `jax` and `jaxlib` together. They have a fairly close integration with each other, and for those who simply want to install a package from their distribution, I see no reason to separate them.

`jax` and `jaxlib` are both built from the same source tree, so you should only need to download the source once.

For `jaxlib`, the build requirements are mostly the same as TensorFlow's build requirements in terms of gcc/clang versions. We explicitly pin a `bazel` version in our build script (3.1.0, same as TF). That's not to say things wouldn't work with other versions, but we test that one.  For CUDA, we always try to support the same release as TF, but we also try to provide wheels for other versions even though they are somewhat less tested.

Hope that helps!
