### ISSUE TITLE
advanced boolean indexing

### ISSUE THREAD

**Issue by LysSanzMoreta** [google/jax#4418]
Hi!

I think issue #166 does not resolve my problem, and I require advanced indexing. Please correct me if I am wrong on the implementation or there is an alternative solution. I am using boolean indexing to create a mask from a multidimensional array as follows:

```
Dataset = [[1,2,0],
              [1,4,0],
              [0,0,0]]

ax1, ax2 = np_jax.where(~Dataset[:, 0].any(axis=2)) # Returns axes where Dataset is 0 for dimension 2 for column 0
mask = np_jax.ones(Dataset.shape)  
mask = jax.ops.index_update(mask, jax.ops.index[ax1,ax2], 0) #equivalent to mask[ax1, ax2] = 0  # zeroes


```

I get the following error:

> IndexError: Array boolean indices must be concrete.

Open to alternatives, otherwise I would like to please request advanced indexing,

Thanks!

**Comment by jakevdp** [comment]
Hi,
The issue is that the single argument version of `jnp.where` is not compatible with JIT, because the size of the returned arrays is dependent on the content of the input array.

I think you could instead use the three-argument version of `np.where`; something along the lines of this:
```
mask = np_jax.where(~Dataset[:, 0].any(axis=2), 0, 1)
```

**Comment by LysSanzMoreta** [comment]
Ohh! It worked, thanks for rethinking it. Last question, because I have the same error problem but with np_jax.isin. I try to use as:

```
c_indexes = [4,5]
sequences = [[3, 1, 4],
                      [5,6,1],
                      [2,5,1],
                      [4,7,8]] 
ix = np_jax.isin(sequences[:,0], c_indexes) 
c = sequences[np_jax.where(ix),1:] 
```

Thanks for your help, I struggle thinking in this unmutable version of numpy, getting used to it hehhe

Thanks again! and have  anice day

**Comment by jakevdp** [comment]
The only way to JIT-compile this code is for `sequences` and `c_indices` to be a static values, because the size of `c` depends on their content, and array sizes must be static within JIT-compiled code.

**Comment by LysSanzMoreta** [comment]
Thanks! I am looking into it, my c_indexes size also changes so might be a problem, but I will try think about something...Thanks again!
