### ISSUE TITLE
JAX Differentially Private SGD Example Compilation Very Slow

### ISSUE THREAD

**Issue by n2cholas** [google/jax#4447]
The differentially private SGD example takes a very long time to JIT compile at larger batch sizes. The compilation time spikes after a batch size of 512. Any way to fix this or get around this? 

Below is a table with some JIT compile times. [This](https://colab.research.google.com/drive/1KItJmLUG0598wfOdx5_kGFDLskH8uE_Y?usp=sharing) colab has more timings.

| Batch Size | Compilation Time |
|------------|---------------------|
|64| 21.71 |
|128| 43.99 |
|256| 63.85 |
|512| 107.62 |
|1024| 300.03 |
|2048| 592.16 |

The DP SGD [example in the repo](https://github.com/google/jax/blob/master/examples/differentially_private_sgd.py) runs with errors, so the colab contains fixes from #4446. 

EDIT: In general, should we expect compilation time to scale with batch size? If so, why?

**Comment by mattjj** [comment]
Thanks for the question!

No, we shouldn't expect compilation time to scale with batch size. It could mean we're unrolling an array somewhere in the example.

**Comment by n2cholas** [comment]
I think it may be a JIT/stax bug, as it seems like stax.MaxPool is the culprit here. When I remove the maxpool layers, the compilation times for per-example gradients stop being linear w.r.t. to the batch size. [Here](https://colab.research.google.com/gist/n2cholas/905e8209e154a99555673b7aa7856b2a/slow-jit-minimal.ipynb) is a minimal example of this.

**Comment by hawkinsp** [comment]
This was already fixed at head by https://github.com/google/jax/pull/4439

Note that PR is too new to be in a `jaxlib` release, so try doing something like:
```
!pip install --upgrade git+https://github.com/google/jax
```
in your Colab.

I get the following timings at head in a Colab:

![image](https://user-images.githubusercontent.com/348932/95104137-7ee27a00-0703-11eb-8ea6-9786b68c50fc.png)
