### ISSUE TITLE
Operations on static inputs/shapes yield concretization errors 

### ISSUE THREAD

**Issue by mathisgerdes** [google/jax#4449]
The newer version of JAX fails with certain computations that depend on static values or shapes inside JIT compiled functions (only tested on CPU). It doesn't seem like this is expected behavior.

In version `0.1.73`, the following shape-dependent JIT compiled function works as expected:
```python
@jax.jit
def custom_ones(arr):
  count = jnp.add(arr.size, 1)
  return jnp.ones((count,))

>>> a = jnp.ones((3,))
>>> custom_ones(a)
DeviceArray([1., 1., 1., 1.], dtype=float32)
```
Using version `0.2.0` (e.g. on colab), the same thing fails with a `TypeError: Shapes must be 1D sequences of concrete values of integer type (...)`. Similar behavior occurs if instead of the shape of an input array, the function is statically compiled on a single input value. Besides `jnp.add`, other operations like `jnp.sqrt` and `jnp.ceil` also fail for the new but not the old version.
Interestingly, it works if instead of `jnp.add` one uses `arr.size + 1` (some functions like `jnp.round` also work).

**Comment by mattjj** [comment]
Thanks for the question! Can you check out [this doc on omnistaging](https://github.com/google/jax/blob/master/design_notes/omnistaging.md) and let me know if it answers your questions? (See in particular [this section](https://github.com/google/jax/blob/master/design_notes/omnistaging.md#using-jaxnumpy-for-shape-computations) though I recommend reading the whole thing if you want the full context.)

**Comment by mathisgerdes** [comment]
Yes! Thank you. Should've maybe investigated the docs again, before posting it here.
