### ISSUE TITLE
conda installation cuda incompatibility error invalid

### ISSUE THREAD

**Issue by andyorange** [google/jax#4450]
Trying to install jax via 

conda install -c conda-forge jax

results in an error wrt cuda that makes no sense, see attached snapshot.
![jaxCondaError](https://user-images.githubusercontent.com/23657793/95017394-61f16c80-0659-11eb-9718-f58d81462937.png)

**Comment by jakevdp** [comment]
Hi @andyorange, thanks for the report, and sorry that you're seeing this issue! It might be worth also posting this question at https://github.com/conda-forge/jax-feedstock/issues. That should get the attention of the people who put together the JAX conda-forge recipe, and they may have more direct expertise in conda issues.

**Comment by hawkinsp** [comment]
Closing, because the Conda recipe is maintained separately to JAX itself.
