### ISSUE TITLE
Integer matrix multiplication with int8 input and int32 accumulation

### ISSUE THREAD

**Issue by malmaud** [google/jax#4465]
I'm trying to do a hardware-accelerated matmul with int8 input tensors and get back an int32 tensor, but I don't see any way to do that:

```
x=jnp.array(100).reshape((1,1)).astype(jnp.int8)
jnp.matmul(x,x)
```

gives back an int8 result, [[16]]. I don't see any options to specify an accumulator type separate from an input type to `jnp.matmul` or `lax.dot_general`. 

I could cast `x` to `jnp.int32` before the multiply, but I want to use a hardware-accelerated int8 matmul, if available.

Ultimately, I'd like to be able to specify an arbitrary integer bit width input and desired accumulator as well (eg, 4-bit input with 16-bit accumulation), even if current hardware can't accelerate that.

Thanks!

**Comment by hawkinsp** [comment]
Thanks! I filed a feature request with the XLA folks; they will need to add support first before we can have hardware acceleration.

**Comment by lukaszlew** [comment]
Can we emit correct XLA i.e. int8 inputs, int32 output, before there is hardware acceleration?
TPU compiler is not the only consumer of the HLO.

**Comment by jekbradbury** [comment]
I _believe_ the situation here is that HLO service protobufs can represent the difference between "int8 input, int8 output dot" and "int8 input, int32 output dot", but this isn't accessible from the client HLO builder. I could definitely be wrong about that, though (and the most straightforward way to add support to the client would be to add a new `output_precision` attribute, which would also show up in the service HLO).
