### ISSUE TITLE
Embedded GPUs and TPUs with JAX

### ISSUE THREAD

**Issue by aizzaac** [google/jax#4487]
Hi

I want to know if the functionalities for cloud TPUs are available for embedded GPUs and TPUs?
Has anyone tested it?

Thank you

**Comment by skye** [comment]
Can you be more specific about which functionalities you mean? In general, most JAX code that runs on Cloud TPU can be run other platforms as well. Depending on how the code was written, you might need access to multiple GPUs.

**Comment by skye** [comment]
Based on your question in #3004, do you mean [Edge TPUs](https://cloud.google.com/edge-tpu) when you say embedded TPUs?

**Comment by aizzaac** [comment]
Yes, the embedded processors. Those usually need quantization.

**Comment by hawkinsp** [comment]
We have no specific support for embedded GPUs or TPUs at this time. That said, I see no reason JAX wouldn't work on an embedded NVidia GPU (e.g., a Jetson) or similar if built for that platform. We have nothing to announce with respect to Edge TPU at this time.
