### ISSUE TITLE
[question] how to JIT a function which includes custom primitives

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#451]
Wandering around source code of JAX, I come up with the following solution to implement a custom primitive. But when I run `jit(g)(x)`, I got the error message `NotImplementedError: XLA translation rule for 'f' not implemented`. The message suggests that I have to write some translation rule in XLA language. But it is clear that I can jit both `f_impl` and `f_grad`. I wonder if there is any solution without having to write translation rule?

```
import jax.numpy as np

from jax import jit, grad
from jax.core import Primitive
from jax.interpreters import ad

def f(x):
    return f_p.bind(x)

def f_impl(x):
    return x ** 2

def f_grad(o, x):
    return 2 * x + 1  # make it wrong to test

f_p = Primitive('f')
f_p.def_impl(f_impl)
f_p.def_abstract_eval(lambda x: x)
ad.defjvp2(f_p, lambda g, o, x: g * f_grad(o, x))

def g(x):
    y = x * 3
    z = f(y)
    return np.sum(z)

x = np.arange(3.)
h = grad(g)
print(h(x))
```

Another non-related question is: `jacrev` will give a correct gradient despite that I haven't defined `transpose_rule` for `f`. Is it true that under the hood, `vjp` will use the definition of `jvp` with tangent is replaced by cotangent?

Thanks in advance!

**Comment by neerajprad** [comment]
This is not related to the question specifically, but I would like to register an interest in documentation / tutorial on writing custom primitives in JAX.

**Comment by shoyer** [comment]
See here for some recent work on custom JVPs: https://github.com/google/jax/pull/636

Per https://github.com/google/jax/issues/623#issuecomment-485147248, it seems that one viable way to define JIT-able custom ops on CPUs (e.g., calling back into NumPy) would be to make use of XLA's CustomCall() primitive.

**Comment by fehiepsi** [comment]
Thanks @shoyer for the update! I’ll try to make a PR for grad of gamma sampler to test out the recent support for defining custom primitives. :)

**Comment by shoyer** [comment]
I opened https://github.com/google/jax/issues/766 to address this specific issue
