### ISSUE TITLE
[Feature Request] mish activation function

### ISSUE THREAD

**Issue by abhinavsp0730** [google/jax#4523]
Hi, @mattjj @froystig I would like to contribute by adding  ```mish``` activation in  Jax function. It's a  Self Regularized Non-Monotonic Neural Activation Function.

```mish``` =  ```x * tanh(softplus(x))```
paper: https://arxiv.org/abs/1908.08681

**Comment by hawkinsp** [comment]
This has come up multiple times before, see #1676 and #2842 .

I think the only thing that would change our minds is if `mish` is now more popular. Can you provide evidence that it is widely used? Otherwise it makes sense to me to keep it out of tree, given it is a 1-liner anyway.

**Comment by abhinavsp0730** [comment]
Hi, @hawkinsp thanks. ```mish``` is having official implementation in various ML library. Kindly see the attached pics. 
![IMG_20201009_221440](https://user-images.githubusercontent.com/43638955/95610407-e8ed7d00-0a7d-11eb-95fc-3a933e4aef77.jpg)
![IMG_20201009_221425](https://user-images.githubusercontent.com/43638955/95610433-f145b800-0a7d-11eb-9ae2-c11e0d550372.jpg)
This activation function is quite new(2019) but gained a lot of popularity. This paper is having ```82``` citation. And you can find some more amazing stats about ```mish``` here, https://github.com/digantamisra98/Mish .
Thanks.

**Comment by hawkinsp** [comment]
`mish` seems to have little usage in the research community, so I'm reluctant to add it the standard library. It also wouldn't help JAX users much to add it; if anyone wants `mish`, the complete implementation is:
```
def mish(x): return x * jnp.tanh(jax.nn.softplus(x))
```
and that's something that is easy to copy and paste into a model.

We can reevaluate if `mish` has significant research impact and becomes widely used. So I would say: not yet.

**Comment by digantamisra98** [comment]
@hawkinsp It would be nice to re-evaluate this request as of now considering Mish got added to standard PyTorch ([PR](https://github.com/pytorch/pytorch/pull/58648), [Feature Request Issue](https://github.com/pytorch/pytorch/issues/58375#issuecomment-842654130)) based on similar evaluation criteria. 
Additionally the paper has received nearly 270 citations as per [Scholar](https://scholar.google.com/citations?user=LwiJwNYAAAAJ&hl=en).

**Comment by carlosgmartin** [comment]
The paper now has 1,538 citations according to [Google Scholar](https://scholar.google.com/scholar?q=mish+activation+function).

**Comment by carlosgmartin** [comment]
@hawkinsp @mattjj 

Some places where mish has been requested:
- https://github.com/google/flax/issues/584
- https://github.com/google/flax/discussions/3391
- https://github.com/google/objax/issues/225
- https://github.com/google/jax/issues/2842
- https://github.com/google/flax/discussions/3483
- https://github.com/google/jax/pull/1676
- https://github.com/google/jax/issues/4523

Looks like there's enough demand and citations (see my post above) for it?

The following links might be of interest:
- [Benchmarking PyTorch’s Native Mish](https://benjaminwarner.dev/2021/07/19/benchmarking-pytorch-native-mish)
- [mish-cuda: Mish Activation Function for PyTorch](https://github.com/thomasbrandon/mish-cuda)

So there might be value in a non-trivial efficient implementation.
