### ISSUE TITLE
Fortran reshape order runs but gives wrong behaviour

### ISSUE THREAD

**Issue by martiningram** [google/jax#453]
Hi there,

Big fan of Jax, thanks for making this!

I believe there is a problem with specifying the reshaping order:

```python
a = np.arange(6) + 1
np.reshape(a, (3, 2), order='F')
```

Should give:

```
array([[1, 4],
       [2, 5],
       [3, 6]])
```

But instead gives:

```
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)
```

Basically, it is ignored and always does column-major reordering. If unsupported, it would be nice for it to just fail rather than silently carry on.

**Comment by mattjj** [comment]
Thanks for noticing this! #456 should squash it.
