### ISSUE TITLE
host_callback.id_print fails with empty arrays on CPU

### ISSUE THREAD

**Issue by gnecula** [google/jax#4533]
Printing or tapping empty arrays fails on CPU (works on GPU and TPU)

Simplest example:
```
host_callback.id_print(np.ones((2, 0)))
```

**Comment by NeilGirdhar** [comment]
(I've been hit by this before.)

**Comment by gnecula** [comment]
I have fixed this in XLA, so the bug should be fixed with an up-to-date version of XLA.
