### ISSUE TITLE
Jax is slower than Numpy on CPU

### ISSUE THREAD

**Issue by CleanPegasus** [google/jax#4537]
I ran the sample Colab notebook from Jax Quickstart" on CPU and found that Jax is slower compared to NumPy. 

Numpy took **523 ms** while Jax took **847 ms**.

**Comment by mattjj** [comment]
Which cell are you referring to?

In general, JAX can be slower than NumPy on CPU; it all depends on how `jax.jit` is used. In fact, without `jax.jit`, we should expect JAX to be slower than NumPy; NumPy is quite hard to beat! With `jax.jit`, it depends on the workload, and whether there are enough optimizations available to do better than NumPy can.
