### ISSUE TITLE
Support for scipy.stats.norm.logcdf

### ISSUE THREAD

**Issue by martiningram** [google/jax#454]
Hi there,

Adding support for `scipy.stats.norm.logcdf` would be very useful to me (for probit in the likelihood).

A workaround would be good too. I saw there is `erf`, but I could really do with a log version for numerical reasons.

Thanks!

**Comment by hawkinsp** [comment]
PR #460 should have fixed the problem. Please try it out!

**Comment by martiningram** [comment]
Fantastic, thanks so much!
