### ISSUE TITLE
factor named_call primitive into jax core

### ISSUE THREAD

**Issue by froystig** [google/jax#4558]
Both [Flax](https://github.com/google/flax/blob/717d50489d46efb92fa846878d51c4c06936b7cd/flax/core/named_call.py) and [Haiku](https://github.com/deepmind/dm-haiku/blob/1909345c550f56825e8c8aa42621c8a307741ac8/haiku/_src/named_call.py) implement a `named_call` JAX primitive. How about we move this into JAX core?

This is the same as JAX's call primitive (see `jax.core.call_p`), except in how it compiles to XLA, where the name that it carries is included in the HLO computation name. This makes it useful for annotating profiles.

cc @LenaMartens @tomhennigan @trevorcai @levskaya @jheek @avital

**Comment by levskaya** [comment]
I'd be a big fan of doing this!  I tried suggesting it before, but I think people were too busy to think about it at the time.  It would be much better having such a simple, basic primitive live in a single place in JAX.

**Comment by shoyer** [comment]
Yes, please!

**Comment by froystig** [comment]
As I understand it, there might be differences between what we'd upstream to JAX and what's currently in Haiku, namely due to Haiku's state threading (?). The Flax version is roughly what I had in mind originally.

**Comment by qiuminxu** [comment]
The stateful_named_call in haiku looks like a user of the named_call_p that doesn't need to be upstreamed. I attempted a draft in PR #4733 .

**Comment by froystig** [comment]
closed by #4733
