### ISSUE TITLE
tracking function compilation

### ISSUE THREAD

**Issue by jonasrauber** [google/jax#457]
I find myself adding statements like `print('compiling function $NAME')` to jitted functions quite often to detect accidental recompilations (e.g. due to unnecessary changes in arrays sizes or static args that get overriden accidentally, maybe even with an equal but not identical value).

Here are three ideas (potential feature requests) that I would find quite helpful:

1. a single position / hook to print a log statement whenever a function gets compiled
2. the ability to disable recompilation of functions (or to even specify how often a function is allowed to be compiled for different types; e.g. as a parameter to `jax.jit`)
3. the ability to disable jit compilation from a certain point of the program onwards (not to _disable jit_ in the sense of making it a no-op and executing without jit, but a way to say that every compilation that is triggered after this point of the program should be considered an error)

**Comment by jekbradbury** [comment]
Idea 1 was implemented in #1240.

**Comment by jakevdp** [comment]
Circling back after five years (!) and things are in a pretty good state:

- [`jax.log_compiles`](https://jax.readthedocs.io/en/latest/_autosummary/jax.log_compiles.html) now exists, and can be used to turn on logging of compilation.
- [ahead of time lowerning](https://jax.readthedocs.io/en/latest/aot.html) tools now exist, so e.g. you can do `f_compiled = jax.jit(f).lower(*args).compile()`, and then `f_compiled` will error if it is passed arguments that would trigger a re-compilation
- the [`jax.disable_jit`](https://jax.readthedocs.io/en/latest/_autosummary/jax.disable_jit.html) and [`jax.ensure_compile_time_eval`](https://jax.readthedocs.io/en/latest/_autosummary/jax.ensure_compile_time_eval.html) decorators exist and can be used to ensure that code within their context is not jit-compiled.

Given those tools, I think this request can be closed!
