### ISSUE TITLE
[Documentation? + Feature Req] Pytrees do not appear to work with `jax.experimental.loops`

### ISSUE THREAD

**Issue by zachary-jablons-okcupid** [google/jax#4600]
Hey there,

A while back I made some Jax stuff I was doing much faster (than a simple for loop) by wrapping the training steps using `jax.experimental.loops` and compiling that with `jit`. I was revisiting this code with the hopes of refactoring some of the uglier parts to use Haiku, and found some issues with this part. It appears that while a function that iterates through and updates a Pytree using a simple Python loop works, putting this Pytree in a `jax.experimental.loops.Scope` object fails with `jax.traceback_util.FilteredStackTrace: TypeError: <class 'dict'> is not a valid JAX type`

I'm not sure if this is intended behavior, so I'm tagging this as potentially a documentation issue - as the [documetnation](https://jax.readthedocs.io/en/latest/jax.experimental.loops.html) on the `jax.experimental.loops` module makes no mention of Pytrees in the restrictions section (afaict, but I may have simply missed it). 

I've cribbed an example from the [post](https://sjmielke.com/jax-purify.htm) that introduced me to Pytrees in Jax to show what happens. Here's the [code](https://gist.github.com/zachary-jablons-okcupid/663c1e69621ea5c5677f3ecde8ffe728) and here's the [output](https://gist.github.com/zachary-jablons-okcupid/f46d656db95bf2f1af7c95cbb13c10b3) I get in my environment.

My environment is Python 3.7.5, with

```
jax==0.2.3
jaxlib==0.1.55
```

If this is intentionally unsupported, I would love to know how I can speed up this training loop using Pytrees, as this example with an incredibly simple function and just 10 steps takes over 11000ms (units changed for dramatic effect), whereas I was able to see fairly significant speedups using the `loops` module for a much larger problem.

Thanks,
Zach

**Comment by gnecula** [comment]
pytrees should be supported, I will implement this.

**Comment by zachary-jablons-okcupid** [comment]
Hey just checking in - is there any update available on this? Thanks!

**Comment by zachary-jablons-okcupid** [comment]
Hey there,

Is this merged solution part of the latest release? (`jax==0.2.8` / `jaxlib == 0.1.59`)

I see in the [documentation](https://jax.readthedocs.io/en/latest/jax.experimental.loops.html) the line 

>The scope fields can be pytrees, and can themselves be mutable data structures.

However with the new releases I am still getting the same error with that code as I was before (unless there's something special I need to do to modify that code to work?).

**Comment by gnecula** [comment]
Hi,

The feature is merged in github master but came in after we cut the latest release ([changelog](https://jax.readthedocs.io/en/latest/CHANGELOG.html)).
