### ISSUE TITLE
Tensorboard profiler not working on GCloud TPUs

### ISSUE THREAD

**Issue by AlbertAlonso** [google/jax#4610]
I wanted to see the tracer of a simple jax script running on a Cloud TPU but the task has become harder than anticipated. 

I've got tensorboard profiler working as expected when running Tensorflow. That is, when all the versions of my programs match, e.g. tensorflow==2.3, tensorboard==2.3, cloud-tpu-profiler==2.3 and TPU software version==2.3, as mentioned in [this issue](https://github.com/tensorflow/tensorboard/issues/2628). 

However, JAX seems to not be compatible with TPU software version 2.3, since when I try to run `simple_jax.py` on that TPU, it can't connect to the TPU. Looking at the JAX setup guide for TPU, I saw that the tpu version has to be `tpu_driver_nightly`. Hence, I changed the version by following [this guide](https://cloud.google.com/tpu/docs/version-switching), and now the jax program runs perfectly on TPU, but when I want to profile it, it seems like tensorboard captures the profile (the log files are indeed created in the correct bucket directory), but it is not able to display them. 

![tpu-issue](https://user-images.githubusercontent.com/38870744/96236793-c2a77000-0f9c-11eb-8f04-a7fecb014888.gif)
(The gif starts with the dialog open to avoid being a perfectly looped gif)

It looks like it is loading the profile and then goes back to "No Profile data found". If I download the log files and try to open them in my own machine, tensorboard doesn't detect them either. (There is no terminal error display at any point).

My guess is that there is some version incompatibility, but I was wondering what you think the issue is and how could it be fixed.

**Comment by willwhitney** [comment]
This is happening for me on both CPU and GPU. 

It started happening when I updated jax (to 0.2.3) and jaxlib (to 0.1.55). I updated tensorboard to 2.3.0 in the hopes that it was a version mismatch and updating would fix it, but this did not help.

**Comment by willwhitney** [comment]
I believe this is the same as https://github.com/google/jax/issues/4427

**Comment by bchetioui** [comment]
@willwhitney @AlbertAlonso did you try with the versions recommended by @zhangqiaorjc [here](https://github.com/google/jax/issues/4427#issuecomment-731341850)?

**Comment by AlbertAlonso** [comment]
It seems like it's working! Great! I will close the issue then.
