### ISSUE TITLE
Can't fix ReadTheDocs build

### ISSUE THREAD

**Issue by alewis** [google/jax#4612]
Hi all,

I'm having trouble understanding the build errors in #4175 in service of #1531 . One seems to be a test failing on only one build (but there is no error message that I can understand), and the other has something to do with ReadTheDocs (but again the error messages don't seem to actually address the code changes). The PR I think is otherwise ready to go. Could anyone help me out?

**Comment by hawkinsp** [comment]
Those look unrelated to your change, so I wouldn't worry about them. Hopefully they are some sort of transient problem.

Maybe try rebasing your change on top of git master and push it again? (This will force a rebuild, which might work.)

**Comment by alewis** [comment]
That actually fixed it, thank you!
