### ISSUE TITLE
docs: jax.scipy.stats.poisson not on the public API docs webpage

### ISSUE THREAD

**Issue by matthewfeickert** [google/jax#4648]
Hi. With the release of JAX [`v0.2.4`](https://github.com/google/jax/releases/tag/jax-v0.2.4) (congrats on the release btw) we noticed that `jax.scipy.stats.poisson` is not documented on the [public API docs for the `jax.scipy` package](https://jax.readthedocs.io/en/stable/jax.scipy.html#jax-scipy-stats). However, other distributions like [`jax.scipy.stats.norm` are documented](https://jax.readthedocs.io/en/stable/jax.scipy.html#module-jax.scipy.stats.norm).

Is this intentional (are there upcoming plans for `jax.scipy.stats.poisson`)? Or does `jax.scipy.stats.poisson` just still need to get put into Sphinx?

(cc @lukasheinrich @kratsg)

**Comment by hawkinsp** [comment]
We just forgot to add `poisson` (and in fact several other distributions to the docs). #4652 fixes this.

**Comment by matthewfeickert** [comment]
Thanks!
