### ISSUE TITLE
Behavior of jnp.in1d not matching np.in1d

### ISSUE THREAD

**Issue by aldragan0** [google/jax#4660]
While implementing setdiff1d, I've come across this weird case where the `np.in1d` would return duplicate items if it finds such items and the `np.in1d` implementation would return the set-like array.

I've attached a code sample to reproduce this below:
```
from jax import numpy as jnp # version: 0.2.3
import numpy as np # version: 1.19.2

a = jnp.array([3,-1,0,0,7,-3,-5,0,3,-5,-3,7,0,1,-1,-1,0,1,-1,0,-7,-4,3,-2])
b = jnp.array([-2,-3,-1,0,3,-2,6,0,1,0,0,-5,-2,0,0,0,-2,-2,6,2,-6,-3,-2,-3])

lax_ar = jnp.in1d(a, b, invert=True)
np_ar = np.in1d(a, b, assume_unique=True, invert=True)

print(a[lax_ar])
print(a[np_ar])
```

Upon further verification of this issue I've found that the problem reproduces due to numpy's implementation of in1d. I believe we might need to implement the sorting based option for longer sequences.

Also, if it is possible, I would like to try and implement it :).

**Comment by jakevdp** [comment]
I think the issue here is that you passed `assume_unique=True`, when the values in the arrays are not unique. In this case, I think the output is expected to be nonsensical.

If you pass `assume_unique=False`, the numpy results match JAX.

**Comment by aldragan0** [comment]
Sorry, I was under the presumption that it will behave similarly even though `assume_unique=True`, I now understand that this is not the case :).
Will close this issue.
