### ISSUE TITLE
Derivation of an array using grad function 

### ISSUE THREAD

**Issue by yangzehao** [google/jax#4670]
I am a new guy using jax. When I try to derivate a function using the function grad, errors exist. 
#### The code with an error:
```python
from jax import grad
from scipy.misc import derivative
from jax.scipy.special import *
from jax.numpy import *

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return f


f = lambda x: sin(x)
df = diff(f)
m = array([1.0, 2.0, 3.0])
print(df(m))
```

#### The code without an error:
```python
from jax import grad
from scipy.misc import derivative
from jax.scipy.special import *
from jax.numpy import *

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return f


f = lambda x: sin(x)
df = diff(f)
m = [1.0, 2.0, 3.0]
print(list(map(lambda x: float(df(x)), m)))
```
From my understanding, the second code block is not perfect. Can jax natively get the derivation of a function at points: [1., 2., 3.] without using the map function? Any suggestion is appreciated. Thanks

**Comment by jakevdp** [comment]
In the first version of your code, you are trying to compute the gradient of a function with multiple outputs, and you get this error:
```pytb
TypeError: Gradient only defined for scalar-output functions. Output had shape: (3,)
```
If you want the function to compute the gradient element-by-element, you can use the [`vmap` transform](https://jax.readthedocs.io/en/latest/jax.html#jax.vmap) to do this:
```python
from jax import grad, vmap
from scipy.misc import derivative
from jax.scipy.special import *
from jax.numpy import *

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return f


f = lambda x: sin(x)
df = vmap(diff(f))
m = array([1.0, 2.0, 3.0])
print(df(m))
# [ 0.5403023  -0.41614684 -0.9899925 ]
```
This effectively does the same thing a your map-based approach, but in a way that keeps the function compatible with `jit` and other JAX transforms.

**Comment by mattjj** [comment]
+1 to Jake's answer, except one tweak to the last sentence: `jit` and other JAX transformations still work with Python's builtin `map`, but using `vmap` instead can make things faster to compile and faster to execute!

**Comment by jakevdp** [comment]
What I had in mind when I said the `map` solution was incompatible with JIT was a situation like this, wherre we put the map within a function and attempt to jit compile it:
```python
from jax import grad, jit
from scipy.misc import derivative
from jax.scipy.special import *
from jax.numpy import *

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return f


f = lambda x: sin(x)
df = diff(f)
m = [1.0, 2.0, 3.0]
def g(x):
  return list(map(lambda x: float(df(x)), m))

jit(g)(m)
```
```pytb
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

The problem arose with the `float` function. If trying to convert the data type of a value, try using `x.astype(float)` or `jnp.array(x, float)` instead.

While tracing the function g at <ipython-input-1-25f2990dcd06>:16, this value became a tracer due to JAX operations on these lines:

  operation e:float32[] = sin d:float32[]
    from line <ipython-input-1-25f2990dcd06>:13 (<lambda>)

  operation f:float32[] = cos d:float32[]
    from line <ipython-input-1-25f2990dcd06>:13 (<lambda>)

  operation h:float32[] = mul g:float32[] f:float32[]
    from line <ipython-input-1-25f2990dcd06>:13 (<lambda>)

You can use transformation parameters such as `static_argnums` for `jit` to avoid tracing particular arguments of transformed functions.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(float32[])>with<DynamicJaxprTrace(level=0/1)>
```

**Comment by mattjj** [comment]
Well, I think the problem is `float` there, not `map`. This version runs fine:

```python
from jax import grad, jit
from scipy.misc import derivative
from jax.scipy.special import *
from jax.numpy import *

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return f


f = lambda x: sin(x)
df = diff(f)
m = [1.0, 2.0, 3.0]
def g(x):
  return list(map(lambda x: df(x), m))

jit(g)(m)
```

**Comment by yangzehao** [comment]
Thanks, @jakevdp, and @mattjj. I compared the performance of the code above, it seems that the vmap function is much more efficient
#### Performance comparison

```python
from jax.scipy.special import *
from jax.numpy import *
import jax.random
from jax import vmap, grad, jit
import time

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return f
	
f = lambda x: sin(x)
m = linspace(1,10,10000)

#1. Test with map	
start = time.time()
df = diff(f)
res = list(map(lambda x: float(df(x)), m))
elapsed_time = (time.time() - start)
print(elapsed_time)
#7.52 cpu time

#2. Test with vmap	
start = time.time()
df = vmap(diff(f))
res = df(m)
elapsed_time = (time.time() - start)
print(elapsed_time)
#0.034 cpu time

#3. Test with jit and map
start = time.time()
df = diff(f)
def g(x):
	return list(map(lambda x: df(x), m))
res = jit(g)(m)
elapsed_time = (time.time() - start)
print(elapsed_time)
#56.96 cpu time
```

If there is any way to further enhance the performance, that should be perfect.

**Comment by jakevdp** [comment]
Note that JAX executes asynchronously, so for microbenchmarks you should call `.block_until_ready()` on the result. See https://jax.readthedocs.io/en/latest/async_dispatch.html?highlight=block_until_ready#asynchronous-dispatch

Your benchmarks are also including the jit compilation time, so keep in mind that subsequent runs of the function should be faster.

**Comment by yangzehao** [comment]
Hi @jakevdp and @mattjj, I have another two questions about the application of jax. It involves the combination of jax and scipy, and the code is shown below:
#### Question 1. The root and integration of a simple function using jax and scipy:
```python
from scipy.optimize import root
from scipy.integrate import quad
from numpy import *
import jax.numpy as jnp

def diff(fun, order=1):
	f = fun
	for i in range(order):
		f = grad(f)
	return vmap(f)

f = lambda x: jnp.sin(x) # jnp function
df = diff(f) # The derivative of f using jax
fun = lambda x: log(x) - array(df(x)) # log(x) is a numpy function and array(df(x)) is used to transform jax into numpy function
print(root(fun,array([1.0]) # The root function works
print(quad(fun,array([1.0]),array([2.0]))) # The integration function does not work (error)
```

#### Question 2. Convert the numpy function to jax function:
Right now, I know that if I want to have a jax function such as sin(x), I need to use code: lambda x: jnp.sin(x). If I want to have a numpy function such as sin(x), I need to use code: lambda x: np.sin(x). If I have the code below, is there any way to transform numpy function to jax function? (jnp is jax.numpy and np is numpy)

```python
"""
It should be noted that the *transform(f)* below is a way to convert the numpy function to jax function. It may not exist at all. 
"""
import numpy as np
import jax.numpy as jnp

f = np.sin(x) * np.tan(x) + x**2
g = transform(f) # g = jnp.sin(x) *jnp.tan(x) +x**2
```

Any suggestion is appreciated. Thanks.

**Comment by jakevdp** [comment]
For Question 1, the reason `quad` fails is that it calls the function with a scalar argument. You can get the same error this way:
```
print(fun(1.0))
```

For Question 2, no, there is no builtin way to take a numpy function and automatically convert it to a JAX function, but this idea is explored a bit in https://github.com/google/jax/issues/2774.
