### ISSUE TITLE
Anything using cuSolver fails jax version 0.2.5, jaxlib version 0.1.56 CUDA 10.1

### ISSUE THREAD

**Issue by vkramanuj** [google/jax#4674]
I'm running into a bug which is preventing me from using the GPU for anything which relies on cuSolver. In particular, the following minimal example produces the error.

```
>> import jax.numpy as jnp
>> A = jnp.array([[0, 1], [1, 1], [1, 1], [2, 1]])
>> q, r = jnp.linalg.qr(A)
```

or 

```
>> import jax.numpy as jnp
>> import jax.scipy as jsp
>> A = A = jnp.array([[9, 3, 1, 5], [3, 7, 5, 1], [1, 5, 9, 2], [5, 1, 2, 6]])
>> c, low = jsp.linalg.cho_factor(A)
```

The error in question is `RuntimeError: cuSolver has not been initialized`

I have checked that `libcusolver.so` is in `/usr/local/cuda/lib64` and the LD library path is pointing to this file.

Relevant software versions:
tensorflow-gpu 2.3.1
jax 0.2.5
jaxlib 0.1.56+101
CUDA driver 418.87.00

Any help would be greatly appreciated! This is a very blocking bug for me.

**Comment by mattjj** [comment]
@hawkinsp or @skye does this look familiar to you?

**Comment by jakevdp** [comment]
Possibly related to #4677?

**Comment by skye** [comment]
I'm not able to repro this with jax 0.2.4 and jaxlib 0.1.56+cuda101. @vkramanuj are you sure about the versions? jax 0.2.5 hasn't been released yet, do you mean you're running from github HEAD?

Can you also set the env var `TF_CPP_MIN_LOG_LEVEL=0`, rerun the failing commands, and share the full output? Maybe we can find some more clues.

**Comment by vkramanuj** [comment]
My apologies, I meant jax 0.2.4. Let me reinstall and try again.

**Comment by hawkinsp** [comment]
Closing because there was no response. Please reopen if this is still a problem!

**Comment by thanhnguyentang** [comment]
hi @vkramanuj, did you resolve this problem? Could you please share how you resolved it? I run into the same problem and could not find any other discussion rather than this thread.

**Comment by thanhnguyentang** [comment]
What I have observed in my case is the cuSolver runtime error shows up for the first run, but if I simply ignore it and rerun that code, it will proceed without the error.

**Comment by shanshanhao** [comment]
has it been solved?

**Comment by hawkinsp** [comment]
My suspicion is that this may be related to JAX grabbing too much GPU memory.
https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html

Try `XLA_PYTHON_CLIENT_MEM_FRACTION=.8`. Does it help?

What GPU do you have and how much GPU RAM does it have?
