### ISSUE TITLE
jax.experimental.stax: unifying the interface for all layers?

### ISSUE THREAD

**Issue by epignatelli** [google/jax#4679]
Hi guys,

I have been experimenting with stax for the last month, and I found it of striking simplicity and efficacy.
Thank you for that!

In defining new layers, and combining them with native stax layers (e.g. a new, user-defined `ResidualBlock` and a `GeneralConv`), I found it useful to have the same interface to access the `init` function and the `apply` function. I followed the same pattern you used for the `Optimiser`s defined in `jax.experimental.optimizers` using a `class Module(NamedTuple)` schema and a `@module(layer_maker)` decorator:
https://github.com/google/jax/blob/20ee41501372a142c20eeee9413df07f5a5e0880/jax/experimental/optimizers.py#L131-L205

Would a `Module` schema be useful for layers as it is for optimisers?
Here's a gist to explain what I mean?

https://gist.github.com/epignatelli/42662667f7be1ea0daa3e34a375f027a
     
    
To be clear, this is just syntactic sugar and nothing else. Accessing the `init` and the `apply` functions will not break existing code: `dense[0] == dense.init`

**Comment by hawkinsp** [comment]
We've decided to keep `stax` as an example and a source of inspiration, but not to try to evolve it further. For real-world use, we recommend one of the great neural network libraries built on top of JAX, such as Flax or Haiku.
