### ISSUE TITLE
Accept `dtype=complex` in `jax.random.uniform` and similar

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#4680]
Hi, 
over at [netket](https://github.com/netket/netket) we now rely heavily on jax to define wavefunctions and mixed density-matrices that describe quantum states.

However, we very often (but not always) deal with networks that are complex. In quantum physics this is quite standard by now (but also in _standard_ machine learning some people are finding interesting results thanks to complex numbers). Moreover, other than their omni-presence in quantum-mechanics, in general scientific applications complex number are often used to model periodic processes.

I'd love to be able to provide to some initialisers the `dtype=complex64` kwarg, and get out random complex numbers and initialise layers (Dense, for example, or Flax networks) with complex numbers.

Essentially, it all boils down to `jax.random.uniform` and `jax.random.normal` not accepting `dtype=complexXX` kwargs.

As you are not following ad-litteram the numpy api in this, I think there is the space to do better!

An example for that functionality is Julia, which is capable of generating complex random numbers...
In Julia `rand(ComplexF64)` generates uniformly-distributed random numbers in the box going from `[-1-1j]` to `[1+1j]` and `randn(ComplexF64)` draws values from the circularly symmetric complex normal distribution of variance 1 (corresponding to real and imaginary part having independent normal distribution with mean zero and variance 1/2) ([see source](https://github.com/JuliaLang/julia/blob/54d8d5b511193b060a3cd070f532b5d4ac025145/stdlib/Random/src/normal.jl#L71)).

Would you consider implementing such a feature or merging a PR adding this functionality?

I believe this would simplify notably working with complex-valued neural-networks, grant out of the box such support to flax with no additional work, and not have any drawback.

cc @gcarleo

**Comment by PhilipVinc** [comment]
bump...

**Comment by jakevdp** [comment]
I'm going to close this; as discussed in https://github.com/google/jax/pull/4805#pullrequestreview-530120374 and related discussion, the meaning of complex random numbers for distributions other than normal is somewhat ambiguous.
