### ISSUE TITLE
Fast custom division by 0

### ISSUE THREAD

**Issue by juliuskunze** [google/jax#4689]
Is there an efficient GPU (i. e. XLA one-op) implementation of floating-point division available in JAX where division by `0` returns `0`, instead of ~raising an error~ `inf`? In my use case, the divisor is guaranteed to be non-negative, and only `0` if the dividend is `0`. Two somewhat unsatisfying implementations I considered are
- `c / jnp.where(d, d, 1)`, which is implemented with a `broadcast_in_dim` and `select` lax primitive, and
- `c / (d + np.finfo(d.dtype).tiny)`, which has a slight semantic difference and requires more bit operations than necessary.

I was hoping for something that is faster and simpler than both of these.

**Comment by jakevdp** [comment]
Have you tried benchmarking these? Once compiled to XLA, the `where` based solution shows comparable execution time compared to the straightforward approach:
```python
import numpy as np
import jax.numpy as jnp
from jax import make_jaxpr, jit

@jit
def f1(x, y):
  return x / y

@jit
def f2(x, y):
  return jnp.where(y != 0, x / y, 0)

x = jnp.array(np.random.randint(0, 10, (1000, 1000))).astype(jnp.float32)
y = jnp.array(np.random.randint(0, 10, (1000, 1000))).astype(jnp.float32)  

# trigger compilations...
f1(x, y) 
f2(x, y)

%timeit f1(x, y).block_until_ready()
# 1000 loops, best of 3: 1.03 ms per loop
%timeit f2(x, y).block_until_ready()
# 1000 loops, best of 3: 1.06 ms per loop
```

**Comment by jekbradbury** [comment]
For GPU, you could look at the PTX instruction set and see if there's an instruction or instruction sequence that you'd like XLA to emit here?

**Comment by JuliusKunze** [comment]
@jakevdp I hadn't yet, thanks for doing this! How would you explain this behavior, i. e. is branching optimized out during compilation or just dirt-cheap? Are you certain that overhead (i. e. communication to host or similar) doesn't dominate cost?

@jekbradbury Thanks for the pointer! I found the [spec of the PTX division op](https://www.nvidia.com/content/CUDA-ptx_isa_1.4.pdf#page=73) (to which there seems to be no alternative division op), and it just returns `inf` for division by `0`. Also made me realize that it doesn't even cause a warning in JAX/XLA by default, unlike NumPy.

**Comment by hawkinsp** [comment]
I'm pretty sure Jake's suggestion is about as good as we are going to do. Let us know if it isn't fast enough!
