### ISSUE TITLE
jax.random does not respect its dtype argument if `jax_enable_x64` is not set

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#470]
Despite that I have specified `dtype=np.float64` or `dtype=onp.float64`, I always get 32-bit array.
```
x = random.uniform(random.PRNGKey(0), (1000,), dtype="float64")
x.dtype  # return float32
```

**Comment by hawkinsp** [comment]
You need to set the `jax_enable_x64` flag to true:

```
In [1]: from jax.config import config; config.update("jax_enable_x64", True)

In [2]: from jax import numpy as np, random

In [3]: x = random.uniform(random.PRNGKey(0), (1000,), dtype=np.float64)
   ...: x.dtype
/Users/phawkins/p/jax/jax/lib/xla_bridge.py:167: UserWarning: No GPU found, falling back to CPU.
  warnings.warn('No GPU found, falling back to CPU.')
Out[3]: dtype('float64')
```

We squash types to 32 btits by default because numpy has a bad habit of aggressively promoting everything to doubles. We probably need to document this better (and perhaps warn more loudly).

**Comment by Bharat123rox** [comment]
Probably documented in #656?

**Comment by fehiepsi** [comment]
Opps... looking like I should close this issue. Somehow I missed notifications.
