### ISSUE TITLE
How do I save an optimizer state of trained model? 

### ISSUE THREAD

**Issue by egorssed** [google/jax#4701]
I am playing with the mnist_vae example and can't figure out how to properly save/load weights of the trained model.

```
enc_init_rng, dec_init_rng = random.split(random.PRNGKey(2))
_, init_encoder_params = encoder_init(enc_init_rng, (batch_size, 28 * 28))
_, init_decoder_params = decoder_init(dec_init_rng, (batch_size, 10))
init_params = init_encoder_params, init_decoder_params

opt_init, opt_update, get_params = optimizers.momentum(step_size, mass=0.9)
opt_state = opt_init(init_params)
```

after that, I train the model using opt_update and want to save it. However, I haven't found any function to save the optimizer state to the disk.

I tried to save parameters and initialize opt_state with them, but not all the information conserves, and the result opt_state_1 is not the original opt_state.

```
weights=get_params(opt_state)  
jnp.save(file, weights)  
weights = jnp.load(file,allow_pickle=True)  
opt_state_1 = opt_init(init_params)
```

How do I properly save the model I trained?

**Comment by CheeGY** [comment]
Hi, did you manage to get a solution for this? I'm also encountering a similar issue and would appreciate some help on this.

**Comment by egorssed** [comment]
> Hi, did you manage to get a solution for this? I'm also encountering a similar issue and would appreciate some help on this.

Actually no. I train my networks using TF and then load the trained weights in JAX. If you need a reference you can find JAX realisation of this [VAE](https://github.com/egorssed/Galaxy_modelling_VAE/blob/main/Modules/Variational_autoencoder.py) in this [folder](https://github.com/egorssed/Galaxy_modelling_VAE/tree/main/VAE%20on%20Jax)

**Comment by CheeGY** [comment]
I ended up following the instructions listed here and managed to get something that looks correct: 
https://stackoverflow.com/questions/64550792/how-do-i-save-an-optimizer-state-of-jax-trained-model

**Comment by gnecula** [comment]
Have you considered using the Flax or Haiku libraries for writing models. You will likely find more examples for how to do things with neural networks in those libraries support channels.

**Comment by jakevdp** [comment]
I'm going to close this issue – I think referring to Flax or Haiku for this sort of problem is probably the best solution.

If there are further questions along these lines, please feel free to open a [new discussion](https://github.com/google/jax/discussions/new) about the specific issue you're having. Thanks!
