### ISSUE TITLE
jax.random.bernoulli has surprising broadcasting semantics

### ISSUE THREAD

**Issue by fehiepsi** [google/jax#471]
For example, `jax.lax.broadcast(np.arange(2.), (3, 2)).shape` will return an array with shape `(3, 2, 2)` instead of `(3, 2)`.

**Comment by hawkinsp** [comment]
Thanks for the issue report! That's actually what it's supposed to do. It follows the semantics of the XLA operator: https://jax.readthedocs.io/en/latest/jax.lax.html#jax.lax.broadcast

Note that the `lax` library isn't supposed to necessarily match `numpy`; that's the job of `jax.numpy`. Any primitives in the `numpy` library should match numpy semantics as closely as we can. The `lax` primitives may or may not.

**Comment by fehiepsi** [comment]
Agree! Indeed, I got this problem when using `lax.random.bernoulli`. Do you think that `lax.random.bernoulli` has a right behaviour with shape parameter? It seems to me that [this line](https://github.com/google/jax/blob/master/jax/random.py#L382) will append dimension instead of broadcasting.

**Comment by hawkinsp** [comment]
Actually, I think I'd agree that's a bug.

The `random` module doesn't have to follow `numpy`, but I agree that its notion of broadcast probably *should* be numpy's notion here. If you wanted to send a PR changing that line to, say, `np.broadcast_to`, it would seem reasonable to me.

**Comment by fehiepsi** [comment]
Sure, I'll do that. :)

**Comment by mattjj** [comment]
Closed by #472 I believe!
