### ISSUE TITLE
Inconsistent type promotion between nupmy and jax.numpy

### ISSUE THREAD

**Issue by tberghammer** [google/jax#4718]
```
In [18]: (np.arange(2, dtype=jnp.bfloat16) + 1.0).dtype
Out[18]: dtype('float32')
In [19]: (jnp.arange(2, dtype=jnp.bfloat16) + 1.0).dtype
Out[19]: dtype(bfloat16)
```

The above two single line example only differs on which version of numpy it uses (numpy or jax.numpy) but they result in a different output dtype. It would be great if we can get the two to agree.

**Comment by tberghammer** [comment]
Is there any way to force one or the other promotion rules?

Lets, say I have the following function:
```
def fun(a, b):
  return a + b
```

And I want the return dtype to be the same independently of the fact that what combination of DeviceArray and ndarray I pass in (preferably to always use JAX type promotion even if both arguments are ndarray).

**Comment by jakevdp** [comment]
No, I'm not aware of any way to force Numpy to use different promotion rules.

**Comment by jakevdp** [comment]
Have you considered calling `jnp.asarray` on your inputs, so that they will always have the semantics of DeviceArrays?

**Comment by tberghammer** [comment]
I certainly don't want to monkey patch numpy but `jnp.asarray` should do the trick.  Thank you.
