### ISSUE TITLE
Performance difference between @jit and jit()

### ISSUE THREAD

**Issue by fabiannagel** [google/jax#4729]
I've been playing around with JAX and noticed the following behavior: A function jitted by using the corresponding decorator seems to be much faster in compilation time than using the `jit()` function. Is this intended and does it mean to always prefer the "decorator way"?

```
import jax.numpy as jnp
from jax import grad, jit

def relu_default(x):
  return jnp.maximum(0, x)

@jit
def relu_decorator(x):
  return jnp.maximum(0, x)


# jit the function without any decorator and trigger its first compilation.
relu_jit = jit(relu_default)
%time relu_jit(2.0).block_until_ready()       # around 11 ms

# do the same for the function with the @jit decorator.
%time relu_decorator(2.0).block_until_ready() # around 6 ms

# why is the decorator version faster?

# after the initial complilation, the speed discrepancy seems to vanish.
%timeit relu_jit(2.0).block_until_ready()         # 320 µs per loop
%timeit relu_decorator(2.0).block_until_ready()   # 319 µs per loop
```

Hope I didn't miss any of the beginner pitfalls here. In any case, I did check the documentation.

**Comment by jakevdp** [comment]
There is no difference in calling jit via a decorator or via a function. So why the different timings?

If you try this again, but first run
```python
jit(jnp.maximum)(0, 2.0)
```
you'll find that the compilation times are much more similar.

Why? The first time `jnp.maximum` is encountered in a jit context, it is traced and compiled, and this takes some time. In your version, the first statement does the work to jit-compile `jnp.maximum` and the second statement re-uses this cached result.

**Comment by mattjj** [comment]
I think perhaps the surprise here is that these two functions share the same cache:

```python
relu_jit1 = jit(relu_default)
relu_jit2 = jit(relu_default)
```

The `jit` compilation cache is a module-level dict keyed on the callable you give it (i.e. keyed on `relu_default` in this case). (It holds a weak reference to the callable so that if all other references are dropped then the corresponding cache entries are cleared.) That lets you write things like `jit(f)(x, y, z)` at a call-site and you can still get compilation caching.

**Comment by fabiannagel** [comment]
Right, that makes sense. Thanks for the clarification!
