### ISSUE TITLE
Negative index in jax.numpy.take

### ISSUE THREAD

**Issue by mglisse** [google/jax#4795]
```python
import numpy as onp
import jax.numpy as jnp

print(onp.take(onp.arange(10), -2))
print(jnp.take(jnp.arange(10), -2))
print(jnp.arange(10)[-2])
```
prints
> 8
> 0
> 8

I don't know if that's related to #278. It appears that the index gets clamped to [0, size-1], when using `take`, but not with regular indexing.

**Comment by jakevdp** [comment]
Thanks for the report! I'm going to mark as a bug; JAX should support negative indices in the default mode.

**Comment by gnecula** [comment]
As discussed in #278 it is hard to replicate the numpy behavior. But it would be possible to at least make sure that the result in the 3rd example above is also `0`.

**Comment by mglisse** [comment]
#278 explains why giving an error would be hard. But it doesn't seem to explain why clipping the index is easier than wrapping?

**Comment by gnecula** [comment]
Clipping the index is what is implemented by the XLA compiler, which JAX uses.

**Comment by LuiGiovanni** [comment]
Hello! Is this issue being worked on? I would love to contribute. This is my first issue on this project.

**Comment by knshkp** [comment]
Hello! Is this issue being worked on or not? I would like to contribute to this issue

**Comment by hevrard** [comment]
I just tried the snippet in the first comment with jax 44b1791b7aed840073 on a laptop (no GPU/TPU backend), and I get a consistent behavior:

```
$ cat test.py 
import numpy as onp
import jax.numpy as jnp

print(onp.take(onp.arange(10), -2))
print(jnp.take(jnp.arange(10), -2))
print(jnp.arange(10)[-2])

$ python test.py 
8
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
8
8
```

Does this issue requires a GPU backend to manifest? Or maybe it is fixed already?
