### ISSUE TITLE
_min = builtins.max ?

### ISSUE THREAD

**Issue by lumip** [google/jax#4797]
There is a very suspicious assignment `_min = builtins.max` in `lax.py`. Is this a potential bug or is there actually a reason for this?

https://github.com/google/jax/blob/5c9204a4613b5a92dc6c60c13579d783bab4976f/jax/_src/lax/lax.py#L58

**Comment by hawkinsp** [comment]
Oops. Yes, that's a copy-and-paste bug. Fortunately that particular definition is used as part of a shape check in one function only.
