### ISSUE TITLE
jax.numpy.minimum returning traced value even if all inputs are concrete

### ISSUE THREAD

**Issue by lumip** [google/jax#4798]
This presents a problem when using it to 'filter' shape indices and wasn't the case in earlier versions. Consider the following example:
```
import jax.numpy as jnp
import jax
from functools import partial

@partial(jax.jit, static_argnums=(0,))
def foo(n, x):
    n_aval = jnp.shape(x)[0]
    n_actual = jnp.minimum(n_aval, n)
    print(type(n), type(n_aval), type(n_actual))
    return jnp.arange(n_actual)

n = 5
x = jnp.arange(10)
foo(n,x)
```

With the latest jax version (0.2.5), this crashes because `n_actual` is a traced value despite `n_aval` and `n` being concrete integers (as verified by the print output: `<class 'int'> <class 'int'> <class 'jax.interpreters.partial_eval.DynamicJaxprTracer'>`). This in turn causes the above snippet to crash in `jnp.arange`, which expects a concrete value.

In an earlier version of jax (0.1.73), this does not happen, i.e., `jnp.minimum` returns a concrete value (print output: `<class 'int'> <class 'int'> <class 'jax.interpreters.xla.DeviceArray'>`).

Is this now expected behavior, and if so, how can I now achieve what the above snippet is meant to achieve?

**Comment by hawkinsp** [comment]
Yes, this is expected. Please read: https://github.com/google/jax/blob/master/design_notes/omnistaging.md

specifically https://github.com/google/jax/blob/master/design_notes/omnistaging.md#using-jaxnumpy-for-shape-computations

and in this case, try using `np.minimum` instead of `jnp.minimum`.

Does that make sense?

**Comment by hawkinsp** [comment]
Closing since I'm pretty sure this will resolve your problem; feel free to reopen if you need!
