### ISSUE TITLE
jit fails for large uint64 inputs

### ISSUE THREAD

**Issue by jakevdp** [google/jax#4809]
Repro:
```python
import jax.numpy as jnp
from jax import jit, random, config
config.update('jax_enable_x64', True)

x = jnp.iinfo(jnp.uint64).max

print(jnp.uint64(x))
# 18446744073709551615

print(jit(jnp.uint64)(x))
# OverflowError: Python int too large to convert to C long
```
I suspect somewhere in the JIT codepath JAX is implicitly converting Python integers to signed int.

**Comment by hawkinsp** [comment]
The stack trace with the C++ JIT is instructive:

It turns out to boil down to:
```
In [7]: np.array(np.iinfo(np.uint64).max, np.dtype(np.int_))
---------------------------------------------------------------------------
OverflowError                             Traceback (most recent call last)
<ipython-input-7-947cfe59245c> in <module>
----> 1 np.array(np.iinfo(np.uint64).max, np.dtype(np.int_))

OverflowError: Python int too large to convert to C long
```

We always choose `int_` as the type for Python scalars promoted to NumPy.

**Comment by jakevdp** [comment]
I think we could use value-dependent dtypes here, but it's not clear to me whether that would have downsides.

**Comment by jakevdp** [comment]
I'm going to close this as Working as Intended.

We definitely don't want to have value-based type semantics, and so all we can do is assume that integer inputs should be wrapped in int64, and error if they overflow.

The workaround would be to cast to `uint64` directly if that is the intended input.
