### ISSUE TITLE
SAME Code & Two Runs ==> Varied Results

### ISSUE THREAD

**Issue by ssydasheng** [google/jax#4823]
Dear Jax Developers, 

Thanks for the awesome jax package. However, during my experimenting with jax, though I have set all the random states, I found independent runs of **the same code** might output **different results** (different in terms of the last several digits). I have tried my best to slim down my code and attached them for your reference. **restart.py** is the main file, and **re_data.py** is for mnist loading.
[re_data.txt](https://github.com/google/jax/files/5505305/re_data.txt)
[restart.txt](https://github.com/google/jax/files/5505306/restart.txt)

My jobs are all run using P100. However, since I use slurm for running jobs, I cannot ensure all my runs happening  on the same cpu & gpu (I guess the device is important). I am using **cudnn-10.0-v7.6.3.30** and **cuda-10.0**. I also attached the conda **environment.yml**
[environment.txt](https://github.com/google/jax/files/5505313/environment.txt)

Thanks a lot for your help.

**Comment by ssydasheng** [comment]
Here are the results for two runs. 
[res1.txt](https://github.com/google/jax/files/5505360/res1.txt)
[res2.txt](https://github.com/google/jax/files/5505361/res2.txt)

**Comment by mattjj** [comment]
Thanks for the question!

Unfortunately, it's quite tricky to make GPU computations deterministic up to every floating point numerical detail. And the differences here are quite small:

```
$ diff res1.txt res2.txt
28c28
< TAKS 1 Epoch 0 Iter 2 | loss = 1.9029290676116943 | reg = 1.903028964996338 | prevx = 0.0 |  xb = 0.0
---
> TAKS 1 Epoch 0 Iter 2 | loss = 1.9029291868209839 | reg = 1.9030290842056274 | prevx = 0.0 |  xb = 0.0
34c34
< TAKS 1 Epoch 0 Iter 8 | loss = 1.8939218521118164 | reg = 1.8943889141082764 | prevx = 0.0 |  xb = 0.0
---
> TAKS 1 Epoch 0 Iter 8 | loss = 1.8939217329025269 | reg = 1.8943887948989868 | prevx = 0.0 |  xb = 0.0
43c43
< TAKS 1 Epoch 1 Iter 5 | loss = 1.720825433731079 | reg = 1.721971869468689 | prevx = 0.0 |  xb = 0.0
---
> TAKS 1 Epoch 1 Iter 5 | loss = 1.7208256721496582 | reg = 1.721972107887268 | prevx = 0.0 |  xb = 0.0
```

I'm not an expert in this area, but I can think of a few potential culprits, like the fact that XLA:GPU does autotuning to select cuDNN kernels (and so the exact kernel that gets selected can depend on the amount of heat near the GPU at a particular time), and nondeterministic reduction computations on GPU (due to threading).

One thing you can do is set the environment variable `XLA_FLAGS='--xla_gpu_deterministic_reductions --xla_gpu_autotune_level=0'` (before importing `jax`). That may cost some performance, but it should help rule out some causes of nondeterminism.

Can you try those and see if they help?

We're working with the XLA:GPU team to improve this over time, but I think the above summarizes the current state of control we have. @hawkinsp let me know if I missed anything!

See also google/flax#33.

**Comment by ssydasheng** [comment]
Thanks for the quick response ! 

I tried setting the variable `XLA_FLAGS='--xla_gpu_deterministic_reductions --xla_gpu_autotune_level=0'`. It indeed helps, seems that the results are fully reproducible now.

Thanks again, my concerns have been cleared. I think you can close this issue if having not more comments.

**Comment by mattjj** [comment]
Really glad to hear it helped!

I'll try to improve our docs around this.

**Comment by mattjj** [comment]
#4824 is an attempt to improve the docs here. Thanks for raising this!

**Comment by ssydasheng** [comment]
Hi, I have some followups on the determinisms. For the[ resnet example ](https://github.com/google/jax/blob/master/examples/resnet50.py), the stochasticity is more pronounced. 

Based on the example, I added the following codes for printing out some information. Then I found that even the first three iterations print out different numbers in different runs. These differences are quite noticeable to me. Probably because the bigger network enhances the stochasticity? Btw, I have set the environment variables by `os.environ["XLA_FLAGS"] = "--xla_gpu_deterministic_reductions --xla_gpu_autotune_level=0"`.

**Iter 0  1722.7124 \\\  Iter 1  1685.9337 \\\ Iter 2  1209.861**
**Iter 0  1722.7078 \\\  Iter 1  1690.5673 \\\ Iter 2  1227.6748**. 


```

  test_images = npr.RandomState(0).rand(*input_shape).astype('float32')
  test_labels = npr.RandomState(0).randint(num_classes, size=(batch_size, 1))
  print('sampled test data', test_images[0][0][0][0], test_labels[0])
  test_labels = (test_labels == jnp.arange(num_classes))

  for i in range(num_steps):
    opt_state = update(i, opt_state, next(batches))
    print('Iter %d ' % i, loss(get_params(opt_state), (test_images, test_labels)))
```

**Comment by ysngshn** [comment]
I have also tried training resnet20 for cifar10, the setting that makes the process deterministic is with `XLA_FLAGS='--xla_gpu_autotune_level=2 --xla_gpu_deterministic_reductions' TF_CUDNN_DETERMINISTIC=1`. In my case, `TF_CUDNN_DETERMINISTIC=1` is necessary. For `xla_gpu_autotune_level`, alternatively one can set it to 1 or not setting it at all and the result is still the same, but setting it to 0 as suggested in the doc make the result nondeterministic again ...

**Comment by samuela** [comment]
What is the meaning of `--xla_gpu_autotune_level=0` vs `--xla_gpu_autotune_level=1` vs `--xla_gpu_autotune_level=2`? Are there other values? Are there docs for these options?

**Comment by DT6A** [comment]
I also met the same problem. In my case adding only
```Python3
os.environ["TF_CUDNN_DETERMINISTIC"] = "1"
```
before the jax import helped while setting `XLA_FLAGS` was crashing processes.
