### ISSUE TITLE
No reference documentation for lax.Precision

### ISSUE THREAD

**Issue by nikitakit** [google/jax#4833]
The `lax.Precision` enum doesn't have any reference documentation, which I would expect to find at https://jax.readthedocs.io/en/latest/jax.lax.html.

Multiple times I've read a docstring like the one below for `lax.dot`:

```
  Args:
    precision: Optional. Either ``None``, which means the default precision for
      the backend, a ``lax.Precision`` enum value (``Precision.DEFAULT``,
      ``Precision.HIGH`` or ``Precision.HIGHEST``) or a tuple of two
      ``lax.Precision`` enums indicating precision of ``lhs``` and ``rhs``.
```

and gone to open the reference docs to remind myself what each variant actually means (as well as verify that the enum doesn't support any other values than the ones listed). But there are no reference docs for this type. The only documentation is actually the README for the Cloud TPU colab examples.

**Comment by skye** [comment]
Hi @a-ma-n ! Please feel free to create a PR if you still have time/interest. I'm unfortunately not sure the best way to add even add documentation to `Precision`, as it's a [wrapped C++ enum](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/xla_compiler.cc#L630-L633) (aliased in jax.lax [here](https://github.com/google/jax/blob/master/jax/_src/lax/lax.py#L504)). Here's the relevant Cloud TPU docs mentioned by OP: https://github.com/google/jax/tree/master/cloud_tpu_colabs#bfloat16-dtype
