### ISSUE TITLE
jax.numpy.mean over list of arrays

### ISSUE THREAD

**Issue by Baschdl** [google/jax#4837]
Taking the mean over a list of arrays (e.g. when averaging multiple gradients) doesn't work with jax.numpy:
```python
import jax.numpy
import numpy
arrays = [numpy.random.random((4,2)) for _ in range(3)]

numpy.mean(arrays, axis=0) —> works
jax.numpy.mean(arrays, axis=0) —> `TypeError: data type not understood`
```

If this is intended, maybe don't state ["If a is not an array, a conversion is attempted."](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.mean.html) like in the numpy docs which implies that both functions work the same way.

**Comment by hawkinsp** [comment]
This is intended. in a general sense that jax.numpy is intentionally more strict about only accepting arrays where classic numpy also accepts lists. I agree that we should fail more understandably.

**Comment by jakevdp** [comment]
Just a note that we recently improved this error message; in the current release, the code results in the following error:
```pytb
TypeError: mean requires ndarray or scalar arguments, got <class 'list'> at position 0.
```

**Comment by hawkinsp** [comment]
@Baschdl does that satisfy you?

**Comment by Baschdl** [comment]
@hawkinsp Yes, that's a clearer error message. There is no way to make `jax.numpy` functions like `mean` in this example easily applicable to the output of functions like `grad`, is there?

**Comment by hawkinsp** [comment]
I'd call `jnp.mean(jnp.stack(...))`.

Hope that helps! Closing since I think there's no further action needed here, but feel free to reopen if you want to continue the discussion.

**Comment by Baschdl** [comment]
@hawkinsp That's unfortunately not that easy as `gradient1, gradient2,...` in `jnp.mean(jnp.stack(gradient1, gradient2,...))` are list of arrays or even worse list of tuples of arrays. I would like to write a function which can average gradients of arbitrary functions (neural networks, linear functions etc.) but I don't see a way with jax where you don't have too write a custom loop for every function class.

**Comment by jakevdp** [comment]
if `np.mean(obj)` works, then `jnp.mean(jnp.array(obj))` will also work.

**Comment by uduse** [comment]
> But be aware that this does a round-trip to numpy to construct the arrays, so it will not be particularly efficient.

@jakevdp Do you mind elaborating this? In my `jax.jit`-ed loss function, I use something like
```python
loss = jnp.sum(jnp.array(tree.flatten(losses)))
```
If I understand it correctly, doing the following will be much more efficient?
```python
loss = jnp.sum(jnp.stack(tree.flatten(losses)))
```

**Comment by jakevdp** [comment]
That comment no longer applies in the current version of JAX. `jnp.sum(jnp.array(x))` should be fine.
