### ISSUE TITLE
jax2tf.convert: handy when used as a decorator, but can't take arguments at the moment

### ISSUE THREAD

**Issue by flederbaysian** [google/jax#4859]
jax2tf.convert can be used as a decorator at the moment:

```
@jax2tf.convert
def my_function(inputs):
  # ...
```

This is nice, but if I want to pass in any arguments, it no longer works. The following code fails with

> Invalid keyword argument with_gradients to function jax.experimental.jax2tf.convert [wrong-keyword-args]
>          Expected: (fun, *, enable_xla, in_shapes, with_gradient)
>   Actually passed: (with_gradients)"

```
@jax2tf.convert(with_gradient=False)
def my_function(inputs):
  # ...
```

To resolve that, you could introduce a method like:
```
def convert_with(fun, **kwargs):
  return functools.partial(convert, **kwargs)
```

which would allow code like:
```
@jax2tf.convert_with(with_gradient=False)
def my_function(inputs):
  # ...
```

**Comment by hawkinsp** [comment]
In JAX we tend to use the pattern:
```
from functools import partial

@partial(jax2tf.convert, with_gradient=False)
def my_function(inputs):
  # ...
```

e.g., see: https://cs.opensource.google/search?q=%22@partial%22&sq=&ss=jax%2Fjax

Some people find it awkward at first, but we have mostly grown to prefer it rather than having more "magic" decorators that do complicated argument wrangling.

What do you think?

**Comment by flederbaysian** [comment]
If that's what's available, that's what I'll use. 👍
