### ISSUE TITLE
Behler Parinello network in example Colab notebook

### ISSUE THREAD

**Issue by marcimarc1** [google/jax#4881]
While testing the behler_parinello functionality in the colab [notebook](https://colab.research.google.com/github/google/jax-md/blob/master/notebooks/neural_networks.ipynb) an error occurs
The only code that I changed is:

```
box_size = 10.862  # The size of the simulation region.
displacement, shift = space.periodic(box_size)
##starts here
species = np.zeros(positions.shape[0])  # needs to provide species, otherwise throws error in sym_fn

mlp_kwargs = {'activation': np.tanh}  # hyperparameters for MLP
sym_kwargs = {'cutoff_distance': 0.5}
neighbor_fn, init_fn, energy_fn = energy.behler_parrinello_neighbor_list(displacement,box_size, mlp_sizes=(30, 30),
                                                mlp_kwargs=mlp_kwargs, sym_kwargs=sym_kwargs, species=species)
##ends here
```

when trying to execute the cell to predict the energy, following error occurs:

_IndexError: Array boolean indices must be concrete._

I am rather confused about the error message, as I do not pass anything by index I guess, as I just changed the Neural network?

**Comment by froystig** [comment]
The colab notebook seems to be from the jax-md repository. It might be easier to try there for help? We probably need to dig into how the jax-md library function being called uses jax.

cc @sschoenholz @ekindogus from jax-md

**Comment by sschoenholz** [comment]
Hey @marcimarc1, thanks for raising this issue. It should be fixed at head now as of JAX-MD pull request [#105](https://github.com/google/jax-md/pull/105). While I was at it, I fixed the issue you were running into when `species=None` was passed into the network initialization function. Don't hesitate to let us know if this doesn't work or if you run into other trouble!

Also, I plan to update PyPi later in the week, but if you'd like me to push a new version sooner including this fix let me know.

**Comment by froystig** [comment]
Thanks @sschoenholz!

**Comment by marcimarc1** [comment]
Thank you very much for the fast fix @sschoenholz.
Next time I read twice, where I post my issue @froystig -> Thank you for your forwarding
