### ISSUE TITLE
jnp.hypot is numerically unstable

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#4882]
`sqrt(x**2 + y**2)` is not a good implementation of hypot (e.g., see Wikipedia https://en.wikipedia.org/wiki/Hypot)

**Comment by jakevdp** [comment]
For reference, here's numpy's implementation: https://github.com/numpy/numpy/blob/31ffdecf07d18ed4dbb66b171cb0f998d4b190fa/numpy/core/src/npymath/npy_math_internal.h.src#L192-L219
