### ISSUE TITLE
optimize device_put of ShardedDeviceArray

### ISSUE THREAD

**Issue by jekbradbury** [google/jax#4885]
This currently falls back to bouncing through host, which is slow and causes a synchronization.

**Comment by jekbradbury** [comment]
This is one of those cases (DeviceArray iteration #3821 is another) where there are three categories of solution:
- something that goes through the host / causes a host sync
- something that could potentially do compilation
- something that calls many small runtime operations from Python

All of these can be performance bottlenecks for different people in different contexts, but I personally think category 1 is by far the worst and we should try to avoid host syncs at almost all costs.

**Comment by hawkinsp** [comment]
I think we can declare this fixed, in the brave new world of `jax.Array`. We might still be making suboptimal choices in some cases, but we handle at least some cases of resharding directly now.
