### ISSUE TITLE
Jax slow on cuda 11.0

### ISSUE THREAD

**Issue by cgarciae** [google/jax#4889]
Hey, I updated to:
```
cuda: 11.0
cuDNN: v8.0.4
jaxlib==0.1.56+cuda110
```
Suddenly JAX is super slow. Am I getting the requirements right?

**Comment by mattjj** [comment]
Can you try jaxlib==0.1.57? (Looks like our readme isn't updated to indicate 0.1.57.)

**Comment by cgarciae** [comment]
Thanks
Don't know exactly what happened but speed is on par now, I think it was somehow the drivers.
