### ISSUE TITLE
np.cint/np.int32 type confusion

### ISSUE THREAD

**Issue by cloudhan** [google/jax#4903]
```python
import numpy as np
import jax.numpy as jnp

xs = np.array([1000000000000, 2, 3, 4])
jxs = jnp.array([1000000000000, 2, 3, 4])

print(xs)
print(jxs)
```

Outputs:
```
[1000000000000             2             3             4]
[-727379968          2          3          4]
```

**Comment by cloudhan** [comment]
OK, `export JAX_ENABLE_X64=1` solves this, but no warning is raised.

**Comment by cloudhan** [comment]
Here is another issue:
```python
import numpy as np
import jax.numpy as jnp

xs = np.array([1000000000000, 2, 3, 4])
jxs = jnp.array([1000000000000, 2, 3, 4])

for x in xs:
    print(x, x.dtype, type(x))

for x in jxs:
    print(x, x.dtype, type(x))
```

Output:
```
1000000000000 int64 <class 'numpy.int64'>
2 int64 <class 'numpy.int64'>
3 int64 <class 'numpy.int64'>
4 int64 <class 'numpy.int64'>
1000000000000 int64 <class 'numpy.longlong'>
2 int64 <class 'numpy.longlong'>
3 int64 <class 'numpy.longlong'>
4 int64 <class 'numpy.longlong'>
```

jax iterator outputs platform dependent element type 
In this case, `int64` became `numpy.longlong`.
On windows, I also observe `int32` became `cint`, but not on linux.

**Comment by hawkinsp** [comment]
I think this is an issue that other folks have hit before. There's a difference between "native" and "standard" sizes in NumPy that manifests only in Windows:
https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment
https://github.com/pybind/pybind11/issues/1806
https://github.com/pybind/pybind11/issues/1908

My guess is we need to change some of the format descriptors returned here:
https://github.com/tensorflow/tensorflow/blob/516f4a121c5c1f9bb712b774109c6ad5283d27ad/tensorflow/compiler/xla/python/types.cc#L104

to have `=` prefixes.

**Comment by cloudhan** [comment]
This is not specific to windows.
