### ISSUE TITLE
[jax2tf] Incorrect translation for jax.lax.round

### ISSUE THREAD

**Issue by tberghammer** [google/jax#4952]
```
import jax
import jax.experimental.jax2tf as jax2tf
import jax.numpy as jnp
import tensorflow as tf
tf.compat.v1.enable_eager_execution()

print("Jax:", jax.lax.round(0.5))
print("Jax2Tf:", jax2tf.convert(jax.lax.round)(0.5))
```

```
Jax: 1.0
Jax2Tf: tf.Tensor(0.0, shape=(), dtype=float32)
```

The issue is coming from the fact that jax.lax.round uses away from zero rounding based on what the corresponding XLA op is doing but then it maps to tf,round what does round towards even.

**Comment by hawkinsp** [comment]
@bchetioui Is this now fixed?

**Comment by bchetioui** [comment]
@hawkinsp I think #4959 is ready, but it has not been merged!
