### ISSUE TITLE
has_aux for forward-mode differentiation functions 

### ISSUE THREAD

**Issue by zhongwen** [google/jax#497]
Related to PR https://github.com/google/jax/pull/484

We should have corresponding `has_aux` implementation of passing side-information for the forward-mode functions like `jvp`, `jacfwd` etc.

My use case is under a scenario that forward-mode is much more efficient than the reverse-mode.

**Comment by mattjj** [comment]
Does #499 have the right API for you?

**Comment by mattjj** [comment]
Oh, just noticed you asked for it plumbed through `jacfwd` too. I can add that to #499.

**Comment by zhongwen** [comment]
Yes! That would work well! Maybe also for all other forward-mode functions (I am not sure the whole list of those though).

**Comment by mtthss** [comment]
It would indeed be very useful if `jacfwd` and `jacrev` had the `has_aux` option

**Comment by sguada** [comment]
Once `jacfwd` and `jacrev` had the has_aux option, then add it to `hessian` too.

**Comment by mtthss** [comment]
Can we bump this up?
