### ISSUE TITLE
JAX Random Docs Page is Blank

### ISSUE THREAD

**Issue by jacksonwb** [google/jax#4992]
Seems the page for Jax.random is not generating correctly...?

https://jax.readthedocs.io/en/latest/jax.random.html

**Comment by jakevdp** [comment]
Thanks for reporting. I'll take a look - I suspect it may be because jax/random.py does not have a module-level docstring.

**Comment by jakevdp** [comment]
Hmm... looks like it's due to more than just the docstring. #4964 put the random functions into a private module, so sphinx sees this and skips them in autodoc. The solution, I think, is to explicitly list all functions to be documented, as we do in `jax.numpy.rst`.
