### ISSUE TITLE
Add support for `prepend` and `append` in jax.numpy.diff

### ISSUE THREAD

**Issue by jakevdp** [google/jax#5009]
These arguments are currently not supported; see NumPy's description of the behavior here: https://numpy.org/devdocs/reference/generated/numpy.diff.html, and JAX's current implementation here: https://github.com/google/jax/blob/c9579b85584ea7439202d3eab37eb59bd9e3d0b2/jax/_src/numpy/lax_numpy.py#L1099-L1122

**Comment by soumya997** [comment]
hey, @jakevdp I want to contribute to this, but I am fairly new to JAX. If you can share what are the prerequisites for this issue then it would be very helpful. 
if I am not wrong then By this issue, you want to implement `prepend` and `append` in jax.numpy.diff which is not available currently and this feature is similar to `prepend` and `append` of numpy.

**Comment by jakevdp** [comment]
Hi @soumya997 – there is already an effort underway at the PR linked above (#5035)

**Comment by soumya997** [comment]
Is there any other issue where I can contribute? @jakevdp
