### ISSUE TITLE
Add support for more padding modes in jax.numpy.pad

### ISSUE THREAD

**Issue by jakevdp** [google/jax#5010]
Currently only a few of the available modes are implemented. See https://numpy.org/devdocs/reference/generated/numpy.pad.html#numpy.pad for details, and the current JAX implementation here: https://github.com/google/jax/blob/c9579b85584ea7439202d3eab37eb59bd9e3d0b2/jax/_src/numpy/lax_numpy.py#L2398-L2404

**Comment by minoring** [comment]
Do we have to implement ‘empty’ and 'function' mode? 
Those are new in numpy version 1.17.

**Comment by jakevdp** [comment]
I think it would make sense to implement these (with tests marked to skip in older numpy versions).

Note that it's not possible to create uninitialized data in JAX, but we could fill with zeros in this case, similar to how `jnp.empty` is implemented.

**Comment by jakevdp** [comment]
Looking at it, the function version would have to be implemented differently from numpy, because numpy's version has the function to modify the array in-place, while JAX arrays are immutable.

**Comment by minoring** [comment]
I see. Let me implement those :)
Thanks for the tips!

**Comment by minoring** [comment]
By the way, unsupported keyword argumenets should raise an error.
I am not sure this is another issue, but I will handle it after implementing 'empty' and 'function' mode.
```python
>>> import numpy as np
>>> a = [1, 2, 3]
>>> np.pad(a, mode='maximum', pad_width=2, reflect_type='odd')
ValueError: unsupported keyword arguments for mode 'maximum': {'reflect_type'}

>>> import jax.numpy as jnp
>>> a = [1, 2, 3]
>>> jnp.pad(a, mode='maximum', pad_width=2, reflect_type='odd')
DeviceArray([3, 3, 1, 2, 3, 3, 3], dtype=int32)
```

**Comment by minoring** [comment]
I believe `jax.numpy.pad` support every padding modes now :)

**Comment by jakevdp** [comment]
Thanks for the work on this!
