### ISSUE TITLE
Masking + Jit to deal with dynamic/variable shape arrays?

### ISSUE THREAD

**Issue by LysSanzMoreta** [google/jax#5013]
Hi!

I have been struggling with the issue that my array cannot change the shapes of my array with every iteration if I use the JIT compiler. I tried to follow #2521 , but everything seems in the air.

The goal is to compute the following, where jnp.sum(block_lengths) result/value **changes** with every iteration( m and l are static/concrete !!)

`u = random.randint(rng_key, (jnp.sum(block_lengths), ), 0, m)`

I get the following error:

```
  File "/home/.../numpyro/numpyro/contrib/hmcecs.py", line 128, in _sample_u_poisson
    u = random.randint(sub_key, (jnp.sum(block_lengths), m), 0, m)
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/random.py", line 442, in randint
    shape = abstract_arrays.canonicalize_shape(shape)
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/core.py", line 1130, in canonicalize_shape
    raise TypeError(msg.format(shape))
TypeError: Shapes must be 1D sequences of concrete values of integer type, got (Traced<ShapedArray(int32[]):JaxprTrace(level=-1/1)>, 22).
If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions.
```

I have been wondering around several issues and possible solutions, including **static arguments** ,  **masking**, but none have worked and I end up back in the same error.

_Static arguments approach:_

```
b = jnp.sum(block_lengths)
u_random = jit(random.randint, static_argnums=(0,1, 2,3))
u = u_random((sub_key, (b,m), 0, m))

```

**Error** Static args:

```
  File "/home/.../numpyro/numpyro/contrib/hmcecs.py", line 138, in _sample_u_poisson
    u = u_random(sub_key, (b, m), 0, m)
  File "/home/../anaconda3/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 133, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/api.py", line 207, in f_jitted
    f, dyn_args = argnums_partial_except(f, static_argnums, args)
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/api_util.py", line 90, in argnums_partial_except
    "Non-hashable static arguments are not supported, as this can lead "
ValueError: Non-hashable static arguments are not supported, as this can lead to unexpected cache-misses. Static argument (index 0) of type <class 'numpy.ndarray'> for function randint is non-hashable.

```
_Masking approach A:_

```
   @partial(mask, in_shapes=['(_,)'], out_shape='(_, _)')
   def u_rand(block_lenghts):
        b = jnp.sum(block_lengths)
        return random.randint(sub_key, (b,m), 0, m)
   u = u_rand([block_lengths],{} )

```
**Error** masking A:: Back to same original error

```
 File "/home/.../numpyro/numpyro/contrib/hmcecs.py", line 134, in _sample_u_poisson
    u = u_rand([block_lengths],{})#dict(b=jnp.sum(block_lengths).astype(int),m=m,l=l))
  File "/home/../anaconda3/lib/python3.7/site-packages/jax/api.py", line 1592, in wrapped_fun
    flat_fun, logical_env, padded_env, args_flat, in_shapes)
  File "/home/../anaconda3/lib/python3.7/site-packages/jax/interpreters/masking.py", line 85, in mask_fun
    out_vals = fun.call_wrapped(*(logical_env_vals + in_vals))
  File "/home/lys/anaconda3/lib/python3.7/site-packages/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "/home/.../numpyro/numpyro/contrib/hmcecs.py", line 133, in u_rand
    return random.randint(sub_key, (b,m), 0, m)
  File "/home/lys/anaconda3/lib/python3.7/site-packages/jax/random.py", line 442, in randint
    shape = abstract_arrays.canonicalize_shape(shape)
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/core.py", line 1130, in canonicalize_shape
    raise TypeError(msg.format(shape))
TypeError: Shapes must be 1D sequences of concrete values of integer type, got (Traced<ShapedArray(int32[]):JaxprTrace(level=-1/1)>, 22).
If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions.
```

_Masking approach B:_
```
  @partial(mask, in_shapes=['(l,)'], out_shape='(b, m)')
   def u_rand(block_lenghts):
        b = jnp.sum(block_lengths)
        return random.randint(sub_key, (b,m), 0, m)
   u = u_rand([block_lengths],dict(b=jnp.sum(block_lengths).astype(int),m=m,l=l))
```

**Error** masking B: The block lenghts is a ShapeArray, so I cannot reach it's concrete value

```
  File "/home/.../numpyro/numpyro/contrib/hmcecs.py", line 764, in _init_state
    self._u = _sample_u_poisson(rng_key, self.m, self._l)
  File "/home/.../numpyro/numpyro/contrib/hmcecs.py", line 134, in _sample_u_poisson
    u = u_rand([block_lengths],dict(b=jnp.sum(block_lengths).astype(int),m=m,l=l))
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/api.py", line 1602, in wrapped_fun
    masking.check_shapes(out_specs, out_spec_tree, list(out_shapes), out_tree)
  File "/home/.../anaconda3/lib/python3.7/site-packages/jax/interpreters/masking.py", line 489, in check_shapes
    raise ShapeError(f"{message_prefix} shapes should be {specs} but are {shapes}.")
jax.interpreters.masking.ShapeError: Output shapes should be ShapeSpec(b, m) but are (58, 22).
```

I am not sure whether what I am trying to accomplish is doable at the moment. 

Thanks so much for your attention and help!

**Comment by LysSanzMoreta** [comment]
Hi! Does anyone have any insights on this issue? Thanks!!

**Comment by mattjj** [comment]
Hey, sorry for the long delay.

If you're still interested in this, can you provide a complete runnable example of what you'd like to accomplish? I'm thinking of something that runs without `jit`, but that you'd ideally like to stage out with `jit` and have it keep working.

(If you're not still interested in pursuing this, let's close the issue!)

**Comment by OlaRonning** [comment]
Hi @mattjj,

Awesome you'll take a look at it, there is a simple runnable example here #5100.

**Comment by LysSanzMoreta** [comment]
Thanks @mattjj ! Yes, now @OlaRonning is mainly taking care of the code but we are both interested :D

**Comment by mattjj** [comment]
That's a great example!

However, it doesn't fit into what `mask` can support: the `mask` transformation (which is really just a prototype) wasn't designed to handle arrays with shapes that depend on values computed at runtime, like random samples. Instead, it only handles shapes of intermediates that have a polynomial dependence on arguments to the function being `mask`-transformed (in particular on the shapes of other arguments).

This is the sort of thing we'd like to be able to support in the future, but `mask` isn't enough. For now the only option is not to `jit` this code. You can still apply `jit` to other functions and subroutines, but not the `jax.random.randint(sub_key, (rand_shape.sum(), 3), 0, n)` part.

While we're actively working on improvements that will help here, I think it's best to close this issue for now (since otherwise we might have a proliferation of such issues waiting for dynamic shape support in `jit`). Perhaps check back in a couple months for progress!
