### ISSUE TITLE
Help understanding jit tracing in small example

### ISSUE THREAD

**Issue by DanPuzzuoli** [google/jax#5017]
Hi,

I apologize if the explanation for this is already out there - there are a lot of issues and documentation related to this, but I'm having trouble understanding what's going on due to very limited knowledge of `xla` and jax tracing.

What I'd like to understand comes from the following stripped down code snippet:

```python
import jax.numpy as jnp
from jax.lax import scan
import numpy as np

def jaxfixedsolve(rhs, t_span, y0, max_dt):

    delta_t = t_span[1] - t_span[0]
    steps = jnp.array(delta_t // max_dt).astype(int)
    h = delta_t / steps

    def scan_func(carry, step):
        eval_time = t_span[0] + (h * step)
        return (carry + rhs(eval_time, carry)*h, None)

    yf = scan(scan_func, y0, jnp.arange(steps))[0]
    return yf

def sim_function(coeff):

    def rhs(t, y):
        return coeff * y
    
    return jaxfixedsolve(rhs, t_span=[0, 0.5], y0=jnp.array(1., dtype=float), max_dt = 0.1)
```

basically, the point of the above is: `jaxfixedsolve` is a rudimentary fixed step ODE solver, and `sim_function` is a function that I'd like to apply `jax` transformations to. (Note that the above code works without `jit`-ing.)  If I `jit` `sim_function`, I get an error containing:

```
ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.
```

Upon reading up on other issues/on the jax documentation, this makes sense to me as the value of the arguments `t_span` and `max_dt` affect the variable `steps`, which affects the shape of the output of `scan`, and due to this indeterminate shape of the output of `scan` `jit` won't work on this function. However, if I modify the line defining `steps` to:

```
    steps = np.array(delta_t // max_dt).astype(int)
```

i.e. `steps` is wrapped in a standard numpy array (as opposed to `jax` array) the problem disappears: I am able to `jit` and differentiate `sim_function` as desired.

I know this must have something to do with abstract vs concrete vs static types, but I haven't had much luck figuring it out. Also, any recommendations on doing the above "correctly" would be much appreciated!

Thank you!

**Comment by jakevdp** [comment]
The issue here is in this statement:
```python
jnp.arange(steps)
```
In jitted code, the length of arrays must be statically determined. But here, `steps` is a dynamic value, and so there's no way to know at trace-time what the length of `jnp.arange(steps)` will be. For this reason, the compilation fails.

Is there any way in your approach that you could make the number of steps a static value?

**Comment by DanPuzzuoli** [comment]
Yes it would be fine if the number of steps is a static value. Does putting into a standard numpy array effectively achieve this?

**Comment by jakevdp** [comment]
Yes, I think the only change you would need in that case is to change
```python
steps = jnp.array(delta_t // max_dt).astype(int)
```
to
```python
steps = np.array(delta_t // max_dt).astype(int)
```
That is, use numpy to compute trace-time static values.

**Comment by DanPuzzuoli** [comment]
Is this the "correct" way to do this in `jax`? I.e. is there some way to decorate this function so that, if it's involved in a bigger computation that gets `jit`ed, it knows to treat `delta_t` and `max_dt` as static? I know that if I want to do this when jitting a function directly I can use `static_argnums`, but in this case I want to use it as a subroutine of a bigger computation I want to compile.

**Comment by jakevdp** [comment]
Yes, you can consider that the correct way to do this. In short, any computation done via `jax.numpy` or related jax operations will be staged for compilation; anything that you want to be a trace-time constant should be computed by other means (e.g. normal numpy routines). There currently isn't any means to specify that jax computations should happen statically at trace-time.

**Comment by DanPuzzuoli** [comment]
Awesome, thank you so much!
