### ISSUE TITLE
revise vmap docs to specify `in_axes=None` on its own is not valid

### ISSUE THREAD

**Issue by mattjj** [google/jax#5021]
The `vmap` docstring implies that this may be valid:

```python
vmap(lambda x: x, in_axes=None, out_axes=None)(3.14)
```

but actually it's an error:

```
ValueError: vmap must have at least one non-None value in in_axes
```

We could make `in_axes=None` work when `out_axes=None` as well, though it'd be completely trivial. But we can't make `in_axes=None` work with `out_axes=0` (or any other non-`None` value) unless we also add a way of specifying the mapped axis size, separately from reading the size off the input arguments.

In any case, probably best to update the docs to reflect the current behavior.

**Comment by 8bitmp3** [comment]
@mattjj @jakevdp @skye Assuming this is still an issue, I can create a PR with an extra paragraph and a code snippet at the bottom of the `jax.vmap` (and `pmap`?) doc string (https://jax.readthedocs.io/en/latest/_autosummary/jax.vmap.html).

**Comment by jakevdp** [comment]
I think this issue is stale because `vmap` now accepts an `axis_size` argument, which is one of the possibilities @mattjj referred to above. So, for example this executes without error:
```python
vmap(lambda x: x, in_axes=None, out_axes=None, axis_size=0)(3.14) 
```

**Comment by 8bitmp3** [comment]
excellent, thanks @jakevdp
