### ISSUE TITLE
jax.numpy.polyval coeffitients format

### ISSUE THREAD

**Issue by PgLoLo** [google/jax#5040]
I've just noticed, that polynomial coefficients in jax poly* functions have the different format compared to the numpy one:

In jax, coefficient of `x^i` has index `deg - i`
In numpy coefficient of `x^i` has an index `i`

Why there is such a backward compatibility breaking architecture decision? I have never doubt before this moment, that the numpy format is the only intuitive and because of the the most  preferred one.

**Comment by jakevdp** [comment]
If there is a difference between `jax.numpy.polyval` and `numpy.polyval`, that is a bug. Can you give an example of code that demonstrates this difference?

**Comment by PgLoLo** [comment]
Ok, while doing reproduction test I found this two different functions in numpy: [np.polyval](https://numpy.org/doc/stable/reference/generated/numpy.polyval.html) and [np.polynomial.polynomial.polyval](https://numpy.org/doc/stable/reference/generated/numpy.polynomial.polynomial.polyval.html#numpy.polynomial.polynomial.polyval)

Turned out, that `np.polyval` has the reversed order of coefficients as well (and thus `jnp.polyval` perfectly reproduce this behaviour). Sorry for the misleading, at least the design problem is not on the jax side.

**Comment by jakevdp** [comment]
Interesting - thanks for the update! Sounds like we can close this.
