### ISSUE TITLE
Improve __str__/__repr__ of PyTreeDefs

### ISSUE THREAD

**Issue by j-towns** [google/jax#5047]
Currently calling `print` on a pytree definition (the second output of `tree_util.tree_flatten`), produces something like:
```python
>>> from jax import tree_util
>>>
>>> _, treedef = tree_util.tree_flatten([1, 2, {'a': 3}])
>>> print(treedef)
PyTreeDef(list, [*,*,PyTreeDef(dict[['a']], [*])])
```
That's ok, but I think it's easier to parse if instead of nested PyTreeDefs we produce a Pythonic representation of the pytree, with variables replaced by `*`, i.e.
```python
PyTreeDef([*, *, {'a': *}])
```
It's pretty easy to implement a custom print function that does this in Python:
```python
def pretty_repr(treedef):
  class star(): __repr__ = lambda _: "*"
  return "PyTreeDef({})".format(treedef.unflatten(treedef.num_leaves * [star()]))
```
Could we make this the default representation?

**Comment by hawkinsp** [comment]
Seems reasonable. The relevant code is here: https://github.com/tensorflow/tensorflow/blob/3b2b12fb53e1e9b1a52038e0ceaf0b24c1c1872b/tensorflow/compiler/xla/python/pytree.cc#L568

If you wanted to send a PR that would speed up the process!

**Comment by j-towns** [comment]
How does one build using a local branch of TF/XLA?

**Comment by hawkinsp** [comment]
I'd do this by:
* checkout `tensorflow` as a subdirectory of your `jax` source tree
* uncomment https://github.com/google/jax/blob/945017225a4bf64252349b346b485df6c231950f/WORKSPACE#L38 and comment out https://github.com/google/jax/blob/945017225a4bf64252349b346b485df6c231950f/WORKSPACE#L29
* make whatever changes you want to the tensorflow tree.
* build a jaxlib wheel (`python build/build.py`), which will use your TF tree to get XLA, and install it.
* profit!

**Comment by NeilGirdhar** [comment]
This would be really useful.  I actually had to [improve](https://github.com/NeilGirdhar/tjax/commit/6189b5658bc0e64bfe0334e3ed651fee31740d73#diff-f97125ab417b9f7cc7c68a6f3947d038669b173acc74acc9d8e2bfcc49a0836b) this for my code too since my PyTrees are really complicated.  I frequently have to diff PyTreeDefs returned when the custom VJP complains that they don't match.  It might also be nice to consider displaying PyTreeDef on multiple lines, with sub-elements indented.

**Comment by j-towns** [comment]
@hawkinsp would it be acceptable (perhaps temporarily) to patch in the python __repr__ function above (i.e. do
```python
def tree_repr(treedef):
  class star(): __repr__ = lambda _: "*"
  return "PyTreeDef({})".format(treedef.unflatten(treedef.num_leaves * [star()]))
xla_client._xla.PyTreeDef.__repr__ = tree_repr
```
here: https://github.com/google/jax/blob/f58f1ee4563852de2853115d885c2eec7a69a77b/jax/lib/__init__.py#L58-L59? It would make sense to delete the C++ ToString code to avoid confusion, which I can also do.

My assumption is that users are unlikely to be calling `__repr__` inside a critical loop so we needn't worry too much about performance. I started writing the above in C++ but I suspect it'll take me a long time to get around to finishing it (not that it's complicated, I just suck at C++ :)).

**Comment by hawkinsp** [comment]
One thing that gives me pause about that implementation is that we can't be sure all user-defined PyTree nodes will be happy with `*` strings as leaf values.

**Comment by j-towns** [comment]
Good point. It looks like, generally speaking, custom PyTree node implementations can reasonably assume that the data in the PyTree are arrays, scalars or None. I think xmap also uses pytrees containing string data, and there may be other examples I'm not aware of, but yes, I agree it would be surprising if the `star` class implementation above didn't break _some_ user code.

**Comment by NeilGirdhar** [comment]
Could you wrap your print code in a try-except and fall back to the old version if the new code raises?  Another benefit of this is that it seems that it would work with dataclasses like `flax.struct.dataclass`?

**Comment by zhangqiaorjc** [comment]
/sub, i've been manually copy-pasting pytree print to online python formatter.

A common util seems useful. Additionally, sometimes, I do care about the type or shape or dtype of leaves.

**Comment by hawkinsp** [comment]
I think this is fixed! At head, this prints:
```
PyTreeDef([*, *, {'a': *}])
```
