### ISSUE TITLE
numpy fft not yet implemented

### ISSUE THREAD

**Issue by dwrtz** [google/jax#505]
As a fairly fundamental operation I was surprised to find out this wasn't implemented.

NotImplementedError: Numpy function <function fft at 0x7fdb56275510> not yet implemented

In the short term is there a suggested workaround? I suppose I could use a full dft matrix.

**Comment by hawkinsp** [comment]
We haven't implemented any FFT functionality yet. It's probably best that we just implement it. We're trying to be fairly user-driven in the things that we add.

Do you just need to compute FFTs (easy enough), or do you also need to differentiate through them?

**Comment by dwrtz** [comment]
Being able to differentiate through the fft and ifft would be amazing. In particular for end-to-end optimization of frequency-domain audio processing algorithms.

**Comment by psmaragdis** [comment]
I would like to second this functionality, it will make a lot of signal processing users happy.

**Comment by skye** [comment]
I started working on this earlier and got distracted by other things, I'll try to get something up for review soon!

**Comment by skye** [comment]
Hi, sorry this took so long! I just added np.fft.fftn support, with some limitations (see https://github.com/google/jax/commit/5d1c014509d429001181ff7ffcfcb54bd6aa907d for details). Please comment here or open a new issue if you need extra functionality! I committed this as-is to get the basics in, but any follow-up work will be much easier.

**Comment by brianwa84** [comment]
Looks not too hard to add ifftn?

**Comment by dynamicwebpaige** [comment]
Do we have a guide or tutorial showing how to use FFTs with JAX? If no, I'll add a feature request - it would be a great add. 🙂

**Comment by mattjj** [comment]
No tutorial yet AFAIK.

**Comment by shoyer** [comment]
I added https://github.com/google/jax/issues/1877 for keeping track of all the other FFT functions.
