### ISSUE TITLE
Test Failures - RTX 3090, Cuda 11.1, Cudnn 8.0.5, AMD 5900X

### ISSUE THREAD

**Issue by tomweingarten** [google/jax#5067]
Build command: `TMP=/tmp python build/build.py --enable_cuda --cuda_version 11.1 --cudnn_version 8.0.5 --cuda_compute_capabilities 8.6 --enable_mkl_dnn true --enable_march_native true --bazel_path=/usr/local/bin/bazelisk --bazel_options="--local_ram_resources=HOST_RAM*.75"`

Test command: `JAX_SKIP_SLOW_TESTS=1 pytest -n 1 tests`

I was surprised to see a number of failed tests with OOM errors. The GPU has 24G of memory and <150M was used by other applications. 

[testoutput.20201130.2.txt](https://github.com/google/jax/files/5623173/testoutput.20201130.2.txt)

Despite the failures, I'm able to run the Performer model in jax successfully. The speed is decent but not as fast as I'd expect given the hardware. I've attached the output of the pmap and api benchmarks.

[pmap_benchmark_results.20201201.txt](https://github.com/google/jax/files/5623450/pmap_benchmark_results.20201201.txt)
[api_benchmark_results.20201201.txt](https://github.com/google/jax/files/5623452/api_benchmark_results.20201201.txt)

**Comment by tomweingarten** [comment]
Some additional info I forgot:
Ubuntu 20.10
Nvidia driver: 455.45.01

**Comment by hawkinsp** [comment]
> Is this still on the Jetson device?
> 
> Can you see if the OOM errors go away with `XLA_PYTHON_CLIENT_ALLOCATOR=platform` ? This will hurt speed, but I think allocating 90% of memory is much too high on a platform with unified CPU/GPU memory.

Ah, I see from the title that this is on a desktop machine (and a nice looking one too!)

**Comment by tomweingarten** [comment]
No idea if this is useful, but I notice that the CPU uses a single core at 100% during training. This is surprising to me because loading the dataset is trivial and I'm only prefetching a few batches. I expect nearly all the work to be done on the GPU, which is also at 100% (as expected). Apologies if this is obvious for reasons I'm not aware of :)

**Comment by hawkinsp** [comment]
#5072 fixed a number of the test failures that I was able to reproduce on my desktop's GPU (a GTX 1080). Some I cannot reproduce.

**Comment by tomweingarten** [comment]
Definitely a big improvement, down to 36 failing tests. Some of them involve GPU memory issues on PyTorch, I assume I'll be able to fix those easily by just limiting XLA's GPU memory usage.

[testoutput.20201204.txt](https://github.com/google/jax/files/5643384/testoutput.20201204.txt)

**Comment by hawkinsp** [comment]
Bar the `array_interoperability_test` failures, which are known and expected due to GPU memory usage unless you set the right environment variables (https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html), we don't have any way to reproduce any of the remaining failures. They don't show up in our CI builds.

Please feel to reopen this issue if you have a way for us to reproduce them at head!
