### ISSUE TITLE
Tensorboard profiling fails with jax

### ISSUE THREAD

**Issue by tomweingarten** [google/jax#5069]
I get the following error when I follow the jax documentation for profiling using tensorboard:
`Failed to capture profile: ; No such file or directory`

The console output from tensorboard is:
```
2020-12-01 11:16:21.437665: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
TensorBoard 2.5.0a20201120 at http://0.0.0.0:6006/
```

One thing to note is that in order to make CUDA 11.1 work, libcudart.so.11.0 is a symbolic link to libcudart.so.11.1.74

I'm using CUDA 11.1 and CUDNN 8.0.5. I've tried this on using both the stable and nightly versions of tensorboard and the tensorboard profiling plugin.

**Comment by bchetioui** [comment]
@tomweingarten did you try with the versions recommended by @zhangqiaorjc [here](https://github.com/google/jax/issues/4427#issuecomment-731341850)?

**Comment by tomweingarten** [comment]
Thanks! Just gave those versions a try, unfortunately I'm still getting the same error. I should note I compiled jax and jaxlib from master so that I can use CUDA 11.1 and CUDNN 8.0.5

**Comment by 8bitmp3** [comment]
Hi @tomhennigan, will you be able to list the steps you've taken so far?

For example:

1. Update/uninstall CUDA (in Colab):

```shell
!apt-get --purge remove cuda nvidia* libnvidia-*
!dpkg -l | grep cuda- | awk '{print $2}' | xargs -n1 dpkg --purge
!apt-get remove cuda-*
!apt autoremove
!apt-get update
```

2. Install CUDA 11.1:

```shell
# Check that your version of Ubuntu on Colab is 18.04
!lsb_release -a
```

```shell
# Download CUDA 11.1 for Ubuntu 18.04
# (source: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=deblocal
!wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-ubuntu1804.pin
!sudo mv cuda-ubuntu1804.pin /etc/apt/preferences.d/cuda-repository-pin-600
!wget https://developer.download.nvidia.com/compute/cuda/11.1.1/local_installers/cuda-repo-ubuntu1804-11-1-local_11.1.1-455.32.00-1_amd64.deb
!sudo dpkg -i cuda-repo-ubuntu1804-11-1-local_11.1.1-455.32.00-1_amd64.deb
!sudo apt-key add /var/cuda-repo-ubuntu1804-11-1-local/7fa2af80.pub
!sudo apt-get update
!sudo apt-get -y install cuda
```

3. Check the CUDA version:

```shell
!nvcc --version
```

4. Install cuDNN 8.0.6 by following https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#installlinux (requires to be logged in to download).

5. Install TensorFlow nightly and TensorBoard profiler nightly 
(Source: https://github.com/google/jax/issues/4427)

```shell
!pip install --upgrade tf-nightly tbp-nightly
```

6. Import JAX and JAX Profiler:

```python
import jax
import jax.profiler
```

etc

**Comment by 8bitmp3** [comment]
I followed the advice of @qiuminxu 👋 (in Issue https://github.com/google/jax/issues/4427#issuecomment-714146672):

> Profiler recently moved the data processing from TensorFlow data collection side into the TensorBoard. Data collection will generate a single .xplane.pb file, and TensorBoard will process and visualize the trace. These all lands in the recent nightly, the reported issue is caused by old version of profile plugin not able to visualize the new .xplane.pb format.
> 
> Can you try: pip3 install -U tf-nightly tbp-nightly in the same virtual env of your tensorboard and see if this works?

I get an error when trying to launch TensorBoard in Colab using either of the nightlies:

1) `tf-nightly` with `tbp-nightly`; or
2) `tb-nightly==2.5.0a20201203` with `tbp-nightly==2.4.0a20201203` and `tf-nightly==2.5.0.dev20201203`.

---

Here're the steps to reproduce this:

1. Check the CUDA version (10.1 in Colab) (`!nvcc --version`)

2. Install nightly versions of TF and TensorBoard profiler:

```python
!pip install tf-nightly with tbp-nightly
# or try:
# !pip install --upgrade tb-nightly==2.5.0a20201203 tbp-nightly==2.4.0a20201203 tf-nightly==2.5.0.dev20201203 tensorboard-plugin-wit==1.7.0
```

3. Import a few things, start the JAX Profiler server, run some NumPy and JAX code, then launch TensorBoard:

```python
import jax
import jax.profiler # !
import jax.numpy as jnp
import jax.random as random
from jax import jit, grad, vmap
import numpy as np

# Start the JAX Profiler server
server = jax.profiler.start_server(port=1234)

# Some NumPy and JAX code
np.random.seed(1)
elems = np.arange(1,1000000, dtype=np.float64)

@jax.profiler.trace_function
def jax_vectorized_f(elems):
  return vmap(lambda x: x**6)(elems)

%timeit jax_vectorized_f(elems).block_until_ready()

# Load the TensorBoard notebook extension
%load_ext tensorboard

# Start a TensorBoard server
%tensorboard --logdir logs
```

Output:

```
ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
2020-12-04 22:34:16.046130: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
Traceback (most recent call last):
  File "/usr/local/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/main.py", line 75, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 291, in main
    return runner(self.flags) or 0
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 307, in _run_serve_subcommand
    server = self._make_server()
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/program.py", line 439, in _make_server
    deprecated_multiplexer,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 149, in TensorBoardWSGIApp
    experimental_middlewares,
  File "/usr/local/lib/python3.6/dist-packages/tensorboard/backend/application.py", line 257, in __init__
    "Duplicate plugins for name %s" % plugin.plugin_name
ValueError: Duplicate plugins for name projector
```

---

Alternatively, if you run stable TensorBoard and TF in Colab (`!pip install tensorflow tensorboard_plugin_profile`), then `%tensorboard --logdir logs` opens a TensorBoard instance but the Profiler remains "empty" in my experience so far.

---

(Any help would be appreciated. cc @skye @mattjj @hawkinsp @jekbradbury @jakevdp)

**Comment by 8bitmp3** [comment]
Linking https://github.com/google/flax/issues/745 (a JAX profiling Colab in the works) - it may help

**Comment by hawkinsp** [comment]
I'm guessing this issue is stale! I've verified that the profiler is working as recently as last week.

Sorry that we didn't address this in the issue sooner!
