### ISSUE TITLE
soft_pmap requests way too much memory

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#5070]
When I use `soft_pmap` for SPMD over the leading dimensions of some arrays, the memory allocation is enormous (apparently requesting as much memory as `vmap` would).
In the case I'm using it, the leading dimension is ~2.9million. It appears that `soft_pmap` is requesting way too much memory, as I get this error:

``` python
RuntimeError: Resource exhausted: Failed to allocate request for 1.33TiB
```

When it should be requesting on the order of MB of memory. As a solution I have tried using `pmap` iteratively from the python shell but face some sort of race condition that prevents this #5065. 

```
jaxjax==0.2.6
jaxlib==0.1.57
```

**Comment by Joshuaalbert** [comment]
@mattjj I think you're the guy for `soft_pmap` stuff.

**Comment by mattjj** [comment]
We're working to replace `soft_pmap`. It was always a placeholder for something better! cc @apaszke @jekbradbury @froystig 

I'm not sure if you're running into a known issue or not, but there are known issues with `soft_pmap` and memory. If you could provide a repro, we might be able to advise a workaround. Or we might be able to advise you to start using the new thing, `xmap`, which generalizes and replaces `soft_pmap`. (I'm not sure if the new thing solves your use case yet though.)

**Comment by Joshuaalbert** [comment]
Thanks @mattjj, so it sounds like at JAX you're putting more attention into the distribution side now? Is it possible to have a small  update on roadmap/timeline of some features?

**Comment by apaszke** [comment]
Hi @Joshuaalbert! We've revamped the implementation of `soft_pmap` (in terms of `xmap` which really is a better tool for this job) and so hopefully your issue should be gone. Do you have any way for us to reproduce this, or do you think it's ok to close this one?

**Comment by Joshuaalbert** [comment]
I haven't tried to reproduce this. Could you give some good documentation of xmap and when it should be used?

**Comment by apaszke** [comment]
[Here you go](https://jax.readthedocs.io/en/latest/jax.experimental.maps.html?highlight=xmap#jax.experimental.maps.xmap). I'll close the issue for now, but please reopen in case you do manage to get a self-contained example that we could use to reproduce the problem.
