### ISSUE TITLE
Incorrect results from take_along_axis with uint8 indices

### ISSUE THREAD

**Issue by alexander-g** [google/jax#5088]
I get incorrect values from `jnp.take_along_axis ` for arrays larger than 128 in any dimension and `uint8 `indices. It works with when I cast the indices to larger bit widths.
Jax version 0.2.6
Jaxlib version 0.1.57

```
h = np.random.random((256,256,100))
g = np.random.randint(0,100, size=(256,256,1)).astype(np.uint8)

q0 = jnp.take_along_axis(h, g, axis=-1)
q1 = np.take_along_axis( h, g, axis=-1)

print(np.allclose(q0[:128,:128], q1[:128,:128]))  #True
print(np.allclose(q0, q1))                        #False
```

**Comment by hawkinsp** [comment]
This is because of an integer overflow in an internal indexing calculation. I'll send a fix shortly.

**Comment by hawkinsp** [comment]
#5089 should fix this!
