### ISSUE TITLE
add docstrings for major public functions

### ISSUE THREAD

**Issue by georgedahl** [google/jax#51]
It would be very helpful when using and learning JAX to have docstrings for as many major functions as possible. Especially https://github.com/google/jax/blob/master/jax/api.py but docstrings for any non-trivial function would be helpful.

**Comment by hawkinsp** [comment]
I think we can declare this more or less done (see: jax.readthedocs.io). Obviously we can always improve the documentation, but let's close this issue and open individual issues for specific problems.
