### ISSUE TITLE
code that doesn't terminate, except with jit or disable_jit context

### ISSUE THREAD

**Issue by Joshuaalbert** [google/jax#5117]
I am using JAX to write a nested sampling package (JAXNS). In doing so I have uncovered some strange behaviour of JAX which I think is a bug. 

The problem is encapsulated in this [complete example henceforth referred to as "the code"](https://github.com/Joshuaalbert/jaxns/blob/master/jaxns/examples/gh_issue11/main.py).
To run it, simply first install the package with `pip install git+https://github.com/joshuaalbert/jaxns.git@8329c21`.

The problem is this:

1. When I run the code in a `disable_jit` context the code correctly terminates slowly (in about 15 min as expected).
2. When I wrap the code with a `jit` and run it, it terminates correctly and quickly (in about 10 seconds including compile as expected).
3. When I **neither** wrap the code in `jit`, nor place in a `disable_jit` context the code never terminates and the CPU that it is running on just hangs. No subcomponents are explicitly jitted, however there are plenty of things, like `scan` which do tracing on their own. In addition, when I run this code with this [line](https://github.com/Joshuaalbert/jaxns/blob/master/jaxns/examples/gh_issue11/main.py#L105) set to 11.0 it runs in about 10 seconds including compile just as (2). 

Please feel free to change the issue title to a more appropriate one. 

```
jax==0.2.6
jaxlib==0.1.57
```

**Comment by Joshuaalbert** [comment]
To paraphrase this bug is encapsulate in this code:
``` python
def fun(x):
  # code here linked in the main post

with disable_jit():
  fun(x) # <- works

jit(fun)(x) # <- works

fun(x) # <- doesn't work
```

**Comment by Joshuaalbert** [comment]
Not really possible to track down, so I'll close. Worthy more as a point of concern, and see if other similar stories come in.

**Comment by ethanabrooks** [comment]
This is an issue for me as well. Appreciate any help resolving.
