### ISSUE TITLE
i meet a bug when i use the latest version

### ISSUE THREAD

**Issue by XDongiang** [google/jax#5123]
when run my code , i meet a error . like this
```
2020-12-07 19:44:25.564257: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_client.cc:1809] Execution of replica 0 failed: Invalid argument: Argument does not match host shape or layout of computation parameter 0: want f32[169000,4]{1,0}, got f64[169000,4]{1,0}
Traceback (most recent call last):
  File "CalculateCache.py", line 16, in <module>
    calculateT.Calculate(my_func,mycdl)
  File "/mnt/DJC-pwa/foo/Tensor/CalculateTensor.py", line 178, in Calculate
    tensor = Tf.run()
  File "/mnt/DJC-pwa/foo/Tensor/CalculateTensor.py", line 156, in run
    _tensor = self.func(*parameter)
  File "/usr/local/lib/python3.6/dist-packages/jax/api.py", line 371, in f_jitted
    return cpp_jitted_f(*args, **kwargs)
RuntimeError: Invalid argument: Argument does not match host shape or layout of computation parameter 0: want f32[169000,4]{1,0}, got f64[169000,4]{1,0}

```

**Comment by jakevdp** [comment]
Could you provide an example snippet of code that causes this error?

**Comment by jblespiau** [comment]
(My guess is that you use an old version of jaxlib. You may want to use a newer one.).

**Comment by XDongiang** [comment]
> (My guess is that you use an old version of jaxlib. You may want to use a newer one.).
Yes , why it happened this error ?

**Comment by jwnys** [comment]
I receive the same error with the latest jax (0.2.7) and jaxlib (0.1.57, gpu). The error is raised when jit is disabled. The exact same code works when jax is enabled.

**Comment by jakevdp** [comment]
Can you provide a short example of code that leads to seeing this error? Thanks!

**Comment by 8bitmp3** [comment]
Just taking a guess here, so I apologize in advance, but can you check the `dtype` of your arrays? 

Maybe this is because the NDArray is in a double-prevision format and your JAX is set up to accept 32-bit floats (the default JAX format)?

The original error said:

> RuntimeError: Invalid argument: Argument does not match host shape or layout of computation parameter 0: **want f32[169000,4]{1,0}, got f64[169000,4]{1,0}**

(emphasis added)

In [🍴Common Gotchas 🍴](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#Double-(64bit)-precision) in the docs it says that:

> At the moment, JAX by default enforces single-precision numbers to mitigate the Numpy API’s tendency to aggressively promote operands to double. This is the desired behavior for many machine-learning applications, but it may catch you by surprise!

The docs describe 4 ways of resolving this, including adding this _at startup_:

```py
from jax.config import config
config.update("jax_enable_x64", True)
```

**Comment by jwnys** [comment]
I always enable it. Switching it on and off doesn't matter.
For me, the origin seems to be related to this bug: #4672
