### ISSUE TITLE
JIT compiler error crashes Python for simple function

### ISSUE THREAD

**Issue by clemisch** [google/jax#5135]
Dear jax team,

I'm sorry that I can't think of a more specific title. While looking into #5133 I have gotten the same crash from `jax_jit.cc` from a simple function including a `newaxis`:

```python
import numpy as np
import jax
import jax.numpy as jnp

@jax.jit
def forward(x, y):
    return x[None] * y

nshots = 1200
dim = (28, 285)

a = np.random.rand(*dim)
b = np.random.rand(nshots, *dim)

fwd = forward(a, b)  # crash
```

crashes Python with 

```
2020-12-08 16:09:15.463435: F external/org_tensorflow/tensorflow/compiler/xla/python/jax_jit.cc:771] Check failed: executable_handlers_out_tree.size() == 3 (5 vs. 3)
Aborted
```

I am building jax and jaxlib from source at fa15380d97be56b24008a0135beb37bd841f4dd9

**Comment by jblespiau** [comment]
Thanks a lot for reporting, and sorry for the inconvenience. Building from source is definitly legitimate, I had just not considered that case when submitting a CL.

You just need to use a more recent version of TF, the related CL should fix the issue. If not, feel free to say so and we will rollback.

**Comment by clemisch** [comment]
Thank you @jblespiau for the swift response! I will try your PR and report if the bug persists.

**Comment by clemisch** [comment]
Everything works! Thank you :+1:

**Comment by hawkinsp** [comment]
Interestingly this turned up a hole in the set of the CI builds that we make. We regularly test a jaxlib + jax build with jaxlib from the latest TF head, but we don't actually test jaxlib pinned at the version in the `WORKSPACE`. This was a rare case where the former worker but the latter failed. Sorry for the breakage!
