### ISSUE TITLE
How to Run JAX on multi-host GPU platforms

### ISSUE THREAD

**Issue by yxd886** [google/jax#5143]
Hi, Currently I found the step to JAX on multi-host TPU Cloud, but I do not find the step to Run JAX on multi-host GPU platforms. Does anyone can help?

**Comment by brettkoonce** [comment]
see also #2731

**Comment by hawkinsp** [comment]
Closing as a duplicate of #2731 

(The current state is: this actually works, but we don't yet expose a Python API for it, and we don't yet overlap communication with compute, which limits scalability.)
