### ISSUE TITLE
FFT crashed on recent jaxlib with CUDA 11.0

### ISSUE THREAD

**Issue by clemisch** [google/jax#5147]
Dear jax team,

`jnp.fft.fft` crashes Python on recent jaxlib and CUDA 11.0.

Repro:

```python
import numpy as np
import jax
import jax.numpy as jnp

import os
os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"
os.environ["XLA_PYTHON_CLIENT_ALLOCATOR"] = "platform"

x = jax.device_put(np.random.rand(100, 200, 300))
jnp.fft.fft(x)
```

crashes with 

```
2020-12-09 16:54:19.478050: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_fft.cc:207] failed to create cuFFT batched plan:11
2020-12-09 16:54:19.478087: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_fft.cc:430] Initialize Params: rank: 1 elem_count: 300 input_embed: 300 input_stride: 1 input_distance: 300 output_embed: 300 output_stride:
1 output_distance: 300 batch_count: 20000
2020-12-09 16:54:19.478098: F external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_fft.cc:439] failed to initialize batched cufft plan with customized allocator: Failed to create cuFFT batched plan.
Aborted
```

I am not using another process on this GPU. It crashed with jax & jaxlib compiled from HEAD as well as with your prebuilt `jaxlib==0.1.57+cuda110`. `/usr/local/cuda` is pointing to CUDA 11.0.  I'm on a Titan RTX with driver 410.104.

Of course I don't expect you to fix my CUDA installation :wink: I am rather asking for a hint whether this is likely to be caused by an error in my setup and/or where to look.

**Comment by hawkinsp** [comment]
I can't reproduce this. I tried on a GCP VM with a V100 GPU and the following version of cufft:
```
ii  libcufft-11-0                      10.2.1.245-1                                amd64        CUFFT native runtime libraries
ii  libcufft-dev-11-0                  10.2.1.245-1                                amd64        CUFFT native dev links, headers
```

Error 11 in the cuFFT error codes is:
```
    CUFFT_INVALID_DEVICE = 11, //  Execution of a plan was on different GPU than plan creation
```

What GPUs do you have on your machine? Can you show the output of `nvidia-smi`?

**Comment by clemisch** [comment]
Thank you @hawkinsp for your response!

> What GPUs do you have on your machine? 

* 2x GeForce GTX 1080 Ti
* 2x RTX TITAN

> Can you show the output of nvidia-smi?

```
[clemisch@server][~]$ nvidia-smi
Thu Dec 10 09:58:32 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.104      Driver Version: 410.104      CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:18:00.0 Off |                  N/A |
| 25%   26C    P8    15W / 250W |  10851MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:3B:00.0 Off |                  N/A |
| 35%   59C    P2    75W / 250W |  10883MiB / 11178MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN RTX           Off  | 00000000:86:00.0 Off |                  N/A |
| 40%   39C    P8    15W / 280W |   3621MiB / 24190MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN RTX           Off  | 00000000:AF:00.0 Off |                  N/A |
|100%   87C    P2    97W / 280W |   7827MiB / 24190MiB |    100%      Default |
+-------------------------------+----------------------+----------------------+
```

(The GPUs are used at the moment, but not when I was testing)

> I can't reproduce this.

FWIW I also can't reproduce this on our other servers. Setup is pretty similar, except the more recent Nvidia driver (`455.45.01` vs `410.104` here).

I am also using 

```
export XLA_FLAGS=--xla_gpu_cuda_data_dir=/usr/local/cuda-11.0
export LD_LIBRARY_PATH=:/usr/local/cuda-11.0/lib64$LD_LIBRARY_PATH
```

before starting Python. 

---

After writing this, I suspect the reason is the older Nvidia driver. I can't comprehend the way I ended up with CUDA 11.0 and an old driver on this machine, and with multiple active users it's not trivial to update the driver to test. I guess I wanted to check first if this might be a known issue.

WDYT?

**Comment by hawkinsp** [comment]
I don't know, but it would be helpful to rule out a bug from the NVIDIA stack. Can you try updating everything and let us know if that helps?

Looking at the line of code from the first error https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/stream_executor/cuda/cuda_fft.cc;l=207

it looks like `cuFftCreate` failed, but I don't see why anything we are doing would cause that: `cuFftCreate` doesn't even take any meaningful arguments!

**Comment by clemisch** [comment]
Hey @hawkinsp, I'll try updating this weekend and report back if the error persists.

**Comment by clemisch** [comment]
I upgraded the driver to `455.45.01` and now the above example works.

I would have prefered a clearer error message. But since that has nothing to do with jax, I'll close. Thank you for your help!
