### ISSUE TITLE
Reporting a documentation bug on scipy.stats.multivariate_normal logpdf

### ISSUE THREAD

**Issue by ericmjl** [google/jax#5149]
The [docs page](https://jax.readthedocs.io/en/latest/_autosummary/jax.scipy.stats.multivariate_normal.logpdf.html#jax.scipy.stats.multivariate_normal.logpdf) shows that multivariate normal's logpdf function accepts `allow_singular` as a kwarg. The source does not have the kwarg. Likely this documentation bug cropped up because of the direct wrapping of NumPy's docstrings. Just wanted to report it, nothing else.

**Comment by jakevdp** [comment]
Thanks for the report! #5150 adds the argument with an explicit NotImplementedError.
