### ISSUE TITLE
jnp.acosh and np.acosh follow different conventions

### ISSUE THREAD

**Issue by bchetioui** [google/jax#5154]
The following code outputs different results

```python
import numpy as np
from jax import numpy as jnp

x = -4.69577+2.1128223j

print(np.arccosh(x))
print(jnp.arccosh(x))
```

While there are infinitely many possible results, numpy defines a convention in its documentation for what the result should be:
https://numpy.org/doc/stable/reference/generated/numpy.arccosh.html

I do not know if it is that important, but figured I would report since we expect `jnp` and `np` to have the same behavior :)

**Comment by jakevdp** [comment]
Thanks! We should change JAX to match numpy's convention here.
