### ISSUE TITLE
jax.pmap causes multiple id_tap callbacks to run

### ISSUE THREAD

**Issue by sbodenstein** [google/jax#5169]
Consider the following:
```
@jax.pmap
def f(x):
  host_callback.id_tap(print, x)
  return x**2
f(jnp.arange(8))

# Prints:
0 ()
1 ()
2 ()
4 ()
5 ()
3 ()
7 ()
6 ()
```
So you get 8 seperate calls to id_tap, and no information is given that you are in a `pmap`. If I switch to `jax.vmap` in the above, you get a single call to id_tap and the print: `[0 1 2 3 4 5 6 7] (('batch', {'batch_dims': (0,)}),)`

There is no test for how `id_tap` should work with `pmap`, other than that the output should be correct. So not sure what the expected behaviour is.

**Comment by gnecula** [comment]
This is actually expected in the current implementation. The computation runs on multiple devices and each device will tap their data. 

One improvement that the bug suggests is to print as the tap metadata that this is coming from pmap on a specific device. I will try to implement this. 

Another possible improvement is to have the tap receiver wait for all devices to report their data and print only one output with the data from all devices. This should also be possible, but would act as a barrier for devices. I am mentioning it here for feedback, but I won't implement it right away.
