### ISSUE TITLE
jax.random.PRNGKey allocated a huge amount of memory

### ISSUE THREAD

**Issue by dasayan05** [google/jax#5181]
I am very new to `jax` and experiencing a strange memory blowup in the creation of just one `PRNGKey()`. Just doing the following
```
$ ipython
In [1]: from jax import random
In [2]: key = random.PRNGKey(0)
```
allocates a huge amount of GPU memory (upon deleting the object `del key`, memory goes down to 200MB)
```
|===============================+======================+======================|
|   0  GeForce GTX 1050    On   | 00000000:01:00.0 Off |                  N/A |
| N/A   46C    P0    N/A /  N/A |   3685MiB /  4040MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
My `jax` is built from source following [the official doc](https://jax.readthedocs.io/en/latest/developer.html).

**System Info**
OS: Ubuntu 20.04
Python: 3.8.3
Jax version: 0.2.5
CUDA: 11.0

**Comment by wiep** [comment]
i think you can find the explanation in jax' documentation: JAX will preallocate 90% of currently-available GPU memory when the first JAX operation is run [1]. 

[1] https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html
