### ISSUE TITLE
[Question] CPU subroutine within a GPU main routine

### ISSUE THREAD

**Issue by AdrienCorenflos** [google/jax#5188]
Hi,

What would be the best way to force a subroutine to run on the CPU whilst the main program would run on GPU? Intuitively I am doing the below: is it correct?

```python
from functools import partial

from jax import jit, device_get
import jax.numpy as jnp

@partial(jit, backend="cpu")
def cpu_sub_func(n):
    return n


@partial(jit, backend="gpu")
def gpu_main_function(n):
    res = cpu_sub_func(n)
    return res
```

**Comment by skye** [comment]
Your example isn't currently runnable; jitted functions can only run on a single type of device. However, you may be able to achieve something similar using `id_tap`, see https://jax.readthedocs.io/en/latest/jax.experimental.host_callback.html for details.

cc @gnecula who's working on `id_tap`.

**Comment by AdrienCorenflos** [comment]
Errr, it ran on colab....

**Comment by gnecula** [comment]
As @skye said, this is work in progress. At the moment, `id_tap` will allow code on accelerators to callback to the host to run some Python computation, but this is only for side-effects only, such as logging or printing (the Python code will not be able to return results back to the accelerator). I am working on an extension that can be used to return the results back to the device also.

**Comment by skye** [comment]
Ah, you're right this is runnable, my mistake! However, the inner jit's backend is ignored, so the whole thing will run on GPU in your example.

**Comment by shoyer** [comment]
> Ah, you're right this is runnable, my mistake! However, the inner jit's backend is ignored, so the whole thing will run on GPU in your example.

I think we could consider this behavior a bug. JAX should raise an error rather than ignoring explicit device/backend specifications on inner functions.

**Comment by AdrienCorenflos** [comment]
@shoyer instead of considering it a bug, I'd probably argue it's a desirable (not implemented) feature. This would be very useful for me to have to run lightweight loops to define for auxiliary variables used in more heavyweight calculations. A good example would be (if/when XLA allows for dynamic shape allocation) if I need to compute a small routine to know the size of a loop a priori so that I can use scan instead of while_loop for the real work.

**Comment by shoyer** [comment]
I agree, full support for explicitly nested CPU computation would be a welcome feature. The bug is silent execution on the GPU when the user requested otherwise.

**Comment by skye** [comment]
It turns out this usually does raise an error. I believe your example runs due to a special case where we short-circuit nested no-op jits calls (see #3169). If you change `cpu_sub_func` to return `n + 1` (or anything beyond just `n`), you should get an error like this:

```
Outer-jit backend specification gpu must match explicit inner-jit backend specification cpu.
```

I think we can get rid of this special case now, but it's tricky so I wanna get a second opinion on that. You can follow #5240. But for now, this should generally raise an error, except in this special case.

I'm gonna close this issue because I don't think there's anything else left to do, but please continue to comment or re-open if you still have questions or issues.

**Comment by gnecula** [comment]
I have just proposed PR #5243 with a feature that should allow you to call a Python function from a GPU computation. Perhaps it works for your use case?
