### ISSUE TITLE
Unclear error message phrasing in pmap (and possibly vmap and soft_pmap)

### ISSUE THREAD

**Issue by cleichner** [google/jax#5201]
_mapped_axis_size will give the an error like the following if you attempt to inappropriately pmap a computation:  "ValueError: pmap got arg 0 of rank 0 but axis to be mapped 0. The tree of ranks is:..." It is difficult to understand what the next steps are for debugging from this from the way it is phrased.

**Comment by gchhablani** [comment]
I agree with @cleichner. It is very hard to understand what it means and what is to be done in case this error appears.
