### ISSUE TITLE
Composition of jet with grad

### ISSUE THREAD

**Issue by vduarte** [google/jax#5217]
@mattjj 
Hi all,

I noticed that sometimes composing jet with grad produces an error. See example below:

```
import jax.numpy as jnp
from jax import grad
from jax.experimental.jet import jet

f = lambda x, ε: x * ε + ε + x

def g(ε):
  x = jnp.array(1.)
  return grad(f)(x, ε)

jet(g, (1.,), ([1.],))
```
Any insights if this is a bug?

Thanks,

**Comment by mattjj** [comment]
Thanks for raising this! It's a missing rule for `jet` (which needs one rule for each primitive), so it's more of an 'enhancement needed' rather than a 'bug'. Or maybe I just prefer that positive framing of things :)

**Comment by mattjj** [comment]
It seems we don't have _any_ tests involving `jet` + `grad`! That's how confident we are in composition of transformations ;)

In this case, `add_any` is basically an addition primitive that arises in autodiff. That's why `jet`-of-`grad` can cause `jet` to encounter one of them.

#5219 will fix!

**Comment by vduarte** [comment]
Awesome! Many Thanks!
