### ISSUE TITLE
A question about side effect (help needed)

### ISSUE THREAD

**Issue by rwbfd** [google/jax#5233]
Assume we have the following function

```
@jit 
def func(x):
    x_copy = x
    x_copy = x_copy ** 2
    # do things with x_copy
```

Will this create a side effect on x (thus leading to strange behaviors?)

**Comment by gnecula** [comment]
You only create a side-effect if you change non-local state for the function. In this case you are creating a new variable `x_copy` and then changing what it points to. There is no side effect here. If you were to add `global x_copy` in the function body, then you'd be modifying a global variable, which is a side effect.
