### ISSUE TITLE
What is the equivalent of tf's experimental_steps_per_execution for Jax.

### ISSUE THREAD

**Issue by rwbfd** [google/jax#5234]
To obtain great tpu performance in tf, the experimental_steps_per_execution seems to be crucial. 
```
    model.compile(optimizer=outer_opt,
                experimental_steps_per_execution = 600,
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True))
```

However, what is the best way to replicate this behavior in Jax?

**Comment by gnecula** [comment]
I am not really an expert in TF, but I found "experimental_steps_per_execution controls how many batches are processed on a device before a callback is run" [here](https://stackoverflow.com/questions/64648513/tf-2-3-using-experimental-steps-per-execution-in-model-compile-cause-drop-in-mod). 

This whole issue is at a higher-level of abstraction than JAX. JAX does not come pre-packaged with neural network libraries. You may want to take a look at Flax or Haiku (see also [JAX README](https://github.com/google/jax/blob/master/README.md#neural-network-libraries) for some pointers). I am pretty sure that those libraries do not have this exact feature.
