### ISSUE TITLE
Composing together jax.jit()-ted functions leading to UnexpectedTracerError ?

### ISSUE THREAD

**Issue by Jeevesh8** [google/jax#5264]
The function(a pure one( through which I want to backpropagate, does the following :-

1. Loops through a ```jax.jit()```-ted function collecting its outputs in a list.
2. Loops through the list, sending it into another ```jax.jit()```-ted function. 
3. This function outputs logits which are sent to another pure function which calculates loss.
4. The losses on all elements in the list are summed over and returned. 

Running this function (wrapped in ```value_and_grad()```) gives the following error
```
UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state.
``` 
I can't find where the leakage is. Any ideas, as to where it might be ? I even tried making deepcopies of the arguments being passed to the outer-most function, so that global state doesn't get modified.  But still it gives same error. Please help. I am grateful. 

I want the gradients to flow through both the ```jit()```-ted  functions.

**Comment by jakevdp** [comment]
It is hard to answer a question like this without seeing code that reproduces the issue, preferably not the original code with all its complexity, but rather a minimal reproduction. I tried reproducing your error using simple code following your description above, but was not able to create an escaped tracer:
```python
from jax import jit, value_and_grad
import jax.numpy as jnp

@jit
def f(x, n):
  return x ** n

@jit
def g(x):
  return jnp.exp(x.mean())

@jit
def h(y):
  return y.sum()

@value_and_grad
def main(x):
  L1 = [f(x, i) for i in range(10)]
  L2 = [g(x) for x in L1]
  return h(jnp.array(L2))

main(jnp.ones(4))
```
Can you provide a similarly stripped-down snippet that reproduces the error you're seeing?

**Comment by Jeevesh8** [comment]
@jakevdp I looked more into the problem, and tried making similar minimal examples like you mentioned above. One of these was as follows :
```
import haiku as hk
import jax
from haiku.data_structures import to_immutable_dict

def lin_5(elem):
    return hk.Linear(output_size=5)(elem)

key, subkey = jax.random.split(key)
pure_lin_5 = hk.transform(lin_5)
params_5 = pure_lin_5.init(subkey, jnp.asarray([1.]))

def lin_1(elem):
    return hk.Linear(output_size=1)(elem)

key, subkey = jax.random.split(key)
pure_lin_1 = hk.transform(lin_1)
params_1 = pure_lin_1.init(subkey, jnp.asarray([1.]*6))

def func(params, key, lis, lis2):
    results = []
    for elem in lis:
        key, subkey = jax.random.split(key)
        results.append(pure_lin_5.apply(params['5'], subkey, elem))
    final_results = []
    for elem, result in zip(lis2, results):
        final_results.append(jnp.concatenate(jnp.asarray([elem]), result))
    loss = 0
    for elem in results:
        key, subkey = jax.random.split(key)
        loss+=pure_lin_1.apply(params['1'], subkey, elem)[0]
    return loss

params = to_immutable_dict( {'1' : params_1,
                             '5' : params_5} )
key, subkey = jax.random.split(key)
arr = jnp.asarray([[3.], [4.], [6.]], dtype=jnp.float32)
arr2 = jnp.asarray([[3.], [4.], [6.]], dtype=jnp.float32)
loss, grad = jax.value_and_grad(func)(params, subkey, arr, arr2)
```

This leads to the error : ```TypeError: 'JVPTracer' object cannot be interpreted as an integer``` , although not the original error. 

Also, original error had additional information that made me realise that it comes from a tracer that was created inside a haiku initializer. And occurs at the very first embedding layer that is passed an integer tensor.. Is there some way I can check if the problem is in ```params``` or the integer tensor that is being passed to the embeddin layer (```hk.Embed```) ?

**Comment by jakevdp** [comment]
In this case, it looks like you're calling `jnp.concatenate` with the wrong signature; the second argument must be an integer axis. Your code passes an array, which when traced results in the error `TypeError: 'JVPTracer' object cannot be interpreted as an integer`.

I tried fixing this by changing it to `jnp.concatenate([jnp.asarray([elem]), result])`, but this fails because the two arrays do not have the same rank.

Also, to highlight code you can specify the language at the start of the code block; for example

    ```python
    print('hello world')
    ```

becomes:
```python
print('hello world')
```

**Comment by Jeevesh8** [comment]
Ohh.. okay, thank you. I understand now. 

The error in original code was coming due to the fact that i had mistakenly reversed the order of ```jax.jit()``` and ```hk.transform()``` . I realise the above behavior of passing through functions while accumulating results in between is completely supported by jax. 

Thank you very much.
