### ISSUE TITLE
Some mistakes when calling jax.vjp 

### ISSUE THREAD

**Issue by LuiGiovanni** [google/jax#5265]
While running some test with `jax.jvp` and `jax.vjp` and running this specific test in reference to issue #5226 I'm trying to reproduce the error that should appear which is that the matrices are not squared. I do receive an error but not the one I was expecting this issue can be seen in both Jupyter notebooks and local terminal alike. 

![image](https://user-images.githubusercontent.com/16671869/103183260-68fdd480-486e-11eb-9d6f-4e1baf0cb58a.png)

Trying to resolve this I ran into this output which is the reason I am opening this issue. I added a second pair of parenthesis to enclose the tuple and I get this output:

![image](https://user-images.githubusercontent.com/16671869/103183294-a6faf880-486e-11eb-89f5-a4a7c34697d8.png)

the highlighted parenthesis are the ones I added for better understanding. Why does it create the first `DeviceArray` but not the second one?

**Comment by jakevdp** [comment]
Hello - if you take a look at the call signature for [`jax.vjp`](https://jax.readthedocs.io/en/latest/jax.html#jax.vjp) you'll see that the expected return type is a tuple `(primals_out, vjpfun)`, where `primals_out` is a `DeviceArray` and `vjpfun` is a callable (function) that evaluates the vjp.

Here's a quick demonstration:
```python
import jax
def f(x):
  return x * 2

n = 10
key = jax.random.PRNGKey(0)
x = jax.random.normal(key, (n,))
x_out, f_vjp = jax.vjp(f, x)

print(x_out)
# [-0.744222    0.5284621  -0.36505547 -1.4736396  -0.8806077  -0.30428854
#  -1.3427072  -1.1817284   1.4633775   1.134605  ]
print(f_vjp(x)[0])
# [-0.744222    0.5284621  -0.36505547 -1.4736396  -0.8806077  -0.30428854
#  -1.3427072  -1.1817284   1.4633775   1.134605  ]
```
Does that answer your question?

**Comment by mattjj** [comment]
I'm going to close this because I think the question was answered, and due to inactivity, but please reopen (or open new issues) as needed!
