### ISSUE TITLE
Unable to install jaxlib on Windows 10

### ISSUE THREAD

**Issue by pranavsarena** [google/jax#5266]
I am trying to install RASA framework but coming across the below error.

**pip install rasa==1.7.0**

```
ERROR: Could not find a version that satisfies the requirement jaxlib>=0.1.51 (from dopamine-rl->tensor2tensor~=1.14.0->rasa==1.7.0) (from versions: none)
ERROR: No matching distribution found for jaxlib>=0.1.51 (from dopamine-rl->tensor2tensor~=1.14.0->rasa==1.7.0)
```
The environment and versions used are below:
Windows-10
Python-3.7
pip: 20.0.2 (default was 20.3.3 which was taking ages to download packages due to backtracking, so downgraded it)
RASA: 1.7.0

It seems jaxlib window support is not ready yet? [Check
](https://github.com/google/jax/issues/438). If so what needs to be done? 

Also one of my colleague was able to install rasa, he has Windows-8 on his system. 

I tried to install JAXLIB but got the below error:

**conda install jaxlib>=0.1.51**

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - jaxlib[version='>=0.1.51']

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```

**Comment by jakevdp** [comment]
Hi - we currently don't provide any pre-built wheels for jaxlib on windows, but there has been recent work in making it easier for Windows users to build `jaxlib` from source, although there still are some issues; see https://github.com/google/jax/issues/438 and https://github.com/google/jax/pull/4843 for some tips & caveats.

**Comment by pranavsarena** [comment]
I got this working. Installed dopamine-rl version 3.0.1 as this error came due to dopamine installation. Seems the default version needs jaxlib. 
**pip install dopamine-rl==3.0.1**
