### ISSUE TITLE
PEP 561 Compliance

### ISSUE THREAD

**Issue by n2cholas** [google/jax#5275]
It's really great to see type annotations throughout the library! When I try to use `mypy` on my project which uses JAX, I get the following error:

```bash
 error: Skipping analyzing 'jax': found module but no type hints or library stubs
```
I think there needs to be an empty `py.typed` file in the root of the source files, as per [PEP 561](https://www.python.org/dev/peps/pep-0561/), and a corresponding entry in the `setup.py`: 
```python
setup(
  ...
  package_data={'jax': ['py.typed']}
  ...
}
```

**Comment by jakevdp** [comment]
This is in progress in #4711

**Comment by n2cholas** [comment]
Thanks @jakevdp!

**Comment by hawkinsp** [comment]
Let's try this out! #4711 added a `py.typed` file and #5423 adds it to `setup.py`. Let us know if it works out!
