### ISSUE TITLE
lax.broadcast_in_dim transposition rule

### ISSUE THREAD

**Issue by gnecula** [google/jax#5276]
I noticed that the transposition rule of lax.broadcast_in_dim assumes that the input operand has a shape that matches the broadcast dimensions in the target shape. That is, we cannot use the following
```
x = np.ones((1, 3, 1))
lax.broadcast_in_dim(x, (2, 3, 4), broadcast_dimensions=(0, 1, 2))
```
The above would compute correctly but will fail in transpose (only if core.skip_checks == False). 

Instead one must do:
```
x = np.ones((1, 3, 1))
lax.broadcast_in_dim(x.reshape((3,)), (2, 3, 4), broadcast_dimensions=(1,))
```

Either we must add a new parameter to broadcast_in_dim with the input shape, or at the very least we ought to change the shape rule to reject unsupported uses.

**Comment by jakevdp** [comment]
We may be able to do this without a new parameter by accessing the input avals, similar to the approach that @mattjj recently used to drop `input_dtype` from `convert_element_type_p`.

**Comment by gnecula** [comment]
One thing that worried me here was that somebody had put effort into making sure that `broadcast_in_dim` was used in this limited way. See, eg., [broadcast_to](https://github.com/google/jax/blob/master/jax/_src/numpy/lax_numpy.py#L1683). That function adds a `squeeze`, I think precisely to ensure the property of broadcast_in_dim relevant here. 

I am wondering if this assumption is present elsewhere in the transformation rules. It seems that it is not.

**Comment by mattjj** [comment]
I have some recollection here! When we added `lax.broadcast_in_dim`, the corresponding XLA op was undocumented. I don't think I knew it was meant to support this singleton dimension behavior at all; I thought it'd be an error! That explains why we do things like squeezing: it wasn't to work around a transpose rule bug, but rather to fit into what I thought was the requirement of the `broadcast_in_dim` function itself.

Actually, our abstract eval rule used to flag this as an error, restricting `broadcast_in_dim`'s behavior not to support this singleton dimension stuff and therefore to be consistent with the transpose rule, until [we updated the abstract eval rule to support its full singleton-dimension generality](https://github.com/google/jax/commit/5cf82c756e6a9acf9102499e9f6d44d24c533c73#diff-46112d10675e74374612fc1dc08323118390e466908bb74a37ff475e08f59896R2375) 10 months ago in #2425.

**Comment by mattjj** [comment]
Actually, I'm not sure if the XLA op always supported the singleton dimension behavior, or if it was added to XLA later (and we just didn't update JAX to match it until #2425, but forgot to update the transpose rule in that PR).

**Comment by mattjj** [comment]
I was curious, and did some digging into JAX+XLA history! cl/217930920 is when support for BroadcastInDim singleton dimensions ("degenerate broadcast") was added, and on _the very same day_ in cl/217952788 I added it to our rewritten JAX (and in cl/218023184, sent out that same day, added the op to our XLA client).

So indeed when we added `lax.broadcast_in_dim` to JAX, this singleton dimension behavior was not supported. But if we had submitted some changes a day later, we probably would've included it.

**Comment by gnecula** [comment]
Thanks for the clarifications. I wonder how blind are we to XLA adding more functionality over time, lax primitives exposing it without realizing, and the transformation rules becoming incomplete or incorrect. Probably not very likely that all this can happen without any tests failing.
