### ISSUE TITLE
Add SVD to jax.random.multivariate_normal

### ISSUE THREAD

**Issue by SetarehAr** [google/jax#5296]
I would like to request an update on the jax.random.multivariate_normal function to accommodate SVD in addition to Cholesky decomposition. This request is made based on two reasons: (1) To match the recent api on Numpy in https://numpy.org/devdocs/reference/random/generated/numpy.random.Generator.multivariate_normal.html (2) The numerical issues I've faced using Cholesky method for dimensions larger than 10, where the issues were fixed with using SVD.

**Comment by minoring** [comment]
Hello @mattjj !
I took a look at history commits and believe `jax.random.multivariate_normal` used Cholesky decomposition only to simplify API.
I would like to get your opinion about this issue :)

**Comment by minoring** [comment]
Related code:
https://github.com/google/jax/blob/6c8fc1b031275c85b02cb819c6caa5afa002fa1d/jax/_src/random.py#L693-L695

**Comment by mattjj** [comment]
This seems like a good idea to me! Thanks for the super clear explanation @SetarehAr. I didn't know this could help with numerical issues.

@minoring are you interested in working on this? If not, I can take a stab at it.

**Comment by minoring** [comment]
Yes, let me handle this issue ;)

**Comment by minoring** [comment]
Hi @mattjj I believe this issue have been solved!

**Comment by mattjj** [comment]
Thank you, @minoring !
