### ISSUE TITLE
jac.scipy.optimize API documentation

### ISSUE THREAD

**Issue by joacorapela** [google/jax#5300]
I cannot find documentation for the package jac.scipy.optimize.
The optimize package does not appear at https://jax.readthedocs.io/en/latest/jax.scipy.html.

**Comment by 8bitmp3** [comment]
Maybe the docs needs to configured (Sphinx). There are docstings in https://github.com/google/jax/tree/master/jax/_src/scipy/optimize:

- `bfbgs.py`: Broyden-Fletcher-Goldfarb-Shanno minimization.
- `line_search.py`: Line search, Zoom.
- `minimize.py`: similar to SciPy's minimize fn with JAX's awesomeness.

**Comment by 8bitmp3** [comment]
Thanks @jakevdp
