### ISSUE TITLE
linalg.svd and linalg.pinv fail for zero-size matrices

### ISSUE THREAD

**Issue by agoose77** [google/jax#5331]
Hi all,

This issue follows from #5313 with PR #5316

`jnp.linalg.svd(jnp.zeros((0,0)))` and `jnp.linalg.pinv(jnp.zeros((0,0)))` both fail with runtime errors.

I will try and take a look if I find time, but I'm not sure how soon that will be I'm afraid :(

**Comment by jakevdp** [comment]
Note that this works correctly on GPU, but results in an error on CPU.

**Comment by jakevdp** [comment]
I made the fix for `pinv`. Note that by comparison, scipy raises a similar error for svd of an empty matrix (see https://github.com/scipy/scipy/issues/1532) while numpy return empty matrices:
```python
>>> np.linalg.svd(np.zeros((0, 0)))
(array([], shape=(0, 0), dtype=float64),
 array([], dtype=float64),
 array([], shape=(0, 0), dtype=float64))
```

**Comment by jakevdp** [comment]
Since JAX CPU translation rules rely on scipy LAPACK wrappers, jax has the same issue as scipy. Numpy specifically special-cases the empty matrix, as can be seen here: https://github.com/numpy/numpy/blob/5cae51e794d69dd553104099305e9f92db237c53/numpy/linalg/umath_linalg.c.src#L2770

**Comment by jakevdp** [comment]
Interestingly:
```python
>>> np.linalg.svd(np.zeros((0, 3)))
(array([], shape=(0, 0), dtype=float64),
 array([], dtype=float64),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

>>> np.linalg.svd(np.zeros((3, 0)))
(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([], dtype=float64),
 array([], shape=(0, 0), dtype=float64))
```

**Comment by agoose77** [comment]
Wow, thanks for digging in to the special cases here Jake.
