### ISSUE TITLE
Jax on WSL with CUDA gives me error: "could not open file to read NUMA node"

### ISSUE THREAD

**Issue by BruceChen2017** [google/jax#5361]
I install jax, jaxlib-cuda102 on WSL with cuda10.2. When I run jax(any code), it will show this message although code still runs well: 
```
E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:927] could not open file to read NUMA node: /sys/bus/pci/devices/0000:01:00.0/numa_node
Your kernel may have been built without NUMA support.
```

**Comment by hawkinsp** [comment]
This is benign and you can safely ignore it. I'll see if we can lower the priority of the message so it does not show up.
