### ISSUE TITLE
Possible bug in jax.linearize()

### ISSUE THREAD

**Issue by DiffeoInvariant** [google/jax#5364]
I'm using `jax.linearize()` to compute pushforwards, and I'm getting the following error:
```
ValueError: linearized function called on tangent values inconsistent with the original primal values: got ConcreteArray([[-0.65073081 -0.0755682 ]
        [ 0.07366651 -1.6313327 ]]) for primal aval ConcreteArray([[ 1.2067288  -0.5176796 ]
        [ 0.4400338   0.39490446]])
```
As far as I can tell, this exception is only documented in the code that raises it (in the form of the exception itself, not any comments or any other documentation), and since the tangent and primal avals are the same shape, I'm not sure what's going wrong here. Is this a bug in jax.linearize(), or have I just made a mistake in my code somewhere? If this isn't a bug in jax.linearize(), then why is this exception being raised? (The code indicates that it comes from a `TypeError` when doing `jax.core.lattice_join(primal_aval.at_least_vspace(),tangent_aval)`)

**Comment by froystig** [comment]
It's possible that the array types differ in ways not shown in the exception string formatting. In that case, it might be a bug in the system, or it might be a reason to improve the error message. Do you have a minimal code example that reproduces the issue?

**Comment by DiffeoInvariant** [comment]
Unfortunately no, it's not possible to provide a minimal example*, but I can answer any questions you may have, like "what type are the inputs" or the such. The functions I'm differentiating can accept a wrapper around `DeviceArray`s (using `register_pytree_node_class()`) as well as a regular `DeviceArray`, but in this case, I verified that all of the inputs are `jax.interpreters.xla.DeviceArray`s. I suspect that there may be an issue with `jax.linearize()` as opposed to a bad error message because the shape appears to match the expected shape (and, at least with other JAX functions, an incorrect shape usually produces a more direct error message), but that definitely doesn't rule anything out.

*I'm integrating JAX with Pyadjoint, a library for computing derivatives of finite element code, and this error only happens in one of the more complicated tests I have, so there would probably just be too much code to share to give you a good idea what's going on in a reasonable amount of time. If you'd like access to the code to see what's going on, just ping me at zane(dot)jakobs(at)colorado(dot)edu.

**Comment by DiffeoInvariant** [comment]
One thing that may be useful: the I'm linearizing about these inputs:
```
 [DeviceArray([[ 1.2067288 , -0.5176796 ],
             [ 0.4400338 ,  0.39490446]], dtype=float32), DeviceArray([], dtype=float64), DeviceArray([[ 0.40187168, -1.0056375 ],
             [-0.6255251 , -0.50311553]], dtype=float32), DeviceArray([], dtype=float64), DeviceArray([[ 0.22214633, -0.44358113],
             [ 0.6906075 ,  0.2209108 ]], dtype=float32), DeviceArray([], dtype=float64)]
```
 and I get the error when I evaluate the linearized function at 
``` [DeviceArray([[-0.78911691,  0.26306756],
             [-0.63031262,  2.26898622]], dtype=float64), DeviceArray([], dtype=float64), DeviceArray([[-0.20120885, -1.64621181],
             [ 1.02999372,  0.57414381]], dtype=float64), DeviceArray([], dtype=float64), DeviceArray([[ 0.33935116,  0.41166852],
             [ 0.1125535 , -0.19607089]], dtype=float64), DeviceArray([], dtype=float64)]
```  (and each of these has type `jax.interpreters.xla.DeviceArray`)

**Comment by DiffeoInvariant** [comment]
Oh, wait, I see the issue, I have a wrong `dtype` somehow! My bad! This isn't a bug, it's an error message that could be improved.

**Comment by hawkinsp** [comment]
I'm guessing that #7619 fixed this, but it's hard to say for sure without a repro.
