### ISSUE TITLE
Enhancement needed: Composition of jet, grad and jacfwd

### ISSUE THREAD

**Issue by vduarte** [google/jax#5365]
@mattjj 

Hi all,

Composing the jet + jacfwd + grad sometimes produces an error:

```
import jax.numpy as jnp
from jax.experimental.jet import jet


def f(x):
  x0 = x[0]
  x1 = x[1]
  return (x0**5 + x1**5).sum()


def h(ε):
  from jax import jacfwd, grad

  x = jnp.array([1., 1.])
  μ = ε * x

  def F(t):
    return f(x + t * μ)

  return grad(jacfwd(F))(0.)


jet(h, (0.,), ([1.],))
```

Any insights?
Thanks!

**Comment by mattjj** [comment]
What's the error?

**Comment by vduarte** [comment]
Here:

python3.8/site-packages/jax/experimental/jet.py in process_primitive(self, primitive, tracers, params)
    125                   if t is zero_term else t for t in series]
    126                  for x, series in zip(primals_in, series_in)]
--> 127     rule = jet_rules[primitive]
    128     primal_out, terms_out = rule(primals_in, series_in, **params)
    129     if not primitive.multiple_results:
KeyError: scatter-add


Adding 

`deflinear(lax.scatter_add_p)`

to jet.py seems to solve the problem.


Thanks
