### ISSUE TITLE
Bug in logsumexp when b argument has 0s

### ISSUE THREAD

**Issue by EddieCunningham** [google/jax#5370]
It looks like logsumexp can give the wrong answer if it's b argument has 0s in the indices where the a argument is large.  For example
``` python
import jax.numpy as jnp
from jax.scipy.special import logsumexp

a = jnp.array([-1000.0, -2.0])
b = jnp.array([1.0, 0.0])
out = logsumexp(a, b=b) # DeviceArray(-inf, dtype=float32)

# out should be DeviceArray(-1000.0, dtype=float32)
```
The bug seems to happen because the implementation subtracts the max value of a without accounting for b.  A simple fix should be to add these 2 lines of code in the first check if b is not None:
``` python
a = a + jnp.where(b, jnp.log(jnp.abs(b)), -jnp.inf)
b = jnp.sign(b)
```

**Comment by jakevdp** [comment]
Thanks for the report! Are you interested in contributing a pull request to fix this issue?

**Comment by EddieCunningham** [comment]
Sure!

**Comment by jakevdp** [comment]
Great! Feel free to submit a pull request with the fix, and ping me when you do. We'll want to make sure to add a new test case that covers this bug (i.e. one that would fail with the current code, but passes with the fix). Let me know if any questions come up along the way
