### ISSUE TITLE
jit compile cache misses only on backward pass with nested transformations

### ISSUE THREAD

**Issue by lukemetz** [google/jax#5375]
I have a jax program which calls jax.grad on a function that contains multiple calls of a jit function. I construct multiple versions of such a function. When running with a single version everything works as desired.

When running with 3 different functions of such a form I suddenly start having cache misses only on the backward pass compilation (as shown by jax's compile logging). This causes a huge performance hit.

This felt like a cache running out of storage space or something. The only example of this I could find is located at :https://github.com/google/jax/blob/master/jax/_src/util.py#L183. When I modify this size (and make this unbounded) everything works as desired again (no recompiles).

As this might be relevant, the inner jit function contains lots of nested scan, cond, remat, as well as a call to grad. The function with which I call grad on has a python for loop (calling the jit function more than once), some other math (also jit), and a call to jax.grad.

**Comment by zhangqiaorjc** [comment]
Assigning to Matt since you and Luke have some ongoing discussions.

**Comment by mattjj** [comment]
I don't think we've seen other occurrences of this issue, and without a repro it's hard to make progress. @lukemetz let us know if you come back to the JAX side and run into this again :D
