### ISSUE TITLE
Regression in jaxlib v0.1.58 for jax.scipy.special.gammaln for CPU

### ISSUE THREAD

**Issue by matthewfeickert** [google/jax#5386]
In `pyhf` we've noticed [one of our unit tests](https://github.com/scikit-hep/pyhf/blob/8c4d1ba60c5b2614bd07310a4dae21830003dbe2/tests/test_probability.py#L64-L74) that was passing for `jax` `v0.2.7` and `jaxlib` `v0.1.57`, however, with the release of `jaxlib` `v0.1.58` it has started failing. We've narrowed it down to being for `jaxlib` `v0.1.58` with `jax_enable_x64=True` in CPU mode (aka, where our unit test run).

## Minimal Reproducible Example

In a fresh Python 3.8 virtual environment

```
$ python --version --version
Python 3.8.6 (default, Jan  5 2021, 00:14:15)
[GCC 9.3.0]
$ python -m pip install --quiet --upgrade pip setuptools wheel
$ python -m pip install jax jaxlib
$ python -m pip list
Package     Version
----------- -------
absl-py     0.11.0
flatbuffers 1.12
jax         0.2.8
jaxlib      0.1.58
numpy       1.19.5
opt-einsum  3.3.0
pip         20.3.3
scipy       1.6.0
setuptools  51.1.2
six         1.15.0
wheel       0.36.2
```

then for

```python
# jaxlab_issue.py
import jax
import jaxlib
from jax.config import config
import jax.numpy as jnp
from jax.scipy.special import gammaln


class Poisson:
    def __init__(self, rate):
        self.rate = jnp.asarray(rate, dtype="float64")

    def log_prob(self, n):
        n = jnp.asarray(n, dtype="float64")
        return n * jnp.log(self.rate) - self.rate - gammaln(n + 1.0)


def main():
    config.update("jax_enable_x64", True)
    print(f"jax version: {jax.__version__}")
    print(f"jaxlib version: {jaxlib.__version__}")

    joint = gammaln(jnp.asarray([2.0, 3.0], dtype="float64")).tolist()
    individual = [
        *gammaln(jnp.asarray([2.0], dtype="float64")).tolist(),
        *gammaln(jnp.asarray([3.0], dtype="float64")).tolist(),
    ]
    print(f"joint:      {joint}")
    print(f"individual: {individual}")
    assert joint == individual

    # This is more akin to what we're seeing
    joint = Poisson([10.0, 10.0]).log_prob([2.0, 3.0])

    poisson_1 = Poisson([10.0]).log_prob(2.0)
    poisson_2 = Poisson([10.0]).log_prob(3.0)

    print(f"\njoint:      {joint.tolist()}")
    print(f"individual: {[*poisson_1.tolist(), *poisson_2.tolist()]}")
    assert joint.tolist() == [*poisson_1.tolist(), *poisson_2.tolist()]


if __name__ == "__main__":
    main()
```

```
$ python jaxlib_issue.py
jax version: 0.2.8
jaxlib version: 0.1.58
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
joint:      [8.881784197001252e-16, 0.693147180559945]
individual: [8.881784197001252e-16, 0.6931471805599432]
Traceback (most recent call last):
  File "jaxlib_issue.py", line 43, in <module>
    main()
  File "jaxlib_issue.py", line 29, in main
    assert joint == individual
AssertionError
```

however for

```
$ python -m pip install --quiet --upgrade "jaxlib<0.1.58"
$ python -m pip list | grep jax
jax               0.2.8
jaxlib            0.1.57
```

things are passing as before

```
$ python jaxlib_issue.py
jax version: 0.2.8
jaxlib version: 0.1.57
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
joint:      [8.881784197001252e-16, 0.693147180559945]
individual: [8.881784197001252e-16, 0.693147180559945]

joint:      [-6.087976994571854, -4.884004190245918]
individual: [-6.087976994571854, -4.884004190245918]
```

If the CUDA enabled version of `jaxlib` is installed the issue is **not** seen

```
$ python -m pip install --quiet --upgrade jax jaxlib==0.1.57+cuda101 --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
$ python -m pip list | grep jax
jax               0.2.8
jaxlib            0.1.57+cuda101
$ python jaxlib_issue.py
jax version: 0.2.8
jaxlib version: 0.1.57
joint:      [8.881784197001252e-16, 0.6931471805599441]
individual: [8.881784197001252e-16, 0.6931471805599441]

joint:      [-6.087976994571852, -4.884004190245918]
individual: [-6.087976994571852, -4.884004190245918]
```

```
$ python -m pip install --quiet --upgrade jax jaxlib==0.1.58+cuda101 --find-links https://storage.googleapis.com/jax-releases/jax_releases.html
$ python -m pip list | grep jax
jax               0.2.8
jaxlib            0.1.58+cuda101
$ python jaxlib_issue.py
jax version: 0.2.8
jaxlib version: 0.1.58
joint:      [8.881784197001252e-16, 0.6931471805599441]
individual: [8.881784197001252e-16, 0.6931471805599441]

joint:      [-6.087976994571852, -4.884004190245918]
individual: [-6.087976994571852, -4.884004190245918]
```

so this seems to be a CPU only issue.

We do realize that this difference is incredibly small, but as this is a change in behavior that we didn't expect we though we'd still report it even if this gets a "won't fix" label.

cc @lukasheinrich @kratsg

**Comment by mattjj** [comment]
Wow, thanks for the detailed report!

This could've been due to an LLVM update or some other low-level XLA:CPU thing. In general we expect compiler updates might affect numerics in small ways.

Is this a problem for your work? If it's not a big problem, it's probably not worth asking the compiler folks to dig into it.

**Comment by mattjj** [comment]
(Also, in general it might not be a good idea to compare for exact equality on floats in unit tests, compared to comparing allclose with tolerances as tight as you care about.)

**Comment by matthewfeickert** [comment]
> Is this a problem for your work? If it's not a big problem, it's probably not worth asking the compiler folks to dig into it.
> ...
> (Also, in general it might not be a good idea to compare for exact equality on floats in unit tests, compared to comparing allclose with tolerances as tight as you care about.)

Yeah, we were surprised about this happening but kinda came to the same conclusion that comparing out to 15 decimal places is not really helpful, let along a great idea. :grimacing: We usually don't do exact `assert`s, but given the nature of the operations used in [the test in question](https://github.com/scikit-hep/pyhf/blob/8c4d1ba60c5b2614bd07310a4dae21830003dbe2/tests/test_probability.py#L64-L74) I think when we wrote this a few years ago we thought it should be fine to ask that they actually be identical.

We more just found this curious that it had worked fine for many releases of `jaxlib` and then broke on `v0.1.58`, so we thought we'd raise it in the event this was curious to anyone else. In terms of `pyhf` development I think we can just change the test and move on.

**Comment by mattjj** [comment]
Excellent, thanks! Yeah I really appreciate the detailed report.

I'll tag @hawkinsp in case he has anything to add, but I think we should be more surprised that these floating point details have been so stable across releases in the past, rather than being surprised that things eventually deviated :)

**Comment by kratsg** [comment]
Hi @mattjj -- thanks for the quick response. 

Initially I was thinking that somehow changes to the underlying compilers would impact things, but the way this bug appears, it seems like the two 1-dimensional calculations isn't exactly equivalent as doing a one 2-dimensional calculation, `[x(a), x(b)] != x([a,b])`. That is, a vectorized calculation shouldn't give a different answer than the non-vectorized calculation?

**Comment by mattjj** [comment]
I think it comes down to how we define "different", i.e. whether it's about exact equality on floats or just floats being close enough, within some tolerance. A vectorized computation can lead to different compiler optimizations (e.g. LLVM sees very different input code in the two cases) and different machine instructions potentially using different hardware (e.g. vector hardware). Given how sensitive exact equality on floats is to the details of a computation (e.g. floating point addition is not associative), I wouldn't expect exact floating point equality to hold between vectorized and un-vectorized versions. But I would still say the results were "the same" if they were within some small tolerance.

I'm not an expert on this stuff. If this is important to your work then I could raise this issue with some experts.

**Comment by kratsg** [comment]
> A vectorized computation can lead to different compiler optimizations (e.g. LLVM sees very different input code in the two cases) and different machine instructions potentially using different hardware (e.g. vector hardware).

I think this explanation is fine. I guess I'm surprised we managed to make it this long with it being exactly the same.  Perhaps by luck. Thanks! (I don't think it needs to be raised further at the moment.)
