### ISSUE TITLE
Jit of grad uses a ton of memory

### ISSUE THREAD

**Issue by EddieCunningham** [google/jax#5395]
It looks like JAX takes a ton of CPU memory when jitting the grad of a function and it seems like the amount of memory grows almost exponentially with the size of the computation instead of linearly as I would expect.  Here is a toy example of the kind of functions I am evaluating:

``` python
import jax
from jax import jit, random
import jax.numpy as jnp

def norm(params, x):
  b, log_s = params
  log_det = log_s.sum()
  z = (x - b)*jnp.exp(-log_s)
  return z, log_det

def prior(params, x):
  sum_axes = tuple([-(i + 1) for i, _ in enumerate(params[0].shape)])
  def unit_gaussian(x):
    return -0.5*jnp.sum(x**2, axis=sum_axes)
  return x, unit_gaussian(x)

def apply_fun(params, x):
  log_px = 0.0
  for i in range(n_layers):
    x, log_det = norm(params, x)
    log_px += log_det

  _, log_pz = prior(params, x)
  log_px += log_pz

  return log_px.mean()
```

I check how much memory is being used by taking a snapshot of the memory before and after a function call:
``` python
from contextlib import contextmanager
import resource

class MemoryTracker():

  def __init__(self):
    self.mem_needed = {}

  def get_memory_usage(self):
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

  @contextmanager
  def track(self, key, n_layers):
    if key not in self.mem_needed:
      self.mem_needed[key] = []

    try:
      start_mem = self.get_memory_usage()
      yield
    finally:
      end_mem = self.get_memory_usage()

    self.mem_needed[key].append((n_layers, end_mem - start_mem))

  def mem_usage(self, key, for_log=False, mb=False):
    mem = jnp.array(self.mem_needed[key])

    const = 1e-3 if mb else 1

    if for_log == False:
      mem = jax.ops.index_update(mem, jax.ops.index[:,1], mem[:,1]*const)
    else:
      mem = jax.ops.index_update(mem, jax.ops.index[:,1], jnp.where(mem[:,1], mem[:,1]*const, 1))
    return mem
```

and here is the overall test.  I check to see how much memory a regular function call, jitted function call, regular grad call and jitted grad call use.

``` python
dim = 8 # 4096
data_shape = (dim,)
mem_tracker = MemoryTracker()

for n_layers in jnp.linspace(2, 30, 10)**1.5:
  n_layers = int(n_layers)

  key = random.PRNGKey(0)
  x = jnp.ones((10,) + data_shape)
  b, log_s = random.normal(key, shape=(2,) + data_shape)
  params = (b, log_s)

  with mem_tracker.track("Apply", n_layers):
    y = apply_fun(params, x)

  with mem_tracker.track("JIT Apply", n_layers):
    y = jit(apply_fun)(params, x)

  with mem_tracker.track("Grad", n_layers):
    g = jax.grad(apply_fun)(params, x)

  with mem_tracker.track("JIT Grad", n_layers):
    g = jit(jax.grad(apply_fun))(params, x)

```

What I find is that "Apply", "JIT Apply" and "Grad" keep a low memory footprint while "JIT Grad" takes a huge amount of memory:
![memory_usage_8](https://user-images.githubusercontent.com/14224280/104487009-8df68500-559a-11eb-89a0-96db8e27633e.png)

Also it looks like the amount of memory used isn't too dependent on the size of the input.  For example, if I change the dimensionality from the 8 that was used to make the above plot to 4096, the results are pretty similar:

![memory_usage_4096](https://user-images.githubusercontent.com/14224280/104487187-c6965e80-559a-11eb-8fb5-32fe90f7cbea.png)

This problem also seems to get worse when the function has more overhead.  For example this same example written using Haiku follows the same trend but blows up to a larger extent.  Any thoughts on whats going on?

**Comment by skye** [comment]
Are you running on CPU or GPU? Either way, I'm guessing this is due to the memory used by XLA to compile your computation. If you're able to set up some memory profiling, that might tell us more specifically what's going on. I'm not super familiar with Python memory profiling but it looks like https://pypi.org/project/memory-profiler/ might work (note that we have [device memory profiling], but this doesn't capture CPU memory usage).

cc @phawkins in case he has other ideas.

**Comment by EddieCunningham** [comment]
I ran this on a GPU, but the CPU gives the same trend but an overall lower memory usage.  
![memory_usage_8_cpu](https://user-images.githubusercontent.com/14224280/104676318-22550a80-56b5-11eb-91da-f59aae12e019.png)
![memory_usage_4096_cpu](https://user-images.githubusercontent.com/14224280/104676319-22550a80-56b5-11eb-97f4-43dfb8e42ba5.png)

I wrapped the jitted grad call with the memory profiler you linked and unfortunately the code is hidden behind a wrapped function:

``` python
Line #    Mem usage    Increment  Occurences   Line Contents
============================================================
   136    637.1 MiB    637.1 MiB           3     @util.wraps(fun)
   137                                           def reraise_with_filtered_traceback(*args, **kwargs):
   138    637.1 MiB      0.0 MiB           3       try:
   139    792.1 MiB    155.0 MiB           3         return fun(*args, **kwargs)
   140                                             except Exception as e:
   141                                               if not is_under_reraiser(e):
   142                                                 filtered_tb, cause, filtered = None, None, None
   143                                                 try:
   144                                                   filtered_tb = filter_traceback_and_stack(e)
   145                                                   if filtered_tb:
   146                                                     msg = format_exception_only(e)
   147                                                     msg = f'{msg}\n\n{_jax_message_append}'
   148                                                     filtered = FilteredStackTrace(msg).with_traceback(filtered_tb)
   149                                                     cause = last_cause(e)
   150                                                     cause.__cause__ = filtered
   151                                                     raise
   152                                                   else:
   153                                                     raise
   154                                                 finally:
   155                                                   del filtered_tb
   156                                                   del cause
   157                                                   del filtered
   158                                               else:
   159                                                 raise

```
Here is the full output for different runs
[mem_bug_profile_results_cpu.txt](https://github.com/google/jax/files/5818170/mem_bug_profile_results_cpu.txt)
[mem_bug_profile_results_gpu.txt](https://github.com/google/jax/files/5818171/mem_bug_profile_results_gpu.txt)

Across different runs the "Increment" memory changed the same way the original test did:

| n_layers      | CPU (MB) | GPU (MB) |
| ----- | ----------- | ----------- |
| 20   | 12.5       | 19.2 |
| 40   | 39.8       | 51.1|
| 80   | 135.8     | 155.0|
| 160 | 399.3     | 836.8|

Also I'm not sure how useful this is, but here is the output of [memory profiling](https://github.com/google/jax/blob/5116fd47aa9cf44888b88c685c380422bf0fdc50/docs/device_memory_profiling.md) when run in CPU mode:
![pprof_cpu](https://user-images.githubusercontent.com/14224280/104676513-8546a180-56b5-11eb-97ca-a852ec42d854.png)


Let me know if you need any more information!

**Comment by skye** [comment]
The fact that you see similar usage when targeting GPU is further evidence that the CPU memory usage is from compiling the program (since the actual program will be using mostly GPU memory). It looks like the memory usage isn't too high in the grand scheme of things though (< 1 GB) -- is the memory usage causing problems for you, or are you just curious why you're seeing nonlinear scaling? I can forward this to the XLA team if it's causing problems, but people are generally more concerned with device memory than host memory, so it might not be high on their priority list to fix.

**Comment by EddieCunningham** [comment]
Unfortunately this issue is stopping me from training large networks in my research.  Can you forward this to the XLA team?  Even if the issue is not fixed, I'm curious about what's going on and if there is a workaround or more memory efficient way I can write my code.  Thanks for taking a look at this!

**Comment by skye** [comment]
I provided the XLA team with your repro (thanks for providing a fully-runnable repro btw, super helpful!). We'll let you know when we have any updates.

BTW, when doing benchmarking like this, be sure to use `block_until_ready()` to make sure you're measuring the right things. See https://jax.readthedocs.io/en/latest/async_dispatch.html for more info. I added `block_until_ready()` calls to your repro and in this case it didn't make a big difference to the final result, but something to watch out for in the future.

**Comment by EddieCunningham** [comment]
Awesome, thanks!  I'll make sure to use block_until_ready() next time I'm timing code.

**Comment by skye** [comment]
@EddieCunningham any chance you could provide a repro that shows the kind of behavior that's blocking your training code? I.e. something that shows more dramatic memory usage. This will be easier for the XLA team to debug, even if it's a more complicated repro.

**Comment by EddieCunningham** [comment]
I was able to work around this by replacing all of my for loops with scan loops.

**Comment by donal-mur** [comment]
I am having a similar problem -  not sure how to use scan loops? 
Seems to leave lots of unterminated version in memory
