### ISSUE TITLE
Dockerfile not installing properly

### ISSUE THREAD

**Issue by Jeevesh8** [google/jax#5436]
I tried to install and run jax from the given dockerfile but when I docker run the image in interactive mode it gives following output and exits : 
```bash
if [ ! -d "/dist" ]
then
  echo "/dist must be mounted to produce output"
  exit 1
fi
+ '[' '!' -d /dist ']'
+ echo '/dist must be mounted to produce output'
/dist must be mounted to produce output
+ exit 1
```
Any ideas as to how to solve it ?

**Comment by hawkinsp** [comment]
This dockerfile isn't intended for this use case. It's used as part of our wheel build process. (See `build/build_jaxlib_wheels.sh` for details on how it is used.) This is therefore as intended. We could add another dockerfile for running JAX, but that isn't the Dockerfile you are looking at.

**Comment by AndrewCSQ** [comment]
For those Googling for a dockerfile to run jax, I've found that tensorflow-gpu images work. See [this discussion](https://github.com/google/jax/discussions/6338)
