### ISSUE TITLE
VMap of jnp.arange throws "Abstract Tracer Value encountered"

### ISSUE THREAD

**Issue by unrealwill** [google/jax#5454]
Hello, 
I'm trying to be able to use some sort of looping over indices inside vmap, and it needs to be able to take some gradients.

I have also tried with jax.lag.fori_loop and it does work for the forward pass but doesn't work for the gradients.

Can you please advise ?

I'd like to do something like this : 
```python
from jax import vmap
import jax.numpy as jnp
import numpy as np
import jax
from jax import grad,jit

def testSimpleRangeInVMap( parts ):
    def innerRange( i ):
        inds = jnp.arange(i)
        selected = parts[inds]
        p = jnp.sum( selected, axis= 0)
        return p

    print( "innerRange(3)")
    print( innerRange(3) )

    print("innerRange(4)")
    print( innerRange(4) )

    bounds = jnp.array([3, 4], dtype="int32")
    res = vmap(innerRange)(bounds)

    return res

parts = jnp.array( np.random.randn(40,2) )
print( testSimpleRangeInVMap( parts ) )
```

Outputs : 

```pytb
innerRange(3)
[-1.4303324  -0.32441515]
innerRange(4)
[-2.736762  -1.7744572]
Traceback (most recent call last):
  File "jaxbug2.py", line 26, in <module>
    print( testSimpleRangeInVMap( parts ) )
  File "jaxbug2.py", line 21, in testSimpleRangeInVMap
    res = vmap(innerRange)(bounds)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/api.py", line 1189, in batched_fun
    axis_name=axis_name)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/interpreters/batching.py", line 35, in batch
    return batched_fun.call_wrapped(*in_vals)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/linear_util.py", line 160, in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
  File "jaxbug2.py", line 9, in innerRange
    inds = jnp.arange(i)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/_src/numpy/lax_numpy.py", line 2824, in arange
    start = require(start, msg("stop"))
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 922, in concrete_or_error
    raise_concretization_error(val, context)
  File "/home/username/venvtf2.4/lib/python3.6/site-packages/jax/core.py", line 899, in raise_concretization_error
    raise ConcretizationTypeError(msg)
jax.core.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected.

It arose in jax.numpy.arange argument `stop`.

See https://jax.readthedocs.io/en/latest/faq.html#abstract-tracer-value-encountered-where-concrete-value-is-expected-error for more information.

Encountered tracer value: Traced<ShapedArray(int32[])>with<BatchTrace(level=1/0)>
  with val = DeviceArray([3, 4], dtype=int32)
       batch_dim = 0
```

**Comment by unrealwill** [comment]
Answering partially my own question.
Using python List comprehension instead of vmap works and gradients works too but is slow (~300x slower).
Jitting doesn't seem to be possible when arrays are of dynamic sizes, though using static_argnums=(0) to jit, allows the computation to be run but is even slower because it needs a new compilation for each new size.

The root problem is **"JAX does not support dynamically sized arrays within JIT compiled functions"** as reported by dynamic_slice's error.

There are probably hacks to to workaround, like jitting with various sizes and masking. 

In theory in my specific problem it should be possible to not have to materialize the inner memory of the function that is going to be reduced, so there is no need to allocate anything inside and dynamically sized array shouldn't be a problem.

Various experiments : 
```
from jax import vmap
import jax.numpy as jnp
import numpy as np
import jax
from jax import grad,jit
import jax.numpy as jnp
from jax import custom_jvp
import time

def testSimpleRangeInVMap( parts ):
    def innerRange( i ):
        p = jnp.sum( parts[  jnp.arange(3) + i ], axis= 0)
        #p = jnp.sum( jax.lax.dynamic_slice(parts,(i,0),(3,2)),axis=0)
        return p
    bounds = jnp.arange(1000)
    err = jnp.sum( vmap(innerRange)(bounds)**2 )
    return err

def testSimpleRangeWithListComprehesion( parts ):
    def innerRange( i ):
        return jnp.sum( parts[jnp.arange(i,i+3)], axis= 0)

    bounds = jnp.arange(1000)
    err = jnp.sum( jnp.array([ innerRange(b)**2 for b in bounds] ))
    return err

def testJittedSimpleRangeWithListComprehesion( parts ):
    def innerRange( i ):
        return jnp.sum( parts[jnp.arange(i,i+3)], axis= 0)

    bounds = jnp.arange(1000)
    jitted = jit( lambda b: innerRange(b)**2,static_argnums=(0))
    err = jnp.sum( jnp.array([ jitted(b) for b in bounds] ))
    return err

parts = jnp.array( np.random.randn(100000,2) )
print( testSimpleRangeInVMap( parts ) )
start_time = time.time()
for i in range(1):
    testSimpleRangeInVMap(parts)
print("testSimpleRangeInVMap x1 --- %s seconds ---" % (time.time() - start_time))

print( testSimpleRangeWithListComprehesion( parts ) )
start_time = time.time()
for i in range(1):
    testSimpleRangeWithListComprehesion(parts)
print("testSimpleRangeWithListComprehesion x1 --- %s seconds ---" % (time.time() - start_time))

print("testJittedSimpleRangeWithListComprehesion")
print( testJittedSimpleRangeWithListComprehesion(parts))
start_time = time.time()
for i in range(1):
    testJittedSimpleRangeWithListComprehesion(parts)
print("testJittedSimpleRangeWithListComprehesion x1 --- %s seconds ---" % (time.time() - start_time))
```

Which outputs : 
```
5629.7705
testSimpleRangeInVMap x1 --- 0.00597381591796875 seconds ---
5629.7705
testSimpleRangeWithListComprehesion x1 --- 1.8765184879302979 seconds ---
testJittedSimpleRangeWithListComprehesion
5629.7705
testJittedSimpleRangeWithListComprehesion x1 --- 15.805928707122803 seconds ---
```

**Comment by jakevdp** [comment]
Hi - thanks for the question! The issue here comes from the fact that in JIT, vmap, and other transforms, array shapes must be static. That is, if you write something like `jnp.arange(i)`, the `i` must be known at compile-time.

In this snippet, since `innerRange` is vmapped, the `i` is not known when the function is compiled, and that leads to the error you see.

Does that make sense?

**Comment by unrealwill** [comment]
Yes it makes sense, now. I was wondering if there is a way to not have jnp.arange materialize the arrays, as the computations I'm doing can be done without allocating extra-memory.

**Comment by jakevdp** [comment]
In cases like this, you can often re-express your computation to avoid the use of dynamic arrays. For example, instead of
```py
result = arr[np.arange(i)].sum()
```
you could do something like
```py
result = np.where(np.arange(arr.shape[0]) <= i, arr, 0).sum()
```
I believe the latter should be JIT-compatible for a traced value of `i`

**Comment by unrealwill** [comment]
Thanks, good idea but unfortunately in my use case I need the sparsity and can't materialize the dense array.

Basically the problem I'm trying to tackle is some particle in cells simulation, where each cell can have a variable number of particles. 
For each cell, For each pair of particle in the cell : energy += interactionEnergy( p1,p2) 
Then take the gradient, and move the particles.

As there are a potentially quadratic number of interaction in a cell (max ~100 interactions per cell) , and roughly as many cells as particles, memory should be handled carefully. When done correctly in theory it can be written with 0 memory allocations (and the memory cost is O(nbparticle), and computation cost O(nb interactions) )

Code for your suggestion : 
```
def testWhere2D( parts ):
    def innerRange(i):
        cond1 = jnp.arange(parts.shape[0]) < i + 3
        cond2 = i <= jnp.arange(parts.shape[0])
        cond = cond1*cond2
        p0 = jnp.where(cond, parts[:,0], 0).sum()
        p1 = jnp.where(cond, parts[:,1], 0).sum()
        return jnp.array([p0,p1])
    #print( innerRange(3) )
    bounds = jnp.arange(1000)
    err = jnp.sum(vmap(innerRange)(bounds) ** 2)
    return err
```
Output during the gradient computation : 
`RuntimeError: Resource exhausted: Out of memory while trying to allocate 400000000 bytes.`

**Comment by jakevdp** [comment]
I don't have any ideas for how to handle this in a jit-compatible way; but note that your original approach with dynamic array sizes works fine outside JIT.

**Comment by jakevdp** [comment]
That said, you may be able to implement this in terms of a scan to avoid materializing the intermediate array.

**Comment by unrealwill** [comment]
Thanks very much for your dedication.

It does work without JIT acceleration so it's at least useful to check gradients written manually, but that's about it.

I tried to implement it with scan, and it does work with gradient and JIT, as long as the length of the inner loop is of definite size, otherwise it throws  "Abstract tracer value encountered where concrete value is expected"

```
def testScan( parts ):
    def innerRange( i ):
        #p = jnp.sum( jnp.array( [parts[j] for j in range(i,i+3)] ) )
        out = jnp.zeros((2,))
        def body( carry, _ ):
            curr, ii = carry
            return (curr+ parts[ii],ii+1 ) , None

        #When length is not known it crash with "Abstract tracer value encountered where concrete value is expected"
        #(res, _), _ = jax.lax.scan(body, (out, i), jnp.arange(i,i+3))
        (res,_),_ = jax.lax.scan( body,(out,i),None, length= 3)
        return res

    #print( innerRange( 5 ))

    bounds = jnp.arange(1000)
    err = jnp.sum(vmap(innerRange)(bounds) ** 2)
    return err

print("testScan")
print( testScan(parts) )
gtestScan = grad(testScan)
print( gtestScan(parts)[0:10,:])
```

I also tried to implement a custom gradient, which does work but is very slow and breaks higher order derivatives : 
```
@custom_jvp
def testFor( parts ):
    def innerRange( i ):
        out = jnp.zeros((2,))
        return jax.lax.fori_loop(i, i+3, lambda ii,val: val+parts[ii],out )

    bounds = jnp.arange(1000)
    err = jnp.sum(vmap(innerRange)(bounds) ** 2)
    return err

def gradTestFor( x_dot, primal_out, parts):
    outs = [ jnp.sum( 2.0*x_dot[i+j]*parts[i+k] ) for i in range(1000)  for j in range(3) for k in range(3) ]
    out = sum( outs )
    return out

testFor.defjvps(gradTestFor )
```

Currently it seems Jax don't support my use case because of some XLA fixed-sized memory allocation requirements, so I'll close this issue.

It's very frustrating though. It's kind of reminiscent of the old days of Theano, when arange needed to be of fixed size. Then tensorflow came, and this restriction was lifted and it was a bowl of fresh air. Then Jax comes with plenty of composition magic that you can't use, because of this old problem which came back. 

For my code derivatives when iteration is needed, I use source code transformation with Tapenade, then need some manual rewrite to extract and allocate the stacks out of the loops and to wrap cuda, is needed to optimize for performance and obtain zero-extra memory allocations. 

It's killing my productivity though, because it's tedious and low level. So I'm (considering) writing a Domain Specific Language to do what Tapenade does with extra-optimization (cuda + Loop reordering + commutation optimization + MPI partitioning), to do those operations efficiently for my specific use case.
