### ISSUE TITLE
Flax increases jit dispatch cost by x4 compared to pure jax: help? 

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#5485]
I have read several times that Jax dispatch cost to a jitted function is around 60-70  μs.
Testing with a very simple RBM implemented in Flax, I see a 250 μs dispatch cost. Both functions have the same input (different storage format, but same number of leaves) and compile down to the same xla code.

This is unexpected, as Flax is using `FrozenDict` to store parameters which store their hash and therefore should be faster.

I opened an issue on Flax repo, and after some debugging they asked me to open an issue here [Flax#912](https://github.com/google/flax/issues/912).
I also created an accompanying [gist](https://gist.github.com/PhilipVinc/24d7e46abe6a6edd72293f63803b4f09) with a notebook showing this. 

I also tried calling the same jitted function several times under `py-spy`, a sampling profiler, and the traces of jax vs flax are veery different. In particular, it seems the flax RBM hits and spends considerable time in `jax.api_tools.cache_miss`, which I don't understand because the function is only compiled once.

I know that you make no assertions about dispatch cost, because in general that is not very relevant, but in medium size Markov Chain Monte Carlo sampling this popped up.

Could you please help me understand what might be causing this and maybe fix it?

cc @jheek 

```python
➜ sudo py-spy top -- python jax_test.py

Collecting samples from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python wtest.py' (python v3.8.5)
Total Samples 800
GIL: 0.00%, Active: 100.00%, Threads: 1

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
  8.00% 100.00%   0.620s     6.45s   <module> (wtest.py:126)
  0.00%  92.00%   0.040s     6.19s   reraise_with_filtered_traceback (jax/_src/traceback_util.py:139)
 86.00%  86.00%    5.33s     5.84s   f_jitted (jax/api.py:395)
  0.00%   0.00%   0.000s    0.800s   _load_unlocked (<frozen importlib._bootstrap>:671)
  0.00%   0.00%   0.000s    0.800s   _find_and_load (<frozen importlib._bootstrap>:991)
  0.00%   0.00%   0.090s    0.800s   _call_with_frames_removed (<frozen importlib._bootstrap>:219)
  0.00%   0.00%   0.000s    0.800s   exec_module (<frozen importlib._bootstrap_external>:783)
  0.00%   0.00%   0.000s    0.800s   _find_and_load_unlocked (<frozen importlib._bootstrap>:975)
```

```python
➜ sudo py-spy top -- python flax_test.py

Collecting samples from '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/Resources/Python.app/Contents/MacOS/Python ftest.py' (python v3.8.5)
Total Samples 2800
GIL: 0.00%, Active: 100.00%, Threads: 1

  %Own   %Total  OwnTime  TotalTime  Function (filename:line)
  2.00% 100.00%   0.300s    26.62s   <module> (ftest.py:126)
  0.00%  98.00%   0.020s    26.42s   reraise_with_filtered_traceback (jax/_src/traceback_util.py:139)
  9.00%  97.00%    2.12s    25.96s   f_jitted (jax/api.py:395)
  1.00%  73.00%   0.210s    19.86s   cache_miss (jax/api.py:286)
  1.00%  72.00%   0.260s    19.65s   bind (jax/core.py:1235)
  0.00%  62.00%   0.110s    16.74s   call_bind (jax/core.py:1226)
  0.00%  62.00%   0.020s    16.40s   process (jax/core.py:1238)
  1.00%  62.00%   0.170s    16.37s   process_call (jax/core.py:598)
  2.00%  55.00%   0.290s    13.92s   _xla_call_impl (jax/interpreters/xla.py:579)
  0.00%  35.00%   0.240s     8.08s   _execute_compiled (jax/interpreters/xla.py:836)
  0.00%  35.00%   0.120s     7.84s   <genexpr> (jax/interpreters/xla.py:836)
  0.00%  33.00%   0.150s     7.58s   device_put (jax/interpreters/xla.py:127)
  0.00%  21.00%   0.120s     5.34s   _device_put_device_array (jax/interpreters/xla.py:1302)
 11.00%  11.00%    4.04s     4.04s   _execute_compiled (jax/interpreters/xla.py:837)
  0.00%  17.00%   0.060s     3.89s   _force (jax/interpreters/xla.py:1341)
 17.00%  17.00%    3.83s     3.83s   force_fun (jax/interpreters/xla.py:1373)
  2.00%   6.00%   0.200s     2.26s   _xla_call_impl (jax/interpreters/xla.py:576)
  0.00%  12.00%   0.020s     2.08s   _device_put_device_array (jax/interpreters/xla.py:1301)
  1.00%   2.00%   0.590s     1.07s   memoized_fun (jax/linear_util.py:246)
  0.00%   3.00%   0.070s     1.02s   cache_miss (jax/api.py:274)
  0.00%   3.00%   0.130s     1.01s   _execute_compiled (jax/interpreters/xla.py:839)
  3.00%   5.00%   0.570s    0.990s   _copy_device_array_to_device (jax/interpreters/xla.py:1314)
```

**Comment by froystig** [comment]
> it seems the flax RBM hits and spends considerable time in `jax.api_tools.cache_miss`, which I don't understand because the function is only compiled once

Spending considerable relative time in `cache_miss` suggests that it is being re-compiled for some reason. Have we ruled out multiple compilations? Is there somewhere a simple `print` statement can be placed to check that?

**Comment by PhilipVinc** [comment]
Yes I did, at the top level of the jitted function, and it's only executed once.
I'm fairly confident it's not re-compiling.

**Comment by hawkinsp** [comment]
Another experiment to try: can you try disabling the C++ JIT (`JAX_CPP_JIT=0` should do it)?

**Comment by PhilipVinc** [comment]
Tried (`export JAX_CPP_JIT=0` before running python), and the runtime is the same, with a profile trace identical to the ones above.

**Comment by PhilipVinc** [comment]
@hawkinsp Have you any suggestion on what I could do to understand the cause of this slowdown?

**Comment by levskaya** [comment]
_Tempore omnia vulnera sanabuntur_

I wanted to re-check the results here given how much work has gone on in JAX this year concerning dispatch overheads.

Across the board JAX dispatch times are down -a lot-.  The overhead of using flax vs stax is now extremely slight in dispatch-sensitive tests (lots of tiny launches) and non-existent on any reasonably large computation.

on my macbook, small setting:
- `6.81 µs ± 198 ns` STAX vs `7.81 µs ± 195 ns` FLAX  (old numbers were `65µs` vs `255µs`!)
-  ~`1.14x` now vs ~`4x`, and a 10x absolute improvement in dispatch!

on my macbook, larger setting:
- `304 µs ± 23 µs` STAX vs `308 µs ± 42.8 µs` FLAX (old numbers were `410µs` vs `603µs`!)
- ~`1.x` now vs ~`1.5x`

I reran all the benchmarks on colab cpu and my macbook cpu, results here:
https://colab.research.google.com/drive/1mPa51aFSK_NOSOi3USrLu-GnqOlh-LDX?usp=sharing

So I believe for all practical purposes this issue is resolved, and will mark this issue closed.  Please feel free to re-open if you have further concerns here though!
