### ISSUE TITLE
np.rot90 support

### ISSUE THREAD

**Issue by piyushchauhan** [google/jax#55]
There is not provision of rotation of tensor in `lux_numpy.py`

**Comment by mattjj** [comment]
Please reopen if you spot any issues with `np.rot90`!

**Comment by rdaems** [comment]
Hi @mattjj,

I noticed `jnp.rot90` can not be vmapped over the rotation `k` values, because it is a static arg.
However, since there are only four possible `k` values (0, 1, 2, 3), I believe this should be possible.

I managed to write this mockup:

```
import jax
import jax.numpy as jnp


def traceable_rot90(m, k=1, axes=(0, 1)):
    k %= 4
    return jnp.where(k < 2,
        jnp.where(k == 0, m, jnp.rot90(m, 1, axes=axes)),
        jnp.where(k == 2, jnp.rot90(m, 2, axes=axes), jnp.rot90(m, 3, axes=axes))
    )


m = jax.random.randint(jax.random.PRNGKey(7), (2, 4, 4), minval=0, maxval=9)
k = jnp.array([1, 2])

# this doesn't work: Static argument (index 1) of type <class 'jax.interpreters.batching.BatchTracer'> for function rot90 is non-hashable.
# jax.vmap(jnp.rot90)(m, k)

# this does work!
jax.vmap(traceable_rot90)(m, k)
```

Is this the right approach to solve this? I suppose we can remove `k` from the static args in the current implementation?
I'm willing to submit a PR if you think this is a good idea.

Best,
Rembert

**Comment by jakevdp** [comment]
One small suggestion: you could use `lax.switch` rather than nesting `jnp.where` statements. Also you'd probably want to assert that `k` is an integer type.

**Comment by jakevdp** [comment]
Thinking about it though, I'm not certain this will work in general, because the output shape depends on the value of `k`. For example, this case would be problematic:
```python
x = np.random.rand((4, 2, 3))
vmap(jnp.rot90)(x, jnp.arange(4))
```
Some batches would have shape `(2, 3)`, and some would have shape `(3, 2)`, so this operation is not possible.

**Comment by rdaems** [comment]
Hi Jake,

Thanks for the suggestions. That's a good point, I hadn't thought about non-square matrices.
Anyway, if it's of any use to anyone, here is my `lax.switch` implementation:

```
import jax
import jax.numpy as jnp
from functools import partial

def rot90_traceable(m, k=1, axes=(0, 1)):
    k %= 4
    return jax.lax.switch(k, [partial(jnp.rot90, m, k=i, axes=axes) for i in range(4)])
```

**Comment by zaccharieramzi** [comment]
@rdaems this is useful for me so thank you very much, really appreciated!
@jakevdp do you think it would make sense to have another implementation of `rot90` that takes in square matrices and allows the user to have a non-static `k` argument?
