### ISSUE TITLE
Bug with composing jax.grad and jax.remat.

### ISSUE THREAD

**Issue by jg8610** [google/jax#5507]
Hey, I am trying to compose remat and grad and am encountering an error when using activations with constants in, but run into an error which I think is a bug.

```
import jax
import jax.numpy as jnp
import numpy as np
def forward_checkpoint(params, x):
  fwd = jax.remat(lambda a, b: jnp.sum(jax.nn.relu(jnp.matmul(a, b)))) # works with sigmoid
  return jnp.sum(jax.grad(fwd, argnums=1)(params, x))

params = np.random.randn(10,128)
x = np.random.randn(128, 2)
jax.jit(jax.grad(forward_checkpoint))(params, x)
>>

UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state. Detail: Incompatible sublevel: DynamicJaxprTrace(level=0/2), (3, 1).
The tracer that caused this error was created on line <ipython-input-35-7917144d2454>:2 (<lambda>).
```

**Comment by mattjj** [comment]
Thanks for raising this, and for the nice repro.

Is this blocking your work, so that you'd benefit from a workaround?

**Comment by jg8610** [comment]
Hey,

It is blocking in the sense that it be very beneficial to be able to fit my models on a single device. It would certainly be very useful if I could find a work around!

**Comment by mattjj** [comment]
The amazing workaround I have for you is to add this line to your code:

```python
jax.nn.relu.defjvps(lambda g, ans, x: jax.lax.select(x > 0, g, np.zeros(g.shape, g.dtype)))
```

I think that should be maximally memory-efficient, though I'm not 100% sure. I'm working on fixing the underlying bug so hopefully this workaround won't be needed for long.

**Comment by mattjj** [comment]
Actually, I forgot that `np.zeros` doesn't use stride tricks:

```python
print(np.zeros((20, 20)).strides)  # (160, 8)
```

But `np.broadcast_to` will:

```python
print(np.broadcast_to(0, (20, 20)).strides)  # (0, 0)
```

So to be memory-efficient, I think this should work:

```python
jax.nn.relu.defjvps(lambda g, ans, x: jax.lax.select(x > 0, g, np.broadcast_to(np.zeros((), g.dtype), g.shape)))
```

That relies on the fact that JAX [handles NumPy constants with zero strides in a smart way](https://github.com/google/jax/blob/1fd1faa06ca12fed2332ec52b943b4a76bd99da1/jax/lib/xla_bridge.py#L409-L441).

**Comment by jg8610** [comment]
Thank you!

**Comment by mattjj** [comment]
If we use the new `remat` implementation, the code works:

```python
import jax
import jax.numpy as jnp
import numpy as np
from jax.ad_checkpoint import remat  # new remat!

def forward_checkpoint(params, x):
  fwd = remat(lambda a, b: jnp.sum(jax.nn.relu(jnp.matmul(a, b))))
  return jnp.sum(jax.grad(fwd, argnums=1)(params, x))

params = np.random.randn(10,128)
x = np.random.randn(128, 2)
jax.jit(jax.grad(forward_checkpoint))(params, x)
```

Unfortunately the new `remat` doesn't yet work with control flow primitives inside it, though that's on my todo list. Good to know it'll fix this issue too when it lands!

**Comment by mattjj** [comment]
We long ago landed the new remat (and deleted the old one), so this code should all work!
