### ISSUE TITLE
Clean up `DropVar` in `Jaxpr`

### ISSUE THREAD

**Issue by jbcdnr** [google/jax#5520]
Hello,

Is there already a utility method to remove all the equations of a `Jaxpr` that are only used for a `DropVar`. Or is it done automatically anyway?

For the context, I am writing a transform to remove the normalization inside log probabilities.
```
{ lambda  ; a.
  let b = reduce_sum[ axes=(0,) ] a
      c = div a b
      d = log c
  in (d,) }
```

I can easily edit the jaxpr equations but I am left with some `DropVar`. I started to recursively clean up the jaxpr but I wonder if there is already a utility function to do exactly this.

```
{ lambda  ; a.
  let _ = reduce_sum[ axes=(0,) ] a    <--- delete this
      b = log a
  in (b,) }
```

Thanks you!

**Comment by jakevdp** [comment]
Related issue: #4818

**Comment by jakevdp** [comment]
Is your goal here related to printing the resulting jaxprs, or ensuring computational efficiency? If it's the latter, then the XLA compiler should take care of dropping the dead code: you shouldn't have to worry about unnecessary computations being actually materialized.

**Comment by jbcdnr** [comment]
Thanks for linking the issue. 

Good to know that XLA should take care of it. I still implemented something similar to the basic DCE to simplify the computation graph.
