### ISSUE TITLE
'jaxlib.cusolver' has no attribute 'potrf'

### ISSUE THREAD

**Issue by gurgeh** [google/jax#5530]
With the latest jax (0.2.9) and jaxlib (0.1.59) from conda-forge I cannot import jax:

```
import jax
~/anaconda3/lib/python3.7/site-packages/jax/__init__.py in <module>
     91 # These submodules are separate because they are in an import cycle with
     92 # jax and rely on the names imported above.
---> 93 from . import image
     94 from . import lax
     95 from . import nn

~/anaconda3/lib/python3.7/site-packages/jax/image/__init__.py in <module>
     16 
     17 # flake8: noqa: F401
---> 18 from jax._src.image.scale import (
     19   resize,
     20   ResizeMethod,

~/anaconda3/lib/python3.7/site-packages/jax/_src/image/scale.py in <module>
     18 
     19 from jax import jit
---> 20 from jax import lax
     21 from jax import numpy as jnp
     22 import numpy as np

~/anaconda3/lib/python3.7/site-packages/jax/lax/__init__.py in <module>
    349   conv_general_dilated_patches
    350 )
--> 351 from . import linalg

~/anaconda3/lib/python3.7/site-packages/jax/lax/linalg.py in <module>
     14 
     15 # flake8: noqa: F401
---> 16 from jax._src.lax.linalg import (
     17   cholesky,
     18   cholesky_p,

~/anaconda3/lib/python3.7/site-packages/jax/_src/lax/linalg.py in <module>
    342 if cusolver is not None:
    343   xla.backend_specific_translations['gpu'][cholesky_p] = partial(
--> 344     _cholesky_cpu_gpu_translation_rule, cusolver.potrf)
    345 
    346 if rocsolver is not None:

AttributeError: module 'jaxlib.cusolver' has no attribute 'potrf'
```

It worked before the upgrade.

**Comment by mattjj** [comment]
@hawkinsp any ideas?

**Comment by hawkinsp** [comment]
We don't provide the `conda-forge` builds, the community does, but let's try to figure this out...

Is this with a CPU jaxlib or a GPU jaxlib?

If it's a CPU jaxlib (I'm pretty sure the `conda-forge` builds are CPU-only), I'm wondering if something stale is left over in your `jaxlib` installation. Can you try deleting `jaxlib`, verifying that its installed path is gone, and reinstalling it? `cusolver.py` is no longer included in `jaxlib` on CPU. So I'm wondering whether a stale version was left from a previous installation somehow.

**Comment by gurgeh** [comment]
You are correct! For some reason the jaxlib-directory contained two 1 year old files, cusolver.py and cuda_prng.py. I removed them and now it works.
Thank you both for a quick response and a great project!
