### ISSUE TITLE
experimental.enable_x64 fails for random.uniform

### ISSUE THREAD

**Issue by jakevdp** [google/jax#5532]
Short repro:
```python
from jax import random
from jax.experimental import disable_x64, enable_x64

f = lambda: random.uniform(random.PRNGKey(0), (10,), 'float64', -1, 1)
with disable_x64():
    f()
with enable_x64():
    f()
    f()  # <--- fails
```
Failure:
```pytb
Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    f()  # <--- fails
  File "tmp.py", line 4, in <lambda>
    f = lambda: random.uniform(random.PRNGKey(0), (10,), 'float64', -1, 1)
  File "/Users/vanderplas/github/google/jax/jax/_src/random.py", line 365, in uniform
    return _uniform(key, shape, dtype, minval, maxval)  # type: ignore
jax._src.traceback_util.FilteredStackTrace: RuntimeError: Invalid argument: Argument does not match host shape or layout of computation parameter 1: want s64[], got s32[]: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tmp.py", line 11, in <module>
    f()  # <--- fails
  File "tmp.py", line 4, in <lambda>
    f = lambda: random.uniform(random.PRNGKey(0), (10,), 'float64', -1, 1)
  File "/Users/vanderplas/github/google/jax/jax/_src/random.py", line 365, in uniform
    return _uniform(key, shape, dtype, minval, maxval)  # type: ignore
  File "/Users/vanderplas/github/google/jax/jax/_src/traceback_util.py", line 139, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/Users/vanderplas/github/google/jax/jax/api.py", line 401, in f_jitted
    return cpp_jitted_f(context, *args, **kwargs)
RuntimeError: Invalid argument: Argument does not match host shape or layout of computation parameter 1: want s64[], got s32[]: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).
```

**Comment by jakevdp** [comment]
This is not a problem with the python JIT path, but is a problem with the CPP jit. I think the issue is here: https://github.com/google/jax/blob/f4b5ff9d466c3f93d850efd772eee0ef03601a05/jax/api.py#L370-L372

The cpp JIT determines the X64 flag value only the first time the CPP function is called: https://github.com/tensorflow/tensorflow/blob/26bb688b0cba1e56fdee7ecde7ebde0d72ce2066/tensorflow/compiler/xla/python/jax_jit.cc#L1108
and the result is stored in a class-level constant: https://github.com/tensorflow/tensorflow/blob/26bb688b0cba1e56fdee7ecde7ebde0d72ce2066/tensorflow/compiler/xla/python/jax_jit.cc#L900

which means that calling an already-compiled function after recompiling uses the wrong value for the x64 flag.

**Comment by jblespiau** [comment]
Absolutely.

Just to check on the semantics Is the context manager expected to change the code at run time or definition time? (I strongly expect at runtime).

```
with enablex64():
  f= jax.jit(...)
  f(x) => I expect it should be with x64?
f(x) => I imagine it should be with whatever global value is define in the program?
with disablex64():
  f(x) => I imagine it should be x32?
```

Assuming this semantics, it means the C++ will need for each call to know what is the local value for enable_x64.
There are a few options:
- Call Python each time, from C++, to get the value of the flag. I dislike this approach, as the goal is to call the least python as Possible
- Pass the value from Python to C++, e.g. as the first argument, as take it from C++, and consider the rest of the arguments as the jitted function call.
- Have jax_enable_64 live in C++, and have the context manager update this value, and access this value from C++. This is what is done for DisableJit:
https://github.com/tensorflow/tensorflow/blob/26bb688b0cba1e56fdee7ecde7ebde0d72ce2066/tensorflow/compiler/xla/python/jax_jit.cc#L1141

The difficulty of that option, is that we need to move the value from the config to C++ (i.e. when we update the flags, we should set the C++ value).

**Comment by jakevdp** [comment]
> Is the context manager expected to change the code at run time or definition time? (I strongly expect at runtime).

Indeed, the semantics are that that the code is changed at run-time. For the CPP jit, we accomplish this by using the current value of the X64 flag as part of the cache key: https://github.com/google/jax/blob/f4b5ff9d466c3f93d850efd772eee0ef03601a05/jax/_src/util.py#L187-L203

> Assuming this semantics, it means the C++ will need for each call to know what is the local value for enable_x64.

This is True. Our initial attempt at that was to add the X64 flag to the context used to define the cache key: https://github.com/google/jax/blob/f4b5ff9d466c3f93d850efd772eee0ef03601a05/jax/api.py#L378-L379
But obviously this has to be threaded through more deeply.
