### ISSUE TITLE
Bug in shape checking rule when calling jax.lax.reduce_window

### ISSUE THREAD

**Issue by shaobohou** [google/jax#5536]
I stumbled on this by accident and the error message says to report it:

```
jax.lax.reduce_window(
  np.zeros((10, 28, 28, 3), dtype=np.float32), jnp.inf, lambda *args: [jax.lax.min(*args)], [1,3,3,1], [1,2,2,1], "SAME")
```

The computation argument appears to be the one triggering the bug, the plain jax.lax.min works fine.

**Comment by skye** [comment]
Thanks for reporting! FYI the issue here is that the reduction computation should return a single value, not a list. https://github.com/google/jax/pull/5547 attempts to improve the error message.
