### ISSUE TITLE
[Feature request] option to make jax.random.split(1, n) return tuple of 1 and n keys

### ISSUE THREAD

**Issue by cccntu** [google/jax#5554]
Motivation:
I am trying to create a batch of keys, and I also need to update the original key. 
Here is what I am using:
```
def get_batch_keys(key, batch_size):
    keys = jax.random.split(key, batch_size+1)
    return keys[0], keys[1:]
```
Does this make sense? It could be a flag or a new function.

**Comment by mattjj** [comment]
Thanks for the question! That looks like a good way to write it.

We probably wouldn't add this to JAX as a wrapper function or flag, but it seems like a nice short function to have in your own code if it does what you want.
