### ISSUE TITLE
JAX GPU Memory Allocation Settings ignored on Google Colab

### ISSUE THREAD

**Issue by GiacomoFrisoni** [google/jax#5555]
Hi there,
Since yesterday afternoon our team has been experiencing some JAX + Colab + GPU issues, on notebooks that were previously working perfectly.

Despite the presence of `os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"`, this configuration (even in the `!export XLA_PYTHON_CLIENT_PREALLOCATE=false` and `os.environ["XLA_PYTHON_CLIENT_MEM_FRACTION"] = ".X"` variants) is completely ignored, resulting in a 90% GPU allocation to the first JAX instruction.

We tried to reset the runtime and to switch accounts, but the problem persists and seems to be specifically related to Colab: the same code works perfectly on our machines.

Can you help us?

**Comment by skye** [comment]
Can you share a colab that has this problem? I find that `!export XLA_PYTHON_CLIENT_PREALLOCATE=false` doesn't work, but `os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"` does. (Be sure to run this before importing jax, if you're not already.)

We did update the jax + jaxlib versions in colab yesterday, so it's quite possible something changed.

**Comment by GiacomoFrisoni** [comment]
Thank you very much for the prompt reply.
By moving the `os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "false"` before the jax import, the code started working again.

**Comment by skye** [comment]
Great! We may have changed some specifics of when the GPU allocator is initialized with the latest colab update, I'm not sure. I'm gonna close this though because env vars should generally be set before importing jax.
