### ISSUE TITLE
Typed jit decorator

### ISSUE THREAD

**Issue by tetterl** [google/jax#5556]
When running mypy on my typed functions which are using the `jit` decorator I get the following error: `Untyped decorator makes function "f" untyped`

**Comment by jakevdp** [comment]
Thanks for the report – this is actually a shortcoming in mypy; see https://github.com/python/mypy/issues/3157. mypy currently lacks type annotation support for decorators like `jax.jit` that are able to decorate arbitrary functions. I'm going to close this issue because it's being tracked there.
