### ISSUE TITLE
higher order derivatives with `jvp`

### ISSUE THREAD

**Issue by f0uriest** [google/jax#5563]
I'm wondering if there is a simple way to evaluate something like
![image](https://user-images.githubusercontent.com/22567458/106347414-46574500-628c-11eb-8c23-4f41d45872b1.png)
 (ie, the second derivative of a function dotted into two tangent vectors, to return something the same size as the original function) using JVPs, in a way that is fast and memory efficient.

I've managed to do it somewhat inefficiently by first using
`jac = jax.jacfwd(f)`
then
`y = jax.jvp(jac,(x,), (dx1,))[1].dot(dx2)`
but this has the disadvantage of needing the full jacobian df/dx, which in my case is quite large expensive.

**Comment by shoyer** [comment]
I'm not sure I understand what quantity you want to calculate. Could you perhaps write it out some more explicit indexing notation? E.g., perhaps you're trying to calculate:
![image](https://user-images.githubusercontent.com/1217238/106370849-ea83cf00-6312-11eb-9937-c36cdb990b46.png)

**Comment by f0uriest** [comment]
Yes, sorry, that's it exactly

**Comment by shoyer** [comment]
If you expand this out, you'll see that you can write it in the form of two JVPs/VJPs:
![image](https://user-images.githubusercontent.com/1217238/106399227-36df1580-63cc-11eb-9777-8b46bc2e6a57.png)

You should be able to write it in terms of two calls to `jvp`/`vjp`, avoiding any explicit Jacobian matrices.

This is pretty similar to a Hessian-vector product, so I would suggest reading up on the "autodiff cookbook" for implementation suggestions: https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html#Hessian-vector-products-using-both-forward--and-reverse-mode

(The most efficient way to implement this (in terms of forward vs backwards differentiation) will depend on the dimensionality of the inputs/outputs of `f`.)

**Comment by f0uriest** [comment]
ahh ok, I got it to work. I was a bit confused for what the correct tangents are for the 2nd derivative. For anyone else looking at the same problem, this is what seems to work for me:

`dfdx = lambda x, dx: jax.jvp(fun, (x,) , (dx,))[1]
d2fdx2 = lambda dx1, dx2: jax.jvp(dfdx, (x, dx1,) , (dx2,np.zeros_like(x)) )[1]
d2fdx2(dx1,dx2)`
