### ISSUE TITLE
Better tracing of intermediate grads (tangents)

### ISSUE THREAD

**Issue by proteneer** [google/jax#557]
Is it possible to have better support for inspecting intermediate tangents of composed functions? Eg. if we have a function f(g(x)) - the chain rule for df/dx necessitates df/dg.dg/dx - it'd be super useful to able to map back to the tangents of python variables as opposed to having to try to dig through jaxpr to see what the values of the left hand side and right hand side of the chain rule is.

**Comment by proteneer** [comment]
@sschoenholz Filed issue per discussion.

**Comment by mattjj** [comment]
Thanks for bringing this up. Can you elaborate on your example? I'd like to better understand what you mean.

One thing you can do in Python is this:

```python
from jax import vjp

intermediate, g_vjp = vjp(g, x)
y, f_vjp = vjp(f, intermediate)

intermediate_cotangent = f_vjp(1.)
gradval = g_vjp(intermediate_cotangent)  # gradval = grad(lambda x: f(g(x))(x)
```

That is, if you've manually split your code into functions to be composed, you can use `vjp` (and `jvp`) to get intermediate derivative information. (You could even imagine a helper function to do this.)

But maybe you're asking something else. Maybe you want to be able to associate lines and/or variables in a jaxpr with original source lines of your program.

Any of this on the right track?

**Comment by mattjj** [comment]
cross-ref #522

**Comment by proteneer** [comment]
Your code sample is basically the gist of the problem. I have very long composed function and it's not always trivial to split and recompose (especially when you're inside loops).

``` python
import numpy as onp
import jax
import jax.numpy as np

def fog(x):
    # h(x) = (fog)(x) = (2x)^2
    g = 2*x # accumulated tangent: dg/dx = 2 
    fg = g**2 # accumulated tangent: df/dg*dg/dx = 2*2x*2 = 8x
    # in principle with fwd mode autodiff I should be able to inspect g.tangent fg.tangent
    # to actually inspect the both parts of the dual.

    # is there a way to directly inspect their values?
    print("??", g.tangent)
    print("??", fg.tangent)

    return fg

dfog_dx = jax.jacfwd(fog, argnums=(0,))
print(dfog_dx(np.array([3.0])))
```

The jaxpr is

```
-- { lambda b d f g h ;  ; a.
  let c = mul a b
      e = pow c d
      i = pow c h
      j = mul g i
      k = safe_mul f j
      l = pack e k
      (m n) = id l
      o = pack m n
      (p q) = id o
      r = reshape[ new_sizes=()
                   dimensions=None
                   old_sizes=(1,) ] q
      s = pack r
  in s }
```
I have no ability to actually read jaxpr but I suspect that the two muls (c and k) correspond to the two derivatives via fwdmode AD.

I was hoping there'd be a way to directly inspect the values inside the tangents as the code is running.

**Comment by mattjj** [comment]
Ah, thanks for explaining!

It may be that this example isn't representative of everything you're interested in, in which case the advice I'm about to provide won't always apply, but as long as you're not using `jit` or `vmap` then printing values is actually pretty easy:

```python
from jax import custom_transforms
from jax.interpreters.ad import defjvp

def print_tangent_jvp(t, x):
  print(t)
  return t
print_tangent = custom_transforms(lambda x: x)
defjvp(print_tangent.primitive, print_tangent_jvp)

def fog(x):
  g = 2*x
  fg = g**2

  print_tangent(g)
  print_tangent(fg)

  return fg

out, out_tangent = jax.jvp(fog, (3.,), (1.,))
```

Notice I didn't use `jacfwd` like you did in your example. That's because it uses `vmap` internally, meaning the tangents get abstracted to the Shaped level.

Could this kind of thing be useful? Or is it missing some important piece?

**Comment by proteneer** [comment]
Thanks this temporarily suffices. Though I'm using both jit/vmap it seems in my production code, I can live with turning them off in debug mode.

**Comment by proteneer** [comment]
Thanks guys - this works for me for now. Hoping there'd be a way to do this in the future without the existing limitations (lack of JIT and proper vmapp'd jacfwd) but for now I can't compain.

**Comment by mattjj** [comment]
Glad that the temporary fix works! For a longer-term solution, I think we should view this as #364.
