### ISSUE TITLE
Document how to integrate custom GPU kernels

### ISSUE THREAD

**Issue by eamartin** [google/jax#5582]
This GH issue comment (https://github.com/google/jax/issues/623#issuecomment-517819606) is the best documentation I could find for adding new GPU kernels. Are there any other references for adding GPU kernels that I missed while searching? Some more official documentation would be nice eventually.

I might try adding a custom GPU kernel soon. If so, I'll at least comment here if the linked steps still work and maybe open a PR with some docs. 

Further context and a thank you:
I'm considering using a custom GPU kernel because XLA profiling tools helped me determine that cublas performance is very poor for a small batched matrix multiplication. I think I could do better using a kernel generation tool like TVM or by writing a kernel myself.
Thanks for making Jax, it's awesome. I've been using neural net libs since Theano in 2013, and TF 1.x -> Jax is the biggest jump forward I've experienced. Vmap is magical.

**Comment by froystig** [comment]
@dfm recently put together a nice comprehensive [tutorial repository](https://github.com/dfm/extending-jax) on writing custom ops. I recommend taking a look!

> Thanks for making Jax, it's awesome.

Thank you for the kind words and for posting feedback!

**Comment by sharadmv** [comment]
#12632 proposes a new JAX API for custom ops. Anyone interested should give us feedback!

**Comment by dfm** [comment]
I know that it's been a minute, but there are now docs about this. In particular, JAX now has a foreign function interface. Check that out if you're still in the market: https://jax.readthedocs.io/en/latest/ffi.html
