### ISSUE TITLE
JIT for class method

### ISSUE THREAD

**Issue by ShangtongZhang** [google/jax#5595]
I want to use JIT for a class method. The following works fine:

```
class A1:
    def __init__(self):
        self.f = jax.jit(self.f)
        pass

    # @jit
    def f(self, x):
        return x

a = A1()
print(a.f(5))
```

But the following gives a type error:

```
class A1:
    def __init__(self):
        # self.f = jax.jit(self.f)
        pass

    @jit
    def f(self, x):
        return x

a = A1()
print(a.f(5))
```

`TypeError: Argument '<__main__.A1 object at 0x7fabf5a8d400>' of type <class '__main__.A1'> is not a valid JAX type.`
Could anyone help clarify the difference between the two?

**Comment by froystig** [comment]
In the first case, the expression `self.f` binds `f`'s first argument (to `self`), and evaluates to a function of only one argument (`x`), which `jax.jit` handles without issue. In the second case, `jit` wraps a function of two arguments, which is later invoked with an instance of `A1`, a type that it hasn't been taught to handle.

You might also consider the following approach:
```python
from functools import partial

class A1:
    @partial(jit, static_argnums=0)
    def f(self, x):
        return x
```

See the [jit docs](https://jax.readthedocs.io/en/latest/jax.html#jax.jit) for more on this `static_argnums` parameter.

**Comment by jakevdp** [comment]
In case anyone comes across this, there is now a section in the FAQ addressing jit compilation of methods: https://jax.readthedocs.io/en/latest/faq.html#how-to-use-jit-with-methods
