### ISSUE TITLE
Feature request: Detect the number of gpu devices

### ISSUE THREAD

**Issue by lavoiems** [google/jax#5601]
Related to issue #971, it would be useful to have functionality to detect the number of gpu devices on a machine. I am thinking of something like `torch.cuda.device_count()`: [https://pytorch.org/docs/stable/cuda.html#torch.cuda.device_count](https://pytorch.org/docs/stable/cuda.html#torch.cuda.device_count).

**Comment by tomhennigan** [comment]
`jax.local_device_count()` implements this.

**Comment by lavoiems** [comment]
Awesome! I will close the issue.
