### ISSUE TITLE
Memory leak when converting Buffer to float

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#5605]
I noticed a substantial memory leak when calling this function repeatedly and casting the outputs to `float`:

```python
@jax.jit
def loss(weights, observations, actions, rewards):
        """Actor-critic loss."""
        logits, values = network(weights, observations)
        values = jnp.append(values, jnp.sum(rewards))

        td_errors = rlax.td_lambda(
            v_tm1=values[:-1],
            r_t=rewards,
            discount_t=jnp.full_like(rewards, discount),
            v_t=values[1:],
            lambda_=jnp.array(td_lambda),
        )
        critic_loss = jnp.mean(td_errors ** 2)

        if type_ == "a2c":
            actor_loss = rlax.policy_gradient_loss(
                logits_t=logits,
                a_t=actions,
                adv_t=td_errors,
                w_t=jnp.ones(td_errors.shape[0]),
            )
        elif type_ == "supervised":
            mask = jnp.isfinite(logits)
            logprob = jax.nn.log_softmax(jnp.where(mask, logits, -1e5))
            labels = jax.nn.one_hot(actions, logits.shape[-1])
            actor_loss = -jnp.sum(labels * mask * logprob) / labels.shape[0]

        entropy_loss = jnp.mean(entropy_loss_fn(logits, jnp.ones(logits.shape[0])))
        return actor_loss, critic_loss, entropy_cost * entropy_loss

# watch memory usage climb
while True:
    loss_components = loss(weights, observations, actions, rewards)
    loss_components = [float(x) for x in loss_components]
```

I also noticed the following:

```python
>>> type(loss_components[0])
<class 'jaxlib.xla_extension.Buffer'>
```

I would have expected something like `DeviceArray` here.

The following does not leak:

```python
while True:
    loss_components = loss(weights, observations, actions, rewards)
    loss_components = [float(np.asarray(x)) for x in loss_components]
```

--- 

Do you have any intuition what might be going on? If this is a `haiku` or `rlax` issue I'm happy to re-raise there. If you don't know what's going on here let me know and I will create a smaller reproducer.

**Comment by hawkinsp** [comment]
Can you make a self-contained runnable repro? I'd like to debug this.

**Comment by dionhaefner** [comment]
There you go. Turns out this is caused by the interplay of 2 jitted functions (+ grad) and using vanilla NumPy as input.

```python
import numpy as np

import jax
import jax.numpy as jnp


@jax.jit
def loss(observations):
    out = jnp.mean(observations ** 2)
    return out, out, out


@jax.jit
def sgd_step(observations):
    total_loss = lambda *args: sum(loss(*args))
    gradients = jax.grad(total_loss)(observations)
    return gradients


observations = np.ones([10])

gradients = sgd_step(observations)

# watch memory usage climb
while True:
    loss_components = loss(gradients)
    loss_components = [float(x) for x in loss_components]
```

**Comment by hawkinsp** [comment]
It turns out that this problem is already fixed at head (by https://github.com/tensorflow/tensorflow/commit/c7e983d2c43ddc355e565a8a98d4c2dc7540e771#diff-c725219b06d97640433601ea795280b143992eb046c5a79646587546c9395966 ). I don't yet know *why* that is the case. However, you could work around it by building a jaxlib from head for the moment.

**Comment by hawkinsp** [comment]
I'm pretty sure that's the right fix. We were creating cyclic Python garbage (via non-GC able C extension objects) on CPU (only). That refactoring also fixes the bug. Releases 0.1.58 and 0.1.59 are buggy; 0.1.57 should be fine, as is anything built from head.

**Comment by dionhaefner** [comment]
Downgrading to `0.1.57` fixed this and some more leaks I hadn't isolated yet. Thanks!

**Comment by hawkinsp** [comment]
We're going to try to push 0.1.60 today, which will also fix the issue.

**Comment by hawkinsp** [comment]
I just pushed jaxlib 0.1.60, which fixes this issue. Hope that helps!
