### ISSUE TITLE
Docstring jitted function

### ISSUE THREAD

**Issue by GJBoth** [google/jax#5612]
When I use the jit function decorator on any function, I don't see the docstring of the original function, i.e.
```python
@jit
def f(x)
    """Example docstring"
    return x
```

returns as docstring (*args, **kwargs), rather than the wrapped function docstrings. I think this can be fixed using wraps (see e.g. [here](https://stackoverflow.com/questions/1782843/python-decorator-handling-docstrings)). Is there a reason this isn't used?

I think this is much more desirable behaviour for people building libraries on Jax. For example, I implemented a jitted bayesian regression algorithm. It's much more user friendly if users would see that docstring rather than the jit one.

**Comment by jakevdp** [comment]
Hi – thanks for the report. Can you help me understand exactly what it is you want to be different? For example, using jax v0.2.8, I see the following:
```python
>>> import jax
>>> print(jax.__version__)
0.2.8

>>> @jax.jit
... def f(x):
...   """the docstring of f"""
...   return x

>>> help(f)
Help on function f in module __main__:

f(x)
    the docstring of f
```
In which context are you seeing the incorrect information?

**Comment by GJBoth** [comment]
I'm on 0.2.7, but further investigation showed me that it seems to be a VSCode error: on jupyterlab I see the arguments, but with VScode it doesn't. I am using PyLance which is still experimental, but my guess is this has nothing to do with Jax. Issue can be closed for my part, thanks!

**Comment by jakevdp** [comment]
I think it’s worth exploring - VSCode may be accessing attributes that the jit wrapper doesn’t correctly set. Can you paste an example of an incorrect signature you’re seeing?

**Comment by GJBoth** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/32122273/107853657-86cfca80-6e17-11eb-86dc-fe01f1b52bd5.png)

**Comment by GJBoth** [comment]
It's definitely a pylance issue! Using jedi as my language server I the expected arguemnts.

![image](https://user-images.githubusercontent.com/32122273/107853925-dcf13d80-6e18-11eb-81e3-3ff72ef91776.png)

**Comment by jakevdp** [comment]
Thanks - looking at pylance, it seems a main feature is showing type signatures. The current JAX release doesn't correctly set `__annotations__` on wrapped objects, but that's been fixed in #5680. I strongly suspect that change will fix this issue.

**Comment by GJBoth** [comment]
Cool, I'll test it once it's merged and let you know. Thanks for the quick fix (and the good books ;-))!

**Comment by jakevdp** [comment]
Hi @GJBoth - can you upgrade to JAX 0.2.10 and check whether this is still an issue? Thanks!

**Comment by GJBoth** [comment]
I just tested - I now see the correct docstring when using the jitted function in VSCode + Pylance, so it seems to be fixed! Thanks for the quick fix!
