### ISSUE TITLE
Spurious leak checker error with custom JVP

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#5636]
I'd love to be able to use the (great-looking) new leaked tracer tools, but I'm running into a problem. After I set
```
export JAX_CHECK_TRACER_LEAKS=1
```
and then run:
```python
import jax

@jax.custom_jvp
def t(y):
    return y

def t_jvp(primals, tangents):
    assert False

t.defjvp(t_jvp)

@jax.jit
def s(y):
    return t(y)

s(0.0)
```
I unfortunately get
```
Exception: Leaked trace MainTrace(0,DynamicJaxprTrace)
```
There's possibly a deeper bug here because I'm getting leaked tracers in my code wtihout the flag, so I'm hoping this is a spurious error.

**Comment by mattjj** [comment]
Thanks for this repro! The leak checker definitely tends towards false positives right now, so it's a good a priori guess.

**Comment by mattjj** [comment]
Tricky! There are at least two issues, both pertaining to [the same line](https://github.com/google/jax/blob/0f7cc80d38822c8753e076ff6d12022d969c2dbb/jax/interpreters/partial_eval.py#L1131-L1132):
1. That `_memoize` decorator is acting like a cache, and it's a cache we forgot to disable along with the others in #5492 when the leak checker is active. It may be a simple matter of disabling that memoization; I don't think it's necessary for correctness, though I have paged this out and could be wrong about that. All the tests pass, at least!
2. That [`lambda`](https://github.com/google/jax/blob/0f7cc80d38822c8753e076ff6d12022d969c2dbb/jax/interpreters/partial_eval.py#L1132) being created on that line keeps a reference to the MainTrace instance, and it's not being cleaned up fast enough, so the leak checker spots it.

I think both may only arise in the case where the jvp rule raises an exception.

The fix to (1) is easy, as with the other caches:

```python
def _memoize(thunk):
  if core.debug_state.check_leaks:
    return thunk

  cell = []
  saved_state = core.thread_local_state.trace_state.copy()
  def memoized():
    nonlocal thunk
    if not cell:
      prev_state = core.thread_local_state.trace_state
      core.thread_local_state.trace_state = saved_state
      try:
        cell.append(thunk())
      finally:
        del thunk
        core.thread_local_state.trace_state = prev_state
    return cell[0]
  return memoized
```

 The fix to (2) I'm not sure about yet...

**Comment by mattjj** [comment]
(I can't work on this more at the moment but wanted to spend a few mins on an initial investigation!)

**Comment by NeilGirdhar** [comment]
Thanks for looking into this!  Just so you know, I did find the problem (I was jusing `jax.jit` instead of `hk.jit`), so this isn't holding me up anymore.  Hope the MWE is useful to you though :)

**Comment by mattjj** [comment]
Woo, that's great to hear! Sounds like a common issue as well. We're working with the Haiku folks to improve things.

cc @LenaMartens just to bring this leak checker thread to her attention

**Comment by NeilGirdhar** [comment]
@mattjj That's great to hear!  Just to keep you informed, there's a beautiful solution to my problem here https://github.com/google/jax/pull/4117.  I'm just now trying to code up the Haiku side of things to get it to work locally.
