### ISSUE TITLE
jax.devices() behaves unintuitively

### ISSUE THREAD

**Issue by mganahl** [google/jax#5638]
Hi! I noticed some unexpected (?) behaviour in the following code:
```python 
import jax
from jax.config import config
config.update("jax_backend_target", 'grpc://some endpoint:8470')
config.update("jax_xla_backend", 'tpu_driver')
print(jax.devices('cpu')) #prints tpu devices instead of cpu
``` 
I can get the expected behaviour if I do 

```python 
import jax
print(jax.devices('cpu')) #prints cpu devices 
from jax.config import config
config.update("jax_backend_target", 'grpc://11.111.11.1118470')
config.update("jax_xla_backend", 'tpu_driver')
print(jax.devices('cpu')) #now prints cpu devices
print(jax.devices('tpu')) #now prints tpu devices
``` 
I think this may be related the caching of `jax.lib.xla_bridge.get_backend()`. Not sure if this is expected behaviour or a bug. 

I noticed this because I was trying `jit` a few smaller functions on the host vm cpu during a larger TPU computation . I tried using the `backend=cpu` argument and `device_put`, but was unable to obtain the desired behaviour. In the end the only thing that seemed to work was to clear the cache of `get_backend()` reconfigure `jax.config` to cpu.

**Comment by mganahl** [comment]
@jacksonwb

**Comment by skye** [comment]
Aren't you two already using the new Cloud TPU alpha program? That doesn't have this problem :)

This is indeed a bug in the `tpu_driver` client. Given that we're focusing our efforts on the new Cloud TPU architecture and you have a workaround, we probably won't prioritize fixing this. Please let me know if I'm underestimating the impact of this though and we can reconsider!

**Comment by jacksonwb** [comment]
We are using the new Cloud TPU alpha program, but still have some applications on the old Cloud TPU setup due to requirements for GKE support. 

Currently we have a workaround involving calls to `jax.lib.xla_bridge.get_backend.cache_clear()` when switching from TPU to CPU jitting, which seems to be working, but I'm not sure what other unintended consequences this may be creating.

**Comment by skye** [comment]
I think #5751 will fix this, but I didn't verify on Cloud TPU (only on Google-internal TPU). Give it a try? You'll have to run jax from github head.
