### ISSUE TITLE
jax.numpy.full((2,2),[1,2]) fails

### ISSUE THREAD

**Issue by scnlong** [google/jax#5645]
The last example at https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.full.html

`jax.numpy.full((2,2),[1,2])`

couldn't pass. It gives 

`TypeError: full must be called with scalar fill_value, got fill_value.shape (2,).`

**Comment by jakevdp** [comment]
Thanks for the report! We’ll try to get non-scalar inputs implemented soon.
