### ISSUE TITLE
Does the expm matrix function support sparse matrix? 

### ISSUE THREAD

**Issue by JiahaoYao** [google/jax#5651]
Just curious about the matrix function implementation. Does the `expm` matrix function support sparse matrix? or in the near future? (i.e.~ is there any support for `sparse.linalg`.)

**Comment by jakevdp** [comment]
Thanks for the question! There is ongoing work in this area; #1531 tracks the current progress.

**Comment by JiahaoYao** [comment]
Nice, thanks for the quick reply! Also, willing to contribute if possible.
