### ISSUE TITLE
Negative axis support for xmap

### ISSUE THREAD

**Issue by Conchylicultor** [google/jax#5652]
The following correctly inverse the axes:
```python
xmap(
    lambda x: x,
    in_axes=[['batch', ...]],
    out_axes={1: 'batch'},
)(jnp.zeros((2, 5)) # shape=(5, 2)
```

But this fails:

```python
xmap(
    lambda x: x,
    in_axes=[['batch', ...]],
    out_axes={-1: 'batch'},  # << Use -1 as axis
)(jnp.zeros((2, 5))
# TypeError: reshape total size must be unchanged, got new_sizes (5, 1, 10, 2) for shape (5, 1, 2).
```
This feels inconsistent with numpy. It would be very natural I think to support negative values in axis.

**Comment by apaszke** [comment]
There's no negative axis support, but at least I've already improved the error message by the time this issue was opened (see [here](https://github.com/google/jax/commit/be9c58ae21a13ed2e0a0930cda28211084494c58#diff-3bc29ffad9c4a0cfc0acaabe3136231f5c0c87bf5bf85f3e2f17a2d5837ee453R208)). 😄

**Comment by apaszke** [comment]
xmap was removed from JAX, so this is obsolete
