### ISSUE TITLE
jaxlib (0.1.60) depends on numpy (>=1.12,<1.20)

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#5656]
This issue is just for tracking jaxlib's support for numpy 1.20. Numpy 1.20 added type annotations, which are extremely useful.  It would be nice to have it working with Jax if possible.  Is this just untested, or is it actually uncompatible?

**Comment by hawkinsp** [comment]
As you may have noticed, we've fixed this already; it will just need a new release.

As it happens jaxlib 0.1.60 probably works with NumPy 1.20 already, so you can try installing it and ignoring the constraint.

**Comment by NeilGirdhar** [comment]
@hawkinsp I hadn't noticed, so thanks for letting me know!
