### ISSUE TITLE
Recipe on multi-node training with JAX

### ISSUE THREAD

**Issue by connection-on-fiber-bundles** [google/jax#5667]
Hi there. First of all, thanks a lot for making JAX such a great framework. It's awesome.

Actually it's only awesome when we only do training on a single node. To my knowledge, the multi-node support is still missing for now. 10 months ago, @hawkinsp and @gnecula mentioned that there's already some experimental support for multi-GPU training across multiple devices in https://github.com/google/jax/issues/2731 and https://github.com/google/jax/issues/2837 respectively. However, there's no description how we can achieve that, in a hacky way or not. I understand that experimental support could be brittle and/or rough. Just feeling adventurous and want to try out. Could someone share some idea on the multi-node training recipe with JAX?

Also what is the priority and roadmap of fully supporting multi-node training with JAX? From the fact that no one's responding to https://github.com/google/jax/issues/2731 any more, I assume it's not of high priority and not likely coming in the near future? Thanks again!

**Comment by hawkinsp** [comment]
Closing as duplicate of #2731
