### ISSUE TITLE
JAX TypeError disagrees with documentation?

### ISSUE THREAD

**Issue by dfarmer** [google/jax#5706]
The documentation for stable (and latest of course), https://jax.readthedocs.io/en/stable/_autosummary/jax.numpy.array.html says:

```
>>> x = np.array([(1,2),(3,4)],dtype=[('a','<i4'),('b','<i4')])
>>> x['a']
array([1, 3])
```

but when I try to do that in my local jupyterlab notebook (with JAX v0.2.9)  I get 

TypeError: JAX only supports number and bool dtypes, got dtype [('a', '<i4'), ('b', '<i4')] in array

Is the documentation wrong?

**Comment by mattjj** [comment]
The documentation has lied to you!

JAX docstrings include the original NumPy docstrings. There's a critical sentence in there, "Original docstring below.", which indicates that it's just a reproduction of the NumPy docstring. Perhaps it should be clearer that the NumPy docstring may describe features that aren't available in JAX...

@shoyer @jakevdp any ideas?

**Comment by hawkinsp** [comment]
I think in some cases where our behavior differs in significant ways, we should perhaps not simply reference the numpy strings. In this case I think `jnp.array` is significantly different that we should consider it...

**Comment by dfarmer** [comment]
I'm not sure how much work it would be but even if y'all could just get the numpy doctests to actually run instead of having the copy-pasted version then it would at least be honest (your documentation might end up riddled with exceptions -- I don't know). 

Anyway, thanks for clearing that up -- that's useful for interpreting anything I reference on there.

**Comment by jakevdp** [comment]
Fixed by https://github.com/google/jax/pull/5945; docstrings now remove all examples.
