### ISSUE TITLE
jitting jax.scipy.linalg.solve 

### ISSUE THREAD

**Issue by hanrach** [google/jax#5722]
Hi everyone,

According to the documentation of `jax.scipy.linalg.solve`, the function is implemented in `lax` backend, so it is built with XLA operations. But it also ultimately calls routines like ?GESV from LAPACK. My question is that when we jit `jax.scipy.linalg.solve`, does it only jit the preprocessing operations before we finally call a routine from LAPACK? What operations are being jit compiled? The question arises because it seems unlikely that jit will affect the speed of the black box solver that is not built with XLA operations.

**Comment by quattro** [comment]
Note that Jax documentations lists `Original docstring below`, which reflects the documentation from the original SciPy source and likely does not reflect on what Jax/XLA does.

**Comment by froystig** [comment]
Currently, `jax.scipy.linalg.solve` is a `jit`-compiled routine comprising several `lax` primitive operations, including `lax.linalg.cholesky` or `lax.linalg.lu`. We lower either of these two to XLA differently depending on the target device: see [here for Cholesky](https://github.com/google/jax/blob/f5c0951124d8c5c38dcd763371c6f6a1e56bb55e/jax/_src/lax/linalg.py#L330-L348) and [here for LU](https://github.com/google/jax/blob/f5c0951124d8c5c38dcd763371c6f6a1e56bb55e/jax/_src/lax/linalg.py#L891-L903). On CPU, we emit an XLA [CustomCall](https://www.tensorflow.org/xla/operation_semantics#customcall) operation that indeed calls into LAPACK.

You are correct that XLA won't optimize through that custom call to LAPACK in the way that it optimizes XLA HLO in line.

**Comment by hawkinsp** [comment]
Closing because @froystig has answered this question. Feel free to reopen if there's another action for us to take here or more to discuss!

**Comment by hanrach** [comment]
Another question regarding jax.scipy.linalg.solve: the timing results on CPU shows that jax.scipy.linalg.solve is slower than np.linalg.solve although I expected jax to be faster. Is this an expected behaviour? Why?

```
import jax
import jax.numpy as jnp
import numpy as np
import scipy
import matplotlib.pyplot as plt

m = 100; n=100;
J=scipy.sparse.random(m, n, density=0.02) + 0.5*scipy.sparse.identity(100)
Jdense=J.todense()
f=np.random.rand(100,1)

```

```
 %timeit jax.scipy.linalg.solve(Jdense,f)
166 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

```
%timeit np.linalg.solve(Jdense,f)
105 µs ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

```

**Comment by jakevdp** [comment]
> Another question regarding jax.scipy.linalg.solve: the timing results on CPU shows that jax.scipy.linalg.solve is slower than np.linalg.solve although I expected jax to be faster. Is this an expected behaviour? Why?

On CPU backends, an operation like this is basically just being pushed to whatever LAPACK the jaxlib binary is built against.  JAX also has some small constant dispatch overhead that Numpy does not. The difference in timing is probably due to some combination of these effects; you might check the timing for a larger problem (say 1000 x 1000) and see what the difference is there.

Also, for micro-benchmarks like these don't forget to call `.block_until_ready()` to avoid JAX's asynchronous dispatch confounding your results; see https://jax.readthedocs.io/en/latest/async_dispatch.html#asynchronous-dispatch

**Comment by hanrach** [comment]
@jakevdp Thanks! Indeed for a larger 1000 X 1000 matrix, I see that jax is faster:

```
%timeit jax.scipy.linalg.solve(Jdense,f).block_until_ready()
17.1 ms ± 3.66 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)

```
```
%timeit np.linalg.solve(Jdense,f)
21.1 ms ± 5.9 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

**Comment by hanrach** [comment]
> Currently, `jax.scipy.linalg.solve` is a `jit`-compiled routine comprising several `lax` primitive operations, including `lax.linalg.cholesky` or `lax.linalg.lu`. We lower either of these two to XLA differently depending on the target device: see [here for Cholesky](https://github.com/google/jax/blob/f5c0951124d8c5c38dcd763371c6f6a1e56bb55e/jax/_src/lax/linalg.py#L330-L348) and [here for LU](https://github.com/google/jax/blob/f5c0951124d8c5c38dcd763371c6f6a1e56bb55e/jax/_src/lax/linalg.py#L891-L903). On CPU, we emit an XLA [CustomCall](https://www.tensorflow.org/xla/operation_semantics#customcall) operation that indeed calls into LAPACK.
> 
> You are correct that XLA won't optimize through that custom call to LAPACK in the way that it optimizes XLA HLO in line.

I think I'm still missing something. What parts of the linear algebra are accelerated if the `lax` backend eventually calls into LAPACK for the lin alg routine? In CPU, if lax.linalg.lu is lowered to XLA then XLA calls into LAPACK, is it these calls that are being optimized through `jit`? Are there any linear algebra implemented in `lax` primitive operations that is being optimized?

**Comment by froystig** [comment]
The entire `solve` routine is sent to XLA for compilation. Only the `cholesky` or `lu` step inside of `solve` corresponds to a LAPACK call. The other operations surrounding that are maybe other additions, multiplications, broadcasts, etc.

XLA tries to optimize all of `solve` end-to-end (e.g. fusing operations together to create fewer memory operations), but it contains one "call into LAPACK LU" operation that is opaque to XLA. We would not expect that call to participate in fusion optimizations, for example.
