### ISSUE TITLE
np.nansum returns nan

### ISSUE THREAD

**Issue by adamhaber** [google/jax#573]
Hi,

I'm trying to compute the Kullback Leibler divergence between two distributions P and Q: `kl = np.nansum(p*np.log2(p/q))`
The point of using `np.nansum` is to enforce the convention that 0*log(0)=0. However, this expression returns nan if p contains zeros:
```
p = np.array([0,0.5,0.5])
q = np.array([1/3,1/3,1/3])
np.nansum(p*np.log2(p/q))
array(nan, dtype=float32)
```
Is there something I'm doing wrong here, or is `np.nansum` not implemented (despite #70 )?

**Comment by mattjj** [comment]
My guess is this is #276. Does that sound likely?

My understanding is that we're waiting for upstream changes to XLA and/or LLVM to fix #276.

**Comment by hawkinsp** [comment]
And if it is #276, the workaround is to set an environment variable to disable fast math on CPU.

**Comment by adamhaber** [comment]
I've added:
```
import os
os.environ["XLA_FLAGS"]="--xla_cpu_enable_fast_math=false"
```
And it solved the problem. Thanks!

**Comment by mattjj** [comment]
That's great to hear! Though keep in mind it will de-optimize a lot of code and make things slower. The XLA team is working on a better solution.
