### ISSUE TITLE
`pmap` can't deal with dicts in `out_axes`

### ISSUE THREAD

**Issue by mhauru** [google/jax#5737]
Is there a reason why `pmap` can handle dictonaries in `in_axes` but not in `out_axes`? For instance, this produces an `unhashable type: 'dict'` error:
```
import functools
import jax
import jax.numpy as jnp

@functools.partial(
  jax.pmap,
  in_axes=({"A": 1},),  # This is okay
  out_axes=({"A": 1},), # This is not okay
)
def f(d):
  return d

D = len(jax.devices())
A = jnp.zeros((D, D))
B = f({"A": A})
```
`vmap` is fine with this use of `out_axes` (although it's a bit fuzzy and inconsistent with whether it wants the `in/out_axes` wrapped in singleton tuples or not).

**Comment by apaszke** [comment]
This seems to work now (once the singleton tuple is eliminated from `out_axes`, because that's a legit error). I think this was fixed in #6526.
