### ISSUE TITLE
Building with custom cuda/cudnn paths

### ISSUE THREAD

**Issue by blackwer** [google/jax#5743]
Compiling with custom paths to CUDA/CUDNN currently (commit a6a8107) does not work, since tensorflow can't find the paths as described. This is seemingly because the tensorflow build flags `CUDA_TOOLKIT_PATH` and `CUDNN_INSTALL_PATH` are marked as deprecated, but currently don't work at all. I was able to circumvent this by putting, in `build.py:write_bazelrc`, 
```python3
    tf_cuda_paths = ','.join(filter(None, (cuda_toolkit_path, cudnn_install_path)))
    if tf_cuda_paths:
      f.write("build --action_env TF_CUDA_PATHS=\"{tf_cuda_paths}\"\n"
              .format(tf_cuda_paths=tf_cuda_paths))
```
which gives the intended behavior. Sorry for not submitting this as a proper PR. I can if requested, but I'm tired and it's my EOD :)

**Comment by zhangqiaorjc** [comment]
@hawkinsp  should we add this?

**Comment by cloudhan** [comment]
this can be closed by [this change](https://github.com/google/jax/commit/2d321c26e6d96c6b4e77ada096a07c209c98fcd4#diff-4a0bef7f4b92e71c6bfdea2a3cc9aeb7335a73541de5c14fbef1a5d6004e852e)
