### ISSUE TITLE
set tree_map = tree_multimap

### ISSUE THREAD

**Issue by mattjj** [google/jax#5746]
Some users suggested that we should just set `tree_map = tree_multimap` in jax.tree_util. Seems reasonable! We can't think of a reason not to, so let's try it and see if anything breaks.

**Comment by jakevdp** [comment]
Done in #6585

**Comment by carlosgmartin** [comment]
@jakevdp @mattjj Since these functions have been unified, should [the docs](https://jax.readthedocs.io/en/latest/jax-101/05.1-pytrees.html) be updated to reference only `tree_map` to avoid confusion? Perhaps a deprecation warning should be added to `tree_multimap`?

**Comment by jakevdp** [comment]
Yes, those are good ideas!

**Comment by jakevdp** [comment]
Remaining TODO: remove deprecated `tree_multimap` function after July 1, 2022, in accordance with the [API Compatibility Policy](https://jax.readthedocs.io/en/latest/api_compatibility.html).
