### ISSUE TITLE
TypeError: Abstract value passed to `bool`

### ISSUE THREAD

**Issue by adamhaber** [google/jax#575]
Hi,

I'm trying to sample from an exponential distribution using Metropolis-Hasting sampling, and I'm getting the error above when I'm trying to jit the sampling function.
This is the code I'm trying to run is:
```
N = 10

marg_1 = lambda i,x:x[i]
marg_2 = lambda i,j,x:x[i]*x[j]

marg_1s = [jit(partial(marg_1,i)) for i in range(N)]
marg_2s = [jit(partial(marg_2,i,j)) for i,j in list(it.combinations(range(N),r=2))]
funcs = marg_1s+marg_2s

@jit
def calc_e(factors,word):
    return np.sum([factor*func(word) for factor,func in zip(factors,funcs)])

@jit
def sample(factors,N=10,seed=0,n_samps=100):
    key = random.PRNGKey(seed)
    key, subkey = random.split(key)
    
    state = random.randint(subkey,minval=0,maxval=2, shape=(N,))
    all_states = []
    
    for _ in range(n_samps):
        all_states.append(state)
        for i in range(N):
            #flip sign
            state_flipped = index_update(state,i,1-state[i])
            #calc energy difference
            dE = calc_e(factors,state_flipped)-calc_e(factors,state)
            if dE < 0:  
                state = state_flipped
            else:
                key, subkey = random.split(key)
                rand=random.uniform(subkey,shape=(1,))
                if rand < np.exp(-dE):
                    state = state_flipped
    return all_states
```
And I'm getting the following error message:
```
TypeError: Abstract value passed to `bool`, which requires a concrete value. The function to be transformed can't be traced at the required level of abstraction. If using `jit`, try using `static_argnums` or applying `jit` to smaller subfunctions instead.
```
The full trace shows the error is in the `if dE < 0` line. I've read #480  and #196 but wasn't able to understand how to solve the problem (or if it's even solvable).  Is there anything I can do to solve this?

**Comment by mattjj** [comment]
My guess is that using `np.where` here in place of the conditionals is a good strategy. So maybe something like (untested)

```python
key, subkey = random.split(key)
accept = (dE < 0) | (random.uniform(subkey, ()) < np.exp(-dE))
state = np.where(accept, state_flipped, state)
```

That will compute both sides of the conditionals and throw one side away. (In principle XLA could be lazy and only evaluate one side, but in practice it's not.) For this simple part of the calculation, that's not going to waste much effort, especially on a parallel machine.

This next part is just academic. If you ever wanted to stage out a conditional like a Python `if`, where only one side is evaluated, you'd have to use [`lax.cond`](https://jax.readthedocs.io/en/latest/jax.lax.html#jax.lax.cond) here instead of the Python `if` construct. The reason is that JAX needs to trace both sides of the conditional to compile it (because the boolean doesn't have a concrete value while tracing), but our simple tracing technique doesn't let us do that easily on Python control flow. However, I expect `lax.cond` to have overheads relative to `np.where` because it can probably foil a lot of XLA's optimizations.

A third alternative would be not to compile this whole function, but instead to compile sub-functions like `calc_e`, and just stay in regular Python for the `sample` function. But that's probably not a good fit for this kind of computation; unless your energy calculation is very expensive to compute, you probably want to stage the whole `sample` function out of Python.

**Comment by adamhaber** [comment]
Thanks @mattjj for the detailed response!

I've tried using the code you suggested, and it indeed solved the problem reported above; however, sampling is very very slow - it takes me > 20 seconds to produce tens of samples; this is order of magnitude slower than a pure-Python version. Is this an expected behavior? I've used snakeviz to profile the following cell:

```
%%snakeviz

@jit
def sample(factors,seed=0,n_samps=20):
    key = random.PRNGKey(seed)
    key, subkey = random.split(key)
    state = random.randint(subkey,minval=0,maxval=2, shape=(N,))
    
    all_states = []
    for _ in range(n_samps):
        all_states.append(state)
        for i in range(state.size):
            #flip sign
            state_flipped = index_update(state,i,1-state[i])
            #calc energy difference
            dE = calc_e(factors,state_flipped)-calc_e(factors,state)
            key, subkey = random.split(key)
            accept = (dE < 0) | (random.uniform(subkey, ()) < np.exp(-dE))
            state = np.where(accept, state_flipped, state)
    return all_states

sample(factors)
```
This is the profiling output:

ncalls | tottime | percall | cumtime | percall | filename:lineno(function)
-- | -- | -- | -- | -- | --
29 | 4.877 | 0.1682 | 4.877 | 0.1682 | ~:0(built-in method _pywrap_xla.Computation_Compile)
113727/107234 | 0.3531 | 3.293e-06 | 1.071 | 9.986e-06 | util.py:38(safe_map)
2711 | 0.16 | 5.901e-05 | 0.1735 | 6.398e-05 | ~:0(built-in method _pywrap_xla.LocalExecutable_Execute)
326954/312810 | 0.1347 | 4.305e-07 | 0.1572 | 5.025e-07 | ~:0(built-in method builtins.isinstance)
1609/29 | 0.1281 | 0.004417 | 1.356 | 0.04676 | xla.py:145(jaxpr_computation)
28127 | 0.07463 | 2.653e-06 | 0.1224 | 4.35e-06 | xla_client.py:504(__init__)
28087 | 0.07277 | 2.591e-06 | 0.2695 | 9.595e-06 | xla_client.py:485(array_shape)
187890 | 0.06856 | 3.649e-07 | 0.06856 | 3.649e-07 | ~:0(built-in method builtins.len)
14434 | 0.06807 | 4.716e-06 | 0.1347 | 9.332e-06 | linear_util.py:165(hashable_payload)
44633 | 0.06671 | 1.495e-06 | 0.1846 | 4.135e-06 | core.py:267(__getattr__)
68117 | 0.06142 | 9.017e-07 | 0.1404 | 2.061e-06 | partial_eval.py:202(aval)

(I've truncated the profiling trace since the first line is where most of the time is spent anyway)

It seems like the compilation part (which I admittedly know very little about) takes most of the time. Calling the `sample` function with a different seed seems to require re-compilation. If I understand it correctly, it means each time I'm planning to sample from the distribution using a different seed/initial state, the function will be recompiled. Since my use case involved hundreds or thousands of such calls, this sounds like it makes it impracticable. Is there any way to resolve this?

Somewhat unrelated - I find this topic super interesting, but I don't have much prior knowledge in all of this. Is there any good tutorial somewhere (other than the jax/xla github pages) where I can learn more about the subject?

**Comment by mattjj** [comment]
There's certainly too much recompilation going on. Can you provide a full repro?

**Comment by adamhaber** [comment]
Sure. Here's the full code:
```
%load_ext snakeviz

import jax.numpy as np
import jax.random as random
from jax import jit
from jax.ops import index_update
import numpy as onp
from functools import partial
import itertools as it

N = 4

marg_1 = lambda i,x:x[i]
marg_2 = lambda i,j,x:x[i]*x[j]

marg_1s = [jit(partial(marg_1,i)) for i in range(N)]
marg_2s = [jit(partial(marg_2,i,j)) for i,j in list(it.combinations(range(N),r=2))]
funcs = marg_1s+marg_2s

def calc_e(factors,word):
    return np.sum([factor*func(word) for factor,func in zip(factors,funcs)])

factors = np.array(onp.random.randn(len(funcs))*0.01)

%%snakeviz

@jit
def sample(factors,seed=0,n_samps=20):
    key = random.PRNGKey(seed)
    key, subkey = random.split(key)
    state = random.randint(subkey,minval=0,maxval=2, shape=(N,))
    
    all_states = []
    for _ in range(n_samps):
        all_states.append(state)
        for i in range(state.size):
            #flip sign
            state_flipped = index_update(state,i,1-state[i])
            #calc energy difference
            dE = calc_e(factors,state_flipped)-calc_e(factors,state)
            key, subkey = random.split(key)
            accept = (dE < 0) | (random.uniform(subkey, ()) < np.exp(-dE))
            state = np.where(accept, state_flipped, state)
    return all_states

sample(factors)
```

**Comment by adamhaber** [comment]
Small update, in case it helps focusing on the problem - all the above was on CPU mode; I finally installed JAX on a machine with a GPU and reproduced the same behavior (tens of seconds for tens of samples).

**Comment by mattjj** [comment]
I failed to follow up on this in a timely manner :/

@adamhaber is it still useful to you for me to dig in now, or should we close this issue?

**Comment by adamhaber** [comment]
Thanks for coming back to this! 

I was able to solve this by using `fori_loop` and taking the RNG part out of the loop; [Here's](https://github.com/adamhaber/JaxEnt/blob/5191c99e58cc448bcf550dcb4416b05b0475fb84/jaxent/jaxent.py#L162) the current implementation. I'm still trying to get the sampler run faster - I'm using this to learn the parameters of energy-based models, which require generating samples in each SGD step, so every speedup counts. Currently I'm trying to adjust @rlouf latest implementation to binary multivariate data. I can share the attempt here in case anyone's interested; l'll close this in a couple of days if nothing interesting comes up.

**Comment by adamhaber** [comment]
Hi @mattjj! I've went over @rlouf's implementation, and slightly adjusted it to the binary sampling case (hopefully in a reasonable way):

```python

@partial(jax.jit, static_argnums=(1,))
def rw_metropolis_kernel(rng_key, logpdf, position, log_prob, i):
    key1, key2 = jax.random.split(rng_key)
    proposal = index_update(position, i%N, 1-position[i%N])
    proposal_log_prob = logpdf(proposal)

    log_uniform = np.log(jax.random.uniform(key2))
    do_accept = log_uniform < proposal_log_prob - log_prob

    position = np.where(do_accept, proposal, position)
    log_prob = np.where(do_accept, proposal_log_prob, log_prob)
    return position, log_prob


@partial(jax.jit, static_argnums=(1, 2))
def rw_metropolis_sampler(rng_key, n_samples, logpdf, initial_position):
    def mh_update(i, state):
        key, position, log_prob = state
        _, key = jax.random.split(key)
        new_position, new_log_prob = rw_metropolis_kernel(key, logpdf, position, log_prob, i)
        return (key, new_position, new_log_prob)

    logp = logpdf(initial_position)
    rng_key, position, log_prob = jax.lax.fori_loop(0, n_samples, mh_update, (rng_key, initial_position, logp))
    return position

n_chains = 100000
n_dim = 50
rng_key = jax.random.PRNGKey(1)
rng_keys = jax.random.split(rng_key, n_chains) 
initial_position = (jax.random.uniform(rng_key,shape=(n_dim, n_chains))>0.5).astype(int)  

run_mcmc = jax.vmap(rw_metropolis_sampler, in_axes=(0, None, None, 1),
                    out_axes=0)

factors = np.sort((jax.random.normal(rng_key, shape=m.factors.shape)*0.03))

%time positions_comp = run_mcmc(rng_keys, n_samples, logpdf, initial_position).block_until_ready()
```
This is roughly as fast as my previous implementation (~5 sec for 100000 samples from an N=50 all-to-all Ising model); This is still ~15 times slower than the C++ implementation I'm trying to replace, but perhaps that's unavoidable... 
Is there anything obvious in the above code that can be further optimised? Perhaps there's a better way (batched/pre-generated) to handle random number generation?

**Comment by rlouf** [comment]
I suspect the performance hit is due to the `index_update` in the kernel. I'll have a look over the weekend.

**Comment by joaogui1** [comment]
@adamhaber  It seems generating keys in batches can give a significant performance improvement #1421 (around 2x to 3x in the reported issue)

**Comment by mattjj** [comment]
I'm going to close this issue because it's pretty old. We're still working on improvements to PRNG performance on some backends, but there are other open issues tracking that.
