### ISSUE TITLE
Nested `pmap`s hang indefinitely

### ISSUE THREAD

**Issue by mhauru** [google/jax#5757]
This bit of code just hangs for all eternity:
```
import jax
import jax.numpy as jnp

f = jax.pmap(jax.pmap(lambda x: x, in_axes=1, out_axes=0), in_axes=0, out_axes=0)
A = jnp.ones((2, 4, 3))
f(A)
```
Something about that combination of `in_axes`, `out_axes`, and dimensions triggers it, changing any of them in most ways possible results in sensible behavior. I'm running this on a TPU donut on colab.

**Comment by mattjj** [comment]
Hrm, it seems to work on CPU at HEAD (using the latest pypi jaxlib).

Is this Google-internal colab, or external colab?

**Comment by mhauru** [comment]
I'm seeing this on both sandbox and corp colab.

**Comment by jekbradbury** [comment]
This is probably a TPU-only bug; there's a hanging all-reduce on replica groups `{{0,1,2},{3,4,5}}`, meaning both cores of chips 0, 1, and 2. (I think in general XLA collective operations over non-rectangular subsets of TPU chips are poorly tested).

**Comment by jekbradbury** [comment]
We can potentially file an internal bug?
