### ISSUE TITLE
JAX vs TensorFlow perfomance

### ISSUE THREAD

**Issue by qo4on** [google/jax#5767]
Can you share a notebook with time to accuracy comparison for both frameworks on TPU?

**Comment by mattjj** [comment]
Thanks for the question! But that sounds out-of-scope for what we work on.

**Comment by hawkinsp** [comment]
But we don't mind pointing you to things like table 1 of:
https://cloud.google.com/blog/products/ai-machine-learning/google-breaks-ai-performance-records-in-mlperf-with-worlds-fastest-training-supercomputer

So, suffice to say: you can get excellent performance out of JAX in the right circumstances. But performance is a very complicated question with many aspects, and one can't easily summarize it in a single notebook.

**Comment by qo4on** [comment]
> But we don't mind pointing you to things like table 1 of:
> https://cloud.google.com/blog/products/ai-machine-learning/google-breaks-ai-performance-records-in-mlperf-with-worlds-fastest-training-supercomputer
> 
> So, suffice to say: you can get excellent performance out of JAX in the right circumstances. But performance is a very complicated question with many aspects, and one can't easily summarize it in a single notebook.

Thank you. I've already read this article. That's why I would like to know how you got these results.

**Comment by hawkinsp** [comment]
The implementations are all public, see: 
https://github.com/mlperf/training_results_v0.7/tree/master/Google/benchmarks
although those particular results were run on top of Google-internal infrastructure.

If you have specific questions, we can try to answer them.
