### ISSUE TITLE
Inconsistent return type from jax.numpy.linalg.norm

### ISSUE THREAD

**Issue by lukepfister** [google/jax#5780]
With `jax=0.2.9, jaxlib=0.1.61` and `jaxlib=0.1.60`, the return type of `jax.numpy.linalg.norm` is inconsistent.  

The evaluation of `norm` returns a `_DeviceArray`.  But any subsequent evaluations return a `Buffer`:

```python
import jax
from jax.numpy.linalg import norm

key = jax.random.PRNGKey(0)
x = jax.random.normal(key, (32, 32))

print(type(norm(x)))  #  <class 'jax.interpreters.xla._DeviceArray'>
print(type(norm(x)))  #  <class 'jax.interpreters.xla.Buffer'>
print(type(norm(x)))  #  <class 'jax.interpreters.xla.Buffer'>
```
Note that this doesn't happen with `sum`:
```python 

print(type(jax.numpy.sum(x)))  #  <class 'jax.interpreters.xla._DeviceArray'>
print(type(jax.numpy.sum(x)))  #  <class 'jax.interpreters.xla._DeviceArray'>
print(type(jax.numpy.sum(x)))  #  <class 'jax.interpreters.xla._DeviceArray'>
```

This behavior is not present with `jax=0.26, jaxlib=0.1.57`.

**Comment by hawkinsp** [comment]
The difference between `Buffer` and `_DeviceArray` is intended to be an internal difference (one is generated by Python code, the other by C++, and we are gradually moving some logic into C++). Can you say more about why it affects you? It shouldn't change anything other than the type. Note both are instances of `DeviceArray`, which is a superclass.

**Comment by lukepfister** [comment]
I noticed it while debugging a different issue.  This wasn't my real problem, just thought the variable nature of the return type was odd.  Feel free to close if this behavior is expected.
