### ISSUE TITLE
host_callback buffer size

### ISSUE THREAD

**Issue by sbodenstein** [google/jax#5782]
In the [host_callback documentation](https://jax.readthedocs.io/en/latest/jax.experimental.host_callback.html?highlight=outfeed#low-level-details-and-debugging), it states
> The runtime maintains a buffer of configurable size. When the buffer is full, all the receiving threads are paused which eventually pauses the computation on devices

But its never documented how to configure the buffer size, or what the default is. Looking at the source, it doesn't seem that this parameter can be configured (see [initialize_outfeed_receiver](https://github.com/google/jax/blob/e58e45ef9fe3cfbe362bee2da0ffd773c9928cd5/jax/experimental/host_callback.py#L1493) which is called without the `max_callback_queue_size_bytes` argument).

Should this be configurable? Or is the documentation stale?

**Comment by gnecula** [comment]
You are right, the C++ code is configurable but there is no Python API for this. I will add one. 

I am curious, how are you using host_callback; are there particular circumstances that require a very large buffer?

**Comment by sbodenstein** [comment]
Sorry I never replied! No, I haven't run into such a circumstance yet.
