### ISSUE TITLE
[feature request] NotImplementedError: jax.numpy.cov not implemented for nontrivial y.

### ISSUE THREAD

**Issue by cccntu** [google/jax#5786]
I got this error when using `jnp.corrcoef()`
> NotImplementedError: jax.numpy.cov not implemented for nontrivial y. Open a feature request at https://github.com/google/jax/issues !

**Comment by minoring** [comment]
Can I handle this issue? :)

**Comment by jakevdp** [comment]
@minoring - that would be great! I'll assign this to you, please feel free to open a work-in-progress PR and reach out if you need any help or advice.
