### ISSUE TITLE
Docs: repeated title for "XLA in Python" in sidebar

### ISSUE THREAD

**Issue by shoyer** [google/jax#5801]
I'm guessing this glitch is to due to our recent rewrite of how docs are generated:
![image](https://user-images.githubusercontent.com/1217238/108640753-5a87ff80-7450-11eb-8de2-d9687fdd859b.png)

cc @jakevdp

**Comment by jakevdp** [comment]
Thanks - the issue is that the "Caution" message is marked as a level 1 header.
