### ISSUE TITLE
Performance too slow with Jax 

### ISSUE THREAD

**Issue by agobL** [google/jax#5815]
Hello,

For my internship, I need to compare performances between Jax and Autograd.
But when I try to run that code (for example), I get worse performances with Jax than with Autograd :
```python
import jax.numpy as jnp
from jax import jit
import time
import autograd.numpy as np
def foo(a):
	for i in range(128):
		for j in range(128):
			s = a[0]
	return 0
a = jnp.zeros(128) 
t = time.time()
foo(a)
print('Including just-in-time compilation ',time.time()-t)
t = time.time() 
foo(a)
print('Run using compiled code jax ',time.time()-t)
foo1=jit(foo)
t = time.time()
foo1(a)
print('Run using compiled code jax jit ',time.time()-t)
t = time.time()
foo(np.zeros(128))
print('Run using compiled code autograd ',time.time()-t)
```
The outputs I got are : 
```
Including just-in-time compilation  19.96216082572937
Run using compiled code jax  19.06805419921875
Run using compiled code jax jit  36.82775378227234
Run using compiled code autograd  0.003182649612426758
```
I don't know where this issue can come from, I work on Visual Studio Code and run my program on a GPU servor working on Ubuntu. The version of CUDA is the following : 
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```
I also tried the code on jupyther notebook and got the same results.

Thanks in advance for your help.

**Comment by jakevdp** [comment]
Thanks for the question!

The issue is your use of nested for-loops within JIT. These will be unrolled by the JIT compiler, meaning that your program ends up sending over 14000 individual instructions to XLA. Rather than nested for-loops, you should try expressing your program's logic in terms of vectorized computations (similar to how Numpy achieves fast performance) or using jax-specific tools like [vmap](https://jax.readthedocs.io/en/latest/jax.html#jax.vmap).

I'd show an example based on your function, but it seems to be a bit over-simplified.

**Comment by agobL** [comment]
I just do not see how to use vmap in my function foo because I don't know Jax very well. Could you please help me in that case ? Thank you.

**Comment by jakevdp** [comment]
There's no way to use vmap in your function `foo`, because your function doesn't do anything aside from repeatedly assigning a local variable. If you're looking to optimize `foo` above, I'd suggest writing it this way:
```python
def foo(a):
  return 0
```

**Comment by zhangqiaorjc** [comment]
Is the benchmark example trying to measure dispatch time? Might be useful to figure out what you are trying to measure here?
