### ISSUE TITLE
Prevent the recalculation of `permutation` in lu_solve()

### ISSUE THREAD

**Issue by ahoenselaar** [google/jax#5826]
Use case: Repeated solution of a linear system based on LU decomposition.

Currently, the only exposed methods to make this possible are `jax.scipy.linalg.lu_factor()` in conjuction with `jax.scipy.linalg.lu_solve()`. However, to conform with SciPy's API,  `jax.scipy.linalg.lu_factor()` drops the third output `permutation` provided by `jax.lax.linalg.lu()`. Hence, the permuation is recalculated in every invocation of `jax.scipy.linalg.lu_solve()` ([code](https://github.com/google/jax/blob/84f55f87ecd4b1a69ed7eac48b144b57df9d3f11/jax/_src/scipy/linalg.py#L117)).

For reasons that should be investigated separately, [lu_pivots_to_permutation()](https://github.com/google/jax/blob/c9b7d751289f60a852f5e5585e3d99aff29fdaae/jax/_src/lax/linalg.py#L949) exhibits poor performance on GPU.

There are two possible solutions:

- Add an optional argument to `jax.scipy.linalg.lu_solve()` that allows the user to pass in `permutation`. That would cause divergence from SciPy's API.
- Expose `jax.lax.linalg.lu_solve()` directly to the user.

**Comment by hawkinsp** [comment]
I'm curious if you think this is still worth solving, given that #5880 significantly improved the performance (thanks!). I doubt that the pivot to permutation conversion has more than a negligible time cost now?

The underlying `jax.lax.linalg.lu_solve` is accessible, should you want it.

What do you think?

**Comment by ahoenselaar** [comment]
I agree that we can close this issue.

**Comment by hawkinsp** [comment]
Thanks!
