### ISSUE TITLE
where argument for jax.numpy.{mean, var, std, all, any}

### ISSUE THREAD

**Issue by n2cholas** [google/jax#5842]
As of NumPy 1.20.0 `numpy.{mean, var, std, all, any}` support the `where` keyword argument ([release notes](https://numpy.org/doc/stable/release/1.20.0-notes.html#where-keyword-argument-for-numpy-all-and-numpy-any-functions)). `jax.numpy.{sum, max, min, ...}` already support this (the NumPy versions had it since 1.17.0). For API consistency and parity with NumPy, I think this argument should be implemented. Thanks!

**Comment by jakevdp** [comment]
Great idea! This should be pretty straightforward; compare the definition of `min` and `all`: https://github.com/google/jax/blob/bb51a58084caa1537ba7970fb5669f5fe6fe69be/jax/_src/numpy/lax_numpy.py#L2007-L2018

Then for tests, we'd need to remove this condition: https://github.com/google/jax/blob/bb51a58084caa1537ba7970fb5669f5fe6fe69be/tests/lax_numpy_test.py#L832-L835

Although we would still need this skip for older numpy versions (our CI tests as far back as version 1.16). There's an example of skipping based on numpy version here: https://github.com/google/jax/blob/bb51a58084caa1537ba7970fb5669f5fe6fe69be/tests/lax_numpy_test.py#L1500-L1501

**Comment by mtsokol** [comment]
Hi! I would like to try solving it as a first issue if it's still free to take 🙂

**Comment by jakevdp** [comment]
@mtsokol - this is indeed still free to take. Please let me know if you have any questions, and feel free to open a work in progress pull request if that would be convenient!
