### ISSUE TITLE
Implement np.mgrid, np.ogrid, & np.r_, np.c_

### ISSUE THREAD

**Issue by Conchylicultor** [google/jax#5850]
Numpy has a very convenient `np.mgrid` which allow to easily create coordinate grids: https://numpy.org/doc/stable/reference/generated/numpy.mgrid.html.

I was expecting jax to have the same, but it seems to be missing:

```python
jnp.mgrid  # raise AttributeError
```

---
Tracking implementation of these:

- [x] `jnp.mgrid` #6248
- [x] `jnp.ogrid` #6342
- [x] `jnp.r_` #6593
- [x] `jnp.c_` #6593
- [x] `jnp.ix_`
- [x] `jnp.s_`

**Comment by jakevdp** [comment]
Thanks! Agreed it would be useful to have a jax-native version of this.

**Comment by VikasHanumegowda** [comment]
I'd love to solve this. Anyone with a good direction suggestion for me to point to, to solve this issue? @jakevdp @Conchylicultor

**Comment by Conchylicultor** [comment]
To add to the list, `np.c_` is missing too: https://numpy.org/doc/stable/reference/generated/numpy.c_.html#numpy.c_

**Comment by jakevdp** [comment]
The way to implement these woulc be to create a private class, and override the `__getitem__` method to mimic what numpy does. Something like this:
```python
import jax.numpy as jnp

class _Mgrid:
  def __getitem__(self, key):
    if isinstance(key, slice):
      return jnp.arange(key.start or 0, key.stop, key.step or 1)
    else:
      raise NotImplementedError()

mgrid = _Mgrid()
print(mgrid[:5])
# [0 1 2 3 4]
```

**Comment by Conchylicultor** [comment]
You could also look at the numpy implementation to see how they are implementing it

**Comment by jakevdp** [comment]
> You could also look at the numpy implementation to see how they are implementing it

But note that if you copy from numpy's implementation rather than writing your own version, the code should go in https://github.com/google/jax/tree/master/jax/_src/third_party for licensing reasons.

**Comment by hawkinsp** [comment]
And in this case, where there's probably no need to look at NumPy's implementation to implement the API faithfully and well, it's much better to implement from scratch so we don't have to split up the code based on license. In general:

* please try not to use code from NumPy
* if you do use code from NumPy, it *must* go in `third_party/`, and ultimately may need to be rewritten anyway.

**Comment by minoring** [comment]
Is there an any update for this issue? If not, I would like to progress it :)

**Comment by VikasHanumegowda** [comment]
I didn't find time for this @minoring   
Please go ahead.

**Comment by minoring** [comment]
Thanks for your response! @VikasHanumegowda

**Comment by SondosAhmed** [comment]
Hi
I'd like to help with this issue if possible  
any update?

**Comment by jakevdp** [comment]
mgrid has been implemented in #6248, but I don't know of any other work on this

**Comment by minoring** [comment]
Hi!
I was working on implementing `jnp.ogrid`.
Maybe you can implement `jnp.r_` so that we do not have conflict to each other :)

**Comment by SondosAhmed** [comment]
@minoring Thanks for informing me 
Ok, I'm gonna try implementing jnp.r_

**Comment by arvindmuralie77** [comment]
Can I take up `jnp.s_` if no one else is working on this.

**Comment by jakevdp** [comment]
I don't know of anyone working on `jnp.s_` – feel free to dive in!

**Comment by lgeiger** [comment]
Looks like this issue can be closed since all function have been implemented 🚀 
`np.s_` was the last remaining function which was added in #7114.

**Comment by jakevdp** [comment]
Thanks!
