### ISSUE TITLE
Segmentation fault when importing jax.numpy after symengine

### ISSUE THREAD

**Issue by serksah** [google/jax#5897]
When importing jax.numpy after importing symengine: https://github.com/symengine/symengine.py I get a segmentation fault on Linux:

```python
import symengine
import jax.numpy as jnp
```
The code above works on a Mac (Big Sur 11.2.2) and fails on Ubuntu 18.04.

Changing the import order does not throw an error:
```python
import jax.numpy as jnp
import symengine
```

I am not sure if this is an issue with jax or symengine.

**Comment by jakevdp** [comment]
Thanks for the report - I tried this on Colab (which runs Ubuntu 18.0.4) with the following versions installed, and everything seemed to work:
```python
import symengine
import jax.numpy as jnp
import jaxlib
import jax

print(f"symengine: {symengine.__version__}")
print(f"jax: {jax.__version__}")
print(f"jaxlib: {jaxlib.__version__}")
!lsb_release -a
```
```
symengine: 0.6.1
jax: 0.2.9
jaxlib: 0.1.61
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```
Can you say more about the system and/or package versions installed when you see this error?

**Comment by serksah** [comment]
Thanks for looking into this!

I tested it on the aws image:  Deep Learning AMI (Ubuntu 18.04) Version 38.0 in a conda enviroment with Python 3.7.10:

```
symengine: 0.6.1
jax: 0.2.9
jaxlib: 0.1.61
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic
```

I also tested it in a Docker container with the python:3.7-slim-buster image:

```
FROM python:3.7-slim-buster

RUN mkdir /opt/project

WORKDIR /opt/project
```

```
symengine: 0.6.1
jax: 0.2.9
jaxlib: 0.1.61
```

In both cases I see the segmentation fault when importing jax after symengine.

**Comment by isuruf** [comment]
Should be fixed with the new symengine release. (jax and symengine were both using LLVM and even though both were linking statically to llvm, symengine was exporting llvm functions. Hiding them should fix this issue).

**Comment by jakevdp** [comment]
Thanks @isuruf!

**Comment by serksah** [comment]
Thank you @jakevdp @isuruf !
