### ISSUE TITLE
Autodiff cookbook

### ISSUE THREAD

**Issue by alexbw** [google/jax#59]
A notebook which highlights all the weird stuff you can do with `grad`. This could be a literate programming version of https://github.com/HIPS/autograd/blob/master/autograd/differential_operators.py.

**Comment by jermwatt** [comment]
I'd be happy to help build this.

**Comment by mattjj** [comment]
@jermwatt Thanks for the offer! We'll aim to get a draft posted in the next week or two, then we could really use feedback and additions to it!

**Comment by mattjj** [comment]
We finished this in #500 ! Improvements always welcome of course.

We plan to do a Part 2 with some more advanced stuff. But I'm closing this particular issue as finished.

**Comment by Baschdl** [comment]
@mattjj Did someone already work on the “Advanced Autodiff Cookbook”? I'm particularly interested in Gauss-Newton vector products. I found https://github.com/google/jax/issues/529 but am not sure if that's the best solution.
