### ISSUE TITLE
Sharp bits cond signature is wrong

### ISSUE THREAD

**Issue by Relja** [google/jax#5925]
[Sharp bits doc](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#cond) uses `cond` as `lax.cond(pred, true_operand, true_fun, false_operand, false_fun)`
but `cond`'s [docs](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.cond.html#jax.lax.cond) say it's actually `jax.lax.cond(pred, true_fun, false_fun, operand)`

**Comment by jakevdp** [comment]
Thanks - that's an outdated signature. I'll make sure it gets fixed
