### ISSUE TITLE
Please add a Rust front end

### ISSUE THREAD

**Issue by bionicles** [google/jax#5938]
Rust and Jax share a lot of values in terms of functional programming and being careful about mutation to reduce bugs. Rust is the most loved programming language for a while now.

There aren't any great maintained options for differentiable programming in Rust and a statically typed, safety-first language could enable more trustworthy, performant, and explicit production-grade use of Jax.

since Rust compiles to WASM this could enable jax on webapps, including Google.com, as well (!) Shifting resource use closer to customers benefits privacy, security, and speed

Would you possibly be openminded to engineer a Rust front-end for Jax?

**Comment by mattjj** [comment]
Thanks for the idea! But additional language frontends are out of scope for us.

(Interestingly enough, some of our team members like @froystig used to [work on Rust](https://github.com/rust-lang/rust//commits?author=froystig) more than a decade ago!)
