### ISSUE TITLE
Memory problem: Device array from numpy array on linear regression

### ISSUE THREAD

**Issue by d-caviedes** [google/jax#5944]
Hi everyone,

Quite a newbie here, so please understand this could be trivial for you. I've been trying to find the answer at several places without luck. I hope you can help me out.

I am using the Numpyro package which works with JAX to solve a quite simple linear regression problem. In Numpyro repo couldn't help me because it got into the JAX "domain".  I don't know if you are familiar with Numpyro, but the regression is something like

```python
import numpy as np
import scipy as sc
import numpyro
import jax.numpy as jnp
from jax import random as jrandom

def model_sbl(data):
    obs = data["obs"]
    Nw = data["Nw"]
    Nt = data["Nt"]
    X = data["X"]
    tau0 = data["tau0"]
    b = numpyro.sample("b", dist.LogNormal(0, 2))
    sigma = numpyro.sample("sigma", dist.LogNormal(0.0, 0.1))
    dist_var = dist.InverseGamma(1, 10 ** (-b) * jnp.ones(Nw * Nt))
    with numpyro.plate("coefficients", Nw * Nt):
        w_var = jnp.sqrt(numpyro.sample("w_var", dist_var))
        dist_w = dist.Normal(jnp.zeros((Nw * Nt)), tau0 * w_var)
        w = numpyro.sample("w", dist_w)
    mean = jnp.dot(X, w)
    y = dist.Normal(mean, sigma)
    with numpyro.plate("observations", size=len(obs)):
        numpyro.sample("obs", y, obs=obs)


rng_key = jrandom.PRNGKey(0)
rng_key, rng_key_ = jrandom.split(rng_key)
my_kernel = NUTS(model_sbl, max_tree_depth=7)
posterior = MCMC(my_kernel, num_samples=100, num_warmup=50, num_chains=1)
posterior.run(rng_key_, data=data)
```

The problem comes in the way I create the dictionary of features `X`. If I create a dumb dictionary s.t. `X = jnp.ones((Nm*Nt,Nw*Nt))` I can execute the inference without a problem, like a charm. 

However, we would like to create a more interesting dictionary such that

```python
def sinc_dictionary(s, r, t, fs, c, precision="float32"):
    Nw = s.shape[0]
    Nt = len(t)
    Nm = r.shape[0]
    d_ = distance_between(s.T, r.T)
    Dt = t[..., None, None] - (d_ / c)[None]
    #%% Dictionary
    D_ = np.empty((Nt * Nm, Nt * Nw), dtype=precision)
    for m in tqdm(range(Nm)):
        for l in range(Nw):
            column = 1 / (4 * np.pi * d_[m, l]) * np.sinc(fs * Dt[:, m, l])
            # row = 1 / (4 * np.pi * d_[m, l]) * np.sinc(fs_resample * Dt[:, m, l])
            row = np.zeros(column.shape)
            row[0] = column[0]
            D_[Nt * m : Nt * (m + 1), Nt * l : Nt * (l + 1)] = sc.linalg.toeplitz(
                column, row
            )
    # for i in tqdm(range(D_.shape[0])):
    #     for j in range(D_.shape[1]):
    #         jax.ops.index_update(X, jax.ops.index[i, j], D_[i, j])
    return D_

X = jnp.asarray(sinc_dictionary(s, r_fit, t, fs_new, c, precision=precision))
```
If I run the inferences with such dictionary, the ram consumption explodes and, if by any chance it starts sampling, it will collapse at some point

![sudden_stop](https://user-images.githubusercontent.com/26739558/110042063-78edd500-7d45-11eb-90fa-5b420f267c8a.png)

Do you have any idea why? I don't need to differentiate the `sinc_dictionary` function or anything, I just want to create a dictionary and then use it as a constant during the inference. Are there any attributes that are carried when transforming from numpy to jax array and that could mess with jax later?

In case it helps, here the issue that wasn't resolved in Numpyro https://github.com/pyro-ppl/numpyro/issues/936

You are my last hope guys!

**Comment by jakevdp** [comment]
Just so I'm sure I understand: are you saying that your problem is if you use numpyro to run inference code on a numpy array, everything works fine, but if the same array is passed to numpyro in the form of a JAX array, the memory blows up?

**Comment by d-caviedes** [comment]
Hi Jake, thanks for your time, and sorry for the misunderstanding. The problem is that depending on how I create the `X` dictionary array, the compilation will eat all the memory or not. In any case, `X` is always passed as jax array to numpyro once it is created.

This is the minimal reproducible example I could come up with. The modules used

```
import numpy as np
import scipy as sc
import numpyro
import numpyro.distributions as dist
from numpyro.infer import MCMC, NUTS
import jax.numpy as jnp
from jax import random as jrandom
from tqdm import tqdm
```

As an example, I made two functions to generate the dictionary `X`, one will create a dictionary where numpyro behaves fine, and the other one creates it such that it runs out of memory. The only difference between them is that the good dictionary is created out of arrays of ones, and the other is created with random numbers.

```
def create_good_dictionary(Nm, Nw, Nt):
    X = np.empty((Nt * Nm, Nt * Nw))
    column = np.ones((Nt))
    row = np.ones((Nt))
    for m in tqdm(range(Nm)):
        for l in range(Nw):
            X[Nt * m : Nt * (m + 1), Nt * l : Nt * (l + 1)] = sc.linalg.toeplitz(
                column, row
            )
    return X


def create_bad_dictionary(Nm, Nw, Nt):
    X = np.empty((Nt * Nm, Nt * Nw))
    column = np.random.randn(Nt)
    row = np.random.randn(Nt)
    for m in tqdm(range(Nm)):
        for l in range(Nw):
            X[Nt * m : Nt * (m + 1), Nt * l : Nt * (l + 1)] = sc.linalg.toeplitz(
                column, row
            )
    return X
```
The numpyro model is very simple for now. I want to find the coefficients `w` such that `obs=Xw`
```
def model_sbl(data):
    obs = data["obs"]
    Nw = data["Nw"]
    Nt = data["Nt"]
    X = data["X"]
    with numpyro.plate("coefficients", Nw * Nt):
        dist_w = dist.Normal(jnp.zeros((Nw * Nt)), 1)
        w = numpyro.sample("w", dist_w)
    mean = jnp.dot(X, w)
    y = dist.Normal(mean, 1)
    with numpyro.plate("observations", size=len(obs)):
        numpyro.sample("obs", y, obs=obs)
```
To infer the coefficients of the linear regression, this is what I use

```
def linear_regression():
    Nw = 700  # Number of waves
    Nt = 308  # Number of taps
    Nm = 17  # Number of locations

    obs = np.random.randn(Nt, Nm)  # observations

    # X = create_good_dictionary(Nm, Nw, Nt) # Option 1: create a good dictionary with minimal memory consumption at compilation
    X = create_bad_dictionary(
        Nm, Nw, Nt
    )  # Option 2: create a bad dictionary that consumes all the memory at compilation

    # Dictionary used as input in Numpyro model. X needs to be a jax array.
    data = dict(
        obs=jnp.asarray(obs.T.flatten()),
        X=jnp.asarray(X),
        Nw=Nw,
        Nt=Nt,
    )

    # Inferences
    rng_key = jrandom.PRNGKey(0)
    rng_key, rng_key_ = jrandom.split(rng_key)
    my_kernel = NUTS(model_sbl, max_tree_depth=7)
    posterior = MCMC(my_kernel, num_samples=100, num_warmup=50, num_chains=1)
    posterior.run(rng_key_, data=data)

if __name__ == "__main__":
    linear_regression()
```

Finally the system is Ubuntu 20.04, and the Python env is minimal with the following packages (Python 3.9.1)

```
Package     Version
----------- -------------------
absl-py     0.11.0
certifi     2020.12.5
flatbuffers 1.12
jax         0.2.9
jaxlib      0.1.61
numpy       1.20.1
numpyro     0.5.0
opt-einsum  3.3.0
pip         21.0.1
scipy       1.6.1
setuptools  52.0.0.post20210125
six         1.15.0
tqdm        4.58.0
wheel       0.36.2
```

**Comment by jakevdp** [comment]
I'm not familiar with numpyro or its NUTS implementation, but is it possible that it processes non-jax functions, such as numpy/scipy? Those have the side-effect of copying the data back to the CPU as a numpy array, and that might cause this kind of memory blowup.

As for why there is a difference between the good and bad dictionary, perhaps the bad dictionary with its random nature is more difficult to fit, and leads to more iterations and thus more of the data copies referenced above.

**Comment by jakevdp** [comment]
I'm going to close this since it hasn't had any activity for a while. Please let us know if you have other questions or issues!
