### ISSUE TITLE
Grad sorts the input dictionary on the key

### ISSUE THREAD

**Issue by thomaspinder** [google/jax#5948]
This is perhaps easiest to see through code:

```python
import jax.numpy as jnp
from jax import grad

parameters = {"b": jnp.array(1.0), "a": jnp.array(2.0)}

def f(params: dict) -> jnp.DeviceArray:
    return parameters["b"] * jnp.square(params["a"])

grad(f)(parameters)
```
returns `{'a': DeviceArray(4., dtype=float64), 'b': array(0.)}`.

When an input variable is a dictionary, is there a reason why `grad` sorts the input on the keys? In the above example, you can see that the dictionary's order is altered in the output of `grad`.

If this is the intended behaviour of `grad`, then this question is probably best moved to the discussions tab.

**Comment by tomhennigan** [comment]
Hi @thomaspinder , grad (and all other APIs in JAX that accept structured inputs like dicts) make use of `jax.tree_util`s. There is an open feature request to maintain original insertion order for `dict` on unflatten in #4085, if that is fixed then the behaviour of grad et al will change too.
