### ISSUE TITLE
Vmap cookbook

### ISSUE THREAD

**Issue by alexbw** [google/jax#60]
A notebook highlighting creative uses of `vmap`.
Ideas:
 - vanilla matrix-vector to matrix-matrix
 - more complicated, but still vanilla, function
 - pdist
 - cdist
 - vmapping random seeds for hessian trace estimation
 - bootstrap

**Comment by dynamicwebpaige** [comment]
Looks like there are quite a few requests for API docs / cookbooks. 🙂 

Can I get permission to [triage issues](https://help.github.com/en/articles/repository-permission-levels-for-an-organization#permission-levels-for-repositories-owned-by-an-organization), @mattjj?

**Comment by 8bitmp3** [comment]
Just putting together some existing docs `vmap` @alexbw. Autodidax is quite new (by @mattjj and team):

- Transformations: Auto-vectorization with `vmap`
  https://jax.readthedocs.io/en/latest/transformations.html?highlight=vmap#auto-vectorization-with-vmap
- JAX quickstart: Auto-vectorization with `vmap()`
  https://jax.readthedocs.io/en/latest/notebooks/quickstart.html?highlight=vmap#auto-vectorization-with-vmap
- The autodiff cookbook: Composing VJPs, JVPs, and `vmap`
  https://jax.readthedocs.io/en/latest/notebooks/autodiff_cookbook.html?highlight=vmap#composing-vjps-jvps-and-vmap
- Writing custom Jaxpr interpreters in JAX
  https://jax.readthedocs.io/en/latest/notebooks/Writing_custom_interpreters_in_Jax.html?highlight=vmap
- Autodidax: JAX core from scratch: Vectorized batching with `vmap`
  https://jax.readthedocs.io/en/latest/autodidax.html?highlight=vmap#vectorized-batching-with-vmap

**Comment by hawkinsp** [comment]
Closing as stale.
