### ISSUE TITLE
NumPy compatibility of jax.numpy.linalg.eig for real-valued inputs

### ISSUE THREAD

**Issue by IvanYashchuk** [google/jax#6008]
`jax.numpy.linalg.eig` for real-valued input always gives complex-valued output. However, NumPy casts the result to real dtype if the imaginary part of eigenvalues is all zeros.

```python
In [1]: import jax.numpy as jnp
In [2]: import numpy as np
In [3]: np.linalg.eig(np.diag((1, 2, 3)))
   ...: 
Out[3]: 
(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))
In [4]: jnp.linalg.eig(np.diag((1, 2, 3)))
   ...: 
Out[4]: 
[DeviceArray([1.+0.j, 2.+0.j, 3.+0.j], dtype=complex64),
 DeviceArray([[1.+0.j, 0.+0.j, 0.+0.j],
              [0.+0.j, 1.+0.j, 0.+0.j],
              [0.+0.j, 0.+0.j, 1.+0.j]], dtype=complex64)]
```

Is this the intended behavior?

**Comment by jakevdp** [comment]
Yes, this is intended. Due to JAX's XLA compilation model, it is not possible to make the return type of a function dependent on the contents of the returned array.

**Comment by hawkinsp** [comment]
There's probably still an action item here: we should document the difference.
