### ISSUE TITLE
Requesting implementation of scipy.stats.chi2.ppf

### ISSUE THREAD

**Issue by dieterichlawson** [google/jax#6016]
It would be very helpful if there was an implementation of the ppf function for chi squared. I think it has broader interest as well, as it is commonly used in generating Gaussian confidence intervals.

**Comment by skye** [comment]
@jakevdp @shoyer @mattjj @hawkinsp @froystig in case any of y'all are interested (I'm not sure how to triage this lol)

**Comment by mattjj** [comment]
@sharadmv @brianwa84 is this available in TFP?

@dieterichlawson you can [use TFP with JAX](https://www.tensorflow.org/probability/examples/TensorFlow_Probability_on_JAX), without even having TF installed. IIUC there are a lot of super high-quality special function implementations available that way. (And it's great to hear from you!)

**Comment by sharadmv** [comment]
Yes, we have `tfd.Chi2.quantile`. Here's a small example:
```python
from jax import jit, vmap
import jax.numpy as jnp
from tensorflow_probability.substrates import jax as tfp
import matplotlib.pyplot as plt

tfd = tfp.distributions

x = jnp.linspace(0, 1, 100)
plt.plot(x, vmap(jit(tfd.Chi2(4.).quantile))(x))
```
which produces:
![image](https://user-images.githubusercontent.com/1142926/110988957-0fae2900-8326-11eb-8828-62dd41aa80cb.png)

Documentation for Chi2 can be found [here](https://www.tensorflow.org/probability/api_docs/python/tfp/distributions/Chi2).

**Comment by dieterichlawson** [comment]
Awesome, thanks everyone! I honestly should have thought of this, I'm
already using the TFP Jax substrate... And it's great to hear from you too,
Matt!

**Comment by brianwa84** [comment]
@mattjj would JAX folks be up for a little stub inside scipy.stats that tries importing `tensorflow_probability.substrates.jax` and if available implements the TFP-supported bits of the scipy API?
