### ISSUE TITLE
Calculation with between extremely large array, 9 billion elements. Auto distribute computations on GPUs and CPUs at the same time?

### ISSUE THREAD

**Issue by dongxulee** [google/jax#6033]
I find Jax is extremely helpful to my research, but quickly I am running into an issue: I work with calculation between extremely large array, usually with a size of 933120000, for example. So I exhausted the memory on GPU quickly. Is it possible to add in a feature that will detect this OOM and then automatically distribute the calculation into several devices, other GPUs, or CPUs (maybe at the same time, applying CPUs and GPUs)?

I think **pmap** does have a similar feature, kind of writing single-program multiple-data (SPMD) programs. But sometimes I find this feature is difficult to use, especially when you do not want to broadcast the computation into another dimension, which I find kind of confusing sometimes. 

But I think it would be extremely helpful to have a nice feature to distribute the computation of the large array through devices automatically, so we do not have to deal with OOM issues with a single GPU device. To make it more clear about this idea, I list the following example, I hope it's not too confusing: calculate the summation of two arrays:

Objective: 
a + b
Issue:
a.size = b.size = 9 billion, this is too large, can not fit into one single GPU 
Proposed feature:
a = [a1, a2, a3], a1.size = a2.size = a3.size = 9billion/ 3
b = [b1, b2, b3], a1.size = a2.size = a3.size = 9billion/ 3

To calculate  a + b:
Automatically break the array into serval segments and distribute into several GPUs or TPU cores
calculate z1 = a1 + b1 on GPU(0) or cpu 
calculate z2 = a2 + b2 on GPU(1) or cpu
calculate z3 = a3 + b3 on GPU(2) or (and) cpu
Finally concatenate z1,z2,z3 in to Z = [z1, z2, z3].

**Comment by jakevdp** [comment]
You can already do something like this using `jax.device_put_sharded` along with the `pmap` transform. Here's an example with smaller arrays, run on a single CPU that is emulating a cluster of 3 GPUs:
```python
#--- Emulate a pod of 3 GPUs
import os
flags = os.environ.get('XLA_FLAGS', '')
os.environ['XLA_FLAGS'] = flags + " --xla_force_host_platform_device_count=3"
#---

import jax
import jax.numpy as jnp

a = jax.device_put_sharded([jnp.arange(3_000_000) for i in range(3)], jax.devices())
b = jax.device_put_sharded([jnp.arange(3_000_000) for i in range(3)], jax.devices())

@jax.pmap
def func(a, b):
  return a + b

print(func(a, b))
# ShardedDeviceArray([[      0,       2,       4, ..., 5999994, 5999996, 5999998],
#                     [      0,       2,       4, ..., 5999994, 5999996, 5999998],
#                     [      0,       2,       4, ..., 5999994, 5999996, 5999998]], dtype=int32)
```

**Comment by dongxulee** [comment]
@jakevdp Thanks a lot for the solution. I have tested this method on GPUs and TPUs, just to provide a quick observation: For calculation on Vectors of this large size, the speed on GPUs is much faster. I suppose maybe TPUs are better at matrix calculation. 

Another interesting observation is that, if I use only multiple cores CPU machine, seems that Jax is able to automatically distribute workload to all the available cores, and also the machine is more capable of placing large size array in the memory since the memory associated with CPU is significantly larger than the memory available in GPU.

**Comment by jakevdp** [comment]
I'm going to close this, as it looks like the question was answered. If you have additional questions along these lines, feel free to open a new discussion here: https://github.com/google/jax/discussions/new
