### ISSUE TITLE
Not compatible with np.tensordot

### ISSUE THREAD

**Issue by bingykang** [google/jax#6035]
Environments: 
- jaxlib: 0.1.61+cuda110
- jax: 0.2.10
- dm-haiku: 0.0.4.dev0
- numpy: 1.19.5

To reproduce the bug: 
- code is given as bellow
- **you might need to run it multiple times**

```python
import jax
import haiku as hk
import numpy as np

def net(x):
  torso_net = hk.Conv2D(32, kernel_shape=[8, 8], stride=[4, 4], padding='VALID')
  return  hk.BatchApply(torso_net)(x)

def main():
  init_fn, apply_fn = hk.without_apply_rng(
    hk.transform(lambda obs: net(obs))
  )

  # Uncomment can also reproduce the bug
  # @jax.jit
  def initial_params(rng_key):
    _ = np.tensordot(np.zeros((84,84,3)), [0., 0., 0.], (-1, 0))
    return init_fn(rng_key, np.zeros((1,1,84,84,4)))

  rng_key = jax.random.PRNGKey(428)
  params = initial_params(rng_key)

if __name__ == '__main__':
  main()
```

The full error messages/tracebacks.
- with @jax.jit
```
Segmentation fault (core dumped)
```
- without @jax.jit
```
/usr/local/lib/python3.6/dist-packages/jax/_src/numpy/lax_numpy.py:2970: UserWarning: Explicitly requested dtype float64 requested in zeros is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax._check_user_dtype_supported(dtype, "zeros")
Segmentation fault (core dumped)
```

**Comment by mattjj** [comment]
Thanks for the question!

Actually, JAX transformations like `jax.jit` aren't compatible with _any_ `numpy` functions. You need to `import jax.numpy as jnp` and then use `jnp` for operations you want to transform or stage out, e.g. `jnp.tensordot`.

Perhaps take a look at the [JAX 101 Tutorial](https://jax.readthedocs.io/en/latest/jax-101/index.html) and [How to think in JAX](https://jax.readthedocs.io/en/latest/notebooks/thinking_in_jax.html) if you haven't already.

(Usually a better error message prints here (not a segmentation fault), but unfortunately I wasn't able to reproduce the issue on my machine.)

**Comment by mattjj** [comment]
Here's a version of the code using `jnp`:

```python
import jax
import haiku as hk
import jax.numpy as jnp

def net(x):
  torso_net = hk.Conv2D(32, kernel_shape=[8, 8], stride=[4, 4], padding='VALID')
  return  hk.BatchApply(torso_net)(x)

def main():
  init_fn, apply_fn = hk.without_apply_rng(
    hk.transform(lambda obs: net(obs))
  )

  @jax.jit
  def initial_params(rng_key):
    _ = jnp.tensordot(jnp.zeros((84,84,3)), jnp.array([0., 0., 0.]), (-1, 0))
    return init_fn(rng_key, jnp.zeros((1,1,84,84,4)))

  rng_key = jax.random.PRNGKey(428)
  params = initial_params(rng_key)

if __name__ == '__main__':
  main()
```

**Comment by bingykang** [comment]
Hi @mattjj, thank you very much for your quick reply! 

But, actually, when '@jax.jit' is not used, the code can also cause core dumped. 

Could you please explain why is that?

**Comment by bingykang** [comment]
BTW, for the hardware, I am using DGX A100. And I just tried to set JAX_PLATFORM_NAME=cpu, the bug is gone.

**Comment by mattjj** [comment]
Hm, that is weird. Sorry I didn't glean that from your first message. Maybe there is a real bug here, and we need to run on XLA:GPU to see it.

@bingykang any chance you can reproduce the bug without using `haiku`, and just using pure JAX? This isn't critical to do, but it can be helpful to simplify as much as possible.

@zhangqiaorjc any thoughts on what could cause a segfault?

**Comment by mattjj** [comment]
@bingykang on GPU, does [the version using `jnp` instead of `np`](https://github.com/google/jax/issues/6035#issuecomment-797226522) also segfault, or is it only when using raw `np`?

**Comment by bingykang** [comment]
Hi, 

I have tried the following things, 

1. Replacing np with jnp on GPU, the bug is gone. 
OR
2. Replacing np.tensordot with np.dot as follows, the bug is gone. 
```python 
_ = np.dot(np.zeros((84,84,3)), [0., 0., 0.])
```
BTW, I am using the following Dockerfile to build the environment

```
FROM tensorflow/tensorflow:2.4.1-gpu

# Install dependencies 
RUN apt-get update && apt-get install -y tmux ffmpeg libsm6 libxext6 libxrender-dev git vim

# Install JAX
RUN pip3 install --upgrade pip
RUN pip3 install --upgrade jax jaxlib==0.1.61+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html

# Install Haiku 
RUN pip3 install absl-py numpy tabulate \
    dm-env>=1.2 \
    dm-tree>=0.1.1 \
    packaging>=20.9 \
    tensorflow-datasets>=4.2.0
RUN pip3 install git+https://github.com/deepmind/dm-haiku
RUN pip3 install git+git://github.com/deepmind/bsuite.git
RUN pip3 install git+git://github.com/deepmind/optax.git
RUN pip3 install git+git://github.com/deepmind/rlax.git

# Install Atari environment
RUN pip3 install gym[atari]
RUN pip3 install atari-py
RUN pip3 install tensorflow_probability==0.11.0

# Copy SEED codebase and SEED GRPC binaries.
ADD . /impala/
WORKDIR /impala
ENTRYPOINT ["python3"]
```

**Comment by mattjj** [comment]
Can you try this again on the latest `jaxlib==0.1.64`? I think you can just write `pip install --upgrade jaxlib==0.1.64+cuda110 -f https://storage.googleapis.com/jax-releases/jax_releases.html` to use the same cuda110 version you have now.

**Comment by bingykang** [comment]
Looks like the bug is gone.
