### ISSUE TITLE
sticky device (device_put) ignored in jit context

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#6040]
Using device_put is supposed to set the device to be sticky, according to the documentation.
Accordingly, I expect that If I sum 2 cpu arrays (or even a sticky-cpu array + gpu array) the result should live on the cpu.
This is the case for non-jitted functions, but is ignored in the case of jitted functions.

See example: 
```python
import jax
import jax.numpy as jnp

_cpu = jax.devices("cpu")[0]
_gpu = jax.devices("gpu")[0]

a = jnp.ones(5)
b = jnp.ones(5)

def print_device(txt, x):
    print(txt, x.device_buffer.device())

def cpu_add(a,b):
    a_cpu = jax.device_put(a, _cpu)
    b_cpu = jax.device_put(b, _cpu)
    return a_cpu+b_cpu

print_device("cpu_add no jit", cpu_add(a,b))
print_device("cpu_add jit", jax.jit(cpu_add)(a,b))
```

output
```python
cpu_add no jit: cpu:0
cpu_add jit: gpu:0
```

**Comment by PhilipVinc** [comment]
I can confirm that not only the result of the jitted function is in the cpu, but the operations are being encoded in the gpu.
I wished to Call Numba functions with CFFI from jax using custom calls 'a la #1870. This works very well when working only on the cpu, and I hoped that I could move GPU buffers to the GPU so that it would always work.
But since device_put is ignored, that won't work.

**Comment by skye** [comment]
`device_put` doesn't work in jit'd functions -- a jit'd function can only be run on a single device, unless using the [host_callback](https://jax.readthedocs.io/en/latest/jax.experimental.host_callback.html) module. You can think of a jit'd function as a single operation from the device-placement view.

I'll update the documentation to mention this. I also think we should make device_put an error inside a jit'd function since it doesn't behave as expected outside the function, but maybe there's a good reason for allowing it that I'm not thinking of.

**Comment by PhilipVinc** [comment]
Thanks for your answer.

**Comment by azzeddineCH** [comment]
thanks @skye , I think it's still worth asserting that `device_put` is not used in a jitted function as it can lead to silent errors.

**Comment by smorad** [comment]
Just found this after hours of debugging. IMO having a function **silently fail**, but **only under JIT** is a bit masochistic. A standard user will attempt to debug their code by stepping out of the JIT, then the silent error will go back into hiding.

I think it would be very helpful for `device_put` to error under JIT.

**Comment by jakevdp** [comment]
@smorad thanks for the comment here.

This behavior in `device_put` is quite old, and pre-dates the current APIs for specifying device/sharding within JIT. I think we could probably re-evaluate that decision now. We'll explore what it looks like to make `device_put` error during abstract evaluation. cc/ @yashk2810
