### ISSUE TITLE
0**0 is Nan on TPU

### ISSUE THREAD

**Issue by mtthss** [google/jax#6042]
Why does

```
@jax.jit
def fn(x):
  return x**x

fn(jnp.zeros((3,)))
fn(jnp.zeros((3,)))
```

return 1s on CPU but NaNs on TPU?

It forces to write a lot of ugly code to manually set it to 1 on TPUs

**Comment by hawkinsp** [comment]
Filed internal XLA bug b/182538624, since this behavior comes from XLA's TPU implementation of `pow()`.

**Comment by majnemer** [comment]
b/182538624 has been fixed internally.
