### ISSUE TITLE
JIT leads to overflow error for large integers in X64

### ISSUE THREAD

**Issue by jakevdp** [google/jax#6045]
```python
import jax.numpy as jnp
import numpy as np
from jax import config, jit
config.update('jax_enable_x64', True)

big = np.iinfo(np.int64).max

print(np.array(big).dtype)  # int64
print(np.array(big + 1).dtype)  # uint64

print(jnp.array(big).dtype)  # int64
print(jnp.array(big + 1).dtype)  # uint64

print(jit(jnp.array)(big).dtype)  # int64
print(jit(jnp.array)(big + 1).dtype)  # OverflowError: Python int too large to convert to C long
```

**Comment by hawkinsp** [comment]
Seems like the bug is that
```
print(jnp.array(big + 1).dtype)  # uint64
```

should error as well?

**Comment by hawkinsp** [comment]
I think I prefer the error to silently overflowing, which is what NumPy does. (And if you do want NumPy's behavior, you can first cast to a NumPy array.)

**Comment by jakevdp** [comment]
Just to clarify, when you say "silently overflowing" are you referrring to the behavior of switching to `uint64` if the value is too large for `int64`, and swittching to `dtype('O')` if the value is too large for `uint64`?

**Comment by hawkinsp** [comment]
Yeah I guess "overflowing" isn't a correct description, on further thought.

Maybe we should follow NumPy here. We could certainly have the same `uint64` behavior for `jit` of integers outside the `int64` range. We can't use `dtype('O')`, of course, so we'd have to error in that case.

**Comment by jakevdp** [comment]
OK, that sounds like a reasonable approach.

The reason I was going down this route is related to #5952: I need to figure out what to do in X32 mode with Python integers between `int32.max` and `uint32.max`. If we choose to promote to uint64 here, we should probably choose to promote to uint32 there.
