### ISSUE TITLE
Axis not recognized in some cases but not in all - happens when inputs are ignored

### ISSUE THREAD

**Issue by hamzamerzic** [google/jax#6067]
Best shown with a simple reproducer [[link](https://colab.research.google.com/drive/12kEa87JcSpQBpKM71syZ0MuBE0SrA7IR#scrollTo=2Dd2vZbxIg1Q)].

**Comment by mattjj** [comment]
Thanks for reporting this! I think this may be #5515.

**Comment by mattjj** [comment]
I'm going to close this as a duplicate of #5515, but let me know if that sounds incorrect!
