### ISSUE TITLE
Docstrings in api.py

### ISSUE THREAD

**Issue by alexbw** [google/jax#61]
There are none currently.

**Comment by georgedahl** [comment]
Similar issue: https://github.com/google/jax/issues/51

**Comment by hawkinsp** [comment]
Closing this issue. We've added doc strings for most of `api.py`:
https://jax.readthedocs.io/en/latest/jax.html

There are still a few things undocumented (e.g., `pmap`), but it's not clear we are ready to/should document anything that is undocumented yet. We document anything that remains on a case by case basis.
