### ISSUE TITLE
jax.lax.dynamic_slice casts uint indices to a too narrow signed type

### ISSUE THREAD

**Issue by altche** [google/jax#6122]
It seems that `jax.lax.dynamic_slice` (and possibly similar functions) casts `uint` inputs to the nearest signed int type, causing potential overflows. Casting to at least an `int32` would probably be safer.

```python 
tensor = jax.random.uniform(jax.random.PRNGKey(0), shape=(200,))
print(
    tensor[128], 
    tensor[-1],
    jax.lax.dynamic_slice(tensor, np.array([128], dtype=np.uint8), (1,)).squeeze(),
    jax.lax.dynamic_slice(tensor, np.array([128], dtype=np.int32), (1,)).squeeze()
)
>> 0.6517935 0.4809643 0.4809643 0.6517935
```

This behavior is particularly surprising when combined with a vmap (eg over a batch dimension), such as in this toy example:
```python
BDIM = 200
tensor = jnp.arange(BDIM)[:, None]
fake_idx = np.zeros((BDIM, 1), dtype=np.uint8)
take_along_second_axis = jax.vmap(
    lambda x, idx: jax.lax.dynamic_slice(x, idx, (1,)).squeeze())
print(take_along_second_axis(tensor, idx=fake_idx)[124:131])
>> [124 125 126 127 199 199 199]
```

**Comment by jakevdp** [comment]
Digging in, this looks like a bug in XLA's `DynamicSlice`: JAX passes the uint8 indices directly into XLA.

We could put a band-aid on the JAX side by converting unsigned ints into larger signed ints, but I think the real fix here would be in XLA itself.

**Comment by jakevdp** [comment]
Just for posterity, I found this by changing this line: https://github.com/google/jax/blob/c229574cff63e720f8c27975851faa44519296bf/jax/_src/lax/lax.py#L3971-L3972

to:
```python
 def _dynamic_slice_translation_rule(c, operand, *start_indices, slice_sizes):
  print(c.get_shape(start_indices[0]))
  return xops.DynamicSlice(operand, start_indices, slice_sizes)
```
Running the following test script:
```python
import numpy as np
from jax import lax
print(lax.dynamic_slice(np.arange(200), np.array([128], dtype=np.uint8), (1,)))
```
Outputs this:
```
u8[]
[199]
```
Which indicates that the `uint8` index is being passed to XLA, rather than being converted anywhere in JAX's wrappers.

**Comment by jakevdp** [comment]
Internal tracking bug: b/183216273

**Comment by jakevdp** [comment]
Update: this is now fixed on TPU; still waiting on a fix for XLA-CPU and XLA-GPU
