### ISSUE TITLE
Functionality to "unvectorize" a function?

### ISSUE THREAD

**Issue by KristianHolsheimer** [google/jax#6131]
A typical use case that I encounter often is that I have a batched function that I'd like to evaluate on a single input, e.g.

```python
import jax
import jax.numpy as jnp
import haiku as hk

def func(X):
  return hk.Linear(4)(X)

# transform and init haiku function
init, apply = hk.transform(func)
rngs = hk.PRNGSequence(42)
X = jax.random.normal(next(rngs), shape=(8, 10))
params = init(next(rngs), X)

# evaluate on a batch of instances
Y = apply(params, next(rngs), X)
assert Y.shape == (8, 4)
```

Now I would like to evaluate this on a single instance:

```python
x = jax.random.normal(next(rngs), shape=(10,))

# transformation (inverse of vmap)
apply_single = unvectorize(apply, in_axes=(None, None, 0), out_axis=0)

# which I can then call on a single instance
y = apply_single(params, next(rngs), x)
assert y.shape == (4,)
```

I've implemented my own transformation, but I'm pretty sure I'm missing a lot of corner cases.

```python
from functools import partial

def unvectorize(f, in_axes=None, out_axis=None):
  def g(*args):
    in_axes_ = (0,) * len(args) if in_axes is None else in_axes
    out_axis_ = 0 if out_axis is None else out_axis
    assert len(args) == len(in_axes_)
    vargs = [
      arg if axis is None
        else jax.tree_map(partial(jnp.expand_dims, axis=axis), arg)
      for arg, axis in zip(args, in_axes_)]
    return jax.tree_map(partial(jnp.squeeze, axis=out_axis_), f(*vargs))
  return g
```

Would it make sense to add this kind of functionality to JAX?

**Comment by froystig** [comment]
This typically isn't something we would upstream to jax, in the interest of keeping the core minimal, perhaps unless we begin to see many similar requests. As you show, it's possible to write this while interfacing with jax only minimally through `tree_util` and the `vmap` calling convention. We might consider that a good sign, in that it seems easy enough to put together downstream for now, so thanks for filing and asking!
