### ISSUE TITLE
lax.reduce throws "Reduction computations cannot have constants"

### ISSUE THREAD

**Issue by malmaud** [google/jax#6188]
I'm trying to call `lax.reduce` from one branch of a `lax.cond`, but `lax.reduce` throws a `Reduction computations cannot have constants` in some circumstances. Note that I am wrapping the function which calls `lax.reduce` in a `custom_jvp`, so I'm not attempting to differentiate through the custom reduction.

**Comment by hawkinsp** [comment]
This is fixed, I think! (And that message doesn't even appear in the JAX code base any more.) Please reopen with a repro if you still see it!
