### ISSUE TITLE
Upload existing JAX talks to docs/ or talks/ folder

### ISSUE THREAD

**Issue by alexbw** [google/jax#62]
They would be a useful resource for those that want to learn more about the ideas behind JAX.

**Comment by alexbw** [comment]
@froystig @dougalm could you guys throw PDFs into a docs/ folder?

**Comment by joaogui1** [comment]
Are these talks recorded?

**Comment by 8bitmp3** [comment]
@n2cholas has a long list: https://github.com/google/jax/discussions/5235#discussion-78809 -> https://github.com/n2cholas/awesome-jax

DeepMind+JAX at NeurIPS 2020: https://github.com/google/jax/discussions/5409 (also, on YouTube).

You can also find more talks by @mattjj @froystig @jakevdp on YouTube at https://github.com/google/jax/discussions/5027#discussion-38094 + there should be a link by @jekbradbury to some slides.

**Comment by hawkinsp** [comment]
Closing as stale.
