### ISSUE TITLE
jit unable to handle DeviceArray inputs

### ISSUE THREAD

**Issue by LouisDesdoigts** [google/jax#6233]
Hey Jax team, I'm currently trying to understand some strange behaviour I'm encountering with the jit function and device arrays.

Starting with a basic function to apply jnp.arange and its jitted counterpart

```python
def f(x):
    return jnp.arange(-x, x)
f_jit = jit(f, static_argnums=0)
```

Passing in a native python integer to either of these like so:

```python
x_int = int(5)
arange = f(x_int)
arange_jit = f_jit(x_int)
```

does not raise any errors as expected. However, if I pass in a jax DeviceArray like so:

```python
x_device_array = jnp.add(4, 1)
arange = f(x_device_array)
arange_jit = f_jit(x_device_array)
```

I get this error when trying to pass the value into the jitted function: 

---------------------------------------------------------------------------
FilteredStackTrace                        Traceback (most recent call last)
<ipython-input-38-76bbc20c8351> in <module>
     14 arange = f(x_device_array)
---> 15 arange_jit = f_jit(x_device_array)

FilteredStackTrace: ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type <class 'jax.interpreters.xla._DeviceArray'>, 5. The error was:
TypeError: JAX DeviceArray, like numpy.ndarray, is not hashable.

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-38-76bbc20c8351> in <module>
     13 print(type(x_device_array))
     14 arange = f(x_device_array)
---> 15 arange_jit = f_jit(x_device_array)

~/anaconda3/envs/main/lib/python3.8/site-packages/jax/_src/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    137   def reraise_with_filtered_traceback(*args, **kwargs):
    138     try:
--> 139       return fun(*args, **kwargs)
    140     except Exception as e:
    141       if not is_under_reraiser(e):

~/anaconda3/envs/main/lib/python3.8/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    414       return cpp_jitted_f(*args, **kwargs)
    415     else:
--> 416       return cpp_jitted_f(context, *args, **kwargs)
    417   f_jitted._cpp_jitted_f = cpp_jitted_f
    418 

ValueError: Non-hashable static arguments are not supported. An error occured while trying to hash an object of type <class 'jax.interpreters.xla._DeviceArray'>, 5. The error was:
TypeError: JAX DeviceArray, like numpy.ndarray, is not hashable.

---------------------------------------------------------------------------

Is this behaving as expected? It seems strange to need to convert the DeviceArray native to jax into a non-jax object type before being passed back into a jax function. Could you please help me to better why this is the case or if there is something I'm doing wrong in this case.

Edit: This is using jax version 0.2.10

Cheers

**Comment by jakevdp** [comment]
Hi - thanks for the question! This is intended behavior: static arguments to JIT must be hashable, and non-hashable objects like jax arrays, numpy arrays, python lists or dicts, etc. can therefore not be used as static arguments.

**Comment by mattjj** [comment]
For even more context, see #2813, #4712, and #4717, as well as the discussion thread on #4572 including [this comment](https://github.com/google/jax/issues/4572#issuecomment-709809897) which shows how you can write a `HashableArrayWrapper` to work with `DeviceArray`s` or `numpy.ndarrays` as static arguments.
