### ISSUE TITLE
Tensorboard profiling causes random crashes

### ISSUE THREAD

**Issue by adam-hartshorne** [google/jax#6278]
I am using tensorflow / tensorboard 2.4.1 on Windows 10 with Cuda 11. As detailed in https://jax.readthedocs.io/en/latest/profiling.html, I add the the following code to the start of my program,

```
import jax.profiler
server = jax.profiler.start_server(9999)
```
and then invoke the capture profile in Tensorboard. 

However, I find that it randomly crashes my program. Different runs, sometimes it works, captures and the program continues, others it just crashes out while I presume is "jit"ing (I presume because I can hear my computer working hard and it has yet to start optimizing a model).

Initially I thought it might be because the model I was trying to train was using a lot of memory, but I tried a smaller version of it that uses minimum memory and it still occurs.

**Comment by skye** [comment]
Does it print any kind of error message when it crashes?

And just to clarify, it never crashes if you don't try to capture a profile?

**Comment by oracle3001** [comment]
No error, just crashes.

And yes, my code never crashes with the same setup if I don't try and capture a profile.

**Comment by skye** [comment]
Unfortunately we can't offer much support for Windows. Is it possible to set the environment variables `TF_CPP_MIN_LOG_LEVEL=0` and post the output here? Hopefully Windows has a concept of env vars that work the same way they do in linux/mac...

**Comment by hawkinsp** [comment]
We currently don't support Windows CUDA builds at all, so I'm going to close this issue. It seems like it's probably stale.
