### ISSUE TITLE
Add lax.reduce_precision primitive corresponding to XLA's ReducePrecision op

### ISSUE THREAD

**Issue by lukaszkaiser** [google/jax#6283]
I want to round a float32 tensor x to bfloat16 values and get it back as float32.
The natural thing is: x.astype(jnp.bfloat32).astype(jnp.float32)
But it looks like XLA optimizes this away to just x again?
Could we have an op to enforce bfloat16 rounding? (e.g., to simulate bfloat16 training in parts of the net)

**Comment by jakevdp** [comment]
It looks like your strategy works, at least in simple cases:
```python
import jax.numpy as jnp
from jax import jit

@jit
def round(x):
  return x.astype(jnp.bfloat16).astype(jnp.float32)

x = jnp.float32(jnp.pi)
y = round(x)
print(x, y, x == y)
# 3.1415927 3.140625 False
```
Do you have an example of a place where this approach fails?

**Comment by hawkinsp** [comment]
XLA is allowed to make optimizations that increase precision. I know the TPU backend does so in some cases, if nothing else. The only way to guarantee precision is not increased by XLA would be to add a JAX primitive that wraps the `ReducePrecision` operator, that exists explicitly for this purpose.

**Comment by jakevdp** [comment]
I'll take a look at exposing this in `lax.py`
