### ISSUE TITLE
Case where jax.linear_transpose fails, but jax.vjp works 

### ISSUE THREAD

**Issue by lukepfister** [google/jax#6288]
I'm running into an error when I try to use `jax.linear_transpose` on a function that involves `jax.ops.index_update`.  I get an error stating the transpose rule (for reverse-mode differentiation) is not implemented.  However, I don't get this error if I use `jax.vjp` to compute the adjoint.  

Using:
- jax  0.2.11
- jaxlib 0.1.64

I'm happy to contribute a fix, but could use some guidance on where to look.

```python
import numpy as np
import jax

def mosaic(x):
    y = jnp.zeros(x.shape)
    y = jax.ops.index_update(y, jax.ops.index[1::2], x[1::2])
    return y

x = jax.device_put(np.r_[:10].astype(np.float32))
fx = mosaic(x)

vjp_fun = jax.vjp(mosaic, x)[1]
vjp_fun(fx)  # works fine!

trans_fun = jax.linear_transpose(mosaic, x)
trans_fun(fx)  # Raises exception:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/ad.py in get_primitive_transpose(p)
    253   try:
--> 254     return primitive_transposes[p]
    255   except KeyError as err:

KeyError: scatter

The above exception was the direct cause of the following exception:

NotImplementedError                       Traceback (most recent call last)
~/scico/vjp_test.py in <module>
     18 
     19     trans_fun = jax.linear_transpose(mosaic, x)
---> 20     trans_fun(fx)

~/miniconda3/envs/scico/lib/python3.8/site-packages/jax/api.py in transposed_fun(out_cotangent)
   1965                       f"expected {out_avals} but got {out_cotangents}")
   1966     dummies = [ad.UndefinedPrimal(a) for a in in_avals]
-> 1967     in_cotangents = ad.backward_pass(jaxpr, consts, dummies, out_cotangents)
   1968     return tree_unflatten(in_tree, in_cotangents)
   1969 

~/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/ad.py in backward_pass(jaxpr, consts, primals_in, cotangents_in)
    225             params, call_jaxpr, invals, cts_in, cts_in_avals)
    226       else:
--> 227         cts_out = get_primitive_transpose(eqn.primitive)(cts_in, *invals,
    228                                                          **eqn.params)
    229     cts_out = [Zero(v.aval) for v in eqn.invars] if cts_out is Zero else cts_out

~/miniconda3/envs/scico/lib/python3.8/site-packages/jax/interpreters/ad.py in get_primitive_transpose(p)
    254     return primitive_transposes[p]
    255   except KeyError as err:
--> 256     raise NotImplementedError(
    257         "Transpose rule (for reverse-mode differentiation) for '{}' "
    258         "not implemented".format(p)) from err

NotImplementedError: Transpose rule (for reverse-mode differentiation) for 'scatter' not implemented


``

**Comment by shoyer** [comment]
Transpose rules only exist for linear functions, but I don't think `index_update` is necessarily linear.

**Comment by lukepfister** [comment]
FWIW I believe it is linear-- in the vector case, `jax.ops.index_update(x, idx, y)` can be written `M x + y_b`, where `M` is a diagonal matrix with 0's in the locations specified by `idx` and 1 otherwise, and `y_b` is a vector such that `y_b[idx] = y` and is zero in other locations.

**Comment by shoyer** [comment]
Yes, you may be right. It quite possible that simply nobody has bothered to implement this yet.

The implementation of the `scatter` primitive (used for index_update) can we found here:
https://github.com/google/jax/blob/1f1d3dffe2de969c3485535b9bbd5a375600b551/jax/_src/lax/lax.py#L4916-L4921

Interestingly, the JVP rule for scatter looks like a manually calculated the JVP of `scatter` written in terms of `scatter_add`:
https://github.com/google/jax/blob/1f1d3dffe2de969c3485535b9bbd5a375600b551/jax/_src/lax/lax.py#L4835

Scatter is kind of a funny primitive -- it seems like we may only need it because there's a corresponding XLA function.

So one possible solution would be:
1. Write a version of `scatter` written in terms of `scatter_add`.
2. Then either:
    a. Replace `scatter` entirely, if `scatter_add` has good enough performance -- maybe we don't actually need a scatter primitive in JAX, or
    b. Use `jvp(scatter_via_scatter_add)` to implement the JVP rule for `scatter` and `linear_tranpose(scatter_via_scatter_add)` to implement the transpose rule. There is a good example of the later for [rfft](https://github.com/google/jax/blob/1f1d3dffe2de969c3485535b9bbd5a375600b551/jax/_src/lax/fft.py#L87).

**Comment by lukepfister** [comment]
Just curious-- with the recent closing of #6306, is there a path to using `linear_transpose` on this/similar functions?

**Comment by shoyer** [comment]
I think we need a different approach here than what I suggested above and tried in that PR. Instead, I think `scatter` just needs a transpose rule.

**Comment by lukepfister** [comment]
On `jax=0.2.16, jaxlib=0.1.68` this is no longer an issue.  Not sure what commit resolved it, but no complaints here!
