### ISSUE TITLE
Migrate away from absl logging.

### ISSUE THREAD

**Issue by gmaratos** [google/jax#6308]
I would suggest a small change. It seems like Jax's logging facilities rely on [Abseil](https://abseil.io/docs/python/guides/logging) like tensorflow, which is an interesting google product. But, is it really necessary to use though? Python already provides a logging mechanism, would it be easy to migrate to that? It seems to be used in

1. jaxlib/tpu_client.py
2. jaxlib/xla_client.py
3. jax/experimental/host_callback.py
4. jax/interpreters/pxla.py
5. jax/interpreters/sharded_jit.py
6. jax/interpreters/xla.py
7. jax/lib/xla_bridge.py

Using abseil can confuse users who are trying to silence warnings and assume jax is using python's warning systems. For example, the famous
```
 WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
```

**Comment by froystig** [comment]
Thanks for that list. It may be worth looking into supporting either module with some simple indirection if possible.

**Comment by ShannonTown** [comment]
Hi, I found that if I run `import jax; print(jax.devices())`, my logging settings later on will not work -- no logging info can be printed. If I only import jax, but don't run `print(jax.devices())`, it's fine.

From this post I figured that's because it's somehow `print(jax.devices())` suppressed the logging since the Abseil logging system is implemented on top of the standard logging module in Python. I wondered is there a way to bypass this (I still want to print the jax.devices), can anyone just remind me how to set up the abseil logging or how to use the python logging instead.

**Comment by mattjj** [comment]
I wonder if we can close this issue within less than a year of it being opened... 😛 

We had a discussion about this just now and the tentative decision is that **we should switch to Python standard logging** (and perhaps use absl just in Google-internal code). There are some minor details to iron out (@froystig want to list them here?) but overall that seems like the right move.

If someone is keen to help make this change, make it known in this thread!

**Comment by nicholasjng** [comment]
Hey, I am happy to take a look at this. I have dealt with friction between absl and builtin logging interop in personal projects in the past, so I believe I have a first impression of what issues can arise there. Nevertheless, it would help to have the details spelled out by someone on the team as you suggested. Let me know if you are interested!

**Comment by froystig** [comment]
Ideally we could still use absl optionally but hide that behind a Python `logging` interface. What do you think of the following?

1. Introduce a `jax.config.jax_use_absl_logging` flag, off by default.
2. Set up a module (say, `jax.logging`) that offers the interface of Python's `logging`. Have this forward to Python `logging` by default, or delegate to `absl.logging` where applicable if the config flag says to do that instead.
3. Change jax internals to use `jax.logging` across the codebase. This will require e.g. moving away from calls to absl's `vlog` and instead directly calling `jax.logging.debug` etc.
