### ISSUE TITLE
Modifying self in a scan function.

### ISSUE THREAD

**Issue by HHalva** [google/jax#6335]
Not sure if this is a bug or intended behaviour. I am using scan within in a class function. 

I have random key stored in the class i.e. 'self.key'. In order to access it, the function I scan over is something like

```python
def _sample_step(self, prev_val, xs):
  self.key, sub_key = jrandom.split(self.key)
  new_val = sample_distribution(sub_key, prev_val)
  return new_val, prev_val

def gen_data(self, init_x):
  init_val = sample(self.key, init_x)
  vals = scan(_sample_step, init_val, None, length=100)
```
I found that this doesn't work correctly. There is no stochasticity in the values generated by scan, which I suspect is because self.key isn't modified within scan? I can't check because if I try to access self.key after scan, then I get
```
Traced<ShapedArray(uint32[2])>with<DynamicJaxprTrace(level=1/0)> 
```

Now, I know the better way to do this is to split the self.key into 100 outside of scan and pass that as 'xs', but was just wondering why my initial method didn't work.

**Comment by jakevdp** [comment]
JAX transforms only work on pure functions, i.e. functions without side effects (see [🔪 JAX - The Sharp Bits 🔪: Pure Functions](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#pure-functions). Modifying `self` within the function is a side-effect, and so it is not compatible with functions used in JAX transforms.

For some more discussion of stateful computations in JAX, you might find this section of the documentation helpful: https://jax.readthedocs.io/en/latest/jax-101/07-state.html

**Comment by HHalva** [comment]
Thanks, that's what I suspected. Hadn't seen the second link though -- useful!
