### ISSUE TITLE
add depthwise convolution (expose `feature_group_count` in lax conv ops)

### ISSUE THREAD

**Issue by mattjj** [google/jax#635]
We should expose [XLA's `feature_group_count`](https://www.tensorflow.org/xla/operation_semantics#convwithgeneralpadding_convolution).

We might wait for people to +1 this issue though.

cc @jekbradbury @dmrd

**Comment by hawkinsp** [comment]
@jheek added this to `lax`. If there is desire for this in `stax` too we can open a new issue for it.
