### ISSUE TITLE
Confusing `vmap` user experience when passing in `False` into `in_axes`

### ISSUE THREAD

**Issue by avital** [google/jax#6372]
`False` is interpreted as 0 in the `in_axes` argument to `jax.vmap`. This is an invalid value (and some users may expect it to behave like `None`). See this code:

```python
import jax.numpy as jnp

def f(x, y):
  return jnp.sum(x) + jnp.sum(y)

print(jax.vmap(f, in_axes=[False, 0])(arr, arr))
print(jax.vmap(f, in_axes=[None, 0])(arr, arr))
print(jax.vmap(f, in_axes=[0, 0])(arr, arr))
```

prints

```
[ 6 14]
[13 17]
[ 6 14]
```

The `vmap` documentation states that each item in `in_axes` must be either an integer or None. @mbz was confused by this and accidentally thought that `False` would behave like `None`. But instead it's interpreted as 0.

It would be good to raise an error for users accidentally using `False` in `in_axes`.

**Comment by mattjj** [comment]
Thanks for raising this! I think the trouble is [on this line](https://github.com/google/jax/blob/f1a6397948a179665b7977592949dc33093e9b33/jax/api.py#L1263), due to the fact that `isinstance(True, int)` (like `issubclass(bool, int)`) is True in Python.

**Comment by avital** [comment]
Thanks for the swift response!

**Comment by mattjj** [comment]
Anything for you, @avital !
