### ISSUE TITLE
Difference in behaviour under jax.experimental.enable_x64 for numpy vs jax.numpy

### ISSUE THREAD

**Issue by tberghammer** [google/jax#6407]
Take the following two implementation, where the only difference is that the first one used `np.array` while the second one is using `jnp.array`:
```
def fun():
  with jax.experimental.enable_x64():
    return jax.lax.rng_bit_generator(
        np.array((1, 2)).astype(np.uint64),
        (1024, 1024))
jax.xla_computation(fun)().as_hlo_text()
```

```
def fun():
  with jax.experimental.enable_x64():
    return jax.lax.rng_bit_generator(
        jnp.array((1, 2)).astype(np.uint64),
        (1024, 1024))
jax.xla_computation(fun)().as_hlo_text()
```

I would expect the two implementation to be equivalent (i.e. result in the same HLO text) but the X64 scope seemingly gets ignored in the first case (i.e. rng_bit_generator gets an int32 input) while works as expected in the second case.

The same behaviour is observable if the function is run under `jax.jit` but it is a bit harder to observe it there.

**Comment by jakevdp** [comment]
Thanks for the report! I think this is similar to an issue we've recently been discussing (I can't find the link right now) that essentially comes down to the fact that dtypes for constants are canonicalized at trace-time, and this might cause them to be wrong at compile time when using x64 context (incidentally, this is one of the main reasons these context managers are still in `jax.experimental` and not recommended for regular use).

**Comment by jakevdp** [comment]
I think maybe @mattjj was looking at this issue last week?

**Comment by jakevdp** [comment]
Update: we are in the process of deprecating the `enable_x64()` context manager (and the X64 flag altogether), because it's not clear its semantics can be made to work with JAX's transforms, which will obviate this issue. This deprecation is tracked in #8178
