### ISSUE TITLE
bug in jax.numpy.linalg.inv?

### ISSUE THREAD

**Issue by jkitchin** [google/jax#646]
The inv function in the latest version seems to return nan for me:

```
import jax.numpy as np

print(np.linalg.inv(np.array([[0.0, 1.0, 1.0],
                                               [1.0, 0.0, 1.0],
                                               [1.0, 1.0, 0.0]])))
```

#+RESULTS:
: [[nan nan nan]
:  [nan nan nan]
:  [nan nan nan]]

That array is definitely invertable:

```
import numpy as np

print(np.linalg.inv(np.array([[0.0, 1.0, 1.0],
                              [1.0, 0.0, 1.0],
                              [1.0, 1.0, 0.0]])))
```

#+RESULTS:
: [[-0.5  0.5  0.5]
:  [ 0.5 -0.5  0.5]
:  [ 0.5  0.5 -0.5]]

The root seems to be in the call to qr, and eventually to qr_p in lax_linalg, which is returning the nan arrays.

**Comment by hawkinsp** [comment]
Thanks for the report! That's unfortunate. We'll look into it. I suspect the issue is in the QR decomposition implementation which JAX calls.

(On CPU, we should also call LAPACK's implementation of QR, and np.linalg.inv should probably use an LU decomposition anyway.)

**Comment by jkitchin** [comment]
Here is a way to get a differentiable inverse with LU decomposition (on a cpu):

```
def differentiable_inv(A):
    # P A = L U
    # P = L U Ainv
    #   = L U X = P
    # U X = d
    # L d = P  -> solve for d
    # U X = d  -> solve for X which is Ainv

    lu, pivots = jax.lax_linalg.lu(A)
    permutation = jax.lax_linalg.lu_pivots_to_permutation(pivots, len(A))

    U = np.tril(lu.T).T
    L = np.tril(lu,-1) + np.eye(len(A))
    P = np.eye(3)[permutation]

    d = jax.lax_linalg.triangular_solve(L, P,
                                    lower=True)

    # I do not know why we need left_side=True here.
    return jax.lax_linalg.triangular_solve(U, d, left_side=True)
```

**Comment by hawkinsp** [comment]
This turns out to be a tiny bug in the computation of the elementary Householder reflector in the case that the element on the diagonal is exactly 0. Fix coming shortly. For now, adding any non-zero constant (e.g., epsilon) to the diagonal matrix elements would probably fix the problem.

**Comment by hawkinsp** [comment]
This is now fixed at git head, but requires a `jaxlib` rebuild (or wait for us to make another `jaxlib` wheel release)
