### ISSUE TITLE
reduce_window produces negative shapes

### ISSUE THREAD

**Issue by jjaraalm** [google/jax#6487]
Invalid window dimensions and/or strides produce an output array which can have negative shape. In most cases this will be caught elsewhere, but errors should probably be raised in `reduce_window` instead.

```python
import jax.numpy as jnp
import jax.lax
x = jnp.ones((5, 1))
y = jax.lax.reduce_window(x, 0., jnp.maximum, [1, 5], [1, 1], 'valid')
print(y.shape)
# (5, -3)
```

**Comment by jakevdp** [comment]
Which version of JAX and jaxlib are you using? On the most recent releases (jax v0.2.12 and jaxlib v0.1.65) I see `(5, 0)` when running this code.

**Comment by jjaraalm** [comment]
I'm using jax v0.2.9 and jaxlib v0.1.59, but if this is fixed in newer releases that's great.

**Comment by jakevdp** [comment]
I'm not sure which change along the way affected this, but it does appear to be fixed.

**Comment by jakevdp** [comment]
Possibly #6010?

**Comment by jjaraalm** [comment]
SGTM
