### ISSUE TITLE
[jax2tf] Support untraced arguments in jax2tf.convert

### ISSUE THREAD

**Issue by gnecula** [google/jax#6494]
Filed based on a suggestion by Eirikur Agustsson.

For a `f_jax(*args, k=v)` we may want to convert a specialization of `f_jax` for each value of `k`. In this case the argument `k` is not even traced, which is helpful if its values are non-arrays, e.g., strings. 

Here is the suggestion by Eirikur:

```
import functools
from typing import Sequence
def convert_to_tf(static_argnames: Sequence[str] = (), **convert_kwargs):
  """A wrapper for jax2tf.convert that handles static (non-traced) arguments.

  Args:
    static_argnames: A sequence of named arguments that should not be traced.
    convert_kwargs: kwargs for jax2tf.convert(...)

  Returns:
    the appropriate decorator.
  """
  _converted_cache = {}
  def decorator(jax_fn):
    def converted(*args, **kwargs):
      # Let's create (name, val) pairs for those static arguments which are
      # found in **kwargs. We can use this as a dict key.
      kwarg_keys = list(kwargs.keys())
      static_name_val_tuples = tuple([(name, kwargs.pop(name)) for name in static_argnames if name in kwarg_keys])
      static_kwargs = dict(static_name_val_tuples)
      # Now static arguments have been removed from **kwargs and put into 
      # static_kwargs. Now let's only convert with jax2tf if we haven't done
      # so before.
      if static_name_val_tuples in _converted_cache:
        _converted = _converted_cache[static_name_val_tuples]
      else:
        _converted = jax2tf.convert(functools.partial(jax_fn, **static_kwargs), **convert_kwargs)
        _converted_cache[static_name_val_tuples] = _converted
      return _converted(*args, **kwargs)
    return converted
  return decorator

#Let's test out, this should make a TF function, but only trace `image`.

@convert_to_tf(static_argnames=('scale', 'method'))
def upscale(image, scale=2, method=jax.image.ResizeMethod.LANCZOS5):
  """Upscale a image batch spatially by `scale` (default 2x)."""
  image = jnp.asarray(image)
  batch, height, width, channels = image.shape
  return jax.image.resize(
      image, [batch, height * scale, width * scale, channels],
      method=method)

```

**Comment by gnecula** [comment]
I am wondering how this behaves though if some arguments passed to the converted function are things that JAX does not understand, e.g., tf.Tensor or tf.TensorSpec?

**Comment by gnecula** [comment]
Closing this to reflect that we won't be implementing this for now.

**Comment by relational** [comment]
@gnecula , regarding  your proposed solution with partial, AFAIU it would mean that a seconda call to the converted function, with an identical `k=jax_value_for_k`, would result in a second jax2tf conversion as the partial() is created each time.

A workaround would be to just memoize the conversion:

```
@functools.lru_cache(maxsize=None)
def _converted_f(**static_kwargs):
  return jax2tf.convert(functools.partial(jax_scale_space_blur, **static_kwargs))

def f_tf(*tf_args, **static_kwargs):
  return _converted_f(**static_kwargs))(*tf_args)
```
Which behaves as follows:
```
# Here jax2tf.convert gets used.
f_tf(tf_val1, foo='bar')

# Here we hit the cache.
f_tf(tf_val2, foo='bar)

# Now jax2tf.convert again gets used.
f_tf(tf_val3, foo='zar')
```

**Comment by gnecula** [comment]
At the moment the jax2tf converter does no caching whatsoever. Each invocation of the converted function will result in a fresh conversion. I think that this is not so surprising, if one thinks that the "conversion" really means a different form of interpretation: jax.numpy are interpreted in terms of JAX primitives which are then interpreted in terms of TF ops, which are then interpreted by the TF eager executor. 

Users can add their caching separately, e.g., as you propose. In other cases, users can use standard TF mechanism for tracing the function to a TF graph, which can then be executed multiple times.
