### ISSUE TITLE
numerical NaN in apparently random instances following vmap of nested loops using jax.experimental.loops

### ISSUE THREAD

**Issue by whbdupree** [google/jax#6499]
Sorry for terrible title. Please feel free to edit it.
See example below. The function sim1() has nested for loops. The function sim2 skips the first for loop.  Two of the five results of sim1() return NaNs. None of the five results of sim2() return NaNs. Both functions should return the same arrays.

Results on my computer:
nested loops result with NaN:
[[2.5682993  0.11878163 1.0513388 ]
 [2.5682993  0.11878163 1.0513388 ]
 [       nan        nan        nan]
 [       nan        nan        nan]
 [2.5682993  0.11878163 1.0513388 ]]
no nest; no Nan:
[[2.5682993  0.11878163 1.0513388 ]
 [2.5682993  0.11878163 1.0513388 ]
 [2.5682993  0.11878163 1.0513388 ]
 [2.5682993  0.11878163 1.0513388 ]
 [2.5682993  0.11878163 1.0513388 ]]

The code

```python
from jax import jacfwd,vmap
from jax import numpy as jnp
from jax.experimental import loops
from jax.tree_util import Partial

## numerical simulation: activation function 
def phi(g,x,x0):
    return g*jnp.max(jnp.array([0.,x-x0]))

## numerical simulation: derivatives
def f( u, p ):
    x,y,z = u
    ix = 5.*x - 1.*y - z
    dx = ( phi( 1.,ix,-1. ) - x ) / 10.
    iy = 10.*x - 0.5*y
    dy = ( phi( 4.,iy,25. ) - y ) / 2.
    dz  = ( 7.*x - z/p ) / 500.
    return jnp.array([dx,dy,dz])

## numerical simulation: integrator function
def g(ynext,ylast,p):
    return ynext - 0.1 * f(ynext,p) - ( ylast + 0.1 * f(ylast,p) )
Jcn = jacfwd( g)


## simulation function with nested loops:
def sim1(p,u0):
    with loops.Scope() as s:
        s.q = u0
        s.qlast = u0
        for j in s.range(1):
            for k in s.range(2):
                s.q = s.q - jnp.matmul(
                    jnp.linalg.inv( Jcn(s.q,s.qlast,p) ),
                    g( s.q, s.qlast, p ) )
            s.qlast = s.q
    return s.q

## simulation function without nested loops:
def sim2(p,u0):
    with loops.Scope() as s:
        s.q = u0
        s.qlast = u0
        for k in s.range(2):
            s.q = s.q - jnp.matmul(
                jnp.linalg.inv( Jcn(s.q,s.qlast,p) ),
                g( s.q, s.qlast, p ) )
    return s.q

u0 = jnp.array( [2.3728049, 0.,        1.0448406])
vsim1 = vmap(Partial(sim1,u0=u0))
vsim2 = vmap(Partial(sim2,u0=u0))
p = jnp.array([1.]*5)
q1 = vsim1(p)
q2 = vsim2(p)
print('nested loops result with NaN:')
print(q1)
print('no nest; no Nan:')
print(q2)

```

- [ ] If applicable, include full error messages/tracebacks.

**Comment by whbdupree** [comment]
I just tested this and I am able to reproduce it on google collab.

**Comment by hawkinsp** [comment]
Assigned to @gnecula . However, I will note that `jax.experimental.loops` is, like it says on the tin, experimental, and so comes with fewer guarantees...

**Comment by hawkinsp** [comment]
jax.experimental.loops was removed from JAX. Closing as stale.
