### ISSUE TITLE
jacfwd through while_loop

### ISSUE THREAD

**Issue by proteneer** [google/jax#650]
Are there plans for supporting jacfwd for while_loops? Tensorflow afaik supports gradients for backprop'd while_loops. I'm really interested in jax's fwd-mode support as well.

**Comment by hawkinsp** [comment]
Forward-mode automatic differentiation for while loops is quite feasible (much easier than reverse mode, actually). It just requires that we define a jvp rule for `while_loop`, which is not hard to do since it's just the original loop executed with dual-number semantics.

**Comment by mattjj** [comment]
We do need to do some AD lattice fixed point business (like we do on the differentiable-scan branch). It might make sense to wait for that branch to land, then reuse those tools.

**Comment by mattjj** [comment]
My rule of thumb is that while_loop constructs can help with compile times (potentially a lot!), but don't help execution times (and can even hurt in some cases). Is that the kind of performance improvement you want, i.e. compile times?

**Comment by proteneer** [comment]
It depends on the scaling of the compile time, if its O(number of iterations in the for loop) then it'd be pretty catastrophic. But otherwise it might not be a big issue.

**Comment by mattjj** [comment]
I think it's worse than that: XLA optimizations tend to make compile times be super-linear in the size of the graph.

Sounds like you do want jvp (and hence jacfwd) through while_loop then.

**Comment by proteneer** [comment]
I've also verified that the compile times are indeed super linear.

For highly efficient fixed-step optimizers, eg. L-BFGS, where we know roughly apriori convergence can happen in say roughly 30 steps, this isn't so so bad. But for long time scale dynamics this is definitely a real mess.

I'm also playing around with differentiating through experimental.optimizers now - super excited to see all the awesome stuff you guys added in there.

**Comment by mattjj** [comment]
Thanks for the report!

We're almost done with a `scan` primitive, which will be both forward- and reverse-mode differentiable, and includes for-loops and folds as special cases. We can separately make while_loop forward-mode differentiable, likely reusing much of the same machinery, but I suspect that `scan` will be a very useful differentiable loop structure. Keep an eye out for that!

**Comment by proteneer** [comment]
I'm not familiar with the xla lingo of "scan" - but it sounds promising

I've also just verified that the current implementations of experimental.optimizers.sgd is straight-up differentiable if I just use a vanilla for loop. 

https://github.com/proteneer/timemachine/pull/85/files

I'll be testing things like adam/momentum as well later on. It's possible I will be rewriting some of my integrators as jax optimizers once I better understand the internals.

**Comment by georgedahl** [comment]
@proteneer I believe you should be able to try out scan now. Please report back with how it goes.

**Comment by mattjj** [comment]
@georgedahl there is something slightly better we can do for jacfwd-through-while-loops, though, so scan doesn't quite close this issue (unless @proteneer doesn't need the slightly-better thing described below).

We can use `scan` to forward (or reverse) differentiate a while-loop that has a fixed number of iterations (aka a for loop) by writing something like this:

```python
from __future__ import division

from jax import lax
import jax.numpy as np

def fori_loop(num_iters, fun, init):
  dummy_inputs = np.zeros((num_iters, 0))
  out, _ = lax.scan(lambda x, dummy: (fun(x), dummy), init, dummy_inputs)
  return out

print(fori_loop(10, lambda x: x + 2, 3))
```

That doesn't use up any extra memory or anything. But it does require the number of iterations to be known.

In principle we could do forward-mode differentiation of a `lax.while_loop` without knowing the number of iterations. (And we can reuse a lot of the scan machinery to do it.)

@proteneer does scan work for you, or do you care about the case where the number of loop iterations is unknown?

**Comment by proteneer** [comment]
This looks really cool - I haven't had a chance to play with this yet. In terms of fix iterations, it depends on the application. We anticipate using this optimizers with known trip counts as well as ones that predicate on a test of convergence (eg. on-the-fly detection of SGD convergence). 

Let me play with this a little bit first.

**Comment by proteneer** [comment]
For a fixed number of iterations, this was pretty straightforward to implement. Note that I couldn't just set xs to zero since optimizers as written need the iteration count to be provided, so as opposed to allocating a ```np.zeros((iterations, 0))``` requiring O(1) ram, I instead allocated ```np.arange(iterations)``` requiring O(iterations) ram. 

I've tested JITting both the scan itself as well as its derivative:

https://github.com/proteneer/timemachine/pull/87/files

Timings:
```
Old version:

real	1m42.888s
user	1m43.148s
sys	0m0.857s

New version:

real	0m4.244s
user	0m5.040s
sys	0m0.373s
```
Nice! I can probably get away with a fixed trip count for now, though I definitely see a need for variable trip-counts in the future.

**Comment by mattjj** [comment]
Cool! Really great to hear this is useful for you already.

For the iteration count, you might be able to put it in the loop carry, as in (untested):

```python
def apply_carry(carry, _):
    i, x = carry
    g = grad_fn(get_params(x))[0]
    return (i + 1, opt_update(i, g, x)), _
opt_state, _ = jax.lax.scan(apply_carry, (0, opt_state), jnp.zeros((75, 0)))
```

In general the loop carry (and the input/output) can be arbitrary pytrees, like tuples or nested tuples or dicts or whatever. The scan function will scan over the leading axis of the leaves.

**Comment by proteneer** [comment]
Including iteration count as part of the carry is a much better idea. I guess this still doesn't solve the need to pre-specify trip count, but I guess could run the above code in another vanilla for loop in batches

**Comment by proteneer** [comment]
It looks like lattice_join doesn't like integer trip count types, as there seems to be a type mismatch:
```
self = <test_optimizers.TestOptimizeGeometry testMethod=test_minimize_CH2>

    def test_minimize_CH2(self):
    
        opt_init, opt_update, get_params = optimizers.sgd(5e-2)
    
        x0 = onp.array([
            [1.0, 0.2, 3.3], # H
            [-0.5,-1.1,-0.9], # C
            [3.4, 5.5, 0.2], # H
        ], dtype=onp.float64)
    
        # ideal bond lengths are 3.0 and 5.5
        k = 10.0
        b0 = 3.0
        b1 = 5.5
        initial_params = onp.array([k, b0, b1], dtype=onp.float64)
    
        param_idxs = onp.array([
            [0,1],
            [1,2],
        ], dtype=onp.int32)
    
        bond_idxs = onp.array([
            [0,1],
            [1,2]
        ], dtype=onp.int32)
    
        def minimize_structure(test_params):
    
            energy_fn = functools.partial(
                bonded.harmonic_bond,
                params=test_params,
                box=None,
                param_idxs=param_idxs,
                bond_idxs=bond_idxs)
    
            grad_fn = jax.jit(jax.grad(energy_fn, argnums=(0,)))
            opt_state = opt_init(x0)
    
            # use lax.scan, way faster compilation times.
            def apply_carry(carry, _):
                i, x = carry
                g = grad_fn(get_params(x))[0]
                new_state = opt_update(i, g, x)
                new_carry = (i+1, new_state)
                return new_carry, _
    
            carry_final, _ = jax.lax.scan(apply_carry, (0, opt_state), jnp.zeros((75, 0)))
    
            trip, opt_final = carry_final
    
            assert trip == 75
    
            x_final = get_params(opt_final)
            test_b0 = jnp.linalg.norm(x_final[1] - x_final[0])
            test_b1 = jnp.linalg.norm(x_final[2] - x_final[1])
    
            return test_b0, test_b1
    
        # this is fine
        tb0, tb1 = minimize_structure(initial_params)
    
        onp.testing.assert_almost_equal(b0, tb0, decimal=2)
        onp.testing.assert_almost_equal(b1, tb1, decimal=2)
    
        # test meta-optimizer by optimizing through an optimizer
        # ground-truth real bond lengths
        ib0, ib1 = 1.0, 2.0
    
        def loss(test_params):
            t0, t1 = minimize_structure(test_params)
            loss = (t0 - ib0)**2 + (t1 - ib1)**2
            return loss
    
        loss_opt_init, loss_opt_update, loss_get_params = optimizers.sgd(5e-2)
    
        # minimze loss
        # very slow for long loops (> 80s), since JITing is super-linear
        # (ytz): we can speed this up significantly when jax.while_loop is
        # differentiable.
        # loss_grad_fn = jax.jit(jax.grad(loss, argnums=(0,)))
        loss_grad_fn = jax.grad(loss, argnums=(0,))
        loss_opt_state = loss_opt_init(initial_params)
    
        for epoch in range(1000):
            # print("epoch", epoch, "parameters", loss_get_params(loss_opt_state))
>           loss_grad = loss_grad_fn(loss_get_params(loss_opt_state))[0]

tests/test_optimizers.py:100: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../jax/jax/api.py:229: in grad_f
    _, g = value_and_grad_f(*args, **kwargs)
../jax/jax/api.py:273: in value_and_grad_f
    ans, vjp_py = vjp(f_partial, *dyn_args)
../jax/jax/api.py:724: in vjp
    out_primal, out_vjp = ad.vjp(jaxtree_fun, primals_flat)
../jax/jax/interpreters/ad.py:105: in vjp
    out_primal, pval, jaxpr, consts = linearize(traceable, *primals)
../jax/jax/interpreters/ad.py:94: in linearize
    jaxpr, out_pval, consts = pe.trace_to_jaxpr(jvpfun, in_pvals)
../jax/jax/interpreters/partial_eval.py:391: in trace_to_jaxpr
    jaxpr, (out_pval, consts, env) = fun.call_wrapped(pvals)
../jax/jax/linear_util.py:147: in call_wrapped
    ans = self.f(*args, **dict(self.params, **kwargs))
tests/test_optimizers.py:84: in loss
    t0, t1 = minimize_structure(test_params)
tests/test_optimizers.py:61: in minimize_structure
    carry_final, _ = jax.lax.scan(apply_carry, (0, opt_state), jnp.zeros((75, 0)))
../jax/jax/lax/lax_control_flow.py:559: in scan
    forward=True, length=length, jaxpr=jaxpr)
../jax/jax/core.py:120: in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
../jax/jax/interpreters/ad.py:248: in process_primitive
    primal_out, tangent_out = jvp(primals_in, tangents_in, **params)
../jax/jax/lax/lax_control_flow.py:616: in _scan_jvp
    forward=forward, length=length, jaxpr=jaxpr_jvp)
../jax/jax/core.py:120: in bind
    out_tracer = top_trace.process_primitive(self, tracers, kwargs)
../jax/jax/interpreters/partial_eval.py:93: in process_primitive
    return partial_eval(self, *tracers, **params)
../jax/jax/lax/lax_control_flow.py:671: in _scan_partial_eval
    *in_consts, forward=forward, length=length, jaxpr=jaxpr_1)
../jax/jax/core.py:117: in bind
    return self.impl(*args, **kwargs)
../jax/jax/lax/lax_control_flow.py:577: in _scan_impl
    carry, ys = fori_loop(0, length, body_fun, (init, ys_init))
../jax/jax/lax/lax_control_flow.py:84: in fori_loop
    _, result = while_loop(while_cond_fun, while_body_fun, (lower, init_val))
../jax/jax/lax/lax_control_flow.py:133: in while_loop
    assert carry_aval == core.lattice_join(carry_aval, carry_aval_out)
../jax/jax/core.py:472: in lattice_join
    return y.join(x)
../jax/jax/core.py:560: in join
    return AbstractTuple(map(lattice_join, self, other))
../jax/jax/util.py:43: in safe_map
    return list(map(f, *args))
../jax/jax/core.py:472: in lattice_join
    return y.join(x)
../jax/jax/core.py:560: in join
    return AbstractTuple(map(lattice_join, self, other))
../jax/jax/util.py:43: in safe_map
    return list(map(f, *args))
../jax/jax/core.py:472: in lattice_join
    return y.join(x)
../jax/jax/core.py:560: in join
    return AbstractTuple(map(lattice_join, self, other))
../jax/jax/util.py:43: in safe_map
    return list(map(f, *args))
../jax/jax/core.py:472: in lattice_join
    return y.join(x)
../jax/jax/core.py:560: in join
    return AbstractTuple(map(lattice_join, self, other))
../jax/jax/util.py:43: in safe_map
    return list(map(f, *args))
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

x = ShapedArray(int64[]), y = ()

    def lattice_join(x, y):
      if x is None:
        return y
      elif y is None:
        return x
      elif isinstance(x, type(y)):
        return y.join(x)
      elif isinstance(y, type(x)):
        return x.join(y)
      else:
>       raise TypeError((x, y))
E       TypeError: (ShapedArray(int64[]), ())
```

**Comment by mattjj** [comment]
Thanks for finding that! Can you open a bug with the repro, and we'll squash it asap?

**Comment by proteneer** [comment]
Filed via #711
