### ISSUE TITLE
jitted vmaped minimize function slows 100x after 31 executions

### ISSUE THREAD

**Issue by JohnGoertz** [google/jax#6559]
I've used `jax.scipy.optimize.minimize` for parameter estimation of an ODE system. After vmapping and jitting this function to perform estimation for an array of observations, I benchmarked it within a loop. Bizarrely, each execution takes about 0.1 ms until the 32nd iteration, after which it takes ~15ms. Interestingly, if you remove the 64-bit precision and just use the default 32-bit, on the 32nd iteration the kernel just locks up.

Now, I'm not necessarily intending to use a `for` loop like way, but it seems to suggest something bad is happening behind the scenes.... Maybe a memory leak?

JAX version: 0.2.12
OS: Ubuntu (WSL on Windows 10)
RAM: 16GB

```python
import jax
import jax.numpy as jnp
from jax.experimental.ode import odeint as odeint
from jax.scipy.optimize import minimize as minimize
from jax.config import config
config.update('jax_enable_x64', True)

from time import time as timer

def rhs(C, t, tau): 
    A, B = C
    dA = -1./tau*A
    dB = -dA
    return jnp.array([dA, dB])

def solve(t, params):
    A0, B0, tau = params
    C0 = jnp.array([A0, B0])
    sol = odeint(rhs, C0, t, tau)
    return sol[:,-1]

def get_loss(params,data,t):
    model = solve(t,params)
    MSE = jnp.mean(jnp.square(model-data))
    return MSE
    
def fit_system(A0,data,t):
    B0 = 0.5
    
    def loss(params):
        A0, tau = params
        _params = jnp.array([A0, B0, tau])
        return get_loss(_params, data, t)
    
    tau_guess = 40.
    init = jnp.array([A0[0],tau_guess])
    
    fit = minimize(loss, x0=init, method='BFGS')
    A0_est, tau_est = fit.x
    return fit.x
    
t = jnp.arange(100.)
A0 = 2.
B0 = 0.5
C0 = jnp.array([A0,B0])
tau = 20.
params = jnp.array([A0, B0, tau])
y = solve(t, params)

ys = jnp.tile(y,[10,1])
A0_guess = jnp.tile(1.5,[10,1])
ts = jnp.tile(t,[10,1])

vfit = jax.jit(jax.vmap(fit_system))
print('Compilation time:')
begin = timer()
vfit(A0_guess,ys,ts)
print(f'{(timer()-begin):.1f} s')
print('')

print('Execution time:')
for i in range(50):
    begin = timer()
    vfit(A0_guess,ys,ts)
    print(f'{i}: {(timer()-begin)*10**3:.3f} ms')
```
Output:
```
Compilation time:
24.1 s

Execution time:
0: 0.537 ms
1: 0.199 ms
2: 0.170 ms
3: 0.220 ms
4: 0.162 ms
5: 0.162 ms
6: 0.214 ms
7: 0.234 ms
8: 0.154 ms
9: 0.151 ms
10: 0.150 ms
11: 0.213 ms
12: 0.146 ms
13: 0.144 ms
14: 0.160 ms
15: 0.151 ms
16: 0.062 ms
17: 0.204 ms
18: 0.162 ms
19: 0.105 ms
20: 0.203 ms
21: 0.099 ms
22: 0.178 ms
23: 0.142 ms
24: 0.155 ms
25: 0.145 ms
26: 0.135 ms
27: 0.140 ms
28: 0.158 ms
29: 0.158 ms
30: 0.157 ms
31: 11.056 ms
32: 16.816 ms
33: 17.240 ms
34: 16.011 ms
35: 16.443 ms
36: 16.680 ms
37: 17.030 ms
38: 16.997 ms
39: 17.344 ms
40: 17.926 ms
41: 17.559 ms
42: 17.862 ms
43: 19.437 ms
44: 17.176 ms
45: 16.719 ms
46: 16.932 ms
47: 17.004 ms
48: 16.342 ms
49: 16.119 ms
```

**Comment by clemisch** [comment]
JAX executes (jit'ed) functions asynchronously, i.e. they return before the values in the array are computed. You can tell JAX to block until computation of an array is finished by adding `.block_until_ready()` to the function call:

```python
print('Execution time:')
for i in range(50):
    begin = timer()
    vfit(A0_guess,ys,ts).block_until_ready()
    print(f'{i}: {(timer()-begin)*10**3:.3f} ms')
```

gives consistent timings for me.

**Comment by hawkinsp** [comment]
The other piece of information that may help here is that there is a queue of size 32 of deferred operations. Once the queue fills up, JAX must wait for an existing operation to complete before it can enqueue another one. (The precise details here may change, but that's why you see a different behavior on the 32nd iteration.)

Hope that helps!

**Comment by hawkinsp** [comment]
(As for the non-termination in float32: I think something is failing to converge in float32.)

**Comment by JohnGoertz** [comment]
Ah, thanks for the explanation, that helps! `.block_until_ready()` does indeed make it consistent. For some reason I had convinced myself that only mattered on a GPU...
