### ISSUE TITLE
segment_sum primitives / advanced indexing in jax.ops.index_add

### ISSUE THREAD

**Issue by proteneer** [google/jax#658]
Would it be useful to others (aside from me) to have better support of sorted and unsorted segment_sums?

https://www.tensorflow.org/api_docs/python/tf/math/unsorted_segment_sum
https://www.tensorflow.org/api_docs/python/tf/math/segment_sum

In numpy one way to do unsorted segment sums is to sort then call np.add.reduceat, but this doesn't seem to be in jax or autograd:

```
>>> import jax.numpy as np
np.add
>>> np.add
<function _one_to_one_binop.<locals>.<lambda> at 0x1430cdbf8>
>>> np.add.reduceat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'reduceat'
```

**Comment by hawkinsp** [comment]
Does `jax.ops.index_add` do what you need? It seems roughly equivalent to `unsorted_segment_sum`.

https://jax.readthedocs.io/en/latest/_autosummary/jax.ops.index_add.html#jax.ops.index_add

**Comment by hawkinsp** [comment]
Ah, I guess it does not *yet* because it does not support advanced indexing. We should fix that.

**Comment by proteneer** [comment]
Nice! Would it be hard to support the basic operators +,-,*,/ on top of add?

**Comment by proteneer** [comment]
After playing around a little bit with the numpy version of advanced index assignment, I take it the idea is to implement the unsorted/sorted segment sums using something similar to:
``` python
ys = np.arange(5)
idxs = [0,0,1,0,1]
sums = np.zeros(2) # two slots
seg_sum = jax.ops.index_add(sums, jax.ops.index[idxs], ys) 
```

**Comment by hawkinsp** [comment]
Yup, that's the idea!

**Comment by user799595** [comment]
It looks like the current way of doing `np.add.reduceat` is `jnp.ufunc(jnp.add, 2, 1).reduceat`.
