### ISSUE TITLE
Support negative numpy.split indices

### ISSUE THREAD

**Issue by juliuskunze** [google/jax#6599]
```python
import numpy as np
np.split([1, 2, 3], [-1])
```

works, while

```python
import jax.numpy as jnp
jnp.split(jnp.array([1, 2, 3]), [-1])
```

fails.

**Comment by saklani** [comment]
Hi! I've got some time. I'd like to take up this issue.

**Comment by jakevdp** [comment]
Awesome! Please take a look at the [contributing](https://jax.readthedocs.io/en/latest/contributing.html#contributing-code-using-pull-requests) doc, and please feel free to reach out if you have questions.

Feel free to open a draft pull request if that would be helpful :grin:
