### ISSUE TITLE
Please consider adding jax.numpy.divide

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#6609]
Currently, `jax.numpy.divide` [points to](https://github.com/google/jax/blob/master/jax/_src/numpy/lax_numpy.py#L571) `jax.numpy.true_divide`.  This means that it doesn't support [the parameters](https://numpy.org/doc/stable/reference/generated/numpy.divide.html?highlight=divide#numpy.divide) `where` and `out`, which can be used to conditionally set the output without warnings:
```python
In [3]: import numpy as np

In [4]: np.divide(np.ones(4), np.arange(4))
<ipython-input-4-ddd914450938>:1: RuntimeWarning: divide by zero encountered in true_divide
  np.divide(np.ones(4), np.arange(4))
Out[4]: array([       inf, 1.        , 0.5       , 0.33333333])

In [5]: np.divide(np.ones(4), np.arange(4), where=np.arange(4) > 0, out=np.zeros(4))
Out[5]: array([0.        , 1.        , 0.5       , 0.33333333])
```

**Comment by jakevdp** [comment]
Thanks for the request! The `out` and `where` keywords are properties of numpy's ufuncs, and JAX wrappers generally do not support these. In the case of `out`, it's for good reason: JAX arrays are immutable, so it's not possible to update the out array in-place with the result.

In the case of `where`, JAX offers the same functionality by composition. In numpy, compositional approaches can be inefficient because they involve creating temporary arrays; this is one reason numpy ufuncs provide options like `where`. In JAX the XLA compiler can optimize sequences of operations, so composition is not a problem.

In JAX, you could do the above operation like this:
```python
>>> import jax.numpy as jnp
>>> x = jnp.ones(4)
>>> y = jnp.arange(4)
>>> jnp.where(y > 0, jnp.divide(x, y), 0)
DeviceArray([0.        , 1.        , 0.5       , 0.33333334], dtype=float32)
```

**Comment by NeilGirdhar** [comment]
@jakevdp Thanks for the thorough explanation!  The only problem with your workaround is that if `JAX_DEBUG_NANS` is true, then it will raise if you try to do `jax.divide(y, y)`—even if you're inside a `jnp.where`.

I've been trying to think of a perfect workaround.  Any ideas?

**Comment by jakevdp** [comment]
If that's a concern, you could use a double where:
```python
jnp.where(y > 0, jnp.divide(x, jnp.where(y != 0, y, 1)), 0)
```
This pattern also turns out to be helpful in the case of [avoiding NaNs in autodiff](https://jax.readthedocs.io/en/latest/faq.html#gradients-contain-nan-where-using-where).

**Comment by NeilGirdhar** [comment]
@jakevdp Nice, that's really clever!  I guess I'll wrap that up in a function like this:
```python
def divide(x: Array, y: Array, *, where: Optional[Array] = None, out: Optional[Array] = None):
    if where is None:
        return jnp.true_divide(x, y)
    x_prime = jnp.where(where, x, 1.0)
    y_prime = jnp.where(where, y, 1.0)
    quotient = jnp.true_divide(x_prime, y_prime)
    return jnp.where(where, quotient, out)
```
I think `numpy`'s use of `out` here is a quirky since it's both an input and the output.  Someone over-valued optimization.

**Comment by jakevdp** [comment]
I think it would be confusing because it's not possible for the result to be written to the `out` array, which is the main purpose of this argument.

And without `out`, there's no way to specify a default value for `where`, so implementing that argument alone wouldn't make much sense.

**Comment by NeilGirdhar** [comment]
Okay, fair enough, I'll just close this then.  Thanks for pointing me in the right direction.

**Comment by mattjj** [comment]
@NeilGirdhar  This might not be directly relevant, but I thought I'd mention that you can get finer-grained control over nan-debugging if you use the `jax.debug_nans` context manager rather than the flag:

```
In [1]: import jax

In [2]: jax.numpy.divide(0, 0)
Out[2]: DeviceArray(nan, dtype=float32)

In [3]: with jax.debug_nans(True):
   ...:     jax.numpy.divide(0, 0)
---------------------------------------------------------------------------
FloatingPointError                        Traceback (most recent call last)
...snip...
FloatingPointError: invalid value (nan) encountered in div

In [4]: with jax.debug_nans(False):
   ...:     jax.numpy.divide(0, 0)
   ...:

In [5]:
```

**Comment by NeilGirdhar** [comment]
@mattjj Oh that is helpful, thank you!
