### ISSUE TITLE
Cannot take gradient of np.prod

### ISSUE THREAD

**Issue by guyvdbroeck** [google/jax#672]
With the latest git version of jax, I get an error trying to `grad` a basic `np.prod` because some underlying `reduce` is not implemented. Perhaps this is a known limitation, but I could not find it in the documentation and it's what currently blocks me. Here is a minimal example:
```
import jax.numpy as np
from jax import grad

g = grad(lambda x: np.prod(x))
g(np.ones((10,8)))
```

> Traceback (most recent call last):
>   File "/home/guy/jax/jax/interpreters/ad.py", line 210, in process_primitive
>     jvp = primitive_jvps[primitive]
> KeyError: reduce
> ...
> NotImplementedError: Forward-mode differentiation rule for 'reduce' not implemented
>

**Comment by hawkinsp** [comment]
This should be easy enough to add. Note that the gradient of `np.sum` is implemented, so one possible workaround in the meantime is to compute `exp(sum(log(x)))`.

**Comment by hawkinsp** [comment]
I added a gradient for `prod` that suffices for first-order gradients. Hope that helps!

**Comment by guyvdbroeck** [comment]
Works like a charm, thanks!
