### ISSUE TITLE
batchnorm in stax experimental reshaping neural network output

### ISSUE THREAD

**Issue by Badi96** [google/jax#6723]
I am trying to use the BatchNorm from the Stax Jax library, where I am using the following Neural Network setup 
```
import jax.numpy as jnp
from jax.experimental import stax
from jax.experimental.stax import (BatchNorm, Dense, Flatten, Relu, LogSoftmax)
from jax.experimental import optimizers
from jax import jit, jacfwd, hessian, vmap, random

init_random_params, nn_forward_fn = stax.serial(
    stax.Dense(128),
    stax.BatchNorm(axis=0),
    stax.Softplus,
    stax.Dense(128),
    stax.BatchNorm(axis=0),
    stax.Softplus,
    stax.Dense(128),
    stax.BatchNorm(axis=0),
    stax.Softplus,
    stax.Dense(1),
    )

_, init_params = init_random_params(rng, (-1, 12))
```
Training the network works without the BatchNorm, but I need the output to be a scalar since I am taking the gradient of it in the predicted model. I am using vmap for my batched data when I input the neural network, and using the BatchNorm across axis=0 as shown above gives the following error 

```
    4   q, q_t = jnp.split(state, 2)
      5   q_tt = (jnp.linalg.pinv(jax.hessian(lagrangian, 1)(q, q_t))
----> 6           @ (jax.grad(lagrangian, 0)(q, q_t)
      7              - jax.jacobian(jax.jacobian(lagrangian, 1), 0)(q, q_t) @ q_t))
      8   return jnp.concatenate([q_t, q_tt])

TypeError: Gradient only defined for scalar-output functions. Output had shape: (1,).
```
In other words, I am taking the gradient and Hessian operation of the single scalar output from the Neural Network and the BatchNorm seems to be reshaping it into an array, which causes problems for the gradient operations. My input data currently has a shape of (batch dimension, 12), since the first dimension is the initial states which I need to compare the results of each input for the MSE loss with the labeled data later. 
Which axis should I use as an argument for the BatchNorm for my case in order to get a scalar as output?

When I am not batching the inputs for the Neural Network, so that the Batch Norm can calculate the mean and variance of each batch of data for the respective layer, I get a similar error 

```
init_random_params, nn_forward_fn = stax.serial(
    stax.Dense(128),
    BatchNorm(axis=0),
    stax.Softplus,
    stax.Dense(128),
    BatchNorm(axis=0),
    stax.Softplus,
    stax.Dense(128),
    BatchNorm(axis=0),
    stax.Softplus,
    stax.Dense(1),
    )

TypeError: Gradient only defined for scalar-output functions. Output had shape: (128,).
```

**Comment by hawkinsp** [comment]
`stax` is intended only as an example. If it works for you, great, otherwise feel free to fork it and improve it. We strongly recommend you consider using one of the much better maintained neural network libraries such as Flax or Haiku. I think that may resolve your issue.

(We are likely to remove stax soon.)
