### ISSUE TITLE
vmap over a list of functions

### ISSUE THREAD

**Issue by adamhaber** [google/jax#673]
Hi,

I'm trying to accelerate a specific computation, in which I compute different functions over the same input. In pure python I would've used something like `[f(input) for f in funcs]`; Is there a way to do something similar in jax?
I've tried a hacky workaround:
```
f_template = lambda i,x:x*i
funcs = [jit(partial(f_template,i)) for i in range(10)]

def helper_func(input,func):
    return func(input)
input = 3
vmap(partial(helper_func,3))(funcs)
```
But got `TypeError: <type 'function'> is not a valid type for batching`.
Is it a reasonable thing to try and do in JAX, or should I stay with list comprehensions?

Thanks!

**Comment by mattjj** [comment]
List comprehensions may be the way to go here.

You can use `vmap` for mapping a single function over array axes, but it's not as general as Python's `map`. (The difference is that `vmap` doesn't do an "outer loop" but instead pushes the map's loop down into the primitives that make up the computation, e.g. turning matrix-multiplies into tensordots. That way your code doesn't need to carry around batch dimensions everywhere, since vmap can add those for you.)

If you expressed your function in a vectorized way over `i` then vmap could work for you, e.g.

```python
x = np.array([3, 1, 4, 1, 5])

f_template = lambda i,x:x*i
out = vmap(f_template)(np.arange(5), x)
```

But I suspect your real use case may be different. List comprehensions should work well in any case!

Does that make sense?

**Comment by adamhaber** [comment]
That makes perfect sense, thank you. 

Indeed, the real use case is more complicated and ideally would support arbitrary functions, so the vectorised version is probably too specific.

**Comment by pharringtonp19** [comment]
@mattjj Does this mean we cannot `vmap` over solvers in a fixed point layer?

I have a fixed point function `fixed_point1(solver, f, params, variables)`, and I was curious about whether I could apply `vmap` over the solver?

The following example is based on the (your!) [implicit layers tutorial](https://www.youtube.com/watch?v=MX1RJELWONc&t=1515s)

```
import jax
import jax.numpy as jnp 
from jax import random
from jax.lax import while_loop


### Data
ndim = 10 
params = random.normal(random.PRNGKey(0), (ndim, ndim)) / jnp.sqrt(ndim)
variables = random.normal(random.PRNGKey(1), (ndim,))
f = lambda params, variables, z: jnp.tanh(jnp.dot(params, z) + variables)

### Functions
def fixed_point1(solver, f, params, variables):
  z_star = solver(lambda z: f(params, variables, z), z_init=jnp.zeros_like(variables))
  return z_star 

def fwd_solver1(f, z_init):

  def cond_fun(carry):
    x_prev, x = carry
    return jnp.linalg.norm(x_prev - x) > 1e-5
  
  def body_fun(carry):
    x_prev, x = carry 
    return x, f(x)
  
  _, x_star = while_loop(cond_fun, body_fun, (z_init, f(z_init)))
  return x_star

def newton_solver1(f, z_init):

  f_root = lambda z: f(z) - z 
  g = lambda z: z - jnp.linalg.solve(jax.jacobian(f_root)(z), f_root(z))

  def cond_fun(carry):
    x = carry
    return jnp.linalg.norm(f_root(x)) > 1e-5
  
  def body_fun(carry):
    x = carry 
    return g(x)
  
  x_star = while_loop(cond_fun, body_fun, (z_init))
  return x_star
```

How would I run something like the following?

```
jax.vmap(fixed_point1, in_axes=(0, None, None, None))

```

**Comment by jakevdp** [comment]
There's no way to vmap directly over an array of functions, but you can achieve roughly the same thing by vmapping over [`lax.switch`](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.switch.html). Here's a simple example:
```python
from jax import lax, vmap
import jax.numpy as jnp

def func1(x):
  return 2 * x

def func2(x):
  return -2 * x

def func3(x):
  return 0 * x

functions = [func1, func2, func3]
index = jnp.arange(len(functions))
x = jnp.ones((3, 5))

vmap_functions = vmap(lambda i, x: lax.switch(i, functions, x))
vmap_functions(index, x)
# DeviceArray([[ 2.,  2.,  2.,  2.,  2.],
#              [-2., -2., -2., -2., -2.],
#              [ 0.,  0.,  0.,  0.,  0.]], dtype=float32)
```
