### ISSUE TITLE
jax.scipy.optimize hangs

### ISSUE THREAD

**Issue by gurgeh** [google/jax#6756]
I'm comparing performance for the scipy BFGS implementation and the replica in jax, but the one in jax keeps hanging and/or being 100x slower. To make sure this is not only my system, I have verified that the code below hangs on Colab.
```python
import jax
import jax.numpy as jnp
import jax.scipy.optimize
import jax.random

jX = jnp.arange(-2, 8, 0.03) # A 1D evaluation grid
targetp = jnp.array(
    [1.3615158,  3.1700504,  0.3901142,  0.8582838,
     -0.24486497,  3.078153,  1.2610698,  2.276195,
     0.84759176,  1.563921, -0.91339713,  0.23969328]) # The "true" parameters

def fun(p): # This function was once auto-generated, so it looks silly
    arg1 = p[2] + p[3] * jnp.tanh(p[4]  + p[5] * jX)
    arg2 = p[6] + p[7] * jnp.log(jnp.abs(p[8] + p[9] * jnp.arctan(p[10] + p[11] * jX)))
    return p[0] + p[1] * arg1 * arg2

targety = fun(targetp)
def mse_loss(p):
    return ((fun(p) - targety) ** 2).mean()
```

I can optimize `mse_loss` just fine in scipy.optimize.minimize, but when I run the code below, the interpreter hangs on the second iteration:
```python
key = jax.random.PRNGKey(1337)
keys = jax.random.split(key, 10)

for k in keys: # Try optimize from different starting points
    x0 = targetp + jax.random.normal(k)
    optx = jax.scipy.optimize.minimize(mse_loss, x0, method='BFGS')
    print(optx.fun, optx.nfev)
```

I have verified this with and without GPU and with and without jitted functions.

[This](https://colab.research.google.com/drive/1sBwLh5w_XRDABHJB2SrmwZtOTXu33EOD) is a link to the above code in Colab.

**Comment by jekbradbury** [comment]
An internal user may have run into a similar issue recently; if this has the same underlying cause then there's a fix on its way.

**Comment by jekbradbury** [comment]
Self-assigning so I can point to the internal PR when it's up.
