### ISSUE TITLE
Inconsistent edge case handling in jax.random.categorical across devices

### ISSUE THREAD

**Issue by GeorgOstrovski** [google/jax#6762]
When provided NaN probabilities, `jax.random.categorical` returns different results depending on the device. 

```
# GPU
> jax.random.categorical(rng_key, jnp.array([0, jnp.nan]))
DeviceArray(2147483647, dtype=int32)

# CPU
> jax.random.categorical(rng_key, jnp.array([0, jnp.nan]))
DeviceArray(1, dtype=int32)
```

Arguably both are not ideal (being valid values, bugs can go unnoticed - especially in the CPU case where 1 is a perfectly valid value coming from this function) but the inconsistency in particular can make debugging very tricky and should be fixed.

**Comment by hawkinsp** [comment]
The issue is actually that `argmax` is handled different on GPU, and its implementation requires an equality comparison, which fails for NaNs.

**Comment by hawkinsp** [comment]
Both CPU and GPU will now return `1` in this case. In other words, if a NaN is present, JAX prefers to return the NaN index to you. I think it is preferable that JAX exposes NaNs if they happen, rather than swallowing them if you get unlucky.

**Comment by GeorgOstrovski** [comment]
Thanks, consistency is an improvement for sure! 

In the very spirit of not swallowing NaNs, wouldn't it be safer to actually have the NaN propagate, i.e. have functions like `jnp.argmax` return NaN whenever they encounter one? 

Also, I'm not sure the current `jnp.argmax` does what you say? On CPU I get:
```
> jnp.argmax(jnp.array([1, jnp.nan, -1, 0]))
DeviceArray(3, dtype=int32)
```
i.e. always the **last** index, rather than the one corresponding to the NaN (note it's also not the argmax when ignoring the NaN entries ...).

**Comment by hawkinsp** [comment]
`argmax` can't return a NaN, because its output is an integer index. The next best thing is to return the index of a NaN.

Are you sure you are at `jax` head?

```
In [1]: from jax import numpy as jnp

In [2]: jnp.argmax(jnp.array([1, jnp.nan, -1, 0]))
Out[2]: DeviceArray(1, dtype=int32)
```
?

If you want to ignore the `nan` entries, I think you want `jnp.nanargmax`:
```
In [3]: jnp.nanargmax(jnp.array([1, jnp.nan, -1, 0]))
Out[3]: DeviceArray(0, dtype=int32)
```

**Comment by GeorgOstrovski** [comment]
You're right, apologies, I was not at head! Case closed, thank you :)
