### ISSUE TITLE
add an is_ready() for checking async readiness

### ISSUE THREAD

**Issue by jackd** [google/jax#6772]
The [asynchronous dispatch](https://jax.readthedocs.io/en/latest/async_dispatch.html) page explains the asynchronous model jax uses and why naive benchmarks can be misleading, but it's difficult to understand what the "jax-y" way of doing more general asynchronous programming is. Are users expected to leverage external tools (e.g. `asyncio`) or are there mechanisms in jax which are more efficient?

As a motivating example, consider an RL learner that has an agent continuously filling a replay buffer on one device and a learner tweaking weights on another. Using `asyncio` I would write something along the lines of:

```python
import asyncio

async def gather_experience(dataset):
  while True:
    trajectory = await environment.random_sample()
    dataset.add(trajectory)

async def train(params, dataset):
  for batch in dataset:
    params = await train_step(params, batch)
  return params

loop = asyncio.get_event_loop()
gather_task = loop.create_task(gather_experience(dataset))
train_task = loop.create_task(train(params, dataset)
loop.run_until_complete(train_task)
```

I've tried using `id_tap` with futures as in the following:
```python
import asyncio
import typing as tp

from jax.experimental.host_callback import id_tap

async def _wait_on(fut: asyncio.Future):
    while not fut.done():
        await asyncio.sleep(0)
    return fut.result()

def as_future(
    x: tp.Any, loop: tp.Optional[asyncio.AbstractEventLoop] = None
) -> asyncio.Future:
    loop = loop or asyncio.get_event_loop()
    fut = loop.create_future()

    def set_result(x_val, _):
        fut.set_result(x_val)

    id_tap(set_result, x)
    return loop.create_task(_wait_on(fut))
```
but it's not exactly elegant (I have no idea why the `_wait_on` is necessary...) and it also forces transfer of data from device to host which isn't always necessary. An exposed `is_ready` method akin to `block_until_ready` which doesn't actually block would make this much nicer - but even then I feel there's likely some redundancy between `jax`'s internal scheduling system and `asyncio`'s event loop.

**Comment by jekbradbury** [comment]
I think some redundancy is inevitable—both the GPU runtime (CUDA) and the TPU runtime have their own lower-level asynchrony, and at some level it's that asynchrony that JAX is piggybacking on and generalizing. But I agree that exposing `is_ready` could improve interop between the runtime's asynchrony and Python-level event loops (another power-user asynchrony feature might be the ability to construct explicit dependency graphs with something like `when_ready(callback)`).

**Comment by mattjj** [comment]
I changed the title to scope the issue more narrowly to adding an `is_ready`. There's more here, but this part of the question is concrete and actionable.

**Comment by zhangqiaorjc** [comment]
@jackd I'm looking into implementing this `is_ready` API now

It won't block the caller the way `block_until_ready` does, but it would still require a mutex in its implementation.

Is `is_ready` a good enough API for the kinds of async stuff you are doing?

**Comment by hawkinsp** [comment]
To add to that: it wasn't totally clear to us what you would be able to do with an `is_ready()` API if we provided one. Can you say more?

**Comment by jackd** [comment]
@zhangqiaorjc I believe either an `is_ready()` or `on_done(callback)` would be enough (one can be implemented in terms of the other). I would have thought `on_done` would be easier to implement since it's just `id_tap` without copying data from device to host - but that's based on zero understanding of jax internals.

@hawkinsp Ideally I'd like to coordinate different processes on multiple devices via code run on host that uses `asyncio`. The example above does that (assume `train_step` and `gather_experience` run on difference devices). However, if I only had 1 device and the buffer was smaller, I'd like to be able to use the same/similar code to alternate between tasks and avoid copying data from device to host and back again.

I can do all of the above if I can wrap jax data primitives in `asyncio.Future`s. There's an example above using `id_tap`, but it's a bit clunky and requires potentially uneccessary copying of data from device-to-host.

Given an `is_ready` method it could be re-implemented as:

```python
import typing as tp
import asyncio

def as_future(x, loop: tp.Optional[asyncio.AbstractEventLoop] = None) -> asyncio.Future:
    """`asyncio.Future` wrapper of jax data primitive using `x.is_ready`."""
    async def f():
        while not x.is_ready():
            await asyncio.sleep(0)
        return x

    loop = loop or asyncio.get_event_loop()
    return loop.create_task(f())
``` 

Given an `on_done` method it could be re-implemented as:

```python
import typing as tp
import asyncio

def as_future(x, loop: tp.Optional[asyncio.AbstractEventLoop] = None) -> asyncio.Future:
    """`asyncio.Future` wrapper of jax data primitive using `x.on_done`."""
    loop = loop or asyncio.get_event_loop()
    fut = loop.create_future()

    def on_done_callback():
        fut.set_result(x)

    x.on_done(on_done_callback)
    return fut
```

**Comment by zhangqiaorjc** [comment]
@jackd thanks for the extra context!

looks like `x.is_ready` results in busy polling while `x.on_done` avoids that

@hawkinsp if there are no hidden problems I'm not seeing, `on_done` is strictly better

**Comment by AdityaGudimella** [comment]
Has there been any updates on this? I’m really interested in this too. Ids there anyway I can contribute.

**Comment by erikstrand** [comment]
XLA's [PyArray](https://github.com/openxla/xla/blob/8d259c5f1770cbb53789316f9d968222ba32d74a/xla/python/py_array.h) already has a method [`is_ready`](https://github.com/openxla/xla/blob/8d259c5f1770cbb53789316f9d968222ba32d74a/xla/python/py_array.cc#L1023), so it appears to be a simple change to expose it within JAX.

@zhangqiaorjc I made the necessary changes in [this fork](https://github.com/google/jax/compare/main...erikstrand:jax:async_is_ready), if I open a PR is this something that could get merged?

For anyone who wants to use `is_ready` right away, the fix is pure Python so you don't need to build anything from source. I've been installing jaxlib with pip and then my JAX fork locally (on the branch [`async_is_ready`](https://github.com/erikstrand/jax/tree/async_is_ready)):

```
pip install --upgrade "jaxlib[cuda12_local]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
pip install -e /your/clone/of/erikstrand/jax
```

For context, my particular use case is to update a visualization (built with [pygfx](https://github.com/pygfx/pygfx)) whenever I get new state from a physics simulation (written in JAX), without blocking the GUI while we wait for the simulation to run. With `is_ready` it's easy to do this in a single thread. In the example below, `sim_state` is some pytree containing several JAX arrays, `sim_step` advances the simulation by one time step, and `app.run()` adds a task to the asyncio event loop that re-renders the scene in response to user input or updated simulation data.

```python
async def run_simulation(sim_state, app):
    while not app.is_closed():
        sim_state = sim_step(sim_state)
        while not jax.is_ready(sim_state):
            await asyncio.sleep(0.001)
        app.update(sim_state)

async def main():
    sim_state = initialize_simulation()
    app = SimVisApp()
    sim_task = asyncio.create_task(run_simulation(sim_state, app))
    app.run()
    await sim_task

asyncio.run(main)
```

**Comment by ArvinSKushwaha** [comment]
Hey all, will this be a feature we can expect to see in JAX soon? This is something that would be very useful for my applications of asynchronously executing machine learning tasks to model physically constrained systems.

**Comment by yashk2810** [comment]
`arr.is_ready()` is available on a jax.Array since a long time. Try it?

**Comment by ArvinSKushwaha** [comment]
Oh, my apologies; my LSP didn't show that as a function that existed. I will check it out! Thanks!

**Comment by ArvinSKushwaha** [comment]
Would it be possible to implement a method like `on_done` to avoid this busy polling issue? If not, could I have some direction on how to implement such a method using JAX or XLA internals? Thanks!
