### ISSUE TITLE
No GPU/TPU found on nvidia cuda docker image.

### ISSUE THREAD

**Issue by golanor** [google/jax#6775]
Hi,

I'm trying to run jax on a docker image based on `nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu18.04` (I also tried different versions).

I'm installing jax and jaxlib according to the readme (I'm using poetry) - 
`poetry run pip install --upgrade jax jaxlib==0.1.67+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html`

And when I try to run my script, I get the following error messages:

`external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
`

`external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:269] failed call to cuInit: UNKNOWN ERROR (303)
`

I tried using a tensorflow base image, but I got the same errors. I tried searching for these errors, and most suggestions involve reinstalling cuda.

Anyone has any idea how to debug/fix these?

Thanks!

**Comment by skye** [comment]
I haven't seen this error before, but based on the message, I would first verify you have `libcuda.so.1` somewhere on your system (try `locate libcuda.so`), and then add that directory to `LD_LIBRARY_PATH` (try `export LD_LIBRARY_PATH=/new/cuda/path:$LD_LIBRARY_PATH`).

You also may need to create a symlink from your cuda install to `/usr/local/cuda-11.1`.

cc @hawkinsp who may know more.

**Comment by mattiasmar** [comment]
Hi, @golanor 
Could you please share your dockerfile?
Thanks!

**Comment by golanor** [comment]
Sure:
```
FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04

WORKDIR /app

COPY . /app

RUN apt update
RUN apt install -y curl unzip python3.8 python3-pip python3.8-dev

RUN mkdir /aws-cli \
    && curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /aws-cli/awscliv2.zip \
    && unzip /aws-cli/awscliv2.zip \
    && ./aws/install

RUN python3.8 -m pip install --upgrade pip \
    && pip install poetry \
    && poetry install \
    && poetry run pip install --upgrade "jax[cuda111]" -f https://storage.googleapis.com/jax-releases/jax_releases.html

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/
```

**Comment by mattiasmar** [comment]
Thanks a lot.
The line command "poetry install" breaks for  me. Does this error give you any ideas about what went wrong? I have never used 'poetry' before.

 ```
 RuntimeError

  Poetry could not find a pyproject.toml file in /app or its parents

  at /usr/local/lib/python3.8/dist-packages/poetry/core/factory.py:369 in locate
      365│             if poetry_file.exists():
      366│                 return poetry_file
      367│
      368│         else:
    → 369│             raise RuntimeError(
      370│                 "Poetry could not find a pyproject.toml file in {} or its parents".format(
      371│                     cwd
      372│                 )
      373│             )
```

**Comment by golanor** [comment]
If you're not using poetry, then you can drop the two lines related to it:
```
FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu18.04

WORKDIR /app

COPY . /app

RUN apt update
RUN apt install -y curl unzip python3.8 python3-pip python3.8-dev

RUN mkdir /aws-cli \
    && curl https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip -o /aws-cli/awscliv2.zip \
    && unzip /aws-cli/awscliv2.zip \
    && ./aws/install

RUN python3.8 -m pip install --upgrade pip \
    && poetry run pip install --upgrade "jax[cuda111]" -f https://storage.googleapis.com/jax-releases/jax_releases.html

ENV LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/
```

**Comment by mattiasmar** [comment]
Thanks @golanor. Your docker file expresses the same "solution"  that has been suggested in many tickets before, also above by @skye, and that is to include the cuda directory to the LD_LIBRARY_PATH. 
Nevertheless, I still can't run a simple example from Flax without getting the "No GPU" error.

I build the dockerfile that you provided (minus references to 'poetry') and inside the docker container I execute:
```
 apt-get install -y git python3.8
 git clone https://github.com/google/flax.git
 pip install ml_collections clu tensorflow-datasets
 cd flax/examples/mnist
 python train_test.py
```

@golanor: Would you like to do me the **_favor_** and test this on your side?

**Comment by mattiasmar** [comment]
@golanor Hi! Problem solved if I base the docker image on `nvidia/cuda:11.4.1-cudnn8-devel-ubuntu18.04` and install `jax[cuda]` rather than` jax[cuda111]`
