### ISSUE TITLE
`TpuTransferManager_ReadMetadataLiteral` not available in this library.

### ISSUE THREAD

**Issue by kaushikb11** [google/jax#6797]
It throws an error for jaxlib version `0.1.67` (on tpuvm)

<img width="1792" alt="Screen Shot 2021-05-20 at 6 45 30 AM" src="https://user-images.githubusercontent.com/45285388/118904287-2c269d00-b937-11eb-93de-39b7d5711624.png">

**Comment by skye** [comment]
I reached out to you offline with how to get help with Cloud TPU VMs.
