### ISSUE TITLE
New jaxlib wheels cause `ptxas` error

### ISSUE THREAD

**Issue by astanziola** [google/jax#6799]
Hi everyone! I've been using (and enjoying 😁) JAX on an university cluster for quite a while, without much problems until now.

Unfortunately since the new `jaxlib` wheels 0.1.66 and 0.1.67 have been released I'm not able to upgrade and keep a functioning install.

Here's the error I get after upgrading
```bash
>>> import jax, jaxlib
>>> print(jax.version.__version__, jaxlib.version.__version__)
0.2.13 0.1.67
>>> a = jax.numpy.ones((100,100))**2
2021-05-20 10:09:06.617783: E external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:93] You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 9.2.88).  Compilation of XLA kernels below will likely fail.

You do not need to update CUDA; cherry-picking the ptxas binary is sufficient.
2021-05-20 10:09:06.630330: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:478] ptxas returned an error during compilation of ptx to sass: 'Internal: ptxas exited with non-zero error code 65280, output: ptxas /tmp/tempfile-kinsler-56b28778-3690660-5c2bf4b9c1e23, line 5; fatal   : Unsupported .version 6.0; current version is '5.0'
ptxas fatal   : Ptx assembly aborted due to errors
'  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
Aborted (core dumped)
```

Reverting back to jaxlib 0.1.65 fixes the problem.
The CUDA installation is non-standard (the cluster uses environment `module`s and I don't have admin rights), but by setting the appropriate environment variables and paths I've got everything working until the new wheels came out. For completeness, here's my nvcc

```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```

**Comment by hawkinsp** [comment]
What versions of `ptxas` do you have installed, and where are they? (e.g., is there one in your PATH? What about in `/usr/local/cuda*/bin` ?) Normally I would expect `ptxas` to be installed next to `nvcc`.

The issue is that JAX isn't finding the correct version, and it would help to know where your copy is to try to guess why.

**Comment by astanziola** [comment]
Thank you for your reply @hawkinsp !

As I mentioned, I can load various CUDA verisions using `module`. 

The one I've loaded is in `/apps/software/CUDA/11.2.1/`, so I'm updating the LD_LIBRARY_PATH and XLA_FLAGS as follows (the `PATH` is automatically updated by `module`)
```
export LD_LIBRARY_PATH=/apps/software/CUDA/11.2.1/targets/x86_64-linux/lib:$LD_LIBRARY_PATH
export XLA_FLAGS="--xla_gpu_cuda_data_dir=/apps/software/CUDA/11.2.1/"
```
Here's the version of `ptxas` in that folder, which is the same version as the one in the `PATH`
```
astanziola@cl:/apps/software/CUDA/11.2.1/bin$ ./ptxas --version
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:31:31_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0

astanziola@cl:/apps/software/CUDA/11.2.1/bin$ cd ~

astanziola@cl:~$ ptxas --version
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:31:31_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
```

However, I think you're into something, because `/usr/local/cuda/bin` does have an older `ptxas` version that matches the error.
```
astanziola@cl:/usr/local/cuda/bin$ ./ptxas --version
ptxas: NVIDIA (R) Ptx optimizing assembler
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:21:54_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```
but it if is a path problem, isn't odd that I don't have this issue with jaxlib 0.1.65?

**Comment by hawkinsp** [comment]
I think the issue is that we are now preferring `/usr/local/cuda/bin/ptxas` if it exists, in preference to your `PATH`.

We could possibly revert that change; I think it may not be needed now that we bundle `libdevice`, which was the thing that change was originally trying to make sure that we find.

**Comment by hawkinsp** [comment]
I'm preparing a PR that makes `jaxlib` prefer the copy of `ptxas` in your PATH to the one in `/usr/local/cuda`. At least then you can override it!

**Comment by hawkinsp** [comment]
#6820  should have fixed this issue, although you'll either need to rebuild `jaxlib` from source or wait for us to make a new release. Hope that helps!

**Comment by astanziola** [comment]
@hawkinsp That is amazing!! Thank you very much for helping with this, as soon as the new release is out I'll check it out (I can't compile on the cluster)
