### ISSUE TITLE
Compilation hangs indefinitely on GPU

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#6823]
I am encountering an issue where compilation on GPU hangs forever in a semi-deterministic way (happens every time, but at slightly different places). All functions have been compiled successfully before (but with different shapes).

This happens in the middle of a huge model code, and I unfortunately haven't been able to come up with a reproducer. After 2 minutes I get the "slow compile" warning, then all I can do is send `SIGKILL`. 

I have dumped the HLO but it looks inconspicuous to me:

https://gist.github.com/dionhaefner/e5680e131975b6bf566c1e1cbc554476

The only lead I have is that right before it hangs, I do something like this:

```python
# <do computations on GPU with JAX>

import numpy as onp
rhs = onp.asarray(rhs)
x0 = onp.asarray(x0)

linear_solution, info = scipy.sparse.linalg.bicgstab(
    _matrix,
    rhs,
    x0=x0,
    atol=0,
    tol=settings.congr_epsilon,
    maxiter=settings.congr_max_iterations,
    **self._extra_args,
)

return jnp.asarray(linear_solution)

# a couple of lines later everything hangs
```

If I comment out the BiCG solver everything works.

This happens on JAX built from source and current wheels. <s>Downgrading jaxlib did not help either.</s> Works on jaxlib 0.1.64, albeit poorly (factor of 10 slower for some reason).

If you have any pointer on how to debug this I would be grateful.

**Comment by hawkinsp** [comment]
Your HLO dump only includes a single module. Are you sure that's the module that is hanging? (It doesn't appear to hang for me, and it looks unremarkable.)

**Comment by dionhaefner** [comment]
Yes, it's this one (according to the slow compilation warning).

The function is unremarkable, and sometimes compilation succeeds (but then the compiler hangs on the next module). So I doubt this has anything to do with it.

To me this sounds like a race condition or something running out of resources.

Anyhow, I was hoping there would be some more debug flags I could use to understand what's going on internally. If that's not the case I will have to get back to you when I can narrow it down a bit.

**Comment by hawkinsp** [comment]
Is this a multi-GPU machine? @skye was trying to track down a similar-looking hang that exhibits on multi GPU machines.

**Comment by dionhaefner** [comment]
> Is this a multi-GPU machine?

Yes, it is!

After you mentioned that I hoped that something like `CUDA_VISIBLE_DEVICES=0` would fix it, but that doesn't seem to be the case...

**Comment by hawkinsp** [comment]
Ok, I think we'll need a way to reproduce this. If you share all of the HLO dumps, it's possible we can reproduce from that, although a Python repro would be best.

**Comment by dionhaefner** [comment]
I don't have a self-contained example, sorry.

This is how I can reproduce it reliably:

```bash
$ git clone https://github.com/team-ocean/veros.git
$ cd veros
$ git checkout 6d7833a1801c028048f4d7cf6b80e86bec7f3224
$ pip install -e .
$ pip install jax jaxlib==0.1.67+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html
$ export VEROS_LINEAR_SOLVER=scipy
$ python benchmarks/acc_benchmark.py --size 304 304 108 --timesteps 10 -b jax --device gpu

Importing core modules
 Using computational backend jax on gpu
  Kernels are compiled during first iteration, be patient
 Runtime settings are now locked

Running model setup

# lots of output, until...

Initializing linear solver
Computing ILU preconditioner...
 Solving for boundary contribution by island 0
2021-05-26 13:05:29.319948: E external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:55]
********************************
Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
Compiling module primitive_computation_scatter__8.10
********************************
```

Platform info:

```bash
$ nvidia-smi
Wed May 26 13:04:13 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla P100-PCIE...  Off  | 00000000:03:00.0 Off |                    0 |
| N/A   25C    P0    31W / 250W |  14690MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-PCIE...  Off  | 00000000:04:00.0 Off |                    0 |
| N/A   25C    P0    32W / 250W |    257MiB / 16280MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```


I understand that you can't debug my code for me, so I'm putting this out there mostly as a reminder to self. It would also be valuable to know whether someone else can reproduce this on different hardware.

**Comment by dionhaefner** [comment]
This sounds related: https://github.com/google/jax/issues/6471

In both cases, we get hanging compilations on GPU after calling `scipy.sparse.linalg.bicgstab`. Would be a hell of a coincidence...

**Comment by dionhaefner** [comment]
FWIW, this does not occur when I do

```bash
$ export OMP_NUM_THREADS=1
```

Could this be SciPy's internal OpenMP parallelization clashing with JAX's thread parallelism?

**Comment by sudhakarsingh27** [comment]
@dionhaefner Was this resolved? Do you still need help?

**Comment by dionhaefner** [comment]
Seems fixed with recent JAX, thanks!
