### ISSUE TITLE
Tridiagonal solver for CUDA

### ISSUE THREAD

**Issue by dpfau** [google/jax#6830]
It would be wonderful if JAX had a tridiagonal solver, perhaps modeled after `scipy.linalg.solve_banded`. There is already a CUDA kernel for this, it would just need to be wrapped for GPU: https://docs.nvidia.com/cuda/cusparse/index.html#gtsv2. I leave it up to you to figure out how best to do this on TPU.

**Comment by jakevdp** [comment]
Thanks - agreed this would be useful! We added wrappers for a few cusparse routines in https://github.com/google/jax/pull/6429; wrapping gtsv2 would be similar.

We'd then need an appropriate primitive, perhaps with a lapack lowering for CPU. I'm not sure how to best address this on TPU.

**Comment by dpfau** [comment]
I've tested this on CPU and it's as fast as `scipy.linalg.solve_banded`, but it's very slow on GPU and wrapping CUDA would be preferred. This could work on TPU though.

**Comment by jakevdp** [comment]
In general scans on TPU will have poor performance, but as a placeholder implementation until a TPU-specific lowering can be used, I think that's fine.

**Comment by hawkinsp** [comment]
There's also a tridiagonal solver in the XLA client library that will work on TPU (https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/xla/client/lib/tridiagonal.h;l=25). It may or may not be better than the Python implementation above, but it's a starting point.
