### ISSUE TITLE
RFC: support complex numbers in `jnp.logaddexp`

### ISSUE THREAD

**Issue by PhilipVinc** [google/jax#6863]
`np.logaddexp` does not support complex numbers even though that operation is well defined on complex numbers ( `scipy.special.logsumexp`, which is a vector version of it does suppot complex numbers).

I recently contributed complex numbers support for `jax.scipy.special.logsumexp` in https://github.com/google/jax/pull/6855 and hopefully that will soon be merged.

I would like to argue for breaking off from standard numpy behaviour of not supporting complex numbers in `np.logaddexp` and support them in `jnp.logaddexp`. 
The operation is well defined, and that will allow to `jax.nn.softplus(x) : jnp.logaddexp(x, 0)` to work out of the box.

If the jax maintainers think that this feature would be ok, i'll contribute a PR.

**Comment by jakevdp** [comment]
This proposal sounds reasonable to me – let's give it a day or two in case others want to weigh in.

**Comment by hawkinsp** [comment]
My only suggestion would be: perhaps the same change should be made to classic NumPy? Or at least a feature request opened for it?

**Comment by PhilipVinc** [comment]
I've sent the feature request to the numpy discussion mailing list and will post back with the feedback received.

**Comment by hawkinsp** [comment]
Unassigning myself: this issue just needs someone to send a PR I think at this point!

**Comment by PhilipVinc** [comment]
Closed by #7141
