### ISSUE TITLE
Relax type-specialization requirement in closure_convert.

### ISSUE THREAD

**Issue by MaxiLechner** [google/jax#6867]
I'm working on some implicit differentiation stuff in jax-md and I'm having some problems when I try to combine ```closure_convert``` with jax-md's ```neighbor_list```.

It boils down to the fact that neighbor_lists elements aren't static.
Here's a minimal working example. The second argument to ```f``` would correspond to a ```neighbor_list```, the first argument to ```f``` is guaranteed to have constant shape.

``` python

def get_f(sigma):
    def f(a,b):
        return sigma*jnp.sum(a[b])
    return f

f = get_f(jnp.array([3.]))
a = jnp.arange(10)
b = jnp.array([3,5])

f_converted, aux_args = jax.closure_convert(f,a,b)

# This works
f_converted(a,b,*aux_args)

# This throws an assertion error because b.shape != c.shape
c = jnp.array([1,4,8])
f_converted(a,c,*aux_args))
```

For my use case  it would be perfectly fine if ```f``` were to be ```closure_converted``` again if the shape of the second argument changes, similar to how value dependent shapes are handled in ```jax.jit``` when using ```static_argnums```.

**Comment by froystig** [comment]
You could closure-convert prior to every call, following [the example in the `closure_convert` docstring](https://github.com/google/jax/blob/3954ba39676e3bb5f5a17897f2c4ccdb475b86c4/jax/_src/custom_derivatives.py#L786-L788). Setting performance concerns aside, would that work?

Converting on every call can lead to redundant conversions. We could try to mitigate that by making it easier to use `closure_convert` with a cache (similar to `jit`'s cache), but first I'd like to be sure that I understand the request here.

**Comment by MaxiLechner** [comment]
Sort of.  Let me expand a bit so we don't talk past each other.

I want to efficiently differentiate through an energy minimization routine by recasting it as a root finding procedure ```root_solve```, which takes in 4 arguments. 

``` python
def root_solve(objective_fn, x0, n0, solver):
    converted_fn, aux_args = closure_convert(objective_fn, x0, n0)
    return _root_solve(converted_fn, x0, n0, solver, *aux_args)


@functools.partial(jax.custom_vjp, nondiff_argnums=(0, 2, 3))
def _root_solve(func, init_xs, n0, solver, *aux_args):
    init_xs = jax.tree_map(jax.lax.stop_gradient, init_xs)
    aux_args = jax.tree_map(jax.lax.stop_gradient, aux_args)
    f = lambda x, neighbor=None: func(x, neighbor, *aux_args)
    return solver(f, init_xs)
```
Here ```objective_fn``` is the function I want to find the root of. ```init_xs``` are my initial starting positions, ```n0``` is the initial ```neighbor_list``` and ```solver``` is a user defined function that computes the root of ```objective_fn/converted_fn```.

```solver``` can internally compute a new ```neighbor_list``` which then causes an assertion error as ```in_tree``` and ```in_tree2```  in ```closure_convert``` are not the same anymore.

As ```solver``` is a user defined function I would very much prefer if they didn't have to learn about ```closure_convert``` and that I can keep ```closure_convert``` internal to ```root_solve```.

The behavior I would like to see from ```closure_convert``` (and I don't know  if that's easily doable), would be that when ```converted_fn``` was called with a different ```neighbor_list``` it would be reconverted again instead of failing the ```assert in_tree == in_tree2``` statement.

Here's a jax-md example: https://colab.research.google.com/drive/1PU3CDO5VacjiSqUal4A9wQgh4-ualkcO?usp=sharing

**Comment by froystig** [comment]
> The behavior I would like to see from `closure_convert` (and I don't know if that's easily doable), would be that when `converted_fn` was called with a different `neighbor_list` it would be reconverted again instead of failing the `assert in_tree == in_tree2` statement.

Any new conversion might result in new hoisted constants, not only a new function.

> As `solver` is a user defined function I would very much prefer if they didn't have to learn about `closure_convert` and that I can keep `closure_convert` internal to `root_solve`.

Would it be possible to address this encapsulation problem on your end with a custom Python callable? For example: define a class that overloads `__call__` and carries (in each instance) a reference to the original function. When an instance is called, it performs closure conversion with the actual final arguments in hand, then calls into the resulting closure-converted function with the correct constants. You could pass such an instance into `solver`, in your application.

**Comment by MaxiLechner** [comment]
> Any new conversion might result in new hoisted constants, not only a new function.

If that happens something went quite wrong.

> Would it be possible to address this encapsulation problem on your end with a custom Python callable? For example: define a class that overloads __call__ and carries (in each instance) a reference to the original function. When an instance is called, it performs closure conversion with the actual final arguments in hand, then calls back to you with the resulting closure-converted function and hoisted constants. You could pass such an instance into solver, in your application.

I can try to do that.

**Comment by froystig** [comment]
> If that happens something went quite wrong.

Perhaps it cannot happen in your application, but it is a possibility in general, so `closure_convert` cannot assume otherwise.

> I can try to do that.

Did this work out? For the record, I had in mind a definition along the following lines:

```python
class ConvertAndCall:
  def __init__(self, closure, callback):
    self.closure = closure
    self.callback = callback

  def __call__(self, *args):
    f, aux_args = jax.closure_convert(self.closure, *args)
    return self.callback(f, *args, *aux_args)
```

I'll close the issue since it seems that the discussion has addressed it, but please reopen if there is more to it.
