### ISSUE TITLE
jax.checking_leaks() detects leak on np.linalg.det and np.linalg.slogdet

### ISSUE THREAD

**Issue by denizokt** [google/jax#6870]
```python
import jax.numpy as np
import jax

with jax.checking_leaks():
  @jax.jit
  def g(x):
    return np.linalg.det(np.eye(2))
    
  g(0.0)
```

Generates: `Exception: Leaked sublevel 3.`

The same thing happens when det is replaced by slogdet. I think this might be from the custom_jvp wrapper around det, since the unfiltered stack trace seems to fail somewhere in the code to handle custom_jvps.

Might be related to https://github.com/google/jax/issues/5636

Thank you!

**Comment by hawkinsp** [comment]
This is fixed at head!
