### ISSUE TITLE
Expected Behaviour of `"--xla_force_host_platform_device_count=8"`

### ISSUE THREAD

**Issue by kaushikb11** [google/jax#6887]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
>>> import os
>>> os.environ["XLA_FLAGS"] = '--xla_force_host_platform_device_count=8'
>>> import jax
>>> jax.devices("cpu")
[CpuDevice(id=0), CpuDevice(id=1), CpuDevice(id=2), CpuDevice(id=3), CpuDevice(id=4), CpuDevice(id=5), CpuDevice(id=6), CpuDevice(id=7)]
```

But the following approaches don't work
```python
>>> import os
>>> import jax
>>> jax.devices("cpu")
[CpuDevice(id=0)]
>>> os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=8"
>>> jax.devices("cpu")
[CpuDevice(id=0)]
```

```python
>>> import os
>>> import jax
>>> from jax.lib import xla_bridge
>>> jax.devices("cpu")
[CpuDevice(id=0)]
>>> os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=8"
>>> xla_bridge.get_backend.cache_clear()
>>> jax.devices("cpu")
[CpuDevice(id=0)]
```

- [ ] If applicable, include full error messages/tracebacks.

**Comment by apaszke** [comment]
Thanks for the report, but this is expected behavior. XLA flags only affect backend initialization and should be set before that happens. [The docs](https://jax.readthedocs.io/en/latest/jax-101/06-parallelism.html?highlight=XLA_FLAGS#aside-hosts-and-devices-in-jax) mention that the flag has to be set before JAX is initialized through any call.

**Comment by kaushikb11** [comment]
Yup, aware of it. But I have noticed a similar pattern being used for CPU devices in some Jax internal tests Ref: https://github.com/google/jax/blob/master/jax/test_util.py#L438

@apaszke I have a use case where I wish to control the CPU devices being used based on `num_devices` input. Would be great to know a workaround for this. Thanks!

**Comment by jakevdp** [comment]
Am I understanding that you essentially want to re-initialize the backends on-demand during the course of a runtime? If so, I don't think there is any API for that.

**Comment by kaushikb11** [comment]
Ahh, I see! Could this be supported? @jakevdp

**Comment by apaszke** [comment]
I think that it is possible to reinitialize them (see [those lines](https://github.com/google/jax/blob/master/jax/test_util.py#L446-L447)), but it is a footgun large enough that we don't want to make any guarantees about it in the public API

**Comment by kaushikb11** [comment]
Yup, I have tried that (the Second approach in the Issue description). Didn't work as expected.

**Comment by mjsML** [comment]
@kaushikb11 yes ... if you remove [this line](https://github.com/google/jax/blob/main/jax/lib/xla_bridge.py#L221) it *should* work?

**Comment by kaushikb11** [comment]
@mjsML Tried that, even did it with `cache.clear`. Unfortunately, didn't work.

**Comment by mjsML** [comment]
@kaushikb11 a hacky workaround is to go to nuclear : 
```python
import os
import sys
import psutil
import logging
import ast 
# https://stackoverflow.com/questions/11329917/restart-python-script-from-within-itself

# print(set_stats(True)) # Do this on the initial run
def read_stats():
  fh=open("some_persistence.txt")
  value=fh.read()
  fh.close()
  value=ast.literal_eval(value)
  return value

def set_stats(value):
  fh=open("some_persistence.txt",'w')
  fh.write(str(value))
  fh.close()
  return read_stats()


if not read_stats():
  os.environ["XLA_FLAGS"] = "--xla_force_host_platform_device_count=8"

import jax
import sys

print(jax.devices("cpu"))
if read_stats():
  set_stats(False)
  print("Restarting process ...")
  # This will work on normal machines
  # os.execv(sys.argv[0], sys.argv)

  # in colab this works
  os.kill(os.getpid(), 9)
  
```
