### ISSUE TITLE
Radom jit for customized jacrev 

### ISSUE THREAD

**Issue by Wedthree** [google/jax#6902]
```python
import jax.numpy as jnp
from jax import custom_vjp
from jax import jit
from jax import jacrev
import time


@custom_vjp
@jit
def f(x):
  print("called f!")
  return jnp.sin(x)

@jit
def f_fwd(x):
  print("called f_fwd!")
  return f(x), jnp.cos(x)

@jit
def f_bwd(cos_x, y_bar):
  print("called f_bwd!")
  return (cos_x * y_bar,)

f.defvjp(f_fwd, f_bwd)

for i in range(5):
  start = time.time()
  print(jacrev(f)(3.0))
  print("duration", time.time()-start)
  print("============")
```
If you run the previous codes many times (for example 10),  you will different results for the same code. And different results imply random compiling customized jacrev function.

**Comment by Wedthree** [comment]
On my mac， called f_bwd! will show up 2 times. 
![image](https://user-images.githubusercontent.com/29997355/120885688-bdc32980-c61c-11eb-8686-73ab694e908f.png)

However, sometimes the result will be like
![image](https://user-images.githubusercontent.com/29997355/120885640-8a809a80-c61c-11eb-89a7-6a3a2d9f59de.png)

"called f_bwd!" implies jit recompiling with longer duration.
The behavior under Linux is also different with called f_bwd! once for most of the time. However, randomness still exists.

**Comment by jakevdp** [comment]
I edited your code to use a `for` loop for clarity - hope that's OK.

I'm not entirely sure why you're seeing indeterminate behavior, but one thing to note is that in the way you've set this up, `f_fwd` and `f_rev` will always be called with tracer objects, and tracer objects are not yet supported by JAX's default JIT cache mechanism (see https://github.com/tensorflow/tensorflow/blob/596967c699fd6b742cd11926b9d0ea2fbedc599c/tensorflow/compiler/xla/python/jax_jit.cc#L800-L801)

So my baseline expectation (if you're using the most recent jaxlib version) is that these functions would be re-compiled each time they are called.

As for why they are not recompiled in some runs, I'm not sure.

**Comment by jakevdp** [comment]
One way you can fix the issue entirely is to wrap the outer function in `jit`:
```python
f_jacrev = jit(jacrev(f))

for i in range(5):
  start = time.time()
  print(f_jacrev(3.0))
  print("duration", time.time()-start)
  print("============")
```
then the whole thing will only be compiled once.

**Comment by Wedthree** [comment]
As the customized jacrev base function is a part of outer none-jit but differentiable function, and differential part is automatic, it is hard to jit jacrev in each diff chain. Moreover, the compiling time is very long for my real case.

**Comment by jakevdp** [comment]
I'm assigning to @zhangqiaorjc, because he might know more about this TODO.

**Comment by rajasekharporeddy** [comment]
Hi @Wedthree 

Looks like this issue has been resolved. I executed the mentioned code on colab with JAX version 0.4.23. All the three functions have been called only once.

```python
import jax.numpy as jnp
from jax import custom_vjp
from jax import jit
from jax import jacrev
import time


@custom_vjp
@jit
def f(x):
  print("called f!")
  return jnp.sin(x)

@jit
def f_fwd(x):
  print("called f_fwd!")
  return f(x), jnp.cos(x)

@jit
def f_bwd(cos_x, y_bar):
  print("called f_bwd!")
  return (cos_x * y_bar,)

f.defvjp(f_fwd, f_bwd)

for i in range(5):
  start = time.time()
  print(jacrev(f)(3.0))
  print("duration", time.time()-start)
  print("============")
```

Output:

```
called f_fwd!
called f!
called f_bwd!
-0.9899925
duration 0.31082868576049805
============
-0.9899925
duration 0.006571531295776367
============
-0.9899925
duration 0.00391077995300293
============
-0.9899925
duration 0.004708528518676758
============
-0.9899925
duration 0.004668712615966797
============
```
Attaching the colab [gist](https://colab.research.google.com/gist/rajasekharporeddy/4fca9ebc99d9d280040ebe8dfa09de85/-6902.ipynb) for reference.

Also verified this behavior on mac and it results the same. Please find the screenshot for reference.
![image](https://github.com/google/jax/assets/153593711/f2abf416-082e-4fc7-8a30-eb924cf23d3c)

Could you please verify and confirm.

Thank you

**Comment by jakevdp** [comment]
Thanks for the followup @rajasekharporeddy – it looks like this can be closed!
