### ISSUE TITLE
Is doc in FAQ "Different kinds of JAX values" wrong ?

### ISSUE THREAD

**Issue by edimetia3d** [google/jax#6976]
Hi,

I am learning/reading the doc now,  and have a question in FAQ part

In "https://github.com/google/jax/blame/master/docs/faq.rst",  line 235

```python
  def func(x):
    print(x)
    return np.cos(x)

  res = jax.jit(func)(0.)
```
The doc says 

> This is why ``np.cos`` works in the example above.

But the example doenst work in my local env, and it doen't make sense for me now. the error message is

```bash
jax._src.traceback_util.UnfilteredStackTrace: jax._src.errors.TracerArrayConversionError: The numpy.ndarray conversion method __array__() was called on the JAX Tracer object Traced<ShapedArray(float32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
While tracing the function func at /jax/test.py:174 for jit, this concrete value was not available in Python because it depends on the value of the argument 'x'.
See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.TracerArrayConversionError
```

As far as I know, `x` is a traced object during the first run, and it only holds dtype and shape info, it may be right to do `np.cos(x.shape)`, but not `np.cos(x)`

Is there something wrong?

I am working in master branch, and commit id is : 7a3a160b26787898fbf192025547430996bc2b59

**Comment by jakevdp** [comment]
Good catch – I think this should be `jnp.cos` rather than `np.cos` – it was probably missed last year when we changed the docs to use `import jax.numpy as jnp` rather than `import jax.numpy as np`.

I'll submit a fix.
