### ISSUE TITLE
Dilated Reduce Window SegFault with S64 input on TPU

### ISSUE THREAD

**Issue by seanmor5** [google/jax#6989]
Running on a Cloud TPU VM, dilated reduce window operations SegFault with S64 inputs:

```python
import jax
from jax import jit, lax
import jax.config
jax.config.update('jax_enable_x64', True)
import numpy as np

@jit
def dilated_window_sum(t):
  return lax.reduce_window(t, 0, lax.add, (3, 2, 1), [1, 1, 1], 'SAME', window_dilation=[1, 2, 2])

dilated_window_sum(lax.reshape(lax.iota(np.int64, 960), (8, 10, 12)))
```

Traceback if it's helpful

<details>
<pre>
https://symbolize.stripped_domain/r/?trace=7f86f745aa20,7f8704cd520f,7f86f73e2c13,7f86f73e2853,7f86f73e926d,7f86f73ebee0,7f86fbac40f9,7f86fbacb36a,7f86fbac65b7,7f86fbd4a98f,7f8704c75608&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f86ef130000-7f86fc162b20 
*** SIGSEGV (@(nil)), see gl__________25#s15 received by PID 34342 (TID 35396) on cpu 13; stack trace: ***
https://symbolize.stripped_domain/r/?trace=7f86f745aa20,7f8704cd520f,7f86f73e2c13,7f86f73e2853,7f86f73e926d,7f86f73ebee0,7f86fbac40f9,7f86fbacb36a,7f86fbac65b7,7f86fbd4a98f,7f8704c75608&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f86ef130000-7f86fc162b20 
E0616 17:40:13.057319   35402 process_state.cc:1061] RAW: Signal 11 raised at PC: 0x7f86f745aa20 while already in FailureSignalHandler!
E0616 17:40:13.057338   35402 process_state.cc:1064] RAW: tid: 35402 raised new signal
PC: @     0x7f86f745aa20  (unknown)  (unknown)
    @     0x7f86fbe2f1e0        976  (unknown)
    @     0x7f8704cd5210     135152  (unknown)
    @     0x7f86f73e2c14        592  (unknown)
    @     0x7f86f73e2854        416  (unknown)
    @     0x7f86f73e926e        960  (unknown)
    @     0x7f86f73ebee1        352  (unknown)
    @     0x7f86fbac40fa         64  (unknown)
    @     0x7f86fbacb36b         96  (unknown)
    @     0x7f86fbac65b8         48  (unknown)
    @     0x7f86fbd4a990        240  (unknown)
    @     0x7f8704c75609  (unknown)  start_thread
https://symbolize.stripped_domain/r/?trace=7f86f745aa20,7f86fbe2f1df,7f8704cd520f,7f86f73e2c13,7f86f73e2853,7f86f73e926d,7f86f73ebee0,7f86fbac40f9,7f86fbacb36a,7f86fbac65b7,7f86fbd4a98f,7f8704c75608&map=ca1b7ab241ee28147b3d590cadb5dc1b:7f86ef130000-7f86fc162b20 
E0616 17:40:13.059248   35396 coredump_hook.cc:292] RAW: Remote crash data gathering hook invoked.
E0616 17:40:13.059267   35396 client.cc:222] RAW: Coroner client retries enabled (b/136286901), will retry for up to 30 sec.
E0616 17:40:13.059274   35396 coredump_hook.cc:447] RAW: Sending fingerprint to remote end.
E0616 17:40:13.059281   35396 coredump_socket.cc:124] RAW: Stat failed errno=2 on socket /var/google/services/logmanagerd/remote_coredump.socket
E0616 17:40:13.059291   35396 coredump_hook.cc:451] RAW: Cannot send fingerprint to Coroner: [NOT_FOUND] Missing crash reporting socket. Is the listener running?
E0616 17:40:13.059301   35396 coredump_hook.cc:522] RAW: Dumping core locally.
</pre>
</details>

**Comment by hawkinsp** [comment]
This certainly shouldn't crash, but I will mention that `int64` math isn't native on TPUs, so you'd do better to avoid it if you can (e.g., use `int32` or `float`).

**Comment by seanmor5** [comment]
Thank you @hawkinsp! We have a pretty large test suite that was built and tested on CPU/GPU and it took awhile to figure out what the problem was when the suite was just crashing on TPU. All of our other unsupported 64-bit tests would raise a clean error. We ended up tagging these tests to be skipped on TPU anyway, but I figured it shouldn't crash. Thanks again!

**Comment by hawkinsp** [comment]
This issue is now fixed with current versions of XLA. (That probably means "in a reasonably recent nightly cloud TPU VM" at the moment.)
