### ISSUE TITLE
atan2 on TPU inconsistent result

### ISSUE THREAD

**Issue by seanmor5** [google/jax#7020]
I apologize if this has been mentioned before - I wasn't able to find an open issue elsewhere. The result of `atan2` on TPU is inconsistent with CPU/GPU and is (maybe?) incorrect:

CPU: 
```python
from jax import lax

lax.atan2(-0.0, -0.0)

DeviceArray(-3.1415927, dtype=float32)
```

TPU:
```python
from jax import lax

lax.atan2(-0.0, -0.0)

DeviceArray(-0., dtype=float32)
```

As defined I guess atan2 is supposed to be undefined at 0, but going with https://en.cppreference.com/w/cpp/numeric/math/atan2 and other definitions isn't the CPU result correct in this case?

**Comment by hawkinsp** [comment]
I filed an internal bug against the XLA folks. IEEE754-2008 explicitly specifies the behavior you describe.

**Comment by hawkinsp** [comment]
This issue is fixed at XLA head. I would imagine the fix would be present in the next release or nightly build of `libtpu`.
