### ISSUE TITLE
GPU Memory usage of jax.numpy more than the actual size of the array

### ISSUE THREAD

**Issue by AkshayRoyal** [google/jax#7046]
Environment Specification
OS: Fedora 33
GPU : NVIDIA GeForce RTX 2070
CUDA Cores :2304
Total Dedicated Memory : 7982MB
Platform : Jupyter notebook (Anaconda virtual env)

```python
import jax.numpy as jnp
from jax import random
key = random.PRNGKey(0)
x = random.normal(key, (200000,1000))
x.nbytes/(1024**2) #size in MB
```
I check the GPU usage before running the code on jupyter notebook and then just after the execution of the above code.
The memory usage of GPU is far too much compared to the size of the array
Before Running the code : GPU usage is 1250MB
After Running the code : GPU usage is 7523MB 
time gap between the two observations of the GPU usage is approx 2 secs
I repeated the same process multiple times and everytime I faced the same issue.
Also, on initializing an array of size= (600000,1000) which is 4.47 GB the RuntimeError for Resource exhaustion is thrown
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-3eeb846fce94> in <module>
      1 key = random.PRNGKey(0)
----> 2 x = random.normal(key, (600000,1000))

~/anaconda3/envs/rapids-21.06/lib/python3.7/site-packages/jax/_src/random.py in normal(key, shape, dtype)
    653   dtype = dtypes.canonicalize_dtype(dtype)
    654   shape = core.as_named_shape(shape)
--> 655   return _normal(key, shape, dtype)  # type: ignore
    656 
    657 @partial(jit, static_argnums=(1, 2))

    [... skipping hidden 7 frame]

~/anaconda3/envs/rapids-21.06/lib/python3.7/site-packages/jax/interpreters/xla.py in _execute_compiled(compiled, avals, handlers, kept_var_idx, *args)
    891           for i, x in enumerate(args)
    892           if x is not token and i in kept_var_idx))
--> 893   out_bufs = compiled.execute(input_bufs)
    894   check_special(xla_call_p.name, out_bufs)
    895   return [handler(*bs) for handler, bs in zip(handlers, _partition_outputs(avals, out_bufs))]

RuntimeError: Resource exhausted: Out of memory while trying to allocate 6000000128 bytes.
```
I am not able to understand why does it need 5.587GB(6000000128 bytes) of memory when the ask is for lesser memory?

**Comment by jakevdp** [comment]
Hi - thanks for the question. This is expected due to JAX's pre-allocation of GPU memory; see https://jax.readthedocs.io/en/latest/gpu_memory_allocation.html for details.

**Comment by AkshayRoyal** [comment]
Thank you @jakevdp  for your prompt response.
