### ISSUE TITLE
Better error messages for vmap dimensions

### ISSUE THREAD

**Issue by vikas-sindhwani** [google/jax#705]
This piece of code is incorrect since in_axes should be (0, 0) instead of (0, 1)

def h(a, b):
 return np.sum(a) + np.sum(b)

X = onp.random.randn(10, 4)
U = onp.random.randn(10, 2)
vmap(h, in_axes=(0, 1))(X, U)

The current error message is:
"got inconsistent map dimension sizes: set([10, 2])"
 
I think the error message could describe the input shapes and mention which dimensions we are batching over.

**Comment by samuela** [comment]
I just got this error:
```
TypeError: got inconsistent map dimension sizes: {64, 1, 10, 4}
```
which really stumped me for a while... More clarity here would definitely be helpful!

**Comment by mattjj** [comment]
After #1613 the error printed is

```
ValueError: vmap got inconsistent sizes for array axes to be mapped:
arg 0 has shape (10, 4) and axis 0 is to be mapped
arg 1 has shape (10, 2) and axis 1 is to be mapped
so
arg 0 has an axis to be mapped of size 10
arg 1 has an axis to be mapped of size 2
```

Should be more informative!
