### ISSUE TITLE
In-place operations with Jax don't seem to work

### ISSUE THREAD

**Issue by ant-pls-dev** [google/jax#7116]
For benchmark purpose, in an attempt to evaluate numba versus jax for some snippets of code, I tried the following : 

```python
# pip install numpy==1.19.5 numba==0.53.1 jax==0.2.16 jaxlib==0.1.68

import numpy as np
import numba as nb
import jax
import jax.numpy as jnp
import time


@jax.jit
def inplace_func_jax(a):
    for i in range(a.size):
        a = a.at[i].set(2 * (2 * (a[i] + 1) + 1))


@nb.njit
def inplace_func_nb(a):
    for i in range(a.size):
        a[i] = 2 * (2 * (a[i] + 1) + 1)


x = np.arange(100, dtype=np.int32)
x_jax = jnp.array(x.copy())
x_nb = x.copy()


# warm up numba and jax
# np.asarray is used to make sure computation is executed

np.asarray(inplace_func_nb(x))
np.asarray(inplace_func_jax(x))


print("nb sum before :", x_nb.sum())
t0 = time.time()
np.asarray(inplace_func_nb(x_nb))
t1 = time.time()
print("nb time :", t1-t0)
print("nb sum after :", x_nb.sum())

print("")

print("jax sum before:", x_jax.sum())
t0 = time.time()
np.asarray(inplace_func_jax(x_jax))
t1 = time.time()
print("jax time :", t1-t0)
print("jax sum after:", x_jax.sum())
```

Output on my machine : 
```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
nb sum before : 4950
nb time : 1.239776611328125e-05
nb sum after : 20400

jax sum before: 4950
jax time : 3.0517578125e-05
jax sum after: 4950
```

"jax sum after" was expected to be equal to "nb sum after" : 
- Why is x_jax not modified in place here?
- Is there an idiomatic way of doing "inplace_func_nb" with Jax' XLA:CPU, without creating intermediary arrays/buffer, and which is competitive with the numba version? (an actual in-place operation)

**Comment by ant-pls-dev** [comment]
Note : the function does very trivial computations, however the numba jitted version is very fast (much faster than numpy), especially on larger-than-cache arrays

**Comment by jakevdp** [comment]
Hi - thanks for the clear question and reproduction! To answer your questions

> "jax sum after" was expected to be equal to "nb sum after" :
> - Why is x_jax not modified in place here?

JAX arrays are immutable, and cannot be modified in-place. in general Python operations of the form `x = <expression>` do not modify the contents of `x` in-place, but rather assign the result of `<expression>` to the variable `x`. This is true of numpy as well, where if you write something like `x = 2 * x` it will not result in the original `x` value being modified.

> Is there an idiomatic way of doing "inplace_func_nb" with Jax' XLA:CPU, without creating intermediary arrays/buffer, and which is competitive with the numba version? (an actual in-place operation)

The idiomatic way to do operations while avoiding intermediate buffer in JAX is to use JIT compilation. Under JIT, the sequence of operations will be compiled by XLA, and often XLA can fuse multiple computations to compute the desired results efficiently even if the eager evaluation of your code would have resulted in inefficient intermediate buffers. But because JAX arrays are immutable, the result  of the JIT-compiled code will always return a new buffer, and will never modify the input buffer.

Hope that helps!

**Comment by ant-pls-dev** [comment]
Hello,

Thank you for the confirmation. I based this experiment on these bits from "The Sharp Bits" (https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#index-update) : 

> If the input values of index_update aren’t reused, jit-compiled code will perform these operations in-place.

(Nitpicking : Regarding "The Sharp Bits", according to #6706, "index_update" is deprecated in favor of ".at[i].set(...)", so maybe the Sharp Bits documentation is lagging a bit. I first tried with index_update.)

Even if "a" is reassigned, I expected "a" to not be actually copied and replaced. Somewhere inside the function, "x_jax" or "a" are still copied when calling and executing "inplace_func_jax". I tried another snippet where everything is included in the JITed function: 

```python
@jax.jit
def inplace_func_jax():
    a = jnp.arange(100, dtype=np.int32)
    before = a.sum()
    for i in range(a.size):
        a = a.at[i].set(2 * (2 * (a[i] + 1) + 1))
    after = a.sum()
    return before, after

p = np.asarray(inplace_func_jax())
print(p)
# correctly prints [ 4950 20400]
```

The output is correct. However, without diving into IR/bytecode/traces, I have no way to confirm if the updates have been in-place, or if "a" has been overwritten by a new copy at every iteration. Maybe could it be interesting to have functions that fails if the in-place operations cannot be guaranteed? (Although I understand users should assume they are working with a functional framework that does not directly provide in-place operations, and they should trust the compiler instead)

Another funny unexpected result : 
```python
@jax.jit
def inplace_func_jax():
    x = np.arange(100000, dtype=np.int32)
    a = jnp.array(x)
    before = a.sum()
    for i in range(a.size):
        a = a.at[i].set(2 * (2 * (a[i] + 1) + 1))
    after = a.sum()
    return before, after
```
... is *very* slow to compile and also takes several gigabytes of RAM to compile. I guess the compiler is generating a specialized function for every possible size of x or something similar. I'm sure I can find the answer in the documentation or past issues, but maybe it would be nice if there were a warning in the console saying "WARNING:you triggered [...] slow behavior, please see [link to the doc]"

Anyway, I understand JAX' jit/XLA may not be optimized for this specific micro test case, as it doesn't actually involve any matrix/tensor operations... and the target is CPU. I guess this is a instance of using the right tool for the right job, and Numba is probably more suited for that specific case. From now on, I will approach JAX as a fully functional framework : some in-place operations may happen as an optimization, but I shouldn't assume in-place operations can be easily controlled/forced.

Thanks!
