### ISSUE TITLE
Qutip can't handle .jnp arrays

### ISSUE THREAD

**Issue by nlwach** [google/jax#7134]
I am trying to differentiate a quantum circuit which uses qutip. Whenever I try to create a `qutip.Qobj` using a `jnp.array` the created `qutip.Qobj` is empty. Somewhere the `jnp`arrays differ too much from the usual `np` arrays. The creation of `qutip.Qobj` using the standard `np.array`'s works perfectly fine.

Here the code for the `jnp` arrays:

```pyhton
state = jnp.array([1+0j, 1+0j])*1/jnp.sqrt(2)
Q_state = q.Qobj(state)
print(Q_state)
```
and the output

```
Quantum object: dims = [[1], [1]], shape = (1, 1), type = bra
Qobj data =
[[0.]]
```

And using `NumPy`arrays:
```pyhton
state = np.array([1+0j, 1+0j])*1/np.sqrt(2)
Q_state = q.Qobj(state)
print(Q_state)
```
and the output

```
Quantum object: dims = [[2], [1]], shape = (2, 1), type = ket
Qobj data =
[[0.70710678]
 [0.70710678]]
```

**Comment by jakevdp** [comment]
Hi - thanks for the question. It appears that qtip does not support duck-typed ndarrays, as you can see in the source: https://github.com/qutip/qutip/blob/dc2abc4be6540a3a3c549ed21d8da83f3f0db5aa/qutip/qobj.py#L221-L343

JAX arrays do not meet any of the `isinstance` checks used there, so they appear to be incompatible with the package. I would suggest explicitly casting the input to numpy, i.e.
```python
Q_state = q.Qobj(np.asarray(state))
```
If you would like qutip to support JAX and other numpy-like arrays (perhaps by checking for an `__array__` attribute on the input), I would suggest opening a feature request in the Qutip repository.
