### ISSUE TITLE
Will JAX add bf16 support soon?

### ISSUE THREAD

**Issue by ghosh-r** [google/jax#7149]
Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

PyTorch will soon add bf16 support on GPUs. Where is JAX on that?

Will JAX soon add support for bf16 precision on GPUs?

**Comment by jakevdp** [comment]
Hi - thanks for the question! JAX already supports bfloat16 on all backends; for example:
```python
import jax
print(jax.default_backend())
# gpu
print(repr(jax.numpy.arange(10, dtype='bfloat16')))
# DeviceArray([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=bfloat16)
```

**Comment by mattjj** [comment]
I think XLA:GPU very recently added support for Ampere TensorCores (for matrix multiplication and convolutions on bf16 values), but that support isn't yet included in the prebuilt jaxlib available on pypi. That is, if you want these operations on bf16 values to make use of TensorCores, you will have to [build your own jaxlib](https://jax.readthedocs.io/en/latest/developer.html#building-from-source) until we upload a new jaxlib.
