### ISSUE TITLE
Constraints for jaxlib version during jax installation

### ISSUE THREAD

**Issue by lumip** [google/jax#7174]
In v0.2.11 jax added the nice optional installation targets `cpu`, `cudaXXX` and `tpu` which install jaxlib for the desired platform. Currently, the setup script guarantees that the installed version of jaxlib is compatible by constraining the version number from below to the earliest known compatible version. However, no similar constraint is put for a maximum compatible version number. Given that jaxlib does not appear to necessarily maintain backward compatibility between updates, this is an issue for installing older versions of jax (as these will always pull the latest available jaxlib version, leading to crashes due to incompatibility).

Jax installation should always result in a working setup, i.e., only the latest compatible version of jaxlib should be installed when installing jax. This either requires version constraints in jax's setup.py or backward compatibility guarantees in jaxlib (or a combination of both).

Please:

- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by jakevdp** [comment]
Thanks for the report – I believe we do pin jaxlib to the current version at the time of the given JAX release; see the source here: https://github.com/google/jax/blob/c97d63dec33845a13c9243a8f821a7d093ff5cfa/setup.py#L43-L60

That said, pip's behavior surrounding extra requirements and version specifications has surprised me before, so it may be that pip doesn't respect these version pinnings during actual installation, but I would consider that a pip bug.

**Comment by jakevdp** [comment]
A potential TODO is to pin the extra requirements for cpu to `jaxlib==_current_jaxlib_version` rather than `jaxlib>=_minimum_jaxlib_version`.

**Comment by lumip** [comment]
Ah, I was apparently focussing only on the `cpu` target and didn't notice that for GPU and TPU this is indeed pinned. The todo you suggest would prevent the incompatibility problem I was worrying about, at the (small?) cost of also preventing users from benefitting from updates to jaxlib that would still be compatible to the version of jax they are installing. But I think this latter point is something that cannot be helped without some backward-compatibility policy reflected in version numbering for jaxlib/jax.

**Comment by jakevdp** [comment]
Sounds good - are you interested in sending a PR? If not I'm happy to take care of it.

**Comment by lumip** [comment]
I don't have the time right now, so please go ahead :)
