### ISSUE TITLE
v0.1.69 Build - Warning Get Tensorflow RT 404 Not Found

### ISSUE THREAD

**Issue by oracle3001** [google/jax#7214]
When attempting to build latest Jaxlib, I get the following warning about being unable to download the Tensorflow RT.

```
WARNING: Download from http://mirror.tensorflow.org/github.com/tensorflow/runtime/archive/73178e93e80de7b2e69aa95cbee99d661dbbe6c2.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found

DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  C:/sdks/jax-jaxlib-v0.1.69/WORKSPACE:34:10: in <toplevel>
  C:/users/adam/_bazel_adam/omyha2fz/external/org_tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  C:/users/adam/_bazel_adam/omyha2fz/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  C:/users/adam/_bazel_adam/omyha2fz/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
```

And also the same for LLVM

`WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/d0fe294729a2ac45625ed45a5619c8405a14db49.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found`

**Comment by hawkinsp** [comment]
That's a (benign) warning. The source of truth for most of these upstream repositories is github, but we mirror them so we can still build if Github is down, as well as to share the load. However, the mirrors aren't always up to date, particularly when building from git head or close to it. At some point they will catch up at and the warning should go away. The warning should be harmless, though, since we can (almost) always download from Github.

Hope that helps!

**Comment by zhangqiaorjc** [comment]
@oracle3001 thanks for trying to build jaxlib on Windows. Let us know if v0.1.69 builds successfully on Windows. Thanks!

**Comment by oracle3001** [comment]
> @oracle3001 thanks for trying to build jaxlib on Windows. Let us know if v0.1.69 builds successfully on Windows. Thanks!

Yes it does, thank you.
