### ISSUE TITLE
recent np.linalg.eig broke builds

### ISSUE THREAD

**Issue by proteneer** [google/jax#722]
Bisecting shows that commit a96944eb535d76ffa0f74dfecdf8a856a29bc658 broke the jaxlib build on my system:

```
Error compiling Cython file:
------------------------------------------------------------
...
      lwork * sizeof(double complex))

  for i in range(b):
    memcpy(a_work, a_in, n * n * sizeof(double complex))
    zgeev(&jobvlr, &jobvlr, &n, a_work, &n, w_out, vl_out, &n, vr_out, &n,
          work, &lwork, r_work, info_out)
                               ^
------------------------------------------------------------

jaxlib/lapack.pyx:1130:32: Converting to Python object not allowed without gil
```

**Comment by hawkinsp** [comment]
What versions of python, scipy and cython do you have installed?

**Comment by proteneer** [comment]
Sorry this was my fault - I had an incompatible scipy/cython version.

**Comment by mattjj** [comment]
No worries -- don't hesitate to open issues here because even if they're not bugs in the JAX code, we might have seen them before and be able to help, and in any case others who run into the same problem will probably benefit from seeing the issue get resolved!
