### ISSUE TITLE
Incorrect results on jaxlib-0.1.68 CPU

### ISSUE THREAD

**Issue by zhangqiaorjc** [google/jax#7229]
jaxlib-0.1.68 has defaulted to a new CPU backend; we recently noticed it produced incorrect results only in open source, and narrowed it down to undefined behavior that shows up in gcc (open source build) and not in clang (Google)

a simple repro looks like

```
from absl.testing import absltest
import jax
from jax import test_util as jtu
import numpy as np
import jax.numpy as jnp

def f(image, delta):
        return image + jnp.asarray(delta, image.dtype)

_IMG_SHAPE = (131, 111, 3)
_RAND_FLOATS_IN_RANGE = list(
    np.random.uniform(0., 1., size=(10,) + _IMG_SHAPE).astype(np.float32))

class Repro(jtu.JaxTestCase):

  def test_f(self):
    jax_fn=f
    jax_fn_jitted = jax.jit(jax_fn)
    for image_rgb in _RAND_FLOATS_IN_RANGE:
      argument = np.random.uniform(-0.5, 0.5, size=())
      adjusted_jax = jax_fn(image_rgb, argument)
      adjusted_jit = jax_fn_jitted(image_rgb, delta=argument)
      self.assertAllClose(adjusted_jax, adjusted_jit, rtol=1e-4, atol=1e-4)

if __name__ == "__main__":
  absltest.main()
```

This bug will be fixed in the next release in a day or two.

**Comment by zhangqiaorjc** [comment]
Fixed in https://github.com/tensorflow/tensorflow/commit/8cc3ffa8d8e4dd659c1534849cf5984ef4ec3532

New jaxlib release started.

**Comment by hawkinsp** [comment]
jax 0.2.17 has been released, and it uses the older (correct) runtime for jaxlib 0.1.68.

**Comment by zhangqiaorjc** [comment]
jaxlib-v0.1.69 has been released
