### ISSUE TITLE
Support for GPU SVD

### ISSUE THREAD

**Issue by Thenerdstation** [google/jax#723]
For doing physics simulation (especially quantum physics) complex SVDs are done very often. It would be a big win for our team if we could get acceleration of this on GPU.

**Comment by proteneer** [comment]
FWIW: in theory this is supported through https://docs.nvidia.com/cuda/cusolver/index.html (look for cusolverDnCgesvd)

**Comment by Thenerdstation** [comment]
Yeah that should make it much easier to implement. I think it was just the plumbing that had to be built?

**Comment by hawkinsp** [comment]
Yes, this is mostly a matter of plugging the cuSolver implementation into JAX.

I will note that complex SVD is already available on CPU (via LAPACK), so you should be able to prototype that way even if it's slower.

**Comment by zhongwen** [comment]
+1

**Comment by romanngg** [comment]
+1, see also https://github.com/google/jax/issues/825

**Comment by ravidziv** [comment]
+1

**Comment by Hwhitetooth** [comment]
+1
