### ISSUE TITLE
Tagging unit test failures to be skipped for ROCm

### ISSUE THREAD

**Issue by reza-amd** [google/jax#7271]
Hi JAX developers,
We are trying to setup our CI builds for JAX and ROCm to help supporting JAX on AMD GPUs.

To track issues effectively, we need a way to filter the known unit tests failures to be excluded from the CI builds (similar to "no_rocm" tag in bazel and "is_built_with_rocm()" in tf.test).

These are the features we are trying to achieve:

- Excluding a whole test file from testing
- Excluding a test case 
- Modifying test case input, if JAX has been built with ROCm.

At the moment, we have two paths to follow, and we like to hear your opinions on these, or propose another solution:

Solution1:
Using "skip_on_flag" functionality to mark excluded test cases, and add a new environment variable (to specify rocm build) and use "if" statements on this new variable to modify the test inputs for ROCm (if necessary).

Solution2:
Include the "no_rocm" and "is_built_with_rocm" from TensorFlow in build files, and use an approach similar to TensorFlow in JAX.

@hawkinsp

**Comment by hawkinsp** [comment]
We already have `jax.test_util.skip_on_devices()`. Currently it knows about `"cpu"`, `"gpu"`, and `"tpu"`. Perhaps it suffice to teach that function about `rocm` as well? I'd be tempted to leave `"gpu"` meaning "all gpus" and have `"cuda"` and `"rocm"` mean NVidia and AMD GPUs specifically.

I'd be tempted to expose the necessary information as a property on `Device` objects, if it isn't already exposed: while we don't support it at the moment, one can imagine in the future you might have both NVidia and AMD GPUs in the same process.

I note that there's already a `.device_kind()` field on devices that is close to what you want, but I think we should perhaps add a `.vendor()` field or something like that.

**Comment by reza-amd** [comment]
Thanks for the comment.
I tried to follow your suggestion in [this](https://github.com/tensorflow/tensorflow/pull/50799) PR for TensorFlow.

If I understood you correctly, based on your suggestion, we can use the ```jax.test_util.skip_on_devices()``` for skipping test cases and the ```device_vendor``` property (will be enabled by the mentioned PR) to modify the test case for AMD devices.
