### ISSUE TITLE
Bug in np.eye.

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#728]
As suggested, it seems like np.eye broke at some point. To repro try, `np.allclose(onp.eye(N), np.eye(N))`. 

Upon closer inspection, it seems like this only kicks in at large N. Try e.g. 5000.

**Comment by mattjj** [comment]
Interestingly, it seems that `onp.allclose` works and `np.allclose` doesn't...

**Comment by sschoenholz** [comment]
The nature of the bug is that np.eye(N) for large N ends up with more nonzero entries than expected. Dogus will followup with some plots that show this as a function of N.

**Comment by mattjj** [comment]
I think we got it. See commits on #730.

**Comment by sschoenholz** [comment]
Awesome, thanks for the super quick fix (as always)!

**Comment by mattjj** [comment]
Thanks so much for raising this!

**Comment by mattjj** [comment]
The more unpleasant thing is that this revealed an important hole in our test coverage, so #730 adds several checks that would have caught this issue.

**Comment by mattjj** [comment]
Just uploaded jax 0.1.31 to pypi with this fix.
