### ISSUE TITLE
Build jaxlib from source Windows 

### ISSUE THREAD

**Issue by GMCobraz** [google/jax#7285]
(base) C:\Users\Aries>conda activate pymc3

(pymc3) C:\Users\Aries>bazel version
Build label: 4.0.0
Build target: bazel-out/x64_windows-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 21 07:39:16 2021 (1611214756)
Build timestamp: 1611214756
Build timestamp as int: 1611214756

(pymc3) C:\Users\Aries>gcc --version
gcc (Rev5, Built by MSYS2 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(pymc3) C:\Users\Aries>g++ --version
g++ (Rev5, Built by MSYS2 project) 5.3.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(pymc3) C:\Users\Aries>python .\build\build.py --enable_cuda
python: can't open file '.\build\build.py': [Errno 2] No such file or directory

Anyone can help to point some possible solutions?

Thank you very much

**Comment by hawkinsp** [comment]
You need to build from within a git checkout of the JAX source tree.

**Comment by GMCobraz** [comment]
Hi @hawkinsp,

(pymc3) C:\Users\Aries\jax>set PATH=%PATH%; C:\Users\Aries\bazel

(pymc3) C:\Users\Aries\jax>set PATH=%PATH%; C:\Users\Aries\msys64\usr\bin

(pymc3) C:\Users\Aries\jax>python .\build\build.py --enable_cuda --cuda_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" --cudnn_path="C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1" --cuda_compute_capabilities="5.0" --cuda_version="10.1" --cudnn_version="7.6.5"

 _   _  __  __
| | / \ \ \/ /
_ | |/ _ \ \ /
| || / ___ /
___// /_/_\

Cannot find or download bazel. Please install bazel.

Did I set the the bazel path wrong?
Thank you very much.
