### ISSUE TITLE
ravel, flatten don't return copies of 1D arrays

### ISSUE THREAD

**Issue by lukepfister** [google/jax#7287]
The docstring for ravel states:
```
Return a contiguous flattened array.

LAX-backend implementation of :func:`ravel`.

The JAX version of this function will return a copy rather than a view of the input.
```

But this isn't true if the array is already flattened:
```python
import jax.numpy as jnp
x = jnp.array([1, 2, 3])
x.ravel().unsafe_buffer_pointer() == x.unsafe_buffer_pointer() #False
```
Why does this matter? It probably doesn't, but the behavior doesn't match the documentation.

**Comment by hawkinsp** [comment]
#7325 clarifies the documentation to state that JAX *may* return a copy, as opposed to *will* return a copy.
