### ISSUE TITLE
Buggy Subscript Parsing in einsum Function

### ISSUE THREAD

**Issue by daskol** [google/jax#7324]
There is an incompatibility between `jax.numpy` and `numpy` in `einsum()` implementation. JAX allows digits and other characters like underscore `_` in subscript but NumPy does not. Here is a snippet to demonstrate.
```python
import jax
import numpy as np

# Set up platform explicitely. There is no access to GPU at the moment.
jax.config.update('jax_platform_name', 'cpu')

# Create two 3-tensors of shape (1, 4, 2).
a = np.array([[[0.7434197 , 0.7274446 ],
               [0.4906099 , 0.814608  ],
               [0.95737267, 0.56509674],
               [0.74777645, 0.08735446]]], np.float32)
b = jax.numpy.array(a)

assert a.shape == (1, 4, 2)

# Get 2-tensor slice of 3-tensor
x = jax.numpy.einsum('1ij', b)  # Ok.
y = np.einsum('1ij', a)  # Fail!

# ValueError: invalid subscript '1' in einstein sum subscripts string, subscripts must be letters
```
Version of jax and jaxlib are 0.2.17 and 0.1.68 correspondently.

**Comment by hawkinsp** [comment]
In general we don't want to promise exact API compatibility with NumPy. In this case, it seems the behavior of JAX is a superset of NumPy's behavior. That seems fine to me?

FWIW, JAX's einsum parser is actually from `opt_einsum`, and this issue probably means that `opt_einsum` is more permissive than NumPy. But I'm not sure that's something we actually want to fix.

**Comment by daskol** [comment]
> this issue probably means that opt_einsum is more permissive than NumPy.
Totally agreed.

> However, in addition to the standard alphabet, opt_einsum also supports unicode characters:
It turns out that `opt_einsum` is much more permissive (even digit means axis).
