### ISSUE TITLE
Unused variable in "Training a Simple Neural Network Advanced Jax Tutorial Notebooks"

### ISSUE THREAD

**Issue by FelipeMartins96** [google/jax#7332]
On both https://github.com/google/jax/blob/main/docs/notebooks/Neural_Network_and_Data_Loading.ipynb and https://github.com/google/jax/blob/main/docs/notebooks/neural_network_with_tfds_data.ipynb notebooks, which are part of the Advanced JAX Tutorials, there is the usage of impure functions.

The step size value which is used on the jitted update function is a global value.

Also, the network initial parameters scale is being as hyperparameters but is not being used, and the actual value used is different.

**Comment by hawkinsp** [comment]
This is really a question of how you define a "pure function".

Yes, in both notebooks, `step_size` is a global variable that is referred to by `update`. So you could argue that by any structural definition of purity it is not pure. It is technically true that if `step_size` were to change, then the behavior of `update` (in the absence of `jit`, etc.) would change, i.e., `update` is not in the strictest sense only a mathematical function of its arguments. But `step_size` does *not* change in this program, so we can consider it in a practical sense "pure": in *this* program, in the way it is used, it acts like a pure function.

Recall also that purity is not something that JAX enforces. Purity is a promise that programmers make to JAX. JAX doesn't really care whether a function uses state internally. All we require is that the programmer must promise that functions transformed by JAX transformations like `jit` act like pure functions, that is, if the function is supplied identical inputs, it will return identical outputs. So long as, during the execution of any given program, that property is maintained, that is all we need.

Hope that helps!

You're correct that `param_scale` is not used. Do you want to send a PR fixing that?

**Comment by FelipeMartins96** [comment]
Got it! Thank you for the explanation.

Sure, I'll create a PR right away.
