### ISSUE TITLE
Chaining JVPs results in infinite recursion

### ISSUE THREAD

**Issue by zgbkdlm** [google/jax#7355]
Hello,
I am currently rewriting the code of my [paper](https://ieeexplore.ieee.org/document/9308966) on continuous-discrete filtering in JAX to make it more efficient and readable (at the moment it relies on SymPy to compote the chain rule...) 

In order to to this, I essentially need to compute a chain of JVP evaluated at the same tangents everytime, informally: `jvp(jvp(jvp(...,v), v), v)` where `v` is the fixed tangent. However when doing it programatically, this results in an infinite recursion as illustrated by the code below.

```python
import jax
import jax.numpy as jnp

def compose_jvp(fun, tangents, n):
    def res(x): return jax.jvp(fun, (x,), tangents)[1]
    for _ in range(n-1):
        def res(x): return jax.jvp(res, (x,), tangents)[1]
    return res

cfun = compose_jvp(jnp.sin, (1.,), 10)
cfun(0.1)  # infinite recursion
```
However doing the same thing manually (see below) works fine. 

```python
afun = lambda z: jax.jvp(jnp.sin, (z,), (1.,))[1]
bfun = lambda zz: jax.jvp(afun, (zz,), (1.,))[1]
bfun(0.1)
```

I can't see anything wrong with my code, what do you think is happening?

Thanks!

**Comment by hawkinsp** [comment]
This isn't a JAX bug. The issue is that your Python program has infinite recursion.

Try:
```
import jax
import jax.numpy as jnp
from functools import partial

def compose_jvp(fun, tangents, n):
    def res(f, x): return jax.jvp(f, (x,), tangents)[1]
    for _ in range(n-1):
      fun = partial(res, fun)
    return fun

cfun = compose_jvp(jnp.sin, (1.,), 10)
print(cfun(0.1))
```

**Comment by zgbkdlm** [comment]
> This isn't a JAX bug. The issue is that your Python program has infinite recursion.
> 
> Try:
> 
> ```
> import jax
> import jax.numpy as jnp
> from functools import partial
> 
> def compose_jvp(fun, tangents, n):
>     def res(f, x): return jax.jvp(f, (x,), tangents)[1]
>     for _ in range(n-1):
>       fun = partial(res, fun)
>     return fun
> 
> cfun = compose_jvp(jnp.sin, (1.,), 10)
> print(cfun(0.1))
> ```

Thank you!
