### ISSUE TITLE
consider adding a jax_numpy_dtype_promotion option

### ISSUE THREAD

**Issue by mattjj** [google/jax#7368]
A user observed that they had an unintentional and silent bfloat16 to float32 promotion which was hard to track down. This kind of promotion is [intended for jax.numpy operations](https://jax.readthedocs.io/en/latest/type_promotion.html) (including infix operators like `*`). But it can be undesirable.

```
In [11]: x = jnp.ones([3], dtype=jnp.float32)
In [12]: x
Out[12]: DeviceArray([1., 1., 1.], dtype=float32)
In [13]: y = jnp.ones([3], dtype=jnp.bfloat16)
In [14]: y
Out[14]: DeviceArray([1, 1, 1], dtype=bfloat16)
In [15]: x * y
Out[15]: DeviceArray([1., 1., 1.], dtype=float32)
```

This is like the situation with unexpected float64 promotions, for which we have the option `enable_x64` (and a default which deviates from NumPy). This is also analogous to the situation with the [`jax_numpy_rank_promotion` option](https://jax.readthedocs.io/en/latest/rank_promotion_warning.html), which is similarly meant to disable a kind of automatic `jax.numpy`-level promotion in favor of stricter semantics.

One option is to use the `lax` functions directly, since they are more strict in that they don't allow silent dtype promotion (or rank promotion, so their behavior is decidedly _less_ "lax" than that of analogous `jax.numpy` operations):

```
In [3]: x = jnp.ones([3], dtype=jnp.float32)
In [4]: x
Out[4]: DeviceArray([1., 1., 1.], dtype=float32)
In [5]: y = jnp.ones([3], dtype=jnp.bfloat16)
In [6]: y
Out[6]: DeviceArray([1, 1, 1], dtype=bfloat16)
In [7]: lax.mul(x, y)
...
TypeError: mul requires arguments to have the same dtypes, got float32, bfloat16.
```

But infix operators are convenient. Moreover, unintended promotion might still happen in library code.

Another option is to add a `jax_numpy_dtype_promotion` option. It would have to be checked in [this logic](https://github.com/google/jax/blob/1db53b11755a86d69238b4e999ad011d1142e23c/jax/_src/numpy/lax_numpy.py#L270) (and perhaps other places), following an analogous pattern to [how the `jax_numpy_rank_promotion` option is checked in the `_promote_shapes` function](https://github.com/google/jax/blob/1db53b11755a86d69238b4e999ad011d1142e23c/jax/_src/numpy/lax_numpy.py#L234-L262). We'd also have to create the option in config.py, analogous to [how we create the `jax_numpy_rank_promotion` option](https://github.com/google/jax/blob/1db53b11755a86d69238b4e999ad011d1142e23c/jax/_src/config.py#L531-L540).

It's not clear yet if this is a good idea, but unless someone can spot a knock-down argument for why this won't work, it might be worth trying.

**Comment by shoyer** [comment]
Another way to this might be to make alternative versions of dtypes that don't implement type promotion, e.g., `jnp.strict_bfloat16` which works exactly like `jnp.bfloat16` but doesn't participate in type promotion. Or you could even put this in the metadata custom NumPy dtypes, e.g., `np.dtype(np.float32, metadata={'strict': True})` (NumPy itself doesn't propagate metadata in operations, but JAX could).

The virtue of this sort of approach is that it would be based on local control, rather than being a global flag, which would make it easier to use in combination with external libraries that might use promotion internally.

**Comment by jakevdp** [comment]
Done in https://github.com/google/jax/pull/10824
