### ISSUE TITLE
tree_util.treedef_tuple fails to set num_leaves on the returned treedef

### ISSUE THREAD

**Issue by shawwn** [google/jax#7377]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
from jax import tree_util
leaves, td = tree_util.tree_flatten( (1, (2, 3), [4], {'a': 42}, 99) )
td.num_leaves, td.num_nodes
# (6, 10)
td2 = tree_util.treedef_tuple(td.children())
td2.num_leaves, td2.num_nodes
# (0, 10)
```

Notice `td.num_leaves` is `6`, but `td2.num_leaves` is `0`.

**Comment by froystig** [comment]
The next jaxlib release will include a fix, by way of https://github.com/tensorflow/tensorflow/commit/5009f5c251b967c40791486e2447f14e3f5256d0. I've added a jax-side test in 86c48ccb7c116d207d235b319912c2de8b7ce41a. Thanks!
