### ISSUE TITLE
bazel server cannot be shutdown

### ISSUE THREAD

**Issue by samuela** [google/jax#739]
The recommended install instructions involve `python build/build.py`, which starts up a bazel server and then sends it build commands. However, there's no cleanup of the server once the build has completed. Attempting to shutdown the server with
```
$ ./build/bazel-0.24.1-linux-x86_64 shutdown
```
returns a 0 exit code but doesn't actually kill the bazel server process as far as I can tell.

I'm running on AWS Ubuntu 18.04.

**Comment by hawkinsp** [comment]
The bazel server will eventually time out.

I'll add a "bazel shutdown" to the build script. If that doesn't work, the best I can suggest is to file a bazel bug. However, note that bazel doesn't share state between workspaces, so if you have run a bazel build from a different directory consider the possibility that the bazel process may be from another workspace. This would at least explain why your manual shutdown had no effect.
