### ISSUE TITLE
How to `vmap` over a batch of trees or dictionaries?

### ISSUE THREAD

**Issue by cisprague** [google/jax#7430]
**Issue**
I want to `vmap` a function over a batch of trees or dictionaries.
However, I am not sure what the appropriate way to pass such a batch is (see the example below).

**Related**
#2367 dealt with passing dictionaries to `vmap`ed functions that do not `vmap` over dictionary entries.
#3161 dealt with `vmap`ing over dictionary entries.
This issue is different because it deals with `vmap`ing over a batch of dictionaries.

**Background**
I want to `vmap` a `haiku` NN execution over a batch of different parameters.
Below is an example that deals with the same issue.

**Minimal example**
Case 0 and 1 work as expected, 2 and 3 do not.

```python
from jax import vmap
import jax.numpy as np

def f(x, params):
  return params['a']*x + params['b']

print('\nCase 0:')
print(f(2, dict(a=3, b=4)))

print('\nCase 1:')
print(vmap(f, in_axes=(0, None))(
    np.array([2, 2]), 
    dict(a=3, b=4)
))

print('\nCase 2:')
try:
  print(vmap(f, in_axes=(0, 0))(
      np.array([2, 2]),
      [dict(a=3, b=4), dict(a=3, b=4)]
  ))
except Exception as e:
  print(e)

print('\nCase 3:')
try:
  print(vmap(f, in_axes=(0, 0))(
      np.array([2, 2]),
      np.array([dict(a=3, b=4), dict(a=3, b=4)])
  ))
except Exception as e:
  print(e)
```

**Output**
```
Case 0:
10

Case 1:
[10 10]

Case 2:
vmap got arg 1 of rank 0 but axis to be mapped 0. The tree of ranks is:
((1, [{'a': 0, 'b': 0}, {'a': 0, 'b': 0}]), {})

Case 3:
JAX only supports number and bool dtypes, got dtype object in array
```

**Comment by pharringtonp19** [comment]
I think the following should work: 

```
import jax.numpy as jnp 
from jax import vmap

def f(x, params):
  return params['a']*x + params['b']

vmap(f, in_axes=(0, 0))(jnp.array([2, 2]), {'a': jnp.array([3, 3]), 'b': jnp.array([4, 4])})
```

**Comment by cisprague** [comment]
> I think the following should work:
> 
> ```
> import jax.numpy as jnp 
> from jax import vmap
> 
> def f(x, params):
>   return params['a']*x + params['b']
> 
> vmap(f, in_axes=(0, 0))(jnp.array([2, 2]), {'a': jnp.array([3, 3]), 'b': jnp.array([4, 4])})
> ```

@pharringtonp19 Thanks. It seems like this solution would work like in #3161.
I'd need to assemble a new dictionary from my batch of dictionaries, which I guess is easy since they have the same keys.
But, it would be convenient if I could just do it like I showed in case 3 in my example.
Maybe it can be a new feature?

**Comment by pharringtonp19** [comment]
You have probably already considered this, but depending on how you construct your dictionary, you could let `vmap` do the work for you. That is, you could create` {'a': jnp.array([3, 3]), 'b': jnp.array([4, 4])} `by applying `vmap` to the function that `returns dict(a=3, b=4)`

```
import jax.numpy as jnp 
from jax import vmap

def f(x, params):
  return params['a']*x + params['b']

def init_dict(arr):
  return {'a':arr[0], 'b':arr[1]}

vmap(f, in_axes=(0, 0))(jnp.array([2, 2]), vmap(init_dict)(jnp.array([[3, 4], [3, 4]])))
```

**Comment by tomhennigan** [comment]
As @pharringtonp19 points out, you might be able to achieve this by `vmap`-ing the `init` function from Haiku. Here is an example of doing that:

https://colab.research.google.com/gist/tomhennigan/d6ef50139547afa7b8e7631c209c8672/example-of-initializing-and-apply-an-ensemble-of-nets.ipynb

You may prefer to not initialize via vmap, in that case you would have a list of parameters that you would want to stack. We see this pattern (usually for stacking batches from a data pipeline):

```python
def make_batch(examples):
  return jax.tree_map(lambda *a: jnp.stack(a), *examples)

make_example = lambda i: {'a': jnp.zeros([1]) + i, 'b': jnp.zeros([2]) + i}
list_of_examples = [make_example(1), make_example(2), make_example(3)]
print(list_of_examples)
# [{'a': DeviceArray([1.], dtype=float32),
#   'b': DeviceArray([1., 1.], dtype=float32)},
#  {'a': DeviceArray([2.], dtype=float32),
#   'b': DeviceArray([2., 2.], dtype=float32)},
#  {'a': DeviceArray([3.], dtype=float32),
#   'b': DeviceArray([3., 3.], dtype=float32)}]

print(make_batch(list_of_examples))
# {'a': DeviceArray([[1.],
#                    [2.],
#                    [3.]], dtype=float32),
#  'b': DeviceArray([[1., 1.],
#                    [2., 2.],
#                    [3., 3.]], dtype=float32)}
```

**Comment by cisprague** [comment]
@tomhennigan thanks for the example and Colab notebook! This seems like a reasonable solution.
Maybe this could be a new end-user feature in Haiku, since pytrees is intended for JAX [internal users](https://jax.readthedocs.io/en/latest/pytrees.html#developer-information).

**Comment by tomhennigan** [comment]
Hi @cisprague , utilities like `jax.tree_map(..)` often appear in user code, so I would personally (although I am not a JAX core team member) consider this part of the public API. I suspect the docs discussing how pytrees work (e.g. the treedef etc) are what are intended to be "implementation details" which you should only consider if developing extensions (new tree types).

I'd be happy for this function to exist in a JAX library though, to avoid copy pasting, but I'm not sure Haiku is the right place (this function is not unique to Haiku and would benefit users of other JAX libraries). I'm not aware of any libraries with JAX recipes/snippets, but this would be at home there.
