### ISSUE TITLE
xmap slower than nested vmap

### ISSUE THREAD

**Issue by GJBoth** [google/jax#7442]
I'm working on a problem which requires vectorization over several axes. `vmap` has been a godsend in simplifying everything, but to vectorize multiple axes I need to nest vmap (four times in our case) to vectorize all. I tried `xmap` as the documentation states it vectorizes over everything and I get back results matching the nested `vmap` approach, but unfortunately it's much slower (approx 4x times). Here's a [notebook](https://colab.research.google.com/drive/1TZrL6x0oCFjcT18MuSX_Cx_ZkbSsWvck?usp=sharing) where I recreate the behavior.

I know `xmap` is experimental, but I wonder what's going on under the hood and if I'm doing anything wrong or suboptimal. I hope we can make it as fast because `xmap` is really awesome and I'd love to use it!

**Comment by apaszke** [comment]
xmap was removed from JAX, so this is obsolete
