### ISSUE TITLE
Unknown cloud_tpu_init KeyError

### ISSUE THREAD

**Issue by joshwolff1** [google/jax#7444]
Google Cloud TPU, v3-v8
```
pip install jax
python3

>>> import jax
/home/josh_wolff_7/.local/lib/python3.7/site-packages/jax/__init__.py:27: UserWarning: cloud_tpu_init failed: KeyEr
ror('<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content="initial-scale=1, minim
um-scale=1, width=device-width">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}ht
ml,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-widt
h:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100%
 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{b
order:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo
{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left
:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelo
go/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/brandi
ng/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{
background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-back
ground-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/
><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL 
<code>/computeMetadata/v1/instance/attributes/accelerator-type</code> was not found on this server.  <ins>That’s al
l we know.</ins>\n')
 This a JAX bug; please report an issue at https://github.com/google/jax/issues
  _warn(f"cloud_tpu_init failed: {repr(exc)}\n This a JAX bug; please report "
```

**Comment by skye** [comment]
We've updated the JAX install command for TPU (https://github.com/google/jax#pip-installation-google-cloud-tpu). Can you try:
`pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`

I'm not sure that will fix the problem, but it'll be helpful to make sure everything's properly installed and up-to-date. Please send the output of importing jax if there's still an error after that.

**Comment by joshwolff1** [comment]
Thank you for getting to this quickly. Unfortunately, I was under an extreme time crunch to get a server back and had to use AWS to do this so this no longer applies to me. Thank you though

**Comment by skye** [comment]
Ah ok. I'm gonna close this, but please let us know if you try again and run into this!

**Comment by KienHuynh** [comment]
I'm having the exact error message, even after installing jax using:
`pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html`
I'm using a TPU v2-8, created with --tf-version=2.4.1.

**Comment by skye** [comment]
Can you share the full TPU create command you're using? (Doesn't have to include full project name, etc.)

If you're not already, we recommend using the new Cloud TPU VM architecture, which requires using `gcloud alpha` commands. See https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm.

**Comment by KienHuynh** [comment]
I used this one:
```
gcloud compute tpus execution-groups create \
 --name=... \
 --zone=us-central1-f \
 --tf-version=2.4.1 \
 --machine-type=n1-standard-8 \
 --accelerator-type=v2-8
```
 
Anyway, I will try the gcloud alpha command to create a new one. Thanks.

**Comment by skye** [comment]
Ok yeah, you should try Cloud TPU VMs! They're much better for running JAX, see [this blog post](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) for a short explanation why.

Installing jax[tpu] on the old architecture will actually cause issues, as you're seeing. We should probably add a note to the README about this, I'll leave this issue open to track that.

**Comment by joshwolff1** [comment]
Hello - I am trying to do this again and running into the same issue. Currently ssh'ed into VM with TPU v3-8

**Comment by joshwolff1** [comment]
I followed this verbatim and it doesn't work - same error as above

Thank you for your help so far

https://cloud.google.com/tpu/docs/jax-quickstart-tpu-vm

**Comment by joshwolff1** [comment]
Here is a video of me going through the setup exactly, just so u can see what I mean

https://youtu.be/xsmelxcByII

**Comment by joshwolff1** [comment]
Note: I got the same error with

gcloud compute tpus execution-groups create --name=aix-test-jax **--zone=us-central1-f** --tf-version=2.4.1 --machine-type=n1-standard-1 **--accelerator-type=v2-8**

The changes are in bold -- I wanted to test v2-8 versus v3-8 --- no difference

**Comment by joshwolff1** [comment]
I followed the link you added above and ran the below commands. Received same error

```
pip install --upgrade pip
pip install "jax[tpu]>=0.2.16" -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

**Comment by skye** [comment]
You need to use the `glcoud alpha` commands as detailed in the quickstart. That's the only way to create TPU VMs, otherwise you're creating the original TPU Nodes (see https://cloud.google.com/tpu/docs/system-architecture-tpu-vm#tpu_nodes).

**Comment by hawkinsp** [comment]
Closing because the solution is to use Cloud TPU VMs!

**Comment by ngaer** [comment]
We want to use JAX in Kubernetes cluster, but GKE only supports TPU nodes. So we can't just switch to TPU VMs, to solve this issue.

But I believe there should be a workaround for TPU nodes as well, e.g. as I understand Google Colab also uses TPU nodes, and JAX works there without any issues. So as I understand from [colab_tpu.py](https://github.com/google/jax/blob/main/jax/tools/colab_tpu.py) we just need to correctly resolve gRPC host for our TPU and set it to the config. 

I tried several ways to do that without much luck. So I would really appreciate any hints @skye @hawkinsp.  Whether my thinking is correct? And if so how we can resolve and set the correct TPU host?

**Comment by skye** [comment]
I'm looking into this, but in the meantime, could you file a new issue with this question? Thanks!

**Comment by ngaer** [comment]
@skye Thanks, for your help. Here's a new issue - https://github.com/google/jax/issues/12917
