### ISSUE TITLE
GPU memory usage despite platform set to "cpu"

### ISSUE THREAD

**Issue by clemisch** [google/jax#7468]
Dear jax team,

I've noticed that jax uses a small amount (137 MiB) of GPU memory, even when the platform is set to `cpu`. 

```python
import jax
jax.config.update("jax_platform_name", "cpu")

jax.numpy.zeros(100_000) + 1   # uses 137 MiB on every GPU, independent of array size
```

This led to crashes on a server where the GPUs are completely full (not best practice, I know), even though no computation is performed on the GPU. 

Is this intended behavior? Is `jax_platform_name` deprecated?

---

A workaround is setting `CUDA_VISIBLE_DEVICES` to an empty string:

```python
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = ""

jax.numpy.zeros(100_000) + 1    # does not use GPU memory
```

**Comment by hawkinsp** [comment]
JAX now initializes all available platforms eagerly, including GPU if present. `jax_platform_name` determines which platform is preferred by default.

So this is working as intended, but you've identified one very good workaround if it's a problem (set `CUDA_VISIBLE_DEVICES` to the empty string).

If this is a problem we could possibly revive some sort of flag to remove certain platforms from the set we initialize.

**Comment by clemisch** [comment]
Thanks for the quick reply @hawkinsp. The workaround is fine for me. 

Fyi, the only difference is this printout

```
2021-08-03 14:30:05.074166: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device
is detected
```

which previously was suppressed when setting `jax_platform_name = "cpu"` .
