### ISSUE TITLE
Use bazel --version to check the bazel version

### ISSUE THREAD

**Issue by Flamefire** [google/jax#7507]
Please use `bazel --version` to check the version of Bazel. The currently used variant ignores the bazel-startup-options and actually starts a full bazel server which is a) overkill and b) wrong in case of options like `--output-user-root` and no or readonly home folders

Potential change:
```
try:
  version_output = shell([bazel_path, "--version"])
except subprocess.CalledProcessError:
  return False
match = re.search("(Build label:|bazel) *([0-9\\.]+)", version_output)
```

I kept the regexp generic enough so that you can still fall back to the current `bazel version` call and parse both kinds of output

**Comment by yashk2810** [comment]
Opened a PR for this: https://github.com/google/jax/pull/7516

**Comment by Flamefire** [comment]
Have you tried that? Because for me the output of `bazel --version` is e.g. `bazel 3.2.1`
So you MUST adjust the regexp to `re.search("bazel *([0-9\\.]+)", version_output)` so this keeps working unless earlier versions of bazel did output something different for `bazel --version` (not `bazel version` which indeed is different)

**Comment by hawkinsp** [comment]
@Flamefire I think @yashk2810 already fixed this in https://github.com/google/jax/pull/7523

**Comment by Flamefire** [comment]
Indeed. Thanks for pointing that out :+1:
