### ISSUE TITLE
jax_debug_nans

### ISSUE THREAD

**Issue by manuel-delverme** [google/jax#7510]
The [current implementation of quantile](https://github.com/google/jax/blob/606cbe036af2d18201709a7a33214d9246d1c495/jax/_src/numpy/lax_numpy.py#L5645) function generates NaNs that are detected when jax_debug_nans is activated.

```python
from jax.config import config
config.update("jax_debug_nans", True)
import jax.numpy as jnp
jnp.quantile(jnp.ones((3, 3)), 0.5)
```
```python
from jax.config import config
config.update("jax_debug_nans", True)
import jax.numpy as jnp
jnp.where(1, float('nan'), 1)
```

Traceback
```
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 5560, in percentile
    return quantile(a, q, axis=axis, out=out, overwrite_input=overwrite_input,
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 5370, in quantile
    return _quantile(a, q, axis, interpolation, keepdims, False)
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 5436, in _quantile
    a = where(any(isnan(a), axis=axis, keepdims=True), nan, a)
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1686, in where
    return _where(condition, x, y)
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 1669, in _where
    x, y = _promote_dtypes(x, y)
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 268, in _promote_dtypes
    return [lax._convert_element_type(x, to_dtype, weak_type) for x in args]
  File "/home/esac/projects/venv/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py", line 268, in <listcomp>
    return [lax._convert_element_type(x, to_dtype, weak_type) for x in args]
FloatingPointError: invalid value (nan) encountered in convert_element_type
python-BaseException
Invalid value encountered in the output of a jit function. Calling the de-optimized version.

```

**Comment by jakevdp** [comment]
Thanks for the report – we don't run many tests with debug_nans=True, which we probably should. This is akin to #7208, which I'm slowly chipping away at.

**Comment by jakevdp** [comment]
Quick question on this: it looks to me like they only way that `jnp.quantile` introduces `nan` values is when the input already contains a `nan`, in which case I think it's correct for `debug_nans` to catch it.

Do you have an example of code that leads to this error when no NaNs are present in the input?

**Comment by manuel-delverme** [comment]
Closing because i can not reproduce it,
the bug was happening with out nans in the input vector

**Comment by jakevdp** [comment]
Ok, no problem. If you come across it again feel free to re-open this issue or to open a new one, and we can do our best to help!

**Comment by manuel-delverme** [comment]
```
import jax.config
import jax.numpy
import jax.ops

jax.config.update("jax_debug_nans", True)

with jax.disable_jit():
    x0 = jax.numpy.zeros(1)
    jax.value_and_grad(lambda x: jax.scipy.special.logsumexp(x))(x0)

```

**Comment by manuel-delverme** [comment]
Internally logsumexp does:
```python
import jax.numpy

jax.config.update("jax_debug_nans", True)

with jax.disable_jit():
    jax.numpy.where(0., jax.numpy.nan, 0.)
```

Which is where the nan comes from.

**Comment by manuel-delverme** [comment]
Screenshot of jax trying to be helpful  
![image](https://user-images.githubusercontent.com/1309922/131270617-12fd6d37-3879-40ac-b357-9e18f48d50a3.png)

**Comment by jakevdp** [comment]
Can you check whether #7648 fixes the issue you're seeing? It's not yet made it into a release, so you'd have to install from the main branch.

**Comment by manuel-delverme** [comment]
![werks](https://user-images.githubusercontent.com/1309922/131274593-518fd380-6515-47e2-bf19-e2614d887f87.jpg)
