### ISSUE TITLE
Incorrect results for reverse-mode differentiation of scan wrt sequence

### ISSUE THREAD

**Issue by matt-graham** [google/jax#753]
Differentiating the output of a `scan` operation with respect to the sequence being scanned over seems to incorrectly give zero-derivatives when using reverse-mode routines such as `api.vjp` or `api.grad`. As a simple example if we define the following function

```Python
import jax.numpy as np
from jax import lax, api

def scan_func(ns, x0, a):

    def trans_func(x, n):
        x = x + a * n 
        return (x, x)

    _, xs = lax.scan(trans_func, x0, ns)
    
    return xs
```

and the following inputs

```Python
a = 1.
x0 = np.array(0.)
n_step = 5
ns = np.arange(n_step) * 1.  # force float
```
and define `xs = scan_func(ns, x0, a)` then we would expect the Jacobian `dxs[i] / dns[j]` to be a lower-triangular matrix with all one entries.

Applying `api.jvp` to `scan_func` to compute a series of JVPs to construct the Jacobian gives the correct result:

```Python
np.stack([
    api.jvp(lambda ns_: scan_func(ns_, x0, a), (ns,), (basis_vct,))[1]
    for basis_vct in np.identity(n_step)], 1)
```

outputs

```Python
DeviceArray([[1., 0., 0., 0., 0.],
             [1., 1., 0., 0., 0.],
             [1., 1., 1., 0., 0.],
             [1., 1., 1., 1., 0.],
             [1., 1., 1., 1., 1.]], dtype=float32)
```

However trying something analogous with `api.vjp` gives a zero-matrix out:

```Python
np.stack([
    api.vjp(lambda ns_: scan_func(ns_, x0, a), ns)[1](basis_vct)[0]
    for basis_vct in np.identity(n_step)], 0)
```

outputs

```Python
DeviceArray([[0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.],
             [0., 0., 0., 0., 0.]], dtype=float32)
```

Similarly applying `api.grad` to the sum the output of `scan_func` gives the incorrect result

```Python
api.grad(lambda ns: np.sum(scan_func(ns, x0, a)))(ns)
```

outputs

```Python
_FilledConstant([0., 0., 0., 0., 0.], dtype=float32)
```

rather than the expected `DeviceArray([5., 4., 3., 2., 1.], dtype=float32)`.

This only appears to be an issue when differentiating with respect to an argument corresponding to the sequence being scanned over - for example both

```Python
api.grad(lambda x0_: np.sum(scan_func(ns, x0_, a)))(x0)
```

and

```Python
api.grad(lambda a_: np.sum(scan_func(ns, x0, a_)))(a)
```

output the correct values.

**Comment by mattjj** [comment]
Thanks for the wonderful report! That's super clear.

In the last couple hours we just squashed a scan autodiff bug in #749 (and greatly improved the scan autodiff tests, which were lacking, pretty sloppy of us). That fix is merged into master and on pypi as well (as jax version 0.1.34 and later).

I tried your code on master after that fix and it seems to work. It seems we caught the bug at about the same time! Can you check that fix on master (and jax 0.1.34) fixes things for you?

(On master, we now [check scan forward- and reverse-mode (and mixed mode) derivatives up to order 2](https://github.com/google/jax/blob/master/tests/lax_control_flow_test.py#L649) using the handy `check_grads` function that all our users should use.)

**Comment by matt-graham** [comment]
Thanks for the super quick response!

Re-running the code after pulling the latest commits does indeed now give the expected results - great timing with the fix :smile: !

Thanks also for the heads-up with regards to the `check_grads` function - I had previously been manually doing finite-difference checks so that will makes things a lot easier.

**Comment by mattjj** [comment]
Apologies for any time of yours this bug wasted. I can't believe we forgot to use our own `check_grads` on scan. That'll teach us... I'll never forget you again, `check_grads`!

Maybe we should put `check_grads` in every code example.

In any case, glad you're unstuck, and thanks again for making this report in a super clear way. It would have saved us time if we had seen it a few hours earlier!
