### ISSUE TITLE
Simple MNIST convnet example

### ISSUE THREAD

**Issue by rustrust** [google/jax#7534]
I am new to JAX. Can I trouble the JAX community to post an official MNIST convnet example? My machine isn't powerful enough to run the resnet50 example in a reasonable amount of time.

**Comment by jakevdp** [comment]
Here's one example that may be helpful: https://colab.research.google.com/github/google/flax/blob/main/examples/mnist/mnist.ipynb

It uses flax, which is one of the higher-level neural network libraries built on JAX.

**Comment by rustrust** [comment]
OK there is a working convnet example. 

For others who come across this, this example works well:
https://github.com/google/flax/tree/main/examples/mnist

Don't forget to install cuDNN!

**Comment by mattjj** [comment]
In general, [the higher-level library repos](https://github.com/google/jax#neural-network-libraries) are indeed the best place to find these examples.
