### ISSUE TITLE
NoneType coming from gradient function when using transformed parameters

### ISSUE THREAD

**Issue by peterroelants** [google/jax#7546]
I have been trying to create constrained parameters, for example a scale parameter that is strictly positive, to be used for example by a normal distribution. Inspired slightly by [`tfp.util.TransformedVariable`](https://www.tensorflow.org/probability/api_docs/python/tfp/util/TransformedVariable).

I have been trying to use `PyTrees`(https://jax.readthedocs.io/en/latest/pytrees.html#extending-pytrees) to create parameter classes that store some unconstrained representation, and return the constraint parameter upon access (see the example below). To create the parameter object, I want to pass in the desired constrained value, transform it to an unconstrained representation and store the latter. However, for some reason, this inverse conversion, from constrained to unconstrained is causing issues.
I hope the example below will provide more clarity on the issue:

```python
import numpy as np
import jax
import jax.numpy as jnp

from jax.tree_util import register_pytree_node_class


def softplus_inv(x):
    """Inverse to softplus"""
    return jnp.log(jnp.exp(x) - 1.)


@register_pytree_node_class
class NormParams:
    """
    Represent parameters of a normal distribution. Ensures scale is strictly positive.
    """
    def __init__(self, loc, scale):
        self.loc = loc
        self._scale = float(softplus_inv(scale))  # ! Seems to be the origin of the issue !
#         self._scale = softplus_inv(scale)  # ! Same issue !
        
    @property
    def scale(self):
        """Make sure `scale` parameter is positive."""
        return jax.nn.softplus(self._scale)
    
    def __repr__(self):
        return "NormParams(loc={}, scale={})".format(self.loc, self.scale)
    
    def tree_flatten(self):
        children = (self.loc, self.scale)
        aux_data = None
        return (children, aux_data)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(*children)
    

# Define parameters and inputs for testing
params_test = NormParams(
    loc=1.,
    scale=1.,
)
print(f"params_test: {params_test!r}")
x_test = np.random.randn(9)



def loss(params: NormParams, x):
    """Negative log-likelihood for the normal distribution."""
    return -jax.scipy.stats.norm.logpdf(x, loc=params.loc, scale=params.scale).sum()


print("loss: ", loss(params_test, x_test))


# Get the grad function of the loss wrt the parameters
grad_fun = jax.grad(loss, argnums=0)
g = grad_fun(params_test, x_test)  # ! FAILS HERE !
print("g: ", g)
```
Results in the following output:
```
params_test: NormParams(loc=1.0, scale=1.0)
loss:  17.600132
````
And traceback:
```python-traceback
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_260926/2260296730.py in <module>
     59 # Get the grad function of the loss wrt the parameters
     60 grad_fun = jax.grad(loss, argnums=0)
---> 61 g = grad_fun(params_test, x_test)  # ! FAILS HERE !
     62 print("g: ", g)

    [... skipping hidden 5 frame]

/tmp/ipykernel_260926/2260296730.py in tree_unflatten(cls, aux_data, children)
     36     @classmethod
     37     def tree_unflatten(cls, aux_data, children):
---> 38         return cls(*children)
     39 
     40 

/tmp/ipykernel_260926/2260296730.py in __init__(self, loc, scale)
     18     def __init__(self, loc, scale):
     19         self.loc = loc
---> 20         self._scale = float(softplus_inv(scale))  # ! Seems to be the origin of the issue !
     21 #         self._scale = softplus_inv(scale)  # ! Same issue !
     22 

/tmp/ipykernel_260926/2260296730.py in softplus_inv(x)
      8 def softplus_inv(x):
      9     """Inverse to softplus"""
---> 10     return jnp.log(jnp.exp(x) - 1.)
     11 
     12 

~/miniconda3/envs/gp_exp/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py in <lambda>(x)
    406 def _one_to_one_unop(numpy_fn, lax_fn, promote_to_inexact=False, lax_doc=False):
    407   if promote_to_inexact:
--> 408     fn = lambda x: lax_fn(*_promote_args_inexact(numpy_fn.__name__, x))
    409   else:
    410     fn = lambda x: lax_fn(*_promote_args(numpy_fn.__name__, x))

~/miniconda3/envs/gp_exp/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py in _promote_args_inexact(fun_name, *args)
    330 
    331   Promotes non-inexact types to an inexact type."""
--> 332   _check_arraylike(fun_name, *args)
    333   _check_no_float0s(fun_name, *args)
    334   return _promote_shapes(fun_name, *_promote_dtypes_inexact(*args))

~/miniconda3/envs/gp_exp/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py in _check_arraylike(fun_name, *args)
    306                     if not _arraylike(arg))
    307     msg = "{} requires ndarray or scalar arguments, got {} at position {}."
--> 308     raise TypeError(msg.format(fun_name, type(arg), pos))
    309 
    310 def _check_no_float0s(fun_name, *args):

TypeError: exp requires ndarray or scalar arguments, got <class 'NoneType'> at position 0.
```

For some reason, that I cannot explain, `grad_fun` is passing a `None` object to create a new `NormParams` object. And I'm not sure where this `None` object is coming from. Note that the `None` is passed in the `grad_fun` to `tree_unflatten` to create a new `NormParams`. At first I thought that because of the inverse transformation (`softplus_inv`) the variable being set is some lazy operation which ends up not being evaluated properly. However, forcing the `float` results in the same issue.

I'm not sure if I'm missing something, if I'm doing something wrong, or if this is a genuine bug. In any case, there might be an opportunity to improve error messages.

Versions used:
```
jax   : 0.2.18
jaxlib: 0.1.69
numpy : 1.21.1
```

**Comment by mkunesch** [comment]
Hey!

I think the problem is that when checking the datatype of the input `value_and_grad` also unflattens the PyTree with None values (returned from `_check_input_dtype_grad`) even though the output isn't used. For your custom PyTree this isn't possible.

It might not be hard to fix - I filed a small PR which should solve it - but I don't know whether jax is meant to support custom PyTrees that restrict their elements.

In the meantime, I think your code should work if you modify your custom node to be able to deal with `None` values in any way (e.g. by not applying softplus_inv if scale is `None`). Since the tree returned from the data type check in `value_and_grad` isn't used this shouldn't affect the gradients you get.

**Comment by peterroelants** [comment]
Hi @mkunesch, thank you for having a look, and for filing that PR. 

It's indeed weird that `None` is returned, which implies that all PyTree leafs could be optional. Ideally, Jax should keep the implicit typing of the PyTrees leaves intact by returning an object of the same type, and not `None`.

I think another case where returning this `None` could be an issue, is when the custom PyTree objects implement some sort of variable checking, similar to [pydantic](https://pydantic-docs.helpmanual.io/) validators or [attrs validators](https://www.attrs.org/en/stable/init.html?highlight=validation#validators).

**Comment by peterroelants** [comment]
I just realized some unrelated potential issue with the code above. I noticed that the gradient will also be wrapped in the same object. Which means that this gradient will also undergo the transformation in `__init__` and `tree_flatten`, to wrap/unwrap it in the same object. 
I think this might have some undesired effects depending on how the gradient is applied

**Comment by mkunesch** [comment]
Yes, whatever logic you have in the custom node would also be applied to the grads - in general I think the PyTree should just give the structure and should work for arbitrary elements. Even if the PR is merged it would probably be better not to have the logic in a custom node.

**Comment by jakevdp** [comment]
FYI, you'll likely run into other issues using this kind of structure with JAX; for example because of your conversion to a python float, it will fail with JIT:
```python
from jax import jit
jit(NormParams)(1., 1.)
```
```pytb
ConcretizationTypeError                   Traceback (most recent call last)
<ipython-input-2-b280c19cb27c> in __init__(self, loc, scale)
     18     def __init__(self, loc, scale):
     19         self.loc = loc
---> 20         self._scale = float(softplus_inv(scale))  # ! Seems to be the origin of the issue !
     21 #         self._scale = softplus_inv(scale)  # ! Same issue !
     22 

ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(float32[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `float` function. If trying to convert the data type of a value, try using `x.astype(float)` or `jnp.array(x, float)` instead.
While tracing the function <unknown> for jit, this concrete value was not available in Python because it depends on the value of the argument 'scale'.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```
Even with that fixed, there are other situations (e.g. `vmap`) where the pytree will also be instantiated with null values. The best course would be to try to make your pytree implementation more flexible in what arguments it accepts.

**Comment by peterroelants** [comment]
I see, thanks for that feedback. Similar, the gradient issue mentioned above made me realize that it would be better to return the untransformed variable while flattening, and only use the `__new__` constructor and not the `__init__` initialization when unwrapping. 

For example see:
```python
import numpy as np
import jax
import jax.numpy as jnp

from jax.tree_util import register_pytree_node_class


def softplus_inv(x):
    """Inverse to softplus"""
    return jnp.log(jnp.exp(x) - 1.)


@register_pytree_node_class
class NormParams:
    """
    Represent parameters of a normal distribution. Ensures scale is strictly positive.
    """
    def __init__(self, loc: float, scale: float):
        self.loc = loc
        self._scale_transformed = softplus_inv(scale)

    @property
    def scale(self):
        """Make sure `scale` parameter is positive."""
        return jax.nn.softplus(self._scale_transformed)
    
    def __repr__(self):
        return "NormParams(loc={}, scale={})".format(self.loc, self.scale)
    
    def tree_flatten(self):
        children = (self.loc, self._scale_transformed)
        aux_data = None
        return (children, aux_data)

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        obj = object.__new__(cls)
        obj.loc = children[0]
        obj._scale_transformed = children[1]
        return obj
    

# Test jit
jax.jit(NormParams)(1., 1.)  # Works


# Define parameters and inputs for testing
params_test = NormParams(
    loc=1.,
    scale=1.,
)
print(f"params_test: {params_test!r}")
x_test = np.random.randn(9)


def loss(params: NormParams, x):
    """Negative log-likelihood for the normal distribution."""
    return -jax.scipy.stats.norm.logpdf(x, loc=params.loc, scale=params.scale).sum()


print("loss: ", loss(params_test, x_test))


# Get the jitted grad function of the loss wrt the parameters
grad_fun = jax.jit(jax.grad(loss, argnums=0))
g = grad_fun(params_test, x_test)  # Works
print("g: ", g)
```

**Comment by peterroelants** [comment]
@mkunesch Thank you for the quick fix of the `None` problem. I'll be closing this issue.
