### ISSUE TITLE
Make samplers in jax.random use float64 as default when jax_enable_x64=True

### ISSUE THREAD

**Issue by neerajprad** [google/jax#756]
Currently, the behavior of samplers in `jax.random` is somewhat inconsistent as compared to other array constructors when `jax_enable_x64=True` because it still uses `np.float32` as the default, unless the dtype argument is explicitly also set to `np.float64`. 

The following code demonstrates the issue:

```python
In [1]: from jax.config import config

In [2]: import jax.numpy as np

In [3]: from jax import random

In [4]: config.update('jax_enable_x64', True)

In [5]: np.array([1.]).dtype
/Users/npradhan/miniconda3/envs/numpyro/lib/python3.6/site-packages/jax/lib/xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Out[5]: dtype('float64')

In [6]: np.ones(1).dtype
Out[6]: dtype('float64')

In [7]: random.normal(random.PRNGKey(0), (1,)).dtype
Out[7]: dtype('float32')  # Expected: float64 (default as in other constructors)
```

This will be really useful to just change one line in the code and run all the computations in float64, instead of having to temporarily insert `dtype`s in calls to all the samplers. This should be a small change, and we are happy to put out a PR with the fix, but I was not sure if there are other design considerations involved. cc. @fehiepsi 

Related: #470.

**Comment by mattjj** [comment]
That seems like a good idea to me!

I couldn't think of any design reasons not to do it, but to double-check I made the change in #761 to try it out. Would one of you, @neerajprad or @fehiepsi, mind reviewing it for correctness?

**Comment by mattjj** [comment]
More broadly, you guys are really driving a lot of this stuff forward, both on the NumPyro side and on the jax.random side, so if you have any more design recommendations like this one, we'd love to hear them! We'll do what we can to adapt JAX to work better for you, especially since this is making it better for all users.

**Comment by neerajprad** [comment]
Thanks @mattjj for the fix! This will really help simplify the code at our end.
