### ISSUE TITLE
Re-implement `named_call` to not use a `call_primitive`

### ISSUE THREAD

**Issue by LenaMartens** [google/jax#7602]
Not sure yet how this would be implemented, but we want to refactor `named_call` to be scope based/track the name_stack through some global machinery. Currently it uses a `call_primitive`, which works similarly to eg. `jit`, but with the only effect of adding a string to XLA metadata when lowered.

Advantages of this new `named_call` implementation:
  - can be used as a context-manager (ie. you don't need to refactor code into functions to use it)
  - does not need to adhere to the JAX call API contract: does not raise abstraction level, does not add a transformation boundary across which you can leak tracers and function arguments can be non-JAX types
  - does not increase compilation time (currently the extra `call`s need to be inlined by XLA)
  - [maybe] other libraries can access this stack to include in their debugging meta-data as well (not sure if this should be supported)
  - the name_stack does not need to be plumbed through the JAX internals as a function argument (eg. in `jaxpr_subcomp`)

Happy to discuss how this would be implemented/if this is a good idea (it seems like a good idea to me :))

**Comment by mattjj** [comment]
I'm going to self-assign this because it touches a lot of internals, though I may try to work with someone on it...

**Comment by LenaMartens** [comment]
This was implemented in https://github.com/google/jax/pull/8395, and turned on by default in https://github.com/google/jax/pull/10941, thanks @sharadmv!
