### ISSUE TITLE
Enable exporting jax graphs to onnx format

### ISSUE THREAD

**Issue by dataplayer12** [google/jax#7629]
I would like to be able to export jax graphs to onnx format for inference. Please note that for many practitioners a new framework is no go unless the results of training can be exported in a standard format for fine tuning/inference. Would the developers be open to this idea? I could also contribute if someone can guide me on where to get started.

**Comment by tomhennigan** [comment]
This is possible by first converting JAX->TF and then converting to ONNX. Here is an example: https://colab.research.google.com/gist/tomhennigan/8075058b6e36e2573610dcff6efaa14d/example-of-jax-tf-onnx.ipynb

Depending on your setup, you may want to export from TF differently (e.g. convert model parameters to tf.Variables such that they are stored in the "external tensor storage" dict).  This should be possible using jax2tf. Here is a short guide where we define a model in JAX, train it in TF and then save the result with saved model. https://dm-haiku.readthedocs.io/en/latest/notebooks/jax2tf.html

**Comment by dataplayer12** [comment]
Thanks for the prompt response. This solves the issue for now. If I face problems in exporting more complex graphs than the examples provide, I might reopen the issue.

**Comment by kartikpodugu** [comment]
can i convert dalle-mini model using this process ?
https://github.com/borisdayma/dalle-mini
