### ISSUE TITLE
How to use `lax.scan()` with `xs` as a tuple?

### ISSUE THREAD

**Issue by DylanMuir** [google/jax#763]
Hi,

The [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.lax.scan.html) for `lax.scan()` suggests that `xs` "can be an array or any pytree (nested Python tuple/list/dict) thereof with consistent leading axis sizes." Does this imply that I can provide multiple arrays for `scan()` to operate over, by calling with something like:

```
lax.scan(f, init, (xs, ys))
```

When I try this, I get a TypeError: 'JaxTuple' object does not support indexing.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-09d2a81e4d1d> in <module>
----> 1 lyr_force(input_t, target_t, bias, tau, np.zeros(20))

~/Development/Projects/LearningToLearn_GIT/fullforce.py in lyr_force(input_t, force_t, bias, tau, x0, H, dt)
     96         return x, H(x, bias)
     97 
---> 98     _, res_output_t = scan(net_step, x0, (input_t, force_t))
     99     return res_output_t
    100 

~/Development/jax/jax/lax/lax_control_flow.py in scan(f, init, xs)
    555   out_aval = core.AbstractTuple((carry_aval, y_aval))
    556   jaxpr = core.TypedJaxpr(lifted_jaxpr, (), in_avals, out_aval)
--> 557   length = _leading_dim_size(xs)
    558   out = scan_p.bind(core.pack(consts), init, xs,
    559                     forward=True, length=length, jaxpr=jaxpr)

~/Development/jax/jax/lax/lax_control_flow.py in _leading_dim_size(xs)
    456 def _leading_dim_size(xs):
    457   if isinstance(xs, core.JaxTuple):
--> 458     return _leading_dim_size(xs[0])
    459   else:
    460     return xs.shape[0]

TypeError: 'JaxTuple' object does not support indexing
```

Could you please point me to an example of using `lax.scan()` over multiple arrays simultaneously?

**Comment by mattjj** [comment]
Thanks for raising this!

You're using it as intended, but there was a bug that led to this behavior. It was just recently squashed.

What's your `jax.version.__version__`? It should be fixed on jax 0.1.34 and later, and also fixed on the master branch.

**Comment by mattjj** [comment]
(I just bumped the version on pypi to 0.1.35 because there were some other scan bugs we squashed yesterday.)

**Comment by DylanMuir** [comment]
This was on 0.1.31. Thanks for the bug fix!
