### ISSUE TITLE
bazel shutdown call ignores arguments

### ISSUE THREAD

**Issue by Flamefire** [google/jax#7639]
The line at https://github.com/google/jax/blob/4e6aef581b90db1c1ab292a1e7f17eb97e2377ab/build/build.py#L518 should be changed to `shell([bazel_path] + args.bazel_startup_options + ["shutdown"])` so that options like `--output_user_root` are honored.

**Comment by yashk2810** [comment]
Sounds good to me. Can you include an output showing if this works?

Also, if you want, you can send a PR :)

**Comment by Flamefire** [comment]
Using it already with success: https://github.com/easybuilders/easybuild-easyconfigs/pull/13758/files#diff-bc1d17061c7afd8013084f11171332424020c3af87c19be5ba4bee3a909cd475

I have a read-only .bazel folder in my HOME to avoid bazel writing stuff there which is how I noticed
