### ISSUE TITLE
Performance issue on GPU: dot product of two complex128 vectors

### ISSUE THREAD

**Issue by FlorianH-1QBit** [google/jax#7640]
Good morning, and thanks for your awesome work on JAX!

I've run into a performance issue using GPU, when contracting two complex128 vectors. It's almost 1000x slower than contracting two float64 vectors of the same size.

Here is benchmarking code, adapted from https://github.com/google/jax/issues/3068 (I don't think this issue here is the same as the one reported there):

```
import numpy as np
import jax
import jaxlib
from jax import config

config.update('jax_enable_x64', True)
import time


@jax.jit
def do_dot_simple(v1, v2):
    res = 0
    for _ in range(100):
        res += v1 @ v2
    return res


def run_timings_matmul_simple(dtype, D):
    v1 = jax.numpy.array(np.random.rand(D).astype(dtype))
    v2 = jax.numpy.array(np.random.rand(D).astype(dtype))
    ts = []

    for _ in range(100):
        t1 = time.time()
        res = jax.numpy.matmul(v1, v2)
        res.block_until_ready()
        ts.append(time.time() - t1)

    print(f'loop over 100 vector-vector dots in dtype {np.dtype(dtype).name}', np.median(ts) * 100)

    res = do_dot_simple(v1, v2)
    res.block_until_ready()
    t1 = time.time()
    res = do_dot_simple(v1, v2)
    res.block_until_ready()
    print(f'do_dot_simple (100 times v1@v2, jitted) for dtype {np.dtype(dtype).name}', time.time() - t1)


print(f'{jax.__version__=}, {jaxlib.__version__=}')
print('########  timings for v1@v2  ###########')
print('      ----------   float   --------------')
run_timings_matmul_simple(np.float64, int(1e6))
print('      ----------   complex   --------------')
run_timings_matmul_simple(np.complex128, int(1e6))

```

Here is the result, on a GCP instance with an A100 GPU:
```
jax.__version__='0.2.19', jaxlib.__version__='0.1.70'
########  timings for v1@v2  ###########
      ----------   float   --------------
loop over 100 vector-vector dots in dtype float64 0.01938343048095703
do_dot_simple (100 times v1@v2, jitted) for dtype float64 0.00012922286987304688
      ----------   complex   --------------
loop over 100 vector-vector dots in dtype complex128 11.447298526763916
do_dot_simple (100 times v1@v2, jitted) for dtype complex128 0.11420249938964844

```

I'd expect that the timings for complex128 are at most 4x slower than those for float64, but they are almost 3 orders of magnitude slower.
Timings are as expected for complex64, and on CPU, and for square matrix-matrix multiplication.
As a work-around, I'm currently splitting my vectors into real and imaginary parts to reduce the complex contraction to a sum of four real contractions.

Thanks for looking into this! 
Florian

**Comment by jakevdp** [comment]
Thanks for the report!

I looked into it, and it looks like this issue has just recently been fixed in XLA:GPU; see https://github.com/tensorflow/tensorflow/commit/bad34ad29f8b5e04c1feca4777a504c280a651d2

This change should make it into the next jaxlib release, at which point this slowdown should be rectified.
