### ISSUE TITLE
Latest Refactor to use `absl::StatusOr` breaks Windows build.

### ISSUE THREAD

**Issue by cloudhan** [google/jax#7641]
Using absl in cuda cpp is causing new type of compiling error.

```
external/com_google_absl\absl/types/internal/variant.h(1042): error: parameter pack "H" was referenced but not expanded
          detected during instantiation of class "absl::lts_20210324::variant_internal::VariantStateBase<H, T...> [with H=T..., T=<>]"
(1281): here

1 error detected in the compilation of "jaxlib/cuda_lu_pivot_kernels.cu.cc".
```

See the logs for more details:
[log1.txt](https://github.com/google/jax/files/6999476/log1.txt)
[log2.txt](https://github.com/google/jax/files/6999477/log2.txt)

Ultimately, it is similar to https://github.com/tensorflow/tensorflow/commit/36314ba572f743e6bda359c345977583a9b46be8

**Comment by cloudhan** [comment]
[Related actions](https://github.com/cloudhan/jax-windows-builder/actions/runs/1135880864)

**Comment by cloudhan** [comment]
@zhangqiaorjc Could you please take a look.

**Comment by zhangqiaorjc** [comment]
I want to check with @hawkinsp (when he's back from vacation) on what's our policy for absl dependencies.

I wonder if there's a Windows-toolchain-compatible and open sourced Status that we can use instead of absl::Status. It might be xla::Status?

**Comment by cloudhan** [comment]
I double checked it, seems only statusor.h will introduce varient.h, so the fix will be pretty easy

**Comment by cloudhan** [comment]
OK, it is not that easy to rule out `statusor.h`

**Comment by cloudhan** [comment]
@zhangqiaorjc Is it possible to use [xla's StatusOr](https://github.com/tensorflow/tensorflow/blob/0af45c032607555bfaa60f68f8661db578cab155/tensorflow/compiler/xla/statusor.h)?

It is used in [non_max_suppression_op.cu.cc](https://github.com/tensorflow/tensorflow/blob/0af45c032607555bfaa60f68f8661db578cab155/tensorflow/core/kernels/image/non_max_suppression_op.cu.cc)

**Comment by zhangqiaorjc** [comment]
@yashk2810 is working with another coworker on replacing absl::Status in this file

**Comment by yashk2810** [comment]
We just rolled out a fix here: https://github.com/google/jax/pull/7674. Can you try again from HEAD? 

I don't think the error should happen again.

> Is it possible to use xla's StatusOr?

No, the binary size increases by >100 MB when we pull in TF's deps for this.

The recent refactor of moving absl out of .cu.cc files should work for every compiler. Its working or gcc now so msvc should also work I hope.

**Comment by cloudhan** [comment]
Fixed in latest, can be verified with [this github actions](https://github.com/cloudhan/jax-windows-builder/actions/runs/1157155121)
