### ISSUE TITLE
jax.scipy.stats.beta.pdf handles x=0, x=1 incorrectly

### ISSUE THREAD

**Issue by terhorst** [google/jax#7645]
```
a = b = 1.
x = np.array([0., 1.])
scipy.stats.beta.pdf(x, a, b)
# array([1., 1.])
jax.scipy.stats.beta.pdf(x, a, b)
# DeviceArray([nan, nan], dtype=float32) 
```

Same issue and resolution as #7256 basically--use xlogy/xlog1py here:
https://github.com/google/jax/blob/f6f1debf700b55ad8c0ecc1daa0ed1f677c2bf00/jax/_src/scipy/stats/beta.py#L30-L31

**Comment by jakevdp** [comment]
Thanks for the report!

**Comment by terhorst** [comment]
Thanks for the quick fix
