### ISSUE TITLE
Standalone pytrees

### ISSUE THREAD

**Issue by tvogels** [google/jax#7707]
I think pytrees are among the neatest parts of jax's API, and they are useful in many non-jax projects, too. While you can already use `jax.tree_utils` for structures of, for example, pytorch tensors, it would be nicer to avoid jax as a dependency in a pytorch project. I think it would be great if pytrees were a separate project/module form jax.

Part of the motivation for this request is that I saw that pytorch internally started [following the same design](https://github.com/pytorch/pytorch/blob/master/torch/utils/_pytree.py), and that seems a bit silly.

**Comment by cgarciae** [comment]
Checkout [dm-tree](https://pypi.org/project/dm-tree) from Deep Mind.

**Comment by tvogels** [comment]
Ah, thanks for the pointer! That sounds like what I was looking for.

**Comment by PhilipVinc** [comment]
Still, it would be amazing if the community collaborated and both pytorch AND jax used the same tree package.
Then downstream packages could define only once packing/unpacking routines for pytrees and get compatibility with both packages...

**Comment by tvogels** [comment]
@PhilipVinc, I agree, even if this initially requires (trivially) wrapping the common tree package for compatibility.
