### ISSUE TITLE
Precompile jitted function

### ISSUE THREAD

**Issue by terhorst** [google/jax#7804]
Is it possible to pre-compile a jitted function _before_ the first invocation? Obviously it must happen at some point internally, but it might be useful to expose this as an API. I have two cases in mind:

1. For those of us who distribute software based on JAX, it would be helpful to inform the user that the program is currently unresponsive because it is compiling.
2. For anyone who develops on JAX, it is occasionally useful to understand how much time is being taken up by compilation vs. execution. Also, rarely, it happens you ran something non-terminating due to e.g. a misuse of `while_loop()`. In large programs where a lengthy compile time is expected, it can take several minutes to figure out what's going on.

Item 2 can more or less be accomplished using `block_until_ready()` as outlined in the benchmarking guide, but it requires two function executions. A cleaner option could be something like:

```{python}
@jit 
def f(x):
  ...

print("Compiling")
f.compile()
print("Done compiling")
```

If this is inadvisable for some reason, a fallback option could be to emit a log entry at the _end_ of each compilation (in addition to the start.)

**Comment by jakevdp** [comment]
No, this is not currently possible, but is in the works (see https://github.com/google/jax/issues/7733)

**Comment by terhorst** [comment]
Ah thanks, missed that.
