### ISSUE TITLE
`repr` error on empty BCOO sparse matrix

### ISSUE THREAD

**Issue by GeoffNN** [google/jax#7810]
I tried to initialize an empty BCOO matrix by:
```
from jax.experimental import sparse as jsparse
import jax.numpy as jnp

M = jsparse.BCOO((jnp.array([]), jnp.array([])), shape=(100, 100))
```

Just using the repr on `M` gives the following error: `<repr(<jax.experimental.sparse.ops.BCOO at 0x7f15fb4c9590>) failed: IndexError: tuple index out of range>`, which is unexpected.

On the other hand, initializing `M` with

```M = jsparse.BCOO((jnp.zeros(0, dtype='float32'), jnp.zeros((0, 2), dtype='int32')), shape=(100, 100)) ```

gives the correct repr output
```
M
BCOO(float32[100, 100], nse=0)
```

**Comment by jakevdp** [comment]
Thanks for the report!

I think we need some input validation on `__init__` – this is a bit difficult, though, because jax transforms sometimes instantiate pytrees with placeholder objects... so we'd have to somehow skip the validation in those cases.

**Comment by GeoffNN** [comment]
I've also noted the following strange behavior:

```
>>> q = jsparse.BCOO.fromdense(jnp.zeros(100, dtype=jnp.float32))
>>> q.data, q.indices
(DeviceArray([], dtype=float32), DeviceArray([], dtype=int32))

>>> jsparse.BCOO((jnp.array([], dtype=jnp.float32), jnp.array([], dtype=jnp.int32)), shape=(100,))
<repr(<jax.experimental.sparse.ops.BCOO at 0x7f4337d49950>) failed: IndexError: tuple index out of range>
```

while 
```
>>> jsparse.BCOO((q.data, q.indices), shape=(100,))
BCOO(float32[100], nse=0)
```

**Comment by jakevdp** [comment]
As above, this is because the indices do not have the expected shape, which is [nse, 1] for a one-dimensional sparse array.

**Comment by jakevdp** [comment]
Yeah, `indices` need to be of shape `[nse, n_sparse]`. You can see this is the case, despite the empty array repr not being clear on this:
```python
import jax.experimental.sparse as jsparse
import jax.numpy as jnp

q = jsparse.BCOO.fromdense(jnp.zeros(100, dtype=jnp.float32))
q.indices.shape
# [0, 1]
```

**Comment by jakevdp** [comment]
And yes, I think that instantiating `BCOO` with an incorrectly-shaped index should result in an immediate error. But as mentioned above this is difficult because of how JAX transforms use placeholders within pytrees.
