### ISSUE TITLE
Keyword arguments to jnp.ndarray.clip() do not follow the documentation

### ISSUE THREAD

**Issue by khdlr** [google/jax#7823]
The following should work according to the docs (https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.html), and it does work when using `numpy` instead of `jax.numpy`:

```python
import jax.numpy as jnp
jnp.zeros(3).clip(min=1)
```

However, in contrast to the docs, `jnp.ndarray.clip` actually expects the arguments to be called `a_min` and `a_max` respectively, just like `jnp.clip` does – i.e. `jnp.zeros(3).clip(a_min=1)` works.

**Comment by jakevdp** [comment]
Thanks for the report – currently the DeviceArray `clip` method delegates directly to `jnp.clip`: https://github.com/google/jax/blob/0dee3550250cf8e0afe8f1c0d24399844648584f/jax/_src/numpy/lax_numpy.py#L6332-L6333

It looks like that has to be changed, given the different API between the function and the method. Are you interested in sending a PR?

**Comment by khdlr** [comment]
Yes, I'm happy to submit a PR, guess this is a good "first issue" to start contributing :)
