### ISSUE TITLE
Implement `mirror` and `reflect` modes for jax.scipy.ndimage.map_coordinates

### ISSUE THREAD

**Issue by khdlr** [google/jax#7837]
Title pretty much says it all, it would be great to have the `mirror` and `reflect` modes for `scipy.ndimage.map_coordinates`.

**Comment by froystig** [comment]
cc @shoyer and @hawkinsp

**Comment by khdlr** [comment]
I submitted a PR for this over at #7838

**Comment by froystig** [comment]
Thanks! I was going through our recent issues and had not seen that yet.
