### ISSUE TITLE
bfloat16 conv crashing on ampere

### ISSUE THREAD

**Issue by GallagherCommaJack** [google/jax#7866]
```python
import jax
import jax.numpy as jnp
key = jax.random.PRNGKey(42)

inp = jax.random.normal(key, shape=(5,3,16,16), dtype=jnp.bfloat16)
k = jax.random.normal(key, shape=(8,3,4,4), dtype=jnp.bfloat16)
print(jax.lax.conv(inp, k, (1,1), 'same').shape)
```

should produce the error:
```
F external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_dnn.cc:1011] Invalid DNN data type: 7
```

**Comment by hawkinsp** [comment]
What versions of CUDA, CuDNN, jax, and jaxlib do you have?

**Comment by GallagherCommaJack** [comment]
CUDA 11.4
CuDNN 8.2
jax: 0.2.20
jaxlib: 0.1.71

**Comment by GallagherCommaJack** [comment]
card i'm testing on is an rtx 3090

**Comment by hawkinsp** [comment]
I suspect this is because jaxlib is built against CuDNN 8.1. Things would probably work if you (or we) built a jaxlib from source against CuDNN 8.2.

**Comment by yashk2810** [comment]
Jaxlib for Cuda 11.1 is built against CuDNN 8.0.5 AFAIK

**Comment by hawkinsp** [comment]
There's still a bug here, because it shouldn't crash, but perhaps we should switch our releases to a newer CuDNN across the board.

**Comment by yashk2810** [comment]
When I tried to do that (Using a wheel built with Cuda 11.2 and running on Cuda 11.1), the tests started failing saying that Cudnn version does not work for Cuda 11.1 since its 8.1 and Cuda 11.1 expects 8.0.5.xx

**Comment by hawkinsp** [comment]
@yashk2810 NVidia claim CuDNN 8.2 is compatible with CUDA 11.1+: https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html#cudnn-versions-824

**Comment by sanjoy** [comment]
CC @cheshire

**Comment by hawkinsp** [comment]
I think this should be fixed by the updated wheels that @yashk2810 linked to. Please reopen the issue if you are still having problems!
