### ISSUE TITLE
`jax2tf` is failing with `__call__() missing 1 required keyword-only argument: 'train'`

### ISSUE THREAD

**Issue by sayakpaul** [google/jax#7884]
Hi.

I am trying to convert a Vision Transformer model to TensorFlow and serialize it as a SavedModel following the guidelines from here: https://github.com/google/jax/blob/main/jax/experimental/jax2tf/examples/README.md.

I am able to generate all the artifacts needed to run the conversion but it seems like the `tf_graph` (out of which one would extract the concrete function) is not getting constructed properly. 

Short code snippet:

```python
predict_fn = lambda params, inputs: model.apply(dict(params=params), inputs)

tf_fn = jax2tf.convert(
    predict_fn,
    with_gradient=False,
    enable_xla=True)

param_vars = tf.nest.map_structure(
    lambda param: tf.Variable(param, trainable=False),
    params)
tf_graph = tf.function(lambda inputs: tf_fn(param_vars, inputs),
                        autograph=False,
                        jit_compile=True)
```

While running `signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY] = \
    tf_graph.get_concrete_function(input_signatures[0])` I get into:

```
/usr/local/lib/python3.7/dist-packages/flax/linen/module.py in wrapped_module_method(*args, **kwargs)
    269     _context.module_stack.append(self)
    270     try:
--> 271       y = fun(self, *args, **kwargs)
    272       if _context.capture_stack:
    273         filter_fn = _context.capture_stack[-1]

TypeError: __call__() missing 1 required keyword-only argument: 'train'
```

Here's the Colab Notebook for reproducing [this error](https://colab.research.google.com/gist/sayakpaul/def1050fc334f6cc8b139000586e54f3/scratchpad.ipynb).

**Comment by sayakpaul** [comment]
@gnecula if we update the TensorFlow version to `tf-nightly` (`2.7.0-dev20210911`) then the error goes away. 

Another question I wanted to ask. Is there any workaround to enable fine-tuning of the converted models? [This](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/examples/saved_model_lib.py#L108-L113) tells me it is NOT supported but I still wanted to know.

**Comment by gnecula** [comment]
I am glad you found that the `tf-nightly` fix. We only test with tf-nightly, but for reasons having to do with some details of how certain TF ops are working. I did not realize that the handling of `kwargs` may have changed in TF. 

It is possible to fine-tune the converted models, first-order reverse-mode AD works, and it is JAX-accurate. I will remove that comment, it is stale.

**Comment by sayakpaul** [comment]
Thank you very much for the clarification @gnecula! I am planning to open-source the entire work done for converting the JAX Vision Transformer models to TensorFlow SavedModel. Would you folks be open to give that a mention from the `jax2tf` README? Might be helpful for the community.

**Comment by gnecula** [comment]
I'd be happy to link in the README materials that the community would find helpful. Please point me to the material that you would like linked.

**Comment by sayakpaul** [comment]
> Would you folks be open to give that a mention from the jax2tf README? Might be helpful for the community.

@gnecula this is the material I was talking about: https://git.io/Jz8pj. It shows how to use the `jax2tf` tool correctly to convert Vision Transformer models to TensorFlow SavedModel and eventually load that in `hub.KerasLayer` for off-the-shelf inference and fine-tuning tasks. 

Let me know if you'd want to have more details. Happy to have them over to you.
