### ISSUE TITLE
"'GLIBCXX_3.4.26' not found" when installing Jax on GCP

### ISSUE THREAD

**Issue by Bihaqo** [google/jax#7896]
Reproducing:
* create a VM with V100 GPU on Google Cloud with "Deep Learning Image: Base m79 CUDA11.0" image;
* run
```bash
pip install --upgrade pip
pip install jaxlib
pip install --upgrade "jax[cuda111]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

And finally run `import jax` from Python.

```
`>>> import jax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.7/site-packages/jax/__init__.py", line 120, in <module>
    from . import nn
  File "/opt/conda/lib/python3.7/site-packages/jax/nn/__init__.py", line 21, in <module>
    from jax._src.nn.functions import (
  File "/opt/conda/lib/python3.7/site-packages/jax/_src/nn/functions.py", line 28, in <module>
    from jax.scipy.special import expit
  File "/opt/conda/lib/python3.7/site-packages/jax/scipy/__init__.py", line 18, in <module>
    from . import signal
  File "/opt/conda/lib/python3.7/site-packages/jax/scipy/signal.py", line 17, in <module>
    from jax._src.scipy.signal import (
  File "/opt/conda/lib/python3.7/site-packages/jax/_src/scipy/signal.py", line 15, in <module>
    import scipy.signal as osp_signal
  File "/opt/conda/lib/python3.7/site-packages/scipy/signal/__init__.py", line 294, in <module>
    from ._max_len_seq import max_len_seq
  File "/opt/conda/lib/python3.7/site-packages/scipy/signal/_max_len_seq.py", line 8, in <module>
    from ._max_len_seq_inner import _max_len_seq_inner
ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/lib/p
ython3.7/site-packages/scipy/signal/_max_len_seq_inner.cpython-37m-x86_64-linux-gnu.so)
```

I tried doing
```
sudo apt-get install gcc-4.9
sudo apt-get upgrade libstdc++6
```
as some suggested on the internet, but that didn't help.

**Comment by hawkinsp** [comment]
That error is coming from `scipy`, which JAX depends on, not JAX.  You need a working `scipy` installation. (e.g. `import scipy` needs to work).

**Comment by Bihaqo** [comment]
I see, thanks for spotting this!
Nevertheless, it's impossible to use Jax right now and I think it can be beneficial to mention this problem in the installation docs (e.g. say that you need to install older version of scipy because the latest one is buggy or something).

**Comment by hawkinsp** [comment]
FWIW, I think the issue is your scipy installation is broken in some way or incompatible with your VM image. I don't think that's something we can mention in our docs.

**Comment by Bihaqo** [comment]
If it's indeed the case, it would probably mean that it's broken for others as well. I created the VM 3 hours ago from the GCP default DeepLearning+GPU image and the only thing I did on that VM is following Jax installation instructions, here is the entire list of commands I executed:
```
pip install --upgrade pip
pip install jaxlib
pip install --upgrade "jax[cuda111]" -f https://storage.googleapis.com/jax-releases/jax_releases.html
``` 

My point is that at the moment there is no working and documented way of getting Jax working on GCP. (Maybe I should better report this internally as a GCP bug?)

**Comment by Bihaqo** [comment]
FYI: the problem went away when trying to repeat the exact same actions under a venv, i.e. after
```
python -m venv env
source env/bin/activate
```

**Comment by hawkinsp** [comment]
I ended up digging into this issue when it was reported by another user: https://github.com/google/jax/issues/9218#issuecomment-1016949739

It turns out to be an incompatibility between the two C++ standard libraries on the deep learning VM image you are using. But your workaround (use a venv) is a great solution to the problem.
