### ISSUE TITLE
Build from source instruction for window in doc has error in using pacman

### ISSUE THREAD

**Issue by nonconvexopt** [google/jax#7912]
As you can see in [additional-notes-for-building-jaxlib-from-source-on-windows](https://jax.readthedocs.io/en/latest/developer.html#additional-notes-for-building-jaxlib-from-source-on-windows) section in doc, 

`pacman -S patch realpath`

should be changed to 

`pacman -S patch coreutils`

Reference: [https://command-not-found.com/realpath](https://command-not-found.com/realpath)

**Comment by zhangqiaorjc** [comment]
Would you like to contribute a PR to fix the doc?

**Comment by nonconvexopt** [comment]
Sure, it is my pleasure.

I also found another error that in Windows:

In the example command to build JAX from source
`python .\build\build.py `
  --enable_cuda `
  --cuda_path='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1' `
  --cudnn_path='C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1' `
  --cuda_compute_capabilities='x.x' `
  --cuda_version='x.x' `
  --cudnn_version='x.x.x'`
'--cuda_compute_capabilities' raises an error and we should get rid of it.

**Comment by hawkinsp** [comment]
Thanks for the PR!
