### ISSUE TITLE
Boolean indexing inconsistent with numpy in the case of a scalar index 

### ISSUE THREAD

**Issue by ajwittmond** [google/jax#7918]
Scalar boolean applied to jax arrays behave differently than when applied to numpy arrays, as the following example demonstrates:
```
>>> import numpy as np
>>> import jax.numpy as jnp
>>> nx = np.array([[1,2],[3,4]])
>>> jx = jnp.array([[1,2],[3,4]])
>>> nx[True]
array([[[1, 2],
        [3, 4]]])
>>> jx[True]
DeviceArray([[1, 2]], dtype=int32)
>>> nx[True] = 1
>>> nx
array([[1, 1],
       [1, 1]])
>>> jx.at[True].set(1)
DeviceArray([[1, 1],
             [3, 4]], dtype=int32)
```
In particular, this is surprising since one might expect the last expression to have the same output as `jnp.where(True, jx, 1)` as `nx[True] = 1` results in `nx` being identical to `np.where(True, nx, 1)`.

**Comment by jakevdp** [comment]
Thanks for the report! I vaguely remember us looking into this before, but I can't find any discussion of it. Scalar boolean indices are kind of weird though....
```python
>>> np.arange(4)[True].shape                                                                                                
(1, 4)

>>> np.arange(4)[False].shape                                                                                               
(0, 4)

>>> np.arange(4)[:, True].shape                                                                                             
(4, 1)

>>> np.arange(4)[:, False].shape                                                                                            
(4, 0)

>>> np.arange(4)[None, :, True].shape                                                                                       
(1, 4, 1)
```
OK, so they act kind of like `np.newaxis`, with size 0 an 1. But wait:
```python
>>> np.arange(4)[None, :, None].shape                                                                                       
(1, 4, 1)

>>> np.arange(4)[True, :, True].shape                                                                                       
(1, 4)
```
it only seems to care about the first boolean scalar passed, and throws out the rest. But...
```python
>>> np.arange(4)[True, :, False].shape                                                                                      
(0, 4)
```
No, it doesn't throw out the last one, it does an `and` reduction across all scalar boolean indices, and puts them in the place of the first. But what if there are boolean masks also?
```
>>> x = jnp.arange(4)

>>> x[True, x < 3]
array([0, 1, 2])
```
huh, it ignores the boolean scalar. What if there's a False?
```python
>>> x[False, x < 3]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-33-0fcaa5b9b07e> in <module>
----> 1 x[False, x < 3]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (0,) (3,) 
```
I don't really understand what's going on here.

I cannot find this behavior documented anywhere in the numpy documentation, so I'm not sure how to implement the behavior in JAX.

I'm tempted to fix this for now by raising a `NotImplementedError` when a scalar boolean index is encountered – what do you think?

**Comment by jakevdp** [comment]
LOL I was searching for info on this and found my own StackOverflow answer https://stackoverflow.com/a/65598320

**Comment by jakevdp** [comment]
I'm more convinced now that `NotImplementedError` is the way to go here – it seems to be a poorly documented corner of the numpy API, and not worth spending too much energy trying to replicate.

**Comment by shoyer** [comment]
> I'm more convinced now that `NotImplementedError` is the way to go here – it seems to be a poorly-defined corner of the numpy API, and not worth spending too much energy trying to replicate.

:+1: I don't think we should support mixed boolean / integer indexing.

**Comment by ajwittmond** [comment]
`NotImplementedError` makes sense to me.  I also couldn't find any documentation to cite when raising this issue and the behavior you bring up with the multi dimensional indices seems pretty inconsistent.  I was surprised by this behavior myself when I discovered it.

**Comment by shoyer** [comment]
FWIW I think `TypeError` would probably be fine, too.
