### ISSUE TITLE
Unable to clear jit cache by dropping reference to the function returned by `jax.jit` - memory leak?

### ISSUE THREAD

**Issue by josephrocca** [google/jax#7930]
This issue might be related to #282, but my problem involves re-compilation due to a changed input shape rather than a large constant input shape. The following code leaks about 1mb per 100 iterations:
```python
def f(x):
    return np.mean(np.dot(x, x.T))

size = 1002
for i in range(1000):
    if i%100 == 0: print(f"\nROUND #{i}")
    
    size -= 1
    a = np.ones([size, size])
    
    jit_f = None
    time.sleep(0.01)
    xla._xla_callable.cache_clear()
    
    if i%100 == 0: print("MEM:", get_gpu_memory())
    jit_f = jit(f)
    out = jit_f(a)
    if i%100 == 0: print(out)
    if i%100 == 0: print("MEM:", get_gpu_memory())
```
https://colab.research.google.com/gist/josephrocca/b56f0cb99b8ac07f15bee467842788f2

But re-defining the function within the loop prevents the leak:
```python
size = 1002
for i in range(1000):
    if i%100 == 0: print(f"\nROUND #{i}")
    
    size -= 1
    a = np.ones([size, size])
    
    jit_f = None
    time.sleep(0.01)
    xla._xla_callable.cache_clear()
    
    if i%100 == 0: print("MEM:", get_gpu_memory())
    def f(x):
      return np.mean(np.dot(x, x.T))
    jit_f = jit(f)
    out = jit_f(a)
    if i%100 == 0: print(out)
    if i%100 == 0: print("MEM:", get_gpu_memory())
```
Is this expected behavior? [This comment](https://github.com/google/jax/issues/2072#issuecomment-578422773) by @mattjj suggests that it would be unexpected, since the cache should be cleared by just dropping the reference to `jit_f`?

I confirmed with a more "real-world" behavior (`jit`ing a large ML model) and I see the same behavior - leak goes away if `f` is redefined: https://colab.research.google.com/gist/josephrocca/d0ddd720fd4bf178337fe8d878a559d9

If this is in fact expected behavior, then this issue can be closed - though it does seem a bit strange to not have a way to clear the cache compiled function once there's no longer any reference to it. I wonder whether it'd be worth noting in the docs somewhere?

**Comment by fabiannagel** [comment]
@Edenhofer: Curious to hear what tool you used to create this memory profile?

**Comment by Edenhofer** [comment]
The tool is aptly named [memory_profiler](https://github.com/pythonprofilers/memory_profiler). It is orthogonal to JAX's memory profiler and can be used for arbitrary python code.

**Comment by fabiannagel** [comment]
Oh I see, so I suppose it's CPU-only. Thanks anyway!

**Comment by jakevdp** [comment]
Resolving this issue:

> The cache seems to be associated with the original function and not the jit-compiled one. Or in other words one explicitly has to drop the reference to the function to free up the memory.

This is precisely how the cache is intended to work: it uses weak references to the original function, so that if you jit-compile the function again, it uses the existing cache. For example:
```python
from jax import jit

def f(x):
  return x

f_jit = jit(f)

print(f_jit._cache_size())  # 0

f_jit(1)
print(f_jit._cache_size())  # 1

# Same type & shape -> cache hit
f_jit(2)
print(f_jit._cache_size())  # 1

# Different type or shape -> new compilation
f_jit(2.0)
print(f_jit._cache_size())  # 2

# Cache is associated with the original function,
# so that re-jitting a function accesses the same cache.
del f_jit
f_jit_2 = jit(f)
print(f_jit_2._cache_size())

# Deleting the original function and all references
# to it should result in the cache being cleared entirely.
del f, f_jit_2
```
