### ISSUE TITLE
FileSystemCache broken on recent Linux kernels - test_least_recently_accessed_file fails

### ISSUE THREAD

**Issue by Flamefire** [google/jax#7944]
We are source-compiling jaxlib 0.1.71 and jax 0.2.20 and running the tests with `pytest -n 1 tests` (higher numbers seems to fail occasionally)

And one of the more annoying tests is `test_least_recently_accessed_file` which fails with:

```
self = <file_system_cache_test.FileSystemCacheTest testMethod=test_least_recently_accessed_file>

    def test_least_recently_accessed_file(self):
      with tempfile.TemporaryDirectory() as tmpdir:
        cache = FileSystemCache(tmpdir, max_cache_size_bytes=6)
        cache.put("first", b"one")
        cache.put("second", b"two")
        # Sleep because otherwise these operations execute too fast and
        # the access time isn't captured properly.
        time.sleep(1)
        cache.get("first")
        cache.put("third", b"the")
>       self.assertEqual(cache.get("first"), b"one")
E       AssertionError: None != b'one'

tests/file_system_cache_test.py:116: AssertionError
```

~~Seeing the `sleep` in there: Is it still possible that the access time is wrong? I.e. IIRC the `sleep` could return early so access time is still the same and a (more or less) random entry is evicted.~~ See below: Access time is not updated on recent kernels

**Comment by Flamefire** [comment]
The implementation is fundamentally broken on recent Linux kernels which only update the access time once every 24 hours. See https://en.wikipedia.org/wiki/Stat_%28system_call%29#Criticism_of_atime and https://stackoverflow.com/a/16464296/1930508

So a cache based on the access time cannot work on most current systems.

**Comment by hawkinsp** [comment]
I think it'd be fine to send a PR disabling the test for now (just add a `@unittest.skip` decorator). Assigning @skye for thinking  about a more comprehensive fix.

**Comment by Flamefire** [comment]
How about using https://docs.python.org/3/library/os.html#os.utime on access?

**Comment by Flamefire** [comment]
Tested this with success:
```
diff --git a/jax/experimental/compilation_cache/file_system_cache.py b/jax/experimental/compilation_cache/file_system_cache.py
index b85969de..4c22d8e3 100644
--- a/jax/experimental/compilation_cache/file_system_cache.py
+++ b/jax/experimental/compilation_cache/file_system_cache.py
@@ -33,6 +33,7 @@ class FileSystemCache(CacheInterface):
     path_to_key = os.path.join(self._path, key)
     if os.path.exists(path_to_key):
       with open(path_to_key, "rb") as file:
+        os.utime(file.fileno())
         return file.read()
     else:
       return None

```

**Comment by mcwitt** [comment]
Can this be closed since https://github.com/google/jax/commit/498ee6007d345b05566aad9c854e4eb04fb60fbb is merged? (the latter removed `FileSystemCache`)

**Comment by Flamefire** [comment]
Well given that `max_cache_size` is not supported anymore and hence cache entries are not evicted anymore this issue does no longer apply.

Just a side note: Yes `FileSystemCache` was removed but a similar implementation is is in `GFileCache`. But due to the above the eviction wasn't also copied so that doesn't suffer from this issue.
