### ISSUE TITLE
`polymorphic_shapes` specification not succeeding with `jax2tf`

### ISSUE THREAD

**Issue by sayakpaul** [google/jax#7954]
@gnecula after following the instructions from ["Shape-polymorphic conversion"](https://github.com/google/jax/tree/main/jax/experimental/jax2tf#shape-polymorphic-conversion), I am unable to run a conversion. 

Here are more details. 

## Versions
   
   ```
   JAX version: 0.2.19
   FLAX version: 0.3.3
   TensorFlow version: 2.7.0-dev20210917
   ```

## Demo code

```python
predict_fn = lambda params, inputs: model.apply(
    dict(params=params), inputs, train=False
)

with_gradient = False if num_classes else True
tf_fn = jax2tf.convert(
    predict_fn, with_gradient=with_gradient, polymorphic_shapes=["(b, 224, 224, 3)"], enable_xla=True
)

trainable = False if num_classes else True
param_vars = tf.nest.map_structure(
    lambda param: tf.Variable(param, trainable=trainable), params
)
tf_graph = tf.function(
    lambda inputs: tf_fn(param_vars, inputs), autograph=False, jit_compile=True
)

signatures[
    tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY
] = tf_graph.get_concrete_function(input_signatures[0])

wrapper = _ReusableSavedModelWrapper(tf_graph, param_vars)
if with_gradient:
    if not saved_model_options:
        saved_model_options = tf.saved_model.SaveOptions(
            experimental_custom_gradients=True
        )
    else:
        saved_model_options.experimental_custom_gradients = True
tf.saved_model.save(
    wrapper, model_dir, signatures=signatures, options=saved_model_options
)
```

I have reused quite a bit of code from [here](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/examples/README.md).

## Short error message

```
TypeError: polymorphic_shapes must be a sequence with the same length as the positional argument list (2). Got polymorphic_shapes=['(b, 224, 224, 3)'].
```

## Colab Notebook to reproduce the issue

https://colab.research.google.com/gist/sayakpaul/74117456db67c8918825ed32c1acc913/conversion.ipynb

Am I missing out on anything?

**Comment by gnecula** [comment]
The problem is that the converted function is called with 2 positional arguments, but `polymorphic_shapes` is a list with only 1 element. It seems to me that you want the converted function to be polymorphic only on the first dimension of the `inputs` argument (this is very typical). You should pass `None` for the polymorphic specification of the `params` argument. E.g., you can use `polymorphic_shapes=[None, "b, 224, 224, 3"]` or even `[None, "b, ..."]`.

The docstring of the `jax2tf.convert` function explains how to construct the `polymorphic_shapes` values.

**Comment by sayakpaul** [comment]
Oh, I was referring to this particular snippet from the official examples:

![image](https://user-images.githubusercontent.com/22957388/133890159-77039e9c-e926-44bf-b3cf-d6215898bd08.png)

FYI, your suggestion worked perfectly fine. Thank you. However, it's unclear to me how `[None, "b, 224, 224, 3"]` gets expanded at least on a high level. Since the issue is resolved I am closing it.

**Comment by gnecula** [comment]
The example you screenshot is for a function with one positional argument. You function takes two arguments, and each argument needs its own specification. `None` is expanded to the shape of the actual argument (your `params`).

**Comment by sayakpaul** [comment]
Thanks much for the explanation.
