### ISSUE TITLE
Request scipy.special.hyp2f1 

### ISSUE THREAD

**Issue by sjiang23** [google/jax#7958]
Hi JAX team:

Thanks for your amazing product.  

I found I need to use Hypergeometric function (hyp), which does not exists in current JAX scipy. Direct using scipy.special.hyp2f1 causes jax.errors.TracerArrayConversionError, as I have a batched version of a function involving hyp. Could you add hyp into JAX scipy?

Best,
Senbao

**Comment by jakevdp** [comment]
Thanks for the request! There's an issue tracking this already with some relevant details: #2991

**Comment by hawkinsp** [comment]
Closing in favor of #2991.
