### ISSUE TITLE
Can not jit-compile piecewise linear function

### ISSUE THREAD

**Issue by idnm** [google/jax#7969]
Here is a code that does not work. 
```python
import jax

def f(x):
    return jax.numpy.piecewise(x, [x<0,0<x<1], [-x, x])

f_jit=jax.jit(f)

f(0.5) # 0.5
f_jit(0.5) # Error
```
Function `f` is working fine but throws an error when jit-compiled. If the second condition is replaced from $0<x<1$ to a single inequality like $0<x$ everything works. Is it intended behavior? How should one define a function on several intervals then?

Full traceback:

---------------------------------------------------------------------------
UnfilteredStackTrace                      Traceback (most recent call last)
<ipython-input-7-2c164e754b94> in <module>
      8 f(0.5)
----> 9 f_jit(0.5)

~/.local/lib/python3.8/site-packages/jax/_src/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    142     try:
--> 143       return fun(*args, **kwargs)
    144     except Exception as e:

~/.local/lib/python3.8/site-packages/jax/_src/api.py in cache_miss(*args, **kwargs)
    425     flat_fun, out_tree = flatten_fun(f, in_tree)
--> 426     out_flat = xla.xla_call(
    427         flat_fun,

~/.local/lib/python3.8/site-packages/jax/core.py in bind(self, fun, *args, **params)
   1564   def bind(self, fun, *args, **params):
-> 1565     return call_bind(self, fun, *args, **params)
   1566 

~/.local/lib/python3.8/site-packages/jax/core.py in call_bind(primitive, fun, *args, **params)
   1555   with maybe_new_sublevel(top_trace):
-> 1556     outs = primitive.process(top_trace, fun, tracers, params)
   1557   return map(full_lower, apply_todos(env_trace_todo(), outs))

~/.local/lib/python3.8/site-packages/jax/core.py in process(self, trace, fun, tracers, params)
   1567   def process(self, trace, fun, tracers, params):
-> 1568     return trace.process_call(self, fun, tracers, params)
   1569 

~/.local/lib/python3.8/site-packages/jax/core.py in process_call(self, primitive, f, tracers, params)
    608   def process_call(self, primitive, f, tracers, params):
--> 609     return primitive.impl(f, *tracers, **params)
    610   process_map = process_call

~/.local/lib/python3.8/site-packages/jax/interpreters/xla.py in _xla_call_impl(fun, device, backend, name, donated_invars, *args)
    577 def _xla_call_impl(fun: lu.WrappedFun, *args, device, backend, name, donated_invars):
--> 578   compiled_fun = _xla_callable(fun, device, backend, name, donated_invars,
    579                                *unsafe_map(arg_spec, args))

~/.local/lib/python3.8/site-packages/jax/linear_util.py in memoized_fun(fun, *args)
    261     else:
--> 262       ans = call(fun, *args)
    263       cache[key] = (ans, fun.stores)

~/.local/lib/python3.8/site-packages/jax/interpreters/xla.py in _xla_callable(fun, device, backend, name, donated_invars, *arg_specs)
    651   abstract_args, _ = unzip2(arg_specs)
--> 652   jaxpr, out_avals, consts = pe.trace_to_jaxpr_final(fun, abstract_args, transform_name="jit")
    653   if any(isinstance(c, core.Tracer) for c in consts):

~/.local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr_final(fun, in_avals, transform_name)
   1208     main.jaxpr_stack = ()  # type: ignore
-> 1209     jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
   1210     del fun, main

~/.local/lib/python3.8/site-packages/jax/interpreters/partial_eval.py in trace_to_subjaxpr_dynamic(fun, main, in_avals)
   1187     in_tracers = map(trace.new_arg, in_avals)
-> 1188     ans = fun.call_wrapped(*in_tracers)
   1189     out_tracers = map(trace.full_raise, ans)

~/.local/lib/python3.8/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    165     try:
--> 166       ans = self.f(*args, **dict(self.params, **kwargs))
    167     except:

<ipython-input-7-2c164e754b94> in f(x)
      3 def f(x):
----> 4     return jax.numpy.piecewise(x, [x<0,0<x<1], [-x, x])
      5 

~/.local/lib/python3.8/site-packages/jax/core.py in __bool__(self)
    537   def __nonzero__(self): return self.aval._nonzero(self)
--> 538   def __bool__(self): return self.aval._bool(self)
    539   def __int__(self): return self.aval._int(self)

~/.local/lib/python3.8/site-packages/jax/core.py in error(self, arg)
    959   def error(self, arg):
--> 960     raise ConcretizationTypeError(arg, fname_context)
    961   return error

UnfilteredStackTrace: jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function. 
While tracing the function f at <ipython-input-7-2c164e754b94>:3, transformed by jit., this concrete value was not available in Python because it depends on the value of the arguments to f at <ipython-input-7-2c164e754b94>:3, transformed by jit. at flattened positions [0], and the computation of these values is being staged out (that is, delayed rather than executed eagerly).
 (https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ConcretizationTypeError                   Traceback (most recent call last)
<ipython-input-7-2c164e754b94> in <module>
      7 
      8 f(0.5)
----> 9 f_jit(0.5)

<ipython-input-7-2c164e754b94> in f(x)
      2 
      3 def f(x):
----> 4     return jax.numpy.piecewise(x, [x<0,0<x<1], [-x, x])
      5 
      6 f_jit=jax.jit(f)

ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(bool[], weak_type=True)>with<DynamicJaxprTrace(level=0/1)>
The problem arose with the `bool` function. 
While tracing the function f at <ipython-input-7-2c164e754b94>:3, transformed by jit., this concrete value was not available in Python because it depends on the value of the arguments to f at <ipython-input-7-2c164e754b94>:3, transformed by jit. at flattened positions [0], and the computation of these values is being staged out (that is, delayed rather than executed eagerly).
 (https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError)

**Comment by jakevdp** [comment]
Thanks for the question – the issue is that comparison operator chaining (i.e. `0<x<1`) is not supported for JAX arrays, similar to the case for Numpy. Instead you should write `(0<x)&(x<1)`:
```python
import jax

def f(x):
    return jax.numpy.piecewise(x, [x<0,(0<x)&(x<1)], [-x, x])

f_jit=jax.jit(f)

f(0.5) # 0.5
f_jit(0.5) # DeviceArray(0.5, dtype=float32)
```

**Comment by hawkinsp** [comment]
@idnm I'd use Github Discussions (the Discussions tab above) instead of Github Issues for asking questions. It's a better format for questions and it's more appropriate when there isn't necessarily something for us to fix.
