### ISSUE TITLE
Unexpected error related to `jax.custom_jvp`  

### ISSUE THREAD

**Issue by tianjuxue** [google/jax#7972]
We are working with  `jax.custom_jvp` @denizokt and want to report the unexpected error with the following code that can reproduce the error.

```python
import jax.numpy as jnp
import jax

def identify_fn(x):
  return x

identify_fn = jax.custom_jvp(identify_fn)

@identify_fn.defjvp
def identify_fn_jvp(primals, tangents):
  aug_init_state = jnp.concatenate((*primals, *tangents))
  ys = aug_init_state[:3]
  ys_dot = aug_init_state[3:]
  return ys, ys_dot
  # Won't cause an error if we do the following instead
  # return (*primals, *tangents)

jac = jax.jacfwd(identify_fn)(jnp.array([5., 5., 5.]))
```

Error message: **ValueError: vmap has mapped output but out_axes is None**

Thanks!

**Comment by denizokt** [comment]
Some more information:

The above code works when replacing `jax.jacfwd` with `jax.jvp`.
Also works when replacing `return ys, ys_dot` with `return *primals, ys_dot`

It seems like when the primal computation depends on the tangents, we get a vmap error when computing full Jacobians.

**Comment by jakevdp** [comment]
> It seems like when the primal computation depends on the tangents, we get a vmap error when computing full Jacobians.

I think that's the correct synopsis... I'm having trouble deciding whether this is a true bug, or just an unintended use. Are there any non-contrived examples in which the primals depend on the tangents? It seems to me that in itself would indicate the JVP function is malformed.

**Comment by tianjuxue** [comment]
> Thanks for raising the issue!
> 
> > It seems like when the primal computation depends on the tangents, we get a vmap error when computing full Jacobians.
> 
> I think that's the correct synopsis... I'm having trouble deciding whether this is a true bug, or just reflects an unintended use. Are there any non-contrived examples in which the primals depend on the tangents? It seems to me that in itself would indicate the JVP function is malformed.
> 
> Perhaps the best fix here would be to raise a clearer error message in this case?

Thanks for the clarification. For a non-contrived example, the `odeint_rk4_jvp` function defined in [this tutorial](http://implicit-layers-tutorial.org/implicit_functions/) would cause the same issue. It'd be great if this issue can be fixed. Otherwise, I think it's possible to rewrite `odeint_rk4_jvp` so that the primal computation is decoupled from the tangents, but in this way we perhaps can't use the _augmented ODE system_ trick in that tutorial example. The trick is also used in [jax/experimental/ode.py](https://github.com/google/jax/blob/main/jax/experimental/ode.py)

**Comment by jakevdp** [comment]
OK, thanks. Agreed that's unfortunate: just to say in words, basically, if you use `jacrev` and your JVP calls a function that requires the primals and tangents to be stacked together, the vmapped tangents will "infect" the primals with their batching tracer, and the `jacrev` will fail (since it doesn't expect the output primals to be batched).

**Comment by froystig** [comment]
This is less of a bug in functionality, more an issue with under-documentation and error messages. For JVPs, jax requires that the primal outputs are independent of input tangents.

We also don't check this directly in JVPs or forward mode, but we require it once reverse-mode takes place, which is when the resulting error happens (and is rather confusing with its message). It is possible today to get away with writing a JVP whose primal output depends on input tangents, provided all autodiff is done in forward mode.

Strictly checking this property of JVPs is challenging, but we can try to mitigate the surprises by better documentation in the context of `custom_jvp`, and perhaps by adding mention of this to the error message in reverse mode.
