### ISSUE TITLE
Wrapper functions for ConvTranspose etc.

### ISSUE THREAD

**Issue by greydanus** [google/jax#80]
It would be great to add a series of wrapper functions for common (de)convolution operations, eg ConvTranspose in PyTorch https://pytorch.org/docs/stable/nn.html#convtranspose2d

Perhaps Jax doesn't need as many as PyTorch (for example, do we really need separate ConvTranspose1D, 2D, _and_ 3D?). However, it would still be very helpful for GANs, VAEs, etc.

**Comment by indbias** [comment]
It will be super useful to have something that is close in functionality to [tf.layers.conv2d_transpose](https://www.tensorflow.org/api_docs/python/tf/layers/conv2d_transpose), particularly for building generative architectures for images. Thanks!

**Comment by mattjj** [comment]
I think #592 solved this long-standing issue!
