### ISSUE TITLE
Check failed: shape.has_layout() && LayoutUtil::IsMonotonicWithDim0Major(shape.layout())

### ISSUE THREAD

**Issue by MInner** [google/jax#801]
Hi and thanks for an amazing project! 

The python process dies with this error 

> Check failed: shape.has_layout() && LayoutUtil::IsMonotonicWithDim0Major(shape.layout())

 in a very specific case when executing jitted vmaped hessian determinant computation with an input array of shape `(n, 1)`. In all other cases (ether not jitted, not vmapped, not determinant, not `(n, 1)` or a different scalar function) the error does not show up. I am using CPU as the backend.

Here is the code snippet to reproduce (I would rather erase it in a week or so): https://gist.github.com/MInner/893cd32982a3ed3b9d8ab3996ba5595e

Thanks!

**Comment by hawkinsp** [comment]
Thanks for the bug report!

I think this is a bug in XLA where it does not correctly handle a mismatch between the layout expected by the LU decomposition inside the implementation of `det` and the layout produced by a batched `dot` operation. I filed a (internal) bug for the XLA team.

In the meantime, here's a workaround. Change your definition of `det_hess_f` to something along the following lines:
```
  def det_hess_f(x, A): return npla.det(hessian(f)(x, A) + 1e-30)
```
The `+ 1e-30` isn't important, the workaround is to add some elementwise operation that XLA isn't smart enough to optimize away between the `hessian` and the input to `det`.

**Comment by hawkinsp** [comment]
Smaller repro:
```
import jax
from jax import numpy as np
x = onp.ones((10, 1, 1), onp.float32)
jax.jit(lambda y, z: np.linalg.det(np.matmul(y, z)))(x, x)
```

**Comment by hawkinsp** [comment]
PR #811 fixes this, although it requires a Jaxlib rebuild, so you'll either have to build it yourself from source or wait until we make another Jaxlib release. Hope that helps!

**Comment by MInner** [comment]
Awesome, thank you, it definitely does!
