### ISSUE TITLE
REPL latency issue

### ISSUE THREAD

**Issue by adamhaber** [google/jax#802]
I'm running JAX from Jupyter and I've noticed a behaviour I don't understand (might be a bug, probably not): 
I'm calling some un-jitted function `f` which, internally, calls some other jitted function `g`. `g` returns some value `x`, and within `f`, I set an attribute to be `x` (I'm ignoring all the details around because I assume they're not important; I can post the entire thing if it helps):
```
def f(self,...):
    @jit
    def g(...):
        stuff g does
    x = g(...)
    self.factors = x
```   
from Jupyter, I call `foo.f(...)` and it works fine. The thing I don't understand is this: When I do
```
%time foo.factors.sum()
```
it takes several microseconds (this is good); however, it takes roughly one minute for the actual value of `foo.factors.sum()` to be displayed on screen. Is this an expected behaviour? 

Version details: 
Jax - 0.1.35 (macOS, so CPU-only version)
Jaxlib - 0.1.16

**Comment by hawkinsp** [comment]
It's hard to say for sure without a complete repro, but I have a pretty good guess.

Jax uses asynchronous dispatch to hide Python overheads. When you run an operation, Jax doesn't wait for it to complete before returning control to the caller's Python code. Instead, Jax returns a future (a `DeviceArray`). You can pass that `DeviceArray` to other computations, all without waiting for the 
original computation to complete. This allows us to overlap Python work with device-side computation. 
 The only thing that forces Jax to wait for the device computation to complete is if you read the *value* of a DeviceArray from the host.

In your example above, the `%time` block dispatches the work, but does not inspect the value of the output, and therefore does not wait for the computation to complete. You need to force the Python code to wait for completion inside the `%time` block. One way to do this would be to pass the `DeviceArray` to an original (non-Jax) `numpy` function e.g., `import numpy as onp; onp.asarray(x)`. This forces the computation to block until the device value has been copied to the host, but does include the device to host copy time in the `%time` block.

For microbenchmarking, I was also planning to add a `block_until_ready` method to `DeviceArray` that blocks without copying.

Hope this helps!

Is there anything else we should look into here (e.g., is a minute slower than you expect, assuming that's the true computation time)?

**Comment by adamhaber** [comment]
> Jax uses asynchronous dispatch to hide Python overheads

 That was my hunch, without the required technical understanding to support it. :-) Thanks for the clear explanation!

> Is there anything else we should look into here (e.g., is a minute slower than you expect, assuming that's the true computation time)?

I'm not really sure what to expect, regarding computation time. Some things go faster compared to non-JAX-based implementations, some go slower... still trying to understand how to write high-performance jax code. I'll try to release a first version of the package in the next two weeks; I'll post a link when it's ready. I'd be  super happy to hear what the jax-dev team thinks can be improved!

**Comment by hawkinsp** [comment]
PR #809 adds a `block_until_ready` method to `DeviceArray`.

After submitting that PR, I plan to add some documentation describing the asynchronous behavior of JAX, and then close this issue.

**Comment by hawkinsp** [comment]
Ok, I've now documented this: https://jax.readthedocs.io/en/latest/async_dispatch.html
I hope that helps!

Since there's no further action to be taken on this bug, I'm closing it. Please open new issues if performance doesn't match your expectations.
