### ISSUE TITLE
JAX Test Case Loader does not filter cases as (self-)advertised

### ISSUE THREAD

**Issue by nicholasjng** [google/jax#8024]
Hello JAX team,
I am developing a hobby project about benchmarking right now, and wanted to look for ideas on how to best filter benchmark targets in a Python module context by regex (the question was, simply put, "use `re.search` or `re.match` ?"). Now looking at the absl flag in the JAX test loader, it defines the following flag, mentioning that targets get `re.match`ed:

https://github.com/google/jax/blob/ef696a0b433fd4a306d784cd27ccc6a700754955/jax/_src/test_util.py#L72-L76

Yet in the code, it seems that `re.search` is used instead on the compiled pattern:

https://github.com/google/jax/blob/ef696a0b433fd4a306d784cd27ccc6a700754955/jax/_src/test_util.py#L865-L868

This is obviously not a huge deal, but I thought I would report / ask for clarification. If it is indeed a bug, I can also send a fix if that's of interest. Thanks!

**Comment by jakevdp** [comment]
Thanks for flagging the issue. It looks like `match` should be changed to `search` in the documentation string. Are you interested in sending a fix?

**Comment by nicholasjng** [comment]
Sent. Thanks for the explanation!

**Comment by nicholasjng** [comment]
Closed by #8029.
