### ISSUE TITLE
New pretty printing

### ISSUE THREAD

**Issue by soraros** [google/jax#8025]
The new pretty printer implemented in #8019 is great. Having type annotation in the repr is just awesome.
However, I noticed when the jaxper is small everything is squeezed in a single line. I understand it makes higher-order ops look saner, but I'm not sure it looks clearer in the simpler case.
```python
def f(x):
  return x * jnp.sin(x)
jax.make_jaxpr(f)(1.)

# gives
# { lambda ; a:f64[]. let b:f64[] = sin a; c:f64[] = mul a b in (c,) }
```
Maybe a top-level jaxper should always use the multiline style? Or even lose the brackets? Something like
```ocaml
lambda ; a:f64[].
let b:f64[] = sin a
    c:f64[] = mul a b
in (c,)

```

**Comment by hawkinsp** [comment]
We could do that. But are you sure you actually prefer it, as opposed to the new style being unfamiliar?

(By the way, if you are looking at jaxprs, try out the new but undocumented color and source context features:
```
print(jaxpr.pretty_print(use_color=True, source_info=True))
```
assuming you have an ANSI-compatible terminal.)

**Comment by soraros** [comment]
> as opposed to the new style being unfamiliar?

That's a fair assumption. I will give the newer style some more time.

> color and source context

Wow, just wow!

Shall I leave this issue open so people have a place to give their feedback about the new pretty printer, or do you prefer that I close?

**Comment by hawkinsp** [comment]
Let's close the issue because there's no action to take. But feel free to reopen it if there's something to do or any comments to make!
