### ISSUE TITLE
Implement `.flat` on JAX arrays

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#8046]
JAX arrays are missing the `.flat` property:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flat.html

We should add it!

**Comment by jakevdp** [comment]
Just a note on this: the full `np.flatiter` API is more than just an iterator, it also supports advanced indexing operations. For example:
```python
In [1]: import numpy as np                                                                                                     

In [2]: x = np.arange(5)                                                                                                       

In [3]: mask = x > 2                                                                                                           

In [4]: x.flat[mask]                                                                                                           
Out[4]: array([3, 4])

In [5]: x.flat[[1, 2, 3]]                                                                                                     
Out[5]: array([1, 2, 3])
```
I think the implementation of this is going to have some subtleties, particularly with regard to JIT lowering and batching.

The easiest way to tick all the boxes might be to do `flat = property(ravel)`

**Comment by shoyer** [comment]
+1 for `flat = property(ravel)`. I don't think we want to make any attempt at implementing NumPy's iterator API.
