### ISSUE TITLE
jax.numpy array does not handle Enum well

### ISSUE THREAD

**Issue by zhongwen** [google/jax#805]
A repro can be found in the following:

```
import jax.numpy as np
import enum

class StepType(enum.IntEnum):
  FIRST = 0
  SECOND = 1

a = StepType.FIRST
b = StepType.SECOND
d = onp.array([a, b])   # works
c = np.array([a, b])   # doesn't work
```

The error was `TypeError: Unexpected input type for array: <enum 'StepType'>`

**Comment by hawkinsp** [comment]
This works and is tested at head!

**Comment by MRiabov** [comment]
Hello.
Does it? I'm getting an error at:
```
class Shape(enum.IntEnum):
    Box = 1
    Sphere = 2

@flax.struct.dataclass
shape: jnp.ndarray = jnp.zeros(1, dtype=GoalShape)
```
The error is this:
```
TypeError: JAX only supports number and bool dtypes, got dtype <enum 'Shape'> in zeros
  ```
I understand jax arrays requirements, but I'm using enum.IntEnum and that should work? 
If not, am I actually forced to use strings/ints in place of enums?

Cheers.

**Comment by jakevdp** [comment]
JAX only supports numerical dtypes; you will not be able to pass an `Enum` in place of a dtype.

**Comment by MRiabov** [comment]
> JAX only supports numerical dtypes; you will not be able to pass an `Enum` in place of a dtype.

Which is reasonable, but not even IntEnum? Would be nice if jax could convert in under the hood.

**Comment by jakevdp** [comment]
Handling enums in place of dtypes would be a very deep and intrusive change in JAX; without a very compelling use-case (or even with one), it's hard to imagin embarking on such a change.
