### ISSUE TITLE
Update jax.ops.index_* documentation to include current preferred index notation

### ISSUE THREAD

**Issue by Sohl-Dickstein** [google/jax#8064]
If you search on Google for how to update array indices in JAX, you end up on [this documentation page](https://jax.readthedocs.io/en/latest/_autosummary/jax.ops.index_update.html#jax-ops-index-update) for `jax.ops.index_update`.

`jax.ops.index_update` is no longer the best way to update indices -- in most cases users should instead write code like `x.at[idx].set(y)`, which is a really great improvement!

The documentation for the `jax.ops.index_*` should also describe and/or link to the alternate, simpler, and preferred notation for working with indices.

**Comment by jakevdp** [comment]
Thanks for the report – agreed this is something that should be addressed. Are you interested in contributing a fix? If not I'm happy to take care of it.

**Comment by Sohl-Dickstein** [comment]
I am not going to have time to submit a fix in a reasonable timeframe. If you are willing, you should definitely do it! Thank you!

**Comment by jakevdp** [comment]
OK, will do. Thanks!
