### ISSUE TITLE
failed to build v0.2.21 on Windows

### ISSUE THREAD

**Issue by dwrtz** [google/jax#8069]
(asdf) PS C:\Users\david\Dev\jax> python .\build\build.py

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\

Bazel binary path: C:\bazel\bazel.EXE
Python binary path: C:/Users/david/Env/asdf/Scripts/python.exe
Python version: 3.8
NumPy version: 1.21.2
MKL-DNN enabled: yes
Target CPU: AMD64
Target CPU features: release
CUDA enabled: no
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
C:\bazel\bazel.EXE run --verbose_failures=true --config=mkl_open_source_only :build_wheel -- --output_path=C:\Users\david\Dev\jax\dist --cpu=AMD64
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading rc options for 'run' from c:\users\david\dev\jax\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  Inherited 'build' options: --python_path=C:/Users/david/Env/asdf/Scripts/python.exe
INFO: Reading rc options for 'run' from c:\users\david\dev\jax\.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs
INFO: Reading rc options for 'run' from c:\users\david\dev\jax\.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=C:/Users/david/Env/asdf/Scripts/python.exe --action_env=PYENV_ROOT --python_path=C:/Users/david/Env/asdf/Scripts/python.exe --distinct_host_configuration=false
INFO: Found applicable config definition build:short_logs in file c:\users\david\dev\jax\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:mkl_open_source_only in file c:\users\david\dev\jax\.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:windows in file c:\users\david\dev\jax\.bazelrc: --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/Zc:preprocessor --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true
DEBUG: Rule 'io_bazel_rules_docker' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1596824487 -0400"
DEBUG: Repository io_bazel_rules_docker instantiated at:
  C:/users/david/dev/jax/WORKSPACE:37:14: in <toplevel>
  C:/users/david/_bazel_david/5thqsmz3/external/org_tensorflow/tensorflow/workspace0.bzl:108:34: in workspace
  C:/users/david/_bazel_david/5thqsmz3/external/bazel_toolchains/repositories/repositories.bzl:35:23: in repositories
Repository rule git_repository defined at:
  C:/users/david/_bazel_david/5thqsmz3/external/bazel_tools/tools/build_defs/repo/git.bzl:199:33: in <toplevel>
INFO: Analyzed target //build:build_wheel (2 packages loaded, 45 targets configured).
INFO: Found 1 target...
ERROR: C:/users/david/_bazel_david/5thqsmz3/external/org_tensorflow/tensorflow/compiler/mlir/hlo/BUILD:571:11: C++ compilation of rule '@org_tensorflow//tensorflow/compiler/mlir/hlo:lhlo' failed (Exit 2): cl.exe failed: error executing command
  cd C:/users/david/_bazel_david/5thqsmz3/execroot/__main__
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\ATLMFC\include;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\\Extensions\Microsoft\IntelliCode\CLI;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\\MSBuild\Current\Bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\;;C:\WINDOWS\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\david\AppData\Local\Temp
    SET TMP=C:\Users\david\AppData\Local\Temp
  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/HostX64/x64/cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE /D_CRT_SECURE_NO_WARNINGS /bigobj /Zm500 /EHsc /wd4351 /wd4291 /wd4250 /wd4996 /Iexternal/org_tensorflow /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow /Iexternal/llvm-project /Ibazel-out/x64_windows-opt/bin/external/llvm-project /Iexternal/llvm_terminfo /Ibazel-out/x64_windows-opt/bin/external/llvm_terminfo /Iexternal/llvm_zlib /Ibazel-out/x64_windows-opt/bin/external/llvm_zlib /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinDialectIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinLocationAttributesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinTypeInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinTypesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/CallOpInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/CastOpInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/InferTypeOpInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/OpAsmInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/RegionKindInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SideEffectInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SubElementInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SymbolInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/TensorEncodingIncGen /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/hlo_ops_base_inc_gen /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_structs_inc_gen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/AffineMemoryOpInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/AffineOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/LoopLikeInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/ControlFlowInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/CopyOpInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/MemRefBaseIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/MemRefOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/StandardOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/VectorInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/TensorOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/ViewLikeInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/LinalgInterfacesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/LinalgStructuredOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/LinalgOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/MathBaseIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/MathOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/ParserTokenKinds /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SCFIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/SCFPassIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/TilingInterfaceIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/PDLOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/PDLTypesIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/PDLInterpOpsIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/ConversionPassIncGen /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/TransformsPassIncGen /Iexternal/org_tensorflow/tensorflow/compiler/mlir/hlo/include /Ibazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/include /Iexternal/llvm-project/llvm/include /Ibazel-out/x64_windows-opt/bin/external/llvm-project/llvm/include /Iexternal/llvm-project/mlir/include /Ibazel-out/x64_windows-opt/bin/external/llvm-project/mlir/include /Dstricmp=_stricmp /Dstrdup=_strdup /DLTDL_SHLIB_EXT=".dll" /DLLVM_PLUGIN_EXT=".dll" /DLLVM_NATIVE_ARCH="X86" /DLLVM_NATIVE_ASMPARSER=LLVMInitializeX86AsmParser /DLLVM_NATIVE_ASMPRINTER=LLVMInitializeX86AsmPrinter /DLLVM_NATIVE_DISASSEMBLER=LLVMInitializeX86Disassembler /DLLVM_NATIVE_TARGET=LLVMInitializeX86Target /DLLVM_NATIVE_TARGETINFO=LLVMInitializeX86TargetInfo /DLLVM_NATIVE_TARGETMC=LLVMInitializeX86TargetMC /DLLVM_NATIVE_TARGETMCA=LLVMInitializeX86TargetMCA /DLLVM_HOST_TRIPLE="x86_64-pc-win32" /DLLVM_DEFAULT_TARGET_TRIPLE="x86_64-pc-win32" /D__STDC_LIMIT_MACROS /D__STDC_CONSTANT_MACROS /D__STDC_FORMAT_MACROS /showIncludes /MD /O2 /Oy- /DNDEBUG /wd4117 -D__DATE__="redacted" -D__TIMESTAMP__="redacted" -D__TIME__="redacted" /Gy /Gw /D_USE_MATH_DEFINES -DWIN32_LEAN_AND_MEAN -DNOGDI /Zc:preprocessor /std:c++14 /Fobazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_objs/lhlo/lhlo_ops_structs.obj /c external/org_tensorflow/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/IR/lhlo_ops_structs.cc
Execution platform: @local_execution_config_platform//:platform
Target //build:build_wheel failed to build
INFO: Elapsed time: 96.887s, Critical Path: 29.87s
INFO: 118 processes: 18 internal, 100 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
b"bazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(25): error C2665: 'mlir::DictionaryAttr::get': none of the 3 overloads could convert all the argument types\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen\\mlir/IR/BuiltinAttributes.h.inc(263): note: could be 'mlir::DictionaryAttr mlir::DictionaryAttr::get(mlir::MLIRContext *,llvm::ArrayRef<mlir::NamedAttribute>)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(25): note: while trying to match the argument list '(llvm::SmallVector<mlir::NamedAttribute,2>, mlir::MLIRContext *)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(116): error C2665: 'mlir::DictionaryAttr::get': none of the 3 overloads could convert all the argument types\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen\\mlir/IR/BuiltinAttributes.h.inc(263): note: could be 'mlir::DictionaryAttr mlir::DictionaryAttr::get(mlir::MLIRContext *,llvm::ArrayRef<mlir::NamedAttribute>)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(116): note: while trying to match the argument list '(llvm::SmallVector<mlir::NamedAttribute,9>, mlir::MLIRContext *)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(266): error C2665: 'mlir::DictionaryAttr::get': none of the 3 overloads could convert all the argument types\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen\\mlir/IR/BuiltinAttributes.h.inc(263): note: could be 'mlir::DictionaryAttr mlir::DictionaryAttr::get(mlir::MLIRContext *,llvm::ArrayRef<mlir::NamedAttribute>)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(266): note: while trying to match the argument list '(llvm::SmallVector<mlir::NamedAttribute,4>, mlir::MLIRContext *)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(356): error C2665: 'mlir::DictionaryAttr::get': none of the 3 overloads could convert all the argument types\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen\\mlir/IR/BuiltinAttributes.h.inc(263): note: could be 'mlir::DictionaryAttr mlir::DictionaryAttr::get(mlir::MLIRContext *,llvm::ArrayRef<mlir::NamedAttribute>)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(356): note: while trying to match the argument list '(llvm::SmallVector<mlir::NamedAttribute,4>, mlir::MLIRContext *)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(446): error C2665: 'mlir::DictionaryAttr::get': none of the 3 overloads could convert all the argument types\r\nbazel-out/x64_windows-opt/bin/external/llvm-project/mlir/_virtual_includes/BuiltinAttributesIncGen\\mlir/IR/BuiltinAttributes.h.inc(263): note: could be 'mlir::DictionaryAttr mlir::DictionaryAttr::get(mlir::MLIRContext *,llvm::ArrayRef<mlir::NamedAttribute>)'\r\nbazel-out/x64_windows-opt/bin/external/org_tensorflow/tensorflow/compiler/mlir/hlo/_virtual_includes/lhlo_ops_inc_gen\\mlir-hlo/Dialect/mhlo/IR/lhlo_ops_structs.cc.inc(446): note: while trying to match the argument list '(llvm::SmallVector<mlir::NamedAttribute,4>, mlir::MLIRContext *)'\r\n"
Traceback (most recent call last):
  File ".\build\build.py", line 521, in <module>
    main()
  File ".\build\build.py", line 516, in main
    shell(command)
  File ".\build\build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "C:\Users\david\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\david\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['C:\\bazel\\bazel.EXE', 'run', '--verbose_failures=true', '--config=mkl_open_source_only', ':build_wheel', '--', '--output_path=C:\\Users\\david\\Dev\\jax\\dist', '--cpu=AMD64']' returned non-zero exit status 1.

**Comment by hawkinsp** [comment]
I'm pretty sure this issue is long fixed, e.g., 0.3.14 can be obtained from the community supported Windows build project (https://github.com/cloudhan/jax-windows-builder).
