### ISSUE TITLE
Binary Distribution for Python 3.10

### ISSUE THREAD

**Issue by daskol** [google/jax#8097]
[Python 3.10][python310] was released yesterday. However, the command below fails
```bash
pip install jaxlib
```
since `jaxlib` is linked against specific version of CPython. It would be great to provide `jaxlib` to end users for the fresh version of Python.

[python310]: https://www.python.org/downloads/release/python-3100/

**Comment by hawkinsp** [comment]
With #8101 merged, JAX builds and the tests pass on Python 3.10.

@yashk2810 would you please take over this bug and look after:
a) adding 3.10 to our release builds and
b) our CI tests?

You may need to wait for scipy to release 3.10 wheels first, which I believe is tracked by https://github.com/scipy/scipy/issues/14567

For the above, I built scipy from git head locally; the released scipy did not work correctly with 3.10, so you can't rely on `pip install scipy` to do the right thing until there is a scipy release.

**Comment by daskol** [comment]
@hawkinsp Many thanks!

**Comment by yashk2810** [comment]
Sounds good. I'll wait for scipy.

**Comment by NeilGirdhar** [comment]
scipy is released now, but jaxlib still doesn't install

**Comment by daskol** [comment]
> scipy is released now, but jaxlib still doesn't install

@NeilGirdhar It's okay. Package `jaxlib` is binary distributable what means that it is pinned to particular version of Python. Information from SciPy maintainers about release with Python 3.10 support appeared one hour ago so JAX maintainers have no enough time to build `jaxlib` and upload to PyPI. Just a little more time.

**Comment by NeilGirdhar** [comment]
@daskol Yes, sorry, I was just trying to let the Jax developers know that scipy is no longer blocking jaxlib 😄

**Comment by grahamgower** [comment]
Hi. Any update on this?

**Comment by yashk2810** [comment]
Hi, yes we are releasing today! Stay tuned :)

**Comment by yashk2810** [comment]
jaxlib 3.10 wheels have been released: https://pypi.org/project/jaxlib/0.1.75/#files

New jax release too: https://pypi.org/project/jax/0.2.26/#files

**Comment by kiefernforst** [comment]
BTW: Is https://pypi.org/project/jaxlib/0.6.2/#files the latest supporting Python 3.10?
