### ISSUE TITLE
make colab notebooks runnable as tests

### ISSUE THREAD

**Issue by mattjj** [google/jax#81]
That will help us avoid breaking notebooks, especially once we have CI going!

**Comment by necula01** [comment]
I would like to take this on. It seems that it is possible to execute notebooks using the jupyter package. This would require adding jupyter as a requirement for testing, along with other packages that may be mentioned in the notebooks, e.g., mathplotlib. The test take about 10 seconds per notebook.

**Comment by gnecula** [comment]
It seems that maml.ipynb has failed at least once due to timeout.
