### ISSUE TITLE
Profiling with XLA_FLAGS=--xla_hlo_profile not working

### ISSUE THREAD

**Issue by juliuskunze** [google/jax#8111]
The command

```sh
TF_CPP_MIN_LOG_LEVEL=0 XLA_FLAGS=--xla_hlo_profile python3 -c "from jax import lax; print(lax.add(1, 2))"
```

given as an example in [XLA profiling](https://jax.readthedocs.io/en/latest/profiling.html#xla-profiling) results in

- a segfault on CPU,
- the error `--xla_hlo_profile for GPU is unsupported.` on GPU and
- the correct output `3` without additional XLA profiling info on TPU.

I would like to trace all executed XLA ops of a `jit` compiled function to understand a potential issue with XLA operator fusion. I tried to use [`jax.profiler.trace()`](https://jax.readthedocs.io/en/latest/profiling.html#programmatic-capture), but it seems that not all operations are traced (or displayed by TensorBoard), which makes debugging more difficult in my case.

**Comment by hawkinsp** [comment]
Unfortunately I think `--xla_hlo_profile` is mostly deprecated at this point, in lieu of the tensorboard approach. I think we should remove its documentation.

Can you say more about what didn't work about the tensorboard approach?
