### ISSUE TITLE
Scatter update seems to not handle symbolic zeros.

### ISSUE THREAD

**Issue by sschoenholz** [google/jax#812]
This is a followup of #776. For a repo see the colab [here](https://colab.research.google.com/drive/1jYf-dWxzYECkwElQmAlrJ9RKx-IIjjDL).

**Comment by mattjj** [comment]
Thanks! (Did we un-fix this?)

**Comment by sschoenholz** [comment]
I had thought it was fixed! However, looking back it seems like maybe scatter_add got fixed but scatter_update did not? Otherwise, perhaps it got unfixed somewhere?

**Comment by mattjj** [comment]
We think this is a version issue; I'll update pypi.

**Comment by mattjj** [comment]
Updating pypi to 0.1.36 seems to fix the notebook! Maybe do this to double-check you're on 0.1.36 (just uploaded) or later:

```python
import jax
print(jax.version.__version__)
```
