### ISSUE TITLE
np.dot for integer arrays

### ISSUE THREAD

**Issue by dbieber** [google/jax#814]
```
import jax.numpy as np
x = np.array((1,2,3))
np.dot(x, x)
```
gives `RuntimeError: Unimplemented: unsupported operand type S32 in op dot`

1. The error isn't super clear since S32 isn't a Python/numpy type
2. This should work, right? In numpy this correctly gives 14:
```
import numpy as onp
onp.dot(x, x)
```

**Comment by mattjj** [comment]
It's surprising that people don't seem to complain about this more :)

That error message is from XLA. Which backend are you on?

**Comment by dbieber** [comment]
Running with the CPU on my mac.
