### ISSUE TITLE
O(n) program takes O(exp(n)) work to linearize

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#8193]
The function `fn` has runtime `O(depth)`; its jaxpr is of size `O(depth)`. Linearising it takes `O(exp(depth))` time.

```python
import time
import jax
import jax.lax as lax
import jax.numpy as jnp

def fn(x, pred, depth):
    if depth == 1:
        return x
    else:
        _fn = lambda x: fn(x, pred, depth - 1)
        return lax.cond(pred, _fn, lambda x: x, x)

def timed(depth):
    start = time.time()
    jax.linearize(lambda x: fn(x, True, depth), jnp.array([1.]))
    timespan = time.time() - start
    print(f"{depth=} {timespan=}")

timed(7)
timed(8)
timed(9)
timed(10)
timed(11)
timed(12)

# Prints:
# depth=7 timespan=0.3668365478515625
# depth=8 timespan=0.5641067028045654
# depth=9 timespan=0.9860150814056396
# depth=10 timespan=2.0171751976013184
# depth=11 timespan=4.0435779094696045
# depth=12 timespan=7.562690019607544
```

The problem is that the partial-eval interpreter recursively calls itself twice during `_cond_partial_eval`, here:
https://github.com/google/jax/blob/a6a469154f68c248dd076e7bc171d4e22df84237/jax/_src/lax/control_flow.py#L907
and here:
https://github.com/google/jax/blob/a6a469154f68c248dd076e7bc171d4e22df84237/jax/_src/lax/control_flow.py#L913
thus resulting in an exponential amount of work done by the interpreter.

c.f. also #8184, which demonstrates a similar issue for `make_jaxpr`-`vmap`-`cond`. (This issue considers just `linearize`-`cond`; no `vmap`.)

**Comment by mattjj** [comment]
Currently at HEAD:

```
depth=7 timespan=0.026594877243041992
depth=8 timespan=0.019034147262573242
depth=9 timespan=0.02187204360961914
depth=10 timespan=0.024119138717651367
depth=11 timespan=0.026736021041870117
depth=12 timespan=0.028378725051879883
```

I think the caching in https://github.com/google/jax/pull/9196 and https://github.com/google/jax/pull/9228 made this example fast.

**But** I'm not claiming that all issues of this kind are fixed. I'm going to try to make harder repros.

**Comment by patrick-kidger** [comment]
Closing as having been fixed for a while.
