### ISSUE TITLE
Slow compile with colab tpu

### ISSUE THREAD

**Issue by luyug** [google/jax#8243]
Running `pmap`  takes very long and may time out compiling on colab running transformer language model pre-training with tpu.

The issue can be reproduced by running pre-training notebook from huggingface https://colab.research.google.com/github/huggingface/notebooks/blob/master/examples/masked_language_modeling_flax.ipynb using a tpu session.

I tried to explicitly set `backend='tpu'` when running `pmap` , but got the following error,
```
RuntimeError: Requested backend tpu, but it failed to initialize: INVALID_ARGUMENT: TpuPlatform is not available.
```

**Comment by luyug** [comment]
Also this should not matter but I used the high RAM TPU sessions. They offer more cpu cores and can make pre-processing faster. In particular setting a higher process count in the dataset map calls significantly reduces the run time before entering the train loop.

```
tokenized_datasets = raw_dataset.map(tokenize_function, batched=True, num_proc=40, 
```
```
tokenized_datasets = tokenized_datasets.map(group_texts, batched=True, num_proc=40)
```

**Comment by MXueguang** [comment]
Hi @jakevdp, I got exactly same error when I trying to add the `backend='tpu'` to `pmap` on colab.

The minimum code to reproduce the error is as below:
```python
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()

from jax import pmap
import jax.numpy as jnp

def f(x):
  print(x)
  return x**2

v = jnp.arange(8)
pf = pmap(f, backend='tpu')
pf(v)
```
```
RuntimeError: Requested backend tpu, but it failed to initialize: INVALID_ARGUMENT: TpuPlatform is not available.
```

**Comment by johnnytshi** [comment]
Same experience here

If I run a perceiver model with 200m params on TPU (8 devices), the compilation gets killed by this error: **compile failed to finish within 1 hour**

However, it compiles fine on GPU (takes 10 min or so)

**Comment by rajasekharporeddy** [comment]
Hi @luyug 

I ran the provided colab notebook using TPU v2 with JAX 0.4.23. It now does produce any RunTimeError. Also, I didn't face any compilation issues and the training process for 10 epoches is completed in around 20 minutes.

Please find the [gist](https://colab.sandbox.google.com/gist/rajasekharporeddy/6de12d65c6a3e21938c2399b2f53c0d9/masked-language-model-pretraining-on-tpu-with-transformers-jax.ipynb) for reference.

Thank you.

**Comment by jakevdp** [comment]
Thanks! Yeah I suspect this had to do with the setup step for the older deprecated TPU runtimes, so it seems like this can be closed now. Thanks for following up!
