### ISSUE TITLE
parser = DepCCGParser() gives error in training.ipnyb tutorial

### ISSUE THREAD

**Issue by dancbeaulieu** [google/jax#8266]
When I run the code in the training.ipnyb in the examples directory I get an error.

```
from lambeq.ccg2discocat import DepCCGParser
from lambeq.tensor import TensorAnsatz
from lambeq.core.types import AtomicType
from discopy import Dim

# Define atomic types
N = AtomicType.NOUN
S = AtomicType.SENTENCE

# Parse a sentence
parser = DepCCGParser()
diagram = parser.sentence2diagram("John walks in the park")

# Apply a tensor ansatz
ansatz = TensorAnsatz({N: Dim(4), S: Dim(2)})
tensor_diagram = ansatz(diagram)
tensor_diagram.draw(figsize=(12,5), fontsize=12)
```

I get the error:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/var/folders/p_/xgkqmkd52bb33842gkzmxdy00000gp/T/ipykernel_87378/340184458.py in <module>
      9 
     10 # Parse a sentence
---> 11 parser = DepCCGParser()
     12 diagram = parser.sentence2diagram("John walks in the park")
     13 

~/opt/anaconda3/envs/qisneur/lib/python3.9/site-packages/lambeq/ccg2discocat/depccg_parser.py in __init__(self, model, use_model_unary_rules, **kwargs)
    105             raise TypeError('`model` must be an `EnglishCCGParser` or a str.')
    106 
--> 107         model_dir, config_file = depccg.download.load_model_directory(
    108                 f'en[{model}]' if model else 'en')
    109 

~/opt/anaconda3/envs/qisneur/lib/python3.9/site-packages/depccg/download.py in load_model_directory(model_name)
     98         model_path = model_path.with_suffix('.tar.gz')
     99     if not model_path.exists():
--> 100         lang, variant = model_name[:-1].split('[')
    101         raise RuntimeError(f'please download the model by doing \'depccg_{lang} download VARIANT\'.')
    102     return model_path, config

ValueError: not enough values to unpack (expected 2, got 1)

     Python 3.9.7
     lambeq Version: 0.1.2

**Comment by hawkinsp** [comment]
I think this bug is filed in the wrong repository --- it's not a JAX bug.
