### ISSUE TITLE
install command doesn't work

### ISSUE THREAD

**Issue by xmax1** [google/jax#8279]
What should the command to install be? 

`
(pansatz) [amawi@sylg nn_ansatz]$ pip install --upgrade pip

Requirement already satisfied: pip in /home/energy/amawi/miniconda3/envs/pansatz/lib/python3.7/site-packages (21.3)

(pansatz) [amawi@sylg nn_ansatz]$ pip install jax[cuda==11, cudnn==82] -f https://storage.googleapis.com/jax-releases/jax_releases.html

ERROR: Invalid requirement: 'jax[cuda==11,'

(pansatz) [amawi@sylg nn_ansatz]$ pip install jax[cuda=11, cudnn=82] -f https://storage.googleapis.com/jax-releases/jax_releases.html

ERROR: Invalid requirement: 'jax[cuda=11,'
Hint: = is not a valid operator. Did you mean == ?

(pansatz) [amawi@sylg nn_ansatz]$ pip install "jax[cuda=11, cudnn=82]" -f https://storage.googleapis.com/jax-releases/jax_releases.html

ERROR: unknown command "install jax[cuda=11, cudnn=82]"
`

**Comment by yashk2810** [comment]
https://pypi.org/project/jax/0.2.24/ is live which fixes the error.

**Comment by yashk2810** [comment]
We don't have py3.10 builds yet.

> I have CUDA 11.3 and cuDNN 8.2.

Try, `pip install -U jax[cuda] -f https://storage.googleapis.com/jax-releases/jax_releases.html`.

The new instructions are here: https://github.com/google/jax/blob/main/README.md#pip-installation-gpu-cuda

**Comment by GeoffNN** [comment]
Thanks!
This gets `jaxlib` -- strangely I still get an import error, this time with `ModuleNotFoundError: No module named 'scipy.linalg'` -- `scipy` is installed.

**Comment by GeoffNN** [comment]
`import jax` gets this stacktrace

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../anaconda3/envs/aaa/lib/python3.9/site-packages/jax/__init__.py", line 37, in <module>
    from . import config as _config_module
  File ".../anaconda3/envs/aaa/lib/python3.9/site-packages/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File ".../anaconda3/envs/aaa/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File ".../anaconda3/envs/aaa/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 75, in <module>
    from jaxlib import lapack
  File ".../anaconda3/envs/aaa/lib/python3.9/site-packages/jaxlib/lapack.py", line 21, in <module>
    from . import _lapack
ImportError: ModuleNotFoundError: No module named 'scipy.linalg'
>>> 
```

**Comment by yashk2810** [comment]
Interesting.. i don't see that.

I just tried this in colab: `!pip install --upgrade jax[cuda11_cudnn805] -f https://storage.googleapis.com/jax-releases/jax_releases.html` with a GPU runtime.

Then `import jax; jax.devices()`

Can you check on colab and see if you hit the error?

**Comment by GeoffNN** [comment]
Probably -- doing `conda update conda` and then re-doing everything from scratch: new environment, first `pip install -U jax`, then `pip install -U jax[cuda] -f https://storage.googleapis.com/jax-releases/jax_releases.html` *worked*. 
Thanks!
