### ISSUE TITLE
sparse.BCOO.fromdense cannot be called inside a function which is jittable

### ISSUE THREAD

**Issue by shailesh1729** [google/jax#8299]
My use case is the following.  Inside a function `f`, after some computation, I get a matrix for which I am sure that it is a sparse matrix. I wish to convert this matrix to a sparse format using BCOO so that I can make the following computations efficient.  Ideally, I should be able to jit `f`. It doesn't look possible right now. 

Here is a simple example:

```python
from jax.experimental import sparse
jsum = sparse.sparsify(jnp.sum)

def test_bcoo(A):
    B  = sparse.BCOO.fromdense(A)
    return jsum(B)

print(test_bcoo(jnp.eye(4)))

test_bcoo_jit = jax.jit(test_bcoo)
print(test_bcoo_jit(jnp.eye(4)))
```

`test_bcoo` runs perfectly but `test_bcoo_jit` fails with following error: 

```
---------------------------------------------------------------------------
ConcretizationTypeError                   Traceback (most recent call last)
<ipython-input-91-4e719b763a0d> in <module>
      9 
     10 test_bcoo_jit = jax.jit(test_bcoo)
---> 11 print(test_bcoo_jit(jnp.eye(4)))

    [... skipping hidden 13 frame]

<ipython-input-91-4e719b763a0d> in test_bcoo(A)
      3 
      4 def test_bcoo(A):
----> 5     B  = sparse.BCOO.fromdense(A)
      6     return jsum(B)
      7 

/opt/anaconda3/envs/jax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py in fromdense(cls, mat, nse, index_dtype, n_dense, n_batch)
    958   def fromdense(cls, mat, *, nse=None, index_dtype=np.int32, n_dense=0, n_batch=0):
    959     """Create a BCOO array from a (dense) :class:`DeviceArray`."""
--> 960     return cls(bcoo_fromdense(mat, nse=nse, index_dtype=index_dtype, n_dense=n_dense, n_batch=n_batch), shape=mat.shape)
    961 
    962   @classmethod

/opt/anaconda3/envs/jax/lib/python3.9/site-packages/jax/experimental/sparse/bcoo.py in bcoo_fromdense(mat, nse, n_batch, n_dense, index_dtype)
    216   if nse is None:
    217     nse = _bcoo_nse(mat, n_batch, n_dense)
--> 218   nse = core.concrete_or_error(operator.index, nse, "nse argument of bcoo_fromdense")
    219   return bcoo_fromdense_p.bind(mat, nse=nse, n_batch=n_batch, n_dense=n_dense,
    220                                index_dtype=index_dtype)

/opt/anaconda3/envs/jax/lib/python3.9/site-packages/jax/core.py in concrete_or_error(force, val, context)
   1009       return force(val.aval.val)
   1010     else:
-> 1011       raise ConcretizationTypeError(val, context)
   1012   else:
   1013     return force(val)

ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(int64[])>with<DynamicJaxprTrace(level=0/1)>
nse argument of bcoo_fromdense
While tracing the function test_bcoo at <ipython-input-91-4e719b763a0d>:4 for jit, this concrete value was not available in Python because it depends on the value of the argument 'A'.

See https://jax.readthedocs.io/en/latest/errors.html#jax.errors.ConcretizationTypeError
```

**Comment by jakevdp** [comment]
Thanks for the report – we should improve this error, but it is expected that `sparse.BCOO.fromdense` will fail within JIT unless you pass a static value to `nse` (number of specified elements):
```python
def test_bcoo(A):
    B  = sparse.BCOO.fromdense(A, nse=4)
    return jsum(B)
```
This is for the same reasons that simpler functions like `jnp.where`, or `jnp.nonzero`, or `jnp.unique`, will fail if used within JIT: JAX array shapes must be statically known, and not depend on the contents of traced arrays. It is a fundamental limitation of JAX's compilation model.

In general, I'd suggest treating sparse matrix creation as something that happens as a setup step before you call your workhorse function, so e.g. something like this:
```python
B  = sparse.BCOO.fromdense(A)

def test_bcoo(B):
    return jsum(B)
```
Then the number of specified elements can be determined automatically while the input matrix is still concrete.

Does that make sense?

**Comment by jakevdp** [comment]
#8305 improves this error message. It now says:
```
jax._src.errors.ConcretizationTypeError: Abstract tracer value encountered where concrete value is expected: Traced<ShapedArray(int32[])>with<DynamicJaxprTrace(level=0/1)>

The error arose for the nse argument of bcoo_fromdense. In order for BCOO.fromdense()
to be used in traced or compiled code, you must pass a concrete value to the nse
(number of specified elements) argument
```

**Comment by shailesh1729** [comment]
Thanks for the explanation. That is very helpful. Is `nse` an upper limit on the number of non-zero elements inside A?  Or does it have to be the exact number of non-zero elements in A?  If it's an upper limit, I may have some idea about computing it statically in my use case. Otherwise, it will be impossible. 

A couple of more questions about storage, as they are not explained in detail in the current documentation of `jax.experimental.sparse`. 
- If a BCOO based array is filled to capacity `nse` and I add a new element, say `A = A.at[i,j].set(v)` at an index that was previously zero, would that work without any issues? I am guessing, this cannot be supported as the output size may or may not increase and such a JAX operation cannot be jitted. The only way this is doable is if nse increases by 1 whenever an array element is set. 
- Can I add/subtract two BCOO based matrices? If yes, and, If I add two BCOO based matrices A and B, how does BCOO compute the nse for the sum C = A + B?  Technically, this could be done with nse_c = nse_a + nse_b (thus size calculation can be static), although it could be somewhat storage inefficient. 
- Will something like C = A + A.T also retain BCOO format? 
- Will the product C = A @ B also be BCOO based? 
- I guess my general question is: what are the binary operations on sparse matrices under which output remains sparse? 

It feels like to allow different types of unary/binary operations on sparse BCOO formatted matrices, some storage inefficiency would have to be allowed to meet the requirements of jit. 

Let me go over some more details about the specific use case I am working on so that I may be able to spell out more needs I have with BCOO API.  Not sure if it aligns with the current plans for BCOO. I start with a dense matrix, generate a sparse matrix as an intermediate step, and then do spectral clustering (involving things like truncated SVD on the sparse matrix) to achieve the final result. Ideally, I wish to achieve all this within a single jittable function. That is why preparing the sparse matrix as a setup step is not really fitting in my use case. 

More specifically, I am working on a sparse subspace clustering via orthogonal matching pursuit implementation using JAX.  Here is a full [example notebook](https://cr-sparse.readthedocs.io/en/latest/gallery/cluster/ssc_omp.html#sphx-glr-gallery-cluster-ssc-omp-py).  Main steps:
- Construct sparse representations from a dense collection of points.
- Generate an affinity matrix using the sparse representations. The affinity matrix is sparse too. 
- Perform spectral clustering on the affinity matrix. 

You have a set of points from different low dimensional subspaces (k dimensional) of an ambient space R^n arranged in a  matrix X (column-wise). You now treat (column normalized) X as a dictionary and try to construct a representation of each point in X (each column) in terms of other points in X with the representation consisting of up to k points using orthogonal matching pursuit.   

The implementation is [here](https://github.com/carnotresearch/cr-sparse/blob/master/src/cr/sparse/_src/cluster/ssc/omp.py).
The output of this function is Z, I, R.  If X is of size (n, s) where s is the number of points in X, then Z is of size (k,s) and I is of size (k,s). Each column z in Z is a k-dimensional representation of the corresponding point in X in terms of other points.  The corresponding column i in I identifies the indices of points in X which were used to create the representation z. R contains residuals. Not relevant for this discussion. 

I am currently using the following function to generate a full matrix (with a large number of zeros) to combine Z and I.

```python
@jit
def sparse_to_full_rep(X, I):
    """Combines values and indices arrays to sparse representations
    """
    # number of signals
    n  = X.shape[1]
    mapper = lambda x, i : jnp.zeros(n).at[i].set(x)
    return vmap(mapper, (1,1), 1)(X, I)
```

The output of this function has shape (s,s)  and it has up to sk non-zero entries.  Some of the entries in Z could be 0. Hence,  the 
number of non-zero elements could actually be less than sk. 

With the current BCOO API, I could possibly do the following inside a jittable code:

```python
BCOO.fromdense(sparse_to_full_rep(X, I), nse=sk)
```
But this will involve extra work of first forming a dense matrix and then converting it back to BCOO format. If BCOO had an API to fill directly from values and indices, that would be great. In fact, in that case, it would not need an nse parameter also as the maximum number of non-zero entries would directly come from the indices matrix.  Something like
```python
BCOO.from_values_and_indices(shape, values, indices)
```
I can see that this particular need is too specific to two-dimensional matrices while BCOO implementation is focused on general sparse ND arrays.  MATLAB does provide API to [create sparse matrices](https://in.mathworks.com/help/matlab/ref/sparse.html) from values and indices. 

Since the spectral clustering needs only k eigenvalues and corresponding eigenvectors, I also implemented a jittable truncated SVD computation using Lanczos bidiagonalization and partial reorthogonalization in [lansvd.py](https://github.com/carnotresearch/cr-sparse/blob/master/src/cr/sparse/_src/la/svdpack/lansvd.py) and [lanbpro.py](https://github.com/carnotresearch/cr-sparse/blob/master/src/cr/sparse/_src/la/svdpack/lanbpro.py). 

JAX doesn't yet have an SVDS or EIGS function.  My current implementation of `lansvd` is significantly faster than doing a full svd using JAX when I need just a few singular values. 

This code is, I believe,  fully ready to accept a BCOO based matrix as the only API it needs from the input matrix is matrix forward and adjoint multiplication which is already supported by BCOO.  That would probably make lansvd and hence spectral clustering run much faster too.

**Comment by shailesh1729** [comment]
Thank you very much. It gives much greater clarity on BCOO usage.  

Yes, I would be happy to contribute the Lanczos solver to JAX.  The natural place for truncated SVD/EIG computation is in the JAX library itself so that all applications can benefit from it.   However, I am not familiar with the internals of JAX. If someone could take this code and adapt it to fit inside the internal structure of Jax, that would be great.  What I achieved was a straightforward implementation retaining the original logic of the paper. Someone with deeper JAX knowledge could definitely optimize it a lot further.  Also, I guess some work would be required so that the implementation is vectorized for ND array inputs. 

The core `lanbpro` routine has been tested a lot with large matrices with variations in the singular values.  The `lansvd` part is still incomplete. The main problem is with the current `bdsqr` I have so far does require a static k. This forces me to choose a pessimistically large `k` value in the `lansvd_simple` function input and hope that all the actually needed (less than k) singular values will converge.  The full-blown lansvd will require proper tracking of how many singular values have converged and do more `lanbpro` iterations if required.  

I have the following next steps in my mind: 
- Implement an implicit QR with zero shift algorithm for computing the svd of bidiagonal matrices in a manner that doesn't require any static arguments.  LAPACK has it but JAX/LAX/XLA doesn't expose anything like that.
- Complete the refine bounds function for lansvd so that I have better information on how many singular values have actually converged.
- Start with less number of lanbpro iterations and increase it as needed to achieve the needed number of converged singular values. 

Maybe we can discuss this further on a separate enhancement issue.

**Comment by jakevdp** [comment]
> Maybe, a block_until_ready method can be added to BCOO which simply blocks on the data or indices attribute.

+1 - that's a great idea.

**Comment by jakevdp** [comment]
I have a draft of the `todense()` primitive in #8340

I need to add tests first, but once the above PRs are merged you should be able to do this:
```python
import jax.numpy as jnp
from jax.experimental import sparse

def normalized_symmetric(W):
  assert W.ndim == 2
  D = sparse.todense(jnp.sum(W, 0))
  D_half_inv = D**(-1/2)
  return D_half_inv[:, None] * W * D_half_inv

W = jnp.array([[1, 0.5, 0], [0.5, 1, 0], [0, 0, 1]])
normalized_symmetric(W)
# DeviceArray([[0.6666667 , 0.33333334, 0.        ],
#              [0.33333334, 0.6666667 , 0.        ],
#              [0.        , 0.        , 1.        ]], dtype=float32)

W_sp = sparse.BCOO.fromdense(W)
sparse.sparsify(normalized_symmetric)(W_sp).todense()
# DeviceArray([[0.6666667 , 0.33333334, 0.        ],
#              [0.33333334, 0.6666667 , 0.        ],
#              [0.        , 0.        , 1.        ]], dtype=float32)
```

**Comment by shailesh1729** [comment]
I released all the work done so far related to this as part of [CR-Sparse 0.2.0](https://github.com/carnotresearch/cr-sparse/discussions/20) today. 

Here is a[ Jupyter notebook](https://nbviewer.org/github/carnotresearch/cr-sparse-companion/blob/main/modules/clustering/ssc_omp/benchmarks/ssc_omp_synthetic_data.ipynb) showcasing the SSC-OMP fully using BCOO. 


On a side note, the limitation of `lax.while_loop`, `lax.fori_loop` etc. requiring that loop-carried algorithm state must hold a fixed shape makes it difficult to implement algorithms like OMP or even simpler things like incremental Cholesky factorization.  I end up using a regular Python `for` loop but then I have to pass the number of iterations of the loop as a static argument. I guess JAX unrolls the for loop accordingly which takes a lot of JIT compilation time.  Plus, I cannot put early termination criteria inside the regular Python for loops. 

Usually, in these algorithms, the `body_fun` part of the while loop has a well-defined relationship between input and output shape. i.e. the `body_fun` part would easily satisfy current JIT rules that output shape is determined from input shape statically. However, `cond_fun` is the challenge as the number of iterations is data-dependent.  I wonder when JIT will become more gracious towards letting the output shape of a function be determined dynamically. Maybe it's not a major requirement in deep learning type applications, but I guess, it's fairly common in traditional signal processing and numerical linear algebra, convex optimization, etc..
