### ISSUE TITLE
conv_general_dilated returns array with dimension of size 0

### ISSUE THREAD

**Issue by TimSYQQX** [google/jax#8325]
When trying to compute convolution weight update

```
from jax import lax
import functools
import jax.numpy as jnp
from jax.random import PRNGKey
from jax.nn.initializers import normal

rng = PRNGKey(42)
init = functools.partial(normal(), rng)
x = init([128, 3, 224, 224])
k = init([64, 3, 3, 3])
y = lax.conv_general_dilated(lhs=x, rhs=k, window_strides=[1, 1], padding=[(0, 0), (0, 0)],  dimension_numbers=('NCHW', 'OIHW', 'NCHW'))
z = lax.conv_general_dilated(lhs=x[:, None], rhs=y[:, None], window_strides=[1, 1, 1], padding=[(0, 0), (0, 0), (0, 0)],  dimension_numbers=('NCDHW', 'OIDHW', 'NCDHW'))
z.shape # (128, 128, 0, 3, 3)
```
I could not find a way to remove this dimension.  Since squeeze can only remove dimensions of size =1. I suppose conv_general_dilated should either return the dimension size as 1 or throw an error? 
```
ValueError: cannot select an axis to squeeze out which has size not equal to one, got shape=(128, 128, 0, 3, 3) and dimensions=(2,)
```

**Comment by hawkinsp** [comment]
I'm not entirely sure what you are asking. 

If you look at the shapes of the values passed to the second convolution:
```
In [21]: x[:,None].shape
Out[21]: (128, 1, 3, 224, 224)

In [22]: y[:, None].shape
Out[22]: (128, 1, 64, 222, 222)
```
we would expect a size 0 output dimension: the input has a spatial dimension of size `3` where the corresponding window dimension is size `64`. No such windows fit, so the output has size `0` in that spatial dimension. Is that what you intended to compute?

As to removing the size-0 dimension: I'm not sure that makes sense. An array with a size-0 dimension is empty (has no elements). If you were to remove it (squeeze it away somehow), you'd be making an empty array into a non-empty array. Can you say more about what you are trying to do?

Hope that helps!

**Comment by hawkinsp** [comment]
Closing because I'm fairly sure this isn't a bug in JAX, but feel free to continue the discussion!
