### ISSUE TITLE
Feature Request: Add a way to pass non sharded tensors to pmap

### ISSUE THREAD

**Issue by chaserileyroberts** [google/jax#838]
Currently, the only want to pass a non-sharded tensor to `pmap` is to use `onp.broadcast_to`, which is a little messy. It would be a nice to have a way of specifying non-sharded tensors without falling back to original numpy.

**Comment by mattjj** [comment]
`in_axes=None` was added to `pmap` at some point, but only partially supported.

But now you can do this with `shard_map`! As @chaserileyroberts of 2024 surely already knows, but I'm just letting @chaserileyroberts of 2019 know too :)
