### ISSUE TITLE
Couldn't read CUDA version on WSL2

### ISSUE THREAD

**Issue by vuongkienthanh** [google/jax#8394]
I followed this guide https://docs.nvidia.com/cuda/wsl-user-guide/index.html to install CUDA on WSL2 and the ./BlackScholes example works fine.
I installed jax followed README:
```
pip install --upgrade pip
# Installs the wheel compatible with CUDA 11 and cuDNN 8.2 or newer.
pip install --upgrade "jax[cuda]" -f https://storage.googleapis.com/jax-releases/jax_releases.html  # Note: wheels only available on linux.
```
But when I tried the grad(tanh) example, it showed warning but return correct result:
```W external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc:44] Couldn't read CUDA driver version.```
This is my nvidia-smi inside Ubuntu-wsl:
```
Fri Oct 29 09:13:12 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.00       Driver Version: 510.06       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0    15W /  N/A |    105MiB /  4096MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

and nvcc --version:
```nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Wed_Jun__2_19:15:15_PDT_2021
Cuda compilation tools, release 11.4, V11.4.48
Build cuda_11.4.r11.4/compiler.30033411_0```

**Comment by evanphilip** [comment]
There is nothin at `/proc/driver/nvidia/version` since there is no NVIDIA driver installed on the WSL2 system, as stressed in the guide [https://docs.nvidia.com/cuda/wsl-user-guide/index.html](https://docs.nvidia.com/cuda/wsl-user-guide/index.html). NVIDIA drivers are installed on the host Windows OS, not inside WSL2. Installing Linux NVIDIA drivers inside WSL2 will break the ability to use GPU from WSL2. 

Right now, it looks like it is possible to leverage the GPU from WSL2 since the grad(tanh) example showed a warning, but returned the correct result. I think the warning exists because of the non-traditional installation with no NVIDIA drivers.

**Comment by mcleantom** [comment]
If you want to get rid of the warning (considering it is working), you can disable the warning with

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3' 
```

I'm not sure if there is a specific environment variable you can toggle in TensorFlow to only turn off that specific warning
