### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by womkim** [google/jax#84]
any docker image or Dockerfile ?

**Comment by mattjj** [comment]
We could put one together! Can you say a bit about what you would want for a Docker file, or point to a good example? (We have a [Docker file for building wheels](https://github.com/google/jax/blob/master/build/Dockerfile), but I'm guessing you want one that comes with JAX set up and ready to use, perhaps interactively.)

**Comment by womkim** [comment]
yep, that's I want  :)

**Comment by womkim** [comment]
or I will build by myself FROM the Docker file, thanks anyway

**Comment by mattjj** [comment]
Okay, I'll close the issue then.
