### ISSUE TITLE
Incorrect documentation for jax.numpy.linalg.svd

### ISSUE THREAD

**Issue by henrypinkard** [google/jax#8414]
The [documentation](https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.linalg.svd.html) shows that `jax.numpy.linalg.svd` accepts the keyword argument `hermitian`, like the numpy.linalg version. But the signature `jax.numpy.linalg.svd(a, full_matrices=True, compute_uv=True)` does not list this, and when one tries to use it an error is thrown.

**Comment by jakevdp** [comment]
Thanks for the report - documentation for numpy wrappers is automatically generated from the numpy docs. You'll see that the type signature at the top of the page shows the correct parameters, and *Original docstring below* indicates that the remainder of the documentation comes from the original numpy function. It's an imperfect solution, but prevents us from having to copy the content of all docstrings in the wrapped functions (which in terms of open source licensing requirements would be problematic).

What do you think? Is there something we could do to make that more clear?

**Comment by hawkinsp** [comment]
Implementing the `hermitian=True` case looks pretty easy, I'll have a go at that.

**Comment by henrypinkard** [comment]
That makes sense, and nothing really comes to mind for doing anything differently given the constraints you describe.

I was just reporting since my understanding was that the goal was two make the two APIs match as closely as possible.

Thanks for the quick fix @hawkinsp !
