### ISSUE TITLE
Jit not preserving dictionary key order inputs in Python 3.

### ISSUE THREAD

**Issue by alvarosg** [google/jax#8419]
The jitted counterpart of a function changes the order of the keys of a dictionary:

```
def func(input_dict):
  return jnp.concatenate(list(input_dict.values()), axis=0)
func_jitted = jax.jit(func)

input_dict = {"b": np.array([0, 1]), "a": np.array([2, 3])}
func(input_dict)  # [0, 1, 2, 3]
func_jitted(input_dict)  # [2, 3, 0, 1]
```

This is very unintuitive behavior in Python3, where dicts are assumed to be ordered. And can be a common use case when, for example, concatenating a dict of input features for a model.

I suspect the root cause is tree_map (https://github.com/google/jax/issues/4085), which behaves this way:
```
input = {"c": 0, "b": 1, "a": 2}
output = jax.tree_map(lambda x: x, input)
output # {'a': 2, 'b': 1, 'c': 0}
```

Not sure if this can be easily fixed at this point, but this probably deserves a mention in: https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html

**Comment by jakevdp** [comment]
Thanks for the report! See https://github.com/google/jax/issues/4085

This behavior of sorting keys was necessary to support Python 3.6, which was dropped relatively recently. Now that we require Python 3.7 or newer, we could fix this issue.

I'm going to close this issue and continue the discussion in #4085
