### ISSUE TITLE
two-operand cond conflicts with per-branch-operand cond

### ISSUE THREAD

**Issue by froystig** [google/jax#8469]
#8467 introduces multi-operand `lax.cond`. When given two operands, as in:

```python
def f(x):
  return lax.cond(x == 0, lax.add, lax.mul, x, y)
```

`cond` detects five total arguments and falls back to behavior that is backwards-compatible with the deprecated per-branch-operand `cond`. The latter accepts, in order: a predicate, true operand, true branch, false operand, and false branch. This results in an error:

```
TypeError: Value <function add ...> with type <class 'function'> is not a valid JAX type
```

One option is to rollback (or disallow) multi-operand cond for now, complete the deprecation of the previous cond, and roll forward (or re-enable) multi-operand cond.

**Comment by namheegordonkim** [comment]
Having the same issue here! For now, I have to strictly use single operand `cond` calls.

**Comment by mattjj** [comment]
Thanks for letting us know! #8488 will fix.
