### ISSUE TITLE
JAX leak when running on Google Colab

### ISSUE THREAD

**Issue by NTT123** [google/jax#8471]
The following code causes leaks when running on Google Colab.

Run on: Colab CPU instance.
JAX version: 0.2.21
Jaxlib version: 0.1.71

```python
import jax
import jax.numpy as jnp

def g(t):
    for i in range(100): t =  t + 1

while True:
    with jax.check_tracer_leaks(True):
        jax.eval_shape(g, 1)
```

The error traceback:

```
WARNING:absl:No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-1-23a3fa9853e6> in <module>()
      7 while True:
      8     with jax.check_tracer_leaks(True):
----> 9         jax.eval_shape(g, 1)

4 frames
/usr/local/lib/python3.7/dist-packages/jax/_src/api.py in eval_shape(fun, *args, **kwargs)
   2629   out = pe.abstract_eval_fun(wrapped_fun.call_wrapped,
   2630                              *map(shaped_abstractify, args_flat),
-> 2631                              debug_info=debug_info)
   2632   out = [ShapeDtypeStruct(x.shape, x.dtype, x.named_shape) for x in out]
   2633   return tree_unflatten(out_tree(), out)

/usr/local/lib/python3.7/dist-packages/jax/interpreters/partial_eval.py in abstract_eval_fun(fun, debug_info, *avals, **params)
    412 def abstract_eval_fun(fun, *avals, debug_info=None, **params):
    413   _, avals_out, _ = trace_to_jaxpr_dynamic(
--> 414       lu.wrap_init(fun, params), avals, debug_info)
    415   assert all(isinstance(aval, AbstractValue) for aval in avals_out)
    416   return avals_out

/usr/local/lib/python3.7/dist-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr_dynamic(***failed resolving arguments***)
   1489     main.jaxpr_stack = ()  # type: ignore
   1490     jaxpr, out_avals, consts = trace_to_subjaxpr_dynamic(fun, main, in_avals)
-> 1491     del main, fun
   1492   return jaxpr, out_avals, consts
   1493 

/usr/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    117         if type is None:
    118             try:
--> 119                 next(self.gen)
    120             except StopIteration:
    121                 return False

/usr/local/lib/python3.7/dist-packages/jax/core.py in new_main(trace_type, dynamic, **payload)
    796       leaked_tracers = maybe_find_leaked_tracers(t())
    797       if leaked_tracers:
--> 798         raise Exception(f'Leaked level {t()}. Leaked tracer(s): {leaked_tracers}.')
    799 
    800 @contextmanager

Exception: Leaked level MainTrace(1,DynamicJaxprTrace). Leaked tracer(s): [Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>, Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>, Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>, Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>, Traced<ShapedArray(int32[], weak_type=True)>with<DynamicJaxprTrace(level=1/0)>].
```

There is no leak when I run it as a python script.

```bash
$ cat leak.py
import jax
import jax.numpy as jnp

def g(t):
    for i in range(100): t =  t + 1

while True:
    with jax.check_tracer_leaks(True):
        jax.eval_shape(g, 1)
$ python3 leak.py
# No error
```

Also, when I run it as a function in a new thread, there is no leak.

```python
import jax
import jax.numpy as jnp
import threading


def f():
    def g(t):
        for i in range(100): t =  t + 1

    while True:
        with jax.check_tracer_leaks(True):
            jax.eval_shape(g, 1)

th = threading.Thread(target=f)
th.start() # no error
th.join()
```

My theory for this behavior is that Google Colab increases reference count of traced arrays when it looks into the stack for status reports (shown as call stack in the status bar of Colab).

**Comment by jakevdp** [comment]
Thanks for the concise repro! Your theory sounds plausible - I'll take a look and loop-in the Colab team if necessary.

**Comment by jakevdp** [comment]
Internal tracking: b/205274673

**Comment by jakevdp** [comment]
It sounds like the issue comes from Colab's use of [debugpy](https://github.com/microsoft/debugpy) for inspecting runtimes; as such it is likely that a similar failure could be reproduced in, e.g. VSCode in debug mode.

A workaround is to disable tracing in the main thread; if you run this, your snippet no longer errors:
```python
import threading
threading.current_thread().pydev_do_not_trace = True
```

With that in mind, the way forward is not entirely clear to me. A couple options:

1. Perhaps this could be considered an issue with `debugpy`, though I suspect if we raised the issue their answer would be along the lines of, "if grabbing of references is problematic, then don't run in debug mode".
2. Perhaps JAX could be modified to work around this, and set `pydev_do_not_trace` whenever it is checking for leaks. The downside is that it would cause debuggers to stop functioning in these blocks, which some users might see as a bug. Maybe we could add a `disable_debugger` option to  `jax.check_tracer_leaks` that could control this, or perhaps we could somehow detect when a debugger is listening and raise a more informative error.
3. Perhaps this is a rare enough that we could simply document the workaround above.

What do you think?

**Comment by NTT123** [comment]
Thank you for the workaround. It does avoid the problem in my notebooks.

I don't know enough about JAX or debugpy to have a strong opinion about these options.
However, I think most people get this error from time to time. Moreover, the bigger the model is the higher chance of getting the error (I think).

As a Colab user, who uses JAX a lot, I want an option to disable debugpy and its related features.

**Comment by jakevdp** [comment]
One imperfect solution that would address this issue on Colab: within `check_tracer_leaks` we could add something like:
```python
if not getattr(threading.current_thread(), 'pydev_do_not_trace', True):
  raise ValueError("Leak checking is broken by debuggers, set `pydev_do_not_trace = True`")
```
Or, for more convenience, we could also add a `disable_debugger` option to `check_tracer_leaks` and have the error reference that.

This would not catch cases where `pydev_do_not_trace` is not explicitly set, but in Colab in particular it is always set, so it would have prevented your issue. What do you think?

**Comment by NTT123** [comment]
> ```python
> if not getattr(threading.current_thread(), 'pydev_do_not_trace', True):
>   raise ValueError("Leak checking is broken by debuggers, set `pydev_do_not_trace = True`")
> ```

As a user, I like this error message. It tells me the cause and recommends a solution. That is good enough for me.
