### ISSUE TITLE
Colab TPU setup fails with nightly driver

### ISSUE THREAD

**Issue by luyug** [google/jax#8472]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
jax.local_devices()
```

- [x] If applicable, include full error messages/tracebacks.
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-abdb42bb8a9a> in <module>()
      3 import jax.tools.colab_tpu
      4 jax.tools.colab_tpu.setup_tpu()
----> 5 jax.local_devices()

2 frames
/usr/local/lib/python3.7/dist-packages/jax/_src/lib/xla_bridge.py in _get_backend_uncached(platform)
    246     if backend is None:
    247       if platform in _backends_errors:
--> 248         raise RuntimeError(f"Requested backend {platform}, but it failed "
    249                            f"to initialize: {_backends_errors[platform]}")
    250       raise RuntimeError(f"Unknown backend {platform}")

RuntimeError: Requested backend tpu_driver, but it failed to initialize: DEADLINE_EXCEEDED: Failed to connect to remote server at address: grpc://10.91.25.74:8470. Error from gRPC: Deadline Exceeded. Details: 
```

On the other hand, using an earlier version of driver in `setup_tpu` *does* work, e.g.,
```
def setup_tpu():
  """Sets up Colab to run on TPU.
  Note: make sure the Colab Runtime is set to Accelerator: TPU.
  """
  global TPU_DRIVER_MODE

  if not TPU_DRIVER_MODE:
    colab_tpu_addr = os.environ['COLAB_TPU_ADDR'].split(':')[0]
    url = f'http://{colab_tpu_addr}:8475/requestversion/tpu_driver0.1-dev20211030'
    requests.post(url)
    TPU_DRIVER_MODE = 1

  # The following is required to use TPU Driver as JAX's backend.
  config.FLAGS.jax_xla_backend = "tpu_driver"
  config.FLAGS.jax_backend_target = "grpc://" + os.environ['COLAB_TPU_ADDR']
```

**Comment by JonatanGk** [comment]
Any way to solve this? Have the same problem... ;(

**Comment by rog77** [comment]
I am having the same issue.

**Comment by luyug** [comment]
FYI, for people who are running into the same issue, you can try the WAR at the end of my bug report, at least for now...

**Comment by rog77** [comment]
@luyug Might you please share a barebones notebook that demonstrates the fix? I myself am so new to jax that this,  jax.local_devices(), is the very first problem I hit l. For testing I did check the TPU was visible in TF from the same runtime as the one that produced the Jax error. Thanks!

**Comment by JonatanGk** [comment]
> @luyug Might you please share a barebones notebook that demonstrates the fix? I myself am so new to jax that this, jax.local_devices(), is the very first problem that hit l. For testing I did check the TPU was visible in TF from the same runtime as the one that produced the Jax error. Thanks!

I tested too with TF as @rog77  and detects tpu :(

![error-jax-tpu](https://user-images.githubusercontent.com/29007922/140660355-34948ea4-9815-4edb-80ee-f2b209889f6e.jpeg)

**Comment by luyug** [comment]
@rog77 
replace 
```python
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
```
with 
```python
import requests
import os

from jax.config import config

TPU_DRIVER_MODE = 0


def setup_tpu():
  """Sets up Colab to run on TPU.
  Note: make sure the Colab Runtime is set to Accelerator: TPU.
  """
  global TPU_DRIVER_MODE

  if not TPU_DRIVER_MODE:
    colab_tpu_addr = os.environ['COLAB_TPU_ADDR'].split(':')[0]
    url = f'http://{colab_tpu_addr}:8475/requestversion/tpu_driver0.1-dev20211030'
    requests.post(url)
    TPU_DRIVER_MODE = 1

  # The following is required to use TPU Driver as JAX's backend.
  config.FLAGS.jax_xla_backend = "tpu_driver"
  config.FLAGS.jax_backend_target = "grpc://" + os.environ['COLAB_TPU_ADDR']

setup_tpu()
```

**Comment by rog77** [comment]
import requests
import jax
import os
import numpy as np

from jax.config import config

TPU_DRIVER_MODE = 0


def setup_tpu():
  """Sets up Colab to run on TPU.
  Note: make sure the Colab Runtime is set to Accelerator: TPU.
  """
  global TPU_DRIVER_MODE

  if not TPU_DRIVER_MODE:
    colab_tpu_addr = os.environ['COLAB_TPU_ADDR'].split(':')[0]
    url = f'http://{colab_tpu_addr}:8475/requestversion/tpu_driver0.1-dev20211030'
    requests.post(url)
    TPU_DRIVER_MODE = 1

  # The following is required to use TPU Driver as JAX's backend.
  config.FLAGS.jax_xla_backend = "tpu_driver"
  config.FLAGS.jax_backend_target = "grpc://" + os.environ['COLAB_TPU_ADDR']

setup_tpu()

jax.local_devices()

^^

This does indeed give me: 

[TpuDevice(id=0, process_index=0, coords=(0,0,0), core_on_chip=0),
 TpuDevice(id=1, process_index=0, coords=(0,0,0), core_on_chip=1),
 TpuDevice(id=2, process_index=0, coords=(1,0,0), core_on_chip=0),
 TpuDevice(id=3, process_index=0, coords=(1,0,0), core_on_chip=1),
 TpuDevice(id=4, process_index=0, coords=(0,1,0), core_on_chip=0),
 TpuDevice(id=5, process_index=0, coords=(0,1,0), core_on_chip=1),
 TpuDevice(id=6, process_index=0, coords=(1,1,0), core_on_chip=0),
 TpuDevice(id=7, process_index=0, coords=(1,1,0), core_on_chip=1)]

On Colab.

Thank you, @luyug!

**Comment by jakevdp** [comment]
#8485 adds the ability to specify the driver version in `setup_tpu()`

**Comment by JonatanGk** [comment]
@luyug on Colab works fine. Im trying in gce "Vm" and have the previous issue... some trick to setup TPUs?

**Comment by krahnikblis** [comment]
why is this closed? is the solution really to use a bootleg copy of the setup_tpu() function with a dev version of the driver from late last year? i'm still getting this same issue today, with newer versions of everything... the solution CAN'T be to simply roll back to some archaic driver version??

**Comment by jakevdp** [comment]
This is closed because the original issue was fixed. A similar issue has come up recently; it is tracked in https://github.com/googlecolab/colabtools/issues/3009 and we're working on getting it fixed.

**Comment by xaviergonzalez** [comment]
> 

When I try this, I then get the following error when I try `seed = jr.PRNGKey(1234)`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-10-1e2f3f4e5dc5>](https://localhost:8080/#) in <module>
      6 alpha0 = 10.0
      7 beta0 = 5.0
----> 8 seed = jr.PRNGKey(1234)
      9 W_fake, H_fake, Sigma_fake, X_fake = sample_from_model(seed, num_rows, num_cols, num_factors, alpha, beta, alpha0, beta0)

14 frames
[/usr/local/lib/python3.8/dist-packages/jax/_src/random.py](https://localhost:8080/#) in PRNGKey(seed)
    131     raise TypeError("PRNGKey accepts a scalar seed, but was given an array of"
    132                     f"shape {np.shape(seed)} != (). Use jax.vmap for batching")
--> 133   key = prng.seed_with_impl(impl, seed)
    134   return _return_prng_keys(True, key)
    135 

[/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py](https://localhost:8080/#) in seed_with_impl(impl, seed)
    265 # TODO(frostig): remove, rerouting callers directly to random_seed
    266 def seed_with_impl(impl: PRNGImpl, seed: int) -> PRNGKeyArray:
--> 267   return random_seed(seed, impl=impl)
    268 
    269 

[/usr/local/lib/python3.8/dist-packages/jax/_src/prng.py](https://localhost:8080/#) in random_seed(seeds, impl)
    570   # use-case of instantiating with Python hashes in X32 mode.
    571   if isinstance(seeds, int):
--> 572     seeds_arr = jnp.asarray(np.int64(seeds))
    573   else:
    574     seeds_arr = jnp.asarray(seeds)

[/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py](https://localhost:8080/#) in asarray(a, dtype, order)
   2034   lax_internal._check_user_dtype_supported(dtype, "asarray")
   2035   dtype = dtypes.canonicalize_dtype(dtype) if dtype is not None else dtype
-> 2036   return array(a, dtype=dtype, copy=False, order=order)  # type: ignore
   2037 
   2038 

[/usr/local/lib/python3.8/dist-packages/jax/_src/numpy/lax_numpy.py](https://localhost:8080/#) in array(object, dtype, copy, order, ndmin)
   2015     raise TypeError(f"Unexpected input type for array: {type(object)}")
   2016 
-> 2017   out_array: Array = lax_internal._convert_element_type(out, dtype, weak_type=weak_type)
   2018   if ndmin > ndim(out_array):
   2019     out_array = lax.expand_dims(out_array, range(ndmin - ndim(out_array)))

[/usr/local/lib/python3.8/dist-packages/jax/_src/lax/lax.py](https://localhost:8080/#) in _convert_element_type(operand, new_dtype, weak_type)
    586     return type_cast(Array, operand)
    587   else:
--> 588     return convert_element_type_p.bind(operand, new_dtype=new_dtype,
    589                                        weak_type=bool(weak_type))
    590 

[/usr/local/lib/python3.8/dist-packages/jax/core.py](https://localhost:8080/#) in bind(self, *args, **params)
    327     assert (not config.jax_enable_checks or
    328             all(isinstance(arg, Tracer) or valid_jaxtype(arg) for arg in args)), args
--> 329     return self.bind_with_trace(find_top_trace(args), args, params)
    330 
    331   def bind_with_trace(self, trace, args, params):

[/usr/local/lib/python3.8/dist-packages/jax/core.py](https://localhost:8080/#) in bind_with_trace(self, trace, args, params)
    330 
    331   def bind_with_trace(self, trace, args, params):
--> 332     out = trace.process_primitive(self, map(trace.full_raise, args), params)
    333     return map(full_lower, out) if self.multiple_results else full_lower(out)
    334 

[/usr/local/lib/python3.8/dist-packages/jax/core.py](https://localhost:8080/#) in process_primitive(self, primitive, tracers, params)
    710 
    711   def process_primitive(self, primitive, tracers, params):
--> 712     return primitive.impl(*tracers, **params)
    713 
    714   def process_call(self, primitive, f, tracers, params):

[/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in apply_primitive(prim, *args, **params)
    118   compiled_fun = xla_primitive_callable(prim, *unsafe_map(arg_spec, args),
    119                                         **params)
--> 120   return compiled_fun(*args)
    121 
    122 # TODO(phawkins,frostig,mattjj): update code referring to

[/usr/local/lib/python3.8/dist-packages/jax/_src/dispatch.py](https://localhost:8080/#) in <lambda>(*args, **kw)
    203                                     prim.name, donated_invars, False, *arg_specs)
    204   if not prim.multiple_results:
--> 205     return lambda *args, **kw: compiled(*args, **kw)[0]
    206   else:
    207     return compiled

[/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py](https://localhost:8080/#) in _execute_trivial(jaxpr, consts, in_handler, out_handler, kept_var_idx, *args)
   3636   outs = [xla.canonicalize_dtype(v.val) if type(v) is core.Literal else env[v]
   3637           for v in jaxpr.outvars]
-> 3638   return out_handler(in_handler(outs))
   3639 
   3640 

[/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py](https://localhost:8080/#) in __call__(self, out_bufs)
   1915 
   1916   def __call__(self, out_bufs):
-> 1917     return [h(bufs) for h, bufs in safe_zip(self.handlers, out_bufs)]
   1918 
   1919 

[/usr/local/lib/python3.8/dist-packages/jax/interpreters/pxla.py](https://localhost:8080/#) in <listcomp>(.0)
   1915 
   1916   def __call__(self, out_bufs):
-> 1917     return [h(bufs) for h, bufs in safe_zip(self.handlers, out_bufs)]
   1918 
   1919 

[/usr/local/lib/python3.8/dist-packages/jax/_src/array.py](https://localhost:8080/#) in <lambda>(bufs)
    676     return global_aval.dtype._rules.global_sharded_result_handler(
    677         global_aval, out_sharding, committed, is_out_sharding_from_xla)
--> 678   return lambda bufs: ArrayImpl(global_aval, out_sharding, bufs,
    679                                 committed=committed, _skip_checks=True)
    680 pxla.global_result_handlers[(core.ShapedArray, pxla.OutputType.Array)] = _array_global_result_handler

TypeError: Unsupported type for elements in `arrays`: <class 'jaxlib.tpu_client_extension.PyTpuBuffer'>
```

**Comment by jakevdp** [comment]
I would suggest not doing all of this manually, instead use
```python
import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()
```
The advice in this issue was for working around a previous bug that has since been fixed.

**Comment by ranlucienwang** [comment]
Hi, the solution 

> I would suggest not doing all of this manually, instead use
> 
> ```python
> import jax.tools.colab_tpu
> jax.tools.colab_tpu.setup_tpu()
> ```
> 
> The advice in this issue was for working around a previous bug that has since been fixed.

Unfortunately, this is not the case. I have used the same methods, and here is a [recreation of the bugs](https://colab.research.google.com/gist/rwbfd/accb54ed6f61178ccf9e25b3be306bc1/geekbang_chapter_13_part3.ipynb).

**Comment by jakevdp** [comment]
Thanks for the question!

jax 0.4 requires TPU VMs, which Colab does not provide at this time. You can still use jax 0.3.25 on Colab, which is the version that comes installed by default on Colab TPU runtimes.

If possible, I recommend trying Kaggle Notebooks (https://www.kaggle.com/code, click on "New Notebook" near the top), which does support TPU VMs and thus newer jax versions. You have to create an account and log in to get accelerator support. Once you do that, there's a new "TPU VM v3-8" accelerator option. This gives you a TPU notebook environment similar to Colab, but using the newer TPU VM architecture. This should be a less buggy, more performant, and overall better experience than the older TPU Node architecture (see [this blog post](https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms) for a brief overview of the difference).

If you do try Kaggle Notebooks, there's a known issue ([#14600](https://github.com/google/jax/issues/14600)) that causes the TPU runtime to take a while to come up, but that should only affect the first time you access the TPU in a session. Please file more issues if you run into any other problems!

Other options include applying to TRC (https://sites.research.google/trc/about/), which can provide free Cloud TPU VM credits, or trying out a Cloud TPU VM yourself (not free).

Hope this helps.
