### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by gitfan7** [google/jax#8527]
Could anyone please fix the following error when going through "/usr/local/lib/python3.7/dist-packages/haiku/_src/transform.py in check_not_jax_transformed(f)"? Thanks a lot.

"AttributeError: module 'jaxlib.xla_extension' has no attribute 'PmapFunction'"

**Comment by jakevdp** [comment]
This probably indicates that your `jaxlib` installation is too old. Try running
```
pip install -U jaxlib
```
(or, if you're on GPU, follow the GPU-specific instructions at https://github.com/google/jax#pip-installation-gpu-cuda)

**Comment by gitfan7** [comment]
Thank you for your response. But as I tried "pip install -U jaxlib", the same error occurs. So how to fix it? Thanks.

**Comment by gitfan7** [comment]
And why was there no such problem two days ago? Thanks.

**Comment by jakevdp** [comment]
Are you using python 3.6? If so, the most recent supported jaxlib version is 0.1.69. If this is the case, then I'd suggest updating to Python 3.7 to allow using newer versions of jax/jaxlib.

If you must use Python 3.6, then I would suggest downgrading `haiku` to a version that is compatible with older JAX:
```
pip install dm-haiku==0.0.4
```

**Comment by jakevdp** [comment]
The problematic line in `dm-haiku` was added 20 hours ago: https://github.com/deepmind/dm-haiku/commit/e6a13af352a8b46d355ac1b7131b64c615cfcf57

So it sounds like you're using the development branch of dm-haiku with a much older version of JAX, which is leading to this incompatibility.

**Comment by gitfan7** [comment]
> Are you using python 3.6? If so, the most recent supported jaxlib version is 0.1.69. If this is the case, then I'd suggest updating to Python 3.7 to allow using newer versions of jax/jaxlib.
> 
> If you must use Python 3.6, then I would suggest downgrading `haiku` to a version that is compatible with older JAX:
> 
> ```
> pip install dm-haiku==0.0.4
> ```
> 
> dm-haiku 0.0.5 was released on November 1st, so if your code stopped working two days ago I suspect that was due to you updating the dm-haiku package and not the JAX package.

I used Python 3.7 and have been using Python 3.7, but the error still occurs. So how to fix it? Thanks.

**Comment by gitfan7** [comment]
Here are more lines of the error:

"/usr/local/lib/python3.7/dist-packages/haiku/_src/transform.py in transform_with_state(f)
    359   """
    360   analytics.log_once("transform_with_state")
--> 361   check_not_jax_transformed(f)
    362 
    363   unexpected_tracer_hint = (

/usr/local/lib/python3.7/dist-packages/haiku/_src/transform.py in check_not_jax_transformed(f)
    306 def check_not_jax_transformed(f):
    307   # TODO(tomhennigan): Consider `CompiledFunction = type(jax.jit(lambda: 0))`.
--> 308   if isinstance(f, (jax.xla.xe.CompiledFunction, jax.xla.xe.PmapFunction)):  # pytype: disable=name-error
    309     raise ValueError("A common error with Haiku is to pass an already jit "
    310                      "(or pmap) decorated function into hk.transform (e.g. "

AttributeError: module 'jaxlib.xla_extension' has no attribute 'PmapFunction'"

Could you please fix the error? Thanks a lot.

**Comment by hawkinsp** [comment]
What version of `jaxlib` do you have installed?

**Comment by jakevdp** [comment]
Sorry, I assumed too much and should have stuck to the facts:

- the problematic line was added to haiku 20 hours ago, so you are using a development version of haiki
- the line is only problematic if you have jaxlib 0.71.0 or older
- to fix the error, you need to update jaxlib, which can usually be done with `pip install -U jaxlib` if you are on Python 3.7 or newer
- 
You could help us debug your issue by running the following:
```python
import jaxlib
print(jaxlib.__version__)
``
to tell us which version of jaxlib you have installed.

**Comment by gitfan7** [comment]
It doesn't show the error now. Thank you very much.
