### ISSUE TITLE
jax.block_until_ready() for blocking until pytrees leaves are ready

### ISSUE THREAD

**Issue by shoyer** [google/jax#8536]
It is sometimes useful (e.g., in benchmarking) to disable JAX's asynchronous dispatch: https://jax.readthedocs.io/en/latest/async_dispatch.html

The easy way to compute an array is to call `.block_until_ready()`, but this doesn't work on pytrees.

I propose adding a function `jax.block_until_ready()` for mapping block_until_ready() over the leaves of a pytree:
```python
def block_until_ready(pytree):
  return tree_util.tree_map(lambda x: x.block_until_ready(), pytree)
```
I've written versions of this helper function quite a few times and it would be nice not to have to do so again.

This version requires that all leaves are JAX arrays. Alternatively, we could skip calling `.block_until_ready()` on non-JAX arrays, which don't have the method defined. This might be more generally useful.

**Comment by apaszke** [comment]
@mattjj or perhaps we should have a typeclass for things you can block on? 😄
