### ISSUE TITLE
jax.numpy.subtract throws runtime error when one of the arrays is object type

### ISSUE THREAD

**Issue by neha-wadia** [google/jax#856]
When subtracting a traditional numpy array of dtype object whose entries are all floats from a jax.numpy array, jax.numpy.subtract throws a (somewhat inscrutable) runtime error. Subtraction works fine in numpy.

See minimal reproduction [here](https://colab.research.google.com/drive/1RsORCiwcWchwD7XiN4FsPvfx2ZjpMMac).

**Comment by mattjj** [comment]
Indeed, JAX doesn't work with object dtype arrays. Let's close this issue by documenting that somewhere.

**Comment by mattjj** [comment]
Thanks for the clear repro! I'm curious about where you find an application for object arrays.

**Comment by neha-wadia** [comment]
Cool, thank you!
This came up because I had a dataset that was in the form of a list of tuples of `numpy` arrays. Extracting training batches from the list in native `numpy` and passing them to a training loop written in JAX resulted in the error.
