### ISSUE TITLE
JAX numpy mishandles certain 32-bit floating point operations as compared with numpy

### ISSUE THREAD

**Issue by j2kun** [google/jax#8604]
**Might be related to https://github.com/google/jax/issues/8068 ? **

```python
import numpy as np
import jax.numpy as jnp

(1 / 256 ** np.arange(1, 5)).astype(np.float32)
# output:
# array([3.9062500e-03, 1.5258789e-05, 5.9604645e-08, 2.3283064e-10], dtype=float32)

(1 / 256 ** jnp.arange(1, 5)).astype(jnp.float32)
# output:
# DeviceArray([3.9062500e-03, 1.5258789e-05, 5.9604645e-08,           inf],            dtype=float32)
```

The "inf" part seems like a bug. I can represent the numbers correctly individually, as in

```
jnp.float32(1/256**4)
# output: DeviceArray(2.3283064e-10, dtype=float32)
```

It just breaks for this particular version of that same computation...

**Comment by hawkinsp** [comment]
This is integer overflow. If 64-bit types aren't enabled, you get:
```
In [3]: 256 ** jnp.arange(1, 5)
Out[3]: DeviceArray([     256,    65536, 16777216,        0], dtype=int32)
```

Try setting `JAX_ENABLE_X64=1` to enable 64-bit types. Alternatively, perform the exponentiation on floats:

```
In [6]: (1 / 256. ** jnp.arange(1, 5)).astype(jnp.float32)
Out[6]: DeviceArray([3.9062500e-03, 1.5258789e-05, 5.9604645e-08, 2.3283064e-10],            dtype=float32)
```

**Comment by hawkinsp** [comment]
Closing because I don't think this is a bug in JAX. We're already working on enabling x64 mode by default, and I think catching integer overflow would be a big project and not something we would want to enable by default even if we could do it.

**Comment by j2kun** [comment]
Sorry for the noise, in that case, and thanks for the quick assistance!
