### ISSUE TITLE
"TypeError: iteration over a 0-d array" when putting tuple of carriers to jax.lax.scan

### ISSUE THREAD

**Issue by EmperorTransisthor** [google/jax#8605]
I have got a function: 
```python
def holtExponentialSmoothingAdditiveError(params, x): # 
    s0, alpha, beta = params
    def step(s, x):
        previousLevel, previousTrend = s
        a = jax.nn.sigmoid(alpha)
        b = jax.nn.sigmoid(beta)
        trainingError = x - previousLevel - previousTrend
        levelEquasion = previousLevel + previousTrend + a*trainingError
        trendEquasion = previousTrend + b*trainingError

        return (levelEquasion, trendEquasion), previousLevel + previousTrend + trainingError
    return jax.lax.scan(step, s0, x)
```

timeSeries : [452500. 765000. 549000. 560000. 580000. 570000. 510000. 499000. 510000.
 503625. 516500. 583000. 575000. 590000. 558750. 583250. 601000. 600000.
 606000. 560000. 569000. 550000. 573750. 605000. 570000. 595000. 579000.
 603500. 610500. 612500. 600000. 615000. 640000. 630000. 633000. 675000.
 665000. 673750. 675000. 690000. 725000. 730000. 745000. 767500. 770000.
 768250. 747000. 760000. 757500. 715000. 662500.]

When I execute:

```python
alpha = 0.16
beta = 0.1
print(timeSeries)
holtTimeSeries = holtExponentialSmoothingAdditive((timeSeries[0], alpha, beta), timeSeries)
```

I receive an error:

```---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_31725/277494675.py in <module>
      2 beta = 0.1
      3 print(timeSeries)
----> 4 holtTimeSeries = holtExponentialSmoothingAdditiveError((timeSeries[0], alpha, beta), timeSeries)

/tmp/ipykernel_31725/2370628103.py in holtExponentialSmoothingAdditiveError(params, x)
     10 
     11         return (levelEquasion, trendEquasion), previousLevel + previousTrend + trainingError
---> 12     return jax.lax.scan(step, s0, x)

    [... skipping hidden 12 frame]

/tmp/ipykernel_31725/2370628103.py in step(s, x)
      2     s0, alpha, beta = params
      3     def step(s, x):
----> 4         previousLevel, previousTrend = s
      5         a = jax.nn.sigmoid(alpha)
      6         b = jax.nn.sigmoid(beta) 

    [... skipping hidden 1 frame]

~/.local/lib/python3.9/site-packages/jax/_src/lax/lax.py in _iter(tracer)
   2215 def _iter(tracer):
   2216   if tracer.ndim == 0:
-> 2217     raise TypeError("iteration over a 0-d array")  # same as numpy error
   2218   else:
   2219     n = int(tracer.shape[0])

TypeError: iteration over a 0-d array
```

It looks like ```jax.lax.scan``` doesn't like when I pass carriers as a tuple, although I don't understand, why doesn't it work. May somebody explain to me, whether it is a bug or my mistake? 
Note, that I have simpleExponentialSmoothing coded very similar to holt's exponential smoothing and it works just fine, the only difference is that I pass single value in carry instead of tuple.
TimeSeries is <class 'numpy.ndarray'> array, the same I pass to simpleExponentialSmoothing function.

**Comment by jakevdp** [comment]
It looks like you're passing a single value to `s` via `s0`, and then attempting to iterate over it using
```
previousLevel, previousTrend = s
```
Perhaps you meant for `s0` to be a tuple of two values?

**Comment by jakevdp** [comment]
For example, this executes without an error:
```python
holtExponentialSmoothingAdditiveError((0.0, timeSeries[0]), alpha, beta), timeSeries)
```

**Comment by EmperorTransisthor** [comment]
Oh my, a shame I didn't spot this. Thanks a lot :D

Btw it should not be labeled as bug, if someone can moderate.

**Comment by jakevdp** [comment]
Great, thanks!
