### ISSUE TITLE
Segfault when performing convolutions on tensors with large batch dims

### ISSUE THREAD

**Issue by Matematija** [google/jax#8632]
Dear Jax team,

Thank you for a great package.

I am using Jax for quantum physics problem which involves 2 stages: Monte Carlo sampling + backprop gradient calculation. I get a segfault when evaluating a model with `jax.lax.conv_general_dilated` on a large tensor of (batched) MCMC samples. Here is a complete MWE:

```python
from functools import partial

import jax

from jax import jit, vmap
from jax import lax
from jax import numpy as jnp
from jax import random

def model(params, x):

    conv_kernel_1, conv_kernel_2, dense_kernel = params

    x = jnp.atleast_3d(x)[None,:,:,:]

    h = lax.conv_general_dilated(x, conv_kernel_1, (1,1), dimension_numbers=('NHWC', 'HWIO', 'NHWC'), padding='valid')
    h = jax.nn.relu(h)
    h = lax.conv_general_dilated(h, conv_kernel_2, (1,1), dimension_numbers=('NHWC', 'HWIO', 'NHWC'), padding='valid')
    h = jax.nn.relu(h)
    h = dense_kernel @ (h.ravel())

    return -h**2

@partial(vmap, in_axes=(None, None, 0, 0))
def get_samples(params, n_samples, inits, key): # This would be a Markov Chain Monte Carlo sampler in practice
    return random.normal(key, shape=(n_samples, *inits.shape))

def make_inference_kernel(n_samples):

    grad_fn = jax.vmap(jax.grad(model, argnums=0), in_axes=(None, 0))

    @jit
    def inference_kernel(params, inits, key):

        keys = random.split(key, inits.shape[0])
        samples = get_samples(params, n_samples, inits, keys)

        samples = samples.reshape(-1,20,20)

        grads = grad_fn(params, samples)

        return grads

    return inference_kernel

##########################################################

key = jax.random.PRNGKey(0)

dims = (20, 20)

key, *keys = jax.random.split(key, 4)
shapes = [(7,7,1,4), (7,7,4,8), (512,)]

params = tuple(random.normal(k, s) for k, s in zip(keys, shapes))

kernel = make_inference_kernel(n_samples=8000, warmup=2000)

for i in range(10):

    key, key_ = jax.random.split(key, 2)
    inits = random.normal(key, (6,20,20))
    grads = kernel(params, inits, key_)

    ## Do something clever with the gradients here
```

Shell output:
```bash
Segmentation fault (core dumped)
```

I know it's quite a bit of code to go through so let me briefly break it down into essential steps:
1. Define a convolutional model with parameters.
2. Use a MCMC scheme to get samples from it. Here I use `jax.random.normal` as a stand-in.
3. Calculate model gradients by averaging over collected samples.

A couple of observations:
* The issue happens on both GPU and CPU.
* It seems to be related to memory - when I reduce the number of samples, it goes away but the calculation is extremely slow compared to a dense model with roughly as many parameters (may be related to https://github.com/google/jax/issues/5227 ). Dense layers work great.
* I have tried to implement my own 2D convolutional layer (bypassing `lax.conv_general_dilated`) just to see what happens. I get the same segfault. 

Environment:

```bash
>> pip3 list | grep jax
jax                 0.2.25
jaxlib              0.1.74

>> cat /etc/os-release
NAME="Pop!_OS"
VERSION="21.04"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 21.04"
VERSION_ID="21.04"
(...)
```

**Comment by hawkinsp** [comment]
The crash is a symptom of running out of memory because XLA is attempting to allocate several terabytes of memory for an intermediate array. Without digging into the details, I want to double check: do you really want `jax.vmap(jax.grad(model, argnums=0), in_axes=(None, 0))`, which corresponds to per-example gradients? If it were something like of `grad(vmap(...))` you most likely would not have this issue.

I will keep looking into this, but I'm wondering if it's actually intentional.

**Comment by Matematija** [comment]
Yes, I am pretty sure that's what I want to do. My code for this research project was largely inspired by [NetKet](https://github.com/netket/netket), a library that does a very similar type of calculation using per-sample gradients in Jax (+ Flax for elegant model definitions). They have also had problems with convolutional models from what I hear informally.

Also - If it's memory-related then why is it okay to use dense layers?

Some more background (sorry if TMI):

Mathematically - I need gradients of expectation values of certain functions over extremely high-dimensional spaces. The only way to do that is to get Monte Carlo samples to evaluate related integrals and using the reparametrization trick for gradient calculations because otherwise Jax would try to backprop through random number generation which is a no-no. (That's why `grad(vmap(...))` wouldn't be appropriate.) Perhaps there is a more clever way of translating this calculation to Jax?

**Comment by Matematija** [comment]
Awesome, thank you! Looking forward to test it out. When should I (rougly) expect the fix to make its way to jaxlib?

**Comment by hawkinsp** [comment]
This has been in jaxlib (and therefore fixed) for a while! Closing...
