### ISSUE TITLE
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd

### ISSUE THREAD

**Issue by b-hahn** [google/jax#8644]
I'm building JAX from source on a Macbook Pro M1. The compilation finishes but after installing the wheel in a virtualenv I get a RuntimeError when trying to import JAX along with an ImportError:

```
RuntimeError: module compiled against API version 0xe but this version of numpy is 0xd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ben/devel/jax/jax/__init__.py", line 37, in <module>
    from . import config as _config_module
  File "/Users/ben/devel/jax/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/Users/ben/devel/jax/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/Users/ben/devel/jax/jax/_src/lib/__init__.py", line 75, in <module>
    import jaxlib.lapack as lapack
  File "/Users/ben/.pyenv/versions/run_jax_1/lib/python3.9/site-packages/jaxlib/lapack.py", line 21, in <module>
    from . import _lapack
ImportError: ImportError: numpy.core.multiarray failed to import
```

I've built JAX in a virtualenv (python 3.97) with numpy==1.19.5 since that's required by tensorflow_macos. The bazel version is 4.10, installed via homebrew. Bazel also prints that the numpy version is 1.19.5 so I assume that's what's being used.

Is this version of numpy just fundamentally not compatible with the head of JAX (despite the minimum version mentioned in setup.py being 1.18.0)? Or do I have to specify the numpy version somewhere else as well? Thanks for any pointers!

**Comment by hawkinsp** [comment]
I think this means that you have built your `jaxlib` against NumPy 1.20. Version `0xe` is 1.20:
https://github.com/numpy/numpy/blob/f8e87f8d5892dd5fe11ddd05470ae83a0104d417/numpy/core/setup_common.py#L44

Please double-check that you built jaxlib against a NumPy version that is at least as old as the version you wish to use it with.

By the way, we do have (lightly tested) Mac ARM jaxlib wheels available, which you should be able to install with:
```
pip install jaxlib -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

We don't yet release the wheels to pypi because we have no CI testing for them.


Feel free to reopen this issue if the suggestions above don't work for you.

**Comment by b-hahn** [comment]
Thanks for the quick reply! Do you know where I can define what version of numpy should be used? I was assuming it would use whatever is in the path. Since Bazel prints the following I assumed it was using 1.19.5 to build jaxlib:

```
Bazel binary path: /opt/homebrew/bin/bazel
Bazel version: 4.1.0
Python binary path: /Users/ben/.pyenv/versions/build_jax/bin/python
Python version: 3.9
NumPy version: 1.19.5
MKL-DNN enabled: yes
Target CPU: arm64
Target CPU features: release
CUDA enabled: no
TPU enabled: no
ROCm enabled: no
```

I've also seen the wheels for ARM but unfortunately I think they are all built against a newer numpy version as well so I get the same error. The only reason I'd need to use 1.19.5 is tensorflow_macos' requirement, and unfortunately there's no way to build it yourself.
