### ISSUE TITLE
jvp of np.sum fails in shape assertion when jit'ed

### ISSUE THREAD

**Issue by lumip** [google/jax#871]
The following piece of code, which computes the jvp of the `(reduce_)sum` operation, fails with `AssertionError: (3, 2, 2) != (3,)` when the sum is jit'ed. It computes without problems and gives the expected result when the `sum` operation is not jit'ed. The assertion is thrown from the `_reduce_sum_shape_rule` (lax.py, line 3017) which appears to be only called during actual evaluation of the `f_jvp` function when jit'ed.

``` import jax
import jax.numpy as np

T = np.array([[1., 2.], [3., 4.], [5., 6.]])
x = np.array([1, 2, 3])

mysum = jax.jit(np.sum)

# this doesn't work when jit'ed
y, f_jvp = jax.linearize(mysum, x)
Z = f_jvp(T)

# this doesn't work either when jit'ed
# y, Z = jax.jvp(mysum, (x, ), (T, ))

print(y)
print(Z)
```

Unfortunately, I haven't been able to work out a fix for this on my own so far due to the many layers of abstraction and indirections in between and would be grateful if someone could push me the right way on this.

**Comment by mattjj** [comment]
Thanks for raising this!

Actually, `x` and `T` should have the same shape here: in general, tangent vectors need to have the same shape as the corresponding input (primal) values. However, we're not raising this error in a good way, and it's leading to behavior that's only being caught way downstream.

**Comment by lumip** [comment]
That was swift, thanks!
Although I'd have liked to see it fixed the other way round. Having the opportunity to feed in a tangent matrix with larger secondary axes than the primal would be helpful for me. Any chance that could be possible?
