### ISSUE TITLE
Older jaxlib releases no longer available

### ISSUE THREAD

**Issue by lumip** [google/jax#8786]
I was revisiting some software we wrote roughly a year or so ago, tried to install the dependencies and got an error
`Could not find a version that satisfies the requirement jaxlib<0.1.57,>=0.1.48`.
Looking at pypi, it seems that all releases of jaxlib prior to 0.1.60 have been removed without a trace.

Since newer releases are not backwards compatible, I cannot simply upgrade, leaving me in a bit of a pickle. Could you consider making the older releases available again, please?

**Comment by tomhennigan** [comment]
Please see https://github.com/google/jax/issues/8640#issuecomment-975030663 for more details.

tl;dr - you need to install these from our GCS bucket not PyPi:

```
pip install jax==VERSION -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

**Comment by lumip** [comment]
Thanks for the pointer, I've actually been trying that just now. However, it seems that the binaries from the GCS require GLIBC version 2.23 which is not available on our systems (and I cannot currently make it so). This was not a problem with the one from pypi.

(Apart from that, I find the "you cannot use the standard way, please deal with this special way of doing things" a somewhat disappointing reply. Over the last year I sometimes got the feeling that the jax project is actively trying not to be maintainable as a dependency..)

**Comment by jakevdp** [comment]
Hi - sorry you feel that way. We definitely would have preferred to keep older releases available via PyPI, but we had to start removing them once PyPI rejected our uploads of newer releases due to hitting storage caps.

Would you be willing to tell us about other points of friction that make it seem as if the team is actively trying to be unmaintainable as a dependency? Perhaps there's something we can do differently to make things easier.

**Comment by jakevdp** [comment]
Regarding the GLIBC version issue - that's strange to hear, because the wheels in the GCS bucket are identical to the wheels that had been uploaded to PyPI. Perhaps @yashk2810 would have ideas about why this is happening?

**Comment by hawkinsp** [comment]
On a specific note, the binaries on GCS should be identical to what was on Pypi. The GLIBC version is actually a requirement of the `manylinux2010` specification, so if you found a wheel that requires GLIBC 2.23 then it was not a compliant wheel. Which wheel were you using? We have a test that verifies manylinux2010 compatibility as part of our build process, so perhaps it isn't working for some reason. Or perhaps it was broken at some historical revision.

**Comment by hawkinsp** [comment]
On the more general question of backward compatibility, I'm wondering if we could change how we make releases to make it easier for users of JAX. For example, one idea is that we could start using semantic versioning. Another idea is that we could start making releases on a timed schedule (e.g., weekly or monthly), and maintain compatibility for a certain time horizon.  Your input would be welcome! However, we don't want to lose the ability to make breaking changes to JAX: there are still API mistakes we need to fix.

**Comment by lumip** [comment]
Hi, thanks for the responses so far. Before going responding to your points, let me first counteract some of the negative vibes I brought in earlier and thank you all for the effort of developing JAX, which is an awesome project as such - it's just that the release policy is keeping me quite busy at the moment.

As it is currently, whenever a new version of JAX is released, it's a gamble whether our package still works or not, so I spent quite some time this year adopting version ranges in our depending packages. Semantic versioning would help a lot with that (and version numbers are free, after all). If you don't want to touch the major version number yet, at least having breaking changes increase the minor one would already be a good indicator. Compatibility for a certain time would of course be nice, but that depends on how much effort you're willing to spend on that without slowing down new features too much - I'd be happy with semantic version numbers.

As for the GLIBC issue, I just checked again and that seems to be a problem with the particular version I got, others seem to work fine indeed. The wheel in question is `https://storage.googleapis.com/jax-releases/cuda111/jaxlib-0.1.56%2Bcuda111-cp37-none-manylinux2010_x86_64.whl`
which pip picked for install for command
`pip install 'jaxlib >= 0.1.48, <0.1.57' 'jax >= 0.1.70, <0.1.77' -f https://storage.googleapis.com/jax-releases/jax_releases.html`

**Comment by jakevdp** [comment]
Regarding semantic versioning: I'm not sure how helpful it would be. JAX is still a relatively new package, and is evolving fast enough that essentially every change would be arguably a breaking change in a semantic versioning sense. So if we were following that we'd be incrementing the major version with virtually every release. I'm not sure that naming our releases `XX.0.0` or `0.XX.0` instead of `0.1.XX` would in practice be all that helpful in terms of the challenges you mention.

**Comment by skye** [comment]
>The wheel in question is https://storage.googleapis.com/jax-releases/cuda111/jaxlib-0.1.56%2Bcuda111-cp37-none-manylinux2010_x86_64.whl

pip is picking a GPU-enabled jaxlib from the GCS bucket (`jaxlib-0.1.56+cuda111`), so this isn't the same binary originally uploaded to pypi. This is still supposedly `manylinux2010` compliant, so there may have been or still be a bug as @hawkinsp says above, but I bet installing the non-cuda version will fix for now.

I'm not sure the best way to do that though... `pip install jaxlib===0.1.56` works, but it looks like you're trying to specify a version range. The last time I dug into how pip treats local version identifiers (e.g. `+cuda111`), I concluded that it prefers a version with a local version ID and there's no way to change this behavior :disappointed: I wonder if we should create a separate non-GPU package index, so you could specify something like `-f .../jax_pypi_releases.html` and pip will only see the pypi-released wheels.
