### ISSUE TITLE
Cuda Version：Does CUDA 10.2 support Jax?

### ISSUE THREAD

**Issue by kdpan** [google/jax#8854]
Does CUDA 10.2 support Jax?

**Comment by apaszke** [comment]
Yes, we do currently host prebuilt wheels for CUDA 10.2, with the extra requirement of cuDNN7 (as stated in the README). You should be able to install it using the following command:
```
pip install jax jaxlib==0.1.71+cuda102 -f https://storage.googleapis.com/jax-releases/jax_releases.html
```

**Comment by hawkinsp** [comment]
Actually that's out of date. We've dropped support for all CUDA versions less than 11.1.

You can most likely build jaxlib yourself from source for an earlier CUDA version, but please note that all versions prior to 11.1 have known bugs (on NVidia's side, in `ptxas`) which we cannot work around. So I recommend upgrading your CUDA installation!
