### ISSUE TITLE
Context manager to control placement of jax arrays

### ISSUE THREAD

**Issue by jatentaki** [google/jax#8879]
I'm writing a model in jax/flax and I use pytorch `utils.data.DataLoader` for multiprocessed data loading. The dataset functions however do not use pytorch tensors but numpy and jax, because some of the code I use for my model is also relevant for data preprocessing (various 3d geometry routines). This works with just CPU but when I run it on a GPU server I run into

```
2021-12-09 14:23:32.808066: F external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:153] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error
```

which I believe to be because of spawning multiple CUDA-using processes. If I duplicate the geometry-related functions to use `np` instead of `jnp`, everything works fine. Ideally, I would like to have a way to instruct jax to execute all instructions in some context on CPU and avoid the code duplication. I envision it as something like

```python
class Dataset:
   ...
   def _getitem_impl(self, index):
      # uses np and jnp code intermixed
      return data_item

   def __getitem__(self, index):
      with jax.default_device_placement('cpu'):
         return self._getitem_impl(index)
```

I saw that there are other issues asking about similar features, however in my case `jax.device_put` won't really cut it because of the intermixing of jax and numpy code, which would force me to add `device_put` at every API boundary. It is also not something that can be solved with global flags because I still want the model in the main process to run on GPU. Would it be difficult to add such a feature?

**Comment by mattjj** [comment]
@skye did https://github.com/google/jax/pull/9118 fix this?

**Comment by skye** [comment]
Yes, I believe using `jax.default_device(jax.devices("cpu")[0])` should do what you want! Give it a try?

**Comment by mattjj** [comment]
Let's consider this solved! [Docstring here](https://jax.readthedocs.io/en/latest/_autosummary/jax.default_device.html).
