### ISSUE TITLE
Unable to create array on CPU when using GPU backend

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#8933]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
import jax
import jax.numpy as np

device_cpu = jax.devices('cpu')[0]
arr = np.array([0, 1, 2, 3, 4, 5], dtype=np.uint8, device=device_cpu)
print(arr.device_buffer.device())  # prints gpu:0, expected cpu
```

- [x] If applicable, include full error messages/tracebacks.

N/A

**Comment by jakevdp** [comment]
Sorry about this - the `device` argument was unintentinally added to this function, and has no effect. #8938 removes it.

If you want to create an array on a particular device, you can use `jax.device_put`. For example:
```python
import jax 
import jax.numpy as np 

device_cpu = jax.devices('cpu')[0]
arr1 = np.arange(4)
arr2 = jax.device_put(arr1, device=device_cpu) 
print(arr1.device_buffer.device())
# gpu:0
print(arr2.device_buffer.device())
# TFRT_CPU_0
```

**Comment by ayaka14732** [comment]
Thanks for the fix! However, if I am creating a very large array, this approach will not work, since I have to create the array on GPU first, while GPU is not capable of holding it.

**Comment by jakevdp** [comment]
How are you creating the array? Is it an `arange` as in your question?

**Comment by ayaka14732** [comment]
I am trying to write deep learning programs in jax. Previously in PyTorch, I can load the whole dataset (which is very large) to memory first, then send a small subset to GPU for every batch.

**Comment by jakevdp** [comment]
OK, I'm having trouble figuring out how to give actionable advice based on that information. If you have a specific question, I'd love to try and get you an answer.

**Comment by ayaka14732** [comment]
For example,

In numpy:

```python
import numpy as np
import numpy.random as random

batch_size = 2

a = random.uniform(size=(batch_size, 10000, 100000))
b = random.uniform(size=(100000, 10000))

c = np.dot(a, b)
print(c.shape)  # output: (2, 10000, 10000)
```

However, in jax, if using TPU backend (the same applies for GPU), this is not possible:

```python
import jax
import jax.numpy as np
import jax.random as random

batch_size = 2

key = random.PRNGKey(42)

key, *subkey = random.split(key, num=3)
a = random.uniform(subkey[0], shape=(batch_size, 10000, 100000))
b = random.uniform(subkey[1], shape=(100000, 10000))

c = np.dot(a, b)
print(c.shape)
```

because

```
RuntimeError: RESOURCE_EXHAUSTED: Attempting to reserve 14.92G at the bottom of memory. That was not possible. There are 8.02G free, 0B reserved, and 8.02G reservable
```

So I would like to allocate the array directly on CPU, and send a smaller batch to TPU/GPU each time.

**Comment by jakevdp** [comment]
Your Numpy array is allocated on CPU, and you can send pieces of it to TPU/GPU by passing them to `device_put`. Is there a reason that isn't suitable for you?

Also, it sounds like you'd be interested in ongoing work on more fine-grained control of the default device: https://github.com/google/jax/issues/8879
