### ISSUE TITLE
SDA buffers fail isinstance(buf, jnp.ndarray)

### ISSUE THREAD

**Issue by jakevdp** [google/jax#8950]
I'm not sure if this is intended, but I found it surprising:
```python
import jax
import jax.numpy as jnp
sda = jax.pmap(lambda x: x)(jnp.ones((jax.device_count(), 2)))
buf = sda.device_buffers[-1]

print(isinstance(buf, jnp.ndarray))
# False
```

**Comment by mattjj** [comment]
IIUC `device_buffers` is an internal attribute, so this might be WAI, in that maybe users shouldn't ever get their hands on the value of an expression like `sda.device_buffers[-1]`.

**Comment by jakevdp** [comment]
Probably related to the issue we discussed a couple months ago: https://github.com/google/jax/pull/8129

**Comment by hawkinsp** [comment]
The reason is that the device buffers in an SDA have a `.aval` attribute that return `None`, and we have a slightly strange case in the instancecheck code that this fails: https://github.com/google/jax/blob/d6223cd4f843accc4cf9fddf1f5f49aec87c8a2f/jax/_src/numpy/lax_numpy.py#L110

But I'm keen that `.device_buffers` isn't considered a user-facing API, and perhaps we should rename it to make that clearer.

**Comment by mattjj** [comment]
Golf: that check could be faster as `isinstance(getattr(instance, 'aval', None), UnshapedArray)`.

**Comment by mattjj** [comment]
(Also, while there can be traced values that aren't arrays, I don't think users will ever get their hands on one. And maybe we can remove units soon...)

**Comment by hawkinsp** [comment]
I'm wondering if we should be expressing the instancecheck that way at all. It's very strange that an instancecheck looks at an element of the class. Maybe we should be expressing this via a subclass of `Tracer`, e.g., `ArrayTracer`?

**Comment by mattjj** [comment]
Well, it's nice that none of the Tracer machinery is array-specific. Only avals are. That is, each transformation has a Tracer, and each data type has an aval, and we get the full cross product of them.

**Comment by mattjj** [comment]
Should we close this as WAI? Or rename it to be about making `device_buffers` start with an underscore, and/or something about changing how `isinstance(..., jnp.ndarray)` works?

**Comment by mattjj** [comment]
I think we should close this as WAI, though we could open a separate issue about renaming `device_buffers` to start with an underscore or something. Reopen if you disagree!
