### ISSUE TITLE
Please consider implementing scipy.stats.gaussian_kde

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#8954]
Would it be possible to add [`scipy.stats.gaussian_kde`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) to Jax?  I use this function to generate plots, but it's very slow.  If I could apply Jax's awesome jit to it, it could run much faster.

Looking at the code https://github.com/scipy/scipy/blob/master/scipy/stats/_kde.py and https://github.com/scipy/scipy/blob/master/scipy/stats/_stats.pyx#L693, it doesn't seem too crazy as most of the peripheral functions are already in Jax.

**Comment by jakevdp** [comment]
It would definitely be possible. The tricky part of making it efficient in JAX would be to figure out how to take advantage of XLA operations for the convolution-like step (the doubly-nested for-loop in the Cython implementation).

**Comment by NeilGirdhar** [comment]
@jakevdp Yup, I was looking at that and thinking I don't know how to make that efficient in Jax :smile:

**Comment by Edenhofer** [comment]
I implemented one possible approach namely mapping over the elements of the input array (using `vmap`). Maybe this is sufficient if one also implements a simple heuristic to switch to mapping over the datapoints c.f. with [SciPy's `gaussian_kde.logpdf`](https://github.com/scipy/scipy/blob/25b3166c62909bb9d220665c43f960dd11d74967/scipy/stats/_kde.py#L603-L620). Here is a link to my implementation in case it should be of interest https://gist.github.com/Edenhofer/0f4947e4bf02cb2bcb3af7204ed2e626 . With these helper functions it should be trivial to implement SciPy's API. If there is general interest in tidying this up in a merge request, I would also have some tests lying around which I am happy to share as well. Compared to SciPy it should be pretty fast and most importantly for me it is differentiable.

P.S. Feel free to use the code with whatever license you want.
