### ISSUE TITLE
Revert #4867

### ISSUE THREAD

**Issue by donno2048** [google/jax#8980]
Please:
Revert #4867 because it messes up TensorFlow, for example (ignore the fact the code is useless):
```py
>>> from jax.numpy import array
>>> from tensorflow.keras import Sequential
>>> Sequential().predict(array([0]))
[...]
TypeError: Using a non-tuple sequence for multidimensional indexing is not allowed; use `arr[array(seq)]` instead of `arr[seq]`. See https://github.com/google/jax/issues/4564 for more information.
[...]
```
But if you run it with NumPy:
```py
>>> from numpy import array
>>> from tensorflow.keras import Sequential
>>> Sequential().predict(array([0]))
array([0])
```
- [x] Check for duplicate requests.
- [x] Describe your goal, and if possible provide a code snippet with a motivating example.

**Comment by donno2048** [comment]
Might be temporary (tensorflow/tensorflow#53458)

**Comment by jakevdp** [comment]
Hi, thanks for the report. I'd hesitate to roll-back #4867, as it's been part of JAX's public API going back over a year, and as you note in the tensorflow issue, the behavior is deprecated in NumPy as well, so if we revert the change eventually we'll want to re-land it.

I'd like to understand this issue more: should we expect all Keras functionality to work properly on raw JAX inputs? My information may be out of date, but I was under the impression that JAX is not directly compatible with Keras, and to use it you have to convert the JAX arrays to tensorflow arrays. Is that not the case?

If Keras is meant to operate on JAX arrays directly, then I think it's up to the keras library to only use supported operations. What do you think?

**Comment by donno2048** [comment]
I think the keras library is supposed to support that kind of array as there are basically NumPy arrays that are supported by the library (https://keras.io/getting_started/intro_to_keras_for_engineers in _Data loading_ section), that is why I think they should update their package (and why I filed the issue on TensorFlow), but until it'll be resolved JAX is unusable with keras...

**Comment by jakevdp** [comment]
The page you link to doesn't mention JAX, and is pretty explicit on this question:

> - Prepare your data before training a model (by turning it into either NumPy arrays or `tf.data.Dataset` objects).

It sounds like the best fix here would be to follow that advice and convert your inputs into a supported format.

**Comment by donno2048** [comment]
OK, thanks!
