### ISSUE TITLE
np.exp outputs negative numbers on cpu

### ISSUE THREAD

**Issue by matthewdhoffman** [google/jax#900]
`np.exp(-100)` goes beyond underflow and actually returns a negative number:
`DeviceArray(-7.6712354e-35, dtype=float32)`,
This can cause `nan`s where even a careful programmer would only have expected to have to worry about `inf`s.

From talking to @mattjj I suspect this is an avx512 issue or something similarly deep in the stack.

**Comment by jlebar** [comment]
We may have fixed this recently in 2fbfe77e623f0c5ee1c25a502f40e2cc1254da18.  Not sure when jaxlib will be updated, but try it and lmk?

**Comment by hawkinsp** [comment]
Yes, this appears fixed at XLA head:

```
In [3]: np.exp(-100)
Out[3]: DeviceArray(3.783505853677006e-44, dtype=float32)
```

**Comment by hawkinsp** [comment]
And we've actually already updated our TensorFlow reference to include the fix. So all this needs is a rebuild; you can build from source or wait for us to make a Jaxlib release.

Hope that helps!

**Comment by matthewdhoffman** [comment]
Great, thanks!
