### ISSUE TITLE
Device kernel image is invalid on nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04

### ISSUE THREAD

**Issue by mattiasmar** [google/jax#9003]
Originally reported in Flax' github: [https://github.com/google/flax/issues/1731](https://github.com/google/flax/issues/1731) 

**Steps to reproduce:**
Run command:
`python3  examples/imagenet/models_test.py`  
Source code: [models_test.py](https://github.com/google/flax/issues/examples/imagenet/models_test.py)

Tested with docker image: `nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04` including the following installations:
```
ENV PYTHON_VERSION=cp38 \
    CUDA_VERSION=cuda11 \
    PLATFORM=linux_x86_64 \
    BASE_URL='https://storage.googleapis.com/jax-releases'

RUN set -ex; \
    pip install -U $BASE_URL/cuda11/jaxlib-0.1.75+cuda11.cudnn82-cp38-none-manylinux2010_x86_64.whl; \
    pip install -U jax \ 
    pip install --upgrade -q git+https://github.com/google/flax.git \
    pip install torchvision \
    pip install jupyter clu ml-collections 
     
RUN pip install dm-tree dm-sonnet tensorflow tensorflow_datasets ipywidgets matplotlib dm-haiku
RUN pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio===0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
```

- Error message:
```
RuntimeError: UNKNOWN: device kernel image is invalid
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(69): 'cuLinkComplete(link_state, &cubin_out, &cubin_size)'
```

Full log trace here: [https://github.com/google/flax/issues/1731](https://github.com/google/flax/issues/1731)

**Comment by mattjj** [comment]
Thanks for the report!

@yashk2810 can you take a look?

**Comment by mattiasmar** [comment]
Hi! FYI: I tested right now with the latest nvidia docker image: `nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04` and I got the same error as before. The node on the k8s cluster where I run this image has the NVidia Driver Version 495.44  installed (CUDA Version: 11.5).

**Comment by mattiasmar** [comment]
I initialized the compilation of the jaxlib on the `nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04`. Will rerun the test once I see the compilation has completed.

**Comment by mattiasmar** [comment]
I can confirm that the master branch (sha commit: 52cf360e4add14f7001467cfd0cde3d3e2fb31e6) built on `nvidia/cuda:11.4.2-cudnn8-devel-ubuntu20.04` also fails with [models_test.py](https://github.com/google/flax/issues/examples/imagenet/models_test.py) on a pod assigned with 40 CPU cores, 80Gi RAM and 8 GPU's (NVIDIA GeForce GTX TITAN X).

 ```
File "/jax/jax/_src/prng.py", line 185, in _fold_in
    return PRNGKeyArray(self.impl, self.impl.fold_in(self._keys, data))
  File "/jax/jax/_src/prng.py", line 448, in threefry_fold_in
    return _threefry_fold_in(key, jnp.uint32(data))
RuntimeError: UNKNOWN: device kernel image is invalid
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(69): 'cuLinkComplete(link_state, &cubin_out, &cubin_size)'

```

**Comment by hawkinsp** [comment]
Having not seen this myself, if I had to guess, I would have guessed that the Nvidia kernel driver version is too old (probably less than 470). But you said above the kernel driver version is 495.44. Can you double check that? What does `nvidia-smi` print?

**Comment by mattiasmar** [comment]
![image](https://user-images.githubusercontent.com/48177580/146811310-5c6ab115-7e0a-484f-be3b-df8539d297bc.png)

**Comment by mattiasmar** [comment]
This is what nvidia-smi shows me (From inside the docker running on k8s).

**Comment by mattiasmar** [comment]
I tested all of the above with the same docker image outside of k8s on a machine with 4 Quadro RTX 8000 GPU's,  with driver Version: 470.63.01 and   CUDA Version: 11.4. Got the same error as previously.

**Comment by mattiasmar** [comment]
@hawkinsp or @yashk2810  is there a ready docker image with Jax installed that one can pull that has been tested successfully on a GPU host? 

I experimented with the docker [rappdw/docker-jax](https://hub.docker.com/r/rappdw/docker-jax). The original version of this docker image resulted in incompatible jax and jaxlib versions (jaxlib version too old jax complained). To accommodate I adjusted the dockerfile until it matched the configuration expressed in the wheel `cuda11/jaxlib-0.1.74+cuda11.cudnn82-cp38-none-manylinux2010_x86_64.whl` from the official [jax-releases](https://storage.googleapis.com/jax-releases/) which was the oldest jaxlib version that jax said it required. The net result was a docker image very similar to my original docker image, and likely because of that, the error message that I got from the running the same test as above remained the same.

**Comment by mattiasmar** [comment]
@yashk2810 Any ideas on how to further debug this?

**Comment by mattiasmar** [comment]
@mattjj an update: 
When setting `XLA_FLAGS=--xla_gpu_force_compilation_parallelism=1` the flax script (models_test.py of flax/examples/imagenet) does complete with a success indicator.

**Comment by hawkinsp** [comment]
This should be fixed in the next jaxlib release. We will automatically fall back to non-parallel compilation if your driver is too old.
