### ISSUE TITLE
Sparse matrix vector multiplication speed up

### ISSUE THREAD

**Issue by yunweilu** [google/jax#9013]
I do a little experiment to test the performance of sparse matrix-vector multiplication in JAX and compare it with the one in Scipy.
I use csr format and I find jax is about five times slower than Scipy. If the reason is Jax does matvec in python but scipy does matvec in c?

**Comment by jakevdp** [comment]
Yes, we have not yet put much focus on performance for the experimental sparse operations. Our work until now has been focused on developing the right API for interaction between sparse data structures and JAX transforms. That said, on GPU we’ve done some optimization work, particularly in lowering some operations to cuSparse, and more such lowerings are actively being developed. Additionally, we’re starting to work on lowering JAX operations to the MLIR sparse compiler, which has a lot of promise for making *sequences* of sparse operations execute extremely efficiently. So if you’re interested in optimized sparse computation, keep watching this space!
