### ISSUE TITLE
'jaxlib.tpu_client_extension.TpuClient' object has no attribute 'heap_profile'

### ISSUE THREAD

**Issue by sholtodouglas** [google/jax#9038]
If I try to run the memory profiling code on a TPU, it runs into an error - 'no attribute heap_profile'. Would love some guidance - keen to be able to drill into memory usage per device! Works great on CPU/GPU though.

Code to reproduce (e.g., in a TPU colab)
```python

import jax.tools.colab_tpu
jax.tools.colab_tpu.setup_tpu()


!add-apt-repository ppa:longsleep/golang-backports -y
!apt update
!apt install golang-go
%env GOPATH=/root/go
!apt-get install graphviz gv
!go install github.com/google/pprof@latest

import jax
import jax.numpy as jnp
import jax.profiler

def func1(x):
  return jnp.tile(x, 10) * 0.5

def func2(x):
  y = func1(x)
  return y, jnp.tile(x, 10) + 1

x = jax.random.normal(jax.random.PRNGKey(42), (1000, 1000))
y, z = func2(x)

z.block_until_ready()

jax.profiler.save_device_memory_profile("memory.prof")

!go tool pprof -png memory.prof
```

**Comment by skye** [comment]
Hi @sholtodouglas. The Colab TPU runtime is still on an older TPU system architecture (see https://cloud.google.com/blog/products/compute/introducing-cloud-tpu-vms for a brief overview of the new TPU VM architecture), so doesn't support many features that CPU, GPU, and TPU VMs have. We'll need to wait for Colab to upgrade to TPU VMs, but in the meantime, you can try on GPU, or apply to to TRC (https://sites.research.google/trc/about/) to get free access to TPU VMs.

**Comment by sholtodouglas** [comment]
Thanks @skye! :)
