### ISSUE TITLE
`jaxlib.xla_extension.Device` should have a `__repr__` method

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#9049]
Currently, `jaxlib.xla_extension.Device` object has a `__str__` method, but does not have a `__repr__` method. As a consequence, the result of `print(jax.devices())` looks mess:

```python
>>> import os
>>> flags = os.environ.get('XLA_FLAGS', '')
>>> os.environ['XLA_FLAGS'] = flags + " --xla_force_host_platform_device_count=8"
>>> import jax
>>> jax.config.update('jax_platform_name', 'cpu')
>>> print(jax.devices())
[<jaxlib.xla_extension.Device object at 0x7f94256a2d30>, <jaxlib.xla_extension.Device object at 0x7f94256a2db0>, <jaxlib.xla_extension.Device object at 0x7f94256a3fb0>, <jaxlib.xla_extension.Device object at 0x7f940ce81ff0>, <jaxlib.xla_extension.Device object at 0x7f940ce81f70>, <jaxlib.xla_extension.Device object at 0x7f940ce81fb0>, <jaxlib.xla_extension.Device object at 0x7f940ce81f30>, <jaxlib.xla_extension.Device object at 0x7f940ce82030>]
>>> print(list(map(str, jax.devices())))
['TFRT_CPU_0', 'TFRT_CPU_1', 'TFRT_CPU_2', 'TFRT_CPU_3', 'TFRT_CPU_4', 'TFRT_CPU_5', 'TFRT_CPU_6', 'TFRT_CPU_7']
```

If the `__str__` method is changed to the `__repr__` method, the result of `print(jax.devices())` will look like the last line above, which is better. And if `__repr__` method is implemented, the `__str__` method will be the same as `__repr__`, so there is no need to implement the methods twice.

**Comment by ayaka14732** [comment]
The strange thing is that `GpuDevice` has a `__repr__` method, while CPU and TPU do not:

```python
>>> import jax
>>> print(jax.devices())
GpuDevice(id=0, process_index=0)]
```

**Comment by zhangqiaorjc** [comment]
Thanks @ayaka14732 for noticing.

We forgot to update our pybind after a CPU backend swap earlier this year.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/python/xla.cc#L162-L165

This should be 
```c++
  py::class_<TfrtCpuDevice, PjRtDevice, ClientAndPtr<TfrtCpuDevice>>(
      m, "CpuDevice")
      .def("__repr__", [](const TfrtCpuDevice& device) {
        return absl::StrFormat("CpuDevice(id=%i)", device.id());
```

Since xla::CpuDevice is now replaced with the new backend TfrtCpuDevice. I will make this change shortly. But it will only be available in the next jaxlib release.

**Comment by zhangqiaorjc** [comment]
This will be in the next jaxlib release. Closing this for now.
