### ISSUE TITLE
Publish Python 3.8 Mac OS arm64 wheels

### ISSUE THREAD

**Issue by dwyatte** [google/jax#9065]
Following on https://github.com/google/jax/issues/5501, building arm64 wheels for Mac OS is now supported. Currently (0.1.75) Mac OS  arm64 wheels are only published for Python 3.9 and Python 3.10, but Python 3.8 also supports arm64. I've tested this build configuration locally and basic functionality appears to work. Would it be possible to get this build configuration into the published wheels?

**Comment by hawkinsp** [comment]
We should be able to release Python 3.8 wheels whenever we next make a jaxlib release (soon).

**Comment by hawkinsp** [comment]
We just released `jaxlib` 0.3.0 which includes Mac ARM 3.8 wheels. (Note: you now need a `jax` version at least as high as your `jaxlib` version, so you need to upgrade `jax` to 0.3.0 also.)
