### ISSUE TITLE
`KeyboardInterrupt` not handled consistently

### ISSUE THREAD

**Issue by bytbox** [google/jax#9082]
I have a program that runs until I request termination. An easy way to do this is:
```
try:
    while True:
        # Call some jit'd functions
except KeyboardInterrupt:
    # This isn't actually an error -- just ignore it! Or maybe dump some data...
    with open('file', 'wb') as f:
        pickle.dump(1,f)
```
This approach is easy, and _mostly_ works. Unfortunately, sometimes the error thrown as a result of the KeyboardInterrupt is something else. For example:
```
Traceback (most recent call last):
  File "/home/scott/cauchy/mani/./aho.py", line 126, in <module>
    chain.step(N=30)
  File "/home/scott/cauchy/mani/./aho.py", line 71, in step
    if jax.random.uniform(kacc) < jnp.exp(-Sdiff):
  File "/home/scott/cauchy/env/lib/python3.10/site-packages/jax/_src/random.py", line 233, in uniform
    return _uniform(key, shape, dtype, minval, maxval)  # type: ignore
ValueError: Non-hashable static arguments are not supported. An error occured during a call to '_uniform' while trying to hash an object of type <class 'jax.core.NamedShape'>, (). The error was:
KeyboardInterrupt:

At:
  /home/scott/cauchy/env/lib/python3.10/site-packages/jax/core.py(1574): __hash__
  /home/scott/cauchy/env/lib/python3.10/site-packages/jax/_src/random.py(233): uniform
  /home/scott/cauchy/mani/./aho.py(71): step
  /home/scott/cauchy/mani/./aho.py(126): <module>
```

This issue is a bit of a challenge to reproduce reliably, since it only happens maybe one time in 50. I'm hoping those knowledgeable about jax internals will look at this situation and say "well of course that happens", and not need a concrete example.

This is a minor issue --- it's pretty easy to work around, and I could see it being a royal pain to fix --- but I wanted to document it, at least.

Let me know if a better reproduction is needed.

**Comment by mattjj** [comment]
Hrm, weird. Is the non-keyboard-interrupt error always this `ValueError: Non-hashable static arguments...` thing?

That error is raised in [some C++ code](https://github.com/tensorflow/tensorflow/blob/e20d9db02847716f38f1826c622447234473e424/tensorflow/compiler/xla/python/jax_jit.cc#L189) for dispatching jitted computations. I wonder if that implementation is buggy, like it's catching all exceptions and always raising this particular error (rather than only catching hashability exceptions).

@hawkinsp can you take a look?

**Comment by mattjj** [comment]
This issue is fixed in the source, but because there was a change in jaxlib, to get the fix you'd either need to build your own jaxlib from source or else wait for a new binary wheel release on pypi (jaxlib 0.1.76 or greater should have the fix).
