### ISSUE TITLE
docstring processing no longer fully working

### ISSUE THREAD

**Issue by jakevdp** [google/jax#9090]
e.g. 
```python
>>> print('versionadded' in jnp.nansum.__doc__)                                                                                    
True
```
In the past this was removed here: https://github.com/google/jax/blob/97a5719fcb40af7231b5f803f965063538282f8e/jax/_src/numpy/util.py#L127-L132

But something has changed and that is no longer happening.

**Comment by hawkinsp** [comment]
I think the `jit` decorators removed `__code__`.
