### ISSUE TITLE
vmap doesn't handle named arguments.

### ISSUE THREAD

**Issue by hadovanhasselt** [google/jax#912]
Minimalish example:
```
def f(a, b):
  return (2*a, 3*b)

jax.vmap(f)(jnp.array([1]), jnp.array([2]))  # works
jax.vmap(f)(a=jnp.array([1]), b=jnp.array([2]))  # doesn't work
```
The last line fails with `TypeError: reduce() of empty sequence with no initial value`.

**Comment by jqdm** [comment]
I came across a situation where `vmap` will appear to allow keyword arguments but produce incorrect results. In my case the incorrect results were valid values which allowed learning to continue (badly). Ideally an exception would be raised until keyword arguments are supported.

```
def wrapped_argmax(dummy, array):
  return jnp.argmax(array)

batch_wrapped_argmax = jax.vmap(wrapped_argmax)


array = jnp.array([[0, 3, 0], [0, 0, 2], [1, 0, 0]], dtype=jnp.float32)
dummy = jnp.zeros_like(array)

no_kw = batch_wrapped_argmax(
    dummy,
    array,
)
print("good", no_kw)

kw = batch_wrapped_argmax(
    dummy,
    array=array,
)
print("bad ", kw)

kw_slice = batch_wrapped_argmax(
    dummy[2:3],
    array=array[2:3],
)
print("good", kw_slice)

try:
  batch_wrapped_argmax(
      dummy=dummy,
      array=array,
  )
except Exception as err:
  print(err)


# Output:

# good [1 2 0]
# bad  [1 1 1]
# good [0]
# reduce() of empty sequence with no initial value
```

**Comment by sschoenholz** [comment]
@mattjj Is it possible to revert this change or (probably better) replace the NotImplementedError by a warning? Some code that we use in jaxmd relies on passing kwargs to vmapped function (with the expectation that they will not be vmapped over, so for us it's working as expected).

**Comment by hadovanhasselt** [comment]
> Some code that we use in jaxmd relies on passing kwargs to vmapped function (with the expectation that they will not be vmapped over, so for us it's working as expected).

I don't know the details of what you are trying to do, but would it be perhaps easier/clearer to use something like `functools.partial` to feed in the non-vmapped arguments in such cases?

So, something like the following?
```
g = functools.partial(f, a=a, b=b)  # setting generic, non-vmapped, kwargs
h = jax.vmap(g)
z = h(x, y)
```

I appreciate this might be slightly less elegant for your use case. But I think the alternative may be confusing at times, if the code behaves unintuitively to users (but doesn't fail)?

I think ideally named arguments would eventually be supported to `vmap` over.  I suppose that would break your current code, since it relies on them behaving differently?

**Comment by sschoenholz** [comment]
Ah, thanks for the recommendation. If it feels like my suggestion will adversely affect user experience then I can use a pattern like that. 

When calling `f(x, y, a=a, b=b)` in a loop, however, it feels a bit awkward to call `jit(vmap(g))` in the loop (though I guess it will hit the cache and so shouldn't be costly). I am definitely not proposing that jax be silent re: use of kwargs. I just think a warning stating that kwargs are not batched over might suffice to let users know about that behavior and reason about it accordingly. 

Regarding future compatibility, I would assume - as is the case with positional arguments - that eventually vmap will allow one to decide whether or not kwargs are to be vmapped over.

**Comment by mattjj** [comment]
@sschoenholz actually `jit(vmap(g))` _won't_ hit the cache, because `vmap` (like other transformations) produces a new Python callable object each time it's applied. (I promised Adam I'd write a doc explaining when to expect cache hits...)

As for the main topic of the thread: the main reason kwargs are hard to support with vmapped functions is that the way in_axes are specified really depends on arguments being passed as positional. But we can cover some special cases, including the one in the OP. I'll try that!
