### ISSUE TITLE
Potential memory leak using hessian-vector products inside iterative method

### ISSUE THREAD

**Issue by fsherry** [google/jax#9120]
I'm running into a memory issue while using the conjugate gradient method to solve an equation involving the hessian of a given functional. For this I need hessian-vector products which I am computing using automatic differentiation. 

The code snippet below should demonstrate the issue: in this example I end up running out of 16GB of GPU memory after 6 iterations (the exact error message is below the code). 

This example is in some sense minimal: when the inputs to `energy` are real (so that we can get rid of the `complex_to_real` and `real_to_complex` inside `energy_hvp`) the issue goes away, and when I don't use `cg` (just iterating `ll_hvp` many times for example) the issue doesn't exist either. 

I can't figure out a reason why memory usage should be increasing in the loop in the example below. Should I be doing something differently or is there a memory leak? I wasn't able to find a solution by looking at the other issues people have raised before about memory usage.
```python
import jax
import jax.numpy as np
from functools import partial

@jax.jit
def complex_to_real(x):
    return np.stack((x.real, x.imag), axis=-1)

@jax.jit
def real_to_complex(x):
    return x[..., 0] + x[..., 1] * 1.j

@partial(jax.jit, static_argnums=(0, 3))
def cg(A, rhs, xinit, N=1000):
    def f(state, _):
        x, p, r, i = state
        alpha = np.sum(np.abs(r)**2) / np.sum(p * A(p))
        x_ = x + alpha * p
        r_ = r - alpha * A(p)
        r_norm_sqr = np.sum(r**2)
        r__norm_sqr = np.sum(r_**2)
        p_ = r_ + (r__norm_sqr / r_norm_sqr) * p
        i_ = i + 1
        return (x_, p_, r_, i_), None
    x = xinit
    r = rhs - A(x)
    p = r
    i = 0
    return jax.lax.scan(f, (x, r, p, i), None, length=N)[0]

@jax.jit
def energy(x):
    return np.mean(np.abs(x)**2)

@jax.jit
def energy_hvp(x, v):
    x_stacked = complex_to_real(x)
    energy_grad = jax.grad(lambda x_stacked: energy(real_to_complex(x_stacked)))
    hvp = jax.jvp(energy_grad, (x_stacked,), (v,))[1]
    return hvp

x = jax.random.normal(jax.random.PRNGKey(13), (4096, 4096), dtype=np.complex128)
v = jax.random.normal(jax.random.PRNGKey(17), (4096, 4096, 2), dtype=np.float64)

for i in range(1000):
    cg(partial(energy_hvp, x), v, N=1)

```

```
2022-01-07 01:50:13.369175: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2036] Execution of replica 0 failed: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_7338/3698698091.py in <module>
      4 
      5 for i in range(1000):
----> 6     cg(partial(ll_hvp, x), v, N=1)

    [... skipping hidden 7 frame]

*********/lib/python3.9/site-packages/jax/interpreters/xla.py in _execute_compiled(compiled, avals, handlers, kept_var_idx, *args)
    891           for i, x in enumerate(args)
    892           if x is not token and i in kept_var_idx))
--> 893   out_bufs = compiled.execute(input_bufs)
    894   check_special(xla_call_p.name, out_bufs)
    895   return [handler(*bs) for handler, bs in zip(handlers, _partition_outputs(avals, out_bufs))]

RuntimeError: Internal: Failed to load in-memory CUBIN: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```

**Comment by mattjj** [comment]
Thanks for the excellent question!

@zhangqiaorjc does this kind of GPU memory error look familiar at all?

**Comment by PhilipVinc** [comment]
You are creating a new partial object containing the array x (which is rather large) at every iteration. This has a different hash and therefore triggers recompilation.

every recompiled instance stores the x array somehow, which is why it leads to OOM.

you should use jax.Partial instead

**Comment by fsherry** [comment]
> You are creating a new partial object containing the array x (which is rather large) at every iteration. This has a different hash and therefore triggers recompilation.
> 
> every recompiled instance stores the x array somehow, which is why it leads to OOM.
> 
> you should use `jax.tree_util.Partial` instead of `functools.partial`.

@PhilipVinc Thanks for the suggestion, I gave replacing `functools.partial` by `jax.tree_util.Partial` a try and found that the issue persists.

**Comment by PhilipVinc** [comment]
You also have to remove the 0th argument as a static argument from the jotted function, and accept the function as a standard argument. The function itself is automatically considered static but the array x is not
Il 7 gen 2022, 12:32 +0100, Ferdia ***@***.***>, ha scritto:

**Comment by fsherry** [comment]
@PhilipVinc That seems to have fixed all of my problems, thank you very much! I didn't realise you could pass functions wrapped in `Partial` to JIT'ed functions without marking them as static arguments. I should get a better understand of the JIT.
