### ISSUE TITLE
jnp.unique does not properly handle NaN values

### ISSUE THREAD

**Issue by jakevdp** [google/jax#9182]
Example:
```python
import numpy as np
import jax.numpy as jnp

x = np.array([0, 1, np.nan, np.nan])

print(np.unique(x))
# [ 0.,  1., nan])

print(jnp.unique(x))
[ 0.,  1., nan, nan]
```

**Comment by soraros** [comment]
Sorry if this comment comes in too late.

I've seen a discussion about this [here](https://github.com/data-apis/array-api/issues/249) in the array-api repo, and they conclude following the behaviour of the latest numpy(return a single `nan`) is not the way to go. Not that their argument directly transfers to JAX, but for instance, should I be concerned about the performance penalty similar to what's mentioned [here](https://github.com/data-apis/array-api/issues/249#issuecomment-913224110)?

And more generally, should JAX have an API closer to numpy or array-api(whose API seems to take accelerators more seriously and mentions JAX as a backend throughout its documentation)?

**Comment by jakevdp** [comment]
Thanks for raising this issue - I wasn't aware that there is any discussion about it.

My feeling is that because `jax.numpy` is explicitly designed to be an implementation of the `numpy` API, that it makes sense to make the same choice that numpy makes. I'm not aware of any case of `jax.numpy` choosing to diverge from `numpy` based on discussions in array-api.

Regarding extra overhead: I have not directly benchmarked it, but I wouldn't anticipate the added comparison in  #9184 making much of a performance impact.
