### ISSUE TITLE
JaxTuple error when `scan`ning a `jit`ted function

### ISSUE THREAD

**Issue by DylanMuir** [google/jax#921]
When using `lax.scan` on a `jit`ted function, I get this error. Could this be related to #861 and #890? I didn't manage to create a minimal breaking example, but the function works with no errors when the `jit`s are removed.

```
...

/anaconda3/envs/py36_tf/lib/python3.6/site-packages/jax/interpreters/partial_eval.py in instantiate_const(self, tracer)
     77 
     78   def instantiate_const(self, tracer):
---> 79     pv, const = tracer.pval
     80     if isinstance(pv, AbstractValue):
     81       return tracer

AttributeError: 'JaxTuple' object has no attribute 'pval'
```

**Comment by mattjj** [comment]
Can you test it against GitHub master if you're not already? It may be that we haven't pushed to pypi after #890.

**Comment by DylanMuir** [comment]
I no longer receive this error on GitHub `master`. I was using the pypi version.

**Comment by mattjj** [comment]
I'll update pypi now.

**Comment by mattjj** [comment]
Updated to 0.1.39. We'll do our best to stay on top of updating it, but it might be a good protocol to check against GitHub master to see if a bug has already been fixed.

Thanks for noticing this!

**Comment by DylanMuir** [comment]
Thanks @mattjj
