### ISSUE TITLE
Import error after compiling JAX from source on a TPU instance

### ISSUE THREAD

**Issue by awav** [google/jax#9220]
### Discussed in https://github.com/google/jax/discussions/9219

<div type='discussions-op-text'>

<sup>Originally posted by **awav** January 17, 2022</sup>
Hello everyone,

I'm trying to compile JAX with a custom XLA on the TPU VM, but I'm getting an error showed below. I would appreciate it if someone could help me to figure out what is the correct procedure for compiling JAX on TPUs.

I'm building JAX with this command (python with anaconda and python3 without):
```
> cd ~/jax
> python build/build.py --enable_tpu
> pip install --force-reinstall dist/jaxlib-*.whl
```

The import error after successfull compilation:
```
In [1]: import jax
2022-01-17 20:08:33.794365: F external/org_tensorflow/tensorflow/core/tpu/tpu_library_init_fns.inc:34] TpuEmbeddingEngineState_Create not available in this library.
```

A bit more information on the TPU instance:
```
(py37) artem@t1v-n-bla-bla-bla-host-0:~/code/jax$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

JAX SHA: `efa5edfd39632c5864e121de3290326b42b26326`</div>

**Comment by zhangqiaorjc** [comment]
Seems like the custom jaxlib is incompatible with libtpu.so. 

Try this:
cd jax
pip install -e .[tpu] -f https://storage.googleapis.com/jax-releases/libtpu_releases.html

@skye might know more about JAX CloudTPU build

**Comment by awav** [comment]
@zhangqiaorjc Thanks! it didn't work, I still can import jax (the same core dump).

**Comment by skye** [comment]
Hi @awav, try this with your custom-built jaxlib:

```
pip install --upgrade libtpu-nightly -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```

Or that doesn't work, pick the same libtpu-nightly date that you built your jaxlib:

```
pip install --upgrade libtpu-nightly==0.1.devYYYYMMDD -f https://storage.googleapis.com/jax-releases/libtpu_releases.html
```
(Replace the YYYYMMDD with the build date)

Explanation: the `TpuEmbeddingEngineState_Create not available in this library` message means the jaxlib you compiled requires a newer version of libtpu, the library that provides low-level access to Cloud TPUs (sorry the error message is unclear!). By default, we automatically install compatible versions of jaxlib and libtpu-nightly when you `pip install jax[tpu]`. However, when you build your own jaxlib, you'll have to manualy upgrade libtpu-nightly as shown above.

**Comment by awav** [comment]
@skye Thanks, I will try that. Quick question:

I'm using the JAX repo with SHA shown below, therefore should I use 20211107 as the build date?

```
(py37) artem@bla-bla-host: ~/code/jax$ git log -2
commit efa5edfd39632c5864e121de3290326b42b26326 (HEAD -> main, origin/main, origin/HEAD)a
Merge: c877f8bc ece53255
Author: jax authors <no-reply@google.com>
Date:   Thu Oct 7 06:23:59 2021 -0700

    Merge pull request #8091 from eelregit:check-eq-float0

    PiperOrigin-RevId: 401494757
```

**Comment by skye** [comment]
Sorry, I misspoke slightly above. The libtpu version you need depends on what version of tensorflow you use to build jaxlib (most of the jaxlib code lives in the tensorflow repo, e.g. all of XLA). By default, build.py picks up the tensorflow commit specified in jax's [WORKSPACE](https://github.com/google/jax/blob/main/WORKSPACE#L13) (the long hash in the URL is the TF git commit, e.g. it's https://github.com/tensorflow/tensorflow/commit/d8b3d5b22cb61b1a19e7d1c3524f1be92ee45ca6 at the time of writing, which was committed Dec 29).

If in doubt, using the latest libtpu-nightly often works though (we add new libtpu features more often than we change existing ones, and it's fine to use a libtpu with extra features compared to your jaxlib, as long as none of the features jaxlib uses have changed).

OOC, why are you trying to build a custom jaxlib?

**Comment by awav** [comment]
@skye, Hurray, it worked. Thank you so much! 

```
artem@bla-bla-host:~/code$ pip3  freeze | grep jax
-e git+https://github.com/google/jax.git@efa5edfd39632c5864e121de3290326b42b26326#egg=jax
jaxlib @ file:///home/artem/code/jax/dist/jaxlib-0.1.72-cp38-none-manylinux2010_x86_64.whl
```

> OOC, why are you trying to build a custom jaxlib?
I wrote an extension to XLA - some extra optimization passes (it helps a lot with research tasks I'm dealing with). I wonder if it will work out of the box on a TPU VM as well.

**Comment by skye** [comment]
Very cool! Then you've probably figured out how to update the WORKSPACE to point to your custom TF code. FYI you can also use the following to build from a local TF checkout instead of updating the WORKSPACE if it's easier:
```
python3 build/build.py --enable_tpu --bazel_options="--override_repository=org_tensorflow=$HOME/tensorflow"
```
This is what I like to use at least :)

**Comment by awav** [comment]
> Very cool! Then you've probably figured out how to update the WORKSPACE to point to your custom TF code. FYI you can also use the following to build from a local TF checkout instead of updating the WORKSPACE if it's easier:
> 
> ```
> python3 build/build.py --enable_tpu --bazel_options="--override_repository=org_tensorflow=$HOME/tensorflow"
> ```
> 
> This is what I like to use at least :)

Thanks for the tip! That will save me some time :)

**Comment by awav** [comment]
@zhangqiaorjc, @skye, I might have started celebrating too early

**Comment by awav** [comment]
Btw, I think this issue should be closed, the build works and I can import JAX properly. I opened another one #9261, and it is connected to the XLA and TPU interaction.

**Comment by ayaka14732** [comment]
Hi @skye, thanks for the explanation! I still have a question about that.

> The libtpu version you need depends on what version of tensorflow you use to build jaxlib

How can I determine the libtpu version I need based on the tensorflow version?

(Currently I am writing a guide for TPU and JAX: [ayaka14732/tpu-starter](https://github.com/ayaka14732/tpu-starter))
