### ISSUE TITLE
(probably no) Performance issues with v0.2.26 and above?

### ISSUE THREAD

**Issue by lumip** [google/jax#9238]
I have encountered some performance issues with JAX version 0.2.26 and 0.2.27. This has surfaced while running the TestU01 small-crush RNG testsuite against the `jax.random` RNG as well as my own implementation in https://github.com/DPBayes/jax-chacha-prng which run significantly slower than in previous versions. Running JAX version 0.2.26 with JAXlib version 0.1.74 took me 30:47.50 minutes (close to that with JAX version 0.2.27). With JAX version 0.2.25, same JAXlib version, took only 0:38.59 minutes.

I'm not sure what causes this and it's hard to track down. It could of course be an issue in my wrapping code around the Python rngs as I haven't yet found a simpler working example that demonstrates this behaviour. I'm trying to narrow it down further, but wanted to ask whether anyone else has encountered something similar or if there were any changes in JAX version 0.2.26 that I'm not aware of and that could explain this.

Please:

- [x] Check for duplicate issues.
- [ ] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:
As said above, I have not boiled this down to a simple complete example.

**Comment by hawkinsp** [comment]
I think we're going to need some sort of reproduction or trace or profile to track this down. It has been over a month since the previous release, so many things have changed. Without something we can run it's hard to know where to even start debugging this!

**Comment by mattjj** [comment]
That's quite a big regression! Should be easy to spot once we have a repro.

With a repro, we could bisect against git commits.

**Comment by lumip** [comment]
Alright, we have now tracked this down somewhat. I was using Pythons `PySequence_Fast*` family of API functions to access the values in a `DeviceArray` from the C/C++ side. This is very fast if Python recognises the input as a list/tuple-equivalent - this was the case for `DeviceArray` before 0.2.26 but seems to be no longer the case now, which causes the call to `PySequence_Fast` to construct a new list filled by iterating over the input sequence (i.e., the `DeviceArray`). This in turn seems to now create a list of `DeviceArray` objects containing single values.

The same behaviour occurs by constructing a list out of the array directly in Python:
```python
from jax import numpy as jnp
x = jnp.zeros(2)
print(list(x))
# on 0.2.25 prints: [0.0, 0.0]
# on 0.2.26 prints: [DeviceArray(0., dtype=float32), DeviceArray(0., dtype=float32)]
```
The new behaviour seems counter-intuitive to me. However, I can work around it by converting the DeviceArray into a plain numpy array before passing it back to the C/C++ side.

None of this seems to have any performance effect in any of our pure Python environments, so this probably does not affect most users.

I still wonder, is the above is expected behaviour now or an unintended artifact of recent changes?

P.S.: Files for a MWE with C++:
[CMakeLists.txt](https://github.com/google/jax/files/7905868/CMakeLists.txt)
[performance_bug_9238.cpp.zip](https://github.com/google/jax/files/7905875/performance_bug_9238.cpp.zip)
Unzip, then do the following in a terminal with a Python environment and jax installed
```
mkdir build && cd build && cmake .. && make & cd ..
build/performance_bug_9238 ./performance_bug_9238.py
# on 0.2.25 prints: took: 103018
# on 0.2.26 prints: took: 5736011
```

**Comment by hawkinsp** [comment]
Yes, this was an intentional change: https://github.com/google/jax/pull/8043

See the discussion on that PR. WDYT?

**Comment by lumip** [comment]
Well, I guess that makes sense overall. I'll consider this now resolved and will close, thanks for the feedback.
