### ISSUE TITLE
High order derivatives of a multivariate function

### ISSUE THREAD

**Issue by AlOa** [google/jax#924]
Hi,
I have a question about the high order derivatives of a multivariate function: I have function from `R^n -> R:  f(x1, x2, .. xn)` and I want to calculate the second partial derivatives ( may be also higher order ) of  `f` with respect to some of the variables.
I can use jvp to obtain the first derivatives, but i don't know the best way to extend it to higher order derivatives, if it can be done.
Take as example the function:
`def f(W,x):
     return np.sin(dot(W,x))`
with `x=(x1, x2)` and `W:R^1xR^2` and I want the second derivative of `f` with respect to `x1`. How can I obtain that?

**Comment by AlOa** [comment]
If someone is interested I found a solution, which is very simple: use vjp and lambda(or partial).
In the example above:

```
def f(W, x):
    return np.sin(np.dot(W, x)

eye = np.eye(dim)

dfdx1 = lambda x: jvp(partial(f, W), (x,) , (eye[0],) )[1]

d2fd2x1 = lambda x: jvp(dfdx1, (x,) , (eye[0],) )[1]
```
and similar for higher order derivatives.

**Comment by hawkinsp** [comment]
Great!

Is there anything we could add to the [documentation](https://jax.readthedocs.io/en/latest/jax.html) or the [Autodiff cookbook](https://colab.research.google.com/github/google/jax/blob/master/notebooks/autodiff_cookbook.ipynb) that might have helped you figure it out quicker? We'd welcome suggestions or PRs.

**Comment by AlOa** [comment]
I found documentation very helpful, once I began to think more functionally.
If i can make a suggestion, maybe you can add some examples of differentiation less related to standard machine learning. Something simple, like how to differentiate a polynomial function with respect to its variables. So one can see a more general use of vjp/jvp,
