### ISSUE TITLE
Unrecognisable XLA flags in JAX built on a TPU VM with custom XLA

### ISSUE THREAD

**Issue by awav** [google/jax#9261]
### Discussed in https://github.com/google/jax/discussions/9260

<div type='discussions-op-text'>

<sup>Originally posted by **awav** January 20, 2022</sup>
Hello everyone, this question relates to the https://github.com/google/jax/issues/9220 (thanks to @skye and @zhangqiaorjc for resolving it quickly). Now, I'm puzzled how to make JAX to run my custom built XLA with extra optimisation passes on a TPU VM. For CPU and GPU it was straightforward - I simply added my optimisation passes in `(cpu|gpu)_compiler.cc`. I suspect I need to do something similar with TPU backend, but I can't figure out what exactly.

I would really appreciate it if someone could help me with resolving this issue. Thanks!

PS: Error I'm getting right now (with dummy custom flags):
```
2022-01-20 16:55:41.526525: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:171] ****(awav) THIS IS A CUSTOM BUILD****
2022-01-20 16:55:41.526573: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:172] XLA service 0x1b83380 initialized for platform Interpreter (this does not guarantee that XLA will be used). Devices:
2022-01-20 16:55:41.526582: I external/org_tensorflow/tensorflow/compiler/xla/service/service.cc:180]   StreamExecutor device (0): Interpreter, <undefined>
2022-01-20 16:55:41.539829: I external/org_tensorflow/tensorflow/compiler/xla/pjrt/tfrt_cpu_pjrt_client.cc:164] TfrtCpuClient created.
INFO:absl:Unable to initialize backend 'tpu_driver': NOT_FOUND: Unable to find driver in registry given worker:
INFO:absl:Unable to initialize backend 'gpu': NOT_FOUND: Could not find registered platform with name: "cuda". Available platform names are: TPU Host Interpreter
F0120 16:55:41.547101  190667 parse_flags_from_env.cc:229] Unknown flags in XLA_FLAGS: --xla_custom_flag=hello_world Perhaps you meant to specify these on the TF_XLA_FLAGS envvar?
```</div>

**Comment by skye** [comment]
Hi @awav, sorry for the delay. I'm not totally sure how to do this, but I would look at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/tpu/tpu_on_demand_compiler.cc#L54. Most of the TPU-specific compiler stuff is closed-source inside the libtpu.so library (look for `ExecutorApiFn()` calls, that's the entry point into libtpu functions). You won't be able to insert your custom passes in the middle of the closed-source TPU passes, but maybe you can get away with inserting them at the beginning or end.

**Comment by awav** [comment]
Thanks @skye! This is a disappointing news. Is there a documentation for `libtpu` somewhere? :)

**Comment by skye** [comment]
https://cloud.google.com/tpu/docs/system-architecture-tpu-vm mentions libtpu at a very high level, but we don't have any in-depth documentation. Sorry I can't offer any better news -- I'd love for the XLA:TPU compiler to become more hackable in the future, but it's currently not very accessible. Let me know if there are any other specific questions you have and I can try to help.

**Comment by hawkinsp** [comment]
There's no action we can take here: there's no way to add extra compiler passes to the closed-source TPU compiler. The best you can do is add passes at the beginning before the compiler runs as an MHLO->MHLO rewrite, which should be easy enough to do.
