### ISSUE TITLE
Slow compilation from computation involving arithmetic and concatenation

### ISSUE THREAD

**Issue by joschu** [google/jax#927]
Here's a reproduction: https://gist.github.com/joschu/54699199d16b02a78d8d4ff58d349596
Sorry that it's a bit complicated--I can try to simplify if that'd be helpful.
Oddly, the compilation times seem to depend on the size of the arrays involved.

GPU/Linux: compiles in 27 seconds
CPU/OSX: compiles in 14 seconds. Also non-deterministically segfaults on exit

**Comment by hawkinsp** [comment]
PR #932 fixes the compilation time (I get closer to 0.2s afterward).

The segfault on Mac OS I will also look into; it's most likely related to destruction ordering, so it's annoying but unlikely to harm anything.

**Comment by hawkinsp** [comment]
#933 fixed the segfault on exit. It requires a Jaxlib rebuild, so you can either rebuild from source or wait for us to make a binary release. Hope that helps!

**Comment by joschu** [comment]
Nice!!

Sent via Superhuman ( https://sprh.mn/?vip=joschu@openai.com )
