### ISSUE TITLE
Jitted function sometimes doesn't distinguish static arguments with different type

### ISSUE THREAD

**Issue by soraros** [google/jax#9273]
I'm not sure if it is actually a bug, but the following behaviour sure is surprising.
```python
@partial(jit, static_argnums=(0,))
def f(k):
  print('traced!', k)
  return k

list(map(f, [1, True, 1.0]))
# returns:
# [DeviceArray(1, dtype=int64, weak_type=True),
#  DeviceArray(1, dtype=int64, weak_type=True),
#  DeviceArray(1, dtype=int64, weak_type=True)]
```

This is of course because `hash(1) == hash(1.0) == hash(True) == 1`. Maybe we could use a hash function like `lambda x: hash((x, type(x)))`.
Notice `functools.lru_cache` doesn't have the same oddity, when `typed=False` it doesn't distinguish `1` and `1.0`, and when `typed=True` it tells all tree apart.

**Comment by hawkinsp** [comment]
Yes, the issue is that the value has the same `hash()` and compares as equal. I'm not sure it's a bug either!

**Comment by soraros** [comment]
Then maybe it's worth being documented somewhere? Like in [The Shape Bits](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html) or docstring of `jit`.

**Comment by jakevdp** [comment]
Note that the same "bug" exists for Python dictionaries:
```python
print({1.0:1 , 1: 2, True: 3})
# {1.0: 3}
```

**Comment by soraros** [comment]
Well, it's definitely cursed.
```python
from functools import lru_cache

@lru_cache()
def f(x):
  print(x)
  return x

f(1)
f(1.)
f(True)
# prints:
# 1
# 1.0
```
and
```python
@lru_cache(typed=True)
def f(x):
  print(x)
  return x

f(1)
f(1.)
f(True)
# prints:
# 1
# 1.0
# True
```

**Comment by hawkinsp** [comment]
#9311 would fix this. I'm still not completely sure whether it's a good idea or not, but I'm leaning towards being stricter as it seems less surprising.
