### ISSUE TITLE
Custom pytree strange leakage behavior

### ISSUE THREAD

**Issue by eelregit** [google/jax#9283]
I found that a custom pytree (of standard mutable pytree like list/dict)
behave strangely in the following example, where the treedef changes inside a function:

```python
from jax.tree_util import register_pytree_node_class

@register_pytree_node_class
class C:
    def __init__(self, l=[]):
        self.l = l

    def tree_flatten(self):
        return self.l, None

    @classmethod
    def tree_unflatten(cls, aux_data, children):
        return cls(children)
    
def f(c):
    c.l.append(0)
    return c

print(vars(C()))
print(vars(C()), vars(f(C())))
```

returns

```python
{'l': []}
{'l': [0]} {'l': [0]}
```

The two `C()` return different outputs and the second one seem to be polluted by the `f(C(0))` call.

**Comment by eelregit** [comment]
Another example is https://github.com/DifferentiableUniverseInitiative/jax_cosmo/issues/81#issuecomment-1016984119
where treedef doesn't change but aux_data leak among instances.

**Comment by hawkinsp** [comment]
Isn't the problem here that the default value you are using in your `__init__` is mutable? That's a known Python antipattern.

Try something like:
```
    def __init__(self, l=None):
        self.l = [] if l is None else l
```

**Comment by eelregit** [comment]
Thanks @hawkinsp! That explains it.
