### ISSUE TITLE
unjitted_loop_body is not constantly re-compiled in the JIT tutorial 

### ISSUE THREAD

**Issue by GeraldCSC** [google/jax#9288]
Hello there,

I could be misunderstanding something here(new to Jax still) but on the [JIT tutorial](https://jax.readthedocs.io/en/latest/jax-101/02-jitting.html#caching) it seems like the "bad" example is not actually that bad. 

More concretely, the given example is as follows:
```python
def g_inner_jitted_poorly(x, n):
  i = 0
  while i < n:
    # Don't do this!
    i = jax.jit(unjitted_loop_body)(i)
  return x + i
```
Contrary to the description of this example on the tutorial, it seems like the  unjitted_loop_body function is actually not being compiled every iteration, but cached somewhere. 
```python
def unjitted_loop_body(prev_i):
  print("i am being jitted")
  return prev_i + 1

def g_inner_jitted_poorly(x, n):
  i = 0
  while i < n:
    # Don't do this!
    i = jax.jit(unjitted_loop_body)(i)
  return x + i
g_inner_jitted_poorly(10, 3)
```
outputs
```
i am being jitted
```
However, if I switch this to a lambda function, it is indeed being compiled every iteration. Which seems like a more accurate example(if I'm not mistaken).

```python
def unjitted_loop_body(prev_i):
  print("i am being jitted")
  return prev_i + 1

def g_inner_jitted_poorly(x, n):
  i = 0
  while i < n:
    # Don't do this!
    i = jax.jit(lambda x: unjitted_loop_body(x))(i)
  return x + i
g_inner_jitted_poorly(10, 3)
```
outputs 
```
i am being jitted
i am being jitted
i am being jitted
```

Thanks!

**Comment by jakevdp** [comment]
Thanks - I think cacheing has improved since this was originally written, but you're right that anonymous functions still cause the issue that this section speaks to.

Is this something you'd like to address in a PR? If not I'm happy to take the issue. Thanks!

**Comment by GeraldCSC** [comment]
thanks! I've made a PR for this just now. #9312

**Comment by mattjj** [comment]
Thanks for finding this, and explaining it so clearly!
