### ISSUE TITLE
Potential Error in Example in Documentation For Optimizers

### ISSUE THREAD

**Issue by esraa-saleh** [google/jax#9332]
Hi Jax team!

Is the syntax for the sgd example here outdated? 
https://jax.readthedocs.io/en/stable/jax.experimental.optimizers.html

Here's what it says:

```
opt = optimizers.sgd(learning_rate)
opt_state = opt.init(params)

def step(step, opt_state):
  value, grads = jax.value_and_grad(loss_fn)(opt.get_params(opt_state))
  opt_state = opt.update(step, grads, opt_state)
  return value, opt_state

for step in range(num_steps):
  value, opt_state = step(step, opt_state)
```

However, if I use opt.init in this manner, then I'll get this error:
`AttributeError: 'Optimizer' object has no attribute 'init'`

Should the example say opt.init_fn instead? and I'm guessing that if that's the case, then update would need to be update_fn and get_params would need to be params_fn.

If that's the case, I'd be happy to help fix the docs, but I just want to first confirm whether my understanding is correct.

**Comment by skye** [comment]
@froystig are the right person to look at this, or do you know who is?

**Comment by froystig** [comment]
Good catch, thanks for filing.

> Should the example say opt.init_fn instead? and I'm guessing that if that's the case, then update would need to be update_fn and get_params would need to be params_fn.

That indeed seems to be the correct fix. We'd welcome the contribution if you'd like to make a pull request for it!

**Comment by esraa-saleh** [comment]
Ooh I see! I didn't know about the difference between the links. Thank you for clarifying @froystig !
