### ISSUE TITLE
x.at[indices].add differs from numpy if duplicate indices

### ISSUE THREAD

**Issue by cooijmanstim** [google/jax#9344]
The JAX at-add construct will update duplicate indices multiple times:

```python
import jax.numpy as jp
x = jp.array([0, 0])
y = x.at[jp.array([0, 1, 1])].add(1)
# now y == [1, 2]
```

whereas in numpy the update only occurs once:

```python
import numpy as np
x = np.array([0, 0])
y = x.copy()
y[np.array([0, 1, 1])] += 1
# now y == [1, 1]
```

Not sure if this needs to be consistent necessarily, but the discrepancy is not documented.

**Comment by jakevdp** [comment]
Thanks for the report: this is the intended behavior, and is documented at https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html#jax.numpy.ndarray.at

> Unlike NumPy in-place operations such as `x[idx] += y`, if multiple indices refer to the same location, all updates will be applied (NumPy would only apply the last update, rather than applying all updates.)

**Comment by jakevdp** [comment]
Is there a different place in the documentation that you think could be clarified?

**Comment by cooijmanstim** [comment]
Ah nice, I actually prefer JAX's behavior. I was looking at https://jax.readthedocs.io/en/latest/jax.ops.html, which doesn't mention multiple updates.

**Comment by jakevdp** [comment]
Makes sense, thanks. #9345 adds this paragraph to the section you were looking at.
