### ISSUE TITLE
JIT trace+compile without running function

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#9347]
It'd be nice to be able to trace and compile a function -- including all the optimisation done by the XLA compiler, i.e. more than just than is provided by `jax.xla_computation` -- without actually running the function afterwards. In particular this would be useful when benchmarking and optimising compile times.

I think this is already actually doable via `jax.lib.xla_bridge.get_backend().compile`, so this is really just a request to expose this functionality publicly.

**Comment by mattjj** [comment]
You are in luck my friend! Try this out:

```python
import jax

compiled = jax.jit(lambda x: x + 2).lower().compile()
```

You can also run e.g. `compiled(3)`, but you'll get a dtype error if you try `compiled(3.)`.

What do you think?

**Comment by mattjj** [comment]
See #7733. I'm not sure if there are docs yet, but all staging decorators (`jit`, `pjit`, `pmap`, `xmap`) should have roughly the same API here, or will soon.

**Comment by patrick-kidger** [comment]
Hurrah - that's great, thanks! :D
