### ISSUE TITLE
jax.numpy sin and cos functions zero out the complex part when called with a complex number

### ISSUE THREAD

**Issue by naylor-b** [google/jax#9358]
```python
import numpy as np

import jax.numpy as jnp
from jax.config import config
config.update("jax_enable_x64", True)

a = 5. + 1e-40j
ja = jnp.asarray(a, dtype=np.complex128)

print(f"np.sin({a}) -> {np.sin(a)}")
print(f"np.cos({a}) -> {np.cos(a)}")

print("\njax.numpy gives same answer as numpy for the real part but zeros out the complex part:")
print(f"jnp.sin({ja}) -> {jnp.sin(ja)}")
print(f"jnp.cos({ja}) -> {jnp.cos(ja)}")

```

This is the output produced:

```
np.sin((5+1e-40j)) -> (-0.9589242746631385+2.836621854632263e-41j)
np.cos((5+1e-40j)) -> (0.2836621854632263+9.589242746631385e-41j)

jax.numpy gives same answer as numpy for the real part but zeros out the complex part:
jnp.sin((5+1e-40j)) -> (-0.9589242746631385+0j)
jnp.cos((5+1e-40j)) -> (0.2836621854632263-0j)
```

**Comment by naylor-b** [comment]
After submitting this I noticed that it only happens when the complex part is small, around 1e-16 or so.

**Comment by jakevdp** [comment]
Since this only happens when the ratio of the imaginary to real part is smaller than ~1E-16, I suspect the difference is not a bug, so much as a consequence of different implementations leading to different floating point roundoff errors. For example, here are two common expressions for computing the sine of a complex number, computed in both jax and numpy:
```python
print("exponent formula:")
print("np:", (np.exp(1j * a) - np.exp(-1j * a)) / 2j)
print("jnp:", (jnp.exp(1j * a) - jnp.exp(-1j * a)) / 2j)
print()
print("hyperbolic trig formula:")
print("np:", np.sin(a.real) * np.cosh(a.imag) + 1j * np.cos(a.real) * np.sinh(a.imag))
print("jnp:", jnp.sin(a.real) * jnp.cosh(a.imag) + 1j * jnp.cos(a.real) * jnp.sinh(a.imag))
```
```
exponent formula:
np: (-0.9589242746631385-0j)
jnp: (-0.9589242746631385-0j)

hyperbolic trig formula:
np: (-0.9589242746631385+2.8366218546322623e-41j)
jnp: (-0.9589242746631385+2.8366218546322623e-41j)
```
I suspect that XLA internally uses something like the former, while numpy uses something like the latter. Neither is incorrect – you just need to keep in mind that floating point arithmetic is not the same as real number arithmetic, and this is particularly apparent when working with values that differ by a factor of ~10^16 or more.

**Comment by mattjj** [comment]
@naylor-b should we consider this a numerical detail rather than a bug, and close the issue? Or is there a better course of action?

**Comment by hawkinsp** [comment]
XLA uses this expansion for complex cosine:
https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/compiler/xla/service/elemental_ir_emitter.cc;drc=896a2548a4ed330624db67b11e767909722cb730;l=627

NumPy uses this expansion:
`cos(z)  = cosh(1j * z)`:
https://github.com/numpy/numpy/blob/7e76174901a17801dc21e832403a94ed20fc1f97/numpy/core/src/npymath/npy_math_complex.c.src#L531

and `cosh` is defined differently across various ranges, but I think we're in this case:
https://github.com/numpy/numpy/blob/7e76174901a17801dc21e832403a94ed20fc1f97/numpy/core/src/npymath/npy_math_complex.c.src#L610

i.e. `cosh(z) = complex(cosh(re(z))*cos(im(z)), sinh(re(z)) * sin(im(z)))`

Perhaps NumPy's expansion is more accurate?

**Comment by naylor-b** [comment]
Thanks for all of the detailed responses guys.  I'll just consider this a numerical issue instead of a bug.
