### ISSUE TITLE
possible bug in jax.example_libraries.optimizers.adam?

### ISSUE THREAD

**Issue by jkitchin** [google/jax#9377]
Please:

- [x ] Check for duplicate issues.
- [ x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

This code generates a Traceback. If I replace `jax.opt.adam` with `jax_opt.sgd`, it seems to work fine. That is why I suspect something is wrong in `adam`.  This is in jax version 0.2.25.

```python
import jax.example_libraries.optimizers as jax_opt
from jax import value_and_grad
import jax.numpy as np

opt_init, opt_update, get_params = jax_opt.adam(1e-2)

opt_state = opt_init(np.array(1.1))

def objective(x):
    return (x**2).squeeze()

def step(i, opt_state):
    value, grads = value_and_grad(objective)(get_params(opt_state))
    return value, opt_update(step, grads, opt_state)

step(0, opt_state)
```

- [x ] If applicable, include full error messages/tracebacks.

I get this resulting error

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-caac38fbc2ef> in <module>()
     14     return value, opt_update(step, grads, opt_state)
     15 
---> 16 step(0, opt_state)

3 frames
/usr/local/lib/python3.7/dist-packages/jax/example_libraries/optimizers.py in update(i, g, state)
    408     m = (1 - b1) * g + b1 * m  # First  moment estimate.
    409     v = (1 - b2) * jnp.square(g) + b2 * v  # Second moment estimate.
--> 410     mhat = m / (1 - jnp.asarray(b1, m.dtype) ** (i + 1))  # Bias correction.
    411     vhat = v / (1 - jnp.asarray(b2, m.dtype) ** (i + 1))
    412     x = x - step_size(i) * mhat / (jnp.sqrt(vhat) + eps)

TypeError: unsupported operand type(s) for +: 'function' and 'int'
```

**Comment by froystig** [comment]
In your definition of the `step` function, do you mean for the return statement to be the following?
```python
    return value, opt_update(i, grads, opt_state)
```
The current expression you have passes the `step` function itself in to `opt_update`, where an integer is expected.

**Comment by jkitchin** [comment]
You are right, that should have been `i` instead of `step`. I was thrown off that it worked with the sgd optimizer. Thanks for pointing out the error!

**Comment by hawkinsp** [comment]
(Just in case you're not aware of it, we often recommend using `optax` instead of `jax.example_libraries.optimizers` these days: https://github.com/deepmind/optax )
