### ISSUE TITLE
lax.conv does not support float64

### ISSUE THREAD

**Issue by carlini** [google/jax#940]
The lax package currently does not support float64 convolutions. This appears to be an explicit constraint and not a bug.

https://github.com/google/jax/blob/master/jax/lax/lax.py#L1828

Feature request: allow convolutions with float64 -> float64 in full precision. TF supports this type of convolution, so I don't think there's anything inherent preventing this, but maybe it's something subtle.

**Comment by hawkinsp** [comment]
As far as I can tell, this is an oversight. On CPU and GPU XLA should support float64 convolutions.

**Comment by hawkinsp** [comment]
I relaxed the check and added tests for float64 convolutions. Hope that helps!

**Comment by carlini** [comment]
This is great, thanks!

(I'm very impressed with the response time here. If only everything was this quick.)

**Comment by hawkinsp** [comment]
Happy to help! One caveat: I think the float64 conv implementation on CPU may be a slow reference implementation. If you find it to be too slow, we can work with the XLA developers to optimize it. On GPU it should be fast because it just calls CuDNN, like most other frameworks.
