### ISSUE TITLE
Make Jax's API searchable

### ISSUE THREAD

**Issue by yashk2810** [google/jax#9435]
Currently if I search for jax.vmap on google search, I am not directed directly to that point in the big page.

This is very inconvenient because I have to search for vmap again on the big page. It would be good to split each API endpoint into its own page (as @hawkinsp suggested) to make it more searchable.

jax.numpy packages have their own pages and if you search for `jax.numpy.argmax`, you are directed to that page!

**Comment by jakevdp** [comment]
It's possible to make sphinx generate separate pages for different functions or groups of functions. On one extreme,we could have a different generated page for each function, as is done in the Altair library: https://altair-viz.github.io/user_guide/API.html

What do you think?

**Comment by yashk2810** [comment]
I like a different page for each function/class. That;s how jax.numpy is right now. So let's make it consistent?
