### ISSUE TITLE
jax.numpy.power should raise warning as numpy.power for negtive values

### ISSUE THREAD

**Issue by wztdream** [google/jax#9458]
see below example, numpy.power will raise warning for negative values, but jax.numpy.power not raise warning. As negative value in this case will results in nan, so raise warning will be helpful for user to debug nan. Actually this nan cause me lots time to debug. So can we raise warning too in jax? 
```
>>> import numpy as np
>>> import jax.numpy as jnp
>>> x = np.array([-0.5])
>>> x**1.5
<stdin>:1: RuntimeWarning: invalid value encountered in power <---here numpy raise warning, but jax.numpy will not
array([nan])
>>> jx = jnp.array([-0.5])
>>> jx**.15
DeviceArray([nan], dtype=float32)
```

**Comment by wdg3** [comment]
You can turn on NaN debugging by following one of the approaches [here](https://github.com/google/jax/blob/39786c64101bea9524efa6e4ee2926eb06ba7d47/docs/notebooks/Common_Gotchas_in_JAX.md#-nans):

> setting the JAX_DEBUG_NANS=True environment variable;
>
> adding from jax.config import config and config.update("jax_debug_nans", True) near the top of your main file;
>
> adding from jax.config import config and config.parse_flags_with_absl() to your main file, then set the option using a command-line flag like --jax_debug_nans=True;

This will cause NaNs to throw an error immediately with a helpful stack trace that will contain something along the lines of

`jax._src.traceback_util.UnfilteredStackTrace: FloatingPointError: invalid value (nan) encountered in pow`.

I'm not super familiar with the project and its goals so I'll let someone else comment on whether adding numpy-like `RuntimeWarnings` is something that should be taken up.

**Comment by jakevdp** [comment]
The reason JAX cannot raise value-dependent warnings is the same reason that it cannot error on [Out of bound indices](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#out-of-bounds-indexing) – there is no way for computations on accelerators to return value-dependent error or warning codes.

The best way to deal with this issue is using the `debug_nans` functionality that @wdg3 linked to.
