### ISSUE TITLE
Various type inconsistencies

### ISSUE THREAD

**Issue by NeilGirdhar** [google/jax#9462]
Please consider adding `jax.numpy.generic` as an alias for `numpy.generic` (it seems to be missing).  Also,
```
In [5]: jnp.issubdtype(jnp.bfloat16, jnp.inexact)
Out[5]: True

In [6]: issubclass(jnp.bfloat16, jnp.inexact)
Out[6]: False

In [7]: issubclass(np.float32, np.inexact)
Out[7]: True
```
Line 6 should probably return true, which means somehow registering the types like numpy does.

**Comment by jakevdp** [comment]
I'm not sure that would be correct; for example:
```python
import numpy as np
print(type(np.float16(0)))
# numpy.float16

import jax.numpy as jnp
type(jnp.float16(0))
# jaxlib.xla_extension.DeviceArray
```
JAX does not return an instance of a `float16` scalar in this case, but rather returns a zero-dimensional JAX array. THis choice to unify arrays and scalars in JAX is a deliberate one: we have specifically decided to *not* honor the numpy Python type hierarchy in the case of scalar-like instantiations, so enforcing that `jnp.float16` is a subclass of `jnp.inexact` would be misleading.

What do you think?

**Comment by jakevdp** [comment]
I think you're looking for `jnp.issubdtype(t, jnp.inexact)`

**Comment by NeilGirdhar** [comment]
Yes, I know how to check it programmatically.  I'm asking how I should annotate it.

**Comment by jakevdp** [comment]
Sorry, I just noticed that your question is more a question of type annotation than in-program type checking.

JAX aside, I don't think using `T: type[np.inexact]` is the best approach, becuase (for example) `np.dtype('float64')` will fail this.

Instead, you should probably use [`DtypeLike`](https://numpy.org/devdocs/reference/typing.html#dtypelike). Unfortunately, this doesn't give any mechanism to limit inputs to inexact types, but I think that Python type checking simply doesn't have the granularity to do that correctly.

It's one of the reasons that JAX internally aliases so many types to `Any`: Python type declaration is just generally not expressive enough to properlay work with array computing code.

**Comment by jakevdp** [comment]
https://github.com/google/jax/pull/9471
