### ISSUE TITLE
Cannot bitcast complex to float (view complex as real)

### ISSUE THREAD

**Issue by izaid** [google/jax#9496]
Hello Jax developers - many thanks for the great package! Possible bug below ...

In NumPy, it's possible to view a complex array as a float array where the last dimension has twice the length. In Jax, this throws an exception. Being able to do this is very convenient, and helps greatly with interoperability using other array packages. It seems like this should be possible.

```python
import numpy as np
import jax
import jax.numpy as jnp

a = jnp.zeros(10, dtype = jnp.complex64)
b = a.view(jnp.float32)
# TypeError: `bitcast_convert_type` for operand type (complex64) cannot have different destination type (uint32)
```

**Comment by jakevdp** [comment]
Thanks for the report: unfortunately I don't believe this type of cast is supported by XLA.

**Comment by hawkinsp** [comment]
I'm not 100% sure! This might be possible on CPU and GPU. I promise it is not possible on TPU because the memory is not laid out the same way.

**Comment by PhilipVinc** [comment]
I had already asked about this in #8816 , which was closed because a workaround was found.

However an actual implementation would be very welcome!

**Comment by izaid** [comment]
So I saw https://github.com/google/jax/issues/8816, but it was a bit confusing to be honest. My real motivation is to safely use a Jax-allocated array of complex numbers in other packages, but couldn't export via DLPack as per the other issue.

Is there a safe, simple workaround for viewing a complex arrays as floats? Even if XLA allocates things differently, it would be nice to have versions of `view_as_real` and `view_as_complex` like PyTorch does.

**Comment by PhilipVinc** [comment]
Something like this?
```python
@jax.jit
def as_real(x):
    if not jnp.issubdtype(x.dtype, jnp.complexfloating):
        return x

    xr = jnp.zeros(x.shape+(2,), dtype=x.real.dtype)
    xr = xr.at[...,0].set(x.real)
    xr = xr.at[...,1].set(x.imag)
    return xr
```

**Comment by izaid** [comment]
Confirming here that the functions provided by @PhilipVinc return a copy, at least by inspection using `unsafe_buffer_pointer`.

Just curious what Jax's perspective is on this. Let's say, for the moment, I don't actually care about applying Jax operations on the resulting float array. All I want is to get a float view on a complex array, regardless of the resultant shape. Here is where I'm coming from.

There are some external high-performance numerical libraries, including on the GPU, that only support floats but work completely fine if handling the real and imaginary parts of a complex array independently. If I'm working with complex numbers, and I want to use complicated third-party library X that only supports floats, ideally I'd:

1) View my Jax complex array as a Jax float array.
2) Export that Jax float array, via dlpack or whatever, to this other library.

At the moment, since 1) isn't possible, I have to be able to get the pointer, shape, strides, and other layout information and then manually modify that before importing it. If I do this via dlpack, that means manually modifying the dlpack PyCapsule  via ctypes. Alternatively, is it possible to get the strides of a Jax array? I don't see a `.strides` attribute on `DeviceArray`.

If I am on the CPU, the workaround here would be to go through NumPy, but on a GPU I then require going through another heavy package (CuPy, PyTorch, TensorFlow, ...).

Note also it doesn't matter particularly how the complex array is stored, just that I can get as a float array of some shape.

And many thanks for resolving https://github.com/google/jax/issues/9497, that at least makes hack-workarounds possible! (And cleanly resolves other issues.)

**Comment by jakevdp** [comment]
> Confirming here that the functions provided by @PhilipVinc return a copy, at least by inspection using unsafe_buffer_pointer.

Unless I'm mistaken, *every* non-trivial function is going to return a copy according to inspection of `unsafe_buffer_pointer`, even functions that will use views of buffers internally. For example:
```python
import jax
from jax import lax
import jax.numpy as jnp

@jax.jit
def view_as_unsigned(x):
  return lax.bitcast_convert_type(x, jnp.uint32)

x = jnp.arange(5, dtype='int32')
y = view_as_unsigned(x)
print(x.unsafe_buffer_pointer() == y.unsafe_buffer_pointer())
# False
```
So, does the workaround for viewing complex as float really use a view? I suspect the answer is no, but the answer is not clear. The reason is because the choice of whether to use buffer views or copies for a given action is really up to the XLA compiler, and the behavior currently is difficult (or maybe impossible?) to introspect.

There have been requests from users for more transparency on this (e.g. #9132), but I don't know of any satisfactory answer at the moment.

**Comment by rajasekharporeddy** [comment]
Hi @izaid 

Looks like this issue has been resolved. I executed the mentioned code on colab with JAX version 0.4.23 and it now produces the output  as an Array of the preferred dtype without any error.

```python
import jax
import jax.numpy as jnp

a = jnp.zeros(10, dtype = jnp.complex64)
print("'a': {}".format(a))
b = a.view(jnp.float32)
print("'a' is viewed as float: {}".format(b))
c = a.view(jnp.complex64)
print("'a' is viewed as complex: {}".format(c))
```
Output:
```
'a': [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
'a' is viewed as float: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
'a' is viewed as complex: [0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]
```

Please find the [gist](https://colab.research.google.com/gist/rajasekharporeddy/5b01d07be531db9c0052790ae2b060b9/-9496.ipynb) for reference.

Also verified this behavior on cloud VM with T4 GPU with JAX version 0.4.25 and it works fine. Please refer the below screenshot.
<img width="953" alt="image" src="https://github.com/google/jax/assets/153593711/bd502081-5d0f-40c9-98ee-9d0ca988d5c1">

Thank you.

**Comment by rajasekharporeddy** [comment]
Hi @izaid 

Please feel free to close the issue, if resolved.

Thank you

**Comment by jakevdp** [comment]
Thanks all!
