### ISSUE TITLE
Unclarity documentation tree_flatten.

### ISSUE THREAD

**Issue by GJBoth** [google/jax#9520]
The `is_leaf` option of the tree_flatten function is described as,

> an optionally specified function that will be called at each flattening step. It should return a boolean, which indicates whether the flattening should traverse the current object, or if it should be stopped immediately, with the whole subtree being treated as a leaf.

I just got bitten by this as (to me) it seems to imply `true` should be returned if the object needs to be traversed, and `false` if it is a leaf. I would suggest changing it to something clearer along the lines of:

> an optionally specified function that will be called at each flattening step. It should return a boolean, with true stopping the traversal and the whole subtree being treated as a leaf, and false indicating the flattening should traverse the current object.

**Comment by jakevdp** [comment]
Thanks for the report - that would be an improvement. Are you interested in preparing a pull request? If not, someone on our team can take care of it.

**Comment by GJBoth** [comment]
You're right - more an improvement than bug. No need to ask someone else, will prep a PR!

**Comment by 8bitmp3** [comment]
@jakevdp Assuming the issue is resolved, can be closed. WDYT?
