### ISSUE TITLE
`DeviceArray.__mul__` etc. don't respect `__jax_array__`

### ISSUE THREAD

**Issue by patrick-kidger** [google/jax#9538]
```python
import jax.numpy as jnp

class M:
    def __jax_array__(self):
        return jnp.array([1, 1])

M() * jnp.array([1, 1])
```
produces `TypeError: unsupported operand type(s) for *: 'M' and 'DeviceArray'`

In contrast `jnp.multiply(M(), jnp.array([1, 1]))` handles this just fine. No error, works as expected.

Also, NumPy handles this fine:
```python
import numpy as np

class M:
    def __array__(self):
        return np.array([1, 1])

M() * np.array([1, 1])  # no error!
```

**Comment by jakevdp** [comment]
Thanks for the report. I think the issue is we need to check for `__jax_array__` here: https://github.com/google/jax/blob/f02c6fcd728878f8a239de895eb67836fb2f9b46/jax/_src/numpy/lax_numpy.py#L6777
