### ISSUE TITLE
Segmentation fault when using `jit` with `__slots__`

### ISSUE THREAD

**Issue by jakevdp** [google/jax#9541]
Minimal reproduction:
```python
import jax

class CallableWithSlots:
  __slots__ = []
  def __call__(self):
    return 0.0

jax.jit(CallableWithSlots())
```
```pytb
Traceback (most recent call last):
  File "tmp.py", line 8, in <module>
    jax.jit(CallableWithSlots())
  File "/Users/vanderplas/github/google/jax/jax/_src/api.py", line 313, in jit
    return _cpp_jit(fun, static_argnums, static_argnames, device, backend,
  File "/Users/vanderplas/github/google/jax/jax/_src/api.py", line 481, in _cpp_jit
    cpp_jitted_f = jax_jit.jit(fun, cache_miss, get_device_info,
RuntimeError: Could not allocate weak reference!
Segmentation fault: 11
```

**Comment by hawkinsp** [comment]
I have a fix that makes this not crash in C++, although it will now throw a Python exception because the Python code also requires the callable be weak-referenceable. (There are easy workarounds, e.g., add space in `__slots__` for the weak ref list.)

**Comment by jakevdp** [comment]
Nice! A `TypeError` is far preferable to a segfault 😁

**Comment by zhangqiaorjc** [comment]
```python
  __slots__ = ['__weakref__']
```

works as per python documentation:

When __slots__ are defined for a given type, weak reference support is disabled unless a '__weakref__' string is also present in the sequence of strings in the __slots__ declaration

https://docs.python.org/3/reference/datamodel.html#notes-on-using-slots
