### ISSUE TITLE
jax.random.choice has undefined behavior when sampling without replacement and using probabilities

### ISSUE THREAD

**Issue by bycn** [google/jax#9548]
Summary: if enough weights/probabilities are zero such that sampling w/o replacement leads to too few possibilities to sample, jax should raise an error.
Simple case: 
```python
import jax
import jax.numpy as jnp

prob = jnp.zeros(10)
prob = prob.at[9].set(1)
jax.random.choice(jax.random.PRNGKey(5), jnp.arange(10), shape=(5,), replace=False, p=prob)
# DeviceArray([9, 0, 1, 2, 3], dtype=int32)
```
Numpy raises a 
```
ValueError: Fewer non-zero entries in p than size
```
with equivalent code.

Fix: 
https://github.com/google/jax/blob/main/jax/_src/random.py#L493
Here, do a check that the number of nonzero entries is >= desired number of entries.

**Comment by jakevdp** [comment]
Thanks for the report – the reason for this behavior is that JAX cannot raise warnings or errors that depend on the values within arrays. This is due to the nature of JAX's tracing and compilation.

Our best option here is to probably add a warning to the docstring, informing users that if there are not enough nonzero probabilities, the output is ill-defined.

**Comment by MichaelMarien** [comment]
Interesting, sure I'll open new PR with a warning in the docstring. OK if I just close the other one?

**Comment by jakevdp** [comment]
> Interesting, sure I'll open new PR with a warning in the docstring. OK if I just close the other one?

Sure, sounds good.

**Comment by patrick-kidger** [comment]
Ah nice -- that's where #8468 ended up! Thanks for the link. Once the details of that have been worked out (being able to stage `checkify.check` + merging `checkify.checkify` into `jax.jit` (?)) then that looks like it'll be a much more elegant replacement.
