### ISSUE TITLE
[feature request] move step count into opt_state

### ISSUE THREAD

**Issue by samuela** [google/jax#955]
The `jax.experimental.optimizers` module includes a bunch of very handy optimizers ready to go. However, it's a bit unwieldy to do all of the "bookkeeping" to get them working. In particular, I've found that the step parameter (in `update_fun(step, grads, opt_state)`) is a common source of bugs. For example, it's easy to put in `batch_ix` instead of `epoch * batches/epoch + batch_ix`. All this tedious arithmetic gets dangerous. Why not just throw the step parameter in the opt_state along with the rest of the state of the optimizer?

**Comment by samuela** [comment]
FWIW my workaround looks like
```python
from __future__ import annotations

from typing import NamedTuple, TypeVar

_OptState = TypeVar("_OptState")

class Optimizer:
  iteration: int

  def update(self, g) -> Optimizer:
    raise NotImplementedError()

  @property
  def value(self):
    raise NotImplementedError()

def make_optimizer(opt):
  opt_init, opt_update, get_params = opt

  class _Optimizer(NamedTuple, Optimizer):
    iteration: int
    opt_state: _OptState

    def update(self, g) -> Optimizer:
      return _Optimizer(
          iteration=self.iteration + 1,
          opt_state=opt_update(self.iteration, g, self.opt_state),
      )

    @property
    def value(self):
      return get_params(self.opt_state)

  def start(init_params):
    return _Optimizer(iteration=0, opt_state=opt_init(init_params))

  return start
```

**Comment by hawkinsp** [comment]
We're no longer trying to evolve the `jax.experimental.optimizers` API, in favor of projects like `optax` which are much better than `jax.experimental.optimizers` ever was!
