### ISSUE TITLE
Add ability to place computation on a specific GPU

### ISSUE THREAD

**Issue by afrozenator** [google/jax#957]
With multiple GPUs there should be a way to direct specific computations to run on a specific GPU.

Context: I want to run #gpu different models in parallel each on its own GPU.

The current best solution that comes to mind is to RPC between different machines, each with 1 GPU -- I'd like to avoid doing this.

@hawkinsp @mattjj

**Comment by hgt312** [comment]
Besides, is there a way to set default device to cpu?

**Comment by mattjj** [comment]
These features are already implemented, though they're somewhat experimental and the API is likely to change. @levskaya and @skye have been working on different parts of it.

Here's a way to do it now:

```python
import jax

gpus = jax.devices('gpu')
model1 = jax.jit(model1, device=gpus[0])
model2 = jax.jit(model2, device=gpus[1])
```

Let's leave this issue open until we've finalized the API, added tests, and also provided the right documentation.

**Comment by mattjj** [comment]
I think we should always allow explicit annotation on a `jit`, and just have a more sophisticated default policy (like follow-the-arguments-when-clear-and-error-otherwise).

**Comment by ziatdinovmax** [comment]
> These features are already implemented, though they're somewhat experimental and the API is likely to change. @levskaya and @skye have been working on different parts of it.
> 
> Here's a way to do it now:
> 
> ```python
> import jax
> 
> gpus = jax.devices('gpu')
> model1 = jax.jit(model1, device=gpus[0])
> model2 = jax.jit(model2, device=gpus[1])
> ```
> 
> Let's leave this issue open until we've finalized the API, added tests, and also provided the right documentation.

I wonder if the same approach works for TPU?

**Comment by jekbradbury** [comment]
Yes, it does. On a Cloud TPU (e.g. in Colab), `jax.devices()` returns 8 `TpuDevice` objects (corresponding to the 8 cores).

**Comment by ziatdinovmax** [comment]
Very nice. Thanks for the response!

**Comment by andyljones** [comment]
As a stopgap solution for setting the default device, I've found I can just set 

```CUDA_VISIBLE_DEVICES=0,1``` 

before importing JAX. Setting it to an empty string will force JAX to use the CPU.

That only works if you want the entire program on a single GPU mind you; I'd still like to a see a pytorch-style `with torch.device(i)` context manager.

**Comment by skye** [comment]
As of https://github.com/google/jax/pull/1916 or so, computation will "follow" data, meaning if some values are already placed on a specific device, downstream operations will also be placed on that device. For example, something like:
```python
x = device_put(1, jax.devices()[1])
y = x + 1
z = x + y
```
x, y, and z will all be on device 1 (prior to this new behavior, y and z would go back to the default device 0).

Combined with the device argument to jit, I believe this should give full control over where computations are executed. I'm gonna close this issue, but please comment if I'm missing something and I'll reopen!

(Apologies for not mentioning this earlier!)

**Comment by BoyuanJackChen** [comment]
I wonder if this works for flax optimizer?

**Comment by levskaya** [comment]
@BoyuanJackChen - there's nothing special about flax optimizers, they just operate on jax arrays like any other computation, so you should be able to target them if needed.

**Comment by n2cholas** [comment]
Is there any way to create `jax.numpy.array`s on a specific device, instead of creating them then moving them via `device_put`?

> Besides, is there a way to set default device to cpu?

Also, has this question been answered anywhere (@hgt312)?

**Comment by mattjj** [comment]
@n2cholas clearly we should improve our documentation around this (PRs welcome, though I'll open an issue so we don't drop it).

> Is there any way to create jax.numpy.arrays on a specific device, instead of creating them then moving them via device_put?

If you use `jnp.device_put(jnp.zeros(...), jax.devices()[1])` or similar, it'll do the creation on the device thanks to #1668. You can also use `jit`, as in

```python
partial(jit, device=jax.devices()[1])
def foo():
  return jnp.zeros(...)
```

(That second approach will handle more cases once #4038 is in, i.e. so that #3370 is on by default, but for now it should handle simple constant creation.)

 Other than zeros, ones, eye, etc. did you have some other kind of array creation in mind?

> Besides, is there a way to set default device to cpu?

You can use [the `JAX_PLATFORM_NAME` env var, or the `jax_platform_name` absl flag](https://github.com/google/jax/blob/4236eb2b5929b9643977553f7f988ca518b7df4e/jax/lib/xla_bridge.py#L53-L58), to set the default device. After a very quick glance I didn't see this in our documentation anywhere...

**Comment by n2cholas** [comment]
Thanks @mattjj for the quick reply (and sorry about deleting my comment here then opening the issue haha). #1668 has some really really cool stuff.

I would like to specify the device where a PRNG generates numbers. Specifically, in my JIT'd function, I have some computation running on the GPU and would like to sample random numbers on the CPU. Based on your response, it seems like JIT will take care of this for me and do the sampling on the CPU if I do something like `jax.device_put(jax.random.bernoulli(key), jax.devices('cpu')[0])`.

Outside of a JIT context, will the lazy sub-language allow JAX to execute `jax.device_put(jax.random.bernoulli(key), jax.devices('cpu')[0])` directly on the CPU?

**Comment by mattjj** [comment]
I suggest something like `jit(jax.random.bernoulli, static_argnums=2, device=jax.devices('cou')[0])` to get a version of bernoulli that will run on cpu. (You can also use `jit(..., backend='cpu)`, we need to de-duplicate the API.)

The lazy sublanguage stuff really only applies to special cases like jnp.zeros, so `jax.device_put(jax.random.bernoulli(key), jax.devices('cpu')[0])` will run the sampling on the default device (i.e. not the CPU in this case) then transfer.

Actually, maybe the most relevant part of the docs is [Controlling data and computation placement on devices](https://jax.readthedocs.io/en/latest/faq.html#controlling-data-and-computation-placement-on-devices) in the FAQ. That explains the computation-follows-data policy, which means an alternative to giving a `device` argument to `jit` you can write

```python
key = jax.device_put(key, jax.devices('cpu')[0])
jax.random.bernoulli(key)
```

Actually, I think that computation-follows-data control is better than using `jit(..., device=...)`.

**Comment by n2cholas** [comment]
Makes sense, thanks again!
