### ISSUE TITLE
[jax2tf] NotImplementedError: Call to gather cannot be converted with enable_xla=False

### ISSUE THREAD

**Issue by josephrocca** [google/jax#9572]
I see that there is [only partial support](https://github.com/google/jax/blob/main/jax/experimental/jax2tf/g3doc/no_xla_limitations.md#summary-table) for the `XlaGather` op conversion when using `enabled_xla=False` (needed in my case because I want to convert the saved model to tflite/tfjs). I'm wondering if more support for this op is on the roadmap?

Here's the full error that I'm seeing:
```
NotImplementedError
Traceback (most recent call last) [/usr/local/lib/python3.7/dist-packages/jax/experimental/jax2tf/impl_no_xla.py](https://localhost:8080/#) in _gather_using_tf_gather(operand, start_indices, dimension_numbers, slice_sizes, _in_avals)
    568     raise _xla_disabled_error(
    569         "gather",
--> 570         f"unsupported dimension_numbers '{dimension_numbers}'; op_shape={op_shape}."
    571     )
    572   # We added a trailing dimension of size 1

NotImplementedError: Call to gather cannot be converted with enable_xla=False. unsupported dimension_numbers 'GatherDimensionNumbers(offset_dims=(1,), collapsed_slice_dims=(0, 1), start_index_map=(0, 1))'; op_shape=(1, 30, 512).
```

Below is some code that reproduces this error. I've only just started playing around with `jax2tf` so apologies if I'm doing something silly here.
```
!pip install --upgrade flax transformers
```
```python
import jax
from jax.experimental import jax2tf
from jax import numpy as jnp

import numpy as np
import tensorflow as tf

from transformers import FlaxCLIPModel

clip = FlaxCLIPModel.from_pretrained("openai/clip-vit-base-patch32")

def score(pixel_values, input_ids, attention_mask):
    pixel_values = jax.image.resize(pixel_values, (3, 224, 224), "nearest")
    inputs = {"pixel_values":jnp.array([pixel_values]), "input_ids":input_ids, "attention_mask":attention_mask}
    outputs = clip(**inputs)
    return outputs.logits_per_image[0][0]

score_tf = jax2tf.convert(score, enable_xla=False)

my_model = tf.Module()
my_model.f = tf.function(score_tf, autograph=False, jit_compile=True, input_signature=[
  tf.TensorSpec([3, 40, 40], tf.float32),
  tf.TensorSpec([1, 30], tf.int32),
  tf.TensorSpec([1, 30], tf.int32),
])

model_name = 'pixel_text_score'
tf.saved_model.save(my_model, model_name, options=tf.saved_model.SaveOptions(experimental_custom_gradients=True))
```
Here's a public colab with that code: https://colab.research.google.com/drive/18jFruauFcKEJ_SjBZqn5z6AiPqQAfa1j?usp=sharing

Thanks!

**Comment by marcvanzee** [comment]
Thanks for filing this issue, we indeed have experimental support for gather without XLA support, but we haven't yet tested this extensively, so it is great you are trying this out.

It appears we don't properly implement multi-dimensional indexing right now. I actually found two bugs, the first is the one you also encountered.

**Bug 1: gather bug**

```py
def gather_fn1():
  op = jnp.arange(4).reshape((2, 2, 1))
  return op[[0], [0]]

jax2tf.convert(gather_fn1, enable_xla=False)()  # Should return: [[0]]
```
Outputs:
```
NotImplementedError: Call to gather cannot be converted with enable_xla=False. Unsupported arguments for gather: operand shape=(2, 2, 1), start_indices=[[0 0]], dimension_numbes=GatherDimensionNumbers(offset_dims=(1,), collapsed_slice_dims=(0, 1), start_index_map=(0, 1)), slice_sizes=(1, 1, 1), errors:
<function _gather_for_scalar_indexing at 0x13c82cf80>: ValueError('start_indices shape should be 1')
<function _gather_for_multidim_indexing at 0x13c834170>: ValueError('unsupported dimension numbers')
<function _gather_with_batch_dims at 0x13c834320>: ValueError("Batch dimensions in operand and start_indices don't agree")
```

As you can see, there are three paths we implemented for gather, and actually the `gather_for_multidim_indexing` should trigger, but it doesn't. We should simply implement more support here.

**Bug 2: clipping bug**

```py
def gather_fn2():
  op = jnp.arange(2).reshape((1, 2, 1))
  return op[[0], [0]]

jax2tf.convert(gather_fn2, enable_xla=False)()  # Should return: [[0]]
```
Outputs:
```
  File "/Users/marcvanzee/github/jax/jax/experimental/jax2tf/impl_no_xla.py", line 554, in wrapper
    return gather_fn(args)
  File "/Users/marcvanzee/github/jax/jax/experimental/jax2tf/impl_no_xla.py", line 691, in _gather_with_batch_dims
    start_indices = _clip(op_shape, args.start_indices, args.slice_sizes)
  File "/Users/marcvanzee/github/jax/jax/experimental/jax2tf/impl_no_xla.py", line 517, in _clip
    return tf.clip_by_value(tf.cast(start_indices, dtype=tf.int32), 0, max_start)
  File "/Users/marcvanzee/.pyenv/versions/3.7.10/lib/python3.7/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/marcvanzee/.pyenv/versions/3.7.10/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 7107, in raise_from_not_ok_status
    raise core._status_to_exception(e) from None  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.InvalidArgumentError: Incompatible shapes: [1,2] vs. [3] [Op:Minimum]
```

This seems like a bug in clipping. This case will trigger if you run your code with batch size 1 (which could be quite likely on mobile.

I will look into both issues.

**Comment by josephrocca** [comment]
Thanks Marc!! 🙏

**Comment by marcvanzee** [comment]
Hi @josephrocca, I've looked into your problem today. The problematic line in CLIP is the following:

```py
pooled_output = last_hidden_state[jnp.arange(last_hidden_state.shape[0]), input_ids.argmax(axis=-1)]
```

It seems that we can simplifying this to:

```py
pooled_output = last_hidden_state[:, input_ids.argmax()]
```

Which should convert fine, so if you are able to edit the source code of the CLIP model, you can change that line, which should unblock you immediately.

The reason that this does work is because the first code snippet calls `XlaGather` in a way that is not supported because we are selecting multiple indices in the first dimension. However, since this case actually selects _all_ indices, we can simply use a slice to select all elements in the dimension, which results in a simpler call to `XlaGather` that is supported.

In the meantime I will work on a fix so that this case will just work out of the box. Let me know if that works for you!

**Comment by josephrocca** [comment]
That fixed it, thanks @marcvanzee! `jax2tf` is awesome - I had no idea that this has been a thing since 2020. Seems like a very viable path to getting a lot of jax stuff working in the browser (which is my main use case area). I really appreciate the work y'all are doing to get this working & mature!

**Comment by marcvanzee** [comment]
Thanks for the feedback! Please do let us know when you manage to get any models running in the browser using jax2tf, we will gladly link to your examples from our README. Currently this project is still in experimental phase, so we can learn / benefit a lot from early users like you. So thank you back for experimenting with this! 😄

**Comment by gnecula** [comment]
@marcvanzee Is there a way to describe what uses of XlaGather are supported? We could then add this to an FAQ and include a link in the error message.

**Comment by marcvanzee** [comment]
> @marcvanzee Is there a way to describe what uses of XlaGather are supported? We could then add this to an FAQ and include a link in the error message.

This is now documented here: https://github.com/google/jax/blob/main/jax/experimental/jax2tf/g3doc/no_xla_limitations.md

I am closing this issue since it appears it is fixed.
