### ISSUE TITLE
jit-compilable "idx_n_th_occurence"

### ISSUE THREAD

**Issue by SimiPixel** [google/jax#9578]
Workarounds are also welcome, because i actually don't have a solution yet.
The example should be self-explanatory.
```python
@jax.jit 
def idx_n_th_occurence(operand, occurence, n=0):
    arr = jnp.where(operand==occurence, operand, jnp.nan)
    return jnp.where(arr==arr)[n]
```
Works fine *without* jit

**Comment by jakevdp** [comment]
If `n` is static, you could use:
```python
return jnp.where(operand==occurence, size=n + 1)[n]
```
If `n` is not static, you could use
```python
return jnp.where(operand==occurance, size=len(operand))[n]
```
You could optionally specify `fill_value`, which will indicate the value to return if there are fewer than `n + 1` true entries.

**Comment by SimiPixel** [comment]
Thank you! This works, even though i don't really see why my initial solution then doesn't.

**Comment by jakevdp** [comment]
Your initial solution doesn't work because it implicitly creates a dynamically-shaped array, which is not supported by JIT compilation.
