### ISSUE TITLE
Indexing multidim array causes massive slowdown in Jax 0.2.28

### ISSUE THREAD

**Issue by bycn** [google/jax#9592]
On Jax version 0.2.28: (doesn't reproduce on i.e. 0.2.15)
The following code runs extremely slow: 
```python
import jax
import jax.numpy as jnp
import time

def tester(carry, unused):
    selection = jnp.arange(1000)
    selected = carry[:, selection, ...]
    return carry, selected[0,0,0,0,0]
size = 8
starter = jnp.ones((10,2000,size,size,4))
start_time = time.time()
for i in range(200):
    print("time", time.time() - start_time) # 4+ seconds each iteration
    starter, _ = tester(starter, ())
```
Curiously: changing `size` to 7 makes the loop fast again (<< 1s per iteration, as in 0.2.15). Any idea what's going on here?

Replicated across TPU sizes colab, v2-8 and v3-8.

**Comment by hawkinsp** [comment]
Thanks for the report, I agree this is much slower than it should be. I filed a bug against the TPU compiler folks (Google bug b/219921462).

**Comment by bycn** [comment]
I need the latest version but I could stick with a smaller `size` for now. What sort of timescale would you expect this to get fixed? I'd appreciate a workaround if it is going to be more than a few weeks :)

**Comment by hawkinsp** [comment]
This issue has been fixed in the current HEAD version of the TPU compiler (as of about a week ago). If you update to a more recent libtpu, it should solve the issue.

**Comment by bycn** [comment]
@hawkinsp thanks for the fix but — how can I get that version?
https://github.com/google/jax/issues/9220 I tried to upgrade just the nightly but import crashes on TPUVM.
