### ISSUE TITLE
vmap gives wrong values when applied  to a piecewise linear function.

### ISSUE THREAD

**Issue by idnm** [google/jax#9633]
### Discussed in https://github.com/google/jax/discussions/9632

<div type='discussions-op-text'>

<sup>Originally posted by **idnm** February 18, 2022</sup>
I found this strange behavior of vmap which looks like a bug to me. Here is the code defining a piecewise linear function.

```
import jax.numpy as jnp
from jax import vmap
import matplotlib.pyplot as plt

def line(x, x0, y0, x1, y1):
    return (y1-y0)/(x1-x0)*x+(x0*y1-x1*y0)/(x0-x1)

def f(x, xmax, ymax, plato):

    segments = [x <= plato,
                (plato < x) & (x <= xmax - plato),
                (xmax - plato < x) & (x <= xmax + plato),
                (xmax + plato < x) & (x <= jnp.pi - plato),
                (jnp.pi - plato < x) & (x <= jnp.pi)
                ]

    functions = [line(x, 0, 0, plato, 0),
                 line(x, plato, 0, xmax - plato, ymax),
                 line(x, xmax - plato, ymax, xmax + plato, ymax),
                 line(x, xmax + plato, ymax, jnp.pi - plato, 1),
                 line(x, jnp.pi - plato, 1, jnp.pi, 1)]

    return jnp.piecewise(x, segments, functions)
```
Now I plot the resulting function using either vmap or a list comprehension to make an array of function values, and the two results do not agree.
```
xmax = jnp.pi/2
ymax = 2
plato=0.1

g = lambda x: f(x, xmax, ymax, plato)

x_sweep = jnp.linspace(0, jnp.pi, 100)
plt.plot(x_sweep, vmap(g)(x_sweep), label='vmap')  
plt.plot(x_sweep, [g(x) for x in x_sweep], label='list comprehension')
plt.legend()

```
![image](https://user-images.githubusercontent.com/13020565/154652912-fdcc9cda-1b22-422b-8c37-03782b1a592d.png)

What could that be?</div>

OK, this seems to be related to the version of `jax`. If the I run the above code in Colab  (with default 0.2.25 ) everything works fine, however if I upgrade to the newer version (0.3.0) by appending
```
!pip install --upgrade jaxlib
!pip install --upgrade jax
```
to the top of the file vmap goes bad.

**Comment by soraros** [comment]
I think it is a miscompilation bug related introduced in #9482, and has been fixed in #9563.

**Comment by hawkinsp** [comment]
That's correct. I think this is already fixed at head. We're working on a new release with the fix.

**Comment by mattjj** [comment]
@hawkinsp should we close this now, since it's fixed on main, or only after we update pypi?

**Comment by hawkinsp** [comment]
`jax` 0.3.1 is released and contains the fix. Sorry for the breakage!
