### ISSUE TITLE
jitted function hangs when a donated argument is passed twice

### ISSUE THREAD

**Issue by dominikgrewe** [google/jax#9635]
When accidentally passing in the same buffer to a jitted function twice and that buffer should be donated, the execution of the function just hangs making it hard to debug. Is it possible to catch this user error and return an error message instead?

This, for example, hangs on both TPU and GPU (CPU doesn't support argument donation):

```python
import jax
import jax.numpy as jnp

def add(x, y):
  return x + y

f = jax.jit(add, donate_argnums=(0,))
x = jnp.zeros((10,), jnp.float32)

f(x, x)  # Hangs
```

**Comment by mattjj** [comment]
Thanks for raising this!

@zhangqiaorjc is it clear to you where we should catch this error? Maybe in the PJRT runtime?

**Comment by zhangqiaorjc** [comment]
I remember @hawkinsp had a fix but didn't submit it. Looks like he might soon.

**Comment by jiyuuchc** [comment]
Had run into this same problem recently -- although the current version throws an error instead of hang.

Can I ask why JAX cannot simply accept the inputs, and make a copy of the buffer internally? It is not uncommon to have a pytree input, which has multiple leafs sharing the same buffer.

The current JAX behavior forces the user to copy on array assignment, which breaks the numpy convention of copy-on-write.

**Comment by mattjj** [comment]
Thanks for the question!

To make a copy, just don't use `donate_argnums`. That is, `donate_argnums` basically means "don't make a copy; instead you can reuse this buffer".

**Comment by mattjj** [comment]
Maybe you're saying: we could inside jax check whether multiple arguments tagged as donate-able correspond to the same buffer, and handle that correctly. Is that right?

**Comment by soraros** [comment]
@jiyuuchc I think the problem is you made a typo here?
```python
def __init__(self, initial_value):
  self.initial_value = initial_value
  self.update_value = initial_value  # <<< should have been updated_value?
```

**Comment by jiyuuchc** [comment]
It is not a typo.

Both variables start with the same value, but one serves as a backup storage for potential rollbacks.

________________________________________

**Comment by soraros** [comment]
@jiyuuchc Have you tried to run my code? For typo, I meant `updated_` vs `update_`.
