### ISSUE TITLE
Fresh conda jax installation is broken

### ISSUE THREAD

**Issue by jjyyxx** [google/jax#9643]
Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```bash
# On Ubuntu 20.04.3, conda-forge channel only
conda create -n test python=3.9 openssl=1 jax jaxlib=0.3.0
conda activate test
python -c 'import jax'
```

- [x] If applicable, include full error messages/tracebacks.

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:641] File already exists in database: tensorflow/compiler/xla/xla_data.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:2021] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Aborted (core dumped)
```

**Comment by hawkinsp** [comment]
We don't supply the conda packages: they are community-supported. Can you try from the official `pip` packages?

https://github.com/google/jax#installation

**Comment by hawkinsp** [comment]
I took a quick look, and I think it's a problem specific to how the conda-forge wheels are being built (different to how we distribute them). I filed an issue against the conda-forge jaxlib feedstock.

**Comment by hawkinsp** [comment]
This issue is reported to be fixed in the `conda-forge` feedstock. I haven't verified that myself. I'm not sure if new wheels have been released yet.
