### ISSUE TITLE
RuntimeError: UNKNOWN: PTX JIT compiler library not found

### ISSUE THREAD

**Issue by samuela** [google/jax#9644]
I'm getting a weird error when trying to `jit` things:
```
Traceback (most recent call last):
  File "/home/ubuntu/dev/research/lottery/cifar10_convnet_run.py", line 228, in <module>
    test_make_batcher()
  File "/home/ubuntu/dev/research/lottery/cifar10_convnet_run.py", line 87, in test_make_batcher
    for fn in [make_batcher(5, 2), jit(make_batcher(5, 2))]:
  File "/home/ubuntu/dev/research/lottery/cifar10_convnet_run.py", line 79, in make_batcher
    splits = list(jnp.arange(1, num_examples // batch_size + 1) * batch_size)
  File "/nix/store/ix119bzn54cgvsm98cidfdb4c8w0v1qc-python3.9-jax-0.3.0/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py", line 6747, in deferring_binary_op
    return binary_op(self, other)
RuntimeError: UNKNOWN: PTX JIT compiler library not found
in external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_asm_compiler.cc(56): 'cuLinkCreate(0, nullptr, nullptr, &link_state)'
```
What does this mean? What .so am I missing? I can confirm that I have `libnvidia-ptxjitcompiler.so`, `libnvidia-ptxjitcompiler.so.1`, and `libnvidia-ptxjitcompiler.so.495.44` all on my system.

Please:

- [x] Check for duplicate issues.
- [x] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

```python
from jax import jit
jit(lambda x: 2*x)
```

- [x] If applicable, include full error messages/tracebacks.
https://gist.github.com/samuela/7245561c382842d70a729caecbd11912

**Comment by yashk2810** [comment]
What's your driver version, jaxlib version, cuda version?

What command did you use to install jaxlib?

**Comment by samuela** [comment]
I ended up resolving this in a different way (https://discourse.nixos.org/t/using-cuda-enabled-packages-on-non-nixos-systems/17788). I don't have bandwidth to reproduce and investigate but I found the error message unclear. For people coming across this in the future, I would suggest trying with `LD_DEBUG=libs`.
