### ISSUE TITLE
Memory corruption with JAX>=0.2.27

### ISSUE THREAD

**Issue by dionhaefner** [google/jax#9651]
In the testing suite for [Veros](https://github.com/team-ocean/veros), we test for consistency with a Fortran reference code via `f2py`. For this, we essentially do this:

1. Do all variable setup in Python / JAX
2. Clone state to Fortran by doing `getattr(fortran_module, var_name)[...] = getattr(python_module, var_name)`
2. Run Python function that is being tested
3. Run corresponding Fortran function
4. Compare

Starting with JAX 0.2.27 I noticed that one test fails sometimes (~ every 3rd run) because the *Fortran* result has some NaNs sprinkled into it. I do not see this with older JAX versions or when using NumPy instead of JAX, so I have to believe that the JAX / XLA runtime is somehow meddling with the memory used by the Fortran routine. I have verified that what is being copied to Fortran (in step 2) is consistent between backends and does not trigger NaN outputs by itself. I have only tested this on CPU.

I'm at a loss how to debug this further. Maybe someone has a hunch what changed in 0.2.27 that could cause this?

**Comment by hawkinsp** [comment]
Is there a way we can reproduce, ideally as minimal as possible?

**Comment by dionhaefner** [comment]
If there are no leads I could try to create a Dockerfile that reproduces this, but no guarantees since I've only seen these failures on GH Actions so far, not locally 😕

**Comment by hawkinsp** [comment]
Nothing immediately comes to mind, so I think my best bet is to bisect the problem to the change that broke things. For that, I need a self-contained test that says "yes" or "no" that I can easily build and run at a bunch of jax/jaxlib versions.

**Comment by dionhaefner** [comment]
This reproduces it:

```Dockerfile
FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Etc/UTC

RUN apt-get update && \
  apt-get install -y \
    software-properties-common \
    git \
    build-essential \
    gfortran \
    python3-pip \
    libopenblas-dev \
    liblapack-dev

RUN adduser -disabled-password --gecos "" jax
USER jax
WORKDIR /home/jax

RUN pip3 install virtualenv --user

RUN python3 -m virtualenv /home/jax/env
ENV PATH=/home/jax/env/bin:$PATH

RUN pip install cython

# install veros
RUN git clone https://github.com/team-ocean/veros.git

WORKDIR /home/jax/veros

RUN pip install -e .[test,jax]

# build pyom2 fortran lib
ENV PYOM2_DIR=/home/jax/pyom2

RUN mkdir -p $PYOM2_DIR && \
    cp -r vendor/pyom2/* $PYOM2_DIR && \
    cd $PYOM2_DIR && \
    mv pyOM2_site_specific site_specific.mk_ && \
    tar xzf pyOM2.1.0.tar.gz && \
    git init && \
    for patchfile in ./patches/*.patch; do \
        git apply --whitespace=fix $patchfile; \
    done && \
    make -C py_src -j 4 || true && \
    cd -

CMD ["pytest", "-k", "biharmonic_friction", "--backend", "jax", "--pyom2-lib", "/home/jax/pyom2/py_src/pyOM_code.cpython-38-x86_64-linux-gnu.so", "."]
```

Output:

```bash
$ docker build -t jax-bug .
$ docker run jax-bug
============================= test session starts ==============================
platform linux -- Python 3.8.10, pytest-7.0.1, pluggy-1.0.0
rootdir: /home/jax/veros, configfile: pyproject.toml
plugins: cov-3.0.0, forked-1.4.0
collected 98 items / 97 deselected / 1 selected

test/pyom_consistency/friction_test.py F                                 [100%]

=================================== FAILURES ===================================
_ test_biharmonic_friction[/home/jax/pyom2/py_src/pyOM_code.cpython-38-x86_64-linux-gnu.so] _
pyom2_lib = '/home/jax/pyom2/py_src/pyOM_code.cpython-38-x86_64-linux-gnu.so'

    def test_biharmonic_friction(pyom2_lib):
        vs_state, pyom_obj = get_random_state(pyom2_lib, extra_settings=TEST_SETTINGS)
        vs_state.variables.update(friction.biharmonic_friction(vs_state))
        pyom_obj.biharmonic_friction()
>       compare_state(vs_state, pyom_obj)

test/pyom_consistency/friction_test.py:72: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

vs_state = VerosState(
    settings = VerosSettings(
        identifier = 'UNNAMED',
        nx = 70,
        ny = 60,
        nz...la_extension.DeviceArray'> with shape (74, 64), dtype float64
    ),
    diagnostics = {},
    plugin_interfaces = ()
)
pyom_obj = <module 'pyOM_code' from '/home/jax/pyom2/py_src/pyOM_code.cpython-38-x86_64-linux-gnu.so'>
atol = 1e-10, rtol = 1e-08, include_ghosts = False, allowed_failures = []
normalize = False

    def compare_state(
        vs_state,
        pyom_obj,
        atol=1e-10,
        rtol=1e-8,
        include_ghosts=False,
        allowed_failures=None,
        normalize=False,
    ):
        IGNORE_SETTINGS = ("congr_max_iterations",)
    
        if allowed_failures is None:
            allowed_failures = []
    
        pyom_state = state_from_pyom(pyom_obj)
    
        def assert_setting(setting):
            vs_val = vs_state.settings.get(setting)
            setting = VEROS_TO_PYOM_SETTING.get(setting, setting)
            if setting is None or setting in IGNORE_SETTINGS:
                return
    
            pyom_val = pyom_state.settings.get(setting)
            assert vs_val == pyom_val, (vs_val, pyom_val)
    
        def assert_var(var):
            vs_val = vs_state.variables.get(var)
    
            var = VEROS_TO_PYOM_VAR.get(var, var)
            if var is None:
                return
    
            if var not in pyom_state.variables:
                return
    
            pyom_val = pyom_state.variables.get(var)
    
            if var in ("tau", "taup1", "taum1"):
                assert pyom_val == vs_val + 1
                return
    
            if not include_ghosts:
                vs_val = remove_ghosts(vs_val, vs_state.var_meta[var].dims)
                pyom_val = remove_ghosts(pyom_val, pyom_state.var_meta[var].dims)
    
            if normalize:
                vs_val, pyom_val = _normalize(vs_val, pyom_val)
    
            np.testing.assert_allclose(vs_val, pyom_val, atol=atol, rtol=rtol)
    
        passed = True
    
        for setting in vs_state.settings.fields():
            try:
                assert_setting(setting)
            except AssertionError as exc:
                if setting not in allowed_failures:
                    print(f"{setting}:{indent(str(exc), ' ' * 4)}")
                    passed = False
    
        for var in vs_state.variables.fields():
            try:
                assert_var(var)
            except AssertionError as exc:
                if var not in allowed_failures:
                    print(f"{var}:{indent(str(exc), ' ' * 4)}")
                    passed = False
    
>       assert passed
E       assert False

test/pyom_consistency/test_base.py:88: AssertionError
----------------------------- Captured stdout call -----------------------------
K_diss_h:
    Not equal to tolerance rtol=1e-08, atol=1e-10

    x and y nan location mismatch:
     x: array([[[0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.460651e-12,
             1.329739e-12, 6.892134e-13],
            [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 7.309537e-13,...
     y: array([[[0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 1.460651e-12,
             1.329739e-12, 6.892134e-13],
            [0.000000e+00, 0.000000e+00, 0.000000e+00, ..., 7.309537e-13,...
=========================== short test summary info ============================
FAILED test/pyom_consistency/friction_test.py::test_biharmonic_friction[/home/jax/pyom2/py_src/pyOM_code.cpython-38-x86_64-linux-gnu.so]
====================== 1 failed, 97 deselected in 10.15s =======================
```

Should be sufficient for your yes / no answer (better to run it 3x in a row or so since it can pass randomly). 

Let me know if I should boil it down further, e.g. by stripping away `pytest`.

**Comment by hawkinsp** [comment]
This bug is extremely strange. I'm not even sure it's a JAX bug yet. I've spent the best part of two days trying to track it down and I've had no success yet.

A few observations:
* lowering the XLA optimization level `XLA_FLAGS=--xla_backend_optimization_level=2` makes the problem go away. This makes me suspect that the MLIR change is actually innocent: it means that we feed slightly different input to XLA, which get compiled and optimized slightly differently.
* Initially, I was thinking "maybe this is a race condition". But I tried adding code to force the JAX computation to block until completion (by calling `.block_until_ready()` on all the variable outputs) and the bug still occurs.
* The bug *only* occurs if the pyom2 code runs *after* the JAX code. Not before!
* Apparently trivial changes that should not touch *any* array data also make the bug go away. e.g., I added, after the code blocking until the jax computation completes:

```
    for var in list(vs_state.variables.keys()):
        val = getattr(pyom_obj.main_module, var, None)
        if val is not None:
            h = np.ones_like(np.asarray(val))
```
and that makes the bug go away reliably! All this does is allocate *new* arrays that are disjoint from any that exist, and it does so after JAX is done running anything. So something odd is happening.

* I tried printing sha256sums of all of the pyom2 array state before and after the jax code runs.  There was no change. I can't even prove any inputs changed!

At this point I have very few tools left: I can't tell which part of the pyom2 state was corrupted or even if it *is* pyom2's state being corrupted.

The only tool I have left is to minimize the example even further, e.g., could we try to extract just the biharmonic friction kernel out of pyom2 so we can make an even smaller reproduction that is more self-contained? "Making the example smaller until I can understand it" is the only tool I have left. Any help you can give in minimizing the example further would be greatly appreciated.

**Comment by dionhaefner** [comment]
Yikes, what a mess. Thanks for investigating.

> I tried printing sha256sums of all of the pyom2 array state before and after the jax code runs. There was no change. I can't even prove any inputs changed!

I tried something similar: I dumped the PyOM2 state to a pickle file and ran the routine on the pickled state in a different file that doesn't use JAX. You probably guessed it; no NaNs. So the PyOM2 state looks fine until the Fortran routine runs.

How about I compile some print statements into the Fortran code and see where things go haywire.

But you are right, this could also be a bug in f2py, gfortran, the Linux kernel, .......
I remember that JAX had some issues with wrapped Fortran code before, see #6471 and #6823. These are a bit different because it's a compile time hang on GPU, but they also involve Fortran code running through Python...

Anyway, I'll report back when I know where this manifests first.

**Comment by PhilipVinc** [comment]
Maybe [rr](https://rr-project.org/) can help? 
It records all instructions executed, and you can inspect the heap and stack at all times...

**Comment by dionhaefner** [comment]
Oh my god. I'm so sorry. This turned out to be a bug in PyOM2 :man_facepalming: 

The problem is this:

```fortran
 real*8 :: del2(is_pe-onx:ie_pe+onx,js_pe-onx:je_pe+onx,nz)
 ! some other stuff...

 do j=js+1,je
   do i=is+1,ie
    del2(i,j,:)= (flux_east(i,j,:) - flux_east(i-1,j,:))/(cost(j)*dxu(i)) &
                +(flux_north(i,j,:) - flux_north(i,j-1,:))/(cost(j)*dyt(j))
  enddo
 enddo
```

So `del2` is allocated, but then only written from `start+1`. Therefore the first element is *uninitialized memory*, which just so happened to consistently contain NaN values with this particular stack. *This is why it went away when you allocated other stuff before the routine*, you pushed it to a different location in memory that didn't have NaNs :grimacing: 

To make things worse, the value of `del2` at this location drops out later, so the bug is *only* triggered when the allocated memory contains NaNs (no finite value will trigger it).

Anyway, terribly sorry for wasting your time, and I promise to look closer before reporting next time.

**Comment by hawkinsp** [comment]
I'm relieved you found it! We take wrong outputs very seriously.

In general, this is a bug that [MemorySanitizer](https://clang.llvm.org/docs/MemorySanitizer.html) would catch very easily. I don't know if MemorySanitizer works for Fortran code: we mostly use the LLVM/Clang version of msan on C++ code, but there's no LLVM fortran compiler yet so that won't work. Perhaps there is a GCC version that works for gfortran. I am eagerly awaiting an LLVM fortran compiler for this reason alone!

**Comment by soraros** [comment]
@hawkinsp Isn't there flang?

**Comment by hawkinsp** [comment]
@soraros As I understand it, there's an old out-of-tree flang that is more complete but depends on a really old LLVM fork, and its in-tree successor (also `flang`) that can't yet generate code. The classic situation: choose either "deprecated" or "not ready yet". But it looks like progress is happening!
