### ISSUE TITLE
Documentation incorrect for most of jax.nn.initializers

### ISSUE THREAD

**Issue by Sohl-Dickstein** [google/jax#9665]
The [documentation](https://jax.readthedocs.io/en/latest/jax.nn.initializers.html) for initializers in the `jax.nn.initializers` module is correct (though with broken markdown bullet lists) for the `variance_scaling` initializer. All other initializers either have no documentation, or incorrectly inherit the variance_scaling documentation.

**Comment by hawkinsp** [comment]
#9788 adds a lot more documentation to `jax.nn.initializers`.

(Mostly there was no documentation. Many functions copied the `variance_scaling` documentation because they were defined as `functools.partial` applications on `variance_scaling`. I fixed this.)
