### ISSUE TITLE
'pwr9' is not a recognized processor for this target (ignoring processor)

### ISSUE THREAD

**Issue by HanGuo97** [google/jax#9670]
This is a build at `jaxlib-v0.1.76` on a `ppc64le` machine. When running with GPUs, the following program executes without error. However, when running with CPUs, it fails. I have two questions, and thanks in advance for the help!

1. What is the cause of the error, and is there any way to fix it? Presumably, this is caused by the use of `ppc64le` CPUs, but I'm not super familiar with these.
2. I wouldn't mind having this issue as long as programs run using GPUs. However, would the following issue on the CPU side cause some (silent/subtle) issues when executing on GPUs? Put it in a different way, if I only use GPUs, do I need to worry about the error on the CPUs side?

Please:

- [x] Check for duplicate issues.
- [ ] Provide a complete example of how to reproduce the bug, wrapped in triple backticks like this:

- [x] If applicable, include full error messages/tracebacks.
```
(py38)> ipython
Python 3.8.12 (default, Oct 12 2021, 13:02:29) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.31.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import jax, jax.numpy as jnp

In [2]: jax.config.update("jax_platform_name", "cpu")

In [3]: jnp.zeros([3])
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
'pwr9' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
Aborted (core dumped)
```

**Comment by hawkinsp** [comment]
That presumably means that we aren't linking in the right pieces of LLVM for the power architecture, or we aren't configuring them correctly. This only affects computation on CPU, of course. GPU will work fine, so long as you don't need to use CPU for anything. You'll know if you hit it: things will just fail.

As far as I know, the only place where XLA/CPU has anything particularly architecture specific is in which backends we link in: https://github.com/tensorflow/tensorflow/blob/35001a33e50fe38c5c2718feba663a90f57d9fdf/tensorflow/compiler/xla/service/cpu/BUILD#L305

In particular, are we actually correctly enabling the power case during your build?

If you wanted to debug the problem, I'd try building JAX from source with a checkout of TF from head (see the JAX WORKSPACE file for details on how to point JAX to a TF checkout). I might then verify the right backend is being linked in, e.g., try replacing the build target with one that doesn't exist and verify the build fails.

**Comment by HanGuo97** [comment]
Understand, thanks for the explanations -- these are very clear!
