### ISSUE TITLE
how to detect if GPU is being used? (feature request)

### ISSUE THREAD

**Issue by murphyk** [google/jax#971]
In TF and PyTorch, there is an easy way to tell if the GPU is being used (see below).
How can we do this with jax? 

import tensorflow as tf
if tf.test.is_gpu_available():
    print(tf.test.gpu_device_name())
else:
    print("TF cannot find GPU")

import torch
import torchvision
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("Torch cannot find GPU")

**Comment by hawkinsp** [comment]
There's no true public API for this yet, but for right now you can do this:
```
from jax.lib import xla_bridge
print(xla_bridge.get_backend().platform)
```
and it will print `cpu`, `gpu`, or `tpu`. But note that API is internal and subject to change.

I agree we need a supported API, although exactly how that API will look will almost certainly evolve as we grow support for multiple kinds of devices in the same process.

Also note that if no GPU is found, JAX currently prints a loud warning the first time you run an op:
```
xla_bridge.py:130: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
```

Do those address your immediate need, or do you need something better soon?

**Comment by murphyk** [comment]
Thanks, that works.

**Comment by mattjj** [comment]
Closing this because I think we sorted out the current solution. As Peter mentioned, we'll likely make and document a more general API at some point.

**Comment by avital** [comment]
@hawkinsp shared this:

> You can look at `jax.devices()`. For example, to see if you're connected to an accelerator, check `jax.devices()[0].platform != "cpu"`.
> 
> `devices` returns devices from the preferred platform, and we always prefer an accelerator if you have one

**Comment by hawkinsp** [comment]
Here's a slightly better thing to use: `jax.default_backend()`. JAX defaults to a GPU or TPU if you have one. So you can just check it doesn't return `"cpu"`.

**Comment by roger-creus** [comment]
If I have multiple CPUs and GPUs in a cluster, will jax use them all or will just use 1cpu and 1gpu and have the others idle?

**Comment by OverLordGoldDragon** [comment]
Still desired. Proposed approaches don't seem to detect if a GPU _is available_; what if there's both GPU and TPU? Also that they're "subject to change". Current best seems to be a Python classic, though it's perhaps slow:

```python
def jax_has_gpu():
    try:
        _ = jax.device_put(jax.numpy.ones(1), device=jax.devices('gpu')[0])
        return True
    except:
        return False
````

**Comment by innat-asj** [comment]
```python
>>> import jax
>>> jax.default_backend()
'gpu'
>>> def jax_has_gpu():
...     try:
...         _ = jax.device_put(jax.numpy.ones(1), device=jax.devices('gpu')[0])
...         return True
...     except:
...         return False
... 
>>> jax_has_gpu()
True
>>> 
```
