### ISSUE TITLE
Escaped tracer when evaluationg gradients through cpu-parallelised code

### ISSUE THREAD

**Issue by LouisDesdoigts** [google/jax#9728]
Hey Jax team, I'm currently trying to deploy optical modelling code across multiple CPUs for faster model evaluation and optimisation. 

Here is a short overview of what the code is doing:

We have a low level function modelling our optical system `get_psfs(x, y, osys)` that is being deployed across multiple CPUs over a 1-D array of the first two input parameters. I have tried multiple ways of getting this to deploy in parallel with pmap, vmap,. Note the 'osys' object is a non-JAX type defining the optical system we are using so it must be set to static. These are the ways I have tried:

```
psfs_parallel = jit(vmap(get_psfs, inaxes=(0, 0, None), static_argnums=2, backend=cpu)
```

```
import os
os.environ['XLA_FLAGS'] = '--xla_force_host_platform_device_count=100' # we are passing in (100,) shaped vectors
psfs_parallel = pmap(get_psfs, inaxes=(0, 0, None), static_broadcasted_argnums=2)
```
Note: the XLA_FLAG is set at the start of the script as required.

These are then wrapped by a loss function
```
def loss(X, data, osys):
    xs, ys = X[:100], X[100:]
    image = np.sum(psfs_parallel(xs, ys, osys), axis=0)
    return np.sum(np.square(data - image))

loss_grad = value_and_grad(loss, static_argnums=(1, 2))
```

`np.sum(psfs_parallel(xs, ys, osys), axis=0)` works as expected and can be evaluated many times. The issue arises from trying to calculate the gradients through the loss function. 

`loss_grad()` can be evaluated a single time successfully and returns non-zero and non-nan gradients, but upon calling it a second time throws this error: (The full stack trace is at the bottom of the post!)

UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state.
Details: Different traces at same level: Traced<ShapedArray(float64[100,100]):JaxprTrace(level=0/0)>, JaxprTrace(level=0/0).

I have searched extensively and can not find how exactly to locate the source of the problem, or how to fix it. I suspect there maybe a problem in the way I am composing this, as the same error arises using either the jitted vmap or pmap. As far as I can tell this can arise from operating on an the attributes of an object rather than passing around native jax types, however my understanding is that this is required for all jitted or grad() functions and I have never encountered this problem before trying to parallelise over CPUs.

Could this be an issue with the way jax deploys across CPUs? Am I composing these functions appropriately for CPU parallelisation?

Unfortunately this code is running on older versions of jax and jaxlib because we have not had time to re-script our underlying modelling code to integrate with jax 0.2x +. We instead run on 
jax==0.1.77
jaxlib==0.1.57 

Please let me know if you have an idea about whats going on!
Cheers

---------------------------------------------------------------------------
FilteredStackTrace                        Traceback (most recent call last)
<ipython-input-23-40b1b0542173> in <module>
      2 # grads = error_grad(X_true, sim_params, data, new_osys)
----> 3 grads = error_grad(X_true, sim_params, data, osys)

<ipython-input-13-671eb64076d6> in error_min(X, args, data, osys)
     53 #     psfs = model(X, args, osys)
---> 54     psfs = model_min(X, args, osys)
     55     error = np.sum(np.square(psfs-data))

<ipython-input-13-671eb64076d6> in model_min(X, args, osys)
     43 #     print(x)
---> 44     psf_stack = calc_fresnel_psf_vmap(xs_in, ys_in, Fres, wl)
     45 #     psf_stack = calc_fresnel_psf_pmap(xs_in, ys_in, Fres, wl)

FilteredStackTrace: jax.core.UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state.
Details: Different traces at same level: Traced<ShapedArray(float64[100,100]):JaxprTrace(level=0/0)>, JaxprTrace(level=0/0).

The stack trace above excludes JAX-internal frames.
The following is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

UnexpectedTracerError                     Traceback (most recent call last)
<ipython-input-23-40b1b0542173> in <module>
      1 # new_osys = get_fresnel_osys(aperture, pupil_npix, npix, pix_size, fl, fl_shift, beam_ratio, wl)
      2 # grads = error_grad(X_true, sim_params, data, new_osys)
----> 3 grads = error_grad(X_true, sim_params, data, osys)

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    134   def reraise_with_filtered_traceback(*args, **kwargs):
    135     try:
--> 136       return fun(*args, **kwargs)
    137     except Exception as e:
    138       if not is_under_reraiser(e):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/api.py in value_and_grad_f(*args, **kwargs)
    809     tree_map(partial(_check_input_dtype_grad, holomorphic), dyn_args)
    810     if not has_aux:
--> 811       ans, vjp_py = _vjp(f_partial, *dyn_args)
    812     else:
    813       ans, vjp_py, aux = _vjp(f_partial, *dyn_args, has_aux=True)

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/api.py in _vjp(fun, *primals, **kwargs)
   1854   if not has_aux:
   1855     flat_fun, out_tree = flatten_fun_nokwargs(fun, in_tree)
-> 1856     out_primal, out_vjp = ad.vjp(flat_fun, primals_flat)
   1857     out_tree = out_tree()
   1858   else:

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/interpreters/ad.py in vjp(traceable, primals, has_aux)
    108 def vjp(traceable, primals, has_aux=False):
    109   if not has_aux:
--> 110     out_primals, pvals, jaxpr, consts = linearize(traceable, *primals)
    111   else:
    112     out_primals, pvals, jaxpr, consts, aux = linearize(traceable, *primals, has_aux=True)

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/interpreters/ad.py in linearize(traceable, *primals, **kwargs)
     95   _, in_tree = tree_flatten(((primals, primals), {}))
     96   jvpfun_flat, out_tree = flatten_fun(jvpfun, in_tree)
---> 97   jaxpr, out_pvals, consts = pe.trace_to_jaxpr(jvpfun_flat, in_pvals)
     98   out_primals_pvals, out_tangents_pvals = tree_unflatten(out_tree(), out_pvals)
     99   assert all(out_primal_pval.is_known() for out_primal_pval in out_primals_pvals)

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/interpreters/partial_eval.py in trace_to_jaxpr(fun, pvals, instantiate, stage_out, bottom, trace_type)
    420   with core.new_main(trace_type, bottom=bottom) as main:
    421     fun = trace_to_subjaxpr(fun, main, instantiate)
--> 422     jaxpr, (out_pvals, consts, env) = fun.call_wrapped(pvals)
    423     assert not env
    424     del main

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/linear_util.py in call_wrapped(self, *args, **kwargs)
    149 
    150     try:
--> 151       ans = self.f(*args, **dict(self.params, **kwargs))
    152     except:
    153       # Some transformations yield from inside context managers, so we have to

<ipython-input-13-671eb64076d6> in error_min(X, args, data, osys)
     52 def error_min(X, args, data, osys):
     53 #     psfs = model(X, args, osys)
---> 54     psfs = model_min(X, args, osys)
     55     error = np.sum(np.square(psfs-data))
     56     return error

<ipython-input-13-671eb64076d6> in model_min(X, args, osys)
     42 
     43 #     print(x)
---> 44     psf_stack = calc_fresnel_psf_vmap(xs_in, ys_in, Fres, wl)
     45 #     psf_stack = calc_fresnel_psf_pmap(xs_in, ys_in, Fres, wl)
     46     psf_arrays = fluxes_in * psf_stack.reshape([Nims, Nstars, npix, npix])

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/traceback_util.py in reraise_with_filtered_traceback(*args, **kwargs)
    134   def reraise_with_filtered_traceback(*args, **kwargs):
    135     try:
--> 136       return fun(*args, **kwargs)
    137     except Exception as e:
    138       if not is_under_reraiser(e):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/api.py in f_jitted(*args, **kwargs)
    206       _check_arg(arg)
    207     flat_fun, out_tree = flatten_fun(f, in_tree)
--> 208     out = xla.xla_call(
    209         flat_fun,
    210         *args_flat,

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in bind(self, fun, *args, **params)
   1144 
   1145   def bind(self, fun, *args, **params):
-> 1146     return call_bind(self, fun, *args, **params)
   1147 
   1148   def process(self, trace, fun, tracers, params):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in call_bind(primitive, fun, *args, **params)
   1136   else:
   1137     tracers = map(top_trace.full_raise, args)
-> 1138     outs = primitive.process(top_trace, fun, tracers, params)
   1139   return apply_todos(env_trace_todo(), map(full_lower, outs))
   1140 

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in process(self, trace, fun, tracers, params)
   1147 
   1148   def process(self, trace, fun, tracers, params):
-> 1149     return trace.process_call(self, fun, tracers, params)
   1150 
   1151   def post_process(self, trace, out_tracers, params):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/interpreters/ad.py in process_call(self, call_primitive, f, tracers, params)
    273     update_params = call_param_updaters.get(call_primitive)
    274     new_params = update_params(params, nz_tangents) if update_params else params
--> 275     result = call_primitive.bind(f_jvp, *primals, *nonzero_tangents, **new_params)
    276     primal_out, tangent_out = tree_unflatten(out_tree_def(), result)
    277     return [JVPTracer(self, p, t) for p, t in zip(primal_out, tangent_out)]

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in bind(self, fun, *args, **params)
   1144 
   1145   def bind(self, fun, *args, **params):
-> 1146     return call_bind(self, fun, *args, **params)
   1147 
   1148   def process(self, trace, fun, tracers, params):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in call_bind(primitive, fun, *args, **params)
   1136   else:
   1137     tracers = map(top_trace.full_raise, args)
-> 1138     outs = primitive.process(top_trace, fun, tracers, params)
   1139   return apply_todos(env_trace_todo(), map(full_lower, outs))
   1140 

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in process(self, trace, fun, tracers, params)
   1147 
   1148   def process(self, trace, fun, tracers, params):
-> 1149     return trace.process_call(self, fun, tracers, params)
   1150 
   1151   def post_process(self, trace, out_tracers, params):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/interpreters/partial_eval.py in process_call(self, primitive, f, tracers, params)
    179                   else PartialVal.unknown(mapped_aval(pval[0]))
    180                   for pval, is_mapped in zip(in_pvals, params['mapped_invars'])]
--> 181     jaxpr, out_pvals, consts, env_tracers = self.partial_eval(
    182         f, in_pvals, partial(primitive.bind, **params))
    183     if primitive.map_primitive:

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/interpreters/partial_eval.py in partial_eval(self, f, pvals, app)
    282     out_consts, consts = split_list(out_flat, [len(out_flat)-len(jaxpr.constvars)])
    283     out_pvs = map(PartialVal, zip(out_avals, out_consts))
--> 284     env_tracers = map(self.full_raise, env)
    285     return jaxpr, out_pvs, consts, env_tracers
    286 

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/util.py in safe_map(f, *args)
     33   for arg in args[1:]:
     34     assert len(arg) == n, 'length mismatch: {}'.format(list(map(len, args)))
---> 35   return list(map(f, *args))
     36 
     37 def unzip2(xys):

/import/morgana2/snert/louis/anaconda3/envs/morph/lib/python3.8/site-packages/jax/core.py in full_raise(self, val)
    390                                  .format(val, self))
    391     else:  # val._trace.level == self.level:
--> 392       raise escaped_tracer_error("Different traces at same level: {}, {}"
    393                                  .format(val, self))
    394 

UnexpectedTracerError: Encountered an unexpected tracer. Perhaps this tracer escaped through global state from a previously traced function.
The functions being transformed should not save traced values to global state.
Details: Different traces at same level: Traced<ShapedArray(float64[100,100]):JaxprTrace(level=0/0)>, JaxprTrace(level=0/0).

**Comment by LouisDesdoigts** [comment]
Okay so I have found a work around to this. I am able to successfully calculate gradients through this system by creating a copy of the `osys` object using `copy.deepcopy()` before every call of loss_grad(). 

I am curious if there is a better way to solve this problem?

**Comment by PhilipVinc** [comment]
I think you might be storing in `osys` some intermediate arrays in your `get_psfs` function, and you are not supposed to do this, because when operating under jax transformations such as jit/vmap/grad, those arrays are not really arrays, but tracers, and you should not 'capture' them in your 'static' data structures.

By the way, a much better approach to 'static' data structures (that helps you not do errors) is to use [`flax.struct.dataclass`](https://flax.readthedocs.io/en/latest/flax.struct.html#).
Those are frozen dataclasses, so you they oblige you not to store intermediate data inside of them. Moreover they help you distinguish 'mutable' data such as arrays from compile-time static data.

**Comment by zhangqiaorjc** [comment]
Perhaps `with jax.checking_leaks():` can help you narrow down where the tracer leak happens in `get_psfs`

**Comment by zhangqiaorjc** [comment]
Since this seems to be a user-function not being pure, and not a JAX bug, let me close this issue.
