### ISSUE TITLE
jax releases html page needs HTML doctype

### ISSUE THREAD

**Issue by hawkinsp** [google/jax#9770]
`pip` issued the following warning to me when installing from the GCS bucket:

```
warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://storage.googleapis.com/jax-releases/jax_releases.html

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
```

It seems like there's little downside to adding a doctype, so we should probably just do that.

**Comment by jakevdp** [comment]
Is this similar to the issue reported in #5410?

**Comment by hawkinsp** [comment]
I think it's related to the issue in the last comment in that issue, but maybe not the same as the entire issue?

This appears to exhibit on the latest `pip`, btw, so try `pip --upgrade pip`.

**Comment by yashk2810** [comment]
This should now be fixed!

**Comment by yashk2810** [comment]
I am going to close this. Feel free to open if its not fixed.

**Comment by hawkinsp** [comment]
(It won't be fixed until we regenerate the index, but that can wait for the next release.)

**Comment by yashk2810** [comment]
I regenerated the index. We don't need to wait for the next release.
