### ISSUE TITLE
FloatingPointError for expit on large negative values

### ISSUE THREAD

**Issue by cooijmanstim** [google/jax#980]
This results in a FloatingPointError for `k >= 4`:

```python
import numpy as onp
import jax.numpy as np
from jax.scipy.special import expit
from jax.config import config
config.update("jax_debug_nans", True)
k = 4
x = -1e20 * np.ones(k)
print(x)
print(expit(x))
```

**Comment by cooijmanstim** [comment]
Related: #972

**Comment by hawkinsp** [comment]
https://github.com/google/jax/pull/991 updated XLA to a new version that turns off approximate semantics for reciprocals by default. This fixes the problem in this issue, although it requires that you either rebuild Jaxlib from source or wait for us to make a new release. Hope that helps!
