### ISSUE TITLE
ensure_compile_time_eval doc example fails

### ISSUE THREAD

**Issue by eelregit** [google/jax#9823]
The example of [ensure_compile_time_eval](https://jax.readthedocs.io/en/latest/_autosummary/jax.ensure_compile_time_eval.html)

```python
import jax
import jax.numpy as jnp

print(jax.__version__)  # 0.3.1

@jax.jit
def f(x):
    with jax.ensure_compile_time_eval():
        y = jnp.sin(3.0)
        z = jnp.sin(y)
        #z = z.item()  # adding this works
    if z > 0:  # the value of z is availble and can be used in control flow
        return jnp.sin(x)
    else:
        return jnp.cos(x)
    
f(0)
```
gives ConcretizationTypeError.

Converting z to python float works.

**Comment by mattjj** [comment]
Hah, oops, thanks! That makes sense. I'm embarrassed that I apparently didn't test this...

Also putting the `z > 0` inside the context manager works, i.e. having a line like `positive = z > 0` and then testing `if positive`.
