### ISSUE TITLE
Autodidax has some bugs involving reduce_sum

### ISSUE THREAD

**Issue by ezyang** [google/jax#9865]
This works in JAX:

```python
import jax
from jax import grad, vmap
import jax.numpy as np

def simple(a):
  b = a
  t = a + b
  return t * b

def f(a):
  L0 = np.sum(simple(a))
  return L0

def g(a):
  dL0_da = vmap(grad(f), in_axes=0)(a)
  L1 = np.sum(dL0_da * dL0_da)
  return L1

key = jax.random.PRNGKey(0)
print(grad(g)(jax.random.normal(key,(2,4))))
```

However, the same code does not work in autodidax:

```
def simple(a):
  b = a
  t = a + b
  return t * b

def f(a):
  L0 = reduce_sum(simple(a))
  return L0

def g(a):
  dL0_da = vmap(grad(f), in_axes=0)(a)
  L1 = reduce_sum(dL0_da * dL0_da)
  return L1

print(grad(g)(np.random.rand(2,4)))
```

gives

```
[<ipython-input-27-03f392c346bd>](https://localhost:8080/#) in batched_f(*args)
     17     args_flat, in_tree = tree_flatten(args)
     18     in_axes_flat, in_tree2 = tree_flatten(in_axes)
---> 19     if in_tree != in_tree2: raise TypeError
     20     f_flat, out_tree = flatten_fun(f, in_tree)
     21     outs_flat = vmap_flat(f_flat, in_axes_flat, *args_flat)

TypeError:
```

Actually, I was thinking that it would fail because there doesn't appear to be any transpose rule for reduce_sum, but it doesn't seem that Autodidax got that far. What I was actually trying to do was see how Autodidax formulated the transpose rule for sum, because if you support vmap + arbitrary dims to reduce on it gets pretty complicated.

**Comment by mattjj** [comment]
Thanks for finding this! (And I'm glad you're looking at Autodidax!) I'll fix it.

But in the meantime maybe take a look at [JAX's transpose rule for `reduce_sum`](https://github.com/google/jax/blob/main/jax/_src/lax/lax.py#L3560-L3566) if you haven't already. It's basically just a call to broadcast. What complexity do you have in mind?

**Comment by mattjj** [comment]
On the off chance it's useful, `broadcast_in_dim` can be implemented in [a few lines of NumPy like this](https://github.com/google/jax/blob/c35a3ca0feb0cae5fca5ce3407ce38326c96d932/jax/_src/lax_reference.py#L242). We handled `np.sum` directly in the original Autograd [this way](https://github.com/HIPS/autograd/blob/01eacff7a4f12e6f7aebde7c4cb4c1c2633f217d/autograd/numpy/numpy_vjps.py#L297-L300) with a [helper](https://github.com/HIPS/autograd/blob/01eacff7a4f12e6f7aebde7c4cb4c1c2633f217d/autograd/numpy/numpy_vjps.py#L274-L285).

**Comment by mattjj** [comment]
The main problem with Autodidax here is just a bad error message. The assertion failure means that the `in_axes` specification doesn't match the provided argument tuple. In this case, it's because Autodidax's vmap doesn't have in_axis/out_axis tree prefix support, and so `in_axes` needs to be a tuple corresponding to the argument tuple. That is, if we pass `in_axes=(0,)` then the issue goes away. Note that all the other calls to `vmap` in the file pass an `in_axes` which is a tuple rather than an integer.

However, if we fix that it runs into a real bug!

**Comment by mattjj** [comment]
After #9909 this works in Autodidax:

```python
def simple(a):
  b = a
  t = a + b
  return t * b

def f(a):
  L0 = reduce_sum(simple(a))
  return L0

def g(a):
  dL0_da = vmap(grad(f), in_axes=(0,))(a)
  L1 = reduce_sum(dL0_da * dL0_da)
  return L1

print(grad(g)(np.random.normal((2,4))))
```

Autodidax doesn't have any tests though, so it probably has bugs.

**Comment by mattjj** [comment]
Here's [the transpose rule for `reduce_sum`](https://github.com/google/jax/pull/9909/files#diff-bda36e5567d146410fb8b82f722eba347827bb6faae605b5e87f3a32130f3c99R2567-R2570) in that commit.

**Comment by ezyang** [comment]
Thanks a lot!
