### ISSUE TITLE
rocm docker image jax build failure v2

### ISSUE THREAD

**Issue by brettkoonce** [google/jax#9878]
@reza-amd thanks again for looking into #9864!

When building the docker image, things run further now (eg jax compiles cleanly), but on the last step I get this message:

>  ERROR: jaxlib-0.3.1-cp38-none-manylinux2010_x86_64.whl is not a supported wheel on this platform.

and build process fails (eg no output image).  Thanks in advance for your advice!

**Comment by reza-amd** [comment]
Hi @brettkoonce, could you please remove all the ```.whl``` files in your ```./dist``` folder and repeat the build process.

**Comment by brettkoonce** [comment]
@reza-amd you are indeed correct, i had a bad cache!  i got jax working and am currently training a test network!
