### ISSUE TITLE
Add jax.scipy.linalg.eigh_tridiagonal to document

### ISSUE THREAD

**Issue by YouJiacheng** [google/jax#9885]
Just let users know this algorithm has been officially implemented.
I hope others can avoid wasting time like me:
> I check the document and do not find `eigh_tridiagonal`, thus I migrate tensorflow's implementation by myself. When I start to compare my code against `jax.scipy.linalg.eigh`, I suddenly find that there is `eigh_tridiagonal`!!(Thanks to vscode's auto-complete)😭😭😭😭

**Comment by jakevdp** [comment]
Thanks for flagging this! The readthedocs jobs are stalling currently, but once the CI catches up you should see this listed at https://jax.readthedocs.io/en/latest/jax.scipy.html

**Comment by jakevdp** [comment]
Looks like it's live now - thanks!
