### ISSUE TITLE
missing jaxlib minimum version requirement in conda meta.yaml

### ISSUE THREAD

**Issue by pdemarti** [google/jax#9963]
## Overview

After updating `jax` to the current latest on `conda-forge` (`0.3.0`), we get a `RuntimeError` during import.
Indeed, `jax=0.3.3` depends on `jaxlib>=0.3.0` but doesn't say so in the `conda` requirements.

## Steps to reproduce:

```shell
# check that jaxlib is unconstrained
conda search -c conda-forge jax --info | grep jaxlib | sort -u
  - jaxlib

# simulate a previous install
conda create -y -n test --force python=3.9
conda activate test
conda install -y -c conda-forge jax=0.3.0 'jaxlib>=0.1.74'
python -c 'import jax'
# no problem
```

But now:

```shell
# update jax
conda install -y -c conda-forge jax
python -c 'import jax'
(...)
RuntimeError: jaxlib is version 0.1.75, but this version of jax requires version >= 0.3.0.
```

**Comment by jakevdp** [comment]
Thanks for the report! The JAX team doesn't actually maintain the conda-forge recipe; I think the appropriate place to raise this issue would be here: https://github.com/conda-forge/jax-feedstock

**Comment by pdemarti** [comment]
Done, thank you. [Here](https://github.com/conda-forge/jax-feedstock/issues/81) is the issue on jax-feedstock.
