### ISSUE TITLE
TPU cannot do simple arithmetic!

### ISSUE THREAD

**Issue by ayaka14732** [google/jax#9973]
I am trying to do simple matrix multiplication on TPU, but it gives a wrong result:

```python
import jax.numpy as np
import numpy as onp

# On CPU
x = onp.array([[0.3744, 0.1656],
               [0.4707, 0.1663]])
y = onp.array([[0.3946, 0.1186],
               [0.1569, 0.3145]])
z = onp.dot(x, y)

# On TPU
x_ = np.asarray(x)
y_ = np.asarray(y)
z_ = np.dot(x_, y_)

print('JAX device:', x_.device())

# Compare
print('CPU result:', z)
print('TPU result:', z_)
assert np.allclose(z, z_)
```

Output:

```
JAX device: TPU_0(process=0,(0,0,0,0))
CPU result: [[0.17372088 0.09648504]
 [0.21183069 0.10812637]]
TPU result: [[0.17405128 0.09669876]
 [0.21180916 0.10805416]]
Traceback (most recent call last):
  File "/home/ayaka/main.py", line 21, in <module>
    assert np.allclose(z, z_)
AssertionError
```

Manual calculation:

0.3744 * 0.3946 + 0.1656 * 0.1569 = 0.13732088

So the result on CPU is correct, while the result on TPU is wrong.

Library versions:

```sh
jax                  0.3.4
jaxlib               0.3.2
libtpu-nightly       0.1.dev20220315
```

**Comment by tomhennigan** [comment]
There are two ["sharp bits"](https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html) to be aware of here.

**1. float64** - Your NumPy example is running with f64 inputs/outputs but the JAX version is f32.  See https://jax.readthedocs.io/en/latest/notebooks/Common_Gotchas_in_JAX.html#double-64bit-precision

**2. Compute precision** - XLA supports computing dot product in various precisions. JAX's default precision is optimised for performance and thus has relatively low precision (see #9952). This is typically OK for NN training, but can be the wrong choice for other applications.

You can adjust the precision globally using:

```python
jax.config.update('jax_default_matmul_precision', jax.lax.Precision.HIGHEST)
```

Or you can do so on a per operation basis:

```python
c = jnp.dot(a, b, precision=jax.lax.Precision.HIGHEST)
```

Here is a copy of your example using `HIGHEST` precision on TPU (with f32 inputs) and getting a very close result compared to CPU: https://colab.research.google.com/gist/tomhennigan/69844409e46fd71267acf7479e2ba7f4/example-of-changing-default-precision-in-jax.ipynb

**Comment by ayaka14732** [comment]
Thank you for the explanation!

I am wondering:

1. Are there any research indicating low precision will not affect the model performance? As deep learning models are growing larger and larger, I am thinking that different precision may result to totally different output after many layers of operations.
2. How much training time I can save when using lower precision?

**Comment by mattjj** [comment]
I think we can close this issue, but please let me know if not!
