### ISSUE TITLE
print-debugging lax loops

### ISSUE THREAD

**Issue by samuela** [google/jax#999]
I just turned off `@jit` on one of my functions in order to debug NaNs and added print statements throughout the rest of the code. Something like
```python
def step(i, loop_state):
  print(i, loop_state)
  # do stuff...
  return (new_thingy, new_foobar)

init_val = (init_thingy, init_foobar)
lax.fori_loop(0, epside_length, step, init_val)
```
 I was hoping to get actual values out but instead I get
```
Traced<ShapedArray(int32[]):JaxprTrace(level=0/0)> LoopState(optimizer=_Optimizer(iteration=Traced<ShapedArray(int32[]):JaxprTrace(level=0/0)>,...
```
I'm guessing that lax sends things down to XLA regardless of whether it's operating in jit mode or not. This is kind of annoying for debugging. Is there any way to run these loops in "eager" mode without rewriting the whole thing with native python looping?

**Comment by samuela** [comment]
FWIW my current hack is to create a module `flax`, "fake lax", that just contains the obvious python implementations and then I switch between f/lax as necessary.

**Comment by mattjj** [comment]
Great question! Unfortunately not: lax control flow is done in what we've started referring to as ["initial style"](http://okmij.org/ftp/tagless-final/course/lecture.pdf), which basically means we always trace and stage out the functions you pass to them. I think `flax` is a great idea to work around it!

**Comment by mattjj** [comment]
@dougalm had a design to do everything in "final style", like we do `jit`, but we abandoned it because it's super hard to do with control flow.

**Comment by samuela** [comment]
Mmm, interesting. I guess I don't quite see why switching between "final style" and "initial style" is challenging. For example, what about a `fori_loop` function that defaults to a standard python loop during normal execution, but switches to `lax.fori_loop` when running in jit mode? Detecting whether or not execution is being run jit/non-jit could be done a few ways:
* with context managers and thread-local objects,
* https://docs.python.org/3/library/traceback.html#traceback.extract_stack (kinda hacky),
* by checking whether the arguments -- like `init_val` in `fori_loop` -- are concrete or abstract.

**Comment by mattjj** [comment]
Indeed, we could check whether any transformations are being applied to the loop and switch behavior based on that. (The third option is probably the right idea.)

But it's more complexity, and we try to have really clear justifications for added complexity. In cases like these where a user can easily set up something like `flax` themselves, we tend to encourage that so that we can keep JAX simple, which ultimately means it's more maintainable and agile.

This is kind of an edge case though, since together with #852 we have two reasons to prefer un-transformed loops fall through to Python implementations (namely debugging and op-by-op performance).

**Comment by samuela** [comment]
Is there any established approach for checking whether values are concrete or abstract? I'm now realizing that I'm going to repeatedly shoot myself in the foot if I don't double check inputs to flax.

**Comment by mattjj** [comment]
You can try forcing them to concrete values, as in:

```
try:
  int(x)
except TypeError:
  # x is abstracted above the concrete level
else:
  # x is concrete, though may still be a Tracer (e.g. for forward-mode autodiff)
```

**Comment by samuela** [comment]
I see. Although that doesn't seem to work for general pytrees (tuples, dicts, etc).

**Comment by mattjj** [comment]
Also I just realized that you'll get a TypeError if you pass a non-scalar concrete ndarray into `int`. And it'd be nice not to do any real work (e.g. FLOPs or device transfers) to check this, though right now that means using an internal API.

In the context of this thread, maybe the right thing to do is to check `isinstance(x, core.Tracer)`, and to make it work on pytrees just use the functions in `tree_util` like `tree_all` or `tree_reduce` together with `tree_map`.

**Comment by samuela** [comment]
So this issue came back into my life today as I realized that lax loops is essentially the same as `jit`ing code. In my particular use case I'm implementing reinforcement learning algorithms that go back-and-forth between running a physics simulator and calculating gradients in a loop. Previously I was implementing the physics in JAX and therefore could wrap everything in a `lax.while_loop`, effectively `jit`ing the entire process. However more serious physics simulators (mujoco, bullet, etc) are certainly not jax-friendly, and therefore I can't `jit` the entire thing. But I also can't use a `lax.while_loop` either! That means that now I have a function that has to include logic for switching between lax and non-lax loops.

To be more precise what was once simply:
```python
def run_episode(env: Env, gamma: float, ...):
  def step(loop_state: LoopState):
    new_state = physics_sim(loop_state)
    stuff = ddpg_step(new_state, loop_state)
    return LoopState(new_state, stuff, ...)

  init_val = LoopState(...)
  return lax.while_loop(lambda ls: lax.bitwise_not(ls.done), step, init_val)
```
Now has to be able to switch between `lax.while_loop` and a native python loop, producing a monstrosity something like this:
```python
def ddpg_episode(
    env: Env,
    gamma: float,
    lax_mode: bool,
    ...
):
  def step(loop_state: LoopState):
    new_state = physics_sim(loop_state...)
    stuff = ddpg_step(new_state, loop_state...)
    return LoopState(new_state, stuff...)

  init_val = LoopState(...)

  if lax_mode:
    return lax.while_loop(lambda ls: lax.bitwise_not(ls.done), step, init_val)
  else:
    val = init_val
    while not val.done:
      val = step(val)
    return val
```

**Comment by jakevdp** [comment]
Seems like this question has been answered; closing.
