### ISSUE TITLE
vjp TypeError on weakly typed cotangents

### ISSUE THREAD

**Issue by eelregit** [google/jax#9994]
I don't know if this is actually a bug, but was suprised that TypeError is raised if I pass 1 as cotangent to vjp.

```python
import jax
import jax.numpy as jnp

print(jax.__version__)  # 0.3.4

def f(x):
    return x.sum()

out, f_vjp = jax.vjp(f, jnp.ones(5, 'f2'))
f_vjp(1.)  # TypeError: Type of cotangent input to vjp pullback function (float16) is not the
           # expected tangent type (float32) of corresponding primal output with dtype float32.
f_vjp(jnp.array(1., 'f2'))  # this works
```

**Comment by jakevdp** [comment]
Thanks for the report - indeed we don't do any type promotion at this level (even for weakly-typed values) so you need to ensure the inputs to `f_vjp` strictly match the expected types.

This is something we may revisit in the future though.

**Comment by jakevdp** [comment]
I think this is not something we're going to change – at the level of `jax.vjp`, we will not do implicit type promotion for inputs.
